### ISSUE TITLE
Interactive window debug test is consistently failing

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10496] opened 2022-06-18 00:13 UTC
Error: FAILED TEST NAME: Interactive Window Debugging Debugging with VSCodePythonDebugger Debug a cell from a python file
Code lens with command jupyter.debugcell not found
Error: Code lens with command jupyter.debugcell not found
    at Timeout.<anonymous> (src/test/common.ts:56:20)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

From this run here:
https://github.com/microsoft/vscode-jupyter/runs/6944057287?check_suite_focus=true

Screenshot looks like code lenses never activate:
![image](https://user-images.githubusercontent.com/19672699/174414416-24c997cb-a544-4d20-8d74-1baed4d2166e.png)

Maybe we can change the test to just call the code lens provider directly? We don't need to verify code lenses are working in VS code, we just want to use the command that it puts up.

**Comment by DonJayamanne** [comment] 2024-12-12 23:37
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11917

**Closed by DonJayamanne** 2024-12-12 23:37 UTC
Labels: debt, interactive-window-debugging, flaky test
