### ISSUE TITLE
Debug Console flooded with TypeErrors for .ping

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9786] opened 2022-04-26 17:34 UTC
Testing #9767

<img width="1807" alt="image" src="https://user-images.githubusercontent.com/812783/165359150-21887b2a-e0cb-463b-8cf0-50bef40af786.png">

Looks like this is just the keep alive function? Didn't see an actually issue from this.

**Comment by rchiodo** [comment] 2022-04-26 17:42
Dupe of #9765

**Closed by rchiodo** 2022-04-26 17:42 UTC
Labels: needs-triage
