### ISSUE TITLE
Inconsistent IntelliSense behavior in notebooks and py files

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#8907] opened 2022-02-01 23:01 UTC
Version: 1.64.0-insider (user setup)
Commit: 9afbea7caab9dd06592ddd98aa4161b43b126d3f
Date: 2022-01-06T05:15:07.481Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

1. in a Jupyter notebooks file, connect to a kernel.
2. then type in anywhere in the notebook:
import numpy as np
np.random.randint()

Notice no DocString pops up. On mouse hover, it shows up but looks and behaves differently from the py file:

In notebooks
![image](https://user-images.githubusercontent.com/26419852/152065843-f3e1be5d-ec92-4132-be73-e357ddac046c.png)

In py file (and in notebooks when no kernel is connected):
![image](https://user-images.githubusercontent.com/26419852/152065885-e19bf8fe-2d21-45bb-9cc4-44121d41f11b.png)

**Comment by rchiodo** [comment] 2022-02-01 23:08
My guess is that our dupe filtering for pylance isn't picking pylance items instead. Our kernel completions are trumping the pylance ones.

**Comment by rchiodo** [comment] 2022-02-01 23:09
I think VS code eliminates duplicates itself, so ours might have higher priority than Pylances.

**Comment by greazer** [comment] 2022-06-08 06:26
I'm seeing identical behavior in the last stable release of VS Code, Pylance, Jupyter.

**Comment by rchiodo** [comment] 2022-06-08 16:33
I'm not sure why you closed this? It's a regression from 3 months ago?

**Closed** 2022-06-09 20:42 UTC
Labels: bug, notebook-intellisense, nb-golden, triage-needed

**Comment by amunger** [comment] 2022-06-29 20:49
the parameter highlighting is still different between the two, but everything else seems consistent
