### ISSUE TITLE
problem about jupyter sidecar support

### ISSUE THREAD

**Issue by abcdehc** [microsoft/vscode-jupyter#7881] opened 2021-10-11 06:34 UTC
## Environment data

-   VS Code version: 1.60.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.10.1317843341
-   OS (Windows | Mac | Linux distro) and version: windows10x64,21H1
-   Python and/or Anaconda version: python3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local(3.0.16)

## Expected behaviour

i try to use sidecar to create a sidecar to show ipyleaflet map

## Actual behaviour

but i got an error:
控件需要从第三方网站下载支持文件。（加载错误 @jupyter-widgets/jupyterlab-sidecar:1.1.0）。——from Jupyter(Extension)
but i check that sidecar newest version is 0.5.1
https://pypi.org/project/sidecar/

## Steps to reproduce:

```
from ipyleaflet import (
    Map,
    Marker, MarkerCluster, Icon, MeasureControl,
    TileLayer, ImageOverlay,
    Polyline, Polygon, Rectangle, Circle, CircleMarker,
    AntPath,
    Popup,
    GeoJSON,
    DrawControl,
    basemaps,
    AwesomeIcon,
    LayersControl,
    Heatmap,
    FullScreenControl
)
from ipywidgets import HTML, Button, IntSlider, IntText, Output

center = [35,108]
zoom = 14

m = Map(center=center, 
        zoom=zoom, 
        scroll_wheel_zoom = True,
        basemap=basemaps.Esri.WorldImagery)

measure = MeasureControl(
    position='bottomleft',
    active_color = 'orange',
    primary_length_unit = 'kilometers'
)

m.add_control(FullScreenControl())
from sidecar import Sidecar
s = Sidecar(title="My map")
with s:
    display(m)
```

## Logs

Error 2021-10-11 14:31:26: Widget load failure 加载错误 @jupyter-widgets/jupyterlab-sidecar:1.1.0。需要连接互联网才能加载第三方控件。 {
  className: 'SidecarModel',
  moduleName: '@jupyter-widgets/jupyterlab-sidecar',
  moduleVersion: '1.1.0',
  cdnsUsed: false,
  isOnline: false,
  timedout: false,
  error: {}
}

**Comment by DonJayamanne** [comment] 2021-10-11 21:59
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1120

**Closed by DonJayamanne** 2021-10-11 21:59 UTC
Labels: enhancement, ipywidgets
