### ISSUE TITLE
Reduce vsix size by removing redundant files, source map and typings

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4551] opened 2021-01-28 22:27 UTC
## Environment data

-   VS Code version: 1.52-Insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2021.1.499599561-dev
-   OS (Windows | Mac | Linux distro) and version: macOS
-   Python and/or Anaconda version: 2.7.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

The vsix is currently 25MB, which is pretty large compared to other extensions or VS Code itself (~70MB on Windows). After taking a look at what are bundled into the vsix, I found that

* Three copies of vendor renderers (`datasource.bundle`, `geojson`, `vega`, `nteract`, etc). Each copy is around 7.5MB
* Multiple copies of `require.js` (note that VS Code renderer ships with AMD loader)
* Tens of MB source map files, which are not necessary for release

By removing them, the vsix can go down to 16MB (64%), though it's still large, but it's much better than before.

**Comment by greazer** [comment] 2021-08-08 17:43
Basically a dupe of #5870.

**Comment by rchiodo** [comment] 2021-10-18 22:45
This should be completed. Current size is 12MB

**Closed by rchiodo** 2021-10-18 22:45 UTC
Labels: perf, debt, engineering, issue_grooming_rich
