### ISSUE TITLE
Native Notebooks - Stop execution (cell and kernel level) don't work

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#4369] opened 2021-01-13 17:39 UTC
1. Run any long running cell
2. Try to stop the execution (either at the cell level or notebook kernel level) 

Nothing happens, have to close and reopen the notebook

**Comment by DonJayamanne** [comment] 2021-01-13 20:45
@claudiaregio please could you provide a sample code to replicate this issue.
If possible, try to provide a simple sample so we can test/setup easily at our end.

Also, please confirm this is not an issue when you try the same in classic Jupyter (browser).

**Comment by rchiodo** [comment] 2021-01-14 18:53
This is expected (as evidenced here:)
https://github.com/ipython/ipython/issues/3400

However we can make native notebooks automatically restart if they take too long like we do for the old editor.

I'll also add more logging to make sure we're interrupting if this comes up again.

**Comment by greazer** [comment] 2021-01-20 18:45
Looks like this belongs in validate.

**Comment by DonJayamanne** [comment] 2021-01-22 23:35
I couldn't replicate the original issue, hence leaving for someone else to validate.

**Comment by rchiodo** [comment] 2021-01-22 23:58
To repro you have to run with debug bits and uninstall the json rpc stuff. Then the extra layer for interrupt doesn't work.

**Comment by claudiaregio** [comment] 2021-01-23 23:33
I have had all diary study participants mention this same behavior so far and had it happen again during a wrap up interview. Can pull the footage to share on Monday.

**Comment by joyceerhl** [comment] 2021-01-28 06:28
This is still a problem at least on Windows 

![image](https://user-images.githubusercontent.com/30305945/106099066-eecfa280-60ee-11eb-9ed8-b420414344d9.png)

![image](https://user-images.githubusercontent.com/30305945/106099092-fd1dbe80-60ee-11eb-9b29-6af252762990.png)

**Comment by rchiodo** [comment] 2021-01-28 17:17
Joyce, it looks you just validated it. That's the intended behavior when the interrrupt fails. Jupyter is not guaranteed to interrupt so we ask for a restart if it doesn't work.

**Comment by rchiodo** [comment] 2021-01-28 17:22
For me this always happens with a sleep if you don't have the json rpc library installed (dev bits). But it can happen for other code as well. See the ipython bug:
ipython/ipython#3400

**Comment by joyceerhl** [comment] 2021-01-28 18:06
Oh, good. Closing as validated then :)

**Closed by joyceerhl** 2021-01-28 18:06 UTC
Labels: bug, internal contributor
