### ISSUE TITLE
vscode jupyter outputs garbled Russian symbols

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/vscode-jupyter#11437] opened 2022-09-23 02:06 UTC
As the title says, garbled characters when outputting in jupyter

![image](https://user-images.githubusercontent.com/108051416/191880108-149d9938-e4b2-4e89-afd0-ce19efedfe76.png)

System language is russian, cyrillic symbols are not rendered correctly. Default code page in cmd.exe is 866. Folders and files are named in english. –

**Comment by amunger** [comment] 2022-09-23 18:35
@xxc-zsz  what's the editor font you are using? or the notebook output font if you have that set as well

**Comment by Fan4Metal** [comment] 2022-09-24 08:30
> @xxc-zsz what's the editor font you are using? or the notebook output font if you have that set as well

I have the same issue. I use Hack font for my outputs. And russian symbols are rendered fine in **python** output, problem is only with **shell** commands. VS Code terminal also works fine.
I think the problem is cmd.exe but not powershell is used as a shell for such code.

**Comment by xxc-zsz** [comment] 2022-09-28 07:55
@amunger editor font: Consolas, 'Courier New', monospace

**Comment by best-tech** [comment] 2022-10-10 22:41
vote +1

**Comment by amunger** [comment] 2022-12-08 00:01
do you know which symbols are expected there, or any other examples? I can run a cell with `print('₽')` and it prints correctly - does that work for you with symbols that aren't appearing in this output?

**Comment by Fan4Metal** [comment] 2022-12-08 13:39
> do you know which symbols are expected there, or any other examples? I can run a cell with `print('₽')` and it prints correctly - does that work for you with symbols that aren't appearing in this output?

Yes, it should be result of `dir` command in shell (cmd.exe). All python cells outputs (like `print('йцуке')`) work fine. I think the problem is cmd.exe doesn't use utf-8, but WINDOWS-1251 or CP-866.

I've just tried the same command in jupyterlab and the problem is there too. So I assume it is ipykernel problem.

**Comment by amunger** [comment] 2022-12-08 17:59
ah, that makes sense, and I can see a similar repro by simply executing `!echo ₽`. (also repros in the jupyter web UI)
So we're never seeing the correct character in our extension.

As mentioned in the issue you linked, I would think this is more likely an issue in Jupyter notebooks. 
Closing as external

**Closed by amunger** 2022-12-08 17:59 UTC
Labels: bug, info-needed, notebook-output
