### ISSUE TITLE
Kernel issues with Python 2.7

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4680] opened 2021-02-05 21:15 UTC
## Environment data

-   VS Code version: 1.53 Insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2021.1.499599561-dev
-   Python Extension version (available under the Extensions sidebar): 2.7
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 2.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

During the endgame, we used Jupyter extension to test the rich diff editor and verify issues with the native editor however we found it hard to get the execution running properly with Python 2.7:

* `!pip install plotly` take long to finish without any output (it might take a few minutes)
* `Timed out waiting to get a heartbeat from kernel process`

**Comment by rchiodo** [comment] 2021-02-09 21:10
I don't believe we're supporting 2.7 anymore?

**Comment by greazer** [comment] 2021-02-11 01:20
We don't intend to, however, the answer is never that simple. For native notebooks, let's wait to get more upvotes or feedback.

**Comment by DonJayamanne** [comment] 2021-11-11 22:57
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5699

**Closed by DonJayamanne** 2021-11-11 22:57 UTC
Labels: bug, notebook-kernel
