### ISSUE TITLE
Markdown tables are not rendering as expected

### ISSUE THREAD

**Issue by cobey** [microsoft/vscode-jupyter#16043] opened 2024-09-13 22:12 UTC
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

## Steps to Reproduce Issue

1. Create a new ipynb in VS Code
2. Create a new markdown cell
3. Add the following table to the markdown cell

```
| Hey   | Hello | Hi    |      |
| ----- | ----- | ----- | ---- |
| Hello | Hi    | Hey   |      |
| Hi    | Hey   | Hello |      |
```
4. "Execute" cell

## Expected Results

The table renders as a markdown table

## Actual Results

Empty cell

### VS Code Version

1.94.0

### Jupyter Extension Version

2024.8.1

### Jupyter logs

Visual Studio Code - Insiders (1.94.0-insider, undefined, desktop)
Jupyter Extension Version: 2024.8.1.
Python Extension Version: 2024.15.2024091301.
Pylance Extension Version: 2024.9.100.
Platform: win32 (x64).
Temp Storage folder ~\AppData\Roaming\Code - Insiders\User\globalStorage\ms-toolsai.jupyter\version-2024.8.1
No workspace folder opened.

### Coding Language and Runtime Version

Python 3.12.6

### Language Extension Version (if applicable)

2024.15.2024091301

### Running Jupyter locally or remotely?

Local

**Comment by cobey** [comment] 2024-09-23 19:54
This is no longer happening as of `v2024.9.2024092001`, leaving open in case there is still interest in understanding and/or if it happens for others

**Comment by magg-data** [comment] 2024-10-22 22:18
It is an issue for me:

Version: 1.94.2
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-47-generic

**Comment by DonJayamanne** [comment] 2024-12-16 22:09
Closing as a duplicate of https://github.com/microsoft/vscode/issues/236287

**Closed by DonJayamanne** 2024-12-16 22:09 UTC
Labels: bug, triage-needed
