### ISSUE TITLE
Variable viewer: Horizontal padding prevents scroll bars from reaching edges

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10242] opened 2022-06-01 14:50 UTC
Testing #10170

<img width="387" alt="Screen Shot 2022-06-01 at 7 48 34 am" src="https://user-images.githubusercontent.com/2193314/171433283-ab29036e-7978-4f1e-a392-bc276dfd897f.png">

Caused by the margin on `.variable-viewer` and `variable-explorer-data-grid`.

**Comment by sadasant** [comment] 2022-07-06 20:51
Hello @tyriar!

I'm finally able to pick up this issue. Thank you again for reporting it. Since some time has passed, and my team has worked relentlessly on upgrades of many kinds, I'm not sure if I can reproduce this issue. I have not been able to reproduce it so far.

Here's what I have done:

- On the web debugging of VSCode, as well as on insiders.vscode.dev:
  - I have made a new Jupyter notebook with the script I'm adding after this list.
  - I have connected to a remote Jupyter server.
  - I have run the cell with the script.
  - I have opened the variable viewer.
  - I have stretched and enlarged the window, to see how that affects the scrolling in the variable viewer.

Script:

```python
a = [1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3,1,2,3]
b = a
c = a
d = a
e = a
f = a
g = a
h = a
i = a
j = a
k = a
l = a
m = a
print(a)
```

The scroll bars in the variable viewer do go all the way to the end, both horizontally and vertically, even if I stretch or enlarge the window.

Please let me know if I'm doing something different than you. If you have the time, please help me confirm this is fixed!
If we can close this issue, please let us know.

Any feedback appreciated.

**Comment by Tyriar** [comment] 2022-07-06 21:35
If the gap is no longer on the right side you can close this off

**Closed as completed** 2022-07-06 22:04 UTC
Labels: papercut :drop_of_blood:, variable-explorer
