### ISSUE TITLE
Debugging requires ipykernel after some time when using PyImageJ 

### ISSUE THREAD

**Issue by fschiffers** [microsoft/vscode-jupyter#13227] opened 2023-03-30 13:25 UTC
## Environment data

-   VS Code version: 1.76.2
-   Jupyter Extension version: v2023.2.1200692131
-   Python Extension version): v2023.4.1
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: Conda 23.1.0 ( base: 3.10.0, myenv: 3.8.16)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...):  conda
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

Debugging in Jupyter should work all the time ( Ctrl + Shift + Alt + Enter) when using PyImageJ

## Actual behaviour

![image](https://user-images.githubusercontent.com/13521689/228846170-449ef594-4427-48e6-b31c-b1c0a7d93cf8.png)

![image](https://user-images.githubusercontent.com/13521689/228847245-7a8c9dc3-159f-41ba-88d1-b3ea1244e52f.png)

## Steps to reproduce:

1. Checker if Debugging works:
Debugging works well here
![image](https://user-images.githubusercontent.com/13521689/228849631-c8dde9f1-6138-4cc5-bb25-810c2da4c34d.png)

2. Open up the ImageJ Interface (works)
![image](https://user-images.githubusercontent.com/13521689/228849970-870365b4-177b-4424-9218-e5e9ead21428.png)

3. Try to Run the Debugging Cell (doesn't work)

![image](https://user-images.githubusercontent.com/13521689/228850197-64da21ab-f365-40ff-94ae-2362d4d4a36c.png)

4. Try to execute in Non-Debug Mode (Runs, but doesn't print anything anymore)
![image](https://user-images.githubusercontent.com/13521689/228850378-13fd6653-d98c-46fb-a129-c4ad371229a5.png)

`def test_function_for_debug():
    print("test")

import imagej
#ij = imagej.init('sc.fiji:fiji',headless=False)
#ij = imagej.init(headless=False)

ij = imagej.init('sc.fiji:fiji', mode='interactive')
ij.ui().showUI()

test_function_for_debug()`

Please let me know if you need any logs or other information. I've seen this behavior now on several Windows PCs.

**Comment by roblourens** [comment] 2023-03-30 23:53
I wonder if this is the same as https://github.com/microsoft/vscode-jupyter/issues/12801? You can try again after we merge the PR...

**Comment by ctrueden** [comment] 2023-07-06 20:41
The issue is that one of PyImageJ's dependencies [overrides `sys.stdout`](https://github.com/scijava/scyjava/blob/1.9.0/src/scyjava/_script.py#L54-L55), but so does the ipykernel, and the two clash somehow. Even though we are wrapping the old `stdout`, passing along output to the wrapped one (which in this case is an ipykernel thing), it still somehow stops receiving the messages in the notebook window.

Anyway, this issue is not specific to vscode-jupyter—it happens in vanilla Jupyter notebook as well—so I suggest closing this issue.

**Comment by DonJayamanne** [comment] 2023-12-13 01:36
> Anyway, this issue is not specific to vscode-jupyter—it happens in vanilla Jupyter notebook as well—so I suggest closing this issue.

Closing this issue, thanks

**Closed by DonJayamanne** 2023-12-13 01:36 UTC
Labels: bug, notebook-debugging
