### ISSUE TITLE
PATH returned by interactive session is different from iPython launched from terminal

### ISSUE THREAD

**Issue by bernalde** [microsoft/vscode-jupyter#5041] opened 2021-03-05 00:24 UTC
## Environment data

-   VS Code version: 1.54
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): v2021.2.582707922
-   OS (Windows | Mac | Linux distro) and version: 5.4.72-microsoft-standard-WSL2  Description:    Ubuntu 20.04.1 LTS Release:        20.04
-   Python and/or Anaconda version: Python 3.8.5 conda 4.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: WSL

## Expected behaviour

The PATH used by the Jupyter session in the interactive window is not the same as the one from an iPython session ran from the terminal. In particular, the updates to the PATH in the .profile file are not included, although other environment variables in that file make it to the Jupyter terminal session (verified via %env)

It would be expected that the same PATH is used in both cases.

## Actual behaviour

Some of the PATH entries are not included in the environment variable. Most notably, `/snap/bin:`, `/home/USER/anaconda3/condabin`, and all definitions of PATH in .profile are missing.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open an interactive window and type `!echo $PATH`, that is different from it being obtained either by directly in the terminal (using the correct conda environment) or even using an ipython session as follows:
```
(environ) USER@computer:~$ ipython
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: !echo $PATH
```

which is the same thing as expected (full PATH from .profile).

**Comment by DonJayamanne** [comment] 2021-03-12 20:08
Thanks for filing this issue.
I believe the problem is due to the fact that VS Code doesn't inherit those environment variables, when the terminal is opened (the shell) might be reading the profile script to initialize the variables.
As for VS Code, its launched differently and if it doesn't inherit the variables, then the processes launched from VS Code (like extensions) wouldn't inherit them either.

**Comment by DonJayamanne** [comment] 2021-03-12 20:10
I think its because VS Code doesn't launch with the varaibles from the login scrip `.profile` and shells do.
Will look into this.

**Comment by RileyMShea** [comment] 2021-03-16 19:34
@DonJayamanne if it helps I've only encountered this on systems with a bash shell.  I run a zsh shell and haven't experienced it but my coworkers have been plagued by it since the ~ the last monthly update of vscode.

**Comment by DonJayamanne** [comment] 2022-04-13 23:01
@RileyMShea Are you or your coworkers still running into issues. If so, please could you file an issue with the relvant information.

**Comment by DonJayamanne** [comment] 2022-04-13 23:02
@[bernalde](https://github.com/bernalde) Aside from the fact that the PATH value is not the same, are you running into any issues as a result of this?

**Comment by jcjaskula** [comment] 2022-04-24 12:36
I ran into issues as a result of this. I have python scripts that eventually call subprocess.Popen() as far as I recall and hence return errors because my personalized PATH (from .bash_profile on MacOS) is not updated. 
What I noticed is:
- Everytime I restart my kernel, PATH is modified with something like "$VIRTUAL_ENV/__VENV_BIN_NAME__:$PATH" (virtual environment activation). This is creating a very long PATH with mainly $VIRTUAL_ENV/__VENV_BIN_NAME__. 
- the $PATH in the previous line seems to be the PATH at the environment creation. I have several virtual environments and the most recents have my current path while older ones seem to have a previous version of PATH.

**Comment by DonJayamanne** [comment] 2022-05-03 19:49
> I have several virtual environments and the most recents have my current path while older ones seem to have a previous version of PATH.

I'm sorry, but I'm not quite following this issue.
Are you saying that older versions of VS Code had different paths and things are ok now.
Please could you provide a few samples.

**Comment by jcjaskula** [comment] 2022-05-07 01:15
Sorry if I was confusing. I'm only talking about different virtual environments but the same version of VS Code. 
Here is a series of steps I could follow to reproduce my issue. This was done with the latest version of VS Code + the jupyter extension. I'm on MacOS and I set up bash as my default shell through System Preferences/Users & Groups. Hopefully it will make sense. 

```
> echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
> python3 -m venv ~/.venvs/my_first_env

# Open vscode (not from command line)
# Create notebook.ipynb 
# Choose my_first_env for my kernel
# Execute !echo $PATH
# ~/.venvs/my_first_env/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

# Close vscode

> echo PATH=/opt/homebrew/bin:$PATH >> ~/.bash_profile 
> source ~/.bash_profile
> echo $PATH
/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
> python3 -m venv ~/.venvs/my_second_env

# Open vscode
# Open notebook.ipynb 
# Choose my_second_env for my kernel
# Execute !echo $PATH
# ~/.venvs/my_second_env/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

# Choose my_first_env for my kernel
# Execute !echo $PATH
# ~/.venvs/my_first_env/bin:~/.venvs/my_first_env:bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin```

**Comment by DonJayamanne** [comment] 2022-05-16 00:25
@jcjaskula are you on a Mac M1 (Apple silicone chip) by anychance?

**Comment by DonJayamanne** [comment] 2022-08-14 20:48
@jcjaskula Please could you test this in the latest version of VS Code & Jupyter Extesnion, I believe we've addressed this in the new version.

**Comment by DonJayamanne** [comment] 2022-08-22 02:37
Closing this for now, if the problem persists, please feel free to re-open this issue or please create a new one and i'll look into that.

**Closed by DonJayamanne** 2022-08-22 02:37 UTC
Labels: bug, interactive-window
