### ISSUE TITLE
File upload widget crashes extension host when using non-jupyter (zmq)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#10525] opened 2022-06-21 22:09 UTC
# Cell 1
```python
import ipywidgets as widgets
uploader = widgets.FileUpload()
display(uploader)
```
# upload something...

# Cell 2
```python
# once a file is uploaded, use the `.value` attribute to retrieve the content:
uploader.value
```

I guess this works for users today when using non-zmq. 
If we ship zmq for Mac m1 & other linux distros, then this would be a bad regression (bringing down the entire extension host)

**Comment by rchiodo** [comment] 2022-06-23 20:18
Dupe of #10386

**Closed by rchiodo** 2022-06-23 20:18 UTC
Labels: bug, zmq, upstream-zmq
