### ISSUE TITLE
Opening cell output in text editor fails after rerun

### ISSUE THREAD

**Issue by lhic** [microsoft/vscode-jupyter#13980] opened 2023-07-25 18:09 UTC
Type: <b>Bug</b>

## Expected behaviour

Opening the cell output in a text editor opens output in a new tab

## Actual behaviour

Opening output of a cell that was ran twice produces an error.
![image](https://github.com/microsoft/vscode-jupyter/assets/6554290/ba76a351-6f7b-450a-b455-b96404828ebf)

## Steps to reproduce:

1. Run a cell with long output (e.g. `print('a\n' * 100)`)
2. Rerun the cell
3. Click on the "open in a text editor"
4. Error appears: "Unable to resolve text model content for resource vscode-notebook-cell-output:Untitled-1.ipynb?jupyter-notebook#op0e6bcd08-49cc-4e7d-b6ae-407a1a04a123%2Cuntitled"

Extension version: 2023.6.1101941928
VS Code version: Code 1.80.1 (Universal) (74f6148eb9ea00507ec113ec51c489d6ffb4b771, 2023-07-12T17:20:23.298Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|--crash-reporter-id 8b0008c6-65da-4fe5-ae47-e6e4c2477d91|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
89544117:30613380
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30792625
gsofb:30797622
pythonnosmt12:30797651
pythonidxpt:30784022
pythonnoceb:30797650
e537b577:30795824
dsvsc013:30795093
dsvsc014cf:30797590
cmakestatusbarv2:30779594

```

</details>

**Comment by lhic** [comment] 2023-09-04 10:01
I still have the same problem with the latest version (1.81.1). Also, I have no problems with reproducing the problem on different platforms and computers (e.g. I have the same problem on Linux).

Should I provide some additional information about the problem?

**Comment by amunger** [comment] 2023-09-06 15:24
dupe of https://github.com/microsoft/vscode/issues/189673
fixed in insiders and will be released to stable this week

**Closed by amunger** 2023-09-06 15:24 UTC
