### ISSUE TITLE
[Visual Bug] 🐛 tqdm progress bar with leave=False leaves whitespace

### ISSUE THREAD

**Issue by ringohoffman** [microsoft/vscode-jupyter#14759] opened 2023-11-22 01:16 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

https://github.com/microsoft/vscode-jupyter/assets/27844407/175cdf08-330e-4477-abe5-94d29f04c980

The bug isn't observed from the `jupyter` CLI:

https://github.com/microsoft/vscode-jupyter/assets/27844407/504aa6d9-7074-452b-819a-87355db36cc6

---

Someone has submitted a fix to tqdm for it: https://github.com/tqdm/tqdm/pull/1504

Is there anything that VS Code jupyter can do to fix this visual bug in VS Code?

### VS Code Version

Version: 1.84.2 Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e Date: 2023-11-09T10:52:57.054Z (1 wk ago) Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin arm64 23.0.0

### Jupyter Extension Version

v2023.10.1100000000

### Coding Language and Runtime Version

Python 3.9

### Anaconda Version (if applicable)

conda 23.9.0

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment] 2023-11-22 01:53
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/9397

**Closed by DonJayamanne** 2023-11-22 01:53 UTC
Labels: bug
