### ISSUE TITLE
Fail to render LaTeX-based output when viewing function help in Julia

### ISSUE THREAD

**Issue by Neuromancer43** [microsoft/vscode-jupyter#8262] opened 2021-11-14 11:19 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In Julia notebook, we can type "?" in the cell to search the information of functions or classes. A docstring will be displayed in the cell output. 
![image](https://user-images.githubusercontent.com/20223932/141678422-adf432be-476a-4ccc-a7f7-6d462c3611a9.png)

However, in vscode-jupyter, this feature is not well supported. 
![image](https://user-images.githubusercontent.com/20223932/141678482-7525afea-4424-41fe-8257-f9b73210e3be.png)
Rendering of LaTeX failed in the cell output. 

The notebook is runned on a local Julia server, version 1.6.2, not the built-in kernel from VSCode Julia extension. Actually the feature is not supported in if I choose the kernel in Julia Extension. 
  
 

### VS Code Version

1.62.2

### Jupyter Extension Version

v2021.10.1101450599

### Coding Language and Runtime Version

Julia v1.6.2

### Language Extension Version (if applicable)

v1.5.4

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2021-11-18 21:08
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7801

**Closed by DonJayamanne** 2021-11-18 21:08 UTC
Labels: bug, needs-triage
