### ISSUE TITLE
Choosing a kernel should provide a reasonable default language for cells in a new notebook.

### ISSUE THREAD

**Issue by LadyNaggaga** [microsoft/vscode-jupyter#4490] opened 2021-01-25 19:31 UTC
## Environment data

-   VS Code version: 1.53.0-insiders 
-   Jupyter Extension version (available under the Extensions sidebar):v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): Python isn't installed 
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Isn't installed 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A 
-   Jupyter server running: N/A
- .NET Interactive extension: v1.0.207203

## Expected behaviour

Once the user selects the one of a  .Net Interactive kernel is selected from the kernel picker I expect the kernel to be recognize it. This only happens in the initial install of .NET Interactive but, doesn't work in a new instance of VS Code. 

## Actual behaviour

The .NET Interactive kernel isn't recognized in new VS Code instance. The user can select one of the .NET Interactive kernels however, when they hit the run button you are promoted to *"Select a kernel to run the notebook"*

### Opening a New Notebook 
-  Open a new window in VS Code `Ctrl + Shift + N`
- Opened a new notebook - Using the Jupyter 
![image](https://user-images.githubusercontent.com/2546640/105515629-e9172e80-5ca2-11eb-8f1b-5b5f588f721d.png)
- Cell default to a non .NET Interactive kernel 
![image](https://user-images.githubusercontent.com/2546640/105524675-f1c13200-5cad-11eb-8755-59617de785a2.png)
*what kernel is it looking at ?*
- Switching to C# .NET Interactive by clicking on the `c#` label.  .
![image](https://user-images.githubusercontent.com/2546640/105525094-98a5ce00-5cae-11eb-80c3-a55434598e9c.png)
- Selected `C# .NET Interactive` hit run and promoted to select a kernel
![image](https://user-images.githubusercontent.com/2546640/105525650-621c8300-5caf-11eb-9530-1139b31f0c36.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DavidKutu** [comment] 2021-01-25 21:26
Thanks for filing @LadyNaggaga. Currently, that is the expected behavior, selecting the language in a cell does not select the kernel. To select it, please run the command: 'Notebook: Select Notebook Kernel' and select the kernel you want to use.

Does the kernel picker shows your .NET kernel?
Also, what happens if you just create a new notebook and run the first cell? Does the kernel picker appear?

**Comment by DonJayamanne** [comment] 2021-01-25 23:31
@brettfo isn't this a duplicate of https://github.com/microsoft/vscode-jupyter/issues/4423#issuecomment-763246291 & https://github.com/microsoft/vscode-jupyter/issues/4423#issuecomment-763903125

**Comment by DonJayamanne** [comment] 2021-01-26 18:34
@rchiodo @brettfo 
How about the .NET extension chanage the language of the cells when a .NET interactive kernel is selecrted.
This is what we do today. 
* Add handler for notebook kernel selection (`notebook.onDidChangeActiveNotebookKernel`)
* Look for cells in the notebook document & change the language from `C#` to `C# .NET Interact`
	* You can use the VSC API to update the langauages of existing cells
	
Does this work?

**Comment by LadyNaggaga** [comment] 2021-01-26 18:42
Thanks for getting back to me @DavidKutu please find my responses below
> Thanks for filing @LadyNaggaga. Currently, that is the expected behavior, selecting the language in a cell does not select the kernel. To select it, please run the command: 'Notebook: Select Notebook Kernel' and select the kernel you want to use.
> 
> * Does the kernel picker shows your .NET kernel?
Yes, the .NET Interactive Kernel does appear in the language list.  However, when you select C# .NET Interactive for example then hit run the user is promoted to "Select a kernel to run the notebook" but provides no options. 
> * Also, what happens if you just create a new notebook and run the first cell? Does the kernel picker appear? Or does it select a kernel you don't want?
The same thing happens if I open a new notebook in the same new VS Code instance.

**Comment by DavidKutu** [comment] 2021-01-26 19:07
I see @LadyNaggaga. I have another question, on the bottom right of VS code (on the status bar) do you see the .NET kernel selected like this?
 
![image](https://user-images.githubusercontent.com/20347396/105891099-14608d00-5fc5-11eb-92c5-49e3cd77e749.png)

If not, you can click that and this picker should come up:
![image](https://user-images.githubusercontent.com/20347396/105891279-4d006680-5fc5-11eb-8934-18866bb08b88.png)

If nothing comes up in that picker, please try to reinstall the .NET kernel following this instructions:

1. First, make sure you have the following installed:
- The .NET 3.1 SDK (https://dotnet.microsoft.com/download)
- Jupyter. Jupyter can be installed using Anaconda (https://www.anaconda.com/products/individual)

2. Open the Anaconda Prompt (Windows) or Terminal (macOS) and verify that Jupyter is installed and present on the path:
`jupyter kernelspec list`
> python3        ~\jupyter\kernels\python3

3. Next, in an ordinary console, install the dotnet interactive global tool:
`dotnet tool install --global Microsoft.dotnet-interactive`

4. Install the .NET kernel by running the following within your Anaconda Prompt:
`dotnet interactive jupyter install`
> [InstallKernelSpec] Installed kernelspec .net-csharp in ~\jupyter\kernels\.net-csharp
> .NET kernel installation succeeded
> [InstallKernelSpec] Installed kernelspec .net-fsharp in ~\jupyter\kernels\.net-fsharp
> .NET kernel installation succeeded
> [InstallKernelSpec] Installed kernelspec .net-powershell in ~\jupyter\kernels\.net-powershell
> .NET kernel installation succeeded

5. You can verify the installation by running the following again in the Anaconda Prompt:
`jupyter kernelspec list`
>  .net-csharp    ~\jupyter\kernels\.net-csharp
>  .net-fsharp    ~\jupyter\kernels\.net-fsharp
>  .net-powershell ~\jupyter\kernels\.net-powershell
>  python3        ~\jupyter\kernels\python3

Let me know if this works for you.

**Comment by brettfo** [comment] 2021-01-26 21:06
@DonJayamanne We have some unpublished changes that listen for kernel change and if the new kernel is us, then we update the document's allowed languages to our restricted subset of 5.  With a recent change to Insiders that fixed extension activation, the story now is pretty good for us regarding languages, but only if our kernel is selected.  I added a comment to another issue [here](https://github.com/microsoft/vscode-jupyter/issues/4423#issuecomment-767822024) where I discuss how to auto-select our kernel if/when appropriate and some open questions around that experience.

**Comment by joyceerhl** [comment] 2021-04-08 17:01
@brettfo @LadyNaggaga hey team, checking in regarding this issue as it's been a couple months. It sounds like the .NET Interactive extension now selects a default .NET language when the .NET Interactive kernel is selected (and I was able to verify this behavior with v1.0.2207011 of the .NET Interactive extension). Were there any other changes that your team needed from us for this issue to be marked resolved?

**Comment by DonJayamanne** [comment] 2021-04-12 16:16
We're going to have to make changes to the API to make this possible.

* Rather than getting .net to call our API `registerNewNotebookContent`
	* We will query all extensions & check if they contribute to us (read package.json and look for their contributions & update the list of the notebooks in the quick pick
* Modify `CreationOptions.registrations` in `src/client/datascience/notebook/creation/creationOptionsService.ts`
	* Read package.json of other extensions using `vscode.extensions.all.filter(item => item.packageJSON?.contributes?['jupyter.kernels'].....`


```json
contributes: {
  jupyter.kernels: [
    {
      displayName: ".NET Interactive Notebook (C#)",
      kernelId: "dotnet-interactive", // this is how our kernel registers with vscode
      defaultlanguage: "dotnet-interactive.csharp" // this is how our special languages register with vscode
    } ,
    {
      displayName: ".NET Interactive Notebook (F#)",
      kernelId: "dotnet-interactive",
      defaultlanguage: "dotnet-interactive.fsharp"
    }
  ]
}
```

Note sure we need `kernelId` (I'd personally remove that as we don't need it)

**Comment by DonJayamanne** [comment] 2021-04-12 21:36
@DavidKutu Please make note of the changes from `displayName` to `title`

**Closed** 2021-05-03 20:35 UTC
Labels: bug, info-needed
