### ISSUE TITLE
kernel selector does not show full path of the environment

### ISSUE THREAD

**Issue by braindevices** [microsoft/vscode-jupyter#14921] opened 2023-12-15 20:35 UTC
according to [document](https://code.visualstudio.com/docs/datascience/jupyter-kernel-management#_jupyter-kernels)
We should see the full path of the environments.
This is quite important in multi-root workspace. I have a workspace we A, B, C, D 4 different root dirs. Each of them have different venv.

The selector does not show the full path but ./venv/bin/python for all {A,B,C,D}/venv
this is really annoying. I do not know which one is which.

## Environment data

-   VS Code version: 1.85.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1003402403
-   Python Extension version (available under the Extensions sidebar): v2023.22.1
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22.04
-   Python and/or Anaconda version: 3.10.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: N/A

## Expected behaviour

![show full path with ~/](https://code.visualstudio.com/assets/docs/datascience/jupyter-kernel-management/noterbook-kernel-picker.gif)

## Actual behaviour

![image](https://github.com/microsoft/vscode-jupyter/assets/7507440/78e11545-1e91-4ffb-bea1-48d842b7b441)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2023-12-19 02:47
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment] 2024-01-28 14:50
No worries, identified the issue.
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/15066

**Closed by DonJayamanne** 2024-01-28 14:50 UTC
Labels: bug, info-needed, notebook-kernel-picker
