### ISSUE TITLE
Not able to connect to remote juypter lab

### ISSUE THREAD

**Issue by deepcoder** [microsoft/vscode-jupyter#4751] opened 2021-02-10 23:35 UTC
Issue Type: <b>Bug</b>

When specifying url and token for juypter lab server, command fails with error below:
http://192.168.2.242:8000/lab?token=4478f0039b13cbba9cxxxxcczzzzzzzzzzzz

Command 'Jupyter: Specify local or remote Jupyter server for connections' resulted in an error (Running the contributed command: 'jupyter.selectjupyteruri' failed.)

Extension version: 2020.12.414227025
VS Code version: Code - Insiders 1.54.0-insider (40b3204d70a9c72305c613164272175d0b344b5f, 2021-02-10T17:35:33.562Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.11GB free)|
|Process Argv|--crash-reporter-id d133d7c8-580a-45ca-a67d-616a40b299e8|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment] 2021-02-10 23:40
Thanks for the bug but specifying a remote server in insiders is not currently supported. You'll have to use stable for that.

Our next version (coming out shortly) should support it though.

**Comment by rchiodo** [comment] 2021-02-10 23:42
Actually that command should be outside of using the notebook api.

**Comment by rchiodo** [comment] 2021-02-10 23:42
Can you post the contents of the 'Jupyter' output tab to this issue?

**Comment by rchiodo** [comment] 2021-02-11 00:15
Seems like this is a regression. I can repro using jupyterlab. It looks like jupyter lab does not support the contents API.

I get this when making the contents post:
```
[W 2021-02-10 16:11:19.617 LabApp] 405 POST /lab/api/contents/?1613002279513 (127.0.0.1) 41.89ms referer=None
```

**Comment by rchiodo** [comment] 2021-02-11 00:42
Ah yes jupyterlab does not expect a connection for a notebook server at that URI. It removes the ```/lab``` portion.

@deepcoder you can work around this issue by removing lab from the URI you're providing.

So instead of this:

```
http://192.168.2.242:8000/lab?token=4478f0039b13cbba9cxxxxcczzzzzzzzzzzz
```

You can enter this:

```
http://192.168.2.242:8000/?token=4478f0039b13cbba9cxxxxcczzzzzzzzzzzz
```

**Comment by deepcoder** [comment] 2021-02-11 01:47
Hello @rchiodo thanks for your replies. However, I trying to understand them. You first closed my bug by saying that remote jupyter connections are not yet supported in the 'insider' edition of vscode. Then it looks like you reopened it, in your 2nd to last reply you asked me to try the connection command with the 'lab' removed from the URI, I did this and received the same message as shown below. 

In between the two referenced replies, you asked me to 'Can you post the contents of the 'Jupyter' output tab to this issue?'
I don't know where to find this, and I don't see any additional information other than what I shared. If you can direct me to instruction on how to get further debugging information, I will share it. I did try 'toggle developer tools' in vscode, but it did not appear to show me any more information. Thx.

```
http://192.168.2.242:8000/?token=220bfxxxxxxxx0cfbe6c367c


Command 'Jupyter: Specify local or remote Jupyter server for connections' resulted in an error (Running the contributed command: 'jupyter.selectjupyteruri' failed.)

```

**Comment by rchiodo** [comment] 2021-02-11 17:13
Yes if you can include the 'jupyter' output. That would be here:

![image](https://user-images.githubusercontent.com/19672699/107672035-51758200-6c49-11eb-96e3-2a2200ceb6c4.png)

This panel opens if you click on the 'View | Output' menu item.

Additionally if you can set this setting as well, that would produce more output:
![image](https://user-images.githubusercontent.com/19672699/107672146-74079b00-6c49-11eb-98b1-94d7acfdddee.png)

**Comment by rchiodo** [comment] 2021-02-11 17:36
My guess for your issue (pending what the output shows) is this one:
https://github.com/microsoft/vscode-jupyter/issues/4451

This happens if you try using remote in the insiders version.

**Comment by deepcoder** [comment] 2021-02-11 20:24
Yes I see a simillar error message as in the issue you referenced:

```
[2021-02-11 12:21:26.200] [exthost] [error] TypeError: s.authentication.getPassword is not a function
```
I am not sure how to test any of the updated Juypter Extension code that is shown in github. So I think I will wait for a update on the release channel for the insider edition. Question, do the extension such as the Jupyter extension automatically update with the core vscode updates?

Thx.

**Comment by rchiodo** [comment] 2021-02-11 20:36
> Question, do the extension such as the Jupyter extension automatically update with the core vscode updates?

Sorry but no. Extensions update at their own cadence. We generally try to stick to once a month (similar to what VS code does). I think we're about to start releasing for insiders more often though.

If you have auto updates turned on, new bits will automatically install when we release.

**Comment by rchiodo** [comment] 2021-02-11 20:38
Closing as a dupe of #4451

**Closed by rchiodo** 2021-02-11 20:38 UTC
Labels: bug, info-needed, remote-connection-failure
