### ISSUE TITLE
Feature request: Undocking / floating interactive windows

### ISSUE THREAD

**Issue by doubleplusnice** [microsoft/vscode-jupyter#5456] opened 2021-04-08 18:03 UTC
When executing code in python interactive mode, output is displayed in the right pane of a vertical split screen. While this may be desirable most of the time, in many cases it is desirable to have the output shown in a different window, e.g. when working with multiple screens. Please consider making the interactive output window dockable to new window instances :) thanks

**Comment by rchiodo** [comment] 2021-04-08 20:57
Dupe of #5452

**Closed by rchiodo** 2021-04-08 20:57 UTC
Labels: enhancement
