### ISSUE TITLE
Unable to enter code in interactive window

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1107] opened 2020-11-13 05:16 UTC
```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
extension: 2020.11.0 (11 November 2020) v2020.11.358366026
```

I'm unable to enter code at the bottom of the interactive window and has to close it and restart one or restart vscode to resolve the issue, but the problem keep emerging after a while.

**Comment by hid4net** [comment] 2020-11-13 07:18
The same situation arises here

**Comment by skilkis** [comment] 2020-11-13 14:15
I have this same issue except that it happens everytime focus is switched from the interactive-window to elsewhere in VS Code.
```bash
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by wvanvalenberg** [comment] 2020-11-13 14:43
I also have this issue when switching focus. Resizing the width of the editor unfreezes the text input, but I have to do this constantly.

**Comment by greazer** [comment] 2020-11-17 08:34
Dupe of #446.

**Closed by greazer** 2020-11-17 08:34 UTC
Labels: bug
