### ISSUE TITLE
Code cell execution hangs

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#16004] opened 2024-09-05 18:03 UTC
Originally from Francesco Costa on marketplace

> after a few minutes of usage cells start to hang FOREVER. Sometimes it can take several minutes to simply print a string

**Comment by tylzh97** [comment] 2024-12-09 08:14
I faced the same problems. Hangs occur after you edit a cell, and the code hinting box appears. In my situation, uninstalling the pylance and continue plugins resolved these issues.

> https://github.com/continuedev/continue/issues/1463
> https://github.com/microsoft/pylance-release/issues/4742

I believe it's a bug in `vscode-jupyter` plugin because I can't even FORCE STOP the cell...

**Comment by DonJayamanne** [comment] 2024-12-16 22:11
> I believe it's a bug in vscode-jupyter plugin because I can't even FORCE STOP the cell...

Unfortunately from what I've found its not caused by Jupyter extension, some how the continue extension causes issues that breaks this entirely. Generally extensions should not be able to break other extensions in this manner, somehow they're doing something thats not correct. Hence nothing to be done here in Jupyter ext

Closing this issue as its been around for a while and we haven't had any addtional information.

**Closed by DonJayamanne** 2024-12-16 22:11 UTC
Labels: bug, marketplace-review
