### ISSUE TITLE
Kernel not found in Jupyter notebook

### ISSUE THREAD

**Issue by SuperMB** [microsoft/vscode-jupyter#13995] opened 2023-07-27 15:01 UTC
With the updated Python extension a Jupyter notebook can no longer find the Python kernel in a GitHub Codespace. I think this may be because the Jupyter extension is then showed as being installed in the browser and not the Codespace?? However, reverting the Python extension to a few months ago, the Jupyter notebook can find the kernel with no problem. I have tried this in multiple repos now, and the same issue persists. This is really hurting how our users can use our software in Codespaces. 

![CantRunPythonNotebook](https://github.com/microsoft/vscode-python/assets/5454335/d9b51abb-49b4-4673-8536-a8fd635220ba)

**Comment by DonJayamanne** [comment] 2023-07-30 23:40
Duplicate of https://github.com/microsoft/vscode/issues/189280
@SuperMB Sorry you are running into this issue, this caused by an issue in VS Code, I'll have a chat with the team to see what we can do about this.

**Closed by DonJayamanne** 2023-07-30 23:40 UTC
Labels: upstream-vscode, triage-needed
