### ISSUE TITLE
Native notebook interface with percent-encoded scripts

### ISSUE THREAD

**Issue by akdor1154** [microsoft/vscode-jupyter#4861] opened 2021-02-18 05:07 UTC
Apologies if this is a dupe: I've searched for "percent" and "jupytext" with no result but it seems strange that this hasn't been raised.

I want to use the new native notebook interface with percent-encoded notebook/scripts, as supported by the legacy interpreter pane.

E.g.
```py
#%%
# cell 1
import sql
#%%
# cell 2
df = sql.read(...)
#%%
...
```
I would expect the workflow to work roughly like jupyter with the jupytext extension: I'd open a .py file (perhaps with a special "open as notebook" command) and I'd be presented with it rendered and editable as a notebook. Cell outputs would not be saved in this format, but vscode might prepend some metadata to its head if necessary to save kernel params, the fact it's a "notebook", etc.

**Comment by rchiodo** [comment] 2021-02-18 17:38
This is possible today? 

![image](https://user-images.githubusercontent.com/19672699/108397490-dffb7d80-71cc-11eb-94f0-726edf959e53.png)

That exports from the file itself. You can also export from the interactive window. 

It seems it's not available (all the time) on the command palette though. When it is it looks like this:

![image](https://user-images.githubusercontent.com/19672699/108397686-1507d000-71cd-11eb-8604-6cae2d06cecb.png)

**Comment by greazer** [comment] 2021-02-18 21:53
Very close to being a dupe of #1240. Even if it's different, we don't have plans on doing this in the near future. Thanks for the request though!

**Closed by greazer** 2021-02-18 21:53 UTC
Labels: enhancement

**Comment by akdor1154** [comment] 2021-02-18 22:22
Indeed that link is close enough to what I want. Thanks! (And thanks for otherwise thankless triage work :) )
