### ISSUE TITLE
Conda env created doesn't show up

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#11073] opened 2022-08-09 00:26 UTC
## Environment data

-   VS Code version: 1.70.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.7.1002181843
-   Python Extension version (available under the Extensions sidebar): v2022.12.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: Python 3.10.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Actual behaviour

1. Create a conda environment using `conda create ...`
2. See that the environment was created using `conda env list`
3. The environment actually does not show up in the kernel picker

![image](https://user-images.githubusercontent.com/10833267/183533136-cd4f8a09-53d1-4f6a-9364-06cc8c570b42.png)

cc/ @amytnguyen01

**Comment by DonJayamanne** [comment] 2022-08-09 21:21
@amytnguyen01
* Please could you confirm the environment doesn't appear even after you reload VS Code.

**Comment by DonJayamanne** [comment] 2022-08-15 04:46
This isnt a UI issue, but an issue with the API or the code used to fetch the kernels or interpreters from the Python extensiosn. And those are areas I own today, hence re-assining to myself.

**Comment by DonJayamanne** [comment] 2022-08-22 18:33
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/10859

**Closed by DonJayamanne** 2022-08-22 18:33 UTC
Labels: bug, info-needed, kernel-enumeration
