### ISSUE TITLE
Playwright error in ipywidgets ui test

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#4047] opened 2020-11-30 17:43 UTC
![image](https://user-images.githubusercontent.com/30305945/100644626-6c925000-32f0-11eb-846b-db30f2c6e113.png)

First time I've seen this, logging as an issue here so we can track it. Might be related to https://github.com/microsoft/playwright/issues/2974

**Comment by DonJayamanne** [comment] 2020-12-09 18:24
Looks like the original issue reported by others aren't reproducing, and I haven't seen this either, hence suggest we close this.
After all, not sure what we're supposed to do here, its a flaky issue with playwright.
@joyceerhl thoughts?

**Comment by DonJayamanne** [comment] 2020-12-11 17:58
Closing for now, as we haven't seen these issues.

**Closed by DonJayamanne** 2020-12-11 17:58 UTC
Labels: code-health
