### ISSUE TITLE
Kernel crash with no external libraries

### ISSUE THREAD

**Issue by theRealProHacker** [microsoft/vscode-jupyter#12587] opened 2023-01-19 19:04 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have a cell:
```py
def recursive():
    recursive()

recursive()
```

I would expect a `RecursionError`. Something along the line of:
```Traceback (most recent call last):
  File "c:\Rashid\Studium\Module\Alp3 - ADD\test.py", line 4, in <module> 
    recursive()
  File "c:\Rashid\Studium\Module\Alp3 - ADD\test.py", line 2, in recursive
    recursive()
  File "c:\Rashid\Studium\Module\Alp3 - ADD\test.py", line 2, in recursive
    recursive()
  File "c:\Rashid\Studium\Module\Alp3 - ADD\test.py", line 2, in recursive
    recursive()
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```
Instead, the kernel crashed. That is in my opinion a bug. 

### VS Code Version

Version: 1.74.3 (user setup) Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534 Date: 2023-01-09T16:59:02.252Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.19044 Sandboxed: No

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
error 20:06:15.261: Error in execution s [Error]: The kernel 'Python 3.10.5' died. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
    at Function.verifyKernelState (c:\Users\Rashid\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:2325307)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at x.executeCell (c:\Users\Rashid\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:2405345)
    at async Promise.all (index 0)
    at x.handleExecution (c:\Users\Rashid\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:2401348) {
  category: 'unknown',
  originalException: undefined,
  kernelConnectionMetadata: f {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: undefined,
      interpreterPath: 'c:\\Users\\Rashid\\AppData\\Local\\Programs\\Python\\Python310\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0adbff5bb3260ca832b17f114077bcd187b30d7a64d5d0747a0a4c9b01deb644a',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: 'C:\\USERS\\RASHID\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON310\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Rashid\\AppData\\Local\\Programs\\Python\\Python310',
      envPath: undefined,
      displayPath: [d],
      envName: '',
      uri: [d],
      displayName: '',
      envType: 'Unknown',
      version: [Object]
    },
    id: '.jvsc74a57bd0adbff5bb3260ca832b17f114077bcd187b30d7a64d5d0747a0a4c9b01deb644a.c:\\Users\\Rashid\\AppData\\Local\\Programs\\Python\\Python310\\python.exe.c:\\Users\\Rashid\\AppData\\Local\\Programs\\Python\\Python310\\python.exe.-m#ipykernel_launcher'
  }
}
error 20:06:15.262: Error in execution (get message for cell) s [Error]: The kernel 'Python 3.10.5' died. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
    at Function.verifyKernelState (c:\Users\Rashid\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:2325307)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at x.executeCell (c:\Users\Rashid\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:2405345)
    at async Promise.all (index 0)
    at x.handleExecution (c:\Users\Rashid\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\out\extension.node.js:2:2401348) {
  category: 'unknown',
  originalException: undefined,
  kernelConnectionMetadata: f {
    kind: 'startUsingPythonInterpreter',
    kernelSpec: {
      specFile: undefined,
      interpreterPath: 'c:\\Users\\Rashid\\AppData\\Local\\Programs\\Python\\Python310\\python.exe',
      isRegisteredByVSC: 'registeredByNewVersionOfExt',
      name: 'pythonjvsc74a57bd0adbff5bb3260ca832b17f114077bcd187b30d7a64d5d0747a0a4c9b01deb644a',
      argv: [Array],
      language: 'python',
      executable: 'python',
      display_name: 'Python 3',
      metadata: [Object],
      env: {},
      interrupt_mode: undefined
    },
    interpreter: {
      id: 'C:\\USERS\\RASHID\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON310\\PYTHON.EXE',
      sysPrefix: 'C:\\Users\\Rashid\\AppData\\Local\\Programs\\Python\\Python310',
      envPath: undefined,
      displayPath: [d],
      envName: '',
      uri: [d],
      displayName: '',
      envType: 'Unknown',
      version: [Object]
    },
    id: '.jvsc74a57bd0adbff5bb3260ca832b17f114077bcd187b30d7a64d5d0747a0a4c9b01deb644a.c:\\Users\\Rashid\\AppData\\Local\\Programs\\Python\\Python310\\python.exe.c:\\Users\\Rashid\\AppData\\Local\\Programs\\Python\\Python310\\python.exe.-m#ipykernel_launcher'
  }
}

```

### Coding Language and Runtime Version

Python 3.10.5

### Language Extension Version (if applicable)

 v2022.20.2

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2023-01-19 19:18
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12511

**Closed by DonJayamanne** 2023-01-19 19:18 UTC
Labels: bug
