### ISSUE TITLE
Leaked debug processes on VS Code reload window

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-jupyter#6917] opened 2021-07-29 22:01 UTC
Issue Type: <b>Bug</b>

1) enable experimental debugging
2) open a notebook
3) run a cell line-by-line (or use full debugging - doesn't matter)
4) while debugging is running reload window
-> debug process is still hanging around

I ran this in a codespace.

When I run the same steps but using the js debugger, no process leaks.

Extension version: 2021.8.1077987658
VS Code version: Code - Insiders 1.59.0-insider (0f22f2d343e33b03e8033d1083513072f58ece21, 2021-07-29T05:27:33.986Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.8.0-1039-azure
Remote OS version: Linux x64 5.4.0-1055-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|--enable-proposed-api lszomoru.lszomoru-proposed-api-sample --enable-proposed-api donjayamanne.kusto --crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: az-devbox|
|OS|Linux x64 5.8.0-1039-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (4 x 2095)|
|Memory (System)|15.64GB (12.53GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1055-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz (4 x 2693)|
|Memory (System)|7.78GB (0.54GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwt:30312692
pythonvssor306:30340298
bridge0708:30335490
dockerwalkthrucf:30344902

```

</details>

**Comment by greazer** [comment] 2021-08-02 20:57
Dupe of issue David mentions above.

**Comment by roblourens** [comment] 2022-12-08 23:13
This is fixed

**Closed by roblourens** 2022-12-08 23:13 UTC
Labels: bug, notebook-run-by-line, notebook-debugging
