### ISSUE TITLE
Switch localization story so we get free loc

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9913] opened 2022-05-05 18:18 UTC
Not going to work for web yet, but Tyler posted this:
https://gist.github.com/TylerLeonhardt/83abd380686ac1321b01552a5b236bad

**Comment by DonJayamanne** [comment] 2022-05-05 21:48
duplicate of https://github.com/microsoft/vscode-jupyter/issues/9676

**Closed by DonJayamanne** 2022-05-05 21:48 UTC
Labels: engineering, localization
