### ISSUE TITLE
matplotlib import hangs in magic wx environment

### ISSUE THREAD

**Issue by lfriedri** [microsoft/vscode-jupyter#8273] opened 2021-11-16 13:03 UTC
## Environment data

-   VS Code version: 1.62.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Winpython 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## Expected behaviour

Matplotlib figures can be opened as separate windows from interactive window when wx backend is used.

## Actual behaviour

`import matplotlib` hangs, if executed after `%gui wx`

## Steps to reproduce:

Run the following lines in an interactive window:

```
%gui wx
import matplotlib
matplotlib.use('wxAgg')
import matplotlib.pyplot as P
P.ion()
```

**Comment by lfriedri** [comment] 2021-11-16 13:04
Seems to be related to https://github.com/microsoft/vscode-jupyter/issues/8177

**Comment by rchiodo** [comment] 2021-11-16 17:13
Thanks for the bug. I'd hazard a guess that this is the same root cause as #8177. VS code just isn't the same environment as a jupyter notebook and any assumptions the underlying matplotlib code makes just aren't going to work.

**Comment by rchiodo** [comment] 2021-11-16 17:34
The import is taking forever (as @lfriedri  said). We'd have to debug the kernel to see why. Probably waiting for the UI to popup.

**Comment by lfriedri** [comment] 2021-11-23 11:25
Please note that I am using the interactive window, not the notebook interface. My reference case is not the classic jupyter notebook, but rather an ipython session, used in a kind of "matlab" like usecase (running scripts to process data, viewing results in free floating, resizable, interactive matplotlib figures, backend wxAgg)

**Comment by DonJayamanne** [comment] 2022-12-05 23:01
Closing this as a duplicate of #8177

**Closed by DonJayamanne** 2022-12-05 23:01 UTC
Labels: bug, ipywidgets, cell-magics, specific-to-package-library
