### ISSUE TITLE
Data Viewer is not showing dictionaries within a dictionary

### ISSUE THREAD

**Issue by aslangencer** [microsoft/vscode-jupyter#9760] opened 2022-04-25 15:15 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

A dictionary contained within a dictionary is previewed in the 'JUPYTER: VARIABLES' pane however its content is not shown on the 'Data Viewer' window. 
Example: `myDict = { 'Arr1': [1, 2], 'Dict1': { "Key1": "Val1"} }`

### VS Code Version

Version: 1.66.2 (Universal) Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977

### Jupyter Extension Version

v2022.3.1000901801

### Jupyter logs

```shell
Visual Studio Code (1.66.2, undefined, desktop)
Jupyter Extension Version: 2022.3.1000901801.
Python Extension Version: 2022.4.1.
Workspace folder ~
Info 17:10:12: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 17:10:14: Preferred kernel connection found in cache .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 17:10:14: PreferredConnection: .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher found for NotebookDocument: untitled:Untitled-1.ipynb?jupyter-notebook
Info 17:10:14: Early registration of controller for Kernel connection .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 17:10:14: TargetController found ID: .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher for document untitled:Untitled-1.ipynb?jupyter-notebook
Info 17:10:14: Setting controller affinity for untitled:Untitled-1.ipynb?jupyter-notebook .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 17:10:14: Getting activation commands for /usr/local/bin/python3 are not cached. May take a while.
Info 17:10:14: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 17:10:14: Creating controller for jupyter-notebook with interpreter ~/myenv/bin/python
Info 17:10:14: Setting setActiveController for untitled:Untitled-1.ipynb?jupyter-notebook
Info 17:10:14: KernelProvider switched kernel to id = .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 17:10:14: Starting Notebook in kernel.ts id = .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher for untitled:Untitled-1.ipynb?jupyter-notebook
Info 17:10:14: Creating raw notebook for untitled:Untitled-1.ipynb?jupyter-notebook
Info 17:10:14: Getting preferred kernel for untitled:Untitled-1.ipynb?jupyter-notebook
Info 17:10:14: Computing working directory untitled:Untitled-1.ipynb?jupyter-notebook
Info 17:10:14: Starting raw kernel Python 3.9.12 64-bit for interpreter /usr/local/bin/python3
Info 17:10:14: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 17:10:14: Process Execution: > ~/myenv/bin/python -m pip list
> ~/myenv/bin/python -m pip list
Info 17:10:15: No custom variables nor do we have a conda environment
Info 17:10:15: Process Execution: > /usr/local/bin/python3 -m pip list
> /usr/local/bin/python3 -m pip list
Info 17:10:15: Process Execution: > /usr/local/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /usr/local/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 17:10:15: Process Execution: > /usr/local/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"5274fa06-f633-4540-86f9-d86a7ee976a5" --shell=9002 --transport="tcp" --iopub=9004 --f=/var/folders/2t/n41nv4gn6z9627by5mk9ttd4b_mh6q/T/tmp-306797oxSlyDJZJ6L.json
> /usr/local/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"5274fa06-f633-4540-86f9-d86a7ee976a5" --shell=9002 --transport="tcp" --iopub=9004 --f=/var/folders/2t/n41nv4gn6z9627by5mk9ttd4b_mh6q/T/tmp-306797oxSlyDJZJ6L.json
Info 17:10:15: Process Execution: cwd: ~/
cwd: ~/
Info 17:10:15: ipykernel version 6.4.1 for /usr/local/bin/python3
Info 17:10:15: ipykernel location ~/Library/Python/3.9/lib/python/site-packages/ipykernel/__init__.py for /usr/local/bin/python3
Info 17:10:16: Registering dummy command feature
Info 17:10:16: Registering dummy command feature
Warn 17:10:19: StdErr from Kernel Process /Users/gencer/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
/Users/gencer/Library/Python/3.9/lib/python/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '5274fa06-f633-4540-86f9-d86a7ee976a5' instead of 'b"5274fa06-f633-4540-86f9-d86a7ee976a5"'.
  warn(

Info 17:10:19: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing /var/folders/2t/n41nv4gn6z9627by5mk9ttd4b_mh6q/T/tmp-306797oxSlyDJZJ6L.json

Info 17:10:19: Raw session started and connected
Started kernel Python 3.9.12 64-bit
Info 17:10:19: Finished connecting abd53f36-c919-4b43-8365-bae7491904a0
Info 17:10:19: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = "Untitled-1.ipynb"\n%con
Info 17:10:19: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\n__vsc_ipynb_file__ = "Untitled-1.ipynb"\n%con
Info 17:10:19: Waiting for idle on (kernel): 3a9cc0e9-eae8-4700-af85-3b2b2649dd06 -> idle
Info 17:10:19: Finished waiting for idle on (kernel): 3a9cc0e9-eae8-4700-af85-3b2b2649dd06 -> idle
Info 17:10:23: Executing silently Code (idle) = import ipykernel\nprint(ipykernel.__version__)
Info 17:10:23: Executing silently Code (completed) = import ipykernel\nprint(ipykernel.__version__)
Info 17:10:23: Executing silently Code (idle) = import debugpy\ndebugpy.debug_this_thread()
Info 17:10:23: Executing silently Code (completed) = import debugpy\ndebugpy.debug_this_thread()
Info 17:10:23: Loading webview. View is notset
Info 17:10:23: Execute Cells request 0
Info 17:10:23: Execute Cell 0 untitled:Untitled-1.ipynb?jupyter-notebook
Info 17:10:23: Loading web view...
Info 17:10:23: Webview panel created.
Info 17:10:24: Web view react rendered
Info 17:10:24: Searching for token colors ...
Info 17:10:24: Attempting search for colors ...
Info 17:10:24: Loading colors from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 17:10:24: Attempting search for colors ...
Info 17:10:24: Loading base colors from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 17:10:24: Using colors to generate CSS ...
Info 17:10:26: Cell 0 executed with state Success
Warn 17:10:26: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/Users/gencer/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 281, in process_control
    await result
  File "/Users/gencer/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 856, in debug_request
    reply_content = await reply_content
  File "/Users/gencer/Library/Python/3.9/lib/python/site-packages/ipykernel/ipkernel.py", line 426, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/Users/gencer/Library/Python/3.9/lib/python/site-packages/ipykernel/debugger.py", line 595, in process_request
    self.stop()
  File "/Users/gencer/Library/Python/3.9/lib/python/site-packages/ipykernel/debugger.py", line 348, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/Users/gencer/Library/Python/3.9/lib/python/site-packages/ipykernel/debugger.py", line 232, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 640, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory

Info 17:10:26: Executing silently Code (idle) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 17:10:26: Executing silently Code (idle) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 17:10:26: Executing silently Code (completed) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 17:10:26: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:26: Executing silently Code (completed) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 17:10:26: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:26: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:26: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:26: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:26: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:26: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:26: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:29: Loading webview. View is notset
Info 17:10:29: Loading web view...
Info 17:10:29: Webview panel created.
Info 17:10:29: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:29: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:29: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:29: Process Execution: > /usr/local/bin/python3 -c "import pandas;print(pandas.__version__)"
> /usr/local/bin/python3 -c "import pandas;print(pandas.__version__)"
Info 17:10:29: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:29: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:29: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 17:10:29: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:29: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:29: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:29: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:29: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:29: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getVariableInfo(myDict))
Info 17:10:29: Web view react rendered
Info 17:10:29: Searching for token colors ...
Info 17:10:29: Attempting search for colors ...
Info 17:10:29: Loading colors from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 17:10:29: Searching for token colors ...
Info 17:10:29: Attempting search for colors ...
Info 17:10:29: Loading colors from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 17:10:29: Attempting search for colors ...
Info 17:10:29: Loading base colors from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 17:10:29: Attempting search for colors ...
Info 17:10:29: Loading base colors from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/theme-defaults/themes/dark_plus.json ...
Info 17:10:29: Using colors to generate CSS ...
Info 17:10:29: Using colors to generate CSS ...
Info 17:10:30: Executing silently Code (idle) = import pandas as _VSCODE_pd\nimport builtins as _VSCODE_builtins\nimport json as _VSCODE_json\nimport n
Info 17:10:30: Executing silently Code (completed) = import pandas as _VSCODE_pd\nimport builtins as _VSCODE_builtins\nimport json as _VSCODE_json\nimport n
Info 17:10:30: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getDataFrameInfo(myDict))
Info 17:10:30: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getDataFrameInfo(myDict))
Info 17:10:30: Executing silently Code (idle) = import builtins\nbuiltins.print(_VSCODE_getDataFrameRows(myDict, 0, 2))
Info 17:10:30: Executing silently Code (completed) = import builtins\nbuiltins.print(_VSCODE_getDataFrameRows(myDict, 0, 2))
```

### Coding Language and Runtime Version

Python 3.9.12

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2022-04-25 16:24
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1138

**Closed by DonJayamanne** 2022-04-25 16:24 UTC
Labels: bug, needs-triage
