### ISSUE TITLE
ms-toolsai.jupyter Causes Extension Host Crash

### ISSUE THREAD

**Issue by tommykimlab** [microsoft/vscode-jupyter#15727] opened 2024-05-29 06:59 UTC
Type: <b>Bug</b>

1. Start Cursor
2. Auto AI complete not works

Extension version: 2024.4.0
VS Code version: Cursor 0.34.0 (838bc2665badb9638e37757a74e5586cfea89e50, 2024-05-27T00:09:09.301Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|6, 4, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment] 2024-05-29 09:10
Does it crash when not using cursor.

**Comment by DonJayamanne** [comment] 2024-05-30 20:19
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15721

**Closed by DonJayamanne** 2024-05-30 20:19 UTC
