### ISSUE TITLE
Filesystem Jupyterhub

### ISSUE THREAD

**Issue by snami100** [microsoft/vscode-jupyter#14496] opened 2023-10-11 21:24 UTC
In Pycharm you add the Jupyter connection by the URL and everything’s shows up. You see the files and everything. You can select between the kernel and you have the workspace as in Jupyter but in Pycharm. 

In VSC we only can use the kernel, but can’t create new files or browse through directories that easy with jupyterhub.
Am I missing something or is that still not possible?

**Comment by DonJayamanne** [comment] 2023-11-01 04:07
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1366
@snami100 Please upvote the above issue

**Closed by DonJayamanne** 2023-11-01 04:07 UTC
Labels: feature-request
