### ISSUE TITLE
Kernal is not starting: AutoReloadMagics error

### ISSUE THREAD

**Issue by Srikor** [microsoft/vscode-jupyter#14618] opened 2023-10-30 14:00 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Running a simple _import numpy_ in a code block results in the below error. 

Error in callback <bound method AutoreloadMagics.pre_run_cell of <IPython.extensions.autoreload.AutoreloadMagics object at 0x0000028E7918A610>> (for pre_run_cell):
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: AutoreloadMagics.pre_run_cell() takes 1 positional argument but 2 were given

### VS Code Version

1.70.1

### Jupyter Extension Version

v2022.7.1102252217

### Jupyter logs

```shell
Visual Studio Code (1.70.1, undefined, desktop)
Jupyter Extension Version: 2022.7.1102252217.
Python Extension Version: 2022.16.1.
Workspace folder c:\Projects\EdxDataScience
info 19:15:37.84: ZMQ install verified.
info 19:15:37.625: LSP Notebooks experiment is enabled
error 19:15:38.122: getCondaFile, Class name = w, completed in 490ms, has a falsy return value [EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\425998\miniconda3\Scripts\conda.exe'
	at Function._handleError (c:\Users\425998\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:29734)
	at Object.stat (c:\Users\425998\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:28102)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async f.getFileHash (c:\Users\425998\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:7:17708)
	at async w.getCachedInformation (c:\Users\425998\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:7:35788)] {
  code: 'FileNotFound'
}
error 19:15:38.130: getCondaVersion, Class name = w, completed in 498ms, has a falsy return value [EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\425998\miniconda3\Scripts\conda.exe'
	at Function._handleError (c:\Users\425998\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:29734)
	at Object.stat (c:\Users\425998\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:28102)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async f.getFileHash (c:\Users\425998\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:7:17708)
	at async w.getCachedInformation (c:\Users\425998\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\out\extension.node.js:7:35788)] {
  code: 'FileNotFound'
}
info 19:15:38.196: Starting Jupyter Session id = 'startUsingPythonInterpreter:.jvsc74a57bd0db22e7ae9d71cb08592db9a4f35ee0e0bd2c8fed430ba0a756a83dff563b8430.c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe.c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe.-m#ipykernel_launcher' (Python Path: , EnvType: Global, EnvName: '', Version: 3.11.6) for 'c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch\basics.ipynb' (disableUI=true)
info 19:15:38.202: Creating raw notebook for resource 'c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch\basics.ipynb'
info 19:15:38.202: Computing working directory for resource 'c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch\basics.ipynb'
info 19:15:38.905: Starting raw kernel 'Python 3.11.6 64-bit' for interpreter c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe
info 19:15:38.941: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
info 19:15:39.238: Widget Message: Received IPyWidgetMessages.IPyWidgets_IsReadyRequest
info 19:15:39.390: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 19:15:40.604: Preferred Remote kernel for c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch\basics.ipynb is undefined
info 19:15:40.605: Find preferred kernel for c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch\basics.ipynb with metadata {"kernelspec":{"display_name":"Python 3.11.6 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.11.6"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"db22e7ae9d71cb08592db9a4f35ee0e0bd2c8fed430ba0a756a83dff563b8430"}}} & preferred interpreter 
info 19:15:40.607: Preferred Remote kernel for c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch\basics.ipynb is undefined
info 19:15:40.607: Preferred kernel .jvsc74a57bd0db22e7ae9d71cb08592db9a4f35ee0e0bd2c8fed430ba0a756a83dff563b8430.c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe.c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, undefined, true, false)
info 19:15:40.609: PreferredConnection: .jvsc74a57bd0db22e7ae9d71cb08592db9a4f35ee0e0bd2c8fed430ba0a756a83dff563b8430.c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe.c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch\basics.ipynb
info 19:15:41.463: Process Execution: > ~\AppData\Local\Programs\Python\Python311\python.exe -m pip list
> ~\AppData\Local\Programs\Python\Python311\python.exe -m pip list
info 19:15:41.494: Process Execution: > ~\AppData\Local\Programs\Python\Python311\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\AppData\Local\Programs\Python\Python311\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 19:15:41.503: Creating daemon process for c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe with env variables count 55
info 19:15:41.520: Process Execution: > ~\AppData\Local\Programs\Python\Python311\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 5840
> ~\AppData\Local\Programs\Python\Python311\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 5840
info 19:15:41.843: get interrupthandle daemon
info 19:15:41.856: Process Execution: > ~\AppData\Local\Programs\Python\Python311\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"9c842330-38bf-4f8f-8886-4f4982a720ad" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\425998\AppData\Roaming\jupyter\runtime\kernel-v2-58406EEacCVKGWvO.json
> ~\AppData\Local\Programs\Python\Python311\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"9c842330-38bf-4f8f-8886-4f4982a720ad" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\425998\AppData\Roaming\jupyter\runtime\kernel-v2-58406EEacCVKGWvO.json
info 19:15:41.856: Process Execution: cwd: c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch
cwd: c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch
info 19:15:42.294: ipykernel version 6.26.0 for c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe
info 19:15:42.294: ipykernel location ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipykernel\__init__.py for c:\Users\425998\AppData\Local\Programs\Python\Python311\python.exe
info 19:15:43.50: Preferred Remote kernel for c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch\basics.ipynb is undefined
warn 19:15:43.191: StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

info 19:15:43.358: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing c:\Users\425998\AppData\Roaming\jupyter\runtime\kernel-v2-58406EEacCVKGWvO.json

info 19:15:43.439: Started kernel Python 3.11.6 64-bit., (Raw session started and connected)
info 19:15:43.440: Finished connecting 0e238c2a-f139-4a59-afc9-7accd027d15b
info 19:15:43.444: UpdateWorkingDirectoryAndPath in Kernel
info 19:15:43.445: Executing silently Code (idle) = import os\nimport sys\n%cd "c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch"\nif os.getcwd()
info 19:15:43.583: Executing silently Code (completed) = import os\nimport sys\n%cd "c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch"\nif os.getcwd() with 2 output(s)
info 19:15:43.583: Executing silently Code (idle) = %load_ext autoreload\n%autoreload 2
info 19:15:43.618: Executing silently Code (completed) = %load_ext autoreload\n%autoreload 2 with 0 output(s)
info 19:15:43.619: Waiting for idle on (kernel): 90a903cc-c385-48d8-aa61-151f2230a9af -> idle
info 19:15:43.619: Finished waiting for idle on (kernel): 90a903cc-c385-48d8-aa61-151f2230a9af -> idle
info 19:15:43.630: Process Execution: > ~\AppData\Local\Programs\Python\Python311\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\pythonFiles\printJupyterDataDir.py
> ~\AppData\Local\Programs\Python\Python311\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2022.7.1102252217\pythonFiles\printJupyterDataDir.py
info 19:15:43.642: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 19:15:43.642: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
warn 19:15:44.63: Got a non-existent Jupyer Data Dir file:///c%3A/Users/425998/AppData/Roaming/Python/share/jupyter
info 19:15:44.100: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/425998/.vscode/extensions/ms-toolsai.jupyter-2022.7.1102252217/tmp/scripts/7a7ebc9927ff06b851d33dcd8f6dd7bdab169dcab8ea833605e1dcca9b5e193c/jupyter
info 19:16:41.953: Execute Cell 0 c:\Projects\EdxDataScience\kaggle\DigitRecognizer\PyTorch\basics.ipynb
info 19:16:42.335: Cancel all remaining cells true || Error || undefined
info 19:16:42.335: Cancel pending cells
info 19:16:42.336: Cell 0 executed with state Error
```

### Coding Language and Runtime Version

Python 3.11.6 64 bit

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2023-10-30 14:07
Thanks for filing this issue.
Unfortunately you are using an old version of VS Code and Jupter extension.
Please update to the latest versions, if this problem still persists with the latest version, please feel free to re-open thi sissue or feel free to create a new issue.

**Comment by hauselin** [comment] 2023-10-30 14:57
I'm also getting this error. My VS Code and Jupyter extension are the latest versions.

```
VSCode
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:57:32.750Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.1.0

Jupyter
v2023.9.1102792234
```

I'm getting this error when running cells `#%%`.

```
Error in callback <bound method AutoreloadMagics.pre_run_cell of <IPython.extensions.autoreload.AutoreloadMagics object at 0x106845e70>> (for pre_run_cell):

TypeError: AutoreloadMagics.pre_run_cell() takes 1 positional argument but 2 were given
```

It used to work. My settings.json:

```
  "jupyter.runStartupCommands": [    
    "%load_ext autoreload",
    "%autoreload 2"
  ],
```

Removing these two lines resolved the bug for now.

```
    "%load_ext autoreload",
    "%autoreload 2"
```

**Comment by Srikor** [comment] 2023-10-30 15:12
Updated the VS Code version and Jupyter extension. Still getting same error.

**Comment by georgedeath** [comment] 2023-10-30 16:13
> Doesnt seem to be caused by VS Code. The exact same propblem can be replicated in Jupyter lab (outside vscode) as well Will try to fing out what caused this (ipykernel, ipython, etc)

Good shout. Downgrading to ipython version 8.16.1 fixes this (from 8.17.1).

**Comment by DonJayamanne** [comment] 2023-10-30 16:26
Duplicate of https://github.com/ipython/ipython/issues/14230

**Closed by DonJayamanne** 2023-10-30 16:26 UTC
Labels: bug

**Comment by DonJayamanne** [comment] 2023-10-30 16:27
# Solution
Dowgrade ipython to 8.16.1
Upstream issue https://github.com/ipython/ipython/issues/14230

**Comment by Srikor** [comment] 2023-10-31 05:23
For some reason this fix works for global python environment but keep getting the same error when using venv. Package versions are same in both the env. Proceeding with global environment for now. Thanks.
