### ISSUE TITLE
Add support for Julia Variables in Jupyter VS Code Extension

### ISSUE THREAD

**Issue by logankilpatrick** [microsoft/vscode-jupyter#7224] opened 2021-08-22 13:39 UTC
Just like as is described here: https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_variable-explorer-and-data-viewer, it would be nice to have this for Julia support as well. Currently, when I have a Julia notebook open, it shows the "Variables" box greyed out like below: 

<img width="1463" alt="Screen Shot 2021-08-22 at 6 38 14 AM" src="https://user-images.githubusercontent.com/35577566/130357250-80bb35cb-6f53-4ae0-a95d-f657e804f48c.png">

but Julia already has support for this feature in the Julia extension for VS Code so there likely just needs to be some porting of that feature here.

**Comment by davidanthoff** [comment] 2021-08-22 19:13
Just FYI, we do have full variable exploring functionality for Julia kernels already in the Julia Workspace, and it is actually a feature richer variable pane than what is here in the Jupyter extension because we support full drill down into arrays, dicts and composite types. The TODO here is really just to either hook the "Variables" button up to show our variable pane, or hide the "Variables" button from the Jupyter extension when our kernel is used, and then we could show our own button in that case. See also https://github.com/julia-vscode/julia-vscode/issues/2240.

**Comment by joyceerhl** [comment] 2021-08-23 15:38
> either hook the "Variables" button up to show our variable pane, or hide the "Variables" button from the Jupyter extension when our kernel is used

Either of these options makes good sense. As @logankilpatrick discovered, the Jupyter extension doesn't currently support displaying variables for non-Python kernels.

**Comment by DonJayamanne** [comment] 2021-08-23 16:17
Dupe of https://github.com/microsoft/vscode-jupyter/issues/6548

**Comment by greazer** [comment] 2021-08-23 20:19
Closing as dupe.

**Closed by greazer** 2021-08-23 20:19 UTC
Labels: enhancement, needs-triage
