### ISSUE TITLE
Long delay after execution completion due to data upload

### ISSUE THREAD

**Issue by kwikwag** [microsoft/vscode-jupyter#8660] opened 2022-01-09 14:11 UTC
## Environment data

-   VS Code version: 1.63.2 (user setup)
-   Jupyter Extension version: v2021.11.1001550889
-   Python Extension version: v2021.12.1559732655
-   OS: Windows_NT x64 10.0.19043
-   Python and/or Anaconda version: Python 3.6.13, 3.8.8 via Anaconda, conda version 4.10.1
-   Type of virtual environment used: conda
-   Jupyter server running: Local (VS Code running Remote via SSH)

## Expected behaviour

When I am connected via a VS Code remote SSH session running an interactive window (which is running in the same remote machine): for every cell, once evaluation is complete and output displayed, I should be able to evaluate the next cell nearly immediately.

## Actual behaviour

When displaying images in the notebook, a lot of data is being sent to Jupyter server, much more than is being received. Consequently, the notebook hangs until the upload is complete and other cells cannot be evaluated.

## Steps to reproduce:

1. Connect to an SSH remote in VS Code
2. Open a Python file with the following code
```python
# %%
import numpy as np
import matplotlib.pyplot as plt


for i in range(10):
    im = np.random.uniform(0, 1, (200, 200))
    plt.imshow(im)
    plt.show()

# %%
print(2 + 2)

```
3. Open a network monitor and run all cells. You will notice a large delay after the last image is displayed and before the next cell is evaluated. During the run and the delay after, the network monitor will show a large amount of data uploading.

![recording](https://user-images.githubusercontent.com/392199/148686021-4399fba5-cf90-4fbc-a1e0-2be02cd014da.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Jupyter Extension Version: 2021.11.1001550889.
Python Extension Verison: 2021.12.1559732655.
Info 15:48:45: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 15:48:45: ZMQ install verified.
Info 15:48:45: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 15:48:46: Process Execution: > ~\AppData\Local\Continuum\anaconda3\envs\numa\python.exe -m pip list
> ~\AppData\Local\Continuum\anaconda3\envs\numa\python.exe -m pip list
Info 15:48:59: Creating controller for interactive with interpreter ~\AppData\Local\Continuum\anaconda3\envs\numa\python.exe
...
Info 15:53:53: Restart requested vscode-interactive:Interactive-1.interactive
Info 15:53:53: Restart kernel execution
Info 15:53:53: Cancel pending cells
Info 15:53:53: Starting raw kernel myenv (Python 3.6.13)
Info 15:53:53: installMissingDependencies ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe
Info 15:53:53: IPykernel found previously in this enviornment ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe
Info 15:53:53: Restarting 12345678-3f5e-4466-a6bd-12345678f921
Info 15:53:53: Kernel launching with ports 9007,9008,9009,9010,9011. Start port is 9000
Info 15:53:53: Launching kernel daemon for Python 3.6.13 64-bit ('myenv': conda) # ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe
Info 15:53:53: Creating daemon process for ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe with env variables count 77
Info 15:53:53: Process Execution: > ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 15:53:53: Starting kernel from scratch
Warn 15:53:54: Didn't get response for requestKernelInfo after 34ms.
Info 15:53:54: Got new session 12345678-ba19-4762-b3f8-12345678cce7
Info 15:53:54: Started new restart session
Info 15:53:54: Dispose Kernel process
Info 15:53:54: kill daemon
Info 15:53:54: UpdateWorkingDirectoryAndPath in Kernel
Info 15:53:54: changeDirectoryIfPossible
Info 15:53:54: Executing (status idle) silently Code = import os\nimport sys\n%cd "d:\Projects\myenv\research"\nif os.getcwd() not in sys.path:\nsys.path.in
Info 15:53:54: Executing silently Code (completed) = import os\nimport sys\n%cd "d:\Projects\myenv\research"\nif os.getcwd() not in sys.path:\nsys.path.in
Info 15:53:54: Executing (status idle) silently Code = %config Completer.use_jedi = False
Info 15:53:54: Executing silently Code (completed) = %config Completer.use_jedi = False
Info 15:53:54: Executing (status idle) silently Code = %config InlineBackend.figure_formats = ['png']
Info 15:53:54: Executing silently Code (completed) = %config InlineBackend.figure_formats = ['png']
Info 15:53:54: Executing (status idle) silently Code = import sys\nprint(sys.executable)
Info 15:53:54: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 15:53:54: Waiting for idle on (kernel): 12345678-ba19-4762-b3f8-12345678cce7 -> idle
Info 15:53:54: Finished waiting for idle on (kernel): 12345678-ba19-4762-b3f8-12345678cce7 -> idle
Info 15:53:54: Executing (status idle) silently Code = __file__ = 'd:\\Projects\\myenv\\research\\vscode_jupyter_img_ssh_issue.py'
Info 15:53:54: Executing (status idle) silently Code = __file__ = 'd:\\Projects\\myenv\\research\\vscode_jupyter_img_ssh_issue.py'
Info 15:53:54: Executing silently Code (completed) = __file__ = 'd:\\Projects\\myenv\\research\\vscode_jupyter_img_ssh_issue.py'
Info 15:53:54: Executing silently Code (completed) = __file__ = 'd:\\Projects\\myenv\\research\\vscode_jupyter_img_ssh_issue.py'
Info 15:54:35: Executing (status idle) silently Code = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 15:54:35: Executing silently Code (completed) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 15:54:35: Executing (status idle) silently Code = _rwho_ls = %who_ls\nprint(_VSCODE_getVariableTypes(_rwho_ls))
Info 15:54:35: Executing silently Code (completed) = _rwho_ls = %who_ls\nprint(_VSCODE_getVariableTypes(_rwho_ls))
Info 15:54:35: Executing (status idle) silently Code = _rwho_ls = %who_ls\nprint(_VSCODE_getVariableTypes(_rwho_ls))
Info 15:54:35: Executing silently Code (completed) = _rwho_ls = %who_ls\nprint(_VSCODE_getVariableTypes(_rwho_ls))
Info 15:54:36: Executing (status idle) silently Code = _rwho_ls = %who_ls\nprint(_VSCODE_getVariableTypes(_rwho_ls))
Info 15:54:36: Executing silently Code (completed) = _rwho_ls = %who_ls\nprint(_VSCODE_getVariableTypes(_rwho_ls))
Info 15:54:41: Executing (status idle) silently Code = _rwho_ls = %who_ls\nprint(_VSCODE_getVariableTypes(_rwho_ls))
Info 15:54:41: Executing silently Code (completed) = _rwho_ls = %who_ls\nprint(_VSCODE_getVariableTypes(_rwho_ls))
Info 15:54:42: Adding hash for 1 = 0b6cb553f4b5 with 8 lines
Info 15:54:44: Cell 1 executed with state Success
Info 15:54:44: Finished execution for 12345678-1c92-4709-9041-12345678804a
Info 15:54:55: Pre-warming kernel daemon for d:\Projects\myenv\research
Info 15:54:55: IPykernel found previously in this enviornment ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe
Info 15:54:55: Creating daemon process for ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe with env variables count 77
Info 15:54:55: Process Execution: > ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\AppData\Local\Continuum\anaconda3\envs\myenv\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 15:55:12: Adding hash for 2 = 33d6a4e9a2bd with 1 lines
Info 15:55:12: Cell 2 executed with state Success
Info 15:55:12: Finished execution for 12345678-04e7-4a06-8e8e-12345678b2fd
```

</p>
</details>

**Comment by kwikwag** [comment] 2022-01-09 14:22
I should add that I often need to display ~40 plots. In this case the delay is of several minutes after execution is complete.

**Comment by greazer** [comment] 2022-01-10 21:12
This looks like a dupe of microsoft/vscode#140116

**Closed by greazer** 2022-01-10 21:12 UTC
Labels: bug, needs-triage

**Comment by kwikwag** [comment] 2022-01-12 16:37
The duplicate is filed under vscode, while I believe this to be a problem specific to Jupyter. @greazer can you comment on this?
