### ISSUE TITLE
Dataframe columns autocomplete doesn't work in interactive window after extension update (jupytext mode)

### ISSUE THREAD

**Issue by yopparai** [microsoft/vscode-jupyter#6995] opened 2021-08-07 09:47 UTC
Issue Type: <b>Bug</b>

---
![image](https://user-images.githubusercontent.com/55656303/128596127-4fffe654-b50e-4c5b-a7eb-00d47dca6902.jpg)
<details>
<summary>Code</summary>

```python
# %%
import pandas as pd

# %%
df = pd.DataFrame(
    {
        "firstname": [1, 2, 3],
        "lastname": [1, 2, 3],
        'patronymic': [1, 2, 3]
    }
)

# %%
df
```
</details>

---

Extension version: 2021.8.1195043623
VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:20.182Z)
OS version: Linux x64 5.8.0-63-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics (12 x 1722)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.08GB (0.50GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 417bce1b-d3f2-43a2-bf1b-e2eb11a9b3f6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30329788
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30346473

```

</details>

**Comment by greazer** [comment] 2021-08-07 16:56
Not 100% sure this is a regression. I'm assuming so at the moment.

**Comment by greazer** [comment] 2021-08-07 17:01
In the meantime while we're investigating, you can rollback to the old implementation with this setting:
```
    "jupyter.enableNativeInteractiveWindow": false
```

**Comment by yopparai** [comment] 2021-08-07 18:22
@greazer
Thanks for reply. Column autocomplete works fine in old implementation.

**Comment by janosh** [comment] 2021-08-07 18:48
The df column autocomplete was powered by Jupyter in the old webview: https://github.com/microsoft/vscode-jupyter/issues/1561#issuecomment-762983741. Maybe gives some hint about where the regression might have happened.

**Comment by greazer** [comment] 2021-09-20 20:39
Dupe of #7406

**Closed by greazer** 2021-09-20 20:39 UTC
Labels: bug, regression, interactive-window
