### ISSUE TITLE
Kernel state should persist across VS Code sessions

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#9949] opened 2022-05-09 06:48 UTC
Feedback from PyCon 2022

"Sometimes I have to reload VS Code, and other times I accidently close VS Code. And it's a bummer that kernel state doesn't persist between VS Code sessions. I lose all my variables and have to run my whole notebook again to test something out. I want VS Code to persist my kernel state until I tell it to restart my kernel."

**Comment by DonJayamanne** [comment] 2022-05-09 06:57
duplicate of #3998

**Closed by DonJayamanne** 2022-05-09 06:57 UTC
Labels: feature-request, triage-needed
