### ISSUE TITLE
IntelliSense doesn't work in Insiders for basic ipynb and miniconda

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-jupyter#6124] opened 2021-06-04 01:30 UTC
## Environment data

-   VS Code version:

```
Version: 1.57.0-insider
Commit: a62df5d6c53e844bfdc50694f943c3f34b6ff50e
Date: 2021-06-03T17:36:36.265Z (7 hrs ago)
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.902307158
-   Python Extension version (available under the Extensions sidebar): v2021.6.850516022-dev
-   Python and/or Anaconda version: Python 3.8.3 64-bit (base: conda)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n/a
-   Jupyter server running: Local

## Expected behaviour

IntelliSense just works.

## Actual behaviour

No IntelliSense in a basic ipynb.

## Steps to reproduce:

1. Started from fresh VS Code install, Insiders and Release (with native notebooks enabled)
2. Installed extensions
3. Opened up a minimal Notebook
4. Set interpreter to miniconda installation
5. Tried to get arguments for `pd.read_csv(…`

Insiders: Broken
Release: Works

## Logs

Using Pylance:

```
Error 2021-06-03 18:27:48: Live Notebook not available for file:///Users/digitarald/repos/data/feedback/anaylsis.ipynb
```

Using _Jedi_:

```
Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process Traceback (most recent call last):

Warn 2021-06-03 18:26:15: StdErr from Kernel Process Traceback (most recent call last):

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     yield gen.maybe_future(handler(stream, idents, msg))

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     yield gen.maybe_future(handler(stream, idents, msg))

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     yield gen.maybe_future(handler(stream, idents, msg))

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 762, in run

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     value = future.result()

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     value = future.result()

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     value = future.result()

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     yielded = ctx_run(next, result)

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     yielded = ctx_run(next, result)

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     yielded = ctx_run(next, result)

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 583, in complete_request

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 583, in complete_request

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 583, in complete_request

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 360, in do_complete

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 360, in do_complete

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 360, in do_complete

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     return self._experimental_do_complete(code, cursor_pos)

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     return self._experimental_do_complete(code, cursor_pos)

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     return self._experimental_do_complete(code, cursor_pos)

Info 2021-06-03 18:26:15: [32mWidget Coordinator received IPyWidgets_msg_received
Info 2021-06-03 18:26:15: [32mWidget Coordinator received IPyWidgets_iopub_msg_handled
Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 385, in _experimental_do_complete

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 385, in _experimental_do_complete

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 385, in _experimental_do_complete

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     completions = list(_rectify_completions(code, raw_completions))

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     completions = list(_rectify_completions(code, raw_completions))

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     completions = list(_rectify_completions(code, raw_completions))

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 484, in rectify_completions

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 484, in rectify_completions

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 484, in rectify_completions

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     completions = list(completions)

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     completions = list(completions)

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     completions = list(completions)

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1818, in completions

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1861, in _completions

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     matched_text, matches, matches_origin, jedi_matches = self._complete(

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     matched_text, matches, matches_origin, jedi_matches = self._complete(

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     matched_text, matches, matches_origin, jedi_matches = self._complete(

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 2029, in _complete

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     completions = self._jedi_matches(

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     completions = self._jedi_matches(

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     completions = self._jedi_matches(

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     interpreter = jedi.Interpreter(

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     interpreter = jedi.Interpreter(

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     interpreter = jedi.Interpreter(

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__

Warn 2021-06-03 18:26:15: StdErr from Kernel Process   File "/Users/digitarald/miniconda3/lib/python3.8/site-packages/jedi/api/__init__.py", line 725, in __init__

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr:     super().__init__(code, environment=environment,

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process     super().__init__(code, environment=environment,

Warn 2021-06-03 18:26:15: StdErr from Kernel Process     super().__init__(code, environment=environment,

Info 2021-06-03 18:26:15: Python Daemon (pid: 27914): write to stderr: TypeError: __init__() got an unexpected keyword argument 'column'

Warn 2021-06-03 18:26:15: Kernel 27914 as possibly died, StdErr from Kernel Process TypeError: __init__() got an unexpected keyword argument 'column'

Warn 2021-06-03 18:26:15: StdErr from Kernel Process TypeError: __init__() got an unexpected keyword argument 'column'
```

</p>
</details>

**Comment by joyceerhl** [comment] 2021-06-04 01:38
By 'Release' do you mean VS Code stable 1.56.2?

We just fixed an issue with language server support for Python notebooks today: https://github.com/microsoft/vscode-python/pull/16385. That fix is in the Python extension. If you install this build of the Python extension, does IntelliSense work for you?  https://github.com/microsoft/vscode-python/suites/2904962837/artifacts/65133411

FWIW, installing that build of the Python extension, and the latest Insiders and Jupyter extension build off the Marketplace, works for me: 

![image](https://user-images.githubusercontent.com/30305945/120732705-993f4400-c49a-11eb-8eb9-ffefcfbe18e1.png)

If that doesn't just work, could you please let me know if you have a Python interpreter selected (using the Python: Select Interpreter command from the command palette, or the interpreter selector in the bottom left, after switching focus away from a notebook)? That is required for IntelliSense to work (as the language server needs to know which Python environment to evaluate module imports against).

**Comment by digitarald** [comment] 2021-06-04 15:52
> We just fixed an issue with language server support for Python notebooks today: microsoft/vscode-python#16385. That fix is in the Python extension. If you install this build of the Python extension, does IntelliSense work for you? https://github.com/microsoft/vscode-python/suites/2904962837/artifacts/65133411

Yes, that build works for me!

**Comment by joyceerhl** [comment] 2021-06-04 15:54
Perfect. I'll resolve this issue as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/6108. Thanks for the confirmation and for filing a bug @digitarald 😊

**Closed by joyceerhl** 2021-06-04 15:54 UTC
Labels: bug, info-needed
