### ISSUE TITLE
Kernel not updated with Python interpreter

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6643] opened 2021-07-12 23:05 UTC
## Environment data

-   VS Code version: 1.58
-   Jupyter Extension version: v2021.8.1013163132
-   Python Extension version: v2021.6.944021595
-   Pylance Extension version: v2021.7.2

## Steps to reproduce: 
1. Follow instructions here https://github.com/holoviz/holoviz/blob/master/doc/installation.rst *but* replace "anaconda-project run jupyter notebook" command with "anaconda-project run", followed by "code ."
2. Open "Setup" notebook 
3. Change Python interpreter to the provided holoviz one
4. Reload to resolve diagnostics
5. Try to select corresponding kernel  

## Expected behavior
Kernel to show up 

## Actual behavior
Kernel did not show up, required reload to show up

**Comment by rchiodo** [comment] 2021-08-31 19:03
Would this be a dupe of #5319

**Comment by DonJayamanne** [comment] 2021-09-01 15:52
Yup

**Closed by DonJayamanne** 2021-09-01 15:52 UTC
Labels: bug, kernel-enumeration
