### ISSUE TITLE
process of visual code are not getting closed automatically 

### ISSUE THREAD

**Issue by ofiryaish** [microsoft/vscode-jupyter#6936] opened 2021-08-01 13:49 UTC
Hello,

In continuing to this issue: #6738 , I mentioned that I found a problem with the closing process of the vscode-jupyter or with vscode in general, and you said that this should be a new issue

"
An additional problem - the notebook process is still running even if I close the notebook. I found myself with more than 20 python processes after finding it, and I had to close them manually. Why is there not a shutdown kernel feature as Jupyter original notebooks have?

_Originally posted by @ofiryaish in https://github.com/microsoft/vscode-jupyter/issues/6738#issuecomment-886223831_
"

In addition to all python processes that are not getting closed, I have multiple processes which are connected to the vscode and were not killed even after I close the vscode ssh connection like node, bash, tcsh, and even multiple sleep processes.
(I know that the process is connected to vscode from the file descriptors of the process /proc/<pid>/fd).
I'm using vscode using an ssh connection to a Linux server (Centos 7).

I found this problem very annoying since I end up with a lot of unwanted processes even when I end my work with vscode.
I'm aware that it might be that  this problem is behind vscode-jupyter, and it is connected to an upper layer of vscode

Thank you,
Ofir

**Comment by DavidKutu** [comment] 2021-08-02 18:57
Thanks for reporting @ofiryaish. Could you help us by giving us some repro steps? And also please share your info from `Help -> About` as well as your jupyter and python extension version.

Thanks in advance!

**Comment by greazer** [comment] 2021-08-02 21:06
This is a dupe of another linux issue that has been entered.

**Comment by DavidKutu** [comment] 2021-08-02 21:09
Dupe of #5225

**Comment by ofiryaish** [comment] 2021-08-02 21:11
@DavidKutu, here is the about image:

![image](https://user-images.githubusercontent.com/17110771/127924098-faf15620-77eb-4652-b32a-92c275a61a92.png)


I'm using the latest version of your Jupyter , how do I find its version?

**Comment by ofiryaish** [comment] 2021-08-02 21:15
@DavidKutu 
I don't think that this is a duplicate of #5225. 
#5225 is about a known problem that I also have but it is not similar to this one. This problem arises with the latest version, and it is not connected to the GPU.

**Comment by ofiryaish** [comment] 2021-08-02 21:22
Can you please open this issue?

**Comment by DonJayamanne** [comment] 2021-10-11 21:50
@ofiryaish I'm sorry for no looking into this issue.
I'd like to take a look into this and start by replicating this at my end.
Please could you provide instructions used to repro this issue with the following info:
* OS
* Python version
* VS Code, Jupyter Extension Version
* Sample code (minimal repro)

**Comment by rchiodo** [comment] 2021-11-05 16:27
This should be a dupe of #5225. Remote SSH is running the extension host on a linux machine.

**Closed by rchiodo** 2021-11-05 16:27 UTC
Labels: bug, info-needed, notebook-kernel
