### ISSUE TITLE
Run by line not working

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-jupyter#7467] opened 2021-09-08 21:36 UTC
## Environment data

-   VS Code version: 1.61.0
-   Jupyter Extension version (available under the Extensions sidebar): 2021.9.1001208778
-   Python Extension version (available under the Extensions sidebar): 2021.9.1191016588
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.22000
-   Python and/or Anaconda version: Conda 4.10.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

Clicking "Run by line" runs the code in the cell by line.

## Actual behaviour

After running through one time, run by line does nothing on subsequent attempts.

## Steps to reproduce:

1. Clone https://github.com/claudiaregio/data-science
2. Execute "Run By Line" on cell 30 (works)
3. Execute run by line on cell 37 (does not appear to work)

https://user-images.githubusercontent.com/686963/132588914-33743476-a602-4d96-badf-f77892e3b7cc.mp4

**Comment by rchiodo** [comment] 2021-09-08 21:55
Thanks for the bug. I get this same problem too.

**Comment by DavidKutu** [comment] 2021-09-23 18:36
Dupe of #7586

**Closed by DavidKutu** 2021-09-23 18:36 UTC
Labels: bug, run-by-line, nb-golden
