### ISSUE TITLE
Cell output slash highlight/hyperlinking not useful / confusing / broken

### ISSUE THREAD

**Issue by youurayy** [microsoft/vscode-jupyter#12850] opened 2023-02-15 14:26 UTC
## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: Darwin arm64 22.2.0
-   Python and/or Anaconda version: Python 3.8.16
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): miniconda
-   Jupyter server running: Local

## Expected behaviour

Do not think that everything starting with a slash is a path a needs to be made a hyperlink. Simply leave it as it was (do not highlight/hyperlink) or provide a new setting, default off.

## Actual behaviour

Example of a hyperlinking which isn't useful:
![image](https://user-images.githubusercontent.com/588573/219052946-8a9331c0-18f9-47bd-b473-44a4902d55c5.png)

Example of a path hyperlinking which is broken:
![image](https://user-images.githubusercontent.com/588573/219053412-b854fff2-3551-4ebd-858f-42d6c9dde592.png)

Example of a hyperlinking which isn't useful:
![image](https://user-images.githubusercontent.com/588573/219053549-ffbfc44c-7a00-4a83-842e-b391dd970bc1.png)

## Steps to reproduce:

Produce cell output as in above screenshots, e.g. via `print('some/thing')`

**Comment by JasonGross** [comment] 2023-09-12 22:45
Related to https://github.com/microsoft/vscode-jupyter/issues/12975?  Also maybe now fixed?

**Comment by amunger** [comment] 2023-09-12 22:54
I would guess `print('../dir/file.txt')` still renders incorrectly on linux. We also still don't have a way to disable link highlighting

**Comment by amunger** [comment] 2023-12-12 16:54
with https://github.com/microsoft/vscode/pull/200577, filepath linking can be disabled: `"notebook.output.linkifyFilePaths": false`.
In insiders now, and will be in the January release.
closing as duplicate of https://github.com/microsoft/vscode/issues/181922

**Closed by amunger** 2023-12-12 16:54 UTC
Labels: bug, notebook-output
