### ISSUE TITLE
Kernel dies when run from Docker container

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#8670] opened 2022-01-11 15:47 UTC
## Environment data

-   VS Code version: 1.63.2 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: macOS 12.0.1
-   Python and/or Anaconda version: 3.8.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Jupyter should connect to kernel when selected and run.

## Actual behaviour

Jupyter attempts to connect with the following error:

```
Failed to start the Kernel. qemu: uncaught target signal 6 (Aborted) - core dumped. View Jupyter log for further details.
```

## Steps to reproduce:

- Create Docker image with Python
- Run it and connect from VS Code
- Execute code in Jupyter notebook with Jupyter extension installed

## Logs
```
Jupyter Extension Version: 2021.11.1001550889.
Python Extension Verison: 2021.12.1559732655.
Info 15:41:18: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 15:41:18: ZMQ install verified.
Info 15:41:18: Old kernelspecs (created by Jupyter extension) stored in directory /Users/cfonnesbeck/Library/Jupyter/kernels/__old_vscode_kernelspecs
Info 15:41:20: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 15:41:25: Creating controller for interactive with interpreter /usr/bin/python3
Info 15:41:25: Starting interactive window with controller ID ms-toolsai.jupyter/.jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher (Interactive)
Info 15:41:25: Setting setActiveController for vscode-interactive:Interactive-1.interactive
Info 15:41:26: Process Execution: > /usr/bin/python3 -m pip list
> /usr/bin/python3 -m pip list
Info 15:41:27: Starting Notebook in kernel.ts id = .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher
Info 15:41:27: Creating raw notebook for vscode-interactive:Interactive-1.interactive
Info 15:41:27: Getting preferred kernel for vscode-interactive:Interactive-1.interactive
Info 15:41:27: Computing working directory vscode-interactive:Interactive-1.interactive
Info 15:41:27: Process Execution: > /usr/bin/python3 -c "import pip"
> /usr/bin/python3 -c "import pip"
Info 15:41:28: Starting raw kernel Python 3.9.5 64-bit
Info 15:41:28: installMissingDependencies /usr/bin/python3
Info 15:41:28: IPykernel found previously in this enviornment /usr/bin/python3
Info 15:41:28: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 15:41:28: Launching kernel daemon for Python 3.9.5 64-bit # /usr/bin/python3
Info 15:41:28: No custom variables for Kernel as interpreter is not conda, but is Global
Info 15:41:29: Creating daemon process for /usr/bin/python3 with env variables count 0
Info 15:41:29: Process Execution: > /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/bin/python3 -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 15:41:31: Starting kernel from scratch
Warn 15:41:32: StdErr from Kernel Process /usr/bin/python3: No module named ipykernel_launcher

Error 15:41:32: Kernel died [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /usr/bin/python3: No module named ipykernel_launcher....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/usr/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/usr/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/usr/bin/python3: No module named ipykernel_launcher\n'
} /usr/bin/python3: No module named ipykernel_launcher

Error 15:41:32: KernelProcess Exit Exit - 1, /usr/bin/python3: No module named ipykernel_launcher
 [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /usr/bin/python3: No module named ipykernel_launcher....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/usr/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/usr/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/usr/bin/python3: No module named ipykernel_launcher\n'
}
Error 15:41:32: Disposing kernel process due to an error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /usr/bin/python3: No module named ipykernel_launcher....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/usr/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/usr/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/usr/bin/python3: No module named ipykernel_launcher\n'
}
Error 15:41:32: /usr/bin/python3: No module named ipykernel_launcher

Info 15:41:32: Dispose Kernel process
Info 15:41:32: kill daemon
Error 15:41:32: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /usr/bin/python3: No module named ipykernel_launcher....
Error 15:41:32: failed to create INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /usr/bin/python3: No module named ipykernel_launcher....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/usr/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/usr/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/usr/bin/python3: No module named ipykernel_launcher\n'
}
Error 15:41:32: failed to start INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /usr/bin/python3: No module named ipykernel_launcher....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/usr/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/usr/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/usr/bin/python3: No module named ipykernel_launcher\n'
}
Error 15:41:32: DataScience Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /usr/bin/python3: No module named ipykernel_launcher....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/usr/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/usr/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/usr/bin/python3: No module named ipykernel_launcher\n'
}
Error 15:41:32: DataScience Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /usr/bin/python3: No module named ipykernel_launcher....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/usr/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/usr/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/usr/bin/python3: No module named ipykernel_launcher\n'
}
Info 15:41:33: Process Execution: > /usr/bin/python3 -c "import ipykernel"
> /usr/bin/python3 -c "import ipykernel"
Info 15:41:33: installMissingDependencies /usr/bin/python3
Info 15:41:34: Process Execution: > /usr/bin/python3 -c "import ipykernel"
> /usr/bin/python3 -c "import ipykernel"
Info 15:41:34: Process Execution: > /usr/bin/python3 -c "import pip"
> /usr/bin/python3 -c "import pip"
Info 15:41:36: Registering dummy command feature
Info 15:41:39: Disposing kernel .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher for notebook vscode-interactive:Interactive-1.interactive due to selection of another kernel or closing of the notebook
Info 15:41:39: Dispose kernel file:///var/repos/pie_live/research/projections/src/pitchers/ageing_curves.py
Info 15:41:39: Setting setActiveController for vscode-interactive:Interactive-1.interactive
Info 15:41:39: IPyWidgetScriptSource.initialize
Error 15:41:39: Install Missing Dependencies, Class name = k, completed in 5503ms, has a falsy return value, Return Value: undefined [i [Error]: IPyKernel not installed into interpreter Python 3.9.5 64-bit:/usr/bin/python3
	at k.handleKernelDependencyResponse (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1242890)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async k.installMissingDependencies (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1241900)] {
  category: 'noipykernel',
  reason: 3
}
Error 15:41:39: DataScience Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /usr/bin/python3: No module named ipykernel_launcher....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/usr/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/usr/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/usr/bin/python3: No module named ipykernel_launcher\n'
}
Info 15:41:39: Starting Notebook in kernel.ts id = .jvsc74a57bd0949777d72b0d2535278d3dc13498b2535136f6dfe0678499012e853ee9abcab1./usr/local/python./usr/local/python.-m#ipykernel_launcher
Info 15:41:39: Creating raw notebook for vscode-interactive:Interactive-1.interactive
Info 15:41:39: Getting preferred kernel for vscode-interactive:Interactive-1.interactive
Info 15:41:39: Computing working directory vscode-interactive:Interactive-1.interactive
Info 15:41:39: Starting raw kernel Python 3.8.9 64-bit
Info 15:41:39: installMissingDependencies /usr/local/bin/python
Info 15:41:39: IPykernel found previously in this enviornment /usr/local/bin/python
Info 15:41:39: Kernel launching with ports 9008,9009,9010,9011,9012. Start port is 9000
Info 15:41:40: Launching kernel daemon for Python 3.8.9 64-bit # /usr/local/bin/python
Info 15:41:40: No custom variables for Kernel as interpreter is not conda, but is Global
Info 15:41:42: Creating daemon process for /usr/local/bin/python with env variables count 66
Info 15:41:42: Process Execution: > /usr/local/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 15:41:42: Process Execution: > /usr/local/bin/python -m pip list
> /usr/local/bin/python -m pip list
Info 15:41:47: Starting kernel from scratch
Info 15:41:51: Registering dummy command feature
Warn 15:42:12: StdErr from Kernel Process Operation not permitted (src/thread.cpp:309)

Warn 15:42:12: StdErr from Kernel Process qemu: uncaught target signal 6 (Aborted) - core dumped

Error 15:42:12: Kernel died [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: qemu: uncaught target signal 6 (Aborted) - core dumped....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: 'qemu: uncaught target signal 6 (Aborted) - core dumped. \n',
  stdErr: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n',
  exitCode: -6,
  reason: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n'
} Operation not permitted (src/thread.cpp:309)
qemu: uncaught target signal 6 (Aborted) - core dumped

Error 15:42:12: KernelProcess Exit Exit - -6, Operation not permitted (src/thread.cpp:309)
qemu: uncaught target signal 6 (Aborted) - core dumped
 [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: qemu: uncaught target signal 6 (Aborted) - core dumped....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: 'qemu: uncaught target signal 6 (Aborted) - core dumped. \n',
  stdErr: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n',
  exitCode: -6,
  reason: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n'
}
Error 15:42:12: Disposing kernel process due to an error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: qemu: uncaught target signal 6 (Aborted) - core dumped....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: 'qemu: uncaught target signal 6 (Aborted) - core dumped. \n',
  stdErr: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n',
  exitCode: -6,
  reason: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n'
}
Error 15:42:12: Operation not permitted (src/thread.cpp:309)
qemu: uncaught target signal 6 (Aborted) - core dumped

Info 15:42:12: Dispose Kernel process
Info 15:42:12: kill daemon
Error 15:42:12: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: qemu: uncaught target signal 6 (Aborted) - core dumped....
Error 15:42:12: failed to create INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: qemu: uncaught target signal 6 (Aborted) - core dumped....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: 'qemu: uncaught target signal 6 (Aborted) - core dumped. \n',
  stdErr: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n',
  exitCode: -6,
  reason: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n'
}
Error 15:42:12: failed to start INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: qemu: uncaught target signal 6 (Aborted) - core dumped....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: 'qemu: uncaught target signal 6 (Aborted) - core dumped. \n',
  stdErr: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n',
  exitCode: -6,
  reason: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n'
}
```
</p>
</details>

**Comment by rchiodo** [comment] 2022-01-11 17:29
Thanks for the issue. My guess is this is the root cause:

```
Info 15:41:28: IPykernel found previously in this enviornment /usr/bin/python3
```

We cached the fact that ```/usr/bin/python3``` already has ipykernel installed in it. Your docker container doesn't as evidenced by this here:

```
Error: /usr/bin/python3: No module named ipykernel_launcher....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: '/usr/bin/python3: No module named ipykernel_launcher. \n',
  stdErr: '/usr/bin/python3: No module named ipykernel_launcher\n',
  exitCode: 1,
  reason: '/usr/bin/python3: No module named ipykernel_launcher\n'
}
```

You should be able to workaround this bug by installing ipykernel yourself on the docker container. This command here would install it into the environment you're using:

```
/usr/bin/python3 -m pip install ipykernel
```
Just make sure to run it inside the docker container and not on your local machine.


Alternatively, you could try deleting your global storage cache. On LINUX I believe that is here:

```
$HOME/.config/Code/User/GlobalStorage
```

**Comment by fonnesbeck** [comment] 2022-01-11 19:59
OK, I think I sorted that out. Its now hitting /usr/local/bin/python which is what gets provisioned by the Dockerfile I am using. `ipykernel` is there, but I still get a kernel dump:

```
Jupyter Extension Version: 2021.11.1001550889.
Python Extension Verison: 2021.12.1559732655.
Info 19:54:47: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 19:54:47: ZMQ install verified.
Info 19:54:48: Old kernelspecs (created by Jupyter extension) stored in directory /Users/cfonnesbeck/Library/Jupyter/kernels/__old_vscode_kernelspecs
Info 19:54:50: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 19:54:53: Process Execution: > /usr/local/bin/python -m pip list
> /usr/local/bin/python -m pip list
Info 19:54:57: Creating controller for interactive with interpreter /usr/local/bin/python
Info 19:54:57: Starting interactive window with controller ID ms-toolsai.jupyter/.jvsc74a57bd0949777d72b0d2535278d3dc13498b2535136f6dfe0678499012e853ee9abcab1./usr/local/python./usr/local/python.-m#ipykernel_launcher (Interactive)
Info 19:54:57: Setting setActiveController for vscode-interactive:Interactive-1.interactive
Info 19:54:59: Starting Notebook in kernel.ts id = .jvsc74a57bd0949777d72b0d2535278d3dc13498b2535136f6dfe0678499012e853ee9abcab1./usr/local/python./usr/local/python.-m#ipykernel_launcher
Info 19:54:59: Creating raw notebook for vscode-interactive:Interactive-1.interactive
Info 19:54:59: Getting preferred kernel for vscode-interactive:Interactive-1.interactive
Info 19:54:59: Computing working directory vscode-interactive:Interactive-1.interactive
Info 19:55:00: Starting raw kernel Python 3.8.9 64-bit
Info 19:55:00: installMissingDependencies /usr/local/bin/python
Info 19:55:00: IPykernel found previously in this enviornment /usr/local/bin/python
Info 19:55:00: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 19:55:00: Launching kernel daemon for Python 3.8.9 64-bit # /usr/local/bin/python
Info 19:55:00: No custom variables for Kernel as interpreter is not conda, but is Global
Info 19:55:03: Creating daemon process for /usr/local/bin/python with env variables count 66
Info 19:55:03: Process Execution: > /usr/local/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 19:55:06: Starting kernel from scratch
Info 19:55:12: Registering dummy command feature
Warn 19:55:23: StdErr from Kernel Process Operation not permitted (src/thread.cpp:309)

Warn 19:55:23: StdErr from Kernel Process qemu: uncaught target signal 6 (Aborted) - core dumped

Error 19:55:23: Kernel died [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: qemu: uncaught target signal 6 (Aborted) - core dumped....
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:1023351
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:695951
	at /root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:696169
	at Immediate._onImmediate (/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.11.1001550889/out/client/extension.js:66:697734)
	at processImmediate (internal/timers.js:461:21)] {
  category: 'kerneldied',
  errorMessage: 'qemu: uncaught target signal 6 (Aborted) - core dumped. \n',
  stdErr: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n',
  exitCode: -6,
  reason: 'Operation not permitted (src/thread.cpp:309)\n' +
    'qemu: uncaught target signal 6 (Aborted) - core dumped\n'
} Operation not permitted (src/thread.cpp:309)
qemu: uncaught target signal 6 (Aborted) - core dumped
```

**Comment by fonnesbeck** [comment] 2022-01-11 20:02
I should note that this is an M1 Mac. Not sure if that could be part of the problem.

**Comment by rchiodo** [comment] 2022-01-11 20:04
Can you run jupyter from this environment if you install it?

```
/usr/bin/python3 -m pip install jupyter
```
It looks like the kernel is still dying. Running it with jupyter might give you more data as to why.

**Comment by rchiodo** [comment] 2022-01-11 20:06
Ah looks like this error:
https://github.com/docker/for-mac/issues/6097

May not be supported on mac.

**Comment by fonnesbeck** [comment] 2022-01-11 20:08
Yep, looks like that's the issue. Thanks for finding that.

Installing and running jupyter does indeed work, though.

**Comment by rchiodo** [comment] 2022-01-11 20:10
If jupyter runs in the container and you can see ports on the container from your mac, you can use [remote](https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_connect-to-a-remote-jupyter-server) jupyter support instead.

**Comment by fonnesbeck** [comment] 2022-01-11 20:16
Sadly, I get a core dump using remote jupyter support as well:

```
/127.0.0.1:8888/?token=b232736a7efbb692fda4bd3b4a5afefe4821bafdedc116dc
[I 20:12:55.438 NotebookApp] 302 GET / (127.0.0.1) 5.940000ms
[I 20:12:55.476 NotebookApp] 302 GET /tree? (127.0.0.1) 5.770000ms
[I 20:15:03.428 NotebookApp] Creating new notebook in 
[I 20:15:03.659 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
Operation not permitted (src/thread.cpp:309)
Operation not permitted (src/thread.cpp:309)
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```

**Comment by rchiodo** [comment] 2022-01-11 21:25
Then I'd say jupyter just doesn't work on the container. Running with remote should be the same as using the browser (at least talking to the kernel is).

**Comment by greazer** [comment] 2022-01-13 21:07
Per Rich, sounds like the container is unable to run the Jupyter kernel. So closing this. Thanks for the feedback!

**Closed by greazer** 2022-01-13 21:07 UTC
Labels: bug, kernel-enumeration, kernel-crash, notebook-remote, needs-triage, kernel-management
