### ISSUE TITLE
How to keep kernel alive after closing the vscode window

### ISSUE THREAD

**Issue by NeonYYYYY** [microsoft/vscode-jupyter#15707] opened 2024-05-23 07:52 UTC
keep the code running after closing the vscode window, keep the kernel alive until I proactively shut down

**Comment by timsu92** [comment] 2024-05-25 07:53
This suggest is especially useful when using jupyter notebook over SSH over unhealthy network. If we can leave it running and connect back later, we don't need to worry about poor networks!

**Comment by DonJayamanne** [comment] 2024-07-22 01:14
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/3998
@NeonYYYYY @timsu92 Please upvote the above issue (please upvote the top issue, not towards the bottom)

**Closed by DonJayamanne** 2024-07-22 01:14 UTC
Labels: feature-request
