### ISSUE TITLE
can't set notebook css variables with jupyter.runStartupCommands

### ISSUE THREAD

**Issue by sadguitarius** [microsoft/vscode-jupyter#11504] opened 2022-10-02 18:34 UTC
## Environment data

-   VS Code version: 1.71.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1002511105
-   Python Extension version (available under the Extensions sidebar): v2022.15.12731017
-   OS and version: Windows 11 21H2 22000.1042
-   Python and/or Anaconda version: 3.10.6
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

"jupyter.runStartupCommands" should be able to style the notebook with CSS code using the IPython.core.display module.

## Actual behaviour

The notebook's style does not change.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. add to settings.json:
```
  "jupyter.runStartupCommands": [
    "from IPython.core.display import HTML",
    "HTML('''",
    "<style>",
    ".cell-output-ipywidget-background {",
    "background-color: transparent !important;",
    "}",
    ".widget-label {",
    "color: white !important;",
    "}",
    ".widget-readout {",
    "color: white !important;",
    "}",
    "</style>''')"
  ],
```

2. try running a notebook cell containing the following (test case to fix widget appearance with VSCode dark theme):
```
import ipywidgets as widgets

widgets.IntSlider(
    min=0,
    max=10,
    step=1,
    description='Slider:',
    value=3
)
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
info 11:27:02.223: Restart requested file:///c%3A/Users/sadguitarius/dev/notebooks/scratch/widget%20tests.ipynb
info 11:27:02.224: Restart kernel execution
info 11:27:02.224: Restarting 4b838e45-e190-4b68-b9e8-50edc67d73a0
info 11:27:02.226: Got env vars with python c:\Users\sadguitarius\.local\opt\mambaforge\envs\sg\python.exe, with env var count 84 and custom env var count 0 in 2ms
info 11:27:02.230: Process Execution: > ~\.local\opt\mambaforge\envs\sg\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\.local\opt\mambaforge\envs\sg\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 11:27:02.284: Got env vars with python c:\Users\sadguitarius\.local\opt\mambaforge\envs\sg\python.exe, with env var count 84 and custom env var count 0 in 2ms
info 11:27:02.284: Got env vars with python c:\Users\sadguitarius\.local\opt\mambaforge\envs\sg\python.exe, with env var count 84 and custom env var count 0 in 1ms
info 11:27:02.293: Process Execution: > ~\.local\opt\mambaforge\envs\sg\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"dd2615f9-7b91-4c1b-adc9-d70c2a9bd840" --shell=9007 --transport="tcp" --iopub=9009 --f=c:\Users\sadguitarius\AppData\Roaming\jupyter\runtime\kernel-v2-32948zCsk0Uqfs32t.json
> ~\.local\opt\mambaforge\envs\sg\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"dd2615f9-7b91-4c1b-adc9-d70c2a9bd840" --shell=9007 --transport="tcp" --iopub=9009 --f=c:\Users\sadguitarius\AppData\Roaming\jupyter\runtime\kernel-v2-32948zCsk0Uqfs32t.json
info 11:27:02.293: Process Execution: cwd: ~\dev\notebooks\scratch
cwd: ~\dev\notebooks\scratch
info 11:27:02.608: ipykernel version & path 6.16.0, ~\.local\opt\mambaforge\envs\sg\lib\site-packages\ipykernel\__init__.py for c:\Users\sadguitarius\.local\opt\mambaforge\envs\sg\python.exe
info 11:27:03.530: Kernel Output: To connect another client to this kernel, use: --existing c:\Users\sadguitarius\AppData\Roaming\jupyter\runtime\kernel-v2-32948zCsk0Uqfs32t.json

info 11:27:03.649: Got new session 5894b570-7e27-4d33-97b7-e7281ea93fed
info 11:27:03.649: Started new restart session
info 11:27:03.649: Dispose Kernel process 37968.
warn 11:27:03.806: 2022-10-02 11:27:03,804 UTC - WARNING - Unknown command: DISPOSE_INTERRUPT_HANDLE:2:1836

info 11:27:03.883: UpdateWorkingDirectoryAndPath in Kernel
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2022-10-02 22:19
Thanks for filing this issue, unfortunately outputs of startup comments are not processed to inject HTML/CSS content.
This is because there's no visible cell, hence we don't have any place to add the output when such commands run.
These startup commands are supported today as a means to initialize the kernel state, and not the uI state.

Closing this as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/7161 (which I believe is what you're trying to work around)

**Closed by DonJayamanne** 2022-10-02 22:19 UTC
Labels: bug
