### ISSUE TITLE
multiple kernel management

### ISSUE THREAD

**Issue by X-Chen97** [microsoft/vscode-jupyter#4023] opened 2020-11-25 03:17 UTC
Hi! Why are there so many repeated kernels in my vscode? Is there a good way to manage them(delete or add new kernels)? Thanks!
![image](https://user-images.githubusercontent.com/54193597/100178770-78fa5100-2e89-11eb-8d68-c50230cd7322.png)
![image](https://user-images.githubusercontent.com/54193597/100178827-93ccc580-2e89-11eb-8535-41e194d40b38.png)

**Comment by DonJayamanne** [comment] 2020-11-25 16:11
We must python environments as kernels, this way you don't need to install Jupyter to install a kernel.

We'll look into removing the duplicates

If you would like to remove some items then you could:
* Remove some of the python environments
* If you have Jupyter installed then you can remove some Jupyter kernel specs. See here to find where they are located https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs

**Comment by DonJayamanne** [comment] 2020-11-25 17:18
Labelling as a bug to ensure we hide the duplicate items:
* `pytorch_env` is duplicated 3 times

**Comment by DonJayamanne** [comment] 2020-11-25 17:22
@X-Chen97 
Please could you try the following:
* Open a python file, and on the bottom left of VS Code statusbar you will find the interpreter information displayed.
    * Please click that item
	* Take a screenshot of the list of interpreters displayed (it will be similar to what you see above).
* Open your terminal, activate your base conda environment
	* Type in `conda env list`
	* I'm curious about the last 2 entries in your list.
* Finally, please type the following command in your terminal after activating the base conda environbment
	`jupyter kernelspec list` (this might not work, doesn't matter if it fails)

**Comment by IanMatthewHuff** [comment] 2020-11-25 17:27
@DonJayamanne I believe the duplicates might be a semi-recent regression. I believe that I've seen them as well. Let me check my local bits and see if I'm still seeing them.

**Comment by X-Chen97** [comment] 2020-11-25 17:53
> @DonJayamanne I believe the duplicates might be a semi-recent regression. I believe that I've seen them as well. Let me check my local bits and see if I'm still seeing them.

**Comment by X-Chen97** [comment] 2020-11-25 18:02
@DonJayamanne here you are


> Open a python file, and on the bottom left of VS Code statusbar you will find the interpreter information displayed.


![image](https://user-images.githubusercontent.com/54193597/100264898-4b062280-2f04-11eb-8828-75992930cac8.png)
![image](https://user-images.githubusercontent.com/54193597/100264955-607b4c80-2f04-11eb-8259-cd728a1d96e1.png)

> Open your terminal, activate your base conda environment

![image](https://user-images.githubusercontent.com/54193597/100265047-830d6580-2f04-11eb-9442-2d10c56fddf2.png)

> Finally, please type the following command in your terminal after activating the base conda environbment

![image](https://user-images.githubusercontent.com/54193597/100265119-9e787080-2f04-11eb-8d3c-6b0fe24a9619.png)

Actually I added the kernels from different envs to the jupyter manually before, with the command: `python -m ipykernel install --user --name MLproject --display-name MLproject`. This works well when I use the browser to open a jupyter notebook, but not sure whether this causes the bug in vscode.

**Comment by DonJayamanne** [comment] 2020-11-26 01:03
I know I've added some additional logging in the kernel finder & fixed some duplicates there as well.
We were looking for kernels in current interpreter & all interprters (all interpreters already includes current interpreter).

However, I tested this & I too can see some dups.
Dups in Native & WebView notebooks (but different dups).
Should eliminate dups in the finder so both notebooks & interactive window get a unique & the exact same set.

**Comment by DonJayamanne** [comment] 2020-11-26 01:06
@X-Chen97 Please could you:
* Install the attached Jupyter VSIX (its a dev version of the extension)
* Enable debug logging (go into settings `Jupyter->Logging` & select `debug`
* Reload VS Code
* Bring up the kernel picker
* Go into the `Jupyter` output panel & copy everything & paste it here on the issue
(if the contents are too large, please copy into a file & upload file here).

Here is the VSIX
[ms-toolsai-jupyter-insiders-dev.vsix.zip](https://github.com/microsoft/vscode-jupyter/files/5599878/ms-toolsai-jupyter-insiders-dev.vsix.zip)

**Comment by IanMatthewHuff** [comment] 2021-01-12 18:43
@DonJayamanne I'm still seeing duplicates in my list. 
![image](https://user-images.githubusercontent.com/812783/104358129-e1959f80-54c2-11eb-813a-e2ad1b89d325.png)
Want me to take a look since I have the repro?

**Comment by DonJayamanne** [comment] 2021-01-12 22:18
Yes, please do

**Comment by DonJayamanne** [comment] 2021-01-12 22:19
Please let me know what's wrong, possible I have the fix in my existing PR

**Comment by DonJayamanne** [comment] 2021-01-21 16:20
@IanMatthewHuff are you still reproing this issue

**Comment by IanMatthewHuff** [comment] 2021-01-21 16:23
@DonJayamanne Yes, I'm still seeing it. Sorry have been too behind to look yet. I'll look today if I can free a cycle or two.

**Comment by IanMatthewHuff** [comment] 2021-01-22 23:37
![image](https://user-images.githubusercontent.com/812783/105559489-293bd880-5cc6-11eb-92fc-b6538bd813df.png)

![image](https://user-images.githubusercontent.com/812783/105559895-42915480-5cc7-11eb-96d5-80559dc570e0.png)

So I imagine that that this is a pretty unlikely user case. I think that it mostly happened due to my old crufty dev box + the way that we used to register interpreters as kernels. But I have three different kernelspecs registered into my conda env. But they share the same display name. If the display name is the same we don't show anything to uniquely ID them. Doesn't seem pressing to fix as I can't see why someone would want to set this case up. Only happened to me since our old code reregistered an interpreter as a kernel a few times.

**Comment by IanMatthewHuff** [comment] 2021-01-22 23:37
@DonJayamanne So close?

**Comment by DonJayamanne** [comment] 2021-01-23 00:48
Yes, i would say lets close this for now. Thanks

**Closed by DonJayamanne** 2021-01-23 00:48 UTC
Labels: bug, enhancement, info-needed
