### ISSUE TITLE
Improve Plot Viewer performance: Notebook file size becomes very large

### ISSUE THREAD

**Issue by dibliz** [microsoft/vscode-jupyter#458] opened 2020-06-17 09:34 UTC
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open "Preprocessing_LR.ipynb" notebook (attached [issue.zip](https://github.com/microsoft/vscode-python/files/4791526/issue.zip))
2. Run all cells
3. Save the notebook

## Actual behavior
Saved file has extremely large file size (100.6 Mb - see "Preprocessing_LR_vscode.ipynb" (attached [issue.zip](https://github.com/microsoft/vscode-python/files/4791526/issue.zip)))

## Expected behavior
The same file opened, runed and saved in Jupyter Notebook has size 404.6 Kb.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local
-   **Extension version:** 2020.6.88468
-   **VS Code version:** 1.46.0
-   **Setting python.languageServer:** Jedi
-   **Python and/or Anaconda version:** Python 3.7.6, Anaconda 2020.02
-   **OS:** Windows 10
-   **Virtual environment:** conda 

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by greazer** [comment] 2021-04-01 08:42
Dupe of #5059

**Closed by greazer** 2021-04-01 08:42 UTC
Labels: Epic, code-health
