### ISSUE TITLE
Cannot execute code, session has been disposed

### ISSUE THREAD

**Issue by Inrixia** [microsoft/vscode-jupyter#8440] opened 2021-12-03 01:29 UTC
## Environment data

-   VS Code version:
```
1.62.3
ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
x64
```
-   Jupyter Extension version (available under the Extensions sidebar): `v2021.10.1101450599`
-   Python Extension version (available under the Extensions sidebar): `v2021.11.1422169775`
-   OS (Windows | Mac | Linux distro) and version: `Windows10 Pro`
-   Python and/or Anaconda version: `Python 3.10.0`
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): `virtualenv `
-   Jupyter server running: Local | Remote | N/A `Unsure...`

## Expected behaviour

Code executes on spark cluster as seen in [Leverage IPYNB support from Python extension](https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/vscode-tool-synapse#leverage-ipynb-support-from-python-extension).

## Actual behaviour

First attempt at executing a cell gives `Canceled future for execute_request message before replies were done`.
Second attempt gives `Cannot execute code, session has been disposed.`

This worked once previously but I have not managed to get it to work since.
I have a collegue who has been encountering similar issues attempting to run code after following the [guide](https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/vscode-tool-synapse#leverage-ipynb-support-from-python-extension).

I found one other issue https://github.com/microsoft/vscode-jupyter/issues/3026 in relation to this, but @madHatter106 never replied so there is no fix or progress towards one listed on it.

## Steps to reproduce:

- Have/Setup a spark cluster on Azure Synapse
- Follow the [guide](https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/vscode-tool-synapse#leverage-ipynb-support-from-python-extension) to connect to a spark cluster on synapse.
- Attempt to run a notebook with the code:
```py
1+1
```
- ~~Profit?!~~ Get the above errors

## Logs
[vscode-app-1638493460454.log](https://github.com/microsoft/vscode-jupyter/files/7646130/vscode-app-1638493460454.log)

**Comment by amunger** [comment] 2021-12-03 18:35
Could you provide the jupyter logs that are generated while going through the repro steps (output window, select jupyter from the dropdown, and copy all contents of that window).

**Comment by Inrixia** [comment] 2021-12-03 23:15
No output is generated, just the error notifications

**Comment by Inrixia** [comment] 2021-12-04 02:17
Sure

[jupyterLogs.log](https://github.com/microsoft/vscode-jupyter/files/7653145/jupyterLogs.log)

**Comment by Inrixia** [comment] 2021-12-06 02:24
Let me know if you need any other info

**Comment by rchiodo** [comment] 2021-12-06 21:22
This is the root cause:

```
Info 2021-12-04 15:12:41: KernelProcess error: Traceback (most recent call last):
  File "C:\Users\Inrix\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Inrix\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\pysparkkernel\pysparkkernel.py", line 34, in <module>
    IPKernelApp.launch_instance(kernel_class=PySparkKernel)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
    app.initialize(argv)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\traitlets\config\application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\ipykernel\kernelapp.py", line 647, in initialize
    self.init_kernel()
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\ipykernel\kernelapp.py", line 499, in init_kernel
    kernel = kernel_factory(parent=self, session=self.session,
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\traitlets\config\configurable.py", line 540, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\pysparkkernel\pysparkkernel.py", line 26, in __init__
    super(PySparkKernel,
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\wrapperkernel\sparkkernelbase.py", line 47, in __init__
    self._load_magics_extension()
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\wrapperkernel\sparkkernelbase.py", line 75, in _load_magics_extension
    self._execute_cell(register_magics_code, True, False, shutdown_if_error=True,
  File "C:\Users\Inrix\.msvscode.hdinsight\hdinsightJupyter\lib\site-packages\sparkmagic\kernels\wrapperkernel\sparkkernelbase.py", line 107, in _execute_cell
    if shutdown_if_error and reply_content[u"status"] == u"error":
TypeError: 'coroutine' object is not subscriptable
```

The pyspark team would likely have more information on how to address this issue. Transferring.

**Closed** 2021-12-06 21:24 UTC
Labels: bug, info-needed, needs-triage
