### ISSUE TITLE
VS code v1.93.1 no longer clears ipynb notebook execution counts

### ISSUE THREAD

**Issue by wietzesuijker** [microsoft/vscode-jupyter#16052] opened 2024-09-16 10:13 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

After updating VS code to the latest version (1.93.1) it no longer clears execution counts from notebook cells with the `clear all outputs` button. It seems to do this in the GUI, but the cell's execution counts remain untouched in the raw file.

Can be reproduced by opening a new notebook in vs code v1.93.1, running some cells and clearing all outputs. When re-opening the file / inspecting it with a text editor or git diff, the execution counts remain visible.

### VS Code Version

1.93.1

### Jupyter Extension Version

2024.7.0

### Coding Language and Runtime Version

Python 3.11

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment] 2024-09-17 17:47
easy repro:
execute a cell, note the execution count
clear all outputs
execute the cell again, execution count does not start over

**Comment by SmallhillCZ** [comment] 2024-09-18 08:39
duplicate of https://github.com/microsoft/vscode-jupyter/issues/15266

**Comment by amunger** [comment] 2024-09-18 15:51
thanks @SmallhillCZ, confirmed not a regression in 1.93

**Comment by DonJayamanne** [comment] 2024-10-21 02:41
Steps to repro
* Create a Jupyter notebook
* Add two cells
    * First cell `import sys`
    * Second cell `print("Hello World")`
* Run both cells (`Run All`)
* Clear outputs
* Open the ipynb as plain text and verify that the `execution_count` is `null` for both cells.
*

**Comment by DonJayamanne** [comment] 2024-10-21 04:56
This should be fixed in tomorrows version of VS Code Insiders.

**Closed by DonJayamanne** 2024-10-21 04:56 UTC
Labels: bug, notebook-serialization
