### ISSUE TITLE
Exported Python script from Notebook should have same title as Notebook

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-jupyter#7513] opened 2021-09-14 16:48 UTC
## Environment data

-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001228862
-   Python Extension version (available under the Extensions sidebar): v2021.9.1218897484
-   Python and/or Anaconda version: 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

Version: 1.61.0-insider (Universal)
Commit: ec40cbe164c59f3d13b6eff5fc7b0231ec0ab7aa
Date: 2021-09-13T05:13:59.036Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

## Problem

When I export a Python script from a Notebook I'd expect it to have the same name as the Notebook similar to exporting HTML or PDFs

26:10 of [video log](https://msit.microsoftstream.com/video/71920840-98dc-ae72-3a43-f1ec149ab77a)

**Comment by IanMatthewHuff** [comment] 2021-09-14 20:55
I think that @DonJayamanne mentioned at the meeting that we might need to be careful to not  overwrite default python modules with the exported .py, but it seems like a good suggestion to consider regardless.

**Comment by DonJayamanne** [comment] 2021-10-04 21:46
I don't think this is an issue, we never create any file, infact we create untitled files and let the user save them where ever they want.
This issue is actually asking for a change in workflow, its not a bug, we're now asking for files to be saved on disc instead of creating untitled files.

**Comment by tanhakabir** [comment] 2021-10-04 22:57
@DonJayamanne do you think it's a worser experience to create a file for disk rather than opening an untitled file? I personally found the weird to get `%% text` as a suggested name for the file when I hit save

**Comment by greazer** [comment] 2021-10-04 23:30
I agree with @DonJayamanne. This is the way VS Code deals with new files. Here's an example:

![image](https://user-images.githubusercontent.com/11685408/135937795-4c398c5e-61df-4674-9ff5-977774a6d7a2.png)

If anything perhaps the first line of the exported file should simply be something like:
```# Exported from mynotebook.ipynb```

That would at least provide a hint as to where the file came from.

**Comment by DonJayamanne** [comment] 2021-10-04 23:34
> s a worser experience to create a file for disk rather than opening an untitled file? I personally found the weird to get %% text as a suggested name for the file when I hit save

@tanhakabir  Aren't we trying to work around an issue with VS Code core using the text as the file name.
I.e you're experiencing issues with the default name & suggesting something to circumvent that problem. 

But then again, one could argue that the whole purpose of exporting is to save to a file.

**Comment by tanhakabir** [comment] 2021-10-05 00:48
My assumption was that it should match the HTML and PDF exports.

**Comment by IanMatthewHuff** [comment] 2021-11-09 20:38
@greazer @tanhakabir @DonJayamanne .

With the new default "direct" method of exporting we now just open the file as Untitled-1.py and that's the default save name. You'll only see that #%% text as a suggested name with the nbconvert option specifically selected. I'd say that what we have currently feels correct to me.

HTML and PDF match the file name with the new extension. .py opens an Untitled-1.py file that you can save and name. I'd like to close this issue, but down for hearing dissenting opinions :). @tanhakabir I think that you had different expectations here?

**Comment by tanhakabir** [comment] 2021-11-09 20:52
I did originally but I understand why my original expectations didn't match completely with expected behavior. I'm good to close this issue!

**Comment by IanMatthewHuff** [comment] 2021-11-09 21:12
@tanhakabir Awesome, just wanted to make sure I wasn't closing something down that you were keen on. Thanks for the quick reply.

**Closed by IanMatthewHuff** 2021-11-09 21:12 UTC
Labels: bug, papercut :drop_of_blood:, notebook-import-export, nb-golden
