### ISSUE TITLE
Jupyter ignore none .env PYTHONPATH settings during restart of a jupyter kernel

### ISSUE THREAD

**Issue by liubenyuan** [microsoft/vscode-jupyter#10848] opened 2022-07-18 07:55 UTC
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

I placed `windows.env` and `linux.env` in `.vscode` of current workspace. and point
```json
# settings.json
"python.envFile": "${workspaceFolder}/.vscode/windows.env",
```
where the `windows.env` contains the PYTHONPATH environment settings
```bash
# windows.env
PYTHONPATH = "D:/dhca/pyeit;D:/dhca/eitmesh;D:/dhca/pydhca"
# Jupyter: run all cells
# ctrl + alt + r
```

I then run the following cell using Jupyter
```python
# %% [markdown]
import sys

for p in sys.path:
    print(p)
```

It should print, and it do print these messages on the first run of the above script
```
d:\dhca\pydhca\scripts\tdimage\patent
D:\dhca\pyeit
D:\dhca\eitmesh
D:\dhca\pydhca
d:\Miniconda3\python38.zip
d:\Miniconda3\DLLs
d:\Miniconda3\lib
d:\Miniconda3

d:\Miniconda3\lib\site-packages
d:\Miniconda3\lib\site-packages\win32
d:\Miniconda3\lib\site-packages\win32\lib
d:\Miniconda3\lib\site-packages\Pythonwin
```

but if I restart the jupyter kernel, and rerun this script, the settings in `windows.env` are ignored, and the outputs are:
```
d:\dhca\pydhca\scripts\tdimage\patent
d:\Miniconda3\python38.zip
d:\Miniconda3\DLLs
d:\Miniconda3\lib
d:\Miniconda3

d:\Miniconda3\lib\site-packages
d:\Miniconda3\lib\site-packages\win32
d:\Miniconda3\lib\site-packages\win32\lib
d:\Miniconda3\lib\site-packages\Pythonwin
```
Note that line 2-4 in the `.vscode/windows.env` settings are missing.

## Steps to reproduce:

A workaround is always place the `.vscode/windows.env` at `.env`, then this problem is gone no matter how many times I restart the jupyter kernel. It seem that the jupyter extension always read the PYTHONPATH from `.env` not matter what I set `python.envFile` to.

PS: as windows and linux have different `os.pathsep`, can I place a cross platform `.env` file that favor both operating systems?
```bash
# .env
if windows:
    PYTHONPATH = "D:/dhca/pyeit;D:/dhca/eitmesh;D:/dhca/pydhca"
elif linux:
    PYTHONPATH = "~/dhca/pyeit:~/dhca/eitmesh:~/dhca/pydhca"
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

envFile: "<placeholder>"

condaPath: "<placeholder>"

languageServer: "Pylance"

linting
• flake8Enabled: true

formatting
• provider: "black"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true

```

</p>
</details>

Extension version: 2022.10.1
VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3707)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (11.50GB free)|
|Process Argv|--crash-reporter-id 611f7518-0998-41f4-886f-9073150b14ab|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdc:30486549

```

</details>

**Comment by DonJayamanne** [comment] 2022-07-18 19:32
Closing as a duplicate of #9691

**Closed by DonJayamanne** 2022-07-18 19:32 UTC
Labels: triage-needed
