### ISSUE TITLE
Debug file in interactive window: Breakpoint not working

### ISSUE THREAD

**Issue by darim1** [microsoft/vscode-jupyter#4349] opened 2021-01-12 15:31 UTC
I entcounter problems, when trying to debug a complete file in the interactive window via command "Jupyter: Debug file in interactive window."

## Environment data

-   VS Code version:1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: ManjaroLinux 20.2.1 
-   Python and/or Anaconda version: 3.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour
Stop at breakpoint as it does with command debug cell.

## Actual behaviour
Debug cell works. Debug file in interactive window does not work. 

## Steps to reproduce:
1. Create this file:
```
# %%
# !%reset -f
# !%clear

# %% Import utils
import gc



# %%
def decorator(fun):

    def do(a, b):
        print('Something 1')
        _ret = fun(a, b)
        print('Something 2')
        return _ret
    return do


deco_fun = decorator(lambda a, b: print(a + b))

deco_fun(1, 3)
```
2. Create at breakpoint at the last line.
3. Run Debug Cell from CodeLens Menu. => The program should stop at the breakpoint.
4. Press F1: Jupyter: Debug file in interactive window => The program does not stop

**Comment by IanMatthewHuff** [comment] 2021-01-12 17:51
Hey @darim1 so you are seeing it just run and not stop? I just tried your repro file and when using the Debug file command it first stopped initially at the start of the file `import gc` line, then when I continued with the debugger it ran to the breakpoint on the `deco_fun(1, 3)` line. 
![image](https://user-images.githubusercontent.com/812783/104352483-988e1d00-54bb-11eb-84d2-251140d07946.png)
Do you have your context in the target file when running the command?

**Comment by darim1** [comment] 2021-01-13 14:35
Hey Ian Huff, thanks for this immediate reply!

Yes, if trying to debug the complete file, it just would not stop!

What do you mean by "context in the target file"?

I attached a screenshot of vscode after executing the command:

![Screenshot_20210112_203708](https://user-images.githubusercontent.com/20026777/104465956-ee92bb80-55b4-11eb-86eb-ba5e41bded8a.png)

In my opinion this looks fine. What additional files/ screenshots do you need?

Thanks again,
Daniel

**Comment by IanMatthewHuff** [comment] 2021-01-15 17:08
@darim1 I think the next step here might be taking a peek at the logs for this scenario. In VS Code settings you can change the Jupyter: Logging > Level to 'debug' then try to re-run the debugging scenario. After running the scenario where it doesn't stop look in the VS Code Output window and select 'Jupyter' from the drop down. That window there should now have all our detailed debugging output which I can look over. It can have a lot there so maybe just copy and paste it into a file, and then attach the file to a comment here, probably the easiest way for me to take a look.

Also, just to rule out anything wrong with the general debugging setup, does just debugging a normal .py file (not using the interactive window and without cells) work ok for you?

**Comment by darim1** [comment] 2021-01-15 17:27
@IanMatthewHuff : I've attached the log data. 

[debug.log](https://github.com/microsoft/vscode-jupyter/files/5822081/debug.log)

In addition, I've checked regular debugging. Everything seems to work fine. The program stops at the breakpoint location.

**Comment by roblourens** [comment] 2022-09-02 22:56
Works for me right now. Lots of changes in the past year and a half, and we do have many debug-related issues open which we will be prioritizing this month. I'm closing this in favor of newer issues.

**Closed by roblourens** 2022-09-02 22:56 UTC
Labels: bug, interactive-window-debugging

**Comment by agoodge** [comment] 2023-02-06 06:16
So is this fixed?

**Comment by Tetane** [comment] 2023-05-25 12:06
I just encountered the same issue.
When I select `Jupyter: Debug Current File in Interactive Window` it stops at the beginning of the program (without highlighting the current line in yellow in the code), and if I click on `Continue` or press `F5` the code run to the end ignoring breakpoints. If I press `Step Over` it works as intended. And if I write `breakpoint()` in the code instead of clicking to place a breakpoint, it stops at the line where `breakpoint()` is written.

```
13:29:34.446 [info] Starting interactive window for resource '~\Documents\projets_python\test1.py' with controller '.jvsc74a57bd01cc4f94f50fe45da212b484e2e7b076440d46defa4310df5abd4ad4018d85589.c:\Users\<username>\miniconda3\envs\test_ipython\python.exe.c:\Users\<username>\miniconda3\envs\test_ipython\python.exe.-m#ipykernel_launcher (Interactive)'
13:29:34.595 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd01cc4f94f50fe45da212b484e2e7b076440d46defa4310df5abd4ad4018d85589.c:\Users\<username>\miniconda3\envs\test_ipython\python.exe.c:\Users\<username>\miniconda3\envs\test_ipython\python.exe.-m#ipykernel_launcher  (Python Path: ~\miniconda3\envs\test_ipython\python.exe, Conda, test_ipython, 3.11.3) for 'Interactive-1.interactive' (disableUI=false)
13:29:35.135 [info] Process Execution: ~\miniconda3\envs\test_ipython\python.exe -m pip list
13:29:35.176 [info] Process Execution: ~\miniconda3\envs\test_ipython\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
13:29:35.182 [info] Process Execution: ~\miniconda3\envs\test_ipython\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"298f602f-f5e1-4d76-88d7-63b3b67e8e4f" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\<username>\AppData\Roaming\jupyter\runtime\kernel-v2-17292YGXh2OUBogAC.json
    > cwd: ~\Documents\projets_python
13:29:35.509 [info] ipykernel version & path 6.23.1, ~\miniconda3\envs\test_ipython\Lib\site-packages\ipykernel\__init__.py for ~\miniconda3\envs\test_ipython\python.exe
13:29:35.951 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
13:29:36.213 [info] Started Kernel test_ipython (Python 3.11.3) (pid: 16764)
13:29:36.213 [info] Started new session e538d8f5-50d6-4439-8d13-04460228cdd6
13:29:36.241 [info] Generated code for 1 = <ipython-input-1-e5dd4fbf5d48> with 10 lines
13:29:36.244 [info] start debugging
13:29:36.244 [info] enable debugger attach
13:29:36.252 [info] Appending paths: undefined
13:29:36.543 [info] connected to notebook during debugging
13:29:36.721 [info] import startup: undefined
13:30:10.282 [info] stop debugging
13:30:10.334 [info] Ending debug session d1ae7f5a-21ca-4a31-8a98-c784d15097cd
13:30:10.334 [info] Ending debug session d1ae7f5a-21ca-4a31-8a98-c784d15097cd
```

I don't know how to set `-Xfrozen_modules=off` but I don't think this is the issue, I'm not trying to debug any specific module.
My test code is very simple:
```
print('Before breakpoint.')
print('Should break here!')
print('After breakpoint.')
```
