### ISSUE TITLE
VS Code select Existing Jupyter Server stopped working

### ISSUE THREAD

**Issue by TekeDado** [microsoft/vscode-jupyter#13699] opened 2023-06-14 02:42 UTC
## Environment data

-   VS Code version: 1.79
-   Jupyter Extension version (available under the Extensions sidebar): v2023.5.1001582324
-   Python Extension version (available under the Extensions sidebar): v2023.10.1
-   OS (Windows | Mac | Linux distro) and version: Linux Debian Buster
-   Python and/or Anaconda version: Python 3.8.12
-   Type of virtual environment used: venv
-   Jupyter server running: Remote

## Expected behaviour

Until this week, when I upgraded to VS Code 1.79 and latest Jupyter extension, I would typically SSH attach my VS code window to a remote machine and use a running jupyter kernel there. To do so, I'd use `Jupyter: Create Interactive Window`, then click on the kernel select, do `Select Another Kernel`, then `Existing Jupyter Server`, at which point i'd enter the URI and token of the server. At that point it would show me the available Python kernel to select and I'd click it.

## Actual behaviour

After typing in the URI of the server, I either just get to the window that says 'Select Kernel' and the little blue processing bar bounces back and forth until it times out, or I see a screenshot like the one attached below which directs me to check the connecting from vs code dev [link](https://github.com/microsoft/vscode-jupyter/wiki/Connecting-to-a-remote-Jupyter-server-from-vscode.dev) and shows that the error is ENETUNREACH, which I can't interpret. However, as recommended in that article, I was able to confirm that I can port forward the running jupyter kernel to my local machine and view it in the browser and execute code. So, it seems the kernel is working just fine, but VS Code can't communicate with it for one reason or another.

## Logs

<img width="589" alt="Screenshot 2023-06-13 at 7 33 32 PM" src="https://github.com/microsoft/vscode-jupyter/assets/52013102/f7490a1e-28b7-4456-b56e-a34d515e18c2">

**Comment by DonJayamanne** [comment] 2023-06-14 07:48
Thank you for filing this issue and sorry you are running into this.

> Until this week, when I upgraded to VS Code 1.79 and latest Jupyter extension, I would typi

Does this mean if you revert the Jupyter extension to the older version it works.
Please could you try that and let me know if it works (with the previous version `2022.4.*`)

**Comment by mcitoler** [comment] 2023-06-14 09:14
I encountered the same issue and rolling back the Jupyter extension to `v2023.4.*` did the trick for me.

**Comment by DonJayamanne** [comment] 2023-06-14 10:29
I’m so sorry you are running into this
Please could you reinstall the latest version then enable verbose logging as follows and then share the logs

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment] 2023-06-14 10:30
@mcitoler  are you also using remote SSH or is this just on your local machine
Also are you running into the exact same message with ENETUNREACH

Is this a Jupyter lab or notebook server?

**Comment by DonJayamanne** [comment] 2023-06-14 11:29
@mcitoler @TekeDado 
Please could you help me figure out the problem by installing the following two VSIX

### 2023.4 (from marketplace)
* Please install the previous version (@mcitoler already installed this)
* Reload VS Code
* Try to replicate the issue (it should work, as validated by @mcitoler )
* Open the command palette and select the command `Jupyter: Show Output` and copy the output from the output panel  
(Tip: The output panel is displayed at the bottom , where the terminal is displayed, and you can also get to it using the command `View: Toggle Output` and then select the option `Jupyter` from the dropdown list displayed at the top right of the output panel)
* Please remember to copy all the messages and paste it (in particular the error messages)


### First VSIX (should fail)
* Install this VSIX (download this file, extract it and then install using the command `Extensions: Install from VSIX`)
[ms-toolsai-jupyter-insiders.vsix (2).zip](https://github.com/microsoft/vscode-jupyter/files/11745112/ms-toolsai-jupyter-insiders.vsix.2.zip)
* Reload VS Code
* Try to replicate the issue (this should fail with the error message)
* Open the Jupyter Output panel and copy all of the output again.

### Second VSIX (should work)
* Repeat the same steps with this new VSIX
[ms-toolsai-jupyter-insiders.vsix (3).zip](https://github.com/microsoft/vscode-jupyter/files/11745136/ms-toolsai-jupyter-insiders.vsix.3.zip)
* Remember to reload VS Code after installing this.
* This VSIX should work, however I am still interested in the logs


The logs will help me determine the difference between the versions

**Comment by DonJayamanne** [comment] 2023-06-14 20:06
@adamlopuch please could you try the VSIX provided above https://github.com/microsoft/vscode-jupyter/issues/13699#issuecomment-1591013925
and could you share the logs, so that I can get to the bottom of the issue as I'd like fix it in the latest version

**Comment by TekeDado** [comment] 2023-06-14 22:29
@DonJayamanne Hi, sorry for delay.

Update: I found that reverting to v2023.4.* or the First VSIX you sent I was unable to get it to connect to any kernel--when I entered the URI of the kernel, it wouldn't respond to me pressing "enter" to confirm my selection. However, I then tried running Jupyter: Clear Jupyter Remote Server List while running the first VSIX version, and it succeeded (I was not able to run this on the latest version of jupyter extension previously). After clearing old URIs, I am able to connect to the server whether on v2023.4.*, the first VSIX, or even the latest published version of v2023.5.*. With the second VSIX, it also was failing to successfully clear my previous kernels, so even though it would show an empty list when i clicked 'Existing jupyter server', when I entered the URI it would tell me that server with that URL already exists. So i wasn't able to get the second VSIX to work.

Logs here now showing from latest published version. You can see it gets upset and says Invalid remote URI, that I had previously entered when testing the first VSIX, then re-select the kernel URI by typing it in, and it works even though it raises a warning about invalid uri. So, basically, downgrading so I could clear kernels then upgrading back to most recent version allowed it to work.

> Visual Studio Code (1.79.0, ssh-remote, desktop)
Jupyter Extension Version: 2023.5.1001582324.
Python Extension Version: 2023.10.1.
Platform: linux (x64).
Workspace folder <redacted>, Home = <redacted>
22:08:59.421 [info] Start refreshing Interpreter Kernel Picker (1686780539421)
22:08:59.460 [info] Using Pylance
22:09:00.156 [error] Failed to parse remote URI http://0.0.0.0:4997/?token=<token> [Error: Invalid remote URI
	at qr (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1001582324-linux-x64/out/extension.node.js:2:1694598)
	at hk.parseUri (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1001582324-linux-x64/out/extension.node.js:24:529924)
	at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1001582324-linux-x64/out/extension.node.js:24:527677]
22:09:00.771 [info] Starting interactive window for resource '' with controller '.jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher (Interactive)'
22:09:01.312 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher  (Python Path: /usr/bin/python3, Unknown, 3.8.10) for '/Interactive-1.interactive' (disableUI=false)
22:09:01.816 [warn] Failed to get activated env vars for /usr/bin/python3 in 1102ms
22:09:01.822 [warn] Failed to get activated env vars for /usr/bin/python3 in 506ms
22:09:01.842 [info] Process Execution: /usr/bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
22:09:01.885 [error] Unable to determine site packages path for python /usr/bin/python3 (Unknown)
22:09:01.885 [error] Unable to determine site packages path for python /usr/bin/python3 (Unknown)
22:09:01.904 [info] Process Execution: /usr/bin/python3 -m pip list
22:09:01.921 [info] Process Execution: /usr/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
22:09:01.940 [info] Process Execution: /usr/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"fef672d8-9b54-4fd6-8764-98a0ffb19fa5" --shell=9007 --transport="tcp" --iopub=9009 --f=~/.local/share/jupyter/runtime/kernel-v2-1180025FtwyQOtYbljX.json
    > cwd: ~<redacted>
22:09:02.253 [info] ipykernel version & path 6.13.0, ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /usr/bin/python3
22:09:02.827 [info] Started Kernel Python 3.8.10 (pid: 1180504)
22:09:02.827 [info] Started new session c70c9a82-6e3c-4239-baf2-9daf9b7c4153
22:09:02.996 [info] Process Execution: /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1001582324-linux-x64/pythonFiles/printJupyterDataDir.py
22:09:05.513 [info] End refreshing Interpreter Kernel Picker (1686780539421)
22:09:16.655 [error] Failed to parse remote URI http://0.0.0.0:4997/lab?token=<token> [Error: Invalid remote URI
	at qr (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1001582324-linux-x64/out/extension.node.js:2:1694598)
	at hk.parseUri (~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1001582324-linux-x64/out/extension.node.js:24:529924)
	at ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.5.1001582324-linux-x64/out/extension.node.js:24:528712
	at b.invoke (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at f._fireDidAccept (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:102:114142)
	at E.$onDidAccept (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:102:112352)
	at s.N (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:112:11717)
	at s.M (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:112:11435)
	at s.H (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:112:10516)
	at s.G (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:112:9494)
	at ~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:112:8282
	at b.invoke (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at ~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:128:32461
	at b.invoke (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at p.fire (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:73:14783)
	at D.E (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:73:18830)
	at ~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:73:16818
	at b.invoke (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at h.acceptChunk (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:73:12514)
	at ~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:73:11801
	at b.invoke (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at deliver (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
	at n.fire (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
	at E.u (~/.vscode-server/bin/b380da4ef1ee00e224a15c1d4d9793e27c2b6302/out/vs/workbench/api/node/extensionHostProcess.js:128:20017)]
22:09:18.199 [info] End refreshing Interpreter Kernel Picker (1686780539421)
22:09:19.186 [info] Disposing kernel .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher for notebook /Interactive-1.interactive due to selection of another kernel or closing of the notebook
22:09:19.187 [info] Dispose Kernel '/Interactive-1.interactive' associated with '/Interactive-1.interactive'
22:09:19.189 [info] Dispose Kernel process 1180504.
22:09:19.263 [info] Dispose Kernel '/Interactive-1.interactive' associated with '/Interactive-1.interactive'
22:09:19.265 [info] Starting Kernel startUsingRemoteKernelSpec, f53c7b4529f298acdd6f73af1c1f4512f95365fc7f21e945090178ab55b32ecb..python3./python./.-m#ipykernel_launcher  for '/Interactive-1.interactive' (disableUI=false)
22:09:20.412 [info] Started new session bfb00907-8532-41e5-a353-c5fa5cc51064
22:09:20.413 [info] Started session for kernel startUsingRemoteKernelSpec:f53c7b4529f298acdd6f73af1c1f4512f95365fc7f21e945090178ab55b32ecb..python3./python./.-m#ipykernel_launcher
22:09:20.839 [info] End refreshing Interpreter Kernel Picker (1686780539421)

**Comment by ivanguag** [comment] 2023-06-15 05:27
I had the same problem yesterday after automatic update, thanks to @adamlopuch  and @mcitoler as what you did helped me to solve the issue. Now, this clearly looks like an error in the code for the extension as it was working before the update and I couldn't get it to work in all the releases after 2023.4

Thanks a lot.

**Comment by DonJayamanne** [comment] 2023-06-15 05:44
@ivanguag  sorry you are running into this
Please could you install the extensions in this comment and provide the logs
Please check this comment

Please could you share a sample of the URL that you paste into the textbox.
You can remove the server name/ip address and token.

**Note:** When uploading the logs, you might want to strip the server name and the token (please ensure you replace with a string such as `<serverName>`, `<token>`, this way I know you have replaced them your self.


### 2023.4 (from marketplace)
* Please install the previous version (@mcitoler already installed this)
* Reload VS Code
* Try to replicate the issue (it should work, as validated by @mcitoler )
* Open the command palette and select the command `Jupyter: Show Output` and copy the output from the output panel  
(Tip: The output panel is displayed at the bottom , where the terminal is displayed, and you can also get to it using the command `View: Toggle Output` and then select the option `Jupyter` from the dropdown list displayed at the top right of the output panel)
* Please remember to copy all the messages and paste it (in particular the error messages)


### First VSIX (should fail)
* Install this VSIX (download this file, extract it and then install using the command `Extensions: Install from VSIX`)
[ms-toolsai-jupyter-insiders.vsix (2).zip](https://github.com/microsoft/vscode-jupyter/files/11745112/ms-toolsai-jupyter-insiders.vsix.2.zip)
* Reload VS Code
* Try to replicate the issue (this should fail with the error message)
* Open the Jupyter Output panel and copy all of the output again.

### Second VSIX (should work)
* Repeat the same steps with this new VSIX
[ms-toolsai-jupyter-insiders.vsix (3).zip](https://github.com/microsoft/vscode-jupyter/files/11745136/ms-toolsai-jupyter-insiders.vsix.3.zip)
* Remember to reload VS Code after installing this.
* This VSIX should work, however I am still interested in the logs


The logs will help me determine the difference between the versions
Please do send all of the logs.

thank you for your patience and help here.

**Comment by mcitoler** [comment] 2023-06-15 07:04
> @mcitoler are you also using remote SSH or is this just on your local machine
> Also are you running into the exact same message with ENETUNREACH

You're right, my setup is slightly different. I'm running a jupyter server on a kubernetes pod and I'm connecting to it using a port forward. In the end, the URI I provide to VSCode looks like `http://localhost:9999/user/<name>/?token=<token>` and it hangs at the kernel selection stage. The Jupyter output window complains about not being able to parse the URI, similar to https://github.com/microsoft/vscode-jupyter/issues/13693. I'll try out the VSIX and report back.

**Comment by ivanguag** [comment] 2023-06-15 07:11
sure, in my case, I run jupyter Server as a Docker container inside a Linux Server using port forward: http://<lan_server_ip>:8888/lab?token=<token>

same as @mcitoler , it hangs in the kernel selection stage, the output window complains about not being able to parse the URI, similar to https://github.com/microsoft/vscode-jupyter/issues/13693.

**Comment by mcitoler** [comment] 2023-06-15 07:24
I tried all the VSIX and the latest VSCode Jupyter extension and they all work now, :/. I suspect it's a cache issue now:
```
...
09:21:48.620 [debug] UniversalRemoteKernelFinder: Writing 0 remote kernel connection metadata to cache
09:21:48.620 [warn] Could not fetch kernels from the remote server, falling back to cache: Error: Server Not found
...
```

**Comment by DonJayamanne** [comment] 2023-06-15 07:34
>  latest VSCode Jupyter extension and they all work now, :/. I suspect it's a cache issue now:

@mcitoler 
Thank you very much for confirming the fact that the latest version also works.
I will try to get a fix into the latest version to ensure the clearing of cache works.

> s that I'm not comfortable sharing (work related). I might try to repro the issue later on my personal laptop.

Given that this works in the latest version, we can ignore this.

The fix for https://github.com/microsoft/vscode-jupyter/issues/13693 has been added into the main branch, will try to get that into a release.

**Comment by mcitoler** [comment] 2023-06-15 07:39
> 

It's mostly file paths that contain private repo names. There are also some tokens that are logged. For example, in the log that I copy pasted above, i needed to replace the actual token with `<token>` myself.

**Comment by DonJayamanne** [comment] 2023-06-15 07:43
Thanks
@mcitoler There's no need to share the logs anymore.
Just double checking, the latest version of the extension works, doesn't it?
If it does then there's no need to share the logs.

**Comment by mcitoler** [comment] 2023-06-15 14:58
> Just double checking, the latest version of the extension works, doesn't it?
Yes, it is working.

**Comment by DonJayamanne** [comment] 2023-06-16 10:29
If anyone is running into this issue, please could you install this VSIX and let me know if this works
* Download the file
* Extract the file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* Reload VS Code and check if it works
[ms-toolsai-jupyter-insiders.vsix.zip](https://github.com/microsoft/vscode-jupyter/files/11769086/ms-toolsai-jupyter-insiders.vsix.zip)

**Comment by TekeDado** [comment] 2023-06-16 20:24
hi @DonJayamanne , tried this latest VSIX. can confirm that it allows me to clear the kernel cache successfully and specify a new existing jupyter server kernel. I still do get an 'error' in the logs like:

`20:21:14.879 [error] Failed to parse remote URI http:://<REMOTE SERVER>:4997 [Error: Invalid remote URI`

In spite of this message, I can execute python successfully against the kernel. As a side note, i do see that you are redacting the remote server name now!

**Comment by DonJayamanne** [comment] 2023-06-16 21:29
sorry you are running into this
Please could you install the extensions in this comment and provide the logs
Please check this comment

Please could you share a sample of the URL that you paste into the textbox.
You can remove the server name/ip address and token.

**Note:** When uploading the logs, you might want to strip the server name and the token (please ensure you replace with a string such as `<serverName>`, `<token>`, this way I know you have replaced them your self.


### 2023.4 (from marketplace)
* Please install the previous version (@mcitoler already installed this)
* Reload VS Code
* Try to replicate the issue (it should work, as validated by @mcitoler )
* Open the command palette and select the command `Jupyter: Show Output` and copy the output from the output panel  
(Tip: The output panel is displayed at the bottom , where the terminal is displayed, and you can also get to it using the command `View: Toggle Output` and then select the option `Jupyter` from the dropdown list displayed at the top right of the output panel)
* Please remember to copy all the messages and paste it (in particular the error messages)


### First VSIX (should fail)
* Install this VSIX (download this file, extract it and then install using the command `Extensions: Install from VSIX`)
[ms-toolsai-jupyter-insiders.vsix (2).zip](https://github.com/microsoft/vscode-jupyter/files/11745112/ms-toolsai-jupyter-insiders.vsix.2.zip)
* Reload VS Code
* Try to replicate the issue (this should fail with the error message)
* Open the Jupyter Output panel and copy all of the output again.

### Second VSIX (should work)
* Repeat the same steps with this new VSIX
[ms-toolsai-jupyter-insiders.vsix (3).zip](https://github.com/microsoft/vscode-jupyter/files/11745136/ms-toolsai-jupyter-insiders.vsix.3.zip)
* Remember to reload VS Code after installing this.
* This VSIX should work, however I am still interested in the logs


The logs will help me determine the difference between the versions
Please do send all of the logs.

thank you for your patience and help here.

**Comment by DonJayamanne** [comment] 2023-06-20 04:30
# Temporary work around
We're sorry for the inconvenience caused by this issue,
As a temporary solution please try the following:
* Downgrade to the old extension then use the command `Jupyter: Clear Jupyter Remote Server List`
* Upgrade to the new version of the extension
* Add the new URL once again

This should allow you to use remote Jupyter servers with the latest version.
Optionally you can try VS Code Insiders and the latest pre-release version of the Jupyter extesnion.

**Comment by DonJayamanne** [comment] 2023-07-07 01:42
Closing this as fixed, if this issue persists in the latest version of Jupyter extension 2023.6 (released moments ago), then please feel free to file a new issue

**Closed by DonJayamanne** 2023-07-07 01:42 UTC
Labels: bug, info-needed, notebook-remote, notebook-kernel-remote
