### ISSUE TITLE
Consider shipping ZMQ binaries using VS Code's platform specific extension support 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7253] opened 2021-08-24 17:30 UTC
Right now ZMQ binaries we ship occupies about 5MB. The Jupyter extension all up is around 14MB and may be shrinking further.

**Comment by DonJayamanne** [comment] 2022-12-04 18:24
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5206

**Closed by DonJayamanne** 2022-12-04 18:24 UTC
Labels: notebook-kernel, engineering, zmq
