### ISSUE TITLE
Window Freezes when typing in Interactive Python Console

### ISSUE THREAD

**Issue by mikayel-musheghyan** [microsoft/vscode-jupyter#9936] opened 2022-05-07 21:00 UTC
Issue Type: <b>Bug</b>

VS Code completely freezes if I launch an interactive Python instance and start typing in its console. After typing a few commands, it freezes and becomes completely unresponsive.

Extension version: 2022.5.1001281006
VS Code version: Code - Insiders 1.67.0-insider (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:03:42.454Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.78GB free)|
|Process Argv|-n --crash-reporter-id 1027e5a2-9c41-4d7c-a5b3-6a67febb910d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by amunger** [comment] 2022-05-09 16:50
To clarify, all of VS code is freezing up, or just the Interactive Window? Can you provide the jupyter logs from the output pane if it's just the Interactive Window freezing?
Can you take a look at the memory usage in task manager? Is vscode (or another process) taking up an unusually large amount of memory?
Does this still occur when you disable all extensions aside from Jupyter and Python?

**Comment by scherp14** [comment] 2022-05-10 16:22
+1 for this issue. Running into freezes on both notebooks and the interactive window both with and without other extensions.

As OP mentioned, I am able to run a single cell, then after I typing a few characters into a second cell, the entire VSC window freezes.

No excessive memory usage by VSC or other apps (1-1.5 GB for VSC out of with ~40GB free on 64GB total).

I can't access the extension logs given that the entire window is frozen. Is there a way to dump them to the file system? If so, I can pull and upload.


I first noticed this issue running through a 'Remote - SSH' instance, but I had no issues on my local instance. However, this issue has now worked it's way over to my local instance, so my notebooks have become unusable within VSC.

**Comment by amunger** [comment] 2022-05-10 16:41
Is there some specific code that causes this to happen? Are you able to share it?

**Comment by mikayel-musheghyan** [comment] 2022-05-10 16:44
The entirety of the window was freezing. It doesn't matter what the code is. I think it has something to do with the intellisense. I was able to fix this by downgrading Jupyter, Python, Pylance and then upgrading again to the newest version. No idea what caused it, but it now works fine.

**Comment by scherp14** [comment] 2022-05-10 16:54
I created an empty venv and executed `print(1)` in the first cell and tried to repeat in the second cell, but the window froze again. Does not seem to be code specific.

Interestingly, the downgrade and upgrade for those 3 extensions seems to fix it. I'd note that I had tried doing this for each extension individually with no success.

**Comment by scherp14** [comment] 2022-05-11 21:49
@amunger -- I ran into this issue again today, so I tried to get a profile but could not download it once everything froze. I did notice, however, that the freezes were occurring shortly after the suggestion pane popped up. Not sure if that gets us any closer to the cause, but it's something...

**Comment by allenc97** [comment] 2022-05-12 05:55
I have the same problem with vscode insiders. Using the stable version is perfectly fine.

**Comment by agftrading** [comment] 2022-05-12 15:50
Same issue.  Version 1.67.1 Screenshot of freeze attached.
<img width="352" alt="Screenshot 2022-05-12 164844" src="https://user-images.githubusercontent.com/38389489/168116661-a0c38ba8-4935-4008-b266-9016a9544040.png">

**Comment by agftrading** [comment] 2022-05-12 15:56
Downgrading (without reupgrading) Jupyter, Python and Pylance, resolves the freezing issue.  So assume it has to do with a latest release of one of these extentions.  Hope that helps point us in the right direction.

**Comment by amunger** [comment] 2022-05-12 16:26
alright, I have a repro now in pre-release and dev, so I should be able to debug it

**Comment by DonJayamanne** [comment] 2022-05-12 16:28
i can replicate this as well (ran into this yesterday), the problem disappear when you disable the pylance extension, that's the culprit.

**Comment by bogurd** [comment] 2022-05-12 19:57
I had opened an issue https://github.com/microsoft/pylance-release/issues/2783 on the pylance repo, perhaps it's best to track the issue there if pylance is the only culprit?

**Comment by amunger** [comment] 2022-05-13 15:30
The issue should be fixed in the next update of pylance. Rolling back that extension to a previous version should work until then.

**Closed by amunger** 2022-05-13 15:30 UTC
Labels: bug

**Comment by AdeelK93** [comment] 2022-05-13 18:42
> Agreed that Pylance seems to be causing it. I can reproduce the freeze in versions >=2022.5.1, but version 2022.4.3 seems to work fine.

Thank you @scherp14!!
