### ISSUE TITLE
Cannot show modal in native notebook in cell's output

### ISSUE THREAD

**Issue by Kingwl** [microsoft/vscode-jupyter#6899] opened 2021-07-29 06:37 UTC
## Environment data

-   VS Code version: 1.28.2
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: Windows NT x64 10.0.19043
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used:  conda
-   Jupyter server running: Local

## Behaviour

We have a widget that has the ability to display some content at the top (in a modal). It works fine in webview notebook but not good at native notebook. 

Because there's no height limit in native notebook. All the outputs are rendered in a single iframe(If i'm correct). The iframe in native notebook shows all content. 

![image](https://user-images.githubusercontent.com/6831019/127444490-c2735679-6f07-4d7a-8616-89e22730719c.png)
Which means the modal will cross all the notebook (from first cell to the last) rather than only the cell which It rendered.
And the position of the iframe is static. which means we cannot directly set zIndex to workaround.

Are there any way to show a modal in a limited rendered cell rather than cross all the notebook?

## Steps to reproduce:

Sorry. I cannot share the notebook. It's a bit hard to mvp.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2021-07-29 16:12
Thanks for filling this issue.
What kind of coffee is used to display the modal dialog in JavaScript, is it `window.show...` or some dom element that's displayed in the output.

**Comment by Kingwl** [comment] 2021-07-30 05:40
We are using https://developer.microsoft.com/ja-jp/fluentui#/controls/web/modal

**Comment by DonJayamanne** [comment] 2021-07-30 20:32
Thanks, I've been able to replicate this at my end.

**Comment by DonJayamanne** [comment] 2021-07-30 20:38
Sample code to replicate issue
* With the below code, we'll see that there are errors logged in console window
* The problem is React isn't getting defined (see error message)
* & when we try to use it the variable `window.FluentUIReactHooks` is also undefined (as react isn't loaded)
* Removing the global `require/define` seems to help a little, at least now React loads
**Code to fix react not loading**
``` html
<script type="text/javascript">
    delete window.define 
    delete window.require
    delete window.requirejs
</script>
```

**Code to replicate error**
```html
%%html
<script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
<script src="http://unpkg.com/@fluentui/react@8/dist/fluentui-react.js"></script>
<script src="http://unpkg.com/@fluentui/react-hooks@8/dist/react-hooks.js"></script>
<div id="content"></div> 
```

<details>
<summary>Using React</summary>

```html

%%html
<script src="http://unpkg.com/@fluentui/react@8/dist/fluentui-react.js"></script>
<script src="http://unpkg.com/@fluentui/react-hooks@8/dist/react-hooks.js"></script>
<div id="content"></div>
<script type="text/javascript">
function doIt(){
    "use strict";
const { useId, useBoolean } = window.FluentUIReactHooks;
const { getTheme, mergeStyleSets, FontWeights, ContextualMenu, Toggle, Modal, IDragOptions, IIconProps, Stack, IStackProps, DefaultButton, IconButton, IButtonStyles, ThemeProvider, initializeIcons } = window.FluentUIReact;
// Initialize icons in case this example uses them
initializeIcons();
const ModalBasicExample = () => {
    const [isModalOpen, { setTrue: showModal, setFalse: hideModal }] = useBoolean(false);
    const [isDraggable, { toggle: toggleIsDraggable }] = useBoolean(false);
    const [keepInBounds, { toggle: toggleKeepInBounds }] = useBoolean(false);
    // Normally the drag options would be in a constant, but here the toggle can modify keepInBounds 
    const dragOptions = React.useMemo(() => ({
        moveMenuItemText: "Move",
        closeMenuItemText: "Close",
        menu: ContextualMenu,
        keepInBounds
    }), [keepInBounds]);
    // Use useId() to ensure that the IDs are unique on the page.
    // (It's also okay to use plain strings and manually ensure uniqueness.)
    const titleId = useId("title");
    return (React.createElement("div", null,
        React.createElement(Stack, Object.assign({}, stackProps),
            React.createElement(Toggle, { label: "Is draggable", inlineLabel: true, onChange: toggleIsDraggable, checked: isDraggable }),
            React.createElement(Toggle, { label: "Keep in bounds", inlineLabel: true, onChange: toggleKeepInBounds, checked: keepInBounds, disabled: !isDraggable })),
        React.createElement(DefaultButton, { onClick: showModal, text: "Open Modal" }),
        React.createElement(Modal, { titleAriaId: titleId, isOpen: isModalOpen, onDismiss: hideModal, isBlocking: false, containerClassName: contentStyles.container, dragOptions: isDraggable ? dragOptions : undefined },
            React.createElement("div", { className: contentStyles.header },
                React.createElement("span", { id: titleId }, "Lorem Ipsum"),
                React.createElement(IconButton, { styles: iconButtonStyles, iconProps: cancelIcon, ariaLabel: "Close popup modal", onClick: hideModal })),
            React.createElement("div", { className: contentStyles.body },
                React.createElement("p", null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas lorem nulla, malesuada ut sagittis sit amet, vulputate in leo. Maecenas vulputate congue sapien eu tincidunt. Etiam eu sem turpis. Fusce tempor sagittis nunc, ut interdum ipsum vestibulum non. Proin dolor elit, aliquam eget tincidunt non, vestibulum ut turpis. In hac habitasse platea dictumst. In a odio eget enim porttitor maximus. Aliquam nulla nibh, ullamcorper aliquam placerat eu, viverra et dui. Phasellus ex lectus, maximus in mollis ac, luctus vel eros. Vivamus ultrices, turpis sed malesuada gravida, eros ipsum venenatis elit, et volutpat eros dui et ante. Quisque ultricies mi nec leo ultricies mollis. Vivamus egestas volutpat lacinia. Quisque pharetra eleifend efficitur."),
                React.createElement("p", null, "Mauris at nunc eget lectus lobortis facilisis et eget magna. Vestibulum venenatis augue sapien, rhoncus faucibus magna semper eget. Proin rutrum libero sagittis sapien aliquet auctor. Suspendisse tristique a magna at facilisis. Duis rhoncus feugiat magna in rutrum. Suspendisse semper, dolor et vestibulum lacinia, nunc felis malesuada ex, nec hendrerit justo ex et massa. Quisque quis mollis nulla. Nam commodo est ornare, rhoncus odio eu, pharetra tellus. Nunc sed velit mi."),
                React.createElement("p", null, "Sed condimentum ultricies turpis convallis pharetra. Sed sagittis quam pharetra luctus porttitor. Cras vel consequat lectus. Sed nec fringilla urna, a aliquet libero. Aenean sed nisl purus. Vivamus vulputate felis et odio efficitur suscipit. Ut volutpat dictum lectus, ac rutrum massa accumsan at. Sed pharetra auctor finibus. In augue libero, commodo vitae nisi non, sagittis convallis ante. Phasellus malesuada eleifend mollis. Curabitur ultricies leo ac metus venenatis elementum."),
                React.createElement("p", null, "Aenean egestas quam ut erat commodo blandit. Mauris ante nisl, pellentesque sed venenatis nec, aliquet sit amet enim. Praesent vitae diam non diam aliquet tristique non ut arcu. Pellentesque et ultrices eros. Fusce diam metus, mattis eu luctus nec, facilisis vel erat. Nam a lacus quis tellus gravida euismod. Nulla sed sem eget tortor cursus interdum. Sed vehicula tristique ultricies. Aenean libero purus, mollis quis massa quis, eleifend dictum massa. Fusce eu sapien sit amet odio lacinia placerat. Mauris varius risus sed aliquet cursus. Aenean lectus magna, tincidunt sit amet sodales a, volutpat ac leo. Morbi nisl sapien, tincidunt sit amet mauris quis, sollicitudin auctor est."),
                React.createElement("p", null, "Nam id mi justo. Nam vehicula vulputate augue, ac pretium enim rutrum ultricies. Sed aliquet accumsan varius. Quisque ac auctor ligula. Fusce fringilla, odio et dignissim iaculis, est lacus ultrices risus, vitae condimentum enim urna eu nunc. In risus est, mattis non suscipit at, mattis ut ante. Maecenas consectetur urna vel erat maximus, non molestie massa consequat. Duis a feugiat nibh. Sed a hendrerit diam, a mattis est. In augue dolor, faucibus vel metus at, convallis rhoncus dui.")))));
};
const cancelIcon = { iconName: "Cancel" };
const theme = getTheme();
const contentStyles = mergeStyleSets({
    container: {
        display: "flex",
        flexFlow: "column nowrap",
        alignItems: "stretch"
    },
    header: [
        // eslint-disable-next-line deprecation/deprecation
        theme.fonts.xLargePlus,
        {
            flex: "1 1 auto",
            borderTop: `4px solid ${theme.palette.themePrimary}`,
            color: theme.palette.neutralPrimary,
            display: "flex",
            alignItems: "center",
            fontWeight: FontWeights.semibold,
            padding: "12px 12px 14px 24px"
        }
    ],
    body: {
        flex: "4 4 auto",
        padding: "0 24px 24px 24px",
        overflowY: "hidden",
        selectors: {
            p: { margin: "14px 0" },
            "p:first-child": { marginTop: 0 },
            "p:last-child": { marginBottom: 0 }
        }
    }
});
const stackProps = {
    horizontal: true,
    tokens: { childrenGap: 40 },
    styles: { root: { marginBottom: 20 } }
};
const iconButtonStyles = {
    root: {
        color: theme.palette.neutralPrimary,
        marginLeft: "auto",
        marginTop: "4px",
        marginRight: "2px"
    },
    rootHovered: {
        color: theme.palette.neutralDark
    }
};
const ModalBasicExampleWrapper = () => (React.createElement(ThemeProvider, null,
    React.createElement(ModalBasicExample, null)));
ReactDOM.render(React.createElement(ModalBasicExampleWrapper, null), document.getElementById("content"));

}
doIt();
</script>

```

</details>

**Comment by DonJayamanne** [comment] 2022-12-01 23:34
Its been over a year and there haven't been any upvotes on this issue, hence closing this.

**Closed by DonJayamanne** 2022-12-01 23:34 UTC
Labels: bug, notebook-output, jupyter-output
