### ISSUE TITLE
Traceback messages include long absolute file path

### ISSUE THREAD

**Issue by stevenlis** [microsoft/vscode-jupyter#14302] opened 2023-09-11 00:40 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Traceback messages include long absolute file path

![CS-coFA6LkR@2x](https://github.com/microsoft/vscode-jupyter/assets/33796896/c1295ef9-e5ae-4ac9-a0c5-57ccb03cb323)

I believe this issue didn't occur previously, but currently, it's impossible to read the problematic code because the file paths have taken over my entire screen.

### VS Code Version

Version: 1.82.0

### Jupyter Extension Version

v2023.8.1002501831

### Running Jupyter locally or remotely?

None

**Comment by amunger** [comment] 2023-09-11 16:01
duplicate of https://github.com/microsoft/vscode/issues/192605

**Closed by amunger** 2023-09-11 16:01 UTC
Labels: bug
