### ISSUE TITLE
Don't notify the user to reload after installing the extension

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-jupyter#6353] opened 2021-06-22 18:22 UTC
Python (or Jupyter?) does its own reload after install prompt:

![image](https://user-images.githubusercontent.com/8599/122977344-2236f600-d34a-11eb-8830-cc687ac598cf.png)

(the screenshot is from usertesting but I had no luck reproducing this for myself)

It would be great if it was left to VS Code to handle the reload, so extensions don't run extra notifications. If there are edge cases that VS Code doesn't handle well or if the UX isn't obvious enough, we should improve those in VS Code to make this easier for all extensions.

**Comment by IanMatthewHuff** [comment] 2021-06-23 01:12
@digitarald Thanks for filing. I do think we could probably handle this better. I believe there are a few edge cases that might not work in a specific open notebook or Interactive Window document. But this messaging is pretty non-standard. We might be able to winnow out those edge cases or if not, just go ahead and have VS Code do a full reload.

**Comment by greazer** [comment] 2021-06-24 20:40
We should eliminate this message box from needing to be shown by scanning our source for calls to the Python extension and testing to see whether those scenarios are working without having to reload VS Code. If so, then we can remove the message box.

**Comment by digitarald** [comment] 2021-06-24 20:44
A proposal I discussed with @isidorn was that if the extension determines that it needs to reload, it should be handled by VS Code. Worst case would be that a user syncs multiple extensions into a fresh VS Code instance and multiple extensions prompting for restart.

**Comment by Tyriar** [comment] 2021-07-08 11:39
I just installed the python extension to try debug a python file without a launch config and I got this notification, I don't have any notebooks open so I don't know what it's talking about.

**Comment by IanMatthewHuff** [comment] 2022-08-12 21:42
This was a duplicate of a previous issue that I cleaned up. The new logic is only to show this message if there is an active notebook or interactive window python kernel. In which case the warning seems reasonable.

**Closed by IanMatthewHuff** 2022-08-12 21:42 UTC
Labels: notebook-getting-started, feature-request
