### ISSUE TITLE
Creating a new conda environment does not make it appear until python is installed in it

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10859] opened 2022-07-19 18:18 UTC
With stable bits:

- Create new conda environment without python `conda create -n newEnv`
- Start VS code
- Open a notebook
- Conda environment will not appear in the list of kernels

Then
- Open a python file
- Select this environment as the active interpreter
- Python extension installs python into it
- You can now pick it as a notebook controller

**Comment by DonJayamanne** [comment] 2022-12-05 23:49
Duplicate of #11855

**Closed by DonJayamanne** 2022-12-05 23:49 UTC
Labels: bug, kernel-enumeration, notebook-getting-started, kernel-picker
