### ISSUE TITLE
Go to definition does not work

### ISSUE THREAD

**Issue by SergeyHein** [microsoft/vscode-jupyter#15918] opened 2024-08-04 13:21 UTC
## Environment data

Version: 1.92.0 (user setup)
Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124
Date: 2024-07-31T23:26:45.634Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631
  Python : 3.11 on WSL
  Type of virtual environment used : poetry
  Jupyter server running: Local 
Jupyter plugin : v2024.8.2024080201 (pre-release) 

## Expected behaviour

Go to definition works in jupyter notebook

## Actual behaviour

Go to definition does not work in jupyter notebook

## Steps to reproduce:

write a simple code in jupyter like

from pathlib import Path
click Go to definition

## Details

![goto_definition_doesnotwork](https://github.com/user-attachments/assets/2dbf62b4-ab4f-4120-98fb-e16200d29d7c)

Note: neither release not pre-release work

**Comment by DonJayamanne** [comment] 2024-08-05 00:26
Thanks for filing this issue, sorry you are running into this.

Do you have the [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) extension installed, if not, then its a duplicate of the issue https://github.com/microsoft/vscode-python/issues/23897

**Comment by SergeyHein** [comment] 2024-08-12 06:25
thanks for a feedback.

I just tried on a different box - it works (???)


Here is env snapshot of a box where is works ( WSL again) - please note that pylance is installed


Version: 1.92.1 (user setup)
Commit: eaa41d57266683296de7d118f574d0c2652e1fc4
Date: 2024-08-07T20:16:39.455Z (4 days ago)
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Just in case here is a full list of installed extentions

`code --list-extensions | xargs -L 1 echo code --install-extension`

code --install-extension alexcvzz.vscode-sqlite
code --install-extension batisteo.vscode-django
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension googlecloudtools.cloudcode
code --install-extension kevinrose.vsc-python-indent
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension njpwerner.autodocstring
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension wholroyd.jinja
code --install-extension xelad0m.jupyter-toc
code --install-extension zeshuaro.vscode-python-poetry



Let me know if you need any further info

**Comment by DonJayamanne** [comment] 2024-08-12 10:23
Please can you disable all extensions, except for Jupyter, Python and Pylance and verify it works.

**Comment by SergeyHein** [comment] 2024-08-17 06:04
Hey, @DonJayamanne , I can't reproduce the issue anymore, looks like recent updates of vscode / plugins solved it.

**Comment by DonJayamanne** [comment] 2024-08-17 07:57
Thank you very much for getting back with an update

**Closed by DonJayamanne** 2024-08-17 07:57 UTC
Labels: bug, info-needed, notebook-intellisense
