### ISSUE TITLE
Fails to open with latest insiders build

### ISSUE THREAD

**Issue by flipphillips** [microsoft/vscode-jupyter#5808] opened 2021-05-07 21:57 UTC
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Using latest insiders, May 7 1.57.0-insiders, macos 11.3.1

Updated today to new insiders, notebooks I was editing this morning wont open. "Cannot open resource with notebook editor type 'jupyter-notebook' dialog appears

Extension version: 2021.6.819764235
VS Code version: Code - Insiders 1.57.0-insider (Universal) (a19565da7dfc739fa26e36aae96113e19fe3806f, 2021-05-07T18:11:54.098Z)
OS version: Darwin x64 20.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.83GB free)|
|Process Argv|--crash-reporter-id ab6bc183-d736-4b49-b638-134227ff53ae|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551cf:30291413
vspre833:30267464
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscus158cf:30286554
pythonvsuse255:30296409
vscgsv2ct:30286873
vscorehovct:30295782

```

</details>

**Comment by flipphillips** [comment] 2021-05-07 21:59
<img width="483" alt="Screen Shot 2021-05-07 at 5 59 14 PM" src="https://user-images.githubusercontent.com/671183/117512616-f1e3f580-af5d-11eb-8b06-cdcd806723d7.png">

**Comment by joyceerhl** [comment] 2021-05-07 23:24
Dupe of https://github.com/microsoft/vscode-jupyter/issues/5804. Please see https://github.com/microsoft/vscode-jupyter/issues/5804#issuecomment-834794393 for a workaround. Sorry for the trouble!

**Closed by joyceerhl** 2021-05-07 23:24 UTC
