### ISSUE TITLE
Error: "Error Loading Preloads" instead of "ModuleNotFoundError"

### ISSUE THREAD

**Issue by hamzamohdzubair** [microsoft/vscode-jupyter#7045] opened 2021-08-10 15:01 UTC
## Environment data
![image](https://user-images.githubusercontent.com/13695228/128888520-6fc2bc77-3bc5-4831-b25d-b53f56a60bf8.png)

![image](https://user-images.githubusercontent.com/13695228/128889061-84247ec3-b2b4-4b2f-9996-6c0a7631d927.png)

-   VS Code version: 1.59.0
-   Python Extension version (available under the Extensions sidebar): Python 3.6.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

ModuleNotFoundError

This way we know which module is not installed.

## Actual behaviour
![image](https://user-images.githubusercontent.com/13695228/128888376-3a68f320-03a0-4856-ae67-73a64296db1a.png)

The error goes away after installing the specific module that was throwing the error

**Comment by IanMatthewHuff** [comment] 2021-08-10 20:24
@hamzamohdzubair Thanks for reporting this. Currently I'm actually seeing the following:
![image](https://user-images.githubusercontent.com/812783/128929797-4b0f7a49-a0a6-45bc-bd9d-2c27b6698190.png)
It looks like an expected part of the extension actually didn't download in this case. Could you try uninstalling and reinstalling the Jupyter extension? If the error still happens, pulling the logs from the Output: Jupyter window might help with debugging this.

**Comment by greazer** [comment] 2021-08-12 20:19
Thanks for the feedback! This is a dupe of microsoft/vscode#123494

**Closed by greazer** 2021-08-12 20:19 UTC
Labels: bug, info-needed, needs-triage

**Comment by hamzamohdzubair** [comment] 2021-08-13 07:11
Issue persists after reinstalling the following:

VScode:
- VSCode Jupyter Extension
- VSCode Python Extension
Python:
- jupyter
- jupyter-client
- jupyter-console
- jupyter-core

## LOGS

Following is the output from the OUTPUT > Jupyter window (shown in image)

![image](https://user-images.githubusercontent.com/13695228/129318703-7592035d-440e-4c73-966c-7f6593425a60.png)

```
Info 2021-08-13 12:08:08: Execute Cells request 1 0
Info 2021-08-13 12:08:08: Execute Cell 0 file:///home/hamza/1_rome/soluscompose/api2.ipynb
Info 2021-08-13 12:08:08: Cell Index:0, state:1, exec: 1. User queued cell for execution
Info 2021-08-13 12:08:08: Cell Index:0, state:1, exec: 1. Ready to execute
Info 2021-08-13 12:08:08: Cell Index:0, state:1, exec: 1. Before Execute individual cell
Info 2021-08-13 12:08:08: Cell Index:0, state:1, exec: 1. Start execution
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: undefined. Send code for execution
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: undefined. Wait for jupyter execution
Info 2021-08-13 12:08:08: [32mWidget Coordinator sent IPyWidgets_mirror_execute
Info 2021-08-13 12:08:08: [32mPosting message to Notebook UI 
Info 2021-08-13 12:08:08: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-08-13 12:08:08: [32mPosting message to Notebook UI 
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: undefined. Kernel switching to busy
Info 2021-08-13 12:08:08: Notebook Session status file:///home/hamza/1_rome/soluscompose/api2.ipynb # Busy
Info 2021-08-13 12:08:08: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-08-13 12:08:08: [32mPosting message to Notebook UI 
Info 2021-08-13 12:08:08: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-08-13 12:08:08: [32mPosting message to Notebook UI 
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: undefined. Update output
Info 2021-08-13 12:08:08: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-08-13 12:08:08: [32mPosting message to Notebook UI 
Info 2021-08-13 12:08:08: [32mWidget Coordinator sent IPyWidgets_msg
Info 2021-08-13 12:08:08: [32mPosting message to Notebook UI 
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: 2. Kernel switching to idle
Info 2021-08-13 12:08:08: Notebook Session status file:///home/hamza/1_rome/soluscompose/api2.ipynb # Idle
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: 2. Jupyter execution completed
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: 2. Completed successfully
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: 2. Completed successfully & resolving
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: 2. After Execute individual cell 4
Info 2021-08-13 12:08:08: Cancel all remaining cells true || 4
Info 2021-08-13 12:08:08: Cancel pending cells
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: 2. Executed successfully in executeCell
Info 2021-08-13 12:08:08: Cell Index:0, state:3, exec: 2. Execution disposed
```

**Comment by hamzamohdzubair** [comment] 2021-08-13 07:36
@IanMatthewHuff 

I am able to get the actual error output by changing the Mimetype of output cell

![image](https://user-images.githubusercontent.com/13695228/129321304-2c51529b-c078-4020-adf2-ee79af945a4f.png)

By changing to built-in i am able to get the actual error. However, everytime i run a cell it changes to the default jupyter error renderer.
