### ISSUE TITLE
Line magics are highlighted as syntax errors

### ISSUE THREAD

**Issue by nfx** [microsoft/vscode-jupyter#5397] opened 2021-04-03 09:06 UTC
Issue Type: <b>Bug</b>

`%` sign in notebook is presented as invalid

```python
import os,json
sys.path.append(os.path.abspath('..')) # i'd like to automate it even more!
%load_ext autoreload # i'd like to automate it...
%autoreload 2
```

copy paste from "Problems":

```json
{
	"resource": "...",
	"owner": "_generated_diagnostic_collection_name_#1",
	"severity": 8,
	"message": "Expected expression",
	"source": "Pylance",
	"startLineNumber": 4,
	"startColumn": 1,
	"endLineNumber": 4,
	"endColumn": 2
}
```

Extension version: 2021.5.697286501
VS Code version: Code - Insiders 1.55.0-insider (Universal) (e4b1e9ac57ab3cc942ab9bff09967bf3238a7910, 2021-03-19T05:12:46.929Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (17.11GB free)|
|Process Argv|-psn_0_323663 --crash-reporter-id a434f477-393e-4181-9de5-32e58ed4464b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
openwsldoc:30278403
vsget980:30265949
vspre833:30267464
vsdfh931:30275552
vshan820cf:30276953

```

</details>

**Comment by rchiodo** [comment] 2021-04-05 18:01
This should be a dupe of #https://github.com/microsoft/vscode-jupyter/issues/1497.

The easiest thing for us to do would be to swallow diagnostics for magics.

**Closed by rchiodo** 2021-04-05 18:01 UTC
