### ISSUE TITLE
IntelliSense not Working

### ISSUE THREAD

**Issue by PeterQiu0516** [microsoft/vscode-jupyter#4459] opened 2021-01-22 19:48 UTC
## Environment data

-   VS Code version: 1.521
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.7.9 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

As in a `test.py` file we have 

![image](https://user-images.githubusercontent.com/47267715/105537883-9b112380-5cc0-11eb-83ce-4257e904fc40.png)

(I use the *Microsoft* server for Python extension, but it turns out that Jupyter would not use Python extension's IntelliSense Server.

## Actual behaviour

But in a `test.ipynb` file we have
![image](https://user-images.githubusercontent.com/47267715/105537924-abc19980-5cc0-11eb-99bb-f8ca5752b065.png)

And there is also no hovering doc available.

## Steps to reproduce:

Not available.

**Comment by claudiaregio** [comment] 2021-01-23 17:59
Closing as dupe of #4218, should be fixed in the next release

**Closed by claudiaregio** 2021-01-23 17:59 UTC
Labels: bug
