### ISSUE TITLE
python kernel still up after closing VSCode if extension host is on a linux machine

### ISSUE THREAD

**Issue by goncamateus** [microsoft/vscode-jupyter#5225] opened 2021-03-21 06:07 UTC
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.619093157
-   Python Extension version (available under the Extensions sidebar): v2021.3.658691958
-   OS (Windows | Mac | Linux distro) and version: 20.04
-   Python and/or Anaconda version: Python 3.8.5 /conda 4.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Close python kernel.
## Actual behaviour

Python kernel's still up.

## Steps to Reproduce:

1. Open an ipython notebook
2. Type the following
```python
import torch

a = torch.ones((1,)).cuda()
```
3. Close VSCode
4. Open terminal
5. nvidia-smi
6. Check if any python process is consuming GPU memory

## Gif:
![bug_jupyter](https://user-images.githubusercontent.com/9999972/111895583-6edcff00-89f2-11eb-8fe9-33885ab578cb.gif)

## Logs
N/A

**Comment by DavidKutu** [comment] 2021-03-23 02:30
Thanks for the issue @goncamateus. This might either be exclusive to conda or to Linux. I tried it on windows with regular python and the process did disappear. 

Tomorrow I'll spin up a VM to see if I can repro. In the mean time, I have a favor to ask you. Cloud you try to repro the same steps, but without conda? That would help a lot!

**Comment by DavidKutu** [comment] 2021-03-23 02:31
@IanMatthewHuff @DonJayamanne @joyceerhl Could any of you try this on a mac and see if you can repro?

**Comment by DonJayamanne** [comment] 2021-03-23 02:38
I don't have an nvidia gpu, u don't need a mac, you need an nvidia gpu for this.
Or better yet, just check if the GPU is being used (i don't think it matters if its nvidia).
Basically the processes should be killed when you exit VSCode.

**Comment by DavidKutu** [comment] 2021-03-23 17:14
I tried it with conda, also doesn't repro on windows, this might be only on linux, maybe mac.

**Comment by greazer** [comment] 2021-06-06 06:51
@goncamateus, we've made some significant changes to our notebook support. Can you try this scenario in VS Code insiders to see if it still repros?

**Comment by goncamateus** [comment] 2021-06-06 12:17
@greazer yup! Still happening. The kernel does not close and so the process.

https://user-images.githubusercontent.com/9999972/120923997-e17f8180-c6a7-11eb-9ea5-9a578082c3ad.mp4

**Comment by Aleko2286** [comment] 2021-06-29 21:20
The same thing is happening on my machine (Ubuntu 21.04), but it's not limited to processes on the GPU. 

I am only using interactive windows, but I suspect it's the same issue. 

Right now, when you run an interactive window, there will be 5 python processes, 2 of them being related to the kernel and 3 helpers. If you exit VS Code, it will shut down the 3 helper processes, but the 2 kernel processes will remain open. However, if you close the interactive window, VS code will shut down the kernel processes just fine (while the 3 helper processes remain). So the current work around for me is to first close the interactive window and only then close VS code.

**Comment by greazer** [comment] 2021-07-23 21:27
@Aleko2286, from what you're describing, this is actually by design. We have traditionally been starting two kernels instead of just one because at one point in our past, getting kernels started could take a long time. Having a second one waiting in the wings to be used on a kernel restart, was the rational for this.

That said, kernel startup times have improved and so starting with builds next week, there should only now only be one kernel process started.

**Comment by Aleko2286** [comment] 2021-07-23 21:44
The issue isn't 2 kernel processes being started though, but them not closing on VS code exit. They only close when closing the interactive window manually, but they do not close when youclose VS code right away when the interactive window is still open.

**Comment by rchiodo** [comment] 2021-07-27 16:50
I'm reproing this with WSL. 

Before shutdown:
/bin/python3 -m vscode_datascience_helper
/bin/python3 -m ipykernel_launcher --ip=1

After shutdown
/bin/python3 -m ipykernel_launcher --ip=1

**Comment by rchiodo** [comment] 2021-07-27 19:43
I believe this has something to do with the daemon. When I forgot to install python jsonrpc, it didn't repro anymore.

**Comment by rchiodo** [comment] 2021-07-27 20:53
Current guess - python daemon's kill signal is not getting handled by the time the daemon process itself is killed. Might be better to have the daemon kill itself on kill?

**Comment by rchiodo** [comment] 2021-07-27 21:22
Another possibility is skip having the daemon launch the kernel and have raw kernels just launch from the typescript code. Then the daemon wouldn't own the lifetime of the kernel.

**Comment by rchiodo** [comment] 2021-08-30 21:42
Basically we need to fix the daemon to actually kill the kernel on shutdown.

**Comment by DonJayamanne** [comment] 2021-10-11 17:23
@rchiodo are you still able to repro this issue? I couldn't repro this.

**Comment by rchiodo** [comment] 2021-10-11 17:24
Yes repros on linux machines. I can repro on WSL2

**Comment by DonJayamanne** [comment] 2021-10-12 01:10
I'm trying with stable build and insiders, instead of the dev version.
Hmm

**Comment by greazer** [comment] 2022-01-20 21:10
This should be fixed in the latest pre-release build of the Jupyter extension.

**Closed by greazer** 2022-01-20 21:10 UTC
Labels: bug, notebook-kernel, debt, needs-triage
