### ISSUE TITLE
Use Local Version of ipywidgets

### ISSUE THREAD

**Issue by gregegg** [microsoft/vscode-jupyter#15921] opened 2024-08-05 20:43 UTC
I am working on a Jupyter Notebook over the remote-ssh interface and I'm unable to use the jupyter_bokeh extension.    I'm working on a corporate computer that does not have access to jsdeliver.com or unpkg.com to grab the needed files.

I am requesting a way to point to a local copy of the files needed from jsdeliver.com as described [here](https://github.com/microsoft/vscode-jupyter/wiki/IPyWidget-Support-in-VS-Code-Python).  

e.g., (on the local computer), add something like

    "jupyter.widgetScriptSources": [
        "jsdelivr.com", 
        "C:\\path\\to\\env\\Lib\\site-packages\\jupyter_bokeh\\nbextension"
    ],

**Comment by DonJayamanne** [comment] 2024-08-05 21:37
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/14791

**Closed by DonJayamanne** 2024-08-05 21:37 UTC
Labels: feature-request
