### ISSUE TITLE
Cannot copy images from notebook in native notebook experience

### ISSUE THREAD

**Issue by Genius1237** [microsoft/vscode-jupyter#6532] opened 2021-07-05 16:05 UTC
## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.999662501
-   Python Extension version (available under the Extensions sidebar): 2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10 21H1
-   Python and/or Anaconda version: Python 3.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running:  Local

## Expected behaviour

In the older notebook experience (before native notebooks), you could copy images into the clipboard (select the image, then Ctrl+C) and then paste it anywhere - libreoffice, onenote online etc...

## Actual behaviour

In the new native notebook experience, the image doesn't get copied to the clipboard properly. When I paste it in libreoffice, I get a blank image with the text `blob:vscode-webview://e4792a7d-0522-446f-9f27-c33b1b57d7cf/dfcad83b-c092-4a21-963e-2ce0dba467b0`. If I try pasting it in onenote online, I just get a blank/grey image.

## Steps to reproduce:

Refer above

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DavidKutu** [comment] 2021-07-06 18:20
Thanks for the issue @Genius1237 and sorry for the trouble.

I can also repro your issue on windows. This might be something we need to resolve on the vs code side. I'll bring it up on our next meeting.

**Comment by claudiaregio** [comment] 2021-07-06 21:49
Believe this is dupe of #6512

**Closed** 2021-07-08 20:31 UTC
Labels: bug
