### ISSUE TITLE
plotly.js outdated version

### ISSUE THREAD

**Issue by GP-Quinten** [microsoft/vscode-jupyter#15234] opened 2024-02-26 15:57 UTC
## Environment data

-   VS Code version: 1.86.2
-   Jupyter Extension version v2024-1-1
-   Python Extension version v2024.0.1
-   OS Windows 10
-   Python 3.10.9
-   Environment in docker
-   Jupyter server running: Remote

## Expected behaviour

Some Latest plotly features are not working with the version of plotly.js proposed in VS code for jupyter notebooks. Can you update it?

I noticed it doing a sankey plot with a new argument called 'align' released in latest plotly version v5.19.0. In the following picture I expect the sankey plot to align to the left, but it does not as I have plotly.js  v2.20.0 instead of v2.29.1 for example. I tried it in Jupyterlab and it works as expected. It is the following picture. You can read plotly.js version in the top right corner.

<img width="523" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/149507862/ec874193-bc5d-4da0-99ff-59df2f61ec1c">

## Actual behaviour

And Here is the final figure I get in VS code.

<img width="575" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/149507862/6a5a1f63-c01c-4a0b-a276-343ed7424495">

## Steps to reproduce:

If needed, I can share with you the code I used.

**Comment by gnuille** [comment] 2024-09-23 14:23
Using plotly 5.24.0, 5.23.0 and 5.16.1 I don't get any plot to show unless:
- I specify the `notebook` renderer in the `show` call (as @GP-Quinten mentions above)
- I specify `notebook ` as default renderer:
```python
import plotly.io as pio
pio.renderers.default = 'notebook'
```

So the issue may not be related with the notebook renderer but with the default `plotly` renderer which we can know which it is by printing it, which for me is empty :/
```python
import plotly.io as pio
pio.renders
```
Output:
```
Renderers configuration
-----------------------
    Default renderer: ''
    Available renderers:
        ['plotly_mimetype', 'jupyterlab', 'nteract', 'vscode',
         'notebook', 'notebook_connected', 'kaggle', 'azure', 'colab',
         'cocalc', 'databricks', 'json', 'png', 'jpeg', 'jpg', 'svg',
         'pdf', 'browser', 'firefox', 'chrome', 'chromium', 'iframe',
         'iframe_connected', 'sphinx_gallery', 'sphinx_gallery_png']
```

@GP-Quinten can you confirm your default renderer is also empty?

**Comment by DonJayamanne** [comment] 2024-10-02 06:15
Duplicate of https://github.com/microsoft/vscode-notebook-renderers/issues/214

**Closed by DonJayamanne** 2024-10-02 06:15 UTC
Labels: debt, ipywidgets, notebook-output
