### ISSUE TITLE
ipywidgets not capturing user input correctly after May update

### ISSUE THREAD

**Issue by ewokdanceparty** [microsoft/vscode-jupyter#10427] opened 2022-06-10 21:23 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Since upgrading to 1.68.0 today, ipywidgets (versions 7.7.0 and 7.6.5) are no longer working correctly.

If I create a Dropdown and click on it, it will briefly flash open and close. When I click on it a second time, it will stay open properly. This incorrect behavior started happening after my VSCode install upgraded to the May update today, and the same code works fine in Google Colab and JupyterLab (the Dropdown stays open on the first click). This issue appears to be related to an issue that was closed in jupyter-widgets/ipywidgets in February [here.](https://github.com/jupyter-widgets/ipywidgets/issues/3383)

Also, when I create RadioButtons, there is now an unexpected box around the first of two radio buttons, and when I select the second radio button, the box momentarily moves to that button, and then jumps right back to the first button. 

And finally, if I have RadioButtons followed by a Dropdown, the Dropdown is almost unusable. When I click on the Dropdown, it briefly opens and then closes, and the aforementioned box flashes on the radio buttons. This behavior does not change if I click on the Dropdown multiple times.

![vscode_widgets_bug](https://user-images.githubusercontent.com/78064/173149745-1fa85ceb-a8a2-4e93-8f00-4c90d6797a4a.JPG)

### VS Code Version

Version: 1.68.0 (user setup) Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f Date: 2022-06-08T11:44:16.822Z Electron: 17.4.7 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19044 ipywidgets: 7.7.0 (and 7.6.5)

### Jupyter Extension Version

v2022.5.1001601848

### Coding Language and Runtime Version

Python 3.9.12

### Anaconda Version (if applicable)

4.12.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment] 2022-06-10 23:16
thanks for the bug and repro code, I can confirm the bad behavior.

repro to copy paste
```
import ipywidgets as widgets
from IPython.display import display

radio_button = widgets.RadioButtons(options = ['hello', 'goodbye'])
display(radio_button)

file_chooser_dropdown = widgets.Dropdown( options = [1,2,3] )
display(file_chooser_dropdown)
```

**Comment by DonJayamanne** [comment] 2022-06-13 17:06
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/10433

**Closed by DonJayamanne** 2022-06-13 17:06 UTC
Labels: bug, ipywidgets, triage-needed
