### ISSUE TITLE
Jupyter Extension activation failed.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#5815] opened 2021-05-08 02:44 UTC
## Environment data

-   VS Code version: 1.57.0-insider
-   Jupyter Extension version: 2021.6.780948196
-   Python Extension version: 2021.5.775026543-dev
-   OS (Windows | Mac | Linux distro) and version: Win10 Enterprise 64bit
-   Python and/or Anaconda version: Python 3.8.5 64bit (conda)

## Expected behaviour
Jupyter Extension works well.

## Actual behaviour
Jupyter Extension activation failed.
![image](https://user-images.githubusercontent.com/59192491/117523341-f99dab80-afea-11eb-8e85-c0b4994a93fb.png)

## Toggle Developer Tools
```
extension activation failed TypeError: o.getConfiguration(...).get(...).find is not a function
	at new m (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:683169)
	at Object.t.resolveInstance (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:263270)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:262475
	at Object.t.resolve (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:262738)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:253835
	at e._get (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:253601)
	at e.get (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:252313)
	at a.get (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:90:509426)
	at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:245341
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:37:825686
	at async t.activate (c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:37:825373)
	at async Promise.all (index 0) (at c:\Users\vyizh12\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:37:826205)

```

**Comment by joyceerhl** [comment] 2021-05-08 03:14
Dupe of #5804. Please see #5804 (comment) for a workaround. Sorry for the trouble!

**Closed by joyceerhl** 2021-05-08 03:14 UTC
Labels: bug
