### ISSUE TITLE
Interactive Window: Variable Explorer issues

### ISSUE THREAD

**Issue by hunterdanielsmith** [microsoft/vscode-jupyter#7153] opened 2021-08-16 18:30 UTC
Using #%% in .py files, I've had issues with the interactive window variable explorer.

Since the new update: the variables do not load consistently. I often see "no variables defined" after running my code. 

Also, I dislike that the variable explorer tab now opens in the bottom panel. And it seems I can only view one variable at a time now.

**Comment by greazer** [comment] 2021-08-16 23:13
Thanks! This is a dupe of #6993

**Closed by greazer** 2021-08-16 23:13 UTC
Labels: bug, interactive-window
