### ISSUE TITLE
cells' content being squashed / reduced / hidden when simply scrolling up and down

### ISSUE THREAD

**Issue by SebKp** [microsoft/vscode-jupyter#15944] opened 2024-08-20 14:22 UTC
## Environment data

-   VS Code version: 1.83.0 upwards (reproduced it in multiple versions, also the latest 1.92.1 is affected)
-   Jupyter Extension version (available under the Extensions sidebar): v2024.4.0
-   Python Extension version (available under the Extensions sidebar): v2024.12.3
-   OS (Windows | Mac | Linux distro) and version: MAC Sonoma 14.6.1
-   Python and/or Anaconda version: python 3.9 to 3.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry/virtualenv/pyenv
-   Jupyter server running: Local

## Expected behaviour

Scrolling up and down without seeing cells being squashed or hidden. All code should be visualised correctly.

## Actual behaviour

When scrolling the notebook editor up and down, cells gets squashed (either consecutive cells are being merged together, or their visible lines getting reduced so the user has to scroll further within the cell to visualise them). 

The only way to see the full content of a squashed cell, is to either scroll further within, or modify its content. When the content is modified, the cell gets unsquashed and the content is visualised correctly.

## Steps to reproduce:

- Open a jupyter notebook with some content and some output (pandas dataframe, graphs) 
- then scroll up and down a couple of times.

Please look under [this issue](https://github.com/microsoft/vscode/issues/216950) on the vscode repo, where there are some screenshots documenting the problem. I can not tell if it is an issue with the extension or with VS code itself. I randomly tried multiple version with no improvements.

**Comment by amunger** [comment] 2024-08-20 16:17
this would be an issue in vs code - closing as dupe of https://github.com/microsoft/vscode/issues/216950

**Closed by amunger** 2024-08-20 16:17 UTC
Labels: bug, triage-needed
