### ISSUE TITLE
Run Current File in Interactive Window opens an empty window, no code executed

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#12395] opened 2022-12-13 02:27 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

With a Python script, running "Jupyter: Run Current File in Interactive Window" opens an interactive window but executes no code. 

<img width="595" alt="Screenshot 2022-12-12 at 8 19 29 PM" src="https://user-images.githubusercontent.com/81476/207210072-817c47b3-9638-43c7-8e1c-e01a21b1e5d6.png">

The window can be woken up by running a command in the interactive prompt, for example `ls`, which then brings up a prompt asking which kernel to use. Once a kernel is selected, commands can then be sent from the script to the interactive window. 

Occasionally, when I try running this command, I get  my Python kernel version info, but again no code is executed:

<img width="569" alt="Screenshot 2022-12-12 at 8 30 49 PM" src="https://user-images.githubusercontent.com/81476/207211905-e890bc3d-cdb0-4b76-a984-9757a87bc9d4.png">

### VS Code Version

Version: 1.74.0 Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91 Date: 2022-12-05T16:37:54.581Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin arm64 22.1.0 Sandboxed: No

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
Visual Studio Code (1.74.0, ssh-remote, desktop)
Jupyter Extension Version: 2022.11.1003412109.
Python Extension Version: 2022.21.13431008.
Workspace folder /home/cfonnesbeck_phillies_com/phillies/pie
info 02:26:09.444: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 02:26:09.911: LSP Notebooks experiment is enabled
warn 02:26:13.537: No interpreter with path /home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9 found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9
warn 02:26:13.537: No interpreter with path /home/cfonnesbeck_phillies_com/.env/bin/python found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/.env/bin/python
warn 02:26:13.538: No interpreter with path /home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9 found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9
warn 02:26:13.539: No interpreter with path /home/cfonnesbeck_phillies_com/.env/bin/python found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/.env/bin/python
warn 02:26:13.540: No interpreter with path /home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9 found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9
warn 02:26:13.540: No interpreter with path /home/cfonnesbeck_phillies_com/.env/bin/python found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/.env/bin/python
warn 02:26:13.544: No interpreter with path /home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9 found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9
warn 02:26:13.544: No interpreter with path /home/cfonnesbeck_phillies_com/.env/bin/python found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/.env/bin/python
warn 02:26:13.545: No interpreter with path /home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9 found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9
warn 02:26:13.546: No interpreter with path /home/cfonnesbeck_phillies_com/.env/bin/python found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/.env/bin/python
warn 02:26:13.547: No interpreter with path /home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9 found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python3.9
warn 02:26:13.547: No interpreter with path /home/cfonnesbeck_phillies_com/.env/bin/python found in Python API, will convert Uri path to string as Id file:///home/cfonnesbeck_phillies_com/.env/bin/python
info 02:26:13.661: Starting interactive window for resource '/home/cfonnesbeck_phillies_com/phillies/pie/research/projections/pitchers/pitcher_proj.py' with controller 'undefined'
error 02:26:14.367: Execing shell command, Class name = f, completed in 310ms, has a falsy return value, Arg 1: "~/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/printEnvVariables.py", Arg 2: "" [Error: Command failed: conda activate pie && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/cfonnesbeck_phillies_com/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/printEnvVariables.py

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.



	at ChildProcess.exithandler (node:child_process:399:12)
	at ChildProcess.emit (node:events:526:28)
	at maybeClose (node:internal/child_process:1092:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)] {
  killed: false,
  code: 1,
  signal: null,
  cmd: "conda activate pie && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/cfonnesbeck_phillies_com/.vscode-server/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/printEnvVariables.py"
}
info 02:26:14.380: Process Execution: > ~/mambaforge/envs/pie/bin/python -m pip list
> ~/mambaforge/envs/pie/bin/python -m pip list
info 02:26:15.573: Got env vars with python /home/cfonnesbeck_phillies_com/mambaforge/envs/pie/bin/python, with env var count 140 and custom env var count 88 in 1535ms
```

### Coding Language and Runtime Version

Python 3.9

### Language Extension Version (if applicable)

v2022.21.13431008

### Anaconda Version (if applicable)

MambaForge

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment] 2022-12-13 18:08
this should work if you have a python interpreter selected for the workspace, either through the status bar or the command `Python: Select Interpreter`

**Comment by amunger** [comment] 2022-12-13 23:38
likely a duplicate of https://github.com/microsoft/vscode-jupyter/issues/8422

**Closed by amunger** 2022-12-13 23:38 UTC
Labels: bug

**Comment by fonnesbeck** [comment] 2022-12-14 00:38
Sounds the same, yes.
