### ISSUE TITLE
Unable to load Jupyter Notebooks

### ISSUE THREAD

**Issue by vishalbajaj2000** [microsoft/vscode-jupyter#4848] opened 2021-02-16 21:17 UTC
Issue Type: <b>Bug</b>

unable to load or create jupyter notebooks:

Error
Unable to open 'Jacent - SF Data Transfer.ipynb': Cannot read property 'Code' of undefined.

--
Unexpected token c in JSON at position 0

Extension version: 2021.1.502429796
VS Code version: Code - Insiders 1.54.0-insider (5e74ad5430203eadf89fd8e99695f4ebdb0e62ad, 2021-02-16T10:26:28.625Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor  (48 x 3793)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.87GB (102.42GB free)|
|Process Argv|--crash-reporter-id 1f340bb0-4b6d-4e4e-80fb-a5e7292c176e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30244315
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30257802
coreuntitledfile:30249963
openwslfolder:30257850

```

</details>

**Comment by rchiodo** [comment] 2021-02-17 18:35
Dupe of #4796

**Closed by rchiodo** 2021-02-17 18:35 UTC
