### ISSUE TITLE
Move plot viewer icons in output from right to the left

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7198] opened 2021-08-18 19:38 UTC
I believe our old icons were on the left.
If one has a large screen, the icons are on the far right (further away from the image).

**Comment by amunger** [comment] 2022-08-12 21:46
dupe of https://github.com/microsoft/vscode-jupyter/issues/7758

**Closed by amunger** 2022-08-12 21:46 UTC
Labels: bug, papercut :drop_of_blood:, debt, plot-viewer
