### ISSUE TITLE
Edit and continue

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6214] opened 2021-06-08 19:01 UTC
This assumes the ipython kernel supports it. I doubt it does.

**Comment by DonJayamanne** [comment] 2021-06-08 19:03
Isn't this a new optional feature?
I don't think we had this in run by line for webview/interactive window, or did we?

**Comment by DavidKutu** [comment] 2021-08-31 20:19
Dupe of #5621

**Closed by DavidKutu** 2021-08-31 20:19 UTC
Labels: bug, run-by-line
