### ISSUE TITLE
Jupyter sometimes runs wrong cell on cntrl-enter or shift-enter

### ISSUE THREAD

**Issue by jazzlw** [microsoft/vscode-jupyter#7566] opened 2021-09-16 21:10 UTC
## Environment data

-   VS Code version: 1.60.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): V2021.9.1230869389
-   OS (Windows | Mac | Linux distro) and version: Macos 10.13.6
-   Python and/or Anaconda version: Python 3.8 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

shift-return or control-return should run the current cell and (if shift) proceed to the next cell.  Often this is how it works, but often not.

Expected is that the blue vertical line active cell indicator moves with the thin blue surrounding line current cell indicator, but in these problem states that does not happen.

## Actual behaviour

With some regularity, something seems to get stuck, where shift-return will run the same cell over and over again, regardless of where the cursor is or what cell is selected. 

The blue line surrounding the current cell will be around the cell that the cursor is in but the thicker blue line to the right will still be on the other cell. That cell will then be run when the keys are pressed.

## Steps to reproduce:
I have not been able to figure out when this happens / what causes it.  It usually can be fixed by manually pushing the play button on another cell...

**Comment by sdfordham** [comment] 2021-09-17 14:52
I have been having this problem for a week now. I cannot reproduce it reliably either.

**Comment by SteshinSS** [comment] 2021-09-21 13:14
I cannot reproduce it reliably, but I want to add that restarting kernel doesn't fix the bug, but the closing and the opening notebook do.

**Comment by mab8192** [comment] 2021-09-23 16:52
I've also been having this problem regularly ever since the updated UI for notebooks. I can confirm that closing and re-opening the notebook works as a temporary fix for me as well, but that can awfully inconvenient when some cells take a while to run.

**Comment by DonJayamanne** [comment] 2021-09-23 16:58
I'm sorry you're running into this issue.
Closing as a duplicate of https://github.com/microsoft/vscode/issues/133038

**Closed by DonJayamanne** 2021-09-23 16:58 UTC
Labels: bug, needs-triage
