### ISSUE TITLE
User is never prompted to install `nbconvert`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#6879] opened 2021-07-28 21:12 UTC
AFAIK we are never actually attempting to install `nbconvert` anywhere in our product code.

This line here only actually tries to install `jupyter` or `notebook`, i.e. first-run export users are inevitably broken

https://github.com/microsoft/vscode-jupyter/blob/abdb271b466f22397726e3a7963fcc87d035cb04/src/client/datascience/export/exportInterpreterFinder.ts#L41-L42

**Comment by greazer** [comment] 2021-09-02 18:51
Dupe of #5726

**Closed by greazer** 2021-09-02 18:51 UTC
Labels: bug, notebook-import-export
