### ISSUE TITLE
Handle "object has no attribute dtypes" more gracefully

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#4381] opened 2021-01-13 22:42 UTC
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.8.6 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local 

Maybe it's a dupe of https://github.com/microsoft/vscode-jupyter/issues/1464, if it is feel free to close this. 

When I try to visualize an N dimensional array with N > 2 in the data viewer, I get the following notification:

![image](https://user-images.githubusercontent.com/45497113/104518697-f3537180-55ac-11eb-9e36-04c991625289.png)

It would be nice if the notification was more user friendly, saying that this type of variable cannot be visualized by the data viewer. Or even better if the button to open in the data viewer could be hidden if we know it doesn't have a dtypes attribute. 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Run the following cell in a Jupyter notebook:
```py
import numpy as np

x = np.array([[[1,2,3],[4,5,6],[6,7,8]],[[1,2,3],[4,5,6],[6,7,8]]])
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'pythonJoinMailingListVar3'
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
Error 2021-01-13 14:30:29: Jupyter Kernel Spec not found for a local connection
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\AppData\Local\Programs\PythonCodingPack\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> c:\Users\luabud\Apps\pvscc-logo\env\Scripts\python.exe -c "import os;print(os.path.realpath("C:\\Users\\luabud\\AppData\\Roaming\\jupyter\\kernels"))"
> c:\Users\luabud\Apps\pvscc-logo\env\Scripts\python.exe -c "import os;print(os.path.realpath("C:\\Users\\luabud\\AppData\\Roaming\\jupyter\\kernels"))"
> c:\Users\luabud\Apps\pvscc-logo\env\Scripts\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> c:\Users\luabud\Apps\pvscc-logo\env\Scripts\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> c:\Users\luabud\Apps\pvscc-logo\env\Scripts\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3.8.6 64-bit ('env')
> c:\Users\luabud\Apps\pvscc-logo\env\Scripts\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> c:\Users\luabud\Apps\pvscc-logo\env\Scripts\python.exe c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> c:\Users\luabud\Apps\pvscc-logo\env\Scripts\python.exe -c "import pandas;print(pandas.__version__)"
Error 2021-01-13 14:33:31: Failure during variable extraction:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-1325e0f901e0> in <module>
----> 1 print(_VSCODE_getDataFrameInfo(x))

<ipython-input-2-dd1242950119> in _VSCODE_getDataFrameInfo(df)
     75         indexColumn = "index"
     76 
---> 77     columnTypes = _VSCODE_builtins.list(df.dtypes)
     78 
     79     # Make sure the index column exists

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'
Error 2021-01-13 14:33:31: Error: Failure during variable extraction:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-1325e0f901e0> in <module>
----> 1 print(_VSCODE_getDataFrameInfo(x))

<ipython-input-2-dd1242950119> in _VSCODE_getDataFrameInfo(df)
     75         indexColumn = "index"
     76 
---> 77     columnTypes = _VSCODE_builtins.list(df.dtypes)
     78 
     79     # Make sure the index column exists

AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'
    at C.extractJupyterResultText (c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:571793)
    at C.deserializeJupyterResult (c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:571912)
    at C.getDataFrameInfo (c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:569432)
    at r.ensureInitialized (c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:210104)
    at r.getDataFrameInfo (c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:209190)
    at E.prepDataFrameInfo (c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:205160)
    at E.showData (c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:204483)
    at l.create (c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:207932)
    at f.showDataViewer (c:\Users\luabud\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:32:591079)

```

</p>
</details>

**Comment by rchiodo** [comment] 2021-01-13 23:47
@joyceerhl's tensorboard/pytorch work should be fixing this for multidimensional arrays.

**Comment by rchiodo** [comment] 2021-01-14 21:46
Dupe of #298

**Closed by rchiodo** 2021-01-14 21:46 UTC
Labels: bug
