### ISSUE TITLE
Jupyter extension in VSCode incorrectly alerting about file name overriding 

### ISSUE THREAD

**Issue by wardyemc** [microsoft/vscode-jupyter#11041] opened 2022-08-03 22:31 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

With the Jupyter extension enabled, every file is marked as potentially overriding a Python package, even my test one "crap.py"

The message issued is:

```
This file could potentially override an existing Python package and interfere with kernel execution, consider renaming it.
```

Every single file in my directory is marked as such. This doesn't appear to affect .ipynb files

I noticed this appeared a week or two ago with the pre-release one but i never got around to diagnosing it. Now it's in the release version too

### VS Code Version

Version: 1.70.0-insider (Universal) Commit: da76f93349a72022ca4670c1b84860304616aaa2 Date: 2022-08-03T05:55:27.651Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Darwin x64 21.6.0

### Jupyter Extension Version

v2022.8.1002161046

### Jupyter logs

```shell
Visual Studio Code - Insiders (1.70.0-insider, undefined, desktop)
Jupyter Extension Version: 2022.8.1002161046.
Python Extension Version: 2022.13.12151008.
Workspace folder /Users/wardy/Documents/EMC/gitlab.nosync/storage
info 8:30:30.112: ZMQ install verified.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 8:30:30.795: LSP Notebooks experiment is enabled
info 8:30:31.159: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 8:30:32.182: Process Execution: > ~/Library/Caches/pypoetry/virtualenvs/storage-2bDQhgz_-py3.9/bin/python -m pip list
> ~/Library/Caches/pypoetry/virtualenvs/storage-2bDQhgz_-py3.9/bin/python -m pip list
```

### Coding Language and Runtime Version

Python 3.9.0

### Language Extension Version (if applicable)

python - v2022.13.12151008

pylance - v2022.7.40

### Anaconda Version (if applicable)

not using

### Running Jupyter locally or remotely?

locally

![image](https://user-images.githubusercontent.com/56005742/182723746-d2805b90-269b-4ada-860f-9a36cb07b357.png)

**Comment by DonJayamanne** [comment] 2022-08-04 00:27
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11040
Will be fixed as a hot fix.

**Closed by DonJayamanne** 2022-08-04 00:27 UTC
Labels: bug, release-candidate, triage-needed
