### ISSUE TITLE
Exception links don't work in web

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#10284] opened 2022-06-02 22:30 UTC
![image](https://user-images.githubusercontent.com/19672699/171748935-0f345ba3-09aa-4a00-afe2-2287dbd4aec3.png)

Maybe has something to do with path matching on the input

**Comment by rebornix** [comment] 2022-12-12 22:27
/duplicate of https://github.com/microsoft/vscode-jupyter/issues/9879

**Closed by rebornix** 2022-12-12 22:27 UTC
Labels: bug, error-renderer
