### ISSUE TITLE
Assigning shortcut to copy output doesn't work.

### ISSUE THREAD

**Issue by Jnorm911** [microsoft/vscode-jupyter#15046] opened 2024-01-20 23:35 UTC
## Environment data

-   VS Code version: 1.85.2 (current)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1100101639
-   Python Extension version (available under the Extensions sidebar): v2023.22.1
-   OS (Windows | Mac | Linux distro) and version: Windows 11 22631.3007
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used: venv
-   Jupyter server running: Local

## Expected behaviour

When output cell is focused, copy output shortcut should copy output cell
![Screenshot 2024-01-20 152655](https://github.com/microsoft/vscode-jupyter/assets/35921587/2e3868e4-bbcb-4d68-9698-a9ffc73f3687)

## Actual behaviour

error:
Picture is cut short but output cell is focused.
![Screenshot 2024-01-20 152757](https://github.com/microsoft/vscode-jupyter/assets/35921587/2b60c884-bcb5-418c-8522-d948964e6640)

## Steps to reproduce:

set keyboard short cut, have it not work.
![Screenshot 2024-01-20 152643](https://github.com/microsoft/vscode-jupyter/assets/35921587/e9c5fe43-3593-4a9d-a6fc-07e51345dc95)

**Comment by dumpl1n** [comment] 2024-01-22 04:15
i'd like to +1 this issue. came here to open/reopen issue but found this one. i get the following error:
```
Command 'Copy Output' resulted in an error
Cannot use 'in' operator to search for 'outputId' in undefined
```

<img width="737" alt="Screenshot 2024-01-21 at 11 13 04 PM" src="https://github.com/microsoft/vscode-jupyter/assets/130463630/1974294d-0df0-4645-b48c-202e5b53a39e">

mapping:
```
{
  "key": "cmd+6",
  "command": "notebook.cellOutput.copy",
  "when": "notebookEditorFocused && !inputFocus && !notebookOutputInputFocused"
}
```

**Comment by amunger** [comment] 2024-01-22 17:17
duplicate of https://github.com/microsoft/vscode/issues/201862

**Closed by amunger** 2024-01-22 17:17 UTC
Labels: bug
