### ISSUE TITLE
Feature proposal: plot pane

### ISSUE THREAD

**Issue by nbelakovski** [microsoft/vscode-jupyter#13597] opened 2023-05-29 21:09 UTC
A number of folks, myself included, have wanted to switch from, or have switched from Spyder IDE, but one of the things missing in VSCode is the plot pane [1][2][3][4]. While it's possible to see plots within VSCode using the interactive window, having a dedicated plot pane is nice for being able to see changes immediately without having to scroll through output. It also lets one separate text output and image output.

The Julia VSCode extension already has a plot pane that works very similar to Spyder's (indeed several of the sources below make mention of it). I've taken a look at that extension's code and I think it should be relatively straightforward to roll it into the Python extension. We can also include the setting that Julia provides to allow the user to decide whether plots go into a separate pane or remain inline.

I'm happy to volunteer to do the legwork and make the PR but wanted to raise this in an issue first to make sure this work is aligned with the overall vision for the extension. If the maintainers like it all I need is a go-ahead, and/or feedback.

Thanks for reading!

[1] https://www.reddit.com/r/vscode/comments/h7hkar/question_is_it_possible_to_get_a_figure_pane_as/
[2] https://www.reddit.com/r/learnpython/comments/m6ne2r/from_spyder_to_vscode_plot_pane/
[3] https://www.reddit.com/r/learnpython/comments/rxccpb/plotting_pane_in_vscode/
[4] https://stackoverflow.com/questions/49992300/python-how-to-show-graph-in-visual-studio-code-itself

**Comment by DonJayamanne** [comment] 2023-12-13 22:11
> any progress in this issue? 

@nbelakovski we tend to prioritize issues based on upvotes,
And our iteration plans are always posted on github issues (just as the VS Code repo does).

**Comment by Fred-Wu** [comment] 2024-07-04 02:28
Positron IDE was just released for beta testing with promising features that the current vscode-jupyter lacks such as plot pane like the one raised here, and detailed help manual that vscode-jupyter reluctant to implement

<img width="792" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/4111978/a2b840ee-5669-4255-a50c-aa4c83769ed4">

**Comment by DonJayamanne** [comment] 2024-12-16 23:45
Duplicate of https://github.com/microsoft/vscode/issues/143244

**Closed by DonJayamanne** 2024-12-16 23:45 UTC
Labels: plot-viewer, feature-request, extension-candidate
