### ISSUE TITLE
mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)

### ISSUE THREAD

**Issue by atlantiswqq** [microsoft/vscode-jupyter#11579] opened 2022-10-08 07:10 UTC
[确认为插件bug](https://github.com/microsoft/vscode/issues/158109#issue-1338191075)

**Comment by atlantiswqq** [comment] 2022-10-08 07:13
Enter a remote jupyter session, it can be executed normally，

**Comment by atlantiswqq** [comment] 2022-10-08 07:31
`jupyter plugin v2022.9.1002791758`
```版本: 1.72.0 (Universal)
提交: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
日期: 2022-10-04T23:21:58.256Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
沙盒化: No```


`macOS Monterey 12.6`

**Comment by DonJayamanne** [comment] 2022-10-09 21:50
I've checked the logs here https://github.com/microsoft/vscode/issues/158109#issue-1338191075
This seems to be an issue with a package in Python and isn't a problem caused by the VS Code Jupyter extension
I would suggest checking the torch documentation or reaching out to stackoverflow or the like for a solution.

Unfortunately I'll have to close this as I do not have a solution for this problem in torch, and its not a problem with the Jupyter extension in VS Code.

**Closed by DonJayamanne** 2022-10-09 21:50 UTC
Labels: bug
