### ISSUE TITLE
How to make the interactive window positioned below the current group instead of to the right?

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#8092] opened 2021-10-28 21:38 UTC
### Discussed in https://github.com/microsoft/vscode-python/discussions/17872

<div type='discussions-op-text'>

<sup>Originally posted by https://github.com/macintacos October 28, 2021</sup>
Can't seem to find an option to run a cell of code when using the Interactive Mode and have the window that is created to show your output appear below the current window instead of to the right of the current window. Is this just something that's not possible right now?</div>

**Comment by rchiodo** [comment] 2021-11-01 20:20
The default is Group 2. We could change this to be a setting if somebody wanted to add that code.

**Comment by amunger** [comment] 2022-09-29 18:44
new setting introduced to control this

**Comment by macintacos** [comment] 2022-09-29 18:46
A couple of questions:

- What's the setting?
- Why is it a setting instead of a command? In some situations it would be great to split it to the right, sometimes below, sometimes to the left, etc.

**Comment by amunger** [comment] 2022-09-29 21:46
ah sorry, mis-read the title. The setting is just for creating in the active group, beside the active group or always in the second group: `jupyter.interactiveWindowViewColumn`

**Comment by jaxankey** [comment] 2023-03-09 21:58
None of these options seem to put the new interactive windows below the open editor. Am I missing something?

**Comment by amunger** [comment] 2023-12-06 21:49
duplicate of https://github.com/microsoft/vscode/issues/127998

**Closed by amunger** 2023-12-06 21:49 UTC
Labels: interactive-window, feature-request
