### ISSUE TITLE
Notebook fails to open

### ISSUE THREAD

**Issue by diazdc** [microsoft/vscode-jupyter#5268] opened 2021-03-24 20:27 UTC
## Environment data

-   VS Code version: Version: 1.55.0-insider
    Commit: 469e4f6e2755b220dae3eccb04d1ddc587b84a5a
    Date: 2021-03-22T07:48:57.578Z
    Electron: 11.3.0
    Chrome: 87.0.4280.141
    Node.js: 12.18.3
    V8: 8.7.220.31-electron.0
    OS: Linux x64 5.8.0-45-generic

-   Jupyter Extension version: v2021.4.678042391
-   Python Extension version: v2021.4.677374727-dev
-   OS: Kubuntu 20.04
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used : Conda
-   Jupyter server running: Remote 

## Expected behaviour

Opening a jupyter notebook works.

## Actual behaviour

I get the following error when opening a new or existing notebook (please see screenshots):

"Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled."

![Screenshot_20210324_130620](https://user-images.githubusercontent.com/32173539/112378699-7cb9ab00-8ca4-11eb-9009-b338dd96c6ac.png)

![Screenshot_20210324_131233](https://user-images.githubusercontent.com/32173539/112378770-8fcc7b00-8ca4-11eb-9922-d59c7d33edf4.png)

## Steps to reproduce:
Open a jupyter notebook, either new or existing.

(edit:) Downgraded to v2021.4.641214696 and notebooks open without any problem

**Comment by rchiodo** [comment] 2021-03-24 21:56
This happened because you upgraded Jupyter without also upgrading VS code insiders.

Dupe of #5251

**Closed by rchiodo** 2021-03-24 21:56 UTC
Labels: bug
