### ISSUE TITLE
Vscode debugger does not run for all available kernels 

### ISSUE THREAD

**Issue by dokutoshi** [microsoft/vscode-jupyter#12871] opened 2023-02-19 03:46 UTC
## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: 13.2.1 (22D68)
-   Python and/or Anaconda version: 3.10 and Conda 23.1.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A = Remote

## Expected behaviour

Expected: Debug cell should launch visual debugger using debugpy.  The debugger launches then executes code for cell until breakpoint.

## Actual behaviour

Expected: Debug cell should launch visual debugger using debugpy.  The debugger is launching and then crashes requesting to launch.json.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. !python --version. #Breakpoint on single line.

<img width="1396" alt="Screenshot 2023-02-18 at 7 43 14 PM" src="https://user-images.githubusercontent.com/10182821/219905866-bc0f711f-147d-4c43-9449-d30fd41e16ff.png">

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>
<img width="1396" alt="Screenshot 2023-02-18 at 7 43 14 PM" src="https://user-images.githubusercontent.com/10182821/219905886-35bb73b1-6a8e-4a6c-9a96-4a30aed52c74.png">

What are the requirements for a non-conda and the requirements for a conda env to initiate the vscode jupyter cell debugging?  ipykernel and debugpy are insufficient requirements.

**Comment by dokutoshi** [comment] 2023-02-22 19:12
I developed a script to share the outputs of the two similar environments.

### Interactive script:

https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

```
import sys
import os
print(f'Sys path: {sys.path}')
print(f'Sys executable: {sys.executable}')
print(f'Sys prefix: {sys.prefix}')
# !pip show scikit-learn matplotlib
# !{sys.executable} -m pip show ipykernel
!{sys.executable} -m pip show debugpy
!echo $PATH
!type -a python
!type -a conda
!type -a pip
!jupyter kernelspec list
```

### Anaconda kernel (display name in VScode) - Working debugger.
```
Sys path: ['/mnt/home/ec2-user', '/mnt/home/ec2-user/anaconda3/lib/python310.zip', '/mnt/home/ec2-user/anaconda3/lib/python3.10', '/mnt/home/ec2-user/anaconda3/lib/python3.10/lib-dynload', '', '/home/ec2-user/.local/lib/python3.10/site-packages', '/mnt/home/ec2-user/anaconda3/lib/python3.10/site-packages', '/mnt/home/ec2-user/anaconda3/lib/python3.10/site-packages/PyYAML-6.0-py3.10-linux-x86_64.egg']
Sys executable: /mnt/home/ec2-user/anaconda3/bin/python
Sys prefix: /mnt/home/ec2-user/anaconda3
Name: debugpy
Version: 1.6.6
Summary: An implementation of the Debug Adapter Protocol for Python
Home-page: https://aka.ms/debugpy
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT
Location: /home/ec2-user/.local/lib/python3.10/site-packages
Requires: 
Required-by: ipykernel
/mnt/home/ec2-user/anaconda3/bin:/home/ec2-user/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/opt/amazon/openmpi/bin:/opt/amazon/efa/bin:/usr/local/cuda/bin:/opt/tensorflow/bin:/usr/libexec/gcc/x86_64-redhat-linux/7:/opt/aws/bin:/mnt/home/ec2-user/ananconda3/condabin:/opt/amazon/openmpi/bin:/opt/amazon/efa/bin:/usr/local/cuda/bin:/opt/tensorflow/bin:/usr/libexec/gcc/x86_64-redhat-linux/7:/opt/aws/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin
python is /mnt/home/ec2-user/anaconda3/bin/python
python is /opt/tensorflow/bin/python
python is /opt/tensorflow/bin/python
python is /usr/local/bin/python
python is /usr/bin/python
conda is /mnt/home/ec2-user/anaconda3/bin/conda
conda is /mnt/home/ec2-user/ananconda3/condabin/conda
pip is /mnt/home/ec2-user/anaconda3/bin/pip
pip is /opt/tensorflow/bin/pip
pip is /opt/tensorflow/bin/pip
/bin/bash: /mnt/home/ec2-user/anaconda3/bin/jupyter: /home/ec2-user/anaconda3/bin/python: bad interpreter: No such file or directory
```

### TensorFlow kernel (non-working debugger). Per the case, the debugger errors with a launch.json prompt.

```
Sys path: ['/mnt/home/ec2-user', '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10', '/usr/local/lib/python3.10/lib-dynload', '', '/opt/tensorflow/lib/python3.10/site-packages']
Sys executable: /opt/tensorflow/bin/python
Sys prefix: /opt/tensorflow
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
Name: debugpy
Version: 1.6.6
Summary: An implementation of the Debug Adapter Protocol for Python
Home-page: https://aka.ms/debugpy
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT
Location: /opt/tensorflow/lib/python3.10/site-packages
Requires: 
Required-by: ipykernel
/opt/tensorflow/bin:/home/ec2-user/.vscode-server/bin/441438abd1ac652551dbe4d408dfcec8a499b8bf/bin/remote-cli:/opt/amazon/openmpi/bin/:/opt/amazon/efa/bin/:/usr/local/cuda/bin:/opt/tensorflow/bin:/usr/libexec/gcc/x86_64-redhat-linux/7:/opt/aws/bin:/mnt/home/ec2-user/ananconda3/condabin:/opt/amazon/openmpi/bin/:/opt/amazon/efa/bin/:/usr/local/cuda/bin:/opt/tensorflow/bin:/usr/libexec/gcc/x86_64-redhat-linux/7:/opt/aws/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin
python is /opt/tensorflow/bin/python
python is /opt/tensorflow/bin/python
python is /opt/tensorflow/bin/python
python is /usr/local/bin/python
python is /usr/bin/python
conda is /mnt/home/ec2-user/ananconda3/condabin/conda
pip is /opt/tensorflow/bin/pip
pip is /opt/tensorflow/bin/pip
pip is /opt/tensorflow/bin/pip
Available kernels:
  python3      /opt/tensorflow/share/jupyter/kernels/python3
  ipykernel    /home/ec2-user/.local/share/jupyter/kernels/ipykernel
```

**Comment by dokutoshi** [comment] 2023-02-23 04:04
Solved the error of the debugger crash by uninstalling the `typing` package.

https://softhints.com/python-attributeerror-type-object-callable-has-no-attribute-abc-registry/

**Comment by dokutoshi** [comment] 2023-02-24 17:56
VScode debugger should not crash with the typing package.  Once the debugger crashes, restarting VScode is mandatory.

```
(tensorflow) [ec2-user@ip-172-31-2-50 ec2-user]$ python -m pip install typing
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
Collecting typing
  Using cached typing-3.7.4.3-py3-none-any.whl
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
Installing collected packages: typing
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
Successfully installed typing-3.7.4.3
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
(tensorflow) [ec2-user@ip-172-31-2-50 ec2-user]$ python -m pip uninstall typing
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
WARNING: Ignoring invalid distribution -ackaging (/opt/tensorflow/lib/python3.10/site-packages)
Found existing installation: typing 3.7.4.3
Uninstalling typing-3.7.4.3:
  Would remove:
    /opt/tensorflow/lib/python3.10/site-packages/typing-3.7.4.3.dist-info/*
    /opt/tensorflow/lib/python3.10/site-packages/typing.py
Proceed (Y/n)? y
  Successfully uninstalled typing-3.7.4.3
(tensorflow) [ec2-user@ip-172-31-2-50 ec2-user]$ 
```

**Comment by dokutoshi** [comment] 2023-03-30 10:51
As an important note, in Python 3.12 PEP 646 will enhance the Variadic generic to enhance computational packages such as Numpy and Tensorflow.
[Variadic Generics  - Motivation](https://peps.python.org/pep-0646/#motivation)

> Variadic generics have long been a requested feature, for a myriad of use cases [[4]](https://peps.python.org/pep-0646/#typing193). One particular use case - a use case with potentially large impact, and the main case this PEP targets - concerns typing in numerical libraries.

In the context of numerical computation with libraries such as NumPy and TensorFlow, the shape of variables is often just as important as the variable type. For example, consider the following function which converts a batch [[1]](https://peps.python.org/pep-0646/#batch) of videos to grayscale:

def to_gray(videos: Array): ...
From the signature alone, it is not obvious what shape of array [[2]](https://peps.python.org/pep-0646/#array) we should pass for the videos argument. Possibilities include, for example,

batch × time × height × width × channels
and

time × batch × channels × height × width. [[3]](https://peps.python.org/pep-0646/#timebatch)
This is important for three reasons:

Documentation. Without the required shape being clear in the signature, the user must hunt in the docstring or the code in question to determine what the input/output shape requirements are.
Catching shape bugs before runtime. Ideally, use of incorrect shapes should be an error we can catch ahead of time using static analysis. (This is particularly important for machine learning code, where iteration times can be slow.)
Preventing subtle shape bugs. In the worst case, use of the wrong shape will result in the program appearing to run fine, but with a subtle bug that can take days to track down. (See [this exercise](https://spinningup.openai.com/en/latest/spinningup/exercise2_2_soln.html) in a popular machine learning tutorial for a particularly pernicious example.)

**Comment by DonJayamanne** [comment] 2023-12-13 01:51
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/13139

**Closed by DonJayamanne** 2023-12-13 01:51 UTC
Labels: bug
