### ISSUE TITLE
Pre-release version can no longer start local mode kernels without running `jupyter-notebook`

### ISSUE THREAD

**Issue by leifwalsh** [microsoft/vscode-jupyter#13107] opened 2023-03-19 20:49 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

It used to be the case that I could start a local Jupyter kernel for a virtualenv that just had `ipykernel` (and maybe a couple other things) installed, but without `jupyter` (I think) or `notebook` installed.

With the latest pre-release Jupyter extension, it seems that even for local mode kernels, the Jupyter extension now tries to run `jupyter-notebook` in the environment. This is a problem for us because we've got an internal version of `jupyter` with some customizations that lives under a different command name, and for that reason we've patched the `jupyter-notebook` command to print an error instructing people to use the other one (just to reduce confusion). 

But I could imagine it also being a potential problem for other people who were expecting to be able to run kernels with fewer dependencies installed (i.e. without the `jupyter-notebook` command) who will now be prompted to install those other packages. If they're relying on frozen or containerized environments, this will effectively mean that after this upgrade they can no longer run Jupyter notebooks using those environments in VS Code.

![image](https://user-images.githubusercontent.com/46406/226207789-fbe3a1eb-5cf4-47cf-b9eb-4661a22e9a4a.png)
![image](https://user-images.githubusercontent.com/46406/226207825-ba7a2f63-5635-40e4-be6c-f0b9218f6cbd.png)
![image](https://user-images.githubusercontent.com/46406/226207856-9d9069c1-9bfe-4b88-9fef-c4ce67806c32.png)
![image](https://user-images.githubusercontent.com/46406/226207878-377b3c7a-11f6-4123-a394-0038a8016aca.png)
![image](https://user-images.githubusercontent.com/46406/226207991-2d34788f-d3b7-4303-861b-30dd169384db.png)
![image](https://user-images.githubusercontent.com/46406/226208035-af898ebc-ed28-419e-8f5a-44d8858c076a.png)
![image](https://user-images.githubusercontent.com/46406/226208056-59eaf79e-1936-4bd2-90c7-ef49206d69f1.png)

I'm also confused about why it appears to try using an environment from a different project first. I find this behavior very confusing but can't nail down why/when it happens. That might be a bug too.

### VS Code Version

Version: 1.77.0-insider Commit: c97d5812f...

### Jupyter Extension Version

v2023.3.1000771902

### Jupyter logs

```shell
My environment is firewalled such that I cannot directly paste output. I'm sorry, but screenshots are the best I can do. I've added those to the main section above.
```

### Coding Language and Runtime Version

Python v3.9.12

### Running Jupyter locally or remotely?

Local

**Comment by leifwalsh** [comment] 2023-03-19 20:54
Yeah, Debian 10, x64.

The environment I'm in doesn't let me copy text out, unfortunately. Let me see if I can reproduce it elsewhere.

**Comment by DonJayamanne** [comment] 2023-03-19 20:56
> The environment I'm in doesn't let me copy text out, unfortunately. Let me see if I can reproduce it elsewhere.

Ok, then can you scroll to the very top of the logs and take a screenshot of that. I need the first 10 lines of the logs
That contains an error message about zeromq not loading.

& thanks for providing the OS info

**Comment by leifwalsh** [comment] 2023-03-19 21:28
Aha!

```
warn 21:26:39.443: Exception while attempting zmq : /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33` not found (required by /home/leif/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.3.1000771902/out/node_modules/zeromq/prebuilds/linux-x64/node.napi.glibc.node)
```

**Comment by leifwalsh** [comment] 2023-03-19 21:29
We're on glibc 2.28 :-/

**Comment by leifwalsh** [comment] 2023-03-19 21:32
Here's a screenshot of the rest but I doubt it's relevant:

![image](https://user-images.githubusercontent.com/46406/226210944-6d7fd821-3578-4e2c-951b-e8c1e9358c76.png)

**Comment by DonJayamanne** [comment] 2023-03-19 22:55
Thanks , we are planning on addressing this issue
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/13089

**Closed by DonJayamanne** 2023-03-19 22:55 UTC
Labels: bug

**Comment by leifwalsh** [comment] 2023-03-20 02:25
Thank you!

**Comment by DonJayamanne** [comment] 2023-03-20 04:02
Thank you for filing this issue and providing the logs, that helps a lot.
Hopefully this will be fixed in a day or two.

**Comment by DonJayamanne** [comment] 2023-03-21 01:10
@leifwalsh what version of Debian are you currently on.
I'm trying to test this within a docker container that will pull in debian, when testing with Debian latest version, i believe thats 11, then things work as expected (at least for me)
Pleas let me know
* Linux distro
* Version
* Whether arm64 or x64 or x86 (architecture used)

**Comment by DonJayamanne** [comment] 2023-03-21 01:13
[ms-toolsai-jupyter-insiders.vsix (3).zip](https://github.com/microsoft/vscode-jupyter/files/11024163/ms-toolsai-jupyter-insiders.vsix.3.zip)

@leifwalsh Please could you test this and let me know if this works for you.
Thanks

**Comment by leifwalsh** [comment] 2023-03-21 02:37
No, but new error:

```
warn 02:33:38.753: Error occurred while trying to start the kernel, options.disableUI=false Cn [Error]:
    at new Cn (/home/leif/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.3.100/out/extension.node.js:2:1611002)
    at Function.from (/home/leif/.vscode-server-insiders/extension/ms-toolsai.jupyter-2023.3.100/out/extension.node.js:2:1611081)
    at Gg.createJupyterSession (/home/leif/.vscode-server-insiders/extension/ms-toolsai.jupyter-2023.3.100/out/extension.node.js:17:264091)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

TypeError: t.Subscriber is not a constructor
    at /home/leif/.vscode-server-insiders/extension/ms-toolsai.jupyter-2023.3.100/out/extension.node.js:17:97545
...
```

**Comment by leifwalsh** [comment] 2023-03-21 02:38
* Distro: Debian
* Version: 10 (buster)
* Architecture: x64

**Comment by leifwalsh** [comment] 2023-03-21 02:38
fwiw I no longer see a warning about zmq failing to load.

**Comment by DonJayamanne** [comment] 2023-03-21 02:39
thanks, the new error indicates its not working correctly, i will be building a new VSIX shortly.

**Comment by leifwalsh** [comment] 2023-03-21 02:43
I'm here to test when ready!

**Comment by DonJayamanne** [comment] 2023-03-21 04:57
@leifwalsh please try installing the latest pre-release version of the Jupyter extension from the marketplace.
It should be fixed now.
Would appreciate it if you could get back with a confirmation of the fix, and of course if it does not work, please re-open this issue or i will do that, or just create a new issue and I will look into it.

**Comment by leifwalsh** [comment] 2023-03-21 14:58
Yep, v2023.3.1000820547 works great. Thanks!
