### ISSUE TITLE
Ipywidget is not showing properly in the latest version

### ISSUE THREAD

**Issue by gaminglifex** [microsoft/vscode-jupyter#11704] opened 2022-10-19 08:25 UTC
## Environment data

-   VS Code version: 1.72.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1202862440
-   Python Extension version (available under the Extensions sidebar): v2022.16.1
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.10.5 / 2.1.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

![image](https://user-images.githubusercontent.com/72642816/196636786-cec0d919-0dad-43b2-a387-3ecf65afa629.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/72642816/196636424-8f61031f-dd22-4aff-937f-abbddb821b76.png)

## Steps to reproduce:

It is working properly in Jupyter Lab but no response in VSCode

All my packages version:
![image](https://user-images.githubusercontent.com/72642816/196637674-958a744b-f72e-4c8a-81b5-49770f2babd6.png)

**Comment by DonJayamanne** [comment] 2022-10-19 08:44
Duplicate of #8552

**Closed by DonJayamanne** 2022-10-19 08:44 UTC
Labels: bug
