### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jdSheu** [microsoft/vscode-jupyter#4522] opened 2021-01-27 08:30 UTC
- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2020.12.414227025`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1239,
		"activateCallTime": 13,
		"activateResolvedTime": 8407,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": []
}
```

**Comment by jdSheu** [comment] 2021-01-27 08:34
<Neophyte:> New around here. Haven't done enough reading to be fully aware of all involvements at the moment, but the long night turns into a long day most often and I hope to have a better understanding of my potential here.
Please excuse any ignorant actions for a bit. THX!

**Comment by rchiodo** [comment] 2021-01-27 18:26
Thanks for the bug.

Closing as a dupe of #4472

Seems like there's a potential slowdown in our activation.

**Closed by rchiodo** 2021-01-27 18:26 UTC
