### ISSUE TITLE
Language of a cell on opening a notebook keeps switching back to python

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4934] opened 2021-02-24 00:30 UTC
I have a julia notebook that I saved.

Reopening it causes this problem:

![image](https://user-images.githubusercontent.com/19672699/108927028-61e80e00-75f4-11eb-9f04-65f3af80b756.png)

**Comment by jaymegordo** [comment] 2021-02-24 17:19
@rchiodo on a similar note, I also notice that when I add a new code cell, the default language often (but not always) gets set to "plain text" instead of Python. I can't really notice a pattern when it works/doesn't but I'd expect every new code cell to always be set to Python.

jupyter: v2021.3.583204716-dev
python: v2021.3.593199507-dev

Version: 1.54.0-insider
Commit: 4e1234963a10831b2cf76ff08c4c657e3b7a2866
Date: 2021-02-24T05:14:48.525Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by gusbemacbe** [comment] 2021-02-24 22:00
I had this bug as well for two weeks. They always changed the cells from Shell Script to Python.

**Comment by DonJayamanne** [comment] 2021-02-24 22:59
Duplicate of #4757

**Closed by DonJayamanne** 2021-02-24 22:59 UTC
Labels: bug
