### ISSUE TITLE
Webview: Opening a notebook that points to a kernel with no ipykernel shows a modal dialog.

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6083] opened 2021-06-02 21:16 UTC
Create a venv with no ipykernel
Pick this in the kernel dropdown for a webview notebook

This dialog will immediately appear:
![image](https://user-images.githubusercontent.com/19672699/120553220-155b5e00-c3ad-11eb-9f80-9db16024aef9.png)

**Comment by DonJayamanne** [comment] 2021-06-02 22:19
This is how it works today in stable for webview (with the exception its not a modal dialog).
Closing as this is existing functionality.

**Comment by rchiodo** [comment] 2021-06-02 22:59
Yes I'm saying it shouldn't work this way. I understand it isn't a regression.

**Comment by DonJayamanne** [comment] 2021-06-03 17:56
Considering this is how it has been for a while, i do'nt see any value in investing work on this when native will trump this, also users haven't complained about this.

**Comment by rchiodo** [comment] 2021-06-04 15:35
I had some more thoughts on this:
- The dialog being modal sucks. I'm not sure this happens on opening a notebook or not. This needs to be verified. Create a notebook outside that points a python with no ipykernel
- The auto start of a kernel is something I think we want to continue though. Note, this is different than auto start of the server. That's starting jupyter (when jupyter is necessary). Auto starting the kernel was done for a number of reasons:
   1. Faster start for running a cell. We had a lot of feedback that we were slower than jupyter. We don't get this feedback anymore. That's because we auto start every kernel on opening a notebook. 
   2. Status of the kernel. We had a lot of feedback that people didn't know why the kernel wasn't started. They didn't know how (meaning hitting run a cell was not clear).

So given all of that, I think the fix for this is to just disable the error UI when we auto start the kernel. The error UI will still come up if the user tries running a cell, but for the majority case, the kernel would start as it normally do.

I don't think we should just stop auto staring a kernel.

**Comment by DonJayamanne** [comment] 2021-06-04 18:10
Related to #6082, same code, caused by same changes, hence taking this to be fixed along with #6082

**Comment by DonJayamanne** [comment] 2021-06-04 20:36
I haven't been able to replicate the issue described. I have auto start, and don't get a modal dialog.
Tried with RAW & without RAW, still not able to repro.
However what I did manage to repro is `switching kernels is impossible` we get a prompt everytime about ipykernel not being installed, trying to siwthc kernels from UI or command palette will display this message. no way around id.

@rchiodo when possible I'd like to see what's going on at your end, to understand the exact issue.
FYI - The PR #6136 only fixes the modal that prevents kernel changing.

**Comment by rchiodo** [comment] 2021-06-04 21:04
Sorry not sure what you aren't reproing. 

The bug as original entered was the dialog coming up during switch kernels. Sounds like you're reproing this?
I thought it _might_ also repro with opening a notebook with a kernel that didn't have ipykernel. It sounds like this isn't true? That auto start is already skipping the UI?

**Comment by DonJayamanne** [comment] 2021-06-07 20:28
> Sounds like you're reproing this?

yes

> I thought it might also repro with opening a notebook with a kernel that didn't have ipykernel. It sounds like this isn't true? 

Yes, not true.

> That auto start is already skipping the UI?

Yes, hence I don't get any modals with auto start.

Moving to validate.

**Comment by IanMatthewHuff** [comment] 2021-06-11 00:16
Validated. There is a lot of discussion on this, so a bit hard to validate.

I did the following:

IW - Non-modal prompt to install ipykernel
Native notebook - Model prompt to install when executing on missing pykernel
Webview Notebook - Model prompt when switching to missing ipykernel env.

Also checked that I could open a webview notebook with a kernel with ipykernel missing and select a different one.

**Closed by IanMatthewHuff** 2021-06-11 00:16 UTC
Labels: bug
