### ISSUE TITLE
debugging cell for untitled python file behaves poorly

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10599] opened 2022-06-27 22:39 UTC
Issue Type: <b>Bug</b>

1. Create a new file and select python language
2. create a 'cell' with some code
```
# %%
print(1)
print(2)
```
3. click the debug cell code lens
4. (save dialog pops up) save the file

Actual result:
Python file is abrubtly closed, IW opens and attempts to run the cell, cell errors with 
```
Illegal value for `line`. 
View Jupyter log for further details.
```

Extension version: 2022.6.1001801035
VS Code version: Code - Insiders 1.69.0-insider (e71b6105ebb4fbcfbf38a1b62bcbafdb048d3468, 2022-06-27T07:59:47.622Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (14.12GB free)|
|Process Argv|--folder-uri file:///c%3A/src/vscode-jupyter --crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by DonJayamanne** [comment] 2022-06-27 22:56
Not sure why this is a regression, I can repro the same behaviour in stable & insiders.
Does this work without any issues in VS Code stable & jupyter stable version today?

Basically once you hit save, things go bonkers in stable & insiders & I get the same behaviour.
However I don't get the error message you have mentioned about `Illegal value for line...`

**Comment by greazer** [comment] 2022-06-28 17:34
Yeah, I repro in stable too on Mac. Not marking as "important" since it seems there is very little potential data loss. What I see is that the file is actually saved, containing any source that may have already been entered.

**Comment by roblourens** [comment] 2022-12-09 18:22
Here I can probably just set the flag to disable saving when debug starts

**Comment by roblourens** [comment] 2022-12-09 23:49
I see that we save manually because the python debugger doesn't support debugging untitled files. So I removed that check for the new debugger, where debugging untitled files works fine (except for https://github.com/microsoft/vscode/issues/168675).

With the old debugger, breaking in the saved file breaks entirely for some reason
<img width="478" alt="image" src="https://user-images.githubusercontent.com/323878/206813265-782430bf-5044-4ec2-a97b-522aafdcdd03.png">

**Closed** 2022-12-10 00:56 UTC
Labels: bug, interactive-window-debugging, iw-golden
