### ISSUE TITLE
`rich` progress bar creates two empty elements upon completion

### ISSUE THREAD

**Issue by ma-sadeghi** [microsoft/vscode-jupyter#12289] opened 2022-12-04 03:09 UTC
## Environment data
-   VS Code version: 1.73.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1303220346
-   Python Extension version (available under the Extensions sidebar): v2022.18.2
-   OS (Windows | Mac | Linux distro) and version: Linux x64 5.17.5-76051705-generic (Ubuntu 20.04)
-   Python and/or Anaconda version: 3.9.13
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Same as "Actual behaviour" without the extra empty elements. I've tested the same code snippet in both vanilla IPython as well as JupyterLab environments (browser), and the progress bar renders just fine, without the extra empty elements.

## Actual behaviour

![image](https://user-images.githubusercontent.com/14086031/205472101-e982adbf-7a05-419e-9247-3921d26a35a0.png)

## Steps to reproduce:

1. Create a new notebook, and run the following Python code:
```python
import time
from rich.progress import track

for n in track(range(10), description="Processing..."):
    time.sleep(0.1)
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
info 22:03:02.742: Restart requested file:///home/amin/Code/Notebooks/test2.ipynb
info 22:03:02.742: Restart kernel execution
info 22:03:02.743: Restarting b9903df6-9931-4434-a511-9635c5a9b86a
info 22:03:02.744: Got env vars ourselves faster /home/amin/mambaforge/envs/sci/bin/python with env var count 91 in 1ms
info 22:03:02.799: Process Execution: > ~/mambaforge/envs/sci/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/mambaforge/envs/sci/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 22:03:02.817: Got env vars ourselves faster /home/amin/mambaforge/envs/sci/bin/python with env var count 91 in 0ms
info 22:03:02.817: Got env vars ourselves faster /home/amin/mambaforge/envs/sci/bin/python with env var count 91 in 0ms
info 22:03:02.956: Process Execution: > ~/mambaforge/envs/sci/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9018 --control=9016 --hb=9015 --Session.signature_scheme="hmac-sha256" --Session.key=b"59711ede-0c4b-4c92-89da-cd629213dd72" --shell=9017 --transport="tcp" --iopub=9019 --f=/home/amin/.local/share/jupyter/runtime/kernel-v2-2456302xX6NrEIk21fl.json
> ~/mambaforge/envs/sci/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9018 --control=9016 --hb=9015 --Session.signature_scheme="hmac-sha256" --Session.key=b"59711ede-0c4b-4c92-89da-cd629213dd72" --shell=9017 --transport="tcp" --iopub=9019 --f=/home/amin/.local/share/jupyter/runtime/kernel-v2-2456302xX6NrEIk21fl.json
info 22:03:02.958: Process Execution: cwd: ~/Code/Notebooks
cwd: ~/Code/Notebooks
info 22:03:03.067: ipykernel version & path 6.15.2, ~/mambaforge/envs/sci/lib/python3.9/site-packages/ipykernel/__init__.py for /home/amin/mambaforge/envs/sci/bin/python
warn 22:03:03.936: StdErr from Kernel Process /home/amin/mambaforge/envs/sci/lib/python3.9/site-packages/traitlets/traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 22:03:03.937: StdErr from Kernel Process /home/amin/mambaforge/envs/sci/lib/python3.9/site-packages/traitlets/traitlets.py:2346: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '59711ede-0c4b-4c92-89da-cd629213dd72' instead of 'b"59711ede-0c4b-4c92-89da-cd629213dd72"'.
  warn(

info 22:03:03.953: Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-2456302xX6NrEIk21fl.json

info 22:03:04.048: Got new session a2185d07-c497-4555-be08-7d49dcd9eec7
info 22:03:04.048: Started new restart session
info 22:03:04.049: Dispose Kernel process 2729414.
info 22:03:05.020: Got env vars with python /home/amin/mambaforge/envs/sci/bin/python, with env var count 92 and custom env var count 0 in 2277ms
info 22:03:05.150: Got env vars with python /home/amin/mambaforge/envs/sci/bin/python, with env var count 92 and custom env var count 0 in 2333ms
info 22:03:05.159: UpdateWorkingDirectoryAndPath in Kernel
info 22:03:05.254: Got env vars with python /home/amin/mambaforge/envs/sci/bin/python, with env var count 92 and custom env var count 0 in 2437ms
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2022-12-05 23:31
Duplicate of #9397

**Closed by DonJayamanne** 2022-12-05 23:31 UTC
Labels: bug
