### ISSUE TITLE
I can't paste image in Jupyter Notebook's markdown cell ,when I changed "Jupyter: Notebook File Root"

### ISSUE THREAD

**Issue by jadelxy1997** [microsoft/vscode-jupyter#12555] opened 2023-01-17 16:29 UTC
## Environment data

VS Code version: 1.74.3
Jupyter Extension version (available under the Extensions sidebar):
Last released
1/11/2023, 18:14:03
Last updated
1/4/2023, 21:12:02
Python Extension version (available under the Extensions sidebar):
Last released
1/11/2023, 18:27:32
Last updated
1/6/2023, 23:40:36
OS (Windows | Mac | Linux distro) and version: Windows11
Python and/or Anaconda version: Anaconda:3.9.15
Type of virtual environment used : conda
Jupyter server running: Local

## Expected behaviour

please tell me how to make it worked.(all pictures are invalid)

## Actual behaviour

1. I set "Jupyter: Notebook File Root" from "${fileDirname}" to "${workspaceFolder}".
2. then I can't paste image in Jupyter Notebook's markdown cell, it display blank and all pictures are invalid.
3.  I reset "Jupyter: Notebook File Root" to "${fileDirname}" ,it still didn't work.

## Steps to reproduce:
1.
![image](https://user-images.githubusercontent.com/54530758/212957975-80ac0f25-4823-4767-823c-8b6207fab9cf.png)
2.
![image](https://user-images.githubusercontent.com/54530758/212958053-0145d1c2-de94-43d2-aff8-56b189cd07a9.png)
3.
![image](https://user-images.githubusercontent.com/54530758/212958328-d35a9daa-ca78-4825-b439-172f1578d9cf.png)
4.
![image](https://user-images.githubusercontent.com/54530758/212958403-85895631-e847-4ebf-9392-8f5f6541945a.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by MBerman9** [comment] 2023-01-17 20:53
I'm on Windows and had the same issue.
Changing the version of the "Jupyter Notebook Renderers" extension back to v1.0.12 fixed the problem.
---
To whoever the following means something, this is the VSCode info.

Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by mjbvz** [comment] 2023-01-18 18:47
I'm not sure what `Jupyter: Notebook File Root` is or does, but it this doesn't happen without touching that setting, it sounds like a Jupyter specific issue

**Comment by amunger** [comment] 2023-01-18 22:31
duplicate of https://github.com/microsoft/vscode-jupyter/issues/12568, working on pushing out a new version

**Closed by amunger** 2023-01-18 22:31 UTC
Labels: bug
