### ISSUE TITLE
Sys Info message not updated when you do a change kernel operation

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#9460] opened 2022-03-23 18:30 UTC
Testing #9435

Not a big issue that I see, but if you launch with a kernel that doesn't have ipykernel and choose to swap to a different kernel that also needs an install the sys info message isn't updated.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/812783/159770710-06e18444-90d7-41f9-9358-e01c27bf8460.png">

In the example above I launched with newEnv2 (has no ipykernel) and choose to swap to newEnv3 (has no ipykernel) while performing the install the sys info message still says connected to newEnv2.

**Comment by DonJayamanne** [comment] 2022-03-23 20:50
duplicate of https://github.com/microsoft/vscode-jupyter/issues/9454

got a pr in progress that fixes this

**Closed by DonJayamanne** 2022-03-23 20:50 UTC
Labels: needs-triage
