### ISSUE TITLE
Native Notebook Features / toolbar icons missing on Mac

### ISSUE THREAD

**Issue by astrowonk** [microsoft/vscode-jupyter#4668] opened 2021-02-05 01:34 UTC
## Environment data

-   VS Code version: Version: 1.53.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS : Mac Catalina 
-   Python and/or Anaconda version: 3.8
-   Type of virtual environment used (N/A )
-   Jupyter server running: Local

## Expected behaviour

Jupyter buttons such as variable inspector / disconnect /etc. appear in the VS Code window.

## Actual behaviour

Most icons and fuctionality missing.

<img width="893" alt="Screen Shot 2021-02-04 at 8 28 02 PM" src="https://user-images.githubusercontent.com/13702392/106977385-40e47980-6728-11eb-974c-198bf2c2379d.png">

## Steps to reproduce:

Use VS Code insiders on a Mac.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'NativeNotebookEditor'
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/opt/python@3.8/bin/python3.8 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-02-04 20:26:03: Jupyter Kernel Spec not found for a local connection
Error 2021-02-04 20:26:07: Jupyter Kernel Spec not found for a local connection
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Started kernel Python 3.8.6 64-bit
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> /usr/local/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v

```

</p>
</details>

**Comment by astrowonk** [comment] 2021-02-05 01:35
I would expect to see more icons and chrome like so:

<img width="501" alt="Screen Shot 2021-02-04 at 8 34 49 PM" src="https://user-images.githubusercontent.com/13702392/106977525-83a65180-6728-11eb-8b0c-a35c38abff94.png">

in all the various demos and videos of the new notebook editor I have seen.

**Comment by rchiodo** [comment] 2021-02-05 18:54
Thanks for the bug. This is a dupe of #4552. You should be able to get the toolbar to appear if you give input focus to the code in a cell.

**Closed by rchiodo** 2021-02-05 18:54 UTC
Labels: bug
