### ISSUE TITLE
Error: No version of module nglview-js-widgets is registered

### ISSUE THREAD

**Issue by dtunai** [microsoft/vscode-jupyter#15811] opened 2024-07-01 07:57 UTC
Hi vscode-jupyter team,

I'm encountering an error related to nglview-js-widgets in my Jupyter kernel, which causes the kernel to crash. My nglview version is currently set to latest nglview-3.1.2 but tried with different versions still not worked for me.

Error details are as follows:

```bash
[error] Widget load failure {} [ 'jsdelivr.com', 'unpkg.com' ] {
  className: 'ColormakerRegistryModel',
  moduleName: 'nglview-js-widgets',
  moduleVersion: '3.1.0',
  isOnline: true,
  timedout: false,
  error: '{}'
}
[error] Disposing session as kernel process died ExitCode: undefined, Reason: 
```

Thanks!

**Comment by DonJayamanne** [comment] 2024-07-01 15:26
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15757

**Closed by DonJayamanne** 2024-07-01 15:26 UTC
Labels: bug
