### ISSUE TITLE
Notebook grabs attention while processing

### ISSUE THREAD

**Issue by sbland** [microsoft/vscode-jupyter#1425] opened 2020-07-07 12:54 UTC
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Create a notebook and run a few cells
2. Switch tab while it is still running

## Actual behavior
Auto switches back to the notebook tab while it is processing
## Expected behavior
Continues in background

### Your Jupyter and/or Python environment

-   **Jupyter server running:** Local
-   **Extension version:** Python v2020.6.91350
-   **VS Code version:** 1.46.1
-   **OS:** Ubuntu

**Comment by greazer** [comment] 2021-01-05 21:56
Also a dupe of #1260

**Closed by greazer** 2021-01-05 21:56 UTC
Labels: bug
