### ISSUE TITLE
Seaborn heat map doesn't display annotations for all rows

### ISSUE THREAD

**Issue by realashwin** [microsoft/vscode-jupyter#14363] opened 2023-09-23 13:36 UTC
Type: <b>Bug</b>

1.  Generate seaborn heatmap using any data frame.
2. Ensure that "annot" is set  "True".
3. Observe that only first row displays values on the heatmap

Extension version: 2023.8.1002501831
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (8.08GB free)|
|Process Argv|--crash-reporter-id 15e171f7-df7b-41d5-b1ba-265661fec985|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmhint1:30842940
dsvsc015cf:30829746

```

</details>

![image](https://github.com/microsoft/vscode-jupyter/assets/62036136/6292701d-80c8-4a29-a71c-72f1c901191c)

![image](https://github.com/microsoft/vscode-jupyter/assets/62036136/3e371a9f-a9f5-4897-a62f-3253704886f2)

**Comment by rvanxer** [comment] 2023-09-25 21:54
I'm facing a similar issue. For some reason, the newer version of seaborn (v0.12.2) shows annotations sequentially for the no. of cells which is equal to the no. of rows in the input matrix/dataframe. I reproduced this issue for several cases.
![Screenshot 2023-09-25 at 5 52 24 PM](https://github.com/microsoft/vscode-jupyter/assets/13570548/ea3913e0-5ea1-42a1-9435-aaa71aeb630a)

**Comment by DonJayamanne** [comment] 2023-09-26 01:33
@realashwin @rvanxer 
Thank you for filing this issue and sorry you are running into this.
* Please could you share a simple sample that I can run at my end (FYI i do not know much about sea born package, hence the request)
* Please try to keep the package dependencies to a minimum and please do list them so I can setup my end at my end.

Also, please can you confirm this issue only exists in VS Code.
* Run the following code in VS Code and Jupyter Lab to verify you are using the same Python environment
    ```python
    import sys
    sys.executable
    ```
* Try the same code in Jupyter lab to verify you do not run in to same issue
* If you do run into the same issue in Jupyter lab, please check if there are any errors in the terminal or in the browser

**Comment by rvanxer** [comment] 2023-09-26 03:39
```python
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

A = np.random.rand(5, 3)
fig, ax = plt.subplots(figsize=(3, 3)
sns.heatmap(A, ax=ax, annot=True, fmt='.1f')
```

**Comment by DonJayamanne** [comment] 2023-09-26 05:02
> error also appears in Jupyter Lab. So, I guess it's an error with seaborn, not VS Code.

thanks, closing this issue

**Closed by DonJayamanne** 2023-09-26 05:02 UTC
Labels: bug, info-needed, jupyter-output

**Comment by realashwin** [comment] 2023-09-26 05:30
@DonJayamanne Apologies for the delay in response. The error also appears in the Jupyter Lab. I believe then this is a bug in the Seaborn Package.

**Comment by bluewalker-vivant** [comment] 2023-09-29 15:38
Looks like problem goes away if I downgrade MATPLOTLIB to version 3.7.3.

**Comment by bluewalker-vivant** [comment] 2023-09-29 15:39
I experienced the same thing, but it was improved by setting MATPLOTLIB to version 3.7.3.
