### ISSUE TITLE
Python: Select Interpreter and Notebook "Select a Python Environment" are inconsistent

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode-jupyter#15816] opened 2024-07-02 05:30 UTC
"Python: Select Interpreter" shows a list of "discovered" python environments, plus there's an option "+ Enter interpreter path". But this option isn't present when choosing a python environment for notebooks (instead there's a list of "discovered" python environments, plus an option to "+ Create Python Environment".

I have one notebook that has requirements that conflict with the main project requirements, so I want to create a separate venv just for that notebook in my notebooks folder, i.e.

```
/
.venv/
notebooks/
    .venv/
    notebook.ipynb
```

It would be nice if the "change kernel" option accepted a venv path.

**Comment by DonJayamanne** [comment] 2024-07-02 12:59
Thanks for this suggestion, you can instead use `Python: Select Interpreter` enter the path in there and then go into the kernel picker and then the new Python env should now show up.
Please let me know if this doesn't work.

**Comment by david-waterworth** [comment] 2024-07-03 02:17
Thanks @DonJayamanne  - you're right, temporarily using `Python: Select Interpreter` works.

**Comment by DonJayamanne** [comment] 2024-07-22 00:03
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15087

**Closed by DonJayamanne** 2024-07-22 00:03 UTC
Labels: feature-request
