### ISSUE TITLE
The jupyter notebook doesn't have correct code suggestion when typing `''`

### ISSUE THREAD

**Issue by Micro-sheep** [microsoft/vscode-jupyter#7951] opened 2021-10-16 03:28 UTC
## Environment data

-   VS Code version: 1.61.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1336267007
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: python 3.7
-   Type of virtual environment used : conda
-   Jupyter server running: Local

## Expected behaviour

When typing `''`, there should not be any suggestion like typing in `.py` file.

![image](https://user-images.githubusercontent.com/56242295/137572014-d29eb911-073a-4cb0-bc7c-2e5be281dfb8.png)

## Actual behaviour

When typing in jupyter, it show suggestions like bellow
![image](https://user-images.githubusercontent.com/56242295/137571879-96560b35-fc50-4bdd-9871-abc8cd3acde6.png)

## Steps to reproduce:

1. Create a new `.ipynb` file and edit it in vscode
2. Select `python 3.7` as kernel
3. Type `''` or `""` in cell in jupyter
4. Then you will see incorrect suggestions like above.

**Comment by claudiaregio** [comment] 2021-10-16 04:36
Dupe of https://github.com/microsoft/vscode-jupyter/issues/7880

**Closed by claudiaregio** 2021-10-16 04:36 UTC
Labels: bug, needs-triage
