### ISSUE TITLE
duplicate/double information shown when hovering over symbols 

### ISSUE THREAD

**Issue by MrVPlusOne** [microsoft/vscode-jupyter#12177] opened 2022-11-27 03:58 UTC
## Environment data

-   VS Code version: 1.73.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1303220346
-   Python Extension version (available under the Extensions sidebar): v2022.18.2
-   OS (Windows | Mac | Linux distro) and version: MacOS 13.0.1
-   Python and/or Anaconda version: 3.10.4 (doesn't seem to matter)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pipenv
-   Jupyter server running: Happens both on local or on a remote machine via Remote-SSH plugin

## Expected behaviour

Symbol information on hover should only display once.

## Actual behaviour

The information is displayed twice after a Jupyter notebook is opened (as shown below). Sometimes one copy of the information is incorrect (e.g., displaying variable type as unknown).

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/11240361/204118311-1ed47365-671f-41f9-acbc-d11faa19023f.png">

<img width="878" alt="image" src="https://user-images.githubusercontent.com/11240361/204118285-813d726d-749a-45ba-abae-fe4d17053f4a.png">

## Steps to reproduce:

1. Open a python project with a `.py` and a `.ipynb` file in the same directory.
2. In the `.ipynb` notebook, import a symbol from the `.py` file.
3. Hover the mouse on any symbol, two copies of symbol information will be shown instead of the expected one copy.

</details>

**Comment by DonJayamanne** [comment] 2022-12-02 01:51
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11038

**Closed by DonJayamanne** 2022-12-02 01:51 UTC
Labels: bug
