### ISSUE TITLE
dataviewer cannot handle UUID column type

### ISSUE THREAD

**Issue by nmillerPCMC** [microsoft/vscode-jupyter#14318] opened 2023-09-12 20:46 UTC
## Environment data

-   VS Code version: v1.82.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.8.1002501831
-   Python Extension version (available under the Extensions sidebar): v2023.16.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: v3.11.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Poetry
-   Jupyter server running: N/A

## Expected behaviour

DataViewer displays the pandas dataframe

## Actual behaviour

never displays and shows endless loading progress bar

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. #code example
import pandas as pd
import uuid

df=pd.DataFrame(columns=['Number','Text','UUID'])
Number=[i for i in range(10)]
df.Number=Number
Text=["String"+str(i) for i in range(10)]
df.Text=Text
Text=["String"+str(i) for i in range(10)]
df.Text=Text
UUIDcol=[uuid.uuid4() for i in range(10)]
df.UUID=UUIDcol
df

2.  then select Show Variable Snapshot in DataViewer from Jupyter tab

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment] 2023-12-14 23:47
duplicate of https://github.com/microsoft/vscode-jupyter/issues/13619

**Closed by amunger** 2023-12-14 23:47 UTC
Labels: bug, data-viewer
