### ISSUE TITLE
cannot connect to multiple remote servers with passwords 

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#13809] opened 2023-06-28 21:39 UTC
create two independent jupyter servers with passwords

`jupyter notebook password` to set a password (delete the file from the output to unset it)
`jupyter notebook` in two different terminals
in vscode:
1. open a notebook
2. add both servers through the kernel picker
3. reload vscode
4. enter the password again when prompted
5. try to connect to each server
🐛 one of them will be un-reachable because the password was never entered

we should allow passwords to be entered on connection attempt, rather than restricting it to extension startup

**Comment by DonJayamanne** [comment] 2023-07-18 20:32
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/13942
https://github.com/microsoft/vscode-jupyter/issues/13671

**Closed by DonJayamanne** 2023-07-18 20:32 UTC
Labels: bug
