### ISSUE TITLE
Jupyter Notebook Export to HTML does not open the exported file from Azure ML

### ISSUE THREAD

**Issue by iemejia** [microsoft/vscode-jupyter#11454] opened 2022-09-26 10:38 UTC
## Environment data

**VS Code Environment:**
Version: 1.72.0-insider
Commit: b9f7f85e90b4d51b38fcbf4232801ab04bd659cb
Date: 2022-09-23T08:15:07.186Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**VS Code Extensions**
Jupyter Extension: v2022.9.1002681037 Pre-Release
Python Extension: v2022.15.12631011 Pre-Release
Azure Machine Learning - Remote: v0.19.2022092309 Pre-Release
Azure Data Lake Tools: v0.2.15

**Python Environment**
Conda: 4.13.0
Python: 3.9.13
Type of virtual environment: Conda + IPyKernel

**.net Environment**
.net: 6.0.401

**Operating System**
macOS Monterrey 12.6
Macbook Air (M1, 2020)

## Expected behaviour

After exporting a notebook as an `.html` file on Azure ML when VS Code asks `Would you like to open the exported file?` I expect the resulting `.html` to open. (The file is created correctly but it just does not open)

## Actual behaviour

Nothing happens after clicking on the Yes button.

Notice however that for the local export it opens correctly.

## Steps to reproduce:

1. Create a python notebook on Azure ML
2. Open with VS Code
3. Export the notebook to HTML
4. Once exported click yes to the question `Would you like to open the exported file?`

This 'video' shows both behaviours for the remote and local export, for the remote nothing happens when trying to open, for the local it works correctly.
![reportbug-azuremlremote19](https://user-images.githubusercontent.com/79476/192256462-bc4cc9ac-cd74-470e-a2bc-f322b0c24349.gif)

**Comment by amunger** [comment] 2022-09-26 17:46
dupe of https://github.com/microsoft/vscode-jupyter/issues/10743

**Closed by amunger** 2022-09-26 17:46 UTC
Labels: bug, triage-needed
