### ISSUE TITLE
`xeus` Python kernel is currently not supported (hence hidden)

### ISSUE THREAD

**Issue by steffenhennig** [microsoft/vscode-jupyter#5469] opened 2021-04-09 15:53 UTC
## Environment data

-   VS Code version: 1.55.1
-   Jupyter Extension version: v2021.5.702919634
-   Python Extension version: v2021.3.680753044
-   Windows 10
-   Anaconda version: 4.10
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

Start Interactive Window to run cells (#%%) within VSC

Worked fine until last VSC update

## Actual behaviour

Interactive Window fails to start

Unsupported KernelSpec file. args must be [<pythonPath>, '-m', <moduleName>, arg1, arg2, ..]. Provied C:/Users/Steffen/Anaconda3/Library/bin/xpython --ip=127.0.0.1 --stdin=9092 --control=9090 --hb=9089 --Session.signature_scheme="hmac-sha256" --Session.key=b"baa190ae-91cc-46bd-84e8-f36673c6ec37" --shell=9091 --transport="tcp" --iopub=9093 --f=C:\Users\Steffen\AppData\Local\Temp\tmp-15216aFf72oCC3gGk.json

**Comment by claudiaregio** [comment] 2021-04-09 23:55
Hi @steffenhennig I am unable to reproduce at this time. Could you provide all the logs when this issue occurs? 
Terminal -> New Terminal -> Outputs -> Jupyter (please be sure to clear the outputs by clicking on the button I've circled to the right and make sure the following underlined items match). Reproduce the issue and please attach the logs to help us troubleshoot a bit further

![image](https://user-images.githubusercontent.com/19276747/114250944-33c84e80-9954-11eb-82e1-998aa7be86af.png)

**Comment by steffenhennig** [comment] 2021-04-20 18:05
Errors from log-file below:

Error 2021-04-20 11:01:19: Launching kernel daemon, Class name = h, completed in 837ms, has a falsy return value, Arg 1: <Uri:c:\Users\Steffen\xyz\Untitled-1.ipynb>, Arg 2: "c:\\Users\\Steffen\\xyz", Arg 3: {"specFile":"C:\\Users\\Steffen\\Anaconda3\\share\\jupyter\\kernels\\xpython\\kernel.json","interpreterPath":"C:\\Users\\Steffen\\Anaconda3\\python.exe","name":"python385jvsc74a57bd0d406764cf7b946f86536b69511a8b6f70f1dfb17940e02446b1a7c3a63b579ac","argv":["C:/Users/Steffen/Anaconda3/Library/bin/xpython","--ip=127.0.0.1","--stdin=9003","--control=9001","--hb=9000","--Session.signature_scheme=\"hmac-sha256\"","--Session.key=b\"05c116d5-e987-42a9-a0a0-b71160cd874d\"","--shell=9002","--transport=\"tcp\"","--iopub=9004","--f=C:\\Users\\Steffen\\AppData\\Local\\Temp\\tmp-3236MGQQRjQZz5ti.json"],"language":"python","path":"C:/Users/Steffen/Anaconda3/Library/bin/xpython","display_name":"Python 3.8.5 64-bit (conda)","metadata":{"debugger":true}}, Arg 4: {"architecture":3,"path":"C:\\Users\\Steffen\\Anaconda3\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysVersion":"3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]","sysPrefix":"C:\\Users\\Steffen\\Anaconda3","fileHash":"dc146f2ba95052ed212bdaf2a1ecbf7e1fa194db7a049415c412a70a027d26e1a7d487b8e941f391f32bb8f556cd5b1810e4619d6c73d23aba0331c24cd9bc41","companyDisplayName":"Anaconda, Inc.","envType":"Conda","cachedEntry":true,"displayName":"Python 3.8.5 64-bit (conda)"}, Return Value: undefined [Error: Unsupported KernelSpec file. args must be [<pythonPath>, '-m', <moduleName>, arg1, arg2, ..]. Provied C:/Users/Steffen/Anaconda3/Library/bin/xpython --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"05c116d5-e987-42a9-a0a0-b71160cd874d" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\Steffen\AppData\Local\Temp\tmp-3236MGQQRjQZz5ti.json
	at h.launch (c:\Users\Steffen\.vscode\extensions\ms-toolsai.jupyter-2021.5.745244803\out\client\extension.js:47:797283)
	at runNextTicks (internal/process/task_queues.js:62:5)
	at processImmediate (internal/timers.js:429:9)]
Error 2021-04-20 11:01:19: Launching kernel in kernelProcess.ts, Class name = _, completed in 839ms, has a falsy return value, Arg 1: "c:\\Users\\Steffen\\xyz", Return Value: undefined [Error: Unsupported KernelSpec file. args must be [<pythonPath>, '-m', <moduleName>, arg1, arg2, ..]. Provied C:/Users/Steffen/Anaconda3/Library/bin/xpython --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"05c116d5-e987-42a9-a0a0-b71160cd874d" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\Steffen\AppData\Local\Temp\tmp-3236MGQQRjQZz5ti.json
	at h.launch (c:\Users\Steffen\.vscode\extensions\ms-toolsai.jupyter-2021.5.745244803\out\client\extension.js:47:797283)
	at runNextTicks (internal/process/task_queues.js:62:5)
	at processImmediate (internal/timers.js:429:9)]
Error 2021-04-20 11:01:19: Failed to connect raw kernel session: Error: Unsupported KernelSpec file. args must be [<pythonPath>, '-m', <moduleName>, arg1, arg2, ..]. Provied C:/Users/Steffen/Anaconda3/Library/bin/xpython --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"05c116d5-e987-42a9-a0a0-b71160cd874d" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\Steffen\AppData\Local\Temp\tmp-3236MGQQRjQZz5ti.json
Info 2021-04-20 11:01:19: Shutdown session -- complete
Error 2021-04-20 11:01:19: Failed to determine if a notebook is active for the current editor [Error: Unsupported KernelSpec file. args must be [<pythonPath>, '-m', <moduleName>, arg1, arg2, ..]. Provied C:/Users/Steffen/Anaconda3/Library/bin/xpython --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"05c116d5-e987-42a9-a0a0-b71160cd874d" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\Steffen\AppData\Local\Temp\tmp-3236MGQQRjQZz5ti.json
	at h.launch (c:\Users\Steffen\.vscode\extensions\ms-toolsai.jupyter-2021.5.745244803\out\client\extension.js:47:797283)
	at runNextTicks (internal/process/task_queues.js:62:5)
	at processImmediate (internal/timers.js:429:9)]
Error 2021-04-20 11:01:19: DataScience Error [Error: Unsupported KernelSpec file. args must be [<pythonPath>, '-m', <moduleName>, arg1, arg2, ..]. Provied C:/Users/Steffen/Anaconda3/Library/bin/xpython --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"05c116d5-e987-42a9-a0a0-b71160cd874d" --shell=9002 --transport="tcp" --iopub=9004 --f=C:\Users\Steffen\AppData\Local\Temp\tmp-3236MGQQRjQZz5ti.json
	at h.launch (c:\Users\Steffen\.vscode\extensions\ms-toolsai.jupyter-2021.5.745244803\out\client\extension.js:47:797283)
	at runNextTicks (internal/process/task_queues.js:62:5)
	at processImmediate (internal/timers.js:429:9)]

**Comment by steffenhennig** [comment] 2021-04-20 18:05
Thanks for your help

**Comment by DonJayamanne** [comment] 2021-04-22 10:08
Oh you seem to be using the xeus kernel
Please could you confirm that.

**Comment by steffenhennig** [comment] 2021-04-22 17:05
After uninstalling xeus the problem disappears. Thanks.

**Comment by DonJayamanne** [comment] 2021-04-22 19:44
I'll keep this issue open, basically we need to ensure we do not treat xeus kernel as a Python kernel (that can be started using python code).

**Comment by DonJayamanne** [comment] 2021-05-03 19:44
The change is a little bigger:
* We need to treat xeus python kernels as special pytohn kernels
    * We cannot start them using the same way as other python kernels
    * Connections are different (hence we cannot update connection as we do for other kernels)
    * We cannot check for ipykernel & other dependencies the same way
* However variables, widgets, etc should work the same way

**Why should we support xeus:**
* We are a jupyter extension, anything that works in jupyter must work here too

**Why should we not prioritise support for xeus:**
*  I don't think this is a widely used kernel (i was under the impression this is exploratory)
* We might want to check our telemetry for this

**Comment by rchiodo** [comment] 2021-08-31 16:40
I believe this is working now. Adding to milestone so somebody will verify.

**Comment by DonJayamanne** [comment] 2021-09-27 19:46
THis is not working, we didn't do anytihng, we need to address the issues highlighted here https://github.com/microsoft/vscode-jupyter/issues/5469#issuecomment-831489218

**Comment by DonJayamanne** [comment] 2022-12-27 22:26
Closing this issue as its been a while since this was reported and we haven't had any others since then.

**Comment by DonJayamanne** [comment] 2023-07-02 23:10
Reopening as a user reported this issue

**Comment by DonJayamanne** [comment] 2023-10-27 05:19
Should be fine now, I tested this an its displayed.

**Closed by DonJayamanne** 2023-10-27 05:19 UTC
Labels: bug, notebook-kernel, language-any
