### ISSUE TITLE
Notebook gets stuck after deleting and undoing a cell in "Run by line" mode

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#7631] opened 2021-09-22 23:30 UTC
VS Code 1.61.0-insider + Jupyter extension v2021.9.1001261101

1. Open an ipynb file. 
2. Start "run by line", while it's running, hit "delete" in the cell toolbar so the cell is gone.
3. use menu Edit -> Undo to bring back the cell
4. hit "Continue" to continue running through the cell

expected: cell runs through fine
actual: cell runs forever, until the notebook is closed and reopened. Interrupt kernel button is disabled. Restart kernel works but doesn't stop the cell from running.

please refer to this video 14'40'' - 17'40'' https://msit.microsoftstream.com/video/12e10840-98dc-ae71-db7b-f1ec19e01ea4?list=studio

**Comment by DavidKutu** [comment] 2021-09-24 23:03
The above PR fixes the run by line and debugging related issues, but it still reproes while executing normally.

And that is a dupe of https://github.com/microsoft/vscode/issues/133782

**Closed by DavidKutu** 2021-09-24 23:03 UTC
Labels: bug, run-by-line, nb-golden
