### ISSUE TITLE
jupyter file cannot save data normal

### ISSUE THREAD

**Issue by p5ydn0** [microsoft/vscode-jupyter#3958] opened 2020-11-18 04:19 UTC
## Environment data

-   VS Code version: 版本: 1.51.1
-   OS and version: macOS 11.0.1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.3.
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A

## Expected behaviour

The data can be actually saved after clicking command + S

## Actual behaviour

After click command + S, the `*` in the upper right corner of the file name disappears. It seems that the data has been saved, but in fact, it is not saved at all.

## Steps to reproduce:

unknown. No pattern was found, but it does happen in some cases. Has happened many times.

f*!

**Comment by rchiodo** [comment] 2020-11-18 17:12
Thanks for the bug. We haven't seen this issue internally. Any more information you can give about a repro would be great.

For example do you have a notebook that this seems to happen on? What steps were you performing when the problem occurred? 

Can you also include the 'Jupyter' tab output?

**Comment by p5ydn0** [comment] 2020-11-19 05:56
> Thanks for the bug. We haven't seen this issue internally. Any more information you can give about a repro would be great.
> 
> For example do you have a notebook that this seems to happen on? What steps were you performing when the problem occurred?
> 
> Can you also include the 'Jupyter' tab output?

@rchiodo 

This bug happened again this morning.

I currently confirm that there will be at least two of the following situations:

1. Sometimes I modify the file at `time a` and save it (via command + S; confirm that the * sign in the upper right corner of the file name has disappeared), and then at some `time b` after `time a`, I found that the modified content of a cell is not displayed, and the display is still unmodified.

But after I closed the file, exited VSCode, and reopened the file, the modified content was displayed again. This situation is very strange, but fortunately.

2. The second situation is very bad. Similarly, I modify the file at a certain time and save it (via command + S; confirm that the * sign in the upper right corner of the file name has disappeared), and then I close and reopen the file, and I will find the latest modified content is not saved; only the earlier changes are saved.

Both yesterday and today resulted in the loss of my code, and I dare not use it anymore.

*More information that may be useful:*

1. My intuitive feeling is that the saved execution is like a queue. The problem is that although it shows that the latest modification has been saved, it is not actually saved;
2. There are about 300 cells in the jupyter file with these problems. Although there are occasional slight delays and freezes, I think this file is not very large. I am not sure if it is related to this.

Thank you.

**Comment by rchiodo** [comment] 2020-11-19 17:22
Can you share the notebook that causes the problem?

**Comment by rchiodo** [comment] 2020-11-19 18:26
The root cause of this problem is a mismatch between what the UI thinks and what the backend (VS code has an extension host process where our backend lives) thinks the contents of the notebook are .

We've heard this before, but it's always been really difficult to get a repro.

**Comment by rchiodo** [comment] 2020-11-19 18:28
You might have better luck using our newer notebook preview that we've been working on. 
https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

That doesn't have the separate processes trying to keep data in sync (VS code is handling updates).

**Comment by greazer** [comment] 2020-11-19 21:51
Dupe of #427.

**Closed by greazer** 2020-11-19 21:51 UTC

**Comment by p5ydn0** [comment] 2020-11-20 12:08
> Can you share the notebook that causes the problem?

@rchiodo 

Thanks for the reply and processing. I can send it to you before next Monday. How can I send it to you? Maybe you can give me an email?

**Comment by p5ydn0** [comment] 2020-11-20 12:10
> You might have better luck using our newer notebook preview that we've been working on.
> https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/
> 
> That doesn't have the separate processes trying to keep data in sync (VS code is handling updates).

Thanks Reply. I am very happy to know this news. I will continue to follow this progress of the project and hope to support it in the official version as soon as possible.

thanks again!

**Comment by rchiodo** [comment] 2020-11-20 17:15
> Thanks for the reply and processing. I can send it to you before next Monday. How can I send it to you? Maybe you can give me an email?

If you don't want to upload it here, you can e-mail it to me. My same github id followed by at microsoft.com.
