### ISSUE TITLE
Interactive plots failing to update: bokeh's push_notebook() not updating

### ISSUE THREAD

**Issue by lxvm** [microsoft/vscode-jupyter#1714] opened 2020-06-16 10:13 UTC
# Bug: Notebook Editor, Interactive Window, Editor cells

The issue I am reporting is essentially the same as in this other post
https://stackoverflow.com/questions/61872351/vscode-notebook-silently-failing-showmodify-doc
I have a program to create an interactive plot in bokeh that uses ipython widgets to update the data on a plot via updating a ColumnDataSource used by the bokeh plot. This works fine in a regular jupyter notebook, but in VS Code the plot never updates; ultimately I was able to narrow down the issue to the bokeh push_notebook() function never leading to the updates it should be making on the plot.

## Steps to cause the bug to occur
pseudocode for the issue:

import bokeh, ipywidgets, IPython
_Import database to be plotted_
_create columndatasource from database and plot some of that data_

**bokeh.plotting.show(_plot_ , notebook_handle=True)**

def graph_handler(_widget options_):
-   _retrieve new data from database using widget options_
-   _stream new data to columndatasource_
-    **bokeh.io.push_notebook()**

_create widgets_
output = ipywidgets.interactive_output(graph_handler, _widgets_)
IPython.display(_widgets_, output)
 
I suspect that the connection between the lines in bold is the issue because the columndatasource updates correctly. I'm wondering if the issue is due to the jupyter server not allowing the new data to communicate to the plot.

## Actual behavior (VS Code)
The widgets and the plot of the default data appear, however modifying the widgets does not change the data on the plot. E.g. the plot and widgets look like:
![image](https://user-images.githubusercontent.com/66997677/84760926-9263ac80-af7d-11ea-8b8e-d52d5777fa8e.png)
but when the widgets are changed the plots don't update.

## Expected behavior (Jupyter Notebook)
Same initial plot as in the image above, but when the widgets are changed (such as the state for the COVID19 data) then the data in the plot updates.

### Jupyter and/or Python environment

-   **Jupyter server running:** Local
-   **Extension version:** 2020.5.86806
-   **VS Code version:** #.##
-   **Setting python.jediEnabled:** true 
-   **Setting python.languageServer:** Microsoft 
-   **Python and/or Anaconda version:** 3.7.3
-   **OS:** Windows with a WSL2 remote connection to Debian
-   **Virtual environment:**  N/A 
-   **bokeh version** 2.1.0
-   **ipywidgets version** 7.5.1

**Comment by greazer** [comment] 2021-06-06 07:12
In native VS Code notebooks the examples that worked in the Python extension notebooks work now. However, the examples that didn't work in either still don't work in either.

**Comment by michaelaye** [comment] 2022-02-18 20:00
Here's a simple example using hvplot/holoviews/bokeh that doesn't work for me:

```python
import xarray as xr
import hvplot.xarray

arr = xr.DataArray(
    np.random.random((2, 3, 4)), 
    dims=['x', 'y', 'time'],
    coords={'x': np.arange(2), 'y': np.arange(3), 'time': np.arange(4)}
)

arr.hvplot(x='x', y = 'y')
```

This produces this view with a widget for going through the time dimension:

![image](https://user-images.githubusercontent.com/69774/154753146-8c9ffe99-f06f-46a8-9be7-9692a2d65857.png)

But the widget doesn't update the plot.

**Comment by DonJayamanne** [comment] 2022-08-15 00:04
@michaelaye apologies for not getting back to this issue.
I can repro this at my end and will look into this soon.

**Comment by DonJayamanne** [comment] 2022-12-06 21:42
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by michaelaye** [comment] 2022-12-07 07:21
What information request, I can’t see any? Last comment was that you can reproduce the issue?

**Comment by DonJayamanne** [comment] 2022-12-07 07:25
oops , so sorry, i think i posted the messages into the wrong issue

**Comment by DonJayamanne** [comment] 2022-12-08 00:00
Summary:
Looks like bokeh sets up some socket server of the like, and uses that to communicate back and forth (instead of using kernel comms).  
When starting kernels in VS Code we don't spin up a real jupyter server (at least not always), hence bokeh might not be able to setup these servers.

**Comment by DonJayamanne** [comment] 2022-12-27 22:19
I'm closing this issue as i've looked into this issue a lot and bokeh setting up its own communication is something that will not work with the jupyter extension, unless it uses ipywidgets to communicated with the kernel (instead of using a custom comms approach)
If someone can help figure out the problem and a fix i'd be happy to take this, else no real point leaving this issue open anymore.

**Closed by DonJayamanne** 2022-12-27 22:19 UTC
Labels: bug, ipywidgets, jupyter-output

**Comment by michaelaye** [comment] 2022-12-28 08:31
That’s fair. But closing it as “rejected” would have been even more fair.
