### ISSUE TITLE
WSL - jupyter notebook takes to long to open in VS Code Insiders. It's slow. loading performance 

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode-jupyter#5211] opened 2021-03-19 04:29 UTC
## Environment data

Version: 1.55.0-insider (user setup)
Commit: 111a6cec70f9562cdd31a5fd8cdea4b3a9b7bd82
Date: 2021-03-18T05:14:49.087Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

-   VS Code version: XXX
-   Jupyter Extension version v2021.4.641214696
-   Python Extension version v2021.3.658691958
-   Python and/or Anaconda version: 3.8.5 64bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA
-   Jupyter server running: Local

**Running WSL with Ubuntu 20.04 LTS**

On first load of a simple notebook, it can take 15 - 20 seconds for the Notebook to be ready. This is consistent on every reload of the workbench.

In this video I run it 2 times to show the consistency of the timings.

![recording](https://user-images.githubusercontent.com/1487073/111731374-94220f80-8830-11eb-8cfc-1d81eacf81ad.gif)

**Comment by DonJayamanne** [comment] 2021-03-19 15:11
Yikes, I think I know what's going on.
Please could you disable the python extension, we might be activating it too early. Fyi, we have a separate issue whee were trying to manage the dependency on python.

**Comment by chrisdias** [comment] 2021-03-19 15:49
If I disable the python extension, its about 3-4sec to bring up the notebook, which is much more inline with how my normal setup works on my surface with remote-wsl.  

I get this:

![image](https://user-images.githubusercontent.com/1487073/111807114-db8bb880-888f-11eb-911b-ee2e5225ad8a.png)

which seems a little weird since I can use multiple languages with Jupyter, right?  This is perhaps a 2nd issue.

I would do a timing video but it wouldn't help since by the time I moved the mouse to start the timer it would be done :).

**Comment by DonJayamanne** [comment] 2021-03-19 16:32
> s about 3-4sec to bring up the notebook, which is much more inline with how my normal setup works on my surface with remote-wsl.

Yup, i've figured out the cause. Thanks


> which seems a little weird since I can use multiple languages with Jupyter, right? This is perhaps a separate issue.

We're tracking this in a seprate issue. and i've got some fixes for this as well.
We want to display this message only for users who open python notebooks.
If you open a julia notebook, then you shouldn't get this prompt.

**Comment by DonJayamanne** [comment] 2021-03-19 16:39
## Notes
* I tested this on my a Windows machine at my end, and it takes ~32 seconds. 
* I made a few fixes to Jupyter & Python extension and can get it down to ~6 seconds
	* Changes to Jupyter https://github.com/microsoft/vscode-jupyter/pull/5199
	* Changes to Python https://github.com/microsoft/vscode-python/issues/15725
* There could be other improvements we could make, this is a big step forward

**Comment by greazer** [comment] 2021-04-23 23:01
This WSL scenario has been improved. There's likely more we can do here though. Moving to June for further consideration.

**Comment by greazer** [comment] 2021-06-04 08:02
Moving to July as we couldn't get to this for June.

**Comment by chriddyp** [comment] 2021-06-14 20:50
Hi folks! I see this as well. Here are two GIFs for reference.

Loading for the first time - Takes ~45 seconds

![jupyter-loading-2](https://user-images.githubusercontent.com/1280389/121957584-75d88c80-cd17-11eb-8484-60fe624065a1.gif)

Reloading the file the second time (I'm assuming the kernel is already running in background & extension is loaded) - ~10 seconds to open file, another 10 seconds to connect to kernel.

![jupyter-loading-3](https://user-images.githubusercontent.com/1280389/121957600-7bce6d80-cd17-11eb-87a9-3ba0c887bc2a.gif)

**Comment by DonJayamanne** [comment] 2021-06-14 22:04
@chriddyp Please could you try using VS Code Insiders. This issue focuses on the perf related to the use of the new Notebook UI when used in VS Code insiders (note this is the UI we're planning in rolling out in place of the current UI).

**Comment by chriddyp** [comment] 2021-06-15 00:13
Thanks for the pointer @DonJayamanne , and sorry for the noise!

Just downloaded Insiders and the performance is indeed much better. Love the new UI, too!

![insiders-jupyter-loading-1](https://user-images.githubusercontent.com/1280389/121973993-52233f80-cd33-11eb-8785-8cf64ee8bac3.gif)

Timeline on my computer:
@1s - Jupyter Toolbar
@4s - See Jupyter Cells
@6s - Jupyter Cell is Editable
@30s - Finished Connecting to Kernel & Ran Cell

**Comment by DonJayamanne** [comment] 2021-10-18 21:12
Closing this issue as ipynb editor has been moved into VS Code core.
(hence there shouldn't be any more perf issues related to opening ipynb files, at least not ones contributed by the jupyter extension)

**Closed by DonJayamanne** 2021-10-18 21:12 UTC
Labels: bug, notebook-kernel, issue_grooming_don
