### ISSUE TITLE
Arrow key usage for IntelliSense navigates cells

### ISSUE THREAD

**Issue by cobey** [microsoft/vscode-jupyter#10666] opened 2022-07-01 16:29 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Create a new Jupyter Notebook
2. Add > 1 cells
3. In the top cell, begin typing python code to trigger IntelliSense menu
4. Use the arrow key to navigate through the completions list

![Screenflick Movie 8](https://user-images.githubusercontent.com/8754258/176934276-2814c992-0fca-4942-b676-ac7815c99afa.gif)

### Expected Results

Arrows should navigate completion list

### Actual Results

Arrows navigate cells

### VS Code Version

 Version: 1.69.0-insider (Universal) Commit: e7751367f79f327b8103bee33a07c16817a2c7cd

### Jupyter Extension Version

v2022.7.1001841019

### Jupyter logs

```shell
info 9:23:38.830: Started kernel upgraded-telegram-gIjQrpnu (Python 3.10.4)., (Raw session started and connected)
info 9:23:38.831: Finished connecting bfd29cae-fc73-4256-a407-7902b013db59
info 9:23:38.837: Started kernel upgraded-telegram-gIjQrpnu (Python 3.10.4)., (Raw session started and connected)
info 9:23:38.837: Finished connecting bfd29cae-fc73-4256-a407-7902b013db59
info 9:23:38.839: UpdateWorkingDirectoryAndPath in Kernel
info 9:23:38.840: Executing silently Code (idle) = import os\nimport sys\n%cd "/Users/codybeyer/Source/upgraded-telegram"\nif os.getcwd() not in sys.path:
error 9:23:38.842: Live Notebook not available for /Users/codybeyer/Source/upgraded-telegram/Untitled-1.ipynb
info 9:23:38.842: UpdateWorkingDirectoryAndPath in Kernel
info 9:23:38.843: Executing silently Code (idle) = import os\nimport sys\n%cd "/Users/codybeyer/Source/upgraded-telegram"\nif os.getcwd() not in sys.path:
info 9:23:38.867: Executing silently Code (completed) = import os\nimport sys\n%cd "/Users/codybeyer/Source/upgraded-telegram"\nif os.getcwd() not in sys.path: with 1 output(s)
info 9:23:38.868: Waiting for idle on (kernel): 3fa1c15f-6211-42ac-928c-e99c3ad71d9c -> idle
info 9:23:38.868: Finished waiting for idle on (kernel): 3fa1c15f-6211-42ac-928c-e99c3ad71d9c -> idle
info 9:23:38.877: Executing silently Code (completed) = import os\nimport sys\n%cd "/Users/codybeyer/Source/upgraded-telegram"\nif os.getcwd() not in sys.path: with 1 output(s)
info 9:23:38.877: Waiting for idle on (kernel): 815c6e6e-5f45-4f26-950d-73c24e5e1187 -> idle
info 9:23:38.877: Finished waiting for idle on (kernel): 815c6e6e-5f45-4f26-950d-73c24e5e1187 -> idle
info 9:23:38.887: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 9:23:38.888: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 9:23:39.111: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/Users/codybeyer/.vscode-insiders/extensions/ms-toolsai.jupyter-2022.7.1001841019/tmp/scripts/75edf0f6d8a2333a9e4c0da3af4a5b129da9af28cadf79dafa36333ecfa1272f/jupyter
```

### Coding Language and Runtime Version

Python 3.10.4

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment] 2022-07-01 17:49
This is a dupe of https://github.com/microsoft/vscode/issues/152770 which will be fixed in the next release.

**Closed by rchiodo** 2022-07-01 17:49 UTC
Labels: bug, triage-needed
