### ISSUE TITLE
Open or Save Jupyter Notebook fails

### ISSUE THREAD

**Issue by gmkll** [microsoft/vscode-jupyter#7193] opened 2021-08-18 13:58 UTC
## Environment data

-   VS Code version: 1.59
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): v2021.8.1105858891
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda ): venv or not local
-   Jupyter server running: Local | Remote | Local (started or not started) . Could e.g. connect from python file with inline Jupyter #%%

## Expected behaviour

Open Jupyter Notebook, Save Notebook

## Actual behaviour

Opens the not interpolated **source**, that is not recognized as Jupyter Notebook file / Saves the Jupyter Notebook .

## Steps to reproduce:

1. Open existing a.ipynb -> editor shows just the source.

2. Jupyter: Create New or Blank Notebook. Try saving untitled new jupyter file in vscode-> Ctrl-S => Opens File-System wtih "Untitled.txt" (not Untitled.ipynb).
Error from VSCode see below.

## Logs

ad 2. Localized Message ...
`... "Untitled": File name file:///c%3A/xy/wfsffafaf.ipynb is not supported by Jupyter.
Please make sure the file name matches following patterns:
`

**Comment by rchiodo** [comment] 2021-08-18 16:45
I believe this is a dupe of https://github.com/microsoft/vscode/issues/131040

**Closed by rchiodo** 2021-08-18 16:45 UTC
Labels: bug, needs-triage
