### ISSUE TITLE
Cannot export Python Jupyter Notebook due to issue in Python extension

### ISSUE THREAD

**Issue by oaustegard** [microsoft/vscode-jupyter#4410] opened 2021-01-15 18:37 UTC
## Environment data

-   VS Code version: 1.52.1
-   Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS and version: Windows 10
-   Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: ms-toolsai.jupyter v2020.12.414227025
-   Value of the `python.languageServer` setting: Jedi

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

See https://github.com/microsoft/vscode/issues/110934

## Actual behaviour

See https://github.com/microsoft/vscode/issues/110934

## Steps to reproduce:

See https://github.com/microsoft/vscode/issues/110934
Note that this was deemed by @rebornix to be a vscode-python issue

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
None 
```

</p>
</details>

**Comment by claudiaregio** [comment] 2021-01-16 00:23
@oaustegard I am able to reproduce. 

Could you please provide the output for `Jupyter` in the Output panel (`View`→`Output`, change the drop-down the upper-right of the Output panel to Jupyter)

**Comment by oaustegard** [comment] 2021-01-16 00:37
```> C:\Python39\python.exe c:\Users\austegard.oskar\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter nbconvert --version
> C:\Python39\python.exe c:\Users\austegard.oskar\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter nbconvert --version
Error 2021-01-15 19:35:45: Export failed [r [Error]: Traceback (most recent call last):
  File "c:\Users\austegard.oskar\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py", line 26, in <module>
    runpy.run_module(module, run_name="__main__", alter_sys=True)
  File "C:\Python39\lib\runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "C:\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\austegard.oskar\AppData\Roaming\Python\Python39\site-packages\jupyter.py", line 4, in <module>
    main()
  File "C:\Users\austegard.oskar\AppData\Roaming\Python\Python39\site-packages\jupyter_core\command.py", line 285, in main
    command = _jupyter_abspath(subcommand)
  File "C:\Users\austegard.oskar\AppData\Roaming\Python\Python39\site-packages\jupyter_core\command.py", line 124, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-nbconvert` not found.

	at ChildProcess.<anonymous> (c:\Users\austegard.oskar\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:9:101000)
	at Object.onceWrapper (events.js:313:26)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)]
	```

**Comment by greazer** [comment] 2021-01-21 21:16
Likely a dupe of #4347

**Closed by greazer** 2021-01-21 21:16 UTC
Labels: regression
