### ISSUE TITLE
Jupyter plot viewer blocks horizontal scrolling

### ISSUE THREAD

**Issue by mladen5000** [microsoft/vscode-jupyter#14143] opened 2023-08-17 14:57 UTC
Type: <b>Bug</b>

Clicking on a very wide matplotlib or seaborn plot in the interactive plot viewer will allow it to be viewed in detail, however whenever I wish the view the rightmost side of the plot, there is a limit to how far I can drag the plot over. Typically about half-way. This can be reproduced by producing a very wide/horizontal plot and attempting the view the far right side.

Extension version: 2023.8.1002311100
VS Code version: Code - Insiders 1.82.0-insider (Universal) (85dab33f18ea9e16a36609cd203e1f18b1d76e45, 2023-08-16T10:06:03.563Z)
OS version: Darwin arm64 23.0.0
Modes:
Remote OS version: Linux x64 6.2.11-060211-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|77, 68, 75|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 0c3e08e7-ea47-425a-9275-aa898d1457f4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lab|
|OS|Linux x64 6.2.11-060211-generic|
|CPUs|AMD Ryzen Threadripper 3960X 24-Core Processor (48 x 2194)|
|Memory (System)|251.54GB (236.31GB free)|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment] 2023-12-06 04:05
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/9349

**Closed by DonJayamanne** 2023-12-06 04:05 UTC
Labels: bug, plot-viewer
