### ISSUE TITLE
Seeing squiggles in input editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-jupyter#6449] opened 2021-06-30 17:29 UTC
Testing https://github.com/microsoft/vscode/issues/127378

![image](https://user-images.githubusercontent.com/10746682/124005565-86f0f100-d9d9-11eb-8f4f-5bf1b91a7d96.png)

**Comment by rchiodo** [comment] 2021-06-30 17:33
Dupe of https://github.com/microsoft/vscode-jupyter/issues/6432

**Comment by rchiodo** [comment] 2021-06-30 17:33
Sorry not a dupe. This is in the interactive window.

**Comment by rebornix** [comment] 2021-07-15 15:48
This should be fixed now in Python extension.

**Closed by rebornix** 2021-07-15 15:48 UTC
Labels: bug, debt, interactive-window
