### ISSUE TITLE
Jupyter Python parser showing errors where there are not

### ISSUE THREAD

**Issue by lucasczpnk** [microsoft/vscode-jupyter#4452] opened 2021-01-22 15:07 UTC
## Environment data

-   VS Code - Insiders version:
	  ```
	  1.53.0-insider
	  Commit: 1a4b35c2023a41efae1af2661026d57cea90ef5c
	  Date: 2021-01-21T05:12:00.322Z
	  Electron: 11.2.0
	  Chrome: 87.0.4280.141
	  Node.js: 12.18.3
	  V8: 8.7.220.31-electron.0
	  OS: Darwin x64 20.2.0
	  ```
-   Jupyter Extension version: v2020.12.414227025
-   Python Extension version: v2021.2.497453231
-   OS and version: macOS Big Sur 11.1 (20C69)
-   Python and/or Anaconda version: Python 3.9
-   Type of virtual environment used: virtualenv
-   Jupyter server running: Local

## Expected behaviour

No parsing errors

## Actual behaviour

Sometimes while writing new code or refactoring already saved/executed code the parser starts showing errors in practically all code, even though there's nothing wrong with the syntax or object assignments.

Note that the exact same code on the python file (right pane) has no parsing error and the cell is running the code without any issues whatsoever:
![vscodeissue](https://user-images.githubusercontent.com/20496753/105505730-11edf280-5ca8-11eb-905f-b51a950403f7.png)
There are a few blank spaces in the image, where I had to crop out some sensitive data and code.

## Steps to reproduce:

After reproducing the env config, it may happen after running a few code cells and editing/creating new code lines or cells.
Apparently it "solves itself" after restarting the kernel, but since I'm running it locally I have to redo all the work if I want to correct it and there's no guarantee that it won't happen again after going to all the trouble.

## Logs

<details>
<p>
```
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'NativeNotebookEditor'
Error 2021-01-22 09:39:55: Jupyter Kernel Spec not found for a local connection
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Warn 2021-01-22 09:40:07: Python Daemon (pid: 1172): Waiting for Kernel to die 1177
Error 2021-01-22 09:48:06: Jupyter Kernel Spec not found for a local connection
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
Started kernel Python 3.9.1 64-bit ('venv')
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Warn 2021-01-22 09:48:08: Python Daemon (pid: 3383): Waiting for Kernel to die 3384
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Warn 2021-01-22 09:48:09: Python Daemon (pid: 3385): Waiting for Kernel to die 3386
Error 2021-01-22 09:49:19: Jupyter Kernel Spec not found for a local connection
Error 2021-01-22 09:51:00: Jupyter Kernel Spec not found for a local connection
Started kernel Python 3.9.1 64-bit ('venv')
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Warn 2021-01-22 09:51:01: Python Daemon (pid: 3911): Waiting for Kernel to die 3912
> ~/Documents/tech/repos/lczepa/venv/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Warn 2021-01-22 09:51:02: Python Daemon (pid: 3915): Waiting for Kernel to die 3916
```
</p>
</details>

**Comment by rchiodo** [comment] 2021-01-23 00:37
I believe this is a dupe of #4300

**Closed by rchiodo** 2021-01-23 00:37 UTC
Labels: bug
