### ISSUE TITLE
jupyter.jupyterCommandLineArguments must be set to home directory on Apple Silicon M1 laptop

### ISSUE THREAD

**Issue by davidmytton** [microsoft/vscode-jupyter#5771] opened 2021-05-05 17:48 UTC
## Environment data

-   VS Code version: Version: 1.55.2 Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS and version: macOS 11.3.1 Darwin arm64 20.4.0
-   Python and/or Anaconda version: 3.8.2
-   Type of virtual environment used: venv
-   Jupyter server running: Local

## Expected behaviour

When running a code block, the notebook should pick up the selected Python 3 version.

## Actual behaviour

VS Code displays an error saying ipykernel is not installed in Python 2, even though Python 3 is selected as the interpreter.

## Steps to reproduce:

1. Fresh install of VS Code.
2. Install Python and Jupiter extensions, select the Python 3 interpreter and have it install all the dependencies.
3. Open the sample notebook and attempt to run any code block.

Workaround is as described in https://github.com/microsoft/vscode-jupyter/issues/4075#issuecomment-764901241 - set the home directory setting.

**Comment by rchiodo** [comment] 2021-05-05 18:03
Thanks for the bug. This sounds like a dupe of #https://github.com/microsoft/vscode-jupyter/issues/5648.

I believe this should be fixed in our next release (coming out in the next few days)

**Comment by greazer** [comment] 2021-05-06 20:28
@davidmytton, closing for now. Please reopen if it hasn't been fixed.

**Closed by greazer** 2021-05-06 20:28 UTC
Labels: bug
