### ISSUE TITLE
Data Viewer doesn't visualise child Dataframes

### ISSUE THREAD

**Issue by akashtyagi08** [microsoft/vscode-jupyter#7915] opened 2021-10-12 18:30 UTC
## Environment data

- debugpy version: 1.5.0
- OS and version: MAC - Big Sur
- Python version (& distribution if applicable, e.g. Anaconda): 3.6.8
- Using VS Code or Visual Studio: Visual Studio

## Actual behavior
Child Dataframe are visible as `Objects` and not accessible 

<img width="840" alt="Screenshot 2021-10-12 at 11 57 29 PM" src="https://user-images.githubusercontent.com/84968253/137009558-1589549d-8916-4f96-bf61-86c1513ee81b.png">

## Steps to reproduce:
```
import requests
import pandas as pd

url ='http://openinsider.com/screener?s=&o=&pl=&ph=&ll=&lh=&fd=3&fdr=&td=0&tdr=&fdlyl=&fdlyh=&daysago=&xp=1&excludeDerivRelated=1&vl=100&vh=&ocl=&och=&sic1=-1&sicl=100&sich=9999&grp=0&nfl=&nfh=&nil=&nih=&nol=&noh=&v2l=&v2h=&oc2l=&oc2h=&sortcol=0&cnt=1000&page=1'
html = requests.get(url).content
df_list = pd.read_html(html)
```

**Comment by DonJayamanne** [comment] 2022-12-08 00:36
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1138

**Closed** 2022-12-08 00:45 UTC
Labels: data-viewer, variable-explorer, feature-request
