### ISSUE TITLE
`jupyter.hascodecells` should also support other languages.

### ISSUE THREAD

**Issue by uduse** [microsoft/vscode-jupyter#14018] opened 2023-08-01 00:44 UTC
I have [evcxr](https://github.com/evcxr/evcxr) installed and I can run Rust REPL in an interactive Jupyter panel inside of vscode.

## Expected behaviour
By defining `jupyter.interactiveWindow.cellMarker.codeRegex` correctly, I expect jupyter also captures code blocks in Rust files (*.rs) and can use the same keys to send blocks of code to the interactive window.

## Actual behaviour
It doesn't work. Nothing shows up in the interactive window when I press the right shortcut key.

## Diagnosis
The `jupyter.hascodecells` context isn't triggered properly. I think this is because the extension only works in a Python language mode. Reasons: (1) if I rename the file to "*.py" extension doesn't work. (2) changing langauge mode works.

## Solution
Support arbitrary language modes through some extension config.

**Comment by DonJayamanne** [comment] 2023-08-01 03:09
I believe the root cause is https://github.com/microsoft/vscode-jupyter/issues/273

**Comment by amunger** [comment] 2023-08-01 15:48
closing as duplicate

**Closed by amunger** 2023-08-01 15:48 UTC
Labels: bug, interactive-window
