### ISSUE TITLE
Python processes are not terminated after restarting the jupyter kernel or closing the interactive window. 

### ISSUE THREAD

**Issue by qizhou000** [microsoft/vscode-jupyter#11185] opened 2022-08-25 00:12 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

**Steps**

1. Open a python file with VSCode and supervise the task manager, as shown below:
![image](https://user-images.githubusercontent.com/37895152/186548039-4e2227f4-8e4a-4147-8651-709243dcde1b.png)

2. Press `Ctrl + Enter` to run the code. Two python processes and console host are created, as shown below:
![image](https://user-images.githubusercontent.com/37895152/186548128-92e45cf6-8021-45ac-8459-9720621193c9.png)

3. After restarting the Jupyter kernel, extra python and console host processes are created but the previous processes are not  killed. As shown below:
![image](https://user-images.githubusercontent.com/37895152/186548200-7a23f54d-af49-4965-ae7c-becd3b8ea034.png)

4. The idle python processes with around 8MB memory and the corresponding console hosts persist even if I close the interactive window:
![image](https://user-images.githubusercontent.com/37895152/186548439-e142aad6-7a46-4149-b012-b2c6ba7b0c36.png)

**Expect**
I think there should be only one python process corresponding to one interactive window, and after closing the interactive window the python process should be terminated. 

### VS Code Version

版本: 1.70.2 (system setup) 提交: e4503b30fc78200f846c62cf8091b76ff5547662 日期: 2022-08-16T05:35:13.448Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

Jupyter v2022.7.1102252217

### Coding Language and Runtime Version

Python 3.10.6

### Language Extension Version (if applicable)

Python v2022.12.1

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2022-08-25 01:24
I'm unable to replicate this at my end, its possible this has been fixed as part of the issue https://github.com/microsoft/vscode-jupyter/issues/9909
Please could you try installing the latest Pre-Release version of the Jupyter extension, then try again.

If the problem persist, then please could you upload the logs from the `Jupyter` output panel, you can get there output using the command `Jupyter: Show Output`. Please remember to copy and upload all of the output.

**Comment by qizhou000** [comment] 2022-08-25 02:07
> I'm unable to replicate this at my end, its possible this has been fixed as part of the issue #9909 Please could you try installing the latest Pre-Release version of the Jupyter extension, then try again.
> 
> If the problem persist, then please could you upload the logs from the `Jupyter` output panel, you can get there output using the command `Jupyter: Show Output`. Please remember to copy and upload all of the output.

Thank you! The problem is indeed solved after installing the latest Pre-Release version of the Jupyter extension.

**Comment by DonJayamanne** [comment] 2022-08-25 02:41
let's close this as resolved
thanks for the confirmation of the fix
duplicate of #9909

**Closed by DonJayamanne** 2022-08-25 02:41 UTC
Labels: bug, info-needed, notebook-kernel, perf
