### ISSUE TITLE
Copy from code output not working as before

### ISSUE THREAD

**Issue by matrix303** [microsoft/vscode-jupyter#5401] opened 2021-04-04 06:18 UTC
## Environment data

-   VS Code version: 1.56.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.702919634
-   Python Extension version (available under the Extensions sidebar): v2021.4.690665134-dev
-   OS (Windows | Mac | Linux distro) and version: MacOS 11.2.3
-   Python and/or Anaconda version: 3.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

Previously, up until last week, I was able to get a data frame output as below and simply copy and paste it. Not only would it previously copy the values but also the columns and row structure.

<img width="1299" alt="Screen Shot 2021-04-04 at 2 18 32 AM" src="https://user-images.githubusercontent.com/10987493/113500453-0f9be600-94ec-11eb-853f-7dd96c9b3a10.png">

## Actual behaviour

Now, after highlighting and copying as before, nothing is copied. No values/columns/row structure

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Attached is a sample test file → can not copy anything from the table that is outputted in cell 2

[test.ipynb.zip](https://github.com/microsoft/vscode-jupyter/files/6254047/test.ipynb.zip)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment] 2021-04-05 18:08
Thanks for the issue. Dupe of #5384

**Closed by rchiodo** 2021-04-05 18:08 UTC
Labels: bug
