### ISSUE TITLE
Notebook startup takes about 10 seconds

### ISSUE THREAD

**Issue by zazemlenie** [microsoft/vscode-jupyter#12744] opened 2023-02-06 08:59 UTC
## Environment data

-   VS Code version: 1.75.0
-   Jupyter Extension version: v2023.2.1000360234
-   Python Extension version: v2023.2.0
-   OS and version: MaCos Monterey 12.6 (mac air m1 2020)
-   Python version: 3.9.13
-   Type of virtual environment used: virtualenv created by pyenv
-   Jupyter server running: Local

## Expected behaviour

I expect the notebook to start in less than a second like it did before the update

## Actual behaviour

After the last update it takes around 10 seconds to start/restart the kernel

## Steps to reproduce:

1. Open a jupyter notebook and run an empty cell. The notebook will take ~10 seconds to start up
2. Reload the notebook. It will take the same amount of time

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel
</summary>

<p>

```
debug 10:57:39.229: VSCodeNotebookController::handleExecution, Class name = Cv (started execution)
debug 10:57:39.229: Execute Cell 0 /Users/qwerty/Documents/python/ex/blank_notebook.ipynb
debug 10:57:39.229: start the kernel, options.disableUI=false for /Users/qwerty/Documents/python/ex/blank_notebook.ipynb
debug 10:57:39.229: Start Jupyter Session in kernel.ts with disableUI = false
info 10:57:39.230: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python.-m#ipykernel_launcher (Python Path: /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env, EnvType: Pyenv, EnvName: 'blank_env', Version: 3.9.13 (main, Sep 25 2022, 16:24:30) 
[Clang 13.1.6 (clang-1316.0.21.2.5)]) for '/Users/qwerty/Documents/python/ex/blank_notebook.ipynb' (disableUI=false)
debug 10:57:39.230: createNewKernelSession .jvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python.-m#ipykernel_launcher
[I 10:57:39.234 NotebookApp] Creating new notebook in 
debug 10:57:39.243: Check if a kernel is usable
info 10:57:39.243: installMissingDependencies /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python, ui.disabled=false for resource '/Users/qwerty/Documents/python/ex/blank_notebook.ipynb'
debug 10:57:39.244: Create activated Env, Class name = tc (started execution), Arg 1: {"interpreter":{"id":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","sysPrefix":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","envPath":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","scheme":"file"},"displayPath":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","scheme":"file"},"envName":"blank_env","uri":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","external":"file:///Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","scheme":"file"},"displayName":"blank_env","envType":"Pyenv","version":{"major":3,"minor":9,"patch":13,"raw":"3.9.13 (main, Sep 25 2022, 16:24:30) \n[Clang 13.1.6 (clang-1316.0.21.2.5)]"}},"allowEnvironmentFetchExceptions":true}
debug 10:57:39.244: Getting activated env variables, Class name = ps (started execution), Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>, Arg 3: true
debug 10:57:39.244: Getting activated env variables impl, Class name = ps (started execution), Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:57:39.244: Getting activated env variables from Python, Class name = ps (started execution), Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:57:39.244: Get Custom Env Variables, Class name = bc (started execution), Arg 1: "~/Documents/python/ex", Arg 2: "RunPythonCode"
debug 10:57:39.244: Cached data exists getEnvironmentVariables, /Users/qwerty/Documents/python/ex
debug 10:57:39.244: Cached custom vars data exists getCustomEnvironmentVariables, /Users/qwerty/Documents/python/ex
debug 10:57:39.244: Get Custom Env Variables, Class name = bc, completed in 0ms, has a truthy return value, Arg 1: "~/Documents/python/ex", Arg 2: "RunPythonCode"
debug 10:57:39.284: Got env vars with python /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python, with env var count 37 and custom env var count 0 in 40ms
debug 10:57:39.284: Getting activated env variables from Python, Class name = ps, completed in 40ms, has a truthy return value, Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:57:39.284: Got env vars with python /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python in 40ms with 37 variables
debug 10:57:39.284: Getting activated env variables impl, Class name = ps, completed in 40ms, has a truthy return value, Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:57:39.284: Getting activated env variables, Class name = ps, completed in 40ms, has a truthy return value, Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>, Arg 3: true
debug 10:57:39.285: Create activated Env, Class name = tc, completed in 40ms, has a truthy return value, Arg 1: {"resource":{"$mid":1,"fsPath":"/Users/qwerty/Documents/python/ex","external":"file:///Users/qwerty/Documents/python/ex","path":"/Users/qwerty/Documents/python/ex","scheme":"file"},"interpreter":{"id":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","sysPrefix":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","envPath":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","scheme":"file"},"displayPath":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","scheme":"file"},"envName":"blank_env","uri":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","external":"file:///Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","scheme":"file"},"displayName":"blank_env","envType":"Pyenv","version":{"major":3,"minor":9,"patch":13,"raw":"3.9.13 (main, Sep 25 2022, 16:24:30) \n[Clang 13.1.6 (clang-1316.0.21.2.5)]"}},"allowEnvironmentFetchExceptions":true}
info 10:57:39.285: Process Execution: > ~/.pyenv/versions/3.9.13/envs/blank_env/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/.pyenv/versions/3.9.13/envs/blank_env/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
debug 10:57:39.375: Checking if product is installed, Class name = qd, completed in 131ms, has a truthy return value, Arg 1: 19, Arg 2: undefined, Return Value: true
debug 10:57:39.375: Are Dependencies Installed, Class name = Su, completed in 132ms, has a truthy return value, Arg 1: "~/.pyenv/versions/3.9.13/envs/blank_env/python./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python.-m#ipykernel_launcher", Arg 2: {"a":false,"b":{"j":false,"q":{"a":{"element":{"subscription":{}},"next":{},"prev":{}},"b":{"element":{"subscription":{}},"next":{},"prev":{}},"c":1}}}, Arg 3: true, Return Value: true
debug 10:57:39.375: Install Missing Dependencies, Class name = Su, completed in 132ms, has a falsy return value, Arg 1: <argument cannot be serialized for logging>, Return Value: 0
info 10:57:39.376: Spec argv[0] updated from '/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python' to '/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python'
debug 10:57:39.376: Cached custom vars data exists getCustomEnvironmentVariables, /Users/qwerty/Documents/python/ex/blank_notebook.ipynb
debug 10:57:39.376: Getting activated env variables, Class name = ps (started execution), Arg 1: "~/Documents/python/ex/blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>, Arg 3: false
debug 10:57:39.376: Getting activated env variables impl, Class name = ps (started execution), Arg 1: "~/Documents/python/ex/blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:57:39.376: Getting activated env variables from Python, Class name = ps (started execution), Arg 1: "~/Documents/python/ex/blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:57:39.376: Get Custom Env Variables, Class name = bc (started execution), Arg 1: "~/Documents/python/ex/blank_notebook.ipynb", Arg 2: "RunPythonCode"
debug 10:57:39.376: Cached data exists getEnvironmentVariables, /Users/qwerty/Documents/python/ex/blank_notebook.ipynb
debug 10:57:39.376: Cached custom vars data exists getCustomEnvironmentVariables, /Users/qwerty/Documents/python/ex/blank_notebook.ipynb
debug 10:57:39.376: Get Custom Env Variables, Class name = bc, completed in 0ms, has a truthy return value, Arg 1: "~/Documents/python/ex/blank_notebook.ipynb", Arg 2: "RunPythonCode"
debug 10:57:39.376: Got env vars with python /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python, with env var count 37 and custom env var count 0 in 0ms
debug 10:57:39.376: Getting activated env variables from Python, Class name = ps, completed in 0ms, has a truthy return value, Arg 1: "~/Documents/python/ex/blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:57:39.376: Got env vars with python /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python in 0ms with 37 variables
debug 10:57:39.377: Getting activated env variables impl, Class name = ps, completed in 1ms, has a truthy return value, Arg 1: "~/Documents/python/ex/blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:57:39.377: Getting activated env variables, Class name = ps, completed in 1ms, has a truthy return value, Arg 1: "~/Documents/python/ex/blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>, Arg 3: false
debug 10:57:39.377: Updated kernel spec with environment variables for /Users/qwerty/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000360234/temp/jupyter/kernels/pythonjvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c/kernel.json
[I 10:57:39.397 NotebookApp] Kernel started: a6c088d8-c47f-46b1-9cf1-74debf90e364, name: pythonjvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c
debug 10:57:39.401: Waiting for 60000ms idle on (kernel): a6c088d8-c47f-46b1-9cf1-74debf90e364 -> unknown
[W 10:57:39.404 NotebookApp] delete /blank_notebook-jvsc-a357500b-000a-4082-bfe6-4a90efb9a7c6cee394ae-a8a5-43c7-a875-bc7ae8336738.ipynb
debug 10:57:49.920: Got status busy in waitForIdleOnSession
debug 10:57:49.921: Got status idle in waitForIdleOnSession
debug 10:57:49.921: Finished waiting for idle on (kernel): a6c088d8-c47f-46b1-9cf1-74debf90e364 -> idle
info 10:57:49.921: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python.-m#ipykernel_launcher
debug 10:57:49.922: Started running kernel initialization for /Users/qwerty/Documents/python/ex/blank_notebook.ipynb
debug 10:57:49.923: Executing silently Code (idle) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "//Users/qwerty/Documents/python/ex"\nif _VSCOD
debug 10:57:49.948: Executing silently Code (completed) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "//Users/qwerty/Documents/python/ex"\nif _VSCOD with 1 output(s)
debug 10:57:49.948: Not executing startup session: Object, code: 
debug 10:57:49.948: Requesting Kernel info
debug 10:57:49.948: Got Kernel info
debug 10:57:49.948: End running kernel initialization, now waiting for idle
debug 10:57:49.948: Waiting for 60000ms idle on (kernel): a6c088d8-c47f-46b1-9cf1-74debf90e364 -> idle
debug 10:57:49.949: Finished waiting for idle on (kernel): a6c088d8-c47f-46b1-9cf1-74debf90e364 -> idle
debug 10:57:49.949: End running kernel initialization, session is idle
debug 10:57:49.949: IPyWidgetMessageDispatcher.initialize
debug 10:57:49.950: IPyWidgetScriptSource.initialize
debug 10:57:49.953: Start Jupyter Session in kernel.ts with disableUI = false
debug 10:57:49.954: Start cell 0 execution @ 1675673869953
debug 10:57:49.955: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
debug 10:57:49.962: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
debug 10:57:49.968: IPyWidgetMessageDispatcher.initialize
debug 10:57:49.969: IPyWidgetMessageDispatcher.initialize
debug 10:57:49.969: End cell 0 execution @ undefined, started @ 1675673869953, elapsed time = -1675673869.953s
debug 10:57:49.969: Cell 0 executed with state Idle
debug 10:57:49.969: VSCodeNotebookController::handleExecution, Class name = Cv, completed in 10740ms, has a falsy return value
debug 10:57:49.969: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/Users/qwerty/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000360234/tmp/scripts/d660daf0b3fc671f9642a6143ac8869bda5e028f9dbe51db67d9aa4a71e85c35/jupyter
```
</p>
</details>

<details>
<summary>Here is an output for another notebook
</summary>

<p>

```
debug 10:53:56.135: VSCodeNotebookController::handleExecution, Class name = Cv (started execution)
debug 10:53:56.140: Execute Cell 0 /Users/qwerty/Documents/python/ex/another_blank_notebook.ipynb
debug 10:53:56.140: start the kernel, options.disableUI=false for /Users/qwerty/Documents/python/ex/another_blank_notebook.ipynb
debug 10:53:56.140: Start Jupyter Session in kernel.ts with disableUI = false
info 10:53:56.140: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python.-m#ipykernel_launcher (Python Path: /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env, EnvType: Pyenv, EnvName: 'blank_env', Version: 3.9.13 (main, Sep 25 2022, 16:24:30) 
[Clang 13.1.6 (clang-1316.0.21.2.5)]) for '/Users/qwerty/Documents/python/ex/another_blank_notebook.ipynb' (disableUI=false)
debug 10:53:56.141: createNewKernelSession .jvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python.-m#ipykernel_launcher
[I 10:53:56.145 NotebookApp] Creating new notebook in 
debug 10:53:56.153: Check if a kernel is usable
info 10:53:56.153: installMissingDependencies /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python, ui.disabled=false for resource '/Users/qwerty/Documents/python/ex/another_blank_notebook.ipynb'
debug 10:53:56.154: Create activated Env, Class name = tc (started execution), Arg 1: {"interpreter":{"id":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","sysPrefix":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","envPath":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","scheme":"file"},"displayPath":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","scheme":"file"},"envName":"blank_env","uri":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","external":"file:///Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","scheme":"file"},"displayName":"blank_env","envType":"Pyenv","version":{"major":3,"minor":9,"patch":13,"raw":"3.9.13 (main, Sep 25 2022, 16:24:30) \n[Clang 13.1.6 (clang-1316.0.21.2.5)]"}},"allowEnvironmentFetchExceptions":true}
debug 10:53:56.154: Getting activated env variables, Class name = ps (started execution), Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>, Arg 3: true
debug 10:53:56.154: Getting activated env variables impl, Class name = ps (started execution), Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:53:56.154: Getting activated env variables from Python, Class name = ps (started execution), Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:53:56.154: Get Custom Env Variables, Class name = bc (started execution), Arg 1: "~/Documents/python/ex", Arg 2: "RunPythonCode"
debug 10:53:56.154: Cached data exists getEnvironmentVariables, /Users/qwerty/Documents/python/ex
debug 10:53:56.154: Cached custom vars data exists getCustomEnvironmentVariables, /Users/qwerty/Documents/python/ex
debug 10:53:56.154: Get Custom Env Variables, Class name = bc, completed in 0ms, has a truthy return value, Arg 1: "~/Documents/python/ex", Arg 2: "RunPythonCode"
debug 10:53:56.154: Got env vars with python /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python, with env var count 37 and custom env var count 0 in 0ms
debug 10:53:56.154: Getting activated env variables from Python, Class name = ps, completed in 0ms, has a truthy return value, Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:53:56.154: Got env vars with python /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python in 0ms with 37 variables
debug 10:53:56.155: Getting activated env variables impl, Class name = ps, completed in 1ms, has a truthy return value, Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:53:56.155: Getting activated env variables, Class name = ps, completed in 1ms, has a truthy return value, Arg 1: "~/Documents/python/ex", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>, Arg 3: true
debug 10:53:56.155: Create activated Env, Class name = tc, completed in 1ms, has a truthy return value, Arg 1: {"resource":{"$mid":1,"fsPath":"/Users/qwerty/Documents/python/ex","external":"file:///Users/qwerty/Documents/python/ex","path":"/Users/qwerty/Documents/python/ex","scheme":"file"},"interpreter":{"id":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","sysPrefix":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","envPath":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","scheme":"file"},"displayPath":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env","scheme":"file"},"envName":"blank_env","uri":{"$mid":1,"fsPath":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","external":"file:///Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","path":"/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python","scheme":"file"},"displayName":"blank_env","envType":"Pyenv","version":{"major":3,"minor":9,"patch":13,"raw":"3.9.13 (main, Sep 25 2022, 16:24:30) \n[Clang 13.1.6 (clang-1316.0.21.2.5)]"}},"allowEnvironmentFetchExceptions":true}
info 10:53:56.156: Process Execution: > ~/.pyenv/versions/3.9.13/envs/blank_env/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/.pyenv/versions/3.9.13/envs/blank_env/bin/python -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
debug 10:53:56.262: Checking if product is installed, Class name = qd, completed in 108ms, has a truthy return value, Arg 1: 19, Arg 2: undefined, Return Value: true
debug 10:53:56.262: Are Dependencies Installed, Class name = Su, completed in 108ms, has a truthy return value, Arg 1: "~/.pyenv/versions/3.9.13/envs/blank_env/python./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python.-m#ipykernel_launcher", Arg 2: {"a":false,"b":{"j":false,"q":{"a":{"element":{"subscription":{}},"next":{},"prev":{}},"b":{"element":{"subscription":{}},"next":{},"prev":{}},"c":1}}}, Arg 3: true, Return Value: true
debug 10:53:56.262: Install Missing Dependencies, Class name = Su, completed in 109ms, has a falsy return value, Arg 1: <argument cannot be serialized for logging>, Return Value: 0
info 10:53:56.263: Spec argv[0] updated from '/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python' to '/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python'
debug 10:53:56.263: Cached custom vars data exists getCustomEnvironmentVariables, /Users/qwerty/Documents/python/ex/another_blank_notebook.ipynb
debug 10:53:56.263: Getting activated env variables, Class name = ps (started execution), Arg 1: "~/Documents/python/ex/another_blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>, Arg 3: false
debug 10:53:56.263: Getting activated env variables impl, Class name = ps (started execution), Arg 1: "~/Documents/python/ex/another_blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:53:56.263: Getting activated env variables from Python, Class name = ps (started execution), Arg 1: "~/Documents/python/ex/another_blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:53:56.263: Get Custom Env Variables, Class name = bc (started execution), Arg 1: "~/Documents/python/ex/another_blank_notebook.ipynb", Arg 2: "RunPythonCode"
debug 10:53:56.263: Cached data exists getEnvironmentVariables, /Users/qwerty/Documents/python/ex/another_blank_notebook.ipynb
debug 10:53:56.263: Cached custom vars data exists getCustomEnvironmentVariables, /Users/qwerty/Documents/python/ex/another_blank_notebook.ipynb
debug 10:53:56.264: Get Custom Env Variables, Class name = bc, completed in 1ms, has a truthy return value, Arg 1: "~/Documents/python/ex/another_blank_notebook.ipynb", Arg 2: "RunPythonCode"
debug 10:53:56.264: Got env vars with python /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python, with env var count 37 and custom env var count 0 in 1ms
debug 10:53:56.264: Getting activated env variables from Python, Class name = ps, completed in 1ms, has a truthy return value, Arg 1: "~/Documents/python/ex/another_blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:53:56.264: Got env vars with python /Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python in 1ms with 37 variables
debug 10:53:56.264: Getting activated env variables impl, Class name = ps, completed in 1ms, has a truthy return value, Arg 1: "~/Documents/python/ex/another_blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>
debug 10:53:56.264: Getting activated env variables, Class name = ps, completed in 1ms, has a truthy return value, Arg 1: "~/Documents/python/ex/another_blank_notebook.ipynb", Arg 2: <Uri:/Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/bin/python>, Arg 3: false
debug 10:53:56.265: Updated kernel spec with environment variables for /Users/qwerty/.vscode/extensions/ms-toolsai.jupyter-2023.2.1000360234/temp/jupyter/kernels/pythonjvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c/kernel.json
[I 10:53:56.284 NotebookApp] Kernel started: 97142aa2-d6c6-46dd-bb80-078b2727bddd, name: pythonjvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c
debug 10:53:56.288: Waiting for 60000ms idle on (kernel): 97142aa2-d6c6-46dd-bb80-078b2727bddd -> unknown
[W 10:53:56.291 NotebookApp] delete /another_blank_notebook-jvsc-19f53c9e-d3b0-4b0c-b3db-9d37f4ce88713872d3c0-5d77-486c-b5be-73144e9e78f4.ipynb
debug 10:54:06.805: Got status busy in waitForIdleOnSession
debug 10:54:06.806: Got status idle in waitForIdleOnSession
debug 10:54:06.806: Finished waiting for idle on (kernel): 97142aa2-d6c6-46dd-bb80-078b2727bddd -> idle
info 10:54:06.806: Started session for kernel startUsingPythonInterpreter:.jvsc74a57bd0e6a25cac9cac5dee078a4c8ad38f13636dedd442c5bcba4c9921f79fe05d7e6c./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python./Users/qwerty/.pyenv/versions/3.9.13/envs/blank_env/python.-m#ipykernel_launcher
debug 10:54:06.806: Started running kernel initialization for /Users/qwerty/Documents/python/ex/another_blank_notebook.ipynb
debug 10:54:06.808: Executing silently Code (idle) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "//Users/qwerty/Documents/python/ex"\nif _VSCOD
[E 10:54:06.810 NotebookApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/Users/qwerty/.pyenv/versions/entity_matching/lib/python3.9/site-packages/tornado/iostream.py", line 702, in _handle_events
        self._handle_write()
      File "/Users/qwerty/.pyenv/versions/entity_matching/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/qwerty/.pyenv/versions/entity_matching/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/Users/qwerty/.pyenv/versions/3.9.13/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/qwerty/.pyenv/versions/entity_matching/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/Users/qwerty/.pyenv/versions/entity_matching/lib/python3.9/site-packages/tornado/iostream.py", line 702, in _handle_events
    self._handle_write()
  File "/Users/qwerty/.pyenv/versions/entity_matching/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/Users/qwerty/.pyenv/versions/entity_matching/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
[W 10:54:06.813 NotebookApp] zmq message arrived on closed channel
[I 10:54:06.815 NotebookApp] Starting buffering for 97142aa2-d6c6-46dd-bb80-078b2727bddd:f1fc27fa-b10c-4438-b76a-6dd9ad1d0d37
[I 10:54:06.818 NotebookApp] Restoring connection for 97142aa2-d6c6-46dd-bb80-078b2727bddd:f1fc27fa-b10c-4438-b76a-6dd9ad1d0d37
[I 10:54:07.323 NotebookApp] Replaying 1 buffered messages
debug 10:54:07.332: Executing silently Code (completed) = import os as _VSCODE_os\nimport sys as _VSCODE_sys\n%cd "//Users/qwerty/Documents/python/ex"\nif _VSCOD with 1 output(s)
debug 10:54:07.332: Not executing startup session: Object, code: 
debug 10:54:07.332: Requesting Kernel info
debug 10:54:07.336: Got Kernel info
debug 10:54:07.336: End running kernel initialization, now waiting for idle
debug 10:54:07.337: Waiting for 60000ms idle on (kernel): 97142aa2-d6c6-46dd-bb80-078b2727bddd -> idle
debug 10:54:07.337: Finished waiting for idle on (kernel): 97142aa2-d6c6-46dd-bb80-078b2727bddd -> idle
debug 10:54:07.337: End running kernel initialization, session is idle
debug 10:54:07.342: Start Jupyter Session in kernel.ts with disableUI = false
debug 10:54:07.345: Start cell 0 execution @ 1675673647345
debug 10:54:07.364: End cell 0 execution @ undefined, started @ 1675673647345, elapsed time = -1675673647.345s
debug 10:54:07.364: Cell 0 executed with state Idle
debug 10:54:07.364: VSCodeNotebookController::handleExecution, Class name = Cv, completed in 11229ms, has a falsy return value
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2023-02-06 12:11
@zazemlenie Please could you provide all of the logs. thanks

**Comment by zazemlenie** [comment] 2023-02-06 12:19
@DonJayamanne sure. But what do you mean by all of the logs? Changing Jupyter > Logging: Level to "everything" from "verbose" and generating logs again?

**Comment by bibidybop** [comment] 2023-02-07 16:46
> @zazemlenie Please could you provide all of the logs. thanks
Could it be that @DonJayamanne might have missed the foldable code blocks in @zazemlenie's message? I have similar problem here, with similar log messages

**Comment by DonJayamanne** [comment] 2023-02-07 19:26
> But what do you mean by all of the logs?


When opening the output panel, please copy everything, you have only copied and pasted part of the logs (the start of the logs is missing as that contains crucial information). 

YOu shoudl be able to scroll up, optionally use the keyboard shortcut to select everything and copy it.

> Changing Jupyter > Logging: Level to "everything" from "verbose" and generating logs again?

No need, just ensure you select all, insteadc of just pasting a portion of the logs that you can see (you need to scroll up)

**Comment by DonJayamanne** [comment] 2023-02-09 21:49
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12802
See work around in that issue.

**Closed by DonJayamanne** 2023-02-09 21:49 UTC
Labels: bug, info-needed, perf, notebook-kernel-startup
