### ISSUE TITLE
The cell run infinitely 

### ISSUE THREAD

**Issue by myalos** [microsoft/vscode-jupyter#14624] opened 2023-10-31 08:53 UTC
https://github.com/microsoft/vscode/issues/197042 
this link contains more information about the vscode environment 
Just today, I run the cell as before, but it run infinitely. The bottom left corner showed pending icon, and the restart button is disable. After reloading window and running some cells, the same bug occured again. And I reloaded window, the bug occured again after running a few cells.
I am very upset, and hope that i could find the reason and get some help here, thanks in advance!

**Comment by GergelyTuri** [comment] 2023-10-31 16:53
same here. yesterday it worked just fine, today it randomly start to run infinitely even during a simple plotting task. Interrupt button doesn't work. need to restart vscode then it works for a bit then same thing happen.  

vsocde:
```
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19044
```

Jupyter extension:
```
Published
2020-11-11, 14:14:18
Last released
2023-10-26, 05:25:35
Last updated
2023-10-31, 11:48:46
Identifier
ms-toolsai.jupyter
```

**Comment by DonJayamanne** [comment] 2023-10-31 20:45
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/13349

**Closed by DonJayamanne** 2023-10-31 20:45 UTC
Labels: bug

**Comment by myalos** [comment] 2023-11-01 00:17
I am not alone, thanks (heart icon)
