### ISSUE TITLE
ipywidgets dropdown sometimes closes immediately

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10612] opened 2022-06-28 16:32 UTC
Testing #10598

When a dropdown is first created, opening the dropdown will sometimes close immediately. Happens 2 out of 4 times in the gif below

![dropdown](https://user-images.githubusercontent.com/2019016/176232426-67bb0302-26a9-4fb9-b898-ae1a29d0d491.gif)

**Comment by DonJayamanne** [comment] 2022-06-28 16:43
Closing as a duplicate of an upstream issue https://github.com/microsoft/vscode/issues/151981

**Closed by DonJayamanne** 2022-06-28 16:43 UTC
Labels: triage-needed
