### ISSUE TITLE
code intellisense not working when use remote jupyter server

### ISSUE THREAD

**Issue by Lbsl** [microsoft/vscode-jupyter#8370] opened 2021-11-26 03:26 UTC
Issue Type: <b>Bug</b>

1. start a standalone jupyterlab server manually, I use following command "jupyter-lab --port=8899 --NotebookApp.token= --notebook-dir=**/jupyter_notebooks --NotebookApp.disable_check_xsrf=True"
2. in vscode change the jupyter server from local to the standalone jupyterlab server, I use "http://localhost:8889/?token=null"
3. In vscode create a new empty notebook, test intellisense before first run (I disabled the auto start server setting). I use "
from pathlib import Path
Path()
", when entering the above code, intellisense works correctly
4. Run the above notebook to start a new kernel, and type the above code again, the intenllisense not working this time

Extension version: 2021.10.1101450599
VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-58-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (0.79GB free)|
|Process Argv|--crash-reporter-id a83f103d-baaa-494b-a58b-a19e7c7241e4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: clips_lane|
|OS|Linux x64 5.4.0-58-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz (8 x 2499)|
|Memory (System)|31.36GB (1.45GB free)|
|VM|100%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246:30401890
vscexrecpromptc:30404946
vscop804:30404766
vs360cf:30404996

```

</details>

**Comment by rchiodo** [comment] 2021-11-29 17:42
Thanks for the bug.

This is a dupe of https://github.com/microsoft/vscode-jupyter/issues/8285

**Closed by rchiodo** 2021-11-29 17:42 UTC
Labels: needs-triage
