### ISSUE TITLE
Kernels on remote computes listed multiple times

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/vscode-jupyter#11080] opened 2022-08-09 17:18 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am using the notebook/environment from here: https://github.com/claudiaregio/data-science

What it says in the title, there are a number of conda envs on my Azure ML remote compute, and when I launch into VS Code from the Azure ML Studio notebook interface, the list of possible kernels is duplicated and the remote/local distinctions are confusing (given the session is connected to remote compute)

**List of kernels shown from the selector in the top right of the notebook:**
![kernel-picker](https://user-images.githubusercontent.com/6486256/183965401-aa76a771-66f2-4ffc-b3c3-73ebbcb85dae.png)

**What the Python interpreter selection options were:**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6486256/183715739-d493e6eb-5998-44ed-a408-564e49616723.png)

Repro: 
Add the notebook from the repo above to an Az ML workspace, open a remote compute session in VS Code (either web portal or Az ML extension), and then go to switch kernels.

Related: #11077 and #10601

### VS Code Version

Version: 1.70.0 (user setup) Commit: da76f93349a72022ca4670c1b84860304616aaa2 Date: 2022-08-04T04:38:16.462Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2022.7.1002181843

### Coding Language and Runtime Version

Python 3.7.12

### Language Extension Version (if applicable)

v2022.12.0

### Anaconda Version (if applicable)

conda 4.13.0

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment] 2022-08-09 21:13
Thanks for reporting this issues, however the screenshot shared is that of the `Python Extension`, its the list used to select an interpreter.
The kernel picker is displayed only when you have a notebook opened, please confirm the issue is with the kernel picker and not the interpreter picker.

If it is with the kernel picker, please could you upload a screenshot of the kernel picker from a ntoebook.

**Comment by crazy4pi314** [comment] 2022-08-10 16:40
Sorry for that, I was making lots of screenshots and uploaded the wrong one :( I have added one of the kernel picker, and wanted to also show the list of envs the Python Extension found by comparison. Let me know if there is anything else I can add!

**Comment by DonJayamanne** [comment] 2022-08-17 19:11
@crazy4pi314 From what I understand the confusion is the fact that you can see `Remote` kernels in the kernel picker as well as some of the local conda environments in the same kernel picker and that is what's confusing. Please could you confirm that.

**Comment by DonJayamanne** [comment] 2022-08-18 22:34
@IanMatthewHuff i believe this is an issue with the UI, I believe the confusion is we have remote and local kernels in the same dropdown, hence the confusion (leading one to think there are duplicates)

**Comment by crazy4pi314** [comment] 2022-08-22 16:31
There is definitely a UI issue, when I am connected to a remote kernel (like this is with an Azure ML compute) I would assume all kernels are remote, so I was not clear what the local ones were.

I have tried to reproduce this list of kernels, but with the most recent vs code update, I am now getting this list of notebook kernels when launching from Azure ML studio:
<img width="1926" alt="image" src="https://user-images.githubusercontent.com/6486256/185971264-9cfc395f-bd9b-4c46-9527-efe38583b330.png">

If you look at the paths for the different kernel options, there are ones duplicated in the conda env and Jupyter kernel sections, but with different names. Maybe this is ok, but then the approach of a UI fix makes sense.

Also, the conda env I installed via the command line for the compute in the browser does not register that environment as a Jupyter kernel, which idk if it should given it does not have ipykernel installed in the environment...

Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by IanMatthewHuff** [comment] 2022-08-22 17:03
@crazy4pi314 Thanks for the screenshot, that's helpful. We have a few methods of detecting what kernels / python environments are available on a system then we have a de-duplication process to try to remove options that might be covering the same things. From what I'm seeing it looks like that de-duplication process might be missing here for those Conda / KernelSpec options. If two options have the same interpreter path specified they should only both be shown if there was a difference in the Environment specified in the kernelspec, since it is possibly to have a kernelspec with a custom Env block pointing at the same interpreter that is already listed and both options should be available. 

Since those (I believe) are built in options on the Azure ML machine I should be able to investigate that myself in the upcoming iteration. We're tackling the bigger problem of how to improve our kernel picking experience both in the local and remote cases. https://github.com/microsoft/vscode-jupyter/issues/11077 if you are interested in the planning there. In general we are looking to offer a more targeted set of initial kernel options, and moving away from our current implementation that just shows everything that we could possibly use as a kernel in a big flat list.

> Also, the conda env I installed via the command line for the compute in the browser does not register that environment as a Jupyter kernel, which idk if it should given it does not have ipykernel installed in the environment...

Normally I would expect that a Conda env would not show up as a "Jupyter Kernel" in our listings regardless of if ipykernel is installed or not. We reserve that category for actual kernel.json kernelspecs that are installed on the system. With the duplicate entries that you mentioned above my guess is that the Azure ML image might be both creating Conda environments and installing a kernelspec for those environments. I think our miss there is just failing to realize that those environments and kernelspecs are equivalent and not listing both of them.

**Comment by DonJayamanne** [comment] 2022-12-06 00:19
This should get fixed with the new kernel picker.
@crazy4pi314 please could you either
*install vscode insiders and the latest pre-relase versions of Jupyter and Python extensions
* or wait for the next stable version of vscode (some time this week)

Then go into your settings and search for the setting `Notebook -> Kernel Picker Type` and select `MRU` from the dropdown.
Re-load vscode and add the new remote server once again and verify the issue exists.

Please note, you might have to re-add the remtoe server once again and this is a new `experimental` feature and not yet stable.

If you'd prefer not to test this experimental feature thats fine.

I'm closing this for now as the new kernel pickedr addresses this UI issue (will be blogged in the new release that we plan on shipping some time this week)

**Closed by DonJayamanne** 2022-12-06 00:19 UTC
Labels: bug, kernel-enumeration, iteration-candidate, kernel-picker
