### ISSUE TITLE
In-line input box

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#12076] opened 2022-11-17 22:30 UTC
Can we explore in-line input areas?

Other online nb tools provide this consistent experience that VS Code notebook users expect:
- In-line input box
- All inputs are shown in the output

In Jupyter classic (same as JupyterLab):
![jupyternb input](https://user-images.githubusercontent.com/10833267/202573677-058486e7-98c0-48bc-9cd7-0546b1d468b2.gif)

In Colab:
![colab input](https://user-images.githubusercontent.com/10833267/202573698-8b342633-3fcb-47fe-8c9e-199ae4b94514.gif)

This is the experience in VS Code (I often saw users "waiting" for the input box because they couldn't immediately find it):
![vsc input](https://user-images.githubusercontent.com/10833267/202573735-a2c1838c-add4-4d61-a635-7c1bea5f46e4.gif)

**Comment by DonJayamanne** [comment] 2022-11-18 02:15
I thought we already had an issue for this, I did try exploring this at one point.
Will dig that sample and paste that screenshot (gif) here.

**Comment by DonJayamanne** [comment] 2022-11-18 02:17
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11732

**Comment by DonJayamanne** [comment] 2024-12-12 23:44
Given that this issue has been around for a while and no one else has upvoted nor requested this issue I'm closing this.

**Closed by DonJayamanne** 2024-12-12 23:44 UTC
Labels: notebook-kernel, feature-request
