### ISSUE TITLE
Allow a notebook controller to hide the variable viewer

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode-jupyter#7515] opened 2021-09-14 18:19 UTC
If a notebook controller doesn't currently support the .ipynb variable viewer, it would be beneficial for that controller to be able to hide that functionality.

E.g., the .NET Interactive extension is currently not supported by the variable viewer and if the "Variables" button at the top of the notebook could be hidden, that would help clear a lot of confusion.

**Comment by IanMatthewHuff** [comment] 2021-09-14 21:08
Totally agree, it isn't good to have a useless button there. We're currently discussing moving variable fetching functions into part of the controller API (so signaling support could easily be a part of that as well). In the short term I feel like we could also do something better here. Would be quick to check for Jupyter extension provided controllers and only enable the variable view button / commands for those controllers.

**Comment by greazer** [comment] 2021-09-16 20:30
This is a dupe of another bug already in the September milestone. Perhaps this can be a quick fix just until a better solution is hammered out.

**Comment by greazer** [comment] 2021-11-05 23:46
Dupe of #6543

**Closed by greazer** 2021-11-05 23:46 UTC
Labels: bug, partner, duplicate, language-any
