### ISSUE TITLE
The ipyvuetify widgets are not rendering in v.2024.8.0 (JavaScript error). It works in v.2024.7.0

### ISSUE THREAD

**Issue by ndgayan** [microsoft/vscode-jupyter#16008] opened 2024-09-06 18:34 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The ipyvuetify widgets are not rendering and give JavaScript errors in the latest extension. We are using the remote SSH extension. Please try the below code. However, v.2024.7.0 works fine. 

```python
import ipyvuetify as v

my_select = v.Select(
    label='Fruits',
    items=['Apple', 'Pear', 'Cherry'])
my_select
```
![image](https://github.com/user-attachments/assets/d9374d72-7d1e-41c6-b530-4c1935c5b9d9)

Below are the 2 parts of the error.

![image](https://github.com/user-attachments/assets/f9f8e154-c42e-4615-8c49-b632e020346a)

![image](https://github.com/user-attachments/assets/a511e863-89ab-4153-87e5-1e7b765dd54e)

Below are the important packages 

ipykernel                         6.29.5
ipython                           8.27.0
ipyvue                            1.11.1
ipyvuetify                        1.10.0
ipywidgets                        8.1.5

### VS Code Version

Version: 1.93.0

### Jupyter Extension Version

v.2024.8.0

### Coding Language and Runtime Version

Python 3.11

### Running Jupyter locally or remotely?

Remote

**Comment by liningpan** [comment] 2024-09-07 01:57
I ran into the same issue when using the jupyter plugin locally

**Comment by DonJayamanne** [comment] 2024-09-07 02:08
Does it work when rolling back to the older version of Jupyter extension

**Comment by DonJayamanne** [comment] 2024-09-07 02:11
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `trace`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel (use the command `Jupyter: Show Output` to get to the logs).

**Comment by liningpan** [comment] 2024-09-07 02:26
Yes. It works when rolling back to 2024.7.

I also attached output below.

<details>
<summary>Jupyter Output</summary>

```text
22:23:06.291 [debug] Handle Execution of Cells 0 for <path-to-ipynb>
22:23:06.292 [trace] Execute Notebook <path-to-ipynb>. Step 1
22:23:06.292 [trace] Connect to Kernel <path-to-ipynb>. Step 2
22:23:06.292 [trace] Connected to Kernel <path-to-ipynb>. Step 3
22:23:06.292 [trace] executeCell 0. Step 4
22:23:06.293 [trace] Cell Index:0 sent to kernel
22:23:06.306 [trace] Start cell 0 execution @ 1725675786306 (clear output)
22:23:06.307 [debug] Kernel acknowledged execution of cell 0 @ 1725675786306
22:23:06.505 [trace] Cell 0 completed in 0.199s (start: 1725675786306, end: 1725675786505)
22:23:06.506 [trace] Cell 0 executed successfully
22:23:09.731 [debug] Handle Execution of Cells 1 for <path-to-ipynb>
22:23:09.731 [trace] Execute Notebook <path-to-ipynb>. Step 1
22:23:09.732 [trace] Connect to Kernel <path-to-ipynb>. Step 2
22:23:09.732 [trace] Connected to Kernel <path-to-ipynb>. Step 3
22:23:09.732 [trace] executeCell 1. Step 4
22:23:09.733 [trace] Cell Index:1 sent to kernel
22:23:09.753 [trace] Start cell 1 execution @ 1725675789753 (clear output)
22:23:09.754 [debug] Kernel acknowledged execution of cell 1 @ 1725675789753
22:23:09.784 [trace] Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
22:23:09.798 [trace] Widget Message: WidgetManager: Loading class MPLCanvasModel:jupyter-matplotlib:^0.11
22:23:09.802 [trace] Widget Message: WidgetManager: failed, Loading class MPLCanvasModel:jupyter-matplotlib:^0.11
22:23:09.803 [error] Widget load failure {} [ 'jsdelivr.com', 'unpkg.com' ] {
  className: 'MPLCanvasModel',
  moduleName: 'jupyter-matplotlib',
  moduleVersion: '^0.11',
  isOnline: true,
  timedout: false,
  error: '{}'
}
22:23:09.803 [trace] Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
22:23:09.808 [trace] Widget Message: WidgetManager: Loading class ToolbarModel:jupyter-matplotlib:^0.11
22:23:09.814 [trace] Widget Message: WidgetManager: failed, Loading class ToolbarModel:jupyter-matplotlib:^0.11
22:23:09.814 [error] Widget load failure {} [ 'jsdelivr.com', 'unpkg.com' ] {
  className: 'ToolbarModel',
  moduleName: 'jupyter-matplotlib',
  moduleVersion: '^0.11',
  isOnline: true,
  timedout: false,
  error: '{}'
}
22:23:09.818 [trace] Widget Message: Received display data message 8cd9bf2a4ec44999b20da10bfd563eb5
22:23:09.819 [trace] Cell 1 completed in 0.065s (start: 1725675789753, end: 1725675789818)
22:23:09.819 [trace] Cell 1 executed successfully
22:23:09.825 [trace] Version of IPyWidgets 8 determined after 0s
22:23:09.827 [trace] Widget Message: Waiting for model to be available before rendering it 8cd9bf2a4ec44999b20da10bfd563eb5
22:23:09.828 [trace] Widget Message: WidgetManager: Loading class ErrorWidgetView:@jupyter-widgets/base:2.0.0
22:23:09.837 [trace] Widget Message: WidgetManager: Loading class LayoutView:@jupyter-widgets/base:2.0.0
```

</details>

**Comment by juba** [comment] 2024-09-07 13:35
I get the same problem when running widgets in 2024.8. They work fine under Jupyter Lab or under VSCode with jupyter 2024.7, but not under VSCode with jupyter 2024.8.

I get the same kind of error message:

```
15:33:19.775 [error] Widget load failure {} [ 'jsdelivr.com', 'unpkg.com' ] {
  className: 'AnyModel',
  moduleName: 'anywidget',
  moduleVersion: '~0.9.*',
  isOnline: true,
  timedout: false,
  error: '{}'
}
```

**Comment by gabriel-lepetitaimon** [comment] 2024-09-07 16:50
I'm encountering the same issue with ``ipyvuetify`` as well as with a custom ipywidget extension I'm developping: 
after updating to VSCode 2024.8 ipywidget is unable to render the custom widgets with the error:
```
Error: No version of module jupyter-vuetify is registered
```

In the developer tools console of vscode (Help>Toggle Developer Tools) the error is preceded by:
```
Failed to load resource: the server responded with a status of 401 ()
https://vscode-remote+ssh-[...].vscode-resource.vscode-cdn.net/home/[user]/.vscode-server/data/User/globalStorage/ms-toolsai.jupyter/version-2024.8.0/scripts/a09a86bf64b0468aa0d8dec701f6d16b44d453dadd33fa1e4c3a9e6949c9622a/jupyter/nbextensions/jupyter-vuetify/index.js
```
followed by failed attempts to load the widget definition from online repo:
```
ERR [Extension Host] error 10:45:03.535: Jupyter Extension: Widget load failure {} [ 'jsdelivr.com', 'unpkg.com' ] {
  className: 'ThemeModel',
  moduleName: 'jupyter-vuetify',
  moduleVersion: '^1.10.0',
  isOnline: true,
  timedout: false,
  error: '{}'
}
```

In my understanding, the widget definition used to be loaded from the local files of the jupyter extension (e.g. stored under ``.conda/share/jupyter/nbextensions/jupyter-vuetify/index.js``). 

(The file at ``/home/[user]/.vscode-server/.../vuetify/index.js`` exists and I'm able to open it manually. The same 401 error occurs when I attempt to use my custom ipywidget extension.)

**Comment by DonJayamanne** [comment] 2024-09-08 00:43
I'm sorry you are running into this issue, I've identified the cause and have a PR to resolve this.
https://github.com/microsoft/vscode-jupyter/pull/16012

**Comment by DonJayamanne** [comment] 2024-09-08 03:35
Fix will be

**Comment by DonJayamanne** [comment] 2024-09-08 04:24
@ndgayan  @liningpan  @juba  @gabriel-lepetitaimon 
Pleasercan you try installing the latest pre release version of the Jupyter extension 2024.9.*

That should work, please let me knows i hope it goes
Thanks 

Instructions to install pre-release version

Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`  
(Below is a sample, version numbers are not the latest)
<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

**Comment by gabriel-lepetitaimon** [comment] 2024-09-08 05:01
Yes, the pre-release version solved the issue for me.
Thanks a lot!

**Comment by DonJayamanne** [comment] 2024-09-09 21:39
Fixed in the 2024.8.1 version, will  be shipped soon

**Closed by DonJayamanne** 2024-09-09 21:39 UTC
Labels: bug, ipywidgets
