### ISSUE TITLE
Editor Find Widget Does Not Search Output Cells

### ISSUE THREAD

**Issue by RossBencina** [microsoft/vscode-jupyter#12886] opened 2023-02-21 05:07 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I ran a notebook cell that output text, for example:

```
print("hello")
```

I then pressed ctrl-f and searched for "hello". Only one result was found. I expected to be able to search into the cell output. In particular, I expected to be see the matches in the output cell highlighted.

My use-case is that I'm writing code that dumps a block of text in the cell output, and I want to be able to quickly search that block of text to highlight substrings. Right now as a workaround I have to copy the cell output to a new text buffer to search it. [and incidentally, since there is no way to "select all" or "copy cell" to copy the output cell contents, I have to use the mouse in an error prone way to select the text of a cell, while avoiding accidentally selecting half the notebook.]

In the example screenshot below, I expect "assert" to be highlighted in the relevant text:

![image](https://user-images.githubusercontent.com/3253274/220252483-57166bcb-a6c2-4f49-8702-7b60b89d53f6.png)

### VS Code Version

1.75.1

### Jupyter Extension Version

v2023.1.2010391206

### Running Jupyter locally or remotely?

Local

**Comment by RossBencina** [comment] 2023-02-21 05:21
Note that (inconsistent with the above) the global search (ctrl-shift-f) does show search results for text in cell output. However when you click on a search result it does not highlight the text in the output cell.

**Comment by amunger** [comment] 2023-02-23 22:24
duplicate of https://github.com/microsoft/vscode/issues/174969, you need to manually enable searching in outputs

**Closed by amunger** 2023-02-23 22:24 UTC
Labels: feature-request
