### ISSUE TITLE
wandb could not show the log in jupyter notebook

### ISSUE THREAD

**Issue by surfii3z** [microsoft/vscode-jupyter#5430] opened 2021-04-07 09:50 UTC
Issue Type: <b>Bug</b>

I want to show the logged graph locally in my jupyter notebook (.ipynb), so I follow this example. However, it would not show the plot but this instead.

Step to reproduce:
1) Run this jupyter notebook in vscode.

Actual Result: the logging window (tensorboard-like) shows Run not found, sorry, this run was not found.

![Screenshot from 2021-04-07 18-41-09](https://user-images.githubusercontent.com/38914643/113847154-21bea280-97d2-11eb-9730-e1f178587549.png)

Expected Result: It should show the window with the plot like this
<img width="1117" alt="jupyter widget" src="https://user-images.githubusercontent.com/38914643/113847203-30a55500-97d2-11eb-8ab4-51fc3f99a1f3.png">

NOTE: I get the expected result on Google Collab but NOT on vscode.

Extension version: 2021.5.702919634
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:02:21.560Z)
OS version: Linux x64 5.4.0-70-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|31.30GB (15.03GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id e5930b05-b69c-4fd9-8872-04639e4c258c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvspyt639:30281910
pythontb:30283811
openwsldoc:30282072
vsget980cf:30284046
vspre833cf:30267465
pythonptprofiler:30281270
vsdfh931:30280409
vshan820cf:30276953
pythondataviewer:30285071

```

</details>

**Comment by rchiodo** [comment] 2021-04-07 16:23
Thanks for the bug. This is not something we'd likely be able to fix. My guess is that wandb is trying to communicate with something in the kernel and making assumptions about how jupyter is running the kernel.

**Comment by rchiodo** [comment] 2021-04-07 16:24
My guess is this line here is throwing the error:
https://github.com/wandb/client/blob/b181d10f518d356555925be21ea71f1b0c5bebdb/wandb/apis/internal_runqueue.py#L533

**Comment by surfii3z** [comment] 2021-04-07 16:35
Thank you, I shall report this bug to the wandb. Also thank you for pointing out the line

**Comment by vanpelt** [comment] 2021-04-07 18:51
For posterity I took a look at this and found the root cause.  To display live results in jupyter we render an iframe.  When users are running in Colab, Jupyterlab, or Notebooks we rely on the fact that the user is logged into wandb and has a session cookie.

I attempted to initiate a login flow using an iframe in vscode-jupyter and unfortunately it doesn't work.  We use [Auth0](https://auth0.com) to allow users to login with their github or google account.  The oauth flow does not work in the iframe and just renders a blank page.

@rchiodo I'm curious if you have an ideas or guidance on how to authenticate a specific domain within the vscode environment?

**Comment by rchiodo** [comment] 2021-04-07 19:32
I think somebody would have to debug what happens when you create the iframe. It would be nested inside other iframes that VS code creates for the output of a notebook (with different structures based on VS code stable or VS code insiders). I don't know enough about how Auth0 is making its outgoing calls to say for certain why it doesn't work. 

@rebornix do you have any ideas on what may prevent [Auth0](https://auth0.com/) from working in a VS code notebook? (Old webview or new native notebook get the same results)

**Comment by rchiodo** [comment] 2021-04-07 19:44
@vanpelt can you point us to the js that you use to do the Auth0 login? How does the js get the Auth0 js files? It might be a require js problem (require js gets rerouted in VS code)

**Comment by surfii3z** [comment] 2021-04-08 02:06
Hi, I also remember a little that it also has the problem, when working Tensorboard.

It only showed `Launching Tensorboard...` in the cell and nothing else.

Somebody has the same problem [here](https://stackoverflow.com/questions/63938552/how-to-run-tensorboard-in-vscode), which I found that vscode just launched [Tensorboard extension](https://devblogs.microsoft.com/python/python-in-visual-studio-code-february-2021-release/). I have not tried it yet though.

**Comment by vanpelt** [comment] 2021-04-08 02:12
@rchiodo there's no fancy js happening (my [helper method](https://github.com/wandb/client/blob/master/wandb/sdk/lib/ipython.py#L31) just calls `display(HTML(...))`).  We're just displaying an iframe.  Here's a gif of the login attempt:

![2021-04-07 18 59 50](https://user-images.githubusercontent.com/17/113957160-9514e400-97d3-11eb-8e69-dc348f4b8078.gif)

I assume this is due to click jacking prevention / iframe complications.  I'm wondering if there's an official way to get the browser sandbox that's used to render the iframe authenticated with my web service...

**Comment by rchiodo** [comment] 2021-04-08 16:26
Yeah that's not going to work because of the security profile of the iframes that VS code uses. Console shows this:

![image](https://user-images.githubusercontent.com/19672699/114062592-8a4a6580-984c-11eb-92e3-ed1f48fead66.png)

**Comment by rchiodo** [comment] 2021-04-08 16:28
The official way is to actually send a message back to an extension (I think). Meaning you'd have to talk to something in our extension instead of using an iframe. 

@rebornix do you have any ideas on how to get wandb to work?

**Comment by vanpelt** [comment] 2021-04-08 17:16
Yeah, I imagine there are other extensions out there that take a user through an OAuth2 flow.  The trick would be getting the JWT or session cookie associated with a domain into the browser state used to render iframes in vscode-jupyter...

**Comment by vanpelt** [comment] 2021-04-11 22:30
@rchiodo @rebornix I was thinking about this more and if there was an easy way for me to detect if the notebook was running inside of `vscode-jupyter` I could use the python `webbrowser` utility to launch a new window in the users web browser so they could view live updating stats alongside vscode.  Do either of you know a simple way to detect if I'm running in vscode-jupyter?

**Comment by rchiodo** [comment] 2021-04-12 16:04
There are a number of globals you can use to detect VS code. AcquireVsCodeAPI is probably the most consistent one? @rebornix  would know more.  https://code.visualstudio.com/api/extension-guides/webview#passing-messages-from-a-webview-to-an-extension.

If you just check for the existence of that global (don't call it, just check for the function), that should tell you if VS code is being used.

**Comment by greazer** [comment] 2021-06-05 23:53
Unless I'm missing something, any work to be done here is not within the jupyter extension. So closing. :)

**Closed by greazer** 2021-06-05 23:53 UTC
