### ISSUE TITLE
Extension activation failed 

### ISSUE THREAD

**Issue by ZeroRin** [microsoft/vscode-jupyter#12171] opened 2022-11-25 05:21 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Since yesterday the pre-release version of the extension does not work for me.
When opening a notebook, the following error message appears:
```
Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
```
In developer tools I found
```
workbench.desktop.main.js:87 [Extension Host] extension activation failed TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (c:\Users\ZeroRin\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2070921)
	at h.activate (c:\Users\ZeroRin\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:2069968)
	at c:\Users\ZeroRin\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (c:\Users\ZeroRin\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:17:163973)
	at c:\Users\ZeroRin\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003301027\out\extension.node.js:2:1576749
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```
Switch back to v2022.11.1003281132 and everything works fine, the problem only affects later versions

### VS Code Version

1Version: 1.73.1 (user setup) Commit: 6261075646f055b99068d3688932416f2346dd3b Date: 2022-11-09T04:27:29.066Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.17763 Sandboxed: No

### Jupyter Extension Version

2022.11.1003301027

### Jupyter logs

```shell
Not available. Showing `command 'jupyter.viewOutput' is not found`
```

### Running Jupyter locally or remotely?

Local

**Comment by Brainor** [comment] 2022-11-25 05:27
duplicate of #12160

**Comment by DonJayamanne** [comment] 2022-11-25 06:16
Please install the latest version of VS Code insiders
that should fix this issue

**Closed by DonJayamanne** 2022-11-25 06:16 UTC
Labels: bug

**Comment by TankNee** [comment] 2022-11-25 06:18
I have the same issue, and when I switch to the v2022.11.1003281132 everything work well.

**Comment by TankNee** [comment] 2022-11-25 06:18
I have the same issue, and when I switch to the v2022.11.1003281132 everything works well.
