### ISSUE TITLE
Jupyter Extension fails to activate on FreeBSD

### ISSUE THREAD

**Issue by Huskers2020** [microsoft/vscode-jupyter#11348] opened 2022-09-10 17:29 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Jupyter extension does not get activated on FreeBSD - 

This issue also prevails on latest pre-release version

### VS Code Version

1.70_2

### Jupyter Extension Version

2022.7.1102252217

### Jupyter logs

```shell
Jupyter log is not an option available -

[2022-09-10 12:26:08.572] [exthost] [error] Activating extension ms-toolsai.jupyter failed due to an error:
[2022-09-10 12:26:08.573] [exthost] [error] TypeError: Cannot read properties of undefined (reading 'format')
	at Object.68375 (/usr/home/prv/.vscode-oss/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:222041)
	at __webpack_require__ (/usr/home/prv/.vscode-oss/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1359444)
	at Object.66531 (/usr/home/prv/.vscode-oss/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:256026)
	at __webpack_require__ (/usr/home/prv/.vscode-oss/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1359444)
	at Object.45322 (/usr/home/prv/.vscode-oss/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:263461)
	at __webpack_require__ (/usr/home/prv/.vscode-oss/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1359444)
	at /usr/home/prv/.vscode-oss/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1361295
	at /usr/home/prv/.vscode-oss/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1366738
	at Object.<anonymous> (/usr/home/prv/.vscode-oss/extensions/ms-toolsai.jupyter-2022.7.1102252217/out/extension.node.js:17:1366777)
	at Module.u._compile (/usr/local/share/code-oss/resources/app/out/vs/loader.js:4:1313)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
	at Module.load (node:internal/modules/cjs/loader:988:32)
	at Module._load (node:internal/modules/cjs/loader:829:12)
	at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
	at Function.r._load (/usr/local/share/code-oss/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:111:14538)
	at Function.b._load (/usr/local/share/code-oss/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:62507)
	at Function.v._load (/usr/local/share/code-oss/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:61875)
	at Module.require (node:internal/modules/cjs/loader:1012:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (/usr/local/share/code-oss/resources/app/out/vs/loader.js:5:101)
	at w._loadCommonJSModule (/usr/local/share/code-oss/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:63965)
	at w._doActivateExtension (/usr/local/share/code-oss/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:14754)
	at w._activateExtension (/usr/local/share/code-oss/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:13693)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async v._activate (/usr/local/share/code-oss/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8180)
	at async v._waitForDepsThenActivate (/usr/local/share/code-oss/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:8122)
	at async v._initialize (/usr/local/share/code-oss/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:7486)

```

### Coding Language and Runtime Version

Python

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2022-09-11 01:42
Thanks for filing this issue, unfortunately I'm unable to repro this issue at my end, also others haven't reported this issue.
Please could you install the latest version of the Jupyter extesnsion, the version you are using is the older version.
We've since updated to 2022.8.**

Let me know how that goes.

**Comment by Huskers2020** [comment] 2022-09-11 02:14
I tried the latest version and have the same issue

**Comment by Huskers2020** [comment] 2022-09-11 04:59
I was able to go back in version and the last working version is v2022.5.1001601848.

Post this version it does not work.

**Comment by DonJayamanne** [comment] 2022-09-11 05:58
>  this version it does not work.

Have you tried 2022.8.*?

**Comment by Huskers2020** [comment] 2022-09-11 14:14
Yes every version post  v2022.5.1001601848 does not work

**Comment by Huskers2020** [comment] 2022-09-13 19:29
@DonJayamanne  - Do you have an update on why versions after V2022.5 are not working on VSCode / FreeBSD ?

**Comment by DonJayamanne** [comment] 2022-09-13 19:46
> V2022.5 are not working on VSCode / FreeBSD ?

This should work, my only guess is you are using VS Code OSS and perhaps something hasn't been udpated there.
We haven't had any other users report such issues to date.

Note: Each new release of Jupyter extension is updated to require the latest version of VS Code. We do this because the Juptyer extension utilizes proposed API for notebooks and that changes over time, this way when we release a new version of the Jupyter extension we know it will work as the minimum version of VS Code is the versoin we've built and tested the API against.

**Comment by DonJayamanne** [comment] 2022-09-13 19:47
I'd suggest you try the latest stable version of VS Code or the official version of VS Code stable or insiders.
If that works, then you know the problem is definitely in VS Code OSS.
However if someone else reports a similar issue with stable/insider versions of VS Code, then we know its not speciic to VS Code OSS and could be a problem in VS Code itself.

**Comment by Huskers2020** [comment] 2022-09-13 22:15
> > V2022.5 are not working on VSCode / FreeBSD ?
> 
> This should work, my only guess is you are using VS Code OSS and perhaps something hasn't been udpated there. We haven't had any other users report such issues to date.
> 
> Note: Each new release of Jupyter extension is updated to require the latest version of VS Code. We do this because the Juptyer extension utilizes proposed API for notebooks and that changes over time, this way when we release a new version of the Jupyter extension we know it will work as the minimum version of VS Code is the versoin we've built and tested the API against.

I'm using latest version of VS Code 1.70_2 and the plug v2022.5 version of plug in works. So the issue is not with VS Code as my previous versions of VS Code also work with V2022.5 but not with latest version of plug in

**Comment by Huskers2020** [comment] 2022-09-13 22:26
I have spent quite a good amount of time over the weekend to triage this issue. I re-installed older versions of my working VS Code from cache and none work with the latest version of plugin but they all work with May version of plug in. Post June the plugin is broke.

**Comment by DonJayamanne** [comment] 2022-09-14 06:09
Please could you confirm you have tried this with the stable or insider version of VS Code instead of the OSS version?

**Comment by Huskers2020** [comment] 2022-09-14 09:18
@DonJayamanne  - sorry did not realize there were two variations / flavors of VSCode. Unfortunately for FreeBSD we have  OSS version only ported.

**Comment by DonJayamanne** [comment] 2022-09-20 06:04
Will check with a few others and get back on this

**Comment by DonJayamanne** [comment] 2022-10-09 22:36
@Huskers2020 please could you test this with the latest version of the Jupyter extension and let me know how this goes

**Comment by Huskers2020** [comment] 2022-10-14 02:49
Tried the latest version v2022.10.1102881143 and the issue prevails. Let me know what I can share that will assist triage this issue. The last version May 2022 works without any issue.

**Comment by DonJayamanne** [comment] 2022-12-27 22:43
@Huskers2020 does this still fail for you?
Also, do you have similar issues with the Python extension from the marketplace?

**Comment by DonJayamanne** [comment] 2023-01-23 00:20
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Closed by DonJayamanne** 2023-01-23 00:20 UTC
Labels: bug, info-needed, important, triage-needed

**Comment by acontestabile** [comment] 2023-05-20 20:23
I have the same issue of Huskers2020. My environment is FreeBSD x64 13.2-RELEASE, Python 3.9, Code - OSS 1.76.2, Jupyter extension v2023.2.1200692131.
When opening a file with extension .ipynb, the Jupyter extension is being automatically loaded but fails the activation and the file editor tab is not usable.
