### ISSUE TITLE
Race conditions rapidly using executing cells with shift-enter

### ISSUE THREAD

**Issue by nikitakit** [microsoft/vscode-jupyter#4949] opened 2021-02-25 01:45 UTC
My workflow is to have a `#%%`-delimited python file open in one pane, and the Interactive window open in another. Often I need to execute a whole sequence of cells by pressing shift-enter a bunch of times in a row. When doing this, I frequently run into race conditions where the cells don't execute in the correct order, or even execute multiple times!

Below are two examples. Both involve restarting the kernel, and then pressing "Shift-Enter" a few times in the code pane. I've run into this issue even without a kernel restart, but I think restarting exacerbates things because (a) nothing can run until the new kernel starts, and (b) my most frequent next step after restarting is to run a whole bunch of cells. I'm also using Remote-SSH to run everything on a remote machine, which I suspect adds enough latency to make these race conditions an everyday occurrence.

![example2](https://user-images.githubusercontent.com/252225/109090038-341fc980-76c7-11eb-84d0-b14991f99f4a.gif)

![example1](https://user-images.githubusercontent.com/252225/109090036-31bd6f80-76c7-11eb-80c6-922d36e8564b.gif)

The expected behavior above would be to run cells 1-4 in numerical order, and for each cell to run exactly once.

**Comment by DonJayamanne** [comment] 2021-02-25 15:32
Thanks for filing this issue, we'll discuss this in our next triage meeting.

**Comment by joyceerhl** [comment] 2021-04-12 23:38
I'm able to repro this in Remote-Codespaces 
![image](https://user-images.githubusercontent.com/30305945/114475603-733da780-9bad-11eb-95e3-368da985fa12.png)

**Comment by greazer** [comment] 2021-04-23 22:56
We don't believe this is a regression. Therefore, moving to June to fix.

**Comment by greazer** [comment] 2021-06-04 15:38
Didn't have time to address in June, moving to July. Since Joyce was able to more easily repro in codespaces, I'm associating it with that.

**Comment by greazer** [comment] 2021-08-14 06:38
Fixed in VS Code Insiders 1.60

**Closed by greazer** 2021-08-14 06:38 UTC
Labels: bug, codespaces
