### ISSUE TITLE
Python interactive window showing html code instead of rendering error message

### ISSUE THREAD

**Issue by yohai** [microsoft/vscode-jupyter#14325] opened 2023-09-13 12:22 UTC
## Environment data

-   VS Code version: 1.82.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.8.1002501831
-   Python Extension version (available under the Extensions sidebar): v2023.16.0
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: conda 23.1.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Both  Remote and locally

## Expected behaviour

I created the following python file:

```python
# %%

assert False
``` 
and ran the cell. I expected the error in the interactive window to be correctly rendered.

## Actual behaviour

The raw html code is shown:
![Screenshot 2023-09-13 at 15 17 49](https://github.com/microsoft/vscode-jupyter/assets/6164157/204eca3d-9069-487a-8b66-1d07cba87458)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Run a cell with an error.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.82.0, undefined, desktop)
Jupyter Extension Version: 2023.8.1002501831.
Python Extension Version: 2023.16.0.
Platform: darwin (x64).
Workspace folder ~/Dropbox/Apps/Overleaf/JMLR - langevin, Home = /Users/yohai
15:20:04.384 [info] User belongs to experiment group 'NewJupyterSession'
15:20:04.670 [info] Start refreshing Kernel Picker (1694607604670)
15:20:04.685 [info] Using Pylance
15:20:05.135 [info] Starting interactive window for resource '~/Library/CloudStorage/Dropbox/Apps/Overleaf/JMLR - langevin/sdfd.py' with controller '.jvsc74a57bd06a1e7154e47d325f8cab976a6bd57af44c895f8f8d07db2e5aeaaeed3e3842fc.~/miniconda3/python.~/miniconda3/python.-m#ipykernel_launcher (Interactive)'
15:20:05.284 [info] Start refreshing Interpreter Kernel Picker
15:20:06.540 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd06a1e7154e47d325f8cab976a6bd57af44c895f8f8d07db2e5aeaaeed3e3842fc.~/miniconda3/python.~/miniconda3/python.-m#ipykernel_launcher  (Python Path: ~/miniconda3/bin/python, Conda, base, 3.11.4) for '/Interactive-1.interactive' (disableUI=false)
15:20:11.202 [info] End refreshing Kernel Picker (1694607604670)
15:20:11.248 [info] Process Execution: ~/miniconda3/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
15:20:11.250 [info] Process Execution: ~/miniconda3/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"bc81ff6b-4437-4c73-ae7b-8591698efe0c" --shell=9002 --transport="tcp" --iopub=9004 --f=~/Library/Jupyter/runtime/kernel-v2-60846Ve3cLikKANnr.json
    > cwd: ~/Library/CloudStorage/Dropbox/Apps/Overleaf/JMLR - langevin
15:20:11.261 [info] Process Execution: ~/miniconda3/bin/python -m pip list
15:20:12.190 [info] ipykernel version & path 6.25.1, ~/miniconda3/lib/python3.11/site-packages/ipykernel/__init__.py for ~/miniconda3/bin/python
15:20:12.919 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
15:20:13.174 [info] Process Execution: ~/miniconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.8.1002501831-darwin-x64/pythonFiles/printJupyterDataDir.py
15:20:13.179 [info] Generated code for 1 = <ipython-input-1-aefaa91fb82a> with 2 lines
15:20:13.201 [info] Kernel acknowledged execution of cell 1 @ 1694607613187
15:20:13.238 [warn] Got a non-existent Jupyer Data Dir file://~/.local/share/jupyter
15:20:13.627 [info] End cell 1 execution @ 1694607613623, started @ 1694607613187, elapsed time = 0.436s
15:20:13.627 [warn] Cancel all remaining cells due to cancellation or failure in execution
```

</p>
</details>

**Comment by contang0** [comment] 2023-09-13 14:30
Duplicate of [14320](https://github.com/microsoft/vscode-jupyter/issues/14320)

**Closed** 2023-09-13 15:01 UTC
Labels: bug
