### ISSUE TITLE
Completion on dot inputs double dot

### ISSUE THREAD

**Issue by cipri-tom** [microsoft/vscode-jupyter#6200] opened 2021-06-08 15:16 UTC
## Expected behaviour

Choosing a completion should not add double dots

## Actual behaviour

It adds an extra dot

## Steps to reproduce:

1. Edit a cell
2. input `(Path('/') / d['metadata'])`
3. Type a dot after the above expression, and choose one of the members of `Path` (e.g. `name` or `with_suffix)
4. Note that the path needs to contain a dictionary access, otherwise it works fine, so I guess it's the `[ .. ]` that has the bug.

https://user-images.githubusercontent.com/2991890/121210950-66bb8f80-c87c-11eb-973d-3224b220c41a.mp4

## Logs
nothing generated by the completion

## Environment data

-   VS Code version: 1.57.0-insider Commit: c7119ae8b6390a5700f6b28f0f1511d676c96562
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.914258744
-   Python Extension version (available under the Extensions sidebar): v2021.6.908196464-dev | Pylance v2021.6.1-pre.1
-   OS (Windows | Mac | Linux distro) and version: Local = Mac 10.15.7 | Remote = Ubuntu 18.04
-   Python and/or Anaconda version: 3.7.4
-   Type of virtual environment used : conda
-   Jupyter server running: Remote

---

This should have probably been in Pylance. Initially I thought it only happens in jupyter, as shown in the video, but then I noticed the point 4 in _Steps to reproduce_ (after opening this issue). 
If we do `(Path('.') / d['a']).<ctrl+space>` in a normal python file, it doesn't offer any completion at all, so probably not related to jupyter

**Comment by IanMatthewHuff** [comment] 2021-06-09 17:05
@cipri-tom Thanks for filing the detailed report. In general the notebook cells function like normal editor instances, so I would suspect a pylance issue here. Did that specific example with the Image.open command work correctly for you in a standard .py file?

**Comment by cipri-tom** [comment] 2021-06-10 10:32
umm, `Image.open()` is not involved here.

Here's a minimal reproducible example:

```python
from pathlib import Path

p = Path('/')
image_props = {'name': 'image.tiff'} # read from a file
img_path = (p / image_props['name']).with_suffix('.png')
```

erase the `.with_suffix('.png')` and try to complete it after the dot:


https://user-images.githubusercontent.com/2991890/121510285-c3878900-c9e7-11eb-9b92-8613f65012a8.mp4

So yes, it works in standard .py file, but not in jupyter cell.

---

I've run this in a local notebook, with a local Jupyter Server. I'm mentioning this because before I noticed a mismatch between the python version of the kernel and that of the window (#6224). When running everything locally, there's no option to choose Python version in the window, only the kernel.

**Comment by IanMatthewHuff** [comment] 2021-06-10 22:43
@cipri-tom I was just attempting to make sure that I was using the exact example that you had in your original gif.

Initially in the second example I'm wasn't seeing the same issue.

![doubleDot](https://user-images.githubusercontent.com/812783/121605130-b32fd800-ca00-11eb-93d1-98129ab74a70.gif)

However after poking around a bit more I do see a similar issue. For our completions when Jupyter is running we combine results both from Jupyter as well as results from VS Code's language server. It looks to me like we're doing something incorrect here as it looks like we are returning correct language server results (without the extra .) as well as Jupyter results that do have the extra period. In your gif above it looks like it's only returning Jupyter completion results (it has the wrench icon + the extra period). 

When running live my completion looks like this:
![image](https://user-images.githubusercontent.com/812783/121606078-5e8d5c80-ca02-11eb-8d20-f6e99f8be630.png)

We are getting duplication completions and the wrench icon ones do insert an extra period when placed in. I think that we can fix this in our code that looks specifically at Jupyter completion item results. Thanks again for the detailed report.

**Comment by IanMatthewHuff** [comment] 2021-06-11 17:05
Moving to triage.

**Closed** 2021-07-02 01:07 UTC
Labels: bug, regression

**Comment by greazer** [comment] 2021-07-02 01:08
I'm no longer able to reproduce this problem using the latest VS Code Insider, PyLance, Python, and Jupyter extensions. Somewhere the bug must've been fixed. @cipri-tom, please reopen if you're still seeing this behavior.
