### ISSUE TITLE
Data Viewer does not render if moved to New Window

### ISSUE THREAD

**Issue by sebwills** [microsoft/vscode-jupyter#15728] opened 2024-05-29 08:23 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Create any DataFrame or list variable in Jupyter notebook, e.g. `x=[1,2]`
In the Jupyter 'variables view', double click the variable to open it in Data Viewer.
Right-click the Data Viewer tab -> `Move into new Window`.
Data Viewer tab appears in a new window but just shows a progress bar and never renders.

New Data Viewer tabs created after that do render correctly in the new window. It's just the one that was 'moved' that fails.

I am using VSCode remote over SSH. Have not been able to test in local mode VSCode.

### VS Code Version

1.89.0

### Jupyter Extension Version

v2024.4.0

### Jupyter logs

```shell
Visual Studio Code (1.89.0, ssh-remote, desktop)
Jupyter Extension Version: 2024.4.0.
Python Extension Version: 2024.6.0.
Pylance Extension Version: 2024.5.1.
Platform: linux (x64).
No workspace folder opened.
09:10:45.228 [info] Telemetry level is off
09:10:45.228 [info] Experiments are disabled, only manually opted experiments are active.
09:10:55.200 [info] Handle Execution of Cells 0 for Untitled-1.ipynb
09:10:55.207 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd078c94486177a2b0807a4f46c3ddd31c1c6a3f46d6f713f8ab8b62e931d757214./home/~/venvs/cmr/python./home/~/venvs/cmr/python.-m#ipykernel_launcher  (Python Path: ~/venvs/cmr/bin/python, Venv, cmr (Python 3.10.12), 3.10.12) for 'Untitled-1.ipynb' (disableUI=false)
09:10:55.401 [info] Process Execution: ~/venvs/cmr/bin/python -m pip list
09:10:55.466 [info] Process Execution: ~/venvs/cmr/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:10:55.486 [info] Process Execution: ~/venvs/cmr/bin/python -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v2-2208685CpwhOHLxdk17.json
    > cwd: /home/~
09:10:56.067 [info] Process Execution: ~/venvs/cmr/bin/python /home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.4.0/pythonFiles/printJupyterDataDir.py
09:10:56.079 [info] Cell 0 completed in 0.004s (start: 1716970256075, end: 1716970256079)
09:10:56.080 [warn] Got an empty Jupyter Data Dir from /home/~/venvs/cmr/bin/python, stderr = undefined
09:10:56.677 [error] Widget Error: Failed to access CDN https://cdn.jsdelivr.net/npm/requirejs@2.3.6/bin/r.min.js after 0 attempt(s), TypeError: Failed to fetch
09:10:56.741 [error] Widget Error: Failed to access CDN https://unpkg.com/ after 0 attempt(s), TypeError: Failed to fetch
09:12:10.880 [info] Handle Execution of Cells 0 for Untitled-1.ipynb
09:12:10.898 [info] Cell 0 completed in 0.003s (start: 1716970330894, end: 1716970330897)
09:12:13.808 [info] Process Execution: ~/venvs/cmr/bin/python -c "import pandas;print(pandas.__version__);print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d")"
09:17:25.448 [info] Process Execution: ~/venvs/cmr/bin/python -c "import pandas;print(pandas.__version__);print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d")"
09:18:53.595 [info] Execution of code ms-toolsai.jupyter-1 completed in 14ms
09:18:55.258 [info] Handle Execution of Cells 0 for Untitled-1.ipynb
09:18:55.275 [info] Cell 0 completed in 0.004s (start: 1716970735271, end: 1716970735275)
09:18:58.538 [info] Process Execution: ~/venvs/cmr/bin/python -c "import pandas;print(pandas.__version__);print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d")"
```

### Coding Language and Runtime Version

Python 3.10.12

### Language Extension Version (if applicable)

Python v2024.6.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment] 2024-05-29 16:00
duplicate of https://github.com/microsoft/vscode-jupyter/issues/15574

Also, take a look at the data wrangler extension's data viewer since the jupyter extension's dataviewer [will eventually be deprecated](https://github.com/microsoft/vscode-jupyter/issues/15486)

**Closed by amunger** 2024-05-29 16:00 UTC
Labels: bug
