### ISSUE TITLE
Unable to run all cells at once.

### ISSUE THREAD

**Issue by Sanjaykrishnamurthy** [microsoft/vscode-jupyter#12707] opened 2023-02-01 02:44 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I click the run all above button in VSCode Jupyter notebook, I get this error
"notebook controller is DISPOSED. 
View Jupyter [log](command:jupyter.viewOutput) for further details."

I switched back to prerelease version but still the error exists

Details of my Jupyter extension pack are
_Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2023.1.1003441034
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter_

### VS Code Version

1.74.3

### Jupyter Extension Version

2023.1.1003441034

### Jupyter logs

```shell
"notebook controller is DISPOSED. 
View Jupyter [log](command:jupyter.viewOutput) for further details."
```

### Coding Language and Runtime Version

Python 3.8.10

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2023-02-01 02:55
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11747

**Closed by DonJayamanne** 2023-02-01 02:55 UTC
Labels: bug
