### ISSUE TITLE
Dataframe font, table row hover highlight

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#6546] opened 2021-07-06 18:40 UTC
Dataframes in the new native interactive window look great! I especially like the horizontal scroll as opposed to truncating columns.

However, two small requests:
1. Dataframes default to use a monospace font (eg consolas, courier) OR option to change font
    - so numeric columns have consisten vertical alignment
2. Rows highlighted on hover as they used to. I think css is `tr:hover`

Thanks!!

<img width="644" alt="Screen Shot 2021-07-06 at 11 35 35 AM" src="https://user-images.githubusercontent.com/29611875/124650479-a6ab6d80-de4e-11eb-8b43-ddef3c17ec41.png">

**Comment by IanMatthewHuff** [comment] 2021-07-06 20:24
@jaymegordo Thanks for checking out the new Native Interactive UI. Both really good suggestions here, especially on the default font.

**Comment by IanMatthewHuff** [comment] 2021-07-06 20:31
Possible partial duplicate here: https://github.com/microsoft/vscode/issues/123149 though this is not DataFrame specific.

**Comment by DonJayamanne** [comment] 2022-12-06 00:26
Duplicate of #12078

**Closed by DonJayamanne** 2022-12-06 00:26 UTC
Labels: notebook-output, feature-request
