### ISSUE TITLE
No MIME types available for cell outputs

### ISSUE THREAD

**Issue by tgiesselmann-ep** [microsoft/vscode-jupyter#9270] opened 2022-03-08 02:41 UTC
## Environment data

-   VS Code version: 1.65.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.1030672458
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: MacOS Big Sur 11.5
-   Python and/or Anaconda version: 3.9.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Python code cell output should be rendered in a monospaced font – at least, one should be able to change the output presentation.

## Actual behaviour

Code cell output uses a variable-width font, not monospaced. It's not possible to change the presentation because only one MIME type is listed (`application/vnd.code.notebook.stdout`)

## Steps to reproduce:

1. Create a blank Jupyter notebook.
2. Add a code block and add a statement like `print("Where are my MIME types?")`
3. Notice that the output uses variable-width font, not monospaced.
4. Click on the cell's "..." button and select "Change Presentation".
5. Only the current MIME type (`application/vnd.code.notebook.stdout`) is available for selection.

![VSCode Jupyter MIME](https://user-images.githubusercontent.com/70977361/157155379-a4aebf55-6b71-4dfb-b35b-5000771608e5.gif)

## Logs

<details>
<p>

```
Visual Studio Code (1.65.0, undefined, desktop)
Jupyter Extension Version: 2022.2.1030672458.
Python Extension Version: 2022.2.1924087327.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 18:17:15: ZMQ install verified.
Info 18:17:15: Preferred kernel connection found in cache .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 18:17:15: PreferredConnection: .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher found for NotebookDocument: ~/devel/epcc/t/test.ipynb
Info 18:17:15: Early registration of controller for Kernel connection .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 18:17:15: TargetController found ID: .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher for document ~/devel/epcc/t/test.ipynb
Info 18:17:15: Setting controller affinity for ~/devel/epcc/t/test.ipynb .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 18:17:16: Interrupt requested & no kernel.
Info 18:17:16: Setting setActiveController for ~/devel/epcc/t/test.ipynb
Info 18:17:16: Getting activation commands for /usr/local/bin/python3 are not cached. May take a while.
Info 18:17:16: KernelProvider switched kernel to id = .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 18:17:16: Starting Notebook in kernel.ts id = .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 18:17:16: Creating raw notebook for ~/devel/epcc/t/test.ipynb
Info 18:17:16: Getting preferred kernel for ~/devel/epcc/t/test.ipynb
Info 18:17:16: Computing working directory ~/devel/epcc/t/test.ipynb
Info 18:17:16: Starting raw kernel Python 3.9.10 64-bit for interpreter /usr/local/bin/python3
Info 18:17:16: installMissingDependencies /usr/local/bin/python3
Info 18:17:16: IPyKernel found previously in this environment /usr/local/bin/python3
Info 18:17:16: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 18:17:16: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 18:17:16: Creating controller for jupyter-notebook with interpreter /usr/local/opt/python@3.10/bin/python3
Info 18:17:16: Getting activation commands for /usr/local/opt/python@3.10/bin/python3 are not cached. May take a while.
Info 18:17:16: Process Execution: > /usr/local/bin/python3 -m pip list
> /usr/local/bin/python3 -m pip list
Info 18:17:16: Process Execution: > /usr/local/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /usr/local/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 18:17:16: Process Execution: > /usr/local/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"b9afcd5b-0456-4a87-a296-2c06c87a5fbe" --shell=9002 --transport="tcp" --iopub=9004 --f=/var/folders/0y/npqp7r6s3d1cypg6fqjw50940000gp/T/tmp-30306HM9HhW6JEci4.json
> /usr/local/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"b9afcd5b-0456-4a87-a296-2c06c87a5fbe" --shell=9002 --transport="tcp" --iopub=9004 --f=/var/folders/0y/npqp7r6s3d1cypg6fqjw50940000gp/T/tmp-30306HM9HhW6JEci4.json
Info 18:17:16: Process Execution: cwd: ~/devel/epcc/t
cwd: ~/devel/epcc/t
Info 18:17:16: Process Execution: > /usr/local/opt/python@3.10/bin/python3 -m pip list
> /usr/local/opt/python@3.10/bin/python3 -m pip list
Info 18:17:16: Registering dummy command feature
Info 18:17:17: ipykernel version 6.9.1 for /usr/local/bin/python3
Info 18:17:17: ipykernel location /usr/local/lib/python3.9/site-packages/ipykernel/__init__.py for /usr/local/bin/python3
Info 18:17:17: Registering dummy command feature
Info 18:17:17: Execute Cells request 0
Info 18:17:17: Execute Cell 0 ~/devel/epcc/t/test.ipynb
Warn 18:17:17: StdErr from Kernel Process /usr/local/lib/python3.9/site-packages/traitlets/traitlets.py:2202: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

Warn 18:17:17: StdErr from Kernel Process /usr/local/lib/python3.9/site-packages/traitlets/traitlets.py:2157: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'b9afcd5b-0456-4a87-a296-2c06c87a5fbe' instead of 'b"b9afcd5b-0456-4a87-a296-2c06c87a5fbe"'.
  warn(

Info 18:17:17: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing /var/folders/0y/npqp7r6s3d1cypg6fqjw50940000gp/T/tmp-30306HM9HhW6JEci4.json

Info 18:17:17: Raw session started and connected
Started kernel Python 3.9.10 64-bit
Info 18:17:18: Finished connecting ef9faad6-0bd0-4f91-a404-dd4d5277716f
Info 18:17:18: Executing silently Code (idle) = import sys\nprint(sys.executable)
Info 18:17:18: Executing silently Code (completed) = import sys\nprint(sys.executable)
Info 18:17:18: Process Execution: > /usr/local/bin/python3 -c "import sys;print(sys.executable)"
> /usr/local/bin/python3 -c "import sys;print(sys.executable)"
Info 18:17:18: UpdateWorkingDirectoryAndPath in Kernel
Info 18:17:18: Executing silently Code (idle) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "/Users/torben.gies
Info 18:17:18: Executing silently Code (completed) = import site\nsite.addsitedir(site.getusersitepackages())\nimport os\nimport sys\n%cd "/Users/torben.gies
Info 18:17:18: Waiting for idle on (kernel): 98052b3d-7e7d-4b71-b229-c1aa6a35f498 -> idle
Info 18:17:18: Finished waiting for idle on (kernel): 98052b3d-7e7d-4b71-b229-c1aa6a35f498 -> idle
Info 18:17:18: Cell 0 executed with state Success
Info 18:28:18: Execute Cells request 0
Info 18:28:18: Execute Cell 0 ~/devel/epcc/t/test.ipynb
Info 18:28:18: Cell 0 executed with state Success
Info 18:29:03: Execute Cells request 0
Info 18:29:03: Execute Cell 0 ~/devel/epcc/t/test.ipynb
Info 18:29:03: Cell 0 executed with state Success
Info 18:30:40: Execute Cells request 0
Info 18:30:40: Execute Cell 0 ~/devel/epcc/t/test.ipynb
Info 18:30:40: Cell 0 executed with state Success
Info 18:31:44: Execute Cells request 0
Info 18:31:44: Execute Cell 0 ~/devel/epcc/t/test.ipynb
Info 18:31:44: Cell 0 executed with state Success
Info 18:37:08: Loading webview. View is notset
Info 18:37:08: Loading web view...
Info 18:37:08: Webview panel created.
Info 18:37:08: Web view react rendered
Info 18:37:08: Executing silently Code (idle) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 18:37:08: Executing silently Code (idle) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 18:37:09: Executing silently Code (completed) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 18:37:09: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 18:37:09: Executing silently Code (completed) = # Query Jupyter server for the info about a dataframe\nimport json as _VSCODE_json\nimport builtins as
Info 18:37:09: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 18:37:09: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 18:37:09: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
Info 18:37:09: Searching for token colors ...
Info 18:37:09: Attempting search for colors ...
Info 18:37:09: Loading colors from /Users/torben.giesselmann/.vscode/extensions/arcticicestudio.nord-visual-studio-code-0.19.0/themes/nord-color-theme.json ...
Info 18:37:09: Attempting search for colors ...
Info 18:37:09: Loading base colors from /Users/torben.giesselmann/.vscode/extensions/arcticicestudio.nord-visual-studio-code-0.19.0/themes/nord-color-theme.json ...
Info 18:37:09: Using colors to generate CSS ...
```
</p>
</details>

**Comment by SnakeHit** [comment] 2022-03-08 06:52
Believe this is already fixed in vscode core. I use the Ligature nerd font, but my cell outputs is the MIME type

**Comment by tgiesselmann-ep** [comment] 2022-03-08 16:19
> I use the Ligature nerd font, but my cell outputs is the MIME type

This issue is not about fonts, per se. What do you mean when you say _"my cell outputs is the MIME type"_?

**Comment by rchiodo** [comment] 2022-03-08 17:26
Thanks for the bug. This is a dupe of https://github.com/microsoft/vscode/issues/144579

**Closed by rchiodo** 2022-03-08 17:26 UTC
Labels: bug, needs-triage

**Comment by tgiesselmann-ep** [comment] 2022-03-08 22:31
Thanks, @rchiodo. Apologies for the dupe.
