### ISSUE TITLE
Recycle bin gets full of temporary notebooks

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#1645] opened 2020-08-24 04:41 UTC
![image](https://user-images.githubusercontent.com/20347396/91004570-6a01bb00-e589-11ea-9d5b-4dbe5c22793c.png)

I think it happens every time you open a notebook. Its annoying.

**Comment by greazer** [comment] 2021-08-08 17:49
Dupe of #6510

**Closed by greazer** 2021-08-08 17:49 UTC
Labels: bug
