### ISSUE TITLE
Focus jumps to cell N+1 output when evaluating cell N

### ISSUE THREAD

**Issue by yash-ctc** [microsoft/vscode-jupyter#14991] opened 2024-01-05 21:14 UTC
Type: <b>Bug</b>

In the VSCode jupyter notebook renderer, if cell N+1 already has output and that output is large, when cell N is evaluated, focus jumps to show all of cell N+1 output.  this makes cell N output impossible to see, as it is now off the screen.  clearly the user wants to see cell N output, since that is the one that was just evaluated.  jupyter lab fixed this in more recent versions.

Extension version: 1.0.17
VS Code version: Code 1.84.2 (1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, 2023-11-09T10:51:52.184Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 3.10.0-1160.99.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6254 CPU @ 3.10GHz (3 x 3093)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (6.86GB free)|
|Process Argv|--crash-reporter-id 1ecf349b-8e9a-4663-bd7a-4200b498e657|
|Screen Reader|no|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: ch12ldvdi515|
|OS|Linux x64 3.10.0-1160.99.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6342 CPU @ 2.80GHz (96 x 2800)|
|Memory (System)|503.19GB (392.51GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by amunger** [comment] 2024-01-05 23:48
You can change the `notebook.scrolling.revealNextCellOnExecute` setting to adjust this behavior to what you prefer.

**Comment by amunger** [comment] 2024-01-05 23:49
dupe of https://github.com/microsoft/vscode/issues/191086

**Closed by amunger** 2024-01-05 23:49 UTC
Labels: notebook-output
