### ISSUE TITLE
"Go to definition" does not work when connected to remote Jupyter server

### ISSUE THREAD

**Issue by nulinspiratie** [microsoft/vscode-jupyter#8669] opened 2022-01-11 13:01 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When connecting VS Code to an externally connected server (e.g. running `jupyter lab` from command prompt), the "go to definition" functionality is not working for anything. When pressing F12, the error "No definition found for '{variable}'" pops up

Note that when a local server is started, it is able to find the correct function definition. It is also able to find definitions in cell scripts.

I have tried both Jedi and PyLance but the problem persists, leading me to think it might be an issue with the vscode-jupyter extension.

### VS Code Version

Version: 1.63.2 (user setup) Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3 Date: 2021-12-15T09:40:02.816Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2021.11.1001550889

### Jupyter logs

```shell
Jupyter Extension Version: 2021.11.1001550889.
Python Extension Verison: 2021.12.1559732655.
Info 14:01:22: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 14:01:22: Checking for server existence.
Info 14:01:22: Checking for server usability.
Info 14:01:22: Starting notebook server.
Info 14:01:22: Connecting to server
Info 14:01:22: Connecting to process server
Info 14:01:22: Connecting server kernel http://127.0.0.1:8888/
Connecting to Jupyter server at http://127.0.0.1:8888/
Info 14:01:22: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"cdd59fbdd68bf8c5cd09f4335fc2548c98cdcdef57fca825","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 14:01:22: Connection complete server
Info 14:01:22: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 14:01:22: Server started.
Info 14:01:22: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"cdd59fbdd68bf8c5cd09f4335fc2548c98cdcdef57fca825","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 14:01:22: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"cdd59fbdd68bf8c5cd09f4335fc2548c98cdcdef57fca825","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 14:01:22: Process Execution: > C:\ProgramData\Miniconda3\python.exe -c "import jupyter"
> C:\ProgramData\Miniconda3\python.exe -c "import jupyter"
Info 14:01:22: Process Execution: > C:\ProgramData\Miniconda3\python.exe -c "import notebook"
> C:\ProgramData\Miniconda3\python.exe -c "import notebook"
Info 14:01:22: Disposing session manager
Info 14:01:22: SessionManager - dispose contents manager
Info 14:01:22: ShutdownSessionAndConnection - dispose session manager
Info 14:01:22: Finished disposing jupyter session manager
Info 14:01:22: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"cdd59fbdd68bf8c5cd09f4335fc2548c98cdcdef57fca825","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 14:01:22: Disposing session manager
Info 14:01:22: SessionManager - dispose contents manager
Info 14:01:22: ShutdownSessionAndConnection - dispose session manager
Info 14:01:22: Finished disposing jupyter session manager
Info 14:01:23: Setting setActiveController for c:\Users\BF1_V1\Documents\Notebooks\test.ipynb
Info 14:01:23: Disposing session manager
Info 14:01:23: SessionManager - dispose contents manager
Info 14:01:23: ShutdownSessionAndConnection - dispose session manager
Info 14:01:23: Finished disposing jupyter session manager
Info 14:01:23: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"cdd59fbdd68bf8c5cd09f4335fc2548c98cdcdef57fca825","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 14:01:23: KernelProvider switched kernel to id = .python3.C:/ProgramData/Miniconda3\python.exe..-m#ipykernel_launcher
Info 14:01:23: Disposing session manager
Info 14:01:23: SessionManager - dispose contents manager
Info 14:01:23: ShutdownSessionAndConnection - dispose session manager
Info 14:01:23: Finished disposing jupyter session manager
Info 14:01:23: Find preferred kernel for c:\Users\BF1_V1\Documents\Notebooks\test.ipynb with metadata {"interpreter":{"hash":"ecf5722fdaf1897a315d257d89d94520bfcaa453217d5becf09b39e73618b0de"},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"orig_nbformat":4} & preferred interpreter 
Info 14:01:23: Preferred Remote kernel for c:\Users\BF1_V1\Documents\Notebooks\test.ipynb is 034f9600-fbc8-439f-ab59-7eceb6f1a01f
Info 14:01:23: PreferredConnection: .python3.C:/ProgramData/Miniconda3\python.exe..-m#ipykernel_launcher found for NotebookDocument: c:\Users\BF1_V1\Documents\Notebooks\test.ipynb
Info 14:01:23: TargetController found ID: .python3.C:/ProgramData/Miniconda3\python.exe..-m#ipykernel_launcher for document c:\Users\BF1_V1\Documents\Notebooks\test.ipynb
Info 14:01:23: Setting controller affinity for c:\Users\BF1_V1\Documents\Notebooks\test.ipynb .python3.C:/ProgramData/Miniconda3\python.exe..-m#ipykernel_launcher
Info 14:01:23: IPyWidgetScriptSource.initialize
Info 14:01:23: Registering dummy command feature
Info 14:01:24: Process Execution: > C:\ProgramData\Miniconda3\python.exe -m jupyter kernelspec --version
> C:\ProgramData\Miniconda3\python.exe -m jupyter kernelspec --version
Info 14:01:25: Creating daemon pool for C:\ProgramData\Miniconda3\python.exe with env variables count 71
Info 14:01:25: Process Execution: > C:\ProgramData\Miniconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\ProgramData\Miniconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 14:01:25: Process Execution: > C:\ProgramData\Miniconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\ProgramData\Miniconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 14:01:25: Process Execution: > C:\ProgramData\Miniconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\ProgramData\Miniconda3\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 14:01:26: Creating server with settings : {"baseUrl":"http://127.0.0.1:8888/","appUrl":"","wsUrl":"ws://127.0.0.1:8888/","token":"cdd59fbdd68bf8c5cd09f4335fc2548c98cdcdef57fca825","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 14:01:26: Disposing session manager
Info 14:01:26: SessionManager - dispose contents manager
Info 14:01:26: ShutdownSessionAndConnection - dispose session manager
Info 14:01:26: Finished disposing jupyter session manager
```

### Coding Language and Runtime Version

Python 3.9.6

### Language Extension Version (if applicable)

Python extension v2021.12.1559732655

### Anaconda Version (if applicable)

4.10.3

### Running Jupyter locally or remotely?

Remote

**Comment by rchiodo** [comment] 2022-01-11 17:19
Thanks for the bug. This should be a dupe of #8285 which should be in our latest insiders release. You can verify by installing the insiders version of VS code.

**Closed by rchiodo** 2022-01-11 17:19 UTC
Labels: bug, needs-triage
