### ISSUE TITLE
Visual bug: Input frame of the interactive window becomes too narrow to show the characters after switching tabs.

### ISSUE THREAD

**Issue by YuanfengZhang** [microsoft/vscode-jupyter#14513] opened 2023-10-16 02:28 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

![image](https://github.com/microsoft/vscode-jupyter/assets/71358306/64e36f3a-858c-4c0c-b718-1fe9264caaf2)
1. Open an interactive window, it looks fine:
![image](https://github.com/microsoft/vscode-jupyter/assets/71358306/6583a122-6a36-4228-a88e-178556c84792)
2. Switch the tab from this interactive window to a coding script file (.py, .sh ...) and then switch back, just use ```shift+tab``` twice.
3. It collapsed and both the latin and non-latin characters are not shown well.
![image](https://github.com/microsoft/vscode-jupyter/assets/71358306/ea362992-e093-43c2-beee-ac70c0386334)
![image](https://github.com/microsoft/vscode-jupyter/assets/71358306/a90d5b14-757e-4e8d-b04f-29c9c5bcbf85)
4. Quick fix: open and close the side bar (e.g. extension page), or switch to settings/any other non-file tabs then switch back, the input frame is fine again.
![image](https://github.com/microsoft/vscode-jupyter/assets/71358306/8e5f4cae-e604-4172-ad8b-309c86f05ae7)

The jupyter extension settings have never been edited.
I have no clue it's a VSCode problem about scaling or a Jupyter extension problem. 

Here are visual settings:
 + 175% scaling             Windows 11 system-display settings
 + 'AurulentSansMono Nerd Font', 'Firacode Nerd Font', Consolas, 'Courier New', monospace         FontFamily in VSCode
 + 16          FontSize in VSCode

Thanks for your work, and please contact me anytime if you wanna more env details.

### VS Code Version

版本: 1.83.1 (system setup) 提交: f1b07bd25dfad64b0167beb15359ae573aecd2cc 日期: 2023-10-10T23:48:05.904Z Electron: 25.8.4 ElectronBuildId: 24154031 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.22621

### Jupyter Extension Version

v2023.9.1102792234

### Jupyter logs

```shell
2023-10-16 08:30:58.002 [info] Added views:workbench.panel.markers.view in workbench.panel.markers
2023-10-16 08:30:58.003 [info] Added views:workbench.panel.output in workbench.panel.output
2023-10-16 08:30:58.003 [info] Added views:terminal in terminal
2023-10-16 08:30:58.003 [info] Added views:outline in workbench.view.explorer
2023-10-16 08:30:58.003 [info] Added views:workbench.scm in workbench.view.scm
2023-10-16 08:30:58.003 [info] Added views:workbench.view.search in workbench.view.search
2023-10-16 08:30:58.003 [info] Added views:timeline in workbench.view.explorer
2023-10-16 08:30:58.003 [info] Added views:workbench.explorer.fileView in workbench.view.explorer
2023-10-16 08:30:58.147 [info] Added views:workbench.debug.welcome in workbench.view.debug
2023-10-16 08:30:58.147 [info] Added views:workbench.debug.breakPointsView in workbench.view.debug
2023-10-16 08:31:00.058 [info] Added views:~remote.forwardedPorts in ~remote.forwardedPortsContainer
2023-10-16 08:31:00.602 [info] Added views:codium-tree-view,prepr-view in workbench.view.extension.codium-sidebar-view-container
2023-10-16 08:31:00.603 [info] Added views:workspaceEnvironments,pythonEnvironments in workbench.view.extension.package-explorer
2023-10-16 08:31:00.604 [info] Added views:dockerContainers,dockerImages,dockerRegistries,dockerNetworks,dockerVolumes,vscode-docker.views.dockerContexts,vscode-docker.views.help in workbench.view.extension.dockerView
2023-10-16 08:31:00.604 [info] Added views:PowerShellCommands in workbench.view.extension.PowerShell
2023-10-16 08:31:00.605 [info] Added views:remoteTargets in workbench.view.remote
2023-10-16 08:31:00.605 [info] Added views:workspaceViewer in workbench.view.extension.workspaceViewer
2023-10-16 08:31:00.605 [info] Added views:jsonOutline in workbench.view.extension.json-views
2023-10-16 08:31:03.834 [info] Added views:workbench.panel.repl.view in terminal
2023-10-16 08:31:07.394 [info] Added views:remoteExplorer in workbench.view.extension.sftp
2023-10-16 08:31:07.464 [info] Added views:workbench.view.testing in workbench.view.extension.test
2023-10-16 08:31:09.263 [info] Added views:workbench.panel.comments in workbench.panel.comments
2023-10-16 08:31:09.428 [info] Added views:jupyterViewVariables in workbench.view.extension.jupyter-variables
2023-10-16 08:31:09.870 [info] Added views:rHelpPages in workbench.view.extension.workspaceViewer
2023-10-16 08:31:09.872 [info] Added views:rLiveShare in workbench.view.extension.workspaceViewer
2023-10-16 08:31:18.852 [info] Added views:workbench.panel.chat.view.copilot in workbench.panel.chatSidebar
2023-10-16 09:47:43.736 [info] Added views:workbench.views.extensions.local.installed,workbench.views.extensions.remote.installed,workbench.views.extensions.popular,extensions.recommendedList in workbench.view.extensions
2023-10-16 09:47:43.739 [info] Removed views:workbench.views.extensions.popular from workbench.view.extensions
```

### Coding Language and Runtime Version

Python 3.11

### Language Extension Version (if applicable)

python=v2023.18.0,magicpython=v1.1.0, pylance= v2023.10.20

### Anaconda Version (if applicable)

conda=22.9.0

### Running Jupyter locally or remotely?

None

**Comment by YuanfengZhang** [comment] 2023-10-16 02:45
Also, this problem become serious for multi-line draft in the input frame.
Example:
1. Type many lines in the input frame.
![image](https://github.com/microsoft/vscode-jupyter/assets/71358306/67658dff-6a76-43be-b250-46370068667f)
2. Switch to any file or non-file tab then switch back.
3. The frame collapsed to only one line height.
![image](https://github.com/microsoft/vscode-jupyter/assets/71358306/60fbc772-4114-4a85-947c-db7f2b7c5062)
type ```ENTER``` at any position of the draft in the frame, all characters shown again.
![image](https://github.com/microsoft/vscode-jupyter/assets/71358306/954ec957-1f77-475d-a172-cde50ff3dc6c)

Is it a feature or a bug? I think it should be appropriate to maintain/freeze the visual layout before and after switching focus.

**Comment by amunger** [comment] 2023-10-16 15:59
duplicate of https://github.com/microsoft/vscode/issues/157059

**Closed by amunger** 2023-10-16 15:59 UTC
Labels: bug
