### ISSUE TITLE
Problem with conda environment in WSL 2

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9954] opened 2022-05-09 16:02 UTC
I have the similar issue with ModuleNotFoundError in wsl 2. Base env works fine, some env that I created installing env package with "pip install -e ." works perfectly. Only env created with "conda create --name myenv" has issue only with .ipynb notebook files.

- .py files run fine within wsl2 and vs code inside conda created env.
- .ipynb files run fine inside web browser jupyter notebook and installed conda env. outside wsl 2
- Conda env can be activated inside vs code terminal and has necessary packages installed (within wsl2).
- i have the issue running .ipynb inside vscode and wsl 2. any module (import pandas etc) other than python native (import os, sys etc.) is not recognized inside vs code jupyter notebook (while it works fine in terminal or .py run file)

Any ideas?

_Originally posted by @VokaCv in https://github.com/microsoft/vscode-jupyter/issues/9886#issuecomment-1120139399_

**Comment by DonJayamanne** [comment] 2022-05-09 18:12
Isn't the root cause of this issue the fact that Python isn't in the conda environment. Creating conda environments using `conda create --name myname` could be a conda environment for java, hence Python will not be found in that environment.

I believe this is something that Python team was working on.
Basically such environments cannot be used by us until & unless we install Python into the environment `first`.

**Comment by DonJayamanne** [comment] 2022-05-10 01:04
@VokaCv

To unblock you from the current situation please could you provide the following information:
* Version of Python & Jupyter extension
* Version of VS Code
* Version of conda `conda --version`

> Conda env can be activated inside vs code terminal and has necessary packages installed (within wsl2).

* Please could you actiavte the above newly created conda environment in the terminal and run the following code:
```python
import sys
print(sys.executable)
```
	* provide the output you get from the terminal.
	* Provide the name of the newly created conda environment
* Please could you open a notebook in VS Code and ensure you select the above newly created conda environment
	* Run the following cell and provide the output.
	```python
	import sys
	print(sys.executable)
	```
	* Provide the output from the `Jupyter` output panel (use the command `Jupyter; Show Output` to get to the output window)
	* Provide the output from the `Python` output panel (use the command `Python; Show Output` to get to the output window)

**Comment by VokaCv** [comment] 2022-05-10 05:35
Hi,

thanks for your answers. 

I had a task to deliver so i could not wait. I will be unable to provide you the info since I hard reset all my system (uninstall vs code and all extensions, uninstall ubuntu, uninstall anaconda, disable wsl2) and then reinstall all. 

After hard reboot now it works as expected.

**Comment by DonJayamanne** [comment] 2022-05-10 07:25
thanks, closing for now

**Closed by DonJayamanne** 2022-05-10 07:25 UTC
Labels: info-needed, notebook-kernel, kernel-management
