### ISSUE TITLE
`files.insertFinalNewline` applied to notebook cells

### ISSUE THREAD

**Issue by maximlt** [microsoft/vscode-jupyter#14706] opened 2023-11-12 16:53 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have `files.insertFinalNewline: true` set in my config and this leads to an empty new line being added to my cells. It seems to me it's a bug, as I don't consider a cell being a file, having an empty new line in a code cell is not standard practice when editing notebooks.

### VS Code Version

Version: 1.84.2 (Universal) Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e Date: 2023-11-09T10:52:33.687Z Electron: 25.9.2 ElectronBuildId: 24603566 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Darwin arm64 22.6.0

### Jupyter Extension Version

v2023.10.1003070148

### Running Jupyter locally or remotely?

None

**Comment by Yoyokrazy** [comment] 2023-12-08 20:47
Could you attempt to reproduce this within the latest stable release? During the latest iteration there was a decision made to separate the final newline behavior into separate `files.` and `notebooks.` settings due to multiple issues filed matching this. 

The new setting `notebook.insertFinalNewline` should be off by default, which should resolve this.

**Comment by maximlt** [comment] 2023-12-12 21:44
I confirm this is now fixed.

**Comment by Yoyokrazy** [comment] 2023-12-12 22:16
Closing as fixed.

**Closed by Yoyokrazy** 2023-12-12 22:16 UTC
Labels: bug, info-needed
