### ISSUE TITLE
Typing in python interactive window becomes impossible

### ISSUE THREAD

**Issue by RichardHuenermann** [microsoft/vscode-jupyter#3944] opened 2020-11-17 07:42 UTC
As described here:
https://www.reddit.com/r/vscode/comments/i45agt/cannot_type_code_into_python_interactive_console/
It sometimes becomes impossible to type in the interactive window.
A workaround is moving the interactive window tab around, then it works again.

**Comment by rchiodo** [comment] 2020-11-17 20:04
Dupe of #446

**Closed by rchiodo** 2020-11-17 20:04 UTC
