### ISSUE TITLE
Interrupt/Restart Slow or Not Working

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#7867] opened 2021-10-07 01:23 UTC
I have a hunch that interrupt not working is coming from the cell level based on previous feedback and my own experience as well. The cell level interrupt sometimes just doesn't work and requires restarting the entire kernel. 

![image](https://user-images.githubusercontent.com/19276747/136305364-c46f5edb-628c-4765-ba9f-82f2773fb461.png)

**Comment by DonJayamanne** [comment] 2021-10-12 17:28
Interrupt is slow or doesn't work on windows, this is a know issue for Windows (nothing much we can do)
Restart is slow is documented here https://github.com/microsoft/vscode-jupyter/issues/7849

Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/7849

**Closed by DonJayamanne** 2021-10-12 17:28 UTC
Labels: bug, kernel-issues
