### ISSUE TITLE
variable explorer icon goes missing if using both Python + .NET Interactive 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#10087] opened 2022-05-21 00:02 UTC
## Environment data

-   VS Code version: 1.67.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1021342353
-   Python Extension version (available under the Extensions sidebar): v2022.6.2
-   OS (Windows | Mac | Linux distro) and version: Windows

## Steps to reproduce:

1. Work with .NET Notebook
2. Create new jupyter notebook through command palette
3. Switch kernel to Python kernel 

## Expected behaviour

For there to be a variable explorer icon in the toolbar so I can use it

## Actual behaviour

Variable explorer icon missing. Is only solved by bringing focus to another notebook and then bringing it back

![image](https://user-images.githubusercontent.com/19276747/169625900-01e740b5-7027-4581-b350-0a12b6bdf3ce.png)

**Comment by amunger** [comment] 2022-05-23 16:31
thanks for the bug, I can repro

**Comment by rchiodo** [comment] 2022-05-23 20:21
Sounds like a dupe of https://github.com/microsoft/vscode-jupyter/issues/10081

**Closed by rchiodo** 2022-05-23 20:21 UTC
Labels: bug, papercut :drop_of_blood:, triage-needed
