### ISSUE TITLE
KQL syntax stopped working

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-jupyter#6253] opened 2021-06-10 01:57 UTC
<h3> Environment data </h3>

-   Language Server version: 2021.6.2-pre.1
-   OS and version: linux x64
-   Python version (and distribution if applicable, e.g. Anaconda): 
-   python.analysis.indexing: undefined
-   python.analysis.typeCheckingMode: off

<h3> Expected behaviour </h3>

Can use `%kql`

<h3> Actual behaviour </h3>

Pylance puts errors everywhere.

![image](https://user-images.githubusercontent.com/8599/121452501-61ca0f00-c954-11eb-8959-84aec3895c80.png)

<h3> Code Snippet / Additional information </h3>

```python
%%kql RetainedByCohort <<
let cohortWindow = 7d;
```

**Comment by DonJayamanne** [comment] 2021-06-14 15:33
This isn't something we did in the past, hence not sure what you (@digitarald ) mean by stopped working?
@digitarald Pleaes could you provide the following info:
* Version of VS Code
* Version of Jupyter extension
*

**Comment by jakebailey** [comment] 2021-06-14 17:23
I think the confusing thing is why the KQL cell is being sent to Pylance at all...

**Comment by digitarald** [comment] 2021-06-14 18:41
> This isn't something we did in the past,

When I said it worked in the past I meant it worked before Pylance rolled out. Using Jedi works.

**Comment by DonJayamanne** [comment] 2021-06-21 18:43
>  think the confusing thing is why the KQL cell is being sent to Pylance at all...

thats because its a Python cell, `%kql` is a Python magic, meaning this code is executed in the Python kernel. 
Thats why my extension chagnes the language of the cell from `Python` to `Kql` so that we dont get Python language server getting messages for this cell.

**Comment by rchiodo** [comment] 2022-01-20 21:06
Dupe of #4588

**Closed by rchiodo** 2022-01-20 21:06 UTC
Labels: bug, notebook-intellisense, language-any, cell-magics
