### ISSUE TITLE
Autocomplete not working in the interactive python window

### ISSUE THREAD

**Issue by vlsd** [microsoft/vscode-jupyter#5345] opened 2021-03-29 17:23 UTC
## Environment data

-   VS Code version: 1.54.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.684299474
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS: macOS Big Sur 11.2.3
-   Python 3.9.1 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): none or `python3 -m venv`
-   Jupyter server running: Local

## Expected behaviour
Pressing the tab key in the python interactive window input should trigger an autocomplete action.

## Actual behaviour
A literal tab character is inserted

## Steps to reproduce:
1. create an `example.py` file in vscode
1. create one cell in the file, e.g.
```python
#%%
import os
```
1. click on "Run Cell"

**Comment by joyceerhl** [comment] 2021-03-29 20:41
@vlsd thanks for filing an issue. This sounds very similar to https://github.com/microsoft/vscode-jupyter/issues/1106. Are you looking for a keyboard shortcut to trigger autocomplete? If so, ctrl+space or cmd+space should do the trick for you. Please let me know if you're asking about something else.

**Comment by vlsd** [comment] 2021-03-30 14:25
I guess there are two questions here:
1. `TAB` is the standard trigger for autocomplete in just about every REPL out there, is there a way to bind it instead of of ctrl+space?
2. when I use ctrl+space, autocomplete almost always pops up empty and when it's not empty it's not what I would expect it to be; the main use of autocomplete in a REPL is for inspection and introspection, so I would expect it to autocomplete names of variables defined in the local scope as well as the names of attributes and methods belonging to objects in the local scope

My understanding from reading https://github.com/microsoft/vscode-jupyter/issues/3645 is that this was implemented in 2019, and my own memory was that I've used it in the past, which is I suspect there's been a recent regression.

**Comment by joyceerhl** [comment] 2021-04-01 16:23
@vlsd would you mind providing a code example that causes autocomplete to pop up empty? For example this is the list I get for `import os` and then `os.` in the interactive window:

![image](https://user-images.githubusercontent.com/30305945/113323496-dfc1c800-92ca-11eb-9d74-d59ee5849bed.png)


Based on https://github.com/microsoft/vscode-jupyter/issues/1106#issuecomment-728778657 I'm not sure we supported tab to autocomplete in the past. That being said we may be able to map tab to autocomplete in the interactive window input cell. Related: https://github.com/microsoft/monaco-editor/issues/685

**Comment by greazer** [comment] 2021-04-01 20:18
Thanks for the feedback! However, we don't have plans on changing this functionality. It's basically a dupe of #1106

**Comment by vlsd** [comment] 2021-04-01 20:29
I think there's been a misunderstanding. Autocomplete doesn't simply pop up for me, the only way to get it to engage is to press `ctrl+space`. When I do, this is what shows up, which is not exactly what one would expect:

![Screen Shot 2021-04-01 at 3 27 28 PM](https://user-images.githubusercontent.com/278058/113350320-ebc77d00-92fe-11eb-8c23-46c746cdbdb5.png)

**Comment by joyceerhl** [comment] 2021-04-01 20:41
That screenshot really helps. What language server are you using? The setting name is `python.languageServer` in your user settings.json.

**Comment by joyceerhl** [comment] 2021-04-01 20:43
Also, would you mind updating your VS Code build (latest is 1.55) and Jupyter extension (latest is v2021.5.702919634) and checking to see if the behavior above persists?

**Comment by vlsd** [comment] 2021-04-01 21:02
>What language server are you using? The setting name is python.languageServer in your user settings.json.
It's set to Jedi, which I believe is the default

>Also, would you mind updating your VS Code build (latest is 1.55) and Jupyter extension (latest is v2021.5.702919634) and checking to see if the behavior above persists?
Just did and yes, the behavior persists

**Comment by vlsd** [comment] 2021-04-07 21:51
I think I figured something out: sometimes the interactive python window will end up using a different path for python from my system than the one the rest of my IDE uses. Because the versions of the two pythons are often the same (e.g. one is 3.9.1 in a virtualenv, the other is 3.9.1 systemwide) it's hard to tell that there is any discrepancy. Once I switched to the same python path as the rest of my IDE autocomplete started working. I still don't understand why the interactive window picked the wrong version of python though.

**Comment by vlsd** [comment] 2021-04-26 19:06
I am able to replicate the issue pretty consistently by restarting the Jupyter kernel from the "restart kernel" icon. I'll update the original issue to reflect this.

**Comment by vlsd** [comment] 2021-04-26 19:09
I am still getting this every once in a while. I am not sure sure what causes it and how to force it to happen. When it does happen restarting the kernel is not enough, I have to fully close down the window and open a new one.

**Comment by greazer** [comment] 2021-06-06 17:31
Looks like a side-effect of #5041

**Comment by vlsd** [comment] 2021-06-07 14:19
> Looks like a side-effect of #5041

There might be more than one way this can happen. I've had it happen where the wrong kernel was running (which makes a lot of sense) and then selecting the right kernel fixed the issue, but I've also had it happen with the correct kernel running, where opening and closing the interactive session was the only thing that fixed the issue.

**Comment by greazer** [comment] 2021-09-02 20:35
We believe this has been fixed in the most recent release

**Closed by greazer** 2021-09-02 20:35 UTC
Labels: bug, intellisense, interactive-window, needs-triage
