### ISSUE TITLE
I want an option to disable all surveys

### ISSUE THREAD

**Issue by alexschlueter** [microsoft/vscode-jupyter#1700] opened 2020-10-12 07:59 UTC
## Environment data

-   VS Code version: 1.49.3
-   Extension version (available under the Extensions sidebar): 2020.9.114305
-   OS and version: Ubuntu 18.04

## Expected behaviour

There should be a setting to disable all surveys. On the "Python Data Science features" survey notification, there should be a button to never show a survey again.

## Actual behaviour

The "Python Data Science features" survey notification showed up without a button to disable surveys. A search in the settings revealed no setting to disable all surveys.

If every VSCode extension shows multiple different surveys without a way to disable them all, this editor is going to become cluttered very quickly.

## Steps to reproduce:

1. Use the python extension and wait for the survey notification

**Comment by marchmallow** [comment] 2020-11-24 15:16
> Theoretically once you dismiss the survey banner it won't show up again (hence the writing to the global.json). However the surveys don't share the same key. So even if you dismiss one, you may get asked for another.

In the jupyter notebook / data science environment this keeps coming up and it is so annoying.. even after actually responding and submitting the survey comes up continuosly... close to ditch VSC for this really..

**Comment by joyceerhl** [comment] 2020-11-24 16:52
Hi @marchmallow very sorry for the trouble. Are you seeing the same survey prompt appear multiple times? If so that would be a bug. 

Does clicking 'no' on the prompt stop it from reappearing, is it the same survey each time, and are you on the stable or insider version of VS Code?

**Comment by claudiaregio** [comment] 2020-11-24 17:29
@marchmallow Could you please provide a screenshot or text of the survey that keeps popping up? This seems like a bug and in order to troubleshoot it would be very helpful to have the specific survey, we will get this fixed up for you!

**Comment by DonJayamanne** [comment] 2020-11-24 19:16
This is most probably a dupe of https://github.com/microsoft/vscode-jupyter/issues/4002

**Comment by DonJayamanne** [comment] 2020-11-24 19:17
@marchmallow 
Please could you provide a screenshot of the prompt or provide the exact message displayed.
I believe we have you are experiencing the same issue reported here #4002

**Comment by surajx** [comment] 2020-11-25 00:40
Execution of any cell in a Jupyter notebook triggers the survey notification.
![Peek 2020-11-25 11-37](https://user-images.githubusercontent.com/925885/100167369-fb7b2300-2f12-11eb-82e8-65c62699645b.gif)

**Comment by claudiaregio** [comment] 2020-11-25 01:08
@surajx Thanks for the additional info, we believe to have found the bug. Fix coming soon!

**Comment by Schachte** [comment] 2020-11-27 18:58
Confirming survey pops up any time I do something, irrespective of filling out survey or hitting no thanks. Specifically using Jupyter in this instance.

**Closed** 2020-12-16 18:46 UTC
Labels: bug, info-needed

**Comment by marchmallow** [comment] 2021-01-11 00:28
> @marchmallow Could you please provide a screenshot or text of the survey that keeps popping up? This seems like a bug and in order to troubleshoot it would be very helpful to have the specific survey, we will get this fixed up for you!

Sorry I was very busy back in November and seen the question only now.. it has stopped now so I think can confirm bug fixed
