### ISSUE TITLE
Randomly delayed cell execution when pressing "Run cell" or "Shift-Enter"

### ISSUE THREAD

**Issue by ogrisel** [microsoft/vscode-jupyter#10760] opened 2022-07-11 10:14 UTC
## Environment data

```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-15T02:58:26.441Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.15.0-40-generic snap
```

-   Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001601848
-   Python Extension version (available under the Extensions sidebar): v2022.10.0
-   Python and/or Anaconda version: 3.10.5 from conda-forge
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda / mamba
-   Jupyter server running: Local
    - ipython 8.4.0
    - ipykernel 6.15.0
    - notebook 6.4.12
    - jupyterlab 3.4.3

## Expected behaviour

Jupyter side panel is updated with the new input code as soon as "Run cell" is clicked on (irrespective of the duration of the actual cell execution that happens afterwards).

## Actual behaviour

The side panel is sometimes updated straight away but sometimes it only shows-up after a few seconds, sometimes more than 10s.

It can happen for cell of any computational complexity: the lag seems to happen even before the actual Python code gets executed.

## Logs

When this happens, the "Jupyter" output log typically looks like the following:

```
info 11:54:39.476: Generated code for 106 = <ipython-input-106-8988a1a28d7e> with 3 lines
info 11:54:39.513: Cell 121 executed with state Success
info 11:54:40.450: Generated code for 107 = <ipython-input-107-3971efcb5a20> with 9 lines
info 11:54:40.560: Cell 122 executed with state Success
info 11:54:41.669: Generated code for 108 = <ipython-input-108-b1e4e560596e> with 33 lines
info 11:54:41.717: Cell 123 executed with state Success
[W 11:54:45.711 NotebookApp] 404 GET /json/list (127.0.0.1) 1.010000ms referer=None
[W 11:54:45.764 NotebookApp] 404 GET /json/list (127.0.0.1) 0.940000ms referer=None
[W 11:54:45.817 NotebookApp] 404 GET /json/list (127.0.0.1) 1.300000ms referer=None
[W 11:54:45.870 NotebookApp] 404 GET /json/list (127.0.0.1) 1.010000ms referer=None
[W 11:54:45.923 NotebookApp] 404 GET /json/list (127.0.0.1) 0.970000ms referer=None
[W 11:54:45.976 NotebookApp] 404 GET /json/list (127.0.0.1) 0.970000ms referer=None
[W 11:54:46.029 NotebookApp] 404 GET /json/list (127.0.0.1) 0.930000ms referer=None
[W 11:54:46.082 NotebookApp] 404 GET /json/list (127.0.0.1) 1.090000ms referer=None
[W 11:54:46.135 NotebookApp] 404 GET /json/list (127.0.0.1) 0.980000ms referer=None
[W 11:54:46.188 NotebookApp] 404 GET /json/list (127.0.0.1) 1.000000ms referer=None
info 11:55:2.117: Generated code for 109 = <ipython-input-109-a58758cd24dc> with 2 lines
info 11:55:2.194: Cell 124 executed with state Success
info 11:55:2.194: Generated code for 110 = <ipython-input-110-1d61657f6131> with 3 lines
info 11:55:4.91: Cell 125 executed with state Success
info 11:55:4.91: Generated code for 111 = <ipython-input-111-7c3052c3c00f> with 3 lines
info 11:55:5.840: Cell 126 executed with state Success
info 11:55:5.840: Generated code for 112 = <ipython-input-112-3c4bf76476e3> with 3 lines
info 11:55:8.539: Cell 127 executed with state Success
info 11:55:8.540: Generated code for 113 = <ipython-input-113-b49d07f03ca0> with 3 lines
info 11:55:11.381: Cell 128 executed with state Success
info 11:55:11.381: Generated code for 114 = <ipython-input-114-9b3709a5b6dc> with 3 lines
info 11:55:14.57: Cell 129 executed with state Success
info 11:55:14.58: Generated code for 115 = <ipython-input-115-a58758cd24dc> with 2 lines
info 11:55:14.85: Cell 130 executed with state Success
info 11:55:14.85: Generated code for 116 = <ipython-input-116-a58758cd24dc> with 2 lines
info 11:55:14.178: Cell 131 executed with state Success
```

The `info` lines before the `W` lines match "Run cells" events that were executed instantly (no delay). Then the following "Run cells" even were blocked and after a few seconds of delay the `W` lines with the 404 errors show up and the execution resumed with the `info` lines.

## Steps to reproduce:

I can try to edit a minimal reproducer file that triggers the problem if that's helpful.

**Comment by ogrisel** [comment] 2022-07-11 10:14
Might be related to https://github.com/microsoft/vscode-jupyter/issues/8320

**Comment by ogrisel** [comment] 2022-07-11 11:49
I have been trying to craft a minimal reproducer but now I cannot even reproduce it in my original Python file. This is weird because the problem would occur randomly but quite frequently previously. I don't think I have changed much in my environment or the file itself.

**Comment by ogrisel** [comment] 2022-07-11 12:28
It seems that I can only trigger the problem when editing cells. Note just executing the existing cells of the file without changing the file.

I might also be related to hovering code symbols of the source file with the mouse that triggers:

```
info 14:25:38.352: Executing silently Code (idle) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
info 14:25:38.370: Executing silently Code (completed) = import builtins\n_rwho_ls = %who_ls\nbuiltins.print(_VSCODE_getVariableTypes(_rwho_ls))
```

in the Jupyter log output, possibly during the execution of a long running cell. However I am not 100% sure because I have still found a sequence of interactions with VS Code that can trigger the problem deterministically.

**Comment by ogrisel** [comment] 2022-07-11 16:10
One more observation: when this happens, the blue focus on a cell being clicked is not updated either.

**Comment by DonJayamanne** [comment] 2022-07-11 17:37
When you run into this, please could you upload all of the output from the `Jupyter` output panel (you can get there using the `Jupyter: Show Output` command).
As this seems to be spcific to performance, please could you enable `verbose` logging as follows:
* Open your user settings.json file
* Add the following & reload VS Code
```jsonc
"jupyter.logging.level": "verbose",
```

**Comment by DonJayamanne** [comment] 2022-07-11 18:22
@ogrisel 
this looks like a duplicate of https://github.com/microsoft/vscode-jupyter/issues/10736
Please provide the feedback on that issue (i.e. the logs)

**Closed by DonJayamanne** 2022-07-11 18:22 UTC
Labels: bug, info-needed, perf, interactive-window, triage-needed
