### ISSUE TITLE
Can't open notebook after upgrade

### ISSUE THREAD

**Issue by shug1565** [microsoft/vscode-jupyter#5990] opened 2021-05-26 12:53 UTC
Issue Type: <b>Bug</b>

Hi, I can't open my notebooks after the update of the vscode insider, which were perfectly fine just minutes ago. The error message I got is "INVALID mime type, must not be empty or falsy".

Extension version: 2021.6.870847776
VS Code version: Code - Insiders 1.57.0-insider (a18ea9c9ec25c59e599ba3c2eb668315546dd269, 2021-05-26T05:14:06.346Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz (24 x 2007)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.52GB free)|
|Process Argv|--crash-reporter-id 717eb2b4-1f36-481a-a450-8f77d9e8959c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833cf:30267465
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30286553
pythonvsuse255:30303025
vscgsv2:30305091
vscorehov:30301224
vscod805:30301674

```

</details>

**Comment by rchiodo** [comment] 2021-05-26 16:02
Dupe of #5989

**Closed by rchiodo** 2021-05-26 16:02 UTC
