### ISSUE TITLE
Width of displayed data frames

### ISSUE THREAD

**Issue by moritzwilksch** [microsoft/vscode-jupyter#6229] opened 2021-06-09 18:43 UTC
In **VSCode Insiders**, small (i.e. small-width) data frames are stretched to fill the screen:
![image](https://user-images.githubusercontent.com/58488209/121404248-0f8cec00-c95c-11eb-9494-af153a260155.png)

the behavior in the stable VSCode release is more legible:

![image](https://user-images.githubusercontent.com/58488209/121410163-98a72180-c962-11eb-8a55-f97a96202eb7.png)

I think for such small data frames the display style should be more "condensed" for legibility, with column width determined by cell content, not window width.

**Comment by rchiodo** [comment] 2021-06-09 19:27
Thanks for the bug. This is a dupe of #https://github.com/microsoft/vscode/issues/125299

**Closed by rchiodo** 2021-06-09 19:27 UTC
Labels: enhancement
