### ISSUE TITLE
Interactive window autocomplete doesn't work until at least one cell is executed

### ISSUE THREAD

**Issue by oakstreetrec** [microsoft/vscode-jupyter#14680] opened 2023-11-07 22:26 UTC
## Environment data

-   VS Code version: 1.84.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1003070148
-   Python Extension version (available under the Extensions sidebar): v2023.20.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10 and 11
-   Python and/or Anaconda version: 3.9.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Behaviour

It seems that whenever I open up an interactive window to run some python code, autocomplete doesn't work in the code entry field at the bottom of the interactive window until I execute at least one line of code. It can be anything - I usually just type "1" and execute that. Afterwards, autocomplete works fine.

**Comment by DonJayamanne** [comment] 2023-12-01 04:18
@amunger Looks like the IW input cell does not have a languaeg setup until a cell is executed.
As a result there's no code completion.
I cannot tell wherer the language id for the input box editor is setup, but I can install an extension like `Doc View`  to figure this out.

**Comment by amunger** [comment] 2024-11-21 23:56
duplicate of https://github.com/microsoft/vscode-jupyter/issues/13782

**Closed by amunger** 2024-11-21 23:56 UTC
Labels: bug, interactive-window
