### ISSUE TITLE
Ignore Further Scrolling at Scrollable Element's Top or Bottom

### ISSUE THREAD

**Issue by yuji96** [microsoft/vscode-jupyter#14628] opened 2023-10-31 15:53 UTC
I think that when a scrollable element reaches the top or bottom, any further scrolling should be ignored.

The scrollable element is generally used for very long output, so users do not know how far it will go. So, as in the video, the end of the element suddenly appears and the viewing point is unexpectedly skipped over.

https://github.com/microsoft/vscode-jupyter/assets/51022522/db12a200-26c5-40d1-8901-2cd96ad182e2

**Comment by amunger** [comment] 2023-12-08 21:58
closing as duplicate of https://github.com/microsoft/vscode/issues/174913

**Closed by amunger** 2023-12-08 21:58 UTC
Labels: notebook-output, feature-request
