### ISSUE TITLE
Unresolved ipykernel installation - codespaces

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#4244] opened 2020-12-16 18:28 UTC
Testing [Codespace Scenario: 1791](https://github.com/microsoft/vssaas-planning/issues/1791)

## Environment data

-   VS Code version: 1.52.0-insider (Codespace)
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.1
-   Python Extension version (available under the Extensions sidebar): 2020.11.2
-   OS (Windows | Mac | Linux distro) and version: Linux Codespace
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

1. Open a Notebook (old webview) with a Python environment missing ipykernel.
2. Use the ipykernel install prompt.
3. ipykernel installed.

## Actual behaviour

The ipykernel installation never concluded. The indeterminate loader is shown to the user with no other progress indication about the installation:

![image](https://user-images.githubusercontent.com/6413608/102390550-63101580-3f89-11eb-8402-ef4200697945.png)

**Comment by SiddhanthUnnithan** [comment] 2020-12-16 18:29
I'm curious if we have data around the number of users that install the ipykernel and then subsequently hit "Cancel". The lack of progress was frustrating and prompted me to cancel the operation myself (after letting it run for > 10 minutes).

**Comment by IanMatthewHuff** [comment] 2020-12-17 19:46
Maybe it was erroring out earlier than expected? We use the core python extension for installation. And when you install a package it usually opens up the terminal window and you see the pip or conda install output spew.

**Comment by joyceerhl** [comment] 2021-01-05 21:43
Unfortunately I can't repro this after following the setup described in Codespace scenario 1791. @SiddhanthUnnithan would you mind dropping the logs below when you have the time?

<img width="1279" alt="Screen Shot 2021-01-05 at 1 42 06 PM" src="https://user-images.githubusercontent.com/30305945/103703128-dccd6a80-4f5b-11eb-9b6a-a5635ea061d6.png">

**Comment by SiddhanthUnnithan** [comment] 2021-01-22 21:25
Hey @joyceerhl revisiting this today - I'm still unable to run a cell and connect to a conda environment. I see two different behaviours based off of the environment I'm trying to connect to:

1. [newly created environment - 'codespaces'] When running a cell this is the output that I see:

![image](https://user-images.githubusercontent.com/6413608/105549079-5633bf80-5cb5-11eb-936d-7b816e648e47.png)

2. [base conda environment] I'm prompted to install the ipykernel

![image](https://user-images.githubusercontent.com/6413608/105548825-fdfcbd80-5cb4-11eb-886c-59885f602670.png)

After clicking 'Install' I see the following:

![image](https://user-images.githubusercontent.com/6413608/105548898-18369b80-5cb5-11eb-97b6-f1c336be8b46.png)

Looks like a permissions issue - is there a way to run the install command through a different user?

**Comment by SiddhanthUnnithan** [comment] 2021-01-22 21:27
Adding the logs from the Jupyter Output pane here:

Error 2021-01-22 21:26:59: Install Missing Dependencies, Class name = f, completed in 239ms, has a falsy return value, Return Value: undefined Error: Command failed: . activate codespace && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: ". activate codespace && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py",
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
Error 2021-01-22 21:26:59: Find kernel spec, Class name = I, completed in 433ms, has a falsy return value, Arg 1: <Uri:/home/codespace/workspace/pet-detector-pytorch/Untitled-6.ipynb>, Arg 2: {"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":3},"orig_nbformat":2}, Arg 3: undefined, Arg 4: undefined, Return Value: undefined Error: Command failed: . activate codespace && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: ". activate codespace && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py",
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
Error 2021-01-22 21:26:59: Exception attempting to start notebook:  Error: Command failed: . activate codespace && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: ". activate codespace && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py",
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
Error 2021-01-22 21:26:59: DataScience Error Error: Command failed: . activate codespace && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: ". activate codespace && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py",
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}

This is for the first environment above ^

**Comment by joyceerhl** [comment] 2021-01-22 23:50
Thanks @SiddhanthUnnithan I can repro both issues you described in your latest comment. Both seem to be related to conda setup:
1. With the new env you created, the activation command that the Python extension is providing to activate the environment does not work. If you instead run `conda activate codespace && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py"` in your shell, that should correctly print the right environment variables. /cc @karthiknadig @karrtikr 
2. The base env appears to be being created with the wrong permissions. To get to the bottom of this one we would need to figure out how this codespace's conda install is being configured. Otherwise the base conda environment is just going to be broken on Ubuntu codespaces.

AFAIK the root causes of those issues are not in the Jupyter extension, but they would be blockers for Jupyter users with conda on Codespaces.

**Comment by SiddhanthUnnithan** [comment] 2021-01-29 22:31
Running the command directly in the terminal didn't seem to work. I tried isolating just activating the conda env but got the following:

![image](https://user-images.githubusercontent.com/6413608/106333598-d6ba6900-623d-11eb-982a-933b25d819cb.png)

I ran the init command and restarted the shell but now running "conda activate codespace" didn't do anything:
![image](https://user-images.githubusercontent.com/6413608/106333869-67914480-623e-11eb-9f64-4db217f18f13.png)

Seeing the same issue when running the full command:
![image](https://user-images.githubusercontent.com/6413608/106334008-a6bf9580-623e-11eb-8f81-b8a08469cbd2.png)

**Comment by DonJayamanne** [comment] 2021-02-01 21:35
If after you run `conda init` & then `conda actiavte codespace` the terminal still doesn't actiavte `codespace`, then this seems to be an issue with `conda` or the way it is setup on codepaces.
I agree with @joyceerhl.
Do we know who owns the creation/setup of conda on codespaces? Perhaps we can discuss this in Triage?

**Comment by rchiodo** [comment] 2021-02-18 00:35
Moving back to triage

**Comment by greazer** [comment] 2021-02-18 21:47
@luabud, we don't want to forget about this. We think you were tracking environment installation on codespaces. We need to make sure notebooks work in that environment.

**Comment by luabud** [comment] 2021-02-19 18:55
@SiddhanthUnnithan  after you do `conda activate`, can you do python -c "import sys; print(sys.executable)"? I think it did activate the environment, it just didn't change the prompt. 
The VS Code team made a fix for showing **(venv)**  in the terminal when virtual environments are activated. I assumed it would apply for conda too but I guess it didn't.

**Comment by DonJayamanne** [comment] 2021-03-11 02:58
Related upstream issue https://github.com/microsoft/vscode-python/issues/15632

**Comment by DonJayamanne** [comment] 2022-02-21 18:50
Closing this to ensure this gets validated.

**Closed by DonJayamanne** 2022-02-21 18:50 UTC
Labels: bug, notebook-kernel, notebook-codespaces

**Comment by roblourens** [comment] 2022-02-25 02:38
I followed the steps in the linked scenario. On the first run, it installed ipykernel successfully, then failed with this error: `Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory`

I ran the cell a second time and it worked.

Logs through the first run:
```
Visual Studio Code - Insiders (1.65.0-insider, codespaces, codespaces)
Jupyter Extension Version: 2022.2.1010561006.
Python Extension Version: 2022.0.1814523869.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 02:29:47: ZMQ install verified.
Info 02:29:47: Preferred kernel connection found in cache .jvsc74a57bd0b335d4ab9f83d94a1b1485e57f1e59dc63012606dacb0589d17d87ae595d36f9./workspaces/pet-detector-pytorch/.venv/python./workspaces/pet-detector-pytorch/.venv/python.-m#ipykernel_launcher
Info 02:29:47: PreferredConnection: .jvsc74a57bd0b335d4ab9f83d94a1b1485e57f1e59dc63012606dacb0589d17d87ae595d36f9./workspaces/pet-detector-pytorch/.venv/python./workspaces/pet-detector-pytorch/.venv/python.-m#ipykernel_launcher found for NotebookDocument: /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:29:47: Early registration of controller for Kernel connection .jvsc74a57bd0b335d4ab9f83d94a1b1485e57f1e59dc63012606dacb0589d17d87ae595d36f9./workspaces/pet-detector-pytorch/.venv/python./workspaces/pet-detector-pytorch/.venv/python.-m#ipykernel_launcher
Info 02:29:47: TargetController found ID: .jvsc74a57bd0b335d4ab9f83d94a1b1485e57f1e59dc63012606dacb0589d17d87ae595d36f9./workspaces/pet-detector-pytorch/.venv/python./workspaces/pet-detector-pytorch/.venv/python.-m#ipykernel_launcher for document /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:29:47: Setting controller affinity for /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb .jvsc74a57bd0b335d4ab9f83d94a1b1485e57f1e59dc63012606dacb0589d17d87ae595d36f9./workspaces/pet-detector-pytorch/.venv/python./workspaces/pet-detector-pytorch/.venv/python.-m#ipykernel_launcher
Info 02:29:48: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 02:29:48: Interrupt requested & no kernel.
Info 02:29:48: Setting setActiveController for /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:29:48: KernelProvider switched kernel to id = .jvsc74a57bd0bfa0f66713fee4ab7f51ed754b195945217dae473cb7daa55d29bf264519dc1b./home/codespace/.conda/envs/petdpytorch/python./home/codespace/.conda/envs/petdpytorch/python.-m#ipykernel_launcher
Info 02:29:48: Starting Notebook in kernel.ts id = .jvsc74a57bd0bfa0f66713fee4ab7f51ed754b195945217dae473cb7daa55d29bf264519dc1b./home/codespace/.conda/envs/petdpytorch/python./home/codespace/.conda/envs/petdpytorch/python.-m#ipykernel_launcher
Info 02:29:48: Creating raw notebook for /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:29:48: Getting preferred kernel for /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:29:48: Computing working directory /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:29:48: Starting raw kernel petdpytorch (Python 3.7.11)
Info 02:29:48: installMissingDependencies ~/.conda/envs/petdpytorch/bin/python
Info 02:29:52: Got activated conda env vars ourselves for ~/.conda/envs/petdpytorch/bin/python in 3484
Info 02:29:52: Process Execution: > ~/.conda/envs/petdpytorch/bin/python -m pip list
> ~/.conda/envs/petdpytorch/bin/python -m pip list
Info 02:29:52: Process Execution: > ~/.conda/envs/petdpytorch/bin/python -c "import ipykernel"
> ~/.conda/envs/petdpytorch/bin/python -c "import ipykernel"
Error 02:29:52: IPykernel not detected
Error 02:29:52: Install Missing Dependencies, Class name = T, completed in 3750ms, has a falsy return value, Return Value: undefined o [Error]: IPyKernel not installed into interpreter Python 3.7.11 ('petdpytorch'):~/.conda/envs/petdpytorch/bin/python
    at T.handleKernelDependencyResponse (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:723895)
    at T.installMissingDependencies (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:721917) {
  category: 'noipykernel',
  reason: 4,
  anotherKernelSelected: false,
  firstQueuedCell: undefined
}
Error 02:29:52: Raw session failed to start because dependencies not installed
Error 02:29:52: failed to create INotebook in kernel, UI Disabled = true o [Error]: IPyKernel not installed into interpreter Python 3.7.11 ('petdpytorch'):~/.conda/envs/petdpytorch/bin/python
    at T.handleKernelDependencyResponse (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:723895)
    at T.installMissingDependencies (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:721917) {
  category: 'noipykernel',
  reason: 4,
  anotherKernelSelected: false,
  firstQueuedCell: undefined,
  vslsStack: [ CallSite {}, CallSite {} ]
}
Error 02:29:52: failed to start INotebook in kernel, UI Disabled = true o [Error]: IPyKernel not installed into interpreter Python 3.7.11 ('petdpytorch'):~/.conda/envs/petdpytorch/bin/python
    at T.handleKernelDependencyResponse (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:723895)
    at T.installMissingDependencies (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:721917) {
  category: 'noipykernel',
  reason: 4,
  anotherKernelSelected: false,
  firstQueuedCell: undefined,
  vslsStack: [ CallSite {}, CallSite {} ]
}
Info 02:29:52: Creating controller for jupyter-notebook with interpreter /workspaces/pet-detector-pytorch/.venv/bin/python
Info 02:29:52: Registering dummy command feature
Info 02:29:52: Process Execution: > /workspaces/pet-detector-pytorch/.venv/bin/python -m pip list
> /workspaces/pet-detector-pytorch/.venv/bin/python -m pip list
Info 02:29:52: Registering dummy command feature
Error 02:29:53: Failed to get activated conda env variables for ~/.conda/envs/petdpytorch/bin/python
Error 02:29:53: Failed to get activated conda env variables for ~/.conda/envs/petdpytorch/bin/python
Info 02:35:21: Execute Cells request 1
Info 02:35:21: Execute Cell 1 /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:35:21: Starting Notebook in kernel.ts id = .jvsc74a57bd0bfa0f66713fee4ab7f51ed754b195945217dae473cb7daa55d29bf264519dc1b./home/codespace/.conda/envs/petdpytorch/python./home/codespace/.conda/envs/petdpytorch/python.-m#ipykernel_launcher
Info 02:35:21: Creating raw notebook for /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:35:21: Getting preferred kernel for /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:35:21: Computing working directory /workspaces/pet-detector-pytorch/PetDetectorTraining.ipynb
Info 02:35:21: Starting raw kernel petdpytorch (Python 3.7.11)
Info 02:35:21: installMissingDependencies ~/.conda/envs/petdpytorch/bin/python
Info 02:35:21: Process Execution: > ~/.conda/envs/petdpytorch/bin/python -c "import ipykernel"
> ~/.conda/envs/petdpytorch/bin/python -c "import ipykernel"
Info 02:35:21: Got result from python installer for ipykernel, result = 2
Info 02:35:21: Process Execution: > ~/.conda/envs/petdpytorch/bin/python -m pip list
> ~/.conda/envs/petdpytorch/bin/python -m pip list
Error 02:35:21: Failed to get activated conda env variables for ~/.conda/envs/petdpytorch/bin/python
Error 02:35:21: Failed to get activated conda env variables for ~/.conda/envs/petdpytorch/bin/python
Error 02:35:45: Installing Product, Class name = P, completed in 24518ms, has a falsy return value, Arg 1: 19, Arg 2: {"sysPrefix":"/home/codespace/.conda/envs/petdpytorch","envType":"Conda","envName":"petdpytorch","envPath":"/home/codespace/.conda/envs/petdpytorch","path":"/home/codespace/.conda/envs/petdpytorch/bin/python","architecture":3,"sysVersion":"3.7.11 (default, Jul 27 2021, 14:32:16) \n[GCC 7.5.0]","version":{"raw":"3.7.11","major":3,"minor":7,"patch":11,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.7.11 ('petdpytorch')","detailedDisplayName":"Python 3.7.11 ('petdpytorch': conda)"}, Arg 3: {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"element":{"subscription":{}},"next":{},"prev":{}},"_last":{"element":{"subscription":{}},"next":{},"prev":{}},"_size":1}}}, Arg 4: false, Arg 5: false Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: ". activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py",
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
Error 02:35:45: Failed to install ipykernel Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: ". activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py",
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
Error 02:35:45: Install Missing Dependencies, Class name = T, completed in 24667ms, has a falsy return value, Return Value: undefined Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: ". activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py",
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
Error 02:35:45: Failed to connect raw kernel session: Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

Error 02:35:45: failed to create INotebook in kernel, UI Disabled = false Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: ". activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py",
  vslsStack: [
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {},
    CallSite {}
  ]
}
Warn 02:35:45: Kernel Error o [Error]: 
    at new o (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:82421)
    at Function.from (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:82511)
    at /home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:699032

Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  category: 'unknown',
  originalException: Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
  bash: activate: No such file or directory
  
      at ChildProcess.exithandler (node:child_process:397:12)
      at ChildProcess.emit (node:events:394:28)
      at maybeClose (node:internal/child_process:1064:16)
      at Socket.<anonymous> (node:internal/child_process:450:11)
      at Socket.emit (node:events:394:28)
      at Pipe.<anonymous> (node:net:672:12) {
    killed: false,
    code: 1,
    signal: null,
    cmd: ". activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py",
    vslsStack: [
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {}
    ]
  }
}
Error 02:35:45: failed to start INotebook in kernel, UI Disabled = false o [Error]: 
    at new o (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:82421)
    at Function.from (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:82511)
    at /home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:699032

Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  category: 'unknown',
  originalException: Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
  bash: activate: No such file or directory
  
      at ChildProcess.exithandler (node:child_process:397:12)
      at ChildProcess.emit (node:events:394:28)
      at maybeClose (node:internal/child_process:1064:16)
      at Socket.<anonymous> (node:internal/child_process:450:11)
      at Socket.emit (node:events:394:28)
      at Pipe.<anonymous> (node:net:672:12) {
    killed: false,
    code: 1,
    signal: null,
    cmd: ". activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py",
    vslsStack: [
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {}
    ]
  }
}
Error 02:35:45: Failed to execute cells in CellExecutionQueue o [Error]: 
    at new o (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:82421)
    at Function.from (/home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:82511)
    at /home/codespace/.vscode-remote/extensions/ms-toolsai.jupyter-2022.2.1010561006/out/client/extension.js:2:699032

Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
bash: activate: No such file or directory

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:394:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:394:28)
    at Pipe.<anonymous> (node:net:672:12) {
  category: 'unknown',
  originalException: Error: Command failed: . activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py
  bash: activate: No such file or directory
  
      at ChildProcess.exithandler (node:child_process:397:12)
      at ChildProcess.emit (node:events:394:28)
      at maybeClose (node:internal/child_process:1064:16)
      at Socket.<anonymous> (node:internal/child_process:450:11)
      at Socket.emit (node:events:394:28)
      at Pipe.<anonymous> (node:net:672:12) {
    killed: false,
    code: 1,
    signal: null,
    cmd: ". activate petdpytorch && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/codespace/.vscode-remote/extensions/ms-python.python-2022.0.1814523869/pythonFiles/printEnvVariables.py",
    vslsStack: [
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {},
      CallSite {}
    ]
  }
}
Info 02:35:45: Cancel pending cells
Info 02:35:45: Cell 1 executed with state Idle
```
