### ISSUE TITLE
No feedback when specifying a remote kernel

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#8818] opened 2022-01-26 19:48 UTC
Testing #8778

After specifying a remote kernel, I kept opening the kernel picker and not seeing any available remote kernels. I didn't know whether VS Code could not connect to the kernel, or if there was a problem on the kernel side, and there are a lot of logs in the `Jupyter` output channel, I didn't know what to look for. I had to repeat the copy-pasting step a couple of times (alternating between the `localhost` and `127.0.0.1` addresses) for the remote kernels to eventually appear.

It would also be nice if there was an option to specify a remote kernel in the kernel picker.

**Comment by DonJayamanne** [comment] 2022-01-26 20:59
> It would also be nice if there was an option to specify a remote kernel in the kernel picker.

Yup another issue for better UX for Kernel Picker + specifying remote jupyter servers 
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/8797#issuecomment-1022509906

**Closed by DonJayamanne** 2022-01-26 20:59 UTC
Labels: needs-triage
