### ISSUE TITLE
npm install hangs when trying to build vsix plugin from scratch

### ISSUE THREAD

**Issue by SDawley** [microsoft/vscode-jupyter#13260] opened 2023-04-03 22:58 UTC
I checked but couldn't find an existing issue relating to building the plugin.

## Environment data

-   Jupyter Extension version: tested at the latest revision, 2023.02.100, 2022.09.120, 2023.03.100
-   OS: Tested on Fedora 35, RHEL 8.7, RHEL 9.1
-   Python and/or Anaconda version: Tested with both 3.6 and 3.8
-   Type of virtual environment used: tested locally and using dockerfiles so I could test other operating systems
- npm version: Tested with 6.14.15, 8.15.1, latest
- node version: 14.21.1, 16.18.1, 18.12.1

I recognize that the contributing guide explicitly lists node.js 16.14.2 and npm 8.15.1 but I eventually hit a point where I was just trying various combinations that I had available to see if anything worked.

## Expected behavior

npm install runs to completion and installs the required dependencies.

## Actual behavior

Personally, npm runs to about core-js@2.6.12 before stopping, I've asked several co-workers to verify the issue before posting this and all also saw npm install stall. 

## Steps to reproduce:

For an exact list of the steps I'm taking I actually have a Dockerfile checked into [my fork  of redhat-developer/devspaces-vscode-extensions](https://github.com/SDawley/devspaces-vscode-extensions/blob/4049_chaos/ms-toolsai.jupyter/Dockerfile) 

1. Run in a clean environment that has not built vscode-jupyter before. I've been using [registry.access.redhat.com/ubi8/nodejs-16:1-90 ](https://catalog.redhat.com/software/containers/ubi8/nodejs-16/615aee9fc739c0a4123a87e1) or locally my os is Fedora 35.
2. Build and install cmake since [prebuilt zeromq binaries](https://github.com/zeromq/zeromq.js#prebuilt-binaries) are not available.
3. Install npm 8.15.1
6. Clone vscode-jupyter and cd into the folder
7. Run npm install and wait

## Logs

Running npm install -verbose
![image](https://user-images.githubusercontent.com/88796121/229643911-8dd67869-110b-40d0-a30e-a515a48e0277.png)

bufferutil is 4.0.7 in the image because bufferutil and utf-8-validate seem to be the ones that never download (zeromqold takes a LONG time but it does eventually complete) so I'm testing different versions and will update this issue if one of them works...

**Comment by amunger** [comment] 2023-04-04 16:25
@DonJayamanne is currently making some big changes around the zeromq dependency, so hopefully that part will improve. I don't think anyone on the team develops with RHEL though, so it may be difficult to help troubleshoot this.

**Comment by debonte** [comment] 2023-04-04 17:44
I'm hitting this on Ubuntu 22.04.2 LTS with node 16.19.1 and npm 8.19.3.

Here's my npm log after I gave up and pressed Ctrl-C after 2 hours.

[2023-04-04T15_21_39_487Z-debug-0.log](https://github.com/microsoft/vscode-jupyter/files/11151374/2023-04-04T15_21_39_487Z-debug-0.log)

**Comment by RomanNikitenko** [comment] 2023-04-04 18:03
I faced the same problem on macOS with node 16.17.0 and npm 9.6.3.

**Comment by DonJayamanne** [comment] 2023-04-04 20:05
Plase use node 16.14.2 and npm 8.15.1

**Comment by SDawley** [comment] 2023-04-05 01:00
I downloaded and installed node 16.14.2 specifically and am having the same issue, but I will leave it running overnight to see what happens.
I tried running with `--ignore-scripts` and the npm install succeeded quickly but zeromq didn't get built so it threw an error when I tried to build the vsix file.

**Comment by DonJayamanne** [comment] 2023-04-05 01:53
>  but I will leave it running overnight to see what happens.

Looks like some dependencies are missing on your machine or the like, most of us aren't running into this and our CI servers are aloso fine. meaning its a dependency issue

>  zeromq didn't get built so it threw an error when I tried to build the vsix file.

You'd need to install the dependencies required for [zeromq.js](https://www.npmjs.com/package/zeromq) (you might want to check out that npm package to figure out what the dependencies are for that npm package)

**Comment by SDawley** [comment] 2023-04-05 14:58
As I said in the issue report, I checked the zeromq dependencies and built and installed cmake so that it could be built during the npm install. I was merely pointing out that `--ignore-scripts` did not fix the issue.

Zeromq specifially requires libstdc++.so.6.0.21+ (glibc++ 3.4.21+) to install the prebuilt binaries, but I'd found a workaround for that one already because it actually errored.

It's bufferutil and utf-8-validate that hang indefinitely.
They don't seem to have a contributing guide or installation dependencies listed in the readme so it would be guesswork on my end.

Is it possible that the dev team hasn't run into this problem because they've had these dependencies cached for a while? I noticed that the ci build in this repo also runs using `--prefer-offline` and uses a cache: `[Cache restored successfully](https://github.com/microsoft/vscode-jupyter/actions/runs/4619539796/jobs/8168422468#step:7:41)`

Would anyone be willing to test or verify the issue on a new environment, a container or hide the npm cache and install fresh?

**Comment by amunger** [comment] 2023-04-05 21:24
could not repro on a fresh WSL environment

**Comment by filiptronicek** [comment] 2023-04-12 16:21
We have been experiencing this issue for a while now when building the extension from within GitHub Actions [[1](https://github.com/open-vsx/publish-extensions/actions/runs/4674255189/jobs/8278274720#step:9:5030)].

**Comment by DonJayamanne** [comment] 2023-04-17 19:21
I'm sorry you are running into this, (as you can see from our repo) we too are using GitHub Actions quite heavily and aren't running into this.
Please could you help us determine the cause
Tips
* Perhaps shed a few packages from the package.json or package-lock.json file and see when thins start working
*

**Comment by filiptronicek** [comment] 2023-04-17 22:09
Hello there @DonJayamanne 👋. First off, wanted to say: thanks so much for well... caring!

It indeed seems that this is a problem not reproducible everywhere. To explain what I have tried so far:
- I have tried installing on my local M1 MacBook: it seemingly hangs after `> node-gyp-build` at `(##################) ⠙ reify:office-ui-fabric-react: timing reifyNode:node_modules/rxjs Completed in 16017ms`
- I have tried it inside of Gitpod: same as my Mac
- I have tried the devcontainer inside Codespaces: the container failed to build and I sadly couldn't get to running the command
- I have made a new repo, https://github.com/filiptronicek/test-jupyter-actions, and ran the compilation with Actions, and there, [it succeeded](https://github.com/filiptronicek/test-jupyter-actions/actions/runs/4725715939) (what?! 😄) 

I am really puzzled as to what exactly is the culprit.

**Comment by SDawley** [comment] 2023-08-04 20:52
Just to update, I did find a method that works for me locally. It only works for the latest version though (2023.8.100).

Steps:
- Use nodejs 14 / npm 6.14.1
- `npm install` (runs without failing, don't need --ignore-scripts)
- Switch to nodejs 16 / npm 8.19.4
- Install missing packages (@types/vscode, react-is, crypto)
-  `npm run package`

**Comment by DonJayamanne** [comment] 2023-11-03 00:20
FYI = Please try the latest version of node and npm
We have updated contrib guides to use Node 18.15.0 and npm 9.5.0
Hopefylly that works.
Closing this for now.

**Closed by DonJayamanne** 2023-11-03 00:20 UTC
Labels: debt
