### ISSUE TITLE
Access remote jupyter terminal

### ISSUE THREAD

**Issue by joey00072** [microsoft/vscode-jupyter#15621] opened 2024-04-28 13:50 UTC
we can terminal access of remote jupyter server that will help a lot,
I usually  use jupter from runpod, paperspace etc, having terminal access would be great

**Comment by DonJayamanne** [comment] 2024-12-10 22:44
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/14874

**Closed by DonJayamanne** 2024-12-10 22:44 UTC
Labels: notebook-remote, feature-request
