### ISSUE TITLE
Add the support of Semantic Token Colorization in JupyterNotebook like in the python file

### ISSUE THREAD

**Issue by gonghenghai** [microsoft/vscode-jupyter#7225] opened 2021-08-23 02:36 UTC
Jupyter notebook lacks the ability of `Semantic Token Colorization`:

The theme of `Dark+`:

[![enter image description here][1]][1]

[![enter image description here][2]][2]

The theme of `SynthWave '84`:

[![enter image description here][3]][3]

[![enter image description here][4]][4]

  [1]: https://i.stack.imgur.com/6nq0A.png
  [2]: https://i.stack.imgur.com/7q8XW.png
  [3]: https://i.stack.imgur.com/yowGK.png
  [4]: https://i.stack.imgur.com/hOc6n.png

**Comment by joyceerhl** [comment] 2021-08-23 18:10
Thanks for the suggestion. Not sure if we need to do extra work in the notebook LSP middleware module to support this https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_semanticTokens

**Comment by greazer** [comment] 2021-08-23 20:21
Dupe of #6799. Closing.

**Closed by greazer** 2021-08-23 20:21 UTC
Labels: bug, intellisense
