### ISSUE TITLE
Data Viewer fails to load dataframes containing columns named the same.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7603] opened 2021-09-21 20:15 UTC
## Environment data

-   VS Code version: 1.61-insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001256920

## Expected behaviour

Be able to view a simple dataframe

## Actual behaviour

Can't view a simple dataframe

## Steps to reproduce:

1. Create a notebook or IW file
2. Run this code (StateAbbrev.csv is attached)
```python
import pandas as pd

df = pd.read_csv('StateAbbrev.csv')
df.index = df.abbrev
```
3. Try to view the df dataframe in the dataviewer. 

It never loads

The log indicates this:
```ValueError: Overlapping names between the index and columns
    at f.extractJupyterResultText (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:90:260708)
    at f.deserializeJupyterResult (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:90:260826)
    at f.getDataFrameRows (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:90:257939)
    at r.getRows (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:52:866224)
    at c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:52:859192
    at C.wrapRequest (c:\Users\jimg\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.9.1001256920\out\client\extension.js:52:859421)
```

While it may not be common for this to happen when reading a csv file and immediately viewing it, I do think it could be common when doing dataprep.

</details
[StateAbbrev.csv](https://github.com/microsoft/vscode-jupyter/files/7205941/StateAbbrev.csv)
>

**Comment by rebornix** [comment] 2021-12-21 02:18
We are probably seeing 5000 similar failures on around 500 machines.

**Comment by rebornix** [comment] 2021-12-21 05:35
The log we saw is from CI tests though (as @DonJayamanne pointed out) but it might share the same root cause.
```
Error: Failed to fetch variable info from the Jupyter server. 
at PythonVariablesRequester.extractJupyterResultText (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/pythonVariableRequester.js:3529:11) 
at PythonVariablesRequester.deserializeJupyterResult (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/pythonVariableRequester.js:3534:51) 
at PythonVariablesRequester.getVariableNamesAndTypesFromKernel (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/pythonVariableRequester.js:3325:62) 
at runMicrotasks (<anonymous>) 
at processTicksAndRejections (internal/process/task_queues.js:93:5) 
at KernelVariables.getVariablesBasedOnKernel (/home/runner/work/vscode-jupyter/vscode-jupyter/out/client/datascience/jupyter/kernelVariables.js:5262:21) 
```

**Comment by DonJayamanne** [comment] 2021-12-21 06:14
These aren't important, hence removing the label
I think we shoul'dn't be looking at telemetry for tests, else we run into the danger of drawing the wrong conclusion as has been done here. 
Also we could be writing valid tests to test some error handlers or faults in our code.

**Comment by rebornix** [comment] 2021-12-21 18:32
Thanks for pointing it out this is different from the errors we saw on telemetry. I personally think checking the error telemetry is useful for validating the robustness of the code base, considering that Error/Exceptions thrown in the code are not user actionable. No action needs to be taken now but we can discuss in our next sync meeting.

**Comment by DonJayamanne** [comment] 2021-12-23 22:21
# Notes
* Re-opening this so, the team will see this in triage.
* Changes have been made to fix this
* Please close this issue (left open so you see this in triage)

**Closed** 2022-01-03 22:05 UTC
Labels: bug, data-viewer, needs-triage

**Comment by DonJayamanne** [comment] 2022-01-23 22:04
Steps to test:
* Install pandas into python environment
* Create a cell with the following code:
```python
import pandas as pd
df = pd.DataFrame({'num_legs': [2, 4, 8, 0],
                   'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [10, 2, 1, 8]},
                  index=['falcon', 'dog', 'spider', 'fish'])
df.index = df.num_legs
df
```
* Open the Jupyter variables viewer and click on the icon next to `df` to open the data frame viewer
* Verify the data frame contents are displayed (previously it wouldn't load)

**Comment by IanMatthewHuff** [comment] 2022-01-28 22:22
Looks good now, verified:
![image](https://user-images.githubusercontent.com/812783/151629580-e5dfd702-56ec-499e-956e-8b1dae94a01e.png)
