### ISSUE TITLE
Notebook can't import a local package

### ISSUE THREAD

**Issue by chart-magnum** [microsoft/vscode-jupyter#7926] opened 2021-10-14 14:51 UTC
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001312534
-   Python Extension version (available under the Extensions sidebar): v2021.10.1336267007
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N.A
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

Jupyter notebook identifies a local package with API.

## Actual behaviour

Jupyter notebook does not identify a local package with API.

## Steps to reproduce:

I have two projects, one with API: magnum-api and another with notebooks: magnum-nb. Both projects are located at C:\gitlab.
I would like to develop API in vs code and use it while executing notebooks. I created a workspace with both projects. 

![image](https://user-images.githubusercontent.com/88663349/137341168-0205e254-72e2-411c-abc2-b542be7cfa45.png)

Following documentation and similar issues reported here, I created `.env` file, inside `c:/gitlab/magnum-nb` with the following content:
```
workspaceFolder=C:/gitlab/magnum-nb
PYTHONPATH=c:/gitlab/magnum-api
```
I also modified settings.json file to point to the `.env` file:
```json
{
    "workbench.colorTheme": "Default Light+",
    "python.envFile": "${workspaceFolder}/.env",
    "jupyter.askForKernelRestart": false
}
```

When I open any notebook in `magnum-nb` project and execute
```python
import sys
print(sys.path)
```
I expect to see the path to my api package: `c:/gitlab/magnum-api`, however, the path is not present in the path.

I guess I messed something up in the setting of .env file. Could you please kindly help me with getting the right settings.

Thanks in advance!

**Comment by IanMatthewHuff** [comment] 2021-10-14 20:20
@chart-magnum Sorry quick clarification here. When you are executing that notebook, what notebook kernel (in the selector in the top right) are you using for execution?

**Comment by DonJayamanne** [comment] 2021-10-14 20:37
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/4593

**Closed by DonJayamanne** 2021-10-14 20:37 UTC
Labels: bug, needs-triage
