### ISSUE TITLE
Vpython isn't rendering in Jupyter notebooks

### ISSUE THREAD

**Issue by Sarath191181208** [microsoft/vscode-jupyter#11456] opened 2022-09-26 17:16 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I was using the vpython library then, the output took too long to show.

### What I expected :
I expected it to show the image of the sphere & show the controls 

### What I got:
The rendering of the object isn't happening. It's taking too long to render a simple object. I waited there for 10minutes but no luck.

Things I had tried:
- I tried restarting vscode & my computer
- It's working fine actually in jupyter-notebook

### VS Code Version

Version: 1.70.0 (user setup) Commit: da76f93349a72022ca4670c1b84860304616aaa2 Date: 2022-08-04T04:38:16.462Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2022.7.1102252217

### Jupyter logs

```shell
Visual Studio Code (1.70.0, undefined, desktop)
Jupyter Extension Version: 2022.6.1201981810.
Python Extension Version: 2022.10.0.
Workspace folder e:\Sarath\ComputationalPhysics
info 22:29:22.661: ZMQ install verified.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 22:29:23.353: LSP Notebooks experiment is disabled -- not in treatment group
info 22:29:23.834: Starting Jupyter Session id = 'startUsingPythonInterpreter:.jvsc74a57bd011938c6bc6919ae2720b4d5011047913343b08a43b18698fd82dedb0d4417594.c:\Program Files\Python39\python.exe.c:\Program Files\Python39\python.exe.-m#ipykernel_launcher' (Python Path: , EnvType: Global, EnvName: '', Version: 3.9.3) for 'e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb' (disableUI=true)
info 22:29:23.839: Creating raw notebook for resource 'e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb'
info 22:29:23.839: Computing working directory for resource 'e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb'
info 22:29:24.146: Starting raw kernel 'Python 3.9.3 64-bit' for interpreter c:\Program Files\Python39\python.exe
info 22:29:24.247: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
info 22:29:25.13: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
info 22:29:25.259: Registering dummy command feature
info 22:29:25.633: Widget Message: Received IPyWidgetMessages.IPyWidgets_IsReadyRequest
info 22:29:26.837: Preferred Remote kernel for e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb is undefined
info 22:29:26.837: Find preferred kernel for e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb with metadata {"kernelspec":{"display_name":"Python 3.9.3 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.3"},"vscode":{"interpreter":{"hash":"11938c6bc6919ae2720b4d5011047913343b08a43b18698fd82dedb0d4417594"}}} & preferred interpreter 
info 22:29:26.853: Preferred Remote kernel for e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb is undefined
info 22:29:26.854: Preferred kernel .jvsc74a57bd011938c6bc6919ae2720b4d5011047913343b08a43b18698fd82dedb0d4417594.c:\Program Files\Python39\python.exe.c:\Program Files\Python39\python.exe.-m#ipykernel_launcher is exact match
info 22:29:26.856: PreferredConnection: .jvsc74a57bd011938c6bc6919ae2720b4d5011047913343b08a43b18698fd82dedb0d4417594.c:\Program Files\Python39\python.exe.c:\Program Files\Python39\python.exe.-m#ipykernel_launcher found for NotebookDocument: e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb
info 22:29:32.916: Process Execution: > c:\Program Files\Python39\python.exe -m pip list
> c:\Program Files\Python39\python.exe -m pip list
info 22:29:32.940: Process Execution: > c:\Program Files\Python39\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> c:\Program Files\Python39\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 22:29:33.529: Creating daemon process for c:\Program Files\Python39\python.exe with env variables count 59
info 22:29:33.569: Process Execution: > c:\Program Files\Python39\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 4892
> c:\Program Files\Python39\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 4892
info 22:29:34.91: ipykernel version 6.13.0 for c:\Program Files\Python39\python.exe
info 22:29:34.91: ipykernel location c:\Program Files\Python39\lib\site-packages\ipykernel\__init__.py for c:\Program Files\Python39\python.exe
info 22:29:36.968: get interrupthandle daemon
info 22:29:37.6: Process Execution: > c:\Program Files\Python39\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"255d5667-8ed8-4dc2-8a0a-b47054d7d67b" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\Administrator\AppData\Roaming\jupyter\runtime\kernel-v2-4892sD52nc3ZrnLQ.json
> c:\Program Files\Python39\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"255d5667-8ed8-4dc2-8a0a-b47054d7d67b" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\Administrator\AppData\Roaming\jupyter\runtime\kernel-v2-4892sD52nc3ZrnLQ.json
info 22:29:37.6: Process Execution: cwd: e:\Sarath\ComputationalPhysics
cwd: e:\Sarath\ComputationalPhysics
info 22:29:37.904: Execute Cell 0 e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb
info 22:29:38.632: Preferred Remote kernel for e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb is undefined
info 22:29:38.632: Find preferred kernel for e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb with metadata {"kernelspec":{"display_name":"Python 3.9.3 64-bit","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.3"},"vscode":{"interpreter":{"hash":"11938c6bc6919ae2720b4d5011047913343b08a43b18698fd82dedb0d4417594"}}} & preferred interpreter 
info 22:29:38.634: Preferred Remote kernel for e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb is undefined
info 22:29:38.634: Preferred kernel .jvsc74a57bd011938c6bc6919ae2720b4d5011047913343b08a43b18698fd82dedb0d4417594.c:\Program Files\Python39\python.exe.c:\Program Files\Python39\python.exe.-m#ipykernel_launcher is exact match
info 22:29:38.639: Preferred Remote kernel for e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb is undefined
warn 22:29:39.532: StdErr from Kernel Process c:\Program Files\Python39\lib\site-packages\traitlets\traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
c:\Program Files\Python39\lib\site-packages\traitlets\traitlets.py:2346: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '255d5667-8ed8-4dc2-8a0a-b47054d7d67b' instead of 'b"255d5667-8ed8-4dc2-8a0a-b47054d7d67b"'.
  warn(

info 22:29:39.736: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing c:\Users\Administrator\AppData\Roaming\jupyter\runtime\kernel-v2-4892sD52nc3ZrnLQ.json

info 22:29:40.29: Started kernel Python 3.9.3 64-bit., (Raw session started and connected)
info 22:29:40.35: Finished connecting fccb43bb-b370-4389-aa10-f25e7adcefde
info 22:29:40.41: UpdateWorkingDirectoryAndPath in Kernel
info 22:29:40.42: Executing silently Code (idle) = import os\nimport sys\n%cd "e:\Sarath\ComputationalPhysics"\nif os.getcwd() not in sys.path:\nsys.pa
info 22:29:40.71: Executing silently Code (completed) = import os\nimport sys\n%cd "e:\Sarath\ComputationalPhysics"\nif os.getcwd() not in sys.path:\nsys.pa with 1 output(s)
info 22:29:40.72: Waiting for idle on (kernel): b4929bd4-adb2-4a18-a633-366d5bed5dba -> idle
info 22:29:40.72: Finished waiting for idle on (kernel): b4929bd4-adb2-4a18-a633-366d5bed5dba -> idle
info 22:29:40.126: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 22:29:40.126: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 22:29:40.374: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/Administrator/.vscode/extensions/ms-toolsai.jupyter-2022.6.1201981810/tmp/scripts/f32969acbfda228f24b597936499409070d85932e06ec704017c5f53d5ef18d6/jupyter
info 22:29:40.428: Cell 0 executed with state Success
info 22:29:49.650: Execute Cell 1 e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb
info 22:29:49.801: Cell 1 executed with state Success
info 22:29:55.619: Execute Cell 1 e:\Sarath\ComputationalPhysics\RandomWalk3D.ipynb
info 22:36:2.335: Starting interactive window for resource 'e:\Sarath\ComputationalPhysics\main.py'
info 22:36:2.532: Preferred Remote kernel for Interactive-1.interactive is undefined
info 22:36:2.816: Process Execution: > c:\Program Files\Python39\python.exe -m pip list
> c:\Program Files\Python39\python.exe -m pip list
info 22:36:3.70: Starting Jupyter Session id = 'startUsingPythonInterpreter:.jvsc74a57bd011938c6bc6919ae2720b4d5011047913343b08a43b18698fd82dedb0d4417594.c:\Program Files\Python39\python.exe.c:\Program Files\Python39\python.exe.-m#ipykernel_launcher' (Python Path: , EnvType: Global, EnvName: '', Version: 3.9.3) for 'Interactive-1.interactive' (disableUI=false)
info 22:36:3.72: Creating raw notebook for resource 'e:\Sarath\ComputationalPhysics\main.py'
info 22:36:3.72: Computing working directory for resource 'e:\Sarath\ComputationalPhysics\main.py'
info 22:36:3.76: Starting raw kernel 'Python 3.9.3 64-bit' for interpreter c:\Program Files\Python39\python.exe
info 22:36:3.336: Kernel launching with ports 9005,9006,9007,9008,9009. Start port is 9000
info 22:36:3.381: Process Execution: > c:\Program Files\Python39\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> c:\Program Files\Python39\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 22:36:3.418: Creating daemon process for c:\Program Files\Python39\python.exe with env variables count 59
info 22:36:3.477: Process Execution: > c:\Program Files\Python39\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 4892
> c:\Program Files\Python39\python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 4892
info 22:36:5.321: ipykernel version 6.13.0 for c:\Program Files\Python39\python.exe
info 22:36:5.321: ipykernel location c:\Program Files\Python39\lib\site-packages\ipykernel\__init__.py for c:\Program Files\Python39\python.exe
info 22:36:5.331: get interrupthandle daemon
info 22:36:5.410: Process Execution: > c:\Program Files\Python39\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"1b48348e-b7c6-4287-87ee-e7ff38d98ee8" --shell=9007 --transport="tcp" --iopub=9009 --f=c:\Users\Administrator\AppData\Roaming\jupyter\runtime\kernel-v2-4892I203SNkqf4Jm.json
> c:\Program Files\Python39\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"1b48348e-b7c6-4287-87ee-e7ff38d98ee8" --shell=9007 --transport="tcp" --iopub=9009 --f=c:\Users\Administrator\AppData\Roaming\jupyter\runtime\kernel-v2-4892I203SNkqf4Jm.json
info 22:36:5.410: Process Execution: cwd: e:\Sarath\ComputationalPhysics
cwd: e:\Sarath\ComputationalPhysics
warn 22:36:7.37: StdErr from Kernel Process c:\Program Files\Python39\lib\site-packages\traitlets\traitlets.py:2392: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 22:36:7.37: StdErr from Kernel Process c:\Program Files\Python39\lib\site-packages\traitlets\traitlets.py:2346: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '1b48348e-b7c6-4287-87ee-e7ff38d98ee8' instead of 'b"1b48348e-b7c6-4287-87ee-e7ff38d98ee8"'.
  warn(

info 22:36:7.147: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing c:\Users\Administrator\AppData\Roaming\jupyter\runtime\kernel-v2-4892I203SNkqf4Jm.json

info 22:36:7.383: Started kernel Python 3.9.3 64-bit., (Raw session started and connected)
info 22:36:7.390: Finished connecting fccb43bb-b370-4389-aa10-f25e7adcefde
info 22:36:7.395: UpdateWorkingDirectoryAndPath in Kernel
info 22:36:7.419: Executing silently Code (idle) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip
info 22:36:7.464: Executing silently Code (completed) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip with 1 output(s)
info 22:36:7.464: Waiting for idle on (kernel): 1edf1f7d-1f3a-4c96-8e64-6f412983029e -> idle
info 22:36:7.464: Finished waiting for idle on (kernel): 1edf1f7d-1f3a-4c96-8e64-6f412983029e -> idle
info 22:36:7.476: Executing silently Code (idle) = __file__ = 'e:\\Sarath\\ComputationalPhysics\\main.py'
info 22:36:7.499: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
info 22:36:7.499: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
info 22:36:7.528: Executing silently Code (completed) = __file__ = 'e:\\Sarath\\ComputationalPhysics\\main.py' with 0 output(s)
info 22:36:7.532: Generated code for 1 = <ipython-input-1-1c535e1d5a06> with 5 lines
info 22:36:7.618: Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/Administrator/.vscode/extensions/ms-toolsai.jupyter-2022.6.1201981810/tmp/scripts/f32969acbfda228f24b597936499409070d85932e06ec704017c5f53d5ef18d6/jupyter
info 22:36:7.786: Cell 1 executed with state Success
info 22:36:10.202: Generated code for 2 = <ipython-input-2-265c8fd65f41> with 4 lines
info 22:38:58.607: Disposing kernel .jvsc74a57bd011938c6bc6919ae2720b4d5011047913343b08a43b18698fd82dedb0d4417594.c:\Program Files\Python39\python.exe.c:\Program Files\Python39\python.exe.-m#ipykernel_launcher for notebook Interactive-1.interactive due to selection of another kernel or closing of the notebook
info 22:38:58.607: Dispose Kernel 'Interactive-1.interactive' associated with 'e:\Sarath\ComputationalPhysics\main.py'
info 22:38:58.607: Cancel pending cells
info 22:38:58.621: kill daemon
info 22:38:58.634: Dispose Kernel 'Interactive-1.interactive' associated with 'e:\Sarath\ComputationalPhysics\main.py'
info 22:38:58.647: Cancel all remaining cells true || Idle || undefined
info 22:38:58.647: Cancel pending cells
info 22:38:58.655: Cell 2 executed with state Idle
error 22:38:58.655: Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (c:\Users\Administrator\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:2:32353)
    at c:\Users\Administrator\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:2:51405
    at Map.forEach (<anonymous>)
    at y._clearKernelState (c:\Users\Administrator\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:2:51390)
    at y.dispose (c:\Users\Administrator\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:2:44872)
    at c:\Users\Administrator\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:251157
    at t.swallowExceptions (c:\Users\Administrator\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:29:120529)
    at dispose (c:\Users\Administrator\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:251135)
    at t.RawSession.dispose (c:\Users\Administrator\.vscode\extensions\ms-toolsai.jupyter-2022.6.1201981810\out\extension.node.js:24:256072)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
warn 22:38:58.658: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
```

### Coding Language and Runtime Version

Python 3.9.3 64bit

### Language Extension Version (if applicable)

v2022.14.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2022-09-26 21:51
@Sarath191181208 Thanks for filing this issue, 
* please could you check the version of `ipywidgets` installed in your environment, is it 8 or 7.
```
import ipywidgets
print(ipywidgets.__version__)
```

**Comment by Sarath191181208** [comment] 2022-09-27 01:26
`ipywidgets==7.7.1`

**Comment by DonJayamanne** [comment] 2022-09-27 09:37
thanks, can you send the sample code so i can test this at my end

**Comment by Sarath191181208** [comment] 2022-09-27 09:40
Yeah, sure

```python 
from vpython import sphere, canvas
scrn = canvas()
sphere()
```

**Comment by DonJayamanne** [comment] 2022-09-27 09:42
closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/1477#issuecomment-1158293684

**Closed by DonJayamanne** 2022-09-27 09:42 UTC
Labels: bug, info-needed, ipywidgets, jupyter-output
