### ISSUE TITLE
The Jupyter kernel in VSCode has duplicate options.

### ISSUE THREAD

**Issue by Jill-Cheng** [microsoft/vscode-jupyter#4074] opened 2020-12-02 02:36 UTC
## Environment data

-   VS Code version: Version: 1.51.1 (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): 2020.11.392013122
-   Python Extension version (available under the Extensions sidebar): 2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: OS: OS: Windows_NT x64 10.0.19041 
-   Python and/or Anaconda version:      python3.7 from anaconda;    python 3.8; python3.9;
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv; conda; 
-   Jupyter server running:  N/A

## Expected behaviour

The kernel options of Jupyter in VSCode are not duplicated.

![image](https://user-images.githubusercontent.com/61971386/100820828-0f320680-348a-11eb-9e16-9f6544eeb74c.png)

## Actual behaviour：

![image](https://user-images.githubusercontent.com/61971386/100819756-bfead680-3487-11eb-941c-3362d9432878.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open VSCode, install the extension "python".
2. Create a new Jupyter file, the Jupyter kernel displays "_python:3 idle_", click the kernel option, some "_python 3_" appears, from the path point of view, there are some repetitions of the anaconda kernel.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
none
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2020-12-02 17:12
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/399

**Closed by DonJayamanne** 2020-12-02 17:12 UTC
Labels: bug
