### ISSUE TITLE
Debugger does not show "View Value in Data Viewer" for dataframe member of a dataclass

### ISSUE THREAD

**Issue by peterlietz** [microsoft/vscode-jupyter#8338] opened 2021-11-23 10:05 UTC
### VS Code version

1.62.2

### Extension version

v2021.11.1422169775

### OS type

macOS

### OS version

Monterey 12.0.1

### Python distribution

python.org

### Python version

3.8.12

### Language server

Default

### Expected behaviour

In the debugger, while stopping at a breakpoint, when I right-click a pandas dataframe from the "Variables" view I expect the option "View Value in Data Viewer" to be available in the context menu.

### Actual behaviour

While the behaviour is as expected for local variables, the option "View Value in Data Viewer" is not available for dataframes which are themselves members of a dataclass.

### Steps to reproduce

Put a dataframe into a dataclass, stop the debugger at some breakpoint, right-click a local variable which is a dataframe.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/742173/143004238-cb85594f-dff5-43bb-817a-2483825559e1.png">

So far, so good. Now right-click the same dataframe as a member of a dataclass.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/742173/143004545-fed796b8-f62c-4b0f-8f05-c996d5a13e17.png">

Now the option is missing. Neither, by the way, does it work for dataframes in watches, whether top-level or nested.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanMatthewHuff** [comment] 2021-11-24 19:06
@peterlietz I actually just fixed this issue last week, so I'm closing this report as a duplicate of this one:
https://github.com/microsoft/vscode-jupyter/issues/7295

The fix is live now in our insiders build and will release with our next stable release.

**Closed by IanMatthewHuff** 2021-11-24 19:06 UTC
Labels: needs-triage
