### ISSUE TITLE
`display` stops working after Comm open

### ISSUE THREAD

**Issue by slundberg** [microsoft/vscode-jupyter#13243] opened 2023-03-31 21:52 UTC
## Environment data

-   VS Code version: 1.76.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1200692131
-   Python Extension version (available under the Extensions sidebar): v2023.4.1
-   OS (Windows | Mac | Linux distro) and version: Mac OS 13.2.1 (22D68)
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

`display` should keep sending output to the cell's output.

## Actual behaviour

`display` stops working when a font-end comm open message is sent.

## Steps to reproduce:

Run the following in a notebook cell and note that `display` stops working after iteration 5.
(Note that the equivalent version of this works in a Jupyter notebook)

```python
from IPython.display import display_html, clear_output, display
import asyncio

async def f():
    for i in range(10):
        await asyncio.sleep(1)
        if i != 5:
            display({"text/html": f"<b>{i}</b>"}, raw=True, include=["text/html"])
        if i == 5:
            display({"text/html": """<script>window._mgr.widgetManager.proxyKernel.createComm('custom_comm').open({}, '');</script>""" + f"<b>{i}</b>"}, raw=True, include=["text/html"])
display({"text/html": f"<b>-1</b>"}, raw=True, include=["text/html"])
asyncio.get_event_loop().create_task(f())
```

**Comment by DonJayamanne** [comment] 2023-04-20 20:21
@slundberg I'm very sorry for missing this issue,
Thanks for filing this and I'm sorry you are running into this issue.

The problem here is, the script `window._mgr.widgetManager.proxyKernel.createComm` is not supported for use.
This is an internal construct used for internal mechanics.
If you remove that script, then things will work.

Lets closing this as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/13255

**Closed by DonJayamanne** 2023-04-20 20:21 UTC
Labels: bug, ipywidgets
