### ISSUE TITLE
Debug cell not working on macOS

### ISSUE THREAD

**Issue by aljabadi** [microsoft/vscode-jupyter#8940] opened 2022-02-07 02:05 UTC
Issue Type: <b>Bug</b>

Debug cell launches the debugger but won't stop at breakpoint or show any signs of any execution. Trying to access the variables before the first breakpoint in debug console throws an error which probably means it is not just a UI issue. The debugger works just fine in [interactive python files](https://code.visualstudio.com/docs/python/jupyter-support-py#_jupyter-code-cells), but not in [notebooks](https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_debug-cell). This issue reproduces in the Insiders version. A gif will be attached.

Extension version: 2022.1.1001775990
VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:20:22.135Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 9c18ce9b-c0c7-4fa0-a5c2-eecd7b2d0261|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>
![vscode-debug-cell-issue](https://user-images.githubusercontent.com/28503057/152713735-6e439523-0586-4677-9ffc-227c838e64f9.gif)

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop940:30404999
vsrem710cf:30416617

```

</details>

**Comment by aljabadi** [comment] 2022-02-07 02:07
![vscode-debug-cell-issue](https://user-images.githubusercontent.com/28503057/152713788-69510da9-3d50-4b5e-b94c-1fee912a7f62.gif)

**Comment by jmigual** [comment] 2022-02-07 15:46
Can confirm the same behavior on Windows.

## Environment data

-   VS Code version: 1.64.0
-   Jupyter Extension version: v2022.1.1001775990
-   Python Extension version: v2022.0.1786462952
-   OS Windows and version: Windows 10 21H2 Build 19044.1503
-   Python and/or Anaconda version: Python 3.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry / virtualenv
-   Jupyter server running: Local

**Comment by jmigual** [comment] 2022-02-07 15:51
As an addition, I found that if you add the breakpoint in the first line it works, while a breakpoint in any other line is ignored.

**Comment by Syndorik** [comment] 2022-02-07 16:31
After some testings, it seems that the issue is linked to ipykernel version 6.4.1
I have downgraded to ipykernel 6.4.0 and it works perfectly

**Comment by DonJayamanne** [comment] 2022-02-07 18:44
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8803

**Closed by DonJayamanne** 2022-02-07 18:44 UTC
Labels: needs-triage
