### ISSUE TITLE
"View Value in Data View" doesn't show on self parameter 

### ISSUE THREAD

**Issue by jnelson22** [microsoft/vscode-jupyter#8300] opened 2021-11-17 19:43 UTC
### VS Code version

1.62.2

### Extension version

v2021.11.1422169775

### OS type

Windows

### OS version

20H2

### Python distribution

python.org

### Python version

v2021.11.1422169775

### Language server

Default

### Expected behaviour

Should be able right click "View Value in Data View" on self._data (pandas dataframe) in the same way it is available in "local" variables. 

### Actual behaviour

Currently the right click menu doesn't not show "View Value in Data View"

![image](https://user-images.githubusercontent.com/18246480/142269377-04971a88-ec9e-4851-8bd1-7d070e58abc6.png)

When I set df  = self._data in the debug console. This allow the right click to work. 
![image](https://user-images.githubusercontent.com/18246480/142269476-4c5ae858-aff7-4be3-9108-c5ced61c83f6.png)

### Steps to reproduce

Create a python class with self._data that is a pandas dataframe. Then try to right click "View Value in Data View" on the self._data after class has been initialized. Menu option in menu does not exits. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by IanMatthewHuff** [comment] 2021-11-18 19:43
@jnelson22 I was actually just submitting a PR for this off of a similar issue: https://github.com/microsoft/vscode-jupyter/pull/8303. Fix should be incoming shortly. I'll close this issue as a duplicate of 8303.

**Comment by IanMatthewHuff** [comment] 2021-11-18 19:44
Sorry that's the PR link. This is the actual duplicate issue: https://github.com/microsoft/vscode-jupyter/issues/7295

**Closed** 2021-11-18 19:43 UTC
Labels: needs-triage

**Comment by jnelson22** [comment] 2021-11-18 19:54
@IanMatthewHuff Thanks, great to hear that it's in work.
