### ISSUE TITLE
Som Notebook Keyboard Shortcuts does not work.

### ISSUE THREAD

**Issue by zhouwangyang** [microsoft/vscode-jupyter#4420] opened 2021-01-18 11:57 UTC
## Environment data

Version: 1.53.0-insider (user setup)
Commit: eaa959d34b863dec932077d94daece22504a396b
Date: 2021-01-18T05:13:25.733Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.17134
anaconda: python 3.8.5(64 bit)
Build of python-insider: 2020.12.414227025
Build of Jupyter-insider: 2021.1.481581316-rc

## Expected behaviour
these Notebook Keyboard Shortcuts should work well.

## Actual behaviour
Keyboard Shortcuts does not work, among them, after hit `ctrl+enter` , a cell runs and a new cell is added below.

## Steps to reproduce:
1. Using the notebook generated from the manualTestFile.py, do the following:
2. Hit `o` on a code cell with output and verify that outputs disappear
3. Hit `z` and verify a deleted cell reappears
4. Hit `ctrl+enter` and verify a cell runs and selection does not change

**Comment by joyceerhl** [comment] 2021-01-19 08:04
@zhouwangyang, sorry for the trouble here. If you're looking to run a cell in-place, I believe ctrl+alt+enter on Windows is the shortcut you're looking for. Which other notebook shortcuts are not working for you?

**Comment by IanMatthewHuff** [comment] 2021-01-19 19:18
I believe that most of these would be covered by this issue, which we have still not resolved yet:
https://github.com/microsoft/vscode-jupyter/issues/4376

I think these are just not available in the new interface until that point.

**Comment by joyceerhl** [comment] 2021-01-19 20:09
Oh, missed that one @IanMatthewHuff. Thanks for the pointer. I think we can close this one as a dupe then?

**Comment by greazer** [comment] 2021-01-21 21:32
This is a dupe of #4376

**Closed by greazer** 2021-01-21 21:32 UTC
Labels: bug
