### ISSUE TITLE
Data Viewer: Select multiple + Copy/Paste Data

### ISSUE THREAD

**Issue by jake-steele** [microsoft/vscode-jupyter#4236] opened 2020-12-15 17:30 UTC
It does not appear that this request is reflected in any current issues.

I would like to be able to **select multiple data from the Data Viewer** (sequentially by shift, individually by ctrl modifier) and **copy to the clipboard for pasting into other programs**, such as Microsoft Excel (though any sort of copy/paste would be appreciated).

Forgive me if this feature already exists and I am just unaware, but it does not seem to work via local Jupyter on my Windows 10 machine.

VS Code Version Info
Version: 1.51.1 (system setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
Jupyter Extension: v2020.12.414227025

I updated to VS Code 1.52 just now just in case older version was messing with the extension, but it still does not appear to allow copy/paste or multiple selection in Data Viewer.

**Comment by IanMatthewHuff** [comment] 2020-12-16 18:29
@jake-steele Thanks for filing this. Our current data viewer is a bit limited on that front. We're actually looking at making some improvements on that in the near future, so we'll keep your enhancement request logged as part of that work.

**Comment by jake-steele** [comment] 2020-12-21 18:29
> 
> 
> @jake-steele Thanks for filing this. Our current data viewer is a bit limited on that front. We're actually looking at making some improvements on that in the near future, so we'll keep your enhancement request logged as part of that work.

Wonderful to hear, @IanMatthewHuff. Thank you very much. I'll be looking forward to the coming changes. Keep up the great work!

**Comment by joyceerhl** [comment] 2021-02-26 18:05
Copy-paste for individual cells should be possible with the recent February release. We can implement multi-select by writing a slickgrid multicell selection model plugin (by default there's only cellselectionmodel and rowselectionmodel).

**Comment by joyceerhl** [comment] 2021-02-26 18:14
Out of curiosity @jake-steele, what would you expect to see if you selected multiple individual disjoint cells and tried to paste them? (Would you expect to be able to do something like that?)

**Comment by DonJayamanne** [comment] 2022-12-08 00:34
Thanks for this suggestion, however there haven't been enough upvotes on this feature request,
hence closing this for now

**Comment by DonJayamanne** [comment] 2022-12-08 00:53
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1149

**Closed by DonJayamanne** 2022-12-08 00:53 UTC
Labels: data-viewer, feature-request
