### ISSUE TITLE
error highlighting broken in Jupyter Notebooks

### ISSUE THREAD

**Issue by fierval** [microsoft/vscode-jupyter#8677] opened 2022-01-12 19:16 UTC
Issue Type: <b>Bug</b>

Error highlighting in Jupyter is badly broken.

Extension version: 2021.12.1559732655
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (40.86GB free)|
|Process Argv|--folder-uri file:///c%3A/git/fetch/theia-models --crash-reporter-id 28592bab-0cbd-42c4-b35d-ec0a4bb99be1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30421291
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by rchiodo** [comment] 2022-01-12 21:34
I believe this is a dupe of your other issue (#8676) ? I assume you opened this one on the python team to start.

**Closed by rchiodo** 2022-01-12 21:34 UTC
Labels: needs-triage

**Comment by fierval** [comment] 2022-01-12 21:38
Yes. Didn’t realize jupyter extension was separate from Python when opening
the first one. It’s a dup.

Ср, 12 янв. 2022 г. в 13:34, Rich Chiodo ***@***.***>:
