### ISSUE TITLE
Extension server selector API - additional arguments ca, cert etc

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode-jupyter#11628] opened 2022-10-12 09:33 UTC
Hi, I'm implementing an internal extension using `jupyterRemoteServerProvider` and would like to provide `ca` argument to connect to internal servers.

**Comment by DonJayamanne** [comment] 2022-12-04 19:58
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/12268

**Closed by DonJayamanne** 2022-12-04 19:58 UTC
Labels: feature-request, remote-picker
