### ISSUE TITLE
Error: Direct kernel connection broken

### ISSUE THREAD

**Issue by Dilahk7** [microsoft/vscode-jupyter#6625] opened 2021-07-11 14:43 UTC
We have written the need
Issue Type: <b>Bug</b>

Jupyter notebook not ideal for Deep learning,genreally throws 
Error: Direct kernel connection broken

every time trying to process models 

Extension version: 2021.8.1013163132
VS Code version: Code 1.58.0 (2d23c42a936db1c7b3b06f918cde29561cc47cd6, 2021-07-08T06:54:55.083Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.63GB free)|
|Process Argv|C:\\Users\\khali\\Desktop\\11_07\\MobileNet.ipynb --crash-reporter-id 3f32aa6a-ac92-4a38-9d77-8e8c9f732b41|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30335482
vscod805cf:30301675
pythonvspyt200:30331937
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
vstea450:30335276
bridge0708:30335490

```

</details>

ed data into your clipboard because it was too large to send. Please paste.

**Comment by joyceerhl** [comment] 2021-07-11 19:12
@Dilahk7 Sorry to hear you are running into issues. Please could you provide us with the Jupyter error logs from the Jupyter output panel, and could you also share sample code that triggers the error so that we can reproduce the problem on our end?

**Comment by DonJayamanne** [comment] 2021-09-02 19:48
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Closed by DonJayamanne** 2021-09-02 19:48 UTC
Labels: bug, info-needed, kernel-issues
