### ISSUE TITLE
On Azure ML remote connection, after executing some code, the kernel is not displayed in Jupyter as a running kernel or session

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-jupyter#13080] opened 2023-03-15 01:32 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

- Start a remote connection to an Azure ML compute instance (either web or desktop)
- User opens a notebook and clicks on "Select Kernel"
- Click on "Jupyter Kernel..."
- Select a kernel
- Run a cell
- The kernel or session is not displayed as running in Jupyter or Azure ML kernel session manager

https://microsoft.sharepoint.com/:v:/t/AzureMLExtension/EcZoV71WxMVOkXBY8K8oOoQBNqhFhMROAJfScblxejAeug?e=OfTFLo

### VS Code Version

1.76.1

### Jupyter Extension Version

v2023.2.1200692131

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by DonJayamanne** [comment] 2023-04-28 04:35
The problem here is the kernels are not started using Jupyter
The two kernels started from Python Environment and Jupyter Kernel will not end up using Jupyter, hence will never showup in Jupyter/AzML

**Comment by DonJayamanne** [comment] 2023-04-28 23:36
Duplicate of #13424 #13423

**Closed by DonJayamanne** 2023-04-28 23:36 UTC
Labels: bug, partner, notebook-remote
