### ISSUE TITLE
Remote jupyter kernels always use a pythonPath of 'python3'.

### ISSUE THREAD

**Issue by avneeshs1** [microsoft/vscode-jupyter#14446] opened 2023-10-05 13:24 UTC
## Environment data

-   Language Server version: v2023.10.10
-   OS and version: VSCode 1.83.0 running on macOS connected remotely via SSH to AmazonLinux 2023 on aarch64
-   Python version (& distribution if applicable, e.g. Anaconda): python 3.11.3
-  Code being executed in a notebook. **Notebook kernel is connected to an external jupyter server running on the same remote machine**.
- Jupyter server kernels are using the same python runtime as what the python interpreter in VSCode is set to. I just run jupyter server separately to keep kernels alive even is VSCode's ssh connection blips.
- The notebook root is set to `"jupyter.notebookFileRoot": "${workspaceFolder}"`

## Code Snippet

```python
import pandas as pd
import numpy as np
import holoviews as hv
from holoviews import opts
hv.extension('bokeh', 'matplotlib')
```

## Expected behavior

All imports are valid and should be resolved. In fact, if I set the notebook kernel to point to the runtime directly (i.e not the external jupyter server), the imports resolve just fine.

## Actual behavior

Pylance reports imports as unresolved. See below. 

<img width="1118" alt="image" src="https://github.com/microsoft/pylance-release/assets/13733034/409517c1-09d6-4a8e-ac78-09f96daf45ab">

## Logs

attached
[python_lang_server_output.txt](https://github.com/microsoft/pylance-release/files/12818854/python_lang_server_output.txt)

**Comment by avneeshs1** [comment] 2023-10-05 16:30
Thanks @rchiodo. I will file a bug with the jupyter extension team cross-referencing this thread. In the meanwhile though, is there a setting that can tell pylance to use a specific python interpreter overriding whatever jupyter extension is returning?

**Comment by rchiodo** [comment] 2023-10-05 16:32
> Thanks @rchiodo. I will file a bug with the jupyter extension team cross-referencing this thread. In the meanwhile though, is there a setting that can tell pylance to use a specific python interpreter overriding whatever jupyter extension is returning?

Oh, I transferred this issue there. Should be no need for another issue.

Unfortunately, there is no setting. We're asking the Jupyter extension what the python path for the notebook is and they give us back a specific value. We assume they know more than we do, so we don't have a way to override what they return.

**Comment by TTTPOB** [comment] 2023-10-10 11:24
same here, an unpleasant experience. I suggest there should be a user-defined map between kernel and interpreter path to use by pylance.

**Comment by DonJayamanne** [comment] 2023-10-10 11:31
Looks like a regression of https://github.com/microsoft/vscode-jupyter/issues/13550

**Comment by DonJayamanne** [comment] 2023-10-10 11:50
@TTTPOB @avneeshs1 
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by TTTPOB** [comment] 2023-10-10 12:47
here is the log
FYI, I found all my username in path are converted to `<username>`, is this expected behaviour? 
![image](https://github.com/microsoft/vscode-jupyter/assets/19909103/cf265092-30bb-434c-9918-adefb7e371fd)
the notebook I am using is learn to tune. and the remote kernel I am using for this notebook is `/mnt/pool1/projects/personal_projects/xxx/2023/09.28.sc_predict/envs/conda/bin/python` ( as stated above, in the log my username xxx was replaced by `<username>` ).
[output.txt](https://github.com/microsoft/vscode-jupyter/files/12857301/output.txt)

**Comment by avneeshs1** [comment] 2023-10-10 20:01
@DonJayamanne, here is the log from the Jupyter panel. 

[jupyter_output.txt](https://github.com/microsoft/vscode-jupyter/files/12861378/jupyter_output.txt)

**Comment by DonJayamanne** [comment] 2023-10-10 22:05
> username in path are converted to <username>, is this expected behaviour?

Yes thats expected, we did  that based on user feedback, that makes it easier for users to provide logs as some weren't too comfortable sharing logs with the user names.

**Comment by DonJayamanne** [comment] 2023-10-11 02:03
@TTTPOB @avneeshs1 
Please could you install this VSIX, replicate the issue again and share the logs once more
* Download the file
* Extract the zip file
* Go into VS Code and select the command `Extensions: Install from VSIX`
* When prompted, please reload VS Code
* Try to replicate the issue again provide the logs
[ms-toolsai-jupyter-insiders.vsix (1).zip](https://github.com/microsoft/vscode-jupyter/files/12864071/ms-toolsai-jupyter-insiders.vsix.1.zip)


Thanks for your patience and help in resolving this issue.

**Comment by TTTPOB** [comment] 2023-10-11 04:18
[output2.txt](https://github.com/microsoft/vscode-jupyter/files/12864774/output2.txt)
same notebook file `learn_to_tune.ipynb` , and same kernel `sc_predict`. interpreter selected in python extension is the same as the kernel ( `sc_predict` )

**Comment by DonJayamanne** [comment] 2023-10-11 05:22
@TTTPOB 

>  interpreter selected in python extension is the same as the kernel ( sc_predict )

I'm not sure I understand the problem now.
I thought you were selecting a remote kernel, but you seem to be indicating the fact taht you are selecting an interpreter (local kernel).

Please note, when using remote kernels, whether they are localhost or not, Pylance will not work, basically the Jupyter extension will return an empty string to Pylance,  meaning pylance will stop providing code completions as its not aware of the python environment.

**Comment by TTTPOB** [comment] 2023-10-11 05:27
> @TTTPOB
> 
> > interpreter selected in python extension is the same as the kernel ( sc_predict )
> 
> I'm not sure I understand the problem now. I thought you were selecting a remote kernel, but you seem to be indicating the fact taht you are selecting an interpreter (local kernel).
> 
> Please note, when using remote kernels, whether they are localhost or not, Pylance will not work, basically the Jupyter extension will return an empty string to Pylance, meaning pylance will stop providing code completions as its not aware of the python environment.

Yes, I selected a remote (localhost kernel). And selected an interpreter in python extension ( but this is for pylance to do statically analysis for other python file)
the reason why I mentioned I selected an interpreter in python extension is that I though it might be useful to note this python-related information.

**Comment by DonJayamanne** [comment] 2023-10-11 07:03
> before this regression I though Pylance would use the python interpreter selected in python extension to do static analysis in python notebooks (remote kernel), as I see repeated suggestions from both pylance and ipykernel when triggered completion in notebook, am I wrong?

unfortunately this is not a supported scenario.
As its impossible for us to tell whether a remote server is local host or not, localhost:8000 or the like could be port re-directions and the like. Even querying the kernel for the python information is not guaranteed to work, 

Can i ask why you are starting Jupyter outside VS Code and connecting to that as though it were a remote server?
Why not run the kernels directly from within vscode using the Python environment?

**Comment by TTTPOB** [comment] 2023-10-11 07:49
> Thats weird, based on the logs you do not seem to have a remote kernel selected.
> Please can you try to select a different kernel and then re-select the remote kernel and share the logs once again.

[output3.txt](https://github.com/microsoft/vscode-jupyter/files/12866251/output3.txt)

> Can i ask why you are starting Jupyter outside VS Code and connecting to that as though it were a remote server?
Why not run the kernels directly from within vscode using the Python environment?

Becase we need to run time-consuming computations using notebook and persist work progress, as mentioned in this issue. If I use vscode managed kernel, a disconnect will cause my work progress lost.
https://github.com/microsoft/vscode-jupyter/issues/1378#issuecomment-1321146089

> As its impossible for us to tell whether a remote server is local host or not, localhost:8000 or the like could be port re-directions and the like. Even querying the kernel for the python information is not guaranteed to work

I totally agree with you that for a remote jupyter server, it is impossible to tell it is "truely remote" or "actually local". maybe there could be a user defined list of jupyter remove servers to be treated like local?

**Comment by avneeshs1** [comment] 2023-10-11 13:05
@DonJayamanne, if we have a setting that allowed allowed users to choose an interpreter to be passed for external (truly remote or not) kernels, won't that solve this? Like @TTTPOB, I too had thought that pylance would use python extensions interpreter if the notebook interpreter was not accessible. Obviously, that is not the case. But it seems like allowing users to override the "empty" string currently being returned will work.

**Comment by DonJayamanne** [comment] 2023-10-11 13:24
Found a duplicate issue, closing in favour of that.
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/13095

**Closed by DonJayamanne** 2023-10-11 13:24 UTC
Labels: info-needed, feature-request
