### ISSUE TITLE
Automatic tab switching whilst running .ipynb file 

### ISSUE THREAD

**Issue by hannibal90** [microsoft/vscode-jupyter#4278] opened 2021-01-01 15:00 UTC
## Environment data

-   VS Code version: 1.52.1
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS: Linux Ubuntu 20.04
-   Python and/or Anaconda version: 3.8
-   Jupyter server running: Remote

## Behaviour

When running all the cells in a long .ipynb file, if I switch to edit a file in another VS Code tab, every time a cell gets completed I automatically get switched from my new tab back to the running .ipynb tab.

**Comment by joyceerhl** [comment] 2021-01-03 23:34
Hi @hannibal90, we intentionally added this, but it sounds like this is not desirable for you. Would you prefer a way to turn off the tab switching behavior?

**Comment by hannibal90** [comment] 2021-01-04 02:23
Hi, yes a way to disable this would be great.  I have lost count of the number of times I have overwritten code as a result of this auto tab switching. Thanks

**Comment by greazer** [comment] 2021-01-05 21:54
Dupe of #1425

**Closed by greazer** 2021-01-05 21:54 UTC
Labels: bug

**Comment by greazer** [comment] 2021-01-05 21:57
Also a dupe of #1260
