### ISSUE TITLE
Two "Cancel" buttons when interrupting the kernel times out

### ISSUE THREAD

**Issue by slishak** [microsoft/vscode-jupyter#11262] opened 2022-09-01 20:45 UTC
## Environment data

-   VS Code version: 1.70.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.7.1102252217
-   Python Extension version (available under the Extensions sidebar): v2022.12.1
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Only one cancel button - not sure what the other one does!

## Actual behaviour

<img width="600" alt="double cancel" src="https://user-images.githubusercontent.com/12515343/188009130-3320372c-9a26-4531-b152-ae660258f95c.png">

## Steps to reproduce:

No minimum reproducible example given - but can reproduce when clicking "Interrupt" while running a PyTorch optimisation loop on a GPU, for example.

**Comment by DonJayamanne** [comment] 2022-09-02 01:04
Please could you update to the latest version of the Jupyter extension.
I believe this has been resolved in the latest version.
If it still hasn't then please feel free to re-open this issue or create a new issue and we'll be happy to look into this.

Duplicate of https://github.com/microsoft/vscode-jupyter/issues/10858

**Closed by DonJayamanne** 2022-09-02 01:04 UTC
Labels: bug

**Comment by slishak** [comment] 2022-09-02 07:37
Sorry, don't know how I missed the point in the changelog and the duplicate issue! Will update and let you know if that doesn't fix it.
