### ISSUE TITLE
SSO Authentication Remote Jupyter

### ISSUE THREAD

**Issue by mrcmoresi** [microsoft/vscode-jupyter#12400] opened 2022-12-14 11:59 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm trying to use SSO of Azure Active Directory to login into Snowflake. The problem happens when I'm using VSCode to remote a VM in an azure ML environment. 
When I run the command to login the notebook is not showing me a placeholder where to put the URL 
![image](https://user-images.githubusercontent.com/12852824/207589140-96ce2ed5-6f3e-4f64-bfde-ffe7eb3748a0.png)

In case I run directly in a jupyter notebook in the VM it works as expected
![image](https://user-images.githubusercontent.com/12852824/207589607-ad7c98f4-6533-49b3-9f20-c6a6dd3bbeda.png)

Any idea what could I try to fix it?

### VS Code Version

1.74.0

### Jupyter Extension Version

v2022.11.1003412109

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment] 2022-12-20 21:24
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

Could you also copy the output from the `console window`, you can get to that using the command `Toggle Developer Tools`

**Comment by DonJayamanne** [comment] 2023-01-23 00:21
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by 54iceblock** [comment] 2023-03-17 17:30
I have encountered the same issue and here is my workaround: 
1. Run the connect code, your browser will open a page to sign in to the SSO, and then jump to a page that has URL starts with "localhost:xxxxx'. （this is the URL you copied into the input box in jupyter)
2. Go back to vscode, there is a port forwarding page next to terminal window.  Manually setup port forwarding to be the same as the one you see on SSO page.  
3. One port forwarding is ready, go to your browser and refresh the page.
4. Go back to vscode, your connection to SF should be ready in a few second.

I guess there might be an issue with auto port forwarding.

**Comment by 54iceblock** [comment] 2023-03-17 21:35
I change the log level of Jupyter to Verbose but it still starts with debug in the output window, here is the jupyter output from console window:
`debug 17:22:37.220: VSCodeNotebookController::handleExecution, Class name = Kv (started execution)
debug 17:22:37.222: Execute Cell 2 /mnt/**********.ipynb
debug 17:22:37.222: start the kernel, options.disableUI=false for /mnt/**********.ipynb
debug 17:22:37.222: Start Jupyter Session in kernel.ts with disableUI = false
debug 17:22:37.224: Start cell 2 execution @ 1679088157224`


and here is the developer tool output
`log.ts:392  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][1ms] obtaining proxy...
log.ts:392  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][1ms] invoking...
log.ts:392  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][1045ms] waiting...
log.ts:392  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][2003ms] waiting...
log.ts:404   ERR [Extension Host] (node:15960) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
console.ts:137 [Extension Host] (node:15960) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
log.ts:392  INFO [LocalProcess0][resolveAuthority(ssh-remote,1)][2968ms] returned 127.0.0.1:61777
log.ts:392  INFO resolveAuthority(ssh-remote) returned '127.0.0.1:61777' after 2970 ms
log.ts:392  INFO Creating a socket (renderer-Management-56b86923-42d4-4405-b134-a4baf9186736)...
log.ts:392  INFO Creating a socket (renderer-ExtensionHost-ec0d22e8-1dea-4aa6-9db3-b70fe41a820e)...
log.ts:392  INFO Creating a socket (renderer-Management-56b86923-42d4-4405-b134-a4baf9186736) was successful after 168 ms.
log.ts:392  INFO Creating a socket (renderer-ExtensionHost-ec0d22e8-1dea-4aa6-9db3-b70fe41a820e) was successful after 337 ms.
log.ts:404   ERR Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host
    at S.L (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:27:6849)
    at S.updateIcon (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:27:2680)
    at Object.call (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at l.s (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at l.q (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at n.invoke (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:11:2070)
    at c.fire (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:11:1708)
    at process.T (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:9:20949)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
log.ts:404   ERR Could not find pty on pty host: CodeExpectedError: Could not find pty on pty host
    at S.L (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:27:6849)
    at S.updateTitle (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:27:2630)
    at Object.call (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:17:5043)
    at l.s (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:15:5412)
    at l.q (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:15:4915)
    at /mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:15:4326
    at n.invoke (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:11:145)
    at E.deliver (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:11:2070)
    at c.fire (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:11:1708)
    at process.T (/mnt/******/.vscode-server/bin/ee2b180…/out/vs/platform/terminal/node/ptyHostMain.js:9:20949)
    at process.emit (node:events:526:28)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
log.ts:392  INFO [perf] Render performance baseline is 98ms
console.ts:137 [Extension Host] Starting WebSocket: RAW/api/kernels/55858091-a0fb-43a8-8714-175cd70658c3
log.ts:404   ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
3
log.ts:398  WARN Settings pattern "application.*" doesn't match any settings
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002b7b2……ons/ms-toolsai.jupyter-renderers-1.0.15/out/client_renderer/preload.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002b7b2……0692131/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002b7b2……i.jupyter-renderers-1.0.15/out/client_renderer/builtinRendererHooks.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002b7b2……-2023.2.1200692131/out/webviews/webview-side/ipywidgetsKernel/dummy.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
`

sensitive information was replaced with *

At this point, jupyter notebook is running and waiting for a response, I had to manually setup port forwarding, and then the code would execute with no error
here is the jupyter output
`
debug 17:22:37.220: VSCodeNotebookController::handleExecution, Class name = Kv (started execution)
debug 17:22:37.222: Execute Cell 2 /mnt/**********.ipynb
debug 17:22:37.222: start the kernel, options.disableUI=false for /mnt/**********.ipynb
debug 17:22:37.222: Start Jupyter Session in kernel.ts with disableUI = false
debug 17:22:37.224: Start cell 2 execution @ 1679088157224
debug 17:25:11.697: End cell 2 execution @ 1679088311696, started @ 1679088157224, elapsed time = 154.472s
debug 17:25:11.697: Cell 2 executed with state Success
debug 17:25:11.697: VSCodeNotebookController::handleExecution, Class name = Kv, completed in 154477ms, has a falsy return value`

**Comment by DonJayamanne** [comment] 2023-03-17 22:04
Thank you for your help
 Please can you share all of the logs (not just a section)
If the file and folder names are sensitive please could you open a different folder and just mask the user name (leaving rest of the past)
The paths are important, as I will need to map them in the logs and figure out which one is which

**Comment by 54iceblock** [comment] 2023-03-17 22:18
Had to attach a file, otherwise some log would be translated into format

[Jupyter Log.txt](https://github.com/microsoft/vscode-jupyter/files/11006732/Jupyter.Log.txt)
[developertoollog.txt](https://github.com/microsoft/vscode-jupyter/files/11006733/developertoollog.txt)

**Comment by DonJayamanne** [comment] 2023-03-17 23:09
Looks like you are using an old version of vscode and Jupiter extension
Please could you update them and try again
And send the logs once again

**Comment by 54iceblock** [comment] 2023-03-17 23:48
There is no new version of vscode that I can find.
The Jupyter version is v2023.2.1200692131, which is also the latest version I can found, unless I switch to pre-release channel.

**Comment by DonJayamanne** [comment] 2023-03-18 00:04
Oops, sorry was looking at the wrong logs

**Comment by DonJayamanne** [comment] 2023-03-30 19:41
> I have encountered the same issue and here is my workaround:
Run the connect code, your browser will open a page to sign in to the SSO, and then jump to a page that has URL starts with "localhost:xxxxx'. （this is the URL you copied into the input box in jupyter)
Go back to vscode, there is a port forwarding page next to terminal window. Manually setup port forwarding to be the same as the one you see on SSO page.
Once port forwarding is ready, go back to your browser and refresh the SSO page.


@54iceblock sorry it took me a while to get back to this issue, i've re-read this issue and checked the logs
I do not think this is an issue in the extension, instead this is just a configuration (environment setup) issue
I agree this is not the best experience, however you will need to first setup the port forwarding for things to work.
Hence whatyou have described as the work around, is the right solution.

Closing as this is the expected behaviour.
Hope that makes sense, if I have misunderstood something, please do feel free to reply back here

**Comment by 54iceblock** [comment] 2023-03-30 22:02
I think the behavior difference between web hosted jupyter and vscode hoster jupyter is that, on web, it will show a box to paste the URL to jupyter to continue the process but not in vscode. Would it be possible to show the box like the one on shown in the 2nd pic of original post?

**Comment by mrcmoresi** [comment] 2023-05-03 13:43
> I have encountered the same issue and here is my workaround:
> 
> 1. Run the connect code, your browser will open a page to sign in to the SSO, and then jump to a page that has URL starts with "localhost:xxxxx'. （this is the URL you copied into the input box in jupyter)
> 2. Go back to vscode, there is a port forwarding page next to terminal window.  Manually setup port forwarding to be the same as the one you see on SSO page.
> 3. Once port forwarding is ready, go back to your browser and refresh the SSO page.
> 4. Go back to vscode, your connection should be ready in a few second.
> 
> I guess there might be an issue with auto port forwarding. @DonJayamanne, would you mind to re-open this issue and I can try pull the log you needed.

Hi @54iceblock I didn't manage to get the Port Forwarding page next to the terminal while using an Azure ML VM. By any chance did you use this type of VM?

**Comment by 54iceblock** [comment] 2023-05-03 16:02
> > I have encountered the same issue and here is my workaround:
> > 
> > 1. Run the connect code, your browser will open a page to sign in to the SSO, and then jump to a page that has URL starts with "localhost:xxxxx'. （this is the URL you copied into the input box in jupyter)
> > 2. Go back to vscode, there is a port forwarding page next to terminal window.  Manually setup port forwarding to be the same as the one you see on SSO page.
> > 3. Once port forwarding is ready, go back to your browser and refresh the SSO page.
> > 4. Go back to vscode, your connection should be ready in a few second.
> > 
> > I guess there might be an issue with auto port forwarding. @DonJayamanne, would you mind to re-open this issue and I can try pull the log you needed.
> 
> Hi @54iceblock I didn't manage to get the Port Forwarding page next to the terminal while using an Azure ML VM. By any chance did you use this type of VM?
> 
> ![image](https://user-images.githubusercontent.com/12852824/235936221-5afe2d53-fe13-4a01-bac8-2cb142aeb61d.png)

Nope, I'm using cortex lab.  
1. Could you try right click on "OUTPUT" and see if "port" is not checked
2. Hit F1 and then type 'port', see if you have option "forward a port" available

I think port is associated with the remote extension, you might want to play with the extension a bit if none of the solution above works.

**Comment by mrcmoresi** [comment] 2023-05-04 07:00
> > > I have encountered the same issue and here is my workaround:
> > > 
> > > 1. Run the connect code, your browser will open a page to sign in to the SSO, and then jump to a page that has URL starts with "localhost:xxxxx'. （this is the URL you copied into the input box in jupyter)
> > > 2. Go back to vscode, there is a port forwarding page next to terminal window.  Manually setup port forwarding to be the same as the one you see on SSO page.
> > > 3. Once port forwarding is ready, go back to your browser and refresh the SSO page.
> > > 4. Go back to vscode, your connection should be ready in a few second.
> > > 
> > > I guess there might be an issue with auto port forwarding. @DonJayamanne, would you mind to re-open this issue and I can try pull the log you needed.
> > 
> > 
> > Hi @54iceblock I didn't manage to get the Port Forwarding page next to the terminal while using an Azure ML VM. By any chance did you use this type of VM?
> > ![image](https://user-images.githubusercontent.com/12852824/235936221-5afe2d53-fe13-4a01-bac8-2cb142aeb61d.png)
> 
> Nope, I'm using cortex lab.
> 
> 1. Could you try right click on "OUTPUT" and see if "port" is not checked
> 2. Hit F1 and then type 'port', see if you have option "forward a port" available
> 
> I think port is associated with the remote extension, you might want to play with the extension a bit if none of the solution above works.

Thanks for your answer, unfortunately, none of the options 1 and 2 worked. Looks like it's a problem with the Azure Machine Learning - Remote extension which is not letting me forward the ports.

**Comment by 54iceblock** [comment] 2023-05-12 23:52
> 

you can also try paste the URL direct in the terminal, at least it works for me.

**Comment by mrcmoresi** [comment] 2023-05-15 07:32
> > 
> 
> you can also try paste the URL direct in the terminal, at least it works for me.

When I run the cell to establish the connection, the terminal is not showing anything related to an input
![image](https://github.com/microsoft/vscode-jupyter/assets/12852824/7ba749eb-a8f4-4f85-ba83-ec360cf18558)

**Comment by 54iceblock** [comment] 2023-05-19 16:16
> 

I know, but can you try paste it?  that works for me with python directly or via jupyter when sshed into remote cortex machine using remote-ssh extension.

**Comment by mrcmoresi** [comment] 2023-05-25 10:36
I tried it but unfortunately didn't work.

**Comment by DonJayamanne** [comment] 2023-09-02 12:37
@mrcmoresi Is this still an issue?

**Comment by mrcmoresi** [comment] 2023-09-03 15:48
Hi @DonJayamanne 
unfortunately yes, I kept trying different things and nothing worked out.

**Comment by DonJayamanne** [comment] 2023-10-17 02:46
Closing this issue for now, as its now possible for extension authors to create custom extensions that contribute Jupyter servers with custom authentication
I.e. one can create an extension that merely provides the jUpyter server URI and the auth information (allowing 3rd party extension to be responsiblel for auth)

https://code.visualstudio.com/updates/v1_83#_finalized-jupyter-server-provider-api-for-extension-authors

**Closed by DonJayamanne** 2023-10-17 02:46 UTC
Labels: bug, notebook-remote, help-wanted
