### ISSUE TITLE
Invalid character "\u21" in token

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-jupyter#8055] opened 2021-10-26 18:45 UTC
Testing #8024

![image](https://user-images.githubusercontent.com/6561887/138941427-ea8bf9db-e6d5-400d-9c76-10be9abcedc4.png)

Firstly, I don't expect the error since this cell runs. Secondly, the character is cryptic.

**Comment by rchiodo** [comment] 2021-11-10 20:57
Moving this out of November. This would have to be handled by pylance as the file is a python file.

**Comment by IanMatthewHuff** [comment] 2022-11-04 18:37
Dupe of #5800 for pylance needed to recognize ipython syntax in files.

**Closed by IanMatthewHuff** 2022-11-04 18:37 UTC
Labels: bug, notebook-intellisense, upstream-pylance
