### ISSUE TITLE
List running kernels and ability to kill running kernels

### ISSUE THREAD

**Issue by LeanderK** [microsoft/vscode-jupyter#13615] opened 2023-05-31 09:18 UTC
Currently there's no way to list all running kernels and kill selected kernels.

Sometimes I have a lot of notebooks open with some clogging resources after a few hours of work in different notebooks. It is a pain to manually go through each notebook to see whether it's open and manually restart them so that they free up their resources. It can be a really simple UI, but a list of running kernels would be immensely useful for me.

**Comment by DonJayamanne** [comment] 2023-10-27 05:36
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1378

**Closed by DonJayamanne** 2023-10-27 05:36 UTC
Labels: feature-request
