### ISSUE TITLE
Julia exception text isn't printed in the cell output

### ISSUE THREAD

**Issue by green-nsk** [microsoft/vscode-jupyter#8100] opened 2021-10-29 16:49 UTC
See the screenshot -- I only get the stacktrace, but not the message itself.

## Environment data

-   VS Code version: 1.61.2 (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

Jupyter Notebook Renderers v1.0.3
Julia Extention: v1.4.3
Julia version: 1.6.2

Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

## Expected behaviour

Prints "ERROR: message" and then stacktrace

## Actual behaviour

Prints just stacktrace
![image](https://user-images.githubusercontent.com/8025586/139472982-6f2b3f45-50b3-4e24-b0f8-bb20891d8e1e.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a Julia Jupyter notebook
2. run a cell `throw("error")`

## Logs

Nothing relevant is printed in the "Output" panel
<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Info 2021-10-29 13:25:27: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 2021-10-29 13:25:27: ZMQ install verified.
Info 2021-10-29 13:25:28: Find preferred kernel for file:///home/sfokin/code/1Scratch/test.ipynb with metadata {"orig_nbformat":4,"language_info":{"name":"plaintext"}} & preferred interpreter {}
Info 2021-10-29 13:25:28: Find kernel spec, Class name = x, completed in 1203ms, has a falsy return value, Arg 1: <Uri:/home/sfokin/code/1Scratch/test.ipynb>, Arg 2: {"orig_nbformat":4,"language_info":{"name":"plaintext"}}, Arg 3: {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}}}, Return Value: undefined
Info 2021-10-29 13:27:07: No controller, hence notebook communications cannot be initialized for editor file:///home/sfokin/code/1Scratch/test.ipynb
Info 2021-10-29 14:14:27: No controller, hence notebook communications cannot be initialized for editor file:///home/sfokin/code/1Scratch/test.ipynb
Info 2021-10-29 15:25:28: No controller, hence notebook communications cannot be initialized for editor file:///home/sfokin/code/Tutorials/market_signals.ipynb
Info 2021-10-29 15:25:28: Find preferred kernel for file:///home/sfokin/code/Tutorials/market_signals.ipynb with metadata {"kernelspec":{"display_name":"Julia 1.5.2","language":"julia","name":"julia-1.5"},"language_info":{"file_extension":".jl","mimetype":"application/julia","name":"julia","version":"1.5.2"}} & preferred interpreter {}
Info 2021-10-29 15:25:28: Find kernel spec, Class name = x, completed in 3ms, has a falsy return value, Arg 1: <Uri:/home/sfokin/code/Tutorials/market_signals.ipynb>, Arg 2: {"kernelspec":{"display_name":"Julia 1.5.2","language":"julia","name":"julia-1.5"},"language_info":{"file_extension":".jl","mimetype":"application/julia","name":"julia","version":"1.5.2"}}, Arg 3: {"_isCancelled":false,"_emitter":{"_disposed":false,"_listeners":{"_first":{"next":{},"prev":{}},"_last":{"next":{},"prev":{}},"_size":1}}}, Return Value: undefined
Info 2021-10-29 15:37:10: Loading webview. View is notset
Info 2021-10-29 15:37:10: Loading web view...
Info 2021-10-29 15:37:10: Webview panel created.
Info 2021-10-29 15:37:14: Web view react rendered
Info 2021-10-29 15:37:28: Searching for token colors ...
Info 2021-10-29 15:37:28: Attempting search for colors ...
Warn 2021-10-29 15:37:28: Color theme Default Dark+ not found. Using default colors.
Info 2021-10-29 15:37:28: Attempting search for colors ...
Warn 2021-10-29 15:37:28: Color theme Default Dark+ not found. Using default colors.
Info 2021-10-29 15:39:50: No controller, hence notebook communications cannot be initialized for editor file:///home/sfokin/code/Tutorials/market_signals.ipynb
Info 2021-10-29 18:00:34: No controller, hence notebook communications cannot be initialized for editor file:///home/sfokin/code/Tutorials/market_signals.ipynb
Info 2021-10-29 18:28:25: No controller, hence notebook communications cannot be initialized for editor file:///home/sfokin/code/Tutorials/market_signals.ipynb
Info 2021-10-29 18:43:39: Searching for token colors ...
Info 2021-10-29 18:43:39: Attempting search for colors ...
Warn 2021-10-29 18:43:39: Color theme Default Dark+ not found. Using default colors.
Info 2021-10-29 18:43:39: Attempting search for colors ...
Warn 2021-10-29 18:43:39: Color theme Default Dark+ not found. Using default colors.
```

</p>
</details>

**Comment by claudiaregio** [comment] 2021-10-29 20:27
Hi @green-nsk, are you using the Julia extension?

**Comment by green-nsk** [comment] 2021-10-31 15:02
Yes, as per above

Julia Extention: v1.4.3
Julia version: 1.6.2

**Comment by DonJayamanne** [comment] 2021-10-31 15:57
Closing as a duplicate of an issue in the Julia extension
https://github.com/julia-vscode/julia-vscode/issues/2326

Fyi, Julia extension needs to update some api, hopefully they'll release a new version as soon as vscode is released

**Closed by DonJayamanne** 2021-10-31 15:57 UTC
Labels: bug, info-needed, needs-triage
