### ISSUE TITLE
Inredibly slow Python notebooks

### ISSUE THREAD

**Issue by thistlillo** [microsoft/vscode-jupyter#12404] opened 2022-12-14 15:51 UTC
Latest VSC + Python Notebooks are incredibly slow. 

This is a new installation on (unfortunately) Windows 11 Pro, the kernel corresponds to an Anaconda environment. This machine is more powerful than that I am used to, but the Jupyter experience is bad, too slow.

**What do I need to check to speed up Jupyter in VSC?** 

These imports:
```
from cycler import cycler
import matplotlib as mpl
from matplotlib import rc
import matplotlib.pyplot as plt
import numpy as np
from numpy import count_nonzero as nnz
import os
import pandas as pd
from posixpath import join
```
take up to 1 minute. In this screenshot 47 seconds.

![image](https://user-images.githubusercontent.com/6717655/207642628-3f6f441d-2148-440d-920e-4df195754d56.png)

The same imports in the Anaconda prompt are instantaneous.

Details:
```
Python 3.9.15
```

```
Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```

Python VSC extension (by Microsoft): `v2022.20.1`
Jupyter: `v2022.11.1003412109`
Anaconda: `conda 22.11.0`  (miniconda)

**Comment by DonJayamanne** [comment] 2022-12-14 20:56
thanks for filling this issue. 

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by himmetozcan** [comment] 2022-12-17 08:30
This problem is destroying me all the time. sometimes it just prints hello world in 45 seconds. So annoying

**Comment by DonJayamanne** [comment] 2022-12-18 00:10
@himmetozcan 
I'm sorry to hear this, so we can help you, please could you provide them information requested (see previous post)

**Comment by bosmart** [comment] 2023-01-04 21:06
I have the same problem , makes VS Code unusable for Notebooks, which is a real shame as the VS Code debugger is great :(

**Comment by DonJayamanne** [comment] 2023-01-04 22:12
@bosmart 
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by bosmart** [comment] 2023-01-05 06:21
@DonJayamanne 
You mean `jupyter.logging.level`? If so, I tried that and nothing new appeared in the Jupyter Output window while the cell with the print statement was executing for 2 minutes. Will try again but is there any other logging I can enable?

**Comment by DonJayamanne** [comment] 2023-01-05 07:44
> and nothing new appeared in the Jupyter Output window while the cell with the print 

Please send the logs, there could be an indication why it is slow

**Comment by bosmart** [comment] 2023-01-05 14:13
Rather annoyingly, I seem to be unable to reproduce for the past 6 hours but I'm sure it will come back because it did come back in the past - will send over the logs the moment it happens!

**Comment by bosmart** [comment] 2023-01-06 19:19
@DonJayamanne it just happened again, log attached below:

`info 19:01:37.276: Restart kernel execution
info 19:01:37.276: Restart requested file:///storage/m/rn.ipynb
info 19:01:37.276: Restarting fc40eff7-83b4-44aa-bb1a-db78fcb90d2c
info 19:01:37.299: Process Execution: > /usr/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /usr/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 19:01:37.336: Process Execution: > /usr/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9019 --control=9017 --hb=9016 --Session.signature_scheme="hmac-sha256" --Session.key=b"27e37dca-a54d-42a6-9051-e75b7d13c7a5" --shell=9018 --transport="tcp" --iopub=9020 --f=/root/.local/share/jupyter/runtime/kernel-v2-14407K5rGGh4XdVL.json
> /usr/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9019 --control=9017 --hb=9016 --Session.signature_scheme="hmac-sha256" --Session.key=b"27e37dca-a54d-42a6-9051-e75b7d13c7a5" --shell=9018 --transport="tcp" --iopub=9020 --f=/root/.local/share/jupyter/runtime/kernel-v2-14407K5rGGh4XdVL.json
info 19:01:37.336: Process Execution: cwd: /storage/m
cwd: /storage/m
info 19:01:37.471: ipykernel version & path 6.19.4, /usr/local/lib/python3.10/dist-packages/ipykernel/__init__.py for /usr/bin/python3
info 19:01:37.616: Got empty env vars with python /usr/bin/python3 in 339ms
info 19:01:37.658: Got empty env vars with python /usr/bin/python3 in 343ms
info 19:01:37.659: Got empty env vars with python /usr/bin/python3 in 344ms
warn 19:01:37.921: StdErr from Kernel Process /usr/local/lib/python3.10/dist-packages/traitlets/traitlets.py:2547: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(

warn 19:01:37.921: StdErr from Kernel Process /usr/local/lib/python3.10/dist-packages/traitlets/traitlets.py:2498: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '27e37dca-a54d-42a6-9051-e75b7d13c7a5' instead of 'b"27e37dca-a54d-42a6-9051-e75b7d13c7a5"'.
  warn(

info 19:01:37.930: Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-14407K5rGGh4XdVL.json

info 19:01:37.963: Got new session 8364bdb7-ac46-4858-b95e-ea6e1889f9ae
info 19:01:37.963: Started new restart session
info 19:01:37.964: Dispose Kernel process 598047.
error 19:01:37.977: KernelDebugAdapter::handleMessage failure: Error: Canceled future for debug_request message before replies were done
info 19:01:38.138: UpdateWorkingDirectoryAndPath in Kernel
info 19:02:17.831: Cancel all remaining cells true || Error || undefined
info 19:05:08.123: Cancel all remaining cells true || Error || undefined
`

**Comment by DonJayamanne** [comment] 2023-01-06 23:37
@bosmart 
When this happens please could you send the whole lot, the partial log you sent il doesn't give enough information to figure out the issue

**Comment by bosmart** [comment] 2023-01-07 07:19
@DonJayamanne - here's the whole thing:
[vscode-jupyter-log.txt](https://github.com/microsoft/vscode-jupyter/files/10365686/vscode-jupyter-log.txt)

**Comment by DonJayamanne** [comment] 2023-01-12 18:24
Ok, looks like there is an error in one of the Python packages
```
warn 08:31:40.899: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 334, in process_control
    await result
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 951, in debug_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 493, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/debugger.py", line 665, in process_request
    self.stop()
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/debugger.py", line 408, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/debugger.py", line 254, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 668, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
```

Please could you try re-installiing ipykernel using the command `python -m pip install ipykernle --force-reinstall`
basically there are some errors in your environment.

Also looking at the logs I'm not sure whether you've provided all of the logs or if you have edited the log file, some information seems to be missing.
Or it seems you are running a cell and then stopping it immediately.
It would help if you re-load VS Code (as mentioned here https://github.com/microsoft/vscode-jupyter/issues/12404#issuecomment-1352162384) when providing the logs, else we have logs from previous sessions where you are trying different things and it gets in the way of trying to figure out what is goning on.

I'm closing this issue as the original request for information has was requested over 4 weeks ago and the previous issue with zmq is different and is an environment issue (problem with packages on end user machine)

**Closed by DonJayamanne** 2023-01-12 18:24 UTC
Labels: info-needed, notebook-kernel, perf, notebook-getting-started
