### ISSUE TITLE
`raises-exception` cell metadata tag not honored by notebook runtime

### ISSUE THREAD

**Issue by JPvRiel** [microsoft/vscode-jupyter#11441] opened 2022-09-25 14:42 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

As per [ms-toolsai.vscode-jupyter-cell-tags](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-cell-tags), I was finally able to tag a cell with `raises-exception`. However, while this works as expected in the standard jupyter notebook runtime, it does not work for notebooks run in vscode.

It's not the best documented metadata tag feature, but there are some examples showing that it appears fairly conventional:

- [Troubleshooting Errors and Exceptions in Jupyter Notebooks](https://docs.qubole.com/en/latest/troubleshooting-guide/jupy-notebook-ts/troubleshoot-jupy-notebook.html)
- [Ignoring Errors on a Per-Cell Basis](https://nbsphinx.readthedocs.io/en/0.5.0/allow-errors-per-cell.html#Ignoring-Errors-on-a-Per-Cell-Basis)
- [stackoverflow.com: Jupyter magic to handle notebook exceptions comment](https://stackoverflow.com/a/61964142/5472444)

### VS Code Version

1.71.2

### Jupyter Extension Version

v2022.8.1002431955

### Jupyter logs

```shell
N/A.
```

### Coding Language and Runtime Version

Python 3.10.7

### Language Extension Version (if applicable)

Python (v2022.14.0)

### Running Jupyter locally or remotely?

Local

### Related

- <https://github.com/microsoft/vscode-jupyter/issues/1182>

**Comment by DonJayamanne** [comment] 2022-09-25 22:27
Thanks for filing this issue, however this isn't a standard feature, its more of a custom feature added specifically for nbsphinx users. 
However given the fact that this works in Jupyter Lab and Jupyter Notebook, we'll look into this.

Note for internal references:
* https://github.com/jupyterlab/jupyterlab/pull/6424
* https://github.com/jupyterlab/jupyterlab/issues/7015

**Comment by BlankAmber** [comment] 2023-11-12 00:44
I can confirm this occurs in VS Code 1.84.0 and extension version v2023.10.1003070148 with Python version 3.11.5.

**Comment by DonJayamanne** [comment] 2023-12-03 22:56
Closing this issue as out of scope, as this issue hasn't received sufficient upvotes and from what I can tell, only 2 users have run into this in the past year.

**Comment by EliahKagan** [comment] 2023-12-03 23:22
I'm not sure if this is relevant to the issue's scope or not, but this issue prevents me from using VS Code with Jupyter notebooks in a range of situations that I find important, as well as from gaining the full benefit of Jupyter's functionality in other cases (because I cannot readily show in a notebook how particular code produces a particular exception, in a way that looks like what people actually see when they get that exception in a notebook). In particular, this impacts the usability of Jupyter notebooks in VS Code [for teaching](https://github.com/EliahKagan/palgoviz/blob/main/doc/using-notebooks.md#notebooks-in-vs-code).

To be clear, I don't know how commonly used the `raises-exception` tag is. As such, I do not have a firm opinion as to whether this issue should be considered in scope or not. I know that, for me, a fix for this would be a substantial quality improvement.

**Closed** 2023-12-04 01:49 UTC
Labels: notebook-kernel, notebook-execution, works-in-jupyter, feature-request, *out-of-scope
