### ISSUE TITLE
Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.77.3'.

### ISSUE THREAD

**Issue by bverhoeff** [microsoft/vscode-jupyter#13359] opened 2023-04-20 07:45 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Can't install:
Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.77.3'.

### VS Code Version

Code '1.77.3'

### Jupyter Extension Version

ms-toolsai.jupyter-2023.4.1001111035

### Jupyter logs

```shell
n.a.
```

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by bverhoeff** [comment] 2023-04-22 08:37
Tested on both windows 11 and windows server 2016 standard with vscode 1.77.3.

I wonder, did someone else experience this fail?

**Comment by nevdelap** [comment] 2023-04-22 12:06
On Linux, yes, but with code-server, so don't know if that's considered supported, but it is the same error.

`Error: Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.77.3'.`

**Comment by DonJayamanne** [comment] 2023-04-24 06:39
Duplicate of https://github.com/microsoft/vscode/issues/180671

**Comment by nevdelap** [comment] 2023-09-24 04:51
Hi @DonJayamanne. Do you know, why is a 'pre-release' version alway the latest version available in the marketplace? I mean, why doesn't that fact that it is in the martetplace not mean that it is 'released'? I've installed VSCode 1.82.2 and none of the versions available in the marketplace are compatible, (though they are several versions over only a short few days, so maybe they are all pre-release versions?). 😕

**Comment by DonJayamanne** [comment] 2023-09-24 23:45
Duplciate of https://github.com/microsoft/vscode/issues/192738

**Closed by DonJayamanne** 2023-09-24 23:45 UTC
Labels: bug
