### ISSUE TITLE
Unable to use Julia kernel without python installation

### ISSUE THREAD

**Issue by jlperla** [microsoft/vscode-jupyter#3971] opened 2020-11-19 05:45 UTC
## Environment data
Version: 1.52.0-insider (user setup)
Commit: 78908e7eb4ff12fc2ed0dd1f17200fea48c56ab2
Date: 2020-11-18T12:38:39.842Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

-   VS Code version: 1.52.0-insider (user setup)
-   Extension version (available under the Extensions sidebar): v2020.11.358541065
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.358541065
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour
Julia Kernel should work without Python extension, if I understand it correctly?

## Actual behaviour

Have preexisting vscode, jupyter via conda, julia, python, etc. which are all working.

Trying to follow https://github.com/microsoft/vscode-jupyter#quick-start

1. Installed VSCode Insiders.
  - Set to "weekly" insider updates, though that doesn't seem to matter.

2. Installed the jupyter extension and **no other extensions**.  In particular not python or julia, which shouldn't be needed.

See attached 
![image](https://user-images.githubusercontent.com/13106721/99625264-b6bc2d00-29e4-11eb-904f-2e55388a3e4a.png)

3. Checked that the kernelspec is there.  It is in the image above, but it is in `C:\Users\jlperla\AppData\Roaming\jupyter\kernels\julia-1.5\kernel.json` with contents
```json
{
  "display_name": "Julia 1.5.2",
  "argv": [
    "C:\\Users\\jlperla\\AppData\\Local\\Programs\\Julia 1.5.2\\bin\\julia.exe",
    "-i",
    "--startup-file=yes",
    "--color=yes",
    "--project=@.",
    "C:\\Users\\jlperla\\.julia\\packages\\IJulia\\rWZ9e\\src\\kernel.jl",
    "{connection_file}"
  ],
  "language": "julia",
  "env": {},
  "interrupt_mode": "message"
}
```
Furthermore, I have checked that it working correctly in jupyter.
4. I create a new jupyter notebook, and it asks to install python extension:
![image](https://user-images.githubusercontent.com/13106721/99625519-4b268f80-29e5-11eb-9a14-823f9819fe55.png)
- I say no to both.

5. I go `> Jupyter: Select Kernel ` 
![image](https://user-images.githubusercontent.com/13106721/99625722-b7a18e80-29e5-11eb-81ea-a6d92b640e31.png)

- I choose the Julia kernel, which matches the one I had tested.

- Nothing seems to happen.  In particular, it doesn't show any kernels on the bottom.

6. I also try to add in a simple cell that just goes `3 + 4`, and choose `Julia` as the language type

7. When I try to execute the cell, it says `Select a Notebook Kernel to run this notebook`, but it doesn't let me choose any...  I tried t type the `Julia 1.5.2` kernel name, but that doesn't help.

## Logs
<summary>Output for <code>Log (Extension Host)</code>
</summary>

<p>

```
[2020-11-18 21:10:15.574] [exthost] [info] extension host started
[2020-11-18 21:10:15.608] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2020-11-18 21:10:15.608] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/microsoft-authentication/dist/extension.js
[2020-11-18 21:10:15.623] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-11-18 21:10:15.624] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/debug-auto-launch/dist/extension
[2020-11-18 21:10:15.630] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-11-18 21:10:15.630] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2020-11-18 21:10:15.644] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-11-18 21:10:15.644] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/git/dist/main
[2020-11-18 21:10:15.665] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-11-18 21:10:15.665] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2020-11-18 21:10:15.672] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-11-18 21:10:15.672] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/search-result/dist/extension.js
[2020-11-18 21:10:15.676] [exthost] [info] ExtensionService#_doActivateExtension streetsidesoftware.code-spell-checker {"startup":true,"extensionId":{"value":"streetsidesoftware.code-spell-checker","_lower":"streetsidesoftware.code-spell-checker"},"activationEvent":"*"}
[2020-11-18 21:10:15.676] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/.vscode-insiders/extensions/streetsidesoftware.code-spell-checker-1.9.4/dist/extension.js
[2020-11-18 21:10:15.698] [exthost] [info] ExtensionService#_doActivateExtension zhuangtongfa.material-theme {"startup":true,"extensionId":{"value":"zhuangtongfa.material-theme","_lower":"zhuangtongfa.material-theme"},"activationEvent":"*"}
[2020-11-18 21:10:15.698] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/.vscode-insiders/extensions/zhuangtongfa.material-theme-3.9.6/out/extension.js
[2020-11-18 21:10:15.894] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2020-11-18 21:10:15.894] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2020-11-18 21:10:16.373] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-11-18 21:10:16.374] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/github/dist/extension.js
[2020-11-18 21:10:16.419] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2020-11-18 21:10:16.419] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/github-authentication/dist/extension.js
[2020-11-18 21:10:16.438] [exthost] [info] eager extensions activated
[2020-11-18 21:10:16.447] [exthost] [info] ExtensionService#_doActivateExtension eamodio.gitlens {"startup":false,"extensionId":{"value":"eamodio.gitlens","_lower":"eamodio.gitlens"},"activationEvent":"onStartupFinished"}
[2020-11-18 21:10:16.447] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/.vscode-insiders/extensions/eamodio.gitlens-11.0.1/dist/gitlens
[2020-11-18 21:10:16.522] [exthost] [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github {"startup":false,"extensionId":{"value":"GitHub.vscode-pull-request-github","_lower":"github.vscode-pull-request-github"},"activationEvent":"onStartupFinished"}
[2020-11-18 21:10:16.522] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/.vscode-insiders/extensions/github.vscode-pull-request-github-0.21.0/media/extension
[2020-11-18 21:10:16.566] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode-remote.remote-wsl {"startup":false,"extensionId":{"value":"ms-vscode-remote.remote-wsl","_lower":"ms-vscode-remote.remote-wsl"},"activationEvent":"onStartupFinished"}
[2020-11-18 21:10:16.567] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/.vscode-insiders/extensions/ms-vscode-remote.remote-wsl-0.51.3/dist/extension
[2020-11-18 21:10:17.973] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2020-11-18 21:10:17.973] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2020-11-18 21:10:17.982] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2020-11-18 21:10:17.982] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain
[2020-11-18 21:10:18.002] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:jsonc"}
[2020-11-18 21:10:18.002] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/typescript-language-features/dist/extension
[2020-11-18 21:10:30.036] [exthost] [info] extension host started
[2020-11-18 21:10:30.063] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2020-11-18 21:10:30.063] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/microsoft-authentication/dist/extension.js
[2020-11-18 21:10:30.077] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2020-11-18 21:10:30.077] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/debug-auto-launch/dist/extension
[2020-11-18 21:10:30.082] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2020-11-18 21:10:30.083] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2020-11-18 21:10:30.097] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-11-18 21:10:30.097] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/git/dist/main
[2020-11-18 21:10:30.121] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2020-11-18 21:10:30.121] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2020-11-18 21:10:30.126] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2020-11-18 21:10:30.126] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/search-result/dist/extension.js
[2020-11-18 21:10:30.219] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2020-11-18 21:10:30.219] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2020-11-18 21:10:30.326] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-11-18 21:10:30.326] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/github/dist/extension.js
[2020-11-18 21:10:30.337] [exthost] [info] eager extensions activated
[2020-11-18 21:10:30.337] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2020-11-18 21:10:30.337] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/github-authentication/dist/extension.js
[2020-11-18 21:12:40.369] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:json"}
[2020-11-18 21:12:40.369] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2020-11-18 21:12:40.376] [exthost] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"extensionId":{"value":"vscode.extension-editing","_lower":"vscode.extension-editing"},"activationEvent":"onLanguage:json"}
[2020-11-18 21:12:40.376] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/extension-editing/dist/extensionEditingMain
[2020-11-18 21:12:40.403] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:json"}
[2020-11-18 21:12:40.403] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain
[2020-11-18 21:12:40.423] [exthost] [info] ExtensionService#_doActivateExtension vscode.npm {"startup":false,"extensionId":{"value":"vscode.npm","_lower":"vscode.npm"},"activationEvent":"onLanguage:json"}
[2020-11-18 21:12:40.424] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/npm/dist/npmMain
[2020-11-18 21:29:09.253] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter {"startup":false,"extensionId":{"value":"ms-toolsai.jupyter","_lower":"ms-toolsai.jupyter"},"activationEvent":"onCommand:jupyter.createnewnotebook"}
[2020-11-18 21:29:09.253] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.11.358541065/out/client/extension
[2020-11-18 21:29:11.549] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:jsonc"}
[2020-11-18 21:29:11.549] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/typescript-language-features/dist/extension
[2020-11-18 21:29:11.774] [exthost] [info] ExtensionService#_doActivateExtension vscode.python {"startup":false,"extensionId":{"value":"vscode.python","_lower":"vscode.python"},"activationEvent":"onLanguage:python"}
[2020-11-18 21:29:11.775] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/jlperla/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/python/dist/pythonMain


```

</p>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'NativeNotebookEditor'

```

</p>
</details>

**Comment by DonJayamanne** [comment] 2020-11-19 16:34
Thanks for filling this issues.
We have identified this issue and resolved it. The fix will be in the next release (December). 
Closing as a dupe of https://github.com/microsoft/vscode-jupyter/issues/1074

**Closed by DonJayamanne** 2020-11-19 16:34 UTC
Labels: bug

**Comment by jlperla** [comment] 2020-11-19 17:01
Sounds great.  Will this show up in the weekly or daily insider updates before December?

**Comment by DonJayamanne** [comment] 2020-11-19 18:25
> Will this show up in the weekly or daily insider updates before December?

We're planning on shipping this fix some time early next week (as a point fix, hopefully as early as monday).
