### ISSUE TITLE
Not getting reprompted about missing ipykernel when running a cell in a Python file

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode-jupyter#9453] opened 2022-03-22 23:24 UTC
Testing #9434

- Create a blank Python file in an folder with a virtual environment with no ipykernel (any type: pip, conda or poetry)
- Add a cell with a `print` statement
- Click on `Run Cell`
- Click `Cancel` on the prompt
- Click on `Run Cell` again, observe that there is no new prompt appearing

https://user-images.githubusercontent.com/51720070/159592356-eb5cd6e4-c4c7-455b-b9cc-dd87db82867c.mp4

**Comment by rchiodo** [comment] 2022-03-23 00:27
Thanks. This should be a dupe of https://github.com/microsoft/vscode-jupyter/issues/9444

**Closed by rchiodo** 2022-03-23 00:27 UTC
Labels: needs-triage
