### ISSUE TITLE
"Z" binding of "undo" command is firing in a Markdown file

### ISSUE THREAD

**Issue by gussmith23** [microsoft/vscode-jupyter#4547] opened 2021-01-28 19:00 UTC
## Environment data

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z (1 mo ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

-   VS Code version: see above
-   Jupyter Extension version (available under the Extensions sidebar): v2021.1.515826627
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: see above
-   Python and/or Anaconda version: Python 3.7.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): none
-   Jupyter server running: not running

## Expected behaviour

Typing "z" in a markdown file types the letter z.

## Actual behaviour

Either nothing happens (no character is typed), or a z will be typed and subsequently disappear, or no z will be typed and previous characters will be deleted as well.

## Steps to reproduce:

With Jupyter extension enabled, type "z" in markdown buffer. I'm sure there's more happening behind the scenes here, but I have no idea what caused my vscode to get in this state!

## Logs

Jupyter isn't running when this happens!

**Comment by gussmith23** [comment] 2021-01-28 19:06
I tracked this down to the Jupyter extension by disabling extensions one-by-one, FWIW, and then deleting the "z" keybinding once I discovered it. I feel like this keybinding (and its when condition) is very likely the culprit, but let me know if you want me to test something else!

**Comment by rchiodo** [comment] 2021-01-28 19:42
Thanks for the bug. This is definitely not intended. That should only apply to notebooks, not markdown files.

**Comment by rchiodo** [comment] 2021-01-28 19:43
I can't seem to repro. What extension is your markdown file using?

**Comment by gussmith23** [comment] 2021-02-08 19:05
I'm using both Markdown All In One 3.4.0 (Yu Zhang) and markdownlint 0.38.0
(David Anson)

>

**Comment by rchiodo** [comment] 2021-02-09 21:20
Sorry I meant what is the extension of your markdown file? Is it '.md'?

**Comment by gussmith23** [comment] 2021-02-09 21:25
ah, yes it is!

**Comment by rchiodo** [comment] 2021-02-17 00:34
Sorry I still can't repro (even with your two markdown extensions installed).

Do you have a contained folder (with settings.json) that you could zip up and upload here?

**Comment by rchiodo** [comment] 2021-02-17 18:29
@IanMatthewHuff  has been doing some investigation into a similar problem here:
https://github.com/microsoft/vscode-jupyter/issues/4527

That might be the same root cause. It only repros for him so it explains why I can't repro your problem.

**Comment by rchiodo** [comment] 2021-02-18 00:43
We believe this has been fixed in our latest release.

**Closed by rchiodo** 2021-02-18 00:43 UTC
Labels: bug, info-needed

**Comment by gussmith23** [comment] 2021-03-15 16:04
Thanks Rich! Sorry for going AWOL, glad this is fixed.
