### ISSUE TITLE
Take 2: Testing adoption of the new Python Extension API for discovering Python Environments

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#11851] opened 2022-10-31 21:43 UTC
Testing adoption of the new Python Extension API for discovering Python Environments

Refs: #7583

- [ ] MacOS @IanMatthewHuff 
- [x] anyOS @rebornix 
- [x] Windows @amunger 
- [ ] WSL @roblourens 

Complexity: 5

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2311755%0A%0A&assignees=DonJayamanne)

---

### Pre-Test
* Keep track of the kernels displayed in the kernel picker

### Requirements

- Install pre-release Jupyter extension
- Install pre-release Python extension
- Install VS Code Insiders

### Scenarios to test
* [ ] Verify the same kernels (kernel specs and Python environments) are still displayed in the kernle picker
* [ ] New Virtual environments are detected and displayed in the Kernel picker
    Note: You need to have already executed a cell in some notebook
    Then create a virtual environment within VS Code
    I.e. the goal is to test detection of new virtual envs after the extension has been used for a while
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running a Notebook cell against this kernel
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running an Interactive Window cell such a new Python Environment (either re-create a new env or uninstall IPyKernel)
    * [ ] Verify you are prompted to install Pandas data frame into this Python enviornment when using the Data Frame viewer 
    To test this, create a few variables, at least one with a list e.g. `a = [1,2,3]` and use the variable viewer to open the variable `a`
* [ ] New Conda environments are detected and displayed in the Kernle picker
    Note: You need to have already executed a cell in some notebook
    Then create a conda environment within VS Code
    I.e. the goal is to test detection of new virtual envs after the extension has been used for a while
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running a Notebook cell against this kernel
    * [ ] Verify you are prompted to install IPyKernel into this Python enviornment when running an Interactive Window cell such a new Python Environment (either re-create a new env or uninstall IPyKernel)
    * [ ] Verify you are prompted to install Pandas data frame into this Python enviornment when using the Data Frame viewer 
    To test this, create a few variables, at least one with a list e.g. `a = [1,2,3]` and use the variable viewer to open the variable `a`
* [ ] Re-load VS Code and verify you can pick a Kernel Spec before Python environments
    I'm hoping some machines are slow enough and we can see Kernel Specifications before Python environments in the kernel picker.
    In the past we regressed in this space and Jupyter extension waited for ALL python environnents to be loaded before displaying Kernel Specs on disc.
    We're verifyhing the fact that some kernels will appear before others
* [ ] Verify local kernel specs appera before Remote Kernel specs
    Connect to a local Jupyter server after having started a jupyter server using `jupyter notebook --no-browser --NotebookApp.allow_origin=*`
    In the past we regressed in this space and Jupyter extension waited for ALL python environnents to be loaded before displaying Kernel Specs on disc.
    We're verifyhing the fact that some kernels will appear before others
* [ ] Verify debugging works and uses the right Python environment

* [ ] Test other parts of the extension that you believe could be impacted by adopting the new Python Extension API

**Comment by IanMatthewHuff** [comment] 2022-10-31 22:28
Note: Since @rebornix and I were chatting about it, I tested without Python extension installed and it worked as expected.

**Comment by amunger** [comment] 2022-10-31 22:34
LGTM - far better performance and I didn't notice any new regressions.

**Comment by IanMatthewHuff** [comment] 2022-10-31 22:36
Hmm, I'm not getting new Venvs to show up after I create them.

**Comment by amunger** [comment] 2022-10-31 22:38
are you creating them in the workspace? Do they show up in Python's select interpreter list?

**Comment by IanMatthewHuff** [comment] 2022-10-31 22:44
> are you creating them in the workspace? Do they show up in Python's select interpreter list?

It's interesting. I recall on the earlier testing that they showed up in Jupyter relatively quickly. They actually did show up eventually, and I didn't need to reload the window. But they didn't show up in either the Python interpreter list or in the Jupyter list for quite a while (like ~ one minute?). Not sure what's up here, but if it wasn't in the Python list than maybe the issue is not on our side.

**Comment by roblourens** [comment] 2022-10-31 22:48
For me it picked up one new venv quickly, then I've created two more and they haven't showed up even after a reload. A new conda environment also hasn't showed up. But they do all show up in the Python interpreter list.

**Comment by roblourens** [comment] 2022-10-31 23:06
Stable picks these up, but with the vsix, I never see them

**Comment by roblourens** [comment] 2022-10-31 23:10
Oops, I am just seeing https://github.com/microsoft/vscode-jupyter/issues/11848, but is that supposed to be fixed in the vsix?

**Comment by roblourens** [comment] 2022-10-31 23:11
And what does "invalid" mean there? Do I need to install ipykernel into it manually?

**Comment by rebornix** [comment] 2022-10-31 23:14
On window/cache reloading, the vsix behaves exactly the same as Stable with my setup on macOS:

* On window reload, the full list shows quickly enough
* When Python extension is disabled, neither the stable release or the vsix showed the local kernel specs

However for creating new `venv`s, I'm seeing the same behavior as @roblourens . The virtual environment didn't show up but it showed up in VS Code Stable + Jupyter Stable + Python Prerelease. It can be a regression in Python extension or the listeners we have.

**Comment by IanMatthewHuff** [comment] 2022-10-31 23:29
So the behavior for me does seem to indicate that Python extension might be having the issue. What I see is the following.

1. create new .venv (using the terminal, not sure about the create env command)
2. .venv doesn't show up in jupyter list or python interpreter list even after a long wait
3. go to python interpreter list and refresh
4. .venv in is python interpreter list and is in jupyter interpreter list

Given that it shows up for me in Jupyter as soon as it's seen in Python I would flag that as on the Python side. But given that @roblourens was seeing differently (seeing it in the Python list but not in Jupyter) my confidence is really low here.

**Comment by roblourens** [comment] 2022-10-31 23:33
For me they showed up once I deleted a conda environment I'd created

**Comment by rebornix** [comment] 2022-10-31 23:38
What @roblourens was seeing is very likely to be https://github.com/microsoft/vscode-jupyter/issues/11848 and not included in the vsix we are testing. However what @IanMatthewHuff described seems something different.

**Comment by IanMatthewHuff** [comment] 2022-10-31 23:53
It's a bit hard to explain in person, but here is what I'm currently seeing:

https://user-images.githubusercontent.com/812783/199130485-77066066-5f94-4854-93fc-a4d66301b836.mov

**Comment by roblourens** [comment] 2022-10-31 23:53
Can we test with a vsix that includes everything?

**Comment by rebornix** [comment] 2022-11-01 03:09
I ran into an interesting scenario, and not sure what's the right behavior:

* Active python interpreter in terminal is conda python
* Run `python -m venv .testenv`
* Now the interpreter is available in Python Select Interpreter quick pick 
  * we don't show it in kernel picker with the latest vsix
  * we show this env in Stable
  * when running against the env, it will not install ipykernel successfully and show prompt about missing pip
* Create a venv from a python interepter which has pip
* Now both the vsix and Stable will show all python venvs, including `.testenv`

**Comment by roblourens** [comment] 2022-11-01 03:12
Yeah that's weird, but I guess creating a venv from inside conda might not be a normal case. Not sure how venvs normally get pip

**Comment by roblourens** [comment] 2022-11-01 03:31
I do still have the problem that no new conda environments ever show up. I assume they are "invalid" as mentioned above but I don't know what that means.

**Comment by rebornix** [comment] 2022-11-01 03:41
@roblourens that's what's being suggested by Python team that when a detected Python environment has no python interpreter it should then be removed (fixed via https://github.com/microsoft/vscode-jupyter/pull/11847). I guess you created an empty environment like `conda create --name env`, Python extension thinks it's invalid as it doesn't find python interpreter in this environment. This environment does show up in Stable and seems to have a fallback for python interpreter path.

If you try to create an environment with python, I guess it can show up `conda create --name env python=3.9.12`. However on macOS, I still can't install ipykernel in this environment so it never works for me.

**Comment by roblourens** [comment] 2022-11-01 04:01
Yeah that's what I was doing, I guess that's not right, I probably got it from stackoverflow or something

**Comment by DonJayamanne** [comment] 2022-11-27 20:06
Closing this stale issue

**Closed by DonJayamanne** 2022-11-27 20:06 UTC
Labels: testplan-item
