### ISSUE TITLE
Opening a dib file with .NET Interactive prompts the user with a suggestion to install python

### ISSUE THREAD

**Issue by colombod** [microsoft/vscode-jupyter#10968] opened 2022-07-28 16:42 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.0 -insider
- OS Version: Win11

Steps to Reproduce:

1. Setup with only .NET Interactive notebook extension
2. open a dib file (eg [this](https://github.com/dotnet/interactive/blob/main/NotebookTestScript.dib))
3. this notification will pop ![image](https://user-images.githubusercontent.com/375556/181592233-3d3ff0ce-8122-42a5-a338-9d7634f0471f.png)

**Comment by rebornix** [comment] 2022-07-28 19:32
@colombod can you help confirm if this is a regression with latest VS Code/Jupyter/Python? You can check VS Code stable and install .NET extension and see if it happens.

**Comment by rchiodo** [comment] 2022-07-28 19:37
We do trigger a python interpreter request on activation. We need this to get kernels to list in the notebook UI. However, it seems odd that asking for interpreters would then ask the user to install python. Seems like that should be a more explicit thing. Maybe a n error result from getInterpreters that says - nope, cannot because no python on box.

**Comment by rchiodo** [comment] 2022-07-28 19:38
Although why would the user have the Python extension installed anyway if they don't use python?

**Comment by colombod** [comment] 2022-07-28 20:26
In our scenario there is no python extension installed just opening a notebook with then.MET Interactive extension and the Jupyter renderers 

Dr Diego Colombo PhD

**Comment by rchiodo** [comment] 2022-07-28 20:31
There has to be a python extension installed. It's the one putting up that message.

**Comment by bpasero** [comment] 2022-08-02 08:44
Moving to August unless candidate.

**Comment by DonJayamanne** [comment] 2022-12-04 19:18
@colombod is this still an issue. 
I'm closing this issue as verification required, if the issue still persists, please re-open this issue or feel free to create a new one.

**Closed by DonJayamanne** 2022-12-04 19:18 UTC
Labels: info-needed, upstream-python, debt, iteration-candidate, kernel-picker
