### ISSUE TITLE
Launch notebook kernel in specific path in remote server mode

### ISSUE THREAD

**Issue by rogerioo** [microsoft/vscode-jupyter#8927] opened 2022-02-04 18:11 UTC
Hello guys!

I've currently changed using notebooks development in vscode and It's a very good plugin. However, I'm running my notebooks in remote server mode and **_I think it'd be a good idea to be possible to select the path, in the remote server, that you want to launch the kernel_**. Currently, I've managed to work around this by opening the notebook first in the Jupyter Notebook server, so It launch automatically a new kernel in the same path the notebook is, and then selecting It in the kernel picker.

This suggestion is because I work with files opening and I've trouble with them because the path working directory was not the same as the notebook. I know It could be fix by changing the path of the files, but I'm not the only one that uses those notebooks I'm developing and  if I change the path It would have errors when opening in Jupyter Notebook interface.

My path working directory is the same as the one the Jupyter server is running!

Thanks for the attention in advance!

**Comment by amunger** [comment] 2022-02-04 21:03
Are you using VS Code's Remote ssh extension to connect to the remote server? Would the "Notebook File Root" setting do what you're looking for? That should set the current working directory for the notebook to run in.

**Comment by rogerioo** [comment] 2022-02-04 21:16
@amunger Yes! I'm using the **Remote - SSH** extension and my workspace is in the same server as the Jupyter-Notebook server. And, in fact no.. I'm no the only one that uses the Jupyter-Notebook server and, because of that, I cannot change the  "Notebook File Root" parameter.

As It's a default behaviour of Jupyter Notebook web interface to launch the notebook kernel in the same directory of the notebook itself, I think something like that or the possibility to choose manually from the kernel picker It'd be extremely useful.

**Comment by rogerioo** [comment] 2022-02-04 21:18
@amunger I do not want to change the Jupyter Notebook entire file root, but the notebook I'm currently running.

**Comment by amunger** [comment] 2022-02-04 22:38
>  It's a default behaviour of Jupyter Notebook web interface to launch the notebook kernel in the same directory of the notebook itself

That's also the default setting for VS Code, unless I'm misunderstanding what you're trying to achieve.
This will set the working directory to the same one that contains the notebook. Is that setting being overridden in the workspace settings?
```
	// Set the root directory for running notebooks and the Interactive window.
	"jupyter.notebookFileRoot": "${fileDirname}",
```

If you're connecting to an external kernel as well (rather than just using the kernel that VS Code launches), then that's not currently supported (#8771)

**Comment by rogerioo** [comment] 2022-02-04 22:42
@amunger That's the same case of the issue you've mentioned. I've not found this issue before opening this one.

Is there anything I could provide to help this other issue?

**Comment by amunger** [comment] 2022-02-07 18:08
just give a vote for #8771 (react with a thumbs up) and commenting with your use case would be helpful to come up with the best solution. 
From what I've understood so far, you're connecting to a server with remote ssh, then connecting to a remote kernel on that same server and need the working directory to be the same in VS Code as it is on Jupyter Notebooks since the notebook is run in both places. Does that sound correct?

**Comment by marius311** [comment] 2022-02-07 19:20
> From what I've understood so far, you're connecting to a server with remote ssh, then connecting to a remote kernel on that same server and need the working directory to be the same in VS Code as it is on Jupyter Notebooks since the notebook is run in both places. Does that sound correct?

This describes my exact set up as well. I'm also finding that the kernel runs in folder `/` regardless if I set `jupyter.notebookFileRoot` to `{fileDirname}` or even to an explicit path. In addition, this doesn't change if I run VSCode locally and connect to the remote kernel, I still get a kernel in `/`. So essentially, it seems like the path for remote kernels is just inconfigurable. 

I'm on VSCode 1.63.2, vscode-jupyter v2021.11.1001550889, and in the case that I run it that way, RemoteSSH v0.70.0

**Comment by amunger** [comment] 2022-02-08 21:29
thanks for the use cases. I'm closing this as a dupe of https://github.com/microsoft/vscode-jupyter/issues/8771 so that it can be tracked in a single place. You can make sure to support that issue by voting for it.

**Closed by amunger** 2022-02-08 21:29 UTC
Labels: enhancement, info-needed
