### ISSUE TITLE
Metadata language.version extra information after opening notebook in VS Code

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-jupyter#12701] opened 2023-01-31 16:45 UTC
## Environment data

-   VS Code version: 1.74.3
-   Jupyter Extension version (available under the Extensions sidebar): v2022.11.1003412109
-   Python Extension version (available under the Extensions sidebar): v2022.20.2
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04.4 LTS
-   Python and/or Anaconda version: conda 4.13.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour
Opening a notebook in VS code do not change the underlying JSON.

## Actual behaviour

Opening a notebook in VS Code changes the `language.version` property in the metadata.

## Steps to reproduce:

1. Create a notebook in JupyterLab
2. Open the previously created notebook in vscode
3. If the notebook is tracked by Git it will show changes. The change is under language.version.

![image](https://user-images.githubusercontent.com/56176070/215825139-0c4917ef-8cfe-4431-90ca-23c8b6cacf2f.png)

**Comment by DonJayamanne** [comment] 2023-01-31 19:52
Shoudl already be fixed with the latest insider pre-release version of Jupyter extension
https://github.com/microsoft/vscode-jupyter/pull/12419

**Closed by DonJayamanne** 2023-01-31 19:52 UTC
Labels: bug, notebook-serialization

**Comment by DonJayamanne** [comment] 2023-01-31 19:55
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12352
