### ISSUE TITLE
Interactive window shows stack trace with bare <a> tags when running code in unsaved buffer

### ISSUE THREAD

**Issue by bstee615** [microsoft/vscode-jupyter#12532] opened 2023-01-11 16:35 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected behavior: interactive window will show a stack trace with clickable line numbers when an exception is thrown

Actual behavior: interactive window shows line numbers with bare `<a>` tags, e.g. `<a href='untitled:Untitled-1?line=0'</a>`

## Steps to reproduce:

1. Create new unsaved buffer (Untitled-1) using `Ctrl-n` or `File > New Text File`
2. Paste the following code. Do not save the buffer.
```
#%%
raise Exception("foo")
```
3. Run the code in Interactive window using Ctrl-Enter.
4. The stack trace should be displayed in the interactive window, but the line numbers will have bare `<a>` tags on the line numbers. Here is the output I got:
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Untitled-1 in line 2
      <a href='untitled:Untitled-1?line=0'>1</a> #%%
----> <a href='untitled:Untitled-1?line=1'>2</a> raise Exception("foo")

Exception: foo
```

![image](https://user-images.githubusercontent.com/22305849/211863176-62268a3f-4b49-4894-8ba1-97a2bb89e1a4.png)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.15
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
LSP Notebooks experiment is enabled
LSP Notebooks interactive window support is enabled
> conda info --json
Python interpreter path: /bin/python
> /bin/python ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/interpreterInfo.py
> /bin/python3.8 ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/interpreterInfo.py
> /usr/bin/python3.8 ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/interpreterInfo.py
Starting Pylance language server.
> ~/.conda/envs/webcam_mods/bin/python ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/interpreterInfo.py
Jupyter provided interpreter path override: /bin/python
Jupyter provided interpreter path override: /bin/python
Python interpreter path: /bin/python3.8
Jupyter provided interpreter path override: /bin/python
Jupyter provided interpreter path override: /bin/python
Jupyter provided interpreter path override: /bin/python3.8
Python interpreter path: ~/.conda/envs/webcam_mods/bin/python
> conda run -n webcam_mods --no-capture-output python ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/printEnvVariables.py
Jupyter provided interpreter path override: /bin/python3.8
Jupyter provided interpreter path override: /bin/python3.8
> conda info --json
> conda run -n webcam_mods --no-capture-output python ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/printEnvVariables.py
> conda run -n webcam_mods --no-capture-output python ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/printEnvVariables.py
> conda run -n webcam_mods --no-capture-output python ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/get_output_via_markers.py ~/.vscode/extensions/ms-python.python-2022.20.1/pythonFiles/printEnvVariables.py
Jupyter provided interpreter path override: /home/benjis/.conda/envs/webcam_mods/bin/python
Jupyter provided interpreter path override: /usr/bin/python3.8
Jupyter provided interpreter path override: /bin/python3.8
Jupyter provided interpreter path override: /bin/python
Jupyter provided interpreter path override: /bin/python
Jupyter provided interpreter path override: /bin/python
> conda info --json
Send text to terminal: conda activate webcam_mods

```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.20.1
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 6.0.16-300.fc37.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor (12 x 3397)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 4, 2|
|Memory (System)|46.97GB (37.52GB free)|
|Process Argv|--unity-launch --crash-reporter-id cffcd941-ca53-4f99-af13-0185e9339fdf|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by sjwright90** [comment] 2023-09-09 18:00
Hi, having the same problem, tried to find a way to change the mimetype ( described here: https://github.com/microsoft/vscode-jupyter/issues/10663 ) but could not find where to change it? Is there a fix?

**Comment by amunger** [comment] 2023-09-11 15:59
duplicate of https://github.com/microsoft/vscode/issues/192605

**Closed** 2023-09-12 19:01 UTC
Labels: triage-needed
