### ISSUE TITLE
Kernel is being disposed of and cannot be restarted

### ISSUE THREAD

**Issue by nacorid** [microsoft/vscode-jupyter#16230] opened 2024-11-18 08:36 UTC
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm starting vscode from wsl2 ubuntu 24.04 and have the problem that my jupyter kernels are being disposed of after approximately 3 minutes, whether I'm running a cell or not.
I can reliably reproduce the issue by simply starting vscode, opening a notebook and waiting, or, as I have done for the trace logs, create a new venv and a new test notebook that's not idle:

```
import time

end_time = time.time() + 60 * 5
i = 0
while time.time() < end_time:
    i = i + 1
    time.sleep(1)
print(i)
```

As this is longer than the approximately 3 minutes, it gets terminated early. I don't know what else I can do to debug this issue, but as it currently stands, jupyter is unusable for me, because:

When the kernel is disposed of, I cannot start another kernel for that notebook. The restart button is grayed out, but selecting another kernel does nothing. Trying to execute a cell changes the "Execute Cell" and "Run all" buttons to the "Stop Cell execution" and "Interrupt" buttons, but doesn't log anything or throw an error (which I would expect if there's no kernel to execute it on). Then clicking the "Interrupt" or "Stop Cell execution" buttons does nothing either.
When I open a new/different notebook, a kernel is started as expected, but gets disposed of as well.
The only solution for me is to close vscode entirely and restart it again.

If there's anything further missing, let me know what I can do to help you help me.

### VS Code Version

1.95.3

### Jupyter Extension Version

2024.10.0

### Jupyter logs

```shell
Visual Studio Code (1.95.3, wsl, desktop)
Jupyter Extension Version: 2024.10.0.
Python Extension Version: 2024.20.0.
Pylance Extension Version: 2024.11.2.
Platform: linux (x64).
Temp Storage folder ~/.vscode-server/data/User/globalStorage/ms-toolsai.jupyter/version-2024.10.0
Workspace folder ~/gitSources/test, Home = /home/nacorid
09:04:09.762 [debug] Start refreshing Kernel Picker (1731917049762)
09:04:10.168 [trace] Search for KernelSpecs in Interpreter /bin/python3
09:04:10.169 [trace] Search for KernelSpecs in Interpreter /usr/bin/python3
09:04:10.169 [trace] Search for KernelSpecs in Interpreter ~/gitSources/test/.venv/bin/python
09:04:10.170 [debug] Get Custom Env Variables, Class name = Em, completed in 408ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
09:04:10.170 [debug] Jupyter Paths /kernels: 
09:04:10.259 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
09:04:10.403 [debug] KernelProvider switched kernel to id = .jvsc74a57bd00507bbbc5ab43f5deb5fb3c07af56e33b639ea4b3ed070af450698837cc6e880./home/~/gitSources/test/.venv/python./home/~/gitSources/test/.venv/python.-m#ipykernel_launcher
09:04:10.403 [debug] start the kernel, options.disableUI=true for ~/gitSources/test/test.ipynb
09:04:10.425 [trace] Registering commtarget jupyter.widget
09:04:10.426 [debug] Controller selection change completed
09:04:10.497 [debug] Get Custom Env Variables, Class name = Em, completed in 1ms, has a truthy return value, Arg 1: "~/gitSources/test", Arg 2: "RunPythonCode"
09:04:10.497 [info] Starting Kernel (Python Path: ~/gitSources/test/.venv/bin/python, Venv, 3.12.3) for '~/gitSources/test/test.ipynb' (disableUI=true)
09:04:10.497 [trace] Creating raw notebook for resource '~/gitSources/test/test.ipynb'
09:04:10.509 [trace] Hiding default KernelSpec /python for interpreter ~/gitSources/test/.venv/bin/python (KernelSpec file ~/gitSources/test/.venv/share/jupyter/kernels/python3/kernel.json)
09:04:10.510 [debug] End refreshing Kernel Picker (1731917049762)
09:04:10.519 [debug] Get Custom Env Variables, Class name = Em, completed in 0ms, has a truthy return value, Arg 1: "~/gitSources/test/test.ipynb", Arg 2: "RunPythonCode"
09:04:10.583 [debug] Launching kernel .jvsc74a57bd00507bbbc5ab43f5deb5fb3c07af56e33b639ea4b3ed070af450698837cc6e880./home/~/gitSources/test/.venv/python./home/~/gitSources/test/.venv/python.-m#ipykernel_launcher for ~/gitSources/test/test.ipynb in //home/~/gitSources/test with ports 9001, 9000, 9004, 9002, 9003
09:04:10.586 [trace] Conda file is conda
09:04:10.743 [debug] Got env vars from Python Ext in 223ms for ~/gitSources/test/.venv/bin/python, with env var count 41.
09:04:10.743 [trace] Prepend PATH with python bin for ~/gitSources/test/.venv/bin/python
09:04:10.743 [debug] Getting activated env variables, Class name = Id, completed in 224ms, has a truthy return value, Arg 1: "~/gitSources/test/test.ipynb", Arg 2: "~/gitSources/test/.venv/bin/python", Arg 3: undefined
09:04:10.745 [info] Process Execution: ~/gitSources/test/.venv/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:04:10.747 [info] Process Execution: ~/gitSources/test/.venv/bin/python -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v344f87d2cc45cf24a5dce46e1b5d91adef6705df3.json
    > cwd: //home/~/gitSources/test
09:04:10.748 [debug] Kernel process 42830.
09:04:10.750 [debug] Got env vars from Python Ext in 254ms for ~/gitSources/test/.venv/bin/python, with env var count 41.
09:04:10.750 [trace] Prepend PATH with python bin for ~/gitSources/test/.venv/bin/python
09:04:10.751 [debug] Getting activated env variables, Class name = Id, completed in 255ms, has a truthy return value, Arg 1: "~/gitSources/test", Arg 2: "~/gitSources/test/.venv/bin/python", Arg 3: undefined
09:04:10.752 [info] Process Execution: ~/gitSources/test/.venv/bin/python -m pip list
09:04:10.859 [trace] ipykernel version & path 6.29.5, ~/gitSources/test/.venv/lib/python3.12/site-packages/ipykernel/__init__.py for ~/gitSources/test/.venv/bin/python
09:04:10.977 [debug] Kernel output 42830: To connect another client to this kernel, use:
--existing kernel-v344f87d2cc45cf24a5dce46e1b5d91adef6705df3.json
09:04:11.172 [debug] Waiting for Raw Session to be ready in postStartRawSession
09:04:11.172 [debug] Waiting for Raw session to be ready, status: connected
09:04:11.172 [trace] Raw session connected
09:04:11.172 [debug] Waited for Raw session to be ready & got status: connected
09:04:11.172 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
09:04:11.172 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
09:04:11.172 [debug] Sending request for kernelInfo
09:04:11.177 [trace] Got response for requestKernelInfo
09:04:11.177 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 5ms
09:04:11.178 [trace] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
09:04:11.182 [trace] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
09:04:11.183 [trace] Started running kernel initialization for ~/gitSources/test/test.ipynb
09:04:11.183 [trace] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
09:04:11.187 [trace] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 0 output(s)
09:04:11.187 [trace] Determined IPyWidgets Version as undefined
09:04:11.187 [trace] Executing silently Code (idle) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None):
09:04:11.195 [trace] Executing silently Code (completed) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None): with 0 output(s)
09:04:11.195 [debug] Requesting Kernel info
09:04:11.195 [trace] Got Kernel info
09:04:11.195 [trace] End running kernel initialization, now waiting for idle
09:04:11.195 [trace] Waiting for idle on (kernel): 4dc725f5-f369-40fa-a0c0-337ed6e15b7c -> idle
09:04:11.196 [trace] Finished waiting for idle on (kernel): 4dc725f5-f369-40fa-a0c0-337ed6e15b7c -> idle
09:04:11.196 [trace] End running kernel initialization, session is idle
09:04:11.196 [trace] Registering Kernel Completion Provider from kernel .venv (Python 3.12.3) for language python
09:04:11.197 [trace] IPyWidgetScriptSource.initialize
09:04:11.197 [info] Kernel successfully started
09:04:11.198 [debug] getDataDirsImpl, Class name = Kr (started execution), Arg 1: "~/gitSources/test/test.ipynb", Arg 2: "~/gitSources/test/.venv/bin/python"
09:04:11.199 [debug] Get Custom Env Variables, Class name = Em, completed in 0ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
09:04:11.199 [debug] Jupyter Paths : 
09:04:11.202 [info] Process Execution: ~/gitSources/test/.venv/bin/python /home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/pythonFiles/printJupyterDataDir.py
09:04:11.208 [debug] Got an empty Jupyter Data Dir from /home/~/gitSources/test/.venv/bin/python, stderr = undefined
09:04:11.208 [debug] getDataDirsImpl, Class name = Kr, completed in 10ms, has a truthy return value, Arg 1: "~/gitSources/test/test.ipynb", Arg 2: "~/gitSources/test/.venv/bin/python", Return Value: <Uri:/home/~/.local/share/jupyter>, <Uri:/home/~/gitSources/test/.venv/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
09:04:11.370 [debug] Interpreter for Pylance for Notebook URI "~/gitSources/test/test.ipynb" is ~/gitSources/test/.venv/bin/python
09:04:14.037 [debug] Handle Execution of Cells 0 for ~/gitSources/test/test.ipynb
09:04:14.038 [trace] Execute Notebook ~/gitSources/test/test.ipynb. Step 1
09:04:14.038 [trace] Connect to Kernel ~/gitSources/test/test.ipynb. Step 2
09:04:14.038 [trace] Connected to Kernel ~/gitSources/test/test.ipynb. Step 3
09:04:14.038 [trace] executeCell 0. Step 4
09:04:14.039 [trace] Cell Index:0 sent to kernel
09:04:14.042 [trace] Start cell 0 execution @ 1731917054042 (clear output)
09:04:14.042 [debug] Kernel acknowledged execution of cell 0 @ 1731917054042
09:04:14.044 [trace] Cell 0 completed in 0.002s (start: 1731917054042, end: 1731917054044)
09:04:14.044 [trace] Cell 0 executed successfully
09:04:15.399 [debug] Handle Execution of Cells 1 for ~/gitSources/test/test.ipynb
09:04:15.400 [trace] Execute Notebook ~/gitSources/test/test.ipynb. Step 1
09:04:15.400 [trace] Connect to Kernel ~/gitSources/test/test.ipynb. Step 2
09:04:15.400 [trace] Connected to Kernel ~/gitSources/test/test.ipynb. Step 3
09:04:15.400 [trace] executeCell 1. Step 4
09:04:15.400 [trace] Cell Index:1 sent to kernel
09:04:15.403 [trace] Start cell 1 execution @ 1731917055403 (clear output)
09:04:15.403 [debug] Kernel acknowledged execution of cell 1 @ 1731917055403
09:07:10.432 [debug] Disposing kernel associated with ~/gitSources/test/test.ipynb, isClosed=true
09:07:10.432 [info] Dispose Kernel '~/gitSources/test/test.ipynb' associated with '~/gitSources/test/test.ipynb'
09:07:10.432 [debug] Cancel pending cells
09:07:10.432 [trace] Cell 1 completed in -1731917055.403s (start: 1731917055403, end: undefined)
09:07:10.433 [debug] Shutdown session 4dc725f5-f369-40fa-a0c0-337ed6e15b7c, .jvsc74a57bd00507bbbc5ab43f5deb5fb3c07af56e33b639ea4b3ed070af450698837cc6e880./home/~/gitSources/test/.venv/python./home/~/gitSources/test/.venv/python.-m#ipykernel_launcher - start called from Error: 
	at A_.shutdown (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:304:1140)
	at A_.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:304:623)
	at Is (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:115:867)
	at e (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:285:31789)
	at o_.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:285:32034)
	at hy.disposeOldKernel (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:285:23341)
	at hy.<anonymous> (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.10.0-linux-x64/dist/extension.node.js:285:21548)
	at mh.value (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:156:35355)
	at P.B (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at P.C (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:816)
	at P.fire (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:1033)
	at ah.$acceptDocumentAndEditorsDelta (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:155:13126)
	at py.S (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:155639)
	at py.Q (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:155419)
	at py.M (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:154508)
	at py.L (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:153746)
	at mh.value (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:152410)
	at P.B (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at P.fire (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at mh.value (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:174:13300)
	at P.B (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at P.fire (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at Vn.fire (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:9457)
	at Fm.A (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:12573)
	at mh.value (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:10993)
	at P.B (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at P.fire (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at j5.acceptChunk (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:7940)
	at mh.value (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:7226)
	at P.B (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:746)
	at P.fire (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:29:964)
	at V2.z (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:21944)
	at V2.acceptFrame (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:21750)
	at W2.n (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:20278)
	at file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:17510
	at Socket.t (file:///home/~/.vscode-server/bin/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/out/vs/workbench/api/node/extensionHostProcess.js:31:15451)
	at Socket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
09:07:10.433 [debug] Dispose Kernel process 42830.
09:07:10.435 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~/gitSources/test/test.ipynb
09:07:10.436 [debug] Notebook document ~/gitSources/test/test.ipynb got closed
09:07:10.436 [debug] Cancel executions after closing notebook ~/gitSources/test/test.ipynb
09:07:10.436 [debug] Cancel pending cells
09:07:10.436 [debug] Cancel executions after closing notebook ~/gitSources/test/test.ipynb
09:07:10.436 [debug] Cancel pending cells
09:07:10.436 [trace] Cell 1 executed successfully
09:07:10.437 [warn] Cancel all remaining cells due to dead kernel
09:07:10.437 [debug] Cancel pending cells
09:07:10.442 [debug] KernelProcess Exited 42830, Exit Code - undefined 
09:07:10.446 [debug] Disposed Kernel process 42830.
09:07:10.446 [debug] Shutdown session 4dc725f5-f369-40fa-a0c0-337ed6e15b7c, .jvsc74a57bd00507bbbc5ab43f5deb5fb3c07af56e33b639ea4b3ed070af450698837cc6e880./home/~/gitSources/test/.venv/python./home/~/gitSources/test/.venv/python.-m#ipykernel_launcher - shutdown complete
```

### Coding Language and Runtime Version

Python 3.12.3

### Language Extension Version (if applicable)

2024.20.0

### Running Jupyter locally or remotely?

Local

**Comment by nacorid** [comment] 2024-11-18 09:42
AutoSave was disabled; it is indeed one of the other extensions.
I'm going to test all of them to pin it down.

**Comment by DonJayamanne** [comment] 2024-11-18 10:28
Than you got getting back
Closing this issue for now, as it’s not caused by Jupyter extension

**Closed by DonJayamanne** 2024-11-18 10:28 UTC
Labels: bug, info-needed, notebook-kernel
