### ISSUE TITLE
VS Code does not change to selected interpreter

### ISSUE THREAD

**Issue by CooperData** [microsoft/vscode-jupyter#5364] opened 2021-03-30 21:51 UTC
I searched previous issues: #713 is similar and @rchiodo asked to open a new issue.

## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): ms-toolsai.jupyter v2021.3.684299474
-   Python Extension version (available under the Extensions sidebar): ms-python.python v2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: macOS 10.15.7
-   Python and/or Anaconda version: remote server CentOS 7: anaconda 21.48.22.159-1, Python 3.7.10 (target)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 4.9.2
-   Jupyter server running: Remote

## Expected behaviour

VS Code to run the selected interpreter both on the bottom left or top right kernel

## Actual behaviour

Currently I have an environment created which is my target environment. This env was created with conda, and it's python 3.7.10. Additionally, I have a custom library installed in there mlutils. As you can see from the image, if I run from the terminal, It shows the correct environment and correct executable. Furthermore, I can correctly import mlutils. However, on the notebook, I cannot make it change to another interpreter and it's using the base environment. I have changed the interpreter on the bottom left option, and also on the top right kernel. However, it does not work. I have restarted the kernel (using the green circular arrow) and I have restarted vs code multiple times. 

![image](https://user-images.githubusercontent.com/1518908/113061236-bf392700-917f-11eb-8b34-28b7c7b6d0cf.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

I am not sure I can correctly show steps to reproduce. But I am happy to provide more details if needed.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment] 2021-03-30 21:55
@CooperData what does your kernel dropdown look like? Do you have more than one 'Python 3' listed?

This bug might be fixed in our release we're about to ship (like tomorrow or the next day). If there's more than one 'Python 3' listed this is likely the problem we had were the user couldn't actually switch between them.

**Comment by CooperData** [comment] 2021-03-30 22:04
@rchiodo yes, there are multiple "Python 3" environments. Is there a way to rename the environment? Where is vscode reading this from? 

![image](https://user-images.githubusercontent.com/1518908/113062801-4e473e80-9182-11eb-9b2e-d3dea6d0a715.png)

**Comment by rchiodo** [comment] 2021-03-30 22:13
That means there are multiple 'kernelspec.json' files that have a display name of just 'Python 3'. In our new release we handle this case by changing our internal representation to account for that case.

**Comment by rchiodo** [comment] 2021-03-30 22:18
Jupyter has multiple [locations ](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs) where kernelspec.json files can be found. That's where this list is coming from. Plus we add all of your python environments to this list if they don't already match one of those kernelspec.json files.

That's where the dupes come from.

**Comment by RicardoSQueen** [comment] 2021-03-30 23:12
Hello all,
Here to leave my observation, in which I believe is the same bug.
I was having the same issues as @CooperData, the kernel simply wouldn't change to a virtual conda environment. I decided to try using interactive windows and the following error appeared from Jupyter (Extension):

> Command failed: . activate mech && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python /home/ricardoqueen/.vscode-oss/extensions/ms-python.python-2021.3.680753044/pythonFiles/pyvsc-run-isolated.py /home/ricardoqueen/.vscode-oss/extensions/ms-python.python-2021.3.680753044/pythonFiles/printEnvVariables.py bash: line 1: activate: No such file or directory
I remember I had this issue a while back.. If I recall, it's issue #2616 .
Would be nice if @CooperData tried to run in interactive window to see if the same error message appears. Here's my environment:
# Environment data
VS Code version: 1.54.3
Jupyter Extension version (available under the Extensions sidebar): ms-toolsai.jupyter v2021.3.684299474
Python Extension version (available under the Extensions sidebar): ms-python.python v2021.3.680753044
OS: Linux x64 5.9.16-1-MANJARO
Python and/or Anaconda version: conda 4.9.2
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda 
Jupyter server running: Local
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3

**Comment by CooperData** [comment] 2021-03-30 23:45
@RicardoSQueen  So based on @rchiodo answer about where the kernel name is stored, I was able to change the display name, and restart vs code and it actually changed finally to the desired kernel. 
The [location](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernel-specs) show on that link. In my case it was in /home/_myuser_/anaconda3/envs/_myenv_/share/jupyter/kernels/python3 and inside, you will see a kernel.json. Change the display_name for something unique. As @rchiodo, maybe this wont be needed once they ship the new release in the coming days.

**Closed** 2021-03-31 19:50 UTC
Labels: bug

**Comment by Grobson97** [comment] 2021-04-27 16:37
I have this exact issue, despite having the most up to date version of VS code. I have also tried changing the display name of the virtual environment that I wish to use 'GeneralVenv' in the json file as mentioned above.

## Environment data

-   VS Code version: 1.55.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version:  Windows 10.0.19041
-   Python and/or Anaconda version: Python 3.9.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | local

## Expected behaviour

Jupyter to use the virtual environment 'C;\Python Projects\GeneralVenv\Scripts\python.exe' where matplotlib is installed.

## Actual behaviour

Seems like it is using the base interpretter where matplotlib is not installed. Despite the fact VS code says it is using GeneralVenv when I click the purple option in the bottom left to change the interpretter and when choosing which kernel to use, by clicking the option in the top right 'Python 3.9.0 64-bit:idle'. See screenshots.

Bizarrely everything had been working fine until today. One time I ran a cell it worked fine, the next time it came up with this error. As far as i'm aware I didn't do anything that should have impacted which environment python  notebook uses.

Sorry, unsure whether to raise a new issue since my issue is basically identical to this thread.
Any help would be greatly appreciated!

![JupyterIssue1](https://user-images.githubusercontent.com/45102919/116279268-3bbf2580-a77f-11eb-916a-27374794ff5c.PNG)
![JupyterIssue2](https://user-images.githubusercontent.com/45102919/116279272-3c57bc00-a77f-11eb-8a7e-7c9557a2c649.PNG)
![JupyterIssue3](https://user-images.githubusercontent.com/45102919/116279274-3c57bc00-a77f-11eb-818e-5756da3c68e6.png)

**Comment by rchiodo** [comment] 2021-04-27 16:42
@Grobson97 I opened a new issue for you.
