### ISSUE TITLE
Respect "deletable": false and "editable": false metadata values

### ISSUE THREAD

**Issue by coderforlife** [microsoft/vscode-jupyter#8709] opened 2022-01-16 17:55 UTC
Since notebook v5, the official implementation has supported the cell-level metadata values of "deletable" and "editable" values. When set to false, these cells cannot be deleted or edited (which includes deleting). See https://nbformat.readthedocs.io/en/latest/format_description.html#cell-metadata. When first finding out about these, I was hoping that the kernel itself would be controlling it, but it seems to be the client that needs to take care of it.

Setting these values works in Jupyter Notebook and Jupyter Lab. However, VS Code does not respect these. In those other environments, the metadata is at least editable and thus these features can be changed there with some work, VS Code does not have direct access to them (however you can open the notebook as text in VS Code to edit those settings, it isn't as direct). Thus, this will be further encouragement for #1121 and #1182 (which was temporarily available with Jupyter PowerTools but that can no longer be installed).

**Comment by greazer** [comment] 2022-01-20 21:25
@coderforlife, thanks for the feedback! Honoring this type of metadata is on our longer term plans.

**Comment by DonJayamanne** [comment] 2022-08-22 02:45
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1308

**Closed by DonJayamanne** 2022-08-22 02:45 UTC
Labels: notebook-workflow, works-in-jupyter, notebook-table-stakes, feature-request, notebook-serialization
