### ISSUE TITLE
When using debugger in Codespaces notebook with Live Share, kernel dies for other user

### ISSUE THREAD

**Issue by pamelafox** [microsoft/vscode-jupyter#13640] opened 2023-06-02 18:34 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I opened this repo in Codespaces:
https://github.com/pamelafox/materials-fa22

I then started Live Share and invited my colleague to join via link. They joined using GitHub Codespaces in the browser.

I opened fa22/project/project3/project3.ipynb, added a breakpoint in the cell, and opened the run menu to select "Debug cell".

The debugger opened at first, but then exited. 

For my colleague, they saw the notebook crash:

<img width="1194" alt="MicrosoftTeams-image (9)" src="https://github.com/microsoft/vscode-jupyter/assets/297042/3b543a99-2571-4f55-9bac-cae39e07078e">

This is what they see when they click "try again":

<img width="402" alt="MicrosoftTeams-image (10)" src="https://github.com/microsoft/vscode-jupyter/assets/297042/7f0121bf-5ded-48ec-be57-53396df85393">

They realized that a new tab with the same notebook file was opened at that time, to the left of the crashed one. However, when they try to view it, it stops being in debug mode.

<img width="1200" alt="MicrosoftTeams-image (11)" src="https://github.com/microsoft/vscode-jupyter/assets/297042/18dbd755-12b2-4a2f-851c-cf55d7e61c1e">

### VS Code Version

Codespaces

### Jupyter Extension Version

v2023.4.1011241018

### Jupyter logs

```shell
Visual Studio Code (1.78.2, codespaces, codespaces)
Jupyter Extension Version: 2023.4.1011241018.
Python Extension Version: 2023.8.0.
Platform: linux (x64).
Workspace folder /workspaces/materials-fa22, Home = /home/vscode
18:18:18.696 [info] Start refreshing Kernel Picker (1685729898695)
18:18:18.750 [info] Using Pylance
18:18:25.929 [info] End refreshing Kernel Picker (1685729898695)
18:18:26.317 [warn] Failed to get activated env vars for /usr/local/bin/python in 4193ms
18:18:26.342 [info] Process Execution: /usr/local/bin/python -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
18:18:26.395 [info] Process Execution: /usr/local/bin/python -m pip list
18:19:51.726 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0949777d72b0d2535278d3dc13498b2535136f6dfe0678499012e853ee9abcab1./usr/local/python./usr/local/python.-m#ipykernel_launcher  (Python Path: /usr/local/bin/python, Unknown, 3.10.11) for '/workspaces/materials-fa22/materials/fa22/project/project3/project3.ipynb' (disableUI=true)
18:19:52.581 [warn] Failed to get activated env vars for /usr/local/bin/python in 841ms
18:19:52.896 [info] Process Execution: /usr/local/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
18:19:53.118 [info] Process Execution: /usr/local/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"d00f99e1-950d-4725-a2d8-081dd075b7ea" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-2585d42vUj3jP72.json
    > cwd: /workspaces/materials-fa22/materials/fa22/project/project3
18:19:55.863 [info] ipykernel version & path 6.23.1, /usr/local/lib/python3.10/site-packages/ipykernel/__init__.py for /usr/local/bin/python
18:19:59.535 [info] Started Kernel Python 3.10.11 (pid: 1409)
18:19:59.535 [info] Started new session 3b295fe9-9dc2-4267-9c6e-1c770d6568b0
18:19:59.840 [info] Process Execution: /usr/local/bin/python ~/.<username>-remote/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/pythonFiles/printJupyterDataDir.py
18:21:34.625 [info] Starting debugging with mode 1
18:21:37.619 [info] Ending debug session 2f1a1a97-1b25-4df6-877f-293e6c5ab791
18:21:37.622 [warn] StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 337, in process_control
    await result
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 967, in debug_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 503, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 737, in process_request
    self.stop()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 447, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 280, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
18:21:39.736 [info] Ending debug session 2f1a1a97-1b25-4df6-877f-293e6c5ab791
18:21:39.736 [info] Ending debug session 2f1a1a97-1b25-4df6-877f-293e6c5ab791
18:21:51.601 [info] Starting debugging with mode 1
18:21:53.586 [warn] Cancel all remaining cells due to cancellation or failure in execution
18:21:53.932 [info] Ending debug session 6b4f72e0-011b-4b2b-a88a-c0f176148e74
18:21:53.935 [warn] StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 337, in process_control
    await result
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 967, in debug_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 503, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 737, in process_request
    self.stop()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 447, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 280, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
18:21:56.025 [info] Ending debug session 6b4f72e0-011b-4b2b-a88a-c0f176148e74
18:21:56.025 [info] Ending debug session 6b4f72e0-011b-4b2b-a88a-c0f176148e74
18:22:03.139 [info] Starting debugging with mode 1
18:22:05.316 [info] Ending debug session cda21f44-f93d-4c6a-a1fb-00c28097bea8
18:22:05.319 [warn] StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 337, in process_control
    await result
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 967, in debug_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 503, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 737, in process_request
    self.stop()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 447, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 280, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
18:22:07.425 [info] Ending debug session cda21f44-f93d-4c6a-a1fb-00c28097bea8
18:22:07.425 [info] Ending debug session cda21f44-f93d-4c6a-a1fb-00c28097bea8
18:22:18.576 [info] Starting debugging with mode 1
18:22:29.422 [error] Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (~/.<username>-remote/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:32419)
    at qm.<anonymous> (~/.<username>-remote/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:19877)
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:101:9621
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at e.ExtHostDocumentsAndEditors.acceptDocumentsAndEditorsDelta (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:101:13842)
    at e.ExtHostDocumentsAndEditors.$acceptDocumentsAndEditorsDelta (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:101:12316)
    at a.N (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:11620)
    at a.M (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:11338)
    at a.H (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:10431)
    at a.G (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:9412)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:8200
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at g.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:14852)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:127:32403
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at g.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:14852)
    at u.E (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:18899)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:16887
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at d.acceptChunk (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:12583)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:11870
    at Socket.n (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:127:13609)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
18:22:29.424 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
18:22:29.581 [warn] Unhandled message found: execute_reply
18:22:29.661 [info] Ending debug session 1214d461-c880-4c37-93d1-62d9bb6d09d5
18:22:29.663 [warn] StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 337, in process_control
    await result
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 967, in debug_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 503, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 737, in process_request
    self.stop()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 447, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 280, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
18:22:32.283 [info] Ending debug session 1214d461-c880-4c37-93d1-62d9bb6d09d5
18:22:32.283 [info] Ending debug session 1214d461-c880-4c37-93d1-62d9bb6d09d5
18:22:45.697 [info] Starting debugging with mode 1
18:22:47.845 [info] Ending debug session 17402301-da9a-4c51-9e05-9ec856d8182f
18:22:47.848 [warn] StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 337, in process_control
    await result
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 967, in debug_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 503, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 737, in process_request
    self.stop()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 447, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 280, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
18:22:50.085 [info] Ending debug session 17402301-da9a-4c51-9e05-9ec856d8182f
18:22:50.085 [info] Ending debug session 17402301-da9a-4c51-9e05-9ec856d8182f
18:22:53.575 [info] Starting debugging with mode 1
18:22:58.323 [error] Error in waiting for cell to complete Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (~/.<username>-remote/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:2:32419)
    at qm.<anonymous> (~/.<username>-remote/extensions/ms-toolsai.jupyter-2023.4.1011241018-linux-x64/out/extension.node.js:24:19877)
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:101:9621
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at e.ExtHostDocumentsAndEditors.acceptDocumentsAndEditorsDelta (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:101:13842)
    at e.ExtHostDocumentsAndEditors.$acceptDocumentsAndEditorsDelta (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:101:12316)
    at a.N (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:11620)
    at a.M (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:11338)
    at a.H (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:10431)
    at a.G (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:9412)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:111:8200
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at g.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:14852)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:127:32403
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at g.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:14852)
    at u.E (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:18899)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:16887
    at v.invoke (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at i.fire (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at d.acceptChunk (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:12583)
    at /<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:72:11870
    at Socket.n (/<username>/bin/linux-x64/b3e4e68a0bc097f0ae7907b217c1119af9e03435/out/vs/workbench/api/node/extensionHostProcess.js:127:13609)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
18:22:58.324 [warn] Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
18:22:58.479 [warn] Unhandled message found: execute_reply
18:22:58.581 [info] Ending debug session bb9d57c7-02d6-4ca4-b26d-c89311078a1f
18:22:58.584 [warn] StdErr from Kernel Process [IPKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 337, in process_control
    await result
  File "/usr/local/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 967, in debug_request
    reply_content = await reply_content
  File "/usr/local/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 503, in do_debug_request
    return await self.debugger.process_request(msg)
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 737, in process_request
    self.stop()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 447, in stop
    self.debugpy_client.disconnect_tcp_socket()
  File "/usr/local/lib/python3.10/site-packages/ipykernel/debugger.py", line 280, in disconnect_tcp_socket
    self.debugpy_stream.socket.disconnect(self._get_endpoint())
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.disconnect
zmq.error.ZMQError: No such file or directory
18:23:01.212 [info] Ending debug session bb9d57c7-02d6-4ca4-b26d-c89311078a1f
18:23:01.212 [info] Ending debug session bb9d57c7-02d6-4ca4-b26d-c89311078a1f
```

### Coding Language and Runtime Version

Python 3.10

### Language Extension Version (if applicable)

v2023.8.0

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by DonJayamanne** [comment] 2024-12-17 00:49
Its likely this issue was caused by a endironment setup, the zmq errors are always an indication of setup/installation issues at the users end & nothing to do with Jupyter extension
Hence closing this.

If this issue still persists i would suggest creating a new virtual or conda environment and using that instead.
If that still fails, please ping here and i'll re-open this or feel free to create a new issue.

**Closed by DonJayamanne** 2024-12-17 00:49 UTC
Labels: bug, notebook-debugging, notebook-liveshare
