### ISSUE TITLE
Random files appearing in my trash bin everytime I open a Jupyter notebook

### ISSUE THREAD

**Issue by anarchy89** [microsoft/vscode-jupyter#10419] opened 2022-06-10 17:37 UTC
## Environment data

-   VS Code version: 1.68.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001601848
-   Python Extension version (available under the Extensions sidebar): v2022.8.0
-   OS (Windows | Mac | Linux distro) and version: MAC OS MONTEREY 12.4
-   Python and/or Anaconda version: mamba 0.22.1 py39hde45b87_0 conda-forge, conda 4.12.0 py39h2804cbe_0 conda-forge
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A : Local and Remote 

## Expected behaviour

Previously when I was running Jupiter notebooks, they were working fine.

## Actual behaviour

When I open Jupyter notebooks in vscode now, these files appear in my trash bin automatically. Each one is 72 bytes, the file names are in the following format, `"name of file"-jvsc-1ddefa11-e9b6-4e53-af4e-c472c2608261e3c71dba-91c1-44d1-af5e-b96ffff8817d.ipynb` and contain the following code `{
 "cells": [],
 "metadata": {},
 "nbformat": 4,
 "nbformat_minor": 5
}`

They always produce the same file just with a different name. I am worried that this is going to destroy my hard from the constant read and writes. I am running the files from an external APFS SSD drive if that makes a difference.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open a jupyter notebook in vscode using mambaforge 

2. Save the file and reopen it.

3. Open the trash bin and you will see the file I am talking about.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment] 2022-06-10 20:16
thanks for the bug, I was able to repro on Windows as well after disabling zmq (which some macs have to do by default).
1. add `"jupyter.disableZMQSupport" : true` to your settings
2. open a new notebook and run a cell
or
2. open a notebook that has previously run a cell

I see the file temporarily appear in the vscode explorer and then is deleted and ends up in the recycle bin

**Comment by rchiodo** [comment] 2022-06-10 20:42
This is on purpose. We require a 'backing file' in order to start a kernel.

**Comment by amunger** [comment] 2022-06-10 20:49
can we skip the trashcan/recycle bin though? It sounds like this wasn't happening previously, though I haven't confirmed that

**Comment by rchiodo** [comment] 2022-06-10 20:52
I don't believe that's our code doing that. We ask jupyter to delete it:

https://github.com/microsoft/vscode-jupyter/blob/38caef1b0c652d6d534f3c9f5b67d357c65ad70a/src/kernels/jupyter/session/backingFileCreator.base.ts#L77

**Comment by DonJayamanne** [comment] 2022-06-11 08:40
>  don't believe that's our code doing that. We ask jupyter to delete it:

we should be able to delete (these) local files when dealing with non-zmq for local sessions.

**Comment by david-cortes** [comment] 2022-06-11 15:48
Can also confirm that I experience this bug and I don't think it's possible to enable zmq in mac-arm due to not providing builds for that platform.

**Comment by Kurt-Shiwz** [comment] 2022-10-31 08:46
+1

**Comment by anarchy89** [comment] 2022-10-31 09:38
Zeromq is native to Mac arm. Is there anyway to enable it?

**Comment by anarchy89** [comment] 2022-10-31 10:18
Zeromq is native to Mac arm according to this https://formulae.brew.sh/formula/zeromq#default Is there anyway to enable it? @DonJayamanne @amunger

**Comment by santoshkumarradha** [comment] 2022-11-14 05:13
+1 
mac Apple M1 Pro
vscode:1.73.1

**Comment by DonJayamanne** [comment] 2022-12-06 22:23
This will get fixed when #5206 is resolved.
Hence closing this as a duplicate of #5206

**Closed by DonJayamanne** 2022-12-06 22:23 UTC
Labels: bug, papercut :drop_of_blood:, kernel-management
