### ISSUE TITLE
interactive window removes indents when saving to file.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode-jupyter#7231] opened 2021-08-20 18:47 UTC
## Environment data

-   VS Code version: v1.59.0
-   Extension version (available under the Extensions sidebar): v2021.9.1144093763-dev
-   OS and version: win10 20h2 64bit
-   Python version (& distribution if applicable, e.g. Anaconda): python37x86
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: 
 pylance v2021.8.3-pre.1
 jupyter v2021.8.1195043623
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Default

## Expected behaviour

XXX

## Actual behaviour

https://user-images.githubusercontent.com/26390254/130279636-b609da4f-19c4-4a42-b857-8e1f1a46ef4f.mp4

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by joyceerhl** [comment] 2021-08-23 20:06
Sorry for the trouble @byehack. We just fixed https://github.com/microsoft/vscode-jupyter/issues/7088, this should be the same problem. Fix should be available in the Insiders build that goes out tonight, and the upcoming Stable Jupyter extension release a week from now.

**Comment by greazer** [comment] 2021-08-23 20:15
This has been fixed. It's a dupe of #7088.

**Closed by greazer** 2021-08-23 20:15 UTC
Labels: bug
