### ISSUE TITLE
Markdown "# %% [markdown]" cells should be reflected in Outline View

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7122] opened 2021-08-13 20:32 UTC
The interactive window was originally designed to be used as an alternate way to create a notebook. Therefore, it only seems logical that cells delimited with "# %% [markdown]" could appear in the Outline View (aka TOC).

Not sure if this would require changes to PyLance or whether we could do it ourselves.

**Comment by greazer** [comment] 2021-08-16 23:22
The jupyter extension needs to provide this support.

**Comment by claudiaregio** [comment] 2021-09-30 17:18
@greazer Same as https://github.com/microsoft/vscode-jupyter/issues/5552 I believe

**Comment by DonJayamanne** [comment] 2021-09-30 17:47
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/4496

**Closed by DonJayamanne** 2021-09-30 17:47 UTC
Labels: enhancement, interactive-window
