### ISSUE TITLE
interactive window can't render code links correctly

### ISSUE THREAD

**Issue by kaare-mikkelsen** [microsoft/vscode-jupyter#14298] opened 2023-09-09 19:40 UTC
Type: <b>Bug</b>

when I run python code in the interactive window and an error occurs, it writes out the entire html code for the link, like this:

```
KeyError                                  Traceback (most recent call last)
c:\Users\au207178\OneDrive - Aarhus universitet\forskning\sleepInOrbit\reports\sleepReports2.py in line 15
     <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=380'>381</a> subjectIds = mb.get_entity_vals(HYPNO_DERIV_PATH, 'subject', with_key=False)
     <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=382'>383</a> # %matplotlib inline
---> <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=384'>385</a> sleepReport(subject=subjectIds[0],SPEC_DERIV_PATH=SPEC_DERIV_PATH,HYPNO_DERIV_PATH=HYPNO_DERIV_PATH,CLEAN_DERIV_PATH=CLEAN_DERIV_PATH)

c:\Users\au207178\OneDrive - Aarhus universitet\forskning\sleepInOrbit\reports\sleepReports2.py in line 134, in sleepReport(subject, SPEC_DERIV_PATH, HYPNO_DERIV_PATH, CLEAN_DERIV_PATH, earEEGOnly)
    <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=314'>315</a>     spectroPath=hypnoPath.copy().update(root=SPEC_DERIV_PATH,
    <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=315'>316</a>                                         extension='.mat',
    <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=316'>317</a>                                         description='spectrograms')
    <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=318'>319</a>     temp=h5py.File(str(spectroPath))
--> <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=319'>320</a>     usedEpochsList.append(np.array(temp['usedEpochs'],dtype=np.int32).reshape(-1))
    <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=322'>323</a> #load hypnogram files
    <a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=323'>324</a> hypnoGrams = []

File h5py\_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py\_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File c:\Users\au207178\Anaconda3\envs\cuda11\lib\site-packages\h5py\_hl\group.py:328, in Group.__getitem__(self, name)
    <a href='file:///c%3A/Users/au207178/Anaconda3/envs/cuda11/lib/site-packages/h5py/_hl/group.py?line=325'>326</a>         raise ValueError("Invalid HDF5 object reference")
    <a href='file:///c%3A/Users/au207178/Anaconda3/envs/cuda11/lib/site-packages/h5py/_hl/group.py?line=326'>327</a> elif isinstance(name, (bytes, str)):
--> <a href='file:///c%3A/Users/au207178/Anaconda3/envs/cuda11/lib/site-packages/h5py/_hl/group.py?line=327'>328</a>     oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
    <a href='file:///c%3A/Users/au207178/Anaconda3/envs/cuda11/lib/site-packages/h5py/_hl/group.py?line=328'>329</a> else:
...
File h5py\_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py\h5o.pyx:190, in h5py.h5o.open()

KeyError: "Unable to open object (object 'usedEpochs' doesn't exist)"
```

Where is says '<a href='file:///c%3A/Users/au207178/OneDrive%20-%20Aarhus%20universitet/forskning/sleepInOrbit/reports/sleepReports2.py?line=380'>381</a> ', it should just write '381' as a link.

Extension version: 2023.8.1002501831
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:07.438Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (14.13GB free)|
|Process Argv|--crash-reporter-id f1790356-91bc-40a2-a4c7-3a2efbf5bc2f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30831758
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30829745

```

</details>

**Comment by amunger** [comment] 2023-09-11 16:01
duplicate of https://github.com/microsoft/vscode/issues/192605

**Closed by amunger** 2023-09-11 16:01 UTC
