### ISSUE TITLE
Jupyter install fails in new Ubuntu imsage

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-jupyter#12635] opened 2023-01-24 22:26 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Have a new ubuntu install
2. `sudo apt install python3 python3-pip`
3. Try to run a notebook cell in VS Code
4. Get an error notification saying jupyter is missing. Accept the offer to install jupyter
5. After installing jupyter, execution just fails:

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/2230985/214434913-25ca44d0-769b-4de9-a1d6-99504c721bf2.png">

### VS Code Version

1.75.0-insiders

### Jupyter Extension Version

v2023.1.2000251018

### Jupyter logs

```shell
Visual Studio Code - Insiders (1.75.0-insider, undefined, desktop)
Jupyter Extension Version: 2023.1.2000251018.
Python Extension Version: 2023.1.10241007.
Workspace folder /home/connor/Downloads/multi-devcontainer-test
warn 14:23:14.743: Exception while attempting zmq : /snap/core/current/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/node_modules/zeromq/prebuilds/linux-x64/electron.napi.glibc.node)
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 14:23:15.207: LSP Notebooks experiment is enabled
info 14:23:15.746: Process Execution: > /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:23:15.766: Process Execution: > /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:23:15.780: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
error 14:23:37.889: Live Notebook not available for /Interactive-1.interactive
error 14:23:40.004: Live Notebook not available for /Interactive-1.interactive
error 14:23:40.815: Live Notebook not available for /Interactive-1.interactive
info 14:23:42.110: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]) for '/Interactive-1.interactive' (disableUI=false)
info 14:23:42.110: Checking for server existence.
info 14:23:42.165: Process Execution: > /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:23:42.179: Process Execution: > /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
warn 14:23:42.284: Error occurred while trying to start the kernel, options.disableUI=false [lf [Error]: Jupyter cannot be started. Error attempting to locate Jupyter: Running cells requires jupyter and notebook package.
	at bm.startServer (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:252940)
	at async bm.createServer (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:252229)
	at async Xf.connect (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:230534)
	at async fm.create (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:250273)
	at async Zm.createJupyterSession (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:306244)] {
  category: 'jupyterinstall'
}
warn 14:23:42.286: Kernel Error, context = start [lf [Error]: Jupyter cannot be started. Error attempting to locate Jupyter: Running cells requires jupyter and notebook package.
	at bm.startServer (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:252940)
	at async bm.createServer (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:252229)
	at async Xf.connect (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:230534)
	at async fm.create (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:250273)
	at async Zm.createJupyterSession (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:306244)] {
  category: 'jupyterinstall'
}
info 14:23:42.321: Process Execution: > /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:23:42.340: Process Execution: > /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:23:42.352: Process Execution: > /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:23:43.985: Process Execution: > /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:23:44.065: Process Execution: > /bin/python3 -m pip install -U --user jupyter
> /bin/python3 -m pip install -U --user jupyter
info 14:24:03.897: Process Execution: > /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:24:03.923: Process Execution: > /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:24:03.940: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
info 14:24:03.981: Process Execution: > /bin/python3 -m pip install -U --user notebook
> /bin/python3 -m pip install -U --user notebook
info 14:24:05.845: Process Execution: > /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:24:06.058: Process Execution: > /bin/python3 -m pip list
> /bin/python3 -m pip list
info 14:24:06.072: Process Execution: > /bin/python3 -m jupyter kernelspec --version
> /bin/python3 -m jupyter kernelspec --version
info 14:24:06.176: Process Execution: > /bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/pythonFiles/vscode_datascience_helpers/getJupyterKernelspecVersion.py
> /bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/pythonFiles/vscode_datascience_helpers/getJupyterKernelspecVersion.py
info 14:24:06.405: Dispose Kernel '/Interactive-1.interactive' associated with '/Interactive-1.interactive'
info 14:24:06.409: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]) for '/Interactive-1.interactive' (disableUI=false)
info 14:24:06.410: Checking for server existence.
info 14:24:06.411: Connecting to server
info 14:24:06.412: Launching server
info 14:24:06.415: Starting Notebook
info 14:24:06.430: Generating custom default config at /tmp/9bed00b1-0873-4f52-8a66-879275aa28f0/jupyter_notebook_config.py
Starting Jupyter from /bin/python3 with arguments --no-browser --notebook-dir="/home/connor/Downloads/multi-devcontainer-test" --config=/tmp/9bed00b1-0873-4f52-8a66-879275aa28f0/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
info 14:24:06.600: Process Execution: > /bin/python3 -m jupyter notebook --no-browser --notebook-dir="/home/connor/Downloads/multi-devcontainer-test" --config=/tmp/9bed00b1-0873-4f52-8a66-879275aa28f0/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> /bin/python3 -m jupyter notebook --no-browser --notebook-dir="/home/connor/Downloads/multi-devcontainer-test" --config=/tmp/9bed00b1-0873-4f52-8a66-879275aa28f0/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands:

Jupyter command `jupyter-notebook` not found.
warn 14:24:06.732: Error occurred while trying to start the kernel, options.disableUI=false [Er [Error]: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands:

Jupyter command `jupyter-notebook` not found.

	at Sm.rejectStartPromise (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:254830)
	at t._complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:255390)
	at t.n (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:700797)
	at t.__tryOrUnsub (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:701037)
	at t.complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:700930)
	at t._complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:699446)
	at t.complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:699145)
	at ChildProcess.<anonymous> (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:1800807)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'jupyterconnection'
}
warn 14:24:06.733: Kernel Error, context = start [Er [Error]: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands:

Jupyter command `jupyter-notebook` not found.

	at Sm.rejectStartPromise (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:254830)
	at t._complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:255390)
	at t.n (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:700797)
	at t.__tryOrUnsub (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:701037)
	at t.complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:700930)
	at t._complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:699446)
	at t.complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:699145)
	at ChildProcess.<anonymous> (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:1800807)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'jupyterconnection'
}
info 14:24:06.757: Process Execution: > /bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> /bin/python3 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 14:24:07.016: Dispose Kernel '/Interactive-1.interactive' associated with '/Interactive-1.interactive'
error 14:24:07.018: Error in execution [Er [Error]: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands:

Jupyter command `jupyter-notebook` not found.

	at Sm.rejectStartPromise (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:254830)
	at t._complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:255390)
	at t.n (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:700797)
	at t.__tryOrUnsub (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:701037)
	at t.complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:700930)
	at t._complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:699446)
	at t.complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:699145)
	at ChildProcess.<anonymous> (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:1800807)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'jupyterconnection'
}
error 14:24:07.020: Error in execution (get message for cell) [Er [Error]: Jupyter server crashed. Unable to connect. 
Error code from Jupyter: 1
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands:

Jupyter command `jupyter-notebook` not found.

	at Sm.rejectStartPromise (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:254830)
	at t._complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:17:255390)
	at t.n (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:700797)
	at t.__tryOrUnsub (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:701037)
	at t.complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:700930)
	at t._complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:699446)
	at t.complete (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:699145)
	at ChildProcess.<anonymous> (/home/connor/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.1.2000251018/out/extension.node.js:2:1800807)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'jupyterconnection'
}
```
```


### Coding Language and Runtime Version

Python v3.10.6

### Language Extension Version (if applicable)

_No response_

### Anaconda Version (if applicable)

_No response_

### Running Jupyter locally or remotely?

Local

**Comment by connor4312** [comment] 2023-01-24 22:28
Oh, nevermind, this is the same as https://github.com/microsoft/vscode-jupyter/issues/12632

**Comment by DonJayamanne** [comment] 2023-01-24 23:38
This is an issue with the version of Python downloaded, basically Jupyter application is not working outside vscode, hence thats' not working to work in vscode either.

I'm not even able to create a virtual environment using the version of Python that is installed in there.
At this stage this is purely an issue with users environment, not having a version of Python that can be used to install and get things working.

I think we might want to look into this next iteration on how to best solve this problem for users on Ubuntu.

**Comment by DonJayamanne** [comment] 2023-01-24 23:38
from @connor4312 

> Ok. This is using the default python3 and python3-pip apt package on Ubuntu 22.04. Maybe we want to issue some kind of warning if this version of python doesn't work.

**Comment by connor4312** [comment] 2023-01-24 23:47
I was able to get around this by installing Python 3.11 from the deadsnakes PPA and pip via `get-pip.py`

**Comment by DonJayamanne** [comment] 2023-01-24 23:47
Closinmg for now as this could be a duplicate of #12632 (will need to verify)

**Closed by DonJayamanne** 2023-01-24 23:47 UTC
Labels: bug, notebook-kernel-startup
