### ISSUE TITLE
keeps crashin

### ISSUE THREAD

**Issue by blackwidow76** [microsoft/vscode-jupyter#15762] opened 2024-06-12 15:54 UTC
Type: <b>Bug</b>

everytime the extension is opened it crashes

Extension version: 2024.4.0
VS Code version: Cursor 0.35.0 (5f9353ed8be369c4ac2b4d43596f5ff281746ec0, 2024-06-08T04:53:54.048Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment] 2024-06-15 01:49
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15738

**Comment by DonJayamanne** [comment] 2024-06-15 01:49
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15738

**Closed by DonJayamanne** 2024-06-15 01:50 UTC
