### ISSUE TITLE
Problems tab is not cleared after error has been fixed

### ISSUE THREAD

**Issue by arminus** [microsoft/vscode-jupyter#4279] opened 2021-01-03 11:15 UTC
## Environment data

-   VS Code version: 1.53.0-inside
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Win10.18363 x64
-   Python and/or Anaconda version: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Problems tab should clear all error messages after errors have been fixed in a jupyter notebook

## Actual behaviour

Error messages remain in the problems tab until vscode is restarted (restart of jupyter kernel or re-opening the jupyter notebook file does not help)

## Steps to reproduce:

1. create a new jupyter notebook
2. in the first cell add `print "abc"`
3. add a 2nd cell, add `print("abc")`
4. save
5. fix the error in the first cell

[![2021-01-03-121215.png](https://i.postimg.cc/4yHxDLPj/2021-01-03-121215.png)](https://postimg.cc/bS8PbRKR)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'NativeNotebookEditor'
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> C:\Python38\python.exe c:\Users\amueller\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Error 2021-01-03 12:08:54: Jupyter Kernel Spec not found for a local connection
> C:\Python38\python.exe -c "import os;print(os.path.realpath("C:\\Users\\amueller\\AppData\\Roaming\\jupyter\\kernels"))"
> C:\Python38\python.exe -c "import os;print(os.path.realpath("C:\\Users\\amueller\\AppData\\Roaming\\jupyter\\kernels"))"
Error 2021-01-03 12:08:56: Jupyter Kernel Spec not found for a local connection
> C:\Python38\python.exe -c "import os;print(os.path.realpath("C:\\Users\\amueller\\AppData\\Roaming\\jupyter\\kernels"))"
> C:\Python38\python.exe -c "import os;print(os.path.realpath("C:\\Users\\amueller\\AppData\\Roaming\\jupyter\\kernels"))"
Error 2021-01-03 12:09:37: Jupyter Kernel Spec not found for a local connection
Error 2021-01-03 12:09:43: Attempted to SaveAs with a model that is not NativeEditorNotebookModel
Error 2021-01-03 12:09:43: Jupyter Kernel Spec not found for a local connection

```

</p>
</details>

**Comment by joyceerhl** [comment] 2021-01-05 01:57
Thanks for reporting a bug @arminus. What Python language server are you using? You can check this in your user settings.json, the setting name is 'python.languageServer'. Thank you!

**Comment by arminus** [comment] 2021-01-05 07:55
With the test above 'python.languageServer' was set to Microsoft. Switching to Pylance, same issue in the problems section, only the error marker in the first cell is gone. Same with Jedi.

**Comment by joyceerhl** [comment] 2021-01-05 21:47
> error marker in the first cell is gone

Which problems remain with Pylance? The 'Microsoft' option is being deprecated in favor of 'Pylance', so I'd recommend using either Pylance or Jedi regardless.

**Comment by arminus** [comment] 2021-01-05 22:29
The problems tab isn‘t cleared with pylance either.

Joyce Er <notifications@github.com> schrieb am Di. 5. Jan. 2021 um 22:48:

**Comment by arminus** [comment] 2021-01-07 10:19
@joyceerhl here's the full walk-through:

![PylanceJupyterErrors](https://user-images.githubusercontent.com/683680/103880929-0f04d680-50da-11eb-99fd-38a888874dbe.gif)

**Comment by joyceerhl** [comment] 2021-01-07 21:14
Thanks @arminus this is very helpful. I do repro the same behavior following that GIF. I briefly debugged this and it looks like we are correctly deleting the untitled file from our activeDocuments in notebookConverter.ts so not yet sure where the fix would be.

**Comment by arminus** [comment] 2021-01-07 21:24
IMHO this has nothing to do with an untitled file. I see this all the time with existing .ipynb files as well. The problem log accumulates errors but doesn't clear them in certain situations. Sometimes, I also see error markers in the ipynb itself not being removed. I'll try to come up with a 2nd repro case tomorrow.

**Comment by arminus** [comment] 2021-01-08 08:04
@joyceerhl here's the 2nd repro case:


https://user-images.githubusercontent.com/683680/103989727-70877c80-5190-11eb-974e-6ca9d80e263c.mp4

**Comment by chrisdias** [comment] 2021-03-24 19:14
I'm having similar issues... after working with a few cells, adding/removing code I end up with leftover errors that should be gone but they linger.

![image](https://user-images.githubusercontent.com/1487073/112370126-3f502000-8c9a-11eb-99f1-3299c024e77e.png)

This with latest Jupyter/Plyance/Python extensions installed in an Ubuntu 20.04 image running on WSL:

![image](https://user-images.githubusercontent.com/1487073/112370297-6e669180-8c9a-11eb-8261-1fff90345359.png)

**Comment by DonJayamanne** [comment] 2021-03-25 01:01
Looks like a duplicate of #5161

**Closed by DonJayamanne** 2021-03-25 01:01 UTC
Labels: bug

**Comment by arminus** [comment] 2021-03-25 07:50
@DonJayamanne - not sure why you close this, this ticket was earlier an has clear repros...

**Comment by DonJayamanne** [comment] 2021-03-25 19:17
@arminus unfortunately that doesn't work.
Please could you try VS Code Insiders, its possible there are some fixes in VS COde Insiders & our development branch that makes this go away (unlikely as Chris can replicate this in insiders).

**Comment by arminus** [comment] 2021-03-26 13:32
@DonJayamanne this ticket was originally reported for 1.53.0-inside, I'm still on an insider build and although it feels like the problem might occur less frequently, I still observe it. So I still don't understand why a ticket into which someone put some effort of providing repros gets closed as duplicate of a **newer** ticket. 

But, whatever, then I'll observe #5161 from now on.
