### ISSUE TITLE
Allow copy and pasting of image files.

### ISSUE THREAD

**Issue by aztecbinaynay** [microsoft/vscode-jupyter#6041] opened 2021-05-31 16:59 UTC
In a markdown cell, it would be super neat if I could put in pictures there by both copy and pasting an image and by selecting an image from any directories in my computer without the need for code. This would enable me to teach python programming in a more visual way.

**Comment by bogurd** [comment] 2021-06-01 14:54
Currently, there is an option to do this through the base64 encoding of the image. You would use the following in a markdown cell:
```
![](data:image/jpeg;base64,***Image base64 code***)
```

I would very much like if this were automatically done when pasting image content in a cell.

**Comment by DonJayamanne** [comment] 2021-06-03 21:28
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5774, https://github.com/microsoft/vscode/issues/119961

**Closed by DonJayamanne** 2021-06-03 21:28 UTC
Labels: enhancement
