### ISSUE TITLE
Opening up Data Viewer makes Variable View empty

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode-jupyter#7490] opened 2021-09-13 16:13 UTC
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1001228862
-   Python Extension version (available under the Extensions sidebar): v2021.9.1218897484
-   Python and/or Anaconda version: 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

Version: 1.61.0-insider (Universal)
Commit: ec40cbe164c59f3d13b6eff5fc7b0231ec0ab7aa
Date: 2021-09-13T05:13:59.036Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 20.6.0

## Problem

When I open the variable viewer for my notebook and then click on a dataframe the variable view on the bottom becomes undefined. 6:10 of [video log](https://msit.microsoftstream.com/video/71920840-98dc-ae72-3a43-f1ec149ab77a)

![image](https://user-images.githubusercontent.com/12758612/133119584-83e0d08a-7eb0-447a-a217-e02c45f6a3fc.png)

**Comment by greazer** [comment] 2021-09-13 22:22
Please dupe this.

**Comment by DavidKutu** [comment] 2021-09-13 22:36
Dupe of #7325

**Closed by DavidKutu** 2021-09-13 22:36 UTC
Labels: bug, info-needed, data-viewer, variable-explorer, needs-triage
