### ISSUE TITLE
I'm looking for a way to customize Kernel behaviour without creating a fork of vscode-jupyter.

### ISSUE THREAD

**Issue by drykovanov** [microsoft/vscode-jupyter#8761] opened 2022-01-21 15:12 UTC
For example I would like to append custom metadata to execute_request.

I was hoping to create a new VS Code extension, which hooks vscode-jupyter and provides it's own IKernelProvider through InversifyJS DI.

Unfortunately I've found that IKernelProvider and other components are instantiated immediately during extension activation and my extension doesn't have a chance to provide it's own implementation.

What is the recommended way to customize vscode-jupyter?

**Comment by amunger** [comment] 2022-01-21 23:03
It almost sounds like the new Kernel API that @DonJayamanne recently added would help [api.ts](https://github.com/microsoft/vscode-jupyter/blob/c2bbbaac060427e0f9e7af5cc786bf27aeb53ff5/src/client/api.ts#L51), but it looks like that API is just for reading, not providing your own. I'll have to check with him.

**Comment by drykovanov** [comment] 2022-01-24 07:36
> It almost sounds like the new Kernel API that @DonJayamanne recently added would help [api.ts](https://github.com/microsoft/vscode-jupyter/blob/c2bbbaac060427e0f9e7af5cc786bf27aeb53ff5/src/client/api.ts#L51), but it looks like that API is just for reading, not providing your own. I'll have to check with him.

Thank you @amunger! Looking forward to hearing from you and @DonJayamanne.
Besides adding custom metadata I'm looking for a way to hook/override notebook save.

**Comment by DonJayamanne** [comment] 2022-01-24 08:43
will update this issue with details tomorrow/next week.
we're currently in endgame

**Comment by DonJayamanne** [comment] 2022-01-24 18:57
> Besides adding custom metadata I'm looking for a way to hook/override notebook save.

I'm assuming you are after editing the metadata in the notebook. You can do this today using the VS Code API.
However this is still a proposed API.
If the VS Code API isn't sufficient, please could you file a separate issue and we can discuss that there.

**Comment by drykovanov** [comment] 2022-01-26 13:26
> I'm assuming you are after editing the metadata in the notebook. 

More like I was looking for a way to customize metadata attached to execute_request.
Currently even if I have "cellId" in notebook in cell metadata, it is overriden like this:
```
        // Generate metadata from our cell (some kernels expect this.)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const metadata: any = {
            ...(this.cell.metadata?.custom?.metadata || {}), // Send the Cell Metadata
            ...{ cellId: this.cell.document.uri.toString() }
        };
```

**Comment by DonJayamanne** [comment] 2022-01-31 02:19
I think we can fix that by reversing the order of the data.

**Comment by drykovanov** [comment] 2022-01-31 12:00
@DonJayamanne, thank you for the fix!

Still it would be great to have an option to override default extension behaviour by providing custom implementations.

**Comment by DonJayamanne** [comment] 2022-04-01 00:23
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/5532

**Closed by DonJayamanne** 2022-04-01 00:23 UTC
Labels: enhancement, notebook-kernel, documentation, debt, notebook-extensibility
