### ISSUE TITLE
Python version recognition error, resulting in a prompt that the current Python version is not supported

### ISSUE THREAD

**Issue by cosmic-latte** [microsoft/vscode-jupyter#15758] opened 2024-06-12 09:46 UTC
## Environment data

-   VS Code version: 1.90.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.5.0
-   Python Extension version (available under the Extensions sidebar): v2024.8.0
-   OS (Windows | Mac | Linux distro) and version: macOS 14.5
-   Python and/or Anaconda version: Anaconda 2024.02-1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

Unable to correctly identify the Python version of the virtual environment

In fact, the Python version of the base environment is 3.11.7, but it is recognized by vscode as 3.1-1, and then an error message is received: This version is not supported.

In my other conda venv, Python is 3.12.3, but it is also recognized as 3.1-1.

![2024-06-12 AM 10 42 16](https://github.com/microsoft/vscode-jupyter/assets/4134105/02b50319-ce51-48a0-ae1c-2f91c837fb1f)

Version recognized by vscode:
<img width="592" alt="2024-06-12 AM 10 28 38" src="https://github.com/microsoft/vscode-jupyter/assets/4134105/91433558-c74a-4136-aa16-b293982cf73e">

**Comment by Choumingzhao** [comment] 2024-06-12 09:59
I got similar error
![image](https://github.com/microsoft/vscode-jupyter/assets/17885419/1b0a6681-2737-4629-8df3-1cc0fbd74235)

**Comment by DonJayamanne** [comment] 2024-06-12 21:07
Duplicate of https://github.com/microsoft/vscode-python/issues/23580

**Closed by DonJayamanne** 2024-06-12 21:07 UTC
Labels: bug
