### ISSUE TITLE
Cells that should print output never terminate to do so, "silent" cells run fine

### ISSUE THREAD

**Issue by sjmielke** [microsoft/vscode-jupyter#4791] opened 2021-02-12 21:51 UTC
## Environment data

-   VS Code version: 1.54.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: Windows 10.0.19042
-   Python and/or Anaconda version: Python 3.8.5 in custom Anaconda
-   Type of virtual environment used: conda, global base env
-   Jupyter server running: Local, presumably

## Expected behaviour

Creating a new notebook, selecting the conda-based Python install and executing code that has output should show the output, but...

## Actual behaviour

...any cell that prints to stdout or stderr (or uses magic that does so like %%time) never terminates and never produces output. Cells that are "silent" run fine (and the fact that cells with slow code do take an appropriate amount of time to run makes me think that there is at least *some* connection to the kernel...).

## Steps to reproduce:

Fresh User install of VSCode Insiders under Windows 10 (Windows' Anaconda install; WSL2 is installed but not used), installing Jupyter and Python extensions, create a new notebook. A first cell that says `_ = 1` executes fine, but `1` or `%%time\n _ = 1` do not.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'NativeNotebookEditor'
Info 2021-02-12 16:45:52: Attempting to start a server because of preload conditions ...
Info 2021-02-12 16:45:52: ZMQ install verified.
Info 2021-02-12 16:45:52: Found existing keyfile at c:\Users\Sabrina\AppData\Roaming\Code - Insiders\User\globalStorage\ms-toolsai.jupyter\nbsecret
Info 2021-02-12 16:45:53: Attempting to start a server because of preload conditions ...
Info 2021-02-12 16:45:54: Trusting notebook...
Info 2021-02-12 16:45:54: Wrote trust for untitled:Untitled-1.ipynb to c:\Users\Sabrina\AppData\Roaming\Code - Insiders\User\globalStorage\ms-toolsai.jupyter\nbsignatures\6d06b82122aa8160f2475f938718fda4e92baad1e53ed21e72ae1be2d3ebf0ef
Info 2021-02-12 16:45:55: Find kernel spec, Class name = I, completed in 7ms, has a truthy return value, Arg 1: <Uri:Untitled-1.ipynb>, Arg 2: {"kernelspec":{"display_name":"Python 3.8.5 64-bit (conda)","metadata":{"interpreter":{"hash":"82a91a22060084f3e8dbe72ba49a002eddd687e7ed0e7d249946fe1b995c1ddc"}},"name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.5"},"orig_nbformat":2}, Arg 3: {"_isCancelled":false,"_emitter":null}, Arg 4: true, Return Value: {"kind":"startUsingPythonInterpreter","interpreter":{"architecture":3,"path":"C:\\Users\\Sabrina\\anaconda3\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysVersion":"3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]","sysPrefix":"C:\\Users\\Sabrina\\anaconda3","fileHash":"d8f75cb65560b81153187386c4ae1c1a9211d413be8e358d2d44187cae076f32ce345e6bce62b4452fc8d4d6def5758a751ab5994ac18e6ad8bc7f2a198be2b7","companyDisplayName":"Anaconda, Inc.","envType":"Conda","displayName":"Python 3.8.5 64-bit (conda)"}}
Error 2021-02-12 16:45:55: Jupyter Kernel Spec not found for a local connection
Info 2021-02-12 16:45:55: Cached data exists getEnvironmentVariables, <No Resource>
Info 2021-02-12 16:45:55: > ~\anaconda3\python.exe -c "import os;print(os.path.realpath("C:\\Users\\Sabrina\\AppData\\Roaming\\jupyter\\kernels"))"
> ~\anaconda3\python.exe -c "import os;print(os.path.realpath("C:\\Users\\Sabrina\\AppData\\Roaming\\jupyter\\kernels"))"
Info 2021-02-12 16:45:55: > ~\anaconda3\python.exe -c "import os;print(os.path.realpath("C:\\Users\\Sabrina\\AppData\\Roaming\\jupyter\\kernels"))"
> ~\anaconda3\python.exe -c "import os;print(os.path.realpath("C:\\Users\\Sabrina\\AppData\\Roaming\\jupyter\\kernels"))"
Info 2021-02-12 16:45:55: Loading kernelspec from C:\Users\Sabrina\anaconda3\share\jupyter\kernels\python3\kernel.json for C:\Users\Sabrina\anaconda3\python.exe
Info 2021-02-12 16:45:55: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-02-12 16:45:55: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
Info 2021-02-12 16:45:55: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
Info 2021-02-12 16:45:55: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
Info 2021-02-12 16:45:56: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 2021-02-12 16:45:56: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 2021-02-12 16:45:56: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
Info 2021-02-12 16:45:56: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2021-02-12 16:45:56: Python Daemon (pid: 4600): Execute rpc method prewarm_kernel in DS Daemon
Info 2021-02-12 16:45:56: Python Daemon (pid: 4600): Execute rpc method prewarm_kernel from C:\Users\Sabrina\anaconda3\python.exe
Info 2021-02-12 16:45:56: Python Daemon (pid: 4600): Pre-Warm DS Kernel in DS Kernel Launcher Daemon
Info 2021-02-12 16:45:56: Python Daemon (pid: 4600): Exec in DS Kernel Launcher Daemon (observable) ['C:\\Users\\Sabrina\\anaconda3\\python.exe', 'c:\\Users\\Sabrina\\.vscode-insiders\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\vscode_datascience_helpers\\..\\pyvsc-run-isolated.py', 'c:\\Users\\Sabrina\\.vscode-insiders\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\vscode_datascience_helpers\\kernel_prewarm_starter.py']
Info 2021-02-12 16:45:56: Python Daemon (pid: 4600): Exec in DS Kernel Launcher Daemon (observable)
Info 2021-02-12 16:45:56: Python Daemon (pid: 4600): Kernel launched, with PID 7188
Warn 2021-02-12 16:45:56: Python Daemon (pid: 4600): Waiting for Kernel to die 7188
Info 2021-02-12 16:45:56: Python Daemon (pid: 4600): Kernel launched, with PID as a daemon 7188
Info 2021-02-12 16:45:57: Execute Cell in kernelWithMetadata.ts
Info 2021-02-12 16:45:57: Creating raw notebook for untitled:Untitled-1.ipynb
Info 2021-02-12 16:45:57: Getting preferred kernel for untitled:Untitled-1.ipynb
Info 2021-02-12 16:45:57: Find kernel spec, Class name = I, completed in 4ms, has a truthy return value, Arg 1: <Uri:Untitled-1.ipynb>, Arg 2: {"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.5-final"},"orig_nbformat":2,"kernelspec":{"name":"python3","display_name":"Python 3.8.5 64-bit (conda)","metadata":{"interpreter":{"hash":"82a91a22060084f3e8dbe72ba49a002eddd687e7ed0e7d249946fe1b995c1ddc"}}}}, Arg 3: {"_isCancelled":false,"_emitter":null}, Arg 4: undefined, Return Value: {"kind":"startUsingPythonInterpreter","interpreter":{"architecture":3,"path":"C:\\Users\\Sabrina\\anaconda3\\python.exe","version":{"options":{"loose":false,"includePrerelease":false},"loose":false,"raw":"3.8.5-final","major":3,"minor":8,"patch":5,"prerelease":["final"],"build":[],"version":"3.8.5-final"},"sysVersion":"3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]","sysPrefix":"C:\\Users\\Sabrina\\anaconda3","fileHash":"d8f75cb65560b81153187386c4ae1c1a9211d413be8e358d2d44187cae076f32ce345e6bce62b4452fc8d4d6def5758a751ab5994ac18e6ad8bc7f2a198be2b7","companyDisplayName":"Anaconda, Inc.","envType":"Conda","displayName":"Python 3.8.5 64-bit (conda)"}}
Error 2021-02-12 16:45:57: Jupyter Kernel Spec not found for a local connection
Info 2021-02-12 16:45:57: Computing working directory untitled:Untitled-1.ipynb
Info 2021-02-12 16:45:57: Connecting to raw session for untitled:Untitled-1.ipynb
Info 2021-02-12 16:45:57: No custom variables for Kernel as interpreter path is not defined for kernel
Info 2021-02-12 16:45:57: Python Daemon (pid: 4600): Execute rpc method start_prewarmed_kernel in DS Daemon
Info 2021-02-12 16:45:57: Python Daemon (pid: 4600): Execute rpc method start_prewarmed_kernel from C:\Users\Sabrina\anaconda3\python.exe
Info 2021-02-12 16:45:57: Python Daemon (pid: 4600): Start pre-warmed Kernel in DS Kernel Launcher Daemon 7188 with args ['ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9003', '--control=9001', '--hb=9000', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"928c8b00-9466-4b3d-a328-c3b9592cf87e"', '--shell=9002', '--transport="tcp"', '--iopub=9004', '--f=C:\\Users\\Sabrina\\AppData\\Local\\Temp\\tmp-19144VxywYcZZJGMj.json']
Info 2021-02-12 16:45:57: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-02-12 16:45:57: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2021-02-12 16:45:57: Raw session started and connected
Started kernel Python 3.8.5 64-bit (conda)
Info 2021-02-12 16:45:57: Initial setup for untitled:Untitled-1.ipynb starting ...
Info 2021-02-12 16:45:57: Initialize config for plots for untitled:Untitled-1.ipynb
Info 2021-02-12 16:45:57: Kernel switching to busy
Info 2021-02-12 16:45:57: Kernel switching to idle
Info 2021-02-12 16:45:57: Initial setup complete for untitled:Untitled-1.ipynb
Info 2021-02-12 16:45:57: Finished connecting 236891e5-09d6-41ed-aa0b-5ef2c05122b4
Info 2021-02-12 16:45:57: Registering commtarget jupyter.widget
Info 2021-02-12 16:45:57: No custom variables for Kernel as interpreter path is not defined for kernel
Info 2021-02-12 16:45:57: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-02-12 16:45:57: Waiting for idle on (kernel): 5aafb106-aa61-425a-8c79-84093364dd8f -> idle
Info 2021-02-12 16:45:57: Finished waiting for idle on (kernel): 5aafb106-aa61-425a-8c79-84093364dd8f -> idle
Info 2021-02-12 16:45:57: Start cell execution for cell Index 0
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Execute rpc method prewarm_kernel in DS Daemon
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Execute rpc method prewarm_kernel from C:\Users\Sabrina\anaconda3\python.exe
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Pre-Warm DS Kernel in DS Kernel Launcher Daemon
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Exec in DS Kernel Launcher Daemon (observable) ['C:\\Users\\Sabrina\\anaconda3\\python.exe', 'c:\\Users\\Sabrina\\.vscode-insiders\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\vscode_datascience_helpers\\..\\pyvsc-run-isolated.py', 'c:\\Users\\Sabrina\\.vscode-insiders\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\vscode_datascience_helpers\\kernel_prewarm_starter.py']
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Exec in DS Kernel Launcher Daemon (observable)
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Kernel launched, with PID 12464
Warn 2021-02-12 16:45:57: Python Daemon (pid: 1740): Waiting for Kernel to die 12464
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Kernel launched, with PID as a daemon 12464
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Execute rpc method start_prewarmed_kernel in DS Daemon
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Execute rpc method start_prewarmed_kernel from C:\Users\Sabrina\anaconda3\python.exe
Info 2021-02-12 16:45:57: Python Daemon (pid: 1740): Start pre-warmed Kernel in DS Kernel Launcher Daemon 12464 with args ['ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9008', '--control=9006', '--hb=9005', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"95b31fd0-fdbc-4dd6-a470-4cfc155be13a"', '--shell=9007', '--transport="tcp"', '--iopub=9009', '--f=C:\\Users\\Sabrina\\AppData\\Local\\Temp\\tmp-19144j4GShvoXdIe6.json']
Info 2021-02-12 16:45:57: Kernel switching to busy
Info 2021-02-12 16:45:57: Kernel switching to idle
Info 2021-02-12 16:45:57: Completed cell execution for cell Index 0
Info 2021-02-12 16:45:58: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2021-02-12 16:45:58: Python Daemon (pid: 2556): Execute rpc method prewarm_kernel in DS Daemon
Info 2021-02-12 16:45:58: Python Daemon (pid: 2556): Execute rpc method prewarm_kernel from C:\Users\Sabrina\anaconda3\python.exe
Info 2021-02-12 16:45:58: Python Daemon (pid: 2556): Pre-Warm DS Kernel in DS Kernel Launcher Daemon
Info 2021-02-12 16:45:58: Python Daemon (pid: 2556): Exec in DS Kernel Launcher Daemon (observable) ['C:\\Users\\Sabrina\\anaconda3\\python.exe', 'c:\\Users\\Sabrina\\.vscode-insiders\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\vscode_datascience_helpers\\..\\pyvsc-run-isolated.py', 'c:\\Users\\Sabrina\\.vscode-insiders\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\vscode_datascience_helpers\\kernel_prewarm_starter.py']
Info 2021-02-12 16:45:58: Python Daemon (pid: 2556): Exec in DS Kernel Launcher Daemon (observable)
Info 2021-02-12 16:45:58: Python Daemon (pid: 2556): Kernel launched, with PID 9944
Warn 2021-02-12 16:45:58: Python Daemon (pid: 2556): Waiting for Kernel to die 9944
Info 2021-02-12 16:45:58: Python Daemon (pid: 2556): Kernel launched, with PID as a daemon 9944
Info 2021-02-12 16:45:58: Execute Cell in kernelWithMetadata.ts
Info 2021-02-12 16:45:58: Start cell execution for cell Index 1
Info 2021-02-12 16:45:58: Kernel switching to busy
Info 2021-02-12 16:45:59: Trusting notebook...
Info 2021-02-12 16:46:05: restartKernel - finishing cells that are outstanding
Info 2021-02-12 16:46:05: restartKernel - restarting kernel
Info 2021-02-12 16:46:05: Restarting 5aafb106-aa61-425a-8c79-84093364dd8f
Info 2021-02-12 16:46:05: Got new session e9e7d3ac-cdf5-4026-94a9-06d3022282d7
Info 2021-02-12 16:46:05: Started new restart session
Info 2021-02-12 16:46:05: shutdownSession 5aafb106-aa61-425a-8c79-84093364dd8f - start
Info 2021-02-12 16:46:05: restartKernel - initialSetup
Info 2021-02-12 16:46:05: Initial setup for untitled:Untitled-1.ipynb starting ...
Info 2021-02-12 16:46:05: Initialize config for plots for untitled:Untitled-1.ipynb
Info 2021-02-12 16:46:05: No custom variables for Kernel as interpreter path is not defined for kernel
Info 2021-02-12 16:46:05: Kernel switching to busy
Info 2021-02-12 16:46:05: Kernel switching to idle
Info 2021-02-12 16:46:05: Initial setup complete for untitled:Untitled-1.ipynb
Info 2021-02-12 16:46:05: restartKernel - initialSetup completed
Info 2021-02-12 16:46:05: Registering commtarget jupyter.widget
Info 2021-02-12 16:46:05: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
Info 2021-02-12 16:46:05: KernelProcess output: Content-Length: 121
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"Execute rpc method kill_kernel in DS Daemon","pid":4600}}Content-Length: 155
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"Execute rpc method kill_kernel from C:\\Users\\Sabrina\\anaconda3\\python.exe","pid":4600}}Content-Length: 118
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"INFO","msg":"Kill kernel in DS Kernel Launcher Daemon","pid":4600}}Content-Length: 38
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":3,"result":null}
Info 2021-02-12 16:46:05: Python Daemon (pid: 4600): Execute rpc method kill_kernel in DS Daemon
Info 2021-02-12 16:46:05: Python Daemon (pid: 2556): Execute rpc method start_prewarmed_kernel in DS Daemon
Info 2021-02-12 16:46:05: KernelProcess output: Content-Length: 117
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"log","params":{"level":"WARNING","msg":"Kernel has exited with exit code 1, ","pid":4600}}Content-Length: 77
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","method":"kernel_died","params":{"exit_code":1,"reason":""}}
Info 2021-02-12 16:46:05: Python Daemon (pid: 4600): Execute rpc method kill_kernel from C:\Users\Sabrina\anaconda3\python.exe
Info 2021-02-12 16:46:05: Python Daemon (pid: 2556): Execute rpc method start_prewarmed_kernel from C:\Users\Sabrina\anaconda3\python.exe
Info 2021-02-12 16:46:05: Python Daemon (pid: 4600): Kill kernel in DS Kernel Launcher Daemon
Info 2021-02-12 16:46:05: Python Daemon (pid: 2556): Start pre-warmed Kernel in DS Kernel Launcher Daemon 9944 with args ['ipykernel_launcher', '--ip=127.0.0.1', '--stdin=9013', '--control=9011', '--hb=9010', '--Session.signature_scheme="hmac-sha256"', '--Session.key=b"b59465fb-6d45-4441-a10f-a4b3cfc9ba81"', '--shell=9012', '--transport="tcp"', '--iopub=9014', '--f=C:\\Users\\Sabrina\\AppData\\Local\\Temp\\tmp-19144DEuqlnGTKz0g.json']
Info 2021-02-12 16:46:05: shutdownSession 5aafb106-aa61-425a-8c79-84093364dd8f - shutdown complete
Warn 2021-02-12 16:46:05: Python Daemon (pid: 4600): Kernel has exited with exit code 1, 
Info 2021-02-12 16:46:05: Waiting for idle on (kernel): e9e7d3ac-cdf5-4026-94a9-06d3022282d7 -> idle
Info 2021-02-12 16:46:05: Finished waiting for idle on (kernel): e9e7d3ac-cdf5-4026-94a9-06d3022282d7 -> idle
Info 2021-02-12 16:46:05: Kernel died [r [Error]: Kernel died with exit code 1. 
	at c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:47:758009
	at c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:47:421842
	at c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:47:422060
	at Immediate._onImmediate (c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:47:423625)
	at processImmediate (internal/timers.js:456:21)] {
  exitCode: 1,
  reason: ''
} 
Info 2021-02-12 16:46:05: Completed cell execution for cell Index 1
Info 2021-02-12 16:46:05: KernelProcess Exit Exit - null
Info 2021-02-12 16:46:05: Completed cell execution for cell Index 1
Info 2021-02-12 16:46:06: > ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\anaconda3\python.exe c:\Users\Sabrina\.vscode-insiders\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Info 2021-02-12 16:46:06: Python Daemon (pid: 4484): Execute rpc method prewarm_kernel in DS Daemon
Info 2021-02-12 16:46:06: Python Daemon (pid: 4484): Execute rpc method prewarm_kernel from C:\Users\Sabrina\anaconda3\python.exe
Info 2021-02-12 16:46:06: Python Daemon (pid: 4484): Pre-Warm DS Kernel in DS Kernel Launcher Daemon
Info 2021-02-12 16:46:06: Python Daemon (pid: 4484): Exec in DS Kernel Launcher Daemon (observable) ['C:\\Users\\Sabrina\\anaconda3\\python.exe', 'c:\\Users\\Sabrina\\.vscode-insiders\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\vscode_datascience_helpers\\..\\pyvsc-run-isolated.py', 'c:\\Users\\Sabrina\\.vscode-insiders\\extensions\\ms-toolsai.jupyter-2020.12.414227025\\pythonFiles\\vscode_datascience_helpers\\kernel_prewarm_starter.py']
Info 2021-02-12 16:46:06: Python Daemon (pid: 4484): Exec in DS Kernel Launcher Daemon (observable)
Info 2021-02-12 16:46:06: Python Daemon (pid: 4484): Kernel launched, with PID 6276
Warn 2021-02-12 16:46:06: Python Daemon (pid: 4484): Waiting for Kernel to die 6276
Info 2021-02-12 16:46:06: Python Daemon (pid: 4484): Kernel launched, with PID as a daemon 6276
Info 2021-02-12 16:46:06: Trusting notebook...
```

</p>
</details>

**Comment by claudiaregio** [comment] 2021-02-13 01:21
Hi @sjmielke, I am not able to reproduce at this time. Will have someone take a look asap

**Comment by sjmielke** [comment] 2021-02-13 01:26
Makes sense. It feels really strange and I figured the best way might be if I could look into any more-debuggy debug output to see what more exactly fails when trying to communicate results back from the kernel to VS Code---don't know whether that's easy or doable without straight-up recompiling from scratch with more tracing?

**Comment by rBatist4** [comment] 2021-02-13 20:46
I have exactly the same problem and with the same versions of everything mentioned by the author, it started from yesterday when VS Code updated. I am looking everywhere for an earlier version of VSCode on the internet but to no avail.

**Comment by greazer** [comment] 2021-02-16 23:06
Dupe of #4796

**Closed by greazer** 2021-02-16 23:06 UTC
Labels: bug
