### ISSUE TITLE
jupyter in vscode cannot display audio

### ISSUE THREAD

**Issue by Darius-H** [microsoft/vscode-jupyter#10020] opened 2022-05-13 08:00 UTC
The code below cannot display audio correctly in vscode. The audio length is 0. But it can run correctly if i open jupyter in Chrome browser.
```
from IPython.display import Audio, display
display(Audio("_assets\speech.wav"))
```

**Comment by amunger** [comment] 2022-05-13 19:40
duplicate of https://github.com/microsoft/vscode-jupyter/issues/1012

**Closed by amunger** 2022-05-13 19:40 UTC
Labels: bug, triage-needed
