### ISSUE TITLE
Failure to connect to kernel depending on how interpreter is triggered

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-jupyter#10375] opened 2022-06-08 20:03 UTC
## Environment data

-   VS Code version: 1.67.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1021342353
-   Python Extension version (available under the Extensions sidebar): v2022.6.3
-   OS (Windows | Mac | Linux distro) and version: macOS 12.4 (ARM variety)
-   Python and/or Anaconda version: mixture of many (xcode-select, homebrew, pyenv, venvs)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): multiple
-   Jupyter server running: Local

## Steps to reproduce:
* Configure vscode to preserve previous tabs and windows upon launch, and to preserve unsaved files.
* Configure vscode to launch an interactive ipython instead of regular python when running python code with the shift+Enter shortcut.
* Open some folder with python files in vscode.
* Create some unsaved python files.
* Try launching the interactive python interpreter in the following ways:
    * (a) By bringing in the command palette and choosing the option there for "Jupyter: Create interactive window".
    * (b) By launching a new vscode window and doing the same thing.
    * (c) By selecting some python code and triggering the shift+Enter shorcut in a saved python file.
    * (d) By doing the same thing but selecting from from an unsaved file

## Expected behaviour
All of these should correctly trigger the interactive interpreter.

## Actual behaviour
Cases A and D fail to connect to the ipython kernel, regardless of which kernel is selected, while cases B and C always succeed. Trying the same things in an x86-64 linux machine with the same versions of vscode and extensions works correctly.

**Comment by rchiodo** [comment] 2022-06-08 20:12
Thanks for the issue. Can you repro steps A and D and include your jupyter output log? (It's on the 'output' tab). 

My guess is that the default interpreter is either not set or set to something that doesn't have ipykernel installed. Whereas for B and C it's using the interpreter for the active python file. 

The python extension has the concept of the 'selected interpreter'. We use that when opening an interactive window.

This is also likely why it works on the other machine.

**Comment by david-cortes** [comment] 2022-06-08 20:14
> Thanks for the issue. Can you repro steps A and D and include your jupyter output log? (It's on the 'output' tab).
> 
> My guess is that the default interpreter is either not set or set to something that doesn't have ipykernel installed. Whereas for B and C it's using the interpreter for the active python file.
> 
> The python extension has the concept of the 'selected interpreter'. We use that when opening an interactive window.
> 
> This is also likely why it works on the other machine.

It still fails to connect if I manually change the interpreter. The error message doesn't list anything particularly informative.

**Comment by rchiodo** [comment] 2022-06-08 20:14
The output logs should tell us what the issue is.

**Comment by david-cortes** [comment] 2022-06-08 20:16
And by the way, all of these ways of launching it were working correctly a few days ago. Not sure what updated and broke things along the way.

**Comment by rchiodo** [comment] 2022-06-08 20:26
It's hard to say without seeing what the exact failure is. The log should tell us what python command ran and what its exact output is.

**Comment by david-cortes** [comment] 2022-06-11 15:47
> It's hard to say without seeing what the exact failure is. The log should tell us what python command ran and what its exact output is.

@rchiodo Here's some of the output logs. They unfortunately do not provide any hint of what went wrong. The kernel to which it tries to connect is the exact same one in all scenarios mentioned in the description
![pt1](https://user-images.githubusercontent.com/11860098/173194948-34eff635-d692-42fe-a7e1-dcd8d6f6b1ef.jpg)
![pt2](https://user-images.githubusercontent.com/11860098/173194971-16aace89-dc39-48fc-a593-813ae0f31cf5.jpg)
![pt3](https://user-images.githubusercontent.com/11860098/173194972-9e1fcff4-7685-4791-8522-7c7d979cb000.jpg)
.

**Comment by david-cortes** [comment] 2022-06-13 16:51
@rchiodo Launching `./jupyter notebook` directly from the `bin` folder in the environment works correctly (launches jupyter, is able to connect through a web browser, create a notebook, and connect to the kernel). Launching it from what it finds under the `PATH` environment variable (a different python environment) also works correctly.

**Comment by rchiodo** [comment] 2022-06-13 16:53
There's a line in the output that describes the exact way we start it. It's right after 'Starting Jupyter Notebook'. Can you try that way?

**Comment by rchiodo** [comment] 2022-06-13 16:57
There's also a custom kernel spec that we generate. It's listed later on. That might be where the problem is too. That's the kernel spec we tell juptyer to use to launch the kernel. 

Additionally this might be caused by the PYTHONNOUSERSITE variable we used to add when starting a kernel. We've since removed this variable (you're on last month's build). That variable affects the sys.path for finding modules and things and might affect the startup of your kernel.

**Comment by david-cortes** [comment] 2022-06-13 17:47
> There's a line in the output that describes the exact way we start it. It's right after 'Starting Jupyter Notebook'. Can you try that way?

I don't think that's the command since it doesn't include "jupyter". If I take the path to the python binary, add `-m jupyter`, and then paste what it says after "with command line", then I get an error as follows:
```
jupyter.py: error: argument --config-dir: ignored explicit argument <long path with /var/folder/random characters/more/stuff/jupyter_notebook_config.py>
```

I'm not sure the path is supposed to keep existing since it looks autogenerated.

**Comment by rchiodo** [comment] 2022-06-13 17:50
Oh that's our autogenerated config file. We send that in case you have your own jupyter config file that might be breaking things. You should be able to skip that argument.

**Comment by rchiodo** [comment] 2022-06-13 18:08
That may be the root cause of the error. You have a module named 'code' in your working directory. Jupyter internally may require a package named 'code'. It would at least explain the failure.

**Comment by rchiodo** [comment] 2022-06-13 18:11
Not sure why the 'code' module you have there is being found, but that sure looks like the root cause of the problem. Is that a path in your workspace?

**Comment by david-cortes** [comment] 2022-06-13 18:14
> Not sure why the 'code' module you have there is being found, but that sure looks like the root cause of the problem. Is that a path in your workspace?

It is a path under which some of the files I have opened in vscode are located.

I can also confirm that if I create a folder `code` with a file `__init__.py` on jupyter's default directory, it will fail to connect to some kernels, and the bug happens also in linux.

I am not sure however why vscode is choosing to launch the interpreter precisely from that folder when I trigger it from an unsaved file or from the command palette.

**Comment by rchiodo** [comment] 2022-06-13 18:19
Reopening as we could do a better job here of surfacing kernel launch errors. Ultimately it was a problem with a dupe module, but it's super hard to tell that.

**Comment by DonJayamanne** [comment] 2022-08-01 20:17
This should now be fixed in the latest pre-release, 
you can install the latest pre-release version of the Jupyter extension after installing vscode insiders or wait for the latest release (some time this week).
If that still doesn't work, please feel free to re-open this issue or create a new issue.

**Closed by DonJayamanne** 2022-08-01 20:18 UTC
Labels: bug, kernel-crash

**Comment by DonJayamanne** [comment] 2022-08-24 04:19
Steps to verify:
* Open workspace folder
* Create a python file named `code.py` in root directory
* Create a python file named `sample.py` in root directory with the following content
```
#%%
print('Hello World')
```
* Run the above cell and verify you get a message about `code.py` causing issues with kernel
* Repeat the above step with a notebook and verify you get a similar message warning about `code.py`.

**Comment by aiday-mar** [comment] 2022-08-25 12:22
I get the following error  in both cases:

i.e.: the module "code" could not be imported because it is shadowed by:
c:\Users\t-aidaym\work\test\code.py
Please rename this file/folder so that the original module from the standard library can be imported. 

Which I suppose is expected, so I will put the verified label on it.
