### ISSUE TITLE
VSCode Jupyter does not render mathematical symbols correctly.

### ISSUE THREAD

**Issue by animehunter123** [microsoft/vscode-jupyter#6535] opened 2021-07-06 02:09 UTC
## Environment
-   VS Code version: 1.57
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.832593372 (and later)
-   Python Extension version (available under the Extensions sidebar): v2021.5.926500501 (and later)
-   OS Windows : 20H2
-   Python and/or Anaconda version: 3.8.7

## Expected behavior

Expected to see the 4/3 fraction displayed as a fraction (just as it displays on github. Expected similarly for r^cubed.

## Actual behavior

Saw 4/3 displayed incorrectly. Same for r^cubed.

## Steps to reproduce:
* Clone the Pierian-Data Python3 Bootcamp Locally
* Open the lesson #08 in the browser: https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/blob/master/03-Methods%20and%20Functions/08-Functions%20and%20Methods%20Homework.ipynb
* Open the same notebook in VSCode.
* You will see that the characters for 4/3 and r cubed are not rendered correctly (as $$\frac{4}{3} πr^3$$)

What can be done to fix this? All math notebooks with formula symbols have this issue.
![jupyternotebook-not-showing-mathsymbols](https://user-images.githubusercontent.com/42163211/124531976-8e395400-de4a-11eb-8457-c602fbd88ac3.png)

**Comment by IanMatthewHuff** [comment] 2021-07-06 19:59
I can confirm the repro here:
![image](https://user-images.githubusercontent.com/812783/124658609-d19abf00-de58-11eb-9d10-32ccf5521abb.png)

Looking at the code there are unknown characters for that pi symbol which seems to causing the issue. I tried the following formula using /pi for the pi representation:
> $$\frac 4 3 \pi r^3$$
Is this what you are trying to render?
![image](https://user-images.githubusercontent.com/812783/124659613-02c7bf00-de5a-11eb-8d38-1a5b7f644cbe.png)

**Comment by animehunter123** [comment] 2021-07-07 01:35
Yes, that is what I am trying to rendor. It doesnt appear like that in VSCode for some reason.

**Comment by IanMatthewHuff** [comment] 2021-07-07 15:14
Yup I repro the π symbol as working in jupyter notebook and having to be replaced with /pi in vscode. Thanks for the reply I think that we've got the issue understood on our side now.

**Comment by greazer** [comment] 2021-07-08 20:34
Dupe of microsoft/vscode#119536

**Comment by mjbvz** [comment] 2021-08-05 06:00
In the original notebook example, the equation is inside of an html element:

```
<p>The volume of a sphere is given as $$\frac{4}{3} πr^3$$</p>
```

It seems to render fine if you don't use an html element

Closing as a duplicate of https://github.com/microsoft/vscode/issues/130149

**Closed by mjbvz** 2021-08-05 06:01 UTC
Labels: bug
