### ISSUE TITLE
`Interactive Window: Focus Input Editor` command appears in palette even when no interactive window is open

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#12628] opened 2023-01-24 19:14 UTC
Testing #12613

Executing this command from the palette does nothing if there's no interactive window open. I would expect this to be hidden if there's no open IW.

**Comment by amunger** [comment] 2023-01-24 21:48
dupe of https://github.com/microsoft/vscode/issues/161924, not sure how to fix this

**Closed by amunger** 2023-01-24 21:48 UTC
