### ISSUE TITLE
zmq package does not work on Mac High Sierra (results in EH restart)

### ISSUE THREAD

**Issue by angel-blake** [microsoft/vscode-jupyter#13642] opened 2023-06-03 10:16 UTC
## Environment data

-   VS Code version: 1.78.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.3.1000892223 (and above)
-   Python Extension version (available under the Extensions sidebar): v2023.8.0
-   OS (Windows | Mac | Linux distro) and version: macOS High Sierra 10.13.6
-   Python and/or Anaconda version: Python 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv

### VS Code

- Version: 1.78.2
- Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
- Date: 2023-05-10T14:44:45.204Z (3 wks ago)
- Electron: 22.5.2
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin x64 17.7.0
- Sandboxed: Yes

### VS Code - Insiders

- Version: 1.79.0-insider (Universal)
- Commit: 05ae089c791aa5c8ec05abd5687c9a31517579bc
- Date: 2023-06-02T09:42:42.311Z (23 hrs ago)
- Electron: 22.5.5
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin x64 17.7.0

## Expected behaviour

Kernel should load properly and allow to `Select Another Kernel...` (if necessary).

## Actual behaviour

Kernel crashes with the following error message:

`Extension host terminated unexpectedly 3 times within the last 5 minutes.`

The option `Select Another Kernel...` is empty. No other kernels can be selected.

Afterwards, although `Jupyter` is installed, VS Code outputs the following error message:

`Error: Cannot open resource with notebook editor type 'jupyter-notebook'...`

## Steps to reproduce:

It turns out that one of the `node modules` of `ms-toolsai.jupyter`, i.e. `zeromq` is the culprit.

Newer versions of `ms-toolsai.jupyter` load `node.napi.glibc.node` instead of `node.napi.node`. Note that `node.napi.glibc.node` was built for macOS Catalina 10.15. Also note that these newer versions come shipped with two folders, namely `zeromq` and `zeromqold`. Somehow, `zeromqold` is not loaded in case that `zeromq` fails. Else, 

What's the purpose of `zeromqold`?

## Temporary solution

To solve this for older versions of macOS, either:

1. Manually replace `node.napi.glibc.node` with `node.napi.node`.
or
2. Rename the `zeromq` to `zeromqnew`, and `zeromqold` to `zeromq`.

Preferably save a backup as `node.napi.glibc.node.bak` just in case.

## Logs

<details>

<summary><code>Command Palette</code> > <code>Developer: Toggle Developer Tools</code>
</summary>

<p>

```
[Extension Host] Starting WebSocket: RAW/api/kernels/b7ad93b0-b61d-418a-93a8-adb9d7ae5a64 (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:161026))

Starting WebSocket: RAW/api/kernels/b7ad93b0-b61d-418a-93a8-adb9d7ae5a64
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
    Referenced from: /Users/user-1/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node (which was built for Mac OS X 10.15)
    Expected in: /usr/lib/libSystem.B.dylib
dyld: Symbol not found: ____chkstk_darwin
    Referenced from: /Users/user-1/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.4.1011241018-darwin-x64/out/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node (which was built for Mac OS X 10.15)
    Expected in: /usr/lib/libSystem.B.dylib

The extension host (LocalProcess) terminated unexpectedly. Code: 6, Signal: unknown
```

</p>
</details>

## Remarks

Please fix this as soon as possible, at least for the Jupyter Pre-Release Version. Thanks!

**Comment by DonJayamanne** [comment] 2023-06-03 10:53
Thank you for filling this issue and sorry you are running into this.

> Catalina 10.15. 

Ok so that could be the problem. I will look into this asap.
Thank you very much for the information and the logs

> Also note that these newer versions come shipped with two folders, namely zeromq and zeromqold. Somehow, zeromqold is not loaded in case that zeromq fails. Else,


The old folder is a backup of the first fails to load. Looks like we fail to list from the first folder, however this crashes the extension host hence never goes to the backup.

I will look into this asap.
@deepak1556 /cc

**Comment by DonJayamanne** [comment] 2023-06-04 23:35
Just wanted to get a few things first,
@angel-blake 
What version of MacOS do you have, Do you have `High Sierra`?

**Comment by angel-blake** [comment] 2023-06-05 04:55
> Do you have `High Sierra`?

Yes. As per the context of the issue opened, the latest macOS High Sierra 10.13.6 Final Version (Build 17G65).

**Comment by DonJayamanne** [comment] 2023-06-05 20:04
@deepak1556 thank you very much, will try that.

**Comment by DonJayamanne** [comment] 2023-06-05 21:11
@angel-blake 
* Please could you download the following file, extract it
* Go into VS Code Insiders and from the command palette install this using the command `Install from VSIX`
* Let me know how this goes
* Please remember to use VS Code Insiders

[ms-toolsai-jupyter-insiders.vsix (2).zip](https://github.com/microsoft/vscode-jupyter/files/11657726/ms-toolsai-jupyter-insiders.vsix.2.zip)

**Comment by angel-blake** [comment] 2023-06-06 15:41
Thank you for your response @DonJayamanne.

I followed all the steps (one-to-one), and sadly it still results in the same error:

> [Extension Host] Starting WebSocket: RAW/api/kernels/... (at console.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:99:161026))
> 
> Starting WebSocket: RAW/api/kernels/...
> dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
>     Referenced from: /Users/user-1/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.6.100/out/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node (which was built for Mac OS X 10.15)
>     Expected in: /usr/lib/libSystem.B.dylib
> dyld: Symbol not found: ____chkstk_darwin
>     Referenced from: /Users/user-1/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.6.100/out/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node (which was built for Mac OS X 10.15)
>     Expected in: /usr/lib/libSystem.B.dylib
> 
> The extension host (LocalProcess) terminated unexpectedly. Code: 6, Signal: unknown

Note that Jupyter v2023.6.100 was successfully via `Extensions: Install from VSIX...`

---

### Suggestion:

Instead of having two folders lying around, i.e. `zeromq` and `zeromqold`, why don't you add both of the files `node.napi.glibc.node` and `node.napi.node` to `darwin-x64` and `darwin-arm64`? Then, simply check for the corresponding macOS release version with a conditional clause. You could use [the OS module](http://nodejs.org/api/os.html#os_os_platform) like this:

```
var os = require('os');
os.platform(); // 'darwin'
os.release(); //  '10.8.0'
```

and then map the release version to a specific version of macOS. Darwin to macOS mappings can be found [here](http://en.wikipedia.org/wiki/Darwin_%28operating_system%29#Release_history).

Essentially, any `os.release() >= 19.0.0` should load `node.napi.glibc.node`, else load `node.napi.node`.

**Comment by deepak1556** [comment] 2023-06-06 16:11
@DonJayamanne the logs shows the module is still built for `10.15`, can you check if the versions are correct

```
dyld: Symbol not found: ____chkstk_darwin
Referenced from: /Users/user-1/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.6.100/out/node_modules/zeromq/prebuilds/darwin-x64/node.napi.glibc.node (which was built for Mac OS X 10.15)
```

**Comment by angel-blake** [comment] 2023-06-06 16:13
> the logs shows the module is still built for `10.15`

Precisely @deepak1556, `node.napi.glibc.node` was built for macOS 10.15. Hence, my suggestion.

**Comment by DonJayamanne** [comment] 2023-06-06 20:10
@angel-blake thanks for the suggestions, unfortunately we're using existing packages like node-gyp that loads native packagbes.
@deepak1556 I missed another place where 10.15 is set, the build.ts file has a hardcoded setting of 10.15 that seems to only apply to arm, but they change it for intel builds as well. will re-create another build.

**Comment by angel-blake** [comment] 2023-06-07 09:36
@DonJayamanne the last `VSIX` build also results in the same error. The extension still loads `node.napi.glibc.node`.

AFAIK, `node-gyp` is a cross-platform command-line tool written in Node.js for compiling native addon modules for Node.js. I really don't understand why you don't add both of the files `node.napi.glibc.node` and `node.napi.node` to the `zeromq` prebuilds and add the conditional clause to check for the macOS version before compiling the code. This way, the issue could've been solved already. Please correct me if I'm wrong.

**Comment by DonJayamanne** [comment] 2023-06-07 09:50
> zeromq/.../node.napi.glibc.node

This issue built for Marcos, built by us using azure piplelines

> zeromq old/../node.napi.node

Those is the old binary build and published in npm, we are trying to move away from this as this binary 

We cannot add both into the same folder and make it work the way you have suggested.
Loading goes don't work the way your suggested, we do not load them the existing node packages look for files and load them.

The problem is not that we are still loading the wrong file, the root cause is the fact that the file does not load and we need to fix that.

That's what I'm trying to do, trying to recompile the file to ensure it loads on your machine.
Ie we need to compiler the file for 10.9, instead of trying to load different files.
The zeromqold is loaded if the first fails, unfortunately it brings down the whole process hence the backup fails.

@deepak1556  let's chat tomorrow about this and try to figure out what's wrong with the compilation

**Comment by angel-blake** [comment] 2023-06-07 10:31
> We cannot add both into the same folder and make it work the way you have suggested. Loading goes don't work the way your suggested, we do not load them the existing node packages look for files and load them.
> 
> The problem is not that we are still loading the wrong file, the root cause is the fact that the file does not load and we need to fix that.
> 
> That's what I'm trying to do, trying to recompile the file to ensure it loads on your machine. Ie we need to compiler the file for 10.9, instead of trying to load different files. The zeromqold is loaded if the first fails, unfortunately it brings down the whole process hence the backup fails.

I see @DonJayamanne. Thanks for the explanation!

**Comment by DonJayamanne** [comment] 2024-04-02 02:49
This should now be fixed in the latest versions of VS Code and Jupyter extension

**Closed by DonJayamanne** 2024-04-02 02:49 UTC
Labels: bug, notebook-kernel, zmq
