### ISSUE TITLE
re-opening this since it has a good explanation of the remaining issue - that latex doesn't render within plotly widgets

### ISSUE THREAD

**Issue by zachsiegel-capsida** [microsoft/vscode-jupyter#13165] opened 2023-03-25 04:03 UTC
> "re-opening this since it has a good explanation of the remaining issue - that latex doesn't render within plotly widgets"
    _Originally posted by @amunger in https://github.com/microsoft/vscode-jupyter/issues/8131#issuecomment-1339642577_
            

I still experience this issue. Thank you very much for the wonderful VS Code - Jupyter support!

**Comment by DonJayamanne** [comment] 2023-03-25 04:33
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8131#issuecomment-1339642577

that issue is still open hence let’s track that issue there

**Closed by DonJayamanne** 2023-03-25 04:33 UTC
