### ISSUE TITLE
vscode insides jupyter notebook  undo Ctrl+z will kill the kernel

### ISSUE THREAD

**Issue by pheman** [microsoft/vscode-jupyter#4272] opened 2020-12-29 03:32 UTC
## Environment data

-   VS Code version: 1.53.0 insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.431416030-dev
-   OS (Windows | Mac | Linux distro) and version: Win7
-   Python and/or Anaconda version: python3.6.10, Anaconda3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour
Ctrl+z is the shortcut of Undo an operation.

## Actual behaviour
After Ctrl+z, the kernel seems to be dead.
to reproduce this bug, 
1. just type the codes below in one notebook cell, 
`import time`
`time.sleep(4)`
`a = 1`

2. run the cell once
3. Ctrl+z, and the cell will stay in  running status until closing the notebook.

**Comment by joyceerhl** [comment] 2020-12-30 18:28
Hi @pheman, thanks for filing a bug. We have an identical report for this issue so I'm going to close this is as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/1682.

**Closed by joyceerhl** 2020-12-30 18:28 UTC
Labels: bug
