### ISSUE TITLE
Notebook will not connect to Jupyter server in VS Code

### ISSUE THREAD

**Issue by ayushnoori** [microsoft/vscode-jupyter#14263] opened 2023-09-05 23:12 UTC
## Environment data

-   VS Code version: 1.81.1 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.7.1002162226
-   Python Extension version (available under the Extensions sidebar): v2023.14.0
-   OS (Windows | Mac | Linux distro) and version: CentOS Linux release 7.9.2009 (Core)
-   Python and/or Anaconda version: Python 3.9.14
-   Type of virtual environment used: `virtualenv`
-   Jupyter server running: Local, but in remote development environment

## Bug report

I am using a Jupyter Notebook in VS Code running in a remote environment with the Microsoft Remote Development Extension Pack. I have a virtual environment created using `virtualenv` as follows, in which Python is installed:
```
virtualenv my_env
source my_env/bin/activate
pip install torch torchvision torchaudio
pip install pyg_lib torch_scatter torch_sparse -f https://data.pyg.org/whl/torch-1.13.1+cu117.html
pip install jupyter jupyterlab notebook
pip install pandas scipy matplotlib
pip install urllib3==1.26.6
```

I launch a Jupyter Notebook server with the following:
```
source my_env/bin/activate
jupyter notebook --port=54321 --browser='none'
```
I then attempt to connect to the server from the GUI with Select Kernel > Existing Jupyter Server... > Enter the URL of a running Jupyter server. However, I receive the following error at the GUI (which appears as a red box): "Connection failure. Verify the server is running and reachable from a browser. (Invalid response: 404 Not Found)."

Would appreciate any assistance. Happy to answer more questions about my setup.

My Jupyter logs are below.

```
[I 2023-09-05 19:00:52.337 ServerApp] Package notebook took 0.0001s to import
[I 2023-09-05 19:00:52.386 ServerApp] Package jupyter_lsp took 0.0477s to import
[W 2023-09-05 19:00:52.386 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 19:00:52.404 ServerApp] Package jupyter_server_terminals took 0.0179s to import
[I 2023-09-05 19:00:52.406 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-09-05 19:00:53.005 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-09-05 19:00:53.005 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-09-05 19:00:53.007 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-09-05 19:00:53.020 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-09-05 19:00:53.035 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-09-05 19:00:53.045 ServerApp] notebook | extension was successfully linked.
[I 2023-09-05 19:00:53.498 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-09-05 19:00:53.580 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-09-05 19:00:53.582 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-09-05 19:00:53.583 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-09-05 19:00:53.596 LabApp] JupyterLab extension loaded from my_env/lib/python3.9/site-packages/jupyterlab
[I 2023-09-05 19:00:53.596 LabApp] JupyterLab application directory is my_env/share/jupyter/lab
[I 2023-09-05 19:00:53.597 LabApp] Extension Manager is 'pypi'.
[I 2023-09-05 19:00:53.600 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-09-05 19:00:53.608 ServerApp] notebook | extension was successfully loaded.
[I 2023-09-05 19:00:53.609 ServerApp] Serving notebooks from local directory: XXX
[I 2023-09-05 19:00:53.609 ServerApp] Jupyter Server 2.7.0 is running at:
[I 2023-09-05 19:00:53.610 ServerApp] http://localhost:54321/tree?token=ba7bc90e2faceef8725bd66a54235d616f840595184a5fee
[I 2023-09-05 19:00:53.610 ServerApp]     http://127.0.0.1:54321/tree?token=ba7bc90e2faceef8725bd66a54235d616f840595184a5fee
[I 2023-09-05 19:00:53.610 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2023-09-05 19:00:53.631 ServerApp] No web browser found: Error('could not locate runnable browser').
[C 2023-09-05 19:00:53.631 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/XXX/.local/share/jupyter/runtime/jpserver-125728-open.html
    Or copy and paste one of these URLs:
        http://localhost:54321/tree?token=ba7bc90e2faceef8725bd66a54235d616f840595184a5fee
        http://127.0.0.1:54321/tree?token=ba7bc90e2faceef8725bd66a54235d616f840595184a5fee
[I 2023-09-05 19:00:53.675 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
```
Then, when I attempt to connect, I see the following at the console:
```
[I 2023-09-05 19:02:29.442 JupyterNotebookApp] 302 GET /tree/hub/api (@127.0.0.1) 1.93ms
[I 2023-09-05 19:02:29.459 JupyterNotebookApp] 302 GET /tree/tree? (@127.0.0.1) 0.91ms
[E 2023-09-05 19:02:29.531 ServerApp] Could not open static file ''
[W 2023-09-05 19:02:29.538 JupyterNotebookApp] 404 GET /tree/api/kernelspecs?1693954949462 (ab41f6945c2c4ecf8ded4dc84b1276dd@127.0.0.1) 54.69ms referer=None
[W 2023-09-05 19:02:29.545 JupyterNotebookApp] 404 GET /tree/api/kernelspecs?1693954949534 (07eb39084dc643f786f49cf89ab7decf@127.0.0.1) 4.98ms referer=None
[W 2023-09-05 19:02:29.549 JupyterNotebookApp] 404 GET /tree/api/kernels?1693954949467 (a214730e82af408ea2b0db1b7de0724b@127.0.0.1) 8.76ms referer=None
[W 2023-09-05 19:02:29.554 JupyterNotebookApp] 404 GET /tree/api/kernels?1693954949472 (96fce14de59b421da53c97aa7ba22d90@127.0.0.1) 13.40ms referer=None
[W 2023-09-05 19:02:29.558 JupyterNotebookApp] 404 GET /tree/api/sessions?1693954949478 (de8feeee76b74fe7b6aed893822e6f3f@127.0.0.1) 16.99ms referer=None
```

**Comment by DonJayamanne** [comment] 2023-09-06 10:49
Thanks for filling this issue and sorry you are running into this

* is Jupyter running in your local machine or the remote machine
* please  can you share the logs from the Jupyter extension?
* 

Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by ayushnoori** [comment] 2023-09-06 10:50
Thanks, @DonJayamanne. Everything is running on the remote machine. I will share the logs from the extension.

**Comment by DonJayamanne** [comment] 2023-09-06 11:39
Oh sorry, this has been resolved in the latest version of the Jupyter extension
The latest version of the extension will be released sometime this week along with the latest version of vscode

**Comment by ayushnoori** [comment] 2023-09-06 12:14
Great. Will update and test, then close the issue once I can resolve on my end.

**Comment by DonJayamanne** [comment] 2023-09-07 00:52
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/14191

**Closed by DonJayamanne** 2023-09-07 00:52 UTC
Labels: bug, info-needed, remote-connection-failure
