### ISSUE TITLE
Data viewer takes ages

### ISSUE THREAD

**Issue by AI-The-Foo-Cans** [microsoft/vscode-jupyter#7501] opened 2021-09-10 07:22 UTC
Issue Type: <b>Performance Issue</b>

I use python. The data viewer takes unacceptable long time to show the data.
Can this be fixed asap? This problem is a big dissatisfier.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (10.74GB free)|
|Process Argv|S:\\Python Scripts --crash-reporter-id 21fe488d-ef65-45c6-81ad-059d7e96ec05|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DavidKutu** [comment] 2021-09-13 22:47
Thanks for filing @AI-The-Foo-Cans.

To solve these types of performance issues, I'd really help to get a `.cpuprofile` file from you. To get it, please follow the instructions [here](https://github.com/Microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions). With that we can check why is it so slow.

**Comment by greazer** [comment] 2021-09-14 06:30
@AI-The-Foo-Cans, in addition the profile @DavidKutu mentioned, can you quantify what you mean by "unacceptable long time?" Seconds, minutes? How large is the dataframe you're trying to view? Number of rows & columns and what type of data in general would be interesting to know.

**Comment by AI-The-Foo-Cans** [comment] 2021-09-14 15:22
@DavidKutu, even a small dataframe of 600 rows and 5 columns took more than 20 min for loading. This week's update seems to have resolved my problems.

**Comment by joyceerhl** [comment] 2021-09-14 15:27
This is likely a duplicate of https://github.com/microsoft/vscode-jupyter/issues/7420 which was fixed via https://github.com/microsoft/vscode-jupyter/pull/7451.

**Closed** 2021-09-16 06:25 UTC
Labels: info-needed, data-viewer, perf, needs-triage
