### ISSUE TITLE
Run `%run xxx.ipynb` error, miss `nbformat` package

### ISSUE THREAD

**Issue by li1234yun** [microsoft/vscode-jupyter#9069] opened 2022-02-18 07:33 UTC
## Environment data

-   VS Code version: 1.64.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.3
-   Python Extension version (available under the Extensions sidebar): v2022.0.1814523869
-   OS (Windows | Mac | Linux distro) and version: Debian 11
-   Python and/or Anaconda version: 3.10.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

Run `%run xxx.ipynb` normally.

## Actual behaviour

Raise Exceptions: Miss `nbformat` package

## Resolve

When vscode inits jupyter server environment, `nbformat` package should be added to the dependence packages list, such as: `requirements.txt`.

**Comment by li1234yun** [comment] 2022-02-19 12:53
You are welcome :-) @amunger

**Comment by greazer** [comment] 2022-02-24 21:12
Suggestions for installing modules that are not found, is a dupe of #1566. Closing this one as it would be addressed by that one more than likely.

**Closed by greazer** 2022-02-24 21:12 UTC
Labels: enhancement
