### ISSUE TITLE
Can't write on execute cell

### ISSUE THREAD

**Issue by mauriciogtec** [microsoft/vscode-jupyter#3952] opened 2020-11-17 23:58 UTC
Issue Type: <b>Bug</b>

When switching from source file to interactive session if I click directly on the "shift-enter to run cell" I can't write unless I first click somewhere else on the interactive notebook and then on the cell.

Extension version: 2020.11.358541065
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.34GB free)|
|Process Argv|--crash-reporter-id 21a3b492-a506-4384-a1b3-e8344aa4ce0d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment] 2020-11-18 00:42
Dupe of #446

**Closed by rchiodo** 2020-11-18 00:42 UTC
