### ISSUE TITLE
Cannot plot after setting `%matplotlib widget`: "Internet connection required"

### ISSUE THREAD

**Issue by NateyB** [microsoft/vscode-jupyter#4888] opened 2021-02-20 07:15 UTC
## Environment data

-   VS Code version: Version: `1.53.2` | Commit: `622cb03f7e070a9670c94bae1a45d78d7181fbd4`
-   Jupyter Extension version (available under the Extensions sidebar): `2021.2.576440691`
-   Python Extension version (available under the Extensions sidebar): `2021.2.582707922`
-   OS (**Mac**) and version: `11.1`
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Docker image `mcr.microsoft.com/vscode/devcontainers/python:0-3.7` (using VSCode remote containers, version `0.158.0`).
-   Python and/or Anaconda version: 
    - `python --version` --> `Python 3.7.9`
    - `conda --version` --> `bash: conda: command not found`
-   Jupyter server running: **Remote**

## Expected behaviour
Running this code:
```
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

data = np.arange(10)

%matplotlib widget

plt.plot(data)
```

should produce and display an interactive plot in the inline editor, as it does in the Jupyter web notebook:

<img width="701" alt="image" src="https://user-images.githubusercontent.com/9223829/108586271-437dda80-7388-11eb-8673-3d7903ec7fb1.png">

This is the remote notebook that is the source kernel for VSCode's Jupyter.

## Actual behaviour

The notebook outputs
```
[<matplotlib.lines.Line2D at 0x7f379fc62b20>]
Error loading jupyter-matplotlib:^0.8.3. Internet connection required for loading 3rd party widgets. Error loading jupyter-matplotlib:^0.8.3. Internet connection required for loading 3rd party widgets.
```
This is similar to #1648, but unlike in that issue, this library is available in both [JSDelivr](https://www.jsdelivr.com/package/npm/jupyter-matplotlib?version=0.8.3) and [unpkg](https://unpkg.com/jupyter-matplotlib@0.8.3/src/index.js). Furthermore, the container does have internet access: `curl`ing each of those endpoints from the VSCode terminal returns the appropriate page. Monitoring my network I can see requests to both of these sites.

Additional information is available in the output section below, in which this error looks similar to the error in #1087, but my issue is still present on the latest versions, and the error message I see is not `Script source for Widget jupyter-matplotlib@^0.7.4 not found`, suggesting a different cause.

It is most similar to # #4246, but appears unrelated to WSL—other than the fact that, in both cases, we are using a docker container to run VSCode. Additionally, it is simply using matplotlib.

## Steps to reproduce:

1. Clone the repo I set up: https://github.com/NateyB/vscode-sample
2. Run it as a remote container.
3. To connect the Jupyter notebook to the server (should be prompted when you open the sample notebook), you will have to manually obtain the token. You can run `docker container ls` to get the name of the jupyter container, and then `docker logs <container name>` to get the token to supply VSCode. You will have to reload the window in order to connect.
4. Once connected, run the sample notebook.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'pythonJoinMailingListVar3'
User belongs to experiment group 'jupyterTest'
Connecting to Jupyter server at http://jupyter:8888/
http://jupyter:8888/: Kernel started: e2ff7ac7-831c-491b-964a-ef403d5cb6c7
> /usr/local/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/local/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/local/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2021.2.576440691/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
http://jupyter:8888/: Kernel started: 3b443f64-95e5-48b9-94eb-df40a316b145
http://jupyter:8888/: Kernel started: aaf5e2ca-1ca4-433b-8cad-2ddb966ed404
http://jupyter:8888/: Kernel started: 9b864d79-cbe6-4f7d-a728-b1bcd92d3732
http://jupyter:8888/: Creating new notebook 
Error 2021-02-20 06:49:11: [Error: command 'python.analysis.restartLanguageServer' already exists
...
http://jupyter:8888/: Kernel started: e81340ad-7e0b-44d9-98ca-3092b2e30a12
...
Error 2021-02-20 06:49:27: Error downloading from CDN [Error: Parse Error: JS Exception
	at TLSSocket.socketOnData (_http_client.js:469:22)
	at TLSSocket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at TLSSocket.Readable.push (_stream_readable.js:212:10)
	at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)] {
  bytesParsed: 2176073,
  code: 'HPE_JS_EXCEPTION',
  reason: 'JS Exception',
  rawPacket: <Buffer 74 6f 72 28 74 29 7d 2c 6c 3d 66 75 6e 63 74 69 6f 6e 28 74 29 7b 76 61 72 20 65 3d 7b 7d 3b 72 65 74 75 72 6e 20 66 75 6e 63 74 69 6f 6e 28 74 2c 69 ... 1319 more bytes>
}
```

</p>
</details>

**Comment by DavidKutu** [comment] 2021-02-23 23:15
Thanks for reporting the issue @NateyB. I'm able to get the expected graph both using a local and a remote server (without docker). So it seems like out http client is failing when using docker. I'll bring it up on our next meeting.

**Comment by greazer** [comment] 2021-02-25 21:13
Dupe of #4246

**Closed by greazer** 2021-02-25 21:13 UTC
Labels: WSL, bug
