### ISSUE TITLE
Magic commands not parsed anymore in interactive .py files.

### ISSUE THREAD

**Issue by rsebbe** [microsoft/vscode-jupyter#7557] opened 2021-09-16 07:58 UTC
## Environment data

-   VS Code version: 1.60.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1230869389
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.6.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

When executing cells from interactive .py python files (as opposed to .ipynb notebooks), magic commands are not parsed anymore. This used to be the case earlier this year, and pretty useful.

These lines are ignored (no effect)
```
#!%load_ext autoreload
#!%matplotlib osx
#!%config InlineBackend.figure_format='retina'
#!%autoreload 2
```

I need to use this instead (which is less practical, and makes it harder to move code between .ipynb / .py files)
```
from IPython import get_ipython
from numpy.core.fromnumeric import size
get_ipython().run_line_magic('load_ext', 'autoreload')
get_ipython().run_line_magic('matplotlib', 'osx')
get_ipython().run_line_magic('autoreload', '2')
```

my settings.json does include this:
```
"jupyter.magicCommandsAsComments": true,
``` 

## Actual behaviour

Nothing is executed

## Steps to reproduce:

No particular steps, code is just ignored. It used to work previously (2020, early 2021).

**Comment by joyceerhl** [comment] 2021-09-16 16:54
Apologies for the trouble. This is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/7481. This should already be fixed in Insiders and will be released to Stable at the start of October.

**Closed by joyceerhl** 2021-09-16 16:54 UTC
Labels: bug, needs-triage

**Comment by rsebbe** [comment] 2021-09-17 08:17
> Apologies for the trouble. This is a duplicate of #7481. This should already be fixed in Insiders and will be released to Stable at the start of October.

Thank you for the quick follow-up, much appreciated.
