### ISSUE TITLE
Consider consolidating all the "run" options for interactive window

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#12528] opened 2023-01-11 00:13 UTC
Currently, the "Run [...] in Interactive Window" in the context menu are (orange box) expanded and clutters context menu. We should consider consolidating all the options like "peek" (green box)

![image](https://user-images.githubusercontent.com/10833267/211688326-6b45789b-cffb-4067-80cf-11553cb366a7.png)

cc/ @amunger

**Comment by amunger** [comment] 2023-01-11 00:23
duplicate of https://github.com/microsoft/vscode-jupyter/issues/12392

**Closed by amunger** 2023-01-11 00:23 UTC
Labels: feature-request
