### ISSUE TITLE
Run selection or line fails from a text editor

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#5287] opened 2021-03-25 01:17 UTC
Root cause looks to be extra param that is actually a URL instead of text.

**Comment by andycraig** [comment] 2021-03-25 13:15
This sounds like it might be related to my PR #5053. I'm very sorry if that's the case.

I've tried to do a bit of investigating. I find that I can still run the version from my PR: https://github.com/andycraig/vscode-jupyter/tree/execSelectionInteractive-string

But when I try to run the commit created when it was merged into this repo a7d2d3cbf, I get the error 'Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information' in the Extension Development Host. (I've included the details from the Debug Console below.) I guess something I added is conflicting with other changes in `main` between when I created my PR and when I finished it.

I'm happy to keep investigating this although I understand you're probably in a hurry to fix this regression. If the cause is indeed my PR and you need to revert it that's of course okay. I can submit a new version from the latest `main`.

<p>
<details>
<summary>Output from Debug Console</summary>

<pre><code>
Error Jupyter Extension: 2021-03-25 21:36:02: Failure during activation. [TypeError: vscode_1.notebook.onDidChangeCellExecutionState is not a function
	at NotebookUsageTracker.activate (/home/ac/projects/python/vscode-jupyter/out/client/datascience/interactive-common/notebookUsageTracker.js:38:27)
	at /home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:74
	at Array.map (<anonymous>)
	at ExtensionActivationManager.activate (/home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:55)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error Jupyter Extension: 2021-03-25 21:36:02: sendStartupTelemetry() failed. [TypeError: vscode_1.notebook.onDidChangeCellExecutionState is not a function
	at NotebookUsageTracker.activate (/home/ac/projects/python/vscode-jupyter/out/client/datascience/interactive-common/notebookUsageTracker.js:38:27)
	at /home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:74
	at Array.map (<anonymous>)
	at ExtensionActivationManager.activate (/home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:55)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error Jupyter Extension: 2021-03-25 21:36:02: extension activation failed [TypeError: vscode_1.notebook.onDidChangeCellExecutionState is not a function
	at NotebookUsageTracker.activate (/home/ac/projects/python/vscode-jupyter/out/client/datascience/interactive-common/notebookUsageTracker.js:38:27)
	at /home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:74
	at Array.map (<anonymous>)
	at ExtensionActivationManager.activate (/home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:55)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
Error Jupyter Extension: 2021-03-25 21:36:02: Failed to active the Jupyter Extension [TypeError: vscode_1.notebook.onDidChangeCellExecutionState is not a function
	at NotebookUsageTracker.activate (/home/ac/projects/python/vscode-jupyter/out/client/datascience/interactive-common/notebookUsageTracker.js:38:27)
	at /home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:74
	at Array.map (<anonymous>)
	at ExtensionActivationManager.activate (/home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:55)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)]
(node:6417) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
rejected promise not handled within 1 second: TypeError: vscode_1.notebook.onDidChangeCellExecutionState is not a function
stack trace: TypeError: vscode_1.notebook.onDidChangeCellExecutionState is not a function
	at NotebookUsageTracker.activate (/home/ac/projects/python/vscode-jupyter/out/client/datascience/interactive-common/notebookUsageTracker.js:38:27)
	at /home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:74
	at Array.map (<anonymous>)
	at ExtensionActivationManager.activate (/home/ac/projects/python/vscode-jupyter/out/client/activation/activationManager.js:53:55)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
</code></pre>

</details>
</p>

**Comment by rchiodo** [comment] 2021-03-25 15:54
Thanks @andycraig. I think it should be easy to fix. We just need to check if the 'text' param is a URI or text. 

You can't use main at the moment because you need to update your insiders build. Insiders is changing daily and our main bits are in sync with those changes.

**Closed** 2021-03-25 20:39 UTC
Labels: bug, regression

**Comment by andycraig** [comment] 2021-03-26 11:32
@rchiodo That's a relief! I completely missed that use case. Glad to see that the fix wasn't too complicated. Thank you very much for taking care of it.

Thanks also for the note about Insiders needing to be updated.
