### ISSUE TITLE
Saving notebook does not auto-select file type

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode-jupyter#9789] opened 2022-04-26 17:55 UTC
Testing #9768

![image](https://user-images.githubusercontent.com/6561887/165362251-71a6b850-7892-46f8-b99e-023d344b81c3.png)

**Comment by rchiodo** [comment] 2022-04-26 17:58
Thanks. Should be a dupe of https://github.com/microsoft/vscode/issues/147657

**Closed by rchiodo** 2022-04-26 17:58 UTC
Labels: needs-triage
