### ISSUE TITLE
jupyternotebook no longer working after recent update

### ISSUE THREAD

**Issue by zakaryael** [microsoft/vscode-jupyter#12800] opened 2023-02-09 13:20 UTC
Type: <b>Bug</b>

jupyternotebook extention no longer working after recent update

VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:26:31.005Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id a18a046f-0e2d-4d23-8e56-4f7462aadb5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-gmsh|Ber|0.1.2
markdown50|CS5|1.0.0
markdown-table-prettify|dar|3.6.0
codespaces|Git|1.13.7
copilot|Git|1.71.8269
vscode-pull-request-github|Git|0.58.0
latex-workshop|Jam|9.6.2
latex-snippets-jeff|Jef|1.2.3
cmake-language-support-vscode|jos|0.0.9
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2023.2.0
vscode-pylance|ms-|2023.2.10
jupyter|ms-|2023.1.2010391206
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.14
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.14.1
makefile-tools|ms-|0.6.0
remote-explorer|ms-|0.2.0
vsliveshare|ms-|1.0.5828
vsliveshare-audio|ms-|0.1.93
csv-to-table|php|1.4.0
vscode-yaml|red|1.11.0
learn-vim|vin|0.0.28

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30660299
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
f6dab269:30613381
pythonsymbol12cf:30657549

```

</details>

**Comment by DonJayamanne** [comment] 2023-02-09 20:35
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12798

**Closed by DonJayamanne** 2023-02-09 20:35 UTC
