### ISSUE TITLE
On Jupyter Notbooks add a keyboard shortcut to run current line/selection only 

### ISSUE THREAD

**Issue by gal064** [microsoft/vscode-jupyter#10974] opened 2022-07-28 22:06 UTC
On Jupyter notebook add a keybind that allows you to only run current line. Google Colab has this feature and it's very useful:

https://user-images.githubusercontent.com/50427415/181645586-9583269b-0b05-4002-946a-740ad6b1fd22.mov

**Comment by amunger** [comment] 2022-08-01 21:45
could be included in the scratch pad story

**Comment by amunger** [comment] 2022-08-01 21:45
#4573

**Comment by amunger** [comment] 2022-12-05 17:49
duplicate of https://github.com/microsoft/vscode-jupyter/issues/1471

**Closed by amunger** 2022-12-05 17:49 UTC
Labels: notebook-execution
