### ISSUE TITLE
Issue in R kernel, when more than one line exist in a cell

### ISSUE THREAD

**Issue by mgorjis** [microsoft/vscode-jupyter#7472] opened 2021-09-09 01:31 UTC
## Environment data

-   VS Code version: 1.60
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1191016588
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.7.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): NA
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

a <- 2 + 3
b <- 4 + 5

## Actual behaviour

provides this error when using R kernel
ERROR: Error in parse(text = x, srcfile = src): <text>:1:11: unexpected input
1: a <- 2 + 3
              ^
Error in parse(text = x, srcfile = src): <text>:1:11: unexpected input
1: a <- 2 + 3
              ^
Traceback:

![Capture](https://user-images.githubusercontent.com/11069763/132607243-16c8afab-acd0-4cc2-aa08-db8644d18e27.PNG)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by andycraig** [comment] 2021-09-13 22:10
@mgorjis The position of the ^ in the error message, and the highlighting in the screenshot, makes me think that there might be a non-ASCII whitespace character after '3' and '5'. Could you make sure there are no characters after '3' and '5' and try again?

**Comment by DonJayamanne** [comment] 2021-09-13 23:46
I'm on a mac, is this because we might be sending CRLF to the R kernel?
@andycraig based on your knowledge does the R kernel support CRLF in the code sent?

**Comment by mgorjis** [comment] 2021-09-15 14:21
@andycraig Definitely I have not added any non-ASCII characters to the line. When I save the notebook in VS code, and open it again in jupyter lab, it works completely fine.
If I have a line of code in each cell in VS code, it is working fine. Only if I have two lines in A CELL, I see this weird error.

Thanks

**Comment by andycraig** [comment] 2021-09-16 13:46
@mgorjis Thanks for confirming and checking it works in Jupyter Lab.

@DonJayamanne I haven't had a chance to look into this properly yet but Hydrogen had a similar issue with the R kernel and CRLF so you're almost certainly right I'd say. https://github.com/nteract/hydrogen/issues/312

**Comment by DonJayamanne** [comment] 2021-09-16 17:06
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/4576

**Closed by DonJayamanne** 2021-09-16 17:06 UTC
Labels: bug, kernel-issues, language-R, needs-triage

**Comment by DonJayamanne** [comment] 2021-09-24 20:39
Fixed, it should be in Mondays insiders and next releease
