### ISSUE TITLE
Go To Cell button stopped working

### ISSUE THREAD

**Issue by leehagaman** [microsoft/vscode-jupyter#15274] opened 2024-02-29 20:35 UTC
Type: <b>Bug</b>

Run some cells, click the "Go To" button, and the screen no longer moves to the running cell. Same for clicking "Go To" after a cell has errored, it doesn't jump to the right place. This just started happening today when my VS Code updated.

Extension version: 2024.2.0
VS Code version: Code 1.87.0 (Universal) (019f4d1419fbc8219a181fab7892ebccf7ee29a2, 2024-02-27T23:42:56.944Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id f335be39-0e02-4260-95a2-ad1bc8af23d5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30968133
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
d34g3935:30971562
edj9j583:30969295
fegfb526:30973843
e3gdj431:30958358
dsvsc020cf:30973509
jchc7451:30973076

```

</details>

**Comment by eromoe** [comment] 2024-03-01 05:39
Same, 
I need hover on the `refreshing icon` and  click the red box to go to cell. 
![image](https://github.com/microsoft/vscode-jupyter/assets/3938751/21196c8d-6cf4-436b-b6ec-0602cfd8292d)

**Comment by Kiwinokoto** [comment] 2024-03-01 08:41
Hello, i have the same problem with the "go to" running cell/latest error button. Haven't found a fix yet. Anyone ?

**Comment by mladen5000** [comment] 2024-03-01 16:59
Likewise

**Comment by tom-hehir** [comment] 2024-03-04 16:18
Me too

**Comment by Weiyu-Luo** [comment] 2024-03-04 18:56
Same here on Ubuntu.

**Comment by aqlkzf** [comment] 2024-03-08 11:25
I met the same problem. Any solutions?

**Comment by Trader-McStockster** [comment] 2024-03-15 16:23
same problem. Let me know if anybody finds a solution!

**Comment by Kiwinokoto** [comment] 2024-03-20 12:29
Hi, since February 2024 (version 1.87) update, it's not just the goto button that doesn't work anymore on ubuntu (i work on linux mint). The syntaxic coloration is acting up as well. it's sometimes incomplete, or appears and then disappears, especially for packages imports. Not sure if i should downgrade or wait for a patch ?

**Comment by gdebrun2** [comment] 2024-03-20 20:06
Same issue. 

## Version info:

<details>
  - macOS 14.4
  - M1 Max CPU/GPU with 64 GB ram
  - VsCode info:
    - Version: 1.87.2
    - Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
    - Date: 2024-03-08T15:20:57.520Z
    - Electron: 27.3.2
    - ElectronBuildId: 26836302
    - Chromium: 118.0.5993.159
    - Node.js: 18.17.1
    - V8: 11.8.172.18-electron.0
    - OS: Darwin arm64 23.4.0
  
  - Python extension version v2024.2.1
  - Jupyter extension version v2024.2.0
  - Jupyter renderer version v1.0.17
  - Python 3.12

</details>

**Comment by tom-hehir** [comment] 2024-03-23 18:50
Update: I was having this issue (as noted in my previous comment), but have found a workaround.

- Previously, users could click anywhere in the area of "Go To" button and this would take you to the currently running cell. This is intuitive, and preferably the plugin will be fixed to allow this.
- But I have realised that if you click on the circular arrow symbol part of the "Go To" button it works as expected.

Image: (clicking in red area does not work, but clicking in blue area does)

<img width="62" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/148493038/2cf0f8b2-08c4-448b-806c-c50bb4a40c0c">

**Comment by Yoyokrazy** [comment] 2024-03-26 21:31
Closing as duplicate of https://github.com/microsoft/vscode/issues/206618

/duplicate

**Closed** 2024-03-26 21:33 UTC
