### ISSUE TITLE
Interactive Window - Can't access code history after selecting different tab

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#8718] opened 2022-01-17 23:03 UTC
## Environment data

-   VS Code version: 1.64.0-insider
-   Jupyter Extension version: v2022.1.1001614873
-   Python Extension version: v2022.0.1696779064-dev
-   OS: Darwin arm64 21.2.0
-   Python version: 3.9.7
-   Type of virtual environment used: pipenv
-   Jupyter server running: Local

## Expected behaviour

- When moving away from the IW, then back again, the code entry field is active and up arrow activates cell history.

## Actual behaviour

- When moving back to IW, code entry cell cursor is blinking, but the up arrow does not show cell history.
- User must first press another key (eg tab), then up arrow works again

## Steps to reproduce:

1. Run code in IW
2. Navigate to different editor tab and back again
3. Press up arrow - cell history will not show

In this video, you can see I move away, back again, (in the slight pause I'm pressing the up arrow) before finally pressing tab to make it active again:

https://user-images.githubusercontent.com/29611875/149845801-f0050378-51ce-4ed1-837a-6c0ea8b6dc90.mp4

Admittedly this is a bit of a papercut, but is still pretty annoying multiple times per day.

**Comment by rchiodo** [comment] 2022-01-18 17:19
Thanks for the issue. This should be a dupe of this item: https://github.com/microsoft/vscode/issues/138557

**Closed by rchiodo** 2022-01-18 17:19 UTC
Labels: bug, needs-triage

**Comment by jaymegordo** [comment] 2022-01-18 18:00
> Thanks for the issue. This should be a dupe of this item: [microsoft/vscode#138557](https://github.com/microsoft/vscode/issues/138557)

@rchiodo That issue was closed dec 14, and I'm definitely on the latest daily builds of vscode/python/jupyter but am definitely still experiencing this behaviour. Are you sure that's the exact same thing?

**Comment by rchiodo** [comment] 2022-01-18 18:02
The issue did mention history but it looks like only the scroll position was fixed. I reopened the other issue.
