### ISSUE TITLE
Error: active.DebugSession.configuration.python is not a string

### ISSUE THREAD

**Issue by yc1999** [microsoft/vscode-jupyter#10505] opened 2022-06-20 02:48 UTC
error 10:46:51.633: Error: active.DebugSession.configuration.python is not a string: ["/root/software/miniconda3/envs/gwlan/bin/python"]

**Comment by yc1999** [comment] 2022-06-20 02:53
as mentioned here: https://github.com/microsoft/vscode-jupyter/issues/10012#issuecomment-1157268664

**Comment by yc1999** [comment] 2022-06-20 02:54
more detaiils:
```shell
error 10:47:39.392: Error: active.DebugSession.configuration.python is not a string: ["/root/software/miniconda3/envs/gwlan/bin/python"]
    at I.onVariablePanelShowDataViewerRequest (/root/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:53329)
    at I.<anonymous> (/root/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:805636)
    at o._executeContributedCommand (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:62521)
    at o.$executeContributedCommand (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:63225)
    at s._doInvokeHandler (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:13828)
    at s._invokeHandler (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:13512)
    at s._receiveRequest (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:12173)
    at s._receiveOneMessage (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:10843)
    at /root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:8949
    at g.invoke (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.deliver (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
    at v.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
    at a.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)
    at /root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:102:34863
    at g.invoke (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.deliver (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
    at v.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
    at a.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)
    at r._receiveMessage (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:23606)
    at /root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:21140
    at g.invoke (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.deliver (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
    at v.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
    at v.acceptChunk (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:15856)
    at /root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:14986
    at g.invoke (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.deliver (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
    at v.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
    at f._processReadQueue (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:102:21280)
warn 10:47:39.392: DataScience Error Error: active.DebugSession.configuration.python is not a string: ["/root/software/miniconda3/envs/gwlan/bin/python"]
    at I.onVariablePanelShowDataViewerRequest (/root/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:53329)
    at I.<anonymous> (/root/.vscode-server/extensions/ms-toolsai.jupyter-2022.5.1001601848/out/extension.node.js:2:805636)
    at o._executeContributedCommand (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:62521)
    at o.$executeContributedCommand (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:83:63225)
    at s._doInvokeHandler (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:13828)
    at s._invokeHandler (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:13512)
    at s._receiveRequest (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:12173)
    at s._receiveOneMessage (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:10843)
    at /root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:86:8949
    at g.invoke (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.deliver (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
    at v.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
    at a.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)
    at /root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:102:34863
    at g.invoke (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.deliver (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
    at v.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
    at a.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:19025)
    at r._receiveMessage (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:23606)
    at /root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:21140
    at g.invoke (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.deliver (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
    at v.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
    at v.acceptChunk (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:15856)
    at /root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:66:14986
    at g.invoke (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.deliver (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
    at v.fire (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
    at f._processReadQueue (/root/.vscode-server/bin/30d9c6cd9483b2cc586687151bcbcd635f373630/out/vs/workbench/api/node/extensionHostProcess.js:102:21280)
```

**Comment by DonJayamanne** [comment] 2022-06-20 04:20
Thanks for filing this issue. We'll discuss this issue in standup.
@IanMatthewHuff I believe you have more background on this, i recall you mentioning the fact that we probably made an incorrect assumption about this being a string or not.

**Comment by IanMatthewHuff** [comment] 2022-06-20 16:15
@DonJayamanne Yeah, this shows the new logging that I added. Looks like it can be an array now. I can submit a fix.

**Comment by IanMatthewHuff** [comment] 2022-06-20 16:36
Dupe of #10007 I should be submitting a fix for this today.

**Closed by IanMatthewHuff** 2022-06-20 16:36 UTC
Labels: bug, notebook-regression, triage-needed
