### ISSUE TITLE
VSCode Jupyter Notebook always depends on `os` package

### ISSUE THREAD

**Issue by JiahangXu** [microsoft/vscode-jupyter#8577] opened 2021-12-20 06:45 UTC
## Actual behaviour

In my opinion, a empty notebook with a clean kernel environment should only call `os` methods such as `os.makedirs` after `import os`. However, VSCode notebook can always call `os` methods even if the package `os` is not imported. I wonder if there is some inner operation with dependency introduced. This issue is tiny but may cause  out-of-sync between VSCode Jupyter and regular jupyter notebook.

## Environment data

-   VS Code version: 1.63.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 16.04.6
-   Python and/or Anaconda version: 3.6.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

**Comment by DonJayamanne** [comment] 2021-12-20 06:54
Thanks for filling this issue. Not what's this based on. Area you getting errors about is not being available?

Ie what is exactly the problem (what's wrong)? 
Also how have you concluded that os is not available?

> This issue is tiny but may cause out-of-sync between VSCode Jupyter and regular jupyter notebook.

Part could you elaborate, with an example.

**Comment by JiahangXu** [comment] 2021-12-20 07:04
Thanks for your quick response. Here is a example: 
I open a new jupyter notebook on VSCode and type `print(os)`, and the code cell returns a module path back to me:
`<module 'os' from '/home/.../envs/py36-env/lib/python3.6/os.py'>`

However, I open the same notebook by running `jupyter-notebook` in command line and re-run the code cell, there is an error saying:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-9ad549aa6500> in <module>
----> 1 print(os)

NameError: name 'os' is not defined
```

**Comment by JiahangXu** [comment] 2021-12-20 09:50
I think an empty python script should not have dependence to `os` package. Anyway it's a just a very tiny bug. I just raise the problem to your team to see if it is easy to fix. It's totally okay if you will do nothing.

**Comment by sinekhayantuli** [comment] 2021-12-20 10:27
Its dependency  is on the cashier maintenance  or by filling such a report,
it might be related to bank withdrawals outcomes.

**Comment by DonJayamanne** [comment] 2021-12-20 16:31
> It's totally okay if you will do nothing.

Currently we setup some startup scripts to initialize the workspace folder, and the like, hence some of these packages get imported.
Closing this as it's by design.
I'd this does however cause unexpected issues, please do come a bug and we'll look into this

**Closed by DonJayamanne** 2021-12-20 16:31 UTC
Labels: bug, needs-triage
