### ISSUE TITLE
Captum Insights fails to render inside of Jupyter VsCode 

### ISSUE THREAD

**Issue by poucet** [microsoft/vscode-jupyter#15047] opened 2024-01-21 11:36 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I am running [this pytorch ipynb](https://pytorch.org/tutorials/beginner/introyt/captumyt.html) notebook locally. (Note that to run it you have to download 3 image files).

I am running jupyter and python inside of a conda environment where I've installed all necessary modules (conda, captum ...)

### VS Code Version

Version: 1.85.2 (user setup) Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681 Date: 2024-01-18T06:40:10.514Z Electron: 25.9.7 ElectronBuildId: 26354273 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.22621

### Jupyter Extension Version

v2023.11.1100101639

### Jupyter logs

```shell
jupyter troubleshoot
$PATH:
        C:\Users\chris\bin
        C:\Program Files\Git\mingw64\bin
        C:\Program Files\Git\usr\local\bin
        C:\Program Files\Git\usr\bin
        C:\Program Files\Git\usr\bin
        C:\Program Files\Git\mingw64\bin
        C:\Program Files\Git\usr\bin
        C:\Users\chris\bin
        C:\Users\chris\projects\pytorch\.conda
        C:\Users\chris\projects\pytorch\.conda\Library\mingw-w64\bin
        C:\Users\chris\projects\pytorch\.conda\Library\usr\bin
        C:\Users\chris\projects\pytorch\.conda\Library\bin
        C:\Users\chris\projects\pytorch\.conda\Scripts
        C:\Users\chris\projects\pytorch\.conda\bin
        C:\Users\chris\miniconda3\condabin
        C:\Program Files\Common Files\Oracle\Java\javapath
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0
        C:\Windows\System32\OpenSSH
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
        C:\Program Files\dotnet
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0
        C:\WINDOWS\System32\OpenSSH
        C:\Program Files\nodejs
        C:\Program Files\Git\cmd
        C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
        C:\Users\chris\.cargo\bin
        C:\Users\chris\AppData\Local\Microsoft\WindowsApps
        .
        C:\Users\chris\AppData\Local\Programs\Microsoft VS Code\bin
        C:\Users\chris\.dotnet\tools
        C:\Users\chris\AppData\Roaming\npm
        C:\Program Files\Common Files\Oracle\Java\javapath
        C:\Windows\system32
        C:\Windows
        C:\Windows\System32\Wbem
        C:\Windows\System32\WindowsPowerShell\v1.0
        C:\Windows\System32\OpenSSH
        C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
        C:\Program Files\dotnet
        C:\WINDOWS\system32
        C:\WINDOWS
        C:\WINDOWS\System32\Wbem
        C:\WINDOWS\System32\WindowsPowerShell\v1.0
        C:\WINDOWS\System32\OpenSSH
        C:\Program Files\nodejs
        C:\Program Files\Git\cmd
        C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
        C:\Users\chris\.cargo\bin
        C:\Users\chris\AppData\Local\Microsoft\WindowsApps
        C:\Users\chris\AppData\Local\Programs\Microsoft VS Code\bin
        C:\Users\chris\.dotnet\tools
        C:\Users\chris\AppData\Roaming\npm
        C:\Program Files\Git\usr\bin\vendor_perl
        C:\Program Files\Git\usr\bin\core_perl

sys.path:
        C:\Users\chris\projects\pytorch\.conda\Scripts
        C:\Users\chris\projects\pytorch\.conda\python311.zip
        C:\Users\chris\projects\pytorch\.conda\DLLs
        C:\Users\chris\projects\pytorch\.conda\Lib
        C:\Users\chris\projects\pytorch\.conda
        C:\Users\chris\projects\pytorch\.conda\Lib\site-packages
        C:\Users\chris\projects\pytorch\.conda\Lib\site-packages\win32
        C:\Users\chris\projects\pytorch\.conda\Lib\site-packages\win32\lib
        C:\Users\chris\projects\pytorch\.conda\Lib\site-packages\Pythonwin

sys.executable:
        C:\Users\chris\projects\pytorch\.conda\python.exe

sys.version:
        3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]

platform.platform():
        Windows-10-10.0.22621-SP0

where jupyter:
        C:\Users\chris\projects\pytorch\.conda\Scripts\jupyter.exe

pip list:
        Package                 Version
        ----------------------- ----------
        absl-py                 1.4.0
        aiohttp                 3.9.0
        aiosignal               1.2.0
        asttokens               2.4.1
        attrs                   23.1.0
        blinker                 1.6.2
        Brotli                  1.0.9
        cachetools              4.2.2
        captum                  0.7.0
        certifi                 2023.11.17
        cffi                    1.16.0
        charset-normalizer      2.0.4
        click                   8.1.7
        cloudpickle             2.2.1
        colorama                0.4.6
        comm                    0.2.1
        contourpy               1.2.0
        cryptography            41.0.7
        cycler                  0.11.0
        debugpy                 1.8.0
        decorator               5.1.1
        exceptiongroup          1.2.0
        executing               2.0.1
        Farama-Notifications    0.0.4
        filelock                3.13.1
        Flask                   2.2.5
        Flask-Compress          1.13
        fonttools               4.25.0
        frozenlist              1.4.0
        fsspec                  2023.12.2
        gmpy2                   2.1.2
        google-auth             2.22.0
        google-auth-oauthlib    0.4.1
        grpcio                  1.48.2
        gymnasium               0.28.1
        idna                    3.4
        importlib-metadata      7.0.1
        ipykernel               6.29.0
        ipython                 8.20.0
        ipywidgets              8.0.4
        itsdangerous            2.0.1
        jax-jumpy               1.0.0
        jedi                    0.19.1
        Jinja2                  3.1.2
        jupyter_client          8.6.0
        jupyter_core            5.7.1
        jupyterlab-widgets      3.0.9
        kiwisolver              1.4.4
        Markdown                3.4.1
        MarkupSafe              2.1.3
        matplotlib              3.8.0
        matplotlib-inline       0.1.6
        mkl-fft                 1.3.8
        mkl-random              1.2.4
        mkl-service             2.4.0
        mpmath                  1.3.0
        multidict               6.0.4
        munkres                 1.1.4
        nest_asyncio            1.5.9
        networkx                3.1
        numpy                   1.26.3
        oauthlib                3.2.2
        packaging               23.1
        parso                   0.8.3
        pickleshare             0.7.5
        Pillow                  10.0.1
        pip                     23.3.1
        platformdirs            4.1.0
        ply                     3.11
        prompt-toolkit          3.0.42
        protobuf                3.20.3
        psutil                  5.9.8
        pure-eval               0.2.2
        pyasn1                  0.4.8
        pyasn1-modules          0.2.8
        pycparser               2.21
        Pygments                2.17.2
        PyJWT                   2.4.0
        pyOpenSSL               23.2.0
        pyparsing               3.0.9
        PyQt5                   5.15.10
        PyQt5-sip               12.13.0
        PySocks                 1.7.1
        python-dateutil         2.8.2
        pywin32                 306
        PyYAML                  6.0.1
        pyzmq                   25.1.2
        requests                2.31.0
        requests-oauthlib       1.3.0
        rsa                     4.7.2
        setuptools              68.2.2
        sip                     6.7.12
        six                     1.16.0
        stack-data              0.6.2
        sympy                   1.12
        tensorboard             2.6.0
        tensorboard-data-server 0.6.1
        tensorboard-plugin-wit  1.6.0
        torch                   2.1.2
        torchaudio              2.1.2
        torchvision             0.16.2
        tornado                 6.3.3
        tqdm                    4.66.1
        traitlets               5.14.1
        typing_extensions       4.9.0
        urllib3                 1.26.18
        wcwidth                 0.2.13
        Werkzeug                2.2.3
        wheel                   0.41.2
        widgetsnbextension      4.0.5
        win-inet-pton           1.1.0
        yarl                    1.9.3
        zipp                    3.17.0
```

### Coding Language and Runtime Version

Python 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)] on win32

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment] 2024-01-21 23:15
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15048

**Closed by DonJayamanne** 2024-01-21 23:15 UTC
Labels: bug
