### ISSUE TITLE
Native Notebooks - .NET Compatibility 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5480] opened 2021-04-11 02:59 UTC
## Environment data

-   VS Code version: 1.56.0 - insider
-   Jupyter Extension version: v2021.6.732501275
-   Python Extension: v2021.3.680753044
-   .NET Extension version: v1.0.2210011
-   OS (Windows | Mac | Linux distro) and version: Windows 
-   Python and/or Anaconda version: Anaconda 4.10, Python 3.7.10
-   Type of virtual environment used: Conda
-   Jupyter server running: Local

## Steps to reproduce:
1. Fresh install of .NET Interactive extension
2. Open command palette -> Create new blank Jupyter Notebook -> .NET Interactive option

## Expected behavior 

A blank notebook to open up and the kernel be set to .NET Interactive, and first cell language to be set to their default language C# (.NET Interactive) 

## Actual behavior

The kernel was set to the Python kernel I normally use and the language picker was set to Python. 

**After switching the kernel to the .NET interactive and confirming I could run something, I tried the create new blank jupyter notebook command again and selected .NET interactive. This time I got a Julia kernel. 

If you try to use the command palette option over and over without running anything, you will get Python over and over.
After running something and using the command palette option you get Julia.

**Comment by joyceerhl** [comment] 2021-04-30 20:34
This isn't working as intended. The kernel quickpick shows up after I pick .NET interactive, and the kernel status bar shows that no kernel has been selected.

![kernelpicker](https://user-images.githubusercontent.com/30305945/116751327-b4f58d00-a9b8-11eb-83dd-dde18a4452c9.gif)

**Comment by DonJayamanne** [comment] 2021-04-30 21:30
> e kernel quickpick shows up after I pick .NET interactive, and the kernel status bar shows that no kernel has been selected.



This is a bug in .NET, they are not using the right VS COde API, instead of setting their kernel as preferred, they're forcing vS Code to select their kernel as the current kernel (i.e. mimic a user action, and that's why you get a popup).
We can close this issue as I have confirmed with their engineers that this popup is because of their API call

**Comment by DonJayamanne** [comment] 2021-04-30 21:30
@claudiaregio /cc

**Closed by DonJayamanne** 2021-04-30 21:30 UTC
Labels: bug

**Comment by DonJayamanne** [comment] 2021-04-30 21:31
Here's the duplicate issue with the same behavior https://github.com/microsoft/vscode-jupyter/issues/5686

FYI - I have confirmed with .NET team that they are no longer blocked on us and now blocked on VS Code.
