### ISSUE TITLE
Jupyter theme doesn't work while using VSCode with remote container

### ISSUE THREAD

**Issue by dariocurr** [microsoft/vscode-jupyter#5908] opened 2021-05-17 10:24 UTC
I refer to the issue #1740.
Is there any news? The bug is kind of boring

**Comment by joyceerhl** [comment] 2021-05-17 18:10
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1407. The resolution for this will be our new native notebooks support, which you can currently preview in VS Code Insiders with full theming support, and which we are working to ship out as the default notebook UI ASAP.

**Closed by joyceerhl** 2021-05-17 18:10 UTC
Labels: bug
