### ISSUE TITLE
Source path mapping for remote servers

### ISSUE THREAD

**Issue by david-macleod** [microsoft/vscode-jupyter#16301] opened 2024-12-13 15:22 UTC
When connecting to a remote jupyter server there is often a mismatch between the paths in the local source files and the remote paths. This means that things like clicking through on line numbers on error messages does not work, and the debugger cannot find the relevant source files. 

Is it possible to configure this mapping somewhere so the paths resolve correctly?

**Comment by DonJayamanne** [comment] 2024-12-16 04:29
Sorry you are running into this issue, 
Possible a duplicate of https://github.com/microsoft/vscode-jupyter/issues/9636 or https://github.com/microsoft/vscode-jupyter/issues/13224

> Is it possible to configure this mapping somewhere so the paths resolve correctly?
If all else fails, then duplicate of https://github.com/microsoft/vscode-jupyter/issues/15869

**Closed by DonJayamanne** 2024-12-16 04:29 UTC
Labels: feature-request
