### ISSUE TITLE
Failed to load model class 'MPLCanvasModel' from module 'jupyter-matplotlib'

### ISSUE THREAD

**Issue by amcar-dtu** [microsoft/vscode-jupyter#16007] opened 2024-09-06 08:01 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Upgrading to the new version `v2024.8.0` started throwing the error
    ```
    [Open Browser Console for more detailed log - Double click to close this message]
    Failed to load model class 'MPLCanvasModel' from module 'jupyter-matplotlib'
    Error: No version of module jupyter-matplotlib is registered
        at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/amcar/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
        at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/amcar/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)
        at ph.loadModelClass (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/amcar/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)
        at ph._make_model (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/amcar/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
        at ph.new_model (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/amcar/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)
        at ph.handle_comm_open (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/amcar/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)
        at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/amcar/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.19/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511
        at n._handleCommOpen (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/amcar/.vscode/extensions/ms-toolsai.jupyter-2024.8.2024081201-win32-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:80955)
        at async n._handleMessage (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/amcar/.vscode/extensions/ms-toolsai.jupyter-2024.8.2024081201-win32-x64/dist/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:3:82830)
    ```

2. Rollback to version `v2024.7.0` fixed the error message and now everything works again

### VS Code Version

Version: 1.93.0 (user setup) Commit: 4849ca9bdf9666755eb463db297b69e5385090e3 Date: 2024-09-04T13:02:38.431Z Electron: 30.4.0 ElectronBuildId: 10073054 Chromium: 124.0.6367.243 Node.js: 20.15.1 V8: 12.4.254.20-electron.0 OS: Windows_NT x64 10.0.22631

### Jupyter Extension Version

v2024.8.0

### Coding Language and Runtime Version

Python 3.10.11

### Language Extension Version (if applicable)

Python Extension: v2024.14.0

### Running Jupyter locally or remotely?

Local

**Comment by amcar-dtu** [comment] 2024-09-06 09:02
```
Visual Studio Code (1.93.0, undefined, desktop)
Jupyter Extension Version: 2024.8.0.
Python Extension Version: 2024.14.0.
Pylance Extension Version: 2024.8.2.
Platform: win32 (x64).
Temp Storage folder ~\AppData\Roaming\Code\User\globalStorage\ms-toolsai.jupyter\version-2024.8.0
Workspace folder ~\Documents\python\him-on-gr-hbn, Home = c:\Users\amcar
10:58:42.776 [debug] Start refreshing Kernel Picker (1725613122776)
10:58:43.981 [trace] Search for KernelSpecs in Interpreter ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe
10:58:44.016 [trace] Search for KernelSpecs in Interpreter ~\AppData\Local\Programs\Python\Python310\python.exe
10:58:44.018 [trace] Search for KernelSpecs in Interpreter ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe
10:58:44.020 [trace] Search for KernelSpecs in Interpreter c:\Program Files\Inkscape\bin\python.exe
10:58:44.021 [trace] Search for KernelSpecs in Interpreter ~\.local\pipx\venvs\poetry\Scripts\python.exe
10:58:44.031 [debug] Get Custom Env Variables, Class name = Em, completed in 1256ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
10:58:44.031 [debug] Jupyter Paths kernels: 
10:58:44.034 [warn] Kernel Spec for 'venv' (c:\ProgramData\jupyter\kernels\venv\kernel.json) hidden, as we cannot find a matching interpreter argv = 'C:\Users\~\Documents\python\python-assignments\venv\Scripts\python.exe'. To resolve this, please change 'C:\Users\~\Documents\python\python-assignments\venv\Scripts\python.exe' to point to the fully qualified Python executable.
10:58:44.035 [debug] Kernel Spec Root Paths, ~\AppData\Roaming\jupyter\kernels, c:\ProgramData\jupyter\kernels
10:58:46.004 [debug] KernelProvider switched kernel to id = .jvsc74a57bd0530c4a137a047274ab3f434e8a010a3ceb054fdce29930fb1bbedd1e341274af.c:\Users\~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe.c:\Users\~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe.-m#ipykernel_launcher
10:58:46.005 [debug] start the kernel, options.disableUI=true for ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb
10:58:46.009 [debug] Controller selection change completed
10:58:48.454 [debug] Get Custom Env Variables, Class name = Em, completed in 1ms, has a truthy return value, Arg 1: "/c:/Users/~/Documents/python/him-on-gr-hbn", Arg 2: "RunPythonCode"
10:58:48.459 [info] Starting Kernel (Python Path: ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe, Poetry, 3.10.11) for '~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb' (disableUI=true)
10:58:48.460 [trace] Creating raw notebook for resource '~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb'
10:58:49.636 [debug] Get Custom Env Variables, Class name = Em, completed in 37ms, has a truthy return value, Arg 1: "/c:/Users/~/Documents/python/him-on-gr-hbn/odmr_hamiltonian.ipynb", Arg 2: "RunPythonCode"
10:58:51.264 [trace] Hiding default KernelSpec python for interpreter ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe (KernelSpec file ~\Documents\python\him-on-gr-hbn\.venv\share\jupyter\kernels\python3\kernel.json)
10:58:51.268 [trace] Hiding default KernelSpec python for interpreter ~\AppData\Local\Programs\Python\Python310\python.exe (KernelSpec file ~\AppData\Local\Programs\Python\Python310\share\jupyter\kernels\python3\kernel.json)
10:58:51.271 [debug] End refreshing Kernel Picker (1725613122776)
10:58:54.460 [debug] Launching kernel .jvsc74a57bd0530c4a137a047274ab3f434e8a010a3ceb054fdce29930fb1bbedd1e341274af.c:\Users\~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe.c:\Users\~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe.-m#ipykernel_launcher for ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb in ~\Documents\python\him-on-gr-hbn with ports 9001, 9000, 9004, 9002, 9003
10:58:54.560 [debug] Get Custom Env Variables, Class name = Em, completed in 5ms, has a truthy return value, Arg 1: "/c:/Users/~/Documents/python/him-on-gr-hbn/odmr_hamiltonian.ipynb", Arg 2: "RunPythonCode"
10:58:54.605 [warn] Failed to get activated env vars for ~\AppData\Local\Programs\Python\Python310\python.exe in 50ms
10:58:54.686 [debug] Create ProcessService, Class name = Cm (started execution), Arg 1: undefined
10:58:54.702 [debug] Get Custom Env Variables, Class name = Em, completed in 16ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunNonPythonCode", Arg 3: undefined
10:58:54.703 [debug] Create ProcessService, Class name = Cm, completed in 17ms, has a truthy return value, Arg 1: undefined
10:58:54.914 [info] Process Execution: ~\AppData\Local\Programs\Python\Python310\python.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
10:59:03.230 [debug] Got env vars from Python Ext in 13631ms for ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe, with env var count 70.
10:59:03.231 [trace] Prepend PATH with python bin for ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe
10:59:03.233 [debug] Getting activated env variables, Class name = vd, completed in 13633ms, has a truthy return value, Arg 1: "/c:/Users/~/Documents/python/him-on-gr-hbn/odmr_hamiltonian.ipynb", Arg 2: "~\\DOCUMENTS\\PYTHON\\HIM-ON-GR-HBN\\.VENV\\SCRIPTS\\PYTHON.EXE", Arg 3: undefined
10:59:03.429 [info] Process Execution: ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
10:59:03.435 [debug] Got env vars from Python Ext in 14982ms for ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe, with env var count 70.
10:59:03.435 [trace] Prepend PATH with python bin for ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe
10:59:03.438 [debug] Getting activated env variables, Class name = vd, completed in 14985ms, has a truthy return value, Arg 1: "/c:/Users/~/Documents/python/him-on-gr-hbn", Arg 2: "~\\DOCUMENTS\\PYTHON\\HIM-ON-GR-HBN\\.VENV\\SCRIPTS\\PYTHON.EXE", Arg 3: undefined
10:59:03.538 [info] Process Execution: ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe -m pip list
10:59:03.543 [trace] USER_SITE for ~\AppData\Local\Programs\Python\Python310\python.exe is c:\Users\~\AppData\Roaming\Python\Python310\Scripts
10:59:03.545 [trace] Prepend PATH with user site path for ~\AppData\Local\Programs\Python\Python310\python.exe, user site c:\Users\~\AppData\Roaming\Python\Python310\Scripts
10:59:03.547 [trace] Prepend PATH with python bin for ~\AppData\Local\Programs\Python\Python310\python.exe
10:59:03.548 [debug] Getting activated env variables, Class name = vd, completed in 8993ms, has a truthy return value, Arg 1: "/c:/Users/~/Documents/python/him-on-gr-hbn/odmr_hamiltonian.ipynb", Arg 2: "~\\APPDATA\\LOCAL\\PROGRAMS\\PYTHON\\PYTHON310\\PYTHON.EXE", Arg 3: undefined
10:59:03.673 [info] Process Execution: ~\AppData\Local\Programs\Python\Python310\python.exe c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.8.0-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 34900
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2024.8.0-win32-x64\pythonFiles\vscode_datascience_helpers
10:59:05.657 [debug] Interpreter for Pylance for Notebook URI "~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb" is ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe
10:59:06.727 [trace] Got a response of 1332 for INITIALIZE_INTERRUPT:0
10:59:07.041 [info] Process Execution: ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe -m ipykernel_launcher --f=c:\Users\~\AppData\Roaming\jupyter\runtime\kernel-v3db96837470e269fe4dd2611b93ff2808dd8baa76.json
    > cwd: ~\Documents\python\him-on-gr-hbn
10:59:07.042 [debug] Kernel process 90648.
10:59:08.018 [trace] ipykernel version & path 6.25.1, ~\Documents\python\him-on-gr-hbn\.venv\lib\site-packages\ipykernel\__init__.py for ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe
10:59:19.975 [debug] Waiting for Raw Session to be ready in postStartRawSession
10:59:19.976 [debug] Waiting for Raw session to be ready, status: connected
10:59:19.976 [trace] Raw session connected
10:59:19.979 [debug] Waited for Raw session to be ready & got status: connected
10:59:19.979 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
10:59:19.980 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
10:59:19.980 [debug] Sending request for kernelInfo
10:59:19.984 [debug] Kernel output 90648: To connect another client to this kernel, use:
--existing c:\Users\~\AppData\Roaming\jupyter\runtime\kernel-v3db96837470e269fe4dd2611b93ff2808dd8baa76.json
10:59:20.320 [trace] Got response for requestKernelInfo
10:59:20.326 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 346ms
10:59:20.334 [trace] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
10:59:20.399 [trace] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
10:59:20.402 [trace] Started running kernel initialization for ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb
10:59:20.406 [trace] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
10:59:20.945 [trace] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 1 output(s)
10:59:20.947 [trace] Determined IPyWidgets Version as 8
10:59:20.949 [trace] Executing silently Code (idle) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None):
10:59:21.018 [trace] Executing silently Code (completed) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None): with 0 output(s)
10:59:21.020 [debug] Requesting Kernel info
10:59:21.023 [trace] Got Kernel info
10:59:21.026 [trace] End running kernel initialization, now waiting for idle
10:59:21.029 [trace] Waiting for idle on (kernel): e278fc51-90d6-4f02-b8c5-68db0f87afdf -> idle
10:59:21.032 [trace] Finished waiting for idle on (kernel): e278fc51-90d6-4f02-b8c5-68db0f87afdf -> idle
10:59:21.035 [trace] End running kernel initialization, session is idle
10:59:21.040 [trace] Registering Kernel Completion Provider from kernel .venv (Python 3.10.11) for language python
10:59:21.043 [info] Kernel successfully started
10:59:21.342 [trace] Conda file is conda
10:59:29.784 [trace] IPyWidgetScriptSource.initialize
10:59:29.789 [trace] Registering commtarget jupyter.widget
10:59:29.795 [debug] Start refreshing Interpreter Kernel Picker
10:59:29.796 [debug] Start refreshing Kernel Picker (1725613169796)
10:59:29.808 [trace] Version of IPyWidgets 8 determined after 0.013s
10:59:29.821 [debug] getDataDirsImpl, Class name = Mr (started execution), Arg 1: "/c:/Users/~/Documents/python/him-on-gr-hbn/odmr_hamiltonian.ipynb", Arg 2: "~\\DOCUMENTS\\PYTHON\\HIM-ON-GR-HBN\\.VENV\\SCRIPTS\\PYTHON.EXE"
10:59:29.833 [debug] Get Custom Env Variables, Class name = Em, completed in 11ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
10:59:29.834 [debug] Jupyter Paths : 
10:59:29.946 [info] Process Execution: ~\Documents\python\him-on-gr-hbn\.venv\Scripts\python.exe c:\Users\~\.vscode\extensions\ms-toolsai.jupyter-2024.8.0-win32-x64\pythonFiles\printJupyterDataDir.py
10:59:30.716 [trace] Web view is ready to receive widget messages
10:59:30.772 [trace] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
10:59:30.962 [trace] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
10:59:30.979 [trace] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
10:59:30.984 [trace] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
10:59:30.990 [trace] IPyWidget version in Kernel is 8.
10:59:30.994 [trace] Version of IPyWidgets 8 determined after 0s
10:59:30.997 [trace] Version of IPyWidgets 8 determined after 0s
10:59:31.000 [trace] Version of IPyWidgets 8 determined after 0s
10:59:31.002 [trace] Version of IPyWidgets 8 determined after 0s
10:59:31.005 [trace] Version of IPyWidgets 8 determined after 0s
10:59:31.007 [trace] Version of IPyWidgets 8 determined after 0s
10:59:31.010 [trace] Version of IPyWidgets 8 determined after 0s
10:59:31.031 [trace] Version of IPyWidgets 8 determined after 0s
10:59:31.039 [trace] Version of IPyWidgets 8 determined after 0s
10:59:31.045 [trace] Version of IPyWidgets 8 determined after 0.001s
10:59:31.264 [debug] Got an empty Jupyter Data Dir from C:\USERS\~\DOCUMENTS\PYTHON\HIM-ON-GR-HBN\.VENV\SCRIPTS\PYTHON.EXE, stderr = undefined
10:59:31.266 [debug] getDataDirsImpl, Class name = Mr, completed in 1445ms, has a truthy return value, Arg 1: "/c:/Users/~/Documents/python/him-on-gr-hbn/odmr_hamiltonian.ipynb", Arg 2: "~\\DOCUMENTS\\PYTHON\\HIM-ON-GR-HBN\\.VENV\\SCRIPTS\\PYTHON.EXE", Return Value: <Uri:/C:/Users/~/AppData/Roaming/jupyter>, <Uri:/c:/Users/~/Documents/python/him-on-gr-hbn/.venv/share/jupyter>, <Uri:/C:/ProgramData/jupyter>
10:59:31.685 [trace] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/~/AppData/Roaming/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.8.0/scripts/e9ac82aaf2ad2d16929a7cbb865fe7cef73d4baa9d85df44fa21cb9449fb496b/jupyter
10:59:31.694 [trace] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/~/AppData/Roaming/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.8.0/scripts/e9ac82aaf2ad2d16929a7cbb865fe7cef73d4baa9d85df44fa21cb9449fb496b/jupyter
10:59:32.098 [trace] Widget Message: Received IPyWidget scripts [{"moduleName":"jupyter-matplotlib","scriptUri":"https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/~/AppData/Roaming/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.8.0/scripts/e9ac82aaf2ad2d16929a7cbb865fe7cef73d4baa9d85df44fa21cb9449fb496b/jupyter/nbextensions/jupyter-matplotlib/index","source":"local"}]
10:59:32.103 [trace] Widget Message: Source for IPyWidget jupyter-matplotlib found in local @ https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/~/AppData/Roaming/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.8.0/scripts/e9ac82aaf2ad2d16929a7cbb865fe7cef73d4baa9d85df44fa21cb9449fb496b/jupyter/nbextensions/jupyter-matplotlib/index.
10:59:32.112 [trace] Widget Message: Registering IPyWidget jupyter-matplotlib found in https://file%2B.vscode-resource.vscode-cdn.net/c%3A/Users/~/AppData/Roaming/Code/User/globalStorage/ms-toolsai.jupyter/version-2024.8.0/scripts/e9ac82aaf2ad2d16929a7cbb865fe7cef73d4baa9d85df44fa21cb9449fb496b/jupyter/nbextensions/jupyter-matplotlib/index.
10:59:36.773 [debug] Handle Execution of Cells 5 for ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb
10:59:36.777 [trace] Execute Notebook ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 1
10:59:36.779 [trace] Connect to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 2
10:59:36.782 [trace] Connected to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 3
10:59:36.784 [trace] executeCell 5. Step 4
10:59:36.790 [trace] Cell Index:5 sent to kernel
10:59:36.825 [trace] Start cell 5 execution @ 1725613176821 (clear output)
10:59:36.833 [debug] Kernel acknowledged execution of cell 5 @ 1725613176821
10:59:38.129 [debug] Handle Execution of Cells 6 for ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb
10:59:38.131 [trace] Execute Notebook ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 1
10:59:38.132 [trace] Connect to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 2
10:59:38.134 [trace] Connected to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 3
10:59:38.135 [trace] executeCell 6. Step 4
10:59:41.402 [debug] Handle Execution of Cells 7 for ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb
10:59:41.404 [trace] Execute Notebook ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 1
10:59:41.405 [trace] Connect to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 2
10:59:41.407 [trace] Connected to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 3
10:59:41.410 [trace] executeCell 7. Step 4
10:59:48.036 [debug] Handle Execution of Cells 29 for ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb
10:59:48.037 [trace] Execute Notebook ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 1
10:59:48.039 [trace] Connect to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 2
10:59:48.041 [trace] Connected to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 3
10:59:48.042 [trace] executeCell 29. Step 4
10:59:49.250 [trace] Cell 5 completed in 12.428s (start: 1725613176821, end: 1725613189249)
10:59:49.253 [trace] Cell 5 executed successfully
10:59:49.257 [trace] Cell Index:6 sent to kernel
10:59:49.296 [trace] Start cell 6 execution @ 1725613189296 (clear output)
10:59:49.300 [debug] Kernel acknowledged execution of cell 6 @ 1725613189296
10:59:55.301 [trace] Python API env change detected, update => 'C:\USERS\~\APPDATA\LOCAL\PROGRAMS\PYTHON\PYTHON310\PYTHON.EXE'
10:59:55.306 [trace] Python API env change detected, update => 'C:\USERS\~\DOCUMENTS\PYTHON\HIM-ON-GR-HBN\.VENV\SCRIPTS\PYTHON.EXE'
10:59:55.313 [trace] Python API env change detected, update => 'C:\USERS\~\APPDATA\LOCAL\MICROSOFT\WINDOWSAPPS\PYTHON3.10.EXE'
10:59:55.317 [trace] Python API env change detected, update => 'C:\PROGRAM FILES\INKSCAPE\BIN\PYTHON.EXE'
10:59:55.321 [trace] Python API env change detected, update => 'C:\USERS\~\.LOCAL\PIPX\VENVS\POETRY\SCRIPTS\PYTHON.EXE'
10:59:55.336 [debug] Refreshed Environments
10:59:56.342 [debug] End refreshing Kernel Picker (1725613169796)
11:00:08.150 [trace] Cell 6 completed in 18.854s (start: 1725613189296, end: 1725613208150)
11:00:08.151 [trace] Cell 6 executed successfully
11:00:08.155 [trace] Cell Index:7 sent to kernel
11:00:08.172 [trace] Start cell 7 execution @ 1725613208172 (clear output)
11:00:08.177 [debug] Kernel acknowledged execution of cell 7 @ 1725613208172
11:00:08.214 [trace] Cell 7 completed in 0.042s (start: 1725613208172, end: 1725613208214)
11:00:08.216 [trace] Cell 7 executed successfully
11:00:08.219 [trace] Cell Index:30 sent to kernel
11:00:08.252 [trace] Start cell 30 execution @ 1725613208252 (clear output)
11:00:08.255 [debug] Kernel acknowledged execution of cell 30 @ 1725613208252
11:00:08.270 [trace] Cell 30 completed in 0.018s (start: 1725613208252, end: 1725613208270)
11:00:08.272 [trace] Cell 30 executed successfully
11:00:12.451 [debug] Execution of code ms-toolsai.jupyter-1 completed in 149ms
11:00:22.147 [debug] Handle Execution of Cells 29 for ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb
11:00:22.148 [trace] Execute Notebook ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 1
11:00:22.150 [trace] Connect to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 2
11:00:22.152 [trace] Connected to Kernel ~\Documents\python\him-on-gr-hbn\odmr_hamiltonian.ipynb. Step 3
11:00:22.153 [trace] executeCell 29. Step 4
11:00:22.155 [trace] Cell Index:29 sent to kernel
11:00:22.166 [trace] Start cell 29 execution @ 1725613222166 (clear output)
11:00:22.169 [debug] Kernel acknowledged execution of cell 29 @ 1725613222166
11:00:22.287 [trace] Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
11:00:22.333 [trace] Widget Message: WidgetManager: Loading class MPLCanvasModel:jupyter-matplotlib:^0.11
11:00:22.354 [trace] Widget Message: WidgetManager: failed, Loading class MPLCanvasModel:jupyter-matplotlib:^0.11
11:00:22.361 [error] Widget load failure {} [ 'jsdelivr.com', 'unpkg.com' ] {
  className: 'MPLCanvasModel',
  moduleName: 'jupyter-matplotlib',
  moduleVersion: '^0.11',
  isOnline: true,
  timedout: false,
  error: '{}'
}
11:00:22.364 [trace] Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:2.0.0
11:00:22.371 [trace] Widget Message: WidgetManager: Loading class ToolbarModel:jupyter-matplotlib:^0.11
11:00:22.378 [trace] Widget Message: WidgetManager: failed, Loading class ToolbarModel:jupyter-matplotlib:^0.11
11:00:22.384 [error] Widget load failure {} [ 'jsdelivr.com', 'unpkg.com' ] {
  className: 'ToolbarModel',
  moduleName: 'jupyter-matplotlib',
  moduleVersion: '^0.11',
  isOnline: true,
  timedout: false,
  error: '{}'
}
11:00:22.782 [trace] Widget Message: Received display data message b4986c36d0bd4993a0390556fe1ae95e
11:00:22.791 [trace] Cell 29 completed in 0.623s (start: 1725613222166, end: 1725613222789)
11:00:22.793 [trace] Cell 29 executed successfully
11:00:22.851 [trace] Version of IPyWidgets 8 determined after 0s
11:00:22.919 [trace] Widget Message: Waiting for model to be available before rendering it b4986c36d0bd4993a0390556fe1ae95e
11:00:22.922 [trace] Widget Message: WidgetManager: Loading class ErrorWidgetView:@jupyter-widgets/base:2.0.0
11:00:22.929 [trace] Widget Message: WidgetManager: Loading class LayoutView:@jupyter-widgets/base:2.0.0
```

Definitely reproducible:

![image](https://github.com/user-attachments/assets/2f9509f3-90fb-4259-bf8a-c2a38408f2a3)

Tested on simple code and minimal packages.

**Comment by georgedeath** [comment] 2024-09-06 09:16
I have the same issue. 

If I remove the line `"jupyter.widgetScriptSources": ["jsdelivr.com", "unpkg.com"]` from the settings.json file it will ask to download the widget (and add that line back into the json). This then lets the widget work.

However, if I then reload VSCode again the same error returns.

**Comment by amcar-dtu** [comment] 2024-09-06 09:19
It is also mentioned in the Settings that one should not remove both lines:

<img width="602" alt="image" src="https://github.com/user-attachments/assets/d275726e-00c0-4738-87d8-69337830437f">

**Comment by DonJayamanne** [comment] 2024-09-08 00:41
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/16008

**Closed by DonJayamanne** 2024-09-08 00:41 UTC
Labels: bug
