### ISSUE TITLE
Orphaned process after Python kernel restart (python.exe -m vscode_datascience_helpers.daemon process)

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode-jupyter#10182] opened 2022-05-30 16:41 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Everytime a Python kernel is restarted using the restart toolbar button, Jupyter extension leaves behind one orphaned Python process. If you restart the kernel 8 times, you will have 8 orphaned processes consuming memory. These processes are not closed even if you close the notebook.

The command line of the leaked processes:

`python.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 7352`

### VS Code Version

Version: 1.67.2 (user setup) Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 Date: 2022-05-17T18:15:52.058Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2022.4.1021342353

### Coding Language and Runtime Version

Python v3.10.4

### Language Extension Version (if applicable)

v2022.6.2

### Running Jupyter locally or remotely?

Local

**Comment by greazer** [comment] 2022-06-02 20:20
This process doesn't contain any important code.

**Comment by DonJayamanne** [comment] 2022-08-02 18:26
* We can spawn the python process using the traditional approach and send messages using std stream or sockets. (removing need & complexity of using daemon)
* We can just kill these processes when vscode dies

**Comment by 2-5** [comment] 2022-08-02 18:36
I didn't mention in the original report, but these processes are killed when vscode exits. They are only orphaned while vscode is running. So it's not a problem from that point of view. Still a bit annoying when restarting kernels a lot.

**Comment by DonJayamanne** [comment] 2022-08-02 18:46
>  Still a bit annoying when restarting kernels a lot.

We can update the code to have a single process per VS Code session, instead of having mutiples.

**Comment by DonJayamanne** [comment] 2022-08-10 01:01
Closing as a duplicate of #9909 We will have a single process for interrupting Python kernels & that will be tracked in #9909

**Closed by DonJayamanne** 2022-08-10 01:01 UTC
Labels: bug, perf, notebook-execution
