### ISSUE TITLE
Directly debugging Jupyter Notebook instead of converting to .py first

### ISSUE THREAD

**Issue by ahmednrana** [microsoft/vscode-jupyter#5562] opened 2021-04-20 10:15 UTC
As per my understanding, to debug a jupyter notebook we first need to convert it to .py and then debug that .py file.
Is there possible to debug directly the Jupyter notebook in interactive mode and set breakpoints there?

Xues Python as per the below Jupyter blog can also do this.
https://blog.jupyter.org/a-visual-debugger-for-jupyter-914e61716559

PyCharm Professional provides this out of box.
https://www.jetbrains.com/help/pycharm/running-jupyter-notebook-cells.html#clear-output

It would be helpful if Vs code debug jupyter notebooks directly too.

**Comment by greazer** [comment] 2021-04-21 21:31
Dupe of #1652

**Closed by greazer** 2021-04-21 21:31 UTC
Labels: enhancement
