### ISSUE TITLE
Support auto formatting (e.g. black) for ipynb files

### ISSUE THREAD

**Issue by alonme** [microsoft/vscode-jupyter#9710] opened 2022-04-19 12:23 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I cannot find a way to apply auto formatting (format on save) for jupyter notebooks.
Is there a way to do that?

### VS Code Version

Version: 1.66.2 (Universal) Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977 Date: 2022-04-11T07:49:20.994Z (1 wk ago) Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 OS: Darwin x64 20.4.0

### Jupyter Extension Version

v2022.3.1000901801

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment] 2022-04-19 16:24
Thanks for the suggestion. Marking as a dupe of https://github.com/microsoft/vscode-jupyter/issues/7058

**Closed by rchiodo** 2022-04-19 16:24 UTC
Labels: bug, needs-triage
