### ISSUE TITLE
mitosheet import error in Vs code

### ISSUE THREAD

**Issue by ridhanya99** [microsoft/vscode-jupyter#6336] opened 2021-06-20 08:11 UTC
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DavidKutu** [comment] 2021-06-21 18:06
Hi @ridhanya99, sorry to hear you're having issues. Could you please fill out the issue template for us to help you?

**Comment by ridhanya99** [comment] 2021-06-22 04:05
Thank you for your response..

Error: Module mitosheet3, semver range ^0.3.70 is not registered as a widget module.
Unable to load a compatible version of the widget 'mitosheet3'. Expected behavior may be affected.

**Comment by DavidKutu** [comment] 2021-06-23 00:43
@ridhanya99 could you please upload the output from the `Jupyter` output panel? As well as the Jupyter extension version, the python extension version and your OS (windows, mac, linux)? Also, could you describe what you're trying to do? Are you running a notebook?

Thanks.

**Comment by ridhanya99** [comment] 2021-06-23 06:14
Thank you for your reply sir,
I was trying to use mitosheet in vscode jupyter notebook.
          import mitosheet
          import pandas as pd
          mitosheet.sheet()

I faced the following error:
Error: Module mitosheet3, semver range ^0.3.70 is not registered as a
widget module.
Unable to load a compatible version of the widget 'mitosheet3'. Expected
behavior may be affected.

Then I found that it can be run in jupyter lab, so I am currently using it
there..


Thanks,
@ridhanya99

**Comment by DavidKutu** [comment] 2021-06-23 23:03
Sorry for the trouble @ridhanya99, I'll gladly try to help you resolve this.

Could you upload the output from the `Jupyter` output panel when the error reproes? That would help a lot.

**Comment by greazer** [comment] 2021-06-24 20:10
Dupe of #6320.

**Closed by greazer** 2021-06-24 20:10 UTC
Labels: bug, info-needed

**Comment by ridhanya99** [comment] 2021-06-25 14:47
Thanks a lot!
