### ISSUE TITLE
IntelliSense is not working in Jupyter Notebook editor

### ISSUE THREAD

**Issue by ernurator** [microsoft/vscode-jupyter#4505] opened 2021-01-26 15:47 UTC
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro 10.0.19041
-   Python and/or Anaconda version: Python 3.8.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour
IntelliSense works in .py files
![image](https://user-images.githubusercontent.com/60398507/105867391-3f77ca80-601f-11eb-9f73-5c046455d383.png)

## Actual behaviour
But not working in Jupyter Notebook editor
![image](https://user-images.githubusercontent.com/60398507/105867468-56b6b800-601f-11eb-9fec-1eddd9f5c309.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
User belongs to experiment group 'jupyterTest'
Error 2021-01-26 21:44:36: Jupyter Kernel Spec not found for a local connection
> c:\Users\isenb\projects\comp_vision\opencv\Scripts\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> c:\Users\isenb\projects\comp_vision\opencv\Scripts\python.exe -c "import os;print(os.path.realpath("C:\\Users\\isenb\\AppData\\Roaming\\jupyter\\kernels"))"
> c:\Users\isenb\projects\comp_vision\opencv\Scripts\python.exe -c "import os;print(os.path.realpath("C:\\Users\\isenb\\AppData\\Roaming\\jupyter\\kernels"))"
> c:\Users\isenb\projects\comp_vision\opencv\Scripts\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> c:\Users\isenb\projects\comp_vision\opencv\Scripts\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3.8.0 32-bit ('opencv')
Error 2021-01-26 21:44:42: [Error: command 'python.analysis.restartLanguageServer' already exists
	at _.registerCommand (c:\Users\isenb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:699:970)
	at Object.registerCommand (c:\Users\isenb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1020:634)
	at c.registerCommand (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:59:667016)
	at new r (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:59:52528)
	at Object.t.resolveInstance (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:44:269546)
	at c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:44:268512
	at Array.map (<anonymous>)
	at Object.t.resolveInstance (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:44:269316)
	at c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:44:268512
	at Object.t.resolve (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:44:268775)
	at c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:44:259351
	at e._get (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:44:259117)
	at e.getTagged (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:44:257920)
	at e.getNamed (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:44:258012)
	at a.get (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:59:938360)
	at w.createRefCountedServer (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:52:30816)
	at async Object.getLanguageServer (c:\Users\isenb\.vscode\extensions\ms-python.python-2021.1.502429796\out\client\extension.js:52:6600)
	at async Function.create (c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:290779)
	at async L.getLanguageServer (c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:263836)
	at async L.handleChanges (c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:265911)
	at async L.loadAllCells (c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:49:272724)]
> c:\Users\isenb\projects\comp_vision\opencv\Scripts\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import ipykernel"
> c:\Users\isenb\projects\comp_vision\opencv\Scripts\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~\Anaconda3\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import notebook"
> ~\Anaconda3\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py -c "import jupyter"
> ~\Anaconda3\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py jupyter kernelspec --version
> ~\Anaconda3\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\Anaconda3\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~\Anaconda3\python.exe c:\Users\isenb\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\pythonFiles\pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v

```

</p>
</details>

**Comment by IanMatthewHuff** [comment] 2021-01-26 18:25
@ernurator Thanks for filing this. A quick question here. What language server are you using for the Python: Language server setting?

**Comment by ernurator** [comment] 2021-01-26 20:10
@IanMatthewHuff Microsoft Python Language Server version 0.5.59.0

**Comment by IanMatthewHuff** [comment] 2021-01-27 01:05
@ernurator Can you try moving that setting over to Pylance? Check to see if you get Intellisense after that change.

**Comment by ernurator** [comment] 2021-01-27 06:33
@IanMatthewHuff it partially worked.

![image](https://user-images.githubusercontent.com/60398507/105952330-a2a74280-609b-11eb-9ae7-72497a7e25c8.png)

![image](https://user-images.githubusercontent.com/60398507/105952343-a76bf680-609b-11eb-8f3b-bcba7386586c.png)

Now it doesn't show description of methods

**Comment by IanMatthewHuff** [comment] 2021-01-27 21:02
We actually had a bug for this recently. We have the fix in, but it's not been released yet. Should be in our next extension release. I'm going to close this issue as a duplicate of the other issue on the topic.
https://github.com/microsoft/vscode-jupyter/issues/4218

**Closed** 2021-01-27 21:02 UTC
Labels: bug

**Comment by ernurator** [comment] 2021-01-28 03:49
Okay, thanks!

**Comment by IanMatthewHuff** [comment] 2021-01-28 16:56
If you still see an issue here after our next release (no date promises, but we usually release about every month) just ping back here and I'll reactivate this issue.

**Comment by ernurator** [comment] 2021-02-16 09:22
@IanMatthewHuff problem still exists after new release
![image](https://user-images.githubusercontent.com/60398507/108042908-a3177580-706a-11eb-8544-f77157da4905.png)
![image](https://user-images.githubusercontent.com/60398507/108042981-b9bdcc80-706a-11eb-9f06-2acaadd8a88b.png)

**Comment by IanMatthewHuff** [comment] 2021-02-16 16:38
@ernurator You may be thinking of a release of the Python extension? This fix is in the Jupyter extension (which used to be part of the Python extension) and we have not yet made our release. You can check our release page in the marketplace here:
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
We've had a bit longer gap in our usual release due to the holidays and some large UI changes coming in the next release.

**Comment by ernurator** [comment] 2021-02-16 19:27
@IanMatthewHuff okay, got it.
