### ISSUE TITLE
Jupyter cell debugging does not step into all code

### ISSUE THREAD

**Issue by thoughtfulmoron** [microsoft/vscode-jupyter#10622] opened 2022-06-19 07:01 UTC
Running the Debug Cell option does not step into all code despite the Jupyter: Debug Just my Code being deselected in settings

**Comment by DonJayamanne** [comment] 2022-06-28 20:38
@rchiodo I believe this was by design, even in the old run by line this is what we used to do ( as well as the new nb run by line).

**Comment by rchiodo** [comment] 2022-06-28 20:40
Run by line is different in my opinion. It doesn't really make sense without just my code.

But DebugCell you might want to step into IPython.

**Comment by DonJayamanne** [comment] 2022-06-28 20:53
> But DebugCell you might want to step into IPython.

Agreed

**Comment by DonJayamanne** [comment] 2022-06-28 20:55
Found it, this issue is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/8146

**Comment by DonJayamanne** [comment] 2022-06-30 20:16
Closing as a duplicate

**Closed by DonJayamanne** 2022-06-30 20:16 UTC
Labels: notebook-debugging, triage-needed
