### ISSUE TITLE
VS Code Jupyter integration does not consider custom LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode-jupyter#10927] opened 2022-07-26 02:11 UTC
I recently setup a fresh EC2 instance for development running Amazon Linux 2. To run the recent version of prefect (https://orion-docs.prefect.io/) I had to install an up to date version of SQLite3, which I compiled from source. I then set the LD_LIBRARY_PATH environmental variable to "/usr/local/lib", and installed python 3.10.5 with the LDFLAGS and CPPFLAGS compiler arguments to include that folder as well, so that the new sqlite libraries are found by python. All good so far, when running the jupyter notebook server or the prefect orion server from the terminal everything works fine. If I want to use the integrated jupyter environment from VS Code I run into the issue that the kernel does not start:

> Failed to start the Kernel.
> 
> ImportError: /home/mickelj/.pyenv/versions/3.10.5/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu.so: undefined symbol: sqlite3_trace_v2.

This leads me to believe that the system sqlite library is used, as this is the same error I get when I unset the LD_LIBRARY_PATH env variable. However when calling `ldd /home/mickelj/.pyenv/versions/3.10.5/lib/python3.10/lib-dynload/_sqlite3.cpython-310-x86_64-linux-gnu`.so I am getting the following:

> linux-vdso.so.1 (0x00007ffcde9c8000)
> libsqlite3.so.0 => /usr/local/lib/libsqlite3.so.0 (0x00007f96a3339000)
> libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f96a311b000)
> libc.so.6 => /lib64/libc.so.6 (0x00007f96a2d6e000)
> libz.so.1 => /lib64/libz.so.1 (0x00007f96a2b59000)
> libm.so.6 => /lib64/libm.so.6 (0x00007f96a2819000)
> libdl.so.2 => /lib64/libdl.so.2 (0x00007f96a2615000)
> /lib64/ld-linux-x86-64.so.2 (0x00007f96a3870000)

Where the new sqlite3 library is correctly referenced. If I unset the LD_LIBRARY_PATH variable the second line changes to:

> libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007f9dce52e000)

So my guess is that the VS Code jupyter integration does not consider environment variables, so my question is: is there a way to specify them (and in particular the LD_LIBRARY_PATH) globally for VS Code or for the built-in jupyter server at runtime or anywhere else to fix this?

**Comment by DonJayamanne** [comment] 2022-07-26 05:28
How are you seeing the environment variables?
you can say it two ways:
* create a . env file in your workspace folder and initialuze the variable in that file
* or initialize the variable in your login shell scroll such as .bashrc or the like

we recently fixed a few issues related to losing of env variable.
hence i works suggest you install vscode insiders and then install the latest pre-release version of the jupyter extension to get the fixes.

please ensure you exit vscode completely when making changes to your login shell scripts.

let me know how this goes in vscode insiders.

**Comment by ydmykr** [comment] 2022-08-08 06:24
@DonJayamanne  The latter. I use the fish shell, and have the LD_LIBRARY_PATH set in the fish .config.

**Comment by DonJayamanne** [comment] 2022-08-14 22:56
@ydmykr 
Please could you:
* Exit VS Code completely (ensure you do not have any vscode process running)
* Start vscode,
* Open a notebook and print the value of the env variable `LD_LIBRARY_PATH` using python code
```
import os
os.getenv('LD_LIBRARY_PATH')
```

Let me know if that works
Please ensure you are using the latest version of the Jupyter Extension and latest version of VS Code, we've fixed a few issues with regards to loading env variables.

**Comment by DonJayamanne** [comment] 2022-10-09 22:34
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Closed by DonJayamanne** 2022-10-09 22:34 UTC
Labels: bug, info-needed, kernel-env-vars

**Comment by gchenfc** [comment] 2022-10-11 20:37
I had the same issue.
I switched to pre-release then killed all vscode processes (`pkill -f vscode`) and now it works.

I think this might related to needing to "log-out" for changes .profile to update, but I'm not exactly sure what fixed it (pre-release or killing vscode or both) and can't reproduce.
