### ISSUE TITLE
Input Problems with Interactive Terminal

### ISSUE THREAD

**Issue by tsoud** [microsoft/vscode-jupyter#446] opened 2020-11-09 20:36 UTC
Issue Type: <b>Bug</b>

Typing directly into the Python interactive terminal is buggy. This seems to be an issue in the latest (October 2020) release since it began immediately after the update.

Expected result: You type something into the interactive terminal input cell and characters appear...

Actual result: You type into the interactive terminal and nothing happens. Usually, you can start typing after clicking the cursor a few times but many times the terminal input cell does not respond at all requiring a restart.

Extension version: 2020.10.332292344
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:16:10.374Z)
OS version: Linux x64 5.4.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.20GB (7.46GB free)|
|Process Argv|. --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by ihnorton** [comment] 2020-11-11 22:35
Click-dragging the "Python Interactive" tab and moving it to a new split position (eg side by side or the reverse) seems to fix the problem temporarily :/

**Comment by rboyes** [comment] 2020-11-12 15:16
Same issue here

```
Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by IanMatthewHuff** [comment] 2020-11-12 22:57
Hey everyone. Just wanted to comment to thank folks for reporting this issue. I'm able to repro this as well, and I'm looking into it. Not fully sure on the cause yet as the repro is (at least for me) very sporadic for when it happens.

**Comment by tsoud** [comment] 2020-11-12 23:58
@IanMatthewHuff thanks for taking this on! In my case it's sporadic but frequent, and especially noticeable when switching back and forth between the editor and interactive window.

Additional note: I just updated from 1.51.0 to 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f) and the issue persists.

**Comment by tsoud** [comment] 2020-11-14 18:35
Another update: 
When the prompt in the interactive window won't accept input, I noticed that using Ctrl '+' followed by Ctrl '-' (i.e. zooming in and zooming back out) on my Linux system fixes it temporarily. 
This is the same workaround I use when the text in my VSCode terminal window disappears every now and then.

**Comment by GusHebblewhite** [comment] 2020-11-16 00:42
+1 for this issue

**Comment by anzhaozhou** [comment] 2020-11-16 01:06
Press ctrl+B can temporarily fix this on windows(and also on wsl2), but will happen again very soon,

**Comment by janosh** [comment] 2020-11-16 12:16
The suggestions by @ihnorton to drag the interactive window to a new editor group and by @tsoud zooming in and out (even faster) are both working as temporary fixes. Thanks for that!

**Comment by greazer** [comment] 2020-11-17 08:37
Lots of dupes being entered for this issue, so marking as high-priority.

**Comment by rchiodo** [comment] 2020-11-17 17:30
If I click back and forth between the python editor and the interactive window a bunch, it seems to repro every time. Might be related to our focus tracking.

**Comment by rchiodo** [comment] 2020-11-17 21:17
Root cause looks to be that the body of the interactive window has focus when the monaco editor thinks it does. So when we tell the monaco editor to take focus it doesn't. 

Not sure yet what is stealing focus away for the body yet.

**Comment by rchiodo** [comment] 2020-11-17 23:16
Seems like the VS code webview code is stealing focus. The activate message we send can interfere with this focus. IF we don't use this activate the IW won't lock up (although then it won't get focus unless you click on it).

**Comment by IanMatthewHuff** [comment] 2020-11-19 18:51
Validated based on our bug bash testing.

**Closed by IanMatthewHuff** 2020-11-19 18:51 UTC
Labels: bug

**Comment by bk8190** [comment] 2020-11-20 11:42
azz147 solution of pressing ctrl-B works for me - it temporarily fixes the problem on Windows and is easier than moving the window to a new pane

**Comment by thanosgatos** [comment] 2020-12-10 09:35
I am experiencing the same thing. I was about to create a new issue, but I saw all the late ones have been closed as duplicates. This is still an issue that occurs every few minutes. It has actually been getting worse. It's becoming a blocker. Is there still no solution to this?

**Comment by rchiodo** [comment] 2020-12-10 17:11
> I am experiencing the same thing. I was about to create a new issue, but I saw all the late ones have been closed as duplicates. This is still an issue that occurs every few minutes. It has actually been getting worse. It's becoming a blocker. Is there still no solution to this?

@thanosgatos What is your extension version? This should have been fixed already.

**Comment by pedroschuller** [comment] 2021-01-22 14:09
Any update on this? Experiencing same problem and ctrl-+ or ctrl-B are not helping.
