### ISSUE TITLE
Cannot display `"application/vnd.dataresource+json"`

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode-jupyter#15004] opened 2024-01-09 11:06 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### Minimal Reproduction

1. [install `deno`](https://docs.deno.com/runtime/manual/)
2. enable [deno's jupyter kernel](https://docs.deno.com/runtime/manual/tools/jupyter)
3. write following `.ipynb` file and open in vscode.

```ts
import pl from "npm:nodejs-polars"
import { display } from "https://deno.land/x/display@v1.1.2/mod.ts"

const df = pl.DataFrame({
	fruit: ["Apples", "Oranges"],
	comparability: [0, 1],
})
await display(df)
df
```

### Expected behavior (Jupyter Lab)

<img width="639" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/54838975/8aad07df-be80-4c81-8060-5bc3a5e2da9f">

### Actual behaivor (VSCode)

<img width="633" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/54838975/3b53dd3b-f017-4422-ba37-002bdb35c5f7">

#### Preprocessing

With help of https://github.com/denoland/vscode_deno/issues/1014, found out that the `display` function sent data to jupyter in following format: 

```
message_type: "display_data",
data: {
    "application/vnd.dataresource+json": { data: [ [Object], [Object] ], schema: { fields: [Array] } },
    "text/html": "<table><thead><tr><th>fruit</th><th>comparability</th></tr></thead><tbody><tr><td>Apples</td><td>0</"... 59 more characters
  },
  metadata: {},
  transient: {}
}
```

Removing `"application/vnd.dataresource+json"` field fixes it.

#### Changing presentation

<img width="433" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/54838975/1fd52370-c09a-49b9-948a-11ecadea84c7">
<img width="221" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/54838975/44b66bf9-743c-4afc-a00a-a29100b85a0d">

Changing presentation from  `application/vnd.dataresource+json` to `text/html` fixes it.

However this issue is still problematic because:

- mimetype `application/vnd.dataresource+json` is not recognized as JSON
- data in unrecognized mimetype renders as empty, which is confusing to encounter and hard to figure out the cause
- most of the time users would probably want HTML output to have the highest priority
- the behaviour of VSCode extension differs from jupyter lab

### VS Code Version

1.85.1 (Universal)

### Jupyter Extension Version

v2024.1.2024010901

### Jupyter logs

```shell
18:56:13.795 [info] Restart requested ~/repo/polars/main.ipynb
18:56:13.796 [info] Dispose Kernel process 24186.
18:56:13.801 [warn] StdErr from Kernel Process Client disconnected PeerIdentity(b"XXXXXX")
18:56:13.807 [info] Launching Raw Kernel Deno # ~/.local/share/deno/bin/deno
18:56:13.808 [info] Process Execution: ~/.local/share/deno/bin/deno --unstable jupyter --kernel --conn ~/Library/Jupyter/runtime/kernel-v2-XXXXXX.json
    > cwd: ~/repo/polars
18:56:14.018 [info] Restarted XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX
18:56:16.874 [info] Handle Execution of Cells 0 for ~/repo/polars/main.ipynb
18:56:16.875 [info] Kernel acknowledged execution of cell 0 @ 1704794176875
18:56:16.922 [info] End cell 0 execution after 0.047s, completed @ 1704794176922, started @ 1704794176875
```

### Coding Language and Runtime Version

deno 1.39.2 (release, aarch64-apple-darwin), typescript 5.3.3

### Language Extension Version (if applicable)

Deno, v3.31.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2024-01-10 00:04
Duplicate of https://github.com/microsoft/vscode-notebook-renderers/issues/189

**Closed by DonJayamanne** 2024-01-10 00:04 UTC
Labels: bug, notebook-kernel, notebook-output
