### ISSUE TITLE
Issue with matplotlib widget

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#10391] opened 2022-06-09 17:14 UTC
Run this code in a local window, a virtualenv

```py
%matplotlib widget
import ipywidgets as widgets
import matplotlib.pyplot as plt
import numpy as np

def say_my_name(name):
    print(f'My name is {name}')

widgets.interact(say_my_name, name=["Jim", "Emma", "Bond"]);
```

I see the print output twice for some reason

<img width="453" alt="image" src="https://user-images.githubusercontent.com/323878/172905520-180cba09-0353-4b05-b738-f67b7befa52d.png">

In Jupyter lab it looks like this

<img width="349" alt="image" src="https://user-images.githubusercontent.com/323878/172905561-35eea622-9ca5-4f8e-b6f9-482874a8a459.png">

- `...` > Change Presentation, text: see the text output
- Change Presentation back to the jupyter.widget-view+json: it's blank

<img width="654" alt="image" src="https://user-images.githubusercontent.com/323878/172905748-9b65798c-1683-4213-bc34-3f34869bf8d3.png">

**Comment by DonJayamanne** [comment] 2022-06-09 21:01
This is a duplicate issue, I've come across this in the past, let me find the issue.

**Comment by DonJayamanne** [comment] 2022-06-09 21:02
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/4128

**Closed by DonJayamanne** 2022-06-09 21:02 UTC
Labels: bug, ipywidgets, notebook-output
