### ISSUE TITLE
Widget Tests still failing in CI

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5092] opened 2021-03-09 22:06 UTC
1) DataScience IPyWidgets (With Direct Kernel)
       Widget renders after closing and re-opening notebook:
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

  2) DataScience IPyWidgets (With Direct Kernel)
       "after each" hook for "Render beakerx (plot)":
     Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)
      at listOnTimeout (internal/timers.js:531:17)
      at processTimers (internal/timers.js:475:7)

**Comment by DavidKutu** [comment] 2021-05-05 18:14
Dupe of #5265

**Closed by DavidKutu** 2021-05-05 18:14 UTC
