### ISSUE TITLE
Ability to override the block cursor color

### ISSUE THREAD

**Issue by dinedal** [microsoft/vscode-jupyter#4057] opened 2020-12-01 09:02 UTC
I've been looking all over for some setting to change this. I am using a [solarized dark](https://marketplace.visualstudio.com/items?itemName=ginfuru.ginfuru-better-solarized-dark-theme) theme and for some reason the color of the block cursor is always red and ignoring my customizations.

Here is the problem shown:

![cursor_red](https://user-images.githubusercontent.com/606028/100718673-e6434000-33bb-11eb-89e9-13cb3ad00fd2.gif)

Here is a normal editor window:

![cursor_white](https://user-images.githubusercontent.com/606028/100718902-2c989f00-33bc-11eb-9776-35693ba99a80.gif)

From my settings.json:
```json
  "workbench.colorTheme": "Solarized Dark",
  "workbench.colorCustomizations": {
    "editorCursor.foreground": "#ffffff",
    "editorCursor.background": "#ffffff",
    "[Solarized Dark]": {
      "editorCursor.foreground": "#ffffff",
      "editorCursor.background": "#ffffff"
    }
  },
```

How can I set the cursor block color to match?

**Comment by dinedal** [comment] 2020-12-01 09:16
Seems like it's this https://github.com/microsoft/vscode-jupyter/blob/68bee5c0117a9c7b7fd6f27ebc492e072d15daa8/src/datascience-ui/native-editor/index.html#L68 that is somehow taking over the color of the cursor

**Comment by IanMatthewHuff** [comment] 2020-12-01 23:31
@dinedal Currently our notebooks are implemented as a separate webview (basically a webpage that an extension can host in VS Code). This means that they are not actually instances of the vscode editor. We've tried to match up their features as best we could but there are many instances like your block highlighting setting where they don't line up.

On the plus side, VS Code is now actually creating a native notebook interface and we're currently move over to use this. In this UI the editors are actually VS Code editor instances and will respect all settings regarding that. You can get more info about our move over here (as well as preview bits to look at).

https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

I'm going to close this issue down, not because it doesn't exist as an issue (it does) but because we are not making any more changes to the old webviews as we move over to the new interface and I believe that the new notebook interface should resolve your issue.

If you check out the preview bits and the issue is still there just comment here and I can reactivate this issue.

**Closed by IanMatthewHuff** 2020-12-01 23:31 UTC
Labels: enhancement

**Comment by dinedal** [comment] 2020-12-02 08:42
@IanMatthewHuff looks great, and no pressure, just wondering if there is a release date? Blog post came out at the end of July.

**Comment by IanMatthewHuff** [comment] 2020-12-02 17:14
@dinedal Currently if you are on VS Code - Insiders edition this new interface is standard. There are basically a couple more things coming on line before we put everyone on it (Variable explorer & custom IPyWidgets to name a couple). Sorry but can't commit to an exact full release date, in particular with the upcoming US holidays in December (where much of the team will be out of the office). But it is top of the queue.
