### ISSUE TITLE
Hover Documentation Pop up does not work after VSCode 1.52 update

### ISSUE THREAD

**Issue by canersnli** [microsoft/vscode-jupyter#4218] opened 2020-12-11 21:10 UTC
## Environment data

-   VS Code version: 1.52.0
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: Windows10
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A  Local
-  Microsoft Language Server: Pylance v2020.12.2

## Expected behaviour
In ipynb files, on hover, showing documentation pop-up 

## Actual behaviour
Right after VSCode 1.52 update , on hover documentation pop-up stopped working, nothing pops up.  I have downgraded from 1.52 to 1.51.1 and bug has been solved. 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by claudiaregio** [comment] 2020-12-12 00:57
Thanks @canersnli , I am able to repro this in stable.

**Comment by greazer** [comment] 2021-01-04 23:32
Sounds like a regression.

**Comment by luiztauffer** [comment] 2021-01-11 19:58
so, it looks like #4299 was merged and possibly solved this? When is a patch release planned?

**Comment by rchiodo** [comment] 2021-01-11 20:16
Sometime this month I believe.

**Comment by luiztauffer** [comment] 2021-01-11 20:26
I found that I was having autocompletion error in Ipython and Jupyter and found this Issue: https://github.com/ipython/ipython/issues/12740

`pip install jedi==0.17.2` solved for me, also within VSCode

**Comment by canersnli** [comment] 2021-01-17 14:58
> I found that I was having autocompletion error in Ipython and Jupyter and found this Issue: [ipython/ipython#12740](https://github.com/ipython/ipython/issues/12740)
> 
> `pip install jedi==0.17.2` solved for me, also within VSCode

Thanks for the advice but it didn't work for me.

**Comment by joyceerhl** [comment] 2021-01-23 00:56
Validated with numpy documentation popup in debug bits.

**Closed by joyceerhl** 2021-01-23 00:56 UTC
Labels: bug, regression

**Comment by canersnli** [comment] 2021-02-14 09:39
Unfortunately hover pop-up documentation still does not work on VS Code 1.53.2
On top of that, when I downgraded to 1.51.1 to recover pop-up documentation, surprisingly it didn't work either. 

Then I switched between VS Code 1.50.1 - 1.51.1 - 1.53.2  and all language servers ( Pylance, Jedi, Microsoft) combinations but I couldn't recover hover documentation pop-up.  
@joyceerhl  Can you please share working versions of anaconda, python and extensions ? Any other suggestions are welcome aswell.

**Comment by oag335** [comment] 2021-02-15 03:54
I am on VS Code 1.53.2 (Win 10) and I hover pop-up documentation is not working for me either while trying to write Python code.

**Comment by arribass** [comment] 2021-03-11 11:37
I 'm on VS Code 1.54.1 and hover pop-up docs are not working either. Is there any solution in this topic? Insiders works fine in this matters.

**Comment by rchiodo** [comment] 2021-03-11 17:06
@oag335 and @arribass  can you log new issues? It's not clear whether you're talking about ipynb files, whether or not you have pylance installed, and what UI you are seeing this in (pylance is required for the new native notebook UI).

**Comment by arribass** [comment] 2021-03-11 18:43
I have pylance and I'm using an ipynb file. This is what i see when i try to get the docstrings from a function inside a modelu.
The first one is from VS Code Insiders which works pretty fine.
![Captura de pantalla (22)](https://user-images.githubusercontent.com/55694226/110837592-b7354800-82a1-11eb-9d52-2889c5a7c251.png)
![Captura de pantalla (23)](https://user-images.githubusercontent.com/55694226/110837596-b7cdde80-82a1-11eb-8b96-118b42d2f9b4.png)

**Comment by rchiodo** [comment] 2021-03-11 19:07
Yeah I repro that too. Your best bet is to use insiders. We're moving to that new UI eventually so we likely won't fix this in the old UI.

**Comment by arribass** [comment] 2021-03-11 19:52
Okey, in insiders it only works properly when coding on the same cell you have imported the module. If you try to get the docstrings in any other cell it won't show up.

**Comment by rchiodo** [comment] 2021-03-11 19:59
Weird. That sounds like a separate issue. Not sure why the separate cell would matter. As far as the language server is concerned, the entire notebook is one big py file. I'll log a separate issue. I repro this too.

**Comment by arribass** [comment] 2021-03-12 18:56
Thanks. Where can I find that issue? So I can post some snaps with the errors.
