### ISSUE TITLE
Root space littered with -jvsc- files.

### ISSUE THREAD

**Issue by 3h4** [microsoft/vscode-jupyter#11426] opened 2022-09-21 20:02 UTC
Type: <b>Bug</b>

I'm running some experiments in bacteria_classification.ipynb on a remote server, but my root folder is getting littered by:

bacteria_classification-jvsc-3a834b64-f706-438c-ab7e-db96e69bf178c01d590a-de54-4549-9b33-2024131f15f5.ipynb

bacteria_classification-jvsc-5e5a9f02-1123-4cc9-b81e-4b901cefc600033ccd13-0386-4f25-ab7d-9d736f352fab.ipynb

etc...

Why is this?

Extension version: 2022.9.1002511105
VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:07:15.900Z)
OS version: Darwin arm64 20.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.18.0-348.12.2.el8_5.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 4cf64333-f132-4c56-a15d-29c771efde05|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ber|
|OS|Linux x64 4.18.0-348.12.2.el8_5.x86_64|
|CPUs|AMD EPYC 7502 32-Core Processor (128 x 2500)|
|Memory (System)|503.46GB (340.60GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by IanMatthewHuff** [comment] 2022-09-21 20:46
@3h4 Are you seeing those files getting cleaned up when you close down VS Code. Or are they hanging around after that?

**Comment by IanMatthewHuff** [comment] 2022-09-21 21:23
Not fully sure on our assignment on this. Maybe @DonJayamanne?

**Comment by 3h4** [comment] 2022-09-22 19:19
@IanMatthewHuff I'm not sure, I removed them manually. I can try to not remove them and see if they disappear.

**Comment by 3h4** [comment] 2022-09-23 11:05
They seem to stay... 
<img width="453" alt="Screenshot 2022-09-23 at 11 38 08" src="https://user-images.githubusercontent.com/23310996/191947387-3b2d1c03-959b-4d35-9398-001e7c854fa0.png">

**Comment by zhouconghao** [comment] 2022-09-24 16:42
I am having the same problem.

**Comment by DonJayamanne** [comment] 2022-09-25 22:47
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/6510

**Closed by DonJayamanne** 2022-09-25 22:47 UTC
Labels: bug, triage-needed
