### ISSUE TITLE
Using this with cursor caused the extension host to die repeatedly

### ISSUE THREAD

**Issue by GurRonenExplorium** [microsoft/vscode-jupyter#15729] opened 2024-05-30 09:54 UTC
Type: <b>Bug</b>

chat and extension host died repeatedly. This had this error on it regarding about too many file descriptors

Extension version: 2024.4.0
VS Code version: Cursor 0.34.3 (3bbe86ee075988557f0544b47aeba2e97cc6a7a0, 2024-05-29T22:46:54.063Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 5, 5|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment] 2024-05-30 20:20
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15721

**Closed by DonJayamanne** 2024-05-30 20:20 UTC
