### ISSUE TITLE
Notebook freezes when using any imported module.

### ISSUE THREAD

**Issue by shah-xad** [microsoft/vscode-jupyter#10028] opened 2022-05-14 15:39 UTC
## Environment data

-   VS Code version: 1.67.1
-   Jupyter Extension version: 2022.5.1001351004
-   Python Extension version: 2022.7.11332232
-   OS: Linux (Ubuntu)
-   Python: 3.10
-   Type of virtual environment used: venv
-   Jupyter server running: Local

## Expected behavior

It should work normally.

## Actual behavior

In a notebook, if I import any module and try to use it it just freezes the VSCode and during this time a single thread of my CPU is at 100% usage.  Everything is working perfectly in python .py files.

![Screenshot from 2022-05-14 20-28-42](https://user-images.githubusercontent.com/32363363/168437211-16fe949d-faa6-40a4-a871-ba316e51cbbc.png)

## Steps to reproduce:

-  Create a Jupyter Notebook.
-  Create a new Cell Import any module and run the cell.
-  Now create another Cell and try to use that module e.g. in my case I imported `torch` and when I try to use it, it just freezes the VSCode.

**Comment by MDSvensson** [comment] 2022-05-15 08:52
I have the exact same issue, running on ubuntu 20.04

**Comment by shah-xad** [comment] 2022-05-15 08:58
I have sorted out the issue, I just have to remove this from my settings  `"jupyter.pylanceHandlesNotebooks": true`.

**Comment by amunger** [comment] 2022-05-16 18:50
this sounds like https://github.com/microsoft/vscode-jupyter/issues/9936. Can you try rolling back the Pylance extension to 2022.4.3 or earlier and check if it still reproduces?

**Comment by amunger** [comment] 2022-05-16 18:51
duplicate of #9936

**Closed by amunger** 2022-05-16 18:51 UTC
Labels: bug, triage-needed
