### ISSUE TITLE
cannot switch kernel in vscode ipynb interface

### ISSUE THREAD

**Issue by lindacmsheard** [microsoft/vscode-jupyter#4147] opened 2020-12-04 10:30 UTC
## Environment data

-   VS Code version: **1.51.1**
-   Extension version (available under the Extensions sidebar): **v2020.11.371526539**
-   OS and version: **WSL v2 on Windows 10 Enterprise v20H2**
-   Python version (& distribution if applicable, e.g. Anaconda): **base WSL: python: 2.7.17 / python3: 3.6.9** 
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): **miniconda3 -> conda 4.9.2**
-   Relevant/affected Python packages and their versions: n/a
-   Relevant/affected Python-related VS Code extensions and their versions: **jupyter v2020.11.399280825**
-   Value of the `python.languageServer` setting: n/a

## Expected behaviour

Using the kernel selector in the top right of the notebook interface changes the kernel used by the notebook

## Actual behaviour

The kernel selector is stuck on on one of my conda kernels that I don't want.
In the notebook:
```
! which python
->  /home/user/miniconda3/envs/**wrongenv**/bin/python
```
where `wrongenv` is not the I've selected in the kernel selector (via Command Palette or via selector in the top right)

Also, wrongenv is not the same as my .vscode python.pythonPath setting, which is:
```
"python.pythonPath": "/home/user/miniconda3/envs/**rightenv**/bin/python",
```
and the vscode footer also shows **rightenv**, and is not affected by using the kernel switcher (not sure if that's intended)

## Steps to reproduce:

1. install miniconda3 in WSL (conda 4.9.2)
2. create environments with `conda create --name rightenv|wrongenv python=3.6|3.8`
3. `conda install jupyter nb_conda` into the environments, to support working in the native jupyter interface by running `jupyter notebook` from the command line (I want to keep this capability)
4. open a notebook in vscode (with python extension)
5. try to switch between the kernels in the vscode notebook interface
6. diagnose with `!which python` in the notebook

## Things tried:
**Extension review**
- uninstalled and reinstalled python extension and jupyter extension
-> can end up on rightenv, but then can't switch out of that - similarly stuck

**Starting vscode**
- started from WSL bash with `code .` with and without first setting the conda envrionment (conda activate rightenv)

**.vscode**
- verified settings.json - tried:
```
{
    "python.pythonPath": "/home/user/miniconda3/envs/rightenv/bin/python",
}
```
and
```
{
    "python.condaPath": "/home/lisheard/miniconda3/condabin/conda",
    "python.pythonPath": "/home/lisheard/miniconda3/envs/rightenv/bin/python",
    "jupyter.jupyterServerType": "local"
}
```

## Things noted:

In the drop down that the kernel switcher gives me, each entry has a name and a path. 
- The name is `Python 3` for several different kernels (this is different from the vscode 'select interpreter path interface, where each kernel has a detailed name, for example `Python 3.7.4 64-bit ('rightenv': conda )`

When comparing to `conda env list`
- There is a duplicate entry in the kernel selector (but not in the vscode interpreter selector)
- There is a missing entry in the kernel selector (but not in the vscode interpreter selector)

**Comment by joyceerhl** [comment] 2020-12-08 05:20
Thanks for the detailed info @lindacmsheard. We can repro this issue. (@rchiodo I can repro this occasionally on my Mac as well, no solid repro yet though). Will investigate, thank you for the bug report!

**Comment by greazer** [comment] 2020-12-10 21:21
@lindacmsheard, we have had similar reports of this problem. See https://github.com/microsoft/vscode-jupyter/issues/4011. Can you try installing the VS Code insiders build? We have had reports that this situation is resolved in the latest builds of VS Code. Closing for now as a dupe of 4011.

**Closed by greazer** 2020-12-10 21:21 UTC
