### ISSUE TITLE
data view error

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode-jupyter#9013] opened 2022-02-12 12:34 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

~~~
# %%
from sympy import symbols
import numpy as np
x, y, z = symbols("x,y,z")
site0=np.array([[x],[y],[z]])

~~~

When I use the data view for site0, jupyter extension report the error.

![image](https://user-images.githubusercontent.com/82581024/153711363-94502fc8-4924-40ad-a018-6b3766060d20.png)

### VS Code Version

版本: 1.64.2 (user setup) 提交: f80445acd5a3dadef24aa209168452a3d97cc326 日期: 2022-02-09T22:02:28.252Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19043

### Jupyter Extension Version

v2022.1.1001821375

### Jupyter logs

```shell
Warn 20:31:08: DataScience Error [Error: 变量提取失败：
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
f:\大学资料\数学建模\2021年赛题\A题\程序(Python重写)\第二问\solve2_1.py in <module>
      1 import builtins
----> 2 builtins.print(_VSCODE_getDataFrameRows(site0, 0, 3))

f:\大学资料\数学建模\2021年赛题\A题\程序(Python重写)\第二问\solve2_1.py in _VSCODE_getDataFrameRows(df, start, end)
    154     except:
    155         pass
--> 156     return _VSCODE_pd_json.to_json(None, df, orient="split", date_format="iso")
    157 
    158 

D:\Program Files\Python39\lib\site-packages\pandas\io\json\_json.py in to_json(path_or_buf, obj, orient, date_format, double_precision, force_ascii, date_unit, default_handler, lines, compression, index, indent, storage_options)
    111         raise NotImplementedError("'obj' should be a Series or a DataFrame")
    112 
--> 113     s = writer(
    114         obj,
    115         orient=orient,

D:\Program Files\Python39\lib\site-packages\pandas\io\json\_json.py in write(self)
    173     def write(self):
    174         iso_dates = self.date_format == "iso"
--> 175         return dumps(
    176             self.obj_to_write,
    177             orient=self.orient,

OverflowError: Maximum recursion level reached
	at m.extractJupyterResultText (c:\Users\thinkpad\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001821375\out\client\extension.js:51:581892)
	at m.deserializeJupyterResult (c:\Users\thinkpad\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001821375\out\client\extension.js:51:582010)
	at m.getDataFrameRows (c:\Users\thinkpad\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001821375\out\client\extension.js:51:579043)
	at async r.getRows (c:\Users\thinkpad\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001821375\out\client\extension.js:66:1094165)
	at async c:\Users\thinkpad\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001821375\out\client\extension.js:66:1086847
	at async E.wrapRequest (c:\Users\thinkpad\.vscode\extensions\ms-toolsai.jupyter-2022.1.1001821375\out\client\extension.js:66:1087141)]
```

**Comment by DonJayamanne** [comment] 2022-12-08 00:15
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5551

**Closed by DonJayamanne** 2022-12-08 00:15 UTC
Labels: bug, data-viewer
