### ISSUE TITLE
jupyter code auto completion accompanies double module name occurence

### ISSUE THREAD

**Issue by jiewangjs** [microsoft/vscode-jupyter#6773] opened 2021-07-23 11:30 UTC
## Environment data

-   VS Code version: vscode insider, 1.59.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1055544705
-   Python Extension version (available under the Extensions sidebar): no
-   OS (Windows | Mac | Linux distro) and version: win
-   Python and/or Anaconda version: anaconda python 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | remote

![k34FXBX1JA](https://user-images.githubusercontent.com/11204422/126775691-c7bc1a92-28f9-4dec-9cc0-2356c56b21d6.gif)

**Comment by claudiaregio** [comment] 2021-07-23 17:34
Closing as dupe of https://github.com/microsoft/vscode-jupyter/issues/5956

**Closed by claudiaregio** 2021-07-23 17:34 UTC
Labels: bug, needs-triage
