### ISSUE TITLE
Specify python.tensorBoard.logDirectory for each workspace

### ISSUE THREAD

**Issue by hukz18** [microsoft/vscode-jupyter#8226] opened 2021-08-23 03:15 UTC
Currently, vscode provides a setting option 'python.tensorBoard.logDirectory' for its integrated tensorboard service to launch from. However, this setting item seems only effective in the user setting file but not the workspace settings(it doesn't work when adding 'python.tensorBoard.logDirectory' item to the workspace setting.json, a popup asking launch place for tensorboard still shows up, or am I getting something wrong?). I think it's a common demand to specify a log directory for each workspace, please consider this feature to make vscode's tensorboard experience more fluent.

**Comment by rchiodo** [comment] 2021-11-10 19:07
Dupe of #8225

**Closed by rchiodo** 2021-11-10 19:07 UTC
Labels: needs-triage
