### ISSUE TITLE
Interactive window makes cell markers disappear when a cell doesn't run

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6418] opened 2021-06-29 18:25 UTC
Testing microsoft/vscode#127378

Open python file
Add cell marker
Execute cell

Execution is failing for me because of this error:
https://github.com/microsoft/vscode/issues/127525

But then cell markers disappear?

![image](https://user-images.githubusercontent.com/19672699/123848461-99c9cf80-d8cc-11eb-9c83-91cfd7323a69.png)

**Comment by rebornix** [comment] 2021-06-30 19:51
I'm seeing the same with webview interactive window.

**Comment by joyceerhl** [comment] 2021-07-29 17:25
Probably a dupe of https://github.com/microsoft/vscode-jupyter/issues/6882

**Closed by joyceerhl** 2021-07-29 17:25 UTC
Labels: bug, interactive-window, unreleased
