### ISSUE TITLE
Newest Jupyter extention, downloaded manually, does not support newest VSCode

### ISSUE THREAD

**Issue by gshigin** [microsoft/vscode-jupyter#15800] opened 2024-06-26 09:12 UTC
## Environment data

-   VS Code version: 1.90.2
-   Jupyter Extension version : v2024.6.2024062401
-   Python Extension version : v2024.9.2024062507

## Expected behaviour

The extension should be successfully installed

## Actual behaviour

Getting error : "Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.90.2'."

## Steps to reproduce:

1. Get newest VSCode (version above)
2. Get newest Jupyter Extention (version above) by dowloading extention file
3.  Try installing extention from file

## Logs

It seems like Jupyter extention requires a vscode version that does not exist yet. `packe.json` under engines has line  `"engines":{"vscode":"^1.91.0"} ...`, but at the moment of writing this issue last availible version of VSCode is 1.90.2

</p>
</details>

**Comment by DonJayamanne** [comment] 2024-06-27 00:29
Duplicate of https://github.com/microsoft/vscode/issues/210912

**Closed by DonJayamanne** 2024-06-27 00:29 UTC
Labels: bug, triage-needed
