### ISSUE TITLE
Jupyter Variables data viewer cannot view data

### ISSUE THREAD

**Issue by phgmacedo** [microsoft/vscode-jupyter#10998] opened 2022-08-01 14:32 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

DataViewer does not allow users to inspect dictionary of objects. 

I have the following structure:
![d1](https://user-images.githubusercontent.com/92439290/182170442-b8f16ced-e407-439b-9547-ec1477d6f183.png)

When I try to inspecct it in the Jupyter Variables data viewer, I get these two rows with contents [object Object]. I can't click in the objects to inspect more, and a lot of information is missing. 

![d2](https://user-images.githubusercontent.com/92439290/182172655-797c9bf9-ac9f-43f4-9c50-1f474b90fe0e.png)

Here is what the Jupyter Variables panel can show for the same object:

![d3](https://user-images.githubusercontent.com/92439290/182172865-6134dcd9-9f74-466e-9921-5ee2f6911dbd.png)

### VS Code Version

Version: 1.69.2 (user setup) Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a Date: 2022-07-18T16:12:52.460Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2022.6.1201981810

**Comment by phgmacedo** [comment] 2022-08-01 14:34
Relevant issues: 
https://github.com/microsoft/vscode-jupyter/issues/1148

**Comment by phgmacedo** [comment] 2022-08-01 14:43
With the upvotes from #1148 and #1138 it would be enough to make this issue the third most requested feature.

**Comment by DonJayamanne** [comment] 2022-08-01 21:33
Thanks for filing this issue, as you have mentioned we have a few similar issues.
Hence closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/1138

**Closed by DonJayamanne** 2022-08-01 21:33 UTC
Labels: bug, triage-needed

**Comment by phgmacedo** [comment] 2022-08-01 22:49
Of course it is marked as complete 🤣

**Comment by DonJayamanne** [comment] 2022-08-01 23:13
> Of course it is closed as completed 🤣

Just to clarify, I've only closed this as its a duplicate and its not marked as `completed`.

**Comment by phgmacedo** [comment] 2022-08-01 23:15
maybe I’ve read something wrong 

![993B7BBC-584E-42EF-AF19-B78FAD987687](https://user-images.githubusercontent.com/92439290/182260740-0d2b4b98-7a5f-4491-9ec1-b4360caaf1a9.jpeg)

**Comment by DonJayamanne** [comment] 2022-08-02 16:01
Please check my comments here when the issue was closed https://github.com/microsoft/vscode-jupyter/issues/10998#issuecomment-1201745978, 

The message `closed this as completed` is a message from Github, you might want to file an issue on their repo if you're not happy with the messaging from them.
