### ISSUE TITLE
MRU kernel picker won't open existing servers list

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12637] opened 2023-01-24 22:59 UTC
It may be because I ran the `Jupyter: Clear remote server list` command. Now I can't use the remote picker at all

**Comment by amunger** [comment] 2023-01-24 23:00
![remotePicker](https://user-images.githubusercontent.com/2019016/214440104-55181c4d-73ad-4985-b5af-f4eba2ff9b00.gif)

**Comment by amunger** [comment] 2023-01-24 23:07
I had to change to kernel picker: all to be able to use the `Jupyter: Specify Jupyter Server for Connections` command since it doesn't seem to be available with MRU kernel picker

**Comment by DonJayamanne** [comment] 2023-01-24 23:59
Solution: We should hide the command `upyter: Clear remote server list` when using the new Kernle picker
@amunger in the mean time, can you change the kernel picker to stable (not MRU) and clear your list of remotes and try
If that still fails, then please try using the command `Jupyter (dev): Clear Cache` (you might want to enable the setting `"jupyter.development": true,` in your user settings file)

**Comment by DonJayamanne** [comment] 2023-01-25 00:00
Solution for this issue: We should hide the command `upyter: Clear remote server list` when using the new Kernle picker

**Comment by amunger** [comment] 2023-02-10 23:27
This is happening again without having run the now hidden command, even after running the clear cache and remote server list commands. Only happens with a IW that has an owning resource though, so maybe has to do with the resource being a .py file?

1. open a .py file and add a cell

```
# %%
print(1)
```

3. run the cell to open an IW
4. click the kernel picker and try to get to the remote list
🐛 gets stuck in the same place as the gif above

**Comment by DonJayamanne** [comment] 2023-02-10 23:42
@rebornix  looks like your recent fix might be missing some scenarios

**Comment by rebornix** [comment] 2023-02-11 00:32
@DonJayamanne this is different. The "Existing Jupyter Server" option quits at the very first step as it doesn't find any notebook. Not sure how it's working before in IW scenario as we are not passing in notebook as arguments https://github.com/microsoft/vscode-jupyter/blob/ea866515227bab0dfbaa202d9cd9c2676978828c/src/notebooks/controllers/kernelSource/kernelSourceCommandHandler.ts#L201. 

Maybe we regressed with the update of `acitveNotebookEditor` when focusing Interactive Window.

**Comment by DonJayamanne** [comment] 2023-02-13 00:00
> Maybe we regressed with the update of acitveNotebookEditor when focusing Interactive Window.

Yup, sounds like it, 
if its not provided we access it from `window.activeNotebookEditor?.notebook` and if thats empty, then that means there's no notebook,
& if we believe thats incorrect (for IW), then the problem is certainly with the core API.

**Comment by rebornix** [comment] 2023-02-13 19:40
Nailed it down and it's pretty interesting that how all components are behaving as expected but at the end lead to this bug

* We register kernel source actions for Interactive Window, and since they are all dynamic, we reuse the same command but different command args, e.g.,
```
command: {
    command: 'jupyter.kernel.selectJupyterServerKernel',
    arguments: [provider.id],
    title: provider.displayName ?? provider.id
}
```
* When users pick an item on the kernel source list, we will run the command, with either the provided args (shown above), or the active notebook document the current editor is attached to
* Since we already provide command args, the `[provider.id]` will be passed in, instead of the attached notebook document
* When we now handle this in `jupyter.kernel.selectJupyterServerKernel`, we will check `window.activeNotebookEditor?.notebook`.

This works well if the IW editor is focused, however if users move their focus into the python file, then `window.activeNotebookEditor?.notebook` will be undefined.

**Comment by rebornix** [comment] 2023-02-24 17:46
Reopening and moving to March as @amunger can reproduce this still. Will need his latest reproduce steps to continue troubleshooting.

**Closed** 2023-02-24 17:57 UTC
Labels: bug, verified, notebook-kernel-picker
