### ISSUE TITLE
Pressing enter in both *Select Interpreter to start Jupyter server* and *Specify local or remote Jupyter server for connections* is being ignored

### ISSUE THREAD

**Issue by 205g0** [microsoft/vscode-jupyter#4037] opened 2020-11-27 14:01 UTC
## Environment data

-   VS Code version: 1.5.1.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.11.372831992
-   Python Extension version (available under the Extensions sidebar): v2020.11.371526539

-   OS (Windows | Mac | Linux distro) and version: Windows 2004
-   Python and/or Anaconda version: 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: N/A

## Expected behaviour

Pressing enter in both *Select Interpreter to start Jupyter server* and *Specify local or remote Jupyter server for connections* takes my remote URI.

## Actual behaviour

Pressing enter in both *Select Interpreter to start Jupyter server* and *Specify local or remote Jupyter server for connections* is being ignored and the input box stays open.

## Steps to reproduce:

Open Command Palette search for commands above, enter some URI and try to press enter.

## Logs

No output in output panel.

**Comment by 205g0** [comment] 2020-11-28 04:49
Ok, this seems to be broken to the ground hurting the overall UX.

I found following workaround for others driving by and as a note for myself since getting it up and running is complicted:

1. Start your local Jupyter, even if you don't need it, you need it to be there just to get started
2. Look that default interpreter and server are set to local ones using the command palette menu
3. Run a random code piece, so that the interactive tab opens and runs the code locally, doesn't matter if the code works, in my case usually some libs are missing I have on my server
4. In the interactive tab click on the Jupyter server info top right and **only there and ***NOT*** in the command palette**
5. Set the remote server and enter should hopefully work this time

**Comment by claudiaregio** [comment] 2020-11-30 01:05
Hi @205g0, I am not able to reproduce this issue at this time. Could you please provide a gif showing us what is happening? 
If you need a tool, ScreenToGif works pretty well. https://www.screentogif.com/

**Comment by greazer** [comment] 2020-12-01 00:10
We think this is probably a VS Code issue.

**Comment by rebornix** [comment] 2020-12-01 20:03
@205g0 when you run into this issue next time, could you please run a troubleshooting command "Developer: Toggle Keyboard Shortcuts Troubleshooting" and then repeat the * Select Interpreter* steps again, and lastly share the log from the outputs panel? This can help us understand which component is hijacking the `enter` key.

**Comment by markushi** [comment] 2020-12-04 07:35
The same issue is happening to me as well. After some trial and error I found out that the extension tries to write `"jupyter.jupyterServerType": "remote"` to `.vscode/settings.json` but fails when no workspace is open.

Workaround: Open a workspace/folder first

If you need any more details, just let me know.

**Comment by edofullin** [comment] 2020-12-04 08:03
I had the same issue as well, the problem turned out to be that the OS I was using (Linux Manjaro KDE) did not have Gnome Keyring installed (ofc it doesn't, it's KDE) and that seems to be a required package.

**Comment by 205g0** [comment] 2020-12-05 05:43
Thanks for looking into this and apologies for my late reply. I couldn't reproduce my issue anymore. Now, I can directly open the select remote server dialogue, click existing, add my server URI and press enter. Feel free to close this issue, I will observe this and come back with more info if I encounter this problem again.

**Comment by IanMatthewHuff** [comment] 2020-12-17 19:41
Moving this back to new triage as info has been provided. Sorry about the issue here, but a fix might be a bit slow coming as most of the team is out over the holidays.

**Comment by joyceerhl** [comment] 2021-01-12 19:32
Validated. For 'Select Interpreter to start Jupyter server' and 'Specify local or remote server for connections', hitting enter with a quickpick item selected results in that selection being taken and advancing to the next step in the multistep quickpick.

**Closed by joyceerhl** 2021-01-12 19:32 UTC
Labels: bug

**Comment by gitony0101** [comment] 2021-03-27 03:42
> The same issue is happening to me as well. After some trial and error I found out that the extension tries to write `"jupyter.jupyterServerType": "remote"` to `.vscode/settings.json` but fails when no workspace is open.
> 
> Workaround: Open a workspace/folder first
> 
> If you need any more details, just let me know.

yep I made it by changing but idw how it works
