### ISSUE TITLE
Always create terminals when closing interactive window

### ISSUE THREAD

**Issue by DoctorAnonymous** [microsoft/vscode-jupyter#10101] opened 2022-05-23 07:11 UTC
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Always create a new terminal when closing the interactive window.

## Steps to reproduce:

I installed miniconda3 and set conda in my PATH environment. I run python3 from conda in the interactive window well but when I close the interactive window, vscode creates a new terminal and run "conda activate base" automatically. Kindof annoying.

Thank you for reading.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• autopep8Args: "<placeholder>"

```

</p>
</details>

Extension version: 2022.6.2
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.19GB free)|
|Process Argv|--crash-reporter-id ee79adf4-36af-4e85-afb4-3fbd729a9ecb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

**Comment by rchiodo** [comment] 2022-05-23 20:14
Dupe of #10053

**Closed by rchiodo** 2022-05-23 20:14 UTC
Labels: triage-needed
