### ISSUE TITLE
execute cell and focus container on a markdown cell, then command mode shortcut doesn't work

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode-jupyter#12878] opened 2023-02-20 07:07 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

This issue makes a third "mode": looks like command mode but all shortcuts don't work.

- create an arbitrary markdown cell, and use `execute cell and focus container` to run it
- now it looks like (and should be) in command mode
- press arbitrary command mode shortcut, `a, b, dd, x`, which should take effect, but nothing happens
- use up/down arrow key to select other cell, then try to use command mode shortcut - doesn't work
- single left click makes it really into command mode, and shortcut works.
- another way of exiting such a "mode" using keyboard only: select a code cell, execute it with `execute cell and focus container`.

### VS Code Version

1.75.1

### Jupyter Extension Version

2023.1.2010391206

### Jupyter logs

```shell
(nothing there)
```

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment] 2023-02-21 19:47
duplicate of https://github.com/microsoft/vscode-jupyter/issues/12738, although I didn't realize that all commands were disabled.

**Closed by amunger** 2023-02-21 19:47 UTC
Labels: bug
