### ISSUE TITLE
Cannot enter code in the interactive window (with pseudo-notebooks)

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-jupyter#1113] opened 2020-11-13 15:49 UTC
Issue Type: <b>Bug</b>

When editing a python file with notebook-like cells (# %%), when I click on "run cell"  it properly splits the editor, opens an interactive IPython (notebook? not sure about the difference) intance to the right, and executes my cell in it. However I am unable to interact with that notebook: I can click on the input at the bottom of the notbook that says "Type code here and press shift-enter to run", but nothing happens when I type.

I found this post on Reddit that mentions the same issue: https://www.reddit.com/r/vscode/comments/i45agt/cannot_type_code_into_python_interactive_console/

And indeed, if I move the tab around, it's then possible to add input. 

Let me know if you need more info.

Extension version: 2020.11.358366026
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:16:10.374Z)
OS version: Linux x64 5.4.74-1-lts

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (16 x 3172)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|31.37GB (2.32GB free)|
|Process Argv|. --no-sandbox --crash-reporter-id 66ea3ec9-05eb-4edd-8d35-34bbe6c1aba1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/local/share/xsessions/plasma-i3|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE-i3|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by greazer** [comment] 2020-11-17 08:35
Dupe of #446

**Closed by greazer** 2020-11-17 08:35 UTC
