### ISSUE TITLE
Suggestion: Let me share a kernel with another notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4549] opened 2021-01-28 19:19 UTC
When coding with python or any other language I'm not limited to one file for interacting with the final executable.

It would be great if we could make it easier to share a kernel between notebooks (one suggestion, just list notebook names in the kernel dropdown list)

**Comment by rchiodo** [comment] 2021-01-29 20:12
I also want to start the interactive window from a python file but then pick the kernel of a notebook.

Use case:

Working on a notebook that uses python files as imports. Want to try out the imports as I write them but without messing with notebook. But then by using the same kernel, the new imports just end up automatically in the notebook as I update them. It's like another way to reimport a module.

**Comment by DonJayamanne** [comment] 2021-10-19 17:43
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1516

**Closed by DonJayamanne** 2021-10-19 17:43 UTC
Labels: enhancement, notebook-kernel
