### ISSUE TITLE
Fails to load html scripts, works in lab, not in vscode and jupyter notebook

### ISSUE THREAD

**Issue by tony-maynard** [microsoft/vscode-jupyter#11110] opened 2022-08-12 11:36 UTC
## Environment data

-   VS Code version: 4.5.1 (and below)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001610507
-   Python Extension version (available under the Extensions sidebar): v2022.12.0
-   OS (Windows | Mac | Linux distro) and version: Linux 
-   Python and/or Anaconda version: Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Would be able to interact with d3

## Actual behaviour

Error in console saying d3 is not defined.

## Steps to reproduce:

Copy and paste the below code into a cell to run:
```
from IPython.display import HTML

HTML(''' 
<html>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <body>
      <script>
d3.select("body").append("p").text("Hello World!");
</script>
</body>
</html>
''')
```

## Screenshots 
Both are running on the same server with same dependencies installed 
<img width="894" alt="Screenshot 2022-08-12 at 12 29 43" src="https://user-images.githubusercontent.com/85884885/184346272-f19731cd-41ea-481e-a4a8-f3b04f3b4406.png">
<img width="1347" alt="Screenshot 2022-08-12 at 12 30 24" src="https://user-images.githubusercontent.com/85884885/184346280-35c8a32d-be44-4f86-8733-2d28f15ca482.png">

**Comment by amunger** [comment] 2022-08-12 15:39
Using the same jupyter server doesn't actually mean that the same kernel is being used, and it looks like you may be using a different one in each case:
![image](https://user-images.githubusercontent.com/2019016/184390187-ed579023-7523-404f-ba8c-9a346d325747.png)

Can you run this cell in each notebook to check if they are pointing to the same executable:

```
import sys
print(sys.executable)
```

**Comment by tony-maynard** [comment] 2022-08-12 15:46
>
> 
> Can you run this cell in each notebook to check if they are pointing to the same executable:
> 
> ```
> import sys
> print(sys.executable)
> ```

Hey @amunger, they both return `/opt/conda/envs/sig-env/bin/python`. We set it in vscode using `python.defaultInterpreterPath`

**Comment by amunger** [comment] 2022-08-12 17:09
Did you need to install something to get it to work in the top screenshot? Is that jupyter lab?
I'm getting the same uncaught reference error in both Jupyter notebooks and lab.

**Comment by tony-maynard** [comment] 2022-08-15 12:42
@amunger I think we needed to install https://github.com/jupyter-widgets/ipywidgets within jupyter lab which looks like what this tries to describe https://github.com/microsoft/vscode-jupyter/wiki/Component:-IPyWidgets ?

**Comment by DonJayamanne** [comment] 2022-08-17 19:03
@tony-maynard thanks for checking JupyterHub, I can confirm I'm getting the exact same behaviour in Jupyter Notebook as well, hence this is not specific to VS Code.
As a result I'm going to close this issue as the expected behaviour (as you have identified its due to the async nature of loading the scripts)

**Comment by tony-maynard** [comment] 2022-08-18 08:20
> @tony-maynard thanks for checking JupyterHub, I can confirm I'm getting the exact same behaviour in Jupyter Notebook as well, hence this is not specific to VS Code. As a result I'm going to close this issue as the expected behaviour (as you have identified its due to the async nature of loading the scripts)

I was highlighting it works on jupyterHub once the script is fetched, but it still doesn't work on vscode so I think this should be re opened?

**Comment by DonJayamanne** [comment] 2022-08-22 01:14
Hmm, I've just tested this again in Jupyter NOtebook and as you can see, this doesn't work at all in Jupyter Notebooks, no matter how many times I run the cell.
Not, sure what Jupyter Hub is doing, but I'm going to close this issue as it doesn't work in Juptyer Notebooks, hence if it doesn't work in VS Code as well, then I think thats expected (i.e. doesn't need to be addressed).

![Recording 2022-08-22 at 11 12 32](https://user-images.githubusercontent.com/1948812/185820498-c9182bec-89f7-46d1-a28f-1054d32b2e2c.gif)

**Comment by tony-maynard** [comment] 2022-08-22 08:55
@DonJayamanne Can you tell me how you're running Jupyter? With this `docker-compose.yaml` file I get the following 
```yaml
services:
  jupyter:
    image: jupyter/base-notebook:latest
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
```
<img width="1009" alt="Screenshot 2022-08-22 at 09 54 37" src="https://user-images.githubusercontent.com/85884885/185881375-19cb6253-457d-4e74-a3ee-ca6fbfe629c0.png">

**Comment by DonJayamanne** [comment] 2022-08-22 09:49
looks like you are using jupyter lab.
will check this out tomorrow

**Comment by DonJayamanne** [comment] 2022-08-24 18:17
I'm sorry, but I've tried instlalling the very latest versions of Jupyter Notebook and Jupyter lab manually using pypi and can replicate the same exact problem.
I've tried the docker file you have provided and can repro this there as well, 
Jupyter Lab doesn't work for me in the container you have provided.
Either way, if you were to ignore the above docker file and just install this manually from pypi you can replicate this exact same problem as I can.

I've also tried this in a new Python environemtn as well as we a new Windows machine and same issue.
I'm closing this issue as this is how it behaves in Jupyter Notebook and Lab, at least the very latest builds that I'm looking at.

**Closed by DonJayamanne** 2022-08-24 18:17 UTC
Labels: bug, triage-needed
