### ISSUE TITLE
Tensorboard integration cannot see the needed packages in any conda env on a remote host

### ISSUE THREAD

**Issue by munael** [microsoft/vscode-jupyter#11209] opened 2022-08-26 14:47 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
Using the "launch tensorboard" command gives me options to launch a tensorboard session from a specific directory.

What actually happens is this error:
![image](https://user-images.githubusercontent.com/5769148/186931603-db7153aa-c4bf-4271-af73-e0ee30b26499.png)

Even though the minimum needed versions are installed on all conda envs on the machine, and seen by the command logged in the Output pane.

Running it manually gives:
```
$ conda run -n dev --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py -c "import tensorboard; print(tensorboard.__version__)"
>>>PYTHON-EXEC-OUTPUT
2.4.1
<<<PYTHON-EXEC-OUTPUT
$ conda run -n dev --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py -c "import torch_tb_profiler; print(torch_tb_profiler.__version__)"
>>>PYTHON-EXEC-OUTPUT
0.4.0
<<<PYTHON-EXEC-OUTPUT
```

## Steps to reproduce:

1. Run from a remote environment.
1. Choose the "launch tensorboard" command.
2. Get the error asking to install the correct versions.
3. Click the button to install them.
4. Retry. Still doesn't work.
5. If instead you run tensorboard manually by `tensorboard --logdir $logdir` then open the UI locally via the forwarded port, it works. Opens fine in the local browser and shows everything.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Experiment 'pythonaacf' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonInterpreterInfoUnpinned' is active
LSP Notebooks experiment is disabled -- not in treatment group
LSP Notebooks interactive window support is disabled -- not in LSP Notebooks experiment
> conda info --json
Python interpreter path: /opt/conda/envs/dev/bin/python
[ERROR 2022-7-26 14:37:44.457]: Failed to initialize source map support in extension
> /bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/interpreterInfo.py
> /bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/interpreterInfo.py
> /usr/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/interpreterInfo.py
> /usr/bin/python3 ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/interpreterInfo.py
> /opt/conda/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/interpreterInfo.py
> conda run -n dev --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/printEnvVariables.py
> /opt/conda/envs/dev/bin/python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/interpreterInfo.py
Starting Pylance language server.
> conda run -n dev --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py -c "import tensorboard; print(tensorboard.__version__)"
> conda run -n dev --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py -c "import torch_tb_profiler; print(torch_tb_profiler.__version__)"
> conda run -n dev --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py -c "import tensorboard; print(tensorboard.__version__)"
> conda run -n dev --no-capture-output python ~/.vscode-server-insiders/extensions/ms-python.python-2022.13.12381007/pythonFiles/get_output_via_markers.py -c "import torch_tb_profiler; print(torch_tb_profiler.__version__)"
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```
Multiroot scenario, following user settings may not apply:

languageServer: "Pylance"

terminal
• activateEnvironment: false

```

</p>
</details>

Extension version: 2022.13.12381007
VS Code version: Code - Insiders 1.71.0-insider (1a582f7c079d1eb4c89d4f637da2fc2fcb688b31, 2022-08-15T05:17:18.259Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.0.0-1032-azure

**Comment by DonJayamanne** [comment] 2022-08-29 20:23
Duplicate of https://github.com/microsoft/vscode-python/issues/19591

**Closed by DonJayamanne** 2022-08-29 20:23 UTC
Labels: specific-to-package-library, triage-needed
