### ISSUE TITLE
using 'run cell' on a cell which has indentation produces indentation error

### ISSUE THREAD

**Issue by vttrifonov** [microsoft/vscode-jupyter#10443] opened 2022-06-13 21:06 UTC
Executing indented python code, for example,

    #%%
        a = 1

by clicking on 'Run cell' above #%%  produces `IndentationError: unexpected indent`. This snipped/cell is part of a control statement (if/then) and hence the indentation is required, but I just want to execute this piece (or a much more complicated version of it) in the interactive python shell by using the 'run cell' feature. This used to work, so there must be some update that happened which prevents this from working...  My current version of the python extension is v2022.8.0. Please, bring this back if possible. I thought it was very useful.

**Comment by rchiodo** [comment] 2022-06-14 15:59
Thanks for the issue. Yeah I believe this used to work but recent changes have stopped removing extra indentation.

**Comment by amunger** [comment] 2022-06-17 22:14
as a workaround, the cell should still run successfully if the marker has the same indentation as the next line:
```
    # %%
    a = 1
```

**Comment by amunger** [comment] 2022-06-21 16:01
caused by providing a code override to execute the cell https://github.com/microsoft/vscode-jupyter/commit/e2ccb635ed3cd61639bd1eb30eacc8e261127da5

**Comment by vttrifonov** [comment] 2022-06-21 17:46
Thanks for the workaround. I can work with this although it will still be nice to have the original situation, if possible, as it makes things simpler (one less thing to remember :-)). As a note, I am pretty sure I tried this, but did not have the space after # so it did not work and I dropped it.

**Comment by pgA3D** [comment] 2022-07-15 12:05
Thanks for the work around. I also tried it once I got the indentation error and did not find the correct syntax, since it is not very intuitive. 

This is not working
`    #%%
    a = 1`

This is not working
`    # %% My Comment
    a = 1`

**Comment by pgA3D** [comment] 2022-07-15 12:11
Thanks for the work around. I also tried it once I got the indentation error and did not find the correct syntax, since it is not very intuitive. 

This is not working
```
    #%%
    a = 1
```

This is also not working
```
    # %% My Comment
    a = 1
```

**Comment by Puco4** [comment] 2022-07-15 12:14
In case it helps someone, the workaround I'm using is:
```
#%%
if True:
         a = 1
```

**Comment by EricThomson** [comment] 2023-06-07 20:39
The workaround works 👍 , but makes it a harder to read ( have to inspect code more closely the cells don't jump out as much).

**Comment by amunger** [comment] 2023-12-07 19:43
closing as duplicate of https://github.com/microsoft/vscode-jupyter/issues/13065#issuecomment-1631720005, which has a good breakdown cases that we should support.

**Closed by amunger** 2023-12-07 19:43 UTC
Labels: bug
