### ISSUE TITLE
2.x python kernel suggested but no longer supported

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#10619] opened 2022-06-28 17:45 UTC
Testing #10590

I never know which kernel to pick either 🤷🏼‍♀️
<img width="811" alt="Screen Shot 2022-06-28 at 1 44 08 PM" src="https://user-images.githubusercontent.com/29464607/176248611-976c5568-98da-450f-b480-ee3c29c18514.png">

**Comment by IanMatthewHuff** [comment] 2022-11-04 17:01
Dupe of #11072

**Closed by IanMatthewHuff** 2022-11-04 17:01 UTC
Labels: bug, notebook-getting-started
