### ISSUE TITLE
Jupyter magic %%time prevents format cell (black)

### ISSUE THREAD

**Issue by lgonzalezsa** [microsoft/vscode-jupyter#13421] opened 2023-04-28 21:03 UTC
Type: <b>Bug</b>

Jupyter extension a notebook with a cell having `%%time` at first line of the cell, right click format cell.

Extension version: 2023.3.1201040234
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:52.732Z)
OS version: Linux x64 6.2.6-76060206-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|31.22GB (10.74GB free)|
|Process Argv|--unity-launch --crash-reporter-id b17934b6-16e0-4e3a-8b46-4af0ea75a7cf|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30672706
vsctsb:30705553
azdwalk:30721579
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by amunger** [comment] 2023-04-28 21:19
from what I can see, any cell magic will stop the cell from being formatted. We might need to pre and post processing to avoid trying to format cell magics

**Comment by DonJayamanne** [comment] 2023-04-28 21:33
This is an issue for python extension as they own the format providers

**Comment by FlorinAndrei** [comment] 2023-06-10 00:23
There are many issues that are caused by the iPython magics. E.g. this:

https://github.com/microsoft/vscode-jupyter/issues/11476

Is there a general solution to all these issues?

Is there something that needs to be done in other places / by other extensions?

**Comment by benlindsay** [comment] 2023-08-28 18:00
> There are many issues that are caused by the iPython magics

A summary of all the issues I see:

## Most syntax highlighting within the cell is broken

Without `%%time`:
![image](https://github.com/microsoft/vscode-jupyter/assets/9361152/fdcbca17-16eb-41f9-b15a-4f1622795d61)

With `%%time`:
![image](https://github.com/microsoft/vscode-jupyter/assets/9361152/d74508e2-543a-4859-be6f-43a6a529a40c)

## Module imports in other cells don't recognize usage in `%%time` cell

![image](https://github.com/microsoft/vscode-jupyter/assets/9361152/eef5b08d-82b3-4724-81f0-96a0466cc7a6)

## Black formatting silently fails

As mentioned in this issue

**Comment by turbotimon** [comment] 2024-04-22 11:03
This has been bothering me for a long time, is there an update or a workaround? Is this even a problem of vscode-jupyter and not of [python-language-server](https://github.com/microsoft/python-language-server)?

**Comment by DonJayamanne** [comment] 2024-12-16 21:40
Closing this issue as out of scope, as the tools that support formatting need to take the cell magics into account.
E.g. some language servers support magics, hence by the same token formatters too should support cell magics as this is a popular Jupyter feature.

**Closed by DonJayamanne** 2024-12-16 21:40 UTC
Labels: notebook-intellisense, feature-request, under-discussion
