### ISSUE TITLE
Cant connect to Jupyter Notebook remote

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#3926] opened 2020-11-16 17:57 UTC
@egorgam commented on [Sun Nov 15 2020](https://github.com/microsoft/vscode-python/issues/14737)

VSCode: 1.51.1
Pyhon plugin: v2020.11.358366026
OS: MacOS Big Sur 11.0.1 

Problem:
When I press Enter, there is no action and I cant connect to any url. I think some broke reactivity in plugin UI runtime.
![Screenshot 2020-11-16 at 00 00 37](https://user-images.githubusercontent.com/13712792/99196665-e0841280-279e-11eb-935a-d8b8e74ad172.png)

_Originally posted by @egorgam in https://github.com/microsoft/vscode-python/issues/14735#issuecomment-727636229_

**Comment by greazer** [comment] 2020-12-01 00:24
Dupe of #4037

**Closed by greazer** 2020-12-01 00:24 UTC
Labels: internal contributor
