### ISSUE TITLE
Support for ipypopout

### ISSUE THREAD

**Issue by mariobuikhuizen** [microsoft/vscode-jupyter#16251] opened 2024-11-26 15:15 UTC
Would it be possible to get [ipypopout](https://github.com/widgetti/ipypopout) working? It opens a new browser window, connects to the kernel it was opened from and shows the target widget.

https://github.com/widgetti/ipypopout/assets/1765949/430cae12-2527-404b-9861-610565ac1471

It would need the following:
- The server extension of [Voila](https://github.com/voila-dashboards/voila) _or_ a way to serve a static HTML file accessible by the opened browser window.
- Access the vscode-jupyter-kernel from the opened browser window.

Is this possible in vscode / vscode-jupyter?

**Comment by DonJayamanne** [comment] 2024-11-27 07:34
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1120

**Closed as completed by DonJayamanne** 2024-11-27 07:34 UTC
Labels: feature-request, triage-needed

**Comment by maartenbreddels** [comment] 2024-11-27 09:29
I'm not sure this is a duplicate. I think #1120 would require integration with the vscode interface (and seems difficult to do). For ipypopout we might be able to get this working ourselves if we know how to do both things Mario mentioned (serving assets, and find a way to connect to the kernel).

**Comment by DonJayamanne** [comment] 2024-11-28 03:40
> pypopout we might be able to get this working ourselves if we know how to do both things Mario mentioned (serving assets, and find a way to connect to the kernel).

> way to connect to the kernel).
Unfortunately there's no webserver nor that is served for an external browser window to connect to the kernel.

The only way to connect to the kernel is via some messaging api, and this will not be possible with external browser windows.
The only approach we have and plan on supporting is using a vs code window.
