### ISSUE TITLE
Endless loop for data viewer

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-jupyter#4367] opened 2021-01-13 13:31 UTC
loading a data frame of 1000 * 16, the blue bar is like forever.
The output csv of that data frame is 390K, I dont feel it will be too large?
![image](https://user-images.githubusercontent.com/8154646/104458428-56152f00-55e6-11eb-9e01-133bc4163008.png)

**Comment by rchiodo** [comment] 2021-01-13 17:44
Does it ever finish?

Something similar with random data takes about 5 seconds for me.

It might be that it's crashing and you didn't get or notice an error popup in the bottom right.

**Comment by Victsz** [comment] 2021-01-14 02:32
Does it ever finish? -> No
It might be that it's crashing and you didn't get or notice an error popup in the bottom right.  -> No popup, and after I click the 'x' on data viewer tab I can still execute python snippet.

VS code version 1.49.0
python extension v2020.12.424452561

**Comment by Victsz** [comment] 2021-01-14 02:39
Oh .. I found some clues.

The dataframe is  generated from groupby..

**Comment by rchiodo** [comment] 2021-01-14 17:13
Yes we don't support multiple dimension arrays at the moment.

**Comment by rchiodo** [comment] 2021-01-14 17:35
See this issue here where we're working on it:
https://github.com/microsoft/vscode-jupyter/issues/305

**Comment by greazer** [comment] 2021-09-09 20:10
Most likely this is a dupe of #7441

**Closed by greazer** 2021-09-09 20:10 UTC
Labels: bug, info-needed, needs-triage
