### ISSUE TITLE
"Executing cell" indicator is now gone 

### ISSUE THREAD

**Issue by akald** [microsoft/vscode-jupyter#7006] opened 2021-08-08 09:54 UTC
After the July 2021 update to VScode, it's no longer possible to tell what VScode is doing since the executing cell indicator in the bottom left is now gone. Unless I uncollapse the code every time in the interactive window, I have no idea if the Vscode interactive window is running anything or not.

**Comment by filipporemonato** [comment] 2021-08-09 13:52
I second this issue; After the July 2021 update the new interface for the Interactive Python has received a temendous blow.
- The "executing cell" indicator in the lower-left corner (in VSCode bar) is gone
- The "(busy)/(idle)" indicator that was in the upper-right corner next to the interactive window interpreter is gone
- The indicator next to each cell, that would go from an asterisx (*) during execution, to the cell number ( [n] ) after execution is also gone, and replaced by a weird-looking symbol I fail to understand what it represents.

The above 3 points make it impossible to know if the code is still running, or it has completed.

Additionally, it is now more cumbersome to delete executed cells, since one needs to expand the content of the cell before seeing the "x" to delete it. Moreover, when clicking on the "expand" symbol next to the cell, one is brought down at the end of the output, so to reach the "x" to delete the cell one has to scroll all the way back up. The same would happen for the "copy" or "go to code" buttons that are similarly hidden together with the "delete cell" until one exapands the code.

These changes severely impact the usability and friendliness of the interactive python window.

**Comment by sigbjorngrini** [comment] 2021-08-09 14:58
I am also having problems knowing whether my code is running.

There is a timer when you write in the console, but this indicator does not appear when using "Send Selection To Interactive Window".

![No_timer](https://user-images.githubusercontent.com/10991790/128727589-6b09463f-b80a-41b0-92a7-b7b733c01662.gif)

**Comment by greazer** [comment] 2021-08-09 18:25
This is a dupe of #6990. In the meantime you can expand all cells in the interactive window. 

Alternatively you can temporarily opt out of the new experience by setting 
```json
    "jupyter.enableNativeInteractiveWindow":false
```

**Closed by greazer** 2021-08-09 18:25 UTC
Labels: needs-triage
