### ISSUE TITLE
Command palette interrupt/restart not there for a python file

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#7158] opened 2021-08-16 21:08 UTC

**Comment by rchiodo** [comment] 2021-08-21 00:00
Was looking at this. Kinda confusing as there's more than one restart/interrupt.

```jupyter.notebookeditor.restartkernel``` is the one for notebooks, but is also now used in the new interactive window
```jupyter.restartkernel``` is the one we used to use for the interactive window (i think).

So the first one is probably the one to fix. The context is a little messy though. 

You'd need a file that's active that has code cells but there's also an IW open that's related to the code cells. At least to be completely correct.

**Comment by joyceerhl** [comment] 2021-08-21 00:17
The new interactive window does not use `jupyter.notebookeditor.restartkernel`: https://github.com/microsoft/vscode-jupyter/blob/add2eb6f3fddde47c123133a92f23d2a9d9b4216/package.json#L868-L883

**Comment by joyceerhl** [comment] 2021-08-21 00:20
These context keys aren't being properly set https://github.com/microsoft/vscode-jupyter/blob/add2eb6f3fddde47c123133a92f23d2a9d9b4216/package.json#L1192

**Comment by DonJayamanne** [comment] 2021-08-21 03:12
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/330
I have no idea why we never fixed any of them..

**Comment by rchiodo** [comment] 2021-08-30 16:42
I don't think this is fixed. Or at least it doesn't behave the way I would expect. 

![image](https://user-images.githubusercontent.com/19672699/131373854-e792fded-8cb5-4b9f-b4ba-c4344dfa9834.png)


Shows up even after closing the interactive window. I suppose that's better than it not being there.

Additionally if I have two IW's open, it's not clear which one it's going to restart. Additionally the restart doesn't put out the status message.

I think you enabled the wrong command? Well maybe. The other command might have had the restart message show up. At least it used to.

**Comment by joyceerhl** [comment] 2021-08-30 16:48
>  restart doesn't put out the status message.

The restart message shows up for me, and both the `jupyter.notebookeditor.restartkernel` and `jupyter.restartkernel` commands have the same shared command handler. Is there another command I should have looked at? https://github.com/microsoft/vscode-jupyter/blob/69fda26e079236e98e8aab580f27f2e36ef3ce53/src/client/datascience/jupyter/kernels/kernelCommandListener.ts

Which version of the Jupyter extension do you have? I'm on v2021.8.2031173646.

**Comment by rchiodo** [comment] 2021-08-30 16:50
This one:

Version: 2021.8.2031173646

No restart message shows up at all. Might be because of me not using ZMQ though. Let me check.

**Comment by rchiodo** [comment] 2021-08-30 16:51
No even with ZMQ enabled it fails to show a restart message. Even using the toolbar.

**Closed** 2021-08-30 16:59 UTC
Labels: bug, interactive-window, needs-triage, verification-needed, verified

**Comment by rchiodo** [comment] 2021-08-30 17:00
Restart message is a different issue.
