### ISSUE TITLE
Python inconsistent multiprocessing.Process behavior

### ISSUE THREAD

**Issue by IliasAarab** [microsoft/vscode-jupyter#15935] opened 2024-07-07 00:16 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.90.2 (user setup)
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:34:26.404Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
- OS Version: 
Windows_NT x64 10.0.22621
Steps to Reproduce:

running the below snippet as a Python file in the terminal or within a notebook cell works fine. But running the same snippet within an interactive window fails as the snippet fails to do anything:

```{python}
import multiprocessing
def fn():
    print("here")
process = multiprocessing.Process(target=fn, )
process.start()
process.join()
```

**Comment by IliasAarab** [comment] 2024-08-12 23:06
> Please can you try running the same code in Jupyter Notebook I tried running this against the latest version of Jupyter Lab and Jupyter Notebook and it fails there as well. I.e. it fails to work in Jupyter Lab, Jupyter Notebook and VS Code This looks very much like a duplicate of #12485
> 
@DonJayamanne thank you for the response. Yes you are right. Tested with Jupyter Notebook and Jupyter Lab, and can indeed confirm that the same failure happens as within VS Code Notebooks.  Interesting that everything seems to work fine on Google Colab though. 


> 
> > or within a notebook cell works fine. But running the same snippet within an interactive window fails as the snippet fails to do anything:
> 
> I think you meant it works in interactive window and fails in a notebook.

Yes, just tried again, and works in an interactive window but fails in a notebook. 


Two interesting things to note when it comes to the interactive window:

1. The code only executes properly when the main body is put below a `__main__` if block. Otherwise the file is never populated by the processes. Is this the expected behaviour? I am asking, as in Google Colab, both ways (with and without the `__main__` if statement) work as anticipated. 
2. The code only executes properly when the __file is saved before running the snippet__ in the interactive window, otherwise the same failure is observed as in the notebooks. This does not seem to be the expected behaviour, as other code snippets (not using `multiprocessing`) can be executed in the interactive window without the underlying file being saved.

**Comment by DonJayamanne** [comment] 2024-08-13 04:01
Thank you for getting back
Given this is an issue in Jupyter lab/notebook as well, I’m 
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/12485

As for 1 & 2 , I’m not sure what’s going on, given that this isn’t by design (ie we don’t deliberately try to make it not work)
Ie it’s trying to mimic what ever happens in Jupyter

**Closed by DonJayamanne** 2024-08-13 04:01 UTC
Labels: info-needed, notebook-kernel
