### ISSUE TITLE
KeyboardInterrupt interrupts my code on its own

### ISSUE THREAD

**Issue by f3ss1** [microsoft/vscode-jupyter#9671] opened 2022-04-12 17:06 UTC
## Environment data

-   Jupyter Extension version v2022.3.1000901801
-   Python Extension version v2022.4.1
-   Windows
-   Python 3.9.12
-   Conda
-   Jupyter server running: Local

I am using VSCode with Jupyter to train my ML models using Pytorch. Since 11.04.2022 the training loop for my model sometimes (it does not really make any kind of pattern) just stops with the "KeyboardInterrupt" Exception.

What I did try is simply removing my keyboard and mouse. That did not work and it was kind of funny to get the "KeyboardInterrupt" without even having a keyboard.

Somebody help as I am done with having 1 hour+ loops just breaking down without any real reasons.

**Comment by rchiodo** [comment] 2022-04-12 17:25
Thanks for the issue. 

Can you upload the contents of this output tab after reproing the issue?

![image](https://user-images.githubusercontent.com/19672699/163019368-c310797a-8966-41c7-accb-dc259524bda3.png)


That should show if we sent a keyboard interrupt or not. If we didn't then something in your code (or a module you're using) is sending it.

The callstack for the keyboard interrupt might indicate what sent it (which would show up in the error message for the cell).

**Comment by f3ss1** [comment] 2022-04-12 17:51
Please see the full log in the .txt file
[log.txt](https://github.com/microsoft/vscode-jupyter/files/8475339/log.txt)
.

**Comment by rchiodo** [comment] 2022-04-12 18:14
Thanks. That shows it is coming from VS code. The difficulty now is in figuring out from what. 

The log indicates it happened after 3 minutes? Is that consistent?

What other extensions do you have installed besides Jupyter and Python?

**Comment by f3ss1** [comment] 2022-04-12 19:18
1. It is not really consistent, I believe that seems to be random. I had the loop running for 70 mins+ and it was fine -- and then I sometimes had it broken after 3 mins.
2. There is a bunch of those, please see:
* Bracket Pair Colorizer 2
* Better C++ Syntax
* C/C++
* C/C++ Extension Pack
* C/C++ Themes
* CMake
* CMake Tools
* Code Runner
* Code Spell Checker
* Dracula Official
* GitLens — Git supercharged
* Jupyter
* LaTeX Utilities
* LaTeX Workshop
* Live Share
* MySQL
* Path Intellisense
* Pylance
* Python
* Remote - Containers
* Remote - SSH
* Remote - SSH: Editing Configuration Files
* Remote - WSL
* Russian - Code Spell Checker
* Visual Studio IntelliCode
* Visual Studio IntelliCode API Usage Examples
* vscode-icons

**Comment by rchiodo** [comment] 2022-04-12 19:27
Hmm, none of those seem like they'd send an interrupt command. 

The only way interrupt should happen is if the button is clicked then. You don't have any automation software running do you? Something that clicks buttons for you?

**Comment by f3ss1** [comment] 2022-04-12 19:35
Nope. I have a graphical tablet so I thought it might be it. However, I turned it off -- and the logs I've sent you are when I've turned it off. 

Nothing else really. This is some kind of new problem to me. Anything else ever encountered in the community? Haven't found any reports.

**Comment by f3ss1** [comment] 2022-04-12 19:57
Congratulations then I guess :)

Any ideas on what shall we do next?

**Comment by rchiodo** [comment] 2022-04-12 20:08
Without a repro in house it's rather difficult to solve. I need the callstack of what is sending the command.

If you run the 'Developer: Set Log Level' and set the logging level to trace
![image](https://user-images.githubusercontent.com/19672699/163044544-d31cf21f-61be-46ad-8c43-802a001070c9.png)

This should generate a list of all the commands executed in the `Log (window)` output pane. Maybe it will show something interesting.

Here's an example for me with an interrupt:

```
[2022-04-12 13:07:04.863] [renderer6] [trace] CommandService#executeCommand notebook.cell.cancelExecution
[2022-04-12 13:07:04.863] [renderer6] [trace] [History stack global-default]: notifyNavigation() (editor: file:///d%3A/Source/Testing_3/manualTestFile.ipynb, event: user)
[2022-04-12 13:07:04.864] [renderer6] [trace] [History stack global-default]: notifyNavigation() not ignoring (editor: file:///d%3A/Source/Testing_3/manualTestFile.ipynb, event: user)
[2022-04-12 13:07:04.864] [renderer6] [trace] [History stack global-default]: onSelectionAwareEditorNavigation() (editor: file:///d%3A/Source/Testing_3/manualTestFile.ipynb, event: user)
[2022-04-12 13:07:04.864] [renderer6] [trace] [History stack global-default]: replace() (editor: file:///d%3A/Source/Testing_3/manualTestFile.ipynb, event: <none>)
[2022-04-12 13:07:04.864] [renderer6] [trace] [History stack global-default]: index: 3, navigating: false
```

Interrupt in this case was caused by the 'notebook.cell.cancelExecution' command which is what happens when you click the 'stop' button next to a running cell.

**Comment by f3ss1** [comment] 2022-04-12 21:40
Please see if you can find this useful. I missed that it logs only the latest 15 minutes so in case there is nothing helpful I will rerun and try to reproduce the thing.

[developer_log.txt](https://github.com/microsoft/vscode-jupyter/files/8476743/developer_log.txt)

I can confirm that I've now tried reinstalling VSCode and the extension -- it does not seem to be helping.

**Comment by rchiodo** [comment] 2022-04-12 21:57
So in that log did the error reproduce? There was no command executed that would have caused an interrupt.

**Comment by f3ss1** [comment] 2022-04-12 22:30
It did reproduce. I will re-run the code tomorrow then to get proper logs: I believe the error appeared before the logs I've sent to you: I started the code say at 23:30, and the logs contain only data since 00:15.

**Comment by mcndt** [comment] 2022-04-29 09:41
The same just started happening to me! I thought I was going crazy.

@f3ss1 Do you still experience this bug? Or have you resolved this somehow?

- Jupyter Extension version v2022.3.1000901801
- Python Extension version v2022.4.1
- Windows 10
- Python 3.9.7
- Conda
- Jupyter server running: Local

**Comment by f3ss1** [comment] 2022-04-29 09:54
@mcndt  not really. I did try all the stuff mentioned above and nothing really helped. I also believe I have pretty much the same setup as you do. I had to quite VSCode 'cause it is impossible to work under these conditions. I do hope though to come back once 'cause VSCode's remote access to interpreters is really awesome.

And yeah, that does feel like you are going crazy and somehow clicking some button but i double checked and i really have no hotkey for KeyboardInterrupt :)

Sorry for not providing logs, been quite busy all the time.

**Comment by rchiodo** [comment] 2022-06-08 16:40
Closing for lack of information (and no other reports). If anybody can still repro and can generate the VS code debug log as mentioned [above](https://github.com/microsoft/vscode-jupyter/issues/9671#issuecomment-1097166513), please comment or reopen. Thanks.

**Comment by TJMac93** [comment] 2022-07-29 13:26
I do face a similar issue sometimes but have not been able to deliberately recreate it. Seems like it could be when I run a cell, scroll so that the running cell is no longer on screen, and then make changes to/delete a different cell - but I can't confirm. I don't have random KeybaordInterrupts like the original issue however.

**Comment by nathanterroir** [comment] 2022-08-25 17:07
I have been having the same issue for about the last 4 months. It's been incredibly frustrating. I think it's a more prevalent bug than it seemed.

**Comment by berk-arena** [comment] 2022-09-17 23:14
Nothing to add other than a +1 - I'm experiencing this, can't repro consistently. For whatever it's worth, I'm opening notebooks on a remote server via "Connect to host" and running cells that take a few minutes (5-10 minutes) to run.

**Comment by shop4navo** [comment] 2022-09-18 17:45
suppose you set a cell to run and then scroll to another cell.

If you type in another cell the first cell runs. but if you delete a cell or add a cell, the previous cell which was running stops with a KeyboardInterrupt. I thought this was a known error, but seems not

**Comment by ajbiffl219** [comment] 2022-09-30 14:43
> 

I get similar behavior, but only when I delete another cell that's "pending" to run after the current cell finishes (e.g., when using "run all" or "execute cell and below")

**Comment by DonJayamanne** [comment] 2022-10-09 22:17
> I get similar behavior, but only when I delete another cell that's "pending" to run after the current cell finishes

Thanks, I've been able to replicate this issue with the same steps.

**Comment by DonJayamanne** [comment] 2022-10-09 22:31
Filed upstream issue https://github.com/microsoft/vscode/issues/163133

**Comment by DonJayamanne** [comment] 2022-11-01 17:03
Closing this issue as fixed in VS Code Insiders for now.
This should now be fixed in the latest Insider version of VS Code insiders and will be fixed in the next stable version of VS Code.

**Closed by DonJayamanne** 2022-11-01 17:03 UTC
Labels: bug, upstream-vscode, notebook-execution
