### ISSUE TITLE
Jupyter notebooks changes auto sync to exported HTML/Python/PDF

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#9075] opened 2022-02-19 01:23 UTC
Would be nice if exported HTML/Python/PDF are auto synced with the notebooks changes, perhaps when the files share the same names and live in the same folder. Could also be an option when exporting.

**Comment by rchiodo** [comment] 2022-02-19 01:34
Thanks. This should be a dupe of https://github.com/microsoft/vscode-jupyter/issues/8978

**Closed by rchiodo** 2022-02-19 01:34 UTC
Labels: enhancement, needs-triage
