### ISSUE TITLE
Run by line for native notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1161] opened 2020-08-06 14:38 UTC
Not sure how this would work. The debugger would work the same but putting the ip indicator into the monaco editor is likely not possible. 

We can try decorators though:
https://code.visualstudio.com/api/references/vscode-api (gutterIconPath for the ip indicator?)

**Comment by DavidKutu** [comment] 2021-08-31 21:44
Dupe of #5607

**Closed by DavidKutu** 2021-08-31 21:44 UTC
Labels: internal-contributor, vscode-notebook, work item, run-by-line
