### ISSUE TITLE
Display progress indicator when native interactive window kernel is starting up

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#6500] opened 2021-07-01 18:48 UTC
Testing microsoft/vscode#127378

1. In a new workspace that has not started any extensions
2. Run `Jupyter: Create interactive window` from command palette

**Bug**
There are two delays that cause me to think the command failed (which makes me often try to run the command again):

1. First a long delay when loading the interactive window for the first time (extension activation?)
2. Then a shorter delay when the interactive window is open but has no content

https://user-images.githubusercontent.com/12821956/124175063-f7435500-da61-11eb-8974-0c81e033f4ee.mov

It would be nicer IMO if the interactive window showed instantly with some sort of `initializing...` indicator

**Comment by joyceerhl** [comment] 2021-07-01 20:56
Should also display a global progress indicator when individual cells are executing. Ref https://github.com/microsoft/vscode-jupyter/issues/6473

**Comment by greazer** [comment] 2021-07-01 23:26
dupe of #6466

**Closed by greazer** 2021-07-01 23:26 UTC
Labels: native-interactive
