### ISSUE TITLE
Ship output from renderer extension with Jupyter extension

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4149] opened 2020-12-07 20:55 UTC
**In renderer extension:**
* Upload the output to some blob store as part of build process
**In Jupyter extension:**
* Download the renderer extension output as part of the `npm install` process
(see how bycrypt exe is being downloaded)
* Update package.json to include renderer extension stuff

**Comment by rchiodo** [comment] 2021-01-05 18:34
Dupe of #3936

**Closed by rchiodo** 2021-01-05 18:34 UTC
Labels: vscode-notebook
