### ISSUE TITLE
I and everyone I know don't use vscode-jupyter because it's slow

### ISSUE THREAD

**Issue by loftusa** [microsoft/vscode-jupyter#13338] opened 2023-04-17 17:15 UTC
I'm a data scientist and I am friends with a lot of other data scientists. We talk about different frameworks a lot.

Everybody I know still uses jupyter lab directly, despite the fact that things like copilot and all the nice vscode extensions and themes and having an integrated environment should be pushing everyone to use vscode-jupyter instead.

Some people I know use Python Interactive with the `#%%` setup instead. Everyone I know has tried out using `vscode-jupyter`, and then switched back to normal `jupyter lab` after a bit.

**There are two big reasons for this, one hard to fix, the other incredibly easy:**

**a)** It is simply slower than jupyter lab. Cells just take longer to run. I'm not entirely sure why because I don't know the internals of vscode-jupyter. But jupyter lab just *feels smoother*.

**b)** documentation is more annoying to access because if you press `shift-tab` inside of a call (e.g., `x = foo(param1, <shift-tab>`), it won't pull immediately up the full documentation for the function like in jupyter lab. And you can't press it twice. Or, sometimes it does, but it's way too slow to appear, and so it's better to just look up the documentation manually. Because doing this is such a regular part of everybody's workflow, the lack of it is annoying enough to not switch from jupyter lab. All you have to do here is exactly copy jupyter lab's functionality. Inline documentation is *the* most important thing for the majority of people writing code, and if it's not done right, nothing else matters.

I am writing this because I've wanted to switch entirely to vscode-jupyter for years, because I like copilot and because it would be nice to do everything in one IDE - but I've been blocked for years, and everyone else I know has also been blocked for years. If you guys don't prioritize on these two things, people will simply not switch. Building new features or fixing other minor issues will not do anything because these blocking issues have not been fixed.

Posting out of frustration and the hope that the core developers will see this and realize that these are the only real issues holding what could be a great piece of software back. Please, please, please for the love of god prioritize these.

**Comment by amunger** [comment] 2023-04-17 22:54
Thanks for the feedback!

We have experimented a bit with the second suggestion in the jupyter powertoys extension with the `jupyterContextualHelp.focus` command, although that shows in a separate window rather than a tooltip pop-up. It looks like you actually commented on [the related issue](https://github.com/microsoft/vscode-jupyter/issues/1307) last year. Have you tried that feature out?

The language server also provides the `Trigger Parameter Hints` command, which might be what you're looking for - ctrl+shift+space by default.
<img width="268" alt="image" src="https://user-images.githubusercontent.com/2019016/232627485-a5cb8101-0dde-4cc1-8d3b-25e457d0953b.png">

I can see what you mean about jupyter lab feeling smoother. It seems like it may mostly be the additional UI updates we make like execution time and the status indicator since we have to communicate across processes for that.

**Comment by amunger** [comment] 2023-04-18 22:09
I should actually confirm the specific performance differences that you're seeing to make sure we're looking at the right area - Would you be able to post a gif that demonstrates the slowness?

**Comment by marcglobality** [comment] 2023-07-21 10:53
I do use vscode for notebooks, but certainly I'm missing features I had in Jupyterlab:
- jupytext integration is not well resolved. We only push to GH the .py generated from the notebook. In jupyterlab it's sync'd and saving in the notebook updates the .py. Save on reverse, but the sync is done when opening the notebook. In VScode, among other issues, you can open a py as a notebook, but when you close it you lose all your outputs 😱 
- Slowness that people talk about. When working with a notebook on EC2, the suggestions from VScode (e.g. autocomplete) come much later than those from Copilot. Plus, often it takes 1-2 seconds to start execution of a cell.
- Searching in a long notebook it's slow and sometimes does not even work.
- I had instances of writing a markdown, pressing execute (which does not execute anything, just gets you out of editing) and then the cells looks empty, taking the same space but just a big box empty. If I edit again I see my original text, but this is defo a bug. Not a big deal though.
- Execution time: I was using https://github.com/deshaw/jupyterlab-execute-time, to get good info about the time spent to run a cell and when was the last time. There's something similar but worse (unless I'm unaware of some extension)
   - First, it just shows the time, not the last time when was executed. For that you need to hover the mouse
   - Second, when I open the notebook on the remote the next day, all such information has disappeared. I imagine the info gets erased once reloading the window. In the aforementioned extension, such info is persisted in the metadata of the notebook, so stays with you forever.
   - Because the info stays with the json of the notebook, (this is a very niche case), I could generate a html report from the notebook and persist the execution time info into the html. This is something I cannot do in VScode notebooks.

All of this being said, I use vscode-jupyter because it provides me more pros than cons

**Comment by marctorsoc** [comment] 2023-07-21 10:54
I do use vscode for notebooks, but certainly I'm missing features I had in Jupyterlab:

- jupytext integration is not well resolved. We only push to GH the .py generated from the notebook. In jupyterlab it's sync'd and saving in the notebook updates the .py. Save on reverse, but the sync is done when opening the notebook. In VScode, among other issues, you can open a py as a notebook, but when you close it you lose all your outputs 😱
- Slowness that people talk about. When working with a notebook on EC2, the suggestions from VScode (e.g. autocomplete) come much later than those from Copilot. Plus, often it takes 1-2 seconds to start execution of a cell.
- Searching in a long notebook it's slow and sometimes does not even work.
- I had instances of writing a markdown, pressing execute (which does not execute anything, just gets you out of editing) and then the cells looks empty, taking the same space but just a big box empty. If I edit again I see my original text, but this is defo a bug. Not a big deal though.
- Execution time: I was using https://github.com/deshaw/jupyterlab-execute-time, to get good info about the time spent to run a cell and when was the last time. There's something similar but worse (unless I'm unaware of some extension)
     - First, it just shows the time, not the last time when was executed. For that you need to hover the mouse
     - Second, when I open the notebook on the remote the next day, all such information has disappeared. I imagine the info gets erased once reloading the window. In the aforementioned extension, such info is persisted in the metadata of the notebook, so stays with you forever.
     - Because the info stays with the json of the notebook, (this is a very niche case), I could generate a html report from the notebook and persist the execution time info into the html. This is something I cannot do in VScode notebooks.

All of this being said, I use vscode-jupyter because it provides me more pros than cons

**Comment by amunger** [comment] 2023-07-21 14:32
> In jupyterlab it's sync'd and saving in the notebook updates the .py. Save on reverse, but the sync is done when opening the notebook.

sounds similar to https://github.com/microsoft/vscode-jupyter/issues/1240

> When working with a notebook on EC2, the suggestions from VScode (e.g. autocomplete) come much later than those from Copilot. Plus, often it takes 1-2 seconds to start execution of a cell.

Is this while using remote desktop to the EC2 instance?

>Searching in a long notebook it's slow and sometimes does not even work.
I had instances of writing a markdown, pressing execute (which does not execute anything, just gets you out of editing) and then the cells looks empty, taking the same space but just a big box empty. If I edit again I see my original text, but this is defo a bug. Not a big deal though.

These should be separate issues to get more inf - the markdown one certainly sounds like a bug, but I've never seen something like that and not sure how it would happen

**Comment by marctorsoc** [comment] 2023-07-21 15:01
> sounds similar to https://github.com/microsoft/vscode-jupyter/issues/1240

yup, you can see that the last comment is mine :) (from my work GH)

> Is this while using remote desktop to the EC2 instance?

Just to be very clear, I'm not using any extra layer to connect to the EC2 instance. Just VScode, who connect via ssh to the remote

> These should be separate issues to get more info - the markdown one certainly sounds like a bug, but I've never seen something like that and not sure how it would happen

Do you suggest I open new issues for each of them? The latter certainly is rare, and might be due to an unstable internet connection (even though I never saw something like this in Jupyter after 5-6y, and I've been working with VScode for 6 months and saw it 5-6 times).

**Comment by amunger** [comment] 2023-07-21 15:33
ok, I created a bug for the markdown. Could you create a new issue for the search performance with more info, like how large the notebook is?

**Comment by marctorsoc** [comment] 2023-08-02 14:29
I can confirm the search issue only happens with ssh remote, and when the connection is not stable. I've tried locally, doing the notebook as large as possible, or with a notebook with problems when in remote, and everything is fine. I'm sure the other issue comes from the same cause. In general, I have many problems with VScode with an unstable connection. I'm now during holidays in a house that has a mobile connection only, and I can literally watch youtube videos, but VScode sometimes gets blocked with a notebook in remote to EC2...

**Comment by amunger** [comment] 2024-03-29 18:21
closing in favor of https://github.com/microsoft/vscode-jupyter/issues/14459 (unless your seeing perf issues with a small notebook)

**Closed by amunger** 2024-03-29 18:21 UTC
Labels: bug, perf, notebook-remote
