### ISSUE TITLE
Duplicate intellisense tooltips and dropdowns

### ISSUE THREAD

**Issue by ddonukis** [microsoft/vscode-jupyter#12029] opened 2022-11-15 13:39 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

After opening any ipynb file duplicate intellisense tooltips and code complete suggestions appear, both in ipynb files and in py files.

If VS Code is restarted the issue doesn't re-appear if only py files are opened, but as soon as I open a notebook the duplication issue comes back.

If I disable Jupyter extension duplication doesn't happen.

![image](https://user-images.githubusercontent.com/110604171/201925422-f4eb3b9c-adef-4759-9207-fde2df8fae31.png)

![image](https://user-images.githubusercontent.com/110604171/201925489-40d9c7ee-a664-43eb-8515-603d6d54ddd1.png)

### VS Code Version

Version: 1.73.1 (Universal) Commit: 6261075646f055b99068d3688932416f2346dd3b Date: 2022-11-09T02:08:38.961Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin arm64 21.6.0 Sandboxed: No

### Jupyter Extension Version

v2022.9.1202862440

### Jupyter logs

```shell
don't know where this is
```

### Coding Language and Runtime Version

Python 3.9.14

### Language Extension Version (if applicable)

v2022.18.2

### Anaconda Version (if applicable)

not used (env managed with poetry)

### Running Jupyter locally or remotely?

Local

**Comment by HPUtx813** [comment] 2022-11-16 13:55
I have also encountered this problem and if you disable the pylance extension, duplication does not occur. But I don't want to do that. @ddonukis

**Comment by 0shui** [comment] 2022-11-16 21:27
The same problem on my Apple silicon laptop. Tried Extension Bisect and found the problem to be Jupyter extension. Disabling it will fix the problem but you can't run notebook in the editor anymore..

**Comment by whoeverim5** [comment] 2022-11-19 12:26
just upgrade your jupyter extension to the newest.

**Comment by HPUtx813** [comment] 2022-11-19 13:19
It's already the  the newest.

**Comment by HPUtx813** [comment] 2022-11-19 13:20
It's already the  the newest. @whoeverim5

**Comment by OrkWard** [comment] 2022-11-25 05:23
I've met this problem too, and it has been there since the version last month(2022.9.1202862440). I tried switching to preview version and solved the problem once, but in this version(2022.9.1303220346) it shows up again. This time switch to the preivew will cause a fatal error: can not active the extension.

In the devtool the error is`extension activation failed TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function`.

Meanwhile, I keep all other extensions related to the newest version(Pylance, etc.)

**Comment by bsaunders23** [comment] 2022-11-28 22:14
Adding some more details to bug, **For what it's worth this appears to be an issue that was introduced in `v2022.5`, issue isn't appearing beforehand.**

## What happened?
When opening a jupyter notebook the current implementation of Jupyter extension (v2022.5 and later) spawns a new Pylance service as indicated in the logs below. It's initially starting a service for the workspace ("Pylance_Dupe_Example") but then starting a separate service for the notebook in question ("c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb"). VSCode's renderer is correctly compiling tooltips from Intellisense, so I think it's more a matter of suspending the service intialization when a notebook is first opened in a workspace which worked fine prior to 2022.5.

### Steps to recreate

1. Open a folder/workspace, ensure language server is functioning correctly
2. Open a .ipynb file, observe instantiation of second language service in Python Language Server logs

[](https://github.com/bsaunders23/Pylance_Dupe_Example/blob/main/example.gif)

## VS Code Version
Version: 1.74.0-insider (user setup)
Commit: fef85ea792f6627c83024d1df726ca729d8c9cb3
Date: 2022-11-21T05:22:37.848Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

## Jupyter Extension Version
v2022.5.1001601848+

## Jupyter logs - Including Language Server instead since I think that's more relevant to what's going on here
### Jupyter
```
info 14:4:16.386: Started kernel base (Python 3.6.6), (Raw session started and connected)
info 14:4:16.390: Finished connecting f4410adf-4558-407a-9416-280d168480d4
info 14:4:16.730: UpdateWorkingDirectoryAndPath in Kernel
info 14:4:16.731: Executing silently Code (idle) = import os\nimport sys\n%cd "c:\Users\saun89\Documents\Pylance_Dupe_Example"\nif os.getcwd() not in sys.
info 14:4:16.803: Executing silently Code (completed) = import os\nimport sys\n%cd "c:\Users\saun89\Documents\Pylance_Dupe_Example"\nif os.getcwd() not in sys.
info 14:4:16.805: Waiting for idle on (kernel): 93896faf-b4d0-4a90-a295-ad18bb42bd63 -> idle
info 14:4:16.805: Finished waiting for idle on (kernel): 93896faf-b4d0-4a90-a295-ad18bb42bd63 -> idle
info 14:4:20.790: Preferred Remote kernel for c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb is undefined
info 14:4:20.790: Find preferred kernel for c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb with metadata {"kernelspec":{"display_name":"Python 3.6.6 ('base')","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.6.6"},"orig_nbformat":4,"vscode":{"interpreter":{"hash":"d7fba4c45781ddbf85346bc3cca8da8c57ef4b5e6e654c8f85bee35838195d45"}}} & preferred interpreter c:\Users\saun89\AppData\Local\Continuum\anaconda3\python.exe
info 14:4:20.796: Preferred Remote kernel for c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb is undefined
info 14:4:20.796: Preferred kernel .jvsc74a57bd0d7fba4c45781ddbf85346bc3cca8da8c57ef4b5e6e654c8f85bee35838195d45.c:\Users\saun89\AppData\Local\Continuum\anaconda3\python.exe.c:\Users\saun89\AppData\Local\Continuum\anaconda3\python.exe.-m#ipykernel_launcher is exact match
info 14:4:20.802: Preferred Remote kernel for c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb is undefined
info 14:4:38.176: Disposing kernel .jvsc74a57bd0d7fba4c45781ddbf85346bc3cca8da8c57ef4b5e6e654c8f85bee35838195d45.c:\Users\saun89\AppData\Local\Continuum\anaconda3\python.exe.c:\Users\saun89\AppData\Local\Continuum\anaconda3\python.exe.-m#ipykernel_launcher for notebook c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb due to selection of another kernel or closing of the notebook
info 14:4:38.176: Dispose Kernel 'c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb' associated with 'c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb'
info 14:4:38.182: kill daemon
```
### Language Server
```
[Info  - 2:04:22 PM] (21136) Pylance language server 2022.11.30 (pyright 04a10583) starting
[Info  - 2:04:22 PM] (21136) Server root directory: c:\Users\saun89\.vscode-insiders\extensions\ms-python.vscode-pylance-2022.11.30\dist
[Info  - 2:04:22 PM] (21136) Starting service instance "Pylance_Dupe_Example"
[Info  - 2:04:22 PM] (21136) Notebook support: LSP
[Info  - 2:04:22 PM] (21136) Interactive window support: Legacy
[Info  - 2:04:22 PM] (21136) Starting service instance "c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb"
[Info  - 2:04:22 PM] (21136) No configuration file found.
[Info  - 2:04:22 PM] (21136) No pyproject.toml file found.
[Info  - 2:04:22 PM] (21136) Setting pythonPath for service "Pylance_Dupe_Example": "C:\Users\saun89\AppData\Local\Continuum\anaconda3\python.exe"
[Warn  - 2:04:22 PM] (21136) stubPath c:\Users\saun89\Documents\Pylance_Dupe_Example\typings is not a valid directory.
[Info  - 2:04:23 PM] (21136) Assuming Python version 3.6
[Info  - 2:04:23 PM] (21136) Assuming Python platform Windows
[Info  - 2:04:24 PM] (21136) Searching for source files
[Info  - 2:04:24 PM] (21136) Found 1 source file
[Info  - 2:04:24 PM] (21136) Background analysis(1) root directory: c:\Users\saun89\.vscode-insiders\extensions\ms-python.vscode-pylance-2022.11.30\dist
[Info  - 2:04:24 PM] (21136) Background analysis(1) started
[Info  - 2:04:24 PM] (21136) Background analysis(2) root directory: c:\Users\saun89\.vscode-insiders\extensions\ms-python.vscode-pylance-2022.11.30\dist
[Info  - 2:04:24 PM] (21136) Background analysis(2) started
[Info  - 2:04:24 PM] (21136) No configuration file found.
[Info  - 2:04:24 PM] (21136) No pyproject.toml file found.
[Info  - 2:04:24 PM] (21136) Setting pythonPath for service "c:\Users\saun89\Documents\Pylance_Dupe_Example\workspace.ipynb": "C:\Users\saun89\AppData\Local\Continuum\anaconda3\python.exe"
[Warn  - 2:04:24 PM] (21136) stubPath c:\Users\saun89\Documents\Pylance_Dupe_Example\typings is not a valid directory.
[Info  - 2:04:24 PM] (21136) Assuming Python version 3.6
[Info  - 2:04:24 PM] (21136) Assuming Python platform Windows
[Info  - 2:04:25 PM] (21136) Searching for source files
[Info  - 2:04:25 PM] (21136) No source files found.
[Info  - 2:04:27 PM] (21136) Indexer background runner(3) root directory: c:\Users\saun89\.vscode-insiders\extensions\ms-python.vscode-pylance-2022.11.30\dist (index)
[Info  - 2:04:27 PM] (21136) Indexing(3) started
[Info  - 2:04:29 PM] (21136) Indexing finished(3).
[Info  - 2:04:35 PM] (21136) Indexer background runner(4) root directory: c:\Users\saun89\.vscode-insiders\extensions\ms-python.vscode-pylance-2022.11.30\dist (refresh)
[Info  - 2:04:35 PM] (21136) Indexing(4) started
[Info  - 2:04:38 PM] (21136) [IDX(4)] Long operation: scan packages c:\Users\saun89\Documents\Pylance_Dupe_Example (3645ms)
[Info  - 2:04:38 PM] (21136) scanned(4) 461 files over 1 exec env
[Info  - 2:04:47 PM] (21136) [IDX(4)] Long operation: index execution environment c:\Users\saun89\Documents\Pylance_Dupe_Example (8053ms)
[Info  - 2:04:47 PM] (21136) [IDX(4)] Long operation: index packages c:\Users\saun89\Documents\Pylance_Dupe_Example (8056ms)
[Info  - 2:04:47 PM] (21136) indexed(4) 240 files over 1 exec env
[Info  - 2:04:47 PM] (21136) Indexing finished(4).
```

## Coding Language and Runtime Version
Python 3.6.6

## Language Extension Version (if applicable)
v2022.11.30 (Pylance)

## Anaconda Version (if applicable)
conda version : 4.10.3 (don't use local as much)

## Running Jupyter locally or remotely?
Originally noticed remotely, reproduced locally

**Comment by bsaunders23** [comment] 2022-11-29 18:07
Moving to pre-release version should resolve, think we can close this as duplicate of https://github.com/microsoft/pylance-release/issues/3617

**Comment by corneliusroemer** [comment] 2022-12-04 01:24
Switching to Jupyter prerelease fixed it for me. @ddonukis have you tried reloading your window?

**Comment by DonJayamanne** [comment] 2022-12-08 10:35
@ddonukis Please could you confirm you have the latest pre-release in VS Code insiders.
Or please install the latest stable builds (we had a bug in the past that resulted in users not getting the latest pre-releases in stable builds)

**Comment by roblourens** [comment] 2022-12-08 17:59
@DonJayamanne does the Jupyter extension contribute suggestions?

**Comment by DonJayamanne** [comment] 2022-12-08 21:15
Yes, we contribute suggestions from the kernel as well.

**Comment by jablka** [comment] 2023-02-04 13:55
What are these different types of **icons** next to each suggestion? 
Sometimes the icons are the same, just doubled (like in `print` function), 
sometimes they are different (in `import`, or pandas dataframe `index` ).
![pri](https://user-images.githubusercontent.com/20874763/216771306-5b849203-954c-41df-a76c-4a3f5e69e78d.png)
![imp](https://user-images.githubusercontent.com/20874763/216771322-3367a5ab-ffc2-4556-9822-496ad4ae1841.png)
![index](https://user-images.githubusercontent.com/20874763/216771335-a0b47158-ce43-4669-9c4d-ec053770a425.png)

**Comment by bsaunders23** [comment] 2023-02-07 21:53
> What are these different types of **icons** next to each suggestion? Sometimes the icons are the same, just doubled (like in `print` function), sometimes they are different (in `import`, or pandas dataframe `index` ).
> 
> Anyway it's annoying. How can this bug be resolved?
> 
> ![pri](https://user-images.githubusercontent.com/20874763/216771306-5b849203-954c-41df-a76c-4a3f5e69e78d.png) ![imp](https://user-images.githubusercontent.com/20874763/216771322-3367a5ab-ffc2-4556-9822-496ad4ae1841.png) ![index](https://user-images.githubusercontent.com/20874763/216771335-a0b47158-ce43-4669-9c4d-ec053770a425.png)

@jablka can you confirm when you're seeing the different icons that you aren't seeing those duplicated as well (i.e. 4 print statements, 2 each with the different icons, can scroll down further in the prompt to see). My best guess with be something to do with the ambiguity of keywords in cases where Intellisense picks up on keywords having mutable data types (i.e. `index` as a function + generic object represented as the cube). If you are only seeing these 2 prompts with different icons then it's likely the case that the Intellisense is just picking up on different data type inference between the service running for the specific Jupyter notebook and the workspace in general.

It might also help to look at your language server output when starting up initially to see if you can identify the two different language services at play here (see my [note above](https://github.com/microsoft/vscode-jupyter/issues/12029#issuecomment-1329824941)).

**Comment by jablka** [comment] 2023-02-08 18:30
The issue occurs right **after any of cells of particular notebook is executed**.

First image: everything is okay, suggestion to "import" is only one.
<img width="133" alt="01" src="https://user-images.githubusercontent.com/20874763/217619247-f59c7ffc-dd13-4767-bf5a-2e191725dccb.png">

Second image, after first cell is executed, suggestion to "import" is doubled, and with different icon.
<img width="147" alt="02" src="https://user-images.githubusercontent.com/20874763/217619282-36fc597a-97af-40c9-a376-403150e470a4.png">

**Comment by bsaunders23** [comment] 2023-02-08 19:34
> The issue occurs right **after any of cells of particular notebook is executed**.
> 
> First image: everything is okay, suggestion to "import" is only one. <img alt="01" width="133" src="https://user-images.githubusercontent.com/20874763/217619247-f59c7ffc-dd13-4767-bf5a-2e191725dccb.png">
> 
> Second image, after first cell is executed, suggestion to "import" is doubled, and with different icon. <img alt="02" width="147" src="https://user-images.githubusercontent.com/20874763/217619282-36fc597a-97af-40c9-a376-403150e470a4.png">

Thanks @jablka , this behavior would be consistent then with the one I experienced. Once you instantiate the jupyter kernel the language server spins up a new service for the notebook specifically is a bit simpler in terms of having generic icons. VSCode's interface is setup to simply present all typehinting information, so this is most likely an issue with duplicate language services. If you've already confirmed you're on the pre-release build of the jupyter extension, then I think the next step would be to look at your language server console output and see what happens when you run that cell and identify the duplicate language service that's starting up.

In my case there were two different Pylance services (again this should be resolved moving to the pre-release of jupyter), but if you're seeing different services (i.e. if maybe Jedi or some other service is getting involved from another extension) it might just be a matter of uninstalling/disabling the non-Pylance service.

**Comment by jablka** [comment] 2023-02-10 12:20
just saw these duplicate suggestions in Microsoft official video :)
https://www.youtube.com/watch?v=DA6ZAHBPF1U&t=489s

**Comment by DonJayamanne** [comment] 2023-12-05 03:01
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/13596

**Closed by DonJayamanne** 2023-12-05 03:01 UTC
Labels: bug, notebook-intellisense
