### ISSUE TITLE
Data Viewer/Variable Explorer support for non-array like objects (such as nested dicts)

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#1138] opened 2020-01-16 21:05 UTC
Support for objects in a tree like view, like how you can view objects in debug mode

Ask from one of our users:

> "VScode also has an interactive window that opens a Jupyter kernel (separate console/kernel) which displays a subset of variables without the need of debugger.
> It turns out that you can directly execute code from the editor in the interactive window’s console (no copy/paste needed), but the variable explorer that it provides is not as powerful (doesn’t give info on objects/classes/methods).
> For example, we can’t look at a model object and inspect its components with this method, which has become an important part of our development process.
> 
> I guess we could run VScode in debug mode whenever we desire that level of granularity, but it seems like an unnecessary concession when we can get the desired functionality from PyCharm."

Not sure if this is a dup

**Comment by paamand** [comment] 2021-03-25 11:07
Suggestion to prioritize simple dict-support. I.e. for
`a = {'b':42}`
the variable overview shows
![image](https://user-images.githubusercontent.com/17837300/112463234-493d5600-8d62-11eb-995e-a450a8109446.png)
but inspecting the specific variable gives
![image](https://user-images.githubusercontent.com/17837300/112463282-578b7200-8d62-11eb-8d6e-d6528ab94ebc.png)

For simple nested dicts, `a={'b':{'c':42}}` the variable inspector fails and simply displays
![image](https://user-images.githubusercontent.com/17837300/112463445-8dc8f180-8d62-11eb-9596-ca0b5debdf6d.png)

A nested, expandable viewer for nested dicts would be optimal.

**Comment by phgmacedo** [comment] 2022-08-01 21:39
I don't think this issue should be tagged as a feature request. I think this is a bug, when the variable viewer cannot view a variable it is a bug, **a major one**.

**Comment by MrRogerTheShrubber** [comment] 2022-08-03 00:50
> I don't think this issue should be tagged as a feature request. I think this is a bug, when the variable viewer cannot view a variable it is a bug, **a major one**. It's like shipping a car without wheels and then saying "we'll add support for wheels if there's enough community upvotes".
> 
> "Yes, we have a variable viewer; except that the variable viewer doesn't support most of python's types"

Oh, this is a good one! A lot of issues about supporting different types while debbugging are closed, but in a lot of cases, they don't work. 

---

Hi guys! I was thinking to myself, and I reached the conclusion that public shaming bad projects with bad maintainers is a reasonable way to entice action.

So I'll tag some organizations in particularly egregious examples of bad behavior with the hopes that given enough eyeball, all bugs are shallow!

I sure hope that one day the guys at @google, @aws, or even @facebook, maybe @apple, that someone, will provide a great open source competitor so that we don't get locked into using the bad @microsoft @python extension as the python experience! 😢

Of I course I must mention the @eclipse @apache and @mozilla guys lest they get jealous! ❤️

**Comment by FPRM** [comment] 2022-08-03 13:04
Some updates about this feature ?

**Comment by glennbarrett** [comment] 2023-03-04 16:54
Any update on this?

**Comment by marcos379** [comment] 2023-05-19 17:20
Any update on this? Spyder IDE Data Viewer is years ahead of VSCode in that particular aspect.

**Comment by rubrojas** [comment] 2023-06-15 07:00
Has it been any update? I am also experiencing this issue

**Comment by akiss-ic** [comment] 2023-07-27 13:36
Viewing a dictionary is hilariously bad with the Data Viewer in VSCode. It doesn't even get the keys right, just giving you a list of integers as the key

**Comment by lhg1992** [comment] 2023-07-29 19:42
Even in July 2023, the data viewer still cannot display the keys in the dict, it can only shows the values with the index numbers.

**Comment by bgupta** [comment] 2023-08-08 20:27
Curious is there any workaround short of switching to Spyder?

**Comment by GitHunter0** [comment] 2023-10-09 15:29
Hey folks, I think the ability to visually inspect nested objects (not only dictionaries but specially **nested dataframes**) is a critical feature for a data scientist, it saves a lot of time and gives quick insights.

Here's an example of `RStudio` Viewer for a nested dataframe:
```r
library(tidyverse)

# create a data frame
df <- tibble(
  group = c("A", "A", "B", "B"),
  x = c(1, 2, 3, 4),
  y = c(5, 6, 7, 8)
)

# nest the data frame by group
nested_df <- df %>% 
  group_by(group) %>% 
  nest()

# view the nested data frame
nested_df
```

![image](https://github.com/microsoft/vscode-jupyter/assets/26294221/131d0f11-5b85-4edb-b4f5-02d7dbb68270)

`nested_df`  the Viewer, it also shows the content when you hover on the cell:
![image](https://github.com/microsoft/vscode-jupyter/assets/26294221/f4b933d3-a56e-4c94-8759-efad8a3b4462)

And if you click on the cell with nested data, it opens another tab:
![image](https://github.com/microsoft/vscode-jupyter/assets/26294221/7d6b301c-cbb6-4a99-b138-6230f518e6d3)

I believe it is a great paradigm to borrow from, what do you think, @DonJayamanne ?

Thank you

**Comment by Nightenom** [comment] 2023-11-30 15:30
Just had a thought if it would be feasible to display at least result of `__repr__` instead `[object Object]` which would tell way more for custom classes

**Comment by amunger** [comment] 2023-12-14 23:24
duplicate of https://github.com/microsoft/vscode-jupyter/issues/1148

**Closed by amunger** 2023-12-14 23:24 UTC
Labels: data-viewer, variable-explorer, feature-request

**Comment by GitHunter0** [comment] 2023-12-15 01:05
@amunger , why is it not planned, could you elaborate?

**Comment by amunger** [comment] 2023-12-15 16:29
Duplicating against another issues does not mean it isn't planned, but the majority of the request is covered in a different issue. 

This functionality will very likely be implemented with the built-in variable viewer https://github.com/microsoft/vscode/issues/165445
