### ISSUE TITLE
Running a cell (Ctrl+Enter) should put us in Control mode

### ISSUE THREAD

**Issue by cipri-tom** [microsoft/vscode-jupyter#6198] opened 2021-06-08 13:44 UTC
## Expected behaviour

After running a cell with `Ctrl + Enter`, we can type `b` or `a` to add a new cell.

## Actual behaviour

`b` or `a` is typed inside the cell

## Steps to reproduce:

1. While editing a cell, press Ctrl+Enter
2. Press `a` or `b`

## Environment data

-   VS Code version: 1.57.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.914258744
-   Python Extension version (available under the Extensions sidebar): v2021.6.908196464-dev (pylance v2021.6.1-pre.1)
-   OS (Windows | Mac | Linux distro) and version: Local Mac, Remote Ubuntu 18.04
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

**Comment by joyceerhl** [comment] 2021-06-08 19:11
@cipri-tom Does `ctrl+enter` execute the current cell for you, or does it insert a new line and preserve the cell in edit mode? Are you working with markdown or code cells?

Possible duplicate of https://github.com/microsoft/vscode-jupyter/issues/6037

**Comment by cipri-tom** [comment] 2021-06-09 09:16
Yes, `ctrl+enter` executes the cell, but doesn't put in control mode.

This is for code cells.

For markdown, I cannot get them to render with `Shift/Ctrl + Enter`, but this is already covered in the other issue. My workaround to get them to render is to switch it to code (`y`), then back to MD (`m`), with an `esc` in between since `y` puts us in edit mode.

**Comment by DavidKutu** [comment] 2021-06-10 23:16
validated

**Closed by DavidKutu** 2021-06-10 23:16 UTC
Labels: bug
