### ISSUE TITLE
Creating a new file and picking the "Jupyter" language should render empty cell

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#7491] opened 2021-09-13 17:15 UTC
Users can create a new file through UI and shorthand operations. After creating the file, users are given the option to "select a language", which displays a quick-pick with Jupyter listed as one of the options.

If users choose Jupyter, they're kept in the same file, without being shown any visible changes to the UI to make it clear that they're creating/editing a notebook file.

Instead of keeping users in the seemingly plain text file after choosing Jupyter, the UI should be altered to show cell content (i.e., one empty cell), making it clear that they're editing a notebook file.

**Current Experience**
![image](https://user-images.githubusercontent.com/6413608/133126660-881ef2f2-d406-4e37-ae06-ec02a6878d19.png)

![image](https://user-images.githubusercontent.com/6413608/133127128-6ef99cdf-7be7-4b0e-a31b-eb987d49e4a6.png)

![image](https://user-images.githubusercontent.com/6413608/133127607-ca578912-9b67-4c8d-8f27-97fb5dd9156f.png)

![image](https://user-images.githubusercontent.com/6413608/133127675-9c40d1b8-eb7b-433c-83e4-673977ce3c5f.png)

**Desired Experience**
![image](https://user-images.githubusercontent.com/6413608/133126660-881ef2f2-d406-4e37-ae06-ec02a6878d19.png)

![image](https://user-images.githubusercontent.com/6413608/133127128-6ef99cdf-7be7-4b0e-a31b-eb987d49e4a6.png)

![image](https://user-images.githubusercontent.com/6413608/133127607-ca578912-9b67-4c8d-8f27-97fb5dd9156f.png)

![image](https://user-images.githubusercontent.com/6413608/133127797-03cf663b-f9d3-4921-ae3e-f695d78ff477.png)

**Comment by greazer** [comment] 2021-09-13 22:24
Basically a dupe of https://github.com/microsoft/vscode-jupyter/issues/7363

**Closed by greazer** 2021-09-13 22:24 UTC
Labels: enhancement, notebook-getting-started, notebook-workflow
