### ISSUE TITLE
Jupyter PowerToys not working after updating latest realeased version of jupyter

### ISSUE THREAD

**Issue by Bastin99** [microsoft/vscode-jupyter#12544] opened 2023-01-14 03:50 UTC
## Environment data

-   VS Code version: 1.75.0-insider (user setup)
-   Jupyter Extension version: v2023.1.2000141019
-   Python Extension version : v2023.1.10111008
-   OS and version: Windows 11 22H2
-   Python  version: Python 3.10.9
-   Type of virtual environment used : virtualenv 
-   Jupyter server running: Local

## Expected behaviour
- Jupyter powertoys was working fine before the Jupyter version v2023.1.2000131034 ( This screenshot is from previous version from that) . 
![image](https://user-images.githubusercontent.com/71763120/212448516-1aae4b55-340b-4fd2-9ce9-607892fa0c18.png)

## Actual behaviour
- This screen is from latest  Jupyter version (v2023.1.2000141019) . 
- Contextual help shows progress bar endlessly and others (cell tags and kernal) shows nothing
![image](https://user-images.githubusercontent.com/71763120/212448811-cbbf6806-c7ab-42f4-9166-773d331e13a4.png)

## Steps to reproduce:

1. Install latest version of jupyter and open the powertoys extension side panel in Vscode

## Logs
I think this might be the problem as it states that opening of jupyter powertoys failed ( Log from developer tool-> console)
``
Activating extension 'ms-toolsai.vscode-jupyter-powertoys' failed: t._createParsedCallSite is not a function.
``

**Comment by DonJayamanne** [comment] 2023-01-17 22:30
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12550

**Closed by DonJayamanne** 2023-01-17 22:30 UTC
Labels: bug
