### ISSUE TITLE
Jupyter Kernel `ms-toolsai.jupyter` cause `.py` code folding to disappear

### ISSUE THREAD

**Issue by yasirroni** [microsoft/vscode-jupyter#11703] opened 2022-10-19 01:31 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Enabling the `ms-toolsai.jupyter` extensions in VSCode 1.72.2 cause code folding to disappear in ordinary `.py` files. See https://github.com/microsoft/vscode/issues/163978

I use `ms-toolsai.jupyter` version `v2022.9.1202862440`.

### VS Code Version

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
auto-dark-mode-windows|dan|1.0.11
vscode-markdownlint|Dav|0.48.1
git-graph|mhu|1.30.0
python|ms-|2022.16.1
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
intellicode-api-usage-examples|Vis|0.2.5
vscodeintellicode|Vis|1.2.28

### Jupyter Extension Version

v2022.9.1202862440

### Coding Language and Runtime Version

Python 3.7

### Anaconda Version (if applicable)

-

### Running Jupyter locally or remotely?

Local

**Comment by yasirroni** [comment] 2022-10-19 01:35
Pre=release version `v2022.10.1102931121` also cause the bug. Disabling and restarting VSCode solve the issue.

**Comment by yasirroni** [comment] 2022-10-19 01:44
Using VSCode manual version install as explained in https://stackoverflow.com/questions/42626065/vs-code-how-to-rollback-extension-install-specific-extension-version, the last working version without this bus is `v2022.8.1002431955`.

**Comment by yasirroni** [comment] 2022-10-19 17:35
That's strange.

In my case, I didn't use cell expression at all. So, try with plain python code.

Furthermore, it has a comment on top of every function and class, such as `# this is class`. Ah, the file also has about 1000's lines of code.
___
Can you reproduce with that info?

**Comment by amunger** [comment] 2022-10-19 20:49
still not reproducing for me even with 100k lines. Are these conditions the only case that you don't see folding regions? i.e. Can you still use code folding with a file that just contains

```
x = 1
if (x):
    print('hello')
```

Code folding for `# %%` cells was introduced right around this time, but even if I force that provider to crash, it still returns the standard folding ranges, so it doesn't seem like that could be the issue.

**Comment by yasirroni** [comment] 2022-10-21 07:29
> x = 1
> if (x):
>     print('hello')

Above code did not work, no folding appears.
___
Cell folding using `# %%` inside `.py` files works

```python
# %% <<< folding appears here
x = 1

# %% <<< folding appears here
if (x): <<< folding did not appears here
    print('hello')
```
___
No bug in Markdown `.md` file:

```markdown
# Hello

World!
```
___
So, it just affected `.py` files.
___
Section folding in `.ipynb` files works. I dunno if code folding supported or not inside cells since it is not appearing (or not yet implemented?)
___
Do you need anymore information?

**Comment by amunger** [comment] 2022-10-21 17:56
I have added a `jupyter.pythonCellFolding` that should disable the folding provider from the jupyter extension. That should be available in tomorrow's insiders and hopefully that re-enables the other folding regions for you. Keeping this issue open though to try and figure out why it would be interfereing.

**Comment by yasirroni** [comment] 2022-10-21 19:17
> I have added a `jupyter.pythonCellFolding` that should disable the folding provider from the jupyter extension. That should be available in tomorrow's insiders and hopefully that re-enables the other folding regions for you. Keeping this issue open though to try and figure out why it would be interfereing.

So, cell folding can't coexist with code folding?
___
Based on here:

> Can you provide a screenshot or gif of this occurring? I'm not seeing this behavior: ![image](https://user-images.githubusercontent.com/2019016/196762109-4f2ee581-8a8e-4638-b316-7c6bcde09e31.png)

that is possible.

**Comment by amunger** [comment] 2022-10-21 20:17
yes, it works correctly for me with both types of folding regions, so I'm still trying to figure out how they could be interfering with each other for you. In the meantime, and before the next release, I wanted to make sure that users in your position can still get the previous folding regions to work.

**Comment by zzeitt** [comment] 2022-10-26 16:46
It's happening to more than one. (https://stackoverflow.com/a/74107138/8561448)

**Comment by ravimulpuri** [comment] 2022-10-28 06:51
I have the same issue as well. Unless I disable jupyter extension, I don't get folding for python files

**Comment by yasirroni** [comment] 2022-10-28 07:10
> Using VSCode manual version install as explained in https://stackoverflow.com/questions/42626065/vs-code-how-to-rollback-extension-install-specific-extension-version, the last working version without this bug is `v2022.8.1002431955`.

Since problem is not fixed yet, you can downgrade (and automatically stop auto update) to `v2022.8.1002431955` guys.

**Comment by jslomkowski** [comment] 2022-12-09 17:14
Hello, is there any update on this issue? We have received five updates, but the problem is still present.

**Comment by amunger** [comment] 2022-12-09 18:47
I still don't know what is causing this for some people, but the better workaround than downgrading versions is just to disable the setting mentioned above: `"jupyter.pythonCellFolding": false`

**Comment by psfinal9** [comment] 2022-12-13 13:30
> I still don't know what is causing this for some people, but the better workaround than downgrading versions is just to disable the setting mentioned above: `"jupyter.pythonCellFolding": false`

Hi @amunger
i am newie to vs code. could you give where i place ""jupyter.pythonCellFolding": false" ?
actually, the folding issue keep annoying me and jupyter always roll back to latest even if i install later version.
thanks!!!

**Comment by amunger** [comment] 2022-12-13 16:50
you can just use the settings page and uncheck the `Jupyter: Python Cell Folding` setting. That `"jupyter.pythonCellFolding": false` snippet ends up in your settings.json file, which you can also edit manually.

![image](https://user-images.githubusercontent.com/2019016/207394306-cb42f1eb-b48c-4f85-a224-e5a99adf7896.png)

**Comment by amunger** [comment] 2023-01-10 16:38
closing in favor of https://github.com/microsoft/vscode-jupyter/issues/12520 since that has a deeper investigation.

Workaround: https://github.com/microsoft/vscode-jupyter/issues/12520#issuecomment-1377539302

**Closed by amunger** 2023-01-10 16:38 UTC
Labels: bug, interactive-window

**Comment by psfinal9** [comment] 2023-01-11 14:10
in case of code-server, "editor.foldingStrategy": "indentation" is only available. 

thanks!!!
