### ISSUE TITLE
%load does not work in .ipynb, equivalent actions don't work in .py

### ISSUE THREAD

**Issue by EconoBen** [microsoft/vscode-jupyter#1082] opened 2020-11-11 20:19 UTC
## Environment data

-   VS Code version: 1.51.0
-   Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS and version: Windows_NT x64 10.0.17763
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Value of the `python.languageServer` setting: Microsoft
<img width="664" alt="Screenshot 2020-11-11 095006" src="https://user-images.githubusercontent.com/45580612/98860134-d376c480-2428-11eb-85bd-8771eafd5686.png">

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Script Data is loaded into cell or python file verbatim

## Actual behaviour

Nothing happens.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open a fresh .ipynb or .py file.
2. enter the following code: %load myfile.py
3. Additionally this code does not work in a .py or .ipynb: 
```
from IPython import get_ipython
ipython = get_ipython()
ipython.magic("load myfile.py")
```

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2020-11-12 17:46
Thanks for filing this issue. 
I can confirm we do not support the %load magic.

**Comment by EconoBen** [comment] 2020-11-17 19:43
Will someone be assigned to this task?

**Comment by DonJayamanne** [comment] 2020-11-17 19:54
> Will someone be assigned to this task?

At this stage this has not been prioritized. For such feature requests we look into user upvotes to prioritize it.
If and when this is added to our backlog we will update this issue.
In the mean time we always welcome user contributions.

**Comment by IanMatthewHuff** [comment] 2021-02-09 19:06
Closing as duplicate of #1602

**Closed by IanMatthewHuff** 2021-02-09 19:06 UTC
Labels: enhancement
