### ISSUE TITLE
Interactive Python Window doesn't accept input commands

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#3924] opened 2020-11-16 17:52 UTC
@jbiz25 commented on [Sat Nov 14 2020](https://github.com/microsoft/vscode-python/issues/14734)

Issue Type: <b>Bug</b>

Periodically, but very frequently, the Interactive Python window stops accepting any inputs.  Typing commands just stops working.  Even if the Interactive window has focus.

Extension version: 2020.11.358366026
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (53.89GB free)|
|Process Argv|--crash-reporter-id 0f21024a-5b34-49b8-93e8-c6b889335192|
|Screen Reader|no|
|VM|25%|
</details>

---

@1vecera commented on [Sun Nov 15 2020](https://github.com/microsoft/vscode-python/issues/14734#issuecomment-727556288)

Run current cell does not work, Run current cell and Advance does not work (Nothing happens), I am stuck executing selection in Notebook (selecting + shift enter). VSCode became unusable for me. How can I revert to an earlier Python extension version?  Interestingly, run all cells works, but run all cells above does not work again. 

![image](https://user-images.githubusercontent.com/32644386/99183743-602dc500-273e-11eb-9ac9-d3b0666ce3d1.png)

Extensions:
Jupyter: v2020.11.358541065
Python: v2020.11.358366026

---

@ncuxomun commented on [Sun Nov 15 2020](https://github.com/microsoft/vscode-python/issues/14734#issuecomment-727619875)

Same here. Interactive window does not accept any input commands, with some very rare exceptions. 
What can I do to fix that?

---

@1vecera commented on [Sun Nov 15 2020](https://github.com/microsoft/vscode-python/issues/14734#issuecomment-727641651)

It seems that VSCode is ignoring cells altogether. Now I figured out that run all cells actually runs everything at once.

---

@machsix commented on [Sun Nov 15 2020](https://github.com/microsoft/vscode-python/issues/14734#issuecomment-727700592)

Similar issue here. `Run cell` works but I couldn't type interactive command

**Comment by jonkislin** [comment] 2020-11-17 04:03
Same here. It seems that when I first start the python interactive window, the window excepts input.
I noticed this started happening after I followed the instructions here: 
https://superuser.com/questions/1461655/vs-code-shiftenter-does-not-send-code-to-python-interactive-why so that I could

**Comment by greazer** [comment] 2020-11-17 08:36
Dupe of #446

**Closed by greazer** 2020-11-17 08:36 UTC
Labels: internal contributor
