### ISSUE TITLE
Running a cell shortcut

### ISSUE THREAD

**Issue by Franco-from-Owlish** [microsoft/vscode-jupyter#7639] opened 2021-09-23 07:20 UTC
## Environment data

-   VS Code version:  Version: 1.60.2 (Universal)
                                    Commit: 7f6ab5485bbc008386c4386d08766667e155244e
                                    Date: 2021-09-22T11:59:27.195Z
                                    Electron: 13.1.8
                                    Chrome: 91.0.4472.164
                                    Node.js: 14.16.0
                                    V8: 9.1.269.39-electron.0
                                    OS: Darwin arm64 20.6.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: MacOS BigSur 11.6 (20G165)
-   Python and/or Anaconda version: Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

CMD-Enter should run a cell.
CMD-Shift-Enter should run a cell and advance to the next

## Actual behaviour

I just get a new line.

## Steps to reproduce:

1. Type CMD-Enter

The video attached is with me pressing CMD-Enter and CMD-Shift-Enter.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
N/A

https://user-images.githubusercontent.com/68659574/134468399-9682ff8a-cdee-4e24-bc3a-ff60b581cc2b.mov


```

</p>
</details>

**Comment by rchiodo** [comment] 2021-09-27 20:35
Thanks for the issue. This is a dupe of https://github.com/microsoft/vscode/issues/133038

**Closed by rchiodo** 2021-09-27 20:35 UTC
Labels: bug, needs-triage
