### ISSUE TITLE
Unable to connect to a named server, but can automatically initiate a default server on Jupyterhub.

### ISSUE THREAD

**Issue by Yefee** [microsoft/vscode-jupyter#15178] opened 2024-02-12 03:47 UTC
## Environment data

-   VS Code version: Version: 1.86.1 (Universal)
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:09:01.236Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 22.6.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.1.1
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: mac
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour and Actual behaviour

I use Jupyterhub on an HPC system. Typically, I create a new server (on the computing nodes) and obtain the URL and token in Jupyterhub. For instance, in this example URL: https://jupyterhub.hpc.ucar.edu/stable/user/che43/jupyter-heavy3/?token=xxxxxxxxxxxxxxxxxxxxxxxx, "che43" represents my username and "jupyter-heavy3" is the server name. I can access the remote server using JetBrains Dataspell. However, when using VS code, the IDE always starts a default server on Jupyterhub with limited resources (only 4GB memory).

Problem in VS code
![CleanShot 2024-02-11 at 22 37 13@2x](https://github.com/microsoft/vscode-jupyter/assets/6420873/8dee0a7d-6e61-4700-b8d1-be2582ddc0cb)
![CleanShot 2024-02-11 at 22 38 43@2x](https://github.com/microsoft/vscode-jupyter/assets/6420873/8dcba1dd-d77c-4cd6-b09d-796c9b5f7c28)

Works in Dataspell
![CleanShot 2024-02-11 at 22 41 25@2x](https://github.com/microsoft/vscode-jupyter/assets/6420873/c4417996-0582-454b-a1a8-6c19db6d316c)

## Logs

```Visual Studio Code (1.86.1, ssh-remote, desktop)
Jupyter Extension Version: 2024.1.1.
Python Extension not installed.
Pylance Extension not installed.
Platform: linux (x64).
Workspace folder ~/work/projects/SST-bias, Home = /glade/u/home/che43
20:33:07.458 [info] Start refreshing Kernel Picker (1707708787458)
20:33:07.470 [info] Not using Pylance
20:33:07.961 [info] Starting Kernel connectToLiveRemoteKernel, 2a7c5de6-305c-4b3a-a993-6de5691e5dc7  for '~/work/projects/SST-bias/test_vs_code.ipynb' (disableUI=true)
20:33:25.609 [error] Error fetching kernels from https://jupyterhub.hpc.ucar.edu/stable/user/<username>/ (JupyterHub-heavy3): [r [Error]: JupyterHub server no longer running at /user/<username>/api/kernels. Restart the server at https://jupyterhub.hpc.ucar.edu/stable/hub/spawn/<username>
	at r.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4914)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:19197)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17959] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyterhub.hpc.ucar.edu/stable/hub/user/<username>/api/kernels?1707708805501',
      status: 424,
      statusText: 'Failed Dependency',
      headers: [p [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
20:33:25.613 [error] Error fetching kernels from https://jupyterhub.hpc.ucar.edu/stable/user/<username>/ (JupyterHub-heavy3): [r [Error]: JupyterHub server no longer running at /user/<username>/api/kernels. Restart the server at https://jupyterhub.hpc.ucar.edu/stable/hub/spawn/<username>
	at r.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4914)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:19197)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyterhub.hpc.ucar.edu/stable/hub/user/<username>/api/kernels?1707708805503',
      status: 424,
      statusText: 'Failed Dependency',
      headers: [p [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
20:33:25.622 [error] Failed to fetch running kernels from remote server, connection may be outdated or remote server may be unreachable [r [Error]: JupyterHub server no longer running at /user/<username>/api/kernels. Restart the server at https://jupyterhub.hpc.ucar.edu/stable/hub/spawn/<username>
	at r.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4914)
	at async Promise.all (index 0)
	at async ou.validateRemoteServer (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:252:2987)
	at async ou.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:252:1904)
	at async a_.createJupyterSession (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:252:35995)] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyterhub.hpc.ucar.edu/stable/hub/user/<username>/api/kernels?1707708805505',
      status: 424,
      statusText: 'Failed Dependency',
      headers: [p [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
20:33:25.626 [warn] Error occurred while trying to start the kernel, options.disableUI=true Error: Failed to connect to the remote Jupyter Server 'https://jupyterhub.hpc.ucar.edu/'. Verify the server is running and reachable. (Failed to connect to the remote Jupyter Server 'https://jupyterhub.hpc.ucar.edu/'. Verify the server is running and reachable. (JupyterHub server no longer running at /user/<username>/api/kernels. Restart the server at https://jupyterhub.hpc.ucar.edu/stable/hub/spawn/<username>).).
    > at ou.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:252:2791)
    > url = https://jupyterhub.hpc.ucar.edu/stable/user/<username>/
    > serverProviderHandle = [object Object]
    > originalError = Error: Failed to connect to the remote Jupyter Server 'https://jupyterhub.hpc.ucar.edu/'. Verify the server is running and reachable. (JupyterHub server no longer running at /user/<username>/api/kernels. Restart the server at https://jupyterhub.hpc.ucar.edu/stable/hub/spawn/<username>).
    > baseUrl = https://jupyterhub.hpc.ucar.edu/
20:33:25.646 [warn] Could not fetch kernels from the remote server, falling back to cache: Error: JupyterHub server no longer running at /user/<username>/api/kernels. Restart the server at https://jupyterhub.hpc.ucar.edu/stable/hub/spawn/<username>
20:33:25.646 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4518)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:20060)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17959]
20:33:25.667 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4518)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:20060)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485]
20:33:25.677 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4518)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]
20:33:25.743 [error] Error fetching kernels from https://jupyterhub.hpc.ucar.edu/stable/user/<username>/ (JupyterHub-heavy3): [r [Error]: JupyterHub server no longer running at /user/<username>/api/kernels. Restart the server at https://jupyterhub.hpc.ucar.edu/stable/hub/spawn/<username>
	at r.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4914)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:19197)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyterhub.hpc.ucar.edu/stable/hub/user/<username>/api/kernels?1707708805668',
      status: 424,
      statusText: 'Failed Dependency',
      headers: [p [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
20:33:25.744 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4518)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:20060)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485]
20:33:25.744 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [r [Error]: JupyterHub server no longer running at /user/<username>/api/kernels. Restart the server at https://jupyterhub.hpc.ucar.edu/stable/hub/spawn/<username>
	at r.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4914)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:19197)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyterhub.hpc.ucar.edu/stable/hub/user/<username>/api/kernels?1707708805668',
      status: 424,
      statusText: 'Failed Dependency',
      headers: [p [Headers]],
      counter: 1
    }
  },
  traceback: ''
}
20:33:25.746 [warn] Disposing old controller connectToLiveRemoteKernel:'2a7c5de6-305c-4b3a-a993-6de5691e5dc7' for view = 'jupyter-notebook'
20:33:25.747 [warn] Disposing old controller connectToLiveRemoteKernel:'2a7c5de6-305c-4b3a-a993-6de5691e5dc7 (Interactive)' for view = 'interactive'
20:33:25.747 [info] End refreshing Kernel Picker (1707708787458)
20:35:55.017 [error] Error fetching kernels from https://jupyterhub.hpc.ucar.edu/stable/user/<username>/ (JupyterHeavy1): [r [Error]: Forbidden
	at r.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4914)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:19197)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyterhub.hpc.ucar.edu/stable/user/<username>/api/kernels?1707708954963',
      status: 403,
      statusText: 'Forbidden',
      headers: [p [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
20:35:55.037 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [r [Error]: Forbidden
	at r.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4914)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:19197)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyterhub.hpc.ucar.edu/stable/user/<username>/api/kernels?1707708954963',
      status: 403,
      statusText: 'Forbidden',
      headers: [p [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
20:35:55.038 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4518)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:20060)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485]
20:35:55.039 [info] End refreshing Kernel Picker (1707708787458)
20:36:14.259 [error] Error fetching kernels from https://jupyterhub.hpc.ucar.edu/stable/user/<username>/ (JupyterHub-32G): [r [Error]: Forbidden
	at r.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4914)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:19197)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyterhub.hpc.ucar.edu/stable/user/<username>/api/kernels?1707708974199',
      status: 403,
      statusText: 'Forbidden',
      headers: [p [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
20:36:14.277 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache [r [Error]: Forbidden
	at r.create (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:1006)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Object.Rl [as listRunning] (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:4507)
	at async r.getRunningKernels (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4914)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:19197)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485] {
  response: p [Response] {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'https://jupyterhub.hpc.ucar.edu/stable/user/<username>/api/kernels?1707708974199',
      status: 403,
      statusText: 'Forbidden',
      headers: [p [Headers]],
      counter: 0
    }
  },
  traceback: ''
}
20:36:14.277 [error] Jupyter Lab Helper:getKernelSpecs failure:  [Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
	at v.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:10935)
	at ni.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/node_modules/@jupyterlab/services.js:11:29299)
	at r.dispose (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:139:4518)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async Promise.all (index 0)
	at async VD.listKernelsFromConnection (~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:20060)
	at async ~/.vscode-server/extensions/ms-toolsai.jupyter-2024.1.1-linux-x64/dist/extension.node.js:249:17485]
20:36:14.279 [info] End refreshing Kernel Picker (1707708787458)
```

**Comment by DonJayamanne** [comment] 2024-02-12 07:01
Duplicate of https://github.com/microsoft/vscode-jupyter-hub/issues/39

**Closed by DonJayamanne** 2024-02-12 07:01 UTC
Labels: bug
