### ISSUE TITLE
Jupyter cell running, cannot work on second script because Pylance doesn't see new dependencies

### ISSUE THREAD

**Issue by RobRoseKnows** [microsoft/vscode-jupyter#8912] opened 2022-02-02 18:49 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Idk if this is a problem with Pylance or with Jupyter, but it was pretty annoying. Essentially pylance isn't seeing new packages installed since I started running a cell, so autocomplete and such isn't working for the new packages.

1. Start a long running cell (I used .py files with #%% markers)
2. Create a new script in a new file.
3. pip install a new dependency, while the Long running cell is still running.
4. Try to import the cell in the new script, pylance will say the new pacakge could not be resolved.

Pylance version: v2022.1.5

### VS Code Version

Version: 1.63.2 Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3 Date: 2021-12-15T09:38:17.605Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Darwin arm64 21.2.0

### Jupyter Extension Version

v2021.11.1001550889

### Coding Language and Runtime Version

Python v3.9.7

### Language Extension Version (if applicable)

v2021.12.1559732655

### Anaconda Version (if applicable)

4.10.3

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment] 2022-02-02 18:58
Thanks for the bug. 

This is actually a dupe of https://github.com/microsoft/pylance-release/issues/2246

**Closed by rchiodo** 2022-02-02 18:58 UTC
Labels: bug, needs-triage
