### ISSUE TITLE
Inputs and outputs of previously-executed cells in interactive window not showing

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#12743] opened 2023-02-06 04:09 UTC
Executing cells in the interactive window is successful in the sense that the code runs and variables created are available in the running session, however the inputs and outputs of executed cells seem to disappear when I scroll back to look at them. Here is an example of what I'm seeing:

<img width="616" alt="Screenshot 2023-02-05 at 9 54 24 PM" src="https://user-images.githubusercontent.com/81476/216881318-12431093-7835-4b47-b5fd-46699923432d.png">

I have attempted to resize the window, restart VSCode and restart my machine, but none of these resolve the issue.

## Environment data

-   VS Code version: 1.75.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2000312134
-   Python Extension version (available under the Extensions sidebar): v2023.3.10341119
-   OS (Windows | Mac | Linux distro) and version: MacOS 13.1
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: local

## Expected behaviour

Output and input of previously executed cells should be available

## Actual behaviour

Output and input of previously executed cells cannot be seen

**Comment by fonnesbeck** [comment] 2023-02-06 04:26
This appears to be related to updating VSCode to v1.75, as it is occurring now on other machines after the upgrade (Windows as well as MacOS).

**Comment by fonnesbeck** [comment] 2023-02-06 04:36
Can confirm: reverting VSCode to v1.74 resolves the issue.

**Comment by moritzwilksch** [comment] 2023-02-06 07:41
I'm having the same issue on Windows and Mac since v1.75. I have yet to figure out a pattern to reliably reproduce this bug. So far, it just seems to start happening after some time.

**Comment by amunger** [comment] 2023-02-06 19:09
duplicate of https://github.com/microsoft/vscode/issues/173590

**Closed by amunger** 2023-02-06 19:09 UTC
Labels: bug
