### ISSUE TITLE
Trusted Notebook + .NET Interactive : User unable to trust notebook 

### ISSUE THREAD

**Issue by LadyNaggaga** [microsoft/vscode-jupyter#5950] opened 2021-05-21 12:37 UTC
Jupyter Ext version - v2021.6.832593372
.NET interactive version - 1.0.225602+88e6d92f1cf8ead1c4c0b982e67b4a63902e00e6
VS Code Stable: 1.56.2

## Expected behaviour
Click on the Trusted Notebook icon and get the pop up window to trust notebook 

## Actual behaviour

No action when you click on the trusted notebook icon.  See image below 
![trust-notebook](https://user-images.githubusercontent.com/2546640/119137595-f7861480-ba0e-11eb-9ac7-954796bccb2b.gif)

**Comment by claudiaregio** [comment] 2021-05-21 15:42
Dupe of https://github.com/microsoft/vscode-jupyter/issues/5546

**Closed by claudiaregio** 2021-05-21 15:42 UTC
Labels: bug
