### ISSUE TITLE
Do not use environment APIs if the workspace is not trusted

### ISSUE THREAD

**Issue by bpops** [microsoft/vscode-jupyter#12925] opened 2023-02-23 00:53 UTC
Type: <b>Bug</b>

I am having an issue on a M2 Mac (if that matters) wherein I install a fresh copy of VSCode (even deleting ~/Library/Application Support/Code and ~/.vscode to make sure clean), and verify the python notebooks work correctly. But then, if I close VSCode and reopen a notebook, it will never again find a python kernel.

Steps to Recreate:
1. Download/Drag VSCode into Applications folder and open.
2. Install Microsoft Python Extension
3. Create New Jupyter Notebook
4. Immediately see that the Python 3.11.1 kernel is already selected at the top right of the window.
5. Close VSCode completely. 
6. Reopen and create new Jupyter notebook. See that it still works again in discovering kernel.
7. But now, save that notebook. 
8. Close VSCode.
9. Open that ipynb in VSCode.
10. See that the kernel button now just says “Select Kernel”
<img width="298" alt="Screenshot 2023-02-22 at 6 43 03 PM" src="https://user-images.githubusercontent.com/4554630/220797075-bb0386d2-bb3c-441a-93e8-fd27fea134d2.png">
12. If I click, there are no kernel options available.
13. Next, try Python > Select Interpreter, get a “Command ‘Python: Select Interpreter’ resulted in an error (command ‘python.setInterrpreter’ not found)

<img width="300" alt="Screenshot 2023-02-22 at 6 43 23 PM" src="https://user-images.githubusercontent.com/4554630/220797093-26060385-55ba-47f8-9b4b-243efad4c933.png">

By the way, I have tested this with both Python 3.11 and 3.8. The issue is agnostic of the python version.

Extension version: 2023.2.0
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:34:01.965Z)
OS version: Darwin arm64 22.3.0
Modes: Restricted
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id 3191161d-4d44-47e8-826e-c64eb519ba84|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
3biah626:30602489
pyind779:30662992
f6dab269:30613381
pythonsymbol12cf:30657549
2i9eh265:30646982

```

</details>

**Comment by DonJayamanne** [comment] 2023-02-24 03:00
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by bpops** [comment] 2023-02-24 03:12
Here is the result: 

```
Visual Studio Code (1.75.1, undefined, desktop)
Jupyter Extension Version: 2023.1.2010391206.
Python Extension Version: 2023.2.0.
No workspace folder opened.
warn 21:09:19.533: Exception while attempting zmq : No native build was found for platform=darwin arch=arm64 runtime=electron abi=106 uv=1 armv=8 libc=glibc node=16.14.2 electron=19.1.9
    loaded from: /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/node_modules/zeromq

User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
debug 21:09:19.605: Updating cache with Python kernels 
, Added = 
, Updated = 
, Removed = 
debug 21:09:19.605: Get Custom Env Variables, Class name = bc (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
debug 21:09:19.605: Start refreshing Kernel Picker (1677208159605)
debug 21:09:19.605: Get Active Interpreter, Class name = ls (started execution), Arg 1: undefined
info 21:09:19.607: LSP Notebooks experiment is enabled
debug 21:09:19.607: Get Active Interpreter, Class name = ls (started execution), Arg 1: undefined
debug 21:09:19.610: Get Custom Env Variables, Class name = bc, completed in 5ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
debug 21:09:19.611: Get Jupyter Sub Paths, Class name = Lu, completed in 6ms, has a truthy return value, Arg 1: "", Arg 2: "kernels", Return Value: 
debug 21:09:19.612: Get Jupyter Kernel Paths, Class name = Lu, completed in 6ms, has a truthy return value, Arg 1: "", Return Value: 
debug 21:09:19.612: Get KernelSpec root path, Class name = Lu, completed in 7ms, has a truthy return value, Arg 1: {"a":false,"b":null}, Return Value: <Uri:/usr/share/jupyter/kernels>, <Uri:/usr/local/share/jupyter/kernels>, <Uri:/Users/me/Library/Jupyter/kernels>
debug 21:09:19.619: Not Searching for kernels as path does not exist, /usr/share/jupyter/kernels
debug 21:09:19.619: Not Searching for kernels as path does not exist, /usr/local/share/jupyter/kernels
debug 21:09:19.619: Not Searching for kernels as path does not exist, /Users/me/Library/Jupyter/kernels
debug 21:09:19.620: No controller, hence notebook communications cannot be initialized for editor /Users/me/Desktop/test.ipynb
debug 21:09:19.667: Get Active Interpreter, Class name = ls (started execution), Arg 1: undefined
debug 21:09:19.667: Get Active Interpreter, Class name = ls (started execution), Arg 1: undefined
warn 21:09:19.667: Failed to get active interpreter from Python for workspace  [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1759262]
warn 21:09:19.668: Failed to get active interpreter from Python for workspace  [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1759262]
warn 21:09:19.668: Failed to get active interpreter from Python for workspace  [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1759262]
warn 21:09:19.668: Failed to get active interpreter from Python for workspace  [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1759262]
error 21:09:19.668: Get Active Interpreter, Class name = ls, completed in 63ms, has a falsy return value, Arg 1: undefined, Return Value: undefined [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1759262]
error 21:09:19.668: Get Active Interpreter, Class name = ls, completed in 61ms, has a falsy return value, Arg 1: undefined, Return Value: undefined [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1759262]
debug 21:09:19.668: Full interpreter list after refreshing (total 1ms, resolve 1ms, refresh 0ms) is length: 4, /usr/bin/python3:undefined::/usr/bin/python3:/usr/bin/python3, /usr/local/bin/python3:undefined::/usr/local/bin/python3:/usr/local/bin/python3, /usr/local/bin/python3.11:undefined::/usr/local/bin/python3.11:/usr/local/bin/python3.11, /usr/local/bin/python3.9:undefined::/usr/local/bin/python3.9:/usr/local/bin/python3.9
error 21:09:19.668: Get Active Interpreter, Class name = ls, completed in 1ms, has a falsy return value, Arg 1: undefined, Return Value: undefined [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1759262]
error 21:09:19.668: Get Active Interpreter, Class name = ls, completed in 1ms, has a falsy return value, Arg 1: undefined, Return Value: undefined [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1759262]
error 21:09:19.668: Failed to get env details from Python API for /usr/bin/python3 [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1763575
    at Array.map (<anonymous>)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1763527]
error 21:09:19.668: Failed to get env details from Python API for /usr/local/bin/python3 [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1763575
    at Array.map (<anonymous>)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1763527]
error 21:09:19.668: Failed to get env details from Python API for /usr/local/bin/python3.11 [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1763575
    at Array.map (<anonymous>)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1763527]
error 21:09:19.668: Failed to get env details from Python API for /usr/local/bin/python3.9 [Error: Not allowed to resolve environment in an untrusted workspace
    at Object.resolveEnvironment (/Users/me/.vscode/extensions/ms-python.python-2023.2.0/out/client/extension.js:2:549390)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1763575
    at Array.map (<anonymous>)
    at /Users/me/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/out/extension.node.js:2:1763527]
debug 21:09:19.668: Refreshed Environments
debug 21:09:19.669: Full interpreter list is length: 0, 
debug 21:09:19.669: Refreshed Environments
debug 21:09:20.669: End refreshing Kernel Picker (1677208159605)
info 21:09:32.733: Loading webview. View is notset
info 21:09:32.733: Loading web view...
info 21:09:32.734: Webview panel created.
info 21:09:32.884: Web view react rendered
```

**Comment by DonJayamanne** [comment] 2023-02-24 04:43
* Please install latest VS Code Insiders
* Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`
* Similarly please install the latest `Pre-Release` version of the Python extension

let me know if that works

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

**Comment by bpops** [comment] 2023-02-25 00:23
Ok, I installed VSCode Insiders edition. I installed the pre-release version of Jupyter, then the pre-release version of the Python extension. But unfortunately, the issue persists. When I made the first notebook, it successfully detected the python kernel, but after closing VSCode and reopening, it did not find the Python kernel. I was able to click "Select Kernel" and "Python Environments" and "Python 3.11" once. I closed and reopened again, and then it never can find another kernel. See below:

<img width="763" alt="Screenshot 2023-02-24 at 6 19 10 PM" src="https://user-images.githubusercontent.com/4554630/221324648-969d3ca5-2df2-4206-af7e-d2176cc3886f.png">
<img width="745" alt="Screenshot 2023-02-24 at 6 19 36 PM" src="https://user-images.githubusercontent.com/4554630/221324657-11992d15-b627-46e6-aba5-4ac36207e182.png">
<img width="745" alt="Screenshot 2023-02-24 at 6 20 10 PM" src="https://user-images.githubusercontent.com/4554630/221324663-d42a3aea-13ae-4cc0-b3a3-65970dea9b0e.png">

**Comment by karrtikr** [comment] 2023-02-25 01:17
The error says the workspace is untrusted, can you make sure to run the 'manage trust' command to trust the workspace first?

**Comment by bpops** [comment] 2023-02-25 01:23
I thought I had trusted, but I must have been mistaken. When I explicitly trust this folder the python environment is not auto selected, but it is selectable when I "Select Kernel" and "Python Environment". Is this the intended behavior? (I'm happy with this, thank you!)

**Comment by karrtikr** [comment] 2023-02-25 01:38
Yes, that's intended behavior, I think Jupyter removed auto-selection. I'm transferring this to Jupyter to not use the environment APIs when a workspace is not trusted (or surface that a user needs to trust the workspace first before accessing environments).

**Comment by bpops** [comment] 2023-02-25 01:39
Thanks @karrtikr , appreciate all the help.

**Comment by DonJayamanne** [comment] 2023-02-27 03:17
Closing this issue as this is the expected behaviour
I.e. Python environments might not be displayed if a workspace is not trusted

**Closed by DonJayamanne** 2023-02-27 03:17 UTC
