### ISSUE TITLE
In editor selection of install package buffer is not able to be selected

### ISSUE THREAD

**Issue by Rubix982** [microsoft/vscode-jupyter#5698] opened 2021-04-29 19:00 UTC
## Environment data

-   VS Code version: 1.55.2, 3c4e3df9e89829dce27b7b5c24508306b151f30d, x64
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.745244803
-   Python Extension version (available under the Extensions sidebar): 3.8.5
-   OS (Windows | Mac | Linux distro) and version: Linux saif-kubuntu 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
-   Python and/or Anaconda version: 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local

## Expected behavior

- Allows selecting the confirmation button

## Actual behavior

- Buffer does not detect keyboard input

## Steps to reproduce:

1. Create a new Conda environment
2. Create a new jupyter notebook - ipynb file
3. Open that with Visual Studio Code
4. Attempt to install a new package via the Ipython terminal, for example, `!conda install spacy`
5. See buffer not being able to be selected for the confirmation. Basically, it's not possible to enter 'y' for this prompt here in the notebook itself.

![image](https://user-images.githubusercontent.com/41635766/116401131-4d1e3580-a844-11eb-9e7a-76ee3b43b544.png)

## Logs

Not needed

**Comment by DonJayamanne** [comment] 2021-04-29 19:38
Thanks for filing this issue, unfortunately this is a known issue in Jupyter.
Dupe of https://github.com/microsoft/vscode-jupyter/issues/1625

**Closed by DonJayamanne** 2021-04-29 19:38 UTC
Labels: bug

**Comment by Rubix982** [comment] 2021-04-29 19:44
Acknowledged.
