### ISSUE TITLE
Test Connecting to Remote Jupyter Server with/without Passwords/Tokens in insiders.vscode.dev

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13766] opened 2023-06-26 07:26 UTC
Test Connecting to Remote Jupyter Server with/without Passwords/Tokens

Refs: #13631

- [x] web @sandy081
- [x] anyOS @rebornix 
- [x] anyOS @rzhao271

Complexity: 3

Authors: @DonJayamanne 

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2313766%0A%0A&assignees=DonJayamanne)

---

### Requirements

- Have a Python environment installed
- Familiarity launching Jupyter Notebooks Application outside VS Code

### Instructions

- Run jupyter with the following command line 
  `python -m jupyter notebook --no-browser --NotebookApp.allow_origin='*'`  
  Note the URL it generates for connecting
    - Also see [general setup instructions](https://github.com/microsoft/vscode-jupyter/wiki/Install-and-Setup-Jupyter-Notebook-Lab-for-Testing)   

- Open VS Code
- Add the following to the user settings file
```jsonc
	"jupyter.experiments.enabled": true,
	"jupyter.experiments.optInto": [ "PasswordManager" ],
	"jupyter.experiments.optOutFrom": []
```
- Make sure Jupyter prerelease extension is installed
- Open a notebook and connect to the above Jupyter server via the Kernel Picker
    - Open the kernel picker, select `Select Another Kernel -> Existing Jupyter Server` and enter the above URL
 
- Select a Python kernel and verify you can run a cell with the text `print("Hello World")`
- Start all over again with a Jupyter Server requiring a Password and verify it works (see [general setup instructions](https://github.com/microsoft/vscode-jupyter/wiki/Install-and-Setup-Jupyter-Notebook-Lab-for-Testing#options) for instructions for setting up with a Password)
- Start all over again with a Jupyter Server without a Password but with a Token (see [general setup instructions](https://github.com/microsoft/vscode-jupyter/wiki/Install-and-Setup-Jupyter-Notebook-Lab-for-Testing#options) for instructions)
- Try again with experiments disabled (please remember to re-load VS Code)

**Comment by sandy081** [comment] 2023-06-27 09:43
Tested in Web and it worked for all scenarios except `Start all over again with a Jupyter Server requiring a Password and verify it works (see [here](https://github.com/microsoft/vscode-jupyter/wiki/Install-and-Setup-Jupyter-Notebook-Lab-for-Testing#options) for instructions setting up with a Password )`

@DonJayamanne I have following suggestions for this TPI:

1. If you would like a person with Jupyter notebooks expertise to test this, I would pre-assign the testers you know of. 
2. If you want any person to test this, I would have the setup instructions more clear and verbose and set the complexity level to 4/5. TBH the instructions are not clear and allowing the tester to go and figure out him/herself to set up.

**Comment by DonJayamanne** [comment] 2023-06-27 10:15
> If you would like a person with Jupyter notebooks expertise to test this, I would pre-assign the testers you know of

Yes, thats why I have added the `Requirements` section in the TPI, this is something that was dicussed in the past.

> TBH the instructions are not clear and allowing the tester to go and figure out him/herself to set up.

These are the steps we have used in the past as well, and thats why I created a WIKI as well, to ensure we do not repeat the steps over & over and the `Requirements` section helps ensure we look for the right testers or they can swap it out

**Comment by DonJayamanne** [comment] 2023-06-27 10:25
Got it thanks, I think i should manually assign the TPI next time to avoid this in the future.

**Comment by rzhao271** [comment] 2023-06-27 18:48
I notice that Meghan and I are assigned to anyOS, but that there's the web subheading in the instructions. I'm unsure whether that means that part of the TPI is done on the web and part of it isn't, or whether it means something else.

**Comment by DonJayamanne** [comment] 2023-06-27 20:03
Sorry my mistake, shouldn’t be web

**Comment by rebornix** [comment] 2023-06-27 22:45
It works locally in Insiders but it doesn't work on Web. However I can reproduce this on VS Code stable on Web, so not a regression. It might be because that `NotebookApp.allow_origin` is not working for password support in Jupyter Server.

**Closed** 2023-06-28 04:33 UTC
Labels: testplan-item
