### ISSUE TITLE
Detecting Kernels never stops spinning

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#15422] opened 2024-03-25 16:34 UTC
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Run `Create: new jupyter notebook`

**Bug**
The detecting kernels  spinner never stops

### VS Code Version

1.88

### Jupyter Extension Version

v2024.3.2024032501 (pre-release)

### Jupyter logs
```
Visual Studio Code - Insiders (1.88.0-insider, undefined, desktop)
Jupyter Extension Version: 2024.3.2024032501.
Python Extension Version: 2024.3.10851013.
Pylance Extension Version: 2024.3.101.
Platform: win32 (arm64).
No workspace folder opened.
09:27:22.031 [error] The API registerRemoteServerProvider has being deprecated and will be removed soon, please use createJupyterServerCollection (extension GitHub.codespaces).
09:27:23.177 [info] No interpreter for Pylance for Notebook URI "Untitled-1.ipynb"
```

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment] 2024-05-08 20:25
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15005

**Closed by DonJayamanne** 2024-05-08 20:25 UTC
Labels: bug
