### ISSUE TITLE
Loading widgets from remote Jupyter Server

### ISSUE THREAD

**Issue by Yuri6037** [microsoft/vscode-jupyter#14645] opened 2023-11-01 08:02 UTC
## Environment data

-   VS Code version: 1.83.1
-   Jupyter Extension version (available under the Extensions sidebar): 2023.10.1003011100
-   Python Extension version (available under the Extensions sidebar): 2022.15.12731017
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Anaconda 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Anaconda
-   Jupyter server running: Local

## Expected behaviour

Interactive matplotlib should work (%matplotlib widget) on a computer with NO Internet access, so no access to any external CDN/third party service.

I should add that interactive matplotlib works flawlessly from Microsoft Edge browser.

## Actual behaviour

I get error messages about CDN access and failed attempts (404) at downloading scripts from the Jupyter server.

## Steps to reproduce:

1. Get a computer which is completely disconnected, and has never been connected, to the Internet.
2. Load a Jupyter server with support for ipympl
3. Connect it from VSCode
4. Setup matplotlib with "%matplotlib widget"
5. Enjoy empty plots

## Logs

As the logs are on a machine disconnected from the Internet I can't easily extract any logs.

Only logs I have shows something about CDN access failed and failure to resolve URLs with URL formatting. The first errors are expected because there is no access to any CDN on that machine.

The other problem Is that it attempts to download scripts from `http://localhost:8888/nbextensions/%5C%5Cjupyter-matplotlib%5C%5Cextension.js`. That URL returns 404 all the time however if we remove URL formatting (`http://localhost:8888/nbextensions/jupyter-matplotlib/extension.js`), then the URL works.

Why is vscode-jupyter using bad URLs to download extensions from the local Jupyter server? Also why is there no option to let vscode-jupyter download from local file system instead of a CDN?

**Comment by Yuri6037** [comment] 2023-12-01 21:57
> Thank you for filing this sisue.
> 
> > Also why is there no option to let vscode-jupyter download from local file system instead of a CDN?
> 
> Since you are connected to a remote jupyter server, we have no idea whether its localhost or not. E.g. one can easily setup proxy servers / port forwarding and the like to make it look like servers are running locally, hence its impossible to determine whether its local or not. As a result, we do not fetch scripts from the local machine, except on CDN
> 
> I.e. when you use remote servers, (even if its localhost) we will always attempt to load the scripts from the server/CND.
> 
> I'm sorry but I'm closing this as out of scope.

Sorry but it's not simple to setup proxies on such machine. Why is it out of scope to provide a local directory where to place the downloaded content so that the extension does not have to fetch it from the internet? Is there no cache already, ie do you always re-download instead of using a cache? Which in this case means that no matter what you can't use this extension if you're offline even on a compute which sometimes may be connected to the internet?

**Comment by DonJayamanne** [comment] 2023-12-01 22:32
> Why is it out of scope to provide a local directory where to place the downloaded content so that the extension does not have to fetch it from the internet? Is there no cache already, ie do you always re-download instead of using a cache? 

This is not as simple as you make it sound
Each kernel can point to a different pythohn env, and each python environment can have different packages.
Each package has diferent versions, thus the JS files can be completely different for each version ...
This gets complicated when there are multiple packages at play here

Now trying to come up with a way to say, use this folder for this kernel with this version of python, and these versions of packages is not easy at all.
That thats a lot of work
Given the fact that we have not come across this issue in the past I am marking this as out of scope, as I do not see this being worth the effort to get it working

>  Is there no cache already, ie do you always re-download instead of using a cache? Which in this case means that no matter what you can't use this extension if you're offline even on a computer which sometimes may be connected to the internet?

Absolutely not, if you start kernels connecting to the Python environment it will work without any problems.
I.e. the root of the problem is you are starting jupyter server and connecting to that as though it was a remote server.
That feature exists so usersx can connec to remote servers, but in your case you are connecting to a local server, which isn't really necessary.

You can just go into the kernel picker and select the `Python Environment` or the `Juptyer Kernel` directly.
So, I would ask why aren't you trying that instead of starting jupyter locally, thats not a scenario that we have run into a lot.
I.e. its a edge case and not the majority use case.

> EDIT: You also seem to ignore the fact that your extension is using broken URLs on windows:

Sorry, I missed that, I will look into that

**Comment by DonJayamanne** [comment] 2023-12-01 22:32
> You also seem to ignore the fact that your extension is using broken URLs on windows:

re-opening this to address this issue.

**Comment by Yuri6037** [comment] 2023-12-04 03:59
> Please could you:
> 
> * Download the following VSIX (extract the zip)
> * Open VS Code use the command `Install from VSIX` and select the above extract file
> * When prompted to reload, then reload VS Code
> * Open settings & go into `Jupyter->Logging`
> * Change the value to `verbose`
> * Reload VS Code,
> * Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
> 
> This might fix it, if it doesn't, please do share the logs
> 
> [ms-toolsai-jupyter-insiders.vsix.zip](https://github.com/microsoft/vscode-jupyter/files/13540673/ms-toolsai-jupyter-insiders.vsix.zip)

Thank you for investigating, I'll try to do that but it may take quite some time as it's not simple to transfer files from the internet to the offline machine.

**Closed** 2023-12-11 04:23 UTC
Labels: bug, info-needed, ipywidgets
