### ISSUE TITLE
Console error after executing code cell

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#12560] opened 2023-01-17 23:06 UTC
## Environment data

-   VS Code version: XXXVersion: 1.75.0-insider (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2000141019
-   Python Extension version (available under the Extensions sidebar): v2023.1.10171013
-   OS (Windows | Mac | Linux distro) and version: Darwin arm64 22.2.0
-   Python and/or Anaconda version: Python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local

## Expected behaviour

Running a Python cell should not throw errors in the developer console.

## Actual behaviour

When I run a code cell, I get this error:

```
 TypeError: t._createParsedCallSite is not a function
    at map (/Users/XXX/node_modules/stack-trace/lib/stack-trace.js:91:19)
    at Array.map (<anonymous>)
    at Object.t.Qc (/Users/XXX/node_modules/stack-trace/lib/stack-trace.js:29:6)
    at Bs.determineExtensionFromCallStack (/Users/XXX/src/platform/common/application/extensions.node.ts:45:13)
    at Q_.getService (/Users/XXX/src/standalone/api/kernelApi.ts:39:44)
    at Object.getKernelService (/XXX/src/standalone/api/api.ts:70:41)
    at li.getKernelSession (/Users/XXX/.vscode-insiders/extensions/XXX/src/client/notebookOutputs/XXXHtmlRendererComms.ts:229:68)
    at li.handleShowLaunchButton (/Users/XXX/.vscode-insiders/extensions/ms-toolsai.XXX-0.0.625/src/client/notebookOutputs/XXXHtmlRendererComms.ts:92:46)
    at /Users/XXX/.vscode-insiders/extensions/ms-toolsai.XXX-0.0.625/src/client/notebookOutputs/XXXHtmlRendererComms.ts:210:39
    at h.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at p.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at u.$postRendererMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:98:95054)
    at o.N (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:11239)
    at o.M (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10957)
    at o.H (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:10044)
    at o.G (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:9022)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:106:7810
    at h.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at p.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14905)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:15815
    at h.invoke (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at p.deliver (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at d.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at g.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14905)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:122:13941)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)
    at Object.callbackTrampoline (node:internal/async_hooks:130:17) (at console.error (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:137642))
E @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:692
deliver @ event.ts:899
fire @ event.ts:860
fire @ ipc.net.ts:671
q.onmessage @ localProcessExtensionHost.ts:613
```

## Steps to reproduce:

@DonJayamanne has all the information 🙂

**Comment by DonJayamanne** [comment] 2023-01-17 23:09
Duplicate of #12550

**Closed by DonJayamanne** 2023-01-17 23:09 UTC
Labels: bug

**Comment by sadasant** [comment] 2023-01-18 00:14
@DonJayamanne I thought it wasn't the same issue?

**Comment by sadasant** [comment] 2023-01-18 00:15
Given that I can run `Jupyter: Specify Jupyter Server for Connections` without troubles...
