### ISSUE TITLE
Output for Bokeh/Holoviews not being displayed due to invalid default mime-type being selected for rendering

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#417] opened 2020-11-07 01:10 UTC
The default mimetype doesn't work for Bokeh plot. It loads after switching to the javascript mimetype.

![Bokeh](https://user-images.githubusercontent.com/26419852/98427653-d18cba00-2052-11eb-8aa2-744ccde7363f.jpg)

**Comment by smackesey** [comment] 2020-11-13 22:43
Not even switching MIME types works for me to get Bokeh plots in VS Code notebooks. A few questions:

- when is this renderer extension expected to be released?
- is there a dev version or some other workaround I can use now?
- Will the renderer extension also work for [holoviews](https://holoviews.org/) (which uses bokeh, but has a different mimetype of `application/vnd.holoviews_exec.v0+json`)?

**Comment by DonJayamanne** [comment] 2020-11-16 19:54
> when is this renderer extension expected to be released?

We will be releasing this shortly.

> Not even switching MIME types works for me to get Bokeh plots in VS Code notebooks. A few questions

You do not need the renderer extension to view Bokeh plots.
In all cells, if you have any message `No renderer could be found for application/vdn...+json`
Then please switch the mime type to `application/javascript` (if you have multiple cells, then please do that for all cells in order).

If that still does not work, please provide:
* Code sample
* Instrutions for insallation of any packages used.

**Comment by DonJayamanne** [comment] 2020-11-16 19:55
This issue is blocked on the upstream VS Code issue Upstream issue https://github.com/microsoft/vscode/issues/110750
(i.e. caused by VS Code)

**Comment by DonJayamanne** [comment] 2020-11-16 20:06
@smackesey 
I can confirm that holoviews works in the new editor.
* I tried the following notebook: https://holoviews.org/gallery/demos/bokeh/dropdown_economic.html
* When you execute the first cell, ensure you select the mime type `application/javascript` for both the outputs of the first cell.
* Then run the second cell (no output)
* Finally run the last cell
Once again, change the mime type. This time select `text/html`.
& it will work.

**Comment by smackesey** [comment] 2020-11-17 02:18
> You do not need the renderer extension to view Bokeh plots.
> In all cells, if you have any message No renderer could be found for application/vdn...+json
> Then please switch the mime type to application/javascript (if you have multiple cells, then please do that for all cells in order).

Still not working for me. I am just trying to execute the first three cells of the [`bokeh` quickstart](https://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/quickstart/quickstart.ipynb):

```
from bokeh.plotting import figure
from bokeh.io import output_notebook, show
output_notebook()
from numpy import cos, linspace
x = linspace(-6, 6, 100)
y = cos(x)
p = figure(width=500, height=500)
p.circle(x, y, size=7, color="firebrick", alpha=0.5)
show(p)
```

If I execute this in a cell and then switch the MIME type to `application/json`, I just get totally blank output.

Version info:
VS Code Insiders build: 2020-11-16T11:18:46.350Z (14 hrs ago)
Jupyter extension build: 2020.11.35841065

**Comment by DonJayamanne** [comment] 2021-01-06 17:28
Closing as this is now working, and we will be shipping the renderers with the Jupyter extension in the next release.

**Closed by DonJayamanne** 2021-01-06 17:28 UTC
Labels: bug, upstream-vscode
