### ISSUE TITLE
white background still fills entire output cell for matplotlib ipympl plots

### ISSUE THREAD

**Issue by User087** [microsoft/vscode-jupyter#13660] opened 2023-06-06 11:36 UTC
Note sure if this was supposed to have been covered by #7470, but when you set `%matplotlib ipympl` in the notebook to enable interactive plots rather than inline images, the white background in the resulting plot still covers the entire output area, rather than just the area immediately behind the figure.

**Comment by DonJayamanne** [comment] 2023-06-08 01:00
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7161
When using `ipympl` it ends up using IPyWidgets, hence a duplicate of above issue

**Closed by DonJayamanne** 2023-06-08 01:00 UTC
Labels: feature-request
