### ISSUE TITLE
Incorectly parced brackets in C# cells

### ISSUE THREAD

**Issue by Xotchkass** [microsoft/vscode-jupyter#16269] opened 2024-12-05 16:56 UTC
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Parser doesn't ignore bracket's within string literals, breaking bracket colorization and bracket pairing (is this correct term to use? 😅)
![Image](https://github.com/user-attachments/assets/2034e1a7-68ba-45d8-9576-fa7b6da2afe9)
![Image](https://github.com/user-attachments/assets/6e2b50bc-6862-47d1-bd25-fd8db7acbe95)

Doesn't happen in regular C# files.
![Image](https://github.com/user-attachments/assets/7641af03-22ef-4199-979a-3aae29d6fa6a)

Also in Python cells everything work just fine.
![Image](https://github.com/user-attachments/assets/04e07e91-0ee3-4ed0-85de-73e28e421b85)

### VS Code Version

1.95.3

### Jupyter Extension Version

v2024.10.0

### Jupyter logs

```shell

```

### Coding Language and Runtime Version

.NET 8.0

### Language Extension Version (if applicable)

C# Dev Kit v1.13.9 / C# v2.55.29 

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2024-12-11 07:47
Jupyter extension doesn't provide any language capabilities for C# code.
You might be using the Plotlygot Notebook Extension in VS Code or some other.
Unfortunately I'm not sure what extension it is that you are using, hence cannot offer any help, 
Closing as this isn't caused by Jupyter extension.

**Closed by DonJayamanne** 2024-12-11 07:47 UTC
Labels: bug, triage-needed
