### ISSUE TITLE
NO notebook document for 'file//*.ipynb'

### ISSUE THREAD

**Issue by otavio-silva** [microsoft/vscode-jupyter#15879] opened 2024-07-25 16:18 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

While running a Jupyter notebook on VSCode on Ubuntu WSL2, the kernel randomly dies and gives the error `NO notebook document for 'file://*.ipynb'`. It always happens but I don't know exactly how to reliably reproduce.

### VS Code Version

1.91.1

### Jupyter Extension Version

v2024.6.0

### Jupyter logs

```shell
isual Studio Code (1.91.1, wsl, desktop)
Jupyter Extension Version: 2024.6.0.
Python Extension Version: 2024.10.0.
Pylance Extension not installed.
Platform: linux (x64).
Workspace folder ~/Documents/Code/Python/notebooks/Stable Diffusion XL, Home = /home/azakun
13:07:31.403 [info] Starting Kernel (Python Path: ~/miniforge3/envs/pt/bin/python, Conda, 3.11.9) for '~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb' (disableUI=true)
13:07:33.194 [info] Process Execution: ~/miniforge3/envs/pt/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
13:07:33.272 [info] Process Execution: ~/miniforge3/envs/pt/bin/python -m ipykernel_launcher --f=/home/~/.local/share/jupyter/runtime/kernel-v2-863EAzXr3jSa1xX.json
    > cwd: //home/~/Documents/Code/Python/notebooks/Stable Diffusion XL
13:07:33.280 [info] Process Execution: ~/miniforge3/envs/pt/bin/python -m pip list
13:07:33.979 [info] Kernel successfully started
13:07:33.983 [info] Process Execution: ~/miniforge3/envs/pt/bin/python /home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/pythonFiles/printJupyterDataDir.py
13:10:32.080 [info] Disposing request as the cell (0) was deleted ~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb
13:10:32.081 [info] Disposing request as the cell (1) was deleted ~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb
13:10:32.081 [info] Disposing request as the cell (2) was deleted ~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb
13:10:32.082 [info] Dispose Kernel '~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb' associated with '~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb'
13:10:32.088 [warn] Cancel all remaining cells due to dead kernel
```

### Coding Language and Runtime Version

Python 3.11.9

### Language Extension Version (if applicable)

Python v2024.10.0

### Anaconda Version (if applicable)

mamba 1.5.8 conda 24.5.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2024-07-25 23:34
Thank you for filing this issue and sorry you are running into this.
Can you try disabling `Auto Save` and ensure you are not `saving` while executing the notebook.
There is a known issue with Jupyter ntoebooks where kernels can shutdown due to changes in notebooks being saved while its being executed.
I'd like to determine whether this is the same scenario.

**Comment by otavio-silva** [comment] 2024-07-26 00:05
> Thank you for filing this issue and sorry you are running into this. Can you try disabling `Auto Save` and ensure you are not `saving` while executing the notebook. There is a known issue with Jupyter ntoebooks where kernels can shutdown due to changes in notebooks being saved while its being executed. I'd like to determine whether this is the same scenario.

I went to test this setting, Auto Save was already off. I'm not able to reproduce this error in a reliable/deterministic way, but it happens after the notebook is open and running for a while.

**Comment by DonJayamanne** [comment] 2024-07-26 00:10
> 13:10:32.080 [info] Disposing request as the cell (0) was deleted ~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb
13:10:32.081 [info] Disposing request as the cell (1) was deleted ~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb
13:10:32.081 [info] Disposing request as the cell (2) was deleted ~/Documents/C


Based on the logs the cells were deleted. You are not deleting them, its just a side effect of a problem we've found in VS Code.
And this is a manifestation of users saving notebooks. Hence the suggestion (possible you were editing it and hit `save`)
Or you have some other extension installed thats causing this.

E.g. we've found some extensions can cause issues, hence my suggestion is to then try disabling all extensions except for Jupyter & Python extensions, just for now (if you cannot repro it, then we know its definitely caused by another extension & we can go from there).

**Comment by otavio-silva** [comment] 2024-07-26 00:26
> > 13:10:32.080 [info] Disposing request as the cell (0) was deleted ~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb
> > 13:10:32.081 [info] Disposing request as the cell (1) was deleted ~/Documents/Code/Python/notebooks/Stable Diffusion XL/StableDiffisionXL.ipynb
> > 13:10:32.081 [info] Disposing request as the cell (2) was deleted ~/Documents/C
> 
> Based on the logs the cells were deleted. You are not deleting them, its just a side effect of a problem we've found in VS Code. And this is a manifestation of users saving notebooks. Hence the suggestion (possible you were editing it and hit `save`) Or you have some other extension installed thats causing this.
> 
> E.g. we've found some extensions can cause issues, hence my suggestion is to then try disabling all extensions except for Jupyter & Python extensions, just for now (if you cannot repro it, then we know its definitely caused by another extension & we can go from there).

I can't reproduce it now, having only the Jupyter extensions with Python, Python Debugger (uninstalled Pylance) and Remote - WSL.

**Comment by DonJayamanne** [comment] 2024-07-29 04:33
Lets closing this issue for now, if you do, please try replicating with all extension except for Jupyter and Python

**Closed by DonJayamanne** 2024-07-29 04:33 UTC
Labels: bug, info-needed, notebook-kernel
