### ISSUE TITLE
when stepping through a different cell than the one that started debugging, clicking run will deadlock the kernel

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#15009] opened 2024-01-11 18:03 UTC
1. set a break point in a function in cell 1
2. call that function from cell 2
3. debug cell 2 and wait for it to hit the breakpoint
4. click run on cell 1
:bug: kernel seems to be stuck

we should disable the run button if already debugging. I thought this was already the case.

**Comment by DonJayamanne** [comment] 2024-12-10 06:31
Closing this issue, as the cell execution does get queued, and the Run button turns into a `stop` button, meaning it can be intterrupted/stopped.
Also this means the cell execution has been queued, 

Hence disabling might not be right, as we're queueing it,
Also possible user might want to queue instead of having to wait for debug to complete.

Closing this as kernel isn't stuck, but debugger has paused and this is by design.

**Closed by DonJayamanne** 2024-12-10 06:31 UTC
Labels: bug, papercut :drop_of_blood:
