### ISSUE TITLE
Incorrectly lints magic %%kql cells as Python

### ISSUE THREAD

**Issue by alexchandel** [microsoft/vscode-jupyter#8819] opened 2022-01-26 20:30 UTC
## Environment data

Not particularly important.

-   VS Code version: 1.63.2/latest
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001550889
-   Python Extension version (available under the Extensions sidebar): v2021.12.1559732655
-   OS (Windows | Mac | Linux distro) and version: Win 10 + mac
-   Python and/or Anaconda version: Python 3.9 & 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Expected behaviour

A Jupyterlab cell marked `Python` with a `%%kql` block should not have the text below the `%%kql` block linted as erroneous Python. `%%kql` is used with [Kqlmagic](https://github.com/microsoft/jupyter-Kqlmagic).

## Actual behaviour

The multiline magic is incorrectly linted as erroneous Python.  KQL is Azure's Log Analytics query language.  Microsoft needs to support it in notebooks.

## Steps to reproduce:

1. Create a notebook.
2. Add a Python code cell.  (`Python` is necessary)
3. Add some KQL
```Python
%%kql
let _name = "foo";
```

Installing any of the KQL VSCode extensions (e.g. `kuskus`) doesn't help.

## Logs

N/A

**Comment by DonJayamanne** [comment] 2022-01-26 20:57
@alexchandel 
Please try installing this extesnsion for now https://marketplace.visualstudio.com/items?itemName=donjayamanne.kusto
This extension will update the cells with the `%%kql` magics accordingly (to `kql` language instead of `python`)

Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/4588

**Closed by DonJayamanne** 2022-01-26 20:57 UTC
Labels: bug, needs-triage
