### ISSUE TITLE
same method name appears twice and redundant object name in pylance auto completion 

### ISSUE THREAD

**Issue by hanmala123** [microsoft/vscode-jupyter#6785] opened 2021-07-23 09:53 UTC
## Environment data

- VSCode version: 1.59.0-insider (system setup)
-   Language Server version: pylance v2021.7.5
-   OS and version: Windows 10 19043.1110
-   Python version (& distribution if applicable, e.g. Anaconda): miniconda

## Expected behaviour

no redundant method name and object name
## Actual behaviour
![111](https://user-images.githubusercontent.com/35035210/126764708-866ed43a-1d12-4802-b18c-a607b7567fe1.png)
same method name appears twice（tobitmap and im.tobitmap is same method)

![222](https://user-images.githubusercontent.com/35035210/126764822-de0d03b9-793f-4c1a-ab17-9b002644969e.png)
when press tab or enter, it will add redundant object name in editor

## Code Snippet / Additional information
this problem happens in any python code

**Comment by claudiaregio** [comment] 2021-07-25 04:41
Dupe of https://github.com/microsoft/vscode-jupyter/issues/5956

**Closed by claudiaregio** 2021-07-25 04:41 UTC
Labels: needs-triage
