### ISSUE TITLE
Linux VSCode  Failed to run jupyter as observable with args notebook --no-browser --notebook-dir

### ISSUE THREAD

**Issue by Xinchengzelin** [microsoft/vscode-jupyter#8297] opened 2021-11-18 05:55 UTC
## Environment data

-   VS Code version: 1.62.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): 3.7.6
-   OS (Windows | Mac | Linux distro) and version: Linux
-   Python and/or Anaconda version: 4.5.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | N/A: local

[XXX](https://stackoverflow.com/questions/70002453/vscode-ssh-remote-jupyter-notebook-couldnt-run)

I want to use a linux computer as my remote server,but I don't know linux at all. Now I can connect to the server（Linux） by VSCode, but the Jupyter notebook couldn't run, which shows the error as follows:

'''
Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py", line 54, in _decorator
    return func(self, *args, **kwargs)
  File "/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 108, in m_exec_module_observable
    self._start_notebook(args, cwd, env)
  File "/root/.vscode-server/extensions/ms-toolsai.jupyter-2021.10.1101450599/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py", line 162, in _start_notebook
    app.launch_new_instance()
  File "/root/anaconda3/envs/tf2/lib/python3.7/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/root/anaconda3/envs/tf2/lib/python3.7/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/root/anaconda3/envs/tf2/lib/python3.7/site-packages/notebook/notebookapp.py", line 2292, in start
    self.exit(1)
  File "/root/anaconda3/envs/tf2/lib/python3.7/site-packages/traitlets/config/application.py", line 836, in exit
    sys.exit(exit_status)
SystemExit: 1

[C 09:14:43.602 NotebookApp] 不建议以root身份运行.使用--allow-root绕过过.

Failed to run jupyter as observable with args notebook --no-browser --notebook-dir="/root/xuzelin" --config=/tmp/10d15ad5-c73e-4523-94bf-c6b256ed102b/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0

'''

When I Open code, Open any .ipynb file., Run the code cell  

[stackoverflow](https://stackoverflow.com/questions/70002453/vscode-ssh-remote-jupyter-notebook-couldnt-run)

**Comment by IanMatthewHuff** [comment] 2021-11-18 20:03
Looks like this issue here: https://github.com/microsoft/vscode-jupyter/issues/739. Are you running as root on the remote machine? The best fix would be to run as a non-root user.

**Comment by greazer** [comment] 2021-11-18 21:28
Closing as dupe of #739

**Closed by greazer** 2021-11-18 21:28 UTC
Labels: bug, needs-triage

**Comment by Xinchengzelin** [comment] 2021-11-19 01:21
> Looks like this issue here: #739. Are you running as root on the remote machine? The best fix would be to run as a non-root user.

Thank you, but how should I run jupyter as a non-root user? Please forgive me, I'm fresh

**Comment by IanMatthewHuff** [comment] 2021-11-19 17:26
@Xinchengzelin Sorry I wish that I could help more with that, but I'm not a Linux expert myself. I can really only help with the Jupyter extension for VS Code. How you set up that remote machine can vary quite a bit between linux distributions. I would say that if you connect as root instructions like this might help with getting a non-root user added.

https://www.lifewire.com/create-users-useradd-command-3572157#:~:text=How%20to%20Create%20a%20User%20in%20Linux%201,when%20creating%20a%20user%20in%20Linux.%20See%20More.
