### ISSUE TITLE
Annoying survey keeps reappearing every 10 mins

### ISSUE THREAD

**Issue by RakeshChandran** [microsoft/vscode-jupyter#4044] opened 2020-11-30 08:07 UTC
A user experience survey for Jupyter Extension keeps reappearing even after submitting it twice and saying 'No Thanks' on subsequent pop-ups. It happens on VS Code start-up and almost after every 10 minutes of usage. Please fix this.
Version: v2020.11.372831992

**Comment by larsch** [comment] 2020-11-30 08:36
Duplicate of #4034

**Closed** 2020-11-30 16:33 UTC
