### ISSUE TITLE
Delete Cell icon (Jupyter Notebook) is gone in VS Code 1.74.0

### ISSUE THREAD

**Issue by EduardoNigro** [microsoft/vscode-jupyter#12358] opened 2022-12-08 16:03 UTC
## Environment data

-   VS Code version: 1.74.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.11.1003412109
-   Python Extension version (available under the Extensions sidebar): v2022.20.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise - OS Build 19043.2251
-   Python and/or Anaconda version: Python 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N.A.
-   Jupyter server running: Local

## Issue Description

After updating to VS Code 1.74.0, the "Delete Cell" icon that used to appear next to the "Copy Cell" and "Go to code" icons is gone! One could see the three icons when hovering the mouse over the top right corner of a Jupyter notebook cell. Now only the latter two icons show up.

## Screen shot
![Delete-Icon-Bug](https://user-images.githubusercontent.com/78741781/206497342-ce964c0d-d8ef-4e3e-919d-0b5f11bf0783.png)

**Comment by amunger** [comment] 2022-12-08 20:52
duplicate of https://github.com/microsoft/vscode/issues/168493

**Closed by amunger** 2022-12-08 20:52 UTC
Labels: bug

**Comment by EduardoNigro** [comment] 2022-12-12 14:16
Noted. Thanks. I hope the fix comes out soon.
