### ISSUE TITLE
Neverending Connecting to kernel

### ISSUE THREAD

**Issue by grostein** [microsoft/vscode-jupyter#8951] opened 2022-02-07 22:03 UTC
## Environment data

-   VS Code version: 1.64.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.1.1001775990
-   Python Extension version (available under the Extensions sidebar): v2022.1.1001775990
-   OS (Windows | Mac | Linux distro) and version: macOS 12.1
-   Python: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv 
-   Jupyter server running: Local 

## Actual behaviour

Neverending: Connecting to kernel: Python 3.9.10 64-bit: Waiting for Jupyter Session to be idle

## Steps to reproduce:

1. Run Jupyter  notebook

## Logs

<details>

<code>
To connect another client to this kernel, use:
    --existing /var/folders/9d/2gzgmcws2674tckqmb0khgsw0000gn/T/tmp-41392FF9h1QcZmNqq.json

Info 22:52:34: Raw session started and connected
Started kernel Python 3.9.10 64-bit
Info 22:52:34: Finished connecting 92e4b728-b996-4ee8-ac57-7d031c54d6a8
Warn 22:52:35: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/Users/mp/Library/Python/3.9/lib/python/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'
</code>
<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2022-02-08 03:43
Thanks for filing this issue, please could you provide the following information:
* Output from the `Jupyter` output panel

**Comment by grostein** [comment] 2022-02-08 12:00
```
Visual Studio Code (1.64.0, undefined, desktop)
Jupyter Extension Version: 2022.1.1001775990.
Python Extension Version: 2022.0.1786462952.
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 12:57:15: ZMQ install verified.
Info 12:57:16: Preferred kernel connection found in cache .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 12:57:16: PreferredConnection: .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher found for NotebookDocument: ~/Desktop/MinecraftML/main.ipynb
Info 12:57:16: Early registration of controller for Kernel connection .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 12:57:16: TargetController found ID: .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher for document ~/Desktop/MinecraftML/main.ipynb
Info 12:57:16: Setting controller affinity for ~/Desktop/MinecraftML/main.ipynb .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 12:57:16: Interrupt requested & no kernel.
Info 12:57:16: Setting setActiveController for ~/Desktop/MinecraftML/main.ipynb
Info 12:57:16: Getting activation commands for /usr/local/bin/python3 are not cached. May take a while.
Info 12:57:16: KernelProvider switched kernel to id = .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 12:57:16: Starting Notebook in kernel.ts id = .jvsc74a57bd0aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49./usr/local/bin/python3./usr/local/bin/python3.-m#ipykernel_launcher
Info 12:57:16: Creating raw notebook for ~/Desktop/MinecraftML/main.ipynb
Info 12:57:16: Getting preferred kernel for ~/Desktop/MinecraftML/main.ipynb
Info 12:57:16: Computing working directory ~/Desktop/MinecraftML/main.ipynb
Info 12:57:16: Starting raw kernel Python 3.9.10 64-bit
Info 12:57:16: installMissingDependencies /usr/local/bin/python3
Info 12:57:16: IPykernel found previously in this environment /usr/local/bin/python3
Info 12:57:16: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 12:57:16: No custom variables for Kernel as interpreter is not conda, but is Global
Info 12:57:16: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 12:57:16: Process Execution: > /usr/local/bin/python3 -m pip list
> /usr/local/bin/python3 -m pip list
Info 12:57:16: Process Execution: > /usr/local/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /usr/local/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 12:57:16: Process Execution: > /usr/local/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"c8b9438e-d91f-41a7-8573-272e7a91dc3d" --shell=9002 --transport="tcp" --iopub=9004 --f=/var/folders/9d/2gzgmcws2674tckqmb0khgsw0000gn/T/tmp-804O08WjWQ7ygbo.json
> /usr/local/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"c8b9438e-d91f-41a7-8573-272e7a91dc3d" --shell=9002 --transport="tcp" --iopub=9004 --f=/var/folders/9d/2gzgmcws2674tckqmb0khgsw0000gn/T/tmp-804O08WjWQ7ygbo.json
Info 12:57:16: Process Execution: cwd: ~/Desktop/MinecraftML
cwd: ~/Desktop/MinecraftML
Info 12:57:18: Creating controller for jupyter-notebook with interpreter /usr/local/bin/python3
Info 12:57:22: Registering dummy command feature
Info 12:57:30: ipykernel version 5.4.3 for /usr/local/bin/python3
Info 12:57:30: ipykernel location ~/Library/Python/3.9/lib/python/site-packages/ipykernel/__init__.py for /usr/local/bin/python3
Info 12:57:32: Kernel Output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing /var/folders/9d/2gzgmcws2674tckqmb0khgsw0000gn/T/tmp-804O08WjWQ7ygbo.json

Warn 12:57:32: Didn't get response for requestKernelInfo after 22ms.
Info 12:57:32: Raw session started and connected
Started kernel Python 3.9.10 64-bit
Info 12:57:32: Finished connecting 3a144aa5-95aa-41ec-a137-e63f250f2058
Warn 12:57:33: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/ipykernel/ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/ipykernel/ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/Users/massimilianop/Library/Python/3.9/lib/python/site-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'
```

**Comment by DonJayamanne** [comment] 2022-02-08 18:08
Thanks for filing this issue, please could you try re-installing ipykernel as follows:
`/usr/local/bin/python3 -m pip install ipykernel -U --fore-reinstall`

Looks like some of the dependencies are incompatible.

**Comment by grostein** [comment] 2022-02-08 19:57
Thanks! Worked!

**Comment by DonJayamanne** [comment] 2022-02-16 19:27
@KangMSPeter @grostein 
This issue has now been resolved and the fix is in the pre-release version (You can instlal the pre-release to get this fix now).
We'll be shipping a release today with this fix as well (so users using the stable version of the extension will get this fix)

**Comment by DonJayamanne** [comment] 2022-02-16 19:28
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/9014

**Closed by DonJayamanne** 2022-02-16 19:27 UTC
Labels: bug, info-needed, notebook-kernel

**Comment by brendanartley** [comment] 2023-01-31 22:11
> /usr/local/bin/python3 -m pip install ipykernel ipython -U --fore-reinstall

This worked great for me! Just a small spelling error in the command.

`/usr/local/bin/python3 -m pip install ipykernel ipython -U --force-reinstall`

**Comment by pratt3000** [comment] 2023-03-14 05:34
Didn't work for me. Has this been resolved yet?

**Comment by DonJayamanne** [comment] 2023-03-14 07:36
@pratt3000  pleat could you file a new issue with the details requested in the issue template (specially the logs)
