### ISSUE TITLE
Respect VSCode's telemetry setting

### ISSUE THREAD

**Issue by PeterJCLaw** [microsoft/vscode-jupyter#10934] opened 2022-07-26 16:11 UTC
## Environment data

-   VS Code version: 1.69.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.6.1201981810
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04 LTS

## Expected behaviour

When VSCode's telemetry preference is set to a restricted value (e.g: `off`, `crash`) the extension should not query for or send telemetry.

## Actual behaviour

I observed lines such as `printenv > /tmp/tmp-45935fdNhOTkd5hRYtxt` in my shell history and via https://twitter.com/ferrouswheel/status/1551353490949017600 traced this to having (hopefully!) come from this extension https://github.com/microsoft/vscode-jupyter/blob/545c0a7b00b073da4d73ed58bf6c49e0d31b7ee6/src/platform/terminals/helper.node.ts#L81-L93

I have `telemetry.telemetryLevel` set to `off` on the machine where this was observed.

Ideally the extension should not gather telemetry data outside the enabled telemetry remit.

**Comment by rchiodo** [comment] 2022-07-26 16:53
Thanks for the issue.

The data may be gathered but the way the code is setup, it isn't sent. Turning telemetry off doesn't affect the internal behavior of the extension, it merely prevents the data from being sent anywhere. 

We use this npm module to send our telemetry. It determines if the telemetry data is sent or not:
https://github.com/microsoft/vscode-extension-telemetry/blob/5d778578cb8484d3336549f2b6b667fa9f0411b1/src/common/baseTelemetryReporter.ts#L301

**Comment by r3m0t** [comment] 2022-07-27 16:25
It isn't telemetry, it's used in the code to launch your Jupyter kernels and Jupyter server.

https://github.com/microsoft/vscode-jupyter/blob/545c0a7b00b073da4d73ed58bf6c49e0d31b7ee6/src/kernels/raw/finder/jupyterPaths.node.ts#L352

https://github.com/microsoft/vscode-jupyter/blob/545c0a7b00b073da4d73ed58bf6c49e0d31b7ee6/src/kernels/jupyter/jupyterKernelService.node.ts#L286

**Comment by rchiodo** [comment] 2022-07-27 16:28
Those are not the same 'getEnvironmentVariables' calls. The one adding to the shell history is only used in our jupyter install telemetry.

**Comment by DonJayamanne** [comment] 2022-07-31 16:57
Closing as a duplicate of #10935

**Closed by DonJayamanne** 2022-07-31 16:57 UTC
Labels: debt
