### ISSUE TITLE
[Feature Request] Remove unselected mode for cells.

### ISSUE THREAD

**Issue by aakashsbhowmick** [microsoft/vscode-jupyter#8518] opened 2021-12-10 10:36 UTC
I am a programmer by background and I do not like to use the mouse as I find it slow and unergonomic. Currently I am trying out editing Jupyter notebooks in VS code using Microsoft's Jupyter extension.

From Microsoft's online documentation, I can see that cells can be in 3 modes :

- Unselected
- Selected : Command
- Selected : Edit

**The problem** : Pressing Esc while editing a cell take me from 'Edit' to 'Command' mode. Pressing Esc again takes me from 'Command' to 'Unselected' mode. The problem is that if I accidentally press Esc twice while editing, the cell goes to 'Unselected' mode (from 'Edit' mode), and the only way to select it again is to **click on the cell using the mouse**. This is happening too many times and it is getting annoying. As far as I remember, browser based Jupyter notebook do not have this behaviour.

**Proposed Workflow**:
- User is in editing a cell and therefore cell is in 'Selected:Edit' mode.
- User presses Esc. This switches the cell to 'Selected:Command' mode.
- Pressing Esc again **does not unselect** the current cell and infact does nothing.
- Navigating to another cell using keyboard/mouse deselects current cell and selects the other cell.

I think this workflow would be a lot more convenient.

**Comment by amunger** [comment] 2021-12-10 17:59
That makes sense, thanks for the suggestion. It would probably have to be an optional setting if there are any workflows that rely on that functionality.

Possibly helpful: there are "focus first/last cell" commands (ctrl+home/end on Windows) that could help get focus back, but not so helpful if you're working in the middle of a large notebook.

**Comment by aakashsbhowmick** [comment] 2021-12-13 08:13
Thanks for the feedback, @amunger .

I can help make this modification if there is broad consensus that an optional switch for turning off 'Unselected mode' for cell makes sense.

Please advice if we need more discussion/engagement on this.
If not, please also advice what would be the appropriate place to store this optional switch.

**Comment by greazer** [comment] 2021-12-14 00:18
@aakashsbhowmick, thanks for the feedback. This looks like a dupe of https://github.com/microsoft/vscode/issues/128153.

**Closed by greazer** 2021-12-14 00:18 UTC
Labels: enhancement, needs-triage
