### ISSUE TITLE
Allow configuration of python kernel launcher listen port

### ISSUE THREAD

**Issue by 2pl** [microsoft/vscode-jupyter#6618] opened 2021-07-10 09:59 UTC
The python kernel launcher listen port uses logic below
1.  it starts from a hard coded value port 9000
2. it tries to bind this port on 127.0.0.1 
3. if the port is in use it increments the port number and retries until success

This works pretty well except when using vscode on Windows with a remote connection to a WSL2 instance. The current WSL2 implementation allows binding a port on 127.0.0.1 even though the same port is used by the Windows host as described in [https://github.com/microsoft/WSL/issues/7150]. 

This might be fixed by the WSL team someday but meanwhile as a workaround it would be great to have a way to configure kernel launcher port in vscode-jupyter, or maybe use the WSL2 IP instead of 127.0.0.1 to communicate with the remote.

**Comment by joyceerhl** [comment] 2021-07-10 19:13
Thanks for the suggestion. We'll discuss it at our weekly triage meetings.

**Comment by DonJayamanne** [comment] 2022-08-15 01:08
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/10765

**Closed by DonJayamanne** 2022-08-15 01:08 UTC
Labels: good first issue, notebook-kernel, feature-request
