### ISSUE TITLE
Jupyter kernel issue

### ISSUE THREAD

**Issue by ThemisKoutsellis** [microsoft/vscode-jupyter#13048] opened 2023-03-07 12:25 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.76.0 (Universal)
- OS Version: MacOS Venture Version 13.2.1.

Regardless the VSCode Version, I tried 1.6X.X as well, out of the blue, the last few days the VSCode couldn't connect to the kernel required to execute Jupyter cells. Either at the very beginning or during simple cell commands like DataFrame.plot(). In the second case, the cell runs endlessly and the _interrupt_ button is deactivated. It seems that the kernel has connection issue because I tried many print() statements and only the very first one is executed, i.e. at the first line of the cell. 

![Screenshot 2023-03-07 at 14 03 50](https://user-images.githubusercontent.com/88409436/223420230-b4939530-a943-4e6a-9804-55646b2dab8b.png)

**Comment by DonJayamanne** [comment] 2023-03-10 06:10
Thanks for filing this issue and sorry you are running into this problem
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by ThemisKoutsellis** [comment] 2023-03-11 18:29
Thank you for your reply! 
I already did that. 
However, I don't know what shall I report. The VSCode does not terminate. So, I don't know what shall I capture.
See figure below

![Uploading Screenshot 2023-03-11 at 20.27.00.png…]()

**Comment by farr** [comment] 2023-03-13 16:23
I am seeing a similar error (notebook freezes with 'Reconnecting to kernel...').  It seems to happen randomly, usually after executing O(10) cells.  The error that causes the kernel to terminate is 
```
debug 12:11:09.239: Start cell 14 execution @ 1678723869239
[E 12:11:20.720 NotebookApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/Users/wfarr/miniconda3/envs/ringdown/lib/python3.10/site-packages/tornado/iostream.py", line 702, in _handle_events
        self._handle_write()
      File "/Users/wfarr/miniconda3/envs/ringdown/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/wfarr/miniconda3/envs/ringdown/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/Users/wfarr/miniconda3/envs/ringdown/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/wfarr/miniconda3/envs/ringdown/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/Users/wfarr/miniconda3/envs/ringdown/lib/python3.10/site-packages/tornado/iostream.py", line 702, in _handle_events
    self._handle_write()
  File "/Users/wfarr/miniconda3/envs/ringdown/lib/python3.10/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/Users/wfarr/miniconda3/envs/ringdown/lib/python3.10/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
```
but this is very confusing to me, as the paths there (even the Python version!) do not correspond to the environment in which the kernel is running!  For example: 
```
! echo $PATH
```
produces 
```
[/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/bin](https://file+.vscode-resource.vscode-cdn.net/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/bin):[/Users/wfarr/miniconda3/condabin](https://file+.vscode-resource.vscode-cdn.net/Users/wfarr/miniconda3/condabin):[/usr/local/bin](https://file+.vscode-resource.vscode-cdn.net/usr/local/bin):[/System/Cryptexes/App/usr/bin](https://file+.vscode-resource.vscode-cdn.net/System/Cryptexes/App/usr/bin):[/usr/bin](https://file+.vscode-resource.vscode-cdn.net/usr/bin):[/bin](https://file+.vscode-resource.vscode-cdn.net/bin):[/usr/sbin](https://file+.vscode-resource.vscode-cdn.net/usr/sbin):[/sbin](https://file+.vscode-resource.vscode-cdn.net/sbin):[/Library/TeX/texbin](https://file+.vscode-resource.vscode-cdn.net/Library/TeX/texbin)
```
and Python's `sys.path` is 
```
['[/Users/wfarr/Research/BrightSirenInclinationSystematics/src/notebooks](https://file+.vscode-resource.vscode-cdn.net/Users/wfarr/Research/BrightSirenInclinationSystematics/src/notebooks)',
 '[/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/lib/python311.zip](https://file+.vscode-resource.vscode-cdn.net/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/lib/python311.zip)',
 '[/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/lib/python3.11](https://file+.vscode-resource.vscode-cdn.net/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/lib/python3.11)',
 '[/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/lib/python3.11/lib-dynload](https://file+.vscode-resource.vscode-cdn.net/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/lib/python3.11/lib-dynload)',
 '',
 '[/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/lib/python3.11/site-packages](https://file+.vscode-resource.vscode-cdn.net/Users/wfarr/miniconda3/envs/BrightSirenInclinationSystematics/lib/python3.11/site-packages)']
```
(you can see there that I'm using Python 3.11, in a conda env called `BrightSirenInclinationSystematics`; the error comes from a different Python environment I have on my system, called `ringdown` that uses Python 3.10!).

When I run the same notebook from the command line (`conda activate Bright...` and `jupyter lab`) it does not have this problem, so in spite of appearances I don't think this is the conda envs getting confused.  Is it possible that a recent update to the Jupyter extension(s) accidentally preserves paths from previous sessions in some hidden variable that could be causing the confusion?

**Comment by DonJayamanne** [comment] 2023-03-21 07:07
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/12775
See instructions for fixing this here https://github.com/microsoft/vscode-jupyter/issues/12775#issuecomment-1447175314

The python envrionment use to start jupyter can be configured here 
* Open command palette
* Select the command `Jupyter: Select Interpreter to Start Jupyter Server`
* The item displayed is the python environment used to start jupyter and that is the environment in which the pakcages have to be updated as described here https://github.com/microsoft/vscode-jupyter/issues/12775#issuecomment-1447175314

If you have any questions please post them here or on https://github.com/microsoft/vscode-jupyter/issues/12775

**Closed by DonJayamanne** 2023-03-21 07:07 UTC
