### ISSUE TITLE
Data Viewer displays int64 from dataframe incorrect (last digits wrong)

### ISSUE THREAD

**Issue by andreas-wolf** [microsoft/vscode-jupyter#10517] opened 2022-06-21 13:49 UTC
## Environment data

-   VS Code version: 1.68.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001601848
-   Python Extension version (available under the Extensions sidebar): v2022.8.0
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22.04
-   Python and/or Anaconda version: Python 3.9.13 / 4.12.0
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

The last digits of int64 values are displayed correctly

## Actual behaviour

The last digits of int64 variables are not displayed correctly

## Steps to reproduce:

1. x = pd.DataFrame(data = [-9223086934292230710], index=[-9223086934292230710])
![bug_vs_code_int64_data_viewer_jupyter](https://user-images.githubusercontent.com/10654315/174815184-aaf51e10-2a0b-4924-9e8a-ea8d0afc2a0d.png)

3. show x in Data Viewer
4. -9223086934292230710 is shown as -9223086934292231000
![bug_vs_code_int64_data_viewer](https://user-images.githubusercontent.com/10654315/174814486-c8b58cf1-02dc-48c9-b279-aff37e67973b.png)

**Comment by andreas-wolf** [comment] 2022-06-21 15:19
It does not seem to be realated to rounding:
-9223086934292231679 displayes as -9223086934292231000
-9223086934292231680 displayed as -9223086934292232000

**Comment by rchiodo** [comment] 2022-06-21 16:24
Thanks for the issue. I think this is happening in the webview layer. 

I dumped the output using the code we use to translate the table to json. It looks fine:

![image](https://user-images.githubusercontent.com/19672699/174849574-a7793dea-fab1-4451-b133-de7740dd437d.png)

So my guess is that our data grid is not handling the large number so well.

**Comment by DonJayamanne** [comment] 2022-12-08 00:22
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7426
Basically numbers aren't handled well

**Closed by DonJayamanne** 2022-12-08 00:22 UTC
Labels: bug, data-viewer
