### ISSUE TITLE
Cell magic line breaks in VS code are \r\n not \n and cannot be parsed

### ISSUE THREAD

**Issue by Liu-Yanran** [microsoft/vscode-jupyter#6348] opened 2021-06-22 04:32 UTC
When I use cell magic from rpy2, the line breaks in VS code is \r\n which cannot be parsed because the parser only recognize \n.
The following works in Jupyter notebook but not in VS code because of the differences in line breaks. 

Steps to Reproduce:

1.
%load_ext rpy2.ipython
import numpy as np
import pandas as pd

df = pd.DataFrame(
    {
        "cups_of_coffee": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        "productivity": [2, 5, 6, 8, 9, 8, 0, 1, 0, -1],
    }
)
df.transpose()

2.
%%R -i df
library(ggplot2)
ggplot(df, aes(x=reorder(cups_of_coffee,productivity), y=productivity)) + 
geom_col() + 
coord_flip()

**Comment by greazer** [comment] 2021-06-24 20:22
@Liu-Yanran, can you provide us the file to take a look? Thanks!

**Comment by Liu-Yanran** [comment] 2021-06-25 00:23
[rpy2.zip](https://github.com/microsoft/vscode-jupyter/files/6712702/rpy2.zip)

@greazer 
Here is an example. The R parsed error happened because it could not recognize \r\n. The code works on Linux or Google cloud but not on a Windows machine.

**Comment by rchiodo** [comment] 2021-08-31 18:24
Closing as dupe of #6470

**Closed by rchiodo** 2021-08-31 18:24 UTC
Labels: language-python
