### ISSUE TITLE
Cannot view as scrollable element

### ISSUE THREAD

**Issue by BagelOrb** [microsoft/vscode-jupyter#14204] opened 2023-08-28 15:18 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

`Output is truncated. View as a scrollable element. `

Clicking [scrollable element] does nothing. It stopped working since a month or so.

I think this was still working in 1.80.2, so this is a regression. Not sure how it happened, because this bug was solved more than a year ago.

### VS Code Version

1.81.1

### Jupyter Extension Version

v2023.7.1002162226

### Jupyter logs

```shell
Clicking the link has no effect on the jupyter logs
```

### Coding Language and Runtime Version

python 3.10

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment] 2023-08-28 15:30
duplicate of https://github.com/microsoft/vscode/issues/189699
the fix is out in insiders and will be in stable next week.
As a temporary workaround, you can also use the command notebook.cell.toggleOutputScrolling, bound to `ctrl+k` `y` by default.

**Closed by amunger** 2023-08-28 15:30 UTC
Labels: bug
