### ISSUE TITLE
Jupyter Notebooks are completely blank

### ISSUE THREAD

**Issue by JakobRohrhirsch** [microsoft/vscode-jupyter#4781] opened 2021-02-12 08:51 UTC
Whenever I open an existing Jupyter Notebook on my WSL via VS Code, it just shows up completly blank. No lines to input, just fully blank. Like it cannot connect to the Jupyter Server or something. Hard to troubleshoot.

**Comment by godsic** [comment] 2021-02-12 09:51
The same happens to me on `daily` channel and the following error is displayed 
```
Unable to open 'test.ipynb': Cannot read property 'Rich' of undefined.
```

**Comment by claudiaregio** [comment] 2021-02-13 02:08
Hi @JakobRohrhirsch, are you using VS Code Insiders? Are you having the same issue as @godsic? That issue is a known issue that should be fixed in our next Jupyter insiders release.

**Comment by JakobRohrhirsch** [comment] 2021-02-14 13:39
Hi! 
I'm attaching a screenshot from the blank jupyter notebook. I think I'm using VC Code stable.
Thanks!

![image](https://user-images.githubusercontent.com/29501430/107878350-42553500-6ed2-11eb-82e6-71487f5f2892.png)

**Comment by greazer** [comment] 2021-02-16 23:10
Looks like a dupe of https://github.com/microsoft/vscode/issues/105536. Should be fixed in next month's release of VS Code (stable)

**Closed by greazer** 2021-02-16 23:10 UTC
