### ISSUE TITLE
Double clicking a change ipynb in the working tree/changes view has side-effects

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/vscode-jupyter#5279] opened 2021-03-24 23:08 UTC
## Environment data

-   VS Code version: 
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.684299474
-   Python Extension version (available under the Extensions sidebar): v2021.4.681399556-dev
-   OS (Windows | Mac | Linux distro) and version: macOS 11.3
-   Python and/or Anaconda version: Python 3.9.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local 

## Expected behaviour

1. Clicking and Double clicking on a changed notebook would have the same effect as any other file.
1. A side-by-side comparison of changes is shown

## Actual behaviour

Double-Clicking on a changed notebook from the source control pane opens it twice

## Steps to reproduce:

1. Edit a Jupyter notebook in a git repository
2. Save changes
3. Open the Source Control tab in VS Code
4. Single Click on the .ipynb files in the Changes section on the Source Control pane
**Issue 1: It opens the notebook, not a comparison of changes **
5. Close the tab with the notebook
6. Double click on the  .ipynb files in the Changes section on the Source Control pane
**Issue 2: It opens the notebook twice, once as the live notebook and the second as the notebook with the tab (Working changes)**

**Comment by DonJayamanne** [comment] 2021-03-25 00:43
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/633

**Closed by DonJayamanne** 2021-03-25 00:43 UTC
Labels: bug
