### ISSUE TITLE
Show the finished timestamp when cell finish running

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9508] opened 2022-03-28 15:25 UTC
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/9498

<div type='discussions-op-text'>

<sup>Originally posted by **amssljc** March 26, 2022</sup>
</div>

**Comment by andreaschiappacasse** [comment] 2022-03-28 15:48
+1 on this issue, maybe i'd prefer to be able to see the "start time" instead of the "finish time", so that it could be added to running cells as well (even if it's trivial to get the start time in that case from the ongoing duration).

e.g. something like:
![image](https://user-images.githubusercontent.com/5887658/160436244-8380978e-d541-4a2b-8e71-9d90d8e17186.png)

**Comment by rchiodo** [comment] 2022-03-28 16:02
@andreaschiappacasse Would you want this start time/finish time always displayed, even when opening the notebook somewhere else? 

Meaning the finish time would be saved in the notebook metadata?

**Comment by andreaschiappacasse** [comment] 2022-03-29 08:03
> @andreaschiappacasse Would you want this start time/finish time always displayed, even when opening the notebook somewhere else?
> 
> Meaning the finish time would be saved in the notebook metadata?

Given that the execution time is not currently stored in the notebook, I wouldn't expect this kind of information to be stored either (and it's not needed in my daily use), but I do think it would be a nice feature.
It could be usefuI in some cases to be able to see when a notebook was run last and how long it took.

In that case, it could be nice to be compliant to what [this extension ](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/execute_time/readme.html) does, as in saving it as:

```json
{
    "ExecuteTime": {
        "start_time": "2016-02-11T18:51:18.536796",
        "end_time": "2016-02-11T18:51:35.806119"
    }
}
```

So that opening the notebook in jupyter (with that extension enabled) could recover the timings.

---

On the other hand, if persistence is really needed in one's use case, it is easy to add some timing functionality to the cells output. So I would be equally happy with a solution mimicking the current "execution time" implementation.

---

To build on the idea, UX wise, another, maybe cleaner (?) solution, could be having the starting or/and finishing time to be displayed on mouse over on the execution time.

**Comment by DonJayamanne** [comment] 2022-03-30 22:34
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/8245

**Closed by DonJayamanne** 2022-03-30 22:34 UTC
Labels: enhancement
