### ISSUE TITLE
Data Viewer Problems with version 2022.5.1001601848

### ISSUE THREAD

**Issue by rishabhmonga119** [microsoft/vscode-jupyter#10628] opened 2022-06-29 11:50 UTC
## Environment data

-   VS Code version: 1.68.1
-   Jupyter Extension version (available under the Extensions sidebar): 2022.5.1001601848
-   Python Extension version (available under the Extensions sidebar): v2022.8.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: Python 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): - 
-   Jupyter server running: N/A

## Expected behaviour

Opening a pandas dataframe in Data Viewer should open a new Tab with the dataframe in tabular form

## Actual behaviour

Trying to open a pandas dataframe in Data Viewer, but error thrown each time: name "_VSCODE_json is not defined" or "_VSCODE_pd is not defined" is not defined

### Traceback Error: 
NameError: name '_VSCODE_json' is not defined

<code>
    at o.handleErrorResponse (vscode-file://vscode-app/c:/Users/q535666/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1041:45806)
    at vscode-file://vscode-app/c:/Users/q535666/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1041:45245
warn 13:51:22.498: DataScience Error Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 51, in _VSCODE_getVariableInfo
NameError: name '_VSCODE_json' is not defined

    at o.handleErrorResponse (vscode-file://vscode-app/c:/Users/q535666/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1041:45806)
    at vscode-file://vscode-app/c:/Users/q535666/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1041:45245
</code>

## Solution:

Reverting the Jupyter extension version to v2022.4.1021342353 resolves the issue.

**Comment by rchiodo** [comment] 2022-06-29 16:22
Thanks for the issue. 

This sounds like a dupe of this issue here:
https://github.com/microsoft/vscode-jupyter/issues/10516

Are you viewing a data frame while debugging?

**Comment by rishabhmonga119** [comment] 2022-06-30 07:06
No, I can't view the dataframe in dataviewer. Every time I right click a dataframe in Debugger and choose "View Value in Data Viewer", it throws a traceback with the error "name '_VSCODE_json' is not defined".

**Comment by rchiodo** [comment] 2022-06-30 15:49
Thanks that is what I meant. Your issue is a dupe of #10516. It will be fixed in our next release.

**Closed by rchiodo** 2022-06-30 15:49 UTC
Labels: bug, info-needed, triage-needed
