### ISSUE TITLE
INPUT FEATURE REQUEST

### ISSUE THREAD

**Issue by Annoymous-ss** [microsoft/vscode-jupyter#14957] opened 2023-12-26 19:03 UTC
when i open a notebook in vs code and try to give a input it says me to give the input in the kernel section.
But,  in the real jupyter notebook i am asked to give the input in the output cell. it will be really helpful if i can do the same in VS code jupyter notebook as well.
like in Jupyter Notebook this looks like : 
![Screenshot (7)](https://github.com/microsoft/vscode-jupyter/assets/132259757/ab697c22-5bbc-423a-aa2f-4455ffd0a253)
And in VS CODE in looks like : 
![Screenshot (8)](https://github.com/microsoft/vscode-jupyter/assets/132259757/0142f9d0-a73c-446b-b354-804d31c20259)

**Comment by DonJayamanne** [comment] 2023-12-27 03:24
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12076

**Closed by DonJayamanne** 2023-12-27 03:24 UTC
Labels: feature-request
