### ISSUE TITLE
Error: s.authentication.getPassword is not a function when connecting to kernel

### ISSUE THREAD

**Issue by astahlman** [microsoft/vscode-jupyter#4809] opened 2021-02-13 18:40 UTC
I've tried both connecting to an externally-launched kernel and launching the kernel directly from VSCode. In both cases, I'm unable to connect and get a notification saying "s.authentication.getPassword is not a function".

Interpreter is python3.8, Jupyter version 6.2.0, and I'm running in a virtual environment created with `python3 -m venv`

- Issue Type: `Bug`
- Extension Name: `jupyter`
- Extension Version: `2020.12.414227025`
- OS Version: `Linux x64 5.4.0-62-generic`
- VSCode version: `1.54.0-insider`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 204,
		"activateCallTime": 15,
		"activateResolvedTime": 1637,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "onNotebook:jupyter-notebook"
		}
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "s.authentication.getPassword is not a function"
		}
	]
}
```

**Comment by firegate22** [comment] 2021-02-13 23:26
https://github.com/microsoft/vscode-jupyter/issues/4451

Download a more recent build - current insiders is not updated. Search function helps :)

**Comment by joyceerhl** [comment] 2021-02-16 02:49
@astahlman sorry for the trouble. As @firegate22 said this is most likely a duplicate of #4451. We are planning to publish an update early this week which should resolve this issue, but in the meantime if you download a VSIX from this download link: https://github.com/microsoft/vscode-jupyter/suites/2031392460/artifacts/40832487 the issue should be resolved. Please let us know if otherwise. Thank you for taking the time to report a bug.

**Comment by greazer** [comment] 2021-02-16 23:02
Closing as dupe of #4451

**Closed by greazer** 2021-02-16 23:02 UTC

**Comment by astahlman** [comment] 2021-02-17 02:35
Great, thank you @joyceerhl!
