### ISSUE TITLE
No renderer could be found for MIME type

### ISSUE THREAD

**Issue by acook-geo** [microsoft/vscode-jupyter#5989] opened 2021-05-26 09:00 UTC
## Environment data

-   VS Code version: 1.57.0
-   Jupyter Extension version: 2021.6.870847776
-   Python Extension version: 2021.6.821261989-dev
-   OS and version: Windows 10 v20H2
-   Python and Anaconda version: python 3.8.5, conda 4.10.1
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

Correctly render an integer literal e.g. `2`
... first discovered on a numpy array but then found it to fail on int literals

## Actual behaviour

Unable to render code cell output and returns `No renderer could be found for MIME type: 2
`

## Steps to reproduce:

1. Code Cell: `2`
2. Run Cell
3. Output: No renderer could be found for MIME type: 2

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by benedikt-mayer** [comment] 2021-05-26 09:33
I also have this issue. It goes so far that notebooks cannot be opened at all, with the error:
`Unable to open 'Train_jupyter.ipynb': INVALID mime type, must not be empty or falsy.` (the mime-type is `text/x-python`).

**Comment by eternalphane** [comment] 2021-05-26 13:47
Seems that constructor argument order has changed https://github.com/microsoft/vscode/issues/93265#issuecomment-847723682

**Comment by rchiodo** [comment] 2021-05-26 16:02
This should be fixed shortly. VS code made an API change that we didn't notice until this morning. A new build is in the works.

**Comment by DonJayamanne** [comment] 2021-05-26 16:02
Hi everyone, I'm sorry about this isue, we've identifeied the cause, we'll be pushing a fix within the next 30 minutes or so.

**Comment by jeanga** [comment] 2021-05-26 16:22
Verified fixed for me on my notebooks!
Thank you very much for the quick fix <3

**Closed** 2021-05-26 16:22 UTC
Labels: bug
