### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mavaddat** [microsoft/vscode-jupyter#4895] opened 2021-02-20 01:35 UTC
- Issue Type: `Bug`
- Extension Name: `python`
- Extension Version: `2021.3.572572021-dev`
- OS Version: `Windows_NT x64 10.0.21313`
- VSCode version: `1.54.0-insider`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1687,
		"activateCallTime": 133,
		"activateResolvedTime": 3320,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-toolsai.jupyter",
				"_lower": "ms-toolsai.jupyter"
			},
			"activationEvent": "api"
		}
	},
	"runtimeErrors": []
}
```

**Comment by DavidKutu** [comment] 2021-02-22 22:52
Hey @mavaddat, could you tell us a but more about the issue you're seeing?

**Comment by greazer** [comment] 2021-02-25 21:26
This is likely a dupe of #4890, but even if not we would need more information (a profile).

**Closed by greazer** 2021-02-25 21:26 UTC
