### ISSUE TITLE
Unable to connect to Jupyter server with password

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-jupyter#13799] opened 2023-06-27 21:06 UTC
Testing #13766

I opted into the PasswordManager experiment.

1. Start a server on the terminal with the command `python -m jupyter notebook --no-browser --NotebookApp.allow_origin='*' --NotebookApp.password=sha1:f38e2e15d770:b97ffda8260e04ab8123b67eea9989764bf9690b`.
2. Try connecting to `http://localhost:8888` with the kernel picker.
3. :bug: Access is denied with a message asking to confirm that the password is correct. Is there a separate UX or set of instructions for connecting to prompts with passwords? I was expecting either a password prompt or a notification about password-protected servers not being supported.

**Comment by rzhao271** [comment] 2023-06-27 21:15
With experiments disabled the error message (in my own words) becomes "Failed to connect. Make sure the server is running and accessible (Connection to non-secure server refused)".

**Comment by amunger** [comment] 2023-06-27 22:32
similar for me-
initially, when opted into the experiment, I had the "Failed to connect. Make sure the server is running and accessible" message


once I opted out and reloaded, now I always get this with or without the experiment:
![image](https://github.com/microsoft/vscode-jupyter/assets/2019016/1870407b-7e70-4cc8-890e-ac4c67cb3800)

the connection works fine in stable

**Comment by DonJayamanne** [comment] 2023-06-27 22:48
@rzhao271 @amunger are you using web?

**Comment by DonJayamanne** [comment] 2023-06-27 23:09
Closing as duplicate of https://github.com/microsoft/vscode-jupyter/issues/13801 & https://github.com/microsoft/vscode-jupyter/issues/13802

**Closed by DonJayamanne** 2023-06-27 23:09 UTC

**Comment by rzhao271** [comment] 2023-06-28 16:26
I just realized anyOS could imply web too. I tested on macOS desktop.
