### ISSUE TITLE
Error when inserting new cell

### ISSUE THREAD

**Issue by jorislimonier** [microsoft/vscode-jupyter#5466] opened 2021-04-09 05:32 UTC
## Environment data

-   VS Code version: 1.55.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.702919634
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04
-   Python and/or Anaconda version: 3.9 but problem is on Julia 1.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Insert cell below

## Actual behaviour

See screenshot
![image](https://user-images.githubusercontent.com/43946637/114132786-4ebfa200-9905-11eb-9712-3d875e8104d9.png)
However if I close VS Code and reopen it, the cells are there, well formatted.

## Steps to reproduce:

1. Open a Jupyter Notebook running julia
2. Click the `+` button to "Insert cell below"

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
```

</p>
</details>

**Comment by claudiaregio** [comment] 2021-04-09 23:58
Dupe of https://github.com/microsoft/vscode-jupyter/issues/5396 

We actually recommend that other languages use the VS Code Insiders build to use Native Notebooks.
I do not reproduce this issue on VS Code Insiders. If it is urgent for you to get unblocked I recommend using VS Code Insiders found here: https://code.visualstudio.com/insiders/

**Closed by claudiaregio** 2021-04-09 23:58 UTC
Labels: bug
