### ISSUE TITLE
Jupyter extension starts multiple idle R kernels, clogging up memory

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9700] opened 2022-04-18 16:05 UTC
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/9409

<div type='discussions-op-text'>

<sup>Originally posted by **pehkawn** March 17, 2022</sup>
I've been running R using the Jupyter notebook extension for some time, and for the most part it's working great. I have an issue with how it chews up my memory however. In my system monitor, I can see multiple idle R kernels loaded in memory. They use 0% of CPU, indicating they're just just there without doing anything. During extensive use, the amount of R kernels will keep growing until it takes up all my available memory. Running garbage collect (`gc()`) or clearing up variables `rm(list = ls() )` will do nothing to free up memory, and the only way to clear up my memory is to terminate the process. This  I can not think this is working after intention, but I am uncertain whether this is a bug, or the matter of changing a setting. Any input on this would be appreciated.

#### Version info:
**VS Code:** 1.65.2
**Jupyter extension:** v2022.2.1030672458
**R:** 4.1.3
**Anaconda:** 4.11.0
**OS:** Ubuntu 20.04.4 LTS

![Skjermbilde fra 2022-03-17 15-19-12](https://user-images.githubusercontent.com/44672121/158901540-277b2964-14a5-4ce9-8188-7a26a9457150.png)
 </div>

**Comment by IanMatthewHuff** [comment] 2022-04-18 20:14
@pehkawn This was moved from discussions. My last question in the discussion was to see if you see the same result when running just normal `jupyter notebook` from the command line (not VS Code).

**Comment by carbocation** [comment] 2022-04-19 13:05
For what it's worth, I have the same issue on MacOS

```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:47:29.396Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.3.0
```

In my experience, each new R notebook seems to launch its own R process which doesn't terminate. Re: @IanMatthewHuff 's question, I do not experience this when just running `jupyter notebook` via the command line.

**Comment by pehkawn** [comment] 2022-07-23 11:53
Hi, thought I'd check in and ask if there has been any recent developments on this issue? (I still experience the problem with an ever-increasing memory usage, and a multitude of R inactive kernels stuck in memory.)

**Comment by DonJayamanne** [comment] 2022-07-23 12:35
for every kernel, we start a duplicate kernel. 
so if you open a notebook and run a call, three will be two R processes running.
we do this so that restarting kernels is pretty fast, basically at that point we just switch to an already running kernel. 

i personally think we should stop starting these extra processes.

**Comment by pehkawn** [comment] 2022-07-23 13:10
Not sure what that implies. How many kernels is needed per notebook? Do I understand you correctly that there should be two active kernels per notebook, one that is in use and one idle to take over when in case of kernel restart? If that is the case, it would seem to me that the "old" kernel is not properly terminated when switching to the second running kernel. If so, are these process switches "running behind the scenes"?

What I can say is that, I actively restarted VS Code maybe an hour ago, because almost all 32 GB of memory was hogged up by a numerous R kernels and VS Code sessions. Currently, I have two Jupyter notebooks open and one active R terminal, yet I can count 16 R kernels in the system monitor, using 5 GB of memory altogether, without actively restarting the kernel...

**Comment by DonJayamanne** [comment] 2022-08-02 17:36
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/9909

**Closed by DonJayamanne** 2022-08-02 17:36 UTC
Labels: bug, info-needed, notebook-kernel, perf
