### ISSUE TITLE
Plots in plotviewer not center aligned (hence not visible)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7523] opened 2021-09-14 22:21 UTC
Run the following cell & open the plot in the plot viewer
The plots are not visible (took me 1/2 hour to figure out that the plots are displayed but out of view) - i ended up debugging this.

FYI - This is a sample a user had provided some time ago (when I was looking into issues with rendering plots in notebooks).

```python
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np


df = pd.DataFrame(np.random.randint(0,100,size=(500, 4)), columns=list('ABCD'))

fig, axx = plt.subplots(1, 18, figsize=(10 * 8, 13))
for i in range(18):
    tmp = df[df.A < 50]
    sns.lineplot(data=tmp, x="A", y="B", hue='C', ax=axx[i], marker="o", ci=99)
```

<img width="1066" alt="Screen Shot 2021-09-14 at 15 19 16" src="https://user-images.githubusercontent.com/1948812/133341502-d2731ae8-78cc-49d8-9953-a01171392cd2.png">

Empty screen in plot viewer (its on the very far right)
<img width="654" alt="Screen Shot 2021-09-14 at 15 20 57" src="https://user-images.githubusercontent.com/1948812/133341601-335fdb70-53f1-49f6-a00d-4c8a944f71fe.png">

**Comment by greazer** [comment] 2021-11-08 21:09
Not really necessarily a dupe of #7709.

**Closed** 2022-01-25 01:04 UTC
Labels: bug, plot-viewer
