### ISSUE TITLE
"Run Current File in Interactive Window" opens IW and doesn't run anything

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#12642] opened 2023-01-25 02:31 UTC
I open this .py file with cell markers, use the new command under the play menu, and it opens this empty IW

<img width="1147" alt="image" src="https://user-images.githubusercontent.com/323878/214467494-5a355515-5826-4ba6-86be-b41436786d0d.png">

I select a kernel, and it still doesn't run. Then if I run the command again, now that I have a kernel, it will run the code.

**Comment by amunger** [comment] 2023-01-25 22:06
looks like a duplicate of https://github.com/microsoft/vscode-jupyter/issues/8422 unless you did have an active interpreter for python

**Closed by amunger** 2023-01-25 22:06 UTC
Labels: bug
