### ISSUE TITLE
ValueError renders plain HTML code in the Cell Output area

### ISSUE THREAD

**Issue by kmkolasinski** [microsoft/vscode-jupyter#13428] opened 2023-04-29 16:25 UTC
Hi, I believe this is not a feature :thinking:

![image](https://user-images.githubusercontent.com/10145864/235312798-8f8b423a-c68b-4ce1-bfa8-d160d26e65a3.png)

![image](https://user-images.githubusercontent.com/10145864/235313062-d5f87148-1117-4809-9715-f0ac0dc9ecc1.png)

## Environment data

-   VS Code version: 1.77.3
-   Jupyter Extension version (available under the Extensions sidebar): v2023.3.1201040234
-   Python Extension version (available under the Extensions sidebar): 3.9
-   OS (Windows | Mac | Linux distro) and version: linux
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

**Comment by amunger** [comment] 2023-05-01 21:30
duplicate of https://github.com/microsoft/vscode/issues/177405

**Closed by amunger** 2023-05-01 21:30 UTC
Labels: bug
