### ISSUE TITLE
jupyter does not provide correct completion suggestions

### ISSUE THREAD

**Issue by Micro-sheep** [microsoft/vscode-jupyter#10159] opened 2022-05-27 11:29 UTC
## Environment data

-   VS Code version: 1.67.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1021342353
-   Python Extension version (available under the Extensions sidebar): v2022.6.2
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: 3.7.9
-   Type of virtual environment used: NA
-   Jupyter server running: Local

## Expected behaviour
When typing `as ` in `.ipynb` file, there should not be any suggestion just like typing in `.py` file .

![expected](https://user-images.githubusercontent.com/56242295/170689087-3708ea0d-0c91-4604-8eef-ea12e58e964b.gif)

## Actual behaviour

When typing `as ` in `.ipynb` file, the icon for `as` is wrong and there are completion suggestions

![actual](https://user-images.githubusercontent.com/56242295/170688824-23ea6d80-9cf2-4494-b023-2085b02439ef.gif)

## Steps to reproduce:

1. Open a `.ipynb` file in vscode
2. Type `import requests as r` in python cell

**Comment by amunger** [comment] 2022-05-27 15:06
thanks for the bug. To repro, I had to run a cell first to start the kernel. Still happens in the latest insiders

**Comment by rchiodo** [comment] 2022-05-27 17:52
Oh this is the jupyter kernel completions. It's not smart enough to parse that so it just returns everything.

I imagine if this setting was turned on, it might work:

![image](https://user-images.githubusercontent.com/19672699/170764575-23e8b6c4-4b8d-4ec7-b2eb-61237dac920d.png)

**Comment by Micro-sheep** [comment] 2022-05-27 23:39
> Oh this is the jupyter kernel completions. It's not smart enough to parse that so it just returns everything.
> 
> I imagine if this setting was turned on, it might work:
> 
> ![image](https://user-images.githubusercontent.com/19672699/170764575-23e8b6c4-4b8d-4ec7-b2eb-61237dac920d.png)

I can't find this setting in both latest stable and pre-release version. However, this setting exists in the latest source code on Github. Should I compile it from the source code and install? Or is there another way to set environment variable `VSC_JUPYTER_IntellisenseTimeout`  to make it work which you memtion in https://github.com/microsoft/vscode-jupyter/issues/7925#issuecomment-945942862.
I notice that this option was removed in the latest version.

**Comment by rchiodo** [comment] 2022-05-27 23:47
Sorry there's no way to disable jupyter completions at the moment. The latest prerelease version should have this setting though:

This is the latest version:
Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2022.5.1001491011
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

**Comment by Micro-sheep** [comment] 2022-05-28 00:01
> Sorry there's no way to disable jupyter completions at the moment. The latest prerelease version should have this setting though:
> 
> This is the latest version: Name: Jupyter Id: ms-toolsai.jupyter Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more. Version: 2022.5.1001491011 Publisher: Microsoft VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

Thank you very much, it works for me!

**Comment by rchiodo** [comment] 2022-05-28 00:26
> > Sorry there's no way to disable jupyter completions at the moment. The latest prerelease version should have this setting though:
> > This is the latest version: Name: Jupyter Id: ms-toolsai.jupyter Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more. Version: 2022.5.1001491011 Publisher: Microsoft VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
> 
> Thank you very much, it works for me!

If you notice any slowdowns when executing, you might have to disable that setting. It tells the kernel to use Jedi for completions, but Jedi has performance issues.

**Comment by Micro-sheep** [comment] 2022-05-28 02:15
> > > Sorry there's no way to disable jupyter completions at the moment. The latest prerelease version should have this setting though:
> > > This is the latest version: Name: Jupyter Id: ms-toolsai.jupyter Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more. Version: 2022.5.1001491011 Publisher: Microsoft VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
> > 
> > 
> > Thank you very much, it works for me!
> 
> If you notice any slowdowns when executing, you might have to disable that setting. It tells the kernel to use Jedi for completions, but Jedi has performance issues.

When this setting is enabled, a new problem pops up. 

![image](https://user-images.githubusercontent.com/56242295/170805751-91a92bdb-d468-41e5-b6aa-32be16c65d62.png)

**Comment by DonJayamanne** [comment] 2022-12-08 21:46
@Micro-sheep 
I believe we have fixed this in the latest release bits
Please could you install vscode 1.74 and the latest versions of the Jupyter, Python and Pylance extensions

I've tested this at my end and this works as expected.

If this still doesn't work, please do ping here and i'll reopen this issue or please feel free to create a new issue

**Comment by Micro-sheep** [comment] 2022-12-09 04:52
> @Micro-sheep I believe we have fixed this in the latest release bits Please could you install vscode 1.74 and the latest versions of the Jupyter, Python and Pylance extensions
> 
> I've tested this at my end and this works as expected.
> 
> If this still doesn't work, please do ping here and i'll reopen this issue or please feel free to create a new issue

I have installed the latest version of the three extensions you mentioned, but it still does not work as expected when typing in jupyter.

**Note**: it works as expected when starting jupyter, but after I run a cell, it won't work as expected anymore.

**Env**
- vscode version: v1.74.0
- python extension version: v2022.20.0
- pylance extension version: v2022.12.20
- jupyter  extension version: v2022.11.1003412109

**Actual behaviour**

![screenshot](https://user-images.githubusercontent.com/56242295/206626411-157d2711-0c51-496f-bfca-b5d04f87f80c.gif)

**Comment by DonJayamanne** [comment] 2022-12-09 07:50
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12029

**Closed by DonJayamanne** 2022-12-09 07:50 UTC
Labels: bug, notebook-intellisense
