### ISSUE TITLE
In new native interactive window, restarting the kernel does not clear imported modules

### ISSUE THREAD

**Issue by filipporemonato** [microsoft/vscode-jupyter#7041] opened 2021-08-10 09:02 UTC
## Environment data

-   VS Code version: 1.59.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1195043623
-   Python Extension version (available under the Extensions sidebar): v2021.8.1105858891
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: Python 3.7.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local

## Expected behaviour

Restarting the kernel should clear all variables and imports

## Actual behaviour

After restarting the kernel, the variables remain in displayed in the "variables" tab of jupyter. Querying them from the interactive window's command line results in the correct "name XX not defined".
However, imported modules are not reloaded

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create the following two scripts in the same folder:

`test.py`:
```
#%%
import test_fun as tf
#%%

a = 10
b = 20
# %%

c = tf.my_fun(a)
print(c)
```

`test_fun.py`:
```
import numpy as np

def my_fun(a):
    print('I have received ' + str(a))
    return 2*a
```

2. run `test.py`, notice the output is as expected. In passing, note that the variables are NOT present in the "variables" tab, but they appear if, having the tab open, some code is run through the Interactive Window command line.
3. make some modification to `my_fun`, for instance add another line like `print('now I am printing an extra line')`.
4. Restart jupyter kernel by clicking on the "restart" button at the top of the window. Note that the old variables do not disappear from the "variables" tab, however querying them from the Interactive Window comman line results in an expected error as the variable is not in memory.
5. re-run  `test.py`, notice the new line is not being printed, which means the imported module is not reloaded.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by IanMatthewHuff** [comment] 2021-08-10 18:56
@filipporemonato Thanks for the detailed repro steps here. I do repro both the issue with the variables not showing up until code is run in the IW as well as the issue with variables not being cleared on a restart. However I did see the new line that I added being printed when added to run_test.py ('Extra line added is what I added). Are you sure that you are not seeing the line added from the file change?
![image](https://user-images.githubusercontent.com/812783/128918672-f0b2c51d-093e-4791-94a6-af953794fccb.png)
@joyceerhl I think the variables not initially showing (+ not clearing on restart) might be a known issue already?

**Comment by joyceerhl** [comment] 2021-08-10 19:27
Variables not initially showing is tracked in https://github.com/microsoft/vscode-jupyter/issues/6993. Not clearing on restart is a bug, but I'll add that to #6993 since I should fix both of those issues at the same time.

**Comment by filipporemonato** [comment] 2021-08-11 08:31
Hei @IanMatthewHuff  thanks for checking this out. Good you could repro the variables showing/clearing. I'm unsure why you could not repro the module reload; this is what I see:
![image](https://user-images.githubusercontent.com/6236646/128995969-d3d887ad-6334-45ae-a239-464d9038e62e.png)

As you can see the output does not change after restarting the kernel.
This is how `my_fun` was before the restart:
![image](https://user-images.githubusercontent.com/6236646/128996257-447e459f-30b4-4f4b-a568-16ed41c05a80.png)

And this is after the restart:
![image](https://user-images.githubusercontent.com/6236646/128996408-71a99d68-0e07-4f3b-8f1d-a60eab91df10.png)

I also made sure the modified file was saved before running the import again, and also tried again by saving it before restarting the kernel.

**Comment by joyceerhl** [comment] 2021-08-12 22:27
@filipporemonato Do you happen to have `jupyter.runStartupCommands` configured to something in your user settings, and are you relying on that for module reload? If so, we're fixing an issue where the startup commands aren't rerun after restarting the kernel and this issue would be a dupe of https://github.com/microsoft/vscode-jupyter/issues/7016.

**Comment by yourPhysio** [comment] 2021-08-18 19:00
I am facing the same issue with restart kernel. Does not update the imported modules.

**Comment by filipporemonato** [comment] 2021-08-23 13:33
Hi @joyceerhl, some days ago there has been a small update of VS Code; now I have version 1.59.1 (was 1.59.0).
This update seems to have fixed the issue about modules not being reloaded; now I can see the changes I make in the imported functions pop up in the interactive window as expected.
If @yourPhysio could confirm, then we can consider this part resolved, and then this issue would become a dupe of  [#6993](https://github.com/microsoft/vscode-jupyter/issues/6993) as you mentioned so we can close it.

**Comment by joyceerhl** [comment] 2021-08-31 21:51
Sounds like this issue has been fixed--please file a new issue if this is not working for you.

**Closed by joyceerhl** 2021-08-31 21:51 UTC
Labels: bug, info-needed, interactive-window
