### ISSUE TITLE
How to switch back to prior Jupyter Notebook interface?

### ISSUE THREAD

**Issue by ducalpha** [microsoft/vscode-jupyter#7004] opened 2021-08-08 01:35 UTC
The new Jupyter Notebook interface (native interactive) is unusable with Vim. Changing between the normal and insert mode in Vim in each cell becomes extremely messy because pressing Esc change to mode to moving between cells. Is there any way to disable the new native interactive or disable the Vim Extension only in Jupyter Notebook (.ipynb files)?
I have tried to adapt to the new interface in 2 weeks but it is still so hard to use.

**Comment by greazer** [comment] 2021-08-09 18:14
Dupe of #6997.

**Comment by greazer** [comment] 2021-08-09 18:18
To work around this problem, you can remap the keybinding for Notebook: Stop Editing Cell from something other than escape. However we will be looking into better VIM support in the interactive window in the near term. See https://github.com/microsoft/vscode/issues/130425

```json
{
"key": "escape",
"command": "notebook.cell.quitEdit",
"when": "inputFocus && notebookEditorFocused && !editorHasMultipleSelections && !editorHasSelection && !editorHoverVisible"
}
```

**Closed by greazer** 2021-08-09 18:18 UTC
Labels: enhancement, needs-triage

**Comment by ducalpha** [comment] 2021-08-11 05:10
Thanks for the workaround but the Jupyter Notebook with Vim keybindings is still extremely hard to use. I resolved to temporarily use a Jupyter Lab server.
