### ISSUE TITLE
Hardcoded white background when SVG mode is used

### ISSUE THREAD

**Issue by mohtar** [microsoft/vscode-jupyter#7590] opened 2021-09-20 02:24 UTC
## Environment data

-   VS Code version: 1.60.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1230869389
-   OS (Windows | Mac | Linux distro) and version: macOS 11.5.2
-   Python and/or Anaconda version: 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

Background of SVG plots to be either transparent or to follow editor background

## Actual behaviour

Background of SVG plots is white regardless of color theme in use.

## Steps to reproduce:

1. Set VS Code to use any color theme with a non-white background.

2. Create `test.ipynb` file.

3. Execute the following code:

```
%config InlineBackend.figure_format = 'svg'
import pandas as pd
pd.DataFrame({'y': [1, 2, 3]}).plot()
```

Screenshot:

<img width="1098" alt="Screenshot 2021-09-20 at 10 21 43 AM" src="https://user-images.githubusercontent.com/543182/133951769-694102ae-7749-439b-bf0c-21d8987b0c21.png">

## Logs

Not applicable.

**Comment by joyceerhl** [comment] 2021-09-20 14:21
Thanks for the bug. This is likely a duplicate of https://github.com/microsoft/vscode-jupyter/issues/7470. We plan to set it to only be white immediately behind the figure, not the entire plot.

**Comment by greazer** [comment] 2021-09-20 20:17
Thanks for the feedback! We've been asked about this a lot.  Being able to modify the background of matplotlib to make sure that everything in the plot itself is visible is a tough problem to solve. We don't have plans on attempting it. 

The fact that we're whiting out 100% width is a dupe of #7470.

**Closed by greazer** 2021-09-20 20:17 UTC
Labels: bug, needs-triage
