### ISSUE TITLE
Unable to load a compatible version of the widget 'catboost_module'. Expected behavior may be affected.

### ISSUE THREAD

**Issue by Montaser16** [microsoft/vscode-jupyter#5555] opened 2021-04-19 20:55 UTC
## Environment data

-   VS Code version: 1.56.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 6.1.6 
-   OS (Windows | Mac | Linux distro) and version: ubuntu 21.04
-   Python and/or Anaconda version: 3.7.3 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

in catboost model training step it generates a plot  for the model behavior (accuracy , logloss ,..) , it is expected to generate the plot without any errors

## Actual behaviour

what happened is that it takes a very long time on  in training and doesn't generate the plot , but generates this error

**Comment by DavidKutu** [comment] 2021-04-19 23:19
Hi @Montaser16. Could you please fill out the bug template? The more info you share the better!

**Comment by Montaser16** [comment] 2021-04-20 01:54
> Hi @Montaser16. Could you please fill out the bug template? The more info you share the better!

@DavidKutu

**Comment by DavidKutu** [comment] 2021-04-20 17:38
Thanks @Montaser16, could you share a screenshot of the error you're seeing?

**Comment by greazer** [comment] 2021-04-21 21:28
Dupe of #1684.

**Closed by greazer** 2021-04-21 21:28 UTC
Labels: bug, info-needed
