### ISSUE TITLE
Support displaying images stored in cell metadata attachments in markdown cells

### ISSUE THREAD

**Issue by MarkVazquez** [microsoft/vscode-jupyter#1632] opened 2020-04-18 23:59 UTC
Vs code does not load images properly. When I download a notebook from my class, on anaconda, the images load up properly. However, on vs code there is no images and they all show up as "image.png". These images are not saved locally since I just download the notebook from class.  Note: The notebook was not ran.

![Vs Code Jupyter Notebook](https://user-images.githubusercontent.com/60809118/79674066-57bfdc80-81a5-11ea-9901-93fbfa8aae7f.png)
![Anaconda Jupyter Notebook](https://user-images.githubusercontent.com/60809118/79674069-61494480-81a5-11ea-9ebd-d0fecfef25a8.png)

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by DonJayamanne** [comment] 2021-09-02 18:13
Duplicate of https://github.com/microsoft/vscode/issues/123021

**Comment by greazer** [comment] 2021-09-02 20:15
Dupe of a vscode issue (as above)

**Closed by greazer** 2021-09-02 20:15 UTC
Labels: bug, needs-triage, notebook-rendering
