### ISSUE TITLE
Wide image truncated after double-click plots tab in left-right split mode

### ISSUE THREAD

**Issue by wei-lingfeng** [microsoft/vscode-jupyter#7709] opened 2021-08-13 04:55 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Split vscode in left-right layout.
2. Plot a wide and a slim figure in python interactive window in the right part.
2. Click "Expand image" for both wide & slim figures.
3. Double click the Plots panel to expand it when it's showing the slim figure.
4. Click the wide figure, and it is truncated.

![image](https://user-images.githubusercontent.com/34182375/129306759-1ee8ca69-d6e9-4f78-93df-38bdbfcdd516.png)

**Comment by DonJayamanne** [comment] 2021-09-28 17:21
@Lingfeng-Wei I'm sorry I totally missed this issue. Will look into this ASAP.

**Comment by DonJayamanne** [comment] 2021-09-30 22:27
Thanks for filing this issue, I can replicate this.

**Comment by DonJayamanne** [comment] 2022-12-07 19:50
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/9349

**Closed by DonJayamanne** 2022-12-07 19:50 UTC
Labels: bug, plot-viewer
