### ISSUE TITLE
Active kernels are not located and do not populate

### ISSUE THREAD

**Issue by alexandergursky** [microsoft/vscode-jupyter#12161] opened 2022-11-24 18:21 UTC
Type: <b>Bug</b>

Jupyter Extention
November 24, 2022
version: 2022.11.1003301027
Issue: Available Python kernels are not recognized.

My situation in my own words:
The stable version v2022.9.1303220346 has an issue with Jupyter's own intellisense doubling with Pythons intellisense extention. While this is not functionally a problem, it is really frustrating after 12+ hours of heavy coding. Per Github log from developers for that issue. I migrated to pre-release version 2022.11.1003281132 this fixed this intellisense issue with no other issues to report. 
However, I reloaded VScode on 11/24/2022 and pre-release version 2022.11.1003301027 was whining/notifying/asking for me to update to it, so I did and none of my 4 Python kernels will populate. Pair this issue with some developer warnings/errors that flag. 
It (2022.11.1003301027) does give me the option for a Julia 1.8.2 kernel that I have. But none of my Python kernels will populate as options, as if they do not exist on my machine. This is the problem which is making me file a report for the developers to be notified of issue.
-----------------------------------------------------------------------
Things I have googled in my search to try to fix issue (hopefully a spider will find these for others in my situation so they can be navigated here to see ultimate solution): 

vscode jupyter extension pre-release 2022.11.1003301027 issue
jupyter server : not started, no kernel in vs code 
vscode not locating jupyter kernel
vscode cannot find jupyter kernel
Command 'Jupyter: Select Interpreter to Start Jupyter Server' resulted in an error 
jupyter server : not started, no kernel in vs code
kernel not showing in jupyter vscode
Extension Activation failed vscode
vscode not starting jupyter server in python picking Julia

-----------------------------------------------------------------------
The 4 Python kernels that I have on my machine are as follows: 
1. Python 3.9.4 (local)
2. Python 3.11.0 (local)
3. base (Python 3.9.7) (anaconda3)
4. REnvironment (Python 3.8.2) (anaconda3)
5. Julia 1.8.2 (local) (Julia is not Python however, I will include this as its the only kernel that actually does populate for me on pre-release version 2022.11.1003301027)
-----------------------------------------------------------------------
Prompt that is paired with issue on install:
"Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more Information."
-----------------------------------------------------------------------
On opening of "Developer: Toggle Developer Tools" responses given:
--YELLOW ERROR--
> TMScopeRegistry.ts:47 Overwriting grammar scope name to file mapping for scope source.python.
Old grammar file: file:///private/var/folders/pf/_zjf_55d7mgb5llg516d7fyc0000gn/T/AppTranslocation/2D4D779A-4682-4742-AC05-CA8DA4F0FF38/d/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/python/syntaxes/MagicPython.tmLanguage.json.
New grammar file: file:///Users/alexandergursky/.vscode/extensions/magicstack.magicpython-1.1.0/grammars/MagicPython.tmLanguage

--YELLOW ERROR--
> console.ts:137 [Extension Host] Git installation not found.

--RED ERROR--
> notificationsAlerts.ts:42 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.

--GRAY ERROR--
>   ERR [Extension Host] extension activation failed TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

--RED ERROR--
> console.ts:137 [Extension Host] extension activation failed TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

--YELLOW ERROR--
> console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function

-- RED ERROR--
> mainThreadExtensionService.ts:79 [[object Object]]s.notebooks.createNotebookControllerDetectionTask is not a function

--RED ERROR--
> mainThreadExtensionService.ts:80 TypeError: s.notebooks.createNotebookControllerDetectionTask is not a function
	at h.startRefreshWithPython (/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2070921)
	at h.activate (/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:2069968)
	at /Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163983
	at Array.map (<anonymous>)
	at c.activateSync (/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:17:163973)
	at /Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003301027/out/extension.node.js:2:1576749
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

--YELLOW ERROR--
> DevTools failed to load source map: Could not load content for https://file+.vscode-resource.vscode-cdn.net/Users/alexandergursky/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.12/out/client_renderer/preload.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED

-----------------------------------------------------------------------
My solution: 
1. Travel to website https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

2. Download version v2022.11.1003281132

3. Return to VScode and open Command Palette

4. Run 'Extensions: Install from VSIX'

5. Select file named 'ms-toolsai.jupyter-2022.11.1003281132.vsix' (this is the downloaded version pulled from https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)

6. Select Install

7. Restart and Quit VSCode for update to take hold

Issue is now, 'band-aided', temporarily resolved, fixed
-----------------------------------------------------------------------
System Information: 

macOS Monterey
Version 12.6.1
Processor 2.9 GHz Dual-Core Intel Core i5
Memory 8GB 2133 MHz LPDDR3
Graphics Intel Iris Graphics 550 1536 MB

Visual Studio Code Information:

Visual Studio Code
Version 1.73.1 (Universal)
-----------------------------------------------------------------------
Extension version: 2022.11.1003281132
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 5, 9|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 1c78b910-2956-4037-a7f3-b9788e46cef8|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by Brainor** [comment] 2022-11-25 05:33
duplicate of #12160
According to the [comment](https://github.com/microsoft/vscode-jupyter/issues/12160#issuecomment-1326825258)
1. use VSCode-inserder
2. use pre-release Jupyter `v2022.11.1003281132` as you mentioned
3. wait for stable Jupyter to update

**Comment by Brainor** [comment] 2022-11-25 05:41
By the way, if you want to install an old version of an extension, just follow the instruction [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) without manually downloading the extension file.

**Closed** 2022-12-12 22:11 UTC
Labels: bug, duplicate
