### ISSUE TITLE
IPython install failed for new conda environment

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11781] opened 2022-10-25 17:29 UTC
Testing #11755

I created a new conda environment with the `Python: Create Environment` command
When ran a cell in the IW, I was prompted to install IPython and clicked install
The cell fails, but the install seemed to actually work, subsequent cell executions are successful

The cell failed to execute with the error

Running cells with 'c:\src\test\5\.conda\python.exe' requires ipykernel package.
Run the following command to install 'ipykernel' into the Python environment. 
Command: 'conda install -p c:\src\test\5\.conda\python.exe ipykernel --update-deps --force-reinstall'

Error popup:

Error processing line 7 of C:\Users\aamunger\AppData\Roaming\Python\Python310\site-packages\pywin32.pth: Traceback (most recent call last): File "c:\src\test\5\.conda\lib\site.py", line 186, in addpackage exec(line) File "<string>", line 1, in <module> ModuleNotFoundError: No module named 'pywin32_bootstrap' Remainder of file ignored c:\src\test\5\.conda\python.exe: No module named ipykernel_launcher. View Jupyter [log](command:jupyter.viewOutput) for further details.

**Comment by amunger** [comment] 2022-10-25 18:29
While trying to repro this again, I can no longer get a cell to run at all in a conda environment, mostly failing with 

```
Error processing line 7 of C:\Users\aamunger\AppData\Roaming\Python\Python310\site-packages\pywin32.pth:

  Traceback (most recent call last):
    File "c:\src\test\4\.conda\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'pywin32_bootstrap'

Remainder of file ignored
c:\src\test\4\.conda\python.exe: No module named ipykernel_launcher. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
```

**Comment by DonJayamanne** [comment] 2022-10-25 20:28
looks like the conda env isn't detected as a conda environment
@amunger 
please could you provide the debug logs

**Comment by amunger** [comment] 2022-10-25 22:23
maybe there's a hidden dependency on having `conda` in my path? I'm seeing quite a few logs in python that seem to be erroring on conda not being a valid command

**Comment by DonJayamanne** [comment] 2022-10-25 22:36
> maybe there's a hidden dependency on having conda in my path? I'm seeing quite a few logs in python that seem to be erroring on conda not being a valid command

@IanMatthewHuff @amunger 

Please could you install the stable version of Jupyter and test this out again & verify this works there.
I.e. I'd like to verify this is a bug in the new pre-release verison.

I can get this working in pre-release of Jupyter extension, thouh I'm not using `Python: Create Environment` as that fails for me.

@IanMatthewHuff @amunger 
Please create the environment without the Python extension, I believe I've found the bug, and for now try creating the environment without their (python extension) VS Code UI.

**Comment by amunger** [comment] 2022-10-25 22:58
It looks like it behaves the same with stable jupyter and with externally created environments.

There is some flakiness involved - I saw an install work once on the first try, sometimes it works after failing once, sometimes it never works.

**Comment by DonJayamanne** [comment] 2022-10-25 23:04
Upstream bug filed here https://github.com/microsoft/vscode-python/issues/20070

@amunger try the following:
* Create a new conda envionment using the terminal using the CLI `conda create -n <name> python=3.8`
* Install pre-release of Python and Jupyter extension
* Re-load VS Code and wait for this to get discovered in the kernel picker
* Try running a cell and veriy ipykernel gets installed.

This should work, if not, please upload the logs for both extensions

**Comment by DonJayamanne** [comment] 2022-10-25 23:05
Two bugs that cause issues here:
* Upstream https://github.com/microsoft/vscode-python/issues/20069
* Upstream https://github.com/microsoft/vscode-python/issues/20070

**Comment by IanMatthewHuff** [comment] 2022-10-25 23:07
Yeah, I have issues with an externally created conda env in Stable as well, so not a Python API regression. However it is a regression from some X amount of time, as this used to work. Just not sure when it broke.

**Comment by DonJayamanne** [comment] 2022-10-26 00:18
I'm looking into this now.
Looks like we have 2 issues, it doesn't work in stable and doesn't work in pre-release.
With pre-release it will not workk because of some upstream issues.
@amunger @IanMatthewHuff 
* Please could you upload the logs for pre-release jupyter with stable Python
    * Does this work here?
* Please could you upload the logs for stable jupyter with stable Python
    * Does this work here?

Thanks

**Comment by amunger** [comment] 2022-10-26 17:54
so today, all scenarios I tested with pre-release and stable will give an error in the cell output as if the IPython package installation failed, but running the cell again will succeed. It's very possible that I didn't attempt to rerun a cell when trying this yesterday.

These were all done with clean conda environments that were created externally from vscode.

[jupyterLogs_bothprelease.txt](https://github.com/microsoft/vscode-jupyter/files/9872404/jupyterLogs_bothprelease.txt)
[jupyterLogs_prereleasePython_stableJupyter_failsuccess.txt](https://github.com/microsoft/vscode-jupyter/files/9872405/jupyterLogs_prereleasePython_stableJupyter_failsuccess.txt)
[jupyterLogs_stablePython_prereleaseJupyter_failsuccess.txt](https://github.com/microsoft/vscode-jupyter/files/9872406/jupyterLogs_stablePython_prereleaseJupyter_failsuccess.txt)
[pythonLogs_prereleasePython_stableJupyter_failsuccess.txt](https://github.com/microsoft/vscode-jupyter/files/9872407/pythonLogs_prereleasePython_stableJupyter_failsuccess.txt)
[pythonLogs_stablePython_prereleaseJupyter_failsuccess.txt](https://github.com/microsoft/vscode-jupyter/files/9872408/pythonLogs_stablePython_prereleaseJupyter_failsuccess.txt)

**Comment by amunger** [comment] 2022-10-26 18:15
Just confirmed that a conda env created with `Python: create Environment` still fails repeatedly

**Comment by DonJayamanne** [comment] 2022-10-26 18:19
> Just confirmed that a conda env created with Python: create Environment still fails repeatedly

Yes, this is due to an upstream bug in Python extesnion, see here https://github.com/microsoft/vscode-jupyter/issues/11781#issuecomment-1291230337

**Comment by rebornix** [comment] 2022-10-31 02:17
Both bugs leading to this bug were fixed in upstream, closing this issue for verifcation.

**Closed by rebornix** 2022-10-31 02:17 UTC
Labels: bug, upstream-python

**Comment by DonJayamanne** [comment] 2022-11-01 19:51
Verified as working (upstream Python extension issue has been resolved)
