### ISSUE TITLE
Cannot run lines in multiple interactive windows at the same time

### ISSUE THREAD

**Issue by xiejx5** [microsoft/vscode-jupyter#8615] opened 2021-12-23 08:02 UTC
## Environment data

-   VS Code version: 1.63.2
-   Jupyter Extension version: 2021.11.1001550889
-   Python Extension version: 2021.12.1559732655
-   OS and version: Windows 10 2004
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used: N/A
-   Jupyter server running: Local

## Expected behaviour

Run two time-consuming codes in multiple interactive windows simultaneously, like in the 2021.10 version Jupyter.

## Actual behaviour

The first window successfully executes the code, while the second window does not execute until the first window finishes.

## Steps to reproduce:

Open an interactive window, and use "Run Selection/Line in Interactive Window" to send the following code.
```python
while True:
   pass
```
![image](https://user-images.githubusercontent.com/29588684/147207870-2743d36c-ccdb-42eb-aabc-91a6ab63bea5.png)

Open a second interactive window, and use "Run Selection/Line in Interactive Window" to send the same code to the second window. The second window cannot execute the code unless we turn off the first window.
![image](https://user-images.githubusercontent.com/29588684/147207993-e85b4287-e0a1-4ba9-a7b8-8b6bb2a6dd34.png)

**Comment by xiejx5** [comment] 2021-12-23 08:21
I think the error is related to the change of 2021.11.100.

"For interactive window commands (run all, run above, run below) add them to a queue instead of just trying to execute one by one. (#6982)"

Maybe different interactive windows should have their own queues?

**Comment by DonJayamanne** [comment] 2021-12-23 17:30
Thanks for filing this issue, we'll look into this in the new year.

**Comment by xiejx5** [comment] 2021-12-23 19:41
Merry Christmas and Thanks for your efforts in 2021.

**Comment by greazer** [comment] 2022-01-03 21:25
Seems likely a dupe of #8022. Verify after that one is fixed.

**Closed** 2022-01-05 21:44 UTC
Labels: bug, notebook-regression, interactive-window

**Comment by JackyWeng526** [comment] 2022-06-23 02:46
I have the same problem currently.
I want to test two python scripts simultaneously, but all outputs are messed up in ONE interactive window and not executed in TWO interactive windows respectively.
Is there any suggestion to fix/recover my vscode settings for this issue?

**Comment by rchiodo** [comment] 2022-06-23 16:10
> I have the same problem currently. I want to test two python scripts simultaneously, but all outputs are messed up in ONE interactive window rather than executed in TWO interactive windows respectively. Is there any suggestion to fix/recover my vscode settings for this issue?

There's actually a setting for that:

![image](https://user-images.githubusercontent.com/19672699/175345300-03c54f7c-9f52-4efd-83ea-98a1f12ead64.png)

If you set it to 'perFile' we'll create a new interactive window for every script you run from.

**Comment by JackyWeng526** [comment] 2022-06-24 05:39
Thank you so much. It saves my coding life.
