### ISSUE TITLE
Cmd+1/2 doesn't focus on the input box of Interactive Window

### ISSUE THREAD

**Issue by corneliusroemer** [microsoft/vscode-jupyter#6636] opened 2021-07-09 14:11 UTC
The bug is back. I'm opening this here just to point at the issue in the VS code tracker, because I was about to open it here and only after a lengthy search found out that the issue is already open over there.

Upstream: https://github.com/microsoft/vscode/issues/124788

**Comment by rchiodo** [comment] 2021-07-12 18:13
Dupe of #6602

**Closed by rchiodo** 2021-07-12 18:13 UTC
Labels: needs-triage
