### ISSUE TITLE
import of gdal fails in Jupyter Extension v2024.3.0

### ISSUE THREAD

**Issue by nkruskamp** [microsoft/vscode-jupyter#15518] opened 2024-04-08 18:57 UTC
## Environment data

-   VS Code version: 1.88.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.3.0
-   Python Extension version (available under the Extensions sidebar): v.2024.4.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.11.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local
-  conda version 23.7.1
-  gdal version 3.8.5 installed via conda from conda-forge channel

## Expected behaviour

I expect to be able to import gdal from a fresh conda environment using the below code in a jupyter interactive session in VS Code.

`from osgeo import gdal`

## Actual behaviour

`from osgeo import gdal` retuns an error:
`ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.`
`ModuleNotFoundError: No module named '_gdal'`

## Steps to reproduce:

1. create the environment
`conda create -n gdal_test -c conda-forge python=3.11 gdal ipykernel`

2. In VS Code, start a new Jupyter interactive session (F1, Jupyter: Create Interactive Window).
3. Select the newly created `gdal_test` kernel
4. enter `from osgeo import gdal`

## current solution

Roll back Jupyter extension to v2024.2.0

It appears the latest version of the Jupyter extension fails for me to import gdal.

**Comment by nkruskamp** [comment] 2024-04-08 20:36
To add, if I run the same code in python in either a terminal directly (bash: `python -c "from osgeo import gdal"`) or a jupyter notebook instance started via the terminal, the above code works. So that also leads me to believe this is a VS Code Jupyter extension issue.

This also seems to impact the use of `pyarrow` for `pandas` and `geopandas` where the behavior described above also applies (runs in terminal or juypter, not in VS Code extension). Except that rolling back to v2024.2.0 of the Jupyter extension still has an issue with `pyarrow`. This may warrant it's own issue?

**Comment by DonJayamanne** [comment] 2024-04-08 20:42
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by nkruskamp** [comment] 2024-04-08 20:45
Rolling back to extension version v2024.1.0 appears to solve the `pyarrow` issue.

I will update the logging settings and get back.

**Comment by nkruskamp** [comment] 2024-04-08 20:48
`16:47:54.106 [info] Handle Execution of Cells 1 for Interactive-1.interactive
16:47:54.106 [debug] Cell Index:1 sent to kernel
16:47:54.126 [debug] Start cell 1 execution @ 1712609274126 (clear output)
16:47:54.127 [debug] Kernel acknowledged execution of cell 1 @ 1712609274126
16:47:54.403 [warn] Cell completed with errors [gd [Error]: No module named '_gdal'
	at r.execute (~\.vscode\extensions\ms-toolsai.jupyter-2024.3.0-win32-x64\dist\extension.node.js:327:4943)] {
  ename: 'ModuleNotFoundError',
  evalue: "No module named '_gdal'",
  traceback: [
    '\x1B[1;31m---------------------------------------------------------------------------\x1B[0m',
    '\x1B[1;31mImportError\x1B[0m                               Traceback (most recent call last)',
    'File \x1B[1;32mc:\\Users\\<username>\\AppData\\Local\\mambaforge\\envs\\gdal_test\\Lib\\site-packages\\osgeo\\__init__.py:30\x1B[0m, in \x1B[0;36mswig_import_helper\x1B[1;34m()\x1B[0m\n' +
      '\x1B[0;32m     29\x1B[0m \x1B[38;5;28;01mtry\x1B[39;00m:\n' +
      '\x1B[1;32m---> 30\x1B[0m     \x1B[38;5;28;01mreturn\x1B[39;00m \x1B[43mimportlib\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mimport_module\x1B[49m\x1B[43m(\x1B[49m\x1B[43mmname\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[0;32m     31\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mImportError\x1B[39;00m:\n',
    'File \x1B[1;32mc:\\Users\\<username>\\AppData\\Local\\mambaforge\\envs\\gdal_test\\Lib\\importlib\\__init__.py:126\x1B[0m, in \x1B[0;36mimport_module\x1B[1;34m(name, package)\x1B[0m\n' +
      '\x1B[0;32m    125\x1B[0m         level \x1B[38;5;241m+\x1B[39m\x1B[38;5;241m=\x1B[39m \x1B[38;5;241m1\x1B[39m\n' +
      '\x1B[1;32m--> 126\x1B[0m \x1B[38;5;28;01mreturn\x1B[39;00m \x1B[43m_bootstrap\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43m_gcd_import\x1B[49m\x1B[43m(\x1B[49m\x1B[43mname\x1B[49m\x1B[43m[\x1B[49m\x1B[43mlevel\x1B[49m\x1B[43m:\x1B[49m\x1B[43m]\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mpackage\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mlevel\x1B[49m\x1B[43m)\x1B[49m\n',
    'File \x1B[1;32m<frozen importlib._bootstrap>:1204\x1B[0m, in \x1B[0;36m_gcd_import\x1B[1;34m(name, package, level)\x1B[0m\n',
    'File \x1B[1;32m<frozen importlib._bootstrap>:1176\x1B[0m, in \x1B[0;36m_find_and_load\x1B[1;34m(name, import_)\x1B[0m\n',
    'File \x1B[1;32m<frozen importlib._bootstrap>:1147\x1B[0m, in \x1B[0;36m_find_and_load_unlocked\x1B[1;34m(name, import_)\x1B[0m\n',
    'File \x1B[1;32m<frozen importlib._bootstrap>:676\x1B[0m, in \x1B[0;36m_load_unlocked\x1B[1;34m(spec)\x1B[0m\n',
    'File \x1B[1;32m<frozen importlib._bootstrap>:573\x1B[0m, in \x1B[0;36mmodule_from_spec\x1B[1;34m(spec)\x1B[0m\n',
    'File \x1B[1;32m<frozen importlib._bootstrap_external>:1233\x1B[0m, in \x1B[0;36mcreate_module\x1B[1;34m(self, spec)\x1B[0m\n',
    'File \x1B[1;32m<frozen importlib._bootstrap>:241\x1B[0m, in \x1B[0;36m_call_with_frames_removed\x1B[1;34m(f, *args, **kwds)\x1B[0m\n',
    '\x1B[1;31mImportError\x1B[0m: DLL load failed while importing _gdal: The specified procedure could not be found.',
    '\nDuring handling of the above exception, another exception occurred:\n',
    '\x1B[1;31mModuleNotFoundError\x1B[0m                       Traceback (most recent call last)',
    'Cell \x1B[1;32mIn[2], line 1\x1B[0m\n' +
      '\x1B[1;32m----> 1\x1B[0m \x1B[38;5;28;01mfrom\x1B[39;00m \x1B[38;5;21;01mosgeo\x1B[39;00m \x1B[38;5;28;01mimport\x1B[39;00m gdal\n',
    'File \x1B[1;32mc:\\Users\\<username>\\AppData\\Local\\mambaforge\\envs\\gdal_test\\Lib\\site-packages\\osgeo\\__init__.py:35\x1B[0m\n' +
      '\x1B[0;32m     31\x1B[0m     \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mImportError\x1B[39;00m:\n' +
      "\x1B[0;32m     32\x1B[0m         \x1B[38;5;28;01mreturn\x1B[39;00m importlib\x1B[38;5;241m.\x1B[39mimport_module(\x1B[38;5;124m'\x1B[39m\x1B[38;5;124m_gdal\x1B[39m\x1B[38;5;124m'\x1B[39m)\n" +
      '\x1B[1;32m---> 35\x1B[0m _gdal \x1B[38;5;241m=\x1B[39m \x1B[43mswig_import_helper\x1B[49m\x1B[43m(\x1B[49m\x1B[43m)\x1B[49m\n' +
      '\x1B[0;32m     36\x1B[0m \x1B[38;5;28;01mdel\x1B[39;00m swig_import_helper\n' +
      '\x1B[0;32m     38\x1B[0m __version__ \x1B[38;5;241m=\x1B[39m _gdal\x1B[38;5;241m.\x1B[39m__version__ \x1B[38;5;241m=\x1B[39m _gdal\x1B[38;5;241m.\x1B[39mVersionInfo(\x1B[38;5;124m"\x1B[39m\x1B[38;5;124mRELEASE_NAME\x1B[39m\x1B[38;5;124m"\x1B[39m)\n',
    'File \x1B[1;32mc:\\Users\\<username>\\AppData\\Local\\mambaforge\\envs\\gdal_test\\Lib\\site-packages\\osgeo\\__init__.py:32\x1B[0m, in \x1B[0;36mswig_import_helper\x1B[1;34m()\x1B[0m\n' +
      '\x1B[0;32m     30\x1B[0m     \x1B[38;5;28;01mreturn\x1B[39;00m importlib\x1B[38;5;241m.\x1B[39mimport_module(mname)\n' +
      '\x1B[0;32m     31\x1B[0m \x1B[38;5;28;01mexcept\x1B[39;00m \x1B[38;5;167;01mImportError\x1B[39;00m:\n' +
      "\x1B[1;32m---> 32\x1B[0m     \x1B[38;5;28;01mreturn\x1B[39;00m \x1B[43mimportlib\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43mimport_module\x1B[49m\x1B[43m(\x1B[49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[38;5;124;43m_gdal\x1B[39;49m\x1B[38;5;124;43m'\x1B[39;49m\x1B[43m)\x1B[49m\n",
    'File \x1B[1;32mc:\\Users\\<username>\\AppData\\Local\\mambaforge\\envs\\gdal_test\\Lib\\importlib\\__init__.py:126\x1B[0m, in \x1B[0;36mimport_module\x1B[1;34m(name, package)\x1B[0m\n' +
      '\x1B[0;32m    124\x1B[0m             \x1B[38;5;28;01mbreak\x1B[39;00m\n' +
      '\x1B[0;32m    125\x1B[0m         level \x1B[38;5;241m+\x1B[39m\x1B[38;5;241m=\x1B[39m \x1B[38;5;241m1\x1B[39m\n' +
      '\x1B[1;32m--> 126\x1B[0m \x1B[38;5;28;01mreturn\x1B[39;00m \x1B[43m_bootstrap\x1B[49m\x1B[38;5;241;43m.\x1B[39;49m\x1B[43m_gcd_import\x1B[49m\x1B[43m(\x1B[49m\x1B[43mname\x1B[49m\x1B[43m[\x1B[49m\x1B[43mlevel\x1B[49m\x1B[43m:\x1B[49m\x1B[43m]\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mpackage\x1B[49m\x1B[43m,\x1B[49m\x1B[43m \x1B[49m\x1B[43mlevel\x1B[49m\x1B[43m)\x1B[49m\n',
    "\x1B[1;31mModuleNotFoundError\x1B[0m: No module named '_gdal'"
  ]
}
16:47:54.404 [info] Cell 1 completed in 0.277s (start: 1712609274126, end: 1712609274403)
16:47:54.404 [debug] Cell 1 executed with an error`

**Comment by DonJayamanne** [comment] 2024-04-08 23:01
Pleaser can you upload the full log

**Comment by nkruskamp** [comment] 2024-04-09 16:44
Ah sorry. See the above comment for the updated log. I think I've captured it all now.

**Comment by DonJayamanne** [comment] 2024-04-09 21:12
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15524

**Closed by DonJayamanne** 2024-04-09 21:12 UTC
Labels: bug, info-needed, notebook-kernel
