### ISSUE TITLE
Jupyter ext does not detect Python ext in GH Codespaces

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#13911] opened 2023-07-13 20:33 UTC
Note this happens in any repo I create a GH codespace from scratch.

Repro (from the Browser):
1. Navigate to any github repository
2. Launch a codespace
3. Install the Python and Jupyter extensions
4. Attempt to execute a notebook cell

Expected: I am prompted to select a local Python environment

Actual: Jupyter ext is unable to detect any kernels nor does it provide the option to select a kernel (since it doesnt detect that the python extension is installed)

Note, the Python extension is installed and running. I am able to execute Python extension commands successfully.

Python ext version
![image](https://github.com/microsoft/vscode-jupyter/assets/15910920/1fab4dbe-a9d5-4fc4-9f52-355060f4e059)

Jupyter ext Version
![image](https://github.com/microsoft/vscode-jupyter/assets/15910920/f86c74bb-3b58-4c23-98f1-fb00ac8157a2)

Note that I am only provided the option to select an existing server from URL
![image](https://github.com/microsoft/vscode-jupyter/assets/15910920/9006b6ab-54a9-4431-a29c-76c32dc5030d)

Jupyter output logs
![image](https://github.com/microsoft/vscode-jupyter/assets/15910920/5c4cc09d-4605-434d-828c-e0834c92805b)

Showing that the Python ext is correctly activated
![image](https://github.com/microsoft/vscode-jupyter/assets/15910920/063c2457-66c3-4e23-816c-f281b40c3161)

**Comment by minsa110** [comment] 2023-07-24 18:04
Also ran into this today: https://github.com/microsoft/vscode-jupyter/issues/13972

**Comment by DonJayamanne** [comment] 2023-07-30 23:41
Duplicate of https://github.com/microsoft/vscode/issues/189280
@jmew @minsa110 this is caused by an issue in VS Code

**Closed by DonJayamanne** 2023-07-30 23:41 UTC
Labels: bug, upstream-vscode
