### ISSUE TITLE
[Endgame testing] ipykernel 6 required for debugging to work - not informed when using lower version and strange behavior

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#6405] opened 2021-06-29 18:31 UTC
testing https://github.com/microsoft/vscode/issues/127362 , debugged with @DavidKutu 

## Expected behaviour

I expected debugging to work with ipykernel 5.5.5 installed 

## Actual behaviour

It did not and had some confusing behavior:
- `Jupyter: Debug` appeared in the command palette, but only on window reload
- I could set breakpoints, but they wouldn't get hit

To resolve this, I had to uninstall ipykernel and re-install the latest version with ` pip install ipykernel --pre`

**Comment by DavidKutu** [comment] 2021-06-30 22:23
Now that ipykernel 6 just released. I was thinking we could always expose the button and have it show a message if you don't have it and offer a button to do the installation for you.

@roblourens  had another idea to make this feel more native, to remove the button altogether and have the session start silently when you open the notebook, there would be no extra steps to start debugging, just set a breakpoint and run cells.

**Comment by DavidKutu** [comment] 2021-08-12 17:10
dupe of #7056

**Closed by DavidKutu** 2021-08-12 17:10 UTC
Labels: bug, run-by-line
