### ISSUE TITLE
Debug Cell mode executes in a new tab on a temporary .py file

### ISSUE THREAD

**Issue by r-moret** [microsoft/vscode-jupyter#8259] opened 2021-11-12 20:48 UTC
## Environment data

-   VS Code version: 1.62.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Enterprise 21H1
-   Python and/or Anaconda version: Python 3.8.0    Anaconda 2021.05
-   Type of virtual environment used: conda
-   Jupyter server running: N/A

## Expected behaviour

When activating the Debug Cell mode the cell is supposed to be executed inplace (in the current tab of VS) stopping on every breakpoint marked by the user.

## Actual behaviour

When activating the Debug Cell mode VS opens a new tab with the code of the cell in a new temporary `.py` file that is removed when I finish the execution. 
The debug is executed well in this tab because I can stop on every breakpoint but it gives some errors caused due to the use of functions not declared on the same cell (because in the temp `.py`, as it only contains code from one cell, is unable to find the function declaration, or import, if it is an external function). Although the errors have to be just static because in the execution it finds the function declarations and ends the code well.

## Steps to reproduce:

1. Open a Jupyter Notebook on VS Code

2.  Click on "Debug Cell" in the menu next to the principal Run cell button.

![Debug_Cell](https://user-images.githubusercontent.com/48282844/141386638-d8c5210c-6c15-4b5c-a0d6-080fbd813bd4.gif)

## Logs

There are no logs for this issue.

**Comment by greazer** [comment] 2021-11-12 22:38
Probably the same root cause as #8258, so closing this as a dupe. If after #8258 is resolved, this still repro's please reopen it. Thanks @r-moret!

**Closed by greazer** 2021-11-12 22:38 UTC
Labels: bug, needs-triage, nb-golden
