### ISSUE TITLE
"Restart" kernel button for notebook keeps disappearing even though the kernel is active?

### ISSUE THREAD

**Issue by epicwhale** [microsoft/vscode-jupyter#15280] opened 2024-03-02 10:48 UTC
This one is a bit hard to articulate, but I've been facing it for a few weeks now, so I'm going to give it my best attempt.

## Environment data

-   VS Code version: Version: 1.88.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2024.3.2024030101 (pre-release)
-   Python Extension version (available under the Extensions sidebar): v2024.2.1
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.12.x
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

I would expect the "Restart" button at the top of the notebook to always appear when the Notebook kernel is active.

## Actual behaviour

But frequently, the kernel is running for a Notebook (as I've a cell that just executed a result), but the Restart button never appears.

![image](https://github.com/microsoft/vscode-jupyter/assets/670655/fcf8b026-18c0-4560-9f42-c5785db3e9c2)

If I try to use the "Notebook: Restart Kernel" from command palette
![image](https://github.com/microsoft/vscode-jupyter/assets/670655/6f5c57c3-06ae-4645-b7e4-7da84747872b)

I even noticed the Jupyter tab does not show any variables, almost like it's lost its connection to the kernel temporarily.

## Steps to reproduce:

This bit is tricky. I've noticed this happens especially when I switch between file tabs, or if the Notebook is opened in a separate window. When I switch to-fro between two notebooks, it tends to reappear (I use this as a workaround for now). So maybe the best way to repro is:

1. In a workspace, create a new notebook.
2. Move notebook to separate window, and run a cell. The restart button should appear.
3. Now switch a few times between the notebook window and a file tab inside your workspace, you will notice when you go back to the notebook, the restart button disappears. A few more times, and it reappears.

**Comment by DonJayamanne** [comment] 2024-03-02 23:34
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by epicwhale** [comment] 2024-03-03 00:16
I did switch to verbose, restarted vs code, and repro the issue. Below is the log.. and you can see in screenshot the 'Restart' button is not appearing, even though I just executed a cell successfully moments before.

![image](https://github.com/microsoft/vscode-jupyter/assets/670655/fcbb5435-67c7-4c5f-a350-0565532a1371)


```
00:10:58.215 [debug] Kernel output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-31057R5cJOXCwBj22.json

00:10:58.548 [debug] Waiting for Raw Session to be ready in postStartRawSession
00:10:58.548 [debug] Waiting for Raw session to be ready, status: connected
00:10:58.548 [debug] Raw session connected
00:10:58.548 [debug] Waiting for Raw session to be ready
00:10:58.552 [debug] Waited for Raw session to be ready & got status: connected
00:10:58.552 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
00:10:58.552 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
00:10:58.552 [debug] Sending request for kernelInfo
00:10:58.750 [debug] Got response for requestKernelInfo
00:10:58.750 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 198ms
00:10:58.751 [debug] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
00:10:58.766 [debug] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
00:10:58.766 [debug] End sendTelemetryForPythonKernelExecutable after 15ms
00:10:58.766 [debug] Started running kernel initialization for ~/code/###redacted###/src/app/notebooks/foo_collector.ipynb
00:10:58.766 [debug] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
00:10:58.818 [debug] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 1 output(s)
00:10:58.818 [debug] Determined IPyWidgets Version as 8
00:10:58.818 [debug] Version of IPyWidgets 8 determined after 5.523s
00:10:58.828 [debug] Executing silently Code (idle) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None):
00:10:58.845 [debug] Executing silently Code (completed) = def __VSCODE_inject_module():\ndef __VSCODE_call_function(function, callback, data=None): with 2 output(s)
00:10:58.846 [debug] Requesting Kernel info
00:10:58.847 [debug] Got Kernel info
00:10:58.847 [debug] End running kernel initialization, now waiting for idle
00:10:58.847 [debug] Waiting for idle on (kernel): 9f6f1726-ba1d-481c-a362-43f1e909f8b5 -> idle
00:10:58.848 [debug] Finished waiting for idle on (kernel): 9f6f1726-ba1d-481c-a362-43f1e909f8b5 -> idle
00:10:58.848 [debug] End running kernel initialization, session is idle
00:10:58.854 [info] Registering Kernel Completion Provider from kernel .conda (Python 3.12.2) for language python
00:10:58.855 [debug] IPyWidgetScriptSource.initialize
00:10:58.855 [debug] IPyWidgetMessageDispatcher.initialize
00:10:58.876 [debug] getDataDirsImpl, Class name = Vr (started execution), Arg 1: "~/code/###redacted###/src/app/notebooks/foo_collector.ipynb", Arg 2: "~/code/###redacted###/.conda/bin/python"
00:10:58.876 [debug] Get Custom Env Variables, Class name = Um (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
00:10:58.877 [debug] Get Custom Env Variables, Class name = Um, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
00:10:58.877 [debug] Jupyter Paths : 
00:10:58.879 [info] Process Execution: ~/code/###redacted###/.conda/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024030101-darwin-arm64/pythonFiles/printJupyterDataDir.py
00:10:58.938 [warn] Got a non-existent Jupyter Data Dir file://~/.local/share/jupyter
00:10:58.939 [debug] getDataDirsImpl, Class name = Vr, completed in 63ms, has a truthy return value, Arg 1: "~/code/###redacted###/src/app/notebooks/foo_collector.ipynb", Arg 2: "~/code/###redacted###/.conda/bin/python", Return Value: <Uri:~/Library/Jupyter>, <Uri:~/code/###redacted###/.conda/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
00:10:59.379 [debug] IPyWidgetMessageDispatcher.initialize
00:10:59.379 [debug] Web view is ready to receive widget messages
00:10:59.465 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
00:10:59.465 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
00:10:59.465 [debug] IPyWidgetMessageDispatcher.initialize
00:10:59.465 [debug] IPyWidgetMessageDispatcher.initialize
00:10:59.484 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
00:10:59.484 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
00:10:59.599 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024030101-darwin-arm64/temp/scripts/2f2dd93ffeb4c9c0acff03512bfd4d8dd83285f125b6d275e355e9146008e35f/jupyter
00:10:59.599 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode-insiders/extensions/ms-toolsai.jupyter-2024.3.2024030101-darwin-arm64/temp/scripts/2f2dd93ffeb4c9c0acff03512bfd4d8dd83285f125b6d275e355e9146008e35f/jupyter
00:11:00.044 [debug] Refreshed Environments
00:11:01.045 [info] End refreshing Kernel Picker (1709424652095)
00:11:36.277 [info] Handle Execution of Cells 0 for ~/code/###redacted###/src/app/notebooks/foo_collector.ipynb
00:11:36.282 [debug] Cell Index:0 sent to kernel
00:11:36.288 [debug] Start cell 0 execution @ 1709424696288 (clear output)
00:11:36.288 [info] Kernel acknowledged execution of cell 0 @ 1709424696288
00:11:36.861 [info] End cell 0 execution after 0.572s, completed @ 1709424696860, started @ 1709424696288
00:11:36.861 [debug] Cell 0 executed successfully
```

**Comment by epicwhale** [comment] 2024-03-03 00:19
One thing I noticed is if I click on the kernal name in the top right of the notebook - the 'Restart' button appears (even without me selecting/changing the kernel from the input/dropdown that appears near the command palette) 
![image](https://github.com/microsoft/vscode-jupyter/assets/670655/15196e84-7c28-43e1-a1ea-3c71f95703fb)

**Comment by epicwhale** [comment] 2024-03-03 00:24
and there are no logs produced in the Jupyter output panel when this error dialog appears... 

![image](https://github.com/microsoft/vscode-jupyter/assets/670655/dec7b3b1-3e58-42e6-8cc7-4ed0d64a6203)

**Comment by DonJayamanne** [comment] 2024-03-06 02:58
Please can you open your developer tools using the command `Toggle Developer Tools`, then go into the console window and see if there are any errors there
Thanks

**Comment by DonJayamanne** [comment] 2024-03-06 05:17
Duplicate of https://github.com/microsoft/vscode/issues/200896#issuecomment-1980063937

**Closed by DonJayamanne** 2024-03-06 05:17 UTC
Labels: bug, notebook-toolbar

**Comment by epicwhale** [comment] 2024-03-06 07:44
> Please can you open your developer tools using the command `Toggle Developer Tools`, then go into the console window and see if there are any errors there Thanks

Attached developer tools console... I don't see much activity in the console when I repro this issue, except for the 2 log messages in this file. hope that helps?

[vscode-app-1709710996542.log](https://github.com/microsoft/vscode-jupyter/files/14506404/vscode-app-1709710996542.log)

**Comment by epicwhale** [comment] 2024-03-18 12:23
@DonJayamanne anything more I can help with here? it's causing a lot of pain in my workflows .. :(

**Comment by DonJayamanne** [comment] 2024-03-18 14:21
@Yoyokrazy /cc
