### ISSUE TITLE
Line numbers on notebook are too close to code

### ISSUE THREAD

**Issue by fabiograssiotto** [microsoft/vscode-jupyter#6775] opened 2021-07-23 17:45 UTC
## Environment data

-   VS Code version: 1.59.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1055544705
-   Python Extension version (available under the Extensions sidebar): v2021.8.1057758891-dev
-   OS (Windows | Mac | Linux distro) and version: Windows_NT x64 10.0.19042
-   Python and/or Anaconda version: Python 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local

## Expected behaviour

Line numbers have proper spacing before code

## Actual behaviour

Spacing is too tight

## Steps to reproduce:

1. Enable line numbers on the notebook settings.

![jupyter-line-numbers](https://user-images.githubusercontent.com/6299041/126820408-8ba52d39-f1c1-4bc1-8f55-aadac11ea99c.PNG)

**Comment by fabiograssiotto** [comment] 2021-07-23 18:16
Additionally I believe the spacing was correct before the last update of the plugin (running insiders build).

**Comment by DonJayamanne** [comment] 2021-07-23 18:24
Duplicate of https://github.com/microsoft/vscode/issues/129145

**Closed by DonJayamanne** 2021-07-23 18:24 UTC
Labels: bug, needs-triage
