### ISSUE TITLE
Dataviewer not showing variables when columns are multi-indexed

### ISSUE THREAD

**Issue by riotwhale** [microsoft/vscode-jupyter#11677] opened 2022-10-17 02:19 UTC
## Environment data

-   VS Code version: 1.72.1
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1202862440
-   Python Extension version (available under the Extensions sidebar): v2022.16.1
-   OS (Windows | Mac | Linux distro) and version: Win 10
-   Python version: 3.9.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## Expected & Actual behaviour

When multi-indexing is applied to a dataframe, it will display() correctly inline, however if you double click on the variable from the _Jupyter: Variables_ toolbar then it wont render. **In the code below df2 and 3 wont render.**

EDIT: Just to clarify the code below with df2 and 3 is provided to check it wasnt caused by having a multi-index level being blank. 

## Steps to reproduce:

```import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.randint(0,100,size=(100, 4)), columns=list('ABCD'))

display(df)

df2 = df.copy()

try:
    df2.columns = pd.MultiIndex.from_product([df2.columns, ['']])
except: 
    display("Columns already multi-indexed")

display(df2)

df3 = df2.copy()

df3.columns = pd.MultiIndex.from_tuples(
    [
        ("A", 0),
        ("A", 1),
        ("A", 2),
        ("A", 3),
    ]
)

display(df3)

**Comment by amunger** [comment] 2022-10-17 17:04
thanks for the repro case, confirmed I see the same behavior

**Comment by IanMatthewHuff** [comment] 2022-11-04 20:28
Dupe of #5551

**Comment by YishGene** [comment] 2023-01-24 12:47
I'm still seeing this problem in the jupter extension v2023.1.1003441034. 

I copied the above code snippet by the OP and see this in the Data Viewer:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/16992469/214295448-7432c604-d255-4735-8a7b-914788e352bc.png">

**Comment by VEFM02** [comment] 2024-02-27 18:05
I'm still reproducing this error, I can't see multi-indexed dataframes in data viewer while debugging.

**Comment by amunger** [comment] 2024-11-20 19:11
closing as the jupyter data viewer was deprecated https://github.com/microsoft/vscode-jupyter/issues/15486

**Closed by amunger** 2024-11-20 19:11 UTC
Labels: bug, data-viewer
