### ISSUE TITLE
Implement h (help) command

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#4565] opened 2021-01-29 17:44 UTC
Accessibility for new users, this should bring up all the keyboard shortcuts (a, b, dd) for notebooks.

**Comment by claudiaregio** [comment] 2021-01-29 17:55
Thanks @DavidKutu , will discuss at our team's next triage meeting!

**Comment by DonJayamanne** [comment] 2021-01-29 18:01
Isn't the existing keyboard shortcuts command sufficient. 
Either way if we were to implement our own help command then I vote we just bring up the VS Code keyboard shortcuts (or the like) 

![Screen Shot 2021-01-29 at 09 59 45](https://user-images.githubusercontent.com/1948812/106310762-ea9fa400-6218-11eb-9884-5e23e2136f40.png)

**Comment by DonJayamanne** [comment] 2021-10-19 16:34
Closing as duplicate of https://github.com/microsoft/vscode-jupyter/issues/1307

**Closed by DonJayamanne** 2021-10-19 16:34 UTC
Labels: enhancement, notebook-keybinding, issue_grooming_don
