### ISSUE TITLE
.ipynb Open Changes in Source Control not working

### ISSUE THREAD

**Issue by giammi56** [microsoft/vscode-jupyter#5280] opened 2021-03-24 23:23 UTC
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-45-generic snap

## Expected behaviour

1. Source control upon clicking on a staged on .ipyn (or right click Open Changes): side by side staged and last commit with red and green area for the diff. 
2. Sorce control upon clicking on commit in the timeline: same as above.

## Actual behaviour

1. The file opens, shows (index) in the title for a second, then turn into (git) and display the actual file: no diff, no comparison with the previous commit, just one column.
2.When clicking on a commit in the timeline, SOMETIMES It opens two files side by side with the title "xxxx.ipynb contrast yyyyy.ipynb", but they neither scroll async nor the differences are shown. SOMETIMES shows just one file with title (git).

## Steps to reproduce:

0. [With a the jupyter strip installed and configured](https://github.com/kynan/nbstripout#apply-retroactively).
1.Go to SCM  (ctrl+shoft+G)
2. Stage a .ipynb.
3. click on the stage file (or right click Open Changes)
4. as comparison (and to prove git is working fine) open a new terminal in vs code
5.  type git diff --cahced

NOTE: everything works fine for .py scripts. This problem persists for 2 months.

**Comment by DonJayamanne** [comment] 2021-03-25 00:41
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/633

**Closed by DonJayamanne** 2021-03-25 00:41 UTC
Labels: bug
