### ISSUE TITLE
Jupyter file cause VS Code disconnect from WSL

### ISSUE THREAD

**Issue by viethung9at1** [microsoft/vscode-jupyter#14528] opened 2023-10-19 04:35 UTC
## Environment data

-   VS Code version: 1.83.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1002931100
-   Python Extension version (available under the Extensions sidebar):  v2023.18.0
-   OS (Windows | Mac | Linux distro) and version: Windows: 10.0.22621.2428, WSL: 5.15.90.1-microsoft-standard-WSL2
-   Python and/or Anaconda version: 3.11
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

Running normally

## Actual behaviour

Lost connect to WSL

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create or open any jupyter notebook file
2. Lost connection from WSL
3. Reload WSL
4. File not found

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2023-10-19 14:26
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/14529

**Closed by DonJayamanne** 2023-10-19 14:26 UTC
Labels: bug
