### ISSUE TITLE
Selecting install from prompt when missing `pip` fails because pip is not available

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10400] opened 2022-06-09 19:57 UTC
1. Install a python interpreter without including pip
2. Select that interpreter as the kernel in vscode and run a cell
3. A prompt shows up saying that IPykernel and pip are required, select install

result:
![image](https://user-images.githubusercontent.com/2019016/172933236-a9ea509d-147b-406c-a881-39ec665fde65.png)

This happened after deleting the windows app python installation, and installing a new 3.10.5 to replace it.

**Comment by rchiodo** [comment] 2022-06-09 20:01
I believe this is by design. You need to have pip available. 

This issue is relevant:
https://github.com/microsoft/vscode-python/issues/15937

**Comment by amunger** [comment] 2022-06-09 20:02
we shouldn't have an option to install if we know it's going to fail, the installation prompt already says that pip is missing

**Comment by amunger** [comment] 2022-06-09 20:03
![image](https://user-images.githubusercontent.com/2019016/172934338-3aa39044-3ca0-4030-a393-5677f4274375.png)

**Comment by rchiodo** [comment] 2022-06-09 20:11
We probably should not have the install button in this case. Without 'pip' we don't want to get pip for the user. They should do it but we need to make that clearer.

**Comment by amunger** [comment] 2022-06-09 20:14
I might be in this situation because of a bad python installation, pip should actually be installed

```
PS C:\src\test\3> python -m pip --version
Error processing line 7 of C:\Users\aamunger\AppData\Roaming\Python\Python310\site-packages\pywin32.pth:

  Traceback (most recent call last):
    File "C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\lib\site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named 'pywin32_bootstrap'

Remainder of file ignored
C:\Users\aamunger\AppData\Local\Programs\Python\Python310_5\python.exe: No module named pip
```

**Comment by DonJayamanne** [comment] 2022-08-15 01:25
@IanMatthewHuff I'm taking this as this falls into installation, and kernel startup and the like.

**Comment by DonJayamanne** [comment] 2023-09-13 09:32
Closing as not planned
No one else has reported this

**Closed by DonJayamanne** 2023-09-13 09:32 UTC
Labels: bug, notebook-kernel, notebook-getting-started
