### ISSUE TITLE
Connect to Jupyter Server redundant step

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12260] opened 2022-12-01 16:17 UTC
* Use stable kernel picker (no setting change) on .dev
* Open kernel picker
* Click on Connect to Jupyter Server
* It should go directly to input box instead of one more additional step to pick "Existing Jupyter Server" command.

**Comment by DonJayamanne** [comment] 2022-12-02 01:59
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12226

**Closed by DonJayamanne** 2022-12-02 01:59 UTC
Labels: bug, kernel-picker
