### ISSUE TITLE
Fix tests after kernel push update.

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5585] opened 2021-04-21 15:12 UTC
Tests were broken to unblock kernel push.

**Comment by joyceerhl** [comment] 2021-04-22 21:09
@IanMatthewHuff were you already working on this? If not I can take this on.

**Comment by IanMatthewHuff** [comment] 2021-04-22 21:12
@joyceerhl please grab it if you have cycles. I did one cleanup pass here, but it's still pretty bad. https://github.com/microsoft/vscode-jupyter/pull/5589

**Comment by joyceerhl** [comment] 2021-04-23 15:56
I think we can close this as a dupe of #5535, it's the same set of tests that are failing (apart from ipywidgets, which are legitimately broken).

**Closed** 2021-04-23 16:50 UTC
