### ISSUE TITLE
Code entered into Interactive pane stays after execution

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#8386] opened 2021-11-29 21:10 UTC
This is different to all other implementations of IPython I have used.  It is also different to how it used to work in VS Code.  After I execute the code in the Interactive pane, the code should disappear.  If I want to run the same code again, the up arrow should work.  I don't need the executed code to hang around in the Interactive pane 

## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment] 2021-11-29 21:36
This might be a dupe of https://github.com/microsoft/vscode-jupyter/issues/8203. We've always shown the code in the interactive window but there's a setting to disable that. I believe the setting isn't being applied correctly right now.

**Comment by clayms** [comment] 2021-11-29 22:19
Hi @rchiodo 
Not the same place as #8203 , I am referring to the code entry point at the bottom of the interactive pane.  Not sure what you call this specific entry point. 

Executing the code by pressing <kbd>shift</kbd>+<kbd>enter</kbd> and the code stays in this spot.  
However, pressing the "play" button <kbd>▷</kbd> at the left, and the code disappears as expected.

![image](https://user-images.githubusercontent.com/12793783/143951407-8e80ac47-e87f-4c8c-8f77-4adb6f301cf4.png)

**Comment by rchiodo** [comment] 2021-11-29 22:27
What's your VS code and jupyter extension versions? I don't repro this. Hitting SHIFT+ENTER in the input box executes the code and deletes the line.

There was a problem with the history a while ago, but that should be fixed now.

**Comment by clayms** [comment] 2021-11-30 18:43
Extension version: 2021.10.1101450599
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (2 x 2500)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.43GB free)|
|Process Argv|--crash-reporter-id 1e88d7ed-dfc2-42ed-b5d3-970568cb872e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200:30402083
vsaa593:30376534
vssld246:30401890
vscexrecpromptt1:30404947
vscop804:30404766
vs360cf:30404996

```

</details>

**Comment by rchiodo** [comment] 2021-11-30 18:53
That's the same version I have. Do you have any other extensions installed? (Like maybe VIM?)

Additionally do you have any keybindings set?

**Comment by clayms** [comment] 2021-12-02 20:34
No other extensions.

Here are my other keybindings for "shift+enter".   These were the same before I started seeing this problem.


```
    {
        "key": "shift+enter",
        "command": "-python.execSelectionInTerminal",
        "when": "editorTextFocus && !findInputFocussed && !python.datascience.ownsSelection && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "jupyter.execSelectionInteractive",
        "when": "editorTextFocus && !python.datascience.hascodecells && !findInputFocussed && !python.datascience.ownsSelection && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "jupyter.execSelectionInteractive",
        "when": "editorTextFocus && python.datascience.hascodecells && !findInputFocussed && !python.datascience.ownsSelection && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "jupyter.execSelectionInteractive",
        "when": "editorTextFocus && python.datascience.featureenabled && python.datascience.ownsSelection && !findInputFocussed && !replaceInputFocussed && editorLangId == 'python'"
    },
    {
        "key": "shift+enter",
        "command": "jupyter.execSelectionInteractive",
        "when": "editorTextFocus && python.datascience.featureenabled && !python.datascience.hascodecells && !editorHasSelection && python.datascience.ownsSelection"
    },
    {
        "key": "shift+enter",
        "command": "jupyter.runcurrentcelladvance",
        "when": "editorTextFocus && jupyter.featureenabled && jupyter.hascodecells && !editorHasSelection"
    }
```

**Comment by rebornix** [comment] 2022-01-20 20:11
@clayms it seems you have duplicated keybinding entries for `jupyter.execSelectionInteractive` command, can you please try removing all keybindings and try if you can reproduce?

**Comment by clayms** [comment] 2022-03-31 21:52
@IanMatthewHuff   That was several computers ago. I know I am not having the issue anymore, and the "duplicates" are still there.  The 'when' clauses are different in each case.

**Closed** 2022-05-04 17:20 UTC
Labels: info-needed, interactive-window
