### ISSUE TITLE
Set default kernel to the latest Python version on creating a new Jupyter notebook or load a Jupyter notebok file

### ISSUE THREAD

**Issue by wyatt-wong** [microsoft/vscode-jupyter#16240] opened 2024-11-21 17:38 UTC
When a new Jupyter was created or an existing Jupyer notebook was loaded, user need to select the Kernel version in order to execute the Jupyter commands.

It is adivised to set the default kernel version to the latest Python version for newly created notebook or Jupyter notebook loaded from disk.

**Comment by DonJayamanne** [comment] 2024-11-22 10:28
Thank you for filing this feature request.

kernels will not be changed to the latest version of Python environment for new or existing notebooks.
This is by design, its basically the MRU, we preserve the last used kernel for a notebook
For new notebooks, you will have to select one as we found that users can make the right decision. In the past Jupyter extension would attempt to select these by default but that failed a lot more than it was successful.

You can use this extension to change the default extension https://marketplace.visualstudio.com/items?itemName=donjayamanne.vscode-default-python-kernel

> or an existing Jupyer notebook was loaded, user need to select the Kernel version in order to execute

This should not occur, this is definitely a bug if it does.
Please ensure you have the latest version of VS Code and Jupyter extension.
If this still persists for existing notebooks, then please do ping here or feel free to create a new issue.

Closing this as designed

**Closed by DonJayamanne** 2024-11-22 10:28 UTC
Labels: feature-request
