### ISSUE TITLE
Saved, but new ipynb file continues to remain dirty.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9390] opened 2022-03-16 20:55 UTC
Version: 1.66.0-insider (user setup)
Commit: 6fa3243d3facbbf8b87222bcf4e81c5eddf5d47f
Date: 2022-03-16T05:17:27.938Z
Electron: 17.1.1
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22572

Jupyter:  v2022.3.1000771005

1. File -> New File... -> Jupyter Notebook
2. Save the file, but don't change the name -- Untitled-1.ipynb for instance.

The file is saved, but the state remains dirty.

Notes:
- If you disable the jupyter extension this problem goes away.
- If you name the file something other than Untitled-X, the problem goes away.
- Apparently this occurred with last month's release as well, so not a *recent* regression
-

**Comment by DonJayamanne** [comment] 2022-03-16 22:27
Weird, I cannot repro this in WSL nor on Windows, (with the latest Insider & Pre-release bits)

**Comment by greazer** [comment] 2022-03-17 00:29
Hmmm.. @amunger could repro. I just checked my setup. Definitely up-to-date with everything.

Aaron indicated that you can open the saved ipynb file right next to the one that's dirty. I can too:
<img width="751" alt="image" src="https://user-images.githubusercontent.com/11685408/158713218-63d35daf-6574-4bff-9973-dbb18965b874.png">

**Comment by DonJayamanne** [comment] 2022-03-17 20:20
Rich, Ian, Don cannot repro this issue.
@amunger Please could you try the following:
* Uninstall/disable all extensions except Jupyter extension & try this out
* Possible its not related to Jupyter extension.

**Comment by amunger** [comment] 2022-03-17 21:38
Still repros with all extensions except Jupyter disabled, can't get it to repro with Jupyter disabled

**Comment by rchiodo** [comment] 2022-05-26 17:30
Now I can't repro anymore. Not sure what the issue is. Closing until we get a customer complaining.

**Closed by rchiodo** 2022-05-26 17:30 UTC
Labels: bug, notebook-serialization-save-load
