### ISSUE TITLE
Remote jupyter doesn't reconnect after computer sleeps

### ISSUE THREAD

**Issue by 8enmann** [microsoft/vscode-jupyter#1654] opened 2020-07-12 04:42 UTC
Maybe related: microsoft/vscode-jupyter#822 
# Bug: Notebook Editor, Interactive Window, Editor cells

Steps to Reproduce:

1. Connect to a remote jupyter server
2. Sleep laptop
3. Try to run a cell
Error: Cannot execute code, session has been disposed. Source: Python (Extension)

The workaround I use is close the notebook editor and reopen it, but this loses all my cells. Remote server still has the session.

### Your Jupyter and/or Python environment

Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z (2 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

-   **Jupyter server running:** Remote 
-   **Extension version:** v2020.6.91350
-   **Setting python.languageServer:** pylance
-   **Python and/or Anaconda version:** Python 3.7.3
-   **Virtual environment:** conda

## Developer Tools Console Output

Error Python Extension: 2020-07-11 21:30:39: [Error: Kernel is dead	at f._sendKernelShellControl (/Users/ben/.vscode/extensions/ms-python.python-2020.6.91350/out/client/node_modules/@jupyterlab/services.js:3:510258)	at f.sendShellMessage (/Users/ben/.vscode/extensions/ms-python.python-2020.6.91350/out/client/node_modules/@jupyterlab/services.js:3:510027)	at f.requestExecute (/Users/ben/.vscode/extensions/ms-python.python-2020.6.91350/out/client/node_modules/@jupyterlab/services.js:3:512579)	at _.requestExecute (/Users/ben/.vscode/extensions/ms-python.python-2020.6.91350/out/client/extension.js:1:535559)	at _.requestExecute (/Users/ben/.vscode/extensions/ms-python.python-2020.6.91350/out/client/extension.js:48:460661)	at f.P.generateRequest (/Users/ben/.vscode/extensions/ms-python.python-2020.6.91350/out/client/extension.js:48:436320)	at f.P.handleCodeRequest (/Users/ben/.vscode/extensions/ms-python.python-2020.6.91350/out/client/extension.js:48:437313)	at /Users/ben/.vscode/extensions/ms-python.python-2020.6.91350/out/client/extension.js:48:450604	at runMicrotasks (<anonymous>)	at processTicksAndRejections (internal/process/task_queues.js:85:5)]
t.log @ workbench.desktop.main.js:sourcemap:266
workbench.desktop.main.js:sourcemap:2947 Error: Cannot execute code, session has been disposed.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by 8enmann** [comment] 2020-11-14 02:34
I believe it tries to reconnect after sleep and then gets 
```workbench.desktop.main.js:sourcemap:2947 Error: Cannot execute code, session has been disposed.```

**Comment by zpincus** [comment] 2021-05-14 21:17
I mentioned this in a separate bug (https://github.com/microsoft/vscode-jupyter/issues/1378#issuecomment-840140940) but its relevant here: it seems **extremely weird** for the notebook session management to be tied to when the UI is unloaded/reloaded. 

To be explicit, I here refer to how vscode manages the "local" juptyer servers that it spins up on its own, not the management of kernels on external/existing/"remote" servers that the user has started separately.

In most other cases, vscode tries really hard to maintain user state: e.g. for the embedded terminal session, if you reload the window, the same terminal session is still present. But if you do that for a notebook session, the kernel is killed and restarted. Ideally, the lifecycle rules for notebook sessions should be the same as for terminal sessions -- i.e. notebook sessions should persist through UI reloads, but be killed when the user explicitly closes the notebook tab or the workspace window (perhaps with an alert). Contra #1738, "kill the kernel when and only when I close the tab/workspace" might be sufficient UI for managing the lifecycle of kernels, at least on vscode's "local" servers.

If UI reloads no longer dispose of running notebooks, this would probably also solve the issues everyone raises above, where disconnects over remote-ssh (which can require reloading the UI to resolve if the disconnect has lasted a while) nuke long-running notebook sessions on the remote-ssh host. It's crazy that a jupyter kernel (the "local" kind, auto-started by the vscode-remote extension on the remote machine) would be happy and alive on the remote machine through the whole disconnect, right up until the vscode client manages to reconnect, and then the very first thing the client does as part of the UI reload is to kill the kernel instead of reconnecting to it.

This seems like a major misfeature... should I file it as a separate bug, e.g. "notebook kernels should not be disposed of on UI reload" or something?

**Comment by rchiodo** [comment] 2021-05-14 21:19
It is an interesting idea to keep the kernel around until an explicit close of a tab. Meaning closing VS code wouldn't kill anything. You'd have to explicitly close the notebook while VS code was open.

Although this would have to be behind a setting. I would hazard a guess a lot of people that are used to kernels just being cleaned up would be upset if they didn't go away on VS code shutdown.

**Comment by zpincus** [comment] 2021-05-14 21:25
I think it would be reasonable to kill the kernels in any circumstance where a terminal session is also killed. So e.g. quitting vscode would reasonably be expected to kill any local jupyter servers that it spun up internally.

It would also be reasonable to add a setting where the kernel would be left running when vscode is quit but the workspace window is left open, since restarting vscode could be expected to restore all state. But I don't think that's key -- again, terminal sessions are killed in this instance.

The main thing though is that it seems (to me at least) *unreasonable* for reloading the UI to kill local notebook kernels. That is contrary to how the terminal works, and appears to be the root cause of everyone's network-disconnect woes with notebooks running local to remote-ssh hosts...

**Comment by rchiodo** [comment] 2021-05-14 21:35
I need to double check but I don't think we (as an extension) can tell the difference between quitting VS code and reloading the UI. 

AFAIK, the extension host (the process our extension is running in) is shutdown the same each time. We just get our dispose method called. 

Terminals are handled by VS code itself, so it may be able to treat reload differently. 

I think we'd need a new API from VS code to distinguish this case.

**Comment by zpincus** [comment] 2021-05-14 21:52
> I don't think we (as an extension) can tell the difference between quitting VS code and reloading the UI.

Hmm, that *is* a pickle then!

Will the new "native notebook" feature have this limitation too? Or is that part of the core vscode, more like how terminals are handled?

If the latter, perhaps just waiting for that to roll out (and filing bugs on it if needed) would be the best path forward long-term. But if this issue will carry over into the native-notebook world, do let me know if it would be helpful to file an explicit bug to track the root issue about losing user state on UI reload...

**Comment by rchiodo** [comment] 2021-05-14 21:58
Native notebooks will have the same issue. Kernels are controlled by us. 

I don't think we need a new bug. Maybe just some more visibility for this one. We can ask VS code for the ability to tell when reload happens versus shutdown and then it would be possible to not kill kernels on reload.

**Comment by IanMatthewHuff** [comment] 2021-05-14 22:04
> Terminals are handled by VS code itself, so it may be able to treat reload differently.

Pretty sure this is the case, they landed some code semi-recently for supporting this I believe:
https://github.com/Microsoft/vscode/issues/20013

**Comment by rchiodo** [comment] 2021-05-14 22:20
Reading through the PR, gave me some idea. Might be too much work but we could have a heartbeat in the kernel. Say every 10 minutes or something. If VS code doesn't respond, it kills itself. 

That should work in the sleep case (well because the kernel will go to sleep too) and would keep the kernel alive for 10 minutes after a shutdown.

**Comment by zpincus** [comment] 2021-05-14 22:53
Clever idea!

Might not even need a heartbeat per se? Instead of tearing down the Jupiter server directly on ui reload, set an e.g. 10 minute timer in the server process, after which it tears itself down unless the timer is canceled by a reconnect from vscode. Not sure if that’s dramatically simpler than a full heartbeat system, but perhaps?

**Comment by rchiodo** [comment] 2021-12-06 21:52
Related to this.
https://github.com/microsoft/vscode-jupyter/issues/3998

**Comment by Serebryanskiy** [comment] 2021-12-10 14:05
I've recently started using VS code as a Data Scientist and it helps me a lot with autocompletion and UI. From my point of view, it's much better than a Pycharm. Before VS code I usually set up the container on the remote host with project environment inside and jupyter notebook listening on some port. This way I can launch GPU training and safely close the notebook. But with VS code I can't close the notebook or interrupt the connection, since the state of the notebook and the training progress will fail, which is a great issue for anyone who is using jupyter for GPU training. I really love VS code UI and hope there is a way to resolve this issue.

**Comment by zpincus** [comment] 2021-12-10 19:15
@Serebryanskiy -- IMO the best current workaround is to use a separate jupyter server with vscode, just like you did before. (It's called "Remote Jupyter" in the vscode lingo, to differentiate it from the "Local Jupyter" server that vscode will start for you, but which goes away when you close vscode etc.)

Note that with vscode-remote, if you run the jupyter server on the same machine that you're connected to remotely, you connect to your "Remote" Jupyter server on localhost (i.e. local to where vscode-remote is running). To connect to a "Remote" Jupyter server, just click on the "Jupyter Server" button at the lower right of the window and enter the correct URL with token...

It's not perfect; there are a few rough edges compared to using the "Local Jupyter" (e.g. #8285 and #7610) but they're getting fixed over time.

**Comment by vrpatil131** [comment] 2022-08-19 23:08
> @Serebryanskiy -- IMO the best current workaround is to use a separate jupyter server with vscode

Thanks, this seems to be the best workaround so far. Manually started a Jupyter server on remote machine, connected VSCode to it using "Jupyter Server: Remote" option and verified through Jupyter logs (on remote machine) that VSCode window reload, VPN disconnect or quitting and restarting VSCode doesn't kill the current kernel which means all Jupyter state variables are retained.

**Comment by DonJayamanne** [comment] 2022-08-21 22:51
@vpatil131 @zpincus @8enmann @michaelsanchez-pingidentity 
 Its my understanding that this issue is focused on re-connecting to a remote computer
By `Remote` I mean the Jupyter server is running on a remote Machine and VSCode is locally running and you connect to the remote Jupyter server using the remote Jupyter Connection feature in the Jupyter extension.
If however you launch VS Code on the remote maching using `Remote SSH`, then VS Code is running on the remote machine, hence all kernels are also started on the same remote machine, i.e. everything is local with respect to where VS Code is running. Thus when using `Remote SSH`, the kernels are started locally on that machine.


If anyone is running into any issues with re-connecting to remote jupyter server, please do feel free to comment here and I'll re-open this issue, or please feel free to create a new issue.
It is my understanding that there are no problems (at least anymore) with regards to re-connecting to remove jupyter server kernels, i.e. this works.

If on the other hand someone is starting a local kernel, and the connection dies after the computer sleeps, then please upvote or comment on the issue #3998


>  hard to maintain user state: e.g. for the embedded terminal session, if you reload the window, the same terminal session is still present. But if you do that for a notebook session, the kernel is killed and restarted. Ideally, the lifecycle rules for notebook sessions should be the same as for terminal sessions -- i.e. notebook sessions should persist through UI reloads, but be killed when the user explicitly closes the notebook tab or t

The issue that would address this is #3998

> I am not using jupyter or python extensions in VSCode and I have the exact same issue. All my extensions are Javascript and React related. Steps to reproduce are mostly identical.
> 
> log on to Macbook Pro.
Start VPN client.
Launch VSCode
Open SSH connection with VSCode remote to dev server.
work work work.

Here too, everything is local in the context of VS Code, hence #3998 would address this problem


Closing this issue for now, as I believe there has been some confusion around what is local vs remote hence we have duplicate issues.

**Closed by DonJayamanne** 2022-08-21 22:51 UTC
Labels: bug, notebook-remote, notebook-execution
