### ISSUE TITLE
bundled ripgrep may cause cell execution kept loading

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode-jupyter#15572] opened 2024-04-19 05:21 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm noticing a long-time loading (after clicking executing a cell) where `rg.exe`, vscode bundled `ripgrep`, is busy working, with high network usage (almost full bandwidth). As long as it disappears (after ~1-2min) the code cell gets executed immediately (the code cell itself takes several ms). 

The vscode workspace is an opened folder with ~40 GB of data and ~600kb of notebooks. The folder is on remote server (also where the remote kernel is). The folder is not under any version control. The opened notebook is 22kb large. The cell executed is just `pd_df.col_name.value_counts()`. 

What is `rg.exe` searching and is it really triggered by jupyter extension?

### VS Code Version

1.88.1

### Jupyter Extension Version

v2024.3.1

### Jupyter logs

```shell
nothing special. corresponding line is 

11:12:22.033 [info] Cell 28 completed in 0.003s (start: 1713496342030, end: 1713496342033)
```

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment] 2024-04-19 06:29
> What is rg.exe searching and is it really triggered by jupyter extension?

The Jupyter extension does not trigger the `rg.exe` process at all.
I'm inclined to close this as its definitely not done by Jupyter extension, however lets get to the bottom of this issue.

Can you try disabling other extension, such as Pylance or the like.
Please try this with all extensions disabled except for
* Python
* Jupyter 
* Notebook Renderers

Let me know if that works, if it does, then its definitely caused by some other extension. I would suggest using extension [bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) or the like to identify the extension.


Or do you have the find widget opened and have accidentally typed something into that.

> I'm noticing a long-time loading (after clicking executing a cell) where rg.exe, vscode bundled ripgrep, is busy working, with high network usage (almost full bandwidth). 

If you are certain about this, then please can you follow the WIKI and share the CPUprofiles from the following two
* [Profile the running extensions](https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions)
* Profilging the renderer https://github.com/microsoft/vscode/wiki/Performance-Issues#profiling-the-renderer-process

Please read through the WIKI and share the other information as well.

**Comment by yuuuxt** [comment] 2024-04-19 07:31
I'm guessing `rg.exe` is related to git repo auto dedect, and now I'm observing loading issue without `rg.exe` , but only high CPU usage of vscode, and each of the executions kept loading for some time (still clean for Jupyter logs). 

Sorry that to continue work I'm not going to bisect extensions or any investigations for now, so I'm closing it.

**Comment by yuuuxt** [comment] 2024-04-19 07:47
UPDATE: 
After turning git repo auto dedect to false, I open the folder, seeing with ipynb files not being able to open with jupyter extension (saying please enable jupyter extension or open as plain text) and `rg.exe` not working. I reload this window, then the notebook shows as expected, and `rg.exe` starts working. 

So from my observation, it has something related to jupyter extension.

**Closed** 2024-04-19 07:58 UTC
Labels: bug, info-needed, perf
