### ISSUE TITLE
Jupyter Remote kernel with internal SSL cert CA | failed, reason: unable to get local issuer certificate

### ISSUE THREAD

**Issue by lgonzalezsa** [microsoft/vscode-jupyter#9154] opened 2022-02-28 20:11 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Was working fine just before move to another Linux OS and then configuring the vscode installing the extensions.
Trying to connect to my remote compute node (my settings are sync on) then making sure I have selected the setting Jupyter: Allow Unauthorized Remote Connection.
But not able to connect giving me the reason: unable to get local issuer certificate
 
![image](https://user-images.githubusercontent.com/704686/156051294-14f32683-eb54-474b-b19f-1bf8713aa20e.png)

### VS Code Version

1.64.2

### Jupyter Extension Version

v2022.1.1301854968

### Jupyter logs

```shell
Visual Studio Code (1.64.2, undefined, desktop)
Jupyter Extension Version: 2022.1.1301854968.
Python Extension Version: 2022.0.1814523869.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 10:31:45: ZMQ install verified.
Info 10:31:45: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 10:31:45: Checking for server existence.
Info 10:31:45: Checking for server usability.
Info 10:31:45: Starting notebook server.
Info 10:31:45: Connecting to server
Info 10:31:45: Connecting to process server
Info 10:31:45: Connecting server kernel https://the_hostname_fqdn:8000/user/gonluisr/
Connecting to Jupyter server at https://the_hostname_fqdn:8000/user/gonluisr/
Info 10:31:45: Creating server with settings : {"baseUrl":"https://the_hostname_fqdn:8000/user/gonluisr/","appUrl":"","wsUrl":"wss://the_hostname_fqdn:8000/user/gonluisr/","token":"token_value","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin","agent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"rejectUnauthorized":false,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"fifo","maxTotalSockets":null,"totalSocketCount":0,"maxCachedSessions":100,"_sessionCache":{"map":{},"list":[]}}}}
Info 10:31:45: Connection complete server
Info 10:31:45: Server started.
Info 10:31:45: Creating server with settings : {"baseUrl":"https://the_hostname_fqdn:8000/user/gonluisr/","appUrl":"","wsUrl":"wss://the_hostname_fqdn:8000/user/gonluisr/","token":"token_value","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin","agent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"rejectUnauthorized":false,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"fifo","maxTotalSockets":null,"totalSocketCount":0,"maxCachedSessions":100,"_sessionCache":{"map":{},"list":[]}}}}
Info 10:31:45: Creating controller for jupyter-notebook with interpreter ~/miniconda3/envs/conda_dev/bin/python
Info 10:31:45: Process Execution: > ~/miniconda3/envs/conda_dev/bin/python -m pip list
> ~/miniconda3/envs/conda_dev/bin/python -m pip list
Info 10:31:46: Registering dummy command feature
Info 10:31:47: Disposing session manager
Info 10:31:47: SessionManager - dispose contents manager
Info 10:31:47: ShutdownSessionAndConnection - dispose session manager
Info 10:31:47: Finished disposing jupyter session manager
Error 10:31:47: Failed to get remote kernel connections [FetchError: request to https://the_hostname_fqdn:8000/user/gonluisr/api/kernels?1646065905683 failed, reason: unable to get local issuer certificate
	at ClientRequest.<anonymous> (/home/gonluisr/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:16:357760)
	at ClientRequest.emit (events.js:327:22)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Info 10:31:47: Creating server with settings : {"baseUrl":"https://the_hostname_fqdn:8000/user/gonluisr/","appUrl":"","wsUrl":"wss://the_hostname_fqdn:8000/user/gonluisr/","token":"token_value","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin","agent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"rejectUnauthorized":false,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"fifo","maxTotalSockets":null,"totalSocketCount":0,"maxCachedSessions":100,"_sessionCache":{"map":{},"list":[]}}}}
Info 10:31:48: Disposing session manager
Info 10:31:48: SessionManager - dispose contents manager
Info 10:31:48: ShutdownSessionAndConnection - dispose session manager
Error 10:31:48: SessionManager cannot enumerate kernelspecs. Returning default {}.
Info 10:31:48: Finished disposing jupyter session manager
Error 10:31:48: Failed to get remote kernel connections [FetchError: request to https://the_hostname_fqdn:8000/user/gonluisr/api/kernels?1646065907516 failed, reason: unable to get local issuer certificate
	at ClientRequest.<anonymous> (/home/gonluisr/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:16:357760)
	at ClientRequest.emit (events.js:327:22)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Info 10:31:48: Creating server with settings : {"baseUrl":"https://the_hostname_fqdn:8000/user/gonluisr/","appUrl":"","wsUrl":"wss://the_hostname_fqdn:8000/user/gonluisr/","token":"token_value","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin","agent":{"_events":{},"_eventsCount":2,"defaultPort":443,"protocol":"https:","options":{"rejectUnauthorized":false,"path":null},"requests":{},"sockets":{},"freeSockets":{},"keepAliveMsecs":1000,"keepAlive":false,"maxSockets":null,"maxFreeSockets":256,"scheduling":"fifo","maxTotalSockets":null,"totalSocketCount":0,"maxCachedSessions":100,"_sessionCache":{"map":{},"list":[]}}}}
Info 10:31:49: Disposing session manager
Info 10:31:49: SessionManager - dispose contents manager
Info 10:31:49: ShutdownSessionAndConnection - dispose session manager
Error 10:31:49: SessionManager cannot enumerate kernelspecs. Returning default {}.
Info 10:31:49: Finished disposing jupyter session manager
Error 10:31:49: findKernel crashed [FetchError: request to https://the_hostname_fqdn:8000/user/gonluisr/api/kernels?1646065908350 failed, reason: unable to get local issuer certificate
	at ClientRequest.<anonymous> (/home/gonluisr/.vscode/extensions/ms-toolsai.jupyter-2022.1.1301854968/out/client/extension.js:16:357760)
	at ClientRequest.emit (events.js:327:22)
	at TLSSocket.socketErrorListener (_http_client.js:469:9)
	at TLSSocket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Error 10:31:49: SessionManager cannot enumerate kernelspecs. Returning default {}.
```

### Coding Language and Runtime Version

Python 3.9.7

### Language Extension Version (if applicable)

v2022.0.1814523869

### Anaconda Version (if applicable)

conda 4.10.3

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment] 2022-02-28 23:06
duplicate of https://github.com/microsoft/vscode-jupyter/issues/7558

**Closed by DonJayamanne** 2022-02-28 23:06 UTC
Labels: bug, needs-triage
