### ISSUE TITLE
Unable to open 'foo.ipynb': Cannot read property 'Bar' of undefined.

### ISSUE THREAD

**Issue by iliailmer** [microsoft/vscode-jupyter#4847] opened 2021-02-16 15:59 UTC
## Environment data

-   VS Code version: Version: 1.54.0-insider
-   Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS and version: macOS Big Sur 11.2.1
-   Python version (& distribution if applicable, e.g. Anaconda): miniconda via miniforge, 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: Jupyter notebook 6.2.0, jupyter core 4.7.1
-   Relevant/affected Python-related VS Code extensions and their versions: Pylance v2021.2.2
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

Open a jupyter notebook file

## Actual behaviour

an error message saying `Unable to open 'foo.ipynb': Cannot read property 'Bar' of undefined.`

## Steps to reproduce:

1. Pick any .ipynb file
2. Click on it to open in VS Code with the correct  python environment active (where jupyter is installed)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel 
</summary>

<p>

```
Error 2021-02-16 10:47:28: Exception while attempting zmq : [Error: No native build was found for platform=darwin arch=arm64 runtime=electron abi=85 uv=1 armv=8 libc=glibc
	at Function.load.path (/.../.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/node-gyp-build/index.js:56:9)
	at load (/.../.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/node-gyp-build/index.js:21:30)
	at Object.<anonymous> (/.../.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/zeromq/lib/native.js:6:43)
	at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:27167)
	at Function.E._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:23919)
	at Function.x._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:4643)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/.../.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/zeromq/lib/index.js:3:16)
	at Module.u._compile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.o._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:27167)
	at Function.E._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:23919)
	at Function.x._load (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:4643)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/.../.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:274679)
	at n (/.../.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:186)
	at /.../.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:803883
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async u.zmqSupportedImpl (/.../.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:803850)]
> ~/miniforge3/envs/symbolic-comp/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/miniforge3/envs/symbolic-comp/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/miniforge3/envs/symbolic-comp/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
```

</p>
</details>

**Comment by rchiodo** [comment] 2021-02-17 18:37
Dupe of #4796

**Closed by rchiodo** 2021-02-17 18:37 UTC
