### ISSUE TITLE
No autocompletions for R packages with IRkernel

### ISSUE THREAD

**Issue by david-cortes** [microsoft/vscode-jupyter#13043] opened 2023-03-09 15:48 UTC
## Environment data

-   VS Code version: 1.76.0
-   Jupyter Extension version (available under the Extensions sidebar): v2023.2.1000592019
-   Python Extension version (available under the Extensions sidebar): v2023.4.0
-   OS (Windows | Mac | Linux distro) and version: Linux and mac
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda for python, native for R
-   Jupyter server running: Local

## Steps to reproduce:

1. Install R.
2. Install the `IRkernel` package: https://github.com/IRkernel/IRkernel
3. Add IRkernel to the user's jupyter config: `Rscript -e "IRkernel::installspec()"`
4. Launch VScode.
5. Open the command palette and trigger a new interactive jupyter session.
6. Set the R kernel that was installed above.
7. Optionally, install some random R package such as `data.table` (command: `install.packages("data.table")` in the interactive command prompt).
8. Try to get autocomplete for an R package, such as `MASS` or `parallel` which both come with R - i.e. write the following and then press Ctrl+Space:
```r
MASS::<focus here>
```

## Expected behaviour

Should show me autocompletions like it does in `jupyter-notebook` (see attached screenshot):
![r_kernel_suggestions](https://user-images.githubusercontent.com/11860098/224076969-f912f0db-1f5f-448f-8e06-04e1e4ab76f9.png)

## Actual behaviour

Doesn't find any suggestions:
![r_kernel_no_suggestions](https://user-images.githubusercontent.com/11860098/224077080-3156100e-5f75-4122-b65f-71f0793ec07c.png)

Note that:
* Suggestions for functions/variables within a package do not work when loading it into the global namespace with `library(MASS)` either.
* Autocompletions work correctly for things that are part of the default global namespace in R before doing anything in an R session:
![r_kernel_base_suggestions](https://user-images.githubusercontent.com/11860098/224077441-0b380d21-4894-4c15-99f4-04f18a967495.png)

**Comment by DonJayamanne** [comment] 2023-12-08 03:09
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/14672

**Closed by DonJayamanne** 2023-12-08 03:09 UTC
Labels: bug, language-any
