### ISSUE TITLE
Can't show the picture in markdown cell 

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode-jupyter#7510] opened 2021-09-14 12:22 UTC
![image](https://user-images.githubusercontent.com/82581024/133256434-063295c4-57b1-4ef8-92a2-74c2339e9624.png)

![image](https://user-images.githubusercontent.com/82581024/133256518-e8ce0fa0-c3f2-49df-9edb-1d9464b7a840.png)

The picture is in the same directory.

**Comment by IanMatthewHuff** [comment] 2021-09-14 20:41
@Vincent0706 what is the "attachment:" syntax that you are using there? I tried this out with a local file myself and the local image was working fine with the usual ![](path/to/file) syntax.

**Comment by rhythmthief** [comment] 2021-09-15 02:22
@IanMatthewHuff this syntax is actually a result of drag & dropping an image from a file explorer into a Markdown cell in edit mode. It appears to embed the image directly into the notebook.

**Comment by Vincent0706** [comment] 2021-09-15 14:19
> @Vincent0706 what is the "attachment:" syntax that you are using there? I tried this out with a local file myself and the local image was working fine with the usual ![](path/to/file) syntax.

I don't know. That is from my teacher's jupyter notebook. 
There is my teacher's file:
[2.Python程序结构.zip](https://github.com/microsoft/vscode-jupyter/files/7170816/2.Python.zip)

**Comment by DonJayamanne** [comment] 2021-09-15 16:54
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5774

**Closed by DonJayamanne** 2021-09-15 16:54 UTC
Labels: bug, info-needed, needs-triage
