### ISSUE TITLE
Enhancement to run selected text in interactive window

### ISSUE THREAD

**Issue by abielr** [microsoft/vscode-jupyter#4879] opened 2021-02-19 13:13 UTC
If using Jupyter Lab in a web browser a user can go to Run > Run Selected Text or Current Line in Console. This creates a new console linked to the same kernel as the notebook and runs the selected line(s). I would like to request a similar feature when editing notebooks inside VSCode where the line could be sent to the Interactive Window. It would also be important to be able to link a keyboard shortcut to this.

**Comment by claudiaregio** [comment] 2021-02-19 16:04
Thanks @abielr for the suggestion, will discuss at our triage

**Comment by greazer** [comment] 2021-02-25 21:09
Dupe of #4543

**Closed by greazer** 2021-02-25 21:09 UTC
