### ISSUE TITLE
Reappeared: IPyWidgets do not renderer due to a 401 error in webview

### ISSUE THREAD

**Issue by chawson** [microsoft/vscode-jupyter#16015] opened 2024-09-08 08:52 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Similar to this issue https://github.com/microsoft/vscode-jupyter/issues/12843
When `%matplotlib widget` exists in the code and it is run, you will see in vscode devtools that the status code of the request `jupyter/nbextensions/jupyter-matplotlib/index.js` is 401.
After the jupyter version is rolled back to v2024.7.0, the interactive webview can be rendered normally.
The output of executing `jupyter --version` is as follows:
```sh
IPython          : 8.26.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.5
jupyter_client   : 8.6.2
jupyter_core     : 5.7.2
jupyter_server   : 2.14.2
jupyterlab       : 4.2.5
nbclient         : 0.10.0
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.14.3
```
The python3 code is as follows:
```py
%matplotlib widget
from matplotlib import pyplot
from pandas import Series, date_range, DataFrame
from numpy import random

pyplot.close('all')
random.seed(123456)

ts = Series(random.randn(1000), index = date_range("1/1/2000", periods=1000))
ts = ts.cumsum()

df = DataFrame(data = random.randn(1000, 4), index = ts.index, columns=list('ABCD'))
df = df.cumsum()
df.plot()
pyplot.show()
```

### VS Code Version

1.93.0

### Jupyter Extension Version

v2024.8.0

### Jupyter logs

```shell
Widget load failure {} {
  className: 'ToolbarModel',
  moduleName: 'jupyter-matplotlib',
  moduleVersion: '^0.11',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: '{}'
}
```

### Coding Language and Runtime Version

Python 3.12.3

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2024-09-09 02:37
Sorry you are running into this issue.
This has been fixed in the latest pre-release version of the extension.
duplicate of https://github.com/microsoft/vscode-jupyter/issues/16007

Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`  

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

**Closed by DonJayamanne** 2024-09-09 02:37 UTC
Labels: bug
