### ISSUE TITLE
cannot scroll down when cursor put on cell output

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode-jupyter#12868] opened 2023-02-18 14:56 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. create some arbitrary outputs, e.g.
```python
for i in range(25):
    print((str(i+11)+ ",") * 40)
```
2. put the above cell with output in the middle of a notebook, so that scrolling up/down can be observed for sure
3. put cursor on the **printed output**
4. try to scroll down, and then try to scroll up: down fails (looks "fixed"), up succeeds.

since the issue looks static (try to scroll down but not moving at all), gif is skipped.

ref: another scrolling down issue - #12777 

### VS Code Version

1.75.1

### Jupyter Extension Version

2023.1.2010391206

### Jupyter logs

```shell
(nothing there)
```

### Running Jupyter locally or remotely?

Local

**Comment by yuuuxt** [comment] 2023-02-20 01:52
It's interesting that this issue appears on 2 windows devices (both latest vscode and extension), but doesn't appear on another windows machine (using the same synced configuration).

**Comment by danilo-alm** [comment] 2023-02-21 13:12
I'm having the same problem on my machine. Arch Linux, latest VSCode version

**Comment by amunger** [comment] 2023-02-21 21:48
To clarify, this does not work for you? Are you using the mouse wheel to scroll?
![scrolling](https://user-images.githubusercontent.com/2019016/220466327-1a69d4a8-65cb-45f4-8a6d-8e6916532777.gif)

**Comment by yuuuxt** [comment] 2023-02-21 23:54
> To clarify, this does not work for you? Are you using the mouse wheel to scroll?

That doesn't work, using mouse wheel.

**Comment by amunger** [comment] 2023-02-21 23:58
duplicate of https://github.com/microsoft/vscode/issues/174375. We haven't been able to repro on our end, but there have been a handful of these reports.

**Closed by amunger** 2023-02-21 23:58 UTC
Labels: bug, info-needed, notebook-output
