### ISSUE TITLE
kernel died with exit code 1. What does this mean?????????????????

### ISSUE THREAD

**Issue by Fryguy7991** [microsoft/vscode-jupyter#7522] opened 2021-09-14 21:39 UTC
Everytime I try to run a line of code in visual studio I get this: 

Kernel died with exit code 1. Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ryweb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\ryweb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\ryweb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\ipykernel\connect.py", line 12, in <module>
    import jupyter_client
  File "C:\Users\ryweb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\__init__.py", line 6, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\Users\ryweb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\Users\ryweb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\Users\ryweb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\jupyter_client\channels.py", line 4, in <module>
    import asyncio
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\__init__.py", line 8, in <module>
    from .base_events import *
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 18, in <module>
    import concurrent.futures
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 7, in <module>
    import logging
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 28, in <module>
    from string import Template
ImportError: cannot import name 'Template' from 'string' (c:\Users\ryweb\.vscode\string.py)

I'm new to python so I don't know what this means can someone help me please???????????

**Comment by joyceerhl** [comment] 2021-09-15 00:58
@Fryguy7991 From the last line in your logs, it looks like you have named a file `string.py`. This gets loaded instead of the built-in `string` module that Jupyter tries to import, which is why the kernel fails to start. If you rename this file `c:\Users\ryweb.vscode\string.py` to something else like `c:\Users\ryweb.vscode\my_string.py`, does that resolve the problem?

**Comment by greazer** [comment] 2021-09-22 07:24
Looks like a dupe of #7444

**Comment by DonJayamanne** [comment] 2021-09-23 22:34
Dup of https://github.com/microsoft/vscode-jupyter/issues/7444

**Closed by DonJayamanne** 2021-09-23 22:34 UTC
Labels: bug, info-needed, kernel-crash, iteration-candidate
