### ISSUE TITLE
Reduce margins within each cell and spaces between cells in Jupyter in VSCode

### ISSUE THREAD

**Issue by xwshen51** [microsoft/vscode-jupyter#12997] opened 2023-03-05 17:47 UTC
Is there a way to reduce the margin within each cell and the space between cells in Jupyter in VSCode?

**Comment by rebornix** [comment] 2023-03-06 20:07
/duplicate of https://github.com/microsoft/vscode/issues/175295

**Closed by rebornix** 2023-03-06 20:07 UTC
Labels: feature-request
