### ISSUE TITLE
New env doesn't show up in the kernel list until a VS Code reload

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#7626] opened 2021-09-22 22:58 UTC
VS Code 1.61.0-insider + Jupyter extension v2021.9.1001261101

1. Create a new Conda env from the Python terminal
2. open an ipynb file. 
3. click on the "Select kernel" button in the top right corner of the notebook

expected: new environment shows up in the list
actual: new environment is not in the kernel list until a VS Code reload

**Comment by rchiodo** [comment] 2021-09-22 23:02
Dupe of #https://github.com/microsoft/vscode-python/issues/17492

**Comment by rchiodo** [comment] 2021-09-23 15:59
Should be fixed now with the latest python insiders extension

**Comment by ronglums** [comment] 2021-10-19 18:49
Still seeing this issue in the latest python insiders version.

**Closed** 2021-10-19 19:19 UTC
Labels: bug, papercut :drop_of_blood:, needs-triage, nb-golden
