### ISSUE TITLE
Text inside angle brackets does not get printed

### ISSUE THREAD

**Issue by tillfalko** [microsoft/vscode-jupyter#12476] opened 2023-01-02 23:57 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In Notebooks and Interactive Windows, text between "<" and ">" does not show up in outputs.
Notebook:
![image](https://user-images.githubusercontent.com/62334868/210285192-c37df13c-f35c-480c-9207-11554172615a.png)
![image](https://user-images.githubusercontent.com/62334868/210285642-98361e7e-7978-4116-a292-07101cfc2f78.png)

Interactive Window:
![image](https://user-images.githubusercontent.com/62334868/210284971-d12e85fd-263f-40e9-aad0-8ca758a16f13.png)

I have not found a workaround to this problem. Escaping the angle brackets does not work.
![image](https://user-images.githubusercontent.com/62334868/210285300-12890a5e-037c-4b13-bb23-b7018d173d69.png)

This does not happen with jupyterlabs, or when running the notebook with jupyter-notebook.

Possibly related to https://github.com/microsoft/vscode-jupyter/issues/3149 where the same thing happened in Exception texts. Now exceptions seem to be the only place where it does not occur.
![image](https://user-images.githubusercontent.com/62334868/210285556-26038bde-4a1d-49dc-84f3-da6e3e17d466.png)

### VS Code Version

1.75.0-insider

### Jupyter Extension Version

v2023.1.1003661022

### Coding Language and Runtime Version

Python v3.10.6

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment] 2023-01-03 00:00
Duplicate of https://github.com/microsoft/vscode/issues/170263

**Closed by DonJayamanne** 2023-01-03 00:00 UTC
Labels: bug
