### ISSUE TITLE
Enable Jupyter autoreload extension by default

### ISSUE THREAD

**Issue by nfx** [microsoft/vscode-jupyter#4816] opened 2021-02-14 15:21 UTC
Issue Type: <b>Feature Request</b>

Working with `%autoreload 2` jupyter extension is an extreme productivity booster. If would be good great if it's turned on by default and a button is added, telling it's enabled (optionally allowing to change autoreload mode).

```jupyter
%load_ext autoreload
%autoreload 2
```

More info on the feature can be found here https://ipython.org/ipython-doc/3/config/extensions/autoreload.html

Extension version: 2021.1.502429796
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T16:01:04.046Z)
OS version: Darwin x64 19.6.0

**Comment by joyceerhl** [comment] 2021-02-14 20:39
Thanks for the suggestion @nfx! This would be a behavior change for customers, so it would help to have broad feedback from customers about whether this is expected or desirable.

**Comment by axsk** [comment] 2021-02-16 19:20
I use it all the time and had to configure it for automatic loading in some jupyter config files, but always forget where and how. Having this integrated in the native notebooks would be awesome.

**Comment by rchiodo** [comment] 2021-02-16 21:37
This could be considered a dupe of #4555 (which doesn't necessarily prescribe using autoreload)

**Comment by greazer** [comment] 2021-02-16 22:49
Being tracked with #4555.

**Closed by greazer** 2021-02-16 22:49 UTC
Labels: enhancement
