### ISSUE TITLE
Scrub output of a notebook on save

### ISSUE THREAD

**Issue by ottogin** [microsoft/vscode-jupyter#12623] opened 2023-01-24 01:01 UTC
It would be nice to control if the cells' outputs are saved on disk. As discussed in multiple threads across the internet, there might be multiple reasons to not save the outputs: 
1. Version Control
2. Sensitive information
3. Outputs are too heavy (in my case 3D visualizations in plotly make the notebook freeze on save/ cell run because of the I/O over ssh)

Essentially the request is similar to [the same feature request for VS code core](https://github.com/microsoft/vscode/issues/124551). Would not it be better to implement it in the serializer within the extension?

**Comment by DonJayamanne** [comment] 2023-01-24 01:22
Closing as a duplicate of https://github.com/microsoft/vscode/issues/124551

**Closed by DonJayamanne** 2023-01-24 01:22 UTC
Labels: feature-request
