### ISSUE TITLE
code hints insert already typed code

### ISSUE THREAD

**Issue by bellerofonte** [microsoft/vscode-jupyter#6324] opened 2021-06-18 06:00 UTC
Issue Type: <b>Bug</b>

1) type "sklearn."
2) hint gets shown
3) select option f.e. "model_selection"
4) now you have "sklearn.sklearn.model_selection" instead of "sklearn.model_selection"

this issue affects any kind of class or namespace. very annoing.

Extension version: 2021.6.999406279
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:22:31.215Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|--crash-reporter-id 2ee0aabb-d8f4-4869-8858-84e8c6becb99|
|Screen Reader|no|
|VM|33%|
</details>

**Comment by claudiaregio** [comment] 2021-06-18 16:57
Hi @bellerofonte, what language server are you using? 
Could be dupe of https://github.com/microsoft/vscode-jupyter/issues/5956

**Comment by bellerofonte** [comment] 2021-06-18 18:12
Hi @claudiaregio! 

> Could be dupe of #5956

It is definitely a dup. 
My Jup Server is local, Py interpreter is conda

**Comment by claudiaregio** [comment] 2021-06-18 19:39
Going to go ahead and close as dupe, updating to a language server should get you a more immediate fix

**Closed by claudiaregio** 2021-06-18 19:39 UTC
Labels: info-needed
