### ISSUE TITLE
Variable viewer contribution does not distinguish fully qualified class names

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode-jupyter#15568] opened 2024-04-18 22:49 UTC
## Environment data

-   VS Code version: 1.89.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2024.4.2024041702
-   Python Extension version (available under the Extensions sidebar): v2024.5.11091012
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.11.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Should be able to distinguish different objects of class `DataFrame`, e.g. pandas vs. PySpark vs. polars.

## Actual behaviour

The following code shows a launch button:
<img width="522" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8560030/92fb52c7-366f-4ec0-968a-4eeafbf95c08">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Run the following code and open the variables panel:

```python
import polars as pl
from datetime import datetime

df = pl.DataFrame(
    {
        "integer": [1, 2, 3],
        "date": [
            datetime(2025, 1, 1),
            datetime(2025, 1, 2),
            datetime(2025, 1, 3),
        ],
        "float": [4.0, 5.0, 6.0],
        "string": ["a", "b", "c"],
    }
)

print(df)
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

CC @rebornix

**Comment by DonJayamanne** [comment] 2024-04-18 23:03
I'm not really sure this is a bug, as a user i wouldn't care much as I know whether I'm using Poloars or Df or other.
All i care about is the fact that this is a data frame.

@pwang347 is the issue primarily with just the display?

**Comment by pwang347** [comment] 2024-04-18 23:22
@DonJayamanne This issue is more about the contribution API spec, as far as I know there is no way to specify that only a subset of `DataFrame` classes are supported. Might get a bit tricky if it needs to be fully-qualified, but wonder if it means some sort of regexp should be allowed here to validate.

In general this could also be problematic if there are user-defined classes as well that seem like they support a Data Viewer when they don't.

For example, using the built-in variable viewer for Jupyter we can get this error (for a user-defined `DataFrame` class):
<img width="549" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/8560030/dc9b038f-3324-4aeb-8a9c-860e6c44e6e5">

**Comment by DonJayamanne** [comment] 2024-04-19 00:19
> This issue is more about the contribution API spec, as far as I know there is no way to specify that only a

I think the issue title and screenshots should be updated to make it clear that the problem is with the API and not the UI.
I believe we have addressed this issue.
Seems like a duplicate of https://github.com/microsoft/vscode-jupyter/issues/15345
However I'll wait for @amunger  to reply.

**Comment by DonJayamanne** [comment] 2024-04-19 00:33
aah, got it, thanks for clarification, I misunderstood the issue.

**Comment by pwang347** [comment] 2024-04-19 17:54
No worries at all! Thank you for sharing the issue, it does seem very much related. I tried adding `pandas.core.frame.DataFrame` to the contribution list [here](https://github.com/microsoft/vscode-jupyter/blob/main/package.json#L2054-L2063) but it doesn't seem to resolve properly, so not sure if there's something I'm doing wrong here.

**Comment by amunger** [comment] 2024-04-19 17:59
the fully qualified variable name is in the context for the new builtin variable view, which has a different contribution point directly in core. The existing jupyter view was not updated, and that view should eventually go away, but we could still make the same fix there if necessary

**Comment by pwang347** [comment] 2024-04-19 18:31
@amunger I see. Does this mean that the contribution `jupyterVariableViewers` will be deprecated along with the old variable viewer? I was under the impression that this contribution would still be used later down the line

**Closed** 2024-05-03 15:23 UTC
Labels: bug, data-viewer

**Comment by eleanorjboyd** [comment] 2024-05-29 15:41
Hi @pwang347! Are you able to verify this fix is resolved? You can do so by using vscode insiders and making sure you are on the newest version of insiders and the jupyter extension. Please let me know if you are able to see that the bug is resolved. Thank you!

**Comment by pwang347** [comment] 2024-05-29 16:43
Hi @eleanorjboyd, I can confirm that this issue is resolved as we are getting passed the fully qualified names now. Thank you!
