### ISSUE TITLE
Unable to find widget 'jupyter-matplotlib' version '^0.11' from configured widget

### ISSUE THREAD

**Issue by quentinpossamai** [microsoft/vscode-jupyter#12371] opened 2022-12-09 12:58 UTC
## Environment data

-   VS Code version: 1.74.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.11.1003412109
-   Python Extension version (available under the Extensions sidebar): v2022.20.0
-   OS (Windows | Mac | Linux distro) and version: Windows 10 21H2 on WSL2
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

In a jupyter notebook, plotting with matplotlib should not raise a vscode issue.

## Actual behaviour

Raises the following vscode notification:
```
Unable to find widget 'jupyter-matplotlib' version '^0.11' from configured widget 
sources ["jsdelivr.com","unpkg.com"]. Expected behavior may be affected. 
Click [here](https://aka.ms/PVSCIPyWidgets) for more information.
```
## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

```
%matplotlib widget
import matplotlib.pyplot as plt
plt.plot([1, 2, 3])
```

## Pip list
```
Package                  Version
------------------------ -----------
anyio                    3.6.2
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    22.1.0
backcall                 0.2.0
beautifulsoup4           4.11.1
bleach                   5.0.1
cffi                     1.15.1
comm                     0.1.2
contourpy                1.0.6
cycler                   0.11.0
debugpy                  1.6.4
decorator                5.1.1
defusedxml               0.7.1
entrypoints              0.4
executing                1.2.0
fastjsonschema           2.16.2
flake8                   6.0.0
fonttools                4.38.0
fqdn                     1.5.1
idna                     3.4
importlib-metadata       5.1.0
importlib-resources      5.10.1
ipykernel                6.19.2
ipympl                   0.9.1
ipython                  8.7.0
ipython-genutils         0.2.0
ipywidgets               7.7.2
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
joblib                   1.2.0
jsonpointer              2.3
jsonschema               4.17.3
jupyter_client           7.4.8
jupyter_core             5.1.0
jupyter-events           0.5.0
jupyter_server           2.0.1
jupyter_server_terminals 0.4.2
jupyterlab-pygments      0.2.2
jupyterlab-widgets       1.1.1
kiwisolver               1.4.4
MarkupSafe               2.1.1
matplotlib               3.6.2
matplotlib-inline        0.1.6
mccabe                   0.7.0
mistune                  2.0.4
nbclassic                0.4.8
nbclient                 0.7.2
nbconvert                7.2.6
nbformat                 5.7.0
nest-asyncio             1.5.6
notebook                 6.5.2
notebook_shim            0.2.2
numpy                    1.23.5
packaging                22.0
pandocfilters            1.5.0
parso                    0.8.3
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.3.0
pip                      22.3.1
pkg_resources            0.0.0
pkgutil_resolve_name     1.3.10
platformdirs             2.6.0
prometheus-client        0.15.0
prompt-toolkit           3.0.36
psutil                   5.9.4
ptyprocess               0.7.0
pure-eval                0.2.2
pycodestyle              2.10.0
pycparser                2.21
pyflakes                 3.0.1
Pygments                 2.13.0
pyparsing                3.0.9
pyrsistent               0.19.2
python-dateutil          2.8.2
python-json-logger       2.0.4
PyYAML                   6.0
pyzmq                    24.0.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
scikit-learn             1.2.0
scipy                    1.9.3
Send2Trash               1.8.0
setuptools               44.0.0
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.3.2.post1
stack-data               0.6.2
terminado                0.17.1
threadpoolctl            3.1.0
tinycss2                 1.2.1
tornado                  6.2
tqdm                     4.64.1
traitlets                5.7.0
uri-template             1.2.0
wcwidth                  0.2.5
webcolors                1.12
webencodings             0.5.1
websocket-client         1.4.2
widgetsnbextension       3.6.1
zipp                     3.11.0

```

**Comment by DonJayamanne** [comment] 2022-12-20 21:47
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12401

**Closed by DonJayamanne** 2022-12-20 21:47 UTC
Labels: bug, ipywidgets
