### ISSUE TITLE
Allowing moving Python REPL to bottom panel

### ISSUE THREAD

**Issue by ggydush** [microsoft/vscode-jupyter#15925] opened 2024-08-05 22:36 UTC
Type: <b>Feature Request</b>

# Behaviour

New Python REPL always opens as a separate window, but it would be nice if it was possible to move this window to the terminal panel at the bottom.

## Steps to reproduce:

Start new Python REPL, try to move window to bottom panel.

# Diagnostic data

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

Extension version: 2024.13.2024080501
VS Code version: Code 1.92.0 (Universal) (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Darwin x64 23.3.0
Modes:

**Comment by amunger** [comment] 2024-08-12 16:38
duplicate of https://github.com/microsoft/vscode/issues/127998

**Closed by amunger** 2024-08-12 16:38 UTC
