### ISSUE TITLE
interactive window focus on output window upon executing a cell

### ISSUE THREAD

**Issue by maximilianmordig** [microsoft/vscode-jupyter#15793] opened 2024-06-24 12:11 UTC
Executing a cell in an existing interactive python (.py file with `#%%` markers) does not focus on the corresponding output window in the second editor group, so one has to search for it among the open tabs. 
This is quite distractive when working with it.

**Comment by amunger** [comment] 2024-11-22 23:52
duplicate of https://github.com/microsoft/vscode-jupyter/issues/11138

**Closed by amunger** 2024-11-22 23:52 UTC
Labels: interactive-window
