### ISSUE TITLE
After update today, i cannot use jupyter in wsl2 - Jupyter server crashed. Unable to connect.

### ISSUE THREAD

**Issue by patchie** [microsoft/vscode-jupyter#13623] opened 2023-06-01 12:44 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

![image](https://github.com/microsoft/vscode-jupyter/assets/1792727/d59f3087-16c0-403a-9be2-682e3da770bb)

Just trying to run print("hello world") in a cell for example, and get the error message below the cell:

> Failed to start the Kernel. 
> Jupyter server crashed. Unable to connect. 
> Error code from Jupyter: 1
> /root/.local/lib/python3.11/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/home/xxxx' instead of '"/home/xxxx"' if you require traitlets >=5.
>   warn(
> 
>   _   _          _      _
>  | | | |_ __  __| |__ _| |_ ___
>  | |_| | '_ \/ _` / _` |  _/ -_)
>   \___/| .__/\__,_\__,_|\__\___|
>        |_|
>                        
> Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
> 
> https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
> 
> Please note that updating to Notebook 7 might break some of your extensions.
> 
> [W 12:31:38.249 NotebookApp] Error loading server extension jupyter_lsp
>     Traceback (most recent call last):
>       File "/root/.local/lib/python3.11/site-packages/notebook/notebookapp.py", line 2050, in init_server_extensions
>         func(self)
>       File "/usr/local/lib/python3.11/dist-packages/jupyter_lsp/serverextension.py", line 76, in load_jupyter_server_extension
>         nbapp.io_loop.call_later(0, initialize, nbapp, virtual_documents_uri)
>         ^^^^^^^^^^^^^
>     AttributeError: 'NotebookApp' object has no attribute 'io_loop'
> [W 2023-06-01 12:31:38.540 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 12:31:38.540 LabApp] 'config_file' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
> [W 2023-06-01 12:31:38.540 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 12:31:38.540 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 12:31:38.540 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [I 2023-06-01 12:31:38.542 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.11/dist-packages/jupyterlab
> [I 2023-06-01 12:31:38.542 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab

System info:
Win10
WSL2: Ubuntu (Linux x64 5.15.90.1-microsoft-standard-WSL2)

VScode: 
- Version: 1.79.0-insider (user setup)
- Commit: c3867859cf3e1a73f3ddce5ad36b3791b7883d88
- Date: 2023-06-01T05:24:05.541Z
- Electron: 22.5.4
- Chromium: 108.0.5359.215
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.19044

### VS Code Version

1.79.0-insider

### Jupyter Extension Version

v2023.5.1001541100

### Jupyter logs
> 
> ```shell
> Visual Studio Code - Insiders (1.79.0-insider, wsl, desktop)
> Jupyter Extension Version: 2023.5.1001541100.
> Python Extension Version: 2023.9.11521013.
> Platform: linux (x64).
> No workspace folder opened.
> 14:35:57.357 [warn] Exception while attempting zmq : No native build was found for platform=linux arch=x64 runtime=electron abi=93 uv=1 libc=glibc node=16.17.1
>     loaded from: ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/node_modules/zeromq
> 
> 14:35:57.357 [warn] Exception while attempting zmq (fallback) : No native build was found for platform=linux arch=x64 runtime=electron abi=93 uv=1 libc=glibc node=16.17.1
>     loaded from: ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/node_modules/zeromqold
> 
> 14:35:57.489 [info] Start refreshing Interpreter Kernel Picker (1685622957489)
> 14:35:57.504 [info] Using Pylance
> 14:35:58.260 [warn] No interpreter with path /bin/python3.11 found in Python API, will convert Uri path to string as Id /bin/python3.11
> 14:35:59.033 [warn] Failed to get activated env vars for /bin/python3.11 in 169ms
> 14:35:59.049 [info] Process Execution: /bin/python3.11 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
> 14:35:59.078 [info] Process Execution: /bin/python3.11 -m pip list
> 14:35:59.096 [info] Process Execution: /bin/python3.11 -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> 14:35:59.114 [info] Process Execution: /bin/python3.11 -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> 14:35:59.290 [warn] No interpreter for Pylance for Notebook URI "Untitled-1.ipynb"
> 14:35:59.318 [info] Process Execution: /bin/python3.11 -m jupyter kernelspec --version
> 14:36:00.976 [info] End refreshing Interpreter Kernel Picker (1685622957489)
> 14:36:09.315 [info] Handle Execution of Cells 0 for Untitled-1.ipynb
> 14:36:09.319 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0ead1b95f633dc9c51826328e1846203f51a198c6fb5f2884a80417ba131d4e82./bin/python3.11./bin/python3.11.-m#ipykernel_launcher  (Python Path: /bin/python3.11, Unknown, 3.11.3) for 'Untitled-1.ipynb' (disableUI=false)
> 14:36:09.320 [info] Launching server
> 14:36:09.320 [info] Starting Notebook
> 14:36:09.323 [info] Generating custom default config at /tmp/8af7c5fe-38ed-4632-9999-ad40b7f4e4f8/jupyter_notebook_config.py
> 14:36:09.336 [info] Process Execution: /bin/python3.11 -m jupyter notebook --no-browser --notebook-dir="/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders" --config=/tmp/8af7c5fe-38ed-4632-9999-ad40b7f4e4f8/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0
> 14:36:09.991 [info] Process Execution: /bin/python3.11 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> 14:36:10.013 [info] Process Execution: /bin/python3.11 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> 14:36:10.315 [info] Process Execution: /bin/python3.11 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> 14:36:10.330 [info] Process Execution: /bin/python3.11 ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/pythonFiles/vscode_datascience_helpers/getServerInfo.py
> 14:36:10.429 [error] Failed to start the Jupyter Server Error: Jupyter server crashed. Unable to connect. 
> Error code from Jupyter: 1
> ~/.local/lib/python3.11/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders' instead of '"/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders"' if you require traitlets >=5.
>   warn(
> 
>   _   _          _      _
>  | | | |_ __  __| |__ _| |_ ___
>  | |_| | '_ \/ _` / _` |  _/ -_)
>   \___/| .__/\__,_\__,_|\__\___|
>        |_|
>                        
> Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
> 
> https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
> 
> Please note that updating to Notebook 7 might break some of your extensions.
> 
> [W 14:36:09.999 NotebookApp] Error loading server extension jupyter_lsp
>     Traceback (most recent call last):
>       File "~/.local/lib/python3.11/site-packages/notebook/notebookapp.py", line 2050, in init_server_extensions
>         func(self)
>       File "/usr/local/lib/python3.11/dist-packages/jupyter_lsp/serverextension.py", line 76, in load_jupyter_server_extension
>         nbapp.io_loop.call_later(0, initialize, nbapp, virtual_documents_uri)
>         ^^^^^^^^^^^^^
>     AttributeError: 'NotebookApp' object has no attribute 'io_loop'
> [W 2023-06-01 14:36:10.300 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'config_file' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.11/dist-packages/jupyterlab
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
> [I 2023-06-01 14:36:10.302 LabApp] Extension Manager is 'pypi'.
> [C 14:36:10.304 NotebookApp] Running as <username> is not recommended. Use --allow-<username> to bypass.
>     > at lf.rejectStartPromise (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/extension.node.js:17:120442)
>     > interpreter = [object Object]
> 14:36:10.431 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Jupyter server crashed. Unable to connect. 
> Error code from Jupyter: 1
> ~/.local/lib/python3.11/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders' instead of '"/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders"' if you require traitlets >=5.
>   warn(
> 
>   _   _          _      _
>  | | | |_ __  __| |__ _| |_ ___
>  | |_| | '_ \/ _` / _` |  _/ -_)
>   \___/| .__/\__,_\__,_|\__\___|
>        |_|
>                        
> Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
> 
> https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
> 
> Please note that updating to Notebook 7 might break some of your extensions.
> 
> [W 14:36:09.999 NotebookApp] Error loading server extension jupyter_lsp
>     Traceback (most recent call last):
>       File "~/.local/lib/python3.11/site-packages/notebook/notebookapp.py", line 2050, in init_server_extensions
>         func(self)
>       File "/usr/local/lib/python3.11/dist-packages/jupyter_lsp/serverextension.py", line 76, in load_jupyter_server_extension
>         nbapp.io_loop.call_later(0, initialize, nbapp, virtual_documents_uri)
>         ^^^^^^^^^^^^^
>     AttributeError: 'NotebookApp' object has no attribute 'io_loop'
> [W 2023-06-01 14:36:10.300 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'config_file' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.11/dist-packages/jupyterlab
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
> [I 2023-06-01 14:36:10.302 LabApp] Extension Manager is 'pypi'.
> [C 14:36:10.304 NotebookApp] Running as <username> is not recommended. Use --allow-<username> to bypass.
>     > at lf.rejectStartPromise (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/extension.node.js:17:120442)
>     > interpreter = [object Object]
> 14:36:10.431 [warn] Kernel Error, context = start Error: Jupyter server crashed. Unable to connect. 
> Error code from Jupyter: 1
> ~/.local/lib/python3.11/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders' instead of '"/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders"' if you require traitlets >=5.
>   warn(
> 
>   _   _          _      _
>  | | | |_ __  __| |__ _| |_ ___
>  | |_| | '_ \/ _` / _` |  _/ -_)
>   \___/| .__/\__,_\__,_|\__\___|
>        |_|
>                        
> Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
> 
> https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
> 
> Please note that updating to Notebook 7 might break some of your extensions.
> 
> [W 14:36:09.999 NotebookApp] Error loading server extension jupyter_lsp
>     Traceback (most recent call last):
>       File "~/.local/lib/python3.11/site-packages/notebook/notebookapp.py", line 2050, in init_server_extensions
>         func(self)
>       File "/usr/local/lib/python3.11/dist-packages/jupyter_lsp/serverextension.py", line 76, in load_jupyter_server_extension
>         nbapp.io_loop.call_later(0, initialize, nbapp, virtual_documents_uri)
>         ^^^^^^^^^^^^^
>     AttributeError: 'NotebookApp' object has no attribute 'io_loop'
> [W 2023-06-01 14:36:10.300 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'config_file' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.11/dist-packages/jupyterlab
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
> [I 2023-06-01 14:36:10.302 LabApp] Extension Manager is 'pypi'.
> [C 14:36:10.304 NotebookApp] Running as <username> is not recommended. Use --allow-<username> to bypass.
>     > at lf.rejectStartPromise (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/extension.node.js:17:120442)
>     > interpreter = [object Object]
> 14:36:10.444 [info] Process Execution: /bin/python3.11 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> 14:36:10.445 [warn] Failed to parse JSON when getting server info out from getServerInfo.py SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at vh.getRunningJupyterServers (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/extension.node.js:17:84829)
> 14:36:10.445 [warn] Failed to parse JSON when getting server info out from getServerInfo.py SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at vh.getRunningJupyterServers (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/extension.node.js:17:84829)
> 14:36:10.582 [info] Dispose Kernel 'Untitled-1.ipynb' associated with 'Untitled-1.ipynb'
> 14:36:10.583 [error] Error in execution Error: Jupyter server crashed. Unable to connect. 
> Error code from Jupyter: 1
> ~/.local/lib/python3.11/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders' instead of '"/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders"' if you require traitlets >=5.
>   warn(
> 
>   _   _          _      _
>  | | | |_ __  __| |__ _| |_ ___
>  | |_| | '_ \/ _` / _` |  _/ -_)
>   \___/| .__/\__,_\__,_|\__\___|
>        |_|
>                        
> Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
> 
> https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
> 
> Please note that updating to Notebook 7 might break some of your extensions.
> 
> [W 14:36:09.999 NotebookApp] Error loading server extension jupyter_lsp
>     Traceback (most recent call last):
>       File "~/.local/lib/python3.11/site-packages/notebook/notebookapp.py", line 2050, in init_server_extensions
>         func(self)
>       File "/usr/local/lib/python3.11/dist-packages/jupyter_lsp/serverextension.py", line 76, in load_jupyter_server_extension
>         nbapp.io_loop.call_later(0, initialize, nbapp, virtual_documents_uri)
>         ^^^^^^^^^^^^^
>     AttributeError: 'NotebookApp' object has no attribute 'io_loop'
> [W 2023-06-01 14:36:10.300 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'config_file' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.11/dist-packages/jupyterlab
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
> [I 2023-06-01 14:36:10.302 LabApp] Extension Manager is 'pypi'.
> [C 14:36:10.304 NotebookApp] Running as <username> is not recommended. Use --allow-<username> to bypass.
>     > at lf.rejectStartPromise (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/extension.node.js:17:120442)
>     > interpreter = [object Object]
> 14:36:10.584 [error] Error in execution (get message for cell) Error: Jupyter server crashed. Unable to connect. 
> Error code from Jupyter: 1
> ~/.local/lib/python3.11/site-packages/traitlets/traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use '/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders' instead of '"/mnt/c/Users/xxxxx/AppData/Local/Programs/Microsoft VS Code Insiders"' if you require traitlets >=5.
>   warn(
> 
>   _   _          _      _
>  | | | |_ __  __| |__ _| |_ ___
>  | |_| | '_ \/ _` / _` |  _/ -_)
>   \___/| .__/\__,_\__,_|\__\___|
>        |_|
>                        
> Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.
> 
> https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html
> 
> Please note that updating to Notebook 7 might break some of your extensions.
> 
> [W 14:36:09.999 NotebookApp] Error loading server extension jupyter_lsp
>     Traceback (most recent call last):
>       File "~/.local/lib/python3.11/site-packages/notebook/notebookapp.py", line 2050, in init_server_extensions
>         func(self)
>       File "/usr/local/lib/python3.11/dist-packages/jupyter_lsp/serverextension.py", line 76, in load_jupyter_server_extension
>         nbapp.io_loop.call_later(0, initialize, nbapp, virtual_documents_uri)
>         ^^^^^^^^^^^^^
>     AttributeError: 'NotebookApp' object has no attribute 'io_loop'
> [W 2023-06-01 14:36:10.300 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'config_file' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [W 2023-06-01 14:36:10.300 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.11/dist-packages/jupyterlab
> [I 2023-06-01 14:36:10.302 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
> [I 2023-06-01 14:36:10.302 LabApp] Extension Manager is 'pypi'.
> [C 14:36:10.304 NotebookApp] Running as <username> is not recommended. Use --allow-<username> to bypass.
>     > at lf.rejectStartPromise (~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/extension.node.js:17:120442)
>     > interpreter = [object Object]
> 14:36:10.601 [info] End cell 0 execution @ undefined, started @ undefined, elapsed time = 0s
> ```

### Coding Language and Runtime Version

python 3.11.3

### Language Extension Version (if applicable)

2023.9.11521013.

### Anaconda Version (if applicable)

not applicable

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by patchie** [comment] 2023-06-01 20:52
Upgraded to the following version, but still same problem:
> Version: 1.79.0-insider (user setup)
> Commit: 940571e267875749bac5577689072318d8f02485
> Date: 2023-06-01T19:04:23.199Z
> Electron: 22.5.4
> Chromium: 108.0.5359.215
> Node.js: 16.17.1
> V8: 10.8.168.25-electron.0
> OS: Windows_NT x64 10.0.19044

**Comment by DonJayamanne** [comment] 2023-06-01 22:04
Thank you for filing this issue and sorry you are running into this.
Looks like its not the update to VS Code or Jupyter extension that caused the issue instead you seem to have updated your Python environment and that is causing issues (if you look at the errors, these are errors from your Python environment)

Thats fine, lets try to get that sorted out.

> 14:35:57.357 [warn] Exception while attempting zmq : No native build was found for platform=linux arch=x64 runtime=electron abi=93 uv=1 libc=glibc node=16.17.1
    loaded from: ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/node_modules/zeromq
14:35:57.357 [warn] Exception while attempting zmq (fallback) : No native build was found for platform=linux arch=x64 runtime=electron abi=93 uv=1 libc=glibc node=16.17.1
    loaded from: ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/node_modules/zeromqold

This is not supposed to happen. Hence the questions below.

* Please can you open a terminal and let me know the contents of the file `/etc/os-release` using the command `cat /etc/os-release`
please paste all of the contents.

* Please can you open the following folder in your WSL environment `/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/node_modules/zeromq` and list all of the files and folders
Use the command `ls -R` to list all of the files/folders under the `zeromq` folder above.

Let me know what you get, thank you.

**Comment by DonJayamanne** [comment] 2023-06-01 22:05
In the mean time I will prepare a new VSIX with more logging to help me get more information. thank you.

**Comment by DonJayamanne** [comment] 2023-06-01 23:11
@patchie thats very weird, how did you install the VSIX. Did you manually download it and install it?
* Please could you go to the marketplace here
* Click On the `Download` button
* Select `Linux X64` 
* Download the VSIX to your local machine (paste this into your one of your WSL folders)
* Go into VS Code and then select the command `Install from VSIX` and select the above VSIX downloaded
* Once installed reload VS Code and open a Notebook file.
* Verify the following error message does not appear towards to the top of the logs
(today this error message is right at the top of the logs)
```
14:35:57.357 [warn] Exception while attempting zmq : No native build was found for platform=linux arch=x64 runtime=electron abi=93 uv=1 libc=glibc node=16.17.1
loaded from: ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/node_modules/zeromq
14:35:57.357 [warn] Exception while attempting zmq (fallback) : No native build was found for platform=linux arch=x64 runtime=electron abi=93 uv=1 libc=glibc node=16.17.1
loaded from: ~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-2023.5.1001541100/out/node_modules/zeromqold
```


This should fix things for you, let me know how this goes.
Downloading the VSIX this way is a temporary work around, problem is you are in WSL and somehow only the windows VSIX is downloaded and not the Linux version

**Comment by DonJayamanne** [comment] 2023-06-01 23:19
I just tested this in WSL2 and the right VSIX is getting downloaded and installed, looks like you may have manually downloaded the VSIX from the marketplace, I would suggest you download the `Linux x64` when downloading the VSIX for your instance of WSL.

I'm confident this (downloading the right version of the VSIX or installing it from within VS Code itself) should fix this issue, hence I'm closing this, 
if it does not please do let me know and I'll re-open this issue or please feel free to close this issue.

**Closed by DonJayamanne** 2023-06-01 23:19 UTC
Labels: bug

**Comment by DonJayamanne** [comment] 2023-06-02 07:15
Thank you for getting back with a confirmation of the fix

**Comment by thomasaarholt** [comment] 2023-06-12 11:59
Thank you both for your clear posts and answers:

I just realised that the cause of this issue was the same that I had in #13500 - we were copying over our (mac) extensions in order to "save time" and have them pre-installed when developing in Docker. Turns out there is no check on extension load to determine if the correct OS' version is installed!
