### ISSUE TITLE
Better docs on Issue 14671

### ISSUE THREAD

**Issue by nick-youngblut** [microsoft/vscode-jupyter#15794] opened 2024-06-25 03:37 UTC
While https://github.com/microsoft/vscode-jupyter/issues/14671 is considered closed, all of my colleagues and I have independently run into this issue. While https://github.com/microsoft/vscode-jupyter/issues/14671 does provide a solution, searching through all of the  >10k open/closed issues in this repo is asking a lot, in order to come upon https://github.com/microsoft/vscode-jupyter/issues/14671. One of my colleagues stopped using vscode-jupyter because he couldn't figure out the `tornado.web.HTTPError: HTTP 403: Forbidden` errors that he was getting. I'm glad I found https://github.com/microsoft/vscode-jupyter/issues/14671  before giving up on vscode-jupyter.

It would be helpful to add some docs (maybe [here](https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_connect-to-a-remote-jupyter-server)) with info on what to do in the situation described by https://github.com/microsoft/vscode-jupyter/issues/14671.

**Comment by DonJayamanne** [comment] 2024-12-10 23:57
Closing this issue as I haven't seen any new issues related to this.
If this is still a problem please do let me know, I'd prefer to fix the underlying issue instead of documenting some work arounds.

**Closed by DonJayamanne** 2024-12-10 23:57 UTC
Labels: feature-request

**Comment by DonJayamanne** [comment] 2024-12-11 00:05
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15931
I.e. fixing the above should address this issue as well.
