### ISSUE TITLE
Jupyter Notebooks in VSCode Intermittently extremely slow.

### ISSUE THREAD

**Issue by neelnanda-io** [microsoft/vscode-jupyter#11921] opened 2022-11-05 17:12 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

**Expected:** Jupyter notebook cells run fast

**Observed:** Jupyter notebook cells sometimes run extremely slowly

Jupyter notebooks in VSCode are intermittently extremely slow to run on a remote machine. Extremely simple cells sometimes takes tens of seconds, up to minutes to run. Sometimes it hangs for >10 minutes and I have to reload VSCode before I can continue coding.

Interactive windows, on the other hand, are fast and have no issues.

A simple reproducible example is running a cell containing `raise ValueError`. Running it 5 times, I get runtimes of 247ms, 2376ms, 18083ms, 2436ms and 1531ms. 

This also occurs for cells without errors, but more intermittently.

There were some other issues raised on this topic, but none of the solutions worked for me.

### VS Code Version

Version: 1.72.2 (Universal)

### Jupyter Extension Version

v2022.9.1202862440

### Jupyter logs

```shell
debug 17:09:23.406: VSCodeNotebookController::handleExecution, Class name = x (started execution)
debug 17:09:23.407: Execute Cell 6 /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:23.407: start the kernel, options.disableUI=false
debug 17:09:23.407: Start Jupyter Session in kernel.ts with disableUI = false
info 17:09:23.652: Cancel all remaining cells true || Error || undefined
debug 17:09:23.652: Cancel pending cells
debug 17:09:23.652: Cell 6 executed with state Error
debug 17:09:23.653: VSCodeNotebookController::handleExecution, Class name = x, completed in 247ms, has a falsy return value
debug 17:09:35.662: VSCodeNotebookController::handleExecution, Class name = x (started execution)
debug 17:09:35.662: Execute Cell 6 /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:35.662: start the kernel, options.disableUI=false
debug 17:09:35.662: Start Jupyter Session in kernel.ts with disableUI = false
info 17:09:38.037: Cancel all remaining cells true || Error || undefined
debug 17:09:38.037: Cancel pending cells
debug 17:09:38.037: Cell 6 executed with state Error
debug 17:09:38.037: VSCodeNotebookController::handleExecution, Class name = x, completed in 2376ms, has a falsy return value
debug 17:09:40.645: VSCodeNotebookController::handleExecution, Class name = x (started execution)
debug 17:09:40.646: Execute Cell 6 /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:40.646: start the kernel, options.disableUI=false
debug 17:09:40.646: Start Jupyter Session in kernel.ts with disableUI = false
info 17:09:58.726: Cancel all remaining cells true || Error || undefined
debug 17:09:58.726: Cancel pending cells
debug 17:09:58.726: Cell 6 executed with state Error
debug 17:09:58.728: VSCodeNotebookController::handleExecution, Class name = x, completed in 18083ms, has a falsy return value
debug 17:10:32.651: VSCodeNotebookController::handleExecution, Class name = x (started execution)
debug 17:10:32.652: Execute Cell 6 /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:10:32.652: start the kernel, options.disableUI=false
debug 17:10:32.652: Start Jupyter Session in kernel.ts with disableUI = false
info 17:10:35.085: Cancel all remaining cells true || Error || undefined
debug 17:10:35.085: Cancel pending cells
debug 17:10:35.086: Cell 6 executed with state Error
debug 17:10:35.087: VSCodeNotebookController::handleExecution, Class name = x, completed in 2436ms, has a falsy return value
debug 17:10:46.684: VSCodeNotebookController::handleExecution, Class name = x (started execution)
debug 17:10:46.684: Execute Cell 6 /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:10:46.684: start the kernel, options.disableUI=false
debug 17:10:46.685: Start Jupyter Session in kernel.ts with disableUI = false
info 17:10:48.214: Cancel all remaining cells true || Error || undefined
debug 17:10:48.214: Cancel pending cells
debug 17:10:48.215: Cell 6 executed with state Error
debug 17:10:48.215: VSCodeNotebookController::handleExecution, Class name = x, completed in 1531ms, has a falsy return value
```

### Coding Language and Runtime Version

Python v3.7.13

### Language Extension Version (if applicable)

v2022.16.1

### Anaconda Version (if applicable)

22.9.0

### Running Jupyter locally or remotely?

Remote

**Comment by neelnanda-io** [comment] 2022-11-05 17:15
Additional debugging I tried:
* Disabling all extensions apart from Jupyter, Python & Remote SSH
* Uninstalling and reinstalling VSCode locally
* Uninstalling and reinstalling VSCode on the remote server.

Here are the verbose logs that I get after restarting the kernel in case they're relevant:
<details> <summary> Restarting kernel logs</summary>
debug 17:09:10.317: restart the kernel, options.disableUI=false
info 17:09:10.318: Restart requested file:///workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
info 17:09:10.319: Restart kernel execution
debug 17:09:10.319: Cancel pending cells
info 17:09:10.319: Restarting b43a9b7b-eef5-444d-90ea-43e47ecaec68
debug 17:09:10.319: Kernel Launcher. launch, Class name = r (started execution), Arg 1: {"kind":"startUsingPythonInterpreter","kernelSpec":{"interpreterPath":"/opt/conda/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"python3713jvsc74a57bd0d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3.7.13 ('base')","metadata":{"interpreter":{"path":"/opt/conda/bin/python"}},"env":{}},"interpreter":{"id":"/opt/conda/bin/python","sysPrefix":"/opt/conda","envType":"Conda","envName":"base","envPath":{"$mid":1,"fsPath":"/opt/conda","path":"/opt/conda","scheme":"file"},"architecture":3,"sysVersion":"3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]","version":{"raw":"3.7.13","major":3,"minor":7,"patch":13,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.7.13 ('base')","detailedDisplayName":"Python 3.7.13 ('base': conda)","uri":{"$mid":1,"fsPath":"/opt/conda/bin/python","external":"file:///opt/conda/bin/python","path":"/opt/conda/bin/python","scheme":"file"}},"id":".jvsc74a57bd0d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe./opt/conda/python./opt/conda/python.-m#ipykernel_launcher"}, Arg 2: 60000, Arg 3: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 4: "~/Easy-Transformer", Arg 5: {"_isCancelled":false,"_emitter":null}
debug 17:09:10.319: Create activated Env, Class name = _ (started execution), Arg 1: {"interpreter":{"id":"/opt/conda/bin/python","sysPrefix":"/opt/conda","envType":"Conda","envName":"base","envPath":{"$mid":1,"fsPath":"/opt/conda","path":"/opt/conda","scheme":"file"},"architecture":3,"sysVersion":"3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]","version":{"raw":"3.7.13","major":3,"minor":7,"patch":13,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.7.13 ('base')","detailedDisplayName":"Python 3.7.13 ('base': conda)","uri":{"$mid":1,"fsPath":"/opt/conda/bin/python","external":"file:///opt/conda/bin/python","path":"/opt/conda/bin/python","scheme":"file"}},"resource":{"$mid":1,"fsPath":"/workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","external":"file:///workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","path":"/workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","scheme":"file"}}
debug 17:09:10.319: Getting activated env variables, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>, Arg 3: undefined
debug 17:09:10.319: Getting activated env variables impl, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.319: Getting activated env variables ourselves, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.319: Getting activated env variables from Python, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.319: Get Custom Env Variables, Class name = w (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: "RunPythonCode"
debug 17:09:10.319: Cached data exists getEnvironmentVariables, /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:10.319: Cached custom vars data exists getCustomEnvironmentVariables, /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:10.319: Get Custom Env Variables, Class name = w, completed in 0ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: "RunPythonCode"
debug 17:09:10.321: Got activation Env Vars from cached promise with key /workspace_d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe
debug 17:09:10.321: Getting activated env variables ourselves, Class name = V, completed in 2ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
info 17:09:10.322: Got env vars with python /opt/conda/bin/python, with env var count 38 and custom env var count 0 in 3ms
info 17:09:10.322: Got env vars ourselves faster /opt/conda/bin/python with env var count 37 in 3ms
debug 17:09:10.322: Getting activated env variables from Python, Class name = V, completed in 3ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.322: Got env vars ourselves /opt/conda/bin/python in 3ms
debug 17:09:10.322: Getting activated env variables impl, Class name = V, completed in 3ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.322: Got env vars with python /opt/conda/bin/python in 3ms
debug 17:09:10.322: Getting activated env variables, Class name = V, completed in 3ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>, Arg 3: undefined
debug 17:09:10.323: Create activated Env, Class name = _, completed in 4ms, has a truthy return value, Arg 1: {"interpreter":{"id":"/opt/conda/bin/python","sysPrefix":"/opt/conda","envType":"Conda","envName":"base","envPath":{"$mid":1,"fsPath":"/opt/conda","path":"/opt/conda","scheme":"file"},"architecture":3,"sysVersion":"3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]","version":{"raw":"3.7.13","major":3,"minor":7,"patch":13,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.7.13 ('base')","detailedDisplayName":"Python 3.7.13 ('base': conda)","uri":{"$mid":1,"fsPath":"/opt/conda/bin/python","external":"file:///opt/conda/bin/python","path":"/opt/conda/bin/python","scheme":"file"}},"resource":{"$mid":1,"fsPath":"/workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","external":"file:///workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","path":"/workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","scheme":"file"}}
info 17:09:10.341: Process Execution: > /opt/conda/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /opt/conda/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
debug 17:09:10.345: Launching kernel in kernelProcess.ts, Class name = x (started execution), Arg 1: "~/Easy-Transformer", Arg 2: ""
debug 17:09:10.346: Create activated Env, Class name = _ (started execution), Arg 1: {"resource":{"$mid":1,"fsPath":"/workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","external":"file:///workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","path":"/workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","scheme":"file"},"interpreter":{"id":"/opt/conda/bin/python","sysPrefix":"/opt/conda","envType":"Conda","envName":"base","envPath":{"$mid":1,"fsPath":"/opt/conda","path":"/opt/conda","scheme":"file"},"architecture":3,"sysVersion":"3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]","version":{"raw":"3.7.13","major":3,"minor":7,"patch":13,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.7.13 ('base')","detailedDisplayName":"Python 3.7.13 ('base': conda)","uri":{"$mid":1,"fsPath":"/opt/conda/bin/python","external":"file:///opt/conda/bin/python","path":"/opt/conda/bin/python","scheme":"file"}}}
debug 17:09:10.346: Getting activated env variables, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>, Arg 3: undefined
debug 17:09:10.346: Getting activated env variables impl, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.346: Getting activated env variables ourselves, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.346: Getting activated env variables from Python, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.346: Get Custom Env Variables, Class name = w (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: "RunPythonCode"
debug 17:09:10.346: Cached data exists getEnvironmentVariables, /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:10.346: Cached custom vars data exists getCustomEnvironmentVariables, /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:10.346: Cached custom vars data exists getCustomEnvironmentVariables, /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:10.346: Getting activated env variables, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>, Arg 3: false
debug 17:09:10.346: Getting activated env variables impl, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.346: Getting activated env variables ourselves, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.346: Getting activated env variables from Python, Class name = V (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.346: Get Custom Env Variables, Class name = w (started execution), Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: "RunPythonCode"
debug 17:09:10.346: Cached data exists getEnvironmentVariables, /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:10.346: Cached custom vars data exists getCustomEnvironmentVariables, /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
debug 17:09:10.346: Get Custom Env Variables, Class name = w, completed in 0ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: "RunPythonCode"
debug 17:09:10.347: Get Custom Env Variables, Class name = w, completed in 1ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: "RunPythonCode"
debug 17:09:10.348: Got activation Env Vars from cached promise with key /workspace_d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe
debug 17:09:10.348: Got activation Env Vars from cached promise with key /workspace_d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe
debug 17:09:10.348: Getting activated env variables ourselves, Class name = V, completed in 2ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
info 17:09:10.349: Got env vars with python /opt/conda/bin/python, with env var count 38 and custom env var count 0 in 3ms
debug 17:09:10.349: Getting activated env variables ourselves, Class name = V, completed in 3ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
info 17:09:10.349: Got env vars with python /opt/conda/bin/python, with env var count 38 and custom env var count 0 in 3ms
info 17:09:10.349: Got env vars ourselves faster /opt/conda/bin/python with env var count 37 in 3ms
debug 17:09:10.349: Getting activated env variables from Python, Class name = V, completed in 3ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
info 17:09:10.349: Got env vars ourselves faster /opt/conda/bin/python with env var count 37 in 3ms
debug 17:09:10.349: Getting activated env variables from Python, Class name = V, completed in 3ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.349: Got env vars ourselves /opt/conda/bin/python in 3ms
debug 17:09:10.349: Getting activated env variables impl, Class name = V, completed in 3ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.350: Got env vars with python /opt/conda/bin/python in 4ms
debug 17:09:10.350: Got env vars ourselves /opt/conda/bin/python in 4ms
debug 17:09:10.350: Getting activated env variables impl, Class name = V, completed in 4ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>
debug 17:09:10.350: Got env vars with python /opt/conda/bin/python in 4ms
debug 17:09:10.350: Getting activated env variables, Class name = V, completed in 4ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>, Arg 3: undefined
debug 17:09:10.350: Getting activated env variables, Class name = V, completed in 4ms, has a truthy return value, Arg 1: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 2: <Uri:/opt/conda/bin/python>, Arg 3: false
debug 17:09:10.350: Create activated Env, Class name = _, completed in 4ms, has a truthy return value, Arg 1: {"resource":{"$mid":1,"fsPath":"/workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","external":"file:///workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","path":"/workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb","scheme":"file"},"interpreter":{"id":"/opt/conda/bin/python","sysPrefix":"/opt/conda","envType":"Conda","envName":"base","envPath":{"$mid":1,"fsPath":"/opt/conda","path":"/opt/conda","scheme":"file"},"architecture":3,"sysVersion":"3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]","version":{"raw":"3.7.13","major":3,"minor":7,"patch":13,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.7.13 ('base')","detailedDisplayName":"Python 3.7.13 ('base': conda)","uri":{"$mid":1,"fsPath":"/opt/conda/bin/python","external":"file:///opt/conda/bin/python","path":"/opt/conda/bin/python","scheme":"file"}}}
info 17:09:10.371: Process Execution: > /opt/conda/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"4049bbc3-72ee-45cc-ae01-1753b7cad17d" --shell=9002 --transport="tcp" --iopub=9004 --f=/workspace/.local/share/jupyter/runtime/kernel-v2-196973BnAyZzblOGGs.json
> /opt/conda/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"4049bbc3-72ee-45cc-ae01-1753b7cad17d" --shell=9002 --transport="tcp" --iopub=9004 --f=/workspace/.local/share/jupyter/runtime/kernel-v2-196973BnAyZzblOGGs.json
info 17:09:10.371: Process Execution: cwd: ~/Easy-Transformer
cwd: ~/Easy-Transformer
debug 17:09:10.371: Launching kernel in kernelProcess.ts, Class name = x, completed in 26ms, has a truthy return value, Arg 1: "~/Easy-Transformer", Arg 2: ""
info 17:09:10.474: ipykernel version & path 6.15.1, /opt/conda/lib/python3.7/site-packages/ipykernel/__init__.py for /opt/conda/bin/python
debug 17:09:10.843: KernelProcess error: /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2395: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2349: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '4049bbc3-72ee-45cc-ae01-1753b7cad17d' instead of 'b"4049bbc3-72ee-45cc-ae01-1753b7cad17d"'.
  FutureWarning,

warn 17:09:10.844: StdErr from Kernel Process /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2395: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2349: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '4049bbc3-72ee-45cc-ae01-1753b7cad17d' instead of 'b"4049bbc3-72ee-45cc-ae01-1753b7cad17d"'.
  FutureWarning,

debug 17:09:10.852: KernelProcess output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-196973BnAyZzblOGGs.json

info 17:09:10.852: Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-196973BnAyZzblOGGs.json

debug 17:09:10.977: Kernel Launcher. launch, Class name = r, completed in 658ms, has a truthy return value, Arg 1: {"kind":"startUsingPythonInterpreter","kernelSpec":{"interpreterPath":"/opt/conda/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"python3713jvsc74a57bd0d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3.7.13 ('base')","metadata":{"interpreter":{"path":"/opt/conda/bin/python"}},"env":{}},"interpreter":{"id":"/opt/conda/bin/python","sysPrefix":"/opt/conda","envType":"Conda","envName":"base","envPath":{"$mid":1,"fsPath":"/opt/conda","path":"/opt/conda","scheme":"file"},"architecture":3,"sysVersion":"3.7.13 (default, Mar 29 2022, 02:18:16) \n[GCC 7.5.0]","version":{"raw":"3.7.13","major":3,"minor":7,"patch":13,"build":[],"prerelease":["final","0"]},"companyDisplayName":"Anaconda, Inc.","displayName":"Python 3.7.13 ('base')","detailedDisplayName":"Python 3.7.13 ('base': conda)","uri":{"$mid":1,"fsPath":"/opt/conda/bin/python","external":"file:///opt/conda/bin/python","path":"/opt/conda/bin/python","scheme":"file"}},"id":".jvsc74a57bd0d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe./opt/conda/python./opt/conda/python.-m#ipykernel_launcher"}, Arg 2: 60000, Arg 3: "~/Easy-Transformer/Induction_Heads_Temperature.ipynb", Arg 4: "~/Easy-Transformer", Arg 5: <argument cannot be serialized for logging>
debug 17:09:10.986: Waiting for Raw Session to be ready in postStartRawSession
debug 17:09:10.986: Waiting for Raw session to be ready, currently connected
debug 17:09:10.986: Raw session connected
debug 17:09:10.986: Waiting for Raw session to be ready for 30s
debug 17:09:10.988: Waited for Raw session to be ready & got connected
debug 17:09:10.988: Successfully waited for Raw Session to be ready in postStartRawSession
debug 17:09:10.988: Kernel status before requesting kernel info and after ready is unknown
debug 17:09:10.988: Sending request for kernelinfo
debug 17:09:10.998: Got response for requestKernelInfo
debug 17:09:10.998: Successfully compelted postStartRawSession
info 17:09:11.002: Got new session 3482ad49-c013-4efb-8231-0f5e6c5dab64
info 17:09:11.002: Started new restart session
debug 17:09:11.002: shutdownSession b43a9b7b-eef5-444d-90ea-43e47ecaec68, .jvsc74a57bd0d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe./opt/conda/python./opt/conda/python.-m#ipykernel_launcher - start
debug 17:09:11.002: Session can be shutdown .jvsc74a57bd0d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe./opt/conda/python./opt/conda/python.-m#ipykernel_launcher
info 17:09:11.003: Dispose Kernel process 198332.
debug 17:09:11.025: Begin sendTelemetryForPythonKernelExecutable
debug 17:09:11.025: Executing silently Code (idle) = import sys\nprint(sys.executable)
debug 17:09:11.031: Disposed Kernel process 198332.
debug 17:09:11.032: shutdownSession b43a9b7b-eef5-444d-90ea-43e47ecaec68, .jvsc74a57bd0d4d1e4263499bec80672ea0156c357c1ee493ec2b1c70f0acce89fc37c4a6abe./opt/conda/python./opt/conda/python.-m#ipykernel_launcher - shutdown complete
debug 17:09:11.044: KernelProcess Exit Exit - undefined /opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2395: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  FutureWarning,
/opt/conda/lib/python3.7/site-packages/traitlets/traitlets.py:2349: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '1de2cdab-511b-44cb-84f7-ee320172fb25' instead of 'b"1de2cdab-511b-44cb-84f7-ee320172fb25"'.
  FutureWarning,

debug 17:09:11.216: Widget Message: Received IPyWidgetMessages.IPyWidgets_onRestartKernel
debug 17:09:11.225: Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
debug 17:09:11.225: Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
debug 17:09:11.226: IPyWidgetMessageDispatcher.initialize
debug 17:09:11.226: IPyWidgetMessageDispatcher.initialize
debug 17:09:11.726: Executing silently Code (completed) = import sys\nprint(sys.executable) with 1 output(s)
debug 17:09:11.727: Started running kernel initialization for /workspace/Easy-Transformer/Induction_Heads_Temperature.ipynb
info 17:09:11.730: UpdateWorkingDirectoryAndPath in Kernel
debug 17:09:11.731: Executing silently Code (idle) = import os\nimport sys\n%cd "//workspace/Easy-Transformer"\nif os.getcwd() not in sys.path:\nsys.path
debug 17:09:11.752: Executing silently Code (completed) = import os\nimport sys\n%cd "//workspace/Easy-Transformer"\nif os.getcwd() not in sys.path:\nsys.path with 1 output(s)
debug 17:09:11.753: Not executing startup session: Object, code: 
debug 17:09:11.753: Requesting Kernel info
debug 17:09:11.753: Got Kernel info
debug 17:09:11.753: End running kernel initialization, now waiting for idle
debug 17:09:11.753: Waiting for 60000ms idle on (kernel): 3482ad49-c013-4efb-8231-0f5e6c5dab64 -> idle
debug 17:09:11.753: Finished waiting for idle on (kernel): 3482ad49-c013-4efb-8231-0f5e6c5dab64 -> idle
debug 17:09:11.754: End running kernel initialization, session is idle
debug 17:09:11.754: Registering commtarget jupyter.widget
</details>

**Comment by neelnanda-io** [comment] 2022-11-05 17:20
Ah, I also often use Plotly graphics, and this was done in a notebook with several Plotly graphics, which may be an important factor?

**Comment by neelnanda-io** [comment] 2022-11-05 17:22
Often the cell will have the static symbol of the clock with an anti-clockwise arrow for a while before the icon starts spinning and tracking time

**Comment by DonJayamanne** [comment] 2022-12-04 20:32
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12284

**Closed by DonJayamanne** 2022-12-04 20:32 UTC
Labels: bug
