### ISSUE TITLE
The .ipynb file is opened but it stops after showing the JSON.

### ISSUE THREAD

**Issue by AbeOmor** [microsoft/vscode-jupyter#4317] opened 2021-01-07 01:47 UTC
## Environment data

-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: Python 3.5.2 64-bit
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local 

## Expected behaviour

A jupyter Notebook should be shown

## Actual behaviour

![image](https://user-images.githubusercontent.com/9068012/103839742-f26a8f00-5044-11eb-8f5c-b845efb2959b.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

![VSCode Error](https://user-images.githubusercontent.com/9068012/103840832-2e9eef00-5047-11eb-9223-b7b3fb9efcc5.gif)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Error 2021-01-07 01:23:24: Exception while attempting zmq : [Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/zeromq/prebuilds/linux-x64/node.napi.glibc.node)
	at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
	at Module.load (internal/modules/cjs/loader.js:811:32)
	at Function.Module._load (internal/modules/cjs/loader.js:723:14)
	at Function.t._load (/home/azureuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1116:657)
	at Function.i._load (/home/azureuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1085:334)
	at Function.n._load (/home/azureuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1081:567)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at load (/home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/node-gyp-build/index.js:21:10)
	at Object.<anonymous> (/home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/zeromq/lib/native.js:6:43)
	at Module._compile (internal/modules/cjs/loader.js:955:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	at Module.load (internal/modules/cjs/loader.js:811:32)
	at Function.Module._load (internal/modules/cjs/loader.js:723:14)
	at Function.t._load (/home/azureuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1116:657)
	at Function.i._load (/home/azureuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1085:334)
	at Function.n._load (/home/azureuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1081:567)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Object.<anonymous> (/home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/node_modules/zeromq/lib/index.js:3:16)
	at Module._compile (internal/modules/cjs/loader.js:955:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	at Module.load (internal/modules/cjs/loader.js:811:32)
	at Function.Module._load (internal/modules/cjs/loader.js:723:14)
	at Function.t._load (/home/azureuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1116:657)
	at Function.i._load (/home/azureuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1085:334)
	at Function.n._load (/home/azureuser/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/out/vs/server/remoteExtensionHostProcess.js:1081:567)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Object.<anonymous> (/home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:32:274679)
	at n (/home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:1:124)
	at /home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:803883
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async u.zmqSupportedImpl (/home/azureuser/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/out/client/extension.js:49:803850)]
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> /usr/bin/python3 ~/.vscode-server/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"

```

</p>
</details>

**Comment by DonJayamanne** [comment] 2021-01-07 17:04
Thanks for filing this issue, please could you provide the output from the `Jupyter` output panel.
Also, please could you open `VSCode -> Help-> Toggle Developer Tools` & go into the console window and provide the output from there.
Thanks

**Comment by AbeOmor** [comment] 2021-01-08 20:15
@DonJayamanne Here: 
![image](https://user-images.githubusercontent.com/9068012/104060042-2b247880-51ab-11eb-8eb6-49f0aaf0cd7c.png)

**Comment by DonJayamanne** [comment] 2021-01-08 23:11
Thanks for getting back.
I believe the issue here is ipynb files are not configured to be opened in the notebook editor (this is the default behavior), you need to change the deafult settings so that *.ipynb files always open in the notebook editor.
Please change your settings as follows:
* GO into user settings
* Locate the setting `Automatically open .ipynb in the Notebook Editor.`
* Enable that & it should work after that.

Closing for now, however if this doesn't resolve the issue please reply back or feel free to open another issue.

**Comment by SiddhanthUnnithan** [comment] 2021-01-11 18:02
@DonJayamanne to add - this issue occurs when a remote window is opened. The steps are as follows:

1. User opens remote window through AML extension.
2. AML extension opens .ipynb file as part of resolver.
3. [Expected] .ipynb file opened in the Notebook editor instead of remaining in the raw JSON form.

What's odd is that the behaviour above is what we were seeing in December, but more recently it's changed to not automatically being opened in the Notebook view. If you look at the GIF above it looks like the Python and Jupyter extension activation events are triggered (as a result of the opened file).

Is there a way to change that setting programmatically? One option here might be for the AML extension to set that before it opens the .ipynb file and then see if we're seeing the expected behaviour.

**Comment by DonJayamanne** [comment] 2021-01-11 18:19
> What's odd is that the behaviour above is what we were seeing in December, but more recently it's changed to not automatically being opened in the Notebook view

Not sure about that, this has always been the default behavior.

>  One option here might be for the AML extension to set that before it opens the .ipynb file and then see if we're seeing the expected behaviour.

Yes thats an option.

**Comment by SiddhanthUnnithan** [comment] 2021-01-11 19:56
Reopening this as per the conversation with @DonJayamanne during standup today.

**Comment by DonJayamanne** [comment] 2021-01-12 17:54
Additional information:
* The option to open ipynb files in Notebook editor has been enabled

**Comment by rchiodo** [comment] 2021-02-18 00:38
Is this still a problem? We enabled AML extension to always use the new editor

**Comment by DonJayamanne** [comment] 2021-02-23 20:25
@SiddhanthUnnithan  Closing this as this has been fixed, (AML AML compute machines shoudl get native notebooks).
Please re-open or create a new issue if this persists.

**Closed by DonJayamanne** 2021-02-23 20:25 UTC
Labels: bug, info-needed
