### ISSUE TITLE
cell expended in Interative window by default

### ISSUE THREAD

**Issue by TQTQTQ1991** [microsoft/vscode-jupyter#8533] opened 2021-12-13 08:36 UTC
## Environment data

version 1.63.0 (user setup)
: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
date: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

## Expected behaviour

cell will be collapsed in interactive window when running in jupyter+vscode intervative mode

## Actual behaviour

automatically expended, and there is no setting to set it to collapse by default

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2021-12-13 18:46
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8203

**Closed by DonJayamanne** 2021-12-13 18:46 UTC
Labels: bug, needs-triage
