### ISSUE TITLE
Feature requerst: Add data visualization in Data Viewer

### ISSUE THREAD

**Issue by Chris-Tang6** [microsoft/vscode-jupyter#14223] opened 2023-08-29 11:43 UTC
## Issue Type
Feature Request

## Description

When I debugging pytorch code, I often check the tensor value. 

And I really like the value visualization function ([SciView](https://www.jetbrains.com/help/pycharm/matplotlib-support.html#data)) in Pycharm, cuz with the different color I can quickly know if the feature tensor is normal.

I would be  very thankful if VSCode can add this feature too🤗🤗

![image](https://github.com/microsoft/vscode/assets/53926670/4ab9b800-d1e0-4e40-88d7-22b6958446c4)

![image](https://github.com/microsoft/vscode/assets/53926670/e0fafff4-c6bb-4ac3-bf4b-c477dbc6b23b)

**Comment by roblourens** [comment] 2023-08-30 20:07
Can you tell me how the coloring works, I don't think I follow it?

**Comment by Chris-Tang6** [comment] 2023-08-31 01:00
> Can you tell me how the coloring works, I don't think I follow it?

In my eyes:

for each column in the matrix, it will get the **_min_val_** and **_max_val_**, 

assign **_color_weight_ = 0** to all min_val places, assign **1** to all max_val places.

As to others values, eg. **x**, their **color_weight = (x - min_val) / (max_val - min_val)**

In this way, it get all color weight in one column, we can do the same on others columns.


In the coloring step, when color_weight change from 0 to 1, fill color from blue to red.

**Comment by costabm** [comment] 2023-12-06 10:52
See a related feature request [here](https://github.com/microsoft/vscode-jupyter/issues/13113)

**Comment by amunger** [comment] 2023-12-14 23:47
closing as dupe of https://github.com/microsoft/vscode-jupyter/issues/13113

**Closed by amunger** 2023-12-14 23:47 UTC
Labels: data-viewer, feature-request
