### ISSUE TITLE
Inf, -Inf, and NaNs don't show up in the Data Viewer

### ISSUE THREAD

**Issue by jmew** [microsoft/vscode-jupyter#1147] opened 2020-09-30 21:02 UTC
If i have a data frame with infinity, -infinity, or NaN values, they show up as blank in the data viewer

**Comment by IanMatthewHuff** [comment] 2021-02-09 18:34
Closing as a dupe of #299 which I'll be validating.

**Closed by IanMatthewHuff** 2021-02-09 18:34 UTC
Labels: bug, internal contributor
