### ISSUE TITLE
[bug] Error to export notebook to any format

### ISSUE THREAD

**Issue by wbadry** [microsoft/vscode-jupyter#6712] opened 2021-07-18 14:17 UTC
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10 21H1 (19103.1110)
-   Python and/or Anaconda version: 3.8.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behavior

Ability to export to HTML or PDF

## Actual behavior

 - The `export button` doesn't do anything when pressed.
 - There is an error when using the command `Jupyter: Export` showing the command doesn't exist

## Steps to reproduce:

A `gif` image is showing the exact behavior described

![baehavior](https://user-images.githubusercontent.com/5664750/126070571-c3664d13-2491-4470-a5f6-abc2de9bb2a0.gif)

**Comment by claudiaregio** [comment] 2021-07-18 20:53
Dupe of https://github.com/microsoft/vscode-jupyter/issues/6671

**Closed by claudiaregio** 2021-07-18 20:53 UTC
Labels: bug, needs-triage
