### ISSUE TITLE
Support persistent raw kernel sessions

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6420] opened 2021-06-29 18:48 UTC
Testing microsoft/vscode#127378

Create IW from a code lens
Reload VS code

IW has two sys infos in it after it starts up

![image](https://user-images.githubusercontent.com/19672699/123851384-f7abe680-d8cf-11eb-9065-dc0176c2680d.png)

**Comment by rebornix** [comment] 2022-08-01 15:49
This is currently not supported and we might want to reconsider since we can restore history in IW now.

**Comment by amunger** [comment] 2022-08-01 22:02
duplicate of #3998

**Closed by amunger** 2022-08-01 22:02 UTC
Labels: enhancement, triage-needed
