### ISSUE TITLE
"Go to [#]" codelenses don't work for Interactive Window

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7648] opened 2021-09-23 22:06 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Start an interactive session by running a #%% cell.
2. Click on the 'Go to [1]' codelens

Nothing happens. It should highlight the cell in the interactive window and give it focus.
![image](https://user-images.githubusercontent.com/11685408/134590438-d68406c7-1dc3-4470-b288-c885591ad81b.png)

### VS Code Version

v1.61-insiders

### Jupyter Extension Version

v2021.9.1001261101

**Comment by DonJayamanne** [comment] 2021-09-23 22:18
Lol was fixed in the last release as a regression, looks like we've regressed again after the point fix https://github.com/microsoft/vscode-jupyter/issues/7347
This is bad

**Comment by DonJayamanne** [comment] 2021-09-27 22:33
> Scrolling seems to work. There just isn't a highlight

Aah, I want aware of that

**Comment by rchiodo** [comment] 2021-09-27 22:40
I think we should rethink this too. It's really hokey the highlight.

**Comment by rchiodo** [comment] 2021-09-27 22:41
https://github.com/microsoft/vscode-jupyter/issues/7687

**Closed** 2021-09-27 22:55 UTC
Labels: bug, regression, interactive-window, needs-triage
