### ISSUE TITLE
Jupyter notebook hyperlinks to errors in code file do not open in remote session

### ISSUE THREAD

**Issue by anuszka** [microsoft/vscode-jupyter#14544] opened 2023-10-21 11:47 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I import functions from a file and an error occurs while executing the code, the hyperlink to the code file does not work. The problem occurs in a remote session only.

Steps to reproduce:

1. Open an ssh session on a remote server
2. Save a file with Python code containing an error. Here, I saved the file `error.py` in the current working directory:

        def fun() # Syntax error in this line
            print("Hello world")
            return
3. Save a Jupyter notebook in the current working directory. In the notebook, run:

        from error import * # This file contains an error

4. The error message shows up:

        Traceback (most recent call last):

          File ~/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3508 in run_code
            exec(code_obj, self.user_global_ns, self.user_ns)

          Cell In[1], line 1
            from error import * # This file contains an error

          File ~/myworkspacedir/mycwd/error.py:1
            def fun() # Syntax error in this line
                    ^
          SyntaxError: invalid syntax

5. In the error message, the fragment `~/myworkspacedir/mycwd/error.py:1` is a hyperlink. Click on it.
6. The error message shows up: 

_Unable to open 'error.py'_

_The editor could not be opened because the file was not found_

### VS Code Version

1.83.1

### Jupyter Extension Version

v2023.9.1102792234

### Jupyter logs

```shell
Visual Studio Code (1.83.1, ssh-remote, desktop)
Jupyter Extension Version: 2023.9.1102792234.
Python Extension Version: 2023.18.0.
Platform: linux (x64).
Workspace folder ~/myworkspacedir, Home = /home/user
13:45:37.022 [info] User belongs to experiment group 'NewJupyterSession'
13:45:37.381 [info] Start refreshing Kernel Picker (1697888737381)
13:45:37.386 [info] Using Pylance
13:45:37.698 [info] Start refreshing Interpreter Kernel Picker
13:45:40.276 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher  (Python Path: /bin/python, Unknown, 3.8.10) for '~/myworkspacedir/mycwd/test_hyperlinks.ipynb' (disableUI=true)
13:45:42.965 [info] End refreshing Kernel Picker (1697888737381)
13:45:42.992 [warn] Failed to get activated env vars for /bin/python in 3556ms
13:45:42.997 [warn] Failed to get activated env vars for /bin/python in 2711ms
13:45:43.027 [info] Process Execution: /bin/python -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
13:45:43.043 [error] Unable to determine site packages path for python /bin/python (Unknown)
13:45:43.043 [error] Unable to determine site packages path for python /bin/python (Unknown)
13:45:43.074 [info] Process Execution: /bin/python -m pip list
13:45:43.103 [info] Process Execution: /bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
13:45:43.134 [info] Process Execution: /bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9004 --control=9002 --hb=9001 --Session.signature_scheme="hmac-sha256" --Session.key=b"217c8523-5ad0-4fdc-ac88-815218ee4655" --shell=9003 --transport="tcp" --iopub=9005 --f=~/.local/share/jupyter/runtime/kernel-v2-41275822CET5Nm47vJR.json
    > cwd: ~/myworkspacedir/mycwd
13:45:43.252 [info] ipykernel version & path 6.25.2, ~/.local/lib/python3.8/site-packages/ipykernel/__init__.py for /bin/python
13:45:43.668 [info] Process Execution: /bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.9.1102792234-linux-x64/pythonFiles/printJupyterDataDir.py
13:45:52.872 [info] Handle Execution of Cells 1 for ~/myworkspacedir/mycwd/test_hyperlinks.ipynb
13:45:52.888 [info] Kernel acknowledged execution of cell 1 @ 1697888752887
13:45:52.892 [info] End cell 1 execution @ 1697888752892, started @ 1697888752887, elapsed time = 0.005s
13:45:52.893 [warn] Cancel all remaining cells due to cancellation or failure in execution
```

### Coding Language and Runtime Version

Python 3.8.10

### Language Extension Version (if applicable)

Python extension v2023.18.0

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment] 2023-10-23 17:18
duplicate of https://github.com/microsoft/vscode-jupyter/issues/13212

**Closed by amunger** 2023-10-23 17:18 UTC
Labels: bug
