### ISSUE TITLE
when output latex is error or not display 

### ISSUE THREAD

**Issue by nczsl** [microsoft/vscode-jupyter#8239] opened 2021-11-11 04:22 UTC
## Environment data

-   VS Code version: 1.62.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1001414422
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: window10 19042
-   Python and/or Anaconda version: paython 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): none
-   Jupyter server running: Local | Remote | N/A  local

## Expected behaviour

don't display latex when after run cell
## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2021-11-11 21:41
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7801

**Closed by DonJayamanne** 2021-11-11 21:41 UTC
Labels: bug, needs-triage
