### ISSUE TITLE
Set new notebook folder location

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode-jupyter#5892] opened 2021-05-14 16:03 UTC
In a recent UX study, participants (data scientists with little experience of VS Code) ran into problems writing code to open a data file relative to a new notebook. After using the Create New Notebook command, most participants wrote code using pandas to open a file like so

```py
df = pd.read_csv("datafile.csv")
```
Then when they realised that the datafile was not in the same folder as the notebook, they struggled to find out where the notebook was.

It would be worth thinking about ways that the user can specify where the new notebook should be created rather than creating it in a hard to find temp folder.

**Comment by DonJayamanne** [comment] 2021-05-14 17:33
Thanks for filing this issue,
* Did the user have a workspace folder open?
* Was the user using the webview notebooks or VS Code Native NOtebooks?

**Comment by rchiodo** [comment] 2021-05-18 22:44
No workspace or folder open.

We could tell the user to open a folder or save the file?

**Comment by rchiodo** [comment] 2021-05-18 22:46
Same problem would happen with a new python file.

**Comment by claudiaregio** [comment] 2021-06-13 02:59
@rchiodo Since it's the same problem with a python file, should this be transferred to vsc repo?

**Comment by rchiodo** [comment] 2021-06-14 16:29
Maybe? The root cause of the problem is the user doesn't know where the file is. We could solve this on our side if we save the file before running a cell. This would force them to pick a location.

An untitled python file does have the same problem, but I feel like the user has different expectations there. A notebook user may not think as much about files per se.

**Comment by DonJayamanne** [comment] 2022-12-06 23:13
Been over a year and there haven't been enough upvotes on this issue, hence closing this issue for now

**Closed by DonJayamanne** 2022-12-06 23:13 UTC
Labels: notebook-getting-started, feature-request
