### ISSUE TITLE
Can't type or copy/paste in python interactive window

### ISSUE THREAD

**Issue by asalcedo29** [microsoft/vscode-jupyter#3970] opened 2020-11-18 23:15 UTC
Issue Type: <b>Bug</b>

Seems like randomly it doesn't allow me to type and copy/paste commands.

Extension version: 2020.11.367453362
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (14.27GB free)|
|Process Argv|C:\Users\ansalced\Downloads\PowerPoint_web_drivers_analysis.ipynb --crash-reporter-id ab6e5b6b-9a23-4324-8ca6-95b75b096ca7|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rmarinbe** [comment] 2020-11-19 05:12
the same is happening to me, this is driving me crazy! I also reported the issue.

**Comment by D-Niermann** [comment] 2020-11-19 11:29
Same for me on Windows 10 and on my Macbook! Happens a few times every 10 Minutes. Python extension and VSCode version up to date.
Another way to "fix" this is to drag the tab into another area (I think it refreshes the GUI Elements).

**Comment by rchiodo** [comment] 2020-11-19 18:15
Dupe of #446. A fix should be coming soon.

**Closed by rchiodo** 2020-11-19 18:15 UTC
