### ISSUE TITLE
codelens actions disappeared

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-jupyter#6455] opened 2021-06-30 17:51 UTC
Testing https://github.com/microsoft/vscode/issues/127378

I do not know how I got into this state - but while playing around with interactive window using a python file, all of a sudden I lost codelens actions

![image](https://user-images.githubusercontent.com/10746682/124008256-860d8e80-d9dc-11eb-81cf-91a6b96c6f7b.png)

**Comment by rchiodo** [comment] 2021-06-30 17:53
Dupe of https://github.com/microsoft/vscode-jupyter/issues/6418

**Closed by rchiodo** 2021-06-30 17:53 UTC
Labels: bug
