### ISSUE TITLE
cell output to fullscreen

### ISSUE THREAD

**Issue by bdch1234** [microsoft/vscode-jupyter#10978] opened 2022-07-29 21:03 UTC
It would be fantastic if there was a quick way (small button or keyboard shortcut) to send the output of a cell to fullscreen for further interaction (plotly charts e.g.). Would that be possible to add?

**Comment by amunger** [comment] 2022-07-29 22:04
We have a button that shows up on hover to open a plot viewer for pngs and svgs, 
![image](https://user-images.githubusercontent.com/2019016/181849200-3deaae8b-a7c9-4ecc-97f8-52caa3b298d2.png)

What type of interaction are you hoping for? And were you thinking of having this for different output types?

**Comment by bdch1234** [comment] 2022-07-29 22:17
Ah, nice. That’s exactly the type of thing I was asking about.

In terms of interactions/output I was mainly hoping for support of Plotly-charts, and the interactions found in those really.

**Comment by amunger** [comment] 2022-07-29 22:53
ok, that makes sense. Should be possible

**Comment by DonJayamanne** [comment] 2022-08-01 21:55
Thanks for the suggestion, closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/1120

**Closed by DonJayamanne** 2022-08-01 21:55 UTC
Labels: plot-viewer, feature-request, triage-needed
