### ISSUE TITLE
Show dicts and other types properly in Jupyter data viewer

### ISSUE THREAD

**Issue by alandema** [microsoft/vscode-jupyter#7252] opened 2021-08-22 23:56 UTC
One of the biggest features of Spyder, is that the Variable explorer can show correctly various types of Python and is able to keep opening then when they are nested.

```
import numpy as np
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
aaa={'a':'string',
     'b':100,
     'c':np.array([1,2,3]),
     'd':{'e':[1,2,3,4]},
     'f':scaler}
```
In Spyder
![image](https://user-images.githubusercontent.com/68517641/130374181-e21cab65-695a-4590-9fbc-5203cc966202.png)
![image](https://user-images.githubusercontent.com/68517641/130374186-0f4f0f3f-158a-42f5-a11b-fcc525ed6fb3.png)

When I try to do the same in VSCode
![image](https://user-images.githubusercontent.com/68517641/130374196-5a61a6e6-c922-4274-b3eb-3e216a6f99dc.png)

**Comment by IanMatthewHuff** [comment] 2021-08-24 19:09
@alandema Thanks for the detailed suggestion. The data viewer is an area we are looking to improve so the feedback is super helpful.

**Comment by alandema** [comment] 2021-08-25 00:04
Hello @IanMatthewHuff. So to be more assertive, The Spyder's  Variable Explorer is the best I've test in many IDEs and other softwares like MATLAB, SciLab and Octave. I would not bother if you just CTRL C / CTRL V it to VSCode.

### Things to be considered:
- Like stated above, the fact that you can continuously open nested variables of nested supported types inside lists and dicts is great.
- They way that VSCode opens the variables now, in tabs, remembers me MATLAB. I prefer the way that Spyder does it, opening in windows, because you can put some variables side by side. But this is not a must have, and the tabs version is good too.
- Also as stated above, the variable explorer should be able to open **properly** more types than it can open now. Especially the common types like dicts.
- Spyder's Variable Explorer can also open exotic types like the MinMaxScaler object, and show the methods or values of the object. Again not an urgency, but is a nice to have.

## An urgency
I don't know if it is a bug or what, but it is very slow to open a big variable, like a numpy array [~100000:~100~10]. It is instant in Spyder, Pycharm and other softwares to open a array of this dimension, but in the VSCode it takes a good minute or two. The same happens with other types of big variables (DataFrames, lists...).

**Comment by DonJayamanne** [comment] 2022-04-25 16:24
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1138

**Closed by DonJayamanne** 2022-04-25 16:24 UTC
Labels: enhancement, data-viewer
