### ISSUE TITLE
Variable Explorer Not showing any variabels

### ISSUE THREAD

**Issue by salmanea** [microsoft/vscode-jupyter#7432] opened 2021-09-07 12:44 UTC
## Environment data

VS Code version: 1.60.0
Jupyter Extension version (available under the Extensions sidebar): v2021.8.2031190714
Python Extension version (available under the Extensions sidebar): v2021.9.1191016588
OS: Windows 10 Enterprise Build: 19042.1165
Python and/or Anaconda version: 3.9.1
Type of virtual environment used: conda
Jupyter server running: Local

## Expected behaviour

Showing variables in the variable viewer of the  interactive console

## Actual behaviour

Doesn't show any variable.
It was OK up until the very latest update.
## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by salmanea** [comment] 2021-09-07 17:05
This is besides the fact that the variable explorer is shown with terminal and not the interactive window. That doesn't make sense. Please take it back to the interactive window.

**Comment by IanMatthewHuff** [comment] 2021-09-08 00:08
@salmanea I'm currently not seeing a repro for this issue. Can you provide some sample code that exhibits this issue?

**Comment by salmanea** [comment] 2021-09-08 14:42
It's strange because it does work now.
However, the other problem is that when you open a variable from the Variable Explorer, it shows the Variable Explorer as empty.

![image](https://user-images.githubusercontent.com/7900672/132531015-14e18564-6e23-445a-8854-7905dc717d69.png)

**Comment by IanMatthewHuff** [comment] 2021-09-08 16:30
@salmanea I believe this behavior is as intended by us, but it is confusing, so maybe we can clean it up some. With the new positioning of the variable viewer it's not tied into any specific document. Instead, it shows the variables for whatever notebook document is currently active. In the example above it's not showing anything as the Data Viewer is open and your active editor context is not in a notebook file or interactive window. However that's confusing, because you did open that data viewer from the interactive console. 

I think we might be able to solve that by tracking what document opened up the Data Viewer and using that as the context for the variable view.

**Comment by IanMatthewHuff** [comment] 2021-09-08 16:31
Actually we have an issue for this already, I'm going to close this issue in favor or #7325 . You can just track that issue to see our work on this.

**Closed by IanMatthewHuff** 2021-09-08 16:31 UTC
Labels: bug, info-needed, needs-triage

**Comment by salmanea** [comment] 2021-09-08 16:52
Thanks @IanMatthewHuff 
I really like what you did. The only near-perfect variable explorer I've seen was in Spyder.
I don't know if VSCode is going to have something similar natively, or through your work on Jupyter extension.
What I know is that if it wasn't for this variable explorer that you made, I and many other people would never switch to VSCode. So thanks a lot :-) !

**Comment by IanMatthewHuff** [comment] 2021-09-08 20:54
@salmanea Yeah, Spyder has a really good variable explorer, know that we are not there yet, but hopefully we'll get to that point.

**Comment by abd-shouman** [comment] 2021-09-12 06:39
@salmanea I thought the data viewer was abolished and now it is just the Jupyter variables. Is the data viewer still available? how can we access it?

**Comment by salmanea** [comment] 2021-09-12 11:42
@abd-shouman I am just referring to the variable explorer that you get when you run something in the interactive window.
![image](https://user-images.githubusercontent.com/7900672/132986010-a6bc18ba-1d0f-45b9-8577-39d87b4e427f.png)

What I think are annoying as I explained above are:
1. The fact that the variables are now shown in the terminal instead of the interactive window itself:

![image](https://user-images.githubusercontent.com/7900672/132986059-66dab8b9-6b2d-48e6-9ed1-3625b715d61a.png)


2. The fact that the variable explorer shows no variables as soon as you open a tab in the interactive window. Look how things change below:

![image](https://user-images.githubusercontent.com/7900672/132986156-ed083d43-9c6e-4016-bb0f-7d2de6f34857.png)

![image](https://user-images.githubusercontent.com/7900672/132986179-dfa977f0-175b-41b2-980d-3694c78fa70f.png)

**Comment by abd-shouman** [comment] 2021-09-12 13:34
@salmanea yea I understand and agree with you, hope it gets addressed soon.
