### ISSUE TITLE
Pandas Dataframe debugging auto update as you step through the code

### ISSUE THREAD

**Issue by Pytrader1x** [microsoft/vscode-jupyter#4469] opened 2021-01-23 13:48 UTC
The January 2021 update is really good in allowing inspection of a pandas df, however it would be great to be able to see the data frame viewer update automatically as you step through the code updating the df.

**Comment by greazer** [comment] 2021-01-28 21:19
Dupe of #1143

**Closed by greazer** 2021-01-28 21:19 UTC
