### ISSUE TITLE
Changes to .env file not detected in jupyter until VS Code is restarted

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1546] opened 2020-02-10 22:15 UTC
Changes to .env files are not detected in the kernel.
We'll need to restart jupyter, restarting the kernel doesn't help.

**Solutions**
* Add command `Restart Jupyter`, so user can restart Jupyter
* Detect changes to .env file and prompt user to restart Jupyter (feels too heavy handed - user loses all of their kernel state)
* Update env vars in kernel when detecting changes to env vars (send a custom request to udpate env vars in kernel)

**Comment by greazer** [comment] 2021-04-22 21:15
Dupe of #1722. Keeping that one as it was entered by an external customer.

**Closed by greazer** 2021-04-22 21:15 UTC
Labels: bug
