### ISSUE TITLE
Save doesn't work

### ISSUE THREAD

**Issue by antonios4GitHub** [microsoft/vscode-jupyter#5457] opened 2021-04-08 18:38 UTC
Issue Type: <b>Bug</b>

It's not the first time that this happens. Both the auto and the manual saving function in Jupyter notebook again didn't work. Auto saving is on. Clicking on the save button has no effect (I always click there before I close the notebook despite the auto save function being active). I opened today the same notebook. All code changes, new cells etc. written yesterday are gone. This has to be fixed. I had this issue 5-6 times in the past 12 months. For some reason, saving doesn't always work. 

Extension version: 2021.5.702919634
VS Code version: Code 1.55.0 (c185983a683d14c396952dd432459097bc7f757f, 2021-03-30T16:01:55.261Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (5.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment] 2021-04-08 20:59
Sorry for this horrible bug. We can't seem to repro in house. I'd recommend switching to VS code [insiders](https://code.visualstudio.com/insiders/) instead. It uses a completely different method for saving/writing to files and should be more robust in this regard.

**Comment by rchiodo** [comment] 2021-04-08 21:02
This wouldn't happen to be in a remote ssh situation would it? That might be causing messages to be dropped.

**Comment by antonios4GitHub** [comment] 2021-04-08 22:56
Thanks for the quick response. No, in all cases the notebook was running locally. Unfortunately, I can't really identify any (reproducible) steps/patterns that might be the reason for this issue. Obviously it's not version specific as I had the similar problem with previous (VS code and Python extension) versions as well. Anyway, please keep this issue in mind for the future. It didn't happen a lot but when it happens, well, it's annoying. From my side, if it happens again and I can relate it with specific steps I did, I'll let you know. Thanks again

**Comment by LaurentIsRunning** [comment] 2021-04-10 20:25
Same issue for me ... Really frustrating :-/ .. The local file remains unchanged.
If there is a hack to fix it once it happens, it would be really appreciated :-)!

**Comment by alterapars** [comment] 2021-05-07 08:39
Same for me, error in vscode is:
Failed to save '<filename>.ipynb': Unable to write file '<filename>.ipynb' (Unknown (FileSystemError): Error: UNKNOWN: unknown error, open '<filename>.ipynb')

**Comment by cpetrov** [comment] 2021-06-23 15:50
Just lost modification to a Jupyter notebook when attempting to close the editor window, possibly when trying to do so before having saved the Jupyter notebook file.

The explorer editor UI now shows an unsaved editor, although no editors are open, and attempting to close the VS Code window shows a "Do you want to save the changes you made to ...ipynb" dialog, which does nothing upon tapping on "Save" (the editor remains open).

![Screenshot 2021-06-23 at 18 44 01](https://user-images.githubusercontent.com/2341769/123127476-9a84e080-d44a-11eb-9dca-34e034b1e5ba.png)

Some other community posts lead me to inspecting the cache at `~/Library/Application\ Support/Code/User/globalStorage/ms-toolsai.jupyter`, but couldn't find the recent changes to my Jupyter notebook there, so it seems the changes to the Jupyter notebook I made are irreversibely lost.

**Comment by midori256** [comment] 2021-06-23 21:37
I'm also experiencing this issue on Debian Bullseye. The biggest problem is that there is no error when saving. It seems like it is saving, but it does not. It seems to happen after leaving the notebook open overnight. A workaround I found is to use "Save As" and then overwrite the notebook file in question. I also lost a few hours of work with this previously.

**Comment by pierre-si** [comment] 2021-07-03 13:43
The same issue happened multiple times to me, no error when saving but it does not save.

**Comment by MartyBeGood** [comment] 2021-07-05 12:57
Happened multiple times to me. Clicking on save and triggering a save through the command palette both start to just fail silently after a while of using it.
If you open the changes through the Git panel, you can see that some of your changes are missing.
If you happen to notice it in time, you have a long and tedious recovery process ahead of you.
If you don't catch it and close VSCode, your changes are gone for good - VSCode doesn't ask you if you want to save your file because it thinks the file was saved.

Only notebooks opened with the notebook editor are affected. Saving text files continues to work without issue.

I tried it from 2021-05-11 until 2021-05-28 on macOS with the then-up-to-date versions of VSCode and the python extension, then gave up and moved to Jupyter Lab for notebook editing.

**Comment by janhurst** [comment] 2021-07-08 14:39
my team and I are experiencing this symptom. a notebook editor gets into a state where it thinks it has saved but further saves and file modifications are not actually written out to disk.

it has been very hard to consistently reproduce. could someone give guidance as to what/where to capture log info to help diagnose further?

it appears to happen more often when notebooks have large amounts of output in them, and/or when system memory is running low

**Comment by rchiodo** [comment] 2021-07-12 16:38
The 'jupyter' output tab has all of our logging information. That would be useful to see when the error occurs. Hopefully it has some indication of what went wrong.

You would likely not have this problem if you switched to the [new editor](https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code#enabling-the-new-experience) though. It uses a completely different method for saving files.

**Comment by rchiodo** [comment] 2021-08-31 16:39
Closing as no new cases since switching to new editor.

**Closed by rchiodo** 2021-08-31 16:39 UTC
Labels: bug, notebook-serialization-save-load, needs-inspection
