### ISSUE TITLE
Kernel crashed when using RandomForestRegression module from sklearn.ensemble

### ISSUE THREAD

**Issue by Hoyuri** [microsoft/vscode-jupyter#10057] opened 2022-05-18 01:49 UTC
## Code

- X_train.shape = (1118287, 176)
- y_train.shape = (1118287, 1)

```
bagging_fraction = 0.3
n_estimators = 10

forest = RandomForestRegressor(n_jobs=-1, max_features='sqrt',
                random_state=0, max_samples=bagging_fraction, max_depth=7,
                verbose=0,n_estimators=n_estimators)
forest.fit(X_train.values, y_train.values)
```

## Crash report

Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.

## Jupyter Log

```
error 9:44:22.642: Disposing session as kernel process died ExitCode: 3221225725, Reason: Unable to load extension: pydevd_plugins.extensions.types.pydevd_plugin_pandas_types
xxxxxxx_mypath\temp\lib\site-packages\traitlets\traitlets.py:2389: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
xxxxxxx_mypath\temp\lib\site-packages\traitlets\traitlets.py:2343: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use '72a003ed-29e6-4f50-8c7f-d98eca049a73' instead of 'b"72a003ed-29e6-4f50-8c7f-d98eca049a73"'.
  warn(

info 9:44:22.643: Dispose Kernel process
info 9:44:22.643: kill daemon
error 9:44:22.643: Raw kernel process exited code: 3221225725
error 9:44:22.645: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\win10\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:1322339)
	at c:\Users\win10\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:1341391
	at Map.forEach (<anonymous>)
	at v._clearKernelState (c:\Users\win10\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:1341376)
	at v.dispose (c:\Users\win10\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:1334858)
	at c:\Users\win10\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:537744
	at t.swallowExceptions (c:\Users\win10\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:920640)
	at u.dispose (c:\Users\win10\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:537722)
	at t.RawSession.dispose (c:\Users\win10\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:541401)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 9:44:22.645: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
info 9:44:22.646: Cancel all remaining cells true || Error || undefined
info 9:44:22.646: Cancel pending cells
info 9:44:22.646: Cell 26 executed with state Error
```

## Question

I have tried the model on partial data, i.e. the first 100 rows of data, and there is no bug in jupyter-notebook. It seems to be the depreciation of dependency on traitlets. But I have tried to downgrade it, like version==4.7, but the bug still exists. Future downgrade of traitlets makes the jupyter-notebook stop at opening. So is there any way to fix that? Thanks in advance!

**Comment by Hoyuri** [comment] 2022-05-18 03:36
# Reproduce
```python
import os
import pandas as pd
import numpy as np
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from lightgbm import LGBMRegressor
from boruta import BorutaPy
import warnings; warnings.filterwarnings('ignore')
import time
from sklearn.ensemble import RandomForestRegressor

from sklearn.datasets import make_regression
X, y = make_regression(n_features=176, n_informative=80,
n_samples=1118287,random_state=0, shuffle=False)

df_out = pd.DataFrame()
for bagging_fraction in [0.1,0.3,0.5,0.7,0.9,1]: # full parameter tuning
    for n_estimators in [10,25,50,75,100]:
        start_time = time.time()
        print("Start iteration at bagging_fraction={}, n_estimators={}\n".format(bagging_fraction,n_estimators))

        forest = RandomForestRegressor(n_jobs=-1, max_features='sqrt',
                        random_state=0, max_samples=bagging_fraction, max_depth=7,
                        verbose=0,n_estimators=n_estimators)
        feat_selector = BorutaPy(forest, n_estimators=n_estimators, verbose=0)
        selected_X = feat_selector.fit_transform(X, y, weak=True)

        current_time = time.time()
        elapsed_time = current_time - start_time

        temp = {
            "bagging_fraction":bagging_fraction,
            "n_estimators":n_estimators,
            "num_iter":feat_selector._iter,
            "num_rej_ft":np.sum(feat_selector.dec_reg==-1),
            "num_acpt_ft":selected_X.shape[1],
            "timing_sec":str(int(elapsed_time))
        }
        if df_out.shape[0] == 0:
            df_out = pd.DataFrame({k: [v] for k, v in temp.items()})
        else:
            df_out = df_out.append(temp, ignore_index=True)
        df_out.to_csv("boruta_tuning/output_boruta_sklearnrf_syndata.csv",index=None)
```

Output:

```
.........

Start iteration at bagging_fraction=0.5, n_estimators=25

Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
```

Jupyter [log] is the same as in the issue

**Comment by rchiodo** [comment] 2022-05-18 16:30
Thanks for the issue.

I believe this is the root cause here:

```
Unable to load extension: pydevd_plugins.extensions.types.pydevd_plugin_pandas_types
```

I'm not sure what is including that in the list of packages you have but that is causing the kernel to crash as far as I can tell.

**Comment by rchiodo** [comment] 2022-05-18 16:56
Not sure if this has any bearing on the problem but attempting this on my own machine it consumes a huge amount of CPU and memory. Might be you ran out of memory and that caused an extension to not load.

**Comment by Hoyuri** [comment] 2022-05-19 09:45
I have tried on different datasets. It seems that this issue is generated from the usage of sklearn.RandomForestRegressor. I may submit another issue there. And a downgrade to, say, python version=3.7.0 won't cause any trouble.

**Comment by DonJayamanne** [comment] 2022-05-19 20:18
Closing as per discussions.

**Closed by DonJayamanne** 2022-05-19 20:18 UTC
Labels: bug, triage-needed

**Comment by adampl** [comment] 2022-06-01 12:25
@Hoyuri I'm getting the same error on PyCharm:
`Unable to load extension: pydevd_plugins.extensions.types.pydevd_plugin_pandas_types`
What should I do to avoid it?

**Comment by hrmello** [comment] 2022-06-06 19:10
Same issue when using the transformers library from HuggingFace

**Comment by adampl** [comment] 2022-06-07 22:24
I had to downgrade pydev back to the previous version.

**Comment by espoirMur** [comment] 2022-06-13 17:07
Same issue here.. while running this code

```
for index, row in enumerate(data.head(2).loc[:, ["content"]].values):
    row.tofile(TEXT_DATA_FOLDER.joinpath(f"{index}.txt"), sep=",", format="%s")
```

**Comment by SamCox822** [comment] 2022-11-16 20:01
Has anybody found a solution to this?

**Comment by aurelienfalco** [comment] 2022-11-17 16:18
> Has anybody found a solution to this?

same here. Anybody?

**Comment by rafikoham** [comment] 2022-12-28 15:28
Try to look here for more details, (depending on your Kernel crash's causes and errors : https://github.com/microsoft/vscode-jupyter/wiki/Kernel-crashes  ) 

In my case, it happens when I try to train a Unet model from segmentation_models_pytorch (smp) library.

**Comment by goldenlamp99** [comment] 2023-01-06 02:02
> I had to downgrade pydev back to the previous version.

Can you tell me how to rectify this issue ? This warning or error comes always I start spyder.

**Comment by goldenlamp99** [comment] 2023-01-06 02:05
ImportError: cannot import name 'PANDAS_MAX_ROWS' from '_pydevd_bundle.pydevd_constants' (C:\Anaconda3\envs\python37\lib\site-packages\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_constants.py). This error is coming while importing that in spyder. How to rectify this issue?

**Comment by adampl** [comment] 2023-01-06 02:35
I'm not using Spyder, and I don't remember what it was about, but at the time I've set this in my Python requirements: `pydevd==2.7.0`

However, we're using Docker, so it's easy to control dependencies. If it doesn't help and you don't use containers, try to disable injection of the built-in Pydev package in Spyder or uninstall it.
