### ISSUE TITLE
Run Selection/Line in Interactive Window starts window but does not execute

### ISSUE THREAD

**Issue by clayms** [microsoft/vscode-jupyter#7329] opened 2021-08-28 12:40 UTC
Issue Type: <b>Bug</b>

Likely related to https://github.com/microsoft/vscode-jupyter/issues/7322

Recent update broke `Jupyter: Run Selection/Line in Interactive Window` where using <kbd>Shift</kbd>+<kbd>Enter</kbd> will start an Interactive Window, but the code will not execute.  Try multiple times and nothing at all will happen in the Interactive Window.  However, after running some code directly from the Interactive Terminal, all of the attempts to use <kbd>Shift</kbd>+<kbd>Enter</kbd> to `Run Selection/Line` show up ***after*** the code that was run directly in the Interactive Window.  The *`connecting to kernel...`* message and subsequent python kernel information does not display until after something is ran directly in the Interactive Window.

It should also be noted that this is only happens the first time an Interactive Window is started in a VS Code instance.  In the same VS Code instance, closing the Interactive Window, then using <kbd>Shift</kbd>+<kbd>Enter</kbd> again to `Run Selection/Line` works as expected.

Extension version: 2021.8.1236758218
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:56:46.957Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.85GB free)|
|Process Argv|--crash-reporter-id 1e88d7ed-dfc2-42ed-b5d3-970568cb872e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
bridge0723:30353136
vsdyn478:30356813
vscus224cf:30358040
vssid140:30358036

```

</details>

**Comment by DavidKutu** [comment] 2021-08-30 18:50
Thanks for the issue @clayms. Unfortunately, I can't reproduce this in stable or insiders. It might get fixed on our upcoming release.

I see that you've uploaded your logs on the other issue, so maybe we can use those.

**Comment by greazer** [comment] 2021-08-30 20:20
@clayms, like the related issue you opened please reopen this if it still repros in v1.60 or the latest VS Code insiders build.

**Closed by greazer** 2021-08-30 20:20 UTC
Labels: bug, interactive-window, needs-triage
