### ISSUE TITLE
Jupyter Notebook cells hang forever in VSCode

### ISSUE THREAD

**Issue by marcoBmota8** [microsoft/vscode-jupyter#14716] opened 2023-11-14 09:14 UTC
## Update

VSCode jupyter notebooks work locally. It is an issue on the remote server.

## Environment data

-   VS Code version: 1.84.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.10.1003070148
-   Python Extension version (available under the Extensions sidebar): v2023.20.0
-   OS (Windows | Mac | Linux distro) and version: laptop is Mac, remote machine is Linux
-   Python and/or Anaconda version: 
-   Type of virtual environment used: conda
-   Jupyter server running: Remote through SSH VSCode extension

## Expected behaviour
Cells NOT running. They were running normally and suddenly an interactive notebook started to hang. Then normal `.ipynb` files were also hanging. There was no update of any sort on my end. Might it be something on VSCode end?

I tried many things from related posts:
-Disabling `pylance`.
-Forcing the reinstalling of `notebook`, `jupyter` and `ipykernel`.

## Actual behaviour
Cells running for both interactive notebooks and file-based notebooks.

## Logs (output jupyter)
<details>
  <summary>Show Logs</summary>
  
```
Visual Studio Code (1.84.2, ssh-remote, desktop)
Jupyter Extension Version: 2023.10.1003070148.
Python Extension Version: 2023.20.0.
Platform: linux (x64).
Workspace folder /home/barbem4, Home = /home/barbem4
02:51:57.010 [debug] Get Custom Env Variables, Class name = Ul (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
02:51:57.012 [info] Start refreshing Kernel Picker (1699951917012)
02:51:57.031 [info] Using Pylance
02:52:00.292 [debug] Get Custom Env Variables, Class name = Ul, completed in 3282ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
02:52:00.292 [debug] Jupyter Paths /kernels: 
02:52:00.517 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
02:52:00.561 [debug] Search for KernelSpecs in Interpreter ~/.conda/envs/praxis_env/bin/python
02:52:00.562 [debug] Finding Global Python KernelSpecs
02:52:00.605 [debug] Search for KernelSpecs in Interpreter /bin/python
02:52:00.605 [debug] Search for KernelSpecs in Interpreter /bin/python3.6
02:52:00.606 [debug] Search for KernelSpecs in Interpreter /usr/bin/python
02:52:00.607 [debug] Search for KernelSpecs in Interpreter /usr/bin/python3.6
02:52:00.609 [debug] Search for KernelSpecs in Interpreter /opt/miniconda/bin/python
02:52:00.610 [debug] Search for KernelSpecs in Interpreter ~/sandbox/bin/python
02:52:00.611 [debug] Full interpreter list is length: 7, /bin/python::Unknown:/bin/python, /bin/python3.6::Unknown:/bin/python3.6, /usr/bin/python::Unknown:/usr/bin/python, /usr/bin/python3.6::Unknown:/usr/bin/python3.6, ~/.conda/envs/praxis_env/bin/python:praxis_env:Conda:~/.conda/envs/praxis_env/bin/python, /opt/miniconda/bin/python:base:Conda:/opt/miniconda/bin/python, ~/sandbox/bin/python:sandbox:Venv:~/sandbox/bin/python
02:52:00.615 [debug] Getting activated env variables, Class name = $a (started execution), Arg 1: "~", Arg 2: "~/.conda/envs/praxis_env/bin/python", Arg 3: undefined
02:52:00.616 [debug] Get Custom Env Variables, Class name = Ul (started execution), Arg 1: "~", Arg 2: "RunPythonCode"
02:52:00.616 [debug] Get Custom Env Variables, Class name = Ul, completed in 0ms, has a truthy return value, Arg 1: "~", Arg 2: "RunPythonCode"
02:52:00.784 [debug] Kernels for interpreter /bin/python are .jvsc74a57bd0e7370f93d1d0cde622a1f8e1c04877d8463912d04d973331ad4851f04de6915a./bin/python./bin/python.-m#ipykernel_launcher
02:52:00.786 [debug] Kernels for interpreter /bin/python3.6 are .jvsc74a57bd0db0f6cbdde3eb805f0a229b988d6bd72d452c42e640dd9958b4355934ec01bf5./bin/python3.6./bin/python3.6.-m#ipykernel_launcher
02:52:00.786 [debug] Kernels for interpreter /usr/bin/python are .jvsc74a57bd0767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90./usr/bin/python./usr/bin/python.-m#ipykernel_launcher
02:52:00.786 [debug] Kernels for interpreter /usr/bin/python3.6 are .jvsc74a57bd030295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf./usr/bin/python3.6./usr/bin/python3.6.-m#ipykernel_launcher
02:52:00.787 [debug] Kernels for interpreter /opt/miniconda/bin/python are .jvsc74a57bd04c2b8563932708ac4f64e3bc4797ea8eb43fc7530baa7f01daadf5b46d7b1fd4./opt/miniconda/python./opt/miniconda/python.-m#ipykernel_launcher
02:52:00.822 [debug] Loading kernelspec from ~/.local/share/jupyter/kernels/python3/kernel.json 
02:52:00.822 [debug] Loading kernelspec from ~/.conda/envs/praxis_env/share/jupyter/kernels/python3/kernel.json for ~/.conda/envs/praxis_env/bin/python
02:52:00.823 [debug] Loading kernelspec from ~/sandbox/share/jupyter/kernels/python3/kernel.json for ~/sandbox/bin/python
02:52:00.828 [debug] Kernel Specs found in interpreter ~/.conda/envs/praxis_env/bin/python are [{"specFile":"~/.conda/envs/praxis_env/share/jupyter/kernels/python3/kernel.json","interpreterPath":"~/.conda/envs/praxis_env/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"pythonjvsc74a57bd0af59e808e2bb2d49f2aad3fcaa4e3b4707b54f609965d9d8e3585c2a4131334f","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3 (ipykernel)","metadata":{"debugger":true,"vscode":{"originalSpecFile":"~/.conda/envs/praxis_env/share/jupyter/kernels/python3/kernel.json","originalDisplayName":"Python 3 (ipykernel)"}}}]
02:52:00.828 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'pythonjvsc74a57bd0af59e808e2bb2d49f2aad3fcaa4e3b4707b54f609965d9d8e3585c2a4131334f', /python for interpreter ~/.conda/envs/praxis_env/bin/python and spec ~/.conda/envs/praxis_env/share/jupyter/kernels/python3/kernel.json
02:52:00.828 [debug] Kernels for interpreter ~/.conda/envs/praxis_env/bin/python are .jvsc74a57bd0af59e808e2bb2d49f2aad3fcaa4e3b4707b54f609965d9d8e3585c2a4131334f.~/.conda/envs/praxis_env/python.~/.conda/envs/praxis_env/python.-m#ipykernel_launcher
02:52:00.829 [debug] Kernel Specs found in interpreter ~/sandbox/bin/python are [{"specFile":"~/sandbox/share/jupyter/kernels/python3/kernel.json","interpreterPath":"~/sandbox/bin/python","isRegisteredByVSC":"registeredByNewVersionOfExt","name":"pythonjvsc74a57bd0b0e92fd24cd1235dca8a7d32022db8bc6b9211cbdc26753cfb27ff825bde661f","argv":["python","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"python","display_name":"Python 3 (ipykernel)","metadata":{"debugger":true,"vscode":{"originalSpecFile":"~/sandbox/share/jupyter/kernels/python3/kernel.json","originalDisplayName":"Python 3 (ipykernel)"}}}]
02:52:00.830 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'pythonjvsc74a57bd0b0e92fd24cd1235dca8a7d32022db8bc6b9211cbdc26753cfb27ff825bde661f', /python for interpreter ~/sandbox/bin/python and spec ~/sandbox/share/jupyter/kernels/python3/kernel.json
02:52:00.830 [debug] Kernels for interpreter ~/sandbox/bin/python are .jvsc74a57bd0b0e92fd24cd1235dca8a7d32022db8bc6b9211cbdc26753cfb27ff825bde661f.~/sandbox/python.~/sandbox/python.-m#ipykernel_launcher
02:52:04.360 [info] Start refreshing Interpreter Kernel Picker
02:52:04.372 [debug] KernelProvider switched kernel to id = .jvsc74a57bd0af59e808e2bb2d49f2aad3fcaa4e3b4707b54f609965d9d8e3585c2a4131334f.~/.conda/envs/praxis_env/python.~/.conda/envs/praxis_env/python.-m#ipykernel_launcher
02:52:04.373 [debug] start the kernel, options.disableUI=true for ~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb
02:52:04.400 [debug] Controller selection change completed
02:52:04.404 [debug] Preferred Remote kernel for ~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb is undefined
02:52:04.444 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0af59e808e2bb2d49f2aad3fcaa4e3b4707b54f609965d9d8e3585c2a4131334f.~/.conda/envs/praxis_env/python.~/.conda/envs/praxis_env/python.-m#ipykernel_launcher  (Python Path: ~/.conda/envs/praxis_env/bin/python, Conda, praxis_env, 3.9.18) for '~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb' (disableUI=true)
02:52:04.445 [debug] Creating raw notebook for resource '~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb'
02:52:04.476 [debug] Kernel Launcher. launch, Class name = Fv (started execution), Arg 1: "~/.conda/envs/praxis_env/python.~/.conda/envs/praxis_env/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb", Arg 4: "~/projects/Initial SLE dataset/Linear models SLE/Experiments", Arg 5: ""
02:52:04.492 [debug] Getting activated env variables, Class name = $a (started execution), Arg 1: "~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb", Arg 2: "~/.conda/envs/praxis_env/bin/python", Arg 3: undefined
02:52:04.492 [debug] Get Custom Env Variables, Class name = Ul (started execution), Arg 1: "~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb", Arg 2: "RunPythonCode"
02:52:04.493 [debug] Get Custom Env Variables, Class name = Ul, completed in 1ms, has a truthy return value, Arg 1: "~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb", Arg 2: "RunPythonCode"
02:52:04.579 [debug] Launching kernel in kernelProcess.ts, Class name = Lv (started execution), Arg 1: "~/projects/Initial SLE dataset/Linear models SLE/Experiments", Arg 2: ""
02:52:04.637 [debug] Initialize notebook communications for editor ~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb
02:52:04.637 [debug] Resolving notebook UI Comms (resolve) for ~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb
02:52:04.638 [debug] initialize CommonMessageCoordinator
02:52:04.640 [debug] Registering commtarget jupyter.widget
02:52:04.640 [debug] IPyWidgetMessageDispatcher.initialize
02:52:04.641 [debug] Attempting to determine version of IPyWidgets
02:52:04.649 [debug] Waiting for IPyWidgets version
02:52:04.649 [debug] Waiting for IPyWidgets version promise
02:52:04.701 [debug] Attempting to determine version of IPyWidgets
02:52:04.702 [debug] Waiting for IPyWidgets version
02:52:04.702 [debug] Waiting for IPyWidgets version promise
02:52:05.012 [debug] Python API env change detected, update => '/usr/bin/python3.6m'
02:52:05.033 [debug] Python API env change detected, update => '/usr/bin/python3.6m'
02:52:05.041 [debug] Search for KernelSpecs in Interpreter /usr/bin/python3.6m
02:52:05.044 [debug] Full interpreter list is length: 7, /bin/python::Unknown:/bin/python, /bin/python3.6::Unknown:/bin/python3.6, /usr/bin/python::Unknown:/usr/bin/python, /usr/bin/python3.6m::Unknown:/usr/bin/python3.6m, ~/.conda/envs/praxis_env/bin/python:praxis_env:Conda:~/.conda/envs/praxis_env/bin/python, /opt/miniconda/bin/python:base:Conda:/opt/miniconda/bin/python, ~/sandbox/bin/python:sandbox:Venv:~/sandbox/bin/python
02:52:05.051 [debug] Kernels for interpreter /usr/bin/python3.6m are .jvsc74a57bd0fdb70176b9f68a63fad060439e1eecc9dfd60edecc2378a4464637b9f14b2c93./usr/bin/python3.6m./usr/bin/python3.6m.-m#ipykernel_launcher
02:52:06.315 [debug] Conda file returned by Python Extension is conda
02:52:06.970 [debug] Python API env change detected, update => '/usr/bin/python3.6m'
02:52:06.991 [debug] Full interpreter list is length: 7, /bin/python::Unknown:/bin/python, /bin/python3.6::Unknown:/bin/python3.6, /usr/bin/python::Unknown:/usr/bin/python, /usr/bin/python3.6m::Unknown:/usr/bin/python3.6m, ~/.conda/envs/praxis_env/bin/python:praxis_env:Conda:~/.conda/envs/praxis_env/bin/python, /opt/miniconda/bin/python:base:Conda:/opt/miniconda/bin/python, ~/sandbox/bin/python:sandbox:Venv:~/sandbox/bin/python
02:52:06.991 [debug] Refreshed Environments
02:52:07.550 [debug] Got env vars with python ~/.conda/envs/praxis_env/bin/python, with env var count 51 in 3058ms. 
    PATH value is ~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:~/local/bin:~/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:/opt/python-3.9.12/bin:~/.conda/envs/bin:~/.conda/envs/praxis_env/bin:/opt/miniconda/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/nz/bin:/usr/local/nz/bin64:/usr/local/texlive/2022/bin/x86_64-linux:/usr/local/nz/bin:/usr/local/nz/bin64:~/.fzf/bin and 
    Path value is undefined
02:52:07.550 [debug] Prepend PATH with python bin for ~/.conda/envs/praxis_env/bin/python, 
    PATH value is ~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:~/local/bin:~/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:/opt/python-3.9.12/bin:~/.conda/envs/bin:~/.conda/envs/praxis_env/bin:/opt/miniconda/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/nz/bin:/usr/local/nz/bin64:/usr/local/texlive/2022/bin/x86_64-linux:/usr/local/nz/bin:/usr/local/nz/bin64:~/.fzf/bin and 
    Path value is undefined
02:52:07.551 [debug] Activated Env Variables for ~/.conda/envs/praxis_env/bin/python, 
    PATH value is ~/.conda/envs/praxis_env/bin:~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:~/local/bin:~/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:/opt/python-3.9.12/bin:~/.conda/envs/bin:~/.conda/envs/praxis_env/bin:/opt/miniconda/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/nz/bin:/usr/local/nz/bin64:/usr/local/texlive/2022/bin/x86_64-linux:/usr/local/nz/bin:/usr/local/nz/bin64:~/.fzf/bin and 
    Path value is undefined
02:52:07.551 [debug] Getting activated env variables, Class name = $a, completed in 3059ms, has a truthy return value, Arg 1: "~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb", Arg 2: "~/.conda/envs/praxis_env/bin/python", Arg 3: undefined
02:52:07.576 [info] Process Execution: ~/.conda/envs/praxis_env/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
02:52:07.576 [debug] Kernel Env Variables for ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.10.1003070148-linux-x64/temp/jupyter/kernels/pythonjvsc74a57bd0af59e808e2bb2d49f2aad3fcaa4e3b4707b54f609965d9d8e3585c2a4131334f/kernel.json, PATH value is ~/.conda/envs/praxis_env/bin:~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:~/local/bin:~/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:/opt/python-3.9.12/bin:~/.conda/envs/bin:~/.conda/envs/praxis_env/bin:/opt/miniconda/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/nz/bin:/usr/local/nz/bin64:/usr/local/texlive/2022/bin/x86_64-linux:/usr/local/nz/bin:/usr/local/nz/bin64:~/.fzf/bin
02:52:07.597 [info] Process Execution: ~/.conda/envs/praxis_env/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"d8694d87-d19d-4804-ae60-ce12c4c5aae3" --shell=9007 --transport="tcp" --iopub=9009 --f=~/.local/share/jupyter/runtime/kernel-v2-21257XLJ43cyNnIpN.json
    > cwd: ~/projects/Initial SLE dataset/Linear models SLE/Experiments
02:52:07.598 [debug] Launching kernel in kernelProcess.ts, Class name = Lv, completed in 3019ms, has a truthy return value, Arg 1: "~/projects/Initial SLE dataset/Linear models SLE/Experiments", Arg 2: ""
02:52:07.612 [debug] Got env vars with python ~/.conda/envs/praxis_env/bin/python, with env var count 51 in 6996ms. 
    PATH value is ~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:~/local/bin:~/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:/opt/python-3.9.12/bin:~/.conda/envs/bin:~/.conda/envs/praxis_env/bin:/opt/miniconda/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/nz/bin:/usr/local/nz/bin64:/usr/local/texlive/2022/bin/x86_64-linux:/usr/local/nz/bin:/usr/local/nz/bin64:~/.fzf/bin and 
    Path value is undefined
02:52:07.612 [debug] Prepend PATH with python bin for ~/.conda/envs/praxis_env/bin/python, 
    PATH value is ~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:~/local/bin:~/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:/opt/python-3.9.12/bin:~/.conda/envs/bin:~/.conda/envs/praxis_env/bin:/opt/miniconda/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/nz/bin:/usr/local/nz/bin64:/usr/local/texlive/2022/bin/x86_64-linux:/usr/local/nz/bin:/usr/local/nz/bin64:~/.fzf/bin and 
    Path value is undefined
02:52:07.612 [debug] Activated Env Variables for ~/.conda/envs/praxis_env/bin/python, 
    PATH value is ~/.conda/envs/praxis_env/bin:~/.vscode-server/bin/1a5daa3a0231a0fbba4f14db7ec463cf99d7768e/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:~/local/bin:~/.vscode-server/bin/b3e4e68a0bc097f0ae7907b217c1119af9e03435/bin/remote-cli:~/.conda/envs/bin:/opt/python-3.9.12/bin:/opt/python-3.9.12/bin:~/.conda/envs/bin:~/.conda/envs/praxis_env/bin:/opt/miniconda/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/nz/bin:/usr/local/nz/bin64:/usr/local/texlive/2022/bin/x86_64-linux:/usr/local/nz/bin:/usr/local/nz/bin64:~/.fzf/bin and 
    Path value is undefined
02:52:07.612 [debug] Getting activated env variables, Class name = $a, completed in 6997ms, has a truthy return value, Arg 1: "~", Arg 2: "~/.conda/envs/praxis_env/bin/python", Arg 3: undefined
02:52:07.639 [info] Process Execution: ~/.conda/envs/praxis_env/bin/python -m pip list
02:52:08.216 [info] ipykernel version & path 6.26.0, ~/.conda/envs/praxis_env/lib/python3.9/site-packages/ipykernel/__init__.py for ~/.conda/envs/praxis_env/bin/python
02:52:09.554 [debug] KernelProcess output: NOTE: When using the ipython kernel entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-21257XLJ43cyNnIpN.json

02:52:09.555 [debug] Kernel Output: To connect another client to this kernel, use: --existing kernel-v2-21257XLJ43cyNnIpN.json

02:52:09.800 [debug] Kernel Launcher. launch, Class name = Fv, completed in 5324ms, has a truthy return value, Arg 1: "~/.conda/envs/praxis_env/python.~/.conda/envs/praxis_env/python.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb", Arg 4: "~/projects/Initial SLE dataset/Linear models SLE/Experiments", Arg 5: ""
02:52:09.812 [debug] Waiting for Raw Session to be ready in postStartRawSession
02:52:09.812 [debug] Waiting for Raw session to be ready, currently connected
02:52:09.812 [debug] Raw session connected
02:52:09.812 [debug] Waiting for Raw session to be ready for 30s
02:52:09.813 [debug] Waited for Raw session to be ready & got connected
02:52:09.813 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
02:52:09.813 [debug] Kernel status before requesting kernel info and after ready is unknown
02:52:09.813 [debug] Sending request for kernelInfo
02:52:11.313 [debug] Did not get a response for requestKernelInfo
02:52:11.313 [debug] Sending request for kernelInfo
02:52:12.093 [info] End refreshing Kernel Picker (1699951917012)
02:52:12.814 [debug] Did not get a response for requestKernelInfo
02:52:12.814 [warn] Didn't get response for requestKernelInfo after 3001ms.
02:52:12.819 [debug] Begin sendTelemetryForPythonKernelExecutable
02:52:12.820 [debug] Executing silently Code (unknown) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
02:52:24.563 [info] Handle Execution of Cells 0 for ~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb
02:52:24.567 [debug] start the kernel, options.disableUI=false for ~/projects/Initial SLE dataset/Linear models SLE/Experiments/Check_files.ipynb
```
</details>

**Comment by marcoBmota8** [comment] 2023-11-14 09:16
May be related to #14519

**Comment by marcoBmota8** [comment] 2023-11-14 13:11
I just tried the same .ipynb file with the same environment on a different ssh machine  (both are mounted on the same NSF system) and it works fine. 

The difference in the logs seems to stem from the `requestKernelInfo` not succeeding. 

Non working machine:
`06:56:53.583 [debug] Did not get a response for requestKernelInfo`
`06:56:53.583 [debug] Sending request for kernelInfo`
`06:56:55.084 [debug] Did not get a response for requestKernelInfo`
`06:56:55.084 [warn] Didn't get response for requestKernelInfo after 3001ms.`

Working machine:
`06:57:36.162 [debug] Sending request for kernelInfo`
`06:57:36.468 [debug] Got response for requestKernelInfo`

Why is the resquest not getting a response?

**Comment by DonJayamanne** [comment] 2023-11-14 19:20
Sorry you are running into this issue and thank you for filing this issue
I will have a look and see what's going on here.

**Comment by DonJayamanne** [comment] 2023-11-15 21:01
Closing as a duplicate of #14519

**Closed by DonJayamanne** 2023-11-15 21:01 UTC
Labels: bug
