### ISSUE TITLE
Code cells do not run

### ISSUE THREAD

**Issue by peterschmidt85** [microsoft/vscode-jupyter#4807] opened 2021-02-13 15:59 UTC
## Environment data

-   VS Code version: 1.54.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.502429796
-   OS (Windows | Mac | Linux distro) and version: Mac 11.1
-   Python and/or Anaconda version: 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Python code cells are executed OK

## Actual behaviour

Code cells take infinite time to execute - no output is shown

## Steps to reproduce:

1. Open the IDE
2. Make sure the Python environment is selected properly - Conda's base environment
3. Run a new notebook with a Python code cell
4. Run this cell

<img width="1680" alt="Screenshot 2021-02-13 at 16 51 51" src="https://user-images.githubusercontent.com/54148038/107854456-4292f900-6e1c-11eb-8506-8ef8a0c5e4d4.png">

## Logs

User belongs to experiment group 'NativeNotebookEditor'
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import jupyter"
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import notebook"
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py jupyter kernelspec --version
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py -c "import ipykernel"
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v
Started kernel Python 3.7.6 64-bit ('base': conda)
> ~/opt/anaconda3/bin/python ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2020.12.414227025/pythonFiles/pyvsc-run-isolated.py vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_launcher_daemon -v

**Comment by chenvictor** [comment] 2021-02-14 07:48
Seems to be affecting Julia as well...

**Comment by taldcroft** [comment] 2021-02-14 18:55
I'm seeing exactly the same thing with a nearly identical environment. Some additional notes:
- This ('NativeNotebookEditor' with Code-Insiders on Mac) was working for me about a week ago .
- My conda environment is working fine with the non-native Jupyter extension with Code (non-Insiders).
- This is a recent clean install of Code-insiders.

**Comment by joyceerhl** [comment] 2021-02-14 20:34
Hi all, so sorry for the trouble. This is happening because there was a breaking change in the VS Code API in VS Code Insiders late last week, and the Jupyter extension team is still working on publishing a compatible update to the VS Code marketplace for insiders users. Only VS Code Insiders users should be impacted by this, if you are seeing the same behavior on VS Code stable please file a separate issue. We should have an update early next week due to the long weekend but in the meantime you should be able to work around this by downgrading VS Code Insiders. Again, very sorry about the trouble caused and we appreciate your patience.

**Comment by peterschmidt85** [comment] 2021-02-14 21:15
> downgrading VS Code Insiders

@joyceerhl How can I do it?

**Comment by joyceerhl** [comment] 2021-02-16 04:15
@peterschmidt85 Downgrading for Windows: https://github.com/microsoft/vscode-jupyter/issues/4796#issuecomment-779266138 
Downgrading for Apple Silicon: https://github.com/microsoft/vscode-jupyter/issues/4796#issuecomment-779374887
Based on the above it seems like the non-silicon macOS download link is https://vscode-update.azurewebsites.net/1.53.0-insider/darwin/insider. Please let us know if that doesn't work.

**Comment by greazer** [comment] 2021-02-16 23:03
Dupe of #4796

**Closed by greazer** 2021-02-16 23:03 UTC
Labels: bug, info-needed
