### ISSUE TITLE
Running Jupyter Notebooks with Julia Kernel on M1 Mac

### ISSUE THREAD

**Issue by daler6** [microsoft/vscode-jupyter#7214] opened 2021-08-20 15:38 UTC
## Environment data

-   VS Code version: 1.59
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): 2021.8.1147840270
-   OS (Windows | Mac | Linux distro) and version: macOS Big Sur 11.5.2
-   Jupyter server running: Local | Remote | N/A
-   Julia extension: 1.3.30, with Julia:Notebook Controller option checked

## Expected behaviour

When I open an existing or new Jupyter notebook and select the Julia kernel, everything should work fine.

## Actual behaviour

I am told that I need to install the Python extension for this to work. Once I install that extension, it does work.

This seems to only happen on my new M1 MacMini. On my MacBookPro with an Intel chip running the same setup, I do not need to install the Python extension to run Jupyter Notebooks.

**Comment by DonJayamanne** [comment] 2021-08-20 15:42
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5206

**Closed by DonJayamanne** 2021-08-20 15:42 UTC
Labels: bug, needs-triage
