### ISSUE TITLE
tensorboard integration failed to start

### ISSUE THREAD

**Issue by yongshangli** [microsoft/vscode-jupyter#9467] opened 2022-03-24 08:26 UTC
vscode notification: We failed to start a TensorBoard session due to the following error: Timed out after 60 seconds waiting for TensorBoard to launch.
In the browser is OK, the tensorboard integration in the vscode is not. I tried new conda virtual env, but no use.
I don't know why.
![2022-03-24 160004](https://user-images.githubusercontent.com/59642489/159873504-ac708b11-23f6-43ff-a26a-13410d65a06b.png)

**Comment by IanMatthewHuff** [comment] 2022-03-24 18:24
@yongshangli Thanks for filing this issue. First step here is if you could please change the VS Code setting `python.logging.level` to 'debug', rerun the scenario, and copy out everything in the Output -> Python section. That has all our output tracing which can help us to debug this more easily.

**Comment by Saltsmart** [comment] 2022-05-28 11:58
> This happened to me too but I managed to resolve it. Mine was somehow a dependancy issue (perhaps because I am using both conda and pip for my environment).
> 
> Firstly, try run tensorboard from the command line (even if you're on Remote SSH): `tensorboard --logdir LOGDIR`. I was shown the following error: `pkg_resources.DistributionNotFound: The 'google-auth<2,>=1.6.3' distribution was not found and is required by tensorboard`. I simply did a `pip install google-auth==1.6.3` and tensorboard was then working both via command line and via the integration.

I've also met this problem. `tensorboard --logdir LOGDIR` command gives output as below:
```
TensorFlow installation not found - running with reduced feature set.
xxxxx hh:mm:ss.xxxxxx xxxxx plugin.py:xxx] Monitor runs begin
Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.9.0 at http://localhost:6006/ (Press CTRL+C to quit)
```
The url has nothing abnormal, but intergrated tensorboard can't start in vscode anyway.

**Comment by Saltsmart** [comment] 2022-05-28 12:13
> @yongshangli Thanks for filing this issue. First step here is if you could please change the VS Code setting `python.logging.level` to 'debug', rerun the scenario, and copy out everything in the Output -> Python section. That has all our output tracing which can help us to debug this more easily.

I did as you suggested. It's just the same as Issue [8231](https://github.com/microsoft/vscode-jupyter/issues/8231) for vscode-jupyter extension:
```
> conda run -n d2l --no-capture-output python ~\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\get_output_via_markers.py -c "import tensorboard; print(tensorboard.__version__)"
> conda run -n d2l --no-capture-output python ~\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\get_output_via_markers.py -c "import torch_tb_profiler; print(torch_tb_profiler.__version__)"
> C:\ProgramData\Anaconda3\envs\d2l\python.exe ~\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\tensorboard_launcher.py "."
[ERROR 2022-4-28 20:7:2.195]: Traceback (most recent call last):
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\tensorboard_launcher.py", line 36, in <module>

[ERROR 2022-4-28 20:7:2.195]:     main(logdir)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2022.6.2\pythonFiles\tensorboard_launcher.py", line 17, in main

[ERROR 2022-4-28 20:7:2.195]:     tb = program.TensorBoard()
  File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__

[ERROR 2022-4-28 20:7:2.195]:     return getattr(load_once(self), attr_name)
  File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\tensorboard\lazy.py", line 97, in wrapper

[ERROR 2022-4-28 20:7:2.196]:     cache[arg] = f(arg)
  File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\tensorboard\lazy.py", line 50, in load_once

[ERROR 2022-4-28 20:7:2.196]:     module = load_fn()
  File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\tensorboard\__init__.py", line 99, in program

[ERROR 2022-4-28 20:7:2.196]:     return importlib.import_module("tensorboard.program")
  File "C:\ProgramData\Anaconda3\envs\d2l\lib\importlib\__init__.py", line 127, in import_module

[ERROR 2022-4-28 20:7:2.197]:     return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import

[ERROR 2022-4-28 20:7:2.197]:   File "<frozen importlib._bootstrap>", line 991, in _find_and_load

[ERROR 2022-4-28 20:7:2.197]:   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked

[ERROR 2022-4-28 20:7:2.197]:   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked

[ERROR 2022-4-28 20:7:2.198]:   File "<frozen importlib._bootstrap_external>", line 843, in exec_module

[ERROR 2022-4-28 20:7:2.198]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

[ERROR 2022-4-28 20:7:2.198]:   File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\tensorboard\program.py", line 52, in <module>

[ERROR 2022-4-28 20:7:2.198]:     from tensorboard.backend import application
  File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\tensorboard\backend\application.py", line 44, in <module>

[ERROR 2022-4-28 20:7:2.199]:     from tensorboard.plugins.core import core_plugin
  File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\tensorboard\plugins\core\core_plugin.py", line 32, in <module>

[ERROR 2022-4-28 20:7:2.199]:     from tensorboard.util import grpc_util

[ERROR 2022-4-28 20:7:2.199]:   File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\tensorboard\util\grpc_util.py", line 24, in <module>

[ERROR 2022-4-28 20:7:2.200]:     import grpc
  File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\grpc\__init__.py", line 22, in <module>

[ERROR 2022-4-28 20:7:2.200]:     from grpc import _compression
  File "C:\ProgramData\Anaconda3\envs\d2l\lib\site-packages\grpc\_compression.py", line 15, in <module>

[ERROR 2022-4-28 20:7:2.200]:     from grpc._cython import cygrpc
ImportError
[ERROR 2022-4-28 20:7:2.200]: : DLL load failed while importing cygrpc: 找不到指定的模块。

[ERROR 2022-4-28 20:8:1.663]: Encountered error while starting new TensorBoard session: Error: Timed out after 60 seconds waiting for TensorBoard to launch.

```

**Comment by IanMatthewHuff** [comment] 2022-06-10 21:37
Looks like this is a duplicate of #9678. Closing in favor of that, and pulling that back to triage.

**Closed by IanMatthewHuff** 2022-06-10 21:37 UTC
Labels: bug, info-needed, tensorboard
