### ISSUE TITLE
IPython.display.IFrame("./file.html") doesn't work

### ISSUE THREAD

**Issue by FlorinAndrei** [microsoft/vscode-jupyter#13410] opened 2023-04-27 02:39 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Test file:

[plot_model.html.txt](https://github.com/microsoft/vscode-jupyter/files/11339019/plot_model.html.txt)

Rename the test file to `plot_model.html` then run the code below in a Jupyter notebook.

Code:

```python
from IPython.display import IFrame
IFrame("./plot_model.html", width=800, height=400)
```

With the traditional Jupyter Notebook server, running in Chrome, the test file is displayed just fine.

With VSCode, nothing is displayed.

IPython 8.5.0

The Jupyter server runs remotely on an Ubuntu 22.04 machine. VSCode runs on my Win10 laptop. I connect to Ubuntu via ssh.

### VS Code Version

Version: 1.77.3 (user setup) Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710 Date: 2023-04-12T09:16:02.548Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.19044 Sandboxed: No

### Jupyter Extension Version

v2023.3.1201040234

### Jupyter logs

```shell
info 19:36:22.776: Restart kernel execution
info 19:36:22.776: Restart requested file:///home/florin/kaggle/spaceship-titanic/vscode_bug.ipynb
info 19:36:22.776: Restarting 374938fd-7b9a-46e3-b2c2-c31263966bd4
warn 19:36:23.021: Failed to get activated env vars for /usr/bin/python3 in 244ms
error 19:36:23.023: Unable to determine site packages path for python /usr/bin/python3 (Unknown)
info 19:36:23.034: Process Execution: > /usr/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /usr/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
warn 19:36:23.036: Failed to get activated env vars for /usr/bin/python3 in 254ms
warn 19:36:23.036: Failed to get activated env vars for /usr/bin/python3 in 254ms
error 19:36:23.038: Unable to determine site packages path for python /usr/bin/python3 (Unknown)
error 19:36:23.038: Unable to determine site packages path for python /usr/bin/python3 (Unknown)
info 19:36:23.048: Process Execution: > /usr/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"474b3d25-1267-44a9-a0ae-ec35c56108b7" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/florin/.local/share/jupyter/runtime/kernel-v2-8208p47EfaZ05jXW.json
> /usr/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"474b3d25-1267-44a9-a0ae-ec35c56108b7" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/florin/.local/share/jupyter/runtime/kernel-v2-8208p47EfaZ05jXW.json
info 19:36:23.048: Process Execution: cwd: ~/kaggle/spaceship-titanic
cwd: ~/kaggle/spaceship-titanic
info 19:36:23.120: ipykernel version & path 6.16.0, ~/.local/lib/python3.10/site-packages/ipykernel/__init__.py for /usr/bin/python3
info 19:36:23.460: Got new session 8608c767-83b4-42c6-a99b-2f60c6b1d6ad
info 19:36:23.460: Started new restart session
info 19:36:23.460: Dispose Kernel process 8528.
```

### Coding Language and Runtime Version

Python 3.10.6

### Language Extension Version (if applicable)

v2023.6.1

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment] 2024-12-17 01:03
Duplicate of https://github.com/microsoft/vscode/issues/172867

**Closed by DonJayamanne** 2024-12-17 01:03 UTC
Labels: bug, notebook-output
