### ISSUE TITLE
Jupyter Notebook cell runs infinitely and cannot be interrupted if setting a numpy array element as a sequence

### ISSUE THREAD

**Issue by Charlie-XIAO** [microsoft/vscode-jupyter#12972] opened 2023-03-01 04:25 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### Steps to reproduce the issue

1. Install Jupyter + Python extensions in VSCode.
2. Create an empty `.ipynb` file, and include the following (Python code) cells:
```Python
import numpy as np
```
```Python
array = np.zeros(5)  # or any statement that creates a 1d numpy array
array[0] = np.array([1, 2, 3])  # or any statement that sets an entry to a sequence
```
3. Run all cells.

### Actual output

The second cell will run infinitely, and if one interrupts it, the following error will show up:
![2a2d986d49152731f0c15966db81eba](https://user-images.githubusercontent.com/108576690/222043977-ab0ab96e-496c-4037-ae6f-d76d02aa98f9.png)
In this case, one would be forced to restart the kernel, but that all variables will be lost, which is undesirable.

### Expected output

If one runs the aforementioned code directly using Python, it will throw the following error message and terminate.
```
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Academic\03 - NYU Shanghai\8_Spring 2023\Open Source Software Development\vscode-jupyter-bug\numpy-jupyter-bug.py", line 4, in <module>
    array[0] = np.array([1, 2, 3])
ValueError: setting an array element with a sequence.
```
If one runs the Jupyter Notebook in other environments (for instance on Google Colab), one would also receive this error and then the cell will terminate. This is expected, since then one will be able to debug the corresponding cell instead of being forced to restart the kernel.

See the Jupter log attached for more details. It shows that there are many other exceptions caused by this exception.

### VS Code Version

Version: 1.76.0-insider (user setup) Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb Date: 2023-02-28T11:50:30.886Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: Yes

### Jupyter Extension Version

v2023.2.1000561009

### Jupyter logs

```shell
warn 12:13:55.968: StdErr from Kernel Process [IPKernelApp] ERROR | Exception in message handler:
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\17458\AppData\Local\Temp\ipykernel_67640\842731975.py", line 2, in <module>
    array[0] = np.array([1, 2, 3])
ValueError: setting an array element with a sequence.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "c:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 775, in format_exception_as_a_whole
    assert etb is not None
AssertionError

info 12:14:09.793: Interrupt kernel execution
info 12:14:09.793: Interrupt requested d:\Academic\03 - NYU Shanghai\8_Spring 2023\Open Source Software Development\vscode-jupyter-bug\numpy-jupyter-bug.ipynb
info 12:14:09.793: Interrupt kernel execution
info 12:14:09.793: Interrupting kernel: pythonjvsc74a57bd0b7d0c54d800873a0b070cc8b97354bc0b4baf493b098122dcb9c4c5a26e12be1
info 12:14:09.793: Interrupting kernel via custom event (Win32)
info 12:14:19.806: Interrupt requested & sent for d:\Academic\03 - NYU Shanghai\8_Spring 2023\Open Source Software Development\vscode-jupyter-bug\numpy-jupyter-bug.ipynb in notebookEditor.
info 12:14:24.913: Restart kernel execution
info 12:14:24.913: Cancel all remaining cells true || Idle || undefined
info 12:14:24.913: Restart requested file:///d%3A/Academic/03%20-%20NYU%20Shanghai/8_Spring%202023/Open%20Source%20Software%20Development/vscode-jupyter-bug/numpy-jupyter-bug.ipynb
info 12:14:24.914: Restarting ee0d667e-6674-4fbb-8bc3-ac3295301078
warn 12:14:25.001: Failed to get activated env vars with python c:\Users\17458\AppData\Local\Programs\Python\Python39\python.exe in 87ms
info 12:14:25.020: Process Execution: > ~\AppData\Local\Programs\Python\Python39\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~\AppData\Local\Programs\Python\Python39\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
warn 12:14:25.047: Failed to get activated env vars with python c:\Users\17458\AppData\Local\Programs\Python\Python39\python.exe in 50ms
warn 12:14:25.049: Failed to get activated env vars with python c:\Users\17458\AppData\Local\Programs\Python\Python39\python.exe in 51ms
info 12:14:25.071: Process Execution: > ~\AppData\Local\Programs\Python\Python39\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"4f7a3103-f174-46e3-911e-a67b5a42c1a4" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\17458\AppData\Roaming\jupyter\runtime\kernel-v2-54180g6EhwHgXr60l.json
> ~\AppData\Local\Programs\Python\Python39\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"4f7a3103-f174-46e3-911e-a67b5a42c1a4" --shell=9002 --transport="tcp" --iopub=9004 --f=c:\Users\17458\AppData\Roaming\jupyter\runtime\kernel-v2-54180g6EhwHgXr60l.json
info 12:14:25.071: Process Execution: cwd: d:\Academic\03 - NYU Shanghai\8_Spring 2023\Open Source Software Development\vscode-jupyter-bug
cwd: d:\Academic\03 - NYU Shanghai\8_Spring 2023\Open Source Software Development\vscode-jupyter-bug
info 12:14:25.586: ipykernel version & path 6.15.1, ~\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\__init__.py for c:\Users\17458\AppData\Local\Programs\Python\Python39\python.exe
info 12:14:27.211: Got new session b544a16d-7de4-4a7d-b268-a99247a9bb5d
info 12:14:27.211: Started new restart session
info 12:14:27.211: Dispose Kernel process 67640.
error 12:14:27.227: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
	at t.KernelShellFutureHandler.dispose (c:\Users\17458\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.2.1000561009\out\extension.node.js:2:33213)
	at c:\Users\17458\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.2.1000561009\out\extension.node.js:2:52265
	at Map.forEach (<anonymous>)
	at y._clearKernelState (c:\Users\17458\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.2.1000561009\out\extension.node.js:2:52250)
	at y.dispose (c:\Users\17458\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.2.1000561009\out\extension.node.js:2:45732)
	at c:\Users\17458\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.2.1000561009\out\extension.node.js:17:127079
	at ee (c:\Users\17458\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.2.1000561009\out\extension.node.js:2:1552543)
	at lh.dispose (c:\Users\17458\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.2.1000561009\out\extension.node.js:17:127055)
	at ph.dispose (c:\Users\17458\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.2.1000561009\out\extension.node.js:17:134354)]
warn 12:14:27.227: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'
}
```

### Coding Language and Runtime Version

Python v3.9.6

### Language Extension Version (if applicable)

Python Extension: v2023.5.10591006

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2023-03-21 07:15
I'm sorry for not getting back to you on this,.

Thanks for sharing the logs, please could you share the whole log as some of the initial logs are crucial as well.
Please share the logs after you enable verbose logging as follows
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

> If one runs the Jupyter Notebook in other environments (for instance on Google Colab), one would also receive this error and then the cell will terminate. 

Please could you try the following:
* Install Jupyter notebook/lab in the same Python environment using the command
    `python -m pip install jupyter notebook`
* Run jupyter in side that environment as follows
    `python -m jupyter notebook`
* Run the same notebook and please let me know what happens.
I am curious about the behaviour on your own Widows machine as opposed to Google Colab or other (as those would most likely be running unix, and interrupting any python code in unix is very different compared to windows). By different, i mean interrupting cells work very well on unix compared to windows.

**Comment by DonJayamanne** [comment] 2023-03-21 18:59
> terminate (as is shown from the white circle on the top right corner in the image above, indicating the the kernel is idle)

agreed, however if you look at the cell indicator it showed that the cell is still running, that’s why the asterix is still present
Try running another cell and let me know what happens
Basically you get a similar problem there too

**Comment by Charlie-XIAO** [comment] 2023-03-21 19:26
Oh that's true. I added a new cell `array` after that and tried again, here is what I got:

![image](https://user-images.githubusercontent.com/108576690/226719134-78fb15af-b2ed-425e-afe5-e029ab7abf78.png)

And here's the log:
```
PS D:\Academic\03 - NYU Shanghai\8_Spring 2023\Open Source Software Development\vscode-jupyter-bug> python -m jupyter notebook

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 03:23:41.675 NotebookApp] Serving notebooks from local directory: D:\Academic\03 - NYU Shanghai\8_Spring 2023\Open Source Software Development\vscode-jupyter-bug
[I 03:23:41.690 NotebookApp] Jupyter Notebook 6.5.3 is running at:
[I 03:23:41.690 NotebookApp] http://localhost:8888/?token=aa8803ef6f322caadd320071373563ad7053d34c7dad46ce
[I 03:23:41.690 NotebookApp]  or http://127.0.0.1:8888/?token=aa8803ef6f322caadd320071373563ad7053d34c7dad46ce
[I 03:23:41.690 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 03:23:41.941 NotebookApp] 

    To access the notebook, open this file in a browser:
        file:///C:/Users/17458/AppData/Roaming/jupyter/runtime/nbserver-27560-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=aa8803ef6f322caadd320071373563ad7053d34c7dad46ce
     or http://127.0.0.1:8888/?token=aa8803ef6f322caadd320071373563ad7053d34c7dad46ce
[I 03:23:47.488 NotebookApp] Kernel started: e991b078-625d-44ed-b28c-adf8d83d68ee, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: f1b29277-bdca-470a-8877-99a17823d636
[IPKernelApp] ERROR | Exception in message handler:
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\17458\AppData\Local\Temp\ipykernel_2864\842731975.py", line 2, in <module>
    array[0] = np.array([1, 2, 3])
ValueError: setting an array element with a sequence.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'ValueError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3191, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3268, in run_code
    self.showtraceback(running_compiled_code=True)
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 775, in format_exception_as_a_whole        
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 2814, in _run_cell
    return runner(coro)
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3012, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3210, in run_ast_nodes
    self.showtraceback()
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 775, in format_exception_as_a_whole        
    assert etb is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1934, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AssertionError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\kernelbase.py", line 406, in dispatch_shell
    await result
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\kernelbase.py", line 730, in execute_request
    reply_content = await reply_content
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\ipkernel.py", line 390, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\ipykernel\zmqshell.py", line 528, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 2768, in run_cell
    result = self._run_cell(
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 2819, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 1936, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 1105, in structured_traceback
    return FormattedTB.structured_traceback(
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 999, in structured_traceback
    return VerboseTB.structured_traceback(
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 871, in structured_traceback
    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,
  File "C:\Users\17458\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\ultratb.py", line 775, in format_exception_as_a_whole        
    assert etb is not None
AssertionError
[I 03:24:35.217 NotebookApp] Saving file at /numpy-jupyter-bug.ipynb
[I 03:24:36.178 NotebookApp] Saving file at /numpy-jupyter-bug.ipynb
[I 03:24:37.659 NotebookApp] Starting buffering for e991b078-625d-44ed-b28c-adf8d83d68ee:7d49dd6f0ff44582beb670f7a27e7c99
[I 03:24:38.713 NotebookApp] Shutting down on /api/shutdown request.
[I 03:24:38.728 NotebookApp] Shutting down 1 kernel
[I 03:24:38.728 NotebookApp] Kernel shutdown: e991b078-625d-44ed-b28c-adf8d83d68ee
[I 03:24:38.964 NotebookApp] Shutting down 0 terminals
```

**Comment by DonJayamanne** [comment] 2023-03-21 20:06
Thanks for the logs
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/13087#issuecomment-1478460287

**Closed by DonJayamanne** 2023-03-21 20:06 UTC
Labels: bug, info-needed, notebook-kernel-execution
