### ISSUE TITLE
Python Markdown extension for VS Code

### ISSUE THREAD

**Issue by stefanuddenberg** [microsoft/vscode-jupyter#1655] opened 2019-12-08 21:56 UTC
# Feature Request: "Python Markdown" in Markdown cells

## Description
It would be nice to have the equivalent of the ["Python Markdown" extension for Jupyter](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/python-markdown/readme.html) in VS Code. So within a markdown cell, you could put arbitrary Python code between two curly braces which would be executed and rendered in-line. This is very useful when writing quantitative scientific reports.

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by rchiodo** [comment] 2022-02-24 17:30
Marking this as dupe of #4946 which has more upvotes

**Closed by rchiodo** 2022-02-24 17:30 UTC
Labels: enhancement, notebook-markdown
