### ISSUE TITLE
Runtime kernel.json files are being left behind on shutdown

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9712] opened 2022-04-19 16:31 UTC
Seems like we should clean up the runtime folder kernel.json files. That's likely a result of just killing the process.

_Originally posted by @rchiodo in https://github.com/microsoft/vscode-jupyter/issues/1626#issuecomment-1102851926_

**Comment by Winand** [comment] 2022-04-20 14:02
Is it harmless to remove all these files by mask on exit?

```
cd /home/username/.local/share/jupyter/runtime
rm kernel-*.json nbserver-*.html nbserver-*.json
```

**Comment by rchiodo** [comment] 2022-04-20 16:00
Yes they should be removable as long as you don't have any active kernels you're using.

**Comment by DonJayamanne** [comment] 2022-04-20 20:32
> clean up the runtime folder kernel.json files. 

From what I can tell we are cleaning these up. Possible its only getting cleaned up in our latest main branch.
However the nbserver-*.html & nbserver-*.json don't get cleared up as we don't gracefully shutdown jupyter (in non-raw).

**Comment by DonJayamanne** [comment] 2022-08-02 16:30
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8827

**Closed by DonJayamanne** 2022-08-02 16:30 UTC
Labels: bug, notebook-execution
