### ISSUE TITLE
Markdown Preview Pane is disabled for Markdown cells in Notebooks.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/vscode-jupyter#13967] opened 2023-07-22 13:21 UTC
I'd like to be able to use the Markdown preview pane that's by default bound to the

0.	Left CONTROL key,
0.	Left SHIFT key, and
0.	V key

when editing a `.md` file. I can get something similar by finishing modifying the Markdown cell, but this doesn't provide the same immediate formatting feedback that the preview pane does.

**Comment by DonJayamanne** [comment] 2023-09-07 01:29
I'm sorry for not getting back to you on this, missed this issue.
Thanks for the feature suggestion.

**Comment by amunger** [comment] 2023-09-07 16:05
I think you can actually get this behavior by removing `!notebookEditorFocused` from the when clause for the `markdown.showPreview` keybinding - open keyboard shortcuts, search markdown.showPreview, right click - change when clause.

Let us know if that's not what you were looking for.

**Comment by rokejulianlockhart** [comment] 2023-09-08 10:31
> https://github.com/microsoft/vscode-jupyter/issues/13967#issuecomment-1710418914

@amunger, not quite. It's darn close, but I want to see all sections of the IPYNB file (since it's ultimately meant to appear like a document would, just programmatically generated).

Being able to preview solely one section is actually quite useful, but it's not what I was looking for.

---

Regardless, why is the default

```
!notebookEditorFocused && editorLangId == 'markdown'
```

if it seemingly solely prevents a user using the markdown previewer in other situations where there is markdown? It seems to me like only the second part really needs to be there.

**Comment by amunger** [comment] 2023-09-08 16:24
I see, we would need to concatenate all the markdown cells from the ipynb and send them to the preview to do that, which would be a bit more work. An interesting idea though.

I suspect disabled by default because `notebook.cell.pasteAbove` has the same keybinding.

**Comment by mjbvz** [comment] 2023-12-14 01:05
Duplicate of https://github.com/microsoft/vscode/issues/189082

**Closed by mjbvz** 2023-12-14 01:05 UTC
Labels: notebook-markdown, feature-request
