### ISSUE TITLE
[Endgame Testing] Cannot step into function from one cell above (Could not load source '/tmp/ipykernel_20889/3035911468.py': source unavailable.)

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode-jupyter#6483] opened 2021-07-01 11:18 UTC
Testing https://github.com/microsoft/vscode/issues/127362

* set up jupyter in a dev container:
  * create a new folder
  * (install remote dev container extension)
  * run `Remote Containers: Add Development Container Configuration Files...`
  * pick `Show All Definitions...` at the bottom
  * pick `Jupyter Data Science Notebooks`
  * reopen the folder in container
* follow all the Setup steps from https://github.com/microsoft/vscode/issues/127362
* find a sample notebook e.g. https://raw.githubusercontent.com/jrjohansson/scientific-python-lectures/master/Lecture-4-Matplotlib.ipynb
* open the notebook and press Run All
* enter debug mode
* place a breakpoint at cell number 125 and run the cell
* attempt to step into `flux_qubit_potential`:

https://user-images.githubusercontent.com/5047891/124116097-daf9e500-da6e-11eb-9e68-fa0ede60bfcb.mp4

**Comment by greazer** [comment] 2021-09-02 18:47
Looks like a dupe of #6413

**Closed by greazer** 2021-09-02 18:47 UTC
Labels: bug, notebook-debugging
