### ISSUE TITLE
Support for quick change to raw cell

### ISSUE THREAD

**Issue by YongcaiHuang** [microsoft/vscode-jupyter#15766] opened 2024-06-09 16:37 UTC
in Jupyter Notebook, there is a keyboard shortcut pressing `R` to change a cell into raw text, which is convenient when some cells do not need to run but still keep it. However, in VSCode Notebook, I need to click the language at the bottom right of each cell to change into the raw cell. it would be great if we have some ways to quick change cell into raw with keyboard shortcut.

**Comment by chandradharkoneti** [comment] 2024-07-24 10:48
I agree. When blocking execution of a certain subset of cells, I generally just change them to raw in Jupyter Notebooks (regular).
I know that changing them to markdown using `M` key will also do the job, but if my cell has comments, they become headings when converted to markdown, which is very confusing and clutters the notebook. Simply hitting `R` solves the issue in regular jupyter notebooks. VS Code jupyter does not have that feature. 

It is a very useful feature to have.

**Comment by chandradharkoneti** [comment] 2024-09-30 06:59
https://github.com/microsoft/vscode-jupyter/issues/1466#issuecomment-772200892

This issue with `raw` cells was previously raised. However, that was only for the presence of raw cells. Please enable a keyboard shortcut to change to raw by pressing `R` since the shortcut is anyhow available.

**Comment by DonJayamanne** [comment] 2024-12-17 00:43
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/16158

**Closed by DonJayamanne** 2024-12-17 00:43 UTC
Labels: notebook-commands, feature-request
