### ISSUE TITLE
Extension activation failed on TypeError

### ISSUE THREAD

**Issue by alyssajotice** [microsoft/vscode-jupyter#5344] opened 2021-03-29 16:28 UTC
## Environment data

-   VS Code version: 1.55.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): v2021.5.697286501
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: OS: Windows_NT x64 10.0.19042
-   Python and/or Anaconda version: 3.7.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

Try to open a notebook document in VS Code.

## Expected behaviour
Document opens

## Actual behaviour
Document opens and the following is printed to the console: 

```
extension activation failed TypeError: s.notebook.onDidChangeCellExecutionState is not a function
	at new d (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:49:766571)
	at Object.resolveInstance (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:239920)
	at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:239125
	at Array.map (<anonymous>)
	at Object.resolveInstance (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:239690)
	at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:239125
	at Array.map (<anonymous>)
	at Object.resolveInstance (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:239690)
	at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:239125
	at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:238073
	at Array.map (<anonymous>)
	at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:238045
	at Array.map (<anonymous>)
	at Object.resolveInstance (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:239690)
	at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:239125
	at Object.resolve (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:239388)
	at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:230485
	at e._get (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:230251)
	at e.get (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:228963)
	at a.get (c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:49:817335)
	at c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:47:273173
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:32:772781
	at async c:\Users\allytice\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.5.697286501\out\client\extension.js:32:772468
	at async Promise.all (index 0)
```

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
I did not see this option in the drop down in the Output.
```

</p>
</details>

**Comment by joyceerhl** [comment] 2021-03-29 16:45
@alyssajotice  I believe this is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/5251, as I'm unable to reproduce this behavior with v2021.5.697286501 of the Jupyter extension and the following VS Code build:

Version: 1.55.0-insider (user setup)
Commit: 26a60dbecacc8bdacc06f7681ebe95398878a1cd
Date: 2021-03-29T10:27:14.607Z

If your VS Code build is not the same as the one above, would you mind checking if you have a pending VS Code Insiders update please? Restarting VS Code to update should do the trick.

![image](https://user-images.githubusercontent.com/30305945/112870291-e81fc600-9072-11eb-81cb-c1bd9e7be281.png)

If you don't see a pending update, you may also wish to check that you haven't disabled VS Code updates in your user settings.json--the setting name is `"update.mode"`.

**Comment by greazer** [comment] 2021-03-29 17:59
We think this is a dupe of 5251, please reopen if you are still reproing with the latest VS Code Insiders. Thanks!

**Closed by greazer** 2021-03-29 17:59 UTC
Labels: bug

**Comment by alyssajotice** [comment] 2021-03-29 20:02
Updating resolved it. Thanks!
