### ISSUE TITLE
Unexpected behaviour when running Notebook cells in Codespace

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#4243] opened 2020-12-16 17:44 UTC
Testing [Codespace Scenario: 1791](https://github.com/microsoft/vssaas-planning/issues/1791)

## Environment data

-   VS Code version: 1.52.0-insider (Codespace)
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.1
-   Python Extension version (available under the Extensions sidebar): 2020.11.2
-   OS (Windows | Mac | Linux distro) and version: Linux Codespace
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Running cells in Codespace Notebook should behave the same as desktop client. Starting steps:

1. Invoke Codespace.
2. Create blank Jupyter Notebook via command "Create Blank New Jupyter Notebook"
3. Write cell - _print("hello world")_
4. Run cell - Shift + Enter

## Actual behaviour

1. Cell isn't run inline - terminal instance is invoked.

![image](https://user-images.githubusercontent.com/6413608/102385576-df532a80-3f82-11eb-96e0-6624d44f16ae.png)

2. Prompted to run with Ctrl + Alt + Enter. Seeing the following toast notification:

![image](https://user-images.githubusercontent.com/6413608/102385661-fa259f00-3f82-11eb-831d-f08c841c5af1.png)

3. Same toast notification shown when running via "play" button.

## Steps to reproduce:

Use starting steps from above ^.

**Comment by SiddhanthUnnithan** [comment] 2020-12-16 17:48
Run all cells results in the same "Canceled" notification.

**Comment by SiddhanthUnnithan** [comment] 2020-12-16 17:57
When running cell for the first time with Ctrl + Alt + Enter / Run button / Run All, seeing:

![image](https://user-images.githubusercontent.com/6413608/102387336-188c9a00-3f85-11eb-983f-8d8fc48279a0.png)

**Comment by IanMatthewHuff** [comment] 2020-12-17 19:44
Triage note, looks like path settings on the codespaces instance is not working as expected if the active is not available.

**Comment by rchiodo** [comment] 2021-01-04 17:05
This sounds like it might be a root python problem. It's not creating the python environment correctly.

**Comment by DonJayamanne** [comment] 2021-01-04 18:16
I think this is a dupe of a core extension bug, we have a number of issues that are similar `no such file or directory` when activating envs (https://github.com/microsoft/vscode-python/issues/14812#issuecomment-734404349)

I think something has regressed recently thats breaking env activation for a large number of users (users have been complaining on VS Code as well for similar issues)

**Comment by greazer** [comment] 2021-01-04 23:21
I'm going to call this a dupe of microsoft/vscode-python#14812. Sid after that's resolved we can check this one too.

**Closed by greazer** 2021-01-04 23:21 UTC
Labels: bug
