### ISSUE TITLE
Resizing variable view column doesn't resize all cells in the column together

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#10350] opened 2022-06-07 22:09 UTC
![Recording 2022-06-07 at 15 08 22](https://user-images.githubusercontent.com/876920/172491329-939e2d27-264a-469e-9236-34d653ff7612.gif)

From above gif you can see that resizing the table view columns in the keybindings editor resizes the whole column together while in the variable view, only the column header is resized while dragging.

**Comment by rchiodo** [comment] 2022-06-09 20:33
Dupe of https://github.com/microsoft/vscode-jupyter/issues/10227

**Closed by rchiodo** 2022-06-09 20:33 UTC
Labels: bug, variable-explorer, triage-needed
