### ISSUE TITLE
Telemetry needs to be better documented

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4121] opened 2020-12-04 00:53 UTC
The telemetry constants in this file here:
```src\client\datascience\constants.ts```

could be better documented. This way a 3rd party or our own PMs can understand what causes a telemetry event to fire. 

At the very least we should enforce documentation on new events.

**Comment by DonJayamanne** [comment] 2020-12-04 01:01
Something we wanted to do, but never did happen.
I agree we should enforce it or add a simpler linter to check this.

**Comment by DavidKutu** [comment] 2021-08-31 21:02
Dupe of #4960

**Closed by DavidKutu** 2021-08-31 21:02 UTC
Labels: code-health, debt, telemetry
