### ISSUE TITLE
Interactive window commands are not available until focus goes to interactive window

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#1076] opened 2020-11-12 00:16 UTC
The following export commands are hidden in python files until the focus is moved to interactive window and moved back. 

- Jupyter: Export Current Python File and Output as Jupyter Notebook
- Jupyter: Export Current Python File as Jupyter Notebook

Steps to Reproduce: 
1. Open a python file with cells 
2. With focus on python file, type export -> no command shows up
3. Run a cell and with focus on the python file, type export -> no command shows up
4. Move focus to interactive window
5. Move focus back to python file, type export -> commands show up
(I also tried a variation by moving focus to a notebook instead, did not work. Only works when focus goes to interactive window first) 
![Export Command Bug](https://user-images.githubusercontent.com/19276747/98878769-ab8f5d00-2438-11eb-9af7-405dced98eb0.gif)

**Comment by joyceerhl** [comment] 2020-11-12 00:26
Isn't this by design? We cannot export the IW if it's not open. We also cannot export output from code cells without the IW.

**Comment by claudiaregio** [comment] 2020-11-12 00:31
Copied the wrong second command, updated. The first command is not fixed though if I just open the IW, I have to actually switch focus to it. So a user may open a file, run all cells for a quick check and then have to switch back and forth to have that option actually come up.

**Comment by DonJayamanne** [comment] 2020-11-12 18:31
This is a dupe of of https://github.com/microsoft/vscode-jupyter/issues/330.
& Similar but the opposite is https://github.com/microsoft/vscode-jupyter/issues/329

I don't think this is by design
To me this is a totally busted UX & these things need to be fixed instead of pushing to parking lot and waiting for a user to file an issue, even then we wait for votes... 

Claudia & we know these commands exist & we look for them & we know our work arounds, but users will never come across these (hence the commands are not discoverable, meaning one thing - **it works by chance**) - unless they set focus to interactive window).

**Comment by IanMatthewHuff** [comment] 2020-11-16 22:48
@DonJayamanne did you check in a fix for this already? I'm not seeing the issue:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/8484d1df-5086-4264-99a4-48d16dcb60f8)

**Comment by IanMatthewHuff** [comment] 2020-11-19 18:41
Yeah, I don't see this anymore. Moving to validate if we want a second person to validate that the issue is gone.

**Comment by joyceerhl** [comment] 2020-11-20 03:29
Validated 
![image](https://user-images.githubusercontent.com/30305945/99754579-84bad180-2a9d-11eb-95d6-748f9209b27a.png)

**Closed by joyceerhl** 2020-11-20 03:29 UTC
Labels: bug, regression
