### ISSUE TITLE
trying to open a diff instead opens the notebook editor

### ISSUE THREAD

**Issue by af4jm** [microsoft/vscode-jupyter#5367] opened 2021-03-31 14:28 UTC
## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): 2021.3.684299474
-   Python Extension version (available under the Extensions sidebar): 2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

when I click the changes icon in Source Control, I should see the git diff, regardless of whether it's a notebook or not

## Actual behaviour

the noetbook opens as if it was opened from Explorer

I attempted to work-around by disabling Jupyter, but VSCode claims that I must also disable PY as well... whichi is completely backwards... using Jupyter requires Py (or another language), but opening a Py file requires Py only & whether Jupyter is installed or not is irrelevant

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment] 2021-03-31 15:56
Duplicate of #633

**Closed by rchiodo** 2021-03-31 15:56 UTC
Labels: bug
