### ISSUE TITLE
plotly subplot annotations not working properly on jupyter notebook June 2021 Release

### ISSUE THREAD

**Issue by Softypo** [microsoft/vscode-jupyter#6463] opened 2021-06-30 20:17 UTC
## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999662501
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Pro 21H1
-   Python and/or Anaconda version: python 3.9.5 and 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | Local

## Expected behaviour
![image](https://user-images.githubusercontent.com/66080210/124024727-d5d46180-d9ac-11eb-89d4-4028ff96d8b6.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/66080210/124024596-a4f42c80-d9ac-11eb-8675-c289f5258912.png)
## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

def graph_results_plotly(y, predictions, scores=None, width=None, height=None, template='plotly_dark'):
    # Create figure with secondary y-axis
    fig = make_subplots(rows=1, cols=len(predictions), subplot_titles=tuple(predictions.keys()), shared_yaxes=True)
    c = 1
    if scores==None: scores = {k:None for k in predictions.keys()}
    for score, yhat in zip(scores.items(), predictions.items()):
        # poly1d_fn is a function which takes in yhat values and returns an estimate for y
        coef = np.polyfit(yhat[1], y,1)
        poly1d_fn = np.poly1d(coef)
        #point error
        error = ['point error: '+str(round(abs(yy-yh), 2)) for yy, yh in zip(y, yhat[1])]
        #figures
        fig.add_shape(type="line", x0=0, y0=0, x1=max(y), y1=max(y), line=dict(color="#2700FF", width=3, dash="dashdot",), row=1, col=c)

        fig.add_trace(go.Scatter(x=yhat[1], y=y, name = f'{yhat[0]}', text=error, mode='markers'), secondary_y=False, row=1, col=c)

        fig.add_trace(go.Scatter(x=yhat[1], y=poly1d_fn(yhat[1]), name = f'{yhat[0]} fit', line=dict(color='#FF5733', width=3)), secondary_y=False, row=1, col=c)

        if scores!=None:
            # text annotation
            fig.add_annotation(xref='x domain', yref='y domain', x=0.02, y=1.0,
                text=f'loss: {round(score[1][0], 2)}',
                showarrow=False,
                row=1, col=c)
            fig.add_annotation(xref='x domain', yref='y domain', x=0.02, y=0.96,
                text=f'metric: {round(score[1][1], 2)}',
                showarrow=False,
                row=1, col=c)
        # Axes
        fig.update_traces(opacity=0.6)
        fig.update_yaxes(showgrid=True)
        c += 1

## Logs

<details>
whit this new June 2021 Release of jupyter notebook plotly annotations at least for the subplots does not work properly when explicitly stating which subplot row and columns it belongs to, but instead it stacks all the annotations to the first subplot, also the position within the subplot is not taking into account.

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment] 2021-06-30 20:26
This is partially a dupe of https://github.com/microsoft/vscode-jupyter/issues/6334, but first you need to specify a renderer of type 'notebook'. Once you do that this bug will be fixed in the July release.

**Closed by rchiodo** 2021-06-30 20:26 UTC
Labels: bug

**Comment by Softypo** [comment] 2021-06-30 21:20
Hi Rchiodo, thanks for the prompt response, 

What do you mean by "specify a renderer of type 'notebook' " is it a special definition I need to add to my script? because before this release it worked properly without any type notebook renderer specification.... or do you mean a special specification in your bug report form, beside the ones I already filled?

if it is the last case.. then I dont see a reason to close this case so early

**Comment by rchiodo** [comment] 2021-06-30 21:38
If you look at the example in #6334, it has code like so:

```python
import plotly.express as px
df = px.data.gapminder()
fig = px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="country",
           size="pop", color="continent", hover_name="country",
           log_x=True, size_max=55, range_x=[100,100000], range_y=[25,90])
fig.show(renderer='notebook')
```

The key part being the ```renderer```. That's required for animations to work. There was some more discussion here:
https://github.com/microsoft/vscode-jupyter/issues/4364

**Comment by rchiodo** [comment] 2021-06-30 21:43
You can also test the fix using our insider's build if you install VS code insiders.

**Comment by Softypo** [comment] 2021-06-30 21:50
great... ill add that to my script... thanks again

**Comment by Softypo** [comment] 2021-06-30 22:09
it dint worked... and I tried with every single rendering option.. some of them show the plot but with the incorrect annotations... and some others including 'notebook' does not show anything at all....

is this something that will be addressed in july release?

**Comment by rchiodo** [comment] 2021-06-30 23:07
Yes it doesn't work at the moment, using the 'notebook' renderer will work when the next release comes out.

**Comment by rchiodo** [comment] 2021-06-30 23:07
If you use insiders, it should work today though.
