### ISSUE TITLE
Strange behavior opening variables Interactive Python

### ISSUE THREAD

**Issue by alandema** [microsoft/vscode-jupyter#7898] opened 2021-10-12 00:02 UTC
## Environment data

-   VS Code version: 1.61.0 (user setup)
-   Extension version (available under the Extensions sidebar): 2021.10.1317843341
-   OS and version: W10 21H1
-   Python version (& distribution if applicable, e.g. Anaconda): WinPy python 3.9.5
-   Relevant/affected Python-related VS Code extensions and their versions: Jupyter 2021.9.1001312534
-   Value of the `python.languageServer` setting: XXX

## Expected behaviour

To open any variable as I click in it.

## Actual behaviour

Seems to be a problem with the focus on the tab. When Interactive is not in focus you can only open 1 variable in data viewer. Also, when not in focus, no variables are shown in variable explorer.

## Steps to reproduce
![vscode](https://user-images.githubusercontent.com/68517641/136868906-18fae6b2-3195-4110-8336-b137bda3651c.gif)
:

**Comment by DonJayamanne** [comment] 2021-10-12 01:14
Thanks for filing this issue.
We have already fixed this and you should be able to get the fix in VS Code insiders today 
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7325

If it doesn't work, please feel free to file a separate issue or re-open this.

**Closed by DonJayamanne** 2021-10-12 01:14 UTC
Labels: needs-triage
