### ISSUE TITLE
IntelliSense and Pylance stop working after adding and deleting a cell

### ISSUE THREAD

**Issue by sfo** [microsoft/vscode-jupyter#6586] opened 2021-07-08 12:55 UTC
Ok, this took me some time to come up with a reproducible example, since at first it seemed to happen at random.

I just discovered additional triggers for this bug:
- As shown below: Add a cell behind the current one and delete it again
- Add a cell before the current cell (no need to delete it)
- Open a fresh notebook and just delete a cell, no further interaction required

## Actual behaviour

After adding and deleting a cell, the quick documentation, parameter info, autocomplete, go to definition, go to reference, and Pylance all go crazy or stop working completely until I reload the whole VSCode window, which disconnects all notebooks from their kernel and their state is lost.

Some demos of the mwe:

No docs / parameter info on hover, definition/reference not found:
![vscode_bug](https://user-images.githubusercontent.com/571497/124922731-1742bd80-dffa-11eb-9bf9-a3de797bf588.gif)

Autocomplete stops working
![vscode_bug_autocomplete](https://user-images.githubusercontent.com/571497/124924127-6806e600-dffb-11eb-8b7a-c6ac0ba7a671.gif)

Pylance goes crazy
![vscode_bug_pylance](https://user-images.githubusercontent.com/571497/124924230-840a8780-dffb-11eb-8e1c-6bd663683154.gif)

## Expected behaviour

Adding / Deleting a cell should not change behavior of other features.

## Environment data

- VS Code version: 1.58.0-insider
- Jupyter Extension version (available under the Extensions sidebar): 2021.8.1007436305
- Python Extension version (available under the Extensions sidebar): 2021.7.992362372-dev
- OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04.2
- Python and/or Anaconda version: Python 3.9.5 / Conda 4.9.0
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
- Jupyter server running: Remote, but runs on localhost

## Logs

There is no special output in the Jupyter tab.

**Comment by joyceerhl** [comment] 2021-07-08 18:42
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/6581 apologies for the trouble, we are working on a fix.

**Closed** 2021-07-08 19:19 UTC
Labels: bug
