### ISSUE TITLE
Command 'jupyter.selectjupyteruri' is failing

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-jupyter#5420] opened 2021-04-06 17:26 UTC
## Environment data

-  Jupyter Extension version: v2021.6.718745073
-  Python Extension version: v2021.3.680753044
- Version: 1.56.0-insider (user setup)
- Commit: 58186680eb97fe979e1d986bcfa983ab0a6228e4
- Date: 2021-04-06T10:35:57.015Z
- Electron: 11.4.1
- Chrome: 87.0.4280.141
- Node.js: 12.18.3
- V8: 8.7.220.31-electron.0
- OS: Windows_NT x64 10.0.19041

## Expected behaviour

The dropdown to start a local kernel or input a remote url comes up.

## Actual behaviour

Status bar button:
![image](https://user-images.githubusercontent.com/20347396/113750756-13806180-96c0-11eb-85b0-7ec432eb78b4.png)

Command Palette:
![image](https://user-images.githubusercontent.com/20347396/113750987-44f92d00-96c0-11eb-9c31-4377dd114e1c.png)

## Steps to reproduce:

1. Open a notebook
2. Click the server button on the status bar or use the command palette and run `Jupyter: Specify local or remote Jupyter server for connections`

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Nothing on the ouput, here's the dev tools console:
```
![image](https://user-images.githubusercontent.com/20347396/113752943-622efb00-96c2-11eb-8977-b2078cee4cb1.png)
</p>
</details>

**Comment by IanMatthewHuff** [comment] 2021-04-06 18:13
Dupe of #5419 just came in before yours. Taking a peek now.

**Closed by IanMatthewHuff** 2021-04-06 18:13 UTC
Labels: bug

**Comment by DavidKutu** [comment] 2021-04-06 20:40
![image](https://user-images.githubusercontent.com/20347396/113775518-af6c9600-96dd-11eb-92cc-37f58b66e43e.png)

**Comment by clayms** [comment] 2021-04-07 21:26
@DavidKutu 

did you try the work-around here: https://github.com/microsoft/vscode-jupyter/issues/5419#issuecomment-814272040

**Comment by clayms** [comment] 2021-04-07 21:28
oh.. I see your the one fixing it anyway.  so nevermind.
