### ISSUE TITLE
Remote sessions are not searchable anymore

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8178] opened 2021-11-05 15:49 UTC
Oh no! I just updated to version v2021.10.1001414422 of the Jupyter extension, and the UI changes around the kernel picker now make this issue almost impossible to work around.

Previously, the picker would show the name of each running Jupyter session in the UI, so you could tell which was likely to be the one you wanted to reconnect to (e.g. for `my_notebook.ipynb` you'd probably want to reconnect to an autogenerated session `my_notebook-xxxx-xxxx-xxxx-xxxx` for whatever value xxxxs were the autogenerated name for the session.

This was _already_ a bit of a pain given the kernel-leaking issue above means that you typically get two or three of these for any given open notebook. But now there's just a list of anonymous sessions (see screenshot); if you have a few going in a remote server, good luck guessing which is the one you wanted if the "suggested" one isn't right. 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/174217/140475973-6dc4cebe-7adc-4c1a-9637-e75cb666914a.png">

_Originally posted by @zpincus in https://github.com/microsoft/vscode-jupyter/issues/7610#issuecomment-961690999_

**Comment by rchiodo** [comment] 2021-11-05 15:50
Thanks for the update @zpincus. Hopefully we can get this fixed ASAP.

@DonJayamanne We need to indicate the notebook file path on jupyter sessions so the user can tell which one to pick.

We used to show the notebook file path in the details I believe.

**Comment by DonJayamanne** [comment] 2021-11-05 16:11
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8175

**Closed by DonJayamanne** 2021-11-05 16:11 UTC
Labels: regression, notebook-remote, needs-triage
