### ISSUE TITLE
LaTeX not rendering in Plotly figures based on notebook in VScode

### ISSUE THREAD

**Issue by moonlighthalfwindow** [microsoft/vscode-jupyter#14954] opened 2023-12-23 04:24 UTC
## Environment data

- [ ] 

-   VS Code version: 1.85.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.11.1003402403
-   Python Extension version (available under the Extensions sidebar): v2023.22.1
-   OS (Windows | Mac | Linux distro) and version: WIndows 11 23H2
-   Python and/or Anaconda version: 3.12.0
-   Plotly version: 5.18.0

## Expected behaviour

According to the example in the official Plotly :<https://plotly.com/python/LaTeX/>, the result should look like this:
```python
import plotly.express as px
fig = px.line(x=[1, 2, 3, 4], y=[1, 4, 9, 16], title=r'$\alpha_{1c} = 352 \pm 11 \text{ km s}^{-1}$')
fig.update_layout(
    xaxis_title=r'$\sqrt{(n_\text{c}(t|{T_\text{early}}))}$',
    yaxis_title=r'$d, r \text{ (solar radius)}$'
)
fig.show()
```
![image](https://github.com/microsoft/vscode-jupyter/assets/75985693/38ffcf8f-7efb-4cff-8daf-06895255fdce)

In fact when I ran the code in a py file, it did have the desired effect in Chrome.

## Actual behaviour

But when I use notebook in VScode it renders as follows:
![newplot](https://github.com/microsoft/vscode-jupyter/assets/75985693/24235e51-d757-454e-ab96-96df4ee59de5)

I found that even though he doesn't render properly, he still outputs normal images when I use the code `fig.write_image("test.png")`:
![test](https://github.com/microsoft/vscode-jupyter/assets/75985693/1847ed09-4ead-4dc3-bb5f-a7ee4344b1bd)

Based on the #8131 , I found that just adding a line of code at the beginning renders it properly：

```python
import plotly.express as px
from IPython.display import display, HTML
display(HTML(
    '<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_SVG"></script>'
)) 


fig = px.line(x=[1, 2, 3, 4], y=[1, 4, 9, 16], title=r'$\alpha_{1c} = `352` \pm 11 \text{ km s}^{-1}$')
fig.update_layout(
    xaxis_title=r'$\sqrt{(n_\text{c}(t|{T_\text{early}}))}$',
    yaxis_title=r'$d, r \text{ (solar radius)}$'
)
fig.show()
```
![image](https://github.com/microsoft/vscode-jupyter/assets/75985693/c11fde3e-799d-4a51-b8dd-3ecb2897154a)

On this basis, even if I change this line of code to a comment, he still works and renders the picture(even if clicking reboot kernel):
![image](https://github.com/microsoft/vscode-jupyter/assets/75985693/c20ed1b9-92e6-4fab-baf3-38359ff5f0fb)

But if at this point I close the file and reopen it, he'll fail to render it correctly again:
![image](https://github.com/microsoft/vscode-jupyter/assets/75985693/67a91399-dbc7-4d26-a4e0-88ed12d946fa)

## Steps to reproduce:

Simply run this code in a VScode notebook.

## Logs

```
12:16:18.302 [info] Handle Execution of Cells 0 for e:\<username>\Desktop\test\tets.ipynb
12:16:18.308 [info] Kernel acknowledged execution of cell 0 @ 1703304978307
12:16:18.461 [info] End cell 0 execution after 0.154s, completed @ 1703304978461, started @ 1703304978307
```

**Comment by amunger** [comment] 2024-01-03 18:15
duplicate of https://github.com/microsoft/vscode-jupyter/issues/8131

**Closed by amunger** 2024-01-03 18:15 UTC
Labels: bug
