### ISSUE TITLE
allow jupyter .ipynb files to be renamed without restarting kernel

### ISSUE THREAD

**Issue by tan-js** [microsoft/vscode-jupyter#15764] opened 2024-06-13 03:37 UTC
Hi, thanks for your great work.

I found this closed thread, but I can't post in it anymore.

> Closing this issue for now as this hasn't been reported anyone else for over a year, 
> Closing as out of scope for now.

_Originally posted by @DonJayamanne in https://github.com/microsoft/vscode-jupyter/issues/11010#issuecomment-1835243211_

I have a similar feature request, as I like to rename file often and create copies and backups to keep things well managed and clear, in a quick and easy way, while doing my own iterations of different approaches.

**Comment by DonJayamanne** [comment] 2024-12-10 00:35
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11010

**Closed by DonJayamanne** 2024-12-10 00:35 UTC
Labels: feature-request
