### ISSUE TITLE
`Specifiy Jupyter Server for connections` quick pick has redundant entry

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12233] opened 2022-11-30 21:40 UTC
When using the MRU kernel picker, the quick pick for selecting a jupyter server has two options for the same action when the `Jupyter: Specify Jupyter Server for Connections` command is run (not in the kernel picker itself).

This is a pretty minor issue since the MRU kernel picker is the preferred way to connect to a server when that option is set.

![image](https://user-images.githubusercontent.com/2019016/204913025-e9494dc7-026e-4950-a884-6fae92f25279.png)

**Comment by DonJayamanne** [comment] 2022-11-30 22:38
@amunger  Can you replicate this issue after you reload VS code?

**Comment by amunger** [comment] 2022-11-30 22:44
yes, persists after reloading. I'll note again that this is outside of the kernel picker flow

**Comment by DonJayamanne** [comment] 2022-12-04 19:09
Steps to repro
* Switch to MRU
* Open notebook and view kernle picker and go into selct remote server
* Open command palette and select the command `Specify Jupyter Serer for Connections`

**Comment by amunger** [comment] 2023-01-24 22:38
@rebornix - it looks like the `Specifiy Jupyter Server for connections` command is no longer available when using MRU kernel picker. Is that intentional? It might confuse people that typically use that command

**Comment by amunger** [comment] 2023-01-24 23:11
maybe it's a new bug but I'm re-opening since now I don't have a way to specify "remote: none" and stop the IW from automatically connecting to a remote kernel when using the MRU kernel picker

**Comment by DonJayamanne** [comment] 2023-01-24 23:54
Specifying `none` will not be an option with the new Kernle picker, hence we cannot bring that back
The problem is not with the kernel picker not suporting none, but its the fact that IW always deafults to remote kernels when it is avaialble, i.e. the Jupyter extension is hardoced to always assume that we must use remote when remote is available.
The ideal solution is to get the user to decide instead of hardcoding such a decision

& that issue is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/11967
@amunger I think you might want to discuss this with @rebornix and we might want to prioritize that for IW to ship kernel picker.

Closing issue as the reason for opening is actually a duplicate of https://github.com/microsoft/vscode-jupyter/issues/11967

**Closed by DonJayamanne** 2023-01-24 23:54 UTC
Labels: bug, notebook-kernel, notebook-kernel-picker
