### ISSUE TITLE
Can't run jupyter notebooks in vscode, IPyKernel not installed into interpreter, Windows 10, Ananconda Distributor

### ISSUE THREAD

**Issue by KikeSenpai** [microsoft/vscode-jupyter#4266] opened 2020-12-23 14:30 UTC
I know there are several issues related to this error, but so far none of the solutions I've read has worked, also it seems to be dependent on the software versions, so I decided to make my own post.

## Environment data
-   VS Code version: 1.52.1
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.7.9 with conda 4.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Actual behaviour
The error message I get from vscode says:
IPyKernel not installed into interpreter Python 3.7.9 64-bit (conda): C:\Users\eaperez\AppData\Local\Continuum\anaconda3\python.exe.
If I click install, the terminal says it is already installed.

## Logs
This show output log when the error message appears.

`User belongs to experiment group 'AlwaysDisplayTestExplorer - control'
User belongs to experiment group 'ShowPlayIcon - start'
User belongs to experiment group 'ShowExtensionSurveyPrompt - control'
User belongs to experiment group 'DebugAdapterFactory - experiment'
User belongs to experiment group 'PtvsdWheels37 - experiment'
User belongs to experiment group 'UseTerminalToGetActivatedEnvVars - control'
User belongs to experiment group 'LocalZMQKernel - experiment'
User belongs to experiment group 'CollectLSRequestTiming - control'
User belongs to experiment group 'CollectNodeLSRequestTiming - experiment'
User belongs to experiment group 'EnableIPyWidgets - experiment'
User belongs to experiment group 'DeprecatePythonPath - experiment'
User belongs to experiment group 'RunByLine - experiment'
User belongs to experiment group 'CustomEditorSupport - control'
User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJoinMailingListVar2'
User belongs to experiment group 'pythonSendEntireLineToREPL'
> pyenv root
> python3.7 c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3.6 c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python3 c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python2 c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.7 c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3.6 c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -3 c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> py -2 c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> python c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py -c "import sys;print(sys.executable)"
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
Error 2020-12-23 09:50:23: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): Unable to read file 'e:\Documentos\python\Customer Analytics\.vscode\settings.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'e:\Documentos\python\Customer Analytics\.vscode\settings.json')
	at _handleError (c:\Users\eaperez\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:745:473)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async y.readText (c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\out\client\extension.js:9:262389)
	at async p.doesFileNeedToBeFixed (c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\out\client\extension.js:59:489303)
	at async c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\out\client\extension.js:59:488430
	at async Promise.all (index 1)
	at async p.getFilesToBeFixed (c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\out\client\extension.js:59:488376)
	at async p.updateTestSettings (c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\out\client\extension.js:59:488003)] {
  code: 'FileNotFound',
  name: 'EntryNotFound (FileSystemError)'
}
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe env list
Python interpreter path: ~\AppData\Local\Continuum\anaconda3\python.exe
Starting Pylance language server.
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
Error 2020-12-23 09:50:23: Detection of Python Interpreter for Command python3 and args  failed as file  does not exist
> pyenv root
Error 2020-12-23 09:50:24: Detection of Python Interpreter for Command python and args  failed as file  does not exist
Error 2020-12-23 09:50:24: Detection of Python Interpreter for Command python and args  failed as file  does not exist
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
Error 2020-12-23 09:50:28: Failed to get interpreter information for 'C:\Users\eaperez\AppData\Local\Microsoft\WindowsApps\python.exe' [Error: Command failed: "C:\\Users\eaperez\AppData\Local\Microsoft\WindowsApps\python.exe" "c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py" "c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\eaperez\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe" "c:\\Users\\eaperez\\.vscode\\extensions\\ms-python.python-2020.12.424452561\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\eaperez\\.vscode\\extensions\\ms-python.python-2020.12.424452561\\pythonFiles\\interpreterInfo.py"'
}
Error 2020-12-23 09:50:28: Failed to get interpreter information for 'C:\Users\eaperez\AppData\Local\Microsoft\WindowsApps\python3.exe' [Error: Command failed: "C:\\Users\eaperez\AppData\Local\Microsoft\WindowsApps\python3.exe" "c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py" "c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\interpreterInfo.py"
Python was not found but can be installed from the Microsoft Store: https://go.microsoft.com/fwlink?linkID=2082640
	at ChildProcess.exithandler (child_process.js:304:12)
	at ChildProcess.emit (events.js:223:5)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:223:5)
	at Pipe.<anonymous> (net.js:664:12)] {
  killed: false,
  code: 9009,
  signal: null,
  cmd: '"C:\\\\Users\\eaperez\\AppData\\Local\\Microsoft\\WindowsApps\\python3.exe" "c:\\Users\\eaperez\\.vscode\\extensions\\ms-python.python-2020.12.424452561\\pythonFiles\\pyvsc-run-isolated.py" "c:\\Users\\eaperez\\.vscode\\extensions\\ms-python.python-2020.12.424452561\\pythonFiles\\interpreterInfo.py"'
}
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe env list
> pyenv root
> pyenv root
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
> pyenv root
> ~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json`

thanks in advance I hope someone can help me.

**Comment by IanMatthewHuff** [comment] 2020-12-23 17:06
@KikeSenpai Thanks for providing the error here. If you open up a command prompt outside of VS Code are you able to activate your conda environment in that? In the error logging above it looks like there are a number of errors coming from conda activation and it's failing to activate the environment:
```
~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
Error 2020-12-23 09:50:23: Detection of Python Interpreter for Command python3 and args failed as file does not exist
pyenv root
Error 2020-12-23 09:50:24: Detection of Python Interpreter for Command python and args failed as file does not exist
Error 2020-12-23 09:50:24: Detection of Python Interpreter for Command python and args failed as file does not exist
~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
~\AppData\Local\Continuum\anaconda3\Scripts\conda.exe info --json
```

If you are able to activate conda from a command prompt you can then try starting vs code just by typing `code` from that activated command prompt. That can sometimes help to clear up conda issues.

**Comment by KikeSenpai** [comment] 2020-12-30 14:08
Hello @IanMatthewHuff and thanks for your answer, I opened an Anancoda command prompt, and as I am using the base environment, it was already activated, then I typed 'code' and vscode opened, when I tried to open a jupyter notebook I got the same error telling me that ipykernel is not installed in the environment.

**Comment by KikeSenpai** [comment] 2021-01-04 11:45
Hello happy new year to everyone, is there any other suggestions regarding this issue? I don't want to uninstall everything, as always it has been a problematic experience to uninstall and reinstall anaconda, thanks in advance for your help

**Comment by DonJayamanne** [comment] 2021-01-05 23:06
@KikeSenpai We've identified and resolved a related issue. The fix can be found in the attached VSIX.

1. Please could you enable logging for the Jupyter extension as follows:
* Open user settings (`Preferences: Open User Settings` & go into `Jupyter->Logging`
* Change the value to `debug`
* Reload VS Code,

2. Please could you install this copy of the VSIX (its a new version of the Python extension - we rely on that for activation of conda).
* https://pvsc.blob.core.windows.net/extension-builds-jupyter-public/ms-python-insiders.vsix
* Download & install using the command `Extensions; Install from VSIX`
* Test once again & provide the logs (for `Python` & `Jupyter`)
* If this fixes is then great, else please proceed with the next few steps.

3. Please confirm the following file exists. Error logs indicate these are missing.
`C:\Users\eaperez\AppData\Local\Continuum\anaconda3\Scripts\conda.exe`

4. Please check your settings.json file (use the command `Preferences: Open User Settings` & `Preferences: Open Worksapce Settings` to look for a setting `python.condaPath` & ensure it is valid.

5. Finally please could you run the following command in your `command prompt` (not powershell or other). & let me know what you get (please provide a screenshot if possible).
`C:/Users/eaperez/AppData/Local/Continuum/anaconda3/Scripts/activate && conda activate base && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python c:\Users\eaperez\.vscode\extensions\ms-python.python-2020.12.424452561\pythonFiles\pyvsc-run-isolated.py c:/Users/eaperez/.vscode/extensions/ms-python.python-2020.12.424452561/pythonFiles/printEnvVariables.py`

Thanks for your help in assisting us diagnose this issue.

**Comment by KikeSenpai** [comment] 2021-01-08 18:06
@DonJayamanne Thank you so much, the issue was resolved with the first 2 steps.

**Comment by DonJayamanne** [comment] 2021-01-08 23:13
Duplicate of #4248

**Closed by DonJayamanne** 2021-01-08 23:13 UTC
Labels: bug, info-needed, kernel-issues
