### ISSUE TITLE
Feature request: Choose default location of new interactive python console

### ISSUE THREAD

**Issue by jaxankey** [microsoft/vscode-jupyter#15235] opened 2024-02-24 22:17 UTC
Hi all,

When I `jupyter.runFileInteractive`, the interactive console appears to the right, but I would like it to appear below the editor. :)

Sorry if there is a way to do this, I just can't figure it out and have been searching the web for some time. I swear this used to be a feature.

Cheers,
Jack

**Comment by amunger** [comment] 2024-02-29 15:41
duplicate of https://github.com/microsoft/vscode/issues/127998

**Closed by amunger** 2024-02-29 15:41 UTC
