### ISSUE TITLE
Run Cells Above and Run Cells Below using incorrect (not selected) kernel

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5737] opened 2021-05-03 21:03 UTC
It appears to be using a different kernel versus the selected on for performing run cells above and run cells below.

**Comment by IanMatthewHuff** [comment] 2021-05-03 21:05
'debugEnv' is selected and cells are being run using that. Run above / run below are using something different. You can see in this picture that it's using groovy kernel.

![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/e6784dec-a272-46d0-9be5-6cb64fab2740)

**Comment by DonJayamanne** [comment] 2021-05-03 21:37
@IanMatthewHuff in light of https://github.com/microsoft/vscode/issues/122877
Not sure whether we should fix this issue.

Even if we fixed it, its possible for the user to select a different kernel when the hit the run button. I'd vote we hide the buttons for now.

**Comment by DavidKutu** [comment] 2021-05-03 22:01
Dupe of #5497

**Comment by DonJayamanne** [comment] 2021-05-07 02:27
To be validated on 7th May

**Comment by DavidKutu** [comment] 2021-06-11 01:19
![image](https://user-images.githubusercontent.com/20347396/121616723-4c1e1d80-ca18-11eb-87e3-3c1cba93d99d.png)
Validated (same python)

**Closed by DavidKutu** 2021-06-11 01:19 UTC
