### ISSUE TITLE
Cell output breaks notebook layout and overlaps with other content

### ISSUE THREAD

**Issue by roma-glushko** [microsoft/vscode-jupyter#4274] opened 2020-12-31 08:37 UTC
## Environment data

-   VS Code version: 1.53.0-insider(4a875e23d20b64504a818834f3fa4c40adb8d480)
-   Jupyter Extension version (available under the Extensions sidebar): v2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): v2021.1.429416775-dev
-   OS (Windows | Mac | Linux distro) and version: MacOS Catalina 10.15.5 (19F101)
-   Python and/or Anaconda version: 3.9.1 64bit
-   Type of virtual environment used: venv (poetry env use python3)
-   Jupyter server running: Local
-  Pylance version: v2020.12.2

## Expected behaviour

I want to see output of the cells beneath without overlapping with other content and freezing the notebook.

## Actual behaviour

After reruning the whole notebook or just one cell, it happens that output started to break notebook layout and some areas of the notebook start to ignore scrolling. This issue happens to rich and extensive plot output and also to simple pandas dataframe outputs. After some time, layout may back to normal and output takes its place in the layout without overlapping with other content.

## Steps to reproduce:

Notebook: https://github.com/roma-glushko/kaggle-wine-quality/blob/master/index.ipynb
![2020-12-31_10-15-53 (1)-min](https://user-images.githubusercontent.com/9402690/103401867-61327e80-4b53-11eb-8d14-5fa7c958d104.gif)

**Comment by DonJayamanne** [comment] 2021-01-04 18:20
Duplicate of https://github.com/microsoft/vscode/issues/111889

**Closed by DonJayamanne** 2021-01-04 18:20 UTC
Labels: bug
