### ISSUE TITLE
Syntax Highlighting for Python Broken

### ISSUE THREAD

**Issue by fierval** [microsoft/vscode-jupyter#8676] opened 2022-01-12 19:23 UTC
Issue Type: <b>Bug</b>

Latest release syntax highlighting appears to be buggy. Lots of error and warning squigglies out of place.

Extension version: 2021.11.1001550889
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (40.69GB free)|
|Process Argv|--folder-uri file:///c%3A/git/fetch/theia-models --crash-reporter-id 28592bab-0cbd-42c4-b35d-ec0a4bb99be1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30421291
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710:30416614
vsccppwtstudy:30421978

```

</details>

**Comment by rchiodo** [comment] 2022-01-12 19:26
Thanks for the bug. Do you have an example? 

Also can you list your Python, Jupyter, and Pylance extension versions? All 3 must be the latest for intellisense to work correctly.

**Comment by fierval** [comment] 2022-01-12 19:46
Jupyter: v2021.11.1001550889
Python: v2021.12.1559732655
Pylance: v2022.1.0

**Comment by fierval** [comment] 2022-01-12 19:50
This cell was giving me problems, it comes and goes not sure why
[prep_train_eval_example.txt](https://github.com/microsoft/vscode-jupyter/files/7857313/prep_train_eval_example.txt)
.

**Comment by rchiodo** [comment] 2022-01-12 19:57
Was it while editing the cell? What did the error look like?

Just opening it works of course:

![image](https://user-images.githubusercontent.com/19672699/149212446-f49197b2-40d8-47d8-84e5-577eb1e7f569.png)

**Comment by fierval** [comment] 2022-01-12 20:02
Problems start while editing. As I was prepping a sample everything got refreshed & fixed. I'm sure it'll come back & then I'll attach a screenshot

**Comment by rchiodo** [comment] 2022-01-12 20:05
Can you set these two settings before you repro?

```
    "notebook-intellisense.logLevel": "Trace",
    "notebook-intellisense.trace.server.verbosity": "Verbose",
```

That should generate an output tab like so that logs all of the changes sent to pylance:

![image](https://user-images.githubusercontent.com/19672699/149213458-f39d336d-56e5-42a6-bcf0-e1ea0dbe664a.png)

The name of the output tab is derived from the current kernel in the notebook.

Thanks.

That output log should let me reproduce your edits.

**Comment by fierval** [comment] 2022-01-13 00:30
I tried adding
    "notebook-intellisense.logLevel": "Trace",
    "notebook-intellisense.trace.server.verbosity": "Verbose",
into settings.json on both insider and regular editions - no effect.

**Comment by hardianlawi** [comment] 2022-01-27 07:05
Mine looks like this

![image](https://user-images.githubusercontent.com/22806872/151308356-d1733e50-7a3b-4669-910b-75e159d37a22.png)

**Comment by rchiodo** [comment] 2022-01-27 17:21
@hardianlawi how it looks doesn't really help. We need the logs I described above. When the colorization is off it means the concatenated python files under the covers doesn't match the notebook for some reason.

The logs should help us reproduce the issue so we can see where the concatenation went wrong.

**Comment by gertsfert** [comment] 2022-02-09 22:36
Hello, I am having the same issue - can trigger it by restarting the kernel, but not closing interactive prompt.

Screenshot from running same cell 5 times successively - highlighting changes every time cell is reran.
![image](https://user-images.githubusercontent.com/797446/153301765-90f1a134-c188-482d-88dd-fa6596cde47d.png)

Have attached output from the logs after changing the settings you requested @rchiodo 
[notebook_syntax_highlighting_error_logs.txt](https://github.com/microsoft/vscode-jupyter/files/8036651/notebook_syntax_highlighting_error_logs.txt)

**Comment by gertsfert** [comment] 2022-02-09 22:44
![image](https://user-images.githubusercontent.com/797446/153303034-389b85d0-b725-4ae5-9ab2-8aa2f32e0475.png)
Very peculiar - the hover over tooltip is refererring to an old name for a variable in that file, that does not exist anymore (since restarting the kernel) - and does not appear in the Jupyter:Variables view.

**Comment by rchiodo** [comment] 2022-02-09 22:52
@gertsfert I entered a new bug for you. It's likely a different cause. Can you comment on that one?

https://github.com/microsoft/vscode-jupyter/issues/8969

**Comment by rchiodo** [comment] 2022-05-04 17:11
Haven't heard any more failures related to this so assuming this is fixed for now. Pylance has been actively working on notebook support, so they likely fixed any problems.

**Closed by rchiodo** 2022-05-04 17:11 UTC
Labels: info-needed, notebook-intellisense

**Comment by hbsmith** [comment] 2022-10-31 01:03
I'm having this exact same problem since about a week ago, except it's not in a jupyter notebook it's in a regular `.py` file.

**Comment by denisprovost** [comment] 2022-10-31 13:07
Same here
