### ISSUE TITLE
Language detection and Auto complete not working

### ISSUE THREAD

**Issue by MasterKavi-24** [microsoft/vscode-jupyter#8389] opened 2021-11-30 06:01 UTC
Issue Type: <b>Bug</b>

I just got familiarized with Anaconda's Jupyter Notebook and when I learnt that VS Code also has the functionalility for Jupyter Notebook, I started using ipymb files in VS Code. It was going on nicely, until IDK what happened maybe an extension's bug or something, the langauge of code in the cell is not being detected automatically. Insetead, it shows something called CVE (Wt heck is that !?). If I manually try to set the langauge, it again becomes CVE.

Extension version: 2021.9.1101343141
VS Code version: Code 1.61.2 (6cba118ac49a1b88332f312a8f67186f7f3c1643, 2021-10-19T14:58:13.605Z)
OS version: Linux x64 5.7.0-kali1-amd64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4273)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.59GB (13.17GB free)|
|Process Argv|--unity-launch --crash-reporter-id 1df4a115-7c0f-47b7-8cc8-67ab9f87735d|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|lightdm-xsession|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis200cf:30402084
vsaa593cf:30376535
vssld246cf:30401891
vscexrecpromptc:30404946
vscop804:30404766
vscop453:30404998

```

</details>

**Comment by MasterKavi-24** [comment] 2021-11-30 06:03
Just an image of how it looks
![unnamed](https://user-images.githubusercontent.com/68172796/143994132-d1ccefea-2e0e-4d00-8b9c-081cfc8b4cb1.png)

**Comment by rchiodo** [comment] 2021-11-30 16:54
Thanks for the bug. 

This is a dupe of https://github.com/microsoft/vscode-jupyter/issues/7917. You have an extension that is forcefully changing the language for a cell to "CVE". You can either change the language back to python or uninstall that extension.

**Closed by rchiodo** 2021-11-30 16:54 UTC
Labels: needs-triage

**Comment by MasterKavi-24** [comment] 2021-12-01 12:34
Thanks @Rich, but it would be helpful if you said (texted) me
which extension might cause that. If you want me to send a list of
extensions that I have, I could do that too (is there any VSCode command to
do that ? NVM)

abusaidm.html-snippets
Adrien.VisualStudioDarkTheme
akamud.vscode-theme-onedark
albert.TabOut
AlexTi.intellij-idea-light-theme
almenon.arepl
atreyabain.bfc-server
attilabuti.brainfuck-syntax
bibhasdn.django-snippets
bigonesystems.django
buenon.scratchpads
ceciljacob.code-plus-theme
christian-kohler.path-intellisense
DanijelMalinovic.visual-studio-blue-theme
Dart-Code.dart-code
Dart-Code.flutter
ecmel.vscode-html-css
esbenp.prettier-vscode
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
GitHub.copilot
GitHub.github-vscode-theme
golang.go
helgardrichard.helium-icon-theme
jamiewest.theme-light-vs-mac
KarthikSrivantK.light-theme
malvery.darcula-pycharm-dimmed
moyu.snapcode
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode.cpptools
ms-vscode.cpptools-themes
nicohlr.pycharm
obrejla.netbeans-light-theme
parithon.vscode-snap-texteditor
redhat.fabric8-analytics
redhat.java
redhat.vscode-commons
redhat.vscode-xml
ritwickdey.LiveServer
RobbOwen.synthwave-vscode
shamanu4.django-intellisense
swimmy4days.brainfuck-syntax-highlighter
trinm1709.dracula-theme-from-intellij
vfd.vs2017-light-theme
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
wesbos.theme-cobalt2
xabikos.JavaScriptSnippets
xr0master.webstorm-intellij-darcula-theme
yurihs.sublime-vscode-theme

**Comment by rchiodo** [comment] 2021-12-01 17:58
The other issue I linked should describe which extension it is. In the issue it's called ```Dependency Analytics``` which might be your ```redhat.fabric8-analytics``` in your list. I haven't repro'd the issue myself so you'll have to try removing extensions until the CVE text no longer ends up in a cell.

**Comment by MasterKavi-24** [comment] 2021-12-02 06:25
THANK YOU SO MUCH. IT WORKS.
Can you just, y'know, share this thing in the issue that I created over
there ? It would be helpful to all others who have this problem.

Again, thanking you,

Yours sincerely,
#VSCodeLover

**Comment by MasterKavi-24** [comment] 2021-12-02 06:25
[image: image.png]
Le culprit -> redhat.fabric8-analytics (ID)
