### ISSUE TITLE
Send code selection to interactive window for R

### ISSUE THREAD

**Issue by TekeDado** [microsoft/vscode-jupyter#7684] opened 2021-09-27 21:00 UTC
It would be excellent to have support for non-Python languages getting sent to the interactive window when using a jupyter kernel. I really like being able to use '#%%' and the 'Send selection to interactive window' command to chunk scripts while testing, and since I have to use both R and Python in my work would love this feature being supported for R (and others). The Notebooks experience already does support using R and other languages quite nicely, so it would be a much appreciated extension!

**Comment by DonJayamanne** [comment] 2021-09-27 23:09
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/273

**Closed by DonJayamanne** 2021-09-27 23:09 UTC
Labels: enhancement, needs-triage
