### ISSUE TITLE
Auto refresh imports (support %autoreload magic) 

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4555] opened 2021-01-29 00:47 UTC
Or actually provide some way to make the kernel auto update when I change an external py file.

Suppose I have this:

![image](https://user-images.githubusercontent.com/19672699/106216629-6c93bc80-6188-11eb-8571-5ee9e4e23428.png)

I'm coding along and I realize I need to add something to matrix.py.

I don't want to go find the cell with the import. Just always reimport that matrix.py whenever I save it.

**Comment by rchiodo** [comment] 2021-01-29 00:48
There was some talk of this previously. (like in #1248)

**Comment by rchiodo** [comment] 2021-01-29 01:09
Well actually rerunning the first cell doesn't even work. Uggh. So this is even more important. I can't update the imports without restarting the kernel or using:

```python
import importlib
importlib.reload(matrix)
```

**Comment by DonJayamanne** [comment] 2021-02-01 21:55
Not sure this works, well.
If i use `from matrix import xyz`, then such a solution will not work.
Also this is a destruction operation as we lost all informaiton loaded into the module.
Personally I'd just restart the kernel.

**Comment by rchiodo** [comment] 2021-02-01 21:58
I don't want to lose the information already in the kernel. If the state of the kernel is the thing that's important to me, I can't iterate any longer.

**Comment by rchiodo** [comment] 2021-02-01 22:01
But the module's state is not important. Especially if it's a set of functions I'm working on.

Jupyter has this already. It's called autoreload.
https://ipython.org/ipython-doc/3/config/extensions/autoreload.html

**Comment by nfx** [comment] 2021-02-17 17:48
Would greatly improve workflows. I think we should add a button in UI to enable it.

**Comment by rchiodo** [comment] 2021-04-23 22:02
Debugpy has implemented this already. We should be able to reuse that code.
https://github.com/microsoft/debugpy/blob/2ae7dc96ecc4ca73b119c2056284d203afa10afd/src/debugpy/_vendored/pydevd/pydevd.py#L677

**Comment by nfx** [comment] 2021-05-17 10:51
@rchiodo yes, #5621 is somewhat related

**Comment by ishipachev** [comment] 2021-06-30 15:25
This is a crucial feature for me.
I'm writing my own modules, run them into notebook. And if I want to reimport updated functions I either have to restart kernel, which makes no sense as I just want to update some functions from modules, but not to restart the kernal run from the beggining. Or use the hack @rchiodo suggested.
I think if we want to use VSCode instead default Jupyter Notebook or Jupyter Lab we should have this quite popular functionality. It's really annoying not to have it and break working flow just to restart kernel if you updated a single function in it.

**Comment by rchiodo** [comment] 2022-04-14 16:07
Hmm, I thought I mentioned it here already. 

You can put this in your runStartupCommands. 

```
"jupyter.runStartupCommands": [
   "%load_ext autoreload"
   "%autoreload 2"
]
```

It's actually talked about here: https://github.com/microsoft/vscode-jupyter/issues/1542

That should cause modules to auto reload when they're written to disk. Make sure after you set the 'runStartupCommands' you reload VS code though.

**Comment by wconnell** [comment] 2022-05-13 19:55
a caveat I have experienced adding
```
"jupyter.runStartupCommands": [
   "%load_ext autoreload"
   "%autoreload 2"
]
```
is hanging jupyter cell execution, so much so I had to remove it

**Comment by Lurvetti** [comment] 2022-05-15 00:18
this would be very helpful😄

**Comment by DonJayamanne** [comment] 2022-08-22 03:20
Duplicate of #1542

**Closed by DonJayamanne** 2022-08-22 03:20 UTC
Labels: notebook-execution, notebook-workflow, feature-request
