### ISSUE TITLE
Compiling inexistent code

### ISSUE THREAD

**Issue by giammi56** [microsoft/vscode-jupyter#4100] opened 2020-12-03 14:10 UTC
## Environment data

Version: 1.51.1 (user setup)
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-10T23:34:32.027Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
ipython                   7.19.0           py38hc5df569_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour
COMPILING

## Actual behaviour
TAKING CHARACTERS FROM SOMEWHERE ELSE (maybe git?)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Sadly it is quite random, usually happens when I copy-paste. See the attached pictures for details
2. it stays upon clearing output, restarting the server, closing vccode.
3. Sometimes happens in vscode insider too
4. the only working solution is to copy the cell's content, DELETE THE CELL, create a new cell, paste the content back.

## Logs

```
Error 2020-12-02 10:27:47: Kernel died [r [Error]: [IPKernelApp] ERROR | Exception in message handler:

	at t._next (c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:47:767299)
	at t.__tryOrUnsub (c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:32:5463)
	at t.next (c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:32:4632)
	at t._next (c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:32:3736)
	at t.next (c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:32:3407)
	at t.next (c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:32:8976)
	at c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:9:108204
	at c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:47:432271
	at c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:47:432489
	at Immediate._onImmediate (c:\Users\Giammarco\.vscode\extensions\ms-toolsai.jupyter-2020.11.372831992\out\client\extension.js:47:434054)
	at processImmediate (internal/timers.js:439:21)] 
```

</p>
</details>

![image](https://user-images.githubusercontent.com/11757284/101028583-15eb7700-3579-11eb-9a7f-b24bed7448ec.png)
![image](https://user-images.githubusercontent.com/11757284/101028659-1e43b200-3579-11eb-8a6d-e03d523a3841.png)

**Comment by rchiodo** [comment] 2020-12-03 17:05
@greazer  this is another instance of the out of sync problem. We could use this as the issue to fix this.

**Comment by rchiodo** [comment] 2020-12-03 17:35
Dupe of #1701

**Closed by rchiodo** 2020-12-03 17:35 UTC
Labels: bug
