### ISSUE TITLE
Latex not rendering in HTML output (plots, widgets, etc)

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#6802] opened 2021-07-25 18:48 UTC
## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1054968649

Don't think it's related but just in case - I have the "notebook.experimental.useMarkdownRenderer": true in my settings.json

```
import ipywidgets as widgets

slider = widgets.FloatSlider(description = '$x$', value = 4)
text = widgets.FloatText(disabled = True, description = '$x^2$')

def compute(*ignore):
    text.value = str(slider.value**2)

slider.observe(compute, 'value')
widgets.VBox([slider,text])
```

![image](https://user-images.githubusercontent.com/19276747/126909934-66853c56-f89d-4bdd-8c5b-ea80ae1b7d87.png)

**Comment by joyceerhl** [comment] 2021-07-26 15:51
I can replicate this 

Classic Jupyter 
![image](https://user-images.githubusercontent.com/30305945/127018403-c158e137-b0fc-49d3-864a-a2c90d333ef0.png)


VS Code 
![image](https://user-images.githubusercontent.com/30305945/127018441-8d693b01-5cd2-40a0-8ccf-84299f82f1d9.png)

This is in our custom ipywidget output renderer. Classic Jupyter loads MathJax to render math equations, I think we would need to do the same 
![image](https://user-images.githubusercontent.com/30305945/127019700-2bc1b391-d627-480f-b709-9a719b86083b.png)

**Comment by DonJayamanne** [comment] 2021-11-02 20:32
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7801

**Closed by DonJayamanne** 2021-11-02 20:32 UTC
Labels: bug, notebook-markdown, ipywidgets
