### ISSUE TITLE
Scrolling to bottom of a notebook with a markdown cell causes everything to disappear

### ISSUE THREAD

**Issue by afspies** [microsoft/vscode-jupyter#14743] opened 2023-11-20 04:47 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

On VS Code insiders, with both preview and live Jupyter extensions, in both local and remote dev, if I:

1) Create a notebook
2) Create a markdown cell
3) Scroll down too far

Everything disappears, and reopening the notebook does not fix it (reloading the window does, but only until scrolling too far again)

see:

Thanks!

### VS Code Version

1.85.0-insider

### Jupyter Extension Version

2023.10.11000000

### Jupyter logs

```shell
Visual Studio Code - Insiders (1.85.0-insider, undefined, desktop)
Jupyter Extension Version: 2023.11.1003211000.
Python Extension Version: 2023.21.13211009.
Pylance Extension Version: 2023.11.10.
Platform: darwin (arm64).
Workspace folder ~/Desktop/playground/bug, Home = /Users/alex
13:40:56.111 [info] Start refreshing Kernel Picker (1700455256111)
13:40:56.117 [info] Using Pylance
13:40:56.308 [error] Failed to validate Password info D [FetchError]: request to http://localhost:8888/tree? failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
13:40:56.321 [error] Failed to validate Password info D [FetchError]: request to http://localhost:8888/tree? failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
13:40:56.331 [error] Failed to validate Password info D [FetchError]: request to http://localhost:8888/tree? failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
13:40:56.334 [error] Failed to validate Password info D [FetchError]: request to http://localhost:8888/tree? failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
13:40:56.335 [error] Failed to validate Password info D [FetchError]: request to http://localhost:8888/tree? failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
13:40:56.430 [error] Error fetching kernels from http://localhost:8888/ (localhost): FetchError: request to http://localhost:8888/api/kernels?1700455256320 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.430 [error] Error fetching kernels from http://localhost:8888/ (localhost): FetchError: request to http://localhost:8888/api/kernels?1700455256330 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.430 [error] Error fetching kernels from http://localhost:8888/ (localhost): FetchError: request to http://localhost:8888/api/kernels?1700455256333 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.431 [error] Error fetching kernels from http://localhost:8888/ (localhost): FetchError: request to http://localhost:8888/api/kernels?1700455256335 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.431 [error] Error fetching kernels from http://localhost:8888/ (localhost): FetchError: request to http://localhost:8888/api/kernels?1700455256336 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.431 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache FetchError: request to http://localhost:8888/api/kernels?1700455256320 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.431 [error] Jupyter Lab Helper:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
    at v.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:10935)
    at ni.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:29299)
    at r.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:133:4431)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at bD.listKernelsFromConnection (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:22642)
    at ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:20128
13:40:56.432 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache FetchError: request to http://localhost:8888/api/kernels?1700455256330 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.432 [error] Jupyter Lab Helper:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
    at v.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:10935)
    at ni.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:29299)
    at r.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:133:4431)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at bD.listKernelsFromConnection (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:22642)
    at ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:20128
13:40:56.433 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache FetchError: request to http://localhost:8888/api/kernels?1700455256333 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.433 [error] Jupyter Lab Helper:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
    at v.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:10935)
    at ni.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:29299)
    at r.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:133:4431)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at bD.listKernelsFromConnection (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:22642)
    at ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:20128
13:40:56.433 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache FetchError: request to http://localhost:8888/api/kernels?1700455256335 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.433 [error] Jupyter Lab Helper:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
    at v.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:10935)
    at ni.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:29299)
    at r.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:133:4431)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at bD.listKernelsFromConnection (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:22642)
    at ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:20128
13:40:56.438 [error] UniversalRemoteKernelFinder: Failed to get kernels without cache FetchError: request to http://localhost:8888/api/kernels?1700455256336 failed, reason: connect ECONNREFUSED 127.0.0.1:8888
    at ClientRequest.<anonymous> (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/node-fetch.js:1:306479)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
13:40:56.439 [error] Jupyter Lab Helper:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:KernelSpecManager#specs) is disposed.
    at v.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:10935)
    at ni.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/node_modules/@jupyterlab/services.js:11:29299)
    at r.dispose (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:133:4431)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at bD.listKernelsFromConnection (~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:22642)
    at ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2023.11.1003211000-darwin-arm64/dist/extension.node.js:230:20128
13:40:56.977 [warn] Failed to get activated env vars for /usr/bin/python3 in 626ms
13:40:56.978 [info] Process Execution: /usr/bin/python3 -c "import site;print("USER_BASE_VALUE");print(site.USER_BASE);print("USER_BASE_VALUE");"
13:40:57.009 [info] Process Execution: /usr/bin/python3 -m pip list
13:40:57.352 [info] End refreshing Kernel Picker (1700455256111)
13:40:57.757 [warn] No interpreter for Pylance for Notebook URI "~/Desktop/playground/bug/test.ipynb"
13:41:23.958 [info] Start refreshing Interpreter Kernel Picker
13:41:23.958 [info] Start refreshing Kernel Picker (1700455283958)
13:41:23.968 [warn] No interpreter for Pylance for Notebook URI "~/Desktop/playground/bug/test.ipynb"
13:41:25.954 [info] End refreshing Kernel Picker (1700455283958)
13:41:49.861 [warn] No interpreter for Pylance for Notebook URI "~/Desktop/playground/bug/test.ipynb"
13:41:57.467 [warn] No interpreter for Pylance for Notebook URI "~/Desktop/playground/bug/test_no_mb.ipynb"
```

### Running Jupyter locally or remotely?

Local

**Comment by Shi-YuZhang** [comment] 2023-11-20 04:48
With the same issue here.

**Comment by afspies** [comment] 2023-11-20 04:49
Here the gif:

![CleanShot 2023-11-20 at 13 41 05](https://github.com/microsoft/vscode-jupyter/assets/14139469/bcca2947-7b99-4ece-8b74-e9ef9a0e92cf)

**Comment by DonJayamanne** [comment] 2023-11-20 04:55
Thanks you for filing this issue and sorry you are running into this.
This issue ahs been idenfied and resolved.
The fix will be in tomorrows release of VS Code insiders.
Apologies for the inconvience.

Closing as a duplicate of https://github.com/microsoft/vscode/issues/198639

**Closed by DonJayamanne** 2023-11-20 04:55 UTC
Labels: bug

**Comment by afspies** [comment] 2023-11-20 05:33
Wow that was fast! Thank you :)

**Comment by DonJayamanne** [comment] 2023-11-20 05:56
> Wow that was fast! Thank you :

having users on insiders and  reporting issues on GitHub helps us stay on top of things, so thank you
