### ISSUE TITLE
`python.tensorBoard.logDirectory` doesn't support predefined variables and relative path

### ISSUE THREAD

**Issue by PillarsZhang** [microsoft/vscode-jupyter#9677] opened 2022-04-12 18:07 UTC
Issue Type: <b>Bug</b>

# Behaviour

## Steps to reproduce:

1. Suppose the current working path is `D:/workspace_tmp`, with TensorBoard event files in `D:/workspace_tmp/runs`
2. Set up setting of `python.tensorBoard.logDirectory`.
3. Run command "Python: Launch Tensorboard".

## Expected vs. Actual

| `python.tensorBoard.logDirectory` | TensorBoard webview                                | Expected path         |
|-----------------------------------|----------------------------------------------------|-----------------------|
| .                                 | . [No dashboards are active]                       | D:\workspace_tmp      |
| runs                              | runs [No dashboards are active]                    | D:\workspace_tmp\runs |
| ${workspaceFolder}/runs           | ${workspaceFolder}/runs [No dashboards are active] | D:\workspace_tmp\runs |
| D:\workspace_tmp\runs             | D:\workspace_tmp\runs [Works fine]                 | D:\workspace_tmp\runs |
| [empty]                           | [quick pick]                                       |                       |

When I execute `tensorboard --logdir=./runs` in the shell, it works fine. But when I set `"python.tensorBoard.logDirectory" = "./runs"`, run command "Python: Launch TensorBoard", The TensorBoard page that launches prompts me as follows:

![No dashboards are active for the current data set.](https://user-images.githubusercontent.com/13759663/163016698-2a413021-9081-46e4-93c7-27f9013da58e.png)

No errors in the log.

```
[INFO 2022-3-12 22:46:15.999]: Using log directory specified by python.tensorBoard.logDirectory setting: ./runs
[DEBUG 2022-3-12 22:46:15.999]: Cached data exists getEnvironmentVariables, <No Resource>
> D:\Folders\Users\zhang\anaconda3\python.exe ~\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\tensorboard_launcher.py ./runs
[INFO 2022-3-12 22:46:16.41]: Starting TensorBoard with log directory ./runs...
[INFO 2022-3-12 22:46:16.343]: Starting TensorBoard with logdir ./runs
[ERROR 2022-3-12 22:46:25.552]: INFO:pytorch_profiler:Monitor runs begin
```

During debugging, I found that in [`pythonFiles/tensorboard_launcher.py`](https://github.com/microsoft/vscode-python/blob/e157943a1dc7edfff238e1acdf7e57e3dd6558fc/pythonFiles/tensorboard_launcher.py), command `os.getcwd()` outputs `C:\Users\zhang\AppData\Local\Programs\Microsoft VS Code`.  The working directory in Python script is wrong. TensorBoard cannot find the log directory by relative path.

There is also no support for predefined variables such as ${workspaceFolder}, which is displayed as a same string on the TensorBoard page.

So my idea is to store and pass fully resolved absolute paths to `pythonFiles/tensorboard_launcher.py`, I've tried it 182af46a33ecc5cc5453d8dcc5f0d62bc52899ac, I'm not sure if there's a better solution.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.1
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by rchiodo** [comment] 2022-04-13 16:51
Thanks for the detailed information. I believe this is a dupe of this issue here: https://github.com/microsoft/vscode-jupyter/issues/8802

**Closed by rchiodo** 2022-04-13 16:51 UTC
Labels: needs-triage, classify
