### ISSUE TITLE
Open ipynb file garbled

### ISSUE THREAD

**Issue by XiaoTianJianJun** [microsoft/vscode-jupyter#5802] opened 2021-05-07 09:03 UTC
Issue Type: <b>Bug</b>

After updating version 1.56, there will be garbled code when opening ipynb file directly with vscode. Only when you open the folder with vscode and then open ipynb from the folder can you use it normally

Extension version: 2021.6.811652604
VS Code version: Code 1.56.0 (cfa2e218100323074ac1948c885448fdf4de2a7f, 2021-05-04T22:09:06.405Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2236 CPU @ 3.40GHz (12 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (21.89GB free)|
|Process Argv|--crash-reporter-id a7481430-7956-444c-8925-13ce2a0d0ccf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602cf:30294773
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvsnew554cf:30291488
pythontb:30283811
pythonvspyt551cf:30291415
vspre833cf:30267465
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30286553

```

</details>

**Comment by XiaoTianJianJun** [comment] 2021-05-07 09:04
![image](https://user-images.githubusercontent.com/63184972/117426295-51d69e00-af56-11eb-9668-1d70ecc6ab84.png)
just like this

**Comment by Xinyu-Wu-0000** [comment] 2021-05-07 11:34
vscode-insiders also has this problem

Version: 1.57.0-insider
Commit: 6bee0f2f3fea9df1ad45344f09b2a139c93b384f
Date: 2021-05-07T08:17:31.522Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.11.0-16-generic

when I used `open in notebook editor` to manually open it, I got extention activate failed` error.

**Comment by giuseppefilitto** [comment] 2021-05-07 12:59
@claudiaregio  I think this is a duplicate of this:  #5794

**Comment by DonJayamanne** [comment] 2021-05-07 15:40
Duplicate of

**Closed by DonJayamanne** 2021-05-07 15:40 UTC

**Comment by DonJayamanne** [comment] 2021-05-07 15:59
> I got extention activate failed` error.

Please could go into the developer tools (command palette `Toggle Developer Tools`) and go into the console window, next check if there are errors, and please paste them here.
