### ISSUE TITLE
Refresh buttion for data viewer

### ISSUE THREAD

**Issue by Victsz** [microsoft/vscode-jupyter#4625] opened 2021-02-03 14:21 UTC
After open the data viewer on certain dataframe, there is no way to refresh viewer when the underlying data is updated.

Alsoa minor issue - failed to copy (ctrl+c) text from the data viewer tab.

**Comment by rchiodo** [comment] 2021-02-03 17:40
Thanks for the suggestion. This is a dupe of #https://github.com/microsoft/vscode-jupyter/issues/1143

**Closed by rchiodo** 2021-02-03 17:40 UTC
Labels: enhancement
