### ISSUE TITLE
Turtle widgets support is just not workin ... and always giving error of "error loading nbextensions/mobilecheloninjs/turtlewidget" 

### ISSUE THREAD

**Issue by arpan02122004** [microsoft/vscode-jupyter#8241] opened 2021-11-11 20:21 UTC
## Environment data

-   VS Code version: 1.62
-   Jupyter Extension version (available under the Extensions sidebar): 2021.10.1001414422
-   Python Extension version (available under the Extensions sidebar): 2021.11.1
-   OS (Windows | Mac | Linux distro) and version: windows 10 build 19042
-   Python and/or Anaconda version: 3.9.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): n.a
-   Jupyter server running: Local | Remote | =  local

## Expected behaviour

it should show the turtle widget and start plotting and show the diagram....

## Actual behaviour

it just do not show the widget of turtle and gice eroor of attribule eroor in "t.pensize" which is valid and shows widget to download support file but in the final it does nothing . and give more errors

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. just use this valid code . 
2. from mobilechelonian import Turtle
from ipywidgets import interact
import turtle
t = Turtle()
t.pencolor("red")
turtle.begin_fill()
t.pensize(3)
t.left(50)
t.forward(113)
t.circle(50,200)
t.right(140)
t.circle(50,200)
t.forward(133)
turtle.end_fill()
input()

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

"Eroor given by jupyter :- "
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_1972/308323382.py in <module>
      5 t.pencolor("red")
      6 turtle.begin_fill()
----> 7 t.pensize(3)
      8 t.left(50)
      9 t.forward(113)

AttributeError: 'Turtle' object has no attribute 'pensize'

<p>

```
Arpan kumar 
```

</p>
email : - arpankumar11119@gmail.com 
note :- add support for turtle also in jupyter vs code ....
</details>

**Comment by arpan02122004** [comment] 2021-11-11 20:22
you can check the code also if it is wrong tell me ... and ... also tell be briefly why turtle is working out of the box in this case like annaconda jupyter ........

**Comment by DonJayamanne** [comment] 2021-11-11 20:59
I've had a look at the code, and looks like the widget is written in such a way that it will only work on Jupyter.
The root cause is one of the JS files is looking for code in nbextensions folder as follows:
```js
define(['nbextensions/mobilechelonianjs/paper', "@jupyter-widgets/base"], function(paperlib, widget){
```

We could probably try to pre-emptively register all of these.


@arpan02122004 , Unfortunately for now I cannot find a workaround for this issue, I'll take a look at this.

**Comment by arpan02122004** [comment] 2021-12-14 10:44
what is the root cause of this ..... anything can be done to fix this .....?

**Comment by DonJayamanne** [comment] 2021-12-14 16:50
> what is the root cause of this

The root cause had been clearly documented , in the previous comment.

 >anything can be done to fix this .....?

Unfortunately this issue hasn't been priotized yet, we prioritize issues based on community engagement (upvotes) and usage.

**Comment by DonJayamanne** [comment] 2022-06-17 00:14
I'm closing this as fixed, as I can no longer repro this and the fix for #10319 should fix this as well.
@arpan02122004 If this doesn't work in the ltest jupyter pre-release version, please do let us know and we'll re-open this issue or optionally please feel free to create a new issue.

**Comment by rchiodo** [comment] 2022-06-30 18:44
The example provided here does not work for me. No output is shown and the jupyter log shows this:

```
nfo 11:44:30.478: Widget Message: WidgetManager: Loading class LayoutModel:@jupyter-widgets/base:1.2.0
info 11:44:30.515: Widget Message: WidgetManager: Loading class DOMWidgetModel:@jupyter-widgets/base:1.2.0
info 11:44:30.685: Widget Message: WidgetManager: Loading class TurtleView:nbextensions/mobilechelonianjs/turtlewidget:
info 11:44:30.685: Widget Message: WidgetManager: failed, Loading class TurtleView:nbextensions/mobilechelonianjs/turtlewidget:
error 11:44:30.685: Widget load failure {} {
  className: 'TurtleView',
  moduleName: 'nbextensions/mobilechelonianjs/turtlewidget',
  moduleVersion: '',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: '{}'
}
```

**Comment by rchiodo** [comment] 2022-06-30 18:46
This probably has some impact on the issue - I'm using raw kernels.

**Comment by DonJayamanne** [comment] 2022-06-30 23:06
Notes:
* Install `mobilecheloniajs`
* Have a look at widgets an see whether it uses `_view_module` when loading the script files.
    * We might want to support that.

Heres the source from the widgets
```python
    pkgdir = os.path.dirname(__file__)
    nbextensions.install_nbextension(os.path.join(pkgdir, 'mobilechelonianjs'),
                                     user=True)

class Turtle(widgets.DOMWidget):
    _view_module = Unicode("nbextensions/mobilechelonianjs/turtlewidget").tag(sync=True)
    _view_name = Unicode('TurtleView').tag(sync=True)
```

**Closed** 2022-07-05 20:31 UTC
Labels: bug, ipywidgets, specific-to-package-library, verification-found
