### ISSUE TITLE
Unable to open Notebooks in Insiders

### ISSUE THREAD

**Issue by sztal** [microsoft/vscode-jupyter#5804] opened 2021-05-07 15:01 UTC
Issue Type: <b>Bug</b>

It seems that the last update crashed Jupyter notebook extension.

It cannot find `jupyter.opennotebook` function/object presumably need for opening `.ipynb` files in the Notebook Editor. Moreover, there seems to be some even deeper problem going in the core of the extension which probably cannot load some sort of a configuration file (or so it seems according to the console log in Developer Tools. Below I paste the javascript erorr trace generated in my  particular case and raised at `workbench.desktop.main.js:62`:

```
[Extension Host] extension activation failed TypeError: o.getConfiguration(...).get(...).find is not a function
    at new m (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:683169)
    at Object.t.resolveInstance (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:263270)
    at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262475
    at Object.t.resolve (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262738)
    at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253835
    at e._get (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253601)
    at e.get (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:252313)
    at a.get (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:90:509426)
    at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:245341
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825686
    at t.activate (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825373)
    at async Promise.all (index 0)
    at async Promise.all (index 88)
    at async Promise.all (index 1) (at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:826205)
```

Extension version: 2021.6.819764235
VS Code version: Code - Insiders 1.57.0-insider (6bee0f2f3fea9df1ad45344f09b2a139c93b384f, 2021-05-07T08:17:31.522Z)
OS version: Linux x64 5.11.0-7614-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|15.52GB (6.13GB free)|
|Process Argv|--unity-launch --crash-reporter-id ea2cc0b8-cf43-49b3-a0ce-43755c989cd5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by DonJayamanne** [comment] 2021-05-07 15:14
Thanks for filling this issue, I'll look into this asap.

**Comment by DonJayamanne** [comment] 2021-05-07 16:26
Yup, i too can replicate this.

**Comment by joyceerhl** [comment] 2021-05-07 20:09
This should be fixed in the latest VS Code Insiders build:

Version: 1.57.0-insider (user setup)
Commit: a19565da7dfc739fa26e36aae96113e19fe3806f
Date: 2021-05-07T17:19:03.737Z

@sztal could you please update VS Code Insiders and let us know if the issue persists? Thanks and sorry for the trouble!

**Comment by sztal** [comment] 2021-05-07 20:18
Hi, many thanks for such a quick reaction! However, it seems the problem still persists.

I updated VS Code correctly, I think (below is the version info I get after updating):

```
code-insiders --version
# OUTPUT
# 1.57.0-insider
# a19565da7dfc739fa26e36aae96113e19fe3806f
# x64
```

The errors I see in Developer Tools seems to be identical. And crucially, when I inspect settings I still see that:

```
"workbench.editorAssociations": [
        {
            "viewType": "jupyter.notebook.ipynb",
            "filenamePattern": "*.ipynb"
        }
    ],
```

is marked with a warning `Incorrect type. Expected "object"` and from what I could understand from the above discussions in the issue tickets the problem was related to some incompatibilities in how this config item is represented, right? So unfortunately it seems the problem is not solved yet.

**Comment by Hanuphant** [comment] 2021-05-07 20:44
The same issue is affecting me too.

**Comment by joyceerhl** [comment] 2021-05-07 20:44
@sztal To be clear, you cannot open notebooks even after upgrading?

The warning is benign. TLDR VS Code has changed the layout for this setting, but internally they are supposed to still recognize the old format (though we are likely going to upgrade to the new layout, see https://github.com/microsoft/vscode-jupyter/issues/5806). There was a bug that caused their backward compatibility code to fail which we're told has since been fixed. But if you can't open notebooks at all then the problem is somewhere else.

**Comment by joyceerhl** [comment] 2021-05-07 20:45
@Hanuphant, are you on the latest VS Code Insiders? There was an update that shipped 3 hours ago which should have resolved this.

**Comment by Hanuphant** [comment] 2021-05-07 20:47
> 
> 
> @Hanuphant, are you on the latest VS Code Insiders? There was an update that shipped 3 hours ago which should have resolved this.

Yes, it is still not working. Updated 10 mins ago.

**Comment by sztal** [comment] 2021-05-07 20:49
@joyceerhl , yes, I still cannot open any notebook. In some cases they are opened as plain text .json files and in some cases VS Code just hangs while trying to open them. And also, all the errors I mentioned earlier are still there in the DevTools Console. In  particular, there is this one which looks probably most worrying (raised at `workbench.desktop.main.js:62`):

```
extension activation failed TypeError: o.getConfiguration(...).get(...).find is not a function
    at new m (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:683169)
    at Object.t.resolveInstance (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:263270)
    at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262475
    at Object.t.resolve (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262738)
    at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253835
    at e._get (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253601)
    at e.get (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:252313)
    at a.get (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:90:509426)
    at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:245341
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825686
    at t.activate (/home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825373)
    at async Promise.all (index 0)
    at async Promise.all (index 88)
    at async Promise.all (index 1) (at /home/sztal/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:826205)
S @ workbench.desktop.main.js:sourcemap:62
```

**Comment by Hanuphant** [comment] 2021-05-07 20:52
Currently, from the dev view there are 4 errors and 3 warnings shown now. The update did fix a 5th one which appeared earlier in the day. 

<html>
<body>
<div tabindex="-1" class="console-message-wrapper console-from-api console-error-level console-selected" role="treeitem" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: var(--error-border-color); border-bottom: 1px solid transparent; background-color: rgb(41, 0, 0); color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">workbench.desktop.main.js:1799</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;">Unable to instantiate workbench contribution f. <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read property 'windowsExec' of undefined
    at f._refreshOpenInTerminalMenuItemTitle (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:1973</span>)
    at new f (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:1973</span>)
    at g._createInstance (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:625</span>)
    at g.createInstance (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:625</span>)
    at S.safeCreateInstance (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:1799</span>)
    at S.doInstantiateByPhase (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:1799</span>)
    at <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">workbench.desktop.main.js:1799</span></span></span></span></span></div><div class="" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | safeCreateInstance | @ | workbench.desktop.main.js:1799
-- | -- | -- | --


</span></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-from-api console-error-level" role="treeitem" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: var(--error-border-color); border-bottom: 1px solid transparent; background-color: rgb(41, 0, 0); color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><span is="ui-icon" class="message-level-icon spritesheet-smallicons smallicon-error" aria-label="Error" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: inline-block; flex: 1 1 auto; position: absolute; left: -17px; top: 4px; user-select: none; background-position: var(--spritesheet-position); background-image: url(&quot;Images/smallIcons.svg&quot;); --spritesheet-position:-40px 70px; width: 10px; height: 10px;"></span><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span is="ui-icon" class="console-message-expand-icon spritesheet-smallicons smallicon-triangle-down icon-mask" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: inline-block; flex-shrink: 0; margin-bottom: -2px; background-color: rgb(145, 145, 145); -webkit-mask-position: var(--spritesheet-position); -webkit-mask-image: url(&quot;Images/smallIcons.svg&quot;); --spritesheet-position:-80px 30px; width: 10px; height: 10px;"></span></div></div></div></div></div><br class="Apple-interchange-newline">
</body>
</html>

(node:17900) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders --trace-deprecation ...` to show where the warning was created) (at writeOut (internal/process/warning.js:43:3))

Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.

workbench.desktop.main.js:62 [Extension Host] extension activation failed TypeError: o.getConfiguration(...).get(...).find is not a function
	at new m (c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:683169)
	at Object.t.resolveInstance (c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:263270)
	at c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:262475
	at Object.t.resolve (c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:262738)
	at c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:253835
	at e._get (c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:253601)
	at e.get (c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:252313)
	at a.get (c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:90:509426)
	at c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:52:245341
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:37:825686
	at async t.activate (c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:37:825373)
	at async Promise.all (index 0)
	at async Promise.all (index 89)
	at async Promise.all (index 1) (at c:\Users\shreyash\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.819764235\out\client\extension.js:37:826205)

The aforementioned are the errors I am seeing now.

**Comment by joyceerhl** [comment] 2021-05-07 20:58
Yep I repro the bug. Assigning to myself for investigation. Thanks for letting us know.

**Comment by joyceerhl** [comment] 2021-05-07 21:13
@DonJayamanne It's working for you because your settings.json still contains the old editorAssociations setting format. If you delete it, this code here falls over and crashes activation:

https://github.com/microsoft/vscode-jupyter/blob/94ff177acccd69f520c023924a15402e0279b093/src/client/common/experiments/service.ts#L64-L70

**Comment by joyceerhl** [comment] 2021-05-07 21:32
As a temporary workaround @sztal and @Hanuphant, you can replace the workbench.editorAssociations setting with the following:

```
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter-notebook",
            "filenamePattern": "*.ipynb"
        }
    ]
```

I assume both of you have intentionally opted out of the native notebooks UI. However this will allow the Jupyter extension to activate. We're working on a fix for this (basically we need to support reading the new setting format that VS Code has introduced, which is the default layout now).

**Comment by sztal** [comment] 2021-05-07 21:36
Thanks! But now I am a bit confused. I did not want to opt out from the native notebooks UI. As a matter of fact it was the reason I started to use VS Code Insiders in the first place. So does it mean that I could have opted out somehow accidentally? And if so, how can I check this?

**Comment by joyceerhl** [comment] 2021-05-07 21:39
Do you have `"jupyter.experiments.optOutFrom": [ "NativeNotebookEditor" ]` or `"jupyter.experiments.enabled": false` set anywhere in your settings.json? 

The "jupyter.notebook.ipynb" viewType is for our custom editor implementation of notebooks. So you shouldn't have that entry there. The "jupyter-notebook" viewType is for our native notebooks implementation.

**Comment by sztal** [comment] 2021-05-07 21:41
But in the meantime, I confirm that your solution works (and I still have new native notebooks).

I think that this `jupyter.notebook.ipynb` was somehow added during upgrading of VS Code, but I am not sure. However I really do believe that it was just `jupyter-notebook` earlier. Nonetheless, now I corrected the settings and everything seem to be fine.

So once again, thanks a lot for solving it so quickly!

**Comment by Hanuphant** [comment] 2021-05-07 21:54
> 
> 
> Do you have `"jupyter.experiments.optOutFrom": [ "NativeNotebookEditor" ]` or `"jupyter.experiments.enabled": false` set anywhere in your settings.json?
> 
> The "jupyter.notebook.ipynb" viewType is for our custom editor implementation of notebooks. So you shouldn't have that entry there. The "jupyter-notebook" viewType is for our native notebooks implementation.

Yeah, I did have `"jupyter.experiments.optOutFrom": ["NativeNotebookEditor"]` in my settings.json. 

I am quite new to this, will you be able to help me out with workbench.editorAssociation . Do I have to add that code in settings.json?

**Comment by joyceerhl** [comment] 2021-05-07 22:01
Yup, you would delete the existing "workbench.editorAssociations" key and value, and replace it with this snippet:

```
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter-notebook",
            "filenamePattern": "*.ipynb"
        }
    ]
```

**Comment by Hanuphant** [comment] 2021-05-07 22:14
> 
> 
> Yup, you would delete the existing "workbench.editorAssociations" key and value, and replace it with this snippet:
> 
> ```
>     "workbench.editorAssociations": [
>         {
>             "viewType": "jupyter-notebook",
>             "filenamePattern": "*.ipynb"
>         }
>     ]
> ```

Thanks a lot @joyceerhl & devs. It worked!!!

**Comment by flipphillips** [comment] 2021-05-07 23:26
I too was using Insider for the native view capability.

**Comment by joyceerhl** [comment] 2021-05-07 23:30
@flipphillips are you also unable to open notebooks in insiders? Does this workaround help?: https://github.com/microsoft/vscode-jupyter/issues/5804#issuecomment-834794393

**Comment by flipphillips** [comment] 2021-05-07 23:33
@joyceerhl - I see what the problem is/was, that the settings format is different now than what was in the synced settings (I had other associations in there too).

It appears that this manual fix worked, thanks!

**Comment by flipphillips** [comment] 2021-05-08 00:27
Groovy - makes sense. I'll do the best to pass on the secret sauce to my students. Ironically, I was just showing them the cool/better notebook interface in class, then they got home and couldn't get it to work because of this :) Such is living on the edge.

**Comment by joyceerhl** [comment] 2021-05-08 03:53
@flipphillips Yeah, sorry about the snafu. Team is out for the week but we should have this fixed Monday.

**Comment by joyceerhl** [comment] 2021-05-11 00:36
Closing as this should have been resolved with today's update. Please feel free to open a new issue if otherwise. Thanks everyone for your patience and for reporting a bug!

**Closed by joyceerhl** 2021-05-11 00:36 UTC
