### ISSUE TITLE
Problems in interactive Window dont show while filter "only active file" is selected

### ISSUE THREAD

**Issue by Idontknowwhatimdoing1234** [microsoft/vscode-jupyter#7500] opened 2021-09-13 20:49 UTC
Issue Type: <b>Bug</b>

Problems in the code in the interactive Window dont show while filter "Show active file only" is selected.

Extension version: 2021.8.2041215044
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (7.77GB free)|
|Process Argv|--crash-reporter-id 95a45aab-3aae-4c29-9d68-2e8384463666|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedc2:30360494
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgsc2:30361791
vscus224:30358039
vssid140:30363603
vssur157:30365996

```

</details>

**Comment by DavidKutu** [comment] 2021-09-13 21:21
Thanks for filing @Idontknowwhatimdoing1234 

We'll discuss in our next triage meeting.

**Comment by amunger** [comment] 2022-08-15 17:53
I'm not sure what setting this is referring to or exactly what the issue is. Please provide repro steps and screenshots here or in a new issue to clarify if this is still relevant. Closing for now

**Closed by amunger** 2022-08-15 17:53 UTC
Labels: bug, notebook-intellisense, interactive-window, notebook-workflow
