### ISSUE TITLE
veiwing numpy complex data with Data Viewer

### ISSUE THREAD

**Issue by kopalx** [microsoft/vscode-jupyter#6536] opened 2021-07-06 06:00 UTC
Data Viewer does not display numpy complex data

**Comment by IanMatthewHuff** [comment] 2021-07-06 20:01
@kopalx Could you provide an example notebook that illustrates this? Not fully sure what type of complex data you are referring to here.

**Comment by kopalx** [comment] 2021-07-07 05:21
Hi,
I mean complex number. For instance, invoke following code and view it with the data viewer:

import numpy as np
aaa = np.array([1+j,1-j])

BR,
Alex

**Comment by greazer** [comment] 2021-07-08 20:35
Dupe of #1610

**Closed by greazer** 2021-07-08 20:35 UTC
Labels: info-needed
