### ISSUE TITLE
Kernel Picker - Native Notebooks 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#1206] opened 2020-08-17 23:25 UTC
# Kernel Picker Artifact: 

## Design/Location: 
- Kernel picker to be moved to status bar in bottom left. 
- Python Interpreter to be hidden for notebooks. 
- Kernel picker and connection string to the right of it. 

## Experience: 

- Kernel picker will be generated in status bar **per notebook**. 
- Local: (local *white connected icon*)

- Remote: 
1. If custom display string available, display (remote: custom string *white connected icon*) 
    https://github.com/microsoft/vscode-python/issues/12988
2. If no custom display available, display (remote *white connected icon*)
3. When hovering over the remote string, hover tip to display full url. 

- Clicking the kernel picker will result in quick pick menu options. 
- When new option selected, kernel picker to update. 

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by DonJayamanne** [comment] 2021-01-11 17:03
Duplicate of #254

**Closed by DonJayamanne** 2021-01-11 17:03 UTC
Labels: enhancement, internal contributor, vscode-notebook
