### ISSUE TITLE
Better line numbers in interactive window notebooks

### ISSUE THREAD

**Issue by ArthurConmy** [microsoft/vscode-jupyter#12208] opened 2022-11-29 22:06 UTC
Errors in interactive notebooks are highlighted on the line _in the current cell_  that they're in 

![image](https://user-images.githubusercontent.com/35957051/204658468-b5988a40-2c7d-47da-86a8-6304f97e5a3e.png)

If either

i) line numbers were adjusted so that I could easily search for the line 3 at fault
ii) the stacktrace was about line 7

this would be easier to read

**Comment by amunger** [comment] 2022-12-05 16:59
What you are hoping for should already be implemented, ideally with links to the specific line. (although the line numbers are off by one for me when I just checked) 

@ArthurConmy - can you provide the `ipython` and `ipykernel` versions that you are using

```
import ipykernel
import IPython
print('ipykernel ', ipykernel.__version__)
print('IPython ', IPython.__version__)
```

**Comment by ArthurConmy** [comment] 2022-12-05 19:59
@amunger 

```
ipykernel  6.17.1
IPython  7.29.0
```

**Comment by amunger** [comment] 2023-03-02 18:40
duplicate of this issue for IPython7 https://github.com/microsoft/vscode-jupyter/issues/11002
Ipython8 should work correctly

**Closed by amunger** 2023-03-02 18:40 UTC
Labels: bug, interactive-window, notebook-output
