### ISSUE TITLE
"Socket is busy writing" error when interacting with large dataset using ipyleaflet in VS code

### ISSUE THREAD

**Issue by bacusters** [microsoft/vscode-jupyter#10188] opened 2022-05-31 12:28 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I'm using the Python ipyleaflet package to plot large polylines (~3000 points), using notebooks in VS code. After adding a polyline layer with lots of points to the leaflet map and dragging around/interacting with the ipyleaflet map widget for a while, I start getting the following error in the (Chrome) Developer Tools console:

```
Error: Socket is busy writing; only one send operation may be in progress at any time
	at l.postToSocket (c:\Users\20184217\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:548327)
	at c:\Users\20184217\.vscode\extensions\ms-toolsai.jupyter-2022.4.1021342353\out\extension.node.js:2:548251
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
which then repeats whenever I interact with the map.

As soon as this happens, no cell in the notebook will run anymore until after one or more restarts of the Jupyter kernel. I'm not entirely sure whether this is a vscode-jupyter problem or ipyleaflet, could be that the communication socket is overloaded by the amount of data?

To reproduce, run the code below and pan/zoom for a time until the errors start popping up.
```Python
import ipyleaflet
import random
map_ = ipyleaflet.Map(center=(10,0),scroll_wheel_zoom=True)
def random_float(min_value,max_value): 
    return random.random() * (max_value-min_value) + min_value
map_.add_layer(ipyleaflet.Polyline(locations=[[random_float(9,11),random_float(-1,1)] for i in range(3000)]))
map_
```
This may be related to [https://github.com/zeromq/zeromq.js/issues/381](https://github.com/zeromq/zeromq.js/issues/381), though I'm not knowledgeable enough about the vscode-jupyter codebase to properly assess this?

### VS Code Version

1.67.2

### Jupyter Extension Version

v2022.4.1021342353

### Coding Language and Runtime Version

Python v3.9.7

### Anaconda Version (if applicable)

miniconda 4.11.0

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment] 2022-05-31 16:27
Thanks for the issue. It might be a ZMQ problem. 

There is a workaround that you might try. Set this hidden setting:

```
"jupyter.disableZMQSupport": true
```

That forces us to use jupyter to communicate with a kernel instead of us talking to it directly. You might also have to run this command afterwards though: 

![image](https://user-images.githubusercontent.com/19672699/171225563-d980f13e-ce87-49fe-8ca1-f246d9967f88.png)

That picks a python interpreter for us to use for running jupyter. You'd select one that has jupyter installed. It doesn't have to be the same one you're running your kernel with.

**Comment by DonJayamanne** [comment] 2022-12-05 23:12
Duplicate of #10386

**Closed by DonJayamanne** 2022-12-05 23:12 UTC
Labels: bug, ipywidgets, zmq
