### ISSUE TITLE
Jupyter notebook on vscode hung on "Reconnecting to the kernel..."

### ISSUE THREAD

**Issue by subhashbylaiah** [microsoft/vscode-jupyter#12860] opened 2023-02-16 23:34 UTC
## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: MacOS Ventura 13.2 on Mac M2 Pro
-   Python and/or Anaconda version: 3.10.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local

Issue: 

When I try to run a cell in a jupyter notebook, in VSCode, I get a notification saying "Reconnecting to the kernel ...". Once the notebook kernel gets into this state it just hangs. I have seen reports of this issue here: https://github.com/microsoft/vscode-jupyter/issues/12775
Most often this issue appears right on the second cell (the first cell has imports, which runs fine)

I have change JupyterLogging in vscode and here's a snippet of the log where the error appears:

```
debug 17:18:46.657: VSCodeNotebookController::handleExecution, Class name = _v (started execution)
debug 17:18:46.658: Execute Cell 1 /Users/sbylaiah/Development/cibo/science-analysis/forestry/growing_circles_interpolation.ipynb
debug 17:18:46.658: start the kernel, options.disableUI=false for /Users/sbylaiah/Development/cibo/science-analysis/forestry/growing_circles_interpolation.ipynb
debug 17:18:46.658: Start Jupyter Session in kernel.ts with disableUI = false
everything 17:18:46.658: Telemetry Event : DATASCIENCE.EXECUTE_CELL Measures: undefined Props: {"resourceType":"notebook","resourceHash":"9d6d3d9cd2e2d6a50f5ce0bc7b1b27c62b6fe9861a73984b88ccc8ecd67ba0c3","kernelSessionId":"4e276b0c7c6c54e8771a9d537feab5eb61af200a418fb9a555372f0a58e48d85","capturedEnvVars":"true","userExecutedCell":"true","kernelLanguage":"python","kernelId":"3fe2e62653679ad6038039b4c5c39b6a2daeb83d1f96a46858fa01c593c3a373","pythonEnvironmentType":"Conda","pythonEnvironmentPath":"c3c994132db5243e8c8e4ce449b457b71d2254d179f718ff80131ceaa3c20b02","pythonEnvironmentVersion":"3.10.9","kernelConnectionType":"startUsingPythonInterpreter","pythonEnvironmentPackages":"{\"10179407bb8db6eccacc6da9ca62c2bbbb03bceec4db91e8a021d473e26a5d6c\":\"6.21.2\",\"89e1278be8b894a35e73eaa5c2afd0f745961fd702a4704b2d9c4f1e825f3671\":\"NOT INSTALLED\",\"9916a5fb8a8d51c1412e88aed98e4404cd55f7b96a71c51d539b3cc15ca1eb97\":\"NOT INSTALLED\",\"897912f1d7a38112511452e440bf4c54ef8e57a665e40648e89207d6628a2fd8\":\"7.3.2\",\"3ce399db4dc985069ce539ac0a6cb94e8dd3d49f36dd0b747f88e01358991251\":\"NOT INSTALLED\",\"d927ca7348e5732e599cad20c03d6e3a685e4ebffdb0af3535e1070009a9f978\":\"NOT INSTALLED\",\"d3e7ab21472587eb5ec6e05d0463e93a0b01f604b20c3def0e395b82a268fde5\":\"NOT INSTALLED\",\"94e6eda30eae4335f771fb7e325569f30a9795fd919105b9710e95fdc94e0d66\":\"NOT INSTALLED\",\"b53bcf919f24746d72094b8b86c0325cf40723d3d63240705db51a27b261bc96\":\"NOT INSTALLED\",\"d60b76184370a4ed8fd706458d5bbf85163af824d90732dd0f2e0c0897cd1c68\":\"25.0.0\",\"904075f7a02bc2bda9f4d0cb02f379d7f97c1c0470a4d646ddb5e2ff60ef0793\":\"NOT INSTALLED\",\"83716a35515f728928d7ce0aaa73e3445679d939169124b88fec90b522c45179\":\"6.1\",\"840eb2c1c4b04492f16d4affecb7e8d16837e3aaa81f0df570a65851411acb60\":\"5.9.0\"}","isInsiderExtension":"false","isPythonExtensionInstalled":"true","rawKernelSupported":"false","VSCode.ABExp.Features":"livesharecontinuousaa;reusableLinks;RemoveKernelToolbarInInteractiveWindowcf;portForwardingServiceEnabled-development;portForwardingServiceEnabled-staging;portForwardingServiceEnabled-production;jupyterTest;pylanceIndexingEnabled;NativeNotebookEditor;jupyterEnhancedDataViewer;mindaroBinariesVersion;mindaroBinariesVersion-1.0.20210702;mindaroBinariesVersion-1.0.20210723;account-aacf;shouldUseGrpcService;config.jupyter.showOnlyOneTypeOfKernel;config.python.analysis.indexing;gettingStarted.overrideCategory.vscode.typescript-language-features.nodejsWelcome.when;pylanceAutoIndent;config.autoImportUserSymbolscf","abexp.assignmentcontext":"vsliv368:30146709;vsreu685:30147344;python383cf:30185419;vspor879:30202332;vspor708:30202333;vspor363:30204092;vsjup275:30257433;pythonvspyl392:30443607;vsjup518:30340749;pythondataviewer:30285071;binariesv615:30325510;bridge0708:30335490;bridge0723:30353136;vsaa593cf:30376535;c4g48928:30535728;dsvsc012cf:30540253;pyindex848:30662994;nodejswelcome1cf:30587006;pyind779:30662992;pythonsymbol12cf:30657549;","isamlcompute":"false"} 
debug 17:18:46.658: Start cell 1 execution @ 1676589526658
[E 17:18:54.383 NotebookApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/Users/sbylaiah/miniconda3/envs/deepcdl/lib/python3.9/site-packages/tornado/iostream.py", line 702, in _handle_events
        self._handle_write()
      File "/Users/sbylaiah/miniconda3/envs/deepcdl/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/Users/sbylaiah/miniconda3/envs/deepcdl/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
        assert 0 < size <= self._size
    AssertionError
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/Users/sbylaiah/miniconda3/envs/deepcdl/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/sbylaiah/miniconda3/envs/deepcdl/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/Users/sbylaiah/miniconda3/envs/deepcdl/lib/python3.9/site-packages/tornado/iostream.py", line 702, in _handle_events
    self._handle_write()
  File "/Users/sbylaiah/miniconda3/envs/deepcdl/lib/python3.9/site-packages/tornado/iostream.py", line 976, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/Users/sbylaiah/miniconda3/envs/deepcdl/lib/python3.9/site-packages/tornado/iostream.py", line 182, in advance
    assert 0 < size <= self._size
AssertionError
```

However, like others have reported in the referenced issue, I do not see errors related to ZeroMQ in the stack trace.

**Comment by DonJayamanne** [comment] 2023-02-17 03:15
duplicate of https://github.com/microsoft/vscode-jupyter/issues/12775?notification_referrer_id=NT_kwDOAB28jLI1NTQzMzU1OTQ5OjE5NDg4MTI#issuecomment-1433883946

stack trace still points to tornado upstream

**Closed by DonJayamanne** 2023-02-17 03:15 UTC
Labels: bug, notebook-kernel
