### ISSUE TITLE
Saving file to local filesystem results in NoPermissions error

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#5270] opened 2021-03-24 20:29 UTC
When I generate an image in a Python session on a remote connection, I typically want to save these images locally. However, I am now getting a NoPermissions error when I do so:

```
Error exporting image: NoPermissions (FileSystemError): Unable to write file 'vscode-remote://ssh-remote+7b22686f73744e616d65223a224e5959415753227d/Users/cfonnesbeck/Downloads/no_clusters.png' (NoPermissions (FileSystemError): Error: EACCES: permission denied, mkdir '/Users')
```

This is being saved in a subdirectory of my personal account, so there should be no permissions error. I have tried other subdirs, but with similar effect.

- VSCode Version: 1.54.3
- Local OS Version: macOS 11.3
- Remote OS Version: Ubuntu
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Generate image in Python
2. Open image in plots tab
3. Select save icon
4. Select local filesystem from file browser
5. Save to local folder (e.g. Downloads or Desktop)

**Comment by rchiodo** [comment] 2021-03-24 21:55
Dupe of #5269

**Closed by rchiodo** 2021-03-24 21:55 UTC
Labels: bug
