### ISSUE TITLE
Select kernel causing EH restart (Win 10 Pro 22H2)

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13564] opened 2023-05-25 21:09 UTC
From marketplace https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details

> VCS and J notebooks don't work any more. When I try to select kernel, it simply restarts endlessly, then I see a very useful message "Extension host terminated unexpectedly 3 times within the last 5 minutes", offering me options to start Bisect or restart extension host. Neither of them helps, as I simply can't select a kernel with Bisect running, and if I chose to restart extension, the bug show goes on. Vicious circle. So instead of coding I have to waste my time with this buggy products.

> It seems that the newer version of VSC - the more bugs are introduced. Could you please consider testing VCS better before producing a new release?

> UPDATE - I managed to get it to work by downgrading Python extension v2023.2.0 and Jupyter extension to v2023.1.2000312134.

> What a poor release process you have, guys. Please stop releasing a lot and start testing a lot!

This might be caused by our zmq change but at the same time, in another review it's saying downgrading Python extension fixed their kernel issues https://github.com/microsoft/vscode-jupyter/issues/13517

**Comment by JRiggles** [comment] 2023-06-01 14:54
For what it's worth, I started having this issue after updating Code to v1.78.2. I haven't been able to update the `ms-python.python` or `ms-toolsai` (Jupyter) extensions because VS Code says that neither is compatible with Code v1.78.2. I'm currently running v2022.15.12501015 of `ms-python.python` and v2022.6.1001741036 of `ms-toolsai` (Jupyter), both of which were working fine under Code v1.74.3

Is it safe to assume the only solution is to downgrade VS Code back to v1.74.3?

**Comment by DonJayamanne** [comment] 2023-06-02 01:17
@JRiggles sorry you are running into this.
Please could you try the following
* Uninstall Jupyter and Python extension
* Reload VS Code
* Install the Python extension from within VS Code itself
* Open a Python file and verify the extension host does not crash, if it does, then we know Python extension is causing the crashs
* Next go into the command palette and select the command `Select Interpreter` and in the quick pick please click the `Refresh` icon on the top right 
* Wait for everything to fisnih
* Verify the extension host does not crash.

If you have got to this stage, then we know Python extension does not cause any crashes
* Next uninstall Python extension 
* Reload VS Code
* Install Jupyter extension 
* Open a Jupyter Notebook or a Python file
* Check if the extension host crashes
* Go into the kernel picker and see whether the extension host crashes.
* If nothing crashes at this stage, then we know its not the Jupyter extension nor Python extension that causes the crash
* Next install the Python extension and reload VS Code
* Go back into the kernel picker and attempt to select a kernel again.

Let me know at what point the Extension Host crashes
and the versions of the extensions installed

I understand this is a slow process, however this will help us narrow down the problem. and help us move forward.

**Comment by JRiggles** [comment] 2023-06-05 12:44
@DonJayamanne Thanks for all the info! 

One slight hiccup: the machine I develop on is air-gapped (no internet connection). Is it possible to download the things I need from direct links? I was able to upgrade my installed version of `ms-python.python` from v2022.15.12501015 to v2023.8.0 following instructions on a similar issue here. 

FWIW, everything Python-related is working as expected with the Jupyter extension disabled. However, even after updating the Python extension I'm still seeing the `Extension host terminated unexpectedly` error when I re-enable Jupyter and try to run a cell.

**Comment by DonJayamanne** [comment] 2023-06-05 13:14
Thank you
 please could you provide your OS information?
What platform (wineries, Linux, Mac) and what distro/version are you on?

**Comment by JRiggles** [comment] 2023-06-05 13:18
I'm currently running Windows 10 Pro, 22H2

**Comment by DonJayamanne** [comment] 2023-06-05 20:20
Thank you, after the extension host restarts, please could you go into the Jupyter Output panel and let me know what you see.
To get to the Jupyter Output panel, please use the following options to get there
* Open the output window on the bottom, use the command `View: Toggle Output` to display the bottom output panel
* On the right hand side of the panel is a dropdown with different names, one of them will be `Jupyter`
* Please click on the dropdown and select `Jupyter`
* Please copy the contents of the output (specially towards the end, as that might contain more information about the extension host crash)

**Comment by DonJayamanne** [comment] 2023-06-05 20:38
btw, I have tested this at my end and it works, I suspect its causing the EH crash due to some reason that might be specific to your machine hence the need for the logs.

**Comment by lugres** [comment] 2023-06-07 21:33
Hi, even after downgrading it's very buggy. So now I can't select anything else apart from Python 3.10.4.
When I click "Select Another Kernel..." nothing happens, I just wait endlessly but no kernels appear.
The most interesting thing is that VScode detected that I've created virtual environment and proposed to use it, but instead it just selected my global environment for the new .ipynb file I've created.

At the same time when I use command palette "Jupyter: Select Interpreter to Start Jupyter Server", there's a list of all possible environments which are installed on my MacBook (including Python 2.7.x which was shipped with MacOS, 3.8.2 and 3.10.4 which I installed at some stages, and 3.10.4 'env':venv which I created for my project). But the problem is that selecting venv here doesn't have any effect, regular Python 3.10.4 remains for my .ipynb file (see above).

So the question is how all this written? Why the functionality has such gaps when one module has no clue that other environments exist, whereas other modules see them?

**Comment by DonJayamanne** [comment] 2023-06-07 21:57
> So the question is how all this written? Why the functionality has such gaps when one module has 

the program is it works on one machine and not the other (you are comparing Mac with windows)
python extension and Jupyter extension are completely different extensions

> now I can't select anything else apart from Python 3.10.4.

Not sure what you have downgraded
If you downgrade Jupyter extension then downgrade python extension as well, as Jupyter relies on the api expressed by python extension

please  can you provide the information requested here
https://github.com/microsoft/vscode-jupyter/issues/13564#issuecomment-1577420850

Also please can you open the developer tools via the command ‘Toggle Developer Tools’ then go into the console window are share any error messages from there when the extension host crashes

**Comment by lugres** [comment] 2023-06-07 22:12
It's a bit funny, as that was me who originally posted a one star rating here:
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details

I just clicked on the stars of Jupyter extension inside the 'Extentions' pallet and posted the review. Probably the link under the stars points to the market place for Windows users? Ha-ha, one more bug needs to be fixed. But it's OK, just life with Microsoft products as it is :)

I returned back to my review and found out that you've created a GitHub issue and posted a link which points here.
I have no clue why you decided that I used Windows. I was using MacOS when I was writing my review, and I continue to do this.

As I've noted in my review, I managed to solve the original problem by downgrading Python extension v2023.2.0 and Jupyter extension to v2023.1.2000312134. I did this after reading another user's review "To fix "kernel issue" you should install previous downgrade your python extension."

I don't see any error messages inside ‘Toggle Developer Tools’, only a bunch of CSS classes.

**Comment by DonJayamanne** [comment] 2023-06-07 22:21
> I have no clue why you decided that I used Windows. I was using MacOS when I was writing my review, and I continue to do this.

Oh I’m very  Sorry I got confused with another user commenting on this issue
https://github.com/microsoft/vscode-jupyter/issues/13564#issuecomment-1576790169

Please could share this information,  I am after the Jupyter logs
https://github.com/microsoft/vscode-jupyter/issues/13564#issuecomment-1577420850

**Comment by DonJayamanne** [comment] 2023-06-07 22:26
> Than my question is - are you really interested in resolving the issue the users of your product are reporting? Don't you see a numerous o

as mentioned earlier, I do want to help you
Just got confused with another user commenting on this same issue and automatically assumed your comments was from the same user
And I do apologise for that error on my part

**Comment by DonJayamanne** [comment] 2023-07-18 20:54
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Closed by DonJayamanne** 2023-07-18 20:54 UTC
Labels: bug, info-needed, extension-host-crash
