### ISSUE TITLE
Refactor/Cleanup preferred controller and controller registration and related code

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#11988] opened 2022-11-11 00:00 UTC
* Remove the following code in loadControllersImpl
```
// This is temporary, when we create an MRU list in VS Code or the like, this should go away.
```

**Comment by rebornix** [comment] 2022-12-09 19:13
this is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/11914

**Closed by rebornix** 2022-12-09 19:13 UTC
Labels: debt, notebook-kernel-picker
