### ISSUE TITLE
UInt64 numbers are trimmed in DataViewer

### ISSUE THREAD

**Issue by isvoboda** [microsoft/vscode-jupyter#14514] opened 2023-10-16 10:01 UTC
## Environment data

-   VS Code version: 1.83.1
-   Jupyter Extension version: v2023.9.1102792234
-   Python Extension version: v2023.18.0
-   Python and/or Anaconda version: 3.10.12
-   Type of virtual environment used: venv
-   Jupyter server running: Local

## Expected behaviour
UInt64 DataFrame numbers previewed in DataViewer.

## Actual behaviour

UInt64 numbers are trimmed in DataViewer.

## Steps to reproduce:

![dataframe-view-bug](https://github.com/microsoft/vscode-jupyter/assets/8103900/d906bfdc-17c7-46c9-8e7a-c9db4f9863c9)

**Comment by amunger** [comment] 2023-12-14 23:49
dupe of https://github.com/microsoft/vscode-jupyter/issues/12538

**Closed by amunger** 2023-12-14 23:49 UTC
Labels: bug, data-viewer
