### ISSUE TITLE
Show more in notebook output doesn't work

### ISSUE THREAD

**Issue by dandiep** [microsoft/vscode-jupyter#7207] opened 2021-08-19 21:11 UTC
## Environment data

-   VS Code version: 1.59.0 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1236758218
-   Python Extension version (available under the Extensions sidebar): 2021.8.1147840270
-   Mac OS Big Sur
-   Python 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Clicking on show more used to open up the logs in a new window.

## Actual behaviour

Now it shows a JSON of the data that should be used (see screenshot)

<img width="940" alt="Screen Shot 2021-08-19 at 14 05 42" src="https://user-images.githubusercontent.com/64021/130144436-ead722c6-4a74-4ddb-a72f-3839fa68c564.png">
<img width="1213" alt="Screen Shot 2021-08-19 at 14 05 50" src="https://user-images.githubusercontent.com/64021/130144417-fc9fc0ef-7573-439a-8390-05aa01315a27.png">

## Steps to reproduce:

Just click "Show more" 

## Logs

If there are some specific logs you need, please let me know.

**Comment by DonJayamanne** [comment] 2021-08-19 22:40
Thanks for filing this issue.
This will be fixed in the next release of VS Code.

Duplicate of https://github.com/microsoft/vscode/issues/130187

**Closed by DonJayamanne** 2021-08-19 22:40 UTC
Labels: bug, needs-triage

**Comment by dandiep** [comment] 2021-08-19 22:44
Thanks!
