### ISSUE TITLE
Failed to launch Data Viewer when debugging pandas in docker container

### ISSUE THREAD

**Issue by miaoz2001** [microsoft/vscode-jupyter#6705] opened 2021-07-17 02:28 UTC
Issue Type: <b>Bug</b>

Hi,

When I tried to view a pandas variable in data viewer, it failed with the error
![image](https://user-images.githubusercontent.com/3375172/126022165-103af758-491f-4b44-9e76-a955428261f5.png)
![image](https://user-images.githubusercontent.com/3375172/126022182-ffd12442-2ca5-4d37-95d5-501702435c01.png)

The project is running in docker container with debugpy.

While when I tried on another simple project, it worked
![image](https://user-images.githubusercontent.com/3375172/126022032-d2a03f06-c3a0-4e1c-aed9-cd168d6deb2a.png)
This project is WSL2 too, but not in a docker.

I am not sure container or debugpy is related, but that's one difference I can tell.

Extension version: 2021.8.1013163132
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.03GB free)|
|Process Argv|--disable-features=CalculateNativeWinOcclusion --crash-reporter-id 47d8d639-de3e-449c-b652-748dde3ee1d5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2591)|
|Memory (System)|12.27GB (3.16GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt700cf:30270857
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30322572
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255:30335481
vscod805cf:30301675
pythonvspyt200cf:30331938
vscextlangct:30333562
binariesv615:30325510
vsccppwt:30329788
bridge0708:30335490

```

</details>

**Comment by DavidKutu** [comment] 2021-07-19 18:22
Thanks for the issue @miaoz2001. Please share your logs for us to be able to find the issue.
To find them:
- repro your issue
- go to the output panel
- select `Jupyter` on the top right
- copy all your logs and share them here

Thanks in advance.

**Comment by miaoz2001** [comment] 2021-07-20 00:21
Hi @DavidKutu , thanks.
here is the log
```
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'pythonDeprecatePythonPathcf'
User belongs to experiment group 'NativeNotebookEditor'
Info 2021-07-17 12:00:12: ZMQ install verified.
Info 2021-07-17 12:00:12: Attempting to start a server because of preload conditions ...
Error 2021-07-17 12:07:10: Error: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'vscodeGetVariableInfo'

    at S.handleErrorResponse (vscode-file://vscode-app/c:/Users/***/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:983:31745)
    at vscode-file://vscode-app/c:/Users/***/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:983:31129
```

**Comment by greazer** [comment] 2021-07-22 20:22
This is a dupe of #4065

**Comment by rchiodo** [comment] 2022-03-03 23:20
@miaoz2001 I reopened your original bug instead as it's specific to docker.

**Comment by DonJayamanne** [comment] 2023-01-27 04:57
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Closed by DonJayamanne** 2023-01-27 04:57 UTC
Labels: bug, info-needed, data-viewer
