### ISSUE TITLE
Documentation on hover not working

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode-jupyter#8348] opened 2021-11-24 15:30 UTC
## Environment data

-   VS Code version: 1.63.0-insider c1f2f40bcd81380bf2e286af64becddada57db88 x64
-   Jupyter Extension version (available under the Extensions sidebar): v2021.11.1001498571
-   Python Extension version (available under the Extensions sidebar): v2021.12.1496310747-dev
-   PylanceExtension version (available under the Extensions sidebar): v2021.11.3-pre.1
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04
-   Python and/or Anaconda version: python 3.9.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running:  Remote 

It seems that the docstring doesn't appear when I hover on a piece of code. Like for instance the documentation doesn't show up when I hover on `Overpass`. However autocompletion still works.

![image](https://user-images.githubusercontent.com/28219244/143267001-ffe5f2b6-a21d-4836-bb0a-08b79c6416e0.png)

**Comment by IanMatthewHuff** [comment] 2021-11-24 19:24
@rchiodo can confirm. But you mentioned that you are running on a remote Jupyter server? I believe that in this case our language server support is a bit more limited (we are relying on just what the Jupyter server provides in that case instead of the full language server support) so that is why you are not seeing docstrings.

**Comment by Syndorik** [comment] 2021-11-24 19:48
Well I think I was seeing the docstring before, like 1 or 2 weeks ago (sorry I went on holidays, so can't confirm the exact date of when it broke).

**Comment by rchiodo** [comment] 2021-11-29 17:17
Yes hover shouldn't work with remote. Only autocomplete as we get that from the jupyter server. Pylance isn't running on the remote machine so it doesn't have the environment in order to provide the necessary information.

**Comment by rchiodo** [comment] 2021-11-29 21:21
This should be a dupe of https://github.com/microsoft/vscode-jupyter/issues/8285

**Closed by rchiodo** 2021-11-29 21:21 UTC
Labels: bug, needs-triage
