### ISSUE TITLE
Jupyter Adds Duplicates to Intellisense of regular python modules

### ISSUE THREAD

**Issue by mishamsk** [microsoft/vscode-jupyter#12229] opened 2022-11-30 17:35 UTC
Type: <b>Bug</b>

1. Set-up python environment
2. Create a python notebook
3. Execute any command (effectively starting up a kernel)
4. Create a regular python module
5. Use intellisense for method/attribute lookup - everything is duplicated

Expected behavior: Jupyter should not affect regular python files (at least unless they have code cell tags)

Screenshots:
<img width="635" alt="CleanShot 2022-11-30 at 12 25 35@2x" src="https://user-images.githubusercontent.com/5206955/204868501-6d03d0bc-7ea9-44d4-9beb-4653ca1cda29.png">
<img width="738" alt="CleanShot 2022-11-30 at 12 25 57@2x" src="https://user-images.githubusercontent.com/5206955/204868510-8a5607cd-35fd-4b4c-8d18-eb0e0dd542bf.png">

Extension version: 2022.9.1303220346
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment] 2022-12-02 01:51
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/11038

**Closed by DonJayamanne** 2022-12-02 01:51 UTC
