### ISSUE TITLE
Logging crashes VS Code

### ISSUE THREAD

**Issue by bmaingret** [microsoft/vscode-jupyter#9692] opened 2022-04-15 10:49 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When outputting a lot of logging information in notebook or interactive window, VS Code puts CPU, RAM and Disk usage at max and either froze, becomes unresponsive or crashes.

![image](https://user-images.githubusercontent.com/1751970/163562009-b3147ea1-9c6d-45f1-8dde-d3fa607a19aa.png)
![image](https://user-images.githubusercontent.com/1751970/163562029-cd99f1cb-71c4-4430-abba-93b9bccdf4cf.png)

This does not happen when using `jupyter notebook` or `jupyter lab` in the browser.
This happens in Windows and when using WSL2.

Step to reproduce
```python
import logging

ch = logging.StreamHandler()
ch.setLevel(logging.INFO)

logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.addHandler(ch)

for i in range(100000):
    logger.info(f"debug {i}")

```

### VS Code Version

1.66.2

### Jupyter Extension Version

v2022.3.1000901801

### Jupyter logs

```shell
From where?
```

### Coding Language and Runtime Version

Python-3.9.7

### Language Extension Version (if applicable)

v2022.4.1

### Anaconda Version (if applicable)

4.12.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment] 2022-04-15 15:34
This looks like a duplicate of this vs code issue: https://github.com/microsoft/vscode/issues/146768

**Closed by amunger** 2022-04-15 15:34 UTC
Labels: bug, needs-triage
