### ISSUE TITLE
Enhancement: Use python installed plotly.min.js instead of renderer.

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#8373] opened 2021-11-26 16:04 UTC
Adding `fig.update_layout(legend_groupclick="toggleitem")` ([as documented](https://plotly.com/python/reference/layout/#layout-legend-groupclick)) to the [grouped legend items](https://plotly.com/python/legend/#grouped-legend-items) example does not affect legend click behavior in VS Code. It _does_ when opening the figure in a browser. This appears to be because VS Code Jupyter ships with an outdated version of plotly.js.

Posted earlier: plotly/plotly.py#3488
Related: #2648

```py
import plotly.graph_objects as go


fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=[1, 2, 3],
        y=[2, 1, 3],
        legendgroup="group",  # this can be any string, not just "group"
        legendgrouptitle_text="First Group Title",
        name="first legend group",
        mode="markers",
        marker=dict(color="Crimson", size=10),
    )
)

fig.add_trace(
    go.Scatter(
        x=[1, 2, 3],
        y=[2, 2, 2],
        legendgroup="group",
        name="first legend group - average",
        mode="lines",
        line=dict(color="Crimson"),
    )
)

fig.add_trace(
    go.Scatter(
        x=[1, 2, 3],
        y=[4, 9, 2],
        legendgroup="group2",
        legendgrouptitle_text="Second Group Title",
        name="second legend group",
        mode="markers",
        marker=dict(color="MediumPurple", size=10),
    )
)

fig.add_trace(
    go.Scatter(
        x=[1, 2, 3],
        y=[5, 5, 5],
        legendgroup="group2",
        name="second legend group - average",
        mode="lines",
        line=dict(color="MediumPurple"),
    )
)

# No effect from this line
fig.update_layout(legend_groupclick="toggleitem")
```

**Comment by jackthepanisher** [comment] 2021-11-28 19:24
If you want to stay within VS code, a possible workaround is to use a different renderer for Plotly. Only the default `vscode` renderer will use the old plotly.js but others will use the plotly.js from the installed Plotly Python package:
```Python
fig.show(renderer='notebook')
```
Alternatively, this can be set for all `fig.show()` calls:
```Python
import plotly.io as pio
pio.renderers.default = 'notebook'
```

I believe the https://github.com/microsoft/vscode-notebook-renderers is responsible for supplying the plotly.js that is used for the `vscode `renderer. Currently, that plotly.js is version 2.2.1 while the one from Plotly package 5.4.0 uses already version 2.6.3 of plotly.js.

**Comment by janosh** [comment] 2021-11-28 19:28
Thanks for the help! `fig.show(renderer='notebook')` fixes the issue! Still a bummer that this doesn't work out of the box. There must be a better solution than bundling a really old plotly in the default renderer.

**Comment by janosh** [comment] 2021-11-28 19:34
The fact that there's no error message makes this a particularly pernicious issue. Most users will first suspect their own code to be the problem, then think plotly doesn't work as advertised. I'd never have thought of the possibility that the version of plotly used might not be the one I installed.

**Comment by rchiodo** [comment] 2021-11-29 21:32
We probably just need to get this to go through:
https://github.com/microsoft/vscode-notebook-renderers/pull/78

**Comment by janosh** [comment] 2021-11-30 10:20
@rchiodo Maybe there's a more permanent solution than manually updating deps? Is there still a reason not to use the user-installed plotly.js? Having a version mismatch between what users expect to be running and what VS Code Jupyter actually uses will always be a source for confusion.

**Comment by rchiodo** [comment] 2021-11-30 16:57
> @rchiodo Maybe there's a more permanent solution than manually updating deps? Is there still a reason not to use the user-installed plotly.js? Having a version mismatch between what users expect to be running and what VS Code Jupyter actually uses will always be a source for confusion.

I don't think we realized plotly.js could be installed in the user's environment. Are you talking about as a jupyter extension or is it included in the plotly python package? We'd have to investigate, but for widgets we couldn't use javascript from python packages because it doesn't work in VS code. It all depends upon what plotly does.

**Comment by janosh** [comment] 2021-11-30 17:10
> It all depends upon what plotly does.

@rchiodo In that case it might best to hear @nicolaskruchten's advice. There's a lot going on in [`plotly.py/setup.py`](https://github.com/plotly/plotly.py/blob/7f50aff6a427d3479553f8e5ec1531b0f72cd10f/packages/python/plotly/setup.py) which would take me a while to understand.

But plotly.py _must_ come with its own version of plotly.js in some shape or form or else the fix suggested by @jackthepanisher of doing `fig.show(renderer='notebook')` at the end wouldn't suddenly let the `legend_groupclick="toggleitem"` work as expected. Considering how simple the fix is, I'd imagine it can't be hard for VS Code Jupyter to simply hand over to it and dispense with the bundled plotly.js.

**Comment by rchiodo** [comment] 2021-11-30 17:23
```fig.show(renderer='notebook')``` must inline the renderer into the output then. Yeah it does. Mime type that comes back is 'text/html' instead of 'application/vnd.plotly.v1+json'.

Might be easier for us to just force the renderer to be notebook than try to find the plotly.min.js file on disk and get the renderer to load that (it won't load js files from outside of the extension folder I believe)

**Comment by rchiodo** [comment] 2021-11-30 19:04
Question now becomes:
- Do we try to fix this automatically?
- If we yes, do we
- Try to load the plotly.min.js in the ```Lib\site-packages\plotly\package_data``` folder (probably by copying that entire folder to a subfolder under the renderer extension)
- or
- Force 'renderer=notebook' in some pre code that runs before we run any cells.

**Comment by jackthepanisher** [comment] 2021-11-30 20:04
Afaik, the Plotly Python API for graph objects is generated from the javascript code so that makes it somehow bundled to the Python package version of Plotly. It also seems that minor version differences in Plotly.js don't necessarily lead to errors with a different Python Plotly API version so it wouldn't break anything immediately. Of course feature parity is missing then.

Not sure what the reason(s) for VS Code using its own supplied version of Plotly.js is but there probably is some. Maybe to avoid having to load Plotly.js per cell instead of once per notebook? If there is a good reason for using its own version it maybe is ok to get it from the installed Python package. Of course there could be different Plotly versions per Python kernels as well. Using just the notebook renderer might also be fine but not sure about the caveats. BTW, the classic Jupyter notebook uses the notebook renderer but JupyerLab also uses the mime-type renderer.

**Comment by janosh** [comment] 2021-11-30 20:32
> Force 'renderer=notebook' in some pre code that runs before we run any cells.

@rchiodo Do you know what code that would be? [Didn't see a way](https://plotly.com/python/configuration-options) to set the renderer globally. Happy to add it to my notebook startup commands and try it out for a while if that's possible though. Since I'm using plotly quite heavily lately, potential caveats should come up.

I guess one consideration is the file size of exported notebooks. Says [here](https://plotly.com/python/renderers/#interactive-renderers):

> The `notebook` renderer is intended for use in the classic Jupyter Notebook (not JupyterLab). The full plotly.js JavaScript library bundle is added to the notebook the first time a figure is rendered, so this renderer will work without an Internet connection.

> Note: Adding the plotly.js bundle to the notebook adds a few megabytes to the notebook size. If you can count on always having an Internet connection, you may want to consider using the `notebook_connected` renderer if notebook size is a constraint.

> `notebook_connected` renderer is the same as `notebook` renderer, except the plotly.js JavaScript library bundle is loaded from an online CDN location. This saves a few megabytes in notebook size, but an Internet connection is required in order to display figures that are rendered this way.

**Comment by DonJayamanne** [comment] 2021-11-30 20:50
I don't think we should try to load the plotly.js from users Python folders.
I think we should treat that seprately as an enhancement. and keep the renderes updated with the latest version.
Tying the renderers with the version of the Python extension can be a separate issue and feature of the Jupyter extension (else we end up with too much knowledge in renderer about python environments).

the renderers is designed to work in github.dev, vscode.dev, etc, anywhere, even when using Julia or other kernels.

Hence for simplicity, i'd like to treat the concept of pulling `plotly.js` from python environments as a seprate feature request. To date we haven't had that issue. RIght now the problem is we're not using the latest in the renderers.
We could probably write a simple CI action to trigger a failure in Jupyter extesnion when ever a new version of plotly.js is released, so that we can just update the renderers exension (i.e. to ensure we don't forget to update it).
Or we update the renderers extension every month with the latest plotly.js. Either or.

**Comment by DonJayamanne** [comment] 2021-11-30 20:51
I'll try to update plotly.js some time today

**Comment by nicolaskruchten** [comment] 2021-12-03 01:44
Hey folks!

@archmoj has the following PR open, which I believe is what's needed to get things synced up again? https://github.com/microsoft/vscode-notebook-renderers/pull/78 

The attribute which isn't working in the issue description above [comes from Plotly.js 2.4.0](https://github.com/plotly/plotly.js/releases/tag/v2.4.0) and I can make patterned bar charts now in VSCode Notebooks, and those came out in 2.0.0, so the version that I seem to have is probably from https://github.com/microsoft/vscode-jupyter/pull/6552 and is around 2.2?

cc @alexcjohnson

**Comment by jackthepanisher** [comment] 2021-12-03 09:32
It looks like Plotly.js already got bumped to version 2.6.4 with the 'Jupyter Notebook Renderers' extension 1.0.4. So this should be solved now. Also the newly added Smith Charts are working for me now with the default 'vscode' renderer in VS Code.

**Comment by nicolaskruchten** [comment] 2021-12-03 14:39
OK, interesting. I do seem to have the `Jupyter Notebook Renderers` extension in my VSCode now, although I don't remember installing it, and it said "reload required" and once that was done, Smith Charts do work! As does `fig.update_layout(legend_groupclick="toggleitem")` which was the original topic of this PR :)

Looks like this works because of https://github.com/microsoft/vscode-notebook-renderers/pull/80 which supersedes https://github.com/microsoft/vscode-notebook-renderers/pull/78, so thanks @DonJayamanne !

I'll note that we released Plotly.js 2.7.0 last night, and we anticipate 2.8.0 within 10 days ;)

**Comment by DonJayamanne** [comment] 2021-12-03 17:53
I'm sorry, yes I did update plotly in the renderer to 2.6.4. I'll update it to 2.7.0 on monday.
I'll get the PR ready.

**Comment by rchiodo** [comment] 2021-12-03 21:39
Don's PR should have fixed the immediate issue. The longer term idea of just using the installed plotly.min.js can be tracked as an enhancement I think.

**Comment by janosh** [comment] 2022-05-05 08:51
I encountered a new problem that looks like it could also be caused by the bundled `plotly.min.js`.

`px.imshow(auto_text=True)` has no effect in the IW and Jupyter notebooks. But when I write the plot to disk, it shows heatmap values as expected.

```py
import plotly.express as px

z = [
    [0.1, 0.3, 0.5, 0.7, 0.9],
    [1, 0.8, 0.6, 0.4, 0.2],
    [0.2, 0, 0.5, 0.7, 0.9],
    [0.9, 0.8, 0.4, 0.2, 0],
    [0.3, 0.4, 0.5, 0.7, 1],
]

fig = px.imshow(z, text_auto=True)
fig.show()
fig.write_image("heatmap.png")
```

### In IW and Jupyter

![Screen Shot 2022-05-05 at 09 42 14](https://user-images.githubusercontent.com/30958850/166890482-d5ef22fb-e32e-4239-88f5-8d3695f5bc58.png)

### `heatmap.png`

![matbench-heatmap](https://user-images.githubusercontent.com/30958850/166890787-6b2e3894-44e0-4a15-be52-caf13bd83bee.png)

**Comment by DonJayamanne** [comment] 2022-05-05 09:12
will look into this thinks

**Comment by nicolaskruchten** [comment] 2022-05-05 10:59
(the latest version of Plotly.js is 2.12, and the feature that powers the auto-text above came out in 2.8)

**Comment by jackthepanisher** [comment] 2022-05-05 17:50
This is because the updated vscode-notebook-renderer extension has not made it to a release yet, see https://github.com/microsoft/vscode-notebook-renderers/issues/102

Would be nice if the renderer could be released with a similar cadence than the Jupyter extension and integrating the latest dependencies like Plotly.

**Comment by janosh** [comment] 2022-05-23 11:08
Working with heatmaps a lot atm and seeing the values would be very helpful. I see https://github.com/microsoft/vscode-notebook-renderers/issues/102 was merged but not released yet?

**Closed** 2023-12-01 01:08 UTC
Labels: plot-viewer, ipywidgets, feature-request, jupyter-output

**Comment by janosh** [comment] 2023-12-01 01:14
Bit off-topic but in case you're looking at plotly issues atm, rendering latex in interactive window is still broken but looks fine in exported images (as PDF, SVG, PNG).

![Screenshot 2023-11-30 at 5 12 41 PM](https://github.com/microsoft/vscode-jupyter/assets/30958850/c9f50451-0b08-4de3-a1da-5ec261ac7a67)

**Comment by DonJayamanne** [comment] 2023-12-01 02:19
> Bit off-topic but in case you're looking at plotly issues atm, rendering latex in interactive window is still broken but looks fine

Thanks for reoprting this.
There is an issue tracking this, and we are aware of this.
Sorry we haven't fixed that yet.
https://github.com/microsoft/vscode-jupyter/issues/8131

Please do upvote that issue.
