### ISSUE TITLE
Remove old kernels

### ISSUE THREAD

**Issue by austinmw** [microsoft/vscode-jupyter#12582] opened 2023-01-19 15:46 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Hi, I deleted kernels using:

```bash
NAME=myenv
conda env remove --name NAME
jupyter kernelspec uninstall NAME
```

However even after restarting VS Code, they still show up in the kernel selection list. How can I update this list to remove the kernels? They don't show up when I run `conda env list` or `Jupiter kernelspec list`, so I'm not sure where this info is being saved.

### VS Code Version

Insiders - latest

### Jupyter Extension Version

v2023.1.2000141019

### Coding Language and Runtime Version

Python3

### Anaconda Version (if applicable)

conda 4.8.4

### Running Jupyter locally or remotely?

Remote

**Comment by DonJayamanne** [comment] 2023-01-19 19:27
Closing as a duplicate of #6164, 
this has been fixed in the latest pre-release version (you'll need vscode insiders to test that out for now), or wait for the next release to get this fix

**Comment by austinmw** [comment] 2023-01-19 20:50
@DonJayamanne Hi, I have a fully up to date version of Insiders and still face this issue..

**Comment by DonJayamanne** [comment] 2023-01-20 00:25
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Also**
* Also please let me know what kernelspec should not appear in the list
* And please could you try clicking the `refresh` button on the top right hand corner of the kernel picker & then share the logs

**Comment by DonJayamanne** [comment] 2023-03-01 02:50
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Closed by DonJayamanne** 2023-03-01 02:50 UTC
Labels: bug
