### ISSUE TITLE
Two python versions listed in the status bar

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-jupyter#4090] opened 2020-12-02 21:50 UTC
Issue Type: <b>Bug</b>

**Repro** 
1. With the python extension installed
1. Open a python file
1. Then open a `ipynb` file
 
**Bug**
There are two python entries in the status bar that list different versions of python:

<img width="1155" alt="Screen Shot 2020-12-02 at 1 46 44 PM" src="https://user-images.githubusercontent.com/12821956/100935500-04d13600-34a5-11eb-99de-6e8bcc67c982.png">

While in the notebook, I initially wasn't sure which one to look at or which one use to change the kernel version

Extension version: 2020.11.392013122
VS Code version: Code - Insiders 1.52.0-insider (f4187f22026ff6537f2ca8132ad3209fceb5071f, 2020-12-02T13:18:35.551Z)
OS version: Darwin x64 20.1.0

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry914:30230485
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorer:30219166
openfilemenu:30219168
pythonvsded773:30223139

```

</details>

**Comment by rchiodo** [comment] 2020-12-02 22:24
This is actually a dupe of #https://github.com/microsoft/vscode-jupyter/issues/3979

**Closed by rchiodo** 2020-12-02 22:24 UTC
Labels: bug
