### ISSUE TITLE
Add a scrollbar to output cells in Jupyter Notebooks

### ISSUE THREAD

**Issue by pranavajk1** [microsoft/vscode-jupyter#11796] opened 2022-10-25 19:09 UTC
VS code only has the feature to limit the number of lines in the output cell of the notebook. It would be nice to have a scroll bar in the output cell so that the entire output can be seen. Even jupyter natively supports this, but not in VS Code

**Comment by amunger** [comment] 2022-11-03 17:17
duplicate of https://github.com/microsoft/vscode-jupyter/issues/7096

**Closed by amunger** 2022-11-03 17:17 UTC
Labels: feature-request
