### ISSUE TITLE
Occurence highlighting highlights wrong part of the code

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode-jupyter#5451] opened 2021-04-08 14:07 UTC
## Environment data

-   VS Code version: 1.56.0-inside bb90ba3d5a5f8d114045b045f3bbe1ebc404f54a x64
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.728949111
-   Pylance Extension : 2021.4.0
-   Python Extension version (available under the Extensions sidebar): 2021.4.727679055-dev
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.9.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Actual behaviour
I am using Pylance as language server. When I highlight occurences, I think it highlights all the occurences of the notebook. As you can see on the picture, part of the comment is highlighted while it shouldn't be.
![image](https://user-images.githubusercontent.com/28219244/114040147-a0bfe380-9883-11eb-92c9-a3bfd653f36d.png)

**Comment by joyceerhl** [comment] 2021-04-08 17:50
This is a dupe of https://github.com/microsoft/vscode/issues/120148

**Closed** 2021-04-08 20:48 UTC
Labels: bug
