### ISSUE TITLE
Installation of IPykernel does not complete on CodeSpaces

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5116] opened 2021-03-11 02:39 UTC
## Environment data

-   VS Code version: Codespaces
-   Extension version (available under the Extensions sidebar): Latest
-   OS and version: N/A
-   Python version (& distribution if applicable, e.g. Anaconda): 2021.2.63692...
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: XXX

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

When running a Python notebook IPyKernel will get installed.

## Actual behaviour

* We get the message that its getting installed, 
* The terminal opens, however the text sent to the terminal is messed up and ipykernel installation never completes
here's whats in the terminal (its contains some unnecessary text `[Would you like to...` that breaks the installation)

**Basically the installation script has not run at all.**
We need a way to find out if the shell is ready to accept input, e.g. Write to a file in the terminal and wait for the file to be created, if not then try again & finally send the real commands.
This way we're guaranteed that the text will run. 
FYI - Today we're already running to a log file, perhaps we can utilize that same log file to see if things have started `/tmp/tmp-1055JbKi2leayDSq.log`..

```
/usr/bin/python3 /home/codespace/.vscode-remote/extensions/ms-python.python-2021.2.636928669/pythonFiles/pyvsc-run-isolated.py /home/codespace/.vscode-remote/extensions/ms-python.python-2021.2.636928669/pythonFiles/shell_exec.py /usr/bin/python3 /home/codespace/.vscode-remote/extensions/ms-python.python-2021.2.636928669/pythonFiles/pyvsc-run-isolated.py pip install -U ipykernel --user /tmp/tmp-1055JbKi2leayDSq.log
[Oh My Bash] Would you like to check for updates? [Y/n]: \c
codespace ➜ ~/workspace/PlayCodeSpaces (main ✗) $ 
```

Tracked Upstream https://github.com/microsoft/vscode-python/issues/15632

**Comment by DonJayamanne** [comment] 2021-03-24 21:05
We might want to contribute to this, upstream

**Comment by greazer** [comment] 2021-08-14 06:34
closing as dupe of #6559

**Closed by greazer** 2021-08-14 06:34 UTC
Labels: bug, upstream-python, codespaces
