### ISSUE TITLE
Provide kernel-based auto completions for other languages

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8248] opened 2021-11-11 23:18 UTC
Our kernel completions are registered to only work with python:
https://github.com/microsoft/vscode-jupyter/blob/617384b0e13c1bdb55e7b711dd99bfd3dc313e6e/src/client/datascience/notebook/integration.ts#L40

This is really necessary in order to do a good job filtering the results. 

However this means there is no intellisense for other kernels (unless the language extension for that kernel is able to handle notebooks).

Shouldn't be too hard to add, just register another completion provider that is similar to the python one, but doesn't do the filtering.

**Comment by DonJayamanne** [comment] 2023-12-01 01:07
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/14672

**Closed by DonJayamanne** 2023-12-01 01:07 UTC
Labels: notebook-intellisense, language-any, feature-request
