### ISSUE TITLE
The kernel failed to start due to the missing module 'ipykernel_launcher'

### ISSUE THREAD

**Issue by Dovely-ll** [microsoft/vscode-jupyter#9246] opened 2022-03-06 21:49 UTC
## Environment data

-   VS Code version: 1.65
-   Jupyter Extension version (available under the Extensions sidebar): 2022.2.1020642448
-   Python Extension version (available under the Extensions sidebar): 2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.9.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

The kernel should be correctly connected to VS code.

## Actual behaviour

The kernel is not launching correctly.
I first migrated to an ARM based Mac from an Intel-based one by 'migrate to another mac' app. Then I can run the notebook fine within VS code, and then I downloaded the Apple Silicon binary file to replace the old Intel binary file, then it stops working. Even when I download back the Intel binary file to replace it, it still doesn't work, but I can run jupyter notebook in broswer.

## Steps to reproduce:

Just open any notebook script and click run cell, it will fail to launch the kernel.

## Logs

Visual Studio Code (1.65.0, undefined, desktop)
Jupyter Extension Version: 2022.2.1020642448.
Python Extension Version: 2022.2.1924087327.
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 15:02:38: ZMQ install verified.
Info 15:02:41: Checking for server existence.
Info 15:02:41: Checking for server usability.
Info 15:02:41: Starting notebook server.
Info 15:02:41: Connecting to server
Info 15:02:41: Connecting to process server
Info 15:02:41: Connecting server kernel http://127.0.0.1:8889/
Connecting to Jupyter server at http://127.0.0.1:8889/
Info 15:02:41: Creating server with settings : {"baseUrl":"http://127.0.0.1:8889/","appUrl":"","wsUrl":"ws://127.0.0.1:8889/","token":"0cc2a2a6063563694939a30f44214bf170fb3371a76917f1","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 15:02:41: Connection complete server
Info 15:02:41: Server started.
Info 15:02:41: Creating server with settings : {"baseUrl":"http://127.0.0.1:8889/","appUrl":"","wsUrl":"ws://127.0.0.1:8889/","token":"0cc2a2a6063563694939a30f44214bf170fb3371a76917f1","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 15:02:41: Disposing session manager
Info 15:02:41: SessionManager - dispose contents manager
Info 15:02:41: ShutdownSessionAndConnection - dispose session manager
Info 15:02:41: Finished disposing jupyter session manager
Error 15:02:41: Failed to get remote kernel connections [FetchError: request to http://127.0.0.1:8889/api/kernels?1646600561274 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
	at ClientRequest.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:3895430)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Info 15:02:41: Creating server with settings : {"baseUrl":"http://127.0.0.1:8889/","appUrl":"","wsUrl":"ws://127.0.0.1:8889/","token":"0cc2a2a6063563694939a30f44214bf170fb3371a76917f1","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 15:02:41: Creating server with settings : {"baseUrl":"http://127.0.0.1:8889/","appUrl":"","wsUrl":"ws://127.0.0.1:8889/","token":"0cc2a2a6063563694939a30f44214bf170fb3371a76917f1","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 15:02:41: Disposing session manager
Info 15:02:41: SessionManager - dispose contents manager
Info 15:02:41: ShutdownSessionAndConnection - dispose session manager
Info 15:02:41: Disposing session manager
Info 15:02:41: SessionManager - dispose contents manager
Info 15:02:41: ShutdownSessionAndConnection - dispose session manager
Error 15:02:41: SessionManager cannot enumerate kernelspecs. Returning default {}.
Info 15:02:41: Finished disposing jupyter session manager
Error 15:02:41: Failed to get remote kernel connections [FetchError: request to http://127.0.0.1:8889/api/kernels?1646600561298 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
	at ClientRequest.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:3895430)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Info 15:02:41: Creating server with settings : {"baseUrl":"http://127.0.0.1:8889/","appUrl":"","wsUrl":"ws://127.0.0.1:8889/","token":"0cc2a2a6063563694939a30f44214bf170fb3371a76917f1","appendToken":true,"init":{"cache":"no-store","credentials":"same-origin"}}
Info 15:02:41: Finished disposing jupyter session manager
Error 15:02:41: Failed to get remote kernel connections [FetchError: request to http://127.0.0.1:8889/api/kernels?1646600561298 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
	at ClientRequest.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:3895430)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Info 15:02:41: Disposing session manager
Info 15:02:41: SessionManager - dispose contents manager
Info 15:02:41: ShutdownSessionAndConnection - dispose session manager
Error 15:02:41: SessionManager cannot enumerate kernelspecs. Returning default {}.
Info 15:02:41: Finished disposing jupyter session manager
Error 15:02:41: findKernel crashed [FetchError: request to http://127.0.0.1:8889/api/kernels?1646600561313 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
	at ClientRequest.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:3895430)
	at ClientRequest.emit (events.js:315:20)
	at Socket.socketErrorListener (_http_client.js:469:9)
	at Socket.emit (events.js:315:20)
	at emitErrorNT (internal/streams/destroy.js:106:8)
	at emitErrorCloseNT (internal/streams/destroy.js:74:3)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)]
Error 15:02:41: SessionManager cannot enumerate kernelspecs. Returning default {}.
Error 15:02:41: SessionManager cannot enumerate kernelspecs. Returning default {}.
Info 15:02:41: Interrupt requested & no kernel.
Info 15:02:41: Setting setActiveController for ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:02:41: Getting activation commands for /opt/homebrew/bin/python3 are not cached. May take a while.
Info 15:02:41: KernelProvider switched kernel to id = .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher
Info 15:02:41: Starting Notebook in kernel.ts id = .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher
Info 15:02:41: Creating raw notebook for ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:02:41: Getting preferred kernel for ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:02:41: Computing working directory ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:02:41: Starting raw kernel Python 3.9.10 64-bit
Info 15:02:41: installMissingDependencies /opt/homebrew/bin/python3
Info 15:02:41: IPykernel found previously in this environment /opt/homebrew/bin/python3
Info 15:02:41: Kernel launching with ports 9000,9001,9002,9003,9004. Start port is 9000
Info 15:02:42: Experiment status for python is {"enabled":true,"optInto":[],"optOutFrom":[]}
Info 15:02:43: Creating controller for jupyter-notebook with interpreter /opt/homebrew/bin/python3
Info 15:02:43: No custom variables nor do we have a conda environment
Info 15:02:43: Process Execution: > /opt/homebrew/bin/python3 -m pip list
> /opt/homebrew/bin/python3 -m pip list
Info 15:02:43: Process Execution: > /opt/homebrew/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /opt/homebrew/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 15:02:43: Process Execution: > /opt/homebrew/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"84ad7b89-71f3-4ded-b3dd-eda32e72d8c9" --shell=9002 --transport="tcp" --iopub=9004 --f=/var/folders/zb/pbdry8b504db3s4sxsyvhzr00000gn/T/tmp-382775Od5p9Xhm1P8.json
> /opt/homebrew/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"84ad7b89-71f3-4ded-b3dd-eda32e72d8c9" --shell=9002 --transport="tcp" --iopub=9004 --f=/var/folders/zb/pbdry8b504db3s4sxsyvhzr00000gn/T/tmp-382775Od5p9Xhm1P8.json
Info 15:02:43: Process Execution: cwd: ~/Documents/NetworkX Project/repo
cwd: ~/Documents/NetworkX Project/repo
Error 15:02:43: Disposing kernel process due to an error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: ...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: ''
}
Error 15:02:43: 
Info 15:02:43: Dispose Kernel process
Error 15:02:43: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: ...
Error 15:02:43: failed to create INotebook in kernel, UI Disabled = true [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: ...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Error 15:02:43: failed to start INotebook in kernel, UI Disabled = true [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: ...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Info 15:02:43: ipykernel version 5.5.5 for /opt/homebrew/bin/python3
Info 15:02:43: ipykernel location ~/Library/Python/3.9/lib/python/site-packages/ipykernel/__init__.py for /opt/homebrew/bin/python3
Info 15:02:44: Registering dummy command feature
Info 15:03:08: Execute Cells request 1
Info 15:03:08: Execute Cell 1 ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:03:08: Starting Notebook in kernel.ts id = .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher
Info 15:03:08: Creating raw notebook for ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:03:08: Getting preferred kernel for ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:03:08: Computing working directory ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:03:08: Starting raw kernel Python 3.9.10 64-bit
Info 15:03:08: installMissingDependencies /opt/homebrew/bin/python3
Info 15:03:08: IPykernel found previously in this environment /opt/homebrew/bin/python3
Info 15:03:08: Kernel launching with ports 9008,9009,9010,9011,9012. Start port is 9000
Info 15:03:08: Process Execution: > /opt/homebrew/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /opt/homebrew/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 15:03:08: Process Execution: > /opt/homebrew/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9011 --control=9009 --hb=9008 --Session.signature_scheme="hmac-sha256" --Session.key=b"942922ad-c566-47d1-8b05-41a9933e297f" --shell=9010 --transport="tcp" --iopub=9012 --f=/var/folders/zb/pbdry8b504db3s4sxsyvhzr00000gn/T/tmp-38277zwCN9GRmmNZD.json
> /opt/homebrew/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9011 --control=9009 --hb=9008 --Session.signature_scheme="hmac-sha256" --Session.key=b"942922ad-c566-47d1-8b05-41a9933e297f" --shell=9010 --transport="tcp" --iopub=9012 --f=/var/folders/zb/pbdry8b504db3s4sxsyvhzr00000gn/T/tmp-38277zwCN9GRmmNZD.json
Info 15:03:08: Process Execution: cwd: ~/Documents/NetworkX Project/repo
cwd: ~/Documents/NetworkX Project/repo
Warn 15:03:08: StdErr from Kernel Process /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher

Error 15:03:08: Disposing kernel process due to an error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n'
}
Error 15:03:08: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher

Info 15:03:08: Dispose Kernel process
Error 15:03:08: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
Error 15:03:08: failed to create INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Warn 15:03:08: Kernel Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Error 15:03:08: failed to start INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Error 15:03:08: Failed to execute cells in CellExecutionQueue [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Info 15:03:08: Cancel pending cells
Info 15:03:08: Cell 1 executed with state Idle
Info 15:03:08: Process Execution: > /opt/homebrew/bin/python3 -c "import ipykernel"
> /opt/homebrew/bin/python3 -c "import ipykernel"
Info 15:03:09: ipykernel version 5.5.5 for /opt/homebrew/bin/python3
Info 15:03:09: ipykernel location ~/Library/Python/3.9/lib/python/site-packages/ipykernel/__init__.py for /opt/homebrew/bin/python3
Info 15:03:25: Execute Cells request 1
Info 15:03:25: Execute Cell 1 ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:03:25: Starting Notebook in kernel.ts id = .jvsc74a57bd0b0fa6594d8f4cbf19f97940f81e996739fb7646882a419484c72d19e05852a7e./opt/homebrew/bin/python3./opt/homebrew/bin/python3.-m#ipykernel_launcher
Info 15:03:25: Creating raw notebook for ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:03:25: Getting preferred kernel for ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:03:25: Computing working directory ~/Documents/NetworkX Project/repo/graph_algorithms.ipynb
Info 15:03:25: Starting raw kernel Python 3.9.10 64-bit
Info 15:03:25: installMissingDependencies /opt/homebrew/bin/python3
Info 15:03:25: IPykernel found previously in this environment /opt/homebrew/bin/python3
Info 15:03:25: Kernel launching with ports 9016,9017,9018,9019,9020. Start port is 9000
Info 15:03:25: Process Execution: > /opt/homebrew/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> /opt/homebrew/bin/python3 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
Info 15:03:25: Process Execution: > /opt/homebrew/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9019 --control=9017 --hb=9016 --Session.signature_scheme="hmac-sha256" --Session.key=b"51d8b3de-f46d-457e-b2b3-d7fbe60fe8a3" --shell=9018 --transport="tcp" --iopub=9020 --f=/var/folders/zb/pbdry8b504db3s4sxsyvhzr00000gn/T/tmp-38277EJgK1WjF51Na.json
> /opt/homebrew/bin/python3 -m ipykernel_launcher --ip=127.0.0.1 --stdin=9019 --control=9017 --hb=9016 --Session.signature_scheme="hmac-sha256" --Session.key=b"51d8b3de-f46d-457e-b2b3-d7fbe60fe8a3" --shell=9018 --transport="tcp" --iopub=9020 --f=/var/folders/zb/pbdry8b504db3s4sxsyvhzr00000gn/T/tmp-38277EJgK1WjF51Na.json
Info 15:03:25: Process Execution: cwd: ~/Documents/NetworkX Project/repo
cwd: ~/Documents/NetworkX Project/repo
Warn 15:03:25: StdErr from Kernel Process /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher

Error 15:03:25: Disposing kernel process due to an error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n'
}
Error 15:03:25: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher

Info 15:03:25: Dispose Kernel process
Error 15:03:25: Failed to connect raw kernel session: Error: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
Error 15:03:25: failed to create INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Warn 15:03:25: Kernel Error [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Error 15:03:25: failed to start INotebook in kernel, UI Disabled = false [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Error 15:03:25: Failed to execute cells in CellExecutionQueue [o [Error]: The kernel died. View Jupyter [log](command:jupyter.viewOutput) for further details. 
Error: /opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher...
	at ChildProcess.<anonymous> (/Users/Dovely/.vscode/extensions/ms-toolsai.jupyter-2022.2.1020642448/out/client/extension.js:2:790975)
	at ChildProcess.emit (events.js:327:22)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)] {
  category: 'kerneldied',
  exitCode: 1,
  stdErr: '/opt/homebrew/opt/python@3.9/bin/python3.9: No module named ipykernel_launcher\n',
  vslsStack: [ CallSite {}, CallSite {}, CallSite {} ]
}
Info 15:03:25: Cancel pending cells
Info 15:03:25: Cell 1 executed with state Idle
Info 15:03:25: Process Execution: > /opt/homebrew/bin/python3 -c "import ipykernel"
> /opt/homebrew/bin/python3 -c "import ipykernel"
Info 15:03:26: ipykernel version 5.5.5 for /opt/homebrew/bin/python3
Info 15:03:26: ipykernel location ~/Library/Python/3.9/lib/python/site-packages/ipykernel/__init__.py for /opt/homebrew/bin/python3

**Comment by DonJayamanne** [comment] 2022-03-07 00:19
Thanks for reporting this issue & I'm sorry you're running into this bug, we have a fix ready and will be publishing a release tomorrow.
In the mean time you could install the pre-release version of the Jupyter extension to get around this bug.
GO into the extensions panel and search for Jupyter and then you'll find a button on the Jupyter extension page that allows you to switch to the Pre-Release version.

**Comment by DonJayamanne** [comment] 2022-03-07 00:20
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/9234

**Closed by DonJayamanne** 2022-03-07 00:20 UTC
Labels: bug, needs-triage
