### ISSUE TITLE
Not able to launch tensorboard, and keep asking to install tensorboard

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/vscode-jupyter#10462] opened 2022-06-15 15:39 UTC
VS Code version: Version: 1.68.0
Jupyter Extension version: v2022.5.1001601848
Python Extension version: v2022.8.0
OS: Mac and version: Monterey 12.4
Python: 3.9.13
Jupyter server running: Local
tensorboard version: 2.9.0

I am not able to launch tensorboard from Command Palette, and it keeps asking me to install it even it has been installed already. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4111978/173867771-76966d48-169e-4d56-b919-2b74e905918a.png">

However, it did show up inside interactive window after running the model with
```
%load_ext tensorboard
%tensorboard --logdir logs
```

<img width="971" alt="image" src="https://user-images.githubusercontent.com/4111978/173868672-5fb605fe-0617-4094-943b-9c0f2a5114a5.png">

**Comment by rchiodo** [comment] 2022-06-15 17:08
Thanks for the issue. 

This is likely a dupe of this issue here:
https://github.com/microsoft/vscode-jupyter/issues/9678

**Comment by IanMatthewHuff** [comment] 2022-06-16 20:19
@Fred-Wu Are you using Conda with this environment? If so this will be closed as a duplicate of #9687

**Comment by Fred-Wu** [comment] 2022-06-18 08:33
> @Fred-Wu Are you using Conda with this environment? If so this will be closed as a duplicate of #9687

Yes. I am using Miniforge.

**Comment by IanMatthewHuff** [comment] 2022-06-18 14:40
Closing as duplicate of #9687. Just track that issue for a resolution on this.

**Closed by IanMatthewHuff** 2022-06-18 14:40 UTC
Labels: bug, info-needed, tensorboard

**Comment by aslacour** [comment] 2023-06-16 05:15
I have the same issue as well.

**Comment by pyatsysh** [comment] 2023-08-09 14:39
Has this been solved?

**Comment by amunger** [comment] 2023-08-09 15:45
possibly due to https://github.com/microsoft/vscode-python/issues/21749. I don't think that linked issue is actually a duplicate. 
Please open a new issue if that doesn't look like the same cause

**Comment by mokeddembillel** [comment] 2023-08-12 11:48
I still have this issue guys. has it been solved ?

**Comment by mariamavagyan** [comment] 2023-08-20 03:49
having the same issue. Any solution yet?

**Comment by amunger** [comment] 2023-08-21 15:09
please open a new issue if you are experiencing something similar and include information about your environment.
