### ISSUE TITLE
Displaying Plotly Data Point Hover Data using DASH

### ISSUE THREAD

**Issue by JosephKarpinski** [microsoft/vscode-jupyter#15765] opened 2024-06-06 15:03 UTC
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.90.0
- OS Version: macOS Sonoma 14.4.1 (23E224)

Steps to Reproduce:

1. Run under Jupyter Notebook works
2. Run under VScode, plotly hover data doesn't display 
3. See attached code:
```python
from dash import Dash, html, dcc
from dash.dependencies import Input, Output, State
import numpy as np
import plotly.graph_objects as go
import json

x = np.random.uniform(-10, 10, size=50)
y = np.sin(x)
clicked = []

# Build App
app = Dash(__name__)
app.layout = html.Div(
    [
        dcc.Graph(
            id="fig",
            figure=go.Figure(go.Scatter(x=x, y=y, mode="markers", name="base_points")),
        ),
        html.Div(id="debug"),
    ]
)


@app.callback(
    Output("debug", "children"),
    Input("fig", "clickData"),
)
def point_clicked(clickData):
    if clickData:
        point = clickData["points"][0]
        x, y = point["x"], point["y"]
        hover_text = f"x: {x}, y: {y}"
        return hover_text
    else:
        return ""

# Run app and display result inline in the notebook
if __name__ == "__main__":
    app.run_server()
```
<img width="1246" alt="Screenshot 2024-06-06 at 10 44 59 AM" src="https://github.com/microsoft/vscode/assets/37123616/2be093d5-063d-4087-ab1f-7982db51f44b">

<img width="1246" alt="Screenshot 2024-06-06 at 10 45 26 AM" src="https://github.com/microsoft/vscode/assets/37123616/28f7418f-1255-437a-99e3-3715b16828fc">

**Comment by rebornix** [comment] 2024-06-13 22:42
@DonJayamanne can you help triage this issue?

**Comment by DonJayamanne** [comment] 2024-09-12 20:33
I'm very sorry for never getting back to this.
Most likely a result of https://github.com/microsoft/vscode-jupyter/issues/15234

**Comment by JosephKarpinski** [comment] 2024-09-15 02:18
Tried it today under: 

macOS Sonoma 14.6.1

Visual Studio
Version: 1.93.1
Commit: 38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
Date: 2024-09-11T17:20:05.685Z
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Still doesn't work.

**Comment by DonJayamanne** [comment] 2024-10-02 06:15
Verified that this is due to plotly package being out of date in renderer extension.
Duplicate of https://github.com/microsoft/vscode-notebook-renderers/issues/214

**Closed by DonJayamanne** 2024-10-02 06:15 UTC
Labels: bug, ipywidgets
