### ISSUE TITLE
selected kernel is not the shown kernel

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-jupyter#4421] opened 2021-01-18 13:32 UTC
Issue Type: <b>Bug</b>

When I select a conda kernel it is selected (checked via sys.executable) yet the UI still shows as if the base kernel Python 3 is the selected one (top right corner)

Extension version: 2020.12.414227025
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id e506cf50-5725-42ba-a739-2f80ff9373dc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joyceerhl** [comment] 2021-01-19 08:05
Hi @hanan-vian, sorry about the trouble here. Could you please provide detailed logs from the Jupyter output panel? You can get to these by setting `jupyter.logging.level: 'info'` in your user settings.json, reloading VS Code, attempting to switch kernels, then opening the output panel and selecting Jupyter from the dropdown: 
![image](https://user-images.githubusercontent.com/30305945/105005312-ff469580-59e9-11eb-8d0a-22111972597d.png)

**Comment by rchiodo** [comment] 2021-02-18 00:41
I believe this is the same problem we identified where if the 'default' kernel is used they're always Python 3.

**Comment by greazer** [comment] 2021-02-18 21:49
Likely a dupe of #4831

**Closed by greazer** 2021-02-18 21:49 UTC
