### ISSUE TITLE
"Expand" and "Collapse" are useless.

### ISSUE THREAD

**Issue by ttSpace** [microsoft/vscode-jupyter#8311] opened 2021-11-19 07:08 UTC
## Environment data

Build of Visual Studio Code - Insiders: 1.63.0-insider (user setup)   
Build of python-insider: v2021.12.1478695168-dev 
Build of jupyter-insider: v2021.11.1001475629 
Build of pylance-insider: v2021.11.2 
Build of jupyter Keymap-insider: v1.0.0 
Build of jupyter Notebook Renderers-insider: v1.0.3 

## Expected behaviour

```Expand```: Expand All Interactive Cells
```Collapse```: Collapse All Interactive Cells

## Actual behaviour

Nothing changes.

![image](https://user-images.githubusercontent.com/82852072/142579898-0c645316-4530-40ab-83b3-2647c30d51c3.png)

**Comment by rchiodo** [comment] 2021-11-19 17:44
Thanks for the issue. This is a dupe of #8203

**Closed by rchiodo** 2021-11-19 17:44 UTC
Labels: bug, needs-triage
