### ISSUE TITLE
Data Viewer doesn't support MultiIndex

### ISSUE THREAD

**Issue by ronglums** [microsoft/vscode-jupyter#7306] opened 2021-08-26 17:35 UTC
Repros in both Insiders 1.60.0 and Stable 1.59.1

1. Run this notebook: https://github.com/ronglums/NotebooksDemo/blob/master/DataViz.ipynb
2. Open the Variable Explorer and launch Data Viewer on variable "df"
Expected: Data Viewer to load
Actual:
Data Viewer never finishes loading
![image](https://user-images.githubusercontent.com/26419852/131009501-cc2ea4da-0972-4fe2-bb01-3b4ceb16c408.png)

Output shows MultiIndex is not implemented:
NotImplementedError Traceback (most recent call last)
in
----> 1 print(_VSCODE_getDataFrameRows(df, 0, 920))

in _VSCODE_getDataFrameRows(df, start, end)
154 except:
155 pass
--> 156 return _VSCODE_pd_json.to_json(None, df, orient="table", date_format="iso")
157
158

~\Anaconda3\lib\site-packages\pandas\io\json_json.py in to_json(path_or_buf, obj, orient, date_format, double_precision, force_ascii, date_unit, default_handler, lines, compression, index, indent)
73 raise NotImplementedError("'obj' should be a Series or a DataFrame")
74
---> 75 s = writer(
76 obj,
77 orient=orient,

~\Anaconda3\lib\site-packages\pandas\io\json_json.py in init(self, obj, orient, date_format, double_precision, ensure_ascii, date_unit, index, default_handler, indent)
291 # NotImplemented on a column MultiIndex
292 if obj.ndim == 2 and isinstance(obj.columns, MultiIndex):
--> 293 raise NotImplementedError("orient='table' is not supported for MultiIndex")
294
295 # TODO: Do this timedelta properly in objToJSON.c See GH #15137

NotImplementedError: orient='table' is not supported for MultiIndex
at f.extractJupyterResultText (c:\Users\ronglu.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.2028009458\out\client\extension.js:90:260996)
at f.deserializeJupyterResult (c:\Users\ronglu.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.2028009458\out\client\extension.js:90:261115)
at f.getDataFrameRows (c:\Users\ronglu.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.2028009458\out\client\extension.js:90:258067)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async r.getRows (c:\Users\ronglu.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.2028009458\out\client\extension.js:52:843755)
at async c:\Users\ronglu.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.2028009458\out\client\extension.js:52:836723
at async C.wrapRequest (c:\Users\ronglu.vscode-insiders\extensions\ms-toolsai.jupyter-2021.8.2028009458\out\client\extension.js:52:836952)]

**Comment by IanMatthewHuff** [comment] 2021-09-02 23:26
I think this is not a Dupe of #5551 as this is a full crash / hang and the other bug is not supporting a multi index view correctly.

**Comment by IanMatthewHuff** [comment] 2022-11-04 20:28
Dupe of #5551

**Closed by IanMatthewHuff** 2022-11-04 20:28 UTC
Labels: bug, data-viewer
