### ISSUE TITLE
Test failure with selecting kernel

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#8959] opened 2022-02-08 18:53 UTC
Recent failure:
![image](https://user-images.githubusercontent.com/19672699/153055948-e6e11aed-d0c5-4ca2-9d97-1b23d3de4210.png)

Copied from here:
https://github.com/microsoft/vscode-jupyter/runs/5112911623?check_suite_focus=true

**Comment by DonJayamanne** [comment] 2022-02-08 19:12
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8953 (fails even on Linux)

**Closed by DonJayamanne** 2022-02-08 19:12 UTC
Labels: bug, needs-triage
