### ISSUE TITLE
New interactive window points to root folder `/` instead of `workspaceFolder`

### ISSUE THREAD

**Issue by ma-sadeghi** [microsoft/vscode-jupyter#13082] opened 2023-03-15 13:55 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When opening a new interactive window, `pwd` points to `/` rather than the workspace folder.

PS. I already found a workaround in a another [issue](https://github.com/microsoft/vscode-jupyter/issues/6549#issuecomment-875852103), which ironically seems to have been fixed! Either there's something wrong on my end or the bug has somehow resurfaced:

```json
"jupyter.notebookFileRoot": "${workspaceFolder}",
```

### VS Code Version

Version: 1.76.1 Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b Date: 2023-03-08T16:31:31.010Z Electron: 19.1.11 Chromium: 102.0.5005.196 Node.js: 16.14.2 V8: 10.2.154.26-electron.0 OS: Linux x64 5.17.5-76051705-generic Sandboxed: No

### Jupyter Extension Version

v2023.2.1200692131

### Jupyter logs

```shell
info 09:50:13.000: Starting interactive window for resource '' with controller '.jvsc74a57bd0b58bd5559424689280ce24ff6229e536533c877108d283a6d2846312dfd182d7./home/amin/mambaforge/envs/sci/python./home/amin/mambaforge/envs/sci/python.-m#ipykernel_launcher (Interactive)'
info 09:50:13.539: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0b58bd5559424689280ce24ff6229e536533c877108d283a6d2846312dfd182d7./home/amin/mambaforge/envs/sci/python./home/amin/mambaforge/envs/sci/python.-m#ipykernel_launcher (Python Path: /home/amin/mambaforge/envs/sci, EnvType: Conda, EnvName: 'sci', Version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) 
[GCC 10.3.0]) for '/Interactive-1.interactive' (disableUI=false)
info 09:50:13.562: Process Execution: > ~/mambaforge/envs/sci/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/mambaforge/envs/sci/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 09:50:13.605: Process Execution: > ~/mambaforge/envs/sci/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"20d84fa9-e7ae-403a-8313-dd563833483c" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/amin/.local/share/jupyter/runtime/kernel-v2-13803537JMmKTR4f6nf.json
> ~/mambaforge/envs/sci/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"20d84fa9-e7ae-403a-8313-dd563833483c" --shell=9002 --transport="tcp" --iopub=9004 --f=/home/amin/.local/share/jupyter/runtime/kernel-v2-13803537JMmKTR4f6nf.json
info 09:50:13.606: Process Execution: cwd: ~/Code/CL-model
cwd: ~/Code/CL-model
info 09:50:13.791: ipykernel version & path 6.15.2, ~/mambaforge/envs/sci/lib/python3.9/site-packages/ipykernel/__init__.py for /home/amin/mambaforge/envs/sci/bin/python
info 09:50:14.282: Started Kernel sci (Python 3.9.13) (pid: 1382210)
```

### Coding Language and Runtime Version

Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)

### Language Extension Version (if applicable)

v2023.4.1

### Running Jupyter locally or remotely?

Locally

**Comment by amunger** [comment] 2023-03-15 17:43
seems to be working fine for me. Do you actually have a workspace open? Does the default value (`${fileDirname}`) for that setting work if you run a file in the interactive window?

**Comment by floyebolu** [comment] 2023-03-20 17:00
Hi,

I have the exact same issue - the value in my extension is the default value as suggested:
```
"jupyter.notebookFileRoot": "${fileDirname}"
```

When I run a file in the interactive window, it works without problems ¯\_(ツ)_/¯

**Comment by ma-sadeghi** [comment] 2023-03-21 18:40
@amunger, I don't work with workspaces, I just open the root directory of the project I want to work on in VS Code.

**Comment by DonJayamanne** [comment] 2023-03-21 19:25
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/13057

**Closed by DonJayamanne** 2023-03-21 19:25 UTC
Labels: bug, info-needed, interactive-window
