### ISSUE TITLE
Vscode remote ssh ipynb kernel failed to start

### ISSUE THREAD

**Issue by itsaadish** [microsoft/vscode-jupyter#13685] opened 2023-06-12 18:27 UTC
## Environment data

-   VS Code version: 1.78.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.8.0
-   Python Extension version (available under the Extensions sidebar): v2023.4.1011241018
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.8,3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda and virtualenv
-   Jupyter server running: Local | Remote | N/A: Remote

## Expected behaviour

Kernel initialize and start

## Actual behaviour

ailed to start the Kernel 'finetune_llama_env (Python 3.11.3)'. 

## Steps to reproduce:

Ssh into the server
create or open existing ipynb notebook. install python and jupyter extensions 
select kernel from the list shown.
error throws
<img width="1434" alt="bug" src="https://github.com/microsoft/vscode-jupyter/assets/68146545/867f2452-dc07-4a5f-b9a0-e0b2f7e44f6c">

## Logs

info 02:24:41.179: Starting Jupyter Session startUsingLocalKernelSpec, .finetune_llama_env./home/kokil/anaconda3/envs/finetune_llama_env/bin/python3.11./home/kokil/anaconda3/envs/finetune_llama_env/bin/python3.11.-m#ipykernel_launcher (Python Path: /home/kokil/anaconda3/envs/finetune_llama_env, EnvType: Conda, EnvName: 'finetune_llama_env', Version: 3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]) for '/home/kokil/aadish/projects/indic-bert/test.ipynb' (disableUI=false)
info 02:24:41.194: Process Execution: > ~/anaconda3/envs/finetune_llama_env/bin/python3.11 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/anaconda3/envs/finetune_llama_env/bin/python3.11 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 02:24:41.200: Dispose Kernel process undefined.
error 02:24:41.201: Kernel Launcher. launch, Class name = ah, completed in 21ms, has a falsy return value, Arg 1: {"id":".finetune_llama_env./home/kokil/anaconda3/envs/finetune_llama_env/bin/python3.11./home/kokil/anaconda3/envs/finetune_llama_env/bin/python3.11.-m#ipykernel_launcher","kernelSpec":{"specFile":"/home/kokil/.local/share/jupyter/kernels/finetune_llama_env/kernel.json","name":"finetune_llama_env","argv":["/home/kokil/anaconda3/envs/finetune_llama_env/bin/python3.11","-m","ipykernel_launcher","-f","{connection_file}"],"language":"python","executable":"/home/kokil/anaconda3/envs/finetune_llama_env/bin/python3.11","display_name":"finetune_llama_env","metadata":{"debugger":true,"vscode":{"originalSpecFile":"/home/kokil/.local/share/jupyter/kernels/finetune_llama_env/kernel.json","originalDisplayName":"finetune_llama_env"}}},"interpreter":{"id":"/home/kokil/anaconda3/envs/finetune_llama_env/bin/python3.11","sysPrefix":"/home/kokil/anaconda3/envs/finetune_llama_env","envPath":"/home/kokil/anaconda3/envs/finetune_llama_env","displayPath":"/home/kokil/anaconda3/envs/finetune_llama_env","envName":"finetune_llama_env","displayName":"finetune_llama_env","envType":"Conda","isCondaEnvWithoutPython":false,"version":{"major":3,"minor":11,"patch":3,"raw":"3.11.3 (main, Apr 19 2023, 23:54:32) [GCC 11.2.0]"},"path":"/home/kokil/anaconda3/envs/finetune_llama_env/bin/python3.11"},"kind":"startUsingLocalKernelSpec"}, Arg 2: 60000, Arg 3: "~/aadish/projects/indic-bert/test.ipynb", Arg 4: "~/aadish/projects/indic-bert", Arg 5: <argument cannot be serialized for logging> [Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'
}
error 02:24:41.201: Failed to connect raw kernel session: Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'
warn 02:24:41.203: Error occurred while trying to start the kernel, options.disableUI=false [_n [Error]: 
	at new _n (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:2:1611187)
	at Function.from (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:2:1611266)
	at Qg.createJupyterSession (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:17:264112)

Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {
  category: 'unknown',
  originalException: [Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'
  }
}
warn 02:24:41.203: Kernel Error, context = start [_n [Error]: 
	at new _n (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:2:1611187)
	at Function.from (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:2:1611266)
	at Qg.createJupyterSession (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:17:264112)

Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {
  category: 'unknown',
  originalException: [Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'
  }
}
info 02:24:41.221: Process Execution: > ~/anaconda3/envs/finetune_llama_env/bin/python3.11 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~/anaconda3/envs/finetune_llama_env/bin/python3.11 -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 02:24:41.406: Dispose Kernel '/home/kokil/aadish/projects/indic-bert/test.ipynb' associated with '/home/kokil/aadish/projects/indic-bert/test.ipynb'
error 02:24:41.412: Error in execution [_n [Error]: 
	at new _n (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:2:1611187)
	at Function.from (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:2:1611266)
	at Qg.createJupyterSession (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:17:264112)

Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {
  category: 'unknown',
  originalException: [Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'
  }
}
error 02:24:41.412: Error in execution (get message for cell) [_n [Error]: 
	at new _n (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:2:1611187)
	at Function.from (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:2:1611266)
	at Qg.createJupyterSession (/home/kokil/.vscode-server/extensions/ms-toolsai.jupyter-2023.3.1000892223/out/extension.node.js:17:264112)

Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {
  category: 'unknown',
  originalException: [Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {
    errno: -13,
    code: 'EACCES',
    syscall: 'open',
    path: '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'
  }
}

**Comment by DonJayamanne** [comment] 2023-06-12 20:55
Thank you for filing this issue and sorry you are running into this.

> Error: EACCES: permission denied, open '/tmp/kernel-v2-48692WGPJ4lTpfpJH.json'] {

Looks like the cause is due to the above.
Please could you check the access rights to the above folder, make the changes to give access to that folder (its a temporary folder) and see if that works

**Comment by itsaadish** [comment] 2023-06-13 12:26
but in which directory this folder is located?

**Comment by DonJayamanne** [comment] 2023-07-18 20:52
Please can you open a terminal and print the values for the following env variables
`TMPDIR` , `TMP` and `TEMP`

**Comment by DonJayamanne** [comment] 2023-10-27 05:37
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Closed by DonJayamanne** 2023-10-27 05:37 UTC
Labels: bug, info-needed, notebook-kernel-startup, ssh
