### ISSUE TITLE
code-insiders: autocomplete adds the object name with the attribute

### ISSUE THREAD

**Issue by siva-msft** [microsoft/vscode-jupyter#6700] opened 2021-07-16 21:39 UTC
## Environment data

-   VS Code version: 1.59.0-insiders
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.1036914918
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows (Remote:SSH into Linux)
-   Python and/or Anaconda version: 3.6.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

I have an object `parsed` which has an attribute `file_bytes`. Intellicode finds `file_bytes` alright but the recommendation(completion) includes the attribute name as well, even when it has already been typed.
Refer to screenshot:

![Screenshot (23)](https://user-images.githubusercontent.com/60401095/126010678-53bd399b-82c0-4835-949f-d439f28c7f2f.png)

![Screenshot (24)](https://user-images.githubusercontent.com/60401095/126010693-dc34288c-f072-4178-8890-77cc64f1de6e.png)

Python Language server is set to Pylance. I am starting to see this issue with a recent update, was working fine earlier.

## Steps to reproduce:

Here's a gif of the bug in action
![nb_intellicode_error_gif](https://user-images.githubusercontent.com/60401095/126010984-8f66287c-6978-4089-b082-9d2bae9ac382.gif)

**Comment by claudiaregio** [comment] 2021-07-21 20:04
@siva-msft, can you paste your settings.json?

**Comment by greazer** [comment] 2021-07-22 20:20
Dupe of #5956 as above.

**Closed by greazer** 2021-07-22 20:20 UTC
Labels: bug, info-needed, needs-triage
