### ISSUE TITLE
Insiders - Intellisense or Autocomplete issue 

### ISSUE THREAD

**Issue by firegate22** [microsoft/vscode-jupyter#6162] opened 2021-06-07 15:21 UTC
## Environment data

-   VS Code version: 1.57.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.905800000 / 2021.6.914258744
-   Python Extension version (available under the Extensions sidebar): 2021.5.8429233320 / 2021.5.842923320
-   OS (Windows | Mac | Linux distro) and version: Windows / WSL with Ubuntu 20.04
-   Python and/or Anaconda version: 2.7.18
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): pyenv-virtualenv
-   Jupyter server running: local via SSH to WSL

## Expected behaviour

in a ipynb:

book => <class 'pyspark.sql.dataframe.DataFrame'>
book.colum (press tab to use auto complete suggestion book.columns)

-> book.columns

## Actual behaviour

book.book.columns

## Steps to reproduce:

As describe above - I type book.col (existing pyspark.DataFrame() and hit tab to complete the first suggestion to book.columns and get book.book.columns instead

## Logs

**Comment by claudiaregio** [comment] 2021-06-07 17:23
Hi @firegate22, what language server are you using? 
Potential dupe of https://github.com/microsoft/vscode-jupyter/issues/5956?

**Comment by firegate22** [comment] 2021-06-07 19:38
Damn me, that I didn't see that before - but I have the same result with language server Default (at first) and I tested Pylance and Jedi (incl. reloading the window). It just happens within a notebook, not within an interactive window or the normal editor.

Not entirely sure about this: I checked another kernel with Python 3.8 and it's working fine. However, with my Spark / Python 2.7.18 kernel, the behaviour is exactly reproducible. I guess that is also a reason not to fix it :X

**Comment by prasoon2211** [comment] 2021-07-07 11:41
Wanted to add that I have the same problem:
What I see in autocomplete:
![image](https://user-images.githubusercontent.com/2565248/124753167-f2cae080-df28-11eb-9ac5-018e8cddca38.png)

What I get after I press Enter:
![image](https://user-images.githubusercontent.com/2565248/124753240-0413ed00-df29-11eb-8375-48e05d08937a.png)

**Comment by tmchartrand** [comment] 2021-07-09 22:15
I also have this issue in VSCode 1.58.0, with Pylance server in a python 3.7 kernel

**Comment by tmchartrand** [comment] 2021-07-09 22:18
looks like #6363 may also be an instance of the same issue.

**Comment by kuelumbus** [comment] 2021-07-16 17:10
I am having the same problem as @prasoon2211 for path and code completions.

**Comment by DonJayamanne** [comment] 2021-07-26 22:36
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5956

**Closed by DonJayamanne** 2021-07-26 22:36 UTC
Labels: bug, info-needed
