### ISSUE TITLE
ipynb notebook speed in VSCode vs browser based Jupyter

### ISSUE THREAD

**Issue by BAI-adam** [microsoft/vscode-jupyter#11297] opened 2022-09-06 15:16 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Running an ipynb in VSCode extremely slow (unable to provide code, but notebook was reading files, processing, and writing files to a local folder in the same directory as the notebook).

In VSCode, cell was running for >2h taking about 5 min to process each file (files are less than 5MB each, so not a memory issues). Running this in a browser based notebook took ~5mins TOTAL to process everything.

VSCode had just updated when I started working today, so could be related to this. 

### VS Code Version

1.71.0

### Jupyter Extension Version

v2022.9.1002511105

### Coding Language and Runtime Version

Python 3.7

### Language Extension Version (if applicable)

Python extension 

### Running Jupyter locally or remotely?

Local

**Comment by AlFontal** [comment] 2022-09-23 11:24
I am also seeing way slower performances in VS Code compared to browser based Jupyter, specifically when working with GeoDataFrames and decently-sized Shapefiles. Once these are loaded in memory, any simple operation becomes painfully slow, to the point of making it impossible to work like that.

I suspect this might have to do with the built-in variable explorer?

**Comment by DonJayamanne** [comment] 2022-09-25 23:01
@AlFontal 

* please could you upload the logs from the Jupyter output panel, you can get there output using the command Jupyter: Show Output. Please remember to copy and upload all of the output.

> seeing way slower performances in VS Code compared to browser based Jupyter,

I'd like to understand what you mean by slow performance. Are you referring to editing, navigating through the notebook/cells or editing code in the cells. Or is this performance related to execution of cells in the notebook?

Would you be able to upload such a file or email it to me `<don>.<jayamanne>` at the company i work for.
Please do list the dependencies to be installed as well. thanks

**Comment by AlFontal** [comment] 2022-09-28 10:04
@DonJayamanne 

Editing and navigating through notebook/cells works perfectly, no issues there. By slow performance I mean the execution of cells in the notebook. 

Computationally cheap cells execute in mili-seconds in the browser and in seconds within VS Code, while expensive computations often take ~2/3x the time in VS Code as in the browser.

I am running VS Code locally, on Ubuntu 20.04, with a poetry env using python 3.8.10 and the issue happens both when the kernel is started within VS Code or when starting a jupyter kernel in the terminal and manually inputting it.

I will try and do a small toy example to reproduce the errors side by side.

**Comment by DonJayamanne** [comment] 2022-09-28 12:47
> small toy example to reproduce the errors side by side

thanks that would help. specially having some sample code that we can try at our end as well.

**Comment by DonJayamanne** [comment] 2022-12-04 19:32
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Closed by DonJayamanne** 2022-12-04 19:32 UTC
Labels: bug, info-needed, perf
