### ISSUE TITLE
Python Error Output Line References Showing as Raw HTML 

### ISSUE THREAD

**Issue by weds4** [microsoft/vscode-jupyter#14314] opened 2023-09-12 13:45 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When running a file in python interactive window, any python errors have a display issue where the link to the line with the error displays as raw html instead of as a normal hyperlink. This is happening consistently even after restarting VS Code.

![image](https://github.com/microsoft/vscode-jupyter/assets/36106902/9dda1d19-7254-431b-9b24-a7e707ae55d7)

### VS Code Version

Version: 1.82.0 (user setup) Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314 Date: 2023-09-06T22:07:07.438Z Electron: 25.8.0 ElectronBuildId: 23503258 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.19045

### Jupyter Extension Version

v2023.8.1002501831

### Jupyter logs

```shell
Visual Studio Code (1.82.0, undefined, desktop)
Jupyter Extension Version: 2023.8.1002501831.
Python Extension Version: 2023.16.0.
Platform: win32 (x64).
Workspace folder e:\Python Dev\PDM Project Database Manager, Home = c:\Users\SKerS
09:23:07.240 [info] User belongs to experiment group 'NewJupyterSession'
09:23:07.428 [info] Start refreshing Kernel Picker (1694524987428)
09:23:07.434 [info] Using Pylance
09:23:07.477 [info] Start refreshing Interpreter Kernel Picker
09:23:08.944 [info] Process Execution: e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe -m pip list
09:23:10.332 [info] End refreshing Kernel Picker (1694524987428)
09:27:57.463 [info] Starting interactive window for resource 'e:\Python Dev\PDM Project Database Manager\pdm.py' with controller '.jvsc74a57bd07f8808a45b1dd14ad3c76ceb7c5dcdc1391328d7132dba4c4f6737d2f8ce55b4.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.-m#ipykernel_launcher (Interactive)'
09:27:57.613 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd07f8808a45b1dd14ad3c76ceb7c5dcdc1391328d7132dba4c4f6737d2f8ce55b4.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.-m#ipykernel_launcher  (Python Path: e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe, Venv, .venv, 3.9.6) for 'Interactive-1.interactive' (disableUI=false)
09:27:57.631 [info] Process Execution: e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:27:57.913 [warn] Failed to get activated env vars for e:\Python39\python.exe in 225ms
09:27:57.922 [info] Process Execution: e:\Python39\python.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
09:27:58.062 [info] Process Execution: e:\Python39\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 18292
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\pythonFiles\vscode_datascience_helpers
09:27:58.151 [info] Process Execution: e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"f8f6c23f-befb-43b2-8111-4bc8e1d684a9" --shell=9002 --transport="tcp" --iopub=9004 --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-18292Y64CBbDZoeBj.json
    > cwd: e:\Python Dev\PDM Project Database Manager
09:27:58.230 [info] ipykernel version & path 6.25.2, e:\Python Dev\PDM Project Database Manager\.venv\lib\site-packages\ipykernel\__init__.py for e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe
09:27:59.247 [info] Started Kernel .venv (Python 3.9.6) (pid: 25480)
09:27:59.247 [info] Started new session 18337670-9426-4f10-a0b7-71172138cbf2
09:27:59.324 [info] Process Execution: e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.1002501831-win32-x64\pythonFiles\printJupyterDataDir.py
09:27:59.327 [info] Generated code for 1 = <ipython-input-1-66c294d9b285> with 197 lines
09:27:59.354 [info] Kernel acknowledged execution of cell 1 @ 1694525279333
09:27:59.732 [info] End cell 1 execution @ 1694525279730, started @ 1694525279333, elapsed time = 0.397s
09:27:59.732 [warn] Cancel all remaining cells due to cancellation or failure in execution
09:30:33.064 [info] Disposing kernel .jvsc74a57bd07f8808a45b1dd14ad3c76ceb7c5dcdc1391328d7132dba4c4f6737d2f8ce55b4.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.-m#ipykernel_launcher for notebook Interactive-1.interactive due to selection of another kernel or closing of the notebook
09:30:33.064 [info] Dispose Kernel 'Interactive-1.interactive' associated with 'e:\Python Dev\PDM Project Database Manager\pdm.py'
09:30:33.065 [info] Dispose Kernel process 25480.
09:30:33.070 [info] Process Execution: c:\WINDOWS\System32\taskkill.exe /F /T /PID 25480
09:30:33.075 [info] Dispose Kernel 'Interactive-1.interactive' associated with 'e:\Python Dev\PDM Project Database Manager\pdm.py'
09:33:00.073 [info] Starting interactive window for resource 'e:\Python Dev\PDM Project Database Manager\pdm.py' with controller '.jvsc74a57bd07f8808a45b1dd14ad3c76ceb7c5dcdc1391328d7132dba4c4f6737d2f8ce55b4.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.-m#ipykernel_launcher (Interactive)'
09:33:00.132 [info] Process Execution: e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe -m pip list
09:33:00.241 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd07f8808a45b1dd14ad3c76ceb7c5dcdc1391328d7132dba4c4f6737d2f8ce55b4.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe.-m#ipykernel_launcher  (Python Path: e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe, Venv, .venv, 3.9.6) for 'Interactive-1.interactive' (disableUI=false)
09:33:00.247 [info] Process Execution: e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:33:00.292 [info] Process Execution: e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"f731f40a-bc26-4949-993a-4d5c77e97eba" --shell=9002 --transport="tcp" --iopub=9004 --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-18292KX9hdsHJ0bif.json
    > cwd: e:\Python Dev\PDM Project Database Manager
09:33:00.741 [info] ipykernel version & path 6.25.2, e:\Python Dev\PDM Project Database Manager\.venv\lib\site-packages\ipykernel\__init__.py for e:\Python Dev\PDM Project Database Manager\.venv\Scripts\python.exe
09:33:01.237 [warn] StdErr from Kernel Process e:\Python Dev\PDM Project Database Manager\.venv\lib\site-packages\traitlets\traitlets.py:2548: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
09:33:01.237 [warn] StdErr from Kernel Process e:\Python Dev\PDM Project Database Manager\.venv\lib\site-packages\traitlets\traitlets.py:2499: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'f731f40a-bc26-4949-993a-4d5c77e97eba' instead of 'b"f731f40a-bc26-4949-993a-4d5c77e97eba"'.
  warn(
09:33:01.342 [info] Started Kernel .venv (Python 3.9.6) (pid: 5572)
09:33:01.342 [info] Started new session c2aad274-e1a3-4176-8b3b-357edb03052f
09:33:01.422 [info] Generated code for 1 = <ipython-input-1-66c294d9b285> with 197 lines
09:33:01.457 [info] Kernel acknowledged execution of cell 1 @ 1694525581442
09:33:01.828 [info] End cell 1 execution @ 1694525581825, started @ 1694525581442, elapsed time = 0.383s
09:33:01.828 [warn] Cancel all remaining cells due to cancellation or failure in execution
09:34:01.902 [info] Loading webview. View is notset
09:34:01.902 [info] Loading web view...
09:34:01.902 [info] Webview panel created.
09:34:02.177 [info] Web view react rendered
```

### Coding Language and Runtime Version

python 3.9.6

### Language Extension Version (if applicable)

v2023.16.0

### Anaconda Version (if applicable)

N/A

### Running Jupyter locally or remotely?

Local

**Comment by Mrinal18** [comment] 2023-09-12 20:58
I am facing the same issue and it's really annoying.

**Comment by Mrinal18** [comment] 2023-09-12 21:10
the main issue seems to be here : https://github.com/microsoft/vscode-jupyter/blob/024313d4d68939ba083180dad5ba37d605b96b6d/src/notebooks/outputs/tracebackFormatter.ts#L32

**Comment by JasonGross** [comment] 2023-09-12 22:44
Is this related to https://github.com/microsoft/vscode-jupyter/issues/12975#issuecomment-1535636475 ?  (If HTML rendering of output strings was recently turned off without removing the code that inserted links...)

**Comment by amunger** [comment] 2023-09-12 22:50
duplicate of https://github.com/microsoft/vscode/issues/192605

**Closed by amunger** 2023-09-12 22:50 UTC
Labels: bug
