### ISSUE TITLE
Widgets from ipywidgets 8.0.0rc0 do not load properly in VSCode; checkbox missing, play loads the older version

### ISSUE THREAD

**Issue by saravanabalagi** [microsoft/vscode-jupyter#9507] opened 2022-03-28 13:58 UTC
## Environment data

-   VS Code version: 1.65.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.2.1030672458
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04.4
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): poetry
-   Jupyter server running: Local

## Expected behaviour

Widgets load properly in VSCode as they do in Jupyter Notebook (Browser) and Jupyter Lab (Browser)

![image](https://user-images.githubusercontent.com/8567893/160412729-03ef3fa2-aa84-4ecd-acf2-98d308b058fd.png)

## Actual behaviour

Widgets do not load properly
1. Play button is from the older version, possible caching?
2. Checkbox does not appear

![Screenshot from 2022-03-28 14-44-20](https://user-images.githubusercontent.com/8567893/160412129-ca459a6f-2277-45d7-bde2-ed6d21ebf340.png)

## Steps to reproduce:

1. Create a new env with depedency `ipywidgets = "^8.0.0rc0"`
1. Create widgets

```
from ipywidgets import widgets

play = widgets.Play(
    value=50,
    min=0,
    max=100,
    step=1,
    interval=500,
    description="Press play",
    disabled=False
)
slider = widgets.IntSlider()
widgets.jslink((play, 'value'), (slider, 'value'))
display(widgets.HBox([play, slider]))

display(widgets.Checkbox(
    value=False,
    description='Check me',
    disabled=False,
    indent=False
))
```
## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Info 14:46:52: Execute Cells request 0, 1, 2, 3
Info 14:46:52: Execute Cell 0 /fastscratch/projects/python/dev/test.ipynb
Info 14:46:52: Execute Cell 1 /fastscratch/projects/python/dev/test.ipynb
Info 14:46:52: Execute Cell 2 /fastscratch/projects/python/dev/test.ipynb
Info 14:46:52: Execute Cell 3 /fastscratch/projects/python/dev/test.ipynb
Info 14:46:53: Cell 0 executed with state Success
Info 14:46:53: Cell 1 executed with state Success
Info 14:46:53: Cell 2 executed with state Success
Info 14:46:53: Cell 3 executed with state Success
Error 14:46:53: Widget load failure [object Object] {
  className: 'CheckboxStyleModel',
  moduleName: '@jupyter-widgets/controls',
  moduleVersion: '2.0.0',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: {}
}
Error 14:46:53: Widget load failure [object Object] {
  className: 'CheckboxStyleModel',
  moduleName: '@jupyter-widgets/controls',
  moduleVersion: '2.0.0',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: {}
}
```

</p>
</details>

### Additional Settings

![image](https://user-images.githubusercontent.com/8567893/160413602-eea67f45-c499-459d-aaec-7d7d8fcd7299.png)

**Comment by rchiodo** [comment] 2022-03-28 20:12
Dupe of #8552

**Closed by rchiodo** 2022-03-28 20:12 UTC
Labels: bug, needs-triage
