### ISSUE TITLE
BUG: Screen goes black and closes all other windows from the system when opening .ipynb file in VSCode

### ISSUE THREAD

**Issue by DanielOsorio01** [microsoft/vscode-jupyter#14546] opened 2023-10-22 18:50 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I open a workspace with a .ipynb file, the screen goes black and it closes all my other windows in the system, including the vscode window. I had to open another workspace without a .ipynb file opened, and then disable the Jupyter extension, which fixed the problem when I tried to reopen a .ipynb file.

### VS Code Version

Version: 1.83.1 Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc Date: 2023-10-10T23:45:31.402Z Electron: 25.8.4 ElectronBuildId: 24154031 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Linux x64 6.2.0-34-generic

### Jupyter Extension Version

v2023.9.1102792234

### Coding Language and Runtime Version

Python 3.10.12

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment] 2023-10-22 22:38
Sorry you are running into this issue.
This has been resolved and was caused by another extension `pylance`.
Please update your Pylance extension to the latest version.
Duplicate of https://github.com/microsoft/pylance-release/issues/4983

**Closed by DonJayamanne** 2023-10-22 22:38 UTC
Labels: bug

**Comment by DanielOsorio01** [comment] 2023-10-22 23:35
Thank you! How did you know it wasnt a jupyter extension bug but a pylance bug?

**Comment by DonJayamanne** [comment] 2023-10-23 00:04
> know it wasnt a jupyter extension bug but a pylance bug?

process of elimination
Disabled extensions to see of this problem went away
