### ISSUE TITLE
ctrl-z in notebook causes execution timer to run endlessly

### ISSUE THREAD

**Issue by FGhavamian** [microsoft/vscode-jupyter#4289] opened 2021-01-02 18:28 UTC
Issue Type: <b>Bug</b>

- Open a notebook
- run a cell
- do ctrl-z
- the previously ran cell gets executed endlessly. 

Clicking on the stop icon does not intrupt. Surprisingly, not only my cpu usage goes up, but my GPU usage goes up as well. 

The only way to stop the execution is to reopen the notebook.

Extension version: 2020.12.424452561
VS Code version: Code - Insiders 1.53.0-insider (4a875e23d20b64504a818834f3fa4c40adb8d480, 2020-12-21T12:33:38.481Z)
OS version: Windows_NT x64 10.0.20279
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (19.08GB free)|
|Process Argv|--crash-reporter-id e7f4e6f1-32af-4fc6-b89f-a530bcad4f73|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (4 x 2208)|
|Memory (System)|15.64GB (14.09GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30208929
wsl2prompt:30219162
vstry244:30230484
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenucf:30219169
pythonvsded773:30223139
core-portspanelcf:30233468

```

</details>

**Comment by DonJayamanne** [comment] 2021-01-04 19:23
Dupe of https://github.com/microsoft/vscode-jupyter/issues/1682

**Closed by DonJayamanne** 2021-01-04 19:23 UTC
