### ISSUE TITLE
Kernel list truncates Python version number

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-jupyter#15754] opened 2024-06-10 14:52 UTC
## Environment data

-   VS Code version: 1.90.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.5.0
-   Python Extension version (available under the Extensions sidebar): v2024.8.0
-   OS (Windows | Mac | Linux distro) and version: Fedora 40
-   Python and/or Anaconda version: Various
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

When selecting a kernel for use with the Jupyter extension, the proper Python version numbers should be displayed.

## Actual behaviour

The version numbers are truncated. Instead of "Python 3.11" or "Python 3.12" (the only versions I have installed) it shows just "Python 3.1" and this results in a warning about supported versions when I try and use them.

![image](https://github.com/microsoft/vscode-jupyter/assets/81476/294129ad-cba7-4c47-887c-ac1dab3fbb34)

![image](https://github.com/microsoft/vscode-jupyter/assets/81476/4add53c4-65e5-4ef4-b1c0-d03dff859783)

**Comment by marcus-k** [comment] 2024-06-10 18:57
I am encountering the same issue with a new install of VS Code with the Jupyter extension. Sometimes the version is reported as 3.1, 3.1.-1, or 3.1.undefined as well, seemingly as random. The version numbers change between each time I re-open VS Code.

**Comment by DonJayamanne** [comment] 2024-06-10 20:11
Duplicate of https://github.com/microsoft/vscode-python/issues/23580

**Closed by DonJayamanne** 2024-06-10 20:11 UTC
Labels: bug
