### ISSUE TITLE
Errors when running `jupyter nbconvert` fails not reported and export output is empty file 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#10273] opened 2022-06-02 18:34 UTC
Testing #10183

1. Have a notebook with some cells that print text
2. Run all
3. Save
4. Export to HTML
5. :bug: resultant file is empty

Export to Python script works fine

**Comment by IanMatthewHuff** [comment] 2022-11-04 20:59
Dupe of #5818

**Closed by IanMatthewHuff** 2022-11-04 20:59 UTC
Labels: bug, notebook-import-export
