### ISSUE TITLE
Unable to view output - It shows only as Javascript error

### ISSUE THREAD

**Issue by dai-anna** [microsoft/vscode-jupyter#14553] opened 2023-10-24 11:54 UTC
## Environment data

-   VS Code version: 1.83.1 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.9.1102792234
-   Python Extension version (available under the Extensions sidebar): v2023.18.0
-   OS (Windows | Mac | Linux distro) and version: Mac (M1 Pro)
-   Python and/or Anaconda version: Python 3.11.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Tried running test code:
```from jupyter_innotater import *

reviews = ["I really liked this movie", "It was OK", "Do not watch!"]
sentiments = [1] * len(reviews)
sentiment_classes = ["0 - Positive", "1 - Neutral", "2 - Negative"]

Innotater(
    TextInnotation(reviews), MultiClassInnotation(sentiments, classes=sentiment_classes)
)
```

and excepted output from documentation.

## Actual behaviour

![image](https://github.com/microsoft/vscode-jupyter/assets/89488845/74af3d93-6884-42a6-a516-78b27c1a94a6)

```
Error: No version of module jupyter-innotater is registered
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/annadai/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4099813)
    at ph.loadClass (https://file+.vscode-resource.vscode-cdn.net/Users/annadai/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4403287)
    at ph.loadModelClass (https://file+.vscode-resource.vscode-cdn.net/Users/annadai/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4097773)
    at ph._make_model (https://file+.vscode-resource.vscode-cdn.net/Users/annadai/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4094616)
    at ph.new_model (https://file+.vscode-resource.vscode-cdn.net/Users/annadai/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4092246)
    at ph.handle_comm_open (https://file+.vscode-resource.vscode-cdn.net/Users/annadai/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4091039)
    at https://file+.vscode-resource.vscode-cdn.net/Users/annadai/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.17/out/node_modules/%40vscode/jupyter-ipywidgets8/dist/ipywidgets.js:2:4402511
    at g._handleCommOpen (https://file+.vscode-resource.vscode-cdn.net/Users/annadai/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-arm64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:2:36099)
    at async g._handleMessage (https://file+.vscode-resource.vscode-cdn.net/Users/annadai/.vscode/extensions/ms-toolsai.jupyter-2023.9.1102792234-darwin-arm64/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js:2:37993)
```

**Comment by DonJayamanne** [comment] 2023-10-25 00:38
Duplicate of upstream issue https://github.com/ideonate/jupyter-innotater/issues/53

**Closed by DonJayamanne** 2023-10-25 00:38 UTC
Labels: bug
