### ISSUE TITLE
port setting for tensorboard

### ISSUE THREAD

**Issue by lkct** [microsoft/vscode-jupyter#14333] opened 2023-09-18 00:13 UTC
I'm trying to use the tensorboard integration in vscode, but failed with error:
```log
2023-09-18 00:56:40.229 [error] Address already in use
Port 6006 is in use by another program. Either identify and stop that program, or start the server with a different port.
```
The 6006 port is indeed occupied, and I confirm running the following in a terminal works:
```sh
tensorboard --port 8008 ...
```
However, there's no way to change the port for tensorboard launched by this extension.
It would be great if the port used by tensorboard can be configured in the settings.

**Comment by amunger** [comment] 2023-09-18 17:22
duplicate of https://github.com/microsoft/vscode-jupyter/issues/13890

**Closed by amunger** 2023-09-18 17:22 UTC
Labels: feature-request, triage-needed
