### ISSUE TITLE
Cannot connect to remote server by specifying URL.

### ISSUE THREAD

**Issue by zachsiegel-capsida** [microsoft/vscode-jupyter#13302] opened 2023-04-11 06:00 UTC
Cannot connect to Jupyter server.

## Environment data

-   VS Code version: 1.77.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.3.1000892223
-   Python Extension version (available under the Extensions sidebar): v2023.6.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11 and WSL (tried all combinations of Jupyter and VS Code Windows/remote WSL) (Windows firewall off)
-   Python and/or Anaconda version: 3.9.5, 3.10, fresh 3.10 from Windows MSI
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Linux: venv and global; Windows: venv and global
-   Jupyter server running: Remote (in all cases started from command-line)

## Expected behaviour

Connect to Jupyter kernel via "Jupyter: Specify Jupyter Server for Connections"

## Actual behaviour

CLI logs all display (with `something` different every time)
```
...ServerApp] Forbidden
ServerApp] 403 GET /api/kernelspecs?something (127.0.0.1) 1.03ms referer=None
```

## Steps to reproduce:

1. Create a Jupyter server (`python3 -m jupyterlab` is my preferred command, but I have used `jupyter --notebook`, and my typical preference, which is `python manage.py shell_plus --lab` for a Django `shell_plus` kernel. None of them work).
2. Select "Jupyter: Specify Juptyer Server for Connections" from the command palette and paste in the URL from the Jupyter CLI under "Existing" (this has always been how I've used this extension, for 1.5 years now).
3. VS Code Jupyter does not connect.

## Logs

(directories anonymized) of course. Tokens single-use so not anonymized. Kernel id anonymized.
```
I 2023-04-11 05:41:45.758 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-04-11 05:41:45.764 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///blahblah/.local/share/jupyter/runtime/jpserver-1895-open.html
    Or copy and paste one of these URLs:
        http://anonymized3:8889/lab?token=50556c18ff6947734ce5a895024976b3dcc2f8bf4fc807bd
     or http://127.0.0.1:8889/lab?token=50556c18ff6947734ce5a895024976b3dcc2f8bf4fc807bd
[W 2023-04-11 05:41:45.998 ServerApp] Forbidden
[W 2023-04-11 05:41:45.999 ServerApp] 403 GET /api/kernels?xyz(127.0.0.1) 1.14ms referer=None
[W 2023-04-11 05:41:46.072 ServerApp] Forbidden
[W 2023-04-11 05:41:46.072 ServerApp] 403 GET /api/kernels?xyz(127.0.0.1) 1.33ms referer=None
[W 2023-04-11 05:41:46.461 ServerApp] Forbidden
```

**Comment by DonJayamanne** [comment] 2023-04-11 19:37
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/13240

**Closed by DonJayamanne** 2023-04-11 19:37 UTC
Labels: bug
