### ISSUE TITLE
allowed to switch to a kernel that already has had its session disposed of

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#10201] opened 2022-05-31 22:22 UTC
Testing #10164

I selected the kernel from the last session and saw a notification. I would expect only valid kernels to show up in this list.

![Screen Shot 2022-05-31 at 3 21 56 PM](https://user-images.githubusercontent.com/29464607/171293812-4e321e78-4a43-482b-b39f-e73f8090310e.png)

**Comment by greazer** [comment] 2022-06-02 20:38
This may be by design, but it needs some consideration as far as messaging and behavior.

**Comment by meganrogge** [comment] 2022-06-02 20:39
How would a user benefit from seeing the one that can't be used? I'm not super familiar with Jupyter, which is why I ask.

**Comment by DonJayamanne** [comment] 2022-06-06 00:50
@meganrogge please could you provide the steps to repro this issue.

**Comment by amunger** [comment] 2022-06-06 21:55
> open a session, attaching to a kernel
> exit from that session

@meganrogge - by session, do you mean jupyter server? As in run `jupyter notebook` to start a server, use vscode jupyter to attach to a kernel, then ctrl+c to stop the server?

I think our reasoning was that we automatically include previous sessions because they might still be alive even if we can't reach them at the moment, but then once we try, we find out that it's disposed.
I wonder if we can ping the server to check if it's disposed when populating the rest of the kernel picker tho?

**Comment by meganrogge** [comment] 2022-06-06 23:12
@amunger I believe I closed the window and that ended the session 1 that I mention above. I don't think I did ctrl+c.

**Comment by DonJayamanne** [comment] 2022-06-13 16:09
@meganrogge are you able to repro this issue with the same steps you have provided?

**Comment by DonJayamanne** [comment] 2022-08-10 06:37
I'm no longer able to repro this, hence closing this for verfication.
Possible it has been fixed with some other issue or the latest fixes

**Closed by DonJayamanne** 2022-08-10 06:37 UTC
Labels: bug, kernel-enumeration, notebook-remote, iteration-candidate
