### ISSUE TITLE
Pointing to a non running remote server makes kernel picker and run cell disappear

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6297] opened 2021-06-15 20:27 UTC
Set jupyter to remote
Run a cell
Stop VS code
Kill remote server

Open VS code
Cell is missing run button:

![image](https://user-images.githubusercontent.com/19672699/122118852-6459b800-cddd-11eb-9035-51e2fd31d13b.png)

And there's no kernel selector.

**Comment by DonJayamanne** [comment] 2021-12-08 01:10
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/8474

**Closed by DonJayamanne** 2021-12-08 01:10 UTC
Labels: bug, notebook-kernel
