### ISSUE TITLE
Tensorflow code throws error in local server, but works in remote

### ISSUE THREAD

**Issue by bguisard** [microsoft/vscode-jupyter#5072] opened 2021-03-08 19:52 UTC
## Environment data

- VS Code version:
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0

-   Jupyter Extension version (available under the Extensions sidebar): 
Id: ms-toolsai.jupyter
Version: 2021.2.576440691

-   Python Extension version (available under the Extensions sidebar):
Id: ms-python.python
Version: 2021.3.633143540-dev

-   OS (Windows | Mac | Linux distro) and version: MacOS 10.15.7 and Ubuntu 18.04.1
-   Python and/or Anaconda version: Python 3.8.6
-   Type of virtual environment used: pyenv virtualenv
-   Jupyter server running: Local

## Expected behaviour

I expect code that runs on jupyter notebooks outside of vs code to run correctly inside vs code as well.

## Actual behaviour

Some (possibly all?) Apache Beam `PTransform`s fail when running jupyter server locally. 

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create new virtualenv and install tensorflow 2.4 and tfx 0.27
```sh
pip install tensorflow==2.4.1 tfx==0.27.0
```

2. Start jupyter server locally using that virtualenv (`Jupyter: Create Interactive Window`)

3. Rename the attached file to `.py` and open in vs code

[tft_example.py.txt](https://github.com/microsoft/vscode-jupyter/files/6103477/tft_example.py.txt)

4. Run file (`Jupyter: Run Current File in Interactive Window`)

![Screen Shot 2021-03-08 at 10 52 59](https://user-images.githubusercontent.com/24639498/110367383-7537a800-7ffc-11eb-8f15-faecc1519f9c.png)

![Screen Shot 2021-03-08 at 11 00 07](https://user-images.githubusercontent.com/24639498/110368129-74ebdc80-7ffd-11eb-8367-b862e7adb75e.png)

## Logs

[jupyter.log](https://github.com/microsoft/vscode-jupyter/files/6103553/jupyter.log)

## Additional Notes

I tried this with two different set ups: local development on macOS and using the remote extension server to run it in an Ubuntu remote host. In both cases the code will crash if vs code tries to manage the jupyter server and will run successfully if you manually start a server and connect vs code to it.

![Screen Shot 2021-03-08 at 11 43 01](https://user-images.githubusercontent.com/24639498/110373153-078f7a00-8004-11eb-8210-7b75118c20c9.png)

**Comment by DavidKutu** [comment] 2021-03-09 00:07
Thanks for the issue @bguisard. I'm also able to follow your steps and get the same result. We'll discuss it in our next triage meeting.

**Comment by greazer** [comment] 2021-03-11 21:27
If a regression, we should fix in March. Otherwise, it can wait until later.

**Comment by DonJayamanne** [comment] 2021-03-24 20:13
@DavidKutu Please could you confirm this is a regression or not.
Did this work in the past (I'd check at least the Jan & Feb release)?

**Comment by DavidKutu** [comment] 2021-03-24 22:01
I checked as far back as the December 2020 release. The issue was still there. I don't think its a regression.

**Comment by DonJayamanne** [comment] 2022-08-21 23:19
Closing this issue as this is caused by a Python package thats beyond the control of this exension.
I.e. the Jupyter extension doesn't have any control over how the packages work, I believe the issue might have something to do with how the package is installed locally vs remote, or differences in the version of the package or differences in the Python environments.

**Closed by DonJayamanne** 2022-08-21 23:19 UTC
Labels: bug, notebook-execution, tensorboard
