### ISSUE TITLE
font size used in Variables View and Interactive Window too big

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-jupyter#10213] opened 2022-06-01 11:05 UTC
Testing #10170

The font size used in Variables View and Interactive Window is too big:

![CleanShot 2022-06-01 at 13 01 58@2x](https://user-images.githubusercontent.com/1898161/171389897-eddf4088-0750-49a8-a732-6f05391c625c.png)

**Comment by sadasant** [comment] 2022-06-01 18:07
Thank you, @weinand! We'll follow up after we circle through the open issues during our next triage.

**Comment by amunger** [comment] 2022-12-09 22:54
duplicate of https://github.com/microsoft/vscode-jupyter/issues/8020

**Closed by amunger** 2022-12-09 22:54 UTC
Labels: bug, papercut :drop_of_blood:, variable-explorer
