### ISSUE TITLE
In interactive window, exporting Jupyter notebook incorrectly includes `# %%`

### ISSUE THREAD

**Issue by seekiu** [microsoft/vscode-jupyter#15512] opened 2024-04-08 03:05 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

In a recent Jupyter extension update, the export to jupyter notebook behavior was broken. Cell markers such as `# %%` or `# %% [markdown]` should be ignored. But in most recent version (v2024.3.0), those markers are included in the exported notebook, which mess up the output. The behavior was correct before but now is broken.

Example below:

<img width="243" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/3148124/cf48c170-bf1d-4314-bc68-d30b420d88f3">

<img width="342" alt="image" src="https://github.com/microsoft/vscode-jupyter/assets/3148124/cd22370b-03a8-4dd4-8c7b-c3e115f6a70c">

Notice that the parts highlighted in red rectangles should not be part of the output.

### VS Code Version

1.88.0

### Jupyter Extension Version

v2024.3.0

### Running Jupyter locally or remotely?

Local

**Comment by seekiu** [comment] 2024-04-09 09:41
Just rolled back to v2024.2.0 and the problem is gone. So it looks like the issue is introduced by some changes in v2024.3.0. Hope that helps.

**Comment by seekiu** [comment] 2024-06-02 04:29
May I ask, is there any update to the fix of this issue?

**Comment by amunger** [comment] 2024-10-04 22:22
closing as dupe of https://github.com/microsoft/vscode-jupyter/issues/15778

**Closed by amunger** 2024-10-04 22:22 UTC
Labels: bug, triage-needed
