### ISSUE TITLE
Can't enter the url of a local jupyter server #2

### ISSUE THREAD

**Issue by banderlog** [microsoft/vscode-jupyter#5820] opened 2021-05-10 16:51 UTC
## Environment data

-   VS Code version: 1.56.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.811652604
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 18.04 LTS
-   Python and/or Anaconda version: python3.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv
-   Jupyter server running: Local

## Expected behaviour

I enter link, press 'Enter' key, VSCode closes input field prompt and connects to jupyter-server

## Actual behaviour

I am pushing Enter button and nothing changes.

## Steps to reproduce:

1. Start local jupyter server
2. Try to connect to it by choosing existing server option

![image](https://user-images.githubusercontent.com/2557965/117694902-599d7900-b1c8-11eb-9a48-61bc021cb2b3.png)

## Other

The keycode of my enter key is 36 (from `xev` output).  
The "HP ProBook 440 G5" laptop.

Similar to the enter key part of https://github.com/microsoft/vscode-jupyter/issues/953 but there no sulution to it and all discussion went to ctrl+v issue (I do not have it)

**Comment by banderlog** [comment] 2021-05-10 16:53
Related to https://github.com/microsoft/vscode-jupyter/issues/952, https://github.com/microsoft/vscode/issues/110528

**Comment by greazer** [comment] 2021-05-13 20:25
Dupe of the VS Code issue mentioned above.

**Closed by greazer** 2021-05-13 20:25 UTC
Labels: bug, info-needed
