### ISSUE TITLE
'!' always uses the system shell - no way to change it

### ISSUE THREAD

**Issue by siva-msft** [microsoft/vscode-jupyter#5322] opened 2021-03-25 22:56 UTC
Running `!ls` works perfectly on native Jupyter, but throws a command not found error in VS Code.
However, I am able to run `!dir` cmd/PowerShell commands on VS Code as well as native Jupyter.

Is there a way for me to change this setting, such that I ask Jupyter running on VS Code to let me run UNIX commands (which Git Bash/WSL allows)?

## Environment data

-   VS Code version: 1.54.3
-   Jupyter Extension version (available under the Extensions sidebar): v2021.3.684299474
-   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
-   OS (Windows | Mac | Linux distro) and version: Windows 10.0.19042 Build 19042
-   Python and/or Anaconda version: Python 3.6.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected Output
![vscode_cmd2](https://user-images.githubusercontent.com/60401095/112553728-46525d80-8d82-11eb-9e09-9a9ad4860bb3.PNG)

## What I see
![vscode_cmd1](https://user-images.githubusercontent.com/60401095/112553882-8e718000-8d82-11eb-92c0-360d0d259925.PNG)

**Comment by DonJayamanne** [comment] 2021-03-25 23:48
Thanks for filing this issue, I'll look into this.

**Comment by rchiodo** [comment] 2021-11-05 16:56
`!` should be executing whatever the kernel thinks is the current command shell. If you're on windows, this should be cmd.exe. This generally means your kernel is running on windows.

For example, jupyter notebook has the same behavior for me on windows

![image](https://user-images.githubusercontent.com/19672699/140548890-ef9cb583-5b5d-42fe-aaaf-0add3c1cdf21.png)

There is a jupyter config setting that lets you change the shell in use, but we don't currently support it:
https://stackoverflow.com/questions/52330492/how-to-change-jupyter-notebook-windows-shell-to-bash

**Comment by DonJayamanne** [comment] 2021-11-29 20:37
@rchiodo Why is this an enhancement? Not sure we want to take ownership of running shell commands.
Users can run them a number of ways and also pass python variables as arguments

**Comment by rchiodo** [comment] 2021-11-29 20:44
It's an enhancement because it's behaving as designed. The enhancement would be to support that jupyter config setting so the user could change what shell is used.

**Comment by DonJayamanne** [comment] 2022-08-14 20:56
Closing this issue as this is how Jupyter works, and we don't have any plans to provide some functionality that would work differently in VS Code compared to Jupyter, specially when it comes to execution of code against a kernel.

This is something that's handled natively by the IPython kernel, hence would require changes upstream

**Closed by DonJayamanne** 2022-08-14 20:56 UTC
Labels: notebook-execution, feature-request
