### ISSUE TITLE
Remote kernels forces notebook to hide run & kernel buttons when disconnected

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode-jupyter#7796] opened 2021-10-04 17:48 UTC
I was last testing remote kernels via https://github.com/microsoft/vscode/issues/133903 and when I created a new notebook the run button and kernel info was blank:

1. Connect to a remote kernel (via https://github.com/microsoft/vscode/issues/133903)
2. Close VS Code and turn off remote kernel
3. Open VS Code and create a new file from the explorer
4. :bug: notice that the run button and kernel info is hidden

![image](https://user-images.githubusercontent.com/35271042/135898478-188f8d0c-0f25-4ad4-a1a1-ffbd2b5a4c1a.png)

Jupyter: v2021.9.1001294413
Version: 1.61.0-insider (Universal)
Commit: a4342f3addc29f405a5cb4aab359b0b98223411e
Date: 2021-10-04T08:49:38.005Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.6.0

<details>
<summary>Console log</summary>

```log
workbench.desktop.main.js:sourcemap:603  INFO Starting extension host with pid 71907.
workbench.desktop.main.js:sourcemap:2923 Extension 'rebornix.better-jupyter-errors cannot use PROPOSED API (must started out of dev or enabled via --enable-proposed-api)
updateEnableProposedApi @ workbench.desktop.main.js:sourcemap:2923
workbench.desktop.main.js:sourcemap:603   ERR [Extension Host] (node:71907) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code - Insiders Helper (Renderer) --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:sourcemap:71 [Extension Host] (node:71907) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code - Insiders Helper (Renderer) --trace-deprecation ...` to show where the warning was created) (at writeOut (internal/process/warning.js:43:3))
v @ workbench.desktop.main.js:sourcemap:71
workbench.desktop.main.js:sourcemap:71 [Extension Host] highlight-bad-chars decorator is activated with configuration Object (at activate (/Users/miguelsolorio/.vscode-insiders/extensions/wengerk.highlight-bad-chars-0.0.5/out/src/extension.js:32:13))
workbench.desktop.main.js:sourcemap:71 [Extension Host] Failed to connect to provider "No token found for host github.com" (at WorkflowManager.log (/Users/miguelsolorio/.vscode-insiders/extensions/knisterpeter.vscode-github-0.30.6/out/src/workflow-manager.js:62:17))
workbench.desktop.main.js:sourcemap:2923 Extension Host
workbench.desktop.main.js:sourcemap:2923 Sending schema for [object Object] https://ddtelvscode.kusto.windows.net/: VSCodeSending schema for [object Object] https://ddtelvscode.kusto.windows.net/: VSCode
workbench.desktop.main.js:sourcemap:603   ERR [Extension Host] Failed to fetch controllers without cache Error: 
    at new o (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:44235)
    at new _ (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:32:15163)
    at /Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:52:996436
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
    at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
workbench.desktop.main.js:sourcemap:71 [Extension Host] Failed to fetch controllers without cache Error: 
    at new o (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:44235)
    at new _ (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:32:15163)
    at /Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:52:996436
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
    at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) (at /Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:54:348656)
v @ workbench.desktop.main.js:sourcemap:71
workbench.desktop.main.js:sourcemap:71 [Extension Host] rejected promise not handled within 1 second: Error: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889 (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30915)
v @ workbench.desktop.main.js:sourcemap:71
workbench.desktop.main.js:sourcemap:71 [Extension Host] stack trace: Error:     at new o (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:44235)    at new _ (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:32:15163)    at /Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:52:996436    at processTicksAndRejections (internal/process/task_queues.js:93:5)FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889    at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)    at ClientRequest.emit (events.js:315:20)    at Socket.socketErrorListener (_http_client.js:469:9)    at Socket.emit (events.js:315:20)    at emitErrorNT (internal/streams/destroy.js:106:8)    at emitErrorCloseNT (internal/streams/destroy.js:74:3)    at processTicksAndRejections (internal/process/task_queues.js:80:21) (at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30994)
v @ workbench.desktop.main.js:sourcemap:71
workbench.desktop.main.js:sourcemap:603   ERR request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889: Error: 
    at new o (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:44235)
    at new _ (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:32:15163)
    at /Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:52:996436
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
    at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
</details>

<details>
<summary>Jupyter Output</summary>

```log
Info 2021-10-04 10:38:47: Experimentation service retrieved: [object Object]
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
Info 2021-10-04 10:38:47: Checking for server existence.
Info 2021-10-04 10:38:47: Checking for server usability.
Info 2021-10-04 10:38:47: Starting notebook server.
Info 2021-10-04 10:38:47: Connecting to history server
Info 2021-10-04 10:38:47: Creating jupyter server: 7c318e6a-af06-4d46-bc37-ed66a630b3e6
Info 2021-10-04 10:38:47: Creating server with settings : {"baseUrl":"http://localhost:8889/","appUrl":"","wsUrl":"ws://localhost:8889/","token":"8773fdd9170f336d10fb9a8df469792010e72ca4f83e1c30","init":{"cache":"no-store","credentials":"same-origin"}}
Info 2021-10-04 10:38:47: Experiment status for python is {"enabled":true,"optInto":["All"],"optOutFrom":[]}
Info 2021-10-04 10:38:47: Disposing session manager
Info 2021-10-04 10:38:47: SessionManager - dispose contents manager
Info 2021-10-04 10:38:47: ShutdownSessionAndConnection - dispose session manager
Info 2021-10-04 10:38:47: Finished disposing jupyter session manager
Error 2021-10-04 10:38:47: findKernel crashed FetchError: request to http://localhost:8889/api/kernels?1633369127468 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
    at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Error 2021-10-04 10:38:47: SessionManager:getKernelSpecs failure:  Error: Poll (@jupyterlab/services:SessionManager#specs) is disposed.
    at o.dispose (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/node_modules/@jupyterlab/services.js:3:107551)
    at t.SessionManager.dispose (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/node_modules/@jupyterlab/services.js:3:580355)
    at m.dispose (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:52:986681)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at y.listKernels (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:90:252288)
    at y.findKernel (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:90:250954)
Info 2021-10-04 10:38:47: Find remote kernel spec, Class name = y, completed in 32ms, has a falsy return value, Arg 1: undefined, Arg 2: {"type":"jupyter","baseUrl":"http://localhost:8889/","token":"8773fdd9170f336d10fb9a8df469792010e72ca4f83e1c30","hostName":"localhost","localLaunch":false,"valid":true,"displayName":"http://localhost:8889/?token=8773fdd9170f336d10fb9a8df469792010e72ca4f83e1c30","rootDirectory":"","url":"http://localhost:8889/?token=8773fdd9170f336d10fb9a8df469792010e72ca4f83e1c30"}, Arg 3: undefined, Arg 4: <argument cannot be serialized for logging>, Return Value: undefined
Info 2021-10-04 10:38:47: Connecting to process for history server
Info 2021-10-04 10:38:47: Connecting server 7c318e6a-af06-4d46-bc37-ed66a630b3e6 kernelSpec unknown
Connecting to Jupyter server at http://localhost:8889/
Info 2021-10-04 10:38:47: Creating server with settings : {"baseUrl":"http://localhost:8889/","appUrl":"","wsUrl":"ws://localhost:8889/","token":"8773fdd9170f336d10fb9a8df469792010e72ca4f83e1c30","init":{"cache":"no-store","credentials":"same-origin"}}
Error 2021-10-04 10:38:47: Backing file not supported: TypeError: request to http://localhost:8889/api/contents/?1633369127483 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
Info 2021-10-04 10:38:47: Starting a new session for kernel id = undefined, name = 
Error 2021-10-04 10:38:47: Failed to change kernel, re-throwing _ [Error]: 
    at new o (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:44235)
    at new _ (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:32:15163)
    at /Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:52:996436
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
    at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  category: 'unknown',
  originalException: FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
      at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
      at ClientRequest.emit (events.js:315:20)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at Socket.emit (events.js:315:20)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
}
Info 2021-10-04 10:38:47: Shutdown session -- complete
Error 2021-10-04 10:38:47: Failed to connect to server _ [Error]: 
    at new o (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:44235)
    at new _ (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:32:15163)
    at /Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:52:996436
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
    at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  category: 'unknown',
  originalException: FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
      at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
      at ClientRequest.emit (events.js:315:20)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at Socket.emit (events.js:315:20)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
}
Info 2021-10-04 10:38:47: Killing server because of error Error: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
Info 2021-10-04 10:38:47: Disposing HostJupyterServer
Info 2021-10-04 10:38:47: Shutting down notebooks for 7c318e6a-af06-4d46-bc37-ed66a630b3e6
Info 2021-10-04 10:38:47: Shut down session manager : existing
Info 2021-10-04 10:38:47: Disposing session manager
Info 2021-10-04 10:38:47: SessionManager - dispose contents manager
Info 2021-10-04 10:38:47: ShutdownSessionAndConnection - dispose session manager
Info 2021-10-04 10:38:47: Finished disposing jupyter session manager
Info 2021-10-04 10:38:47: Shutdown server - dispose conn info
Info 2021-10-04 10:38:47: Finished disposing HostJupyterServer
Error 2021-10-04 10:38:47: Error loading notebook controllers _ [Error]: 
    at new o (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:44235)
    at new _ (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:32:15163)
    at /Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:52:996436
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
    at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  category: 'unknown',
  originalException: FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
      at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
      at ClientRequest.emit (events.js:315:20)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at Socket.emit (events.js:315:20)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
}
Error 2021-10-04 10:38:47: Failed to find & set preferred controllers _ [Error]: 
    at new o (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:44235)
    at new _ (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:32:15163)
    at /Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:52:996436
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
    at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  category: 'unknown',
  originalException: FetchError: request to http://localhost:8889/api/sessions?1633369127489 failed, reason: connect ECONNREFUSED 127.0.0.1:8889
      at ClientRequest.<anonymous> (/Users/miguelsolorio/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/out/client/extension.js:16:254546)
      at ClientRequest.emit (events.js:315:20)
      at Socket.socketErrorListener (_http_client.js:469:9)
      at Socket.emit (events.js:315:20)
      at emitErrorNT (internal/streams/destroy.js:106:8)
      at emitErrorCloseNT (internal/streams/destroy.js:74:3)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
}
Info 2021-10-04 10:38:47: Process Execution: > /opt/homebrew/bin/python3 -c "import jupyter"
> /opt/homebrew/bin/python3 -c "import jupyter"
Info 2021-10-04 10:38:47: Process Execution: > /opt/homebrew/bin/python3 -c "import jupyter"
> /opt/homebrew/bin/python3 -c "import jupyter"
Info 2021-10-04 10:38:47: Process Execution: > /opt/homebrew/bin/python3 -c "import notebook"
> /opt/homebrew/bin/python3 -c "import notebook"
Info 2021-10-04 10:38:47: Process Execution: > /opt/homebrew/bin/python3 -c "import notebook"
> /opt/homebrew/bin/python3 -c "import notebook"
Info 2021-10-04 10:38:47: Process Execution: > /opt/homebrew/bin/python3 -m jupyter kernelspec --version
> /opt/homebrew/bin/python3 -m jupyter kernelspec --version
Info 2021-10-04 10:38:47: Process Execution: > /opt/homebrew/bin/python3 -m jupyter kernelspec --version
> /opt/homebrew/bin/python3 -m jupyter kernelspec --version
Info 2021-10-04 10:38:48: Process Execution: > /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/pythonFiles/vscode_datascience_helpers/getJupyterKernelspecVersion.py
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/pythonFiles/vscode_datascience_helpers/getJupyterKernelspecVersion.py
Info 2021-10-04 10:38:48: Process Execution: > /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/pythonFiles/vscode_datascience_helpers/getJupyterKernelspecVersion.py
> /opt/homebrew/bin/python3 ~/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.9.1001294413/pythonFiles/vscode_datascience_helpers/getJupyterKernelspecVersion.py
Error 2021-10-04 10:38:58: Live Notebook not available for file:///Users/miguelsolorio/code/notebooks/requirements.ipynb
```
</details>

cc @DavidKutu @roblourens

**Comment by rchiodo** [comment] 2021-10-04 20:10
The remote server never responds so there's nothing to return. Should we do something in this scenario to indicate the server is down?

**Comment by misolori** [comment] 2021-10-04 21:05
As a user, I'd expect that this would get reset to "Select Kernel" and maybe show a toast that the remote kernel stopped responding.

**Comment by DonJayamanne** [comment] 2021-12-08 01:30
Duplicate of #8474

**Closed by DonJayamanne** 2021-12-08 01:30 UTC
Labels: bug, notebook-kernel, notebook-remote
