### ISSUE TITLE
Scrollable cell output

### ISSUE THREAD

**Issue by Sk7w4tch3r** [microsoft/vscode-jupyter#6537] opened 2021-07-06 07:01 UTC
## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999662501
-   Python Extension version (available under the Extensions sidebar): v2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Windows 10 Build 19042
-   Python and/or Anaconda version: Python 3.9.5
-   Jupyter server running: Local

## Expected behaviour

Each cell's output should be scrollable.

## Actual behaviour

On each run, specially cells expecting to print many logs, have to scroll all the way to the next cell. last version had a scrollbar on each cell's output

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

Run a cell printing any string in an N step loop, i.e., N equal to 100.

**Comment by IanMatthewHuff** [comment] 2021-07-06 20:03
Duplicate of #6506 .

Sorry about this, just a feature that we missed in transitioning to the new UI. Just track the issue above for our progress on fixing this.

**Closed by IanMatthewHuff** 2021-07-06 20:03 UTC
Labels: bug
