### ISSUE TITLE
TOC for `.py` files with percent markup

### ISSUE THREAD

**Issue by syagev** [microsoft/vscode-jupyter#5552] opened 2021-04-19 18:21 UTC
I suggest to have a TOC available for `.py` files with percent markup. I guess for that we'll need to have the user select which kind of "Outline" view is of interest - the one for regular code files (which will not pickup e.g. markdown cells), or the one adjusted for notebooks.

My use case - in our team we manage a big `.py` file that acts as a sort of "catalog" of useful and relatively independent cells. This has to go under source control for version management and collaboration. The typical workflow is then to open an Interactive Window and execute a few of the cells of interest. So for finding these cells in the large file the described TOC is useful.

_Originally posted by @syagev in https://github.com/microsoft/vscode-jupyter/issues/1348#issuecomment-814769835_

**Comment by syagev** [comment] 2021-04-19 18:26
Also opened as a discussion https://github.com/microsoft/vscode-python/discussions/15990 since I'm not sure what the right place is

**Comment by DavidKutu** [comment] 2021-04-19 23:17
Thanks for the request @syagev!
We'll discuss it in an upcoming meeting.

**Comment by GitHunter0** [comment] 2021-04-20 23:32
@DavidKutu , great! A TOC in the Outline pane is incredibly helpful, I miss that feature very much. 

Two suggestions if I may:

(1) The hierarchical section system of `Spyder IDE` seems a good one to implement:
```
#%% Section
#%%% Subsection
#%%%% Subsubsection
And so on
```
(2) Since VScode is providing native conversion from .py files to notebooks (.ipynb), it would be nice to have a syntax that allows the user to go back and forth between .py and .ipynb maintaining code sections, markdown sections and TOC intact.

Thank you

**Comment by Diogo-Rossi** [comment] 2021-07-11 22:28
It is also asked in #4496 and #1964 (this one by me) and also in [this SO question](https://stackoverflow.com/questions/58767627/in-python-can-i-somehow-use-as-top-hierarchy-in-outline-for-vs-code)

Just to point out the request: cells may be defined not only by the "percent markup" but by the regex set in `"jupyter.codeRegularExpression"` setting, which may include others expressions that would enter in the TOC or outline.

**Comment by xgdgsc** [comment] 2021-08-04 05:09
Hope it can do what  https://github.com/jupyterlab/jupyterlab-toc can do, filter by tags, etc.

**Comment by GitHunter0** [comment] 2021-08-04 06:35
> Hope it can do what https://github.com/jupyterlab/jupyterlab-toc can do, filter by tags, etc.

I hope so too, those features from Jupyter are really helpful

**Comment by GitHunter0** [comment] 2021-09-10 00:21
Folks, @syagev , @Diogo-Rossi , @xgdgsc , let's campaign here https://github.com/microsoft/vscode-python/issues/17218

**Comment by DonJayamanne** [comment] 2021-09-30 17:48
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/4496

**Closed by DonJayamanne** 2021-09-30 17:48 UTC
Labels: enhancement, interactive-window, toc-outline
