### ISSUE TITLE
Tensorboard cannot be correctly closed after closing the window.

### ISSUE THREAD

**Issue by MTandHJ** [microsoft/vscode-jupyter#13184] opened 2023-03-26 02:19 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Closing the window should close the Tensorboard but there are two subprocesses remained:

```
/usr/bin/python3 -c from multiprocessing.semaphore_tracker import main;main(3)
/usr/bin/python3 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=4, pipe_handle=8) --multiprocessing-fork
```

## Steps to reproduce:

1.  Use `ctrl + shift + p' to open a new window for Tensorboard. Then,  the two subprocess above will be created.
2. Closing the window however cannot kill the two subprocess.   

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.16
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "yapf"

```

</p>
</details>

Extension version: 2022.18.2
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.4.0-131-generic
Remote OS version: Linux x64 4.4.0-131-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (19.93GB free)|
|Process Argv|--crash-reporter-id e18a8c59-9580-4a60-8871-d5f09bb5da3d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 4_1080ti_1|
|OS|Linux x64 4.4.0-131-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 1295)|
|Memory (System)|125.80GB (117.57GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 4_1080ti_1|
|OS|Linux x64 4.4.0-131-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (32 x 1295)|
|Memory (System)|125.80GB (117.53GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30681851
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
pythonb192cf:30669361
functionswalk:30687959
pythonms35:30686772

```

</details>

**Comment by DonJayamanne** [comment] 2023-03-28 00:24
Thanks for filing this issue, I will look into this.

**Comment by DonJayamanne** [comment] 2023-05-11 10:02
Sorry, I didn't get to this issue, will try to look into this this week.

**Comment by L-I-M-I-T** [comment] 2023-07-26 09:29
I didn't meet this problem until yesterday, now I have to kill the subprocesses which take port 6006 every time before I relaunch my TensorBoard.

**Comment by sunhongfu** [comment] 2023-08-07 11:33
same issue with the latest version of VSCode and everything. please fix this bug. need to find and kill the process mannually every time!

**Comment by mk-fault** [comment] 2023-08-21 11:56
same issue remain until 0821,fix it,pls

**Comment by Ali-Flt** [comment] 2023-08-30 16:35
It doesn't seem like anyone is fixing this. I suggest handling Tensorboard outside of VScode. Like using a reverse proxy to assign a subdomain to each app (Vscode and Tensorboard)

**Comment by DonJayamanne** [comment] 2023-12-01 01:49
@Ali-Flt we have shipped a new exetnsion named `Tensorboard`
Does this repro from this exension as well.

**Comment by DonJayamanne** [comment] 2023-12-12 21:39
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12852

**Closed by DonJayamanne** 2023-12-12 21:39 UTC
Labels: info-needed, tensorboard, triage-needed
