### ISSUE TITLE
Notebook loses keyboard focus after switching tabs

### ISSUE THREAD

**Issue by raiskila** [microsoft/vscode-jupyter#5789] opened 2021-05-06 13:00 UTC
Unclear if this is related to #3954. Couldn't find other relevant issues

## Environment data

-   VS Code version: Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z (1 day ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.811652604
-   Python Extension version (available under the Extensions sidebar): v2021.4.765268190
-   macOS version: 11.3 (20E232)
-   Python and/or Anaconda version: Python 3.9.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

## Expected behaviour

Keyboard inputs like up/down arrows, <kbd>a</kbd> or <kbd>b</kbd> to add a new cell, enter to edit, etc. should continue to work after switching to a different tab in VS Code and then back to a Jupyter notebook.

## Actual behaviour

After switching from a Jupyter notebook to a different tab in VS Code and then back, all keyboard input to the Jupyter notebook tab seems to stop working. Clicking on something in the notebook restores keyboard focus.

## Steps to reproduce:

1. Have latest VS Code installed
2. `mkdir project && cd project`
4. `python3 -m venv venv`
5. `source venv/bin/activate`
6. `pip install jupyter`
7. `code --user-data-dir ../temp-user-data-dir --extensions-dir ../temp-extensions-dir .`
3. Install python and jupyter extensions in VS Code
4. cmd-shift-p -> Python: Select Interpreter -> select the venv
5. cmd-shift-p -> Jupyter: Create New Blank Notebook
6. Add a couple of cells, run some code, etc.
7. cmd-n to create a new tab
9. Switch back to the jupyter tab
10. No keyboard input is possible

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

https://gist.github.com/raiskila/a8f4ab7178d0dc6f3281ff874c62c840

</details>

**Comment by DonJayamanne** [comment] 2021-05-06 15:44
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1616

**Closed by DonJayamanne** 2021-05-06 15:44 UTC
Labels: bug
