### ISSUE TITLE
ipynb notebook connecting to remote jupyter server can't run cell from time to time

### ISSUE THREAD

**Issue by jiajinyu** [microsoft/vscode-jupyter#16321] opened 2024-12-19 07:54 UTC
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

**Environment**: I am working on ipynb files on remoted ssh with kernels are remoted jupyter servers. the remoted jupter servers open a local port. and i'm using vscode to forward it  to a local port and the jupyter server is connecting the local port.

**Problem:** The notebook dies from time to time.  One minute ago, I ran a cell successfully, the next minute, I can't run any cell. Interrupt and restart kernel button don't work. I have to reload the entire vscode session to make it work again

### log
Below there is a log with trace. At 15:35, notebook runs fine. while at 15:36 it suddenly died. the "go to" button keeps spininng, nothing works. I have to reload the entire vscode to make it work again.
![Image](https://github.com/user-attachments/assets/86297a18-f7fb-477a-a52f-46e12f5ccec2)

### VS Code Version

Version: 1.96.0 (user setup) Commit: 138f619c86f1199955d53b4166bef66ef252935c Date: 2024-12-11T02:29:09.626Z Electron: 32.2.6 ElectronBuildId: 10629634 Chromium: 128.0.6613.186 Node.js: 20.18.1 V8: 12.8.374.38-electron.0 OS: Windows_NT x64 10.0.26100

### Jupyter Extension Version

v2024.11.0 

### Jupyter logs

```shell
15:35:28.923 [trace] Cell 18 completed in 0.004s (start: 1734593728919, end: 1734593728923)
15:35:28.923 [trace] Cell 18 executed successfully
15:36:38.850 [debug] Disposing kernel associated with ~/code/proj/python/notebook/demo.ipynb, isClosed=true, reason = notebookClosed
15:36:38.851 [info] Dispose Kernel '~/code/proj/python/notebook/demo.ipynb' associated with '~/code/proj/python/notebook/demo.ipynb'
15:36:38.851 [debug] Cancel pending cells
15:36:38.851 [trace] Shutdown session - current session, called from 
     	at e_.shutdownImplementation (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:282:34055)
    	at e_.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:282:33046)
    	at bs (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:115:867)
    	at e (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:285:32446)
    	at d_.dispose (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:285:32691)
    	at Sy.disposeOldKernel (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:285:23544)
    	at Sy.<anonymous> (/home/~/.vscode-server/extensions/ms-toolsai.jupyter-2024.11.0-linux-x64/dist/extension.node.js:285:21600)
15:36:38.851 [debug] shutdownSession d4a3e5b2-5dc8-4bcb-804c-91bb287b0593, d4a3e5b2-5dc8-4bcb-804c-91bb287b0593 - start
15:36:38.851 [debug] Session cannot be shutdown d4a3e5b2-5dc8-4bcb-804c-91bb287b0593
15:36:38.852 [trace] Disposing Jupyter Lab Helper
15:36:38.852 [trace] SessionManager - dispose contents manager
15:36:38.852 [trace] ShutdownSessionAndConnection - dispose session manager
15:36:38.854 [trace] Shutdown session -- complete
15:36:38.854 [debug] shutdownSession d4a3e5b2-5dc8-4bcb-804c-91bb287b0593, d4a3e5b2-5dc8-4bcb-804c-91bb287b0593 - shutdown complete
15:36:38.854 [debug] Kernel got disposed, hence there is no longer a kernel associated with ~/code/proj/python/notebook/demo.ipynb
15:36:38.856 [debug] Notebook document ~/code/proj/python/notebook/demo.ipynb got closed
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.857 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.857 [debug] Cancel pending cells
15:36:38.858 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.858 [debug] Cancel pending cells
15:36:38.858 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.858 [debug] Cancel pending cells
15:36:38.858 [debug] Cancel executions after closing notebook ~/code/proj/python/notebook/demo.ipynb
15:36:38.860 [trace] Finished disposing Jupyter Lab Helper
15:36:40.855 [debug] Start refreshing Kernel Picker (1734593800855)
15:36:40.867 [trace] Disposing Jupyter Lab Helper
15:36:40.867 [trace] SessionManager - dispose contents manager
15:36:40.867 [trace] ShutdownSessionAndConnection - dispose session manager
15:36:40.867 [trace] Finished disposing Jupyter Lab Helper
15:36:40.867 [trace] UniversalRemoteKernelFinder: Writing 3 remote kernel connection metadata to cache
15:36:40.869 [debug] End refreshing Kernel Picker (1734593800855)
```

### Running Jupyter locally or remotely?

Remote

**Comment by fanurs** [comment] 2024-12-19 17:45
Thank you for reporting this. I’m experiencing the exact same issue with the same VSCode and Jupyter versions.

Additionally, once the problem occurs, I can’t even restart the kernel. I have to reload the entire VSCode window to get it working again, but it only lasts for a few cell runs.

**Comment by DonJayamanne** [comment] 2024-12-20 05:08
Please can you disable all extensions except for Jupyter, Python, Notebook Renderers (& the Msft Remote extensions).
Found that some extensions such as continue and a few others can cause such issues.

**Comment by jiajinyu** [comment] 2024-12-20 05:44
> Please can you disable all extensions except for Jupyter, Python, Notebook Renderers (& the Msft Remote extensions).

no, I can't.  I need these extensions such as `continue` to develop.  

> Please can you disable all extensions except for Jupyter, Python, Notebook Renderers (& the Msft Remote extensions). Found that some extensions such as continue and a few others can cause such issues.

If you already found some extensions may also that. perhaps you should design mechanism so that other extensions won't cause that. or just tell me there won't be a fix so.

**Comment by DonJayamanne** [comment] 2024-12-20 08:02
> need these extensions such as continue to develop.

Sorry should hanger been more clear, I was only asking for you to try that,
Looks like you do have continue extension installed
That extension is known to cause those these issues
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/16129
https://github.com/continuedev/continue/issues/1463

**Closed by DonJayamanne** 2024-12-20 08:02 UTC
Labels: bug, info-needed, notebook-execution

**Comment by jiajinyu** [comment] 2024-12-20 11:11
interesting. 

- from #16129 , I saw "There's a known issue with auto save, if its turned off then you should not run into this issue."
- from https://github.com/continuedev/continue/issues/1463 ， I also saw a lot people try different hack but with no clear clues.

and this problem has been out for quite a while. 

i wish different extensions may not interfere with each other. or at least official extension from microsoft may let other extension know what's wrong.
