### ISSUE TITLE
Input cell collapses when sending code to python interactive window

### ISSUE THREAD

**Issue by parasurama** [microsoft/vscode-jupyter#7108] opened 2021-08-12 21:43 UTC
Issue Type: <b>Bug</b>

Input cell automatically collapses when sending code to python interactive window via `Shift` + `Enter` with the "jupyter.collapseCellInputCodeByDefault" set to false. 

Extension version: 2021.8.1195043623
VS Code version: Code 1.59.0 (Universal) (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:14:40.191Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 5.3.0-1017-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id ff063a8f-916a-4966-bb68-317ca9914445|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: revel|
|OS|Linux x64 5.3.0-1017-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz (32 x 3097)|
|Memory (System)|123.06GB (2.79GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
vstre464cf:30350173
bridge0723:30350414

```

</details>

**Comment by joyceerhl** [comment] 2021-08-12 22:37
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/7031, fixed in https://github.com/microsoft/vscode-jupyter/commit/27a2bf48844416329f24ff89e3f3c8acd326f92c, we will be publishing a recovery build for VS Code Stable shortly. Apologies for the inconvenience.

**Closed by joyceerhl** 2021-08-12 22:37 UTC
Labels: needs-triage
