### ISSUE TITLE
Jupyter Notebook theme when using ssh

### ISSUE THREAD

**Issue by jediyoda36** [microsoft/vscode-jupyter#1407] opened 2020-01-15 04:34 UTC
# Bug: Notebook Editor, Interactive Window, Editor cells

When using jupyter notebook in ssh mode, the theme of jupyter notebook is not same as VS Code's theme.

## Actual behavior
![image](https://user-images.githubusercontent.com/13287220/72405054-753e6e00-3792-11ea-952b-755abb1026ab.png)

## Expected behavior
![image](https://user-images.githubusercontent.com/13287220/72405080-88e9d480-3792-11ea-8886-069d865bd9e7.png)

### Your Jupyter and/or Python environment
*Please provide as much info as you readily know*
- **Jupyter server running:**                       Local | Remote | N/A
- **Extension version:**                               20YY.MM.#####-xxx
- **VS Code version:**                                #.##
- **Setting python.jediEnabled:**               true | false
- **Python and/or Anaconda version:**     #.#.#
- **OS:**                                                     Windows | Mac | Linux (distro):
- **Virtual environment:**                          conda | venv | virtualenv | N/A | ...

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer

**Comment by jake-steele** [comment] 2020-12-15 17:17
> 
> 
> Having the setting doesn't solve the root cause of the problem. We know what theme is picked, we just can't find the theme json data.
> 
> In the `%USERPROFILE%\.vscode\extensions` (on windows) is where theme extensions are installed. In the remote SSH case, our extension is not installed there, but on the remote machine. We need access to this folder in order to find the theme json contents. There's is currently no way for an extension to read this directory.

Would it be possible for Jupyter to take local theme JSON into memory (or something of the sort), then make connection to remote, then ask user if they would like to apply local theme to remote connection (Yes, No, checkbox for Don't Ask Me Again)?

If no access to remote's /.vscode/extensions folder, could write to somewhere in remote Jupyter's working directory (where should invariably have write permission) and potentially include command to delete upon termination of ssh?

**Comment by rchiodo** [comment] 2021-01-04 17:24
> Would it be possible for Jupyter to take local theme JSON into memory (or something of the sort),

Sorry but this isn't possible because we don't have any code running on the local machine. When you're using Remote SSH, our code is actually only running on the remote machine.

**Comment by repied** [comment] 2021-04-27 17:00
> I installed a secondary theme on my local machine, copied its folder to the remote host, and deleted the first copy of the theme extension from my end. This leaves the extension theme on the remote host only, with my main theme installed locally.
> 
> Every time I go onto a remote server with ssh I'll have to switch to the other theme. The same theme can't be used since the local copy would override the remote copy automatically :\

I can confirm that this (non ideal) workaround worked for me.  

Detailed steps:

1. Install a theme locally (I'm using Dracula 2.22.3).
2. Use command `>Remote: install local extensions in 'Remote'` to install the theme on remote.
3. At this stage the local extension is indeed 'overloading' the remote one and the interactive window still uses the default theme. The remote extension is greyed-out in the activity bar.
4. Delete the local subfolder with the extension `~/.vscode/extensions/dracula-theme.theme-dracula-2.22.3`
4. Reload vscode window
5. The extension is gone from the local extension list, and the remote extension is not greyed-out anymore.
6. Click on the extension wheel , and then on `Set Color Theme`. Select one. It applies to the entire vscode window, including the remote interactive window.

Drawback: local vscode windows don't have the theme anymore. 

Workaround to this issue: change the folder name of your local theme (instead of deleting it) and change theme's name in the them `package.json` but that's quite hacky. Then you'll have local and remote vscode with your favorite theme. Not sure how robust this is.

**Comment by rchiodo** [comment] 2021-04-27 17:09
The themeing problems with remote should be fixed in the [insiders ](https://code.visualstudio.com/insiders/) build of VS code. When the 'insiders' version becomes our stable version, we'll finally resolve this. In the meantime you can install the insiders version if you want to get themes.

**Comment by greazer** [comment] 2021-08-04 00:33
Thanks for your feedback. This issue is addressed with new native support for editing notebooks.

**Closed by greazer** 2021-08-04 00:33 UTC
Labels: bug, insiders-released, vscode-notebook
