### ISSUE TITLE
Improve table column hit targets

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10222] opened 2022-06-01 14:07 UTC
Testing #10170

Notice:

- The resize column target is over about half of the sort icon
- There is a pixel or 2 between the resize column target and the name (which would sort) where the cursor is `default`

![Recording 2022-06-01 at 07 06 15](https://user-images.githubusercontent.com/2193314/171424058-15db4e92-1b93-4445-b131-a4052c602be5.gif)

**Comment by sadasant** [comment] 2022-06-01 18:31
Also, this seems to be a duplicate of #10220

**Closed** 2022-06-01 18:46 UTC
Labels: triage-needed
