### ISSUE TITLE
Ability to refresh python environments from notebook interpreter selection

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode-jupyter#7184] opened 2021-08-17 23:22 UTC
If you create a new python environment via the console, then from a notebook try and select it as a kernel it doesn't appear in the list of python environments. This also occurs when running the `Python: Select Interpreter command`, however in the latter case a `Refresh Interpreter List` icon is shown at the top right of the list. The same should be added t the list of kernels.

**Comment by rchiodo** [comment] 2021-08-18 16:20
Thanks for the suggestion.

**Comment by greazer** [comment] 2021-08-19 20:23
Dupe of microsoft/vscode-python#17004

**Closed by greazer** 2021-08-19 20:23 UTC
Labels: enhancement, kernel-issues
