### ISSUE TITLE
Notebook Intellisense crashed 5 times during diffing

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode-jupyter#11939] opened 2022-11-06 04:33 UTC
Type: <b>Bug</b>

Got an error that notebook-intellisense crashed 5 times. I had a notebook diff open in GH PRI.

```
TypeError: Cannot read properties of undefined (reading 'range')
    at m.handleOpen (/home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2022.11.10/dist/pylance-internal/node_modules/@vscode/lsp-notebook-concat/dist/index.js:1:55649)
    at y.handleOpen (/home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2022.11.10/dist/pylance-internal/node_modules/@vscode/lsp-notebook-concat/dist/index.js:1:66284)
    at _0x15e85d.<computed>.handleOpen (/home/vscode/.vscode-server-insiders/extensions/ms-python.vscode-pylance-2022.11.10/dist/server.bundle.js:1:274410)
[Error - 4:32:40 AM] The notebook-intellisense server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

Extension version: 2022.11.10
VS Code version: Code - Insiders 1.74.0-insider (e764c5b816a99eb8673b2fc4fc028827f202872f, 2022-11-04T05:19:54.097Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 6, 5|
|Memory (System)|64.00GB (0.02GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 3|
|OS|Linux x64 5.15.49-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (8 x 2400)|
|Memory (System)|11.70GB (9.90GB free)|
|VM|0%|
</details>

**Comment by digitarald** [comment] 2022-11-07 17:54
@rchiodo in my settings sync all are on pre-release builds, but when I open the PR from https://github.com/digitarald/ds-together-demo I occasionally get the latest stable releases as well for a moment.

**Comment by rchiodo** [comment] 2022-11-07 18:05
I think the culprit might be in the python core extension. At least if I downgrade Python to 2002.16.1, it works as expected again.

**Comment by rchiodo** [comment] 2022-11-07 19:30
Marking as dupe of #11938

**Closed by rchiodo** 2022-11-07 19:30 UTC
Labels: triage-needed
