### ISSUE TITLE
Can't see Variables in python (conda 3.7.10)

### ISSUE THREAD

**Issue by pyuser3000** [microsoft/vscode-jupyter#7022] opened 2021-08-08 07:55 UTC
Issue Type: <b>Bug</b>

1. variables "button" in interactive window doesn't work (dont show the script variables after cell run)
2. Jupiter:Variables table doesn't show any variables after running cell

VS Code version: Code 1.59.0 (379476f0e13988d90fab105c5c19e7abc8b1dea8, 2021-08-04T23:13:12.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
anaconda-extension-pack|ms-|1.0.1
python|ms-|2021.8.1105858891
vscode-pylance|ms-|2021.8.0
jupyter|ms-|2021.8.1195043623

</details>

**Comment by greazer** [comment] 2021-08-09 18:20
Dupe of #6993

**Closed by greazer** 2021-08-09 18:20 UTC
Labels: needs-triage
