### ISSUE TITLE
Failed to start kernel. Jupyter server crashed

### ISSUE THREAD

**Issue by Exterminator11** [microsoft/vscode-jupyter#12760] opened 2023-02-07 15:01 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

<img width="702" alt="Screenshot 2023-02-07 at 8 30 40 PM" src="https://user-images.githubusercontent.com/88940647/217281042-1cd655ed-13f3-47d8-bfcf-6c0632afd549.png">

### VS Code Version

1.75.0

### Jupyter Extension Version

v2023.1.2000312134

### Jupyter logs

```shell
Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: events fileid lab labextension labhub

Jupyter command `jupyter-notebook` not found.

	at Sm.rejectStartPromise (/Users/rachitdas/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:254981)
	at t._complete (/Users/rachitdas/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:17:255541)
	at t.n (/Users/rachitdas/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:700797)
	at t.__tryOrUnsub (/Users/rachitdas/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:701037)
	at t.complete (/Users/rachitdas/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:700930)
	at t._complete (/Users/rachitdas/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:699446)
	at t.complete (/Users/rachitdas/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:699145)
	at ChildProcess.<anonymous> (/Users/rachitdas/.vscode/extensions/ms-toolsai.jupyter-2023.1.2000312134/out/extension.node.js:2:1800927)
	at Object.onceWrapper (node:events:646:26)
	at ChildProcess.emit (node:events:538:35)
	at ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'jupyterconnection'
}
```

### Coding Language and Runtime Version

Python 3.10.9

### Running Jupyter locally or remotely?

N/A or Not sure

**Comment by DonJayamanne** [comment] 2023-02-07 19:21
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/12758#event-8455595294
This should now be fixed, please install the latest version (released a few hours ago)
Optionally install the pre-release version

**Closed by DonJayamanne** 2023-02-07 19:21 UTC
Labels: bug
