### ISSUE TITLE
Intermittently, cells hang with: "No interpreter for Pylance for Notebook URI"

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [microsoft/vscode-jupyter#15307] opened 2024-03-06 12:50 UTC
Opening an interactivate window in a workspace with a kernel selected in the top-right hangs without even a "thinking" clock icon.  Occasionally VSCode was bringing up  a notification box that no kernel was associated with the notebook, but as I hopped between workspaces and opened the interactive window differently (e.g. "Run file in Interactive Window"), that wasn't a reliable indicator and I haven't seen it in the last dozen or so times I've opened workspaces/reinstalled the jupyter extension to demonstrate the issue.

I tried reloading the extension and restarting VSCode, but that didn't work.  Uninstalling and reinstalling the extension did, for that workspace only.  Likewise, upgrading to the pre-release version of the Jupyter extension solved the problem for that workspace only.  Upgrading to pre-release of Pylance did not solve the issue.

## Environment data

-   VS Code version: 1.87.0
-   Jupyter Extension version (available under the Extensions sidebar): v2024.2.2024022602 (pre-release) and v2024.2.0
-   Python Extension version (available under the Extensions sidebar): v2024.2.1
-   OS (Windows | Mac | Linux distro) and version: 6.5.0-21-generic; Ubuntu 22.04.1 Jammy Jellyfish
-   Python and/or Anaconda version: 3.12.1 and 3.10.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

Cells run

## Actual behaviour

Cells hang.  Apparently culpable line in log: 
```
12:37:51.675 [info] No interpreter for Pylance for Notebook URI "/Interactive-1.interactive"
```

## Steps to reproduce:

I tried creating a new workspace and environment to get an MWE, but the problem didn't recur.  Here is an image of what I'm seeing in the interactive window:
![image](https://github.com/microsoft/vscode-jupyter/assets/37048747/d5d4f230-cc65-4e95-b785-36d1309b219f)

## Logs

<details>

<summary> Jupyter VSCode verbose logs </summary>

```
12:10:21.417 [info] Starting interactive window for resource '' with controller '.jvsc74a57bd0dc8f877a7a49103d927e43d8befe50604ba0afe2a23a0672a8c9991226efe377.~/github/gen-experiments/env/python.~/github/gen-experiments/env/python.-m#ipykernel_launcher (Interactive)'
12:10:21.522 [debug] No controller, hence notebook communications cannot be initialized for editor /Interactive-1.interactive
12:10:21.922 [debug] Interactive Window Editor Created: untitled:/Interactive-1.interactive with input box: vscode-interactive-input:/InteractiveInput-1
12:10:21.930 [debug] start the kernel, options.disableUI=false for /Interactive-1.interactive
12:10:21.952 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0dc8f877a7a49103d927e43d8befe50604ba0afe2a23a0672a8c9991226efe377.~/github/gen-experiments/env/python.~/github/gen-experiments/env/python.-m#ipykernel_launcher  (Python Path: ~/github/gen-experiments/env/bin/python, Venv, env, 3.12.1) for '/Interactive-1.interactive' (disableUI=false)
12:10:21.955 [debug] Creating raw notebook for resource '/Interactive-1.interactive'
12:10:21.989 [debug] Getting activated env variables, Class name = yp (started execution), Arg 1: "/Interactive-1.interactive", Arg 2: "~/github/gen-experiments/env/bin/python", Arg 3: undefined
12:10:21.989 [debug] Get Custom Env Variables, Class name = Rm (started execution), Arg 1: "/Interactive-1.interactive", Arg 2: "RunPythonCode"
12:10:21.991 [debug] Get Custom Env Variables, Class name = Rm, completed in 2ms, has a truthy return value, Arg 1: "/Interactive-1.interactive", Arg 2: "RunPythonCode"
12:10:22.025 [debug] Launching kernel .jvsc74a57bd0dc8f877a7a49103d927e43d8befe50604ba0afe2a23a0672a8c9991226efe377.~/github/gen-experiments/env/python.~/github/gen-experiments/env/python.-m#ipykernel_launcher for /Interactive-1.interactive in ~/github/gen-experiments with ports 9001, 9000, 9004, 9002, 9003
12:10:22.473 [debug] Got env vars with python ~/github/gen-experiments/env/bin/python, with env var count 74 in 484ms. 
    PATH value is ~/github/gen-experiments/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin and 
    Path value is undefined
12:10:22.473 [debug] Prepend PATH with python bin for ~/github/gen-experiments/env/bin/python
12:10:22.474 [debug] Activated Env Variables for ~/github/gen-experiments/env/bin/python, 
    PATH value is ~/github/gen-experiments/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin and 
    Path value is undefined
12:10:22.475 [debug] Getting activated env variables, Class name = yp, completed in 486ms, has a truthy return value, Arg 1: "/Interactive-1.interactive", Arg 2: "~/github/gen-experiments/env/bin/python", Arg 3: undefined
12:10:22.557 [info] Process Execution: ~/github/gen-experiments/env/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
12:10:22.557 [debug] Kernel Env Variables for ~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/temp/jupyter/kernels/python3121jvsc74a57bd0dc8f877a7a49103d927e43d8befe50604ba0afe2a23a0672a8c9991226efe377/kernel.json, PATH value is ~/github/gen-experiments/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin
12:10:22.623 [info] Process Execution: ~/github/gen-experiments/env/bin/python -m ipykernel_launcher --f=~/.local/share/jupyter/runtime/kernel-v2-8396ee2SMiIMBCqC.json
    > cwd: ~/github/gen-experiments
12:10:22.623 [info] Kernel process 8757.
12:10:23.251 [debug] ipykernel version & path 6.29.2, ~/github/gen-experiments/env/lib/python3.12/site-packages/ipykernel/__init__.py for ~/github/gen-experiments/env/bin/python
12:10:23.678 [warn] StdErr from Kernel Process 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
12:10:23.678 [debug] KernelProcess error: 0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.

12:10:23.767 [debug] Kernel output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-8396ee2SMiIMBCqC.json

12:10:23.909 [debug] Waiting for Raw Session to be ready in postStartRawSession
12:10:23.909 [debug] Waiting for Raw session to be ready, status: connected
12:10:23.909 [debug] Raw session connected
12:10:23.909 [debug] Waiting for Raw session to be ready
12:10:23.911 [debug] Waited for Raw session to be ready & got status: connected
12:10:23.912 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
12:10:23.912 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
12:10:23.912 [debug] Sending request for kernelInfo
12:10:23.953 [debug] Got response for requestKernelInfo
12:10:23.953 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 41ms
12:10:23.971 [debug] Executing silently Code (idle) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
12:10:23.997 [debug] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
12:10:23.997 [debug] End sendTelemetryForPythonKernelExecutable after 26ms
12:10:23.998 [debug] Started running kernel initialization for /Interactive-1.interactive
12:10:23.999 [debug] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
12:10:24.009 [debug] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 0 output(s)
12:10:24.009 [debug] Determined IPyWidgets Version as undefined
12:10:24.014 [debug] Executing silently Code (idle) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip
12:10:24.063 [debug] Executing silently Code (completed) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip with 0 output(s)
12:10:24.064 [debug] Requesting Kernel info
12:10:24.064 [debug] Got Kernel info
12:10:24.065 [debug] End running kernel initialization, now waiting for idle
12:10:24.065 [debug] Waiting for idle on (kernel): 21d6a8ef-68b9-4ad8-b12d-8f875324cf4c -> idle
12:10:24.065 [debug] Finished waiting for idle on (kernel): 21d6a8ef-68b9-4ad8-b12d-8f875324cf4c -> idle
12:10:24.065 [debug] End running kernel initialization, session is idle
12:10:24.075 [info] Registering Kernel Completion Provider from kernel env (Python 3.12.1) for language python
12:10:30.564 [info] No interpreter for Pylance for Notebook URI "/Interactive-1.interactive"
12:10:30.586 [info] Handle Execution of Cells 1 for /Interactive-1.interactive

```

</details>

**Comment by DonJayamanne** [comment] 2024-03-06 13:29
Thanks for filling this issue and sorry you are running into this
If and when you do run into this issue
Please can you
* Take a screenshot
* Capture the logs again
* 
Please she the above

**Comment by Jacob-Stevens-Haas** [comment] 2024-03-06 15:40
> Please can you
> *    Take a screenshot
> *    Capture the logs again
> *
>
> Please she the above

Thanks for the quick response.  The original screenshot and logs were from an isolated VSCode session in order to provide clean logs, so new ones would look identical.  What is missing from the screenshot/logs, or what would you want me to do differently?  Was there supposed to be a third step?

**Comment by DonJayamanne** [comment] 2024-03-06 19:56
Thanks
1. I do not see you running any cells, please can you replicate this with some text in the cell and then run it.
Based on the logs you are trying to run a cell, but given the cell is empty, i'm not sure I understand the workflow
2. > pace with a kernel selected in the top-right hangs without even a "thinking" clock

What do you mean by hangs? 
This is what I'm struggling to understand, 
* is VS Code frozen and you are not able to do anything else at all (i.e. cannot open files, cannot type into an editor, etc)
* Or are you inferring this based on some UI element (please could you elaborate)
thanks

**Comment by DonJayamanne** [comment] 2024-03-07 21:22
>  ~/.local/share/jupyter/kernels/0530078540366062831988326/kernel.json 

* Question 1
You seem to have a tonne of kernels on your machine.
Please can you delete or move all the files from your `kernels` folder into a separate location (have it empty).
Then try again and see if that makes a difference.
* Question 2
Did you create these manually? Do you have any idea how they ended up there?
Curious to understand how users

**Comment by Jacob-Stevens-Haas** [comment] 2024-03-10 13:34
Ah, interesting!  A package I wrote runs experiments as jupyter notebooks in memory, saving the result as html.  It was [creating a new kernel with a random name for each run](https://github.com/Jacob-Stevens-Haas/mitosis/blob/57436616897580e377e6b438e4063c4a56b6fa5b/mitosis/__init__.py#L496), as I _think_ `kernel_name` was once a required argument to `nbconvert.preprocessors.ExecutePreprocessor`.  But it isn't now, so I think I can get rid of it, or at least have the process clean up the kernels it makes.

**Comment by Jacob-Stevens-Haas** [comment] 2024-03-10 13:45
Thank you!  It looks like deleting those kernels makes it work!

<details>

</summary> New logs </summary>

```
Visual Studio Code (1.87.0, undefined, desktop)
Jupyter Extension Version: 2024.2.0.
Python Extension Version: 2024.2.1.
Pylance Extension Version: 2024.2.106.
Platform: linux (x64).
Workspace folder ~/github/pysindy, Home = /home/jake
13:40:39.848 [debug] Get Custom Env Variables, Class name = Rm (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
13:40:39.849 [info] Start refreshing Kernel Picker (1710078039849)
13:40:39.864 [info] Using Pylance
13:40:39.923 [debug] Get Custom Env Variables, Class name = Rm, completed in 75ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
13:40:39.923 [debug] Jupyter Paths /kernels: 
13:40:39.923 [debug] Kernel Spec Root Paths, /usr/share/jupyter/kernels, /usr/local/share/jupyter/kernels, ~/.local/share/jupyter/kernels
13:40:39.927 [debug] Search for KernelSpecs in Interpreter ~/github/pysindy/env/bin/python
13:40:39.927 [debug] Finding Global Python KernelSpecs
13:40:39.931 [debug] Getting activated env variables, Class name = yp (started execution), Arg 1: "~/github/pysindy", Arg 2: "~/github/pysindy/env/bin/python", Arg 3: undefined
13:40:39.931 [debug] Get Custom Env Variables, Class name = Rm (started execution), Arg 1: "~/github/pysindy", Arg 2: "RunPythonCode"
13:40:39.933 [debug] Get Custom Env Variables, Class name = Rm, completed in 2ms, has a truthy return value, Arg 1: "~/github/pysindy", Arg 2: "RunPythonCode"
13:40:39.945 [debug] Search for KernelSpecs in Interpreter /usr/local/bin/python3.12
13:40:39.950 [debug] Search for KernelSpecs in Interpreter /bin/python3
13:40:39.956 [debug] Search for KernelSpecs in Interpreter /usr/bin/python3
13:40:39.961 [debug] Search for KernelSpecs in Interpreter /usr/local/bin/python3.11
13:40:39.967 [debug] Search for KernelSpecs in Interpreter /usr/local/bin/python3.8
13:40:39.979 [debug] Full interpreter list is length: 6, ~/github/pysindy/env/bin/python:env:Venv:~/github/pysindy/env/bin/python, /usr/local/bin/python3.12::Unknown:/usr/local/bin/python3.12, /bin/python3::Unknown:/bin/python3, /usr/bin/python3::Unknown:/usr/bin/python3, /usr/local/bin/python3.11::Unknown:/usr/local/bin/python3.11, /usr/local/bin/python3.8::Unknown:/usr/local/bin/python3.8
13:40:40.007 [info] Starting interactive window for resource '' with controller '.jvsc74a57bd0af2b7ca702bc007d49e4815451e788ef9429217bc2294f2515f5d80739c8b71b.~/github/pysindy/env/python.~/github/pysindy/env/python.-m#ipykernel_launcher (Interactive)'
13:40:40.080 [debug] Kernels for interpreter /usr/local/bin/python3.12 are .jvsc74a57bd0f1062708a37074d70712b695aadee582e0b0b9f95f45576b5521424137d05fec./usr/local/bin/python3.12./usr/local/bin/python3.12.-m#ipykernel_launcher
13:40:40.081 [debug] Kernels for interpreter /bin/python3 are .jvsc74a57bd0916dbcbb3f70747c44a77c7bcd40155683ae19c65e1c03b4aa3499c5328201f1./bin/python3./bin/python3.-m#ipykernel_launcher
13:40:40.083 [debug] Kernels for interpreter /usr/bin/python3 are .jvsc74a57bd031f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6./usr/bin/python3./usr/bin/python3.-m#ipykernel_launcher
13:40:40.085 [debug] Kernels for interpreter /usr/local/bin/python3.11 are .jvsc74a57bd01a1af0ee75eeea9e2e1ee996c87e7a2b11a0bebd85af04bb136d915cefc0abce./usr/local/bin/python3.11./usr/local/bin/python3.11.-m#ipykernel_launcher
13:40:40.088 [debug] Kernels for interpreter /usr/local/bin/python3.8 are .jvsc74a57bd00adcc2737ebf6a4a119f135174df96668767fca1ef1112612db5ecadf2b6d608./usr/local/bin/python3.8./usr/local/bin/python3.8.-m#ipykernel_launcher
13:40:40.107 [debug] Loading kernelspec from ~/github/pysindy/env/share/jupyter/kernels/python3/kernel.json for ~/github/pysindy/env/bin/python
13:40:40.122 [debug] Conda file returned by Python Extension is conda
13:40:40.200 [debug] Hiding default kernel spec 'Python 3 (ipykernel)', 'python31012jvsc74a57bd0af2b7ca702bc007d49e4815451e788ef9429217bc2294f2515f5d80739c8b71b', /python for interpreter ~/github/pysindy/env/bin/python and spec ~/github/pysindy/env/share/jupyter/kernels/python3/kernel.json
13:40:40.200 [debug] Kernels for interpreter ~/github/pysindy/env/bin/python are .jvsc74a57bd0af2b7ca702bc007d49e4815451e788ef9429217bc2294f2515f5d80739c8b71b.~/github/pysindy/env/python.~/github/pysindy/env/python.-m#ipykernel_launcher
13:40:40.357 [info] Start refreshing Interpreter Kernel Picker
13:40:40.391 [debug] No controller, hence notebook communications cannot be initialized for editor /Interactive-1.interactive
13:40:40.506 [debug] Got env vars with python ~/github/pysindy/env/bin/python, with env var count 75 in 575ms. 
    PATH value is ~/github/pysindy/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin and 
    Path value is undefined
13:40:40.506 [debug] Prepend PATH with python bin for ~/github/pysindy/env/bin/python
13:40:40.506 [debug] Activated Env Variables for ~/github/pysindy/env/bin/python, 
    PATH value is ~/github/pysindy/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin and 
    Path value is undefined
13:40:40.506 [debug] Getting activated env variables, Class name = yp, completed in 575ms, has a truthy return value, Arg 1: "~/github/pysindy", Arg 2: "~/github/pysindy/env/bin/python", Arg 3: undefined
13:40:40.522 [info] Process Execution: ~/github/pysindy/env/bin/python -m pip list
13:40:40.524 [debug] Initialize notebook communications for editor /Interactive-1.interactive
13:40:40.525 [debug] Resolving notebook UI Comms (resolve) for /Interactive-1.interactive
13:40:40.525 [debug] initialize CommonMessageCoordinator
13:40:40.537 [debug] IPyWidgetMessageDispatcher.initialize
13:40:40.538 [debug] Attempting to determine version of IPyWidgets
13:40:40.538 [debug] Controller selection change completed
13:40:40.760 [debug] Interactive Window Editor Created: untitled:/Interactive-1.interactive with input box: vscode-interactive-input:/InteractiveInput-1
13:40:40.764 [debug] start the kernel, options.disableUI=false for /Interactive-1.interactive
13:40:40.765 [debug] Waiting for IPyWidgets version
13:40:40.765 [debug] Waiting for IPyWidgets version promise
13:40:40.775 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0af2b7ca702bc007d49e4815451e788ef9429217bc2294f2515f5d80739c8b71b.~/github/pysindy/env/python.~/github/pysindy/env/python.-m#ipykernel_launcher  (Python Path: ~/github/pysindy/env/bin/python, Venv, env, 3.10.12) for '/Interactive-1.interactive' (disableUI=false)
13:40:40.776 [debug] Creating raw notebook for resource '/Interactive-1.interactive'
13:40:40.795 [debug] Getting activated env variables, Class name = yp (started execution), Arg 1: "/Interactive-1.interactive", Arg 2: "~/github/pysindy/env/bin/python", Arg 3: undefined
13:40:40.795 [debug] Get Custom Env Variables, Class name = Rm (started execution), Arg 1: "/Interactive-1.interactive", Arg 2: "RunPythonCode"
13:40:40.802 [debug] Get Custom Env Variables, Class name = Rm, completed in 7ms, has a truthy return value, Arg 1: "/Interactive-1.interactive", Arg 2: "RunPythonCode"
13:40:40.827 [debug] Attempting to determine version of IPyWidgets
13:40:40.827 [debug] Waiting for IPyWidgets version
13:40:40.827 [debug] Waiting for IPyWidgets version promise
13:40:40.913 [debug] Launching kernel .jvsc74a57bd0af2b7ca702bc007d49e4815451e788ef9429217bc2294f2515f5d80739c8b71b.~/github/pysindy/env/python.~/github/pysindy/env/python.-m#ipykernel_launcher for /Interactive-1.interactive in ~/github/pysindy with ports 9001, 9000, 9004, 9002, 9003
13:40:41.187 [debug] Got env vars with python ~/github/pysindy/env/bin/python, with env var count 75 in 392ms. 
    PATH value is ~/github/pysindy/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin and 
    Path value is undefined
13:40:41.187 [debug] Prepend PATH with python bin for ~/github/pysindy/env/bin/python
13:40:41.187 [debug] Activated Env Variables for ~/github/pysindy/env/bin/python, 
    PATH value is ~/github/pysindy/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin and 
    Path value is undefined
13:40:41.188 [debug] Getting activated env variables, Class name = yp, completed in 393ms, has a truthy return value, Arg 1: "/Interactive-1.interactive", Arg 2: "~/github/pysindy/env/bin/python", Arg 3: undefined
13:40:41.237 [info] Process Execution: ~/github/pysindy/env/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
13:40:41.238 [debug] Kernel Env Variables for python31012jvsc74a57bd0af2b7ca702bc007d49e4815451e788ef9429217bc2294f2515f5d80739c8b71b, PATH value is ~/github/pysindy/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/local/go/bin:/usr/local/go/bin:/usr/local/go/bin
13:40:41.279 [info] Process Execution: ~/github/pysindy/env/bin/python -m ipykernel_launcher --f=~/.local/share/jupyter/runtime/kernel-v2-31756Z3P7YrBoNA55.json
    > cwd: ~/github/pysindy
13:40:41.279 [info] Kernel process 34864.
13:40:41.906 [debug] Full interpreter list is length: 6, /usr/local/bin/python3.12::Unknown:/usr/local/bin/python3.12, /bin/python3::Unknown:/bin/python3, /usr/bin/python3::Unknown:/usr/bin/python3, /usr/local/bin/python3.11::Unknown:/usr/local/bin/python3.11, /usr/local/bin/python3.8::Unknown:/usr/local/bin/python3.8, ~/github/pysindy/env/bin/python:env:Venv:~/github/pysindy/env/bin/python
13:40:41.906 [debug] Refreshed Environments
13:40:41.983 [debug] ipykernel version & path 6.29.0, ~/github/pysindy/env/lib/python3.10/site-packages/ipykernel/__init__.py for ~/github/pysindy/env/bin/python
13:40:42.365 [debug] Kernel output: NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-v2-31756Z3P7YrBoNA55.json

13:40:42.526 [debug] Waiting for Raw Session to be ready in postStartRawSession
13:40:42.526 [debug] Waiting for Raw session to be ready, status: connected
13:40:42.526 [debug] Raw session connected
13:40:42.526 [debug] Waiting for Raw session to be ready
13:40:42.526 [debug] Waited for Raw session to be ready & got status: connected
13:40:42.526 [debug] Successfully waited for Raw Session to be ready in postStartRawSession
13:40:42.526 [debug] Kernel status is 'unknown' before requesting kernel info and after ready
13:40:42.526 [debug] Sending request for kernelInfo
13:40:42.537 [debug] Got response for requestKernelInfo
13:40:42.537 [debug] Successfully completed postStartRawSession after 1 attempt(s) in 11ms
13:40:42.539 [debug] Executing silently Code (busy) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys
13:40:42.562 [debug] Executing silently Code (completed) = import sys as _VSCODE_sys\nprint(_VSCODE_sys.executable); del _VSCODE_sys with 1 output(s)
13:40:42.563 [debug] End sendTelemetryForPythonKernelExecutable after 24ms
13:40:42.563 [debug] Started running kernel initialization for /Interactive-1.interactive
13:40:42.563 [debug] Executing silently Code (idle) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy
13:40:42.699 [debug] Executing silently Code (completed) = try:\nimport ipywidgets as _VSCODE_ipywidgets\nprint("e976ee50-99ed-4aba-9b6b-9dcd5634d07d:IPy with 1 output(s)
13:40:42.700 [debug] Determined IPyWidgets Version as 8
13:40:42.700 [debug] Version of IPyWidgets 8 determined after 2.162s
13:40:42.700 [debug] Version of IPyWidgets 8 determined after 1.873s
13:40:42.702 [debug] Executing silently Code (idle) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip
13:40:42.725 [debug] Executing silently Code (completed) = import types as _VSCODE_types\nimport os\nimport hashlib as _VSCODE_hashlib\nfrom IPython import get_ip with 0 output(s)
13:40:42.726 [debug] Requesting Kernel info
13:40:42.726 [debug] Got Kernel info
13:40:42.726 [debug] End running kernel initialization, now waiting for idle
13:40:42.726 [debug] Waiting for idle on (kernel): 2a0633a5-d02a-47ac-ac40-81e98c722bc7 -> idle
13:40:42.726 [debug] Finished waiting for idle on (kernel): 2a0633a5-d02a-47ac-ac40-81e98c722bc7 -> idle
13:40:42.726 [debug] End running kernel initialization, session is idle
13:40:42.729 [info] Registering Kernel Completion Provider from kernel env (Python 3.10.12) for language python
13:40:42.730 [debug] IPyWidgetScriptSource.initialize
13:40:42.730 [debug] Registering commtarget jupyter.widget
13:40:42.730 [debug] IPyWidgetMessageDispatcher.initialize
13:40:42.732 [debug] getDataDirsImpl, Class name = Fr (started execution), Arg 1: "/Interactive-1.interactive", Arg 2: "~/github/pysindy/env/bin/python"
13:40:42.732 [debug] Get Custom Env Variables, Class name = Rm (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
13:40:42.733 [debug] Get Custom Env Variables, Class name = Rm, completed in 1ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
13:40:42.733 [debug] Jupyter Paths : 
13:40:42.768 [info] Process Execution: ~/github/pysindy/env/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/pythonFiles/printJupyterDataDir.py
13:40:42.886 [warn] Got an empty Jupyter Data Dir from ~/github/pysindy/env/bin/python, stderr = undefined
13:40:42.887 [debug] getDataDirsImpl, Class name = Fr, completed in 155ms, has a truthy return value, Arg 1: "/Interactive-1.interactive", Arg 2: "~/github/pysindy/env/bin/python", Return Value: <Uri:~/.local/share/jupyter>, <Uri:~/github/pysindy/env/share/jupyter>, <Uri:/usr/local/share/jupyter>, <Uri:/usr/share/jupyter>
13:40:42.934 [info] End refreshing Kernel Picker (1710078039849)
13:40:43.262 [debug] IPyWidgetMessageDispatcher.initialize
13:40:43.262 [debug] Web view is ready to receive widget messages
13:40:43.290 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
13:40:43.291 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
13:40:43.301 [debug] IPyWidgetMessageDispatcher.initialize
13:40:43.301 [debug] IPyWidgetMessageDispatcher.initialize
13:40:43.313 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/temp/scripts/5ae505615fc00072cd1edee9092133f0ec478d4945358eb5eebc816aa5e7b28e/jupyter
13:40:43.313 [debug] Widget Message: Received IPyWidgets_kernelOptions in ScriptManager
13:40:43.317 [debug] Widget Message: Received IPyWidgetMessages.IPyWidgets_kernelOptions
13:40:43.317 [debug] Widget Message: data-base-url set to https://file%2B.vscode-resource.vscode-cdn.net~/.vscode/extensions/ms-toolsai.jupyter-2024.2.0-linux-x64/temp/scripts/5ae505615fc00072cd1edee9092133f0ec478d4945358eb5eebc816aa5e7b28e/jupyter
13:40:44.056 [debug] Jupyter completion time: 11
13:40:44.819 [info] Handle Execution of Cells 1 for /Interactive-1.interactive
13:40:44.825 [debug] Cell Index:1 sent to kernel
13:40:44.838 [debug] Start cell 1 execution @ 1710078044837 (clear output)
13:40:44.839 [info] Kernel acknowledged execution of cell 1 @ 1710078044837
13:40:44.843 [info] End cell 1 execution after 0.005s, completed @ 1710078044842, started @ 1710078044837
13:40:44.844 [debug] Cell 1 executed successfully
```

</details>

I wonder if installing the package performs a more robust kernel discovery than merely opening a window or starting up VSCode.  Regardless, my bug is personally fixed.  I'm happy to close the issue, or I'm happy to try to do more debugging steps if it would help :)

**Comment by DonJayamanne** [comment] 2024-03-11 19:51
This is a duplicate of https://github.com/microsoft/vscode/issues/204416

I.e. the fact that you had a large number of kernels cause running of cells to fail.

**Closed as completed by DonJayamanne** 2024-03-11 19:51 UTC
Labels: bug, info-needed, upstream-vscode, notebook-execution
