### ISSUE TITLE
Settings for controlling if outputs should be saved to disk

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4670] opened 2021-02-05 05:01 UTC
Maybe there is already an issue tracking this but I didn't find through search. It would be great if Jupyter has a setting to control if outputs should be transient or not. When set to true, Jupyter content provider can set outputs as transient so outputs change won't make the document dirty.

**Comment by greazer** [comment] 2021-02-16 23:40
Thanks for the recommendation!

**Comment by claudiaregio** [comment] 2021-05-25 04:37
Have received significant amount of feedback from users who are using the native notebooks diffing experience.
They would like to able to omit outputs when git committing notebooks, specifically called out this example a few times.

I asked if using the "Clear all outputs" button in the global notebook toolbar would suffice for them but users mentioned not remembering that was up there and that they would like to be able to do it in one action not two. One user specifically called out the following extension:
https://github.com/kynan/nbstripout

**Comment by DonJayamanne** [comment] 2021-05-25 04:44
I think we should consider adding this into VSCode.
I've implemented this same feature in Kusto notebooks.
Feels like something generic for VS Code.

Similar to toolbar position per viewtype, we can have `Save Notebook Outputs` per viewtype.
This can be achieved easily from VS Code by passing an empty array into the serializer, when saving notebooks.

I personally think this would be useful for rest notebooks as well, one might want the output from the REST api to be saved in the notebook, just like kusto notebooks (some might want the charts/data & some might not)

Thus all notebooks can be considered serializable (including output) & user choses whether the output is to be persisted on disc or not.

@rebornix thoughts?

**Comment by danchitnis** [comment] 2021-06-15 18:03
Can we not simply clear the cell outputs before saving the notebook? both commands are available, they just need to run in a sequence.

**Comment by claudiaregio** [comment] 2021-06-21 22:18
+1 Python blog comment feedback 
![image](https://user-images.githubusercontent.com/19276747/122834678-de89b100-d2a3-11eb-8b54-25358e464dac.png)

**Comment by rchiodo** [comment] 2021-08-31 00:07
Dupe of https://github.com/microsoft/vscode/issues/131944

**Closed by rchiodo** 2021-08-31 00:07 UTC
Labels: enhancement, notebook-serialization-save-load, needs-inspection
