### ISSUE TITLE
Running Python code in a Jupyter notebook fails to install missing notebook dependencies

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#11854] opened 2022-11-01 16:58 UTC
Encountered this in a UX study, cc @bamurtaugh for environment details

**Comment by bamurtaugh** [comment] 2022-11-03 18:47
Thanks for opening, @joyceerhl!

@stevencl would you be able to provide the VM details and info about the Python setup within it? It seems I don't have access to the VM now.

**Comment by stevencl** [comment] 2022-11-04 14:40
@bamurtaugh - The VMs were shut down but I have restarted them now so you should be able to access them.

**Comment by bamurtaugh** [comment] 2022-11-04 15:19
Thanks @stevencl!

Here's the environment info:

OS: Microsoft Windows 11 Pro
Version: 10.0.22000 Build 22000

VS Code Stable, version info:
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

Python 3.11.0 64-bit

Let me know if I can provide any other info.

**Comment by roblourens** [comment] 2022-11-09 17:14
What error message did you get? The log from the Jupyter output channel would be ideal, if you're still able to repro this

**Comment by DonJayamanne** [comment] 2022-12-05 23:48
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by bamurtaugh** [comment] 2023-01-30 18:58
Thanks folks for taking a look at this! I'm revisiting it now.

Here's an example loop if I don't have Python installed at all - I get the first toast, then I'm directed to the quick pick, which just pops the toast again:

![image](https://user-images.githubusercontent.com/25310137/215569457-adf7b338-fe0e-4ad5-9ec6-1924a585c67d.png)

![image](https://user-images.githubusercontent.com/25310137/215569504-c411568b-23d6-470b-8488-6506e7e72999.png)

I believe there were other issue(s) too, so I'll work on reproducing those.

**Comment by DonJayamanne** [comment] 2023-01-30 19:14
@bamurtaugh 
Please could you install VS Code insiders and the latest pre-release version of Jupyter and Python extension
Then please try to repro that issue in there and let me know how that goes.
I believe this has been fixed in the latest pre-release version with the new kernel picker.

**Comment by bamurtaugh** [comment] 2023-01-30 22:27
Thanks @DonJayamanne - I'm trying to open in Insiders the same way I did in desktop, but I'm now running into a separate issue https://github.com/microsoft/vscode/issues/172860, so I'll keep you updated.

**Comment by bamurtaugh** [comment] 2023-01-31 18:23
I revisited this flow today with the latest VS Code Insiders and pre-release version of the Python and Jupyter extensions (worked around the issue I linked above by cloning the repo locally rather than trying to use Remote Repositories or Continue On from vscode.dev). I'm testing on a Windows 10 VM where I only have VS Code Insiders and git installed.

I'm now correctly prompted with installing Python from the Windows store:

![image](https://user-images.githubusercontent.com/25310137/215847739-e9692e5f-9789-4f91-b2ad-fc4ddba532ea.png)
![image](https://user-images.githubusercontent.com/25310137/215847841-6d9f7e5f-3010-4cb8-bcca-6d4fd938b051.png)

But once the Python install completes and I try running the cell again, I'm told Python still isn't installed:
![image](https://user-images.githubusercontent.com/25310137/215848122-f88f4ac5-b56b-4b8a-ac65-c8b18287faf5.png)

I expected to need to reload VS Code, so I close the above prompt and reload.

Now Python is detected, and I'm prompted I'm missing a different package:
![image](https://user-images.githubusercontent.com/25310137/215848554-e70dfad5-0c48-4a47-9ecf-996f602a92c9.png)

I select `Install`, which seems to work:
![image](https://user-images.githubusercontent.com/25310137/215848646-081a60fa-34b2-462a-9938-038ce6b2f26b.png)

But, I'm now told `Failed to start the Kernel`:
![image](https://user-images.githubusercontent.com/25310137/215848912-b28bc1a3-2010-43d3-a780-fa3c6385a95b.png)

Here's the output log:
```
Visual Studio Code - Insiders (1.75.0-insider, undefined, desktop)
Jupyter Extension Version: 2023.1.2000281008.
Python Extension Version: 2023.3.10311007.
Workspace folder c:\Users\bamurtaugh\Documents\python-tuples
warn 18:19:26.569: Exception while attempting zmq : The specified module could not be found.
\\?\c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\node_modules\zeromq\prebuilds\win32-x64\electron.napi.node
User belongs to experiment group 'jupyterTest'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 18:19:27.053: LSP Notebooks experiment is enabled
info 18:19:35.495: Find preferred kernel for c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb with metadata {"kernelspec":{"display_name":"Python","language":"python","name":"conda-env-python-py"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.6.7"}} & preferred interpreter c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe
info 18:19:35.499: Preferred kernel .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], false, false)
info 18:19:35.499: PreferredConnection: .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb
info 18:19:35.602: Find preferred kernel for c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb with metadata {"kernelspec":{"display_name":"Python","language":"python","name":"conda-env-python-py"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.6.7"}} & preferred interpreter c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe
info 18:19:35.604: Preferred kernel .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], false, false)
info 18:19:35.604: PreferredConnection: .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb
info 18:19:35.820: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:19:35.855: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:19:35.969: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m pip list
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m pip list
info 18:19:46.848: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]) for 'c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb' (disableUI=false)
info 18:19:46.850: Checking for server existence.
info 18:19:48.297: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:19:48.520: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
warn 18:19:49.940: Error occurred while trying to start the kernel, options.disableUI=false [lf [Error]: Jupyter cannot be started. Error attempting to locate Jupyter: Running cells requires jupyter and notebook package.
	at bm.startServer (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:253091)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async bm.createServer (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:252386)
	at async Xf.connect (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:230691)
	at async fm.create (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:250430)
	at async Zm.createJupyterSession (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:306419)] {
  category: 'jupyterinstall'
}
warn 18:19:49.941: Kernel Error, context = start [lf [Error]: Jupyter cannot be started. Error attempting to locate Jupyter: Running cells requires jupyter and notebook package.
	at bm.startServer (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:253091)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async bm.createServer (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:252386)
	at async Xf.connect (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:230691)
	at async fm.create (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:250430)
	at async Zm.createJupyterSession (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:306419)] {
  category: 'jupyterinstall'
}
info 18:19:50.117: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:19:50.159: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:19:50.327: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:20:23.460: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 18:20:23.672: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m pip install -U --user jupyter
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m pip install -U --user jupyter
error 18:21:41.979: Error in execution 

error 18:21:41.981: Error in execution (get message for cell) 
```

**Comment by DonJayamanne** [comment] 2023-01-31 21:39
**A couple of issues**
* As suggested we should probably prompt the user to reload vscode after installing Python or prompt the user to refresh the Python environments (reload seems simpler)
* This is a windows machine and zmq is not working!!!
* installing Jupyter did not work, probably need the debug logs, (but lets try to repro locally)

**Comment by DonJayamanne** [comment] 2023-01-31 21:39
@bamurtaugh thanks for providing the information.

**Comment by DonJayamanne** [comment] 2023-01-31 22:41
@bamurtaugh 
please could you check whether the following file exists on your windows VM (the one you used to replicate the bug reported above)
`c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\node_modules\zeromq\prebuilds\win32-x64\electron.napi.node`

This should be in the directory, not sure why its not there.
Is this a VM on azure or is this a VM on your local machine, please could you provide more info on how you created this VM

**Comment by bamurtaugh** [comment] 2023-01-31 22:50
It's an Azure VM I created through the Azure Portal. It uses the `Windows 10 Pro, version 21H2 - x64 Gen 1` image. It is linked to my personal email account.

I'll reconnect to the VM and let you know if the file exists.

**Comment by bamurtaugh** [comment] 2023-01-31 23:03
I created a fresh VM and followed the same exact steps (I deleted the last one; I'll keep this one around as we continue debugging this).

I now get a new error after installing the Jupyter packages:

![image](https://user-images.githubusercontent.com/25310137/215903754-048a6d2c-964b-4540-bfe0-54516f62b33a.png)

With log:

```
Visual Studio Code - Insiders (1.75.0-insider, undefined, desktop)
Jupyter Extension Version: 2023.1.2000281008.
Python Extension Version: 2023.3.10311007.
Workspace folder c:\Users\bamurtaugh\Documents\python-tuples
warn 23:00:13.195: Exception while attempting zmq : The specified module could not be found.
\\?\c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\node_modules\zeromq\prebuilds\win32-x64\electron.napi.node
User belongs to experiment group 'jupyterTestcf'
User belongs to experiment group 'jupyterEnhancedDataViewer'
info 23:00:13.502: LSP Notebooks experiment is enabled
info 23:00:21.886: Find preferred kernel for c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb with metadata {"kernelspec":{"display_name":"Python","language":"python","name":"conda-env-python-py"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.6.7"}} & preferred interpreter c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe
info 23:00:21.888: Preferred kernel .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (true, [object Object], false, false)
info 23:00:21.888: PreferredConnection: .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb
info 23:00:22.269: Find preferred kernel for c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb with metadata {"kernelspec":{"display_name":"Python","language":"python","name":"conda-env-python-py"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.6.7"}} & preferred interpreter c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe
info 23:00:22.271: Preferred kernel .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher is exact match or top match for non python kernels, (false, [object Object], false, false)
info 23:00:22.272: PreferredConnection: .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb
info 23:00:24.648: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:00:24.727: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m pip list
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m pip list
info 23:00:24.856: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:00:26.851: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0d2a35b34d040b4ace21e0f09d91e639fc99afa659fca3ebf27413bc6a0446aba.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.c:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\python3.10.exe.-m#ipykernel_launcher (Python Path: , EnvType: Unknown, EnvName: '', Version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]) for 'c:\Users\bamurtaugh\Documents\python-tuples\Tuples.ipynb' (disableUI=false)
info 23:00:26.852: Checking for server existence.
info 23:00:28.202: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:00:28.846: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
warn 23:00:30.365: Error occurred while trying to start the kernel, options.disableUI=false [lf [Error]: Jupyter cannot be started. Error attempting to locate Jupyter: Running cells requires jupyter and notebook package.
	at bm.startServer (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:253091)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async bm.createServer (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:252386)
	at async Xf.connect (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:230691)
	at async fm.create (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:250430)
	at async Zm.createJupyterSession (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:306419)] {
  category: 'jupyterinstall'
}
warn 23:00:30.366: Kernel Error, context = start [lf [Error]: Jupyter cannot be started. Error attempting to locate Jupyter: Running cells requires jupyter and notebook package.
	at bm.startServer (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:253091)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async bm.createServer (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:252386)
	at async Xf.connect (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:230691)
	at async fm.create (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:250430)
	at async Zm.createJupyterSession (c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\extension.node.js:17:306419)] {
  category: 'jupyterinstall'
}
info 23:00:30.484: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:00:30.571: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import jupyter;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:00:30.747: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import notebook;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:00:33.784: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -c "import pip;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
info 23:00:34.344: Process Execution: > ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m pip install -U --user jupyter
> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m pip install -U --user jupyter
error 23:02:17.891: Error in execution ] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: C:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

error 23:02:17.892: Error in execution (get message for cell) ] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: C:\Users\bamurtaugh\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip
```

I do have `c:\Users\bamurtaugh\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.1.2000281008\out\node_modules\zeromq\prebuilds\win32-x64\electron.napi.node` on this VM.

**Comment by DonJayamanne** [comment] 2023-01-31 23:09
Thanks, I can repro this issue at my end.

**Comment by amunger** [comment] 2023-03-22 22:35
this persists through a Reload Window.

**Comment by DonJayamanne** [comment] 2023-03-22 23:32
@amunger 
Please could you share the logs for Jupyter and Python extension
Looks like a bug in VS Code it self, as the soruces should appear as `Jupyter Kernels, Pytohn Environmetns, Existing Jupyter Server` @rebornix /cc You might know whats going on here, as this is a dif

* Please share verbose logs for Jupyter 
* Please share verbose logs for Python (check if the Python extension has loaded successfully)
* Please check if there are any errors in the VS Code dev tools (console window, possible somethign has failed hter)

Also, aren't you running into a different issue all together, this issue is about not being able install the dependencies, and in your case you cannot see any kernel, these two different issues.

**Comment by DonJayamanne** [comment] 2023-03-23 00:13
I cannot replicate this issue, given the fact that this is stuck at detecting kernels and the sources are not displayed (which comes from core), i'm assigning this to @rebornix

**Comment by amunger** [comment] 2023-03-23 15:24
no errors in the dev tools console, just seems to be stuck in a loop - that repeating group of log lines is still repeating once per second, 10 minutes after I opened the notebook

```
Visual Studio Code - Insiders (1.77.0-insider, undefined, desktop)
Jupyter Extension Version: 2023.3.1000830504.
Python Extension Version: 2023.5.10821010.
No workspace folder opened.
warn 15:14:26.461: Exception while attempting zmq : The specified module could not be found.
\\?\c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.3.1000830504\out\node_modules\zeromq\prebuilds\win32-x64\node.napi.glibc.node
warn 15:14:26.461: Exception while attempting zmq (fallback) : The specified module could not be found.
\\?\c:\Users\aamunger\.vscode-insiders\extensions\ms-toolsai.jupyter-2023.3.1000830504\out\node_modules\zeromqold\prebuilds\win32-x64\electron.napi.node
User belongs to experiment group 'jupyterEnhancedDataViewer'
User belongs to experiment group 'jupyterTestcf'
debug 15:14:29.278: Updating cache with Python kernels 
, Added = 
, Updated = 
, Removed = 
debug 15:14:29.279: Get Custom Env Variables, Class name = Vl (started execution), Arg 1: undefined, Arg 2: "RunPythonCode"
debug 15:14:29.281: Start refreshing Kernel Picker (1679584469281)
debug 15:14:29.283: Found 0 cached controllers
info 15:14:29.291: LSP Notebooks experiment is enabled
debug 15:14:29.291: Get Active Interpreter, Class name = as (started execution), Arg 1: undefined
debug 15:14:31.373: Get Custom Env Variables, Class name = Vl, completed in 2094ms, has a truthy return value, Arg 1: undefined, Arg 2: "RunPythonCode"
debug 15:14:31.390: Get Jupyter Sub Paths, Class name = Dp, completed in 2111ms, has a truthy return value, Arg 1: "", Arg 2: "kernels", Return Value: 
debug 15:14:31.390: Listing kernels for 0 interpreters ()
debug 15:14:31.394: Get Jupyter Kernel Paths, Class name = Dp, completed in 2115ms, has a truthy return value, Arg 1: "", Return Value: 
debug 15:14:31.405: Get KernelSpec root path, Class name = Dp, completed in 2126ms, has a truthy return value, Arg 1: {"a":false,"b":null}, Return Value: <Uri:/c:/Users/aamunger/AppData/Roaming/jupyter/kernels>, <Uri:/C:/ProgramData/jupyter/kernels>
debug 15:14:32.037: Not Searching for kernels as path does not exist, c:\Users\aamunger\AppData\Roaming\jupyter\kernels
debug 15:14:32.038: Not Searching for kernels as path does not exist, c:\ProgramData\jupyter\kernels
debug 15:14:32.692: Get Active Interpreter, Class name = as (started execution), Arg 1: undefined
debug 15:14:32.692: Get Active Interpreter, Class name = as (started execution), Arg 1: undefined
debug 15:14:46.482: Conda file returned by Python Extension is conda
debug 15:14:46.497: Full interpreter list after refreshing (total 7ms, resolve 4ms, refresh 3ms) is length: 0, 
debug 15:14:46.498: loadData after detecting changes to interpreters
debug 15:14:46.498: Updating cache with Python kernels 
, Added = 
, Updated = 
, Removed = 
debug 15:14:46.498: refreshData after detecting changes to interpreters
debug 15:14:46.498: Listing kernels for 0 interpreters ()
debug 15:14:46.502: Full interpreter list is length: 0, 
debug 15:14:46.502: Refreshed Environments
debug 15:14:46.509: Full interpreter list after refreshing (total 1ms, resolve 0ms, refresh 1ms) is length: 0, 
debug 15:14:46.509: loadData after detecting changes to interpreters
debug 15:14:46.509: Updating cache with Python kernels 
, Added = 
, Updated = 
, Removed = 
debug 15:14:46.509: refreshData after detecting changes to interpreters
debug 15:14:46.509: Listing kernels for 0 interpreters ()
debug 15:14:46.512: Full interpreter list is length: 0, 
debug 15:14:46.512: Refreshed Environments
debug 15:14:46.579: Full interpreter list after refreshing (total 1ms, resolve 1ms, refresh 0ms) is length: 0, 
debug 15:14:46.580: loadData after detecting changes to interpreters
debug 15:14:46.580: Updating cache with Python kernels 
, Added = 
, Updated = 
, Removed = 
debug 15:14:46.580: refreshData after detecting changes to interpreters
debug 15:14:46.580: Listing kernels for 0 interpreters ()
debug 15:14:46.583: Full interpreter list is length: 0, 
debug 15:14:46.583: Refreshed Environments
debug 15:14:46.590: Full interpreter list after refreshing (total 1ms, resolve 1ms, refresh 0ms) is length: 0, 
debug 15:14:46.591: loadData after detecting changes to interpreters
debug 15:14:46.591: Updating cache with Python kernels 
, Added = 
, Updated = 
, Removed = 
debug 15:14:46.591: refreshData after detecting changes to interpreters
debug 15:14:46.591: Listing kernels for 0 interpreters ()
debug 15:14:46.593: Full interpreter list is length: 0, 
debug 15:14:46.593: Refreshed Environments
debug 15:14:46.600: Full interpreter list after refreshing (total 1ms, resolve 1ms, refresh 0ms) is length: 0, 
debug 15:14:46.601: loadData after detecting changes to interpreters
debug 15:14:46.601: Updating cache with Python kernels 
, Added = 
, Updated = 
, Removed = 
```

**Comment by rebornix** [comment] 2023-03-23 17:45
```
debug 15:14:46.591: refreshData after detecting changes to interpreters
debug 15:14:46.591: Listing kernels for 0 interpreters ()
debug 15:14:46.593: Full interpreter list is length: 0, 
debug 15:14:46.593: Refreshed Environments
debug 15:14:46.600: Full interpreter list after refreshing (total 1ms, resolve 1ms, refresh 0ms) is length: 0, 
debug 15:14:46.601: loadData after detecting changes to interpreters
debug 15:14:46.601: Updating cache with Python kernels 

```

Is this indicating that we are not getting interpreters from the Python extension?

**Comment by DonJayamanne** [comment] 2023-03-23 18:52
> download vscode insiders and install pre-release jupyter and python

Do you mean install Jupyter extenswion and Python runtime or Python extension?
I misundertood this and installed the Python runtime.

**Comment by DonJayamanne** [comment] 2023-03-23 19:08
@amunger I too can replicate this on a new VM, the difference was  i installed Python instead of Python extension

**Comment by DonJayamanne** [comment] 2023-03-23 19:27
@amunger found the issue, and submitted a fix for this..

**Closed** 2023-03-23 19:51 UTC
Labels: bug, info-needed, verification-found, author-verification-requested, notebook-kernel-picker, notebook-kernel-startup
