### ISSUE TITLE
Long lines in output don't wrap or show scrollbars (new version of notebooks in the insiders edition)

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-jupyter#4471] opened 2021-01-24 11:24 UTC
Issue Type: <b>Bug</b>

Long lines in the output of notebook cells (produced by python code) don't wrap or show scrollbars, making it impossible to view the full output:

![image](https://user-images.githubusercontent.com/8631181/105628734-f6692000-5e3e-11eb-88dc-fcda12fe7abc.png)

Note that I have scrolling enabled in the settings.

Extension version: 2020.12.414227025
VS Code version: Code - Insiders 1.53.0-insider (4d0d36c6ab154d841263c8d223a4bd1b9af07a23, 2021-01-20T09:11:49.862Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.15.0-123-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.97GB free)|
|Process Argv|--crash-reporter-id d0092040-d4fc-4c5d-89c1-5c594ed4fde4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: spidsmus.sdma.nzcorp.net|
|OS|Linux x64 4.15.0-123-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz (12 x 3092)|
|Memory (System)|58.98GB (3.49GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221882
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30208930
wsl2promptcf:30219163
vstry244:30244315
pythonvsdeb440:30224570
unusedprompt:30219164
folderexplorercf:30219167
openfilemenu:30219168
pythonvsded773:30223139
pythonvspyt600cf:30247032
core-portspanelcf:30233468

```

</details>

**Comment by claudiaregio** [comment] 2021-01-24 19:11
Hi @ldorigo, closing as dupe of https://github.com/microsoft/vscode/issues/110825. 
You can upvote the issue there if you would like this feature supported.

**Closed by claudiaregio** 2021-01-24 19:11 UTC
