### ISSUE TITLE
Kill / remove kernel option

### ISSUE THREAD

**Issue by Syndorik** [microsoft/vscode-jupyter#7189] opened 2021-08-18 09:43 UTC
From jupyter notebook extension, I have seen that it is possible to change kernel. I was wondering if it is possible to kill and remove unused kernel instead of just restarting them? This would be useful when multiple kernel are created and unused in the same session.

**Comment by rchiodo** [comment] 2021-08-18 16:33
Thanks for the suggestion. Kernels should be killed when:
- You close VS code
- You close the notebook/interactive window that had the kernel selected.

Do you need another way to kill a kernel? Maybe while VS code is still open?

**Comment by Syndorik** [comment] 2021-08-23 08:26
I am actually using a remote server for Jupyter Notebook.
So when I close VsCode, kernels are usually still runing which is great when I let something run for hours. 

But because of this, sometime I have a lot of kernels that I don't use but are still possible to chose from the list of kernel. It would be great to have an option to remove them if possible!

**Comment by DonJayamanne** [comment] 2021-09-02 18:47
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1379

**Closed by DonJayamanne** 2021-09-02 18:47 UTC
Labels: enhancement, kernel-issues
