### ISSUE TITLE
Jupyter Notebook will not render ipyaggrid.

### ISSUE THREAD

**Issue by hayden-puckeridge** [microsoft/vscode-jupyter#10905] opened 2022-07-23 13:18 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Cannot render a table widget using ipyaggrid in VS Code Jupyter Notebok. 

When running the code below I have seen each of following responses:
* Content of all the cells in the notebook disappears and a prompt appears to save the file.
* Error popup: "Unable to find widget 'ipyaggrid' version '~0.2.2' from configured widget sources ["jsdelivr.com","unpkg.com"]. Expected behavior may be affected. Click [here](https://aka.ms/PVSCIPyWidgets) for more information."
* Cell output: "Error loading preloads: could not find renderer"

```
import pandas as pd

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

from ipyaggrid import Grid

column_defs = [{'field': c} for c in df.columns]

grid_options = {
    'columnDefs' : column_defs,
}

g = Grid(grid_data=df,
         width=600,
         height=500,
         grid_options=grid_options,
         center=True)
g
```

Have tried with VS Code and VS Code - Insiders, also with release, pre-release and previous versions of the Jupyter extension.

ipyaggrid v0.2.2 appears to be available from jsDelivr and UNPKG. 
ipyaggrid behaves as expected in notebooks outside of VS Code. 

### VS Code Version

Version: 1.69.2 (user setup) Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a Date: 2022-07-18T16:12:52.460Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.19042

### Jupyter Extension Version

v2022.6.1201981810

### Jupyter logs

```shell
info 23:7:12.440: Preferred Remote kernel for c:\Users\***\Untitled.ipynb is undefined
info 23:7:12.456: Preferred Remote kernel for c:\Users\***\Untitled.ipynb is undefined
info 23:7:12.457: Find preferred kernel for c:\Users\***\Untitled.ipynb with metadata {"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"vscode":{"interpreter":{"hash":"b0381650795492daa6e76ff104d734f3137a87c8f36c2eb4c4568bd13c4fda5f"}}} & preferred interpreter c:\Users\***\Anaconda3\python.exe
info 23:7:12.460: Preferred Remote kernel for c:\Users\***\Untitled.ipynb is undefined
info 23:7:12.460: Preferred kernel .jvsc74a57bd0b0381650795492daa6e76ff104d734f3137a87c8f36c2eb4c4568bd13c4fda5f.c:\Users\***\Anaconda3\python.exe.c:\Users\***\Anaconda3\python.exe.-m#ipykernel_launcher is exact match
info 23:7:12.461: PreferredConnection: .jvsc74a57bd0b0381650795492daa6e76ff104d734f3137a87c8f36c2eb4c4568bd13c4fda5f.c:\Users\***\Anaconda3\python.exe.c:\Users\***\Anaconda3\python.exe.-m#ipykernel_launcher found for NotebookDocument: c:\Users\***\Untitled.ipynb
info 23:7:12.492: Hiding xeus kernelspec
info 23:7:12.492: Hiding xeus kernelspec
info 23:7:12.495: Hiding xeus kernelspec
info 23:7:12.495: Hiding xeus kernelspec
info 23:7:12.499: Preferred Remote kernel for c:\Users\***\Untitled.ipynb is undefined
info 23:7:12.499: Find preferred kernel for c:\Users\***\Untitled.ipynb with metadata {"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.9.12"},"vscode":{"interpreter":{"hash":"b0381650795492daa6e76ff104d734f3137a87c8f36c2eb4c4568bd13c4fda5f"}}} & preferred interpreter c:\Users\***\Anaconda3\python.exe
info 23:7:12.501: Preferred Remote kernel for c:\Users\***\Untitled.ipynb is undefined
info 23:7:12.501: Preferred kernel .jvsc74a57bd0b0381650795492daa6e76ff104d734f3137a87c8f36c2eb4c4568bd13c4fda5f.c:\Users\***\Anaconda3\python.exe.c:\Users\***\Anaconda3\python.exe.-m#ipykernel_launcher is exact match
info 23:7:12.782: Registering dummy command feature
```

### Coding Language and Runtime Version

Python v3.9.12

### Language Extension Version (if applicable)

Python v2022.10.1

### Anaconda Version (if applicable)

4.13.0

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment] 2022-07-25 16:54
thanks for the bug, aside from the direct issue with the widget rendering, this seems to also expose some issues with error handling in core.

- The open editor crashes and offers a save prompt, but the save operation seems to fail -> potential data loss
- The Jupyter logs seem to clear when the editor crashes, so diagnosing would be tough from bug reports (except that I have a repro)
- Sometimes the editor doesn't actually close after it has crashed, it's just no longer useable
- when re-opening the editor, the inputs don't appear, so there's still issues with that notebook until it is closed cleanly:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/2019016/180832735-40ac8c9f-43f0-406a-956e-95b73335457d.png">

**Comment by rebornix** [comment] 2022-07-25 19:53
> Sometimes the editor doesn't actually close after it has crashed, it's just no longer useable
> when re-opening the editor, the inputs don't appear, so there's still issues with that notebook until it is closed cleanly:


`CodeEditorWidget` doesn't allow text model to be used after it gets disposed and when the extension host died, the text models for cells are not cleared but only disposed, leading to the weird UX that the notebook can be reopen but none of the cells are rendered in cell editors properly.

We need to think about how to improve this experience.

**Comment by rchiodo** [comment] 2022-07-25 19:58
My guess is we're not looking for the right file. ipyaggrid exports this:

![image](https://user-images.githubusercontent.com/19672699/180863439-ba7dc2de-5fd0-4496-9a24-cea92fa2d84d.png)

In our code we look for index.js, not index.min.js.

https://github.com/microsoft/vscode-jupyter/blob/5682a864111a6bfa0b45d77373694d8ee5c4c152/src/notebooks/controllers/ipywidgets/scriptSourceProvider/cdnWidgetScriptSourceProvider.ts#L28

**Comment by hayden-puckeridge** [comment] 2022-07-26 07:23
Thanks for the response. See attached the error log from the dev console when running the sample code, followed by the editor crashing, cells clearing and unsuccessful save prompt.

[vscode-app-1658819761443.log](https://github.com/microsoft/vscode-jupyter/files/9187453/vscode-app-1658819761443.log)

**Comment by amunger** [comment] 2022-07-27 16:24
@hayden-puckeridge - those symptoms sound like the zmq crash. Can you try disabling zmq by adding `"jupyter.disableZMQSupport": true` to your settings json and check if it still repros (and provide the dev console logs again if the result is still bad but different)

**Comment by hayden-puckeridge** [comment] 2022-07-28 00:20
@amunger Thanks, with zmq disabled the widgets render correctly with no issues that I can see.

**Comment by amunger** [comment] 2022-07-28 16:04
thanks for the update, I'll just close this one as a dupe of #10386 then

**Closed by amunger** 2022-07-28 16:04 UTC
Labels: bug, info-needed, ipywidgets, specific-to-package-library, zmq, upstream-zmq
