### ISSUE TITLE
Jupyter math formuals not displayed correctly

### ISSUE THREAD

**Issue by liukidar** [microsoft/vscode-jupyter#4938] opened 2021-02-24 11:58 UTC
Issue Type: <b>Bug</b>

I have a jupyter notebook with this and other embedded code. Some of it is rendered correctly, some is just displayed as black text in a black framed box. It is curious to note that the formulas are all correctly displayed for a second or two when the document is loading.

\begin{align}
\label{eq:vae_likelihood}
p(x \mid z,\theta)&=\mathcal{N}(x; f(z; \theta_{f}), \sigma^{2} I)
\\
\label{eq:vae_prior}
p(z)&=\mathcal{N}(z; 0, I)
\\
\label{eq:vae_q}
q(z\mid x,\theta)&=\mathcal{N}(z; g(x;\theta_{g}), \mathrm{diag}(h(x;\theta_{h})^{2}))~,
\end{align}

Extension version: 2021.2.576440691
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (7.57GB free)|
|Process Argv|--crash-reporter-id 61c25ebf-c895-4069-8289-970689b35e8e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspyt653:30253241
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30256636
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30262999

```

</details>

Here's a screenshot: 
![image](https://user-images.githubusercontent.com/19915578/108997705-d45dfa00-7697-11eb-9627-cd3effa96a65.png)

**Comment by liukidar** [comment] 2021-02-24 11:59
Here's a screenshot:

**Comment by rchiodo** [comment] 2021-02-24 17:27
Thanks for the bug. This is a dupe of https://github.com/microsoft/vscode-jupyter/issues/4231.

We're working on a new notebook UI and markdown renderer that should eliminate these sort of problems. Please track the other bug for when that happens.

**Closed by rchiodo** 2021-02-24 17:27 UTC
