### ISSUE TITLE
Unable to start Kernel due to a timeout waiting for the ports to get used

### ISSUE THREAD

**Issue by Sun-tur-day** [microsoft/vscode-jupyter#14404] opened 2023-10-02 08:31 UTC
## Environment data

-   VS Code version: 1.82.2
-   Jupyter Extension version (available under the Extensions sidebar): v2023.8.1002501831
-   Python Extension version (available under the Extensions sidebar): v2023.16.0
-   OS (Windows | Mac | Linux distro) and version: Windows_NTx64 10.0.19045
-   Python and/or Anaconda version: 3.11.3
-   Type of virtual environment used : conda
-   Jupyter server running: Local 

## Expected behaviour

(codes)     >> print('Hello world')
(expected)>> Hello world

## Actual behaviour

Failed to start the Kernel. 

Unable to start Kernel 'base (Python 3.11.3)' due to a timeout waiting for the ports to get used. 

View Jupyter [log](command:jupyter.viewOutput) for further details.

## Steps to reproduce:

any code just can not run

[example](https://github.com/Sun-tur-day/verbose-system/blob/master/issure.gif)

note:
- file.py can run in vscode
- jupyter-notebook can run in browser

win+R(enter) -> cmd(enter)  -> jupyter-notebook(enter) 

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Visual Studio Code (1.82.2, undefined, desktop)
Jupyter Extension Version: 2023.8.1002501831.
Python Extension Version: 2023.16.0.
Platform: win32 (x64).
Workspace folder ~\Desktop\inbox, Home = c:\Users\1
<username>5:57:08.597 [info] Start refreshing Kernel Picker (<username>696233428597)
<username>5:57:08.603 [info] Using Pylance
<username>5:57:08.6<username>3 [info] Start refreshing Interpreter Kernel Picker
<username>5:57:08.974 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\files\<username>_anaconda\installLocation\python.exe.c:\files\<username>_anaconda\installLocation\python.exe.-m#ipykernel_launcher  (Python Path: c:\files\<username>_anaconda\installLocation\python.exe, Conda, base, 3.<username><username>.3) for '~\Desktop\inbox\a.ipynb' (disableUI=true)
<username>5:57:09.<username>08 [warn] Failed to get activated env vars for d:\file\<username>3_python\python.exe in 3<username>4ms
<username>5:57:09.<username><username>5 [info] Process Execution: d:\file\<username>3_python\python.exe -c "import site;print("USER_BASE_VALUE");print(site.USER_SITE);print("USER_BASE_VALUE");"
<username>5:57:09.<username>54 [info] Process Execution: d:\file\<username>3_python\python.exe -m pip list
<username>5:57:<username>2.582 [info] End refreshing Kernel Picker (<username>696233428597)
<username>5:57:<username>3.440 [info] Process Execution: c:\files\<username>_anaconda\installLocation\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
<username>5:57:<username>3.443 [info] Process Execution: c:\files\<username>_anaconda\installLocation\python.exe ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.<username>00250<username>83<username>-win32-x64\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py --ppid 85564
    > cwd: ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.<username>00250<username>83<username>-win32-x64\pythonFiles\vscode_datascience_helpers
<username>5:57:<username>3.447 [info] Process Execution: c:\files\<username>_anaconda\installLocation\python.exe -m pip list
<username>5:57:<username>3.564 [info] Process Execution: c:\files\<username>_anaconda\installLocation\python.exe -m ipykernel_launcher --ip=<username>27.0.0.<username> --stdin=9003 --control=900<username> --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"9e8b<username>0c7-9cda-4202-bed7-967865f04553" --shell=9002 --transport="tcp" --iopub=9004 --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-85564pbZuZxw6AtxH.json
    > cwd: ~\Desktop\inbox
<username>5:57:<username>3.777 [info] ipykernel version & path 6.<username>9.2, c:\files\<username>_anaconda\installLocation\Lib\site-packages\ipykernel\__init__.py for c:\files\<username>_anaconda\installLocation\python.exe
<username>5:57:<username>3.878 [error] waitUntilUsed timed out [Error: connect ETIMEDOUT <username>27.0.0.<username>:9004
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:<username>494:<username>6)] {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '<username>27.0.0.<username>',
  port: 9004
}
<username>5:57:<username>3.878 [error] Disposing kernel process due to an error Error: Unable to start Kernel 'base (Python 3.<username><username>.3)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\files\<username>_anaconda\installLocation\python.exe.c:\files\<username>_anaconda\installLocation\python.exe.-m#ipykernel_launcher
    > Interpreter Id = c:\FILES\<username>_ANACONDA\INSTALLLOCATION\PYTHON.EXE
    > at ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.<username>00250<username>83<username>-win32-x64\out\extension.node.js:24:87703
<username>5:57:<username>3.878 [error] 
<username>5:57:<username>3.879 [info] Dispose Kernel process 85608.
<username>5:57:<username>3.88<username> [info] Process Execution: c:\Windows\System32\taskkill.exe /F /T /PID 85608
<username>5:57:<username>4.<username><username>2 [error] Kernel Launcher. launch, Class name = ty, completed in 5<username>26ms, has a falsy return value, Arg <username>: ".jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\\files\\<username>_anaconda\\installLocation\\python.exe.c:\\files\\<username>_anaconda\\installLocation\\python.exe.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "/c:/Users/<username>/Desktop/inbox/a.ipynb", Arg 4: "~\\Desktop\\inbox", Arg 5: "" Error: Unable to start Kernel 'base (Python 3.<username><username>.3)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\files\<username>_anaconda\installLocation\python.exe.c:\files\<username>_anaconda\installLocation\python.exe.-m#ipykernel_launcher
    > Interpreter Id = c:\FILES\<username>_ANACONDA\INSTALLLOCATION\PYTHON.EXE
    > at ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.<username>00250<username>83<username>-win32-x64\out\extension.node.js:24:87703
<username>5:57:<username>4.<username><username>2 [error] Failed to connect raw kernel session: Error: Unable to start Kernel 'base (Python 3.<username><username>.3)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
<username>5:57:<username>4.<username><username>3 [warn] Error occurred while trying to start the kernel, options.disableUI=true Error: Unable to start Kernel 'base (Python 3.<username><username>.3)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\files\<username>_anaconda\installLocation\python.exe.c:\files\<username>_anaconda\installLocation\python.exe.-m#ipykernel_launcher
    > Interpreter Id = c:\FILES\<username>_ANACONDA\INSTALLLOCATION\PYTHON.EXE
    > at ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.<username>00250<username>83<username>-win32-x64\out\extension.node.js:24:87703
<username>6:04:3<username>.774 [info] Dispose Kernel '~\Desktop\inbox\a.ipynb' associated with '~\Desktop\inbox\a.ipynb'
<username>6:06:02.032 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\files\<username>_anaconda\installLocation\python.exe.c:\files\<username>_anaconda\installLocation\python.exe.-m#ipykernel_launcher  (Python Path: c:\files\<username>_anaconda\installLocation\python.exe, Conda, base, 3.<username><username>.3) for '~\Desktop\inbox\a.ipynb' (disableUI=true)
<username>6:06:02.035 [info] Process Execution: c:\files\<username>_anaconda\installLocation\python.exe -m pip list
<username>6:06:02.043 [info] Process Execution: c:\files\<username>_anaconda\installLocation\python.exe -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
<username>6:06:02.<username>39 [info] Process Execution: c:\files\<username>_anaconda\installLocation\python.exe -m ipykernel_launcher --ip=<username>27.0.0.<username> --stdin=90<username><username> --control=9009 --hb=9008 --Session.signature_scheme="hmac-sha256" --Session.key=b"8ce0200a-<username>99d-4093-848a-a9d206738e89" --shell=90<username>0 --transport="tcp" --iopub=90<username>2 --f=~\AppData\Roaming\jupyter\runtime\kernel-v2-85564ROQRGhpMiyXR.json
    > cwd: ~\Desktop\inbox
<username>6:06:02.372 [info] ipykernel version & path 6.<username>9.2, c:\files\<username>_anaconda\installLocation\Lib\site-packages\ipykernel\__init__.py for c:\files\<username>_anaconda\installLocation\python.exe
<username>6:06:02.445 [error] waitUntilUsed timed out [Error: connect ETIMEDOUT <username>27.0.0.<username>:90<username>0
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:<username>494:<username>6)] {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '<username>27.0.0.<username>',
  port: 90<username>0
}
<username>6:06:02.445 [error] Disposing kernel process due to an error Error: Unable to start Kernel 'base (Python 3.<username><username>.3)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\files\<username>_anaconda\installLocation\python.exe.c:\files\<username>_anaconda\installLocation\python.exe.-m#ipykernel_launcher
    > Interpreter Id = c:\FILES\<username>_ANACONDA\INSTALLLOCATION\PYTHON.EXE
    > at ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.<username>00250<username>83<username>-win32-x64\out\extension.node.js:24:87703
<username>6:06:02.445 [error] 
<username>6:06:02.445 [info] Dispose Kernel process 37648.
<username>6:06:02.448 [info] Process Execution: c:\Windows\System32\taskkill.exe /F /T /PID 37648
<username>6:06:02.7<username>0 [error] Kernel Launcher. launch, Class name = ty, completed in 67<username>ms, has a falsy return value, Arg <username>: ".jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\\files\\<username>_anaconda\\installLocation\\python.exe.c:\\files\\<username>_anaconda\\installLocation\\python.exe.-m#ipykernel_launcher", Arg 2: 60000, Arg 3: "/c:/Users/<username>/Desktop/inbox/a.ipynb", Arg 4: "~\\Desktop\\inbox", Arg 5: "" Error: Unable to start Kernel 'base (Python 3.<username><username>.3)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\files\<username>_anaconda\installLocation\python.exe.c:\files\<username>_anaconda\installLocation\python.exe.-m#ipykernel_launcher
    > Interpreter Id = c:\FILES\<username>_ANACONDA\INSTALLLOCATION\PYTHON.EXE
    > at ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.<username>00250<username>83<username>-win32-x64\out\extension.node.js:24:87703
<username>6:06:02.7<username><username> [error] Failed to connect raw kernel session: Error: Unable to start Kernel 'base (Python 3.<username><username>.3)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
<username>6:06:02.7<username><username> [warn] Error occurred while trying to start the kernel, options.disableUI=true Error: Unable to start Kernel 'base (Python 3.<username><username>.3)' due to a timeout waiting for the ports to get used. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0<username>83<username>cea0a5db93b7d74df9827e88dbd92686fc34706bb6b584dc3b7<username>43c427d3.c:\files\<username>_anaconda\installLocation\python.exe.c:\files\<username>_anaconda\installLocation\python.exe.-m#ipykernel_launcher
    > Interpreter Id = c:\FILES\<username>_ANACONDA\INSTALLLOCATION\PYTHON.EXE
    > at ~\.vscode\extensions\ms-toolsai.jupyter-2023.8.<username>00250<username>83<username>-win32-x64\out\extension.node.js:24:87703
```

</p>
</details>

**Comment by pothos-dev** [comment] 2023-10-10 14:07
I'm suddenly having the same issue.

Tried reinstalling VSCode and Python using multiple distributions (Anaconda, Miniconda, standalone), different python versions, Release and Pre-Release versions of the VSCode extension.

Scoured the internet for possible solutions, none worked.

I have the same issue in a Github Codespace, so it's unrelated to my computer.

Starting `jupyter notebook` from the terminal opens a working notebook, so the Python/Jupyter installation works generally, just not in VSCode.

**Comment by DonJayamanne** [comment] 2023-10-11 01:15
This is most likely due to some anit virus software of the like that is blocking the ports from getting used.
Please check whether there is some such software running at your end preventing this.

**Comment by DonJayamanne** [comment] 2023-10-27 05:53
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/14519#issuecomment-1778289425
@pothos-dev @Sun-tur-day 
Please could you try the custom VSIX in the above linked comment
Let me know how that goes.
Lets continue the discussion in that issue.

**Closed by DonJayamanne** 2023-10-27 05:53 UTC
Labels: bug, info-needed
