### ISSUE TITLE
Problème d'affichage des variables locales lors du débogage F10

### ISSUE THREAD

**Issue by profRidha** [microsoft/vscode-jupyter#16135] opened 2024-10-19 14:42 UTC
Type: <b>Bug</b>

Lors du débogage d'une cellule de code Jupyter dans Visual Studio Code en utilisant la touche F10 (exécution par ligne), il est observé que lorsque le code contient une fonction, l'activation de l'option "ouvrir l'affichage des variables" ne montre que les variables globales pendant le déroulement du débogage.
[https://youtu.be/wP3oCRQrsGg](url)
<img src= "https://i.postimg.cc/ry15vTRQ/Capture.png">
Extension version: 2024.10.2024100401
VS Code version: Code 1.94.2 (384ff7382de624fb94dbaf6da11977bba1ecd427, 2024-10-09T16:08:44.566Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.68GB free)|
|Process Argv|--crash-reporter-id 112baf61-ccbc-43d1-90db-9e4d7a969c3f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
945dj816:31013170
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31132770
nativeloc2:31134642
wkspc-ranged-t:31151552
cf971741:31144450
defaultse:31146405
iacca1:31156133
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31162478
icondisabled:31158250

```

</details>

**Comment by profRidha** [comment] 2024-10-20 10:06
À noter également que lorsque le débogage atteint une fonction, si je ferme le panneau des variables puis que je l'ouvre à nouveau, il affiche "Chargement des variables" sans rien montrer par la suite.
[https://youtu.be/BRrazmFqCFg](url)

<img src= "https://i.ibb.co/wC5Qkv7/Capture2.png">

**Comment by profRidha** [comment] 2024-10-23 11:44
C'est un problème de compatibilité de l'extension avec la dernière version de l'interpréteur **Python 3.13**

<img src= "https://i.postimg.cc/7ZgN5Gxg/cap1.png">

<img src= "https://i.postimg.cc/MG5bYCfH/cap2.png">

**Comment by profRidha** [comment] 2024-10-29 11:03
Why is this problem not declared as a BUG ?

**Comment by profRidha** [comment] 2024-10-29 17:33
Same problem under vscode 1.95 witdh Jupyter v2024.11.2024102401 (Python 3.13.0) !

**Comment by amunger** [comment] 2024-10-30 00:45
Can you translate this to english? I can't repro what your screenshot shows with that code:

```
def test(param_1, param_2):
    local_1 = param_1
    local_2 = param_2
    return local_1 + local_2

global_1 = 1
global_2 = 2
global_3 = test(global_1, global_2)
```

**Comment by profRidha** [comment] 2024-10-30 09:48
It's a simple code that contains global and local variables.
The purpose of this example is to indicate that the **display of local variables presents an issue.**

> Can you translate this to english? I can't repro what your screenshot shows with that code:
> 
> ```
> def test(param_1, param_2):
>     local_1 = param_1
>     local_2 = param_2
>     return local_1 + local_2
> 
> global_1 = 1
> global_2 = 2
> global_3 = test(global_1, global_2)
> ```

It's a simple code that contains global and local variables.
The purpose of this example is to indicate that the **display of local variables presents an issue.**
<img src="https://i.ibb.co/hm0Fs25/prob.png">

**Comment by profRidha** [comment] 2024-10-30 10:25
Note that the issue occurs only with **Python 3.13.0.**

Here is another example : 
<hr>
Watch this second video and see the content of the "Jupyter variables" tab during debugging : 
[https://youtu.be/VFUD9KHEeGI](url)
<hr>
<a href="https://ibb.co/pJ42qXc"><img src="https://i.ibb.co/Fg86p72/prob44.png">

**Comment by profRidha** [comment] 2024-10-30 10:39
Try to see this image: there are no issues during debugging when the debugger reaches the function (with Python 3.12.7), but there is no display of the variables (with Python 3.13.0).
<img src="https://i.ibb.co/z5t6tGd/problem7.png">

**Comment by profRidha** [comment] 2024-10-31 19:22
...

**Comment by amunger** [comment] 2024-10-31 21:17
marking as duplicate of https://github.com/microsoft/vscode-jupyter/issues/16187

**Closed by amunger** 2024-10-31 21:17 UTC
Labels: info-needed, variable-explorer, triage-needed
