### ISSUE TITLE
Export to HTML fails

### ISSUE THREAD

**Issue by Zoxjib** [microsoft/vscode-jupyter#9012] opened 2022-02-12 11:54 UTC
## Environment data

-   VS Code version: 1.64.2
-   Jupyter Extension version: v2022.1.1201831736
-   Python Extension version: v2022.0.1814523869
-   OS and version: Windows 10, 10.0.19043, Build 19043
-   Python: 3.10.2
-   nbconvert: 6.4.2
-   Jupyter server running: Local

## Expected behaviour

Export to HTML of .ipynb notebook to create a .html file

## Actual behaviour

Export failure

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Choose any .ipynb file
2. Click Export
3. Choose HTML

## Logs

```
Info 13:39:08: Process Execution: > ~\AppData\Local\Programs\Python\Python310\python.exe -m jupyter nbconvert c:\Users\username\AppData\Local\Temp\88e203ff-653a-47c7-b68b-fc9c26da5fa9\Ses3.ipynb --to html --output tmp-21320bRBXXdezrOKt.html --output-dir ~\AppData\Local\Temp --debug
> ~\AppData\Local\Programs\Python\Python310\python.exe -m jupyter nbconvert c:\Users\username\AppData\Local\Temp\88e203ff-653a-47c7-b68b-fc9c26da5fa9\Ses3.ipynb --to html --output tmp-21320bRBXXdezrOKt.html --output-dir ~\AppData\Local\Temp --debug
Error 13:39:08: Export failed [Error: usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands:

Jupyter command `jupyter-nbconvert` not found.

	at a.executeCommand (c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2022.1.1201831736\out\client\extension.js:24:110265)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async a.export (c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2022.1.1201831736\out\client\extension.js:66:1162036)
	at async _.exportToFormat (c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2022.1.1201831736\out\client\extension.js:66:1160286)
	at async _.performNbConvertExport (c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2022.1.1201831736\out\client\extension.js:66:1159502)
	at async _.performExport (c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2022.1.1201831736\out\client\extension.js:66:1159127)
	at async _.exportImpl (c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2022.1.1201831736\out\client\extension.js:66:1158576)
	at async _.export (c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2022.1.1201831736\out\client\extension.js:66:1158309)
	at async b.export (c:\Users\username\.vscode\extensions\ms-toolsai.jupyter-2022.1.1201831736\out\client\extension.js:51:588177)
	at async u._executeContributedCommand (c:\Users\username\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:30224)]
```

I'm getting similar behavior with Export to PDF, with MiKTeX installed and up-to-date, including the `Jupyter command jupyter-nbconvert not found.` followed by a missing TeX error:

```
Error 14:15:28: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions go to https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.
```

**Comment by dynamicwebpaige** [comment] 2022-02-14 06:47
Confirmed, and can replicate; am also experiencing this issue in the latest Insiders' build.

<img width="473" alt="Screen Shot 2022-02-13 at 10 45 43 PM" src="https://user-images.githubusercontent.com/3712347/153813721-e6424f97-407a-475f-9c97-4756cfb8dcd7.png">

**Comment by amunger** [comment] 2022-02-14 18:43
I can't get this to repro, but it looks like we we're not able to ensure that nbconvert was installed. Can you try and manually install nbconvert in your python environment and see if this still occurs?
Also, just to confirm, what do you have for the `Jupyter: Python Export Method` settings?

**Comment by amunger** [comment] 2022-02-14 18:44
possibly related (but should be fixed in latest insiders): https://github.com/microsoft/vscode-jupyter/issues/6838

**Comment by Zoxjib** [comment] 2022-02-14 19:19
> I can't get this to repro, but it looks like we we're not able to ensure that nbconvert was installed. Can you try and manually install nbconvert in your python environment and see if this still occurs? 

After performing `pip uninstall nbconvert` and then `pip install nbconvert` the export works as expected.

> Also, just to confirm, what do you have for the `Jupyter: Python Export Method` settings?

I had `Jupyter: Python Export Method` set to the default `direct`. I tried switching to `nbconvert` and encountered the same error. After I manually reinstalled nbconvert then the export worked as expected with both settings.

**Comment by amunger** [comment] 2022-02-14 21:25
@dynamicwebpaige - can you check if nbconvert is currently installed in your python environment as well? And also verify that reinstalling resolves the issue?

**Comment by amunger** [comment] 2022-03-31 19:57
closing for now as the workaround seems to resolve the issue and we haven't heard of any more issues with it

**Closed by amunger** 2022-03-31 19:57 UTC
Labels: bug, info-needed, notebook-import-export, nb-golden
