### ISSUE TITLE
Rework restart for kernels

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7103] opened 2021-08-12 18:24 UTC
@DonJayamanne and I were just discussing refactoring INotebook.restartKernel into IKernel, and it occurred to us that our code is complicated by retaining the same kernel instance on restart and rerunning all of our initialization commands. Instead we should simply kill the kernel and spin up a new instance.

One issue is to ensure that IPyWidgets get correctly hooked up when the current kernel gets shut down in favor of a new kernel getting spun up, and make sure that the onDidRestart event is handled properly everywhere that it's currently handled.

**Comment by rchiodo** [comment] 2021-08-12 21:31
Dupe of #7086

**Closed by rchiodo** 2021-08-12 21:31 UTC
Labels: bug, needs-triage
