### ISSUE TITLE
Renaming variables didn't work

### ISSUE THREAD

**Issue by ted1030** [microsoft/vscode-jupyter#7433] opened 2021-09-07 13:54 UTC
## Environment data

-   VS Code version: 1.60.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2031190714
-   Python Extension version (available under the Extensions sidebar): v2021.9.1191016588
-   OS (Windows | Mac | Linux distro) and version: Windows 10 20H2
-   Python and/or Anaconda version: 3.8.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

All matched variables are renamed.

## Actual behaviour
Show a message "No result" at the corner.
![image](https://user-images.githubusercontent.com/37107237/132355651-0389fd88-1b4a-49d5-b92e-90f66a0b1ce3.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Create a new blank jupyter notebook by the command in VS Code.
2. Declare a variable.
3. Rename the variable(select the variable and press F2).

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

No any logs produce in Output > Jupyter panel  when renaming a variable. Maybe the problem isn't caused by jupyter.

**Comment by IanMatthewHuff** [comment] 2021-09-08 00:15
@ted1030 Thanks for the report, I repro the same thing. Some language features are currently not supported in notebooks, but we are making plans now to hopefully bring more of those online soon.

**Comment by IanMatthewHuff** [comment] 2021-09-09 20:49
Dupe of #5123

**Closed by IanMatthewHuff** 2021-09-09 20:49 UTC
Labels: bug, needs-triage
