### ISSUE TITLE
ms-toolsai.jupyter Causes Extension Host Crash

### ISSUE THREAD

**Issue by Galbaz1** [microsoft/vscode-jupyter#15721] opened 2024-05-28 08:05 UTC
Type: <b>Bug</b>

1. Start Cursor
2. Try to initialize Git repo.
3. The extension host crashes with an error message about ms-toolsai.jupyter.

Extension version: 2024.4.0
VS Code version: Cursor 0.34.0 (838bc2665badb9638e37757a74e5586cfea89e50, 2024-05-27T00:09:09.301Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 7, 6|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DonJayamanne** [comment] 2024-05-28 21:10
Thank you for filing this issue and sorry you are running into this.
* Please can you try using the official version of VS Code, I'm suspect this crash may have something to do with the Cursor version of VS ,Code.
* Also, please can you disable all extensions except for Jupyter extension and try again
* Finally, try opening a separate empty folder and see if that makes a difference

**Comment by DonJayamanne** [comment] 2024-06-03 13:43
Given this is caused by a non-standard version of VS Code, I'm closing this issue.
If however you run into this same issue or others with the stable/Insiders Version of VS Code, please feel free to ping here or please file a new issue.

**Closed by DonJayamanne** 2024-06-03 13:43 UTC
Labels: info-needed, triage-needed
