### ISSUE TITLE
Cannot run code chunk of R: Error in parse(text = x, srcfile = src)

### ISSUE THREAD

**Issue by skymagician** [microsoft/vscode-jupyter#7656] opened 2021-09-24 09:59 UTC
## Environment data

-   VS Code version: 1.60.2 (system setup)
-   Jupyter Extension version: v2021.8.2041215044
-   Python Extension version: v2021.9.1246542782
-   Windows version: 21H1 (19043.1237)
-   Anaconda version: 2021.05
-   Type of virtual environment used: conda 4.10.3
-   Jupyter server running: Local
-   R version: 4.1.1 for windows x64
-   [R Extension for Visual Studio Code v2.3.0](https://github.com/REditorSupport/vscode-R)

## Expected behaviour
![msedge_bVzLMeh8ZI](https://user-images.githubusercontent.com/25891462/134655252-b87ce699-bbea-4dde-a3e5-addaa4d69d69.png)

## Actual behaviour
![Code_0WVdVyKTMG](https://user-images.githubusercontent.com/25891462/134655308-f5fb3ffa-0cf7-45a7-b381-54d2c485042c.png)

## Logs

```
ERROR: Error in parse(text = x, srcfile = src): <text>:1:32: unexpected input
1: a <- "hello, world! This is R."
                                   ^
Error in parse(text = x, srcfile = src): <text>:1:32: unexpected input
1: a <- "hello, world! This is R."
                                   ^
Traceback:
```

**Comment by DonJayamanne** [comment] 2021-09-24 17:47
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/4576

**Closed by DonJayamanne** 2021-09-24 17:47 UTC
Labels: bug, needs-triage

**Comment by DonJayamanne** [comment] 2021-09-24 20:38
Fixed, it should be in Mondays insiders and next releease
