### ISSUE TITLE
Creating new cell with "+ Code" button does not select new cell properly in VSCode Insiders

### ISSUE THREAD

**Issue by eduardopaul** [microsoft/vscode-jupyter#5536] opened 2021-04-16 20:32 UTC
## Environment data

- VS Code version: 1.56.0-insider
- Jupyter Extension: v2021.6.755784270
- Python Extension: v2021.5.746022950-dev
- OS: MacOS, Darwin x64 18.7.0
- Python: 3.9.4
- Type of virtual environment used: conda
- Jupyter server running: Local

## Expected behaviour

Creating a new cell should always result in it being selected and ready for editing.

## Actual behaviour

When creating a new cell by clicking the "+ Code" button with current cell in *edit mode*, both original and newly created cells are somehow simultaneously selected:
- The original cell is selected in *edit mode* and anything that is typed goes there.
- The new cell is selected in *command mode* and hitting either Ctrl+Enter or Shift+Enter tries to run it.
    - With Ctrl+Enter, both cells remain selected as described.
    - With Shift+Enter, yet another cell is created and selected as expected.
- Also, hitting up/down arrow keys does not move the cursor in original cell, but moves *command mode* selection to another cell provided there is a neighboring cell to be selected.

## Steps to reproduce

- Start a new notebook in VSCode Insiders;
- Type anything;
- Go into *edit mode* in the first cell;
- Click on "+ Code" to create a new cell below.

[![vscode-insiders-jupyter-cell-issue.gif](https://s4.gifyu.com/images/vscode-insiders-jupyter-cell-issue.gif)](https://gifyu.com/image/tSPf)

**Comment by claudiaregio** [comment] 2021-04-16 21:09
Hi @eduardopaul, this appears to be a dupe of both https://github.com/microsoft/vscode/issues/121032 and https://github.com/microsoft/vscode/issues/121030. Can you confirm if this is the case or if I missed anything?

**Comment by eduardopaul** [comment] 2021-04-16 23:38
@claudiaregio Yes, it mostly is, but actually none of those mentioned my second point, namely

- *Also, hitting up/down arrow keys does not move the cursor in original cell, but moves command mode selection to another cell provided there is a neighboring cell to be selected.*

But anyway, fixing the cell selection would fix it all. I'm sorry for the dupe.

**Comment by claudiaregio** [comment] 2021-04-17 03:20
@eduardopaul No need to apologize! There are too many issues going around to keep track! 
I thought fixing the selection would fix the arrow key issue you were experiencing as a side effect but just wanted to double check :)

**Closed by claudiaregio** 2021-04-17 03:20 UTC
Labels: bug
