### ISSUE TITLE
Run by line shouldn't be allowed if kernel is busy. And vice-versa.

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#7740] opened 2021-09-29 00:06 UTC
Run a long running cell or run the entire notebook and then start run by line.
We need to ensure we handle these cases.

Since run by line will send code directly to the kernel and bypass the cell execution queue.
E.g. if you have 10 cells and run all, then for the last cell we hit `RBL`, then the last cell could start debugging immediately after the first cell has completed.

I think we need to add a method `executeHidden` into the KernelExecution class so that it uses the queue & debugging starts after all queued cells have been completed.
Should be an easy enough fix, else we end up in a very weird spot.

**Comment by roblourens** [comment] 2021-09-30 16:38
This is basically what's behind https://github.com/microsoft/vscode-jupyter/issues/7638, as far as i can tell

**Comment by greazer** [comment] 2021-09-30 21:29
Dupe of #7638

**Comment by roblourens** [comment] 2022-12-08 23:18
Seems to be properly queued now

**Closed by roblourens** 2022-12-08 23:18 UTC
Labels: bug, notebook-run-by-line, notebook-debugging
