### ISSUE TITLE
File Path Completion Inserts The Whole Relative Path After ./ or ../

### ISSUE THREAD

**Issue by ahmadfebrianto** [microsoft/vscode-jupyter#6363] opened 2021-06-23 16:35 UTC
When using file path completion/suggestion to import/read a file, it inserts the whole relative path into the path string while it should only insert the remaining path string after we prepend the path with ``./`` or ``../`` notation.

## Environment data

-   VS Code version: 1.57.1
-   Jupyter Extension version: v2021.6.999406279
-   Python Extension version: v2021.6.944021595
-   OS (Linux Mint) and version: 20 (Ulyana)
-   Python: 3.8.5 (64-bit)
-   Type of virtual environment used: (N/A)
-   Jupyter server running: Local

## Steps to reproduce:

1. Create one ``ipynb`` file and one ``csv`` file in the same directory.
2. Open the ipynb file in VS Code.
3. Try reading/importing the second file using ``open()`` or ``pd.read_csv()``.
4. Write ``./`` in the parentheses and click ``CTRL + Space`` until the suggestion list appears.
5. Scroll down to the ``csv`` file from the suggestion list. 
6. Press ``ENTER`` or ``TAB ->``

https://user-images.githubusercontent.com/52089094/123132442-f36b6d80-d478-11eb-9fc4-8e9ff2f6f62e.mp4

**Comment by rchiodo** [comment] 2021-06-23 17:18
Yes this is jupyter doing this. Sorry for the misunderstanding. The TextEdits jupyter gives us don't work in this scenario (I checked and jupyter notebook works fine here, so the codemirror edits must not match what monaco requires).

It also works fine in the interactive window so it must be the new monaco editor that's different.

**Comment by DonJayamanne** [comment] 2021-07-26 22:37
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/5956

**Closed by DonJayamanne** 2021-07-26 22:37 UTC
