### ISSUE TITLE
Plotly plots does not show when ipynb is exported to HTML

### ISSUE THREAD

**Issue by becczor** [microsoft/vscode-jupyter#11890] opened 2022-11-03 15:34 UTC
Type: <b>Bug</b>

Open a new jupyter notebook.
Create a plotly plot.
Export notebook as HTML.
Open HTML file in web browser.
Cells show but not the plots.
(It works if exported in jupyter lab)

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.4.0-131-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|31.01GB (17.73GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
jsonl|Alp|0.0.1
format-json|Cle|1.0.2
gitlens|eam|13.0.3
prettier-vscode|esb|9.9.0
unicode-substitutions|Gle|2.3.4
terraform|has|2.24.3
beautify|Hoo|1.5.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
rainbow-csv|mec|3.2.0
theme-monokai-pro-vscode|mon|1.1.21
python|ms-|2022.16.1
vscode-pylance|ms-|2022.11.10
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
color-highlight|nau|2.5.0
vscode-commons|red|0.0.6
vscode-xml|red|0.22.0
vscode-sort-json|ric|1.20.0
markdown-preview-enhanced|shd|0.6.5

</details>

**Comment by becczor** [comment] 2022-11-04 07:58
I have now updated it to the latest version, and it still does not work.

**Comment by IanMatthewHuff** [comment] 2022-11-04 21:01
Duplicate of #6999

**Closed by IanMatthewHuff** 2022-11-04 21:01 UTC
