### ISSUE TITLE
Jupyter IntelliSense contain error ICONS and duplicate content.

### ISSUE THREAD

**Issue by thefatwhale** [microsoft/vscode-jupyter#7772] opened 2021-10-01 09:02 UTC
## Environment data

-   VS Code version: 1.60.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: Windows 7 x64 SP1
-   Python and/or Anaconda version: Python 3.8.7 and 3.8.8
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local

### display IntelliSense correctly.

1. display `lib` once and with a correct icon.
2. display keyword `as` with keyword icon (not function/method icon).
3. display method once and remove the content of the front.

## Actual behaviour

3 screenshot

![shot1](https://user-images.githubusercontent.com/50515732/135592407-75430f8f-f751-448b-a3dd-74985b34b10b.png)

![image](https://user-images.githubusercontent.com/50515732/135594151-bcaf5927-9735-460a-9fbe-c53182bc255e.png)

![image](https://user-images.githubusercontent.com/50515732/135594197-d49d5116-10f2-4e31-9c68-7fad8d180f3c.png)

**Comment by claudiaregio** [comment] 2021-10-01 20:57
Thanks @thefatwhale, will take a look at our next triage meeting

**Comment by DonJayamanne** [comment] 2021-10-01 21:48
I believe this is caused by the intellisense we get from Jupyter as well.
We should look into remove these duplicates (in jupyter we can call VSC completions API to get the completions for that position & when we get response from both, remove duplicates, if we get response just from jupyter, return that item so that we don't slow down intellisense).

**Comment by rchiodo** [comment] 2021-10-04 20:49
@DonJayamanne had an idea on how to remove dupes.

- During jupyter completion call, call for other completions
- Filter out the ones that are already there

**Comment by cplager** [comment] 2021-11-09 19:31
[Defauolt value should NOT be suggested when entering list](https://github.com/microsoft/vscode-jupyter/issues/7773) was closed as a duplicate to this problem.  Just wanted to make sure that this problem is also on people's radar (as it is neither an issue with duplicates nor error icons).

**Closed** 2021-11-11 23:15 UTC
Labels: bug, regression, notebook-intellisense
