### ISSUE TITLE
Cells in a notebook are rendered incorrectly if some cells are hidden (folded)

### ISSUE THREAD

**Issue by ldk-linux** [microsoft/vscode-jupyter#12791] opened 2023-02-09 06:50 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Steps to reproduce:

1. Create a bunch of cells in a Python notebook in vscode.
2. Hide (fold) some of them by clicking on the highlighted blue left margin
3. Scroll past the hidden (folded) cells and back (may need to try a couple of times)
4. Some or all visible cells are rendered incorrectly - they are shown without any content

This only happen if some of the cells are hidden. If no cell is hidden, all visible cells are rendered correctly. It also happens across multiple Anaconda/Python versions.

Please see the attachment below for a live example.

https://user-images.githubusercontent.com/8700132/217738558-4477d5ad-effa-4088-950c-eaccf5fbc3d7.mp4

### VS Code Version

Version: 1.75.0 Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164 Date: 2023-02-01T15:24:42.903Z (1 wk ago) Electron: 19.1.9 Chromium: 102.0.5005.194 Node.js: 16.14.2 V8: 10.2.154.23-electron.0 OS: Darwin x64 22.1.0 Sandboxed: No

### Jupyter Extension Version

 v1.0.14

### Jupyter logs

```shell
info 23:33:47.279: Starting Jupyter Session startUsingPythonInterpreter, .jvsc74a57bd0b8d8e621e6862c30af44f8e56c18e14fcdd139c3d6eeac4d668e658743949c31./Users/lorenzo/opt/miniconda3/python./Users/lorenzo/opt/miniconda3/python.-m#ipykernel_launcher (Python Path: /Users/lorenzo/opt/miniconda3, EnvType: Conda, EnvName: 'base', Version: 3.8.3 (default, May 19 2020, 13:54:14) 
[Clang 10.0.0 ]) for '/Users/lorenzo/Library/CloudStorage/OneDrive-UniversityofCalgary/Teaching/ENSF338/W23/slides/Week6/trees.ipynb' (disableUI=false)
info 23:33:47.300: Process Execution: > ~/opt/miniconda3/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
> ~/opt/miniconda3/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
info 23:33:47.313: Process Execution: > ~/opt/miniconda3/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"40117e89-b579-42af-9c11-798a97405d49" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/lorenzo/Library/Jupyter/runtime/kernel-v2-68628JVme0DJbg67b.json
> ~/opt/miniconda3/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"40117e89-b579-42af-9c11-798a97405d49" --shell=9002 --transport="tcp" --iopub=9004 --f=/Users/lorenzo/Library/Jupyter/runtime/kernel-v2-68628JVme0DJbg67b.json
info 23:33:47.313: Process Execution: cwd: ~/Library/CloudStorage/OneDrive-UniversityofCalgary/Teaching/ENSF338/W23/slides/Week6
cwd: ~/Library/CloudStorage/OneDrive-UniversityofCalgary/Teaching/ENSF338/W23/slides/Week6
info 23:33:47.663: ipykernel version & path 6.19.2, ~/opt/miniconda3/lib/python3.8/site-packages/ipykernel/__init__.py for /Users/lorenzo/opt/miniconda3/bin/python
info 23:33:48.553: Started Kernel base (Python 3.8.3) (pid: 68727)
info 23:33:48.582: Process Execution: > ~/opt/miniconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
> ~/opt/miniconda3/bin/python ~/.vscode/extensions/ms-toolsai.jupyter-2023.1.2010391206/pythonFiles/printJupyterDataDir.py
warn 23:33:48.621: Got a non-existent Jupyer Data Dir file:///Users/lorenzo/.local/share/jupyter
```

### Coding Language and Runtime Version

Python 3.8.3

### Language Extension Version (if applicable)

v2023.2.0

### Anaconda Version (if applicable)

conda 23.1.0

### Running Jupyter locally or remotely?

Local

**Comment by naoziwatele** [comment] 2023-02-09 08:09
Having the same issue

**Comment by rebornix** [comment] 2023-02-09 17:34
Thanks for reporting. /duplicate of https://github.com/microsoft/vscode/issues/173590, it's fixed in latest Insiders and will be fixed in the Recovery build that will be released today.

**Closed by rebornix** 2023-02-09 17:34 UTC
Labels: bug
