### ISSUE TITLE
Wrong Block execution

### ISSUE THREAD

**Issue by MattioCh** [microsoft/vscode-jupyter#7614] opened 2021-09-22 10:15 UTC
Issue Type: <b>Bug</b>

I select one block to run, it runs the other block

Extension version: 2021.8.2041215044
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 20.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz (8 x 1700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|--crash-reporter-id ae685a7c-88bf-4706-833b-74fcfb92e59d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlang:30333561
binariesv615:30325510
vsccppwt:30364497
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32cf:30365367
pythonf5test824cf:30361778
javagetstartedc:30364665
pythonvspyt187:30365361
pydsgst2:30361792
vssid140cf:30363604
vssur157:30367808

```

</details>

**Comment by munro** [comment] 2021-09-22 15:32
Same!!!!!!

**Comment by rchiodo** [comment] 2021-09-22 15:56
Thanks for the bug. This is a dupe of https://github.com/microsoft/vscode/issues/133038

**Closed by rchiodo** 2021-09-22 15:56 UTC
Labels: needs-triage
