### ISSUE TITLE
Jupyter notebook matplotlib chart fails to save: save dialog hidden, nothing saved

### ISSUE THREAD

**Issue by paul-rogers** [microsoft/vscode-jupyter#15337] opened 2024-03-09 21:17 UTC
The Save As button for a chart output does nothing. After the first use, it appears behind (not in front of) the VS Code window.

## Environment data

About output:

    Version: 1.87.1
    Commit: 1e790d77f81672c49be070e04474901747115651
    Date: 2024-03-06T00:21:07.287Z
    Electron: 27.3.2
    ElectronBuildId: 26836302
    Chromium: 118.0.5993.159
    Node.js: 18.17.1
    V8: 11.8.172.18-electron.0
    OS: Linux x64 5.15.0-94-generic

-   Jupyter Extension version (available under the Extensions sidebar): v2024.2.0
-   Python Extension version (available under the Extensions sidebar): v2024.2.1
-   Python and/or Anaconda version: 3.10.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): None
-   Jupyter server running: Local 

## Expected behaviour

1. Clicking the floppy disk "Save As" icon next to a matpotlib chart should save the chart.
2. A pop-up dialog should appear in front of, not behind, the VS Code window.

## Actual behaviour

1. Clicking  the floppy disk "Save As" icon next to a matpotlib chart does nothing.
2. After the first attempt, subsequent uses of the button displays the Save As dialog behind the VS Code window which renders VS Code unresponsive until one discovers the "pop under" dialog.

## Steps to reproduce:

1. Create a simple chart in a Python notebook using matplot. Probably any example will do.
2. Run the code to display a chart in the output for your cell.
3. Click on the floppy disk "Save As" button.
4. On the first attempt, the dialog pops up in front of the VS Code window.
5. In the dialog, click "Save Plot Image"
6. Nothing happens. No image is saved to the directory named in the dialog.
7. Repeat the process. The second time, the Save As dialog appears behind the VS Code window.

As it turns out, the double-paper "Copy to Clipboard" operation does work. So, the workaround is either:

1. Use a screen shot program to save the image, or
2. Use the Copy to Clipboard option and use an image program to save the image as a file.

One other "gotcha": the "Chart" button, the "Expand Image" command does not appear for previously created charts when opening an existing notebook. However, if I rerun the Python code to create a new output, then the "Expand Image" icon does appear. (I checked both these cases for the Save As command, it does nothing in both the saved-output and new-output cases.)

## Logs

No related log messages appeared in any of the Jupyter, Python, Notebook Rendering or similar logs.

**Comment by amunger** [comment] 2024-03-11 15:40
I'm not able to repro - can you look in the console of `Developer: Toggle Developer Tools` and check for any errors in there.

**Comment by paul-rogers** [comment] 2024-03-11 22:30
Just reproduced the error. As before, the "Save As" dialog again popped up behind the VS Code window, forcing me to hunt it down. No image was saved.

To better isolate the issue, I disabled all extensions except those for Python and Jupyter. Closed all files except the notebook in question. Restarted VS Code. Opened developer tools as requested. Switched to the Console tab. There are a few random errors that I suspect are "generic" and not related to my particular situation (see below). It seems that there is no "copy to clipboard" function in the console, only a Save As feature. Tied that. The behavior is similar to the problem described for saving images above.

Clicked "Save As" from the context menu. The Save As dialog appeared in front of the VS Code window and I clicked Save. The file was saved. Then, I tried a second time. Clicked "Save as..." from the context menu. The second time (after restarting VS Code), the Save As dialog appeared behind the VS Code window. Thus, the window position behavior may be generic. To check, with my notebook open, I clicked File &rarr; Save As... from the main menu. The dialog again appeared behind the VS Code window. Conclusion: this is a generic problem with VS Code on Linux Mint (which is the only OS I can test.)

The only interesting entries in the Developer Tools Console log are:

```text
webviewElement.ts:511 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
mountTo @ webviewElement.ts:511
...
viewLine.ts:418 monospace assumptions have been violated, therefore disabling monospace optimizations!
monospaceAssumptionsAreValid @ viewLine.ts:418
```

No additional Console entries appear when I attempt to save the image. (The image continues to not save.)

To remove any remaining variables, I closed all open files then created a new, empty notebook. Copy/pasted the [example bar chart code](https://matplotlib.org/stable/gallery/lines_bars_and_markers/bar_colors.html#sphx-glr-gallery-lines-bars-and-markers-bar-colors-py) and ran it. The chart appeared. Attempted to save it. Again, got a pop-under Save As dialog and nothing was actually saved.

Tried repeating the above process by Clicking "Restart" in the above test notebook. The following appeared in the Developer Tools Console log:

```text
event.ts:42 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onWillAddFirstListener @ event.ts:42
q @ event.ts:1045
(anonymous) @ event.ts:118
onWillAddFirstListener @ event.ts:193
q @ event.ts:1045
U @ listWidget.ts:685
D @ listWidget.ts:1521
ce @ listWidget.ts:1501
K @ listService.ts:288
j @ instantiationService.ts:119
createInstance @ instantiationService.ts:85
r @ notificationsList.ts:74
show @ notificationsList.ts:53
Q @ notificationsToasts.ts:213
(anonymous) @ notificationsToasts.ts:160
execute @ dom.ts:325
Dt @ dom.ts:366
(anonymous) @ dom.ts:384
```

Used the "Copy to Clipboard" button (which does work), to see if this emits anything to the log. Nothing appeared.

Ran one additional test. Closed my project to get back to the "start" window. Created a new notebook. Again pasted in the Matplotlib example code and ran it to get a chart. Clicked on the Save As button. A pop-under dialog appeared. One quirk: the window's default save location is the root of the Linux directory tree. Suggestion: change this to the user's home directory. (Under Unix, the root directory is not a good place to save things, unlike old-school Windows, when C: was a typical place to save things.) Changed the target directory to my home directory and clicked "Save plot image". Again, nothing was written.

For fun, tried again. The dialog did not remember my previous save location and again wanted to save to the Linux root directory. Suggestion: remember the save location.

Somewhere while trying this, the following appeared in the Console log:

```text
console.ts:94 [Violation] 'setInterval' handler took 52ms
[Violation] 'setTimeout' handler took 54ms
console.ts:94 [Violation] 'setInterval' handler took 60ms
[Violation] 'setTimeout' handler took 54ms
```

Is there some other logging mechanism that might provide inside into the behavior of the code executed when the "Save plot image" button is clicked? Something that might indicate where in the save process things go off the rails?

**Comment by paul-rogers** [comment] 2024-03-12 19:45
@amunger `File -> Save As...` does save the notebook. Similarly, the "Save As" for the developer console does save the log file. What does not work is using the diskette button "Save as..." on the matpotlib chart image: the dialog appears but nothing is actually written to disk.

**Comment by paul-rogers** [comment] 2024-03-13 04:36
The problem persists in latest version for Ubuntu:

```text
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:14:59.643Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 5.15.0-94-generic
```

**Comment by paul-rogers** [comment] 2024-03-15 20:57
A bit more context. I started messing with 3D plots, and added the following magic command to the notebook:

```text
%matplotlib widget
```

This resulted in a wonderful interactive 3D chart. I clicked on the diskette "Download plot" icon. Although the dialog did continue to "pop behind", clicking "Save" did, in fact, save the plot.

One difference I noted was that, in the above, the file name in the "Save As" dialog is `Figure 11.png`. While, in the original use case, the file name was simply `output` (with no file type). And, voila!, if I change the name to `output.png`, the chart image does, in fact, save.

So, the fix might be as easy as giving the "Save As" dialog a file name with a file type attached. Or, default the file type to `.png` since the dialog has a file type selector that offers only PNG as an option. That way, us poor users don't have to remember that we have to tell the software the extension that it has already decided it requires. (Also, it would be nice to fix the "pop under" issue.)

I also noted that, when I save an interactive chart (to the default location, which is the project), the file immediately opens in VS Code. However, if I use the "static" version, the file is also saved to the default project location, but _does not_ open in VS Code. It would be helpful to be consistent. My vote would be to _not_ automatically open the image; that would reduce clutter.

One other (very minor) observation: the button labels are wonderfully inconsistent. "Save As", "Save as", "Save as...", "Download plot", etc. Does VS Code have a naming style guide to help folks be consistent?

**Comment by amunger** [comment] 2024-03-15 22:08
Do you have a simple example cell that creates a plot that would repro this behavior?

**Comment by paul-rogers** [comment] 2024-03-16 04:33
@amunger, the problem seems to occur with every chart, such as the [example bar chart code](https://matplotlib.org/stable/gallery/lines_bars_and_markers/bar_colors.html#sphx-glr-gallery-lines-bars-and-markers-bar-colors-py) mentioned earlier. I created a new notebook with just that code and it exhibited the same issue.

**Comment by DonJayamanne** [comment] 2024-12-13 01:25
I believe this has been fixed in the latest insiders version of the Jupyter extension.
Closing as fixed.

**Closed by DonJayamanne** 2024-12-13 01:25 UTC
Labels: bug, ipywidgets

**Comment by DonJayamanne** [comment] 2024-12-13 01:28
Most likely a duplicate of https://github.com/microsoft/vscode-jupyter/issues/16111
