### ISSUE TITLE
%%HTML magic cell video support

### ISSUE THREAD

**Issue by AlexNakamuraDF** [microsoft/vscode-jupyter#7422] opened 2021-09-06 00:38 UTC
Issue Type: <b>Feature Request</b>

## Description
After adding a cell with the `%%HTML` magic command and including a video (as described [here](https://stackoverflow.com/a/24720804/15217078)), the video doesn't reproduce inside the VS Code notebook interface. When opening the same notebook using the Jupyter interface, the video does reproduce.

This also affected the use of the [`notebook_manim` library](https://github.com/AkashKarnatak/manim_notebook) because it uses HTML to play the generated videos. 

## Steps to reproduce
1. Create a notebook with a cell that contains the following code snipet:
```
%%HTML
<video width="320" height="240" controls>
  <source src="./test_video.mp4" type="video/mp4">
</video>
```
2.  Add an `.mp4` video named `test_video.mp4` to the current working directory.
3.  When running the cell in the VS Code notebook interface, a video player will appear but no video will reproduce.
![image](https://user-images.githubusercontent.com/72317263/132146211-bde749ce-a193-4c10-bb14-a85497740a93.png)
4. Running the same notebook in the Jupyter interface will reproduce the video:
![image](https://user-images.githubusercontent.com/72317263/132146276-4cb87d06-f545-4d0f-850c-0a23987f1e31.png)

## Suspected cause
I suspect that this is caused by the `libffmpeg.so` file. 
- I tried to run the notebook with the Jupyter interface using Opera and I had the same problem. (Opera on Linux has a problem where the included `libffmpeg.so` file [doesn't work for playing certain videos](https://forums.opera.com/topic/28699/why-do-i-have-copy-libffmpeg-so))
- After changing that file in Opera it did work.
- It also worked using the Jupyter interface in Chrome.

I tried changing the `libffmpeg.so` file in VS Code but it didn't work, so I'm not entirely sure that this is the cause.

## Instalation information
Extension version: 2021.8.2031190714
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.11.0-27-generic
Restricted Mode: No

**Comment by joyceerhl** [comment] 2021-09-06 20:59
This may be a duplicate of https://github.com/microsoft/vscode/issues/111073. IIRC VS Code itself needs to add support for audio and video in the notebook interface.

**Comment by greazer** [comment] 2021-09-07 22:48
This is indeed a dupe of microsoft/vscode#111073

**Closed** 2021-09-07 22:48 UTC
Labels: bug, notebook-rendering
