### ISSUE TITLE
Jupyter creates many junk empty ipynb files

### ISSUE THREAD

**Issue by jmfontana** [microsoft/vscode-jupyter#12502] opened 2023-01-08 12:57 UTC
Version: 1.74.2
Jupyter extension v2022.11.1003412109
MacOS Monterrey on Silicon M1
Anaconda

Whenever I use a Jupyter notebook, my folder gets full with lots of copies of the .ipynb file: 

file_name_-2d3962b2-8d56-4e4e-9f46-1faff6d46747a9a34c13-38ce-404b-98a6-2cca61d0efb7.ipynb
file_name_-9dd5fbb0-91f6-4712-8137-084b9fee3f29e11fefa3-fef1-4539-9db7-b9e081ec6135.ipynb
file_name_-3312e1ad-9806-4b64-a79e-54b8c6b42d7b321c97ba-8007-459a-bf1c-72579b6b959f.ipynb
file_name_-5812df30-0798-42a8-b379-f2915a6df6caaa1f8f5c-c625-4006-97df-4c48f424d7df.ipynb
file_name_-c90cefa3-b3cd-4c96-879f-9406193f71a0d432c967-237f-4bd1-96dc-4b49d8c32de6.ipynb
file_name_-cd41d871-56a7-4201-b775-1214b13b3400f29ec548-91f0-4e73-b8f7-4a42e26c7fe2.ipynb

This becomes very annoying because it is hard to find the right files in the middle of so much garbage. When I close the note, these junk files don't go away. 

JM

**Comment by jmfontana** [comment] 2023-01-10 11:39
Some more information that might be relevant. I have two Macs. One with an M1 chip, the other with Intel. I just noticed the problem only occurs with VC Version: 1.74.2  Darwin arm64 21.6.0. I don't see those kinds of files being created with Version: 1.74.2 (Universal) OS: Darwin x64 21.6.0.

**Comment by DonJayamanne** [comment] 2023-01-10 16:53
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/6510

**Closed by DonJayamanne** 2023-01-10 16:53 UTC
Labels: bug
