### ISSUE TITLE
Command/button to auto-fit column sizes in the data viewer

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-jupyter#6585] opened 2021-07-08 12:17 UTC
It would be handy to have a command or button to automatically fit all column sizes to their contents, to allow comfortably previewing dataframes' contents without having to manually resize all columns.

**Comment by DonJayamanne** [comment] 2021-07-09 18:34
Thanks for the suggestion, we'll be looking into this when we review our UI for the data viewer.

**Comment by IanMatthewHuff** [comment] 2022-11-04 20:26
Dupe of #7885

**Closed by IanMatthewHuff** 2022-11-04 20:26 UTC
Labels: data-viewer, feature-request
