### ISSUE TITLE
Not able to run any cell on vscode due to Permission issues on Windows

### ISSUE THREAD

**Issue by hiramshirata** [microsoft/vscode-jupyter#12543] opened 2023-01-13 15:05 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Not able to run jupyter notebook on vscode. No problems with jupyter notebook in the web browser. 

Tried to debug the kernel_interrupt_daemon.py with a print of the PID that raised the error and it returned a Code.exe proccess.

modified this line:
CheckError(hp, "failed to open process" + str(desiredAccess) + str(inherit) + str(pid))
and got this:
PermissionError: [WinError 5] failed to open process2035711False8000

Ps.: couldn't paste the whole jupyter log output :/
### VS Code Version

Version: 1.74.3 (user setup) 
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534 
Date: 2023-01-09T16:59:02.252Z 
Electron: 19.1.8 
Chromium: 102.0.5005.167 
Node.js: 16.14.2 V8: 10.2.154.15-electron.0 
OS: Windows_NT x64 10.0.22000 
Sandboxed: Yes

### Jupyter Extension Version

v2022.11.1003412109

### Jupyter logs

```shell
File "c:\Users\shirahir\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py", line 337, in handle_command
    handle = interrupter.initialize_interrupt()
  File "c:\Users\shirahir\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py", line 301, in initialize_interrupt
    parent_proc_handle = OpenProcess(PROCESS_ALL_ACCESS, False, self.ppid)
  File "c:\Users\shirahir\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py", line 165, in OpenProcess
    CheckError(hp, "failed to open process" + str(desiredAccess) + str(inherit) + str(pid))
  File "c:\Users\shirahir\.vscode\extensions\ms-toolsai.jupyter-2022.11.1003412109\pythonFiles\vscode_datascience_helpers\kernel_interrupt_daemon.py", line 132, in CheckError
    raise ctypes.WinError(ctypes.get_last_error(), msg)
PermissionError: [WinError 5] failed to open process2035711False8000
 ('END')
info 11:54:58.865: Got env vars with python c:\Users\shirahir\Desktop\electrolux\env\Scripts\python.exe, with env var count 61 and custom env var count 55 in 1549ms
debug 11:54:58.865: Getting activated env variables from Python, Class name = K, completed in 1549ms, has a truthy return value, Arg 1: "/c:/Users/shirahir/Desktop/electrolux/stock_management_arg/D2C_arg_models.ipynb", Arg 2: <Uri:/c:/Users/shirahir/Desktop/electrolux/env/Scripts/python.exe>
debug 11:54:58.866: Got env vars with python c:\Users\shirahir\Desktop\electrolux\env\Scripts\python.exe in 1550ms with 78 variables
info 11:54:58.965: Got env vars with python c:\Users\shirahir\Desktop\electrolux\env\Scripts\python.exe, with env var count 61 and custom env var count 55 in 1648ms
debug 11:54:58.965: Getting activated env variables from Python, Class name = K, completed in 1648ms, has a truthy return value, Arg 1: "/c:/Users/shirahir/Desktop/electrolux/stock_management_arg/D2C_arg_models.ipynb", Arg 2: <Uri:/c:/Users/shirahir/Desktop/electrolux/env/Scripts/python.exe>
debug 11:54:58.965: Got env vars with python c:\Users\shirahir\Desktop\electrolux\env\Scripts\python.exe in 1648ms with 78 variables
info 11:54:59.004: ipykernel version & path 6.19.4, ~\Desktop\electrolux\env\lib\site-packages\ipykernel\__init__.py for c:\Users\shirahir\Desktop\electrolux\env\Scripts\python.exe
debug 11:58:04.395: creating new code watcher with matching document file:///c%3A/Users/shirahir/.vscode/extensions/ms-toolsai.jupyter-2022.11.1003412109/pythonFiles/vscode_datascience_helpers/kernel_interrupt_daemon.py
```

### Coding Language and Runtime Version

python 3.10.9

### Language Extension Version (if applicable)

v2022.20.2

### Running Jupyter locally or remotely?

None

**Comment by amunger** [comment] 2023-01-13 20:52
You can also attach a file to provide the full output logs, we'll likely need that to help troubleshoot.

**Comment by hiramshirata** [comment] 2023-01-13 21:01
Sure, steps in this log were just opening vscode and trying to run a cell. In vscode the popup window keeps trying to connect:
Connecting to kernel: env (Python 3.10.9): Activating Python Environment 'c:\Users\shirahir\AppData\Local\Programs\Python\Python310\python.exe'

[jupyter_extension_output.txt](https://github.com/microsoft/vscode-jupyter/files/10415392/jupyter_extension_output.txt)

**Comment by DonJayamanne** [comment] 2023-01-16 03:24
> PermissionError: [WinError 5] failed to open process

Looks like you have some permission error on your windows machine.
Please could you check whether you have some anti-virus sofware or the like that is preventing some of the code form running successfully.

In the mea time, please could you update to the latest pre-relase version of the Jupyter extension.
You will need to install the latest Insider Version of VS Code as well, and let me know if that works for you.

**Comment by hiramshirata** [comment] 2023-01-16 12:42
Tried as you suggested, but still got the same error in the kernel_interrupt_daemon.py: `PermissionError: [WinError 5] failed to open process`

vscode:
Version: 1.75.0-insider (user setup)
Commit: 8be8d96ab86ed4077df554eb62727484d454699f
Date: 2023-01-16T05:21:04.032Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

jupyter:
v2023.1.2000141019

**Comment by DonJayamanne** [comment] 2023-01-17 00:00
Not sure what is going on , can you try running VS Code as an admin, its pretty obvious that there are some permission issues on your machine that is blocking some code.
Unfortunately this is an environment issue (something on your machine) and not a problem with the extension, hence I'm not really able to help you here.

My suggestion, you try running as an admin and trying this again.

**Comment by hiramshirata** [comment] 2023-01-17 12:29
Right, I'll make some tests and tell here when it works. Thanks anyway @DonJayamanne!

**Comment by DonJayamanne** [comment] 2023-01-17 20:35
Thanks for getting back, closing this issue as this is unrelated to the extension and caused by permissions setup on the machine.
Please do let us know how things go 
If the problem lies with the Jupyter extension pelase do feel free to ping here and I'll re-open this or you could do that, or else please feel free to create a new issue

**Closed by DonJayamanne** 2023-01-17 20:35 UTC
Labels: bug, info-needed, notebook-kernel
