### ISSUE TITLE
Interactive window not showing output on long execution, even if "Always Scroll On New Cell" is checked

### ISSUE THREAD

**Issue by smojef** [microsoft/vscode-jupyter#8426] opened 2021-12-02 16:12 UTC
## Environment data

-   VS Code version: 1.62.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.12
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): mini conda 64-bit
-   Jupyter server running: Local

## Expected behaviour

While in a .py file and pressing CTRL+ENTER or SHIFT+ENTER to execute the current cell, I expect the interactive window to display the output like a terminal window, always showing the last output lines, without manual intervention, even for long executions.

## Actual behaviour

It does not wollow the scrolling like a terminal window.  The most recent output lines are missing and we must manually scroll to read recent output.  

Moreover, we can only read the last 5 lines when output is long.  
Ex.: In one script, I have a cell that process many files (filling the interactive output) and then prompts a menu for the next action, but I can only read the last 5 lines of the menu. 

## Steps to reproduce:

1. Check "Always Scroll On New Cell" and "Send Selection To Interactive Window" option in Jupyter settings
2. Add the following code:
```
#%%
import time
for n in range(100):
    print(n)
    #time.sleep(1)
```
3. Press CTRL+ENTER a few time to fill the interactive window
4. Uncomment #time.sleep(1) -> time.sleep(1)
5. Press CTRL+ENTER to simulate a long execution
6. The interactive window does not show the output.  Screenshot:
![image](https://user-images.githubusercontent.com/43252951/144456919-2a03e867-6899-4688-9c57-36eb9449fede.png)
7. If I manually scroll, then I see this:
![image](https://user-images.githubusercontent.com/43252951/144457065-70e06dcc-7f90-4a5e-b2b6-4f7f55e19401.png)

Is there a way to avoid seeing only 5 lines below "show more (open the raw output data in a text editor) ..." (or disable the "show more" feature altogether)?

**Comment by IanMatthewHuff** [comment] 2021-12-02 19:53
@smojef Could you take a peek at your scenario in vscode insiders? We made some changes around scrolling and added a new text line limit setting to help with this.
![image](https://user-images.githubusercontent.com/812783/144492916-11b8c6db-a99a-40ca-8874-ee1216aa67be.png)

However with regards to the scrolling to the bottom I am seeing issues with that with the sleep in the loop. We can look into that.

**Comment by rchiodo** [comment] 2021-12-06 21:30
@rebornix does the jupyter extension handle the auto scroll or does the core? I don't recall.

**Comment by cguerner** [comment] 2022-03-23 10:57
Hi, I'm having this same issue. I'm working with a .py file and submitting individual lines of code to the interactive window via Shift+Enter, and the output is not displayed. I have to manually scroll down in the interactive window to see it every time I submit a new line.

Note that when I enter a code directly into the interactive window entry line at the bottom, it scrolls down partially but not completely (still have to manual scroll a bit).

I think this is new and very frustrating. Thank you for your help in resolving this!

**Comment by rchiodo** [comment] 2022-03-24 21:37
The root cause of this is we have no way to tell when the 'output' is done. We scroll after the execution is singled as complete but outputs actually show up async after that.

We likely need to implement this scrolling in the core of VS code.

**Comment by amunger** [comment] 2022-06-07 16:17
should be fixed in the upcoming release with https://github.com/microsoft/vscode/pull/150300

**Closed by amunger** 2022-06-07 16:17 UTC
Labels: bug, interactive-window, iteration-candidate
