### ISSUE TITLE
Active console while working with notebooks

### ISSUE THREAD

**Issue by alandema** [microsoft/vscode-jupyter#7894] opened 2021-10-11 18:34 UTC
When using Jupyter Notebook web version, very often I like to do some prototype lines before inserting it in the notebook. Instead of creating a cell to exclude it right away, I much prefer to start a qtconsole linked to my jupyter server and do the prototypes in the console.

Sure I could do the same with Jupyter in VSCode, but it would be great if we have a native console for jupyter in VS.

This is my feature request, an integrated console with jupyter to do code prototypes or even some prints without having to create any cell.

**Comment by greazer** [comment] 2021-10-11 20:43
Dupe of #6484

**Closed as completed by greazer** 2021-10-11 20:43 UTC
Labels: notebook-workflow
