### ISSUE TITLE
Feature Request: Save variable state between editing sessions

### ISSUE THREAD

**Issue by dhuntley1023** [microsoft/vscode-jupyter#4643] opened 2021-02-04 00:40 UTC
I would love to have the option for VSCode to save/restore variable state between editing sessions so that I don't have to re-run the notebook to continue my work.

To prevent issues with very large arrays, etc., but there could be configurable limits on max sizes, etc.

**Comment by DonJayamanne** [comment] 2021-02-04 19:33
Thanks for filing this issue, I'm trying to understand the workflow that leads to this issue.
Is it as follows:
* You open a notebook, run something, then you have variables.
* Close close the notebook or close VS Code & open it again & now the variables are lost?

Would appreciate feedback from anyone upvoting as well. Thanks

**Comment by DonJayamanne** [comment] 2022-08-15 00:50
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/300

**Closed by DonJayamanne** 2022-08-15 00:50 UTC
Labels: bug, notebook-kernel
