### ISSUE TITLE
[Issue] Interrupt Kernel Prompt - Multiple Cancel Buttons

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode-jupyter#10858] opened 2022-07-18 22:15 UTC
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

The interrupt kernel prompt has two cancel buttons

![image](https://user-images.githubusercontent.com/25514145/179626363-2cfb8f03-fde5-4559-83f5-b493d819fcc9.png)

It is not clear which cancel does what functionality.

## Steps to reproduce:

1. Interrupt a long running _or_ non-responsive kernel

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.9.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.10.1
VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (1.27GB free)|
|Process Argv|. --crash-reporter-id ce569807-f01d-4ba7-897d-02e5da510beb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by rchiodo** [comment] 2022-07-19 17:05
Thanks for the bug. 

Root cause is here:
https://github.com/microsoft/vscode-jupyter/blob/2aeb886917266b926d6e0f53ca5f8beb97ed8e39/src/kernels/kernel.base.ts#L228

When we added the modal flag, we didn't need the 'cancel' option anymore.

**Comment by DonJayamanne** [comment] 2022-08-04 03:55
Marked as fixed for validation

**Closed by DonJayamanne** 2022-08-04 03:55 UTC
Labels: bug, papercut :drop_of_blood:, iteration-candidate, kernel-management, notebook-mild-regression
