### ISSUE TITLE
the cell is computed infinitely

### ISSUE THREAD

**Issue by metya** [microsoft/vscode-jupyter#4813] opened 2021-02-14 14:43 UTC
I have VS Code Insiders 1.54.0
![image](https://user-images.githubusercontent.com/968934/107879776-f7481b80-6eeb-11eb-96f2-abdcd9abd7ea.png)

Windows 10 Dev Build 21313
![image](https://user-images.githubusercontent.com/968934/107879799-121a9000-6eec-11eb-9bcb-7d7d36626d2c.png)

When I start the jupyter notebook, It starts correctly, but after that, any of the cells compute even the simplest operation indefinitely.
![image](https://user-images.githubusercontent.com/968934/107879880-89e8ba80-6eec-11eb-88f3-c8b11d87803d.png)

But imports end correctly.

Server logs are here. Just switchs to busy forever.
![image](https://user-images.githubusercontent.com/968934/107879899-9ff67b00-6eec-11eb-9d9b-fda82482d808.png)

**Comment by joyceerhl** [comment] 2021-02-14 20:08
Hey @metya, very sorry about the trouble. I believe this is happening because there was a breaking change in the VS Code API in VS Code Insiders late last week, and the Jupyter extension team is still working on publishing a compatible update to the marketplace for insiders users. We should have an update early next week but in the meantime you may be able to work around this by downgrading VS Code Insiders. Again, very sorry about the trouble caused and we appreciate your patience.

**Comment by joyceerhl** [comment] 2021-02-14 20:35
Closing as a duplicate of https://github.com/microsoft/vscode-jupyter/issues/4807

**Closed by joyceerhl** 2021-02-14 20:35 UTC
