### ISSUE TITLE
Unable to select interpreter path while choosing Jupyter kernel from python environment option

### ISSUE THREAD

**Issue by vishalkrish-12** [microsoft/vscode-jupyter#16245] opened 2024-11-23 11:10 UTC
## Environment data

-   VS Code version: 1.95.3
-   Jupyter Extension version (available under the Extensions sidebar): 2024.10.0
-   Python Extension version (available under the Extensions sidebar): 2024.20.0
-   OS (Windows | Mac | Linux distro) and version: Windows 11 Home (OS Build: 26100.2314)
-   Python and/or Anaconda version: 3.10.15
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Jupyter server running: Local | Remote | N/A: Local

## Expected behaviour

While selecting the kernel in jupyter notebook with the option to choose from "Python Environments" need to select the existing interpreter by using the "Enter Interpreter Path" option I can select the env path. So that the specific env will be selected as jupyter kernel.
.
## Actual behaviour

While selecting the kernel in jupyter notebook with the option to choose from "Python Environments" need to select the existing interpreter but the list not have the option "Enter Interpreter Path".

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX![Image](https://github.com/user-attachments/assets/703fa29e-943b-483d-b625-4b5ccfe403cf)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment] 2024-11-24 22:48
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/15087

**Closed by DonJayamanne** 2024-11-24 22:48 UTC
Labels: bug
