### ISSUE TITLE
pylance generates inconsistent errors in jupyter notebook files

### ISSUE THREAD

**Issue by mukor** [microsoft/vscode-jupyter#8283] opened 2021-11-17 07:52 UTC
## Environment data

-   VS Code version: 1.62.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.10.1101450599
-   Python Extension version (available under the Extensions sidebar): v2021.11.1422169775
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: 3.8.10
-   Type of virtual environment used ( venv ): XXX
-   Jupyter server running: Local
-   Pylance Extension Version: v2021.11.1
-   WSL Kernel Version: 5.10.60.1

## Expected behaviour

The errors and warnings raised by pylance  in the PROBLEMS should be consistent no mater if the code is in a jupyter notebook (.ipynb) or a python file (.py)

## Actual behaviour

Identical code in a Jupyter notebook and .py files display different errors from pylance in the PROBLEMS tab

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1.  Enter "good" code in a cell jupyter notebook cell *running from WSL* (example below from notebook (verify.ipynb))

```
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

all_sf = create_engine('sqlite:///all_sf.db')
conn = all_sf.connect()

df1 = pd.read_sql_table('employee', conn, coerce_float=True, index_col='employee_id' )
df2 = pd.read_sql_table('employees_updated', conn, coerce_float=True, index_col='employee_id' )

cols = df2.columns

for i, row in df2.iterrows():
    # print(df2.loc[i])

    for i2 in cols:

        try:
            if df2.at[i,i2] != df1.at[i,i2]:
                print(df2.at[i,'name'] + ' : ' + i2 + " = " +  str(df1.at[i,i2]) + " > " + str(df2.at[i,i2]) )
                df1.at[i,i2] = df2.at[i,i2]
        except KeyError:
            # print("error")
            pass
```
2.  Note the pylance errors in PROBLEMS tab
![image](https://user-images.githubusercontent.com/2307995/142156223-86cd3fdc-8e5a-4192-82c1-ed5aaeb05a89.png)
3.  Take that same code and cut an paste it into a .py file.   
4. Note that PROBLEMS tab shows no errors from the identical code in the .py.   Pylance doesn't treat the identical code the same.

Seems like a pretty big inconsistency.

**Comment by mukor** [comment] 2021-11-17 07:57
here's a screen shot of the cell in VS Code 

![image](https://user-images.githubusercontent.com/2307995/142158989-d7788f46-eb4a-4b58-bc7a-a1f48dc16dee.png)

**Comment by rchiodo** [comment] 2021-11-17 16:51
Thanks for the bug. I don't get the same results but maybe my repro steps are different. 

![image](https://user-images.githubusercontent.com/19672699/142244171-f0638193-42f7-4346-a18a-a1c3136c7c37.png)

sqlalchemy is an expected error and the placement is correct.

Can you provide some more information/try a few things?

You said you're on WSL, can you double check the extension version loading in WSL? Your problem looks like an issue we had with intellisense with older versions of the extension.

Second, you should see an output tab item that matches the 'kernel' you have selected in the upper right.

Example - I have this kernel selected:

![image](https://user-images.githubusercontent.com/19672699/142244452-00677bb1-01a5-48e6-b72f-70b901ac49aa.png)

That gives me an output tab like so:

![image](https://user-images.githubusercontent.com/19672699/142244528-e20c2ed5-d69d-4b32-8a0e-3f8fb68dc887.png)

(same name as kernel but with language-server on the end).

If you have this output tab, can you set these two settings:

```json
    "notebook-intellisense.logLevel": "Trace",
    "notebook-intellisense.trace.server.verbosity": "Verbose",
```

And then repro the problem again. That output tab should then show diagnostic messages from the pylance server that's providing those errors. If you can copy and paste that output it should let us know what went wrong.

Thanks.

**Comment by eervin123** [comment] 2022-02-08 14:18
I have this issue from time to time. Unfortunately it is not happening right now so I can't reproduce. However, often in order to fix it, I will remove comments in code cells and place them in to markdown cells. That and a bit of fanagling with removing small end of line spaces or extra line breaks, higher up in the notebook often does the trick. (I know that isn't the way it should be but, that is how I was able to fix it in the past.) It was often a single item that was causing frustration for pylance early on in the notebook and then it got buggy throughout the rest of the notebook.

Sorry I don't have more detail at this time, I just thought this might help to shed some light on this bug.

**Comment by rchiodo** [comment] 2022-03-30 17:59
Closing for lack of a repro. Thanks for the help.

**Closed by rchiodo** 2022-03-30 17:59 UTC
Labels: bug, info-needed
