### ISSUE TITLE
Code getting shuffled -- causing errors 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#1701] opened 2020-10-02 05:00 UTC
# Bug: Notebook Editor, Interactive Window, Editor cells

## Issue

Not sure how to get this to reproduce but got the same complaint from another customer two days ago. 
Was using the notebook and running and editing code and all of a sudden I got an error for code that is not in my cell. 
The cell appears to have somehow laced code together that led to an error. 

The only solution is to copy and paste the code into a new cell and delete the old. 

## Actual behavior

![image](https://user-images.githubusercontent.com/19276747/94889196-2e7fc980-0430-11eb-965b-f47a6171b1f2.png)

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

- Jupyter server running: Local
- Extension version: v2020.10.111333
- VS Code version: 1.49.2
- Setting python.languageServer: Pylance
- Python and/or Anaconda version: 3.7.6
- OS: Windows: x64 10.0.19042
- Virtual environment: conda

## Python Output

Info 2020-10-01 21:53:08: Executing cell NotebookImport#0
Info 2020-10-01 21:53:08: Submitting code for 3d9bab26-629b-4fb7-bf33-f50ce597a9e7
Info 2020-10-01 21:53:08: Kernel switching to busy
Info 2020-10-01 21:53:08: Kernel switching to idle
Info 2020-10-01 21:53:08: Kernel switching to busy
Info 2020-10-01 21:53:09: Kernel switching to idle
Info 2020-10-01 21:53:09: Finished execution for NotebookImport#0
Info 2020-10-01 21:53:09: Finished executing cell NotebookImport#0
Info 2020-10-01 21:53:12: Executing cell NotebookImport#1
Info 2020-10-01 21:53:12: Submitting code for 3d9bab26-629b-4fb7-bf33-f50ce597a9e7
Info 2020-10-01 21:53:12: Kernel switching to busy
Info 2020-10-01 21:53:13: Kernel switching to idle
Info 2020-10-01 21:53:13: Finished execution for NotebookImport#1
Info 2020-10-01 21:53:13: Finished executing cell NotebookImport#1
Info 2020-10-01 21:53:14: Executing cell NotebookImport#2
Info 2020-10-01 21:53:14: Submitting code for 3d9bab26-629b-4fb7-bf33-f50ce597a9e7
Info 2020-10-01 21:53:14: Kernel switching to busy
Info 2020-10-01 21:53:14: Finished execution for NotebookImport#2
Info 2020-10-01 21:53:14: Finished executing cell NotebookImport#2
Info 2020-10-01 21:53:14: Kernel switching to idle

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by Bewinxed** [comment] 2020-12-03 07:24
I encountered this today, i had a line like

Sys.Stdout = open(xx,xx) and every time i try to edit and save, this line would be shuffled in between the import statements above it.

However, i wouldn’t be able to see this shuffled data until i reloaded the notebook.

I started with a clean install and this hasn’t occurred yet.

Latest insider build here.

**Comment by rchiodo** [comment] 2020-12-03 17:35
The workaround for this as identified by @giammi56 is to copy the contents of the cell to the clipboard, delete the cell, create a new cell in the same spot and paste the old cell. 

The root cause is the edit operations from the UI are not propagating to our backend. Recreating the cell causes the backend to reread the entire contents.

**Comment by greazer** [comment] 2020-12-03 21:40
Since we can't repro this very well, we should at least find a way for users to work around the problem. Ultimately, VS Code's native notebooks should address this, but it's ugly. The proposal is to copy the contents of the cell to run when user executes the cell. In addition we could update all cell contents on save.

**Comment by rchiodo** [comment] 2020-12-03 21:59
The way I think this could work is:
- On execute post a message to the UI to return the contents of the cell
- Wait for response. Update model with new contents, then execute.
- On save, post a message to the UI to return all cells
- Wait for response, Update model with new contents, save the model

**Comment by Bewinxed** [comment] 2020-12-04 09:34
Just want to note that this only happens on the Preview Notebook for me,
the classic one is fine.

I appreciate all of your hard work it's quite something to work with
jupyter books within vscode, we can work around this :)

**Comment by rchiodo** [comment] 2020-12-04 17:23
> Just want to note that this only happens on the Preview Notebook for me,
the classic one is fine.

@Bewinxed this is very unexpected. That might be a separate bug. Does it have the same symptoms? UI shows different code than what is executed?

**Comment by Bewinxed** [comment] 2020-12-04 17:58
Basically, if you open the notebook and run it, it's normal.

But if you edit it, and try to run the code, SOMETIMES it shows a syntax
error, and in the console shows your code from the interpreter perspective,
and it's not the code that is in the IDE.

If you do further edits, the lines you edit + the line before/after gets
shuffled (as in, letters, line breaks, spaces get shuffled around with your
edits), but again, from the Interpreter side.

Your code is fine in the IDE as long as the file is open, If you close and
reopen the file, you will see what the interpreter is seeing, which is your
code that was shuffled.

so this
import socket
import datetime

# Initiate Log
sys.stdout = open(ScriptName + datetime.datetime.today().strftime('%Y%m%d'
), "w")

if I change the word "Scriptname" into "ScriptDate" it gets turned into
this

import ocket
imp
ort datetime# Initiate Log
sys.stdout = open(ScriptNameScriptDate
# + datetime.datetime.today().strftime('%Y%m%d'), "w")


It hasn't happened today though...

Version: 1.52.0-insider (user setup)
Commit: 92192baf760315ac47fb2caaf3ce6d0778962352
Date: 2020-12-03T05:43:59.635Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by rchiodo** [comment] 2020-12-04 18:05
Thanks. This means there's a sync problem with the native editor too. We thought it wouldn't show these errors.

**Comment by Inspired1601** [comment] 2020-12-11 12:03
http://joxi.ru/Q2K9qQLsvGlP0r
Fix it please.
It's very annoying.
I have to re-run my notebooks for 10 times a day just because of this issue.
And after the last update nothing changes, this issue still occurs VERY often.

**Comment by rchiodo** [comment] 2020-12-11 16:59
This should be fixed in our latest release (came out 12/9/2020)

**Comment by rchiodo** [comment] 2020-12-11 17:06
@Inspired1601 are you still seeing this after upgrading to this version?

![image](https://user-images.githubusercontent.com/19672699/101932649-f0212c00-3b8f-11eb-98fd-3028b10ef7ca.png)

If so, can you answer some questions?

1. Are you using remote ssh?
1. Does it happen on just one notebook or all notebooks?
1. When it happens, if you re-execute the cell, does it fix itself?

**Comment by Inspired1601** [comment] 2020-12-11 22:15
> are you still seeing this after upgrading to this version?

Yep: http://joxi.ru/YmEBpM9iMaQQJ2

> Are you using remote ssh?

No, only local notebooks.


> Does it happen on just one notebook or all notebooks?

All of them, looks like the issue often occurs after I delete some lines or copy/paste some code.  
But tbh it still looks like "random issue", and I can't reproduce it.
It just occurs several times a day, no matter what I do.

> When it happens, if you re-execute the cell, does it fix itself?

No. The only method to solve the problem that I found is to delete "bugged" cell and create a new one.  
Even if I restart the Jupyter kernel and clear the cell, this "phantom code" still appears no matter what I type in cleared cell.
Therefore only deleting the cell helps to solve the issue. 
And if I copy all the code from bugged cell and paste it into a new one - everything works fine, so this is a particular cell issue, not a code issue.

**Comment by rchiodo** [comment] 2020-12-11 22:49
Sounds to me like the place we thought where the bug was is not actually where it is (we made some speculative fixes because we're unable to repro).  Thanks, that helps.

**Comment by Bewinxed** [comment] 2020-12-11 23:36
If there was some way we could capture data when this issue happens, like,
when the cell is out-of-sync, we could provide you with some extra
information about what's shown on screen and what's saved in the file
(other than screenshots) don't know if that is feasible.

**Comment by rchiodo** [comment] 2020-12-11 23:46
> If there was some way we could capture data when this issue happens, like,
when the cell is out-of-sync, we could provide you with some extra
information about what's shown on screen and what's saved in the file
(other than screenshots) don't know if that is feasible.

Thanks for the offer, but I'm afraid I'd need to be debugging the issue happening and be able to repro it over and over to be sure. Adding a bunch of logging might be doable if we special cased it with a flag or something, but I wouldn't want to have this logging on for the general public.

My suspicion was that our internal data model was getting out of sync with the UI because we send 'updates' to the data model and not the entire thing each time (entire thing is much too slow). The fix we tried forced all of the code to be sent from the UI during execute and save and that doesn't seem to have fixed the issue. So now I think the issue is in the UI itself.

**Comment by rchiodo** [comment] 2020-12-12 00:43
I have a private binary if somebody would like to give it a try (although not sure if externals can see these or not).
https://github.com/microsoft/vscode-jupyter/suites/1653630785/artifacts/30722321

It's also been submitted, so in about 30 minutes the same bits will be here:
https://pvsc.blob.core.windows.net/extension-builds-jupyter/ms-toolsai-jupyter-insiders.vsix

**Comment by DonJayamanne** [comment] 2021-02-23 21:44
Marking as validated, as this was fixed 2 months ago.

**Closed by DonJayamanne** 2021-02-23 21:44 UTC
Labels: bug
