### ISSUE TITLE
paste images in markdown cell

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [microsoft/vscode-jupyter#4261] opened 2020-12-21 16:17 UTC
Issue Type: <b>Feature Request</b>

Hope I can paste an image to the cell directly.

Extension version: 2020.12.424452561
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.4.0-58-generic

**Comment by joyceerhl** [comment] 2020-12-21 19:47
Thanks for the feature request @Xinyu-Wu-0000. Just to clarify, are you asking for the ability to paste images in a
1) Jupyter notebook
2) Python interactive file with cell markers
3) Interactive window?

**Comment by Xinyu-Wu-0000** [comment] 2020-12-22 01:41
1. Jupyter notebook. Thanks.

**Comment by roma-glushko** [comment] 2020-12-22 19:33
@joyceerhl @Xinyu-Wu-0000 I believe that not all tags are being rendered in markdown cells. Img tags are quite useful in notebooks but they seem to be missing in the cell preview mode:

![2020-12-22_21-31-37 (1)](https://user-images.githubusercontent.com/9402690/102926164-397d4f80-449d-11eb-8a86-2fe98e17a9de.gif)

**Comment by DonJayamanne** [comment] 2021-05-10 18:25
Duplicate of #5321

**Closed by DonJayamanne** 2021-05-10 18:25 UTC
Labels: enhancement, upstream-vscode
