### ISSUE TITLE
The code cell keeps disappearing after sometime

### ISSUE THREAD

**Issue by Kennethfargose** [microsoft/vscode-jupyter#12745] opened 2023-02-06 13:20 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [x] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The code in notebook cell disappears after a couple of minutes.  The first is just a import pandas cell and yet I can't see it.

![ss vs](https://user-images.githubusercontent.com/47985070/216981287-5f9994b4-40b8-4f44-9b03-b0056244dfa5.jpg)

### VS Code Version

1.75.0

### Jupyter Extension Version

v2023.2.0

### Coding Language and Runtime Version

Python 3.8.16

### Language Extension Version (if applicable)

1.7.0

### Anaconda Version (if applicable)

Anaconda3

### Running Jupyter locally or remotely?

Local

**Comment by icarofm** [comment] 2023-02-06 18:56
I'm having the same problem
![Captura de tela de 2023-02-06 15-50-10](https://user-images.githubusercontent.com/6115084/217059491-48791374-3679-4dbb-b0c5-181b259dee3d.png)

VS Code Version
1.75.0

Jupyter Extension Version
v2023.1.2000312134

Jupyter logs
No response

Coding Language and Runtime Version
Python 3.8.13

Language Extension Version (if applicable)
No response

Anaconda Version (if applicable)
Miniconda3

Running Jupyter locally or remotely?
Local

**Comment by rebornix** [comment] 2023-02-06 20:18
/duplicate of https://github.com/microsoft/vscode/issues/173590, let's track it there.

**Closed by rebornix** 2023-02-06 20:18 UTC
Labels: bug
