### ISSUE TITLE
Jupyter Survey Notification popping up again and again

### ISSUE THREAD

**Issue by mra-financial-com** [microsoft/vscode-jupyter#4077] opened 2020-12-02 09:55 UTC
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version: v2020.11.392013122
-   Python Extension version: v2020.11.371526539
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.9.0
-   Type of virtual environment used: N/A
-   Jupyter server running: Local

## Expected behaviour

After selecting no or yes from the survey popup on bottom right, it should not show again

## Actual behaviour

It keeps popping up again and again. Sometimes even after running a cell.

## Steps to reproduce:

1. Open a Notebook.
2. Click on no on survey popup.

![image](https://user-images.githubusercontent.com/67054627/100857181-ae57fd80-348c-11eb-88f8-b644768baaa6.png)

**Comment by rchiodo** [comment] 2020-12-02 17:54
Thanks for the bug. Unfortunately we can't repro the issue. Can you do the following?

1. Change `"jupyter.logging.level":"debug"` in your settings
1. Reload VS code
1. Reproduce the issue
1. Copy the contents of the 'Jupyter' output tab to this bug (or in a file and upload the file to the bug)

Thanks.

**Comment by jla2w** [comment] 2020-12-03 18:31
I also get exact same behavior.  I even did the survey, and now when I click yes it tells me I already filled out the survey.  and it happens constantly

**Comment by DonJayamanne** [comment] 2020-12-03 19:22
@mra-financial-com @jla2w 
We believe we have identified the cause of the issue and will be submitting a fix asap.

**Comment by rchiodo** [comment] 2021-01-13 19:00
I can't repro but I couldn't before. Nobody has reported this since though so closing.

**Closed by rchiodo** 2021-01-13 19:00 UTC
Labels: bug
