### ISSUE TITLE
Enable code lens/interactive window for non-.py file, without changing language?

### ISSUE THREAD

**Issue by ihnorton** [microsoft/vscode-jupyter#14537] opened 2023-10-20 03:06 UTC
I would like to enable the vscode-jupyter code lens features (runcell, runabove, etc.) for a file with a non-python extension, in order to use the interactive window UI instead of the notebook UI with a non-python kernel.

I can sort of do this manually, by selecting a different language in the `Select Language Mode` popup -- but I do _not_ want to change the editor language, because that will also change the help and completion provider (to python).

I believe the activation filtering is done here:

https://github.com/microsoft/vscode-jupyter/blob/5e6985b74f9c3f448c05eb0b7a875459e5614b5e/src/interactive-window/editor-integration/codelensProviderActivator.ts#L20

So, I think the core of this issue is to add a configuration option to override the doc selection filter in the activator code above. The option could take an extension glob or a language identifier.

Is this a feature you would consider implementing, or merging?

**Comment by amunger** [comment] 2023-10-23 17:06
Aside from just enabling it for other languages, we would also need to be able to set different cell markers for those languages since `# %%` isn't always a comment line.

There is also the issue of auto-selecting the python interpreter as the kernel, since you likely wouldn't want that for a different language.

But I am open to the prospect of enabling the Interactive Window for more languages. It's just going to take a bit of work to make it a smooth experience.

**Comment by amunger** [comment] 2023-12-08 21:49
closing as duplicate of https://github.com/microsoft/vscode-jupyter/issues/273

**Closed by amunger** 2023-12-08 21:49 UTC
Labels: interactive-window, feature-request
