### ISSUE TITLE
Request for 'Create New View For Output` like Jupyterlab for Interactive Window and Notebook

### ISSUE THREAD

**Issue by AeneasZhu** [microsoft/vscode-jupyter#1541] opened 2019-11-22 13:50 UTC
![image](https://user-images.githubusercontent.com/44701446/69431024-d12bde00-0d71-11ea-8cbd-b22efda65634.png)

Is that doable? Creating a new view tab for the cell output, and we don't have to scroll up and down check some output again and again

**Comment by DonJayamanne** [comment] 2022-08-15 01:34
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/1120

**Closed by DonJayamanne** 2022-08-15 01:34 UTC
Labels: interactive-window, feature-request
