### ISSUE TITLE
jupyter.selectjupyteruri failed

### ISSUE THREAD

**Issue by firegate22** [microsoft/vscode-jupyter#4330] opened 2021-01-08 10:54 UTC
Command 'Jupyter: Specify local or remote Jupyter server for connections' resulted in an error (Running the contributed command: 'jupyter.selectjupyteruri' failed.)

I got the error above + #4316 

## Environment data

-   VS Code version: Version: 1.53.0-insider (user setup) Commit: 0949d5b794f4f42fb4dbc3d0edc1d33b8b70ab21
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.414227025
-   Python Extension version (available under the Extensions sidebar): 2020.12.424452561
-   OS (Windows | Mac | Linux distro) and version: Windows 10
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): no
-   Jupyter server running: Remote

## Expected behaviour

I get the UI box to choose local vs. past remote vs new remote jupyter server.

## Actual behaviour

Error message

## Steps to reproduce:

Execute Jupyter: Specify local or remote Jupyter server

**Comment by claudiaregio** [comment] 2021-01-08 19:43
Closing as this is dupe of #4316

**Comment by DonJayamanne** [comment] 2021-01-13 20:34
Validated

**Closed** 2021-01-13 20:35 UTC
Labels: bug

**Comment by puddleglum56** [comment] 2021-01-22 15:22
As this change hasn't been released yet, I was still getting this error when trying to specify a remote server for Jupyter Notebooks. I ended up downgrading my Visual Studio Code Insiders to version 1.52.0 (from the most recent 1.53.0) following [these instructions](https://github.com/microsoft/vscode/issues/46089).

Now everything seems to work. Just for further information: I am on the Daily Insiders channel for Python and Jupyter extensions.

**Comment by waydegg** [comment] 2021-01-23 00:29
> As this change hasn't been released yet, I was still getting this error when trying to specify a remote server for Jupyter Notebooks. I ended up downgrading my Visual Studio Code Insiders to version 1.52.0 (from the most recent 1.53.0) following [these instructions](https://github.com/microsoft/vscode/issues/46089).
> 
> Now everything seems to work. Just for further information: I am on the Daily Insiders channel for Python and Jupyter extensions.
> 
> Just in case someone else is encountering this problem.

This appears to be for OSX only? I'm trynna get a .deb file for Ubuntu 20.04 :/
