### ISSUE TITLE
Python Interactive Window Traceback Highlighting

### ISSUE THREAD

**Issue by jaymegordo** [microsoft/vscode-jupyter#8717] opened 2022-01-17 22:42 UTC
Are the colors used in python tracebacks hardcoded somewhere? Do they use a lexer?

In a recent update, I'm noticing the error line now has the background highlighted in bright yellow. With black text I'm sure that looks great, but as you can see, it makes the specific error lines pretty hard to read with a dark theme:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/29611875/149844441-a2761211-77f0-4310-ae26-1ad88ae36fa9.png">

Any way for the user to change these colors?

**Comment by DonJayamanne** [comment] 2022-01-17 23:14
Thanks for filing this issue, for some reason I cannot replicate this issue at my end.
Most of the colors come from the python kernel itself (though we do alter the colors to best suite the VS Code themes).


Please could you provide the following info:
* Theme name
* Python version
* Jupyter extension version
* VS Code Extension version
* version of IPyKernel 
```python
import ipykernel
ipykernel.__version__
```

Thanks

**Comment by DonJayamanne** [comment] 2022-01-17 23:15
Classifying this as a bug as the text is not legible.

**Comment by jaymegordo** [comment] 2022-01-17 23:19
- Github Dark (Github Theme Extension v5.1.0)
- python: v2022.0.1696779064-dev
- jupyter: v2022.1.1001614873
- vscode: 1.64.0-insider, Commit: c6e58d126f6b5676242e32b34180b2a595f29b51
- ipykernel: 5.5.6

Also a more obvious example:
<img width="936" alt="image" src="https://user-images.githubusercontent.com/29611875/149846806-7d4285db-8287-47a6-b31a-cae8fde262bf.png">

**Comment by jaymegordo** [comment] 2022-01-17 23:31
Turns out I can edit this color in `workbench.colorCustomizations` by changing eg:

```json
// "terminal.ansiYellow": "#e5e510",  # bright yellow
"terminal.ansiYellow": "#22e510",  # lime green
```

lime green set:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/29611875/149847263-7eeeebee-ae86-4aee-a382-b969a253b71a.png">

and even with no ansiYellow override, just using GitHub Theme's default:
<img width="929" alt="image" src="https://user-images.githubusercontent.com/29611875/149847309-e88f1901-58dd-4bfa-ba04-c4bbe9c3dd4e.png">

Still pretty illegible, maybe there's a way to use something other than ansiYellow for this particular background highlight color with a dark theme, as the main text color will likely be light/white?

**Comment by jaymegordo** [comment] 2022-01-17 23:35
Ahh I have a feeling the change is related to the latest commit in this file:

https://github.com/microsoft/vscode-jupyter/blob/071106f68780552072537be2ae5b3e0ef5e9b049/src/datascience-ui/error-renderer/index.ts#L56

**Comment by DonJayamanne** [comment] 2022-01-17 23:35
What's weird is the ansi yellow highlighting is coming in. We don't provide this.
Please could you:
* DIsable all extensions except for Jupyter
* Disable all themes as well
* Test once again & confirm you're still getting yellow
* Provide a list of all packages and versions `pip list` in the python environment (probably something in that env is changing the colors returned by the kernel)

**Comment by DonJayamanne** [comment] 2022-01-17 23:37
> Ahh I have a feeling the change could be related to the latest commit in this file?

Aah thanks, a new change I wasn't aware of, thanks, I'll dicuss this with the team.
Please could you confirm this works with previous versions of the extension. Thanks

**Comment by jaymegordo** [comment] 2022-01-17 23:39
Yeah even with all extensions disabled:

<img width="696" alt="image" src="https://user-images.githubusercontent.com/29611875/149847947-ba336e1f-c522-47af-a27f-46fbd0bf03af.png">

**Comment by jaymegordo** [comment] 2022-01-17 23:46
Hmm even using a jupyter extension version from a month ago that color still seems to be determined by ansiYellow, but I don't remember noticing it till a few days ago... Is this related to the python extension somehow too?

**Comment by DonJayamanne** [comment] 2022-01-17 23:49
>  Is this related to the python extension somehow too?

Unlikely, I'm still unable to repro this at my end, even with the latest IPython 8 and older Ipykernels.
Let me dig further into this.

**Comment by jaymegordo** [comment] 2022-01-17 23:53
Actually, I think somehow I got off the "latest" version of jupyter, eg I'm not sure when it switched to an explicit "prerelease" system. So I turned that on, now I have the newest prerelease version and there doesn't seem to be any error highlighting at all haha. So thanks for the help, but I guess its actually all good in the newest version??

<img width="482" alt="image" src="https://user-images.githubusercontent.com/29611875/149848815-98fe6540-5218-4c67-ae2b-9ed381e28cd4.png">

<img width="684" alt="image" src="https://user-images.githubusercontent.com/29611875/149848861-6bbfadd3-43e3-4054-a31c-3f6cf533de05.png">

**Comment by DonJayamanne** [comment] 2022-01-18 00:33
Yes, I believe that's what was meant to be fixed in the change you highlighted.
Thanks for the confirmation

**Comment by mikewojnowicz** [comment] 2022-03-30 20:32
Are you sure this is a VSCode issue? I am seeing the same problem with the Ipython tracebacks.

**Comment by bheinzerling** [comment] 2022-04-17 08:16
Ran into this today, after upgrading to 8.2.0.
As a workaround, you can disable the color scheme by setting
```
c.InteractiveShell.colors = 'NoColor'
```
in `~/.ipython/profile_default/ipython_config.py`. All other schemes (namely: Neutral, Linux, or LightBG) had the same unreadable ansiYellow background. (Disabling the color scheme doesn't affect syntax highlighting, so all's good)

**Comment by aw-west-defra** [comment] 2022-09-09 10:09
Settings > workbench.colorCustomizations > "terminal.ansiYellow": "#626208",  # bright yellow's half bright
Thanks @jaymegordo

**Comment by CoenraadS** [comment] 2022-09-10 07:34
I run into this today, I think issue should be reopened
I will use the ansiYellow workaround for now

![image](https://user-images.githubusercontent.com/5593825/189473971-73376b82-378d-480b-b461-b14c0e2b119b.png)

```
Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2022.8.1002431955
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
```

**Comment by amunger** [comment] 2022-09-12 16:49
This was caused by a change in the IPykernel stack traces that we parse, should be fixed in the latest insiders release with https://github.com/microsoft/vscode-jupyter/pull/11319

**Closed by amunger** 2022-09-12 16:49 UTC
Labels: bug, info-needed, discuss-at-standup, notebook-mild-regression, triage-needed
