### ISSUE TITLE
iPyWidget Textarea does not work properly when used

### ISSUE THREAD

**Issue by UncleHoo** [microsoft/vscode-jupyter#8805] opened 2022-01-25 20:43 UTC
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When using the "Textarea" iPyWidget the widget does not respond properly.  When you select the widget and start typing, the key strokes are sent both to the widget, but also to the Notebook as well.

So, for example, if I hit "a", the letter a will appear in the textarea, but a new Jupyter Cell is also added above the current cell, as if I had pressed the key A while NOT in the widget.

I have tested this in both VSCode and the regular Jupyter Notebook Server and this behavior only occurs in VSCode.

I also tested this with just the "Text" iPyWidget and that functions correctly, so it's only the Textarea widget that has problems.

### VS Code Version

Version: 1.63.2 (user setup) Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3 Date: 2021-12-15T09:40:02.816Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2021.11.1001550889

### Coding Language and Runtime Version

Python 3.8.10

### Language Extension Version (if applicable)

Python Extension - v2021.12.1559732655

### Anaconda Version (if applicable)

conda version : 4.11.0

### Running Jupyter locally or remotely?

Local

**Comment by rchiodo** [comment] 2022-01-25 21:06
Thanks for the issue. This should be a dupe of https://github.com/microsoft/vscode/issues/137902

**Closed by rchiodo** 2022-01-25 21:06 UTC
Labels: bug, needs-triage

**Comment by UncleHoo** [comment] 2022-01-25 21:08
Thanks.............sorry for the duplicate issue. 😃
