### ISSUE TITLE
Clicking error message in interactive Window does not take editor to appropriate line 

### ISSUE THREAD

**Issue by endlessbeloved** [microsoft/vscode-jupyter#14225] opened 2023-08-31 03:59 UTC
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

click the error message should jump to the corresponding line in the file.

it works fine on a temporary file which doesn't save.  I clicked the error message, and the cursor jump to the right position.

but it doesn't works on a existing file. just as I showed on the gif.  I clicked the error message,but show the error message "The editor could not be opened because the file was not found."  but the file exist. 
![5h26f-3o1px](https://github.com/microsoft/vscode-jupyter/assets/52368157/b51bab3b-7dbc-49e8-99c3-611dbe104b3b)

it also does't works on a saved Notebooks (.ipynb files)  but works on a new temporary .ipynb file. 

![image](https://github.com/microsoft/vscode-jupyter/assets/52368157/a9f64715-5ec3-4af7-a1d2-c007a1123632)

I delete vscode and all extension and all config files on remote server and local computer and reinstall them but didn't  solve this problem.

### VS Code Version

Version: 1.81.1 Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794 Date: 2023-08-09T22:40:25.698Z Electron: 22.3.18 ElectronBuildId: 22689846 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Darwin arm64 22.6.0

### Jupyter Extension Version

v2023.7.1002162226

### Jupyter logs

```shell
Visual Studio Code (1.81.1, ssh-remote, desktop)
Jupyter Extension Version: 2023.7.1002162226.
Python Extension Version: 2023.14.0.
Platform: linux (x64).
Workspace folder ~/stru_predict, Home = /home/moouyang
11:02:58.327 [info] User belongs to experiment group 'FastKernelPicker'
11:02:58.327 [info] User belongs to experiment group 'NewRemoteUriStorage'
11:02:58.327 [info] User belongs to experiment group 'PasswordManager'
11:02:58.327 [info] User belongs to experiment group 'NewJupyterSession'
11:02:59.104 [info] Start refreshing Kernel Picker (1693450979104)
11:02:59.124 [info] Using Pylance
11:03:01.026 [info] Start refreshing Interpreter Kernel Picker
11:03:09.498 [info] Process Execution: ~/anaconda3/envs/deep/bin/python -m pip list
11:03:09.538 [info] End refreshing Kernel Picker (1693450979104)
11:03:36.110 [info] Starting interactive window for resource '~/stru_predict/test.py' with controller '.jvsc74a57bd038ac1c1a92f0ed2efe90e63fc6c4d601e7cffc255b4d75612454e16d451d585c.~/anaconda3/envs/deep/python.~/anaconda3/envs/deep/python.-m#ipykernel_launcher (Interactive)'
11:03:36.371 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd038ac1c1a92f0ed2efe90e63fc6c4d601e7cffc255b4d75612454e16d451d585c.~/anaconda3/envs/deep/python.~/anaconda3/envs/deep/python.-m#ipykernel_launcher  (Python Path: ~/anaconda3/envs/deep/bin/python, Conda, deep, 3.9.13) for '/Interactive-1.interactive' (disableUI=false)
11:03:36.457 [info] Process Execution: ~/anaconda3/envs/deep/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:03:36.548 [info] Process Execution: ~/anaconda3/envs/deep/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9003 --control=9001 --hb=9000 --Session.signature_scheme="hmac-sha256" --Session.key=b"a3835f51-9bdb-473e-adb7-f9b4091eb433" --shell=9002 --transport="tcp" --iopub=9004 --f=~/.local/share/jupyter/runtime/kernel-v2-2735025rfG6Y1Kkz83z.json
    > cwd: ~/stru_predict
11:03:37.222 [info] ipykernel version & path 6.15.3, ~/anaconda3/envs/deep/lib/python3.9/site-packages/ipykernel/__init__.py for ~/anaconda3/envs/deep/bin/python
11:03:39.419 [warn] StdErr from Kernel Process ~/anaconda3/envs/deep/lib/python3.9/site-packages/traitlets/traitlets.py:2412: FutureWarning: Supporting extra quotes around strings is deprecated in traitlets 5.0. You can use 'hmac-sha256' instead of '"hmac-sha256"' if you require traitlets >=5.
  warn(
11:03:39.420 [warn] StdErr from Kernel Process ~/anaconda3/envs/deep/lib/python3.9/site-packages/traitlets/traitlets.py:2366: FutureWarning: Supporting extra quotes around Bytes is deprecated in traitlets 5.0. Use 'a3835f51-9bdb-473e-adb7-f9b4091eb433' instead of 'b"a3835f51-9bdb-473e-adb7-f9b4091eb433"'.
  warn(
11:03:39.722 [info] Started Kernel deep (Python 3.9.13) (pid: 2735526)
11:03:39.722 [info] Started new session 94ce6152-a310-4743-b08d-136250f7bca0
11:03:39.756 [info] Starting interactive window for resource 'Untitled-1' with controller '.jvsc74a57bd038ac1c1a92f0ed2efe90e63fc6c4d601e7cffc255b4d75612454e16d451d585c.~/anaconda3/envs/deep/python.~/anaconda3/envs/deep/python.-m#ipykernel_launcher (Interactive)'
11:03:39.856 [info] Starting Kernel startUsingPythonInterpreter, .jvsc74a57bd038ac1c1a92f0ed2efe90e63fc6c4d601e7cffc255b4d75612454e16d451d585c.~/anaconda3/envs/deep/python.~/anaconda3/envs/deep/python.-m#ipykernel_launcher  (Python Path: ~/anaconda3/envs/deep/bin/python, Conda, deep, 3.9.13) for '/Interactive-2.interactive' (disableUI=false)
11:03:40.017 [info] Process Execution: ~/anaconda3/envs/deep/bin/python ~/.vscode-server/extensions/ms-toolsai.jupyter-2023.7.1002162226-linux-x64/pythonFiles/printJupyterDataDir.py
11:03:40.020 [info] Generated code for 1 = <ipython-input-1-0a62a6d48816> with 1 lines
11:03:40.068 [info] Kernel acknowledged execution of cell 1 @ 1693451020056
11:03:41.685 [info] End cell 1 execution @ 1693451021667, started @ 1693451020056, elapsed time = 1.611s
11:03:41.685 [warn] Cancel all remaining cells due to cancellation or failure in execution
11:03:44.290 [info] Process Execution: ~/anaconda3/envs/deep/bin/python -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
11:03:44.306 [info] Process Execution: ~/anaconda3/envs/deep/bin/python -m ipykernel_launcher --ip=127.0.0.1 --stdin=9008 --control=9006 --hb=9005 --Session.signature_scheme="hmac-sha256" --Session.key=b"e4d92562-5fe0-4220-bffa-e3acdb690c47" --shell=9007 --transport="tcp" --iopub=9009 --f=~/.local/share/jupyter/runtime/kernel-v2-2735025EiP6cpQ71wFJ.json
    > cwd: ~/stru_predict
11:03:44.829 [info] ipykernel version & path 6.15.3, ~/anaconda3/envs/deep/lib/python3.9/site-packages/ipykernel/__init__.py for ~/anaconda3/envs/deep/bin/python
11:03:46.820 [info] Started Kernel deep (Python 3.9.13) (pid: 2735623)
11:03:46.820 [info] Started new session 2993fb3e-4901-4eab-a8cd-1e469421a8c0
11:03:47.002 [info] Generated code for 1 = <ipython-input-1-0a62a6d48816> with 1 lines
11:03:47.027 [info] Kernel acknowledged execution of cell 1 @ 1693451027020
11:03:48.191 [info] End cell 1 execution @ 1693451028187, started @ 1693451027020, elapsed time = 1.167s
11:03:48.191 [warn] Cancel all remaining cells due to cancellation or failure in execution
11:28:15.172 [info] Handle Execution of Cells 2 for /Interactive-1.interactive
11:28:15.212 [info] Kernel acknowledged execution of cell 2 @ 1693452495185
11:28:15.217 [info] End cell 2 execution @ 1693452495209, started @ 1693452495185, elapsed time = 0.024s
```

### Coding Language and Runtime Version

3.9.13

### Language Extension Version (if applicable)

v2023.14.0

### Anaconda Version (if applicable)

conda 23.3.1

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment] 2023-09-06 15:29
duplicate of https://github.com/microsoft/vscode-jupyter/issues/13212. The links currently don't work for files on a remote machine

**Closed by amunger** 2023-09-06 15:29 UTC
Labels: bug, interactive-window, error-renderer
