### ISSUE TITLE
Python Plotly animated graph

### ISSUE THREAD

**Issue by Jacques2101** [microsoft/vscode-jupyter#1589] opened 2020-04-17 09:25 UTC
Issue Type: Bug

Hi I am trying to use Plotly v4.6. I am on VsCode with Python (Python code and jupyter integrated inside Vscode).
Everything is working when I tried website examples except when I tried to replicate the animated graph from the website.
For example, I tried :

import plotly.express as px
df = px.data.gapminder()
px.scatter(df, x=“gdpPercap”, y=“lifeExp”, animation_frame=“year”, animation_group=“country”, size=“pop”, color=“continent”, hover_name=“country”, log_x=True, size_max=55, range_x=[100,100000], range_y=[25,90])

I can see the graph but nothing happens. No animation. When I click on the “Play” button or try to change the year on the bar nothing happens. I am stocked on the year 1952 (I can see it when I put the mouse on the bubbles).
I try to implement others examples from here plotly.com/python/animations. Same result. No animation but I can see the graph and all the buttons.
I have no error message. Nothing seems to be wrong.
Last but not the least. I works properly with JupyterLab.

VS Code version: Code 1.44.1 (a9f8623, 2020-04-11T01:47:00.296Z)
OS version: Darwin x64 19.4.0

Item | Value
-- | --
CPUs | Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmetal: disabled_offmultiple_raster_threads: enabled_onoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_renderer: disabled_off_okvideo_decode: enabledviz_display_compositor: enabled_onviz_hit_test_surface_layer: disabled_off_okwebgl: enabledwebgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 16.00GB (1.38GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
bracket-pair-colorizer | Coe | 1.0.61
prettier-vscode | esb | 4.4.0
gc-excelviewer | Gra | 2.1.34
Python-autopep8 | him | 1.0.2
auto-comment-blocks | kev | 1.0.1
kite | kit | 0.110.0
vscode-language-pack-fr | MS- | 1.44.2
python | ms- | 2020.3.71659
autodocstring | njp | 0.4.0
vscode-icons | vsc | 10.1.1

**Comment by stash-196** [comment] 2020-11-15 01:56
I'd really appreciate this one too. It's core to my project workflow. I'd have to abandon working in vscode otherwise.

**Comment by DonJayamanne** [comment] 2021-09-02 18:18
Duplicate of https://github.com/microsoft/vscode-jupyter/issues/4364

**Closed by DonJayamanne** 2021-09-02 18:18 UTC
Labels: bug, needs-triage, notebook-rendering
