### ISSUE TITLE
Undo In JypterNotebook

### ISSUE THREAD

**Issue by AhmedSaad-ML** [microsoft/vscode-jupyter#5427] opened 2021-04-07 05:37 UTC
## Environment data

-   VS Code version: 1.5.5
-   OS (Windows | Mac | Linux distro) and version: Mac
-   Python and/or Anaconda version: 3.7.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

Issue Type: Bug

Hi, When I press cmd+Z for JypterNotebook it is not undoing every cell as it used to but, now it is undoing the whole notebook and even changing the output of the cell not just the code which is crazy and nonsense. Also the redo in Jytper Notebook is not functioning properly.

**Comment by rchiodo** [comment] 2021-04-07 16:36
Thanks for the bug.

I believe this is the new way undo works but that depends upon which editor you have.

Can you share a screen shot of a notebook?

**Comment by rchiodo** [comment] 2021-04-08 20:19
Might be a dupe of this: https://github.com/microsoft/vscode-jupyter/issues/5441

**Comment by greazer** [comment] 2021-06-05 01:10
Undo has been adjusted in the most recent insiders releases.

**Closed by greazer** 2021-06-05 01:10 UTC
Labels: bug, info-needed
