### ISSUE TITLE
Extension activation failed on VS Code Insiders: ERR Cannot have two contributions with the same id editor.contrib.acceptChangesButton

### ISSUE THREAD

**Issue by eraldoluis** [microsoft/vscode-jupyter#5817] opened 2021-05-09 14:32 UTC
## Environment data

-   VS Code version: 1.57.0-insider (commit: a19565da7dfc739fa26e36aae96113e19fe3806f)
-   Jupyter Extension version: v2021.6.819764235
-   Python Extension version: v2021.4.765268190
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.10
-   Python and/or Anaconda version: 
-   Type of virtual environment used: virtualenv
-   Jupyter server running: Local

## Expected behaviour

Open a Jupyter notebook and edit it.

## Actual behaviour

Got error: "Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information."

## Steps to reproduce:

1. Install VS Code insiders
2. Install Python extension
3. Open (or create and open) a Jupyter notebook

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
Error 2021-05-09 10:27:00: extension activation failed [TypeError: o.getConfiguration(...).get(...).find is not a function
	at new m (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:683169)
	at Object.t.resolveInstance (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:263270)
	at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262475
	at Object.t.resolve (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262738)
	at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253835
	at e._get (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253601)
	at e.get (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:252313)
	at a.get (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:90:509426)
	at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:245341
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825686
	at async t.activate (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825373)
	at async Promise.all (index 0)]
Error 2021-05-09 10:27:00: Failed to active the Jupyter Extension [TypeError: o.getConfiguration(...).get(...).find is not a function
	at new m (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:683169)
	at Object.t.resolveInstance (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:263270)
	at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262475
	at Object.t.resolve (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262738)
	at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253835
	at e._get (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253601)
	at e.get (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:252313)
	at a.get (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:90:509426)
	at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:245341
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825686
	at async t.activate (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825373)
	at async Promise.all (index 0)]
```

</p>

</details>

<details>

<summary>Output for <code>Developer: Toggle Developer Tools</code> panel</summary>

<p>

```
log.ts:296   ERR Cannot have two contributions with the same id editor.contrib.acceptChangesButton: Error: Cannot have two contributions with the same id editor.contrib.acceptChangesButton
    at new ln (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:652:76088)
    at g._createInstance (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:1374)
    at g.createInstance (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:625:793)
    at i.createEditorControl (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2243:27035)
    at i.createEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2243:26646)
    at i.create (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1438:57779)
    at l.doCreateEditorPane (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1799:9752)
    at l.doShowEditorPane (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1799:9327)
    at l.openEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1799:9081)
    at file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2453:15947
    at mi.doShowEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2453:16126)
    at mi.doOpenEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2453:15718)
    at mi.openEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2453:14540)
    at M.openEditor (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2291:17640)
    at async N.editorOpenHandler (file:///usr/share/code-insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:2636:161355)
notificationsAlerts.ts:40 Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:622
addNotification @ notifications.ts:206
notify @ notificationService.ts:137
(anonymous) @ mainThreadMessageService.ts:86
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] extension activation failed TypeError: o.getConfiguration(...).get(...).find is not a function
	at new m (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:683169)
	at Object.t.resolveInstance (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:263270)
	at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262475
	at Object.t.resolve (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:262738)
	at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253835
	at e._get (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:253601)
	at e.get (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:252313)
	at a.get (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:90:509426)
	at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:52:245341
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825686
	at async t.activate (/home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:825373)
	at async Promise.all (index 0) (at /home/eraldo/.vscode-insiders/extensions/ms-toolsai.jupyter-2021.6.819764235/out/client/extension.js:37:826205)
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

</p>

</details>

**Comment by joyceerhl** [comment] 2021-05-09 19:24
@eraldoluis This is most likely a duplicate of https://github.com/microsoft/vscode-jupyter/issues/5804. As a temporary workaround, you can replace the workbench.editorAssociations setting with the following, which should allow the Jupyter extension to activate:

```
    "workbench.editorAssociations": [
        {
            "viewType": "jupyter-notebook",
            "filenamePattern": "*.ipynb"
        }
    ]
```

Please let us know if the workaround doesn't fix the problem for you. We plan to ship a VS Code Insiders build with a fix for this on Monday. Thanks and sorry for the trouble!

**Closed by joyceerhl** 2021-05-09 19:24 UTC
Labels: bug

**Comment by eraldoluis** [comment] 2021-05-10 00:04
Thank you for the quick answer and solution. It worked just fine with this workaround.

**Comment by eraldoluis** [comment] 2021-05-10 22:07
It is! Thanks. I have another bug now. :( Will open another issue.

**Comment by joyceerhl** [comment] 2021-05-10 22:29
Yes please do. We appreciate your help 😊
