### ISSUE TITLE
Hitting run / debug cell in interactive python script does not have any effect in remote VM

### ISSUE THREAD

**Issue by jzazo** [microsoft/vscode-jupyter#7424] opened 2021-09-06 08:57 UTC
## Environment data

-   VS Code version: 1.60.0
-   Jupyter Extension version: v2021.8.2031190714
-   Python Extension version: v2021.9.1191016588
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04
-   Python and/or Anaconda version: Python 3.8.5
-   Type of virtual environment used: pipenv, version 2018.11.26
-   Jupyter server running: Remote

## Expected behaviour

I have a python script with `# %%` cells. I click `Run Cell` or `Debug Cell` and I expect the cell to run in a newly opened tab.

## Actual behaviour

New tab opens, wrong kernel is loaded (w.r.t. the script's environment). I change the kernel to correct one, hit `Run Cell` and nothing happens. After a few clicks I get a `1 cells were canceled due to an error in the previous cell`. If I copy the cell to `Execute code` prompt, code runs correctly, but not from script file.

This was working fine until latest August update.

## Steps to reproduce:

1. Just running a cell in a remote VM using interactive python using a custom kernel.

**Comment by joyceerhl** [comment] 2021-09-06 21:03
Just to confirm, are you connected to a remote Jupyter serveror are you using a Remote extension in VS Code like Remote-SSH (i.e. your kernel and script file are on the same machine)?

If you are connected to a remote Jupyter server, this is a duplicate of https://github.com/microsoft/vscode-jupyter/issues/7391

**Comment by jzazo** [comment] 2021-09-07 07:39
I am using Remote-ssh and script and kernel are on the same machine. Thanks!

**Comment by jzazo** [comment] 2021-09-09 09:30
Can you reproduce, or do you need more details of the environment I am using?

**Comment by joyceerhl** [comment] 2021-09-21 01:07
Sorry for the delayed response. I can't reproduce this with Remote-SSH Ubuntu 20.04 and pipenv in VS Code Insiders:
![image](https://user-images.githubusercontent.com/30305945/134097079-22559646-6d57-441f-bd02-08a78a00229b.png)


Would you mind letting us know if the problem persists with VS Code Insiders and the latest builds of both Python and Jupyter extensions? If it does, you mentioned a custom kernel--is there anything special about that kernel that might be relevant to this scenario?

**Comment by jzazo** [comment] 2021-09-21 14:14
Hi! I installed vscod insiders, installed all extensions, and for a brief moment I could test this issue and it was working. After changing some configuration and/or installing python insiders, I get a notification "Python extension loading..." and it never ends. How can I debug/fix that? I can no longer try anything with jupyter.

**Comment by jzazo** [comment] 2021-09-21 15:58
I activated the daily python insiders version, which at the moment is `v2021.10.1255769080-dev`.
Both the insiders and non-insiders is giving me this loading problem. I have reloaded vscode-insiders multiple times also...

**Comment by joyceerhl** [comment] 2021-09-21 16:53
Thanks for the details. I have opened https://github.com/microsoft/vscode-python/issues/17479 to track the Python extension failing to complete loading. Please consider providing the Python logs from the Python output panel in that issue as well.

It sounds like the bug with interactive cells in Jupyter has been resolved so I will close this issue for now, but please feel free to ping if the issue reappears. Apologies for the trouble.

**Closed by joyceerhl** 2021-09-21 16:53 UTC
Labels: bug, regression, interactive-window
